### ISSUE TITLE
how to put the feature vectors into LSTM?

### ISSUE THREAD

**Issue by lbj0411** [dmlc/mxnet#1003]
I have extracted features from another DL models.Now I have many feature vectors(length 4096) ,let's assume it 1000 feature vectors. A block(may be size of 10)of vectors has a label. All my data is in .mat form.

How can I input my data into the LSTM network to train?

**Comment by tornadomeet** [comment]
you may need more description about your task/data.
but the general step is, firstly convert .mat to numpy array( maybe scipy.io can do it), if your data is not big enough, then rearrange to some LSTM network depend on your task style, the data style or lstm model can refer to:https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm_ptb.py#L16-L35

**Comment by weihaoxie** [comment]
I have the same question about this,can anybody answer it .

**Comment by weihaoxie** [comment]
I have the same question about this,can anyone answer this question?
