### ISSUE TITLE
training with alexnet with my own data

### ISSUE THREAD

**Issue by UniqueAndys** [dmlc/mxnet#1007]
Recently I want to use alex_net provided under example/image-classification with my own car-logo dataset. I prepare everything needed for training but finally got train and validation both around 20 per cent. I use the make_list.py and im2rec.py under tools to convert my data to the format required by mxnet and adjust some parameters for my own data. Because I can't find a script to compute the image mean value, I use the original mean value of alex net(r:123.68,g:116.779,b:103.939) for my net temporally and the image size is (3,63,63). I also change some value such as the first conv kernel into (5,5) with pad(1,1), num_class 42, wd 0.0005, lr 0.01,totally 80 epoch, lr-factor-epoch 20, num-examples 17551 and other relatively reasonable parameters. Can anybody fix this problem for me?

**Comment by qiaohaijun** [comment]
how many epoch you trained the model?
can you train inception model first?

**Comment by UniqueAndys** [comment]
@qiaohaijun 80 epoch

**Comment by qiaohaijun** [comment]
@UniqueAndys the alexnet need different initialization condition, try inception
are you familiar with caffe model?

**Comment by UniqueAndys** [comment]
@qiaohaijun Yeah, I have been using Caffe, you mean I using the caffe_converter under tools?I am goning to try it! But how can I initialization different part of the net in mxnet?Because I can't always use the caffe model.
