### ISSUE TITLE
[R] How to use mx.simple.bind() in R package

### ISSUE THREAD

**Issue by junshui** [dmlc/mxnet#1008]
The help information of mx.simple.bind() is too simple. I just can't figure out how to really use it from its help message.  Also, I can't find any sample code that used this function. I wonder if any of you can help me understand its usage a little better. 

Many thanks for your help.

**Comment by junshui** [comment]
Can anyone help me with this? The limited help documentation appears to be the biggest obstacle for mxnet to have wider acceptance.

**Comment by thirdwing** [comment]
@junshui We are working to improve documents and provide more examples. I will really appreciated your understanding of the situation that we are all students and have limited time.

For usage of `mx.simple.bind()`, you can find a good example from

https://github.com/dmlc/mxnet/blob/master/R-package/R/model.R#L472

For the documentation, my advice is to use python doc as a reference, like 

https://github.com/dmlc/mxnet/blob/master/python/mxnet/symbol.py#L495-L499

**Comment by junshui** [comment]
Many thanks for your help. After some research, I saw a lot of potential in mxnet. I have decided to switch to it. Hopefully, you guys can keep it up, and make it one of the dominate DL packages.

**Comment by thirdwing** [comment]
Thank you for your support. We want to make `mxnet` one of the first choices when people want to use deep learning in R.

Right now I am closing this. Feel free to open it if necessary.
