### ISSUE TITLE
GPU evaluation support

### ISSUE THREAD

**Issue by piiswrong** [dmlc/mxnet#1009]
I'm working image segmentation that has a huge output. Computing metric on CPU has become the bottleneck. How can I add a GPU metric op that's only computed on forward and ignored on backward?

**Comment by tornadomeet** [comment]
how about when do the backward(), fix in_grad = 0,then it will not infuence the bottom layer?
another, becasue this evaluation is only used forward, can let NDArray support that compution in gpu?

**Comment by piiswrong** [comment]
I ended up doing it with imperative API. In the process I refactored FeedForward model to directly send GPU output to metric without copying to cpu. I think this is a better interface because this allows metric to be computed on GPU. Also since asnumpy() is called in metrics anyway so this change shouldn't have any side effects.

**Comment by antinucleon** [comment]
I prefer low level way to fix it. I think it is possible to write imperative evaluation by using NDArrary API (if we have enough operator in NDArrary API). Another low level solution we can make some metric symbol, eg:
```
data = mx.sym.Variable("net_out")
label = mx.sym.Variable("label")
logloss_metric = mx.sym.LogLossMetric(data, label)
args = {"net_out" : net.outputs[0], "label" : xxx}
metric = logloss_metric.bind(xxxx)
```
It is dirty but quick solution. For high level API modification, guess Tianqi will have better idea,
