### ISSUE TITLE
[complie error]   undefined reference to `ps::Meta::kEmpty'

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#1011]
build/kvstore/kvstore.o: In function `ps::SimpleApp::Request(int, std::string const&, int)':
kvstore.cc:(.text+0x880): undefined reference to `ps::Meta::kEmpty'
build/kvstore/kvstore.o: In function `ps::SimpleApp::Response(ps::SimpleData const&, std::string const&)':
kvstore.cc:(.text+0x154d): undefined reference to `ps::Meta::kEmpty'
build/kvstore/kvstore.o: In function `ps::KVWorker<float>::Send(int, bool, int, ps::KVPairs<float> const&)':
kvstore.cc:(.text._ZN2ps8KVWorkerIfE4SendEibiRKNS_7KVPairsIfEE[_ZN2ps8KVWorkerIfE4SendEibiRKNS_7KVPairsIfEE]+0x2dd): undefined reference to `ps::Meta::kEmpty'
build/kvstore/kvstore.o: In function `ps::KVServer<float>::Response(ps::KVMeta const&, ps::KVPairs<float> const&)':
kvstore.cc:(.text._ZN2ps8KVServerIfE8ResponseERKNS_6KVMetaERKNS_7KVPairsIfEE[_ZN2ps8KVServerIfE8ResponseERKNS_6KVMetaERKNS_7KVPairsIfEE]+0x17): undefined reference to `ps::Meta::kEmpty'
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1

**Comment by qiaohaijun** [comment]
I have exec "git submodule update", but the error still there

**Comment by qiaohaijun** [comment]
$cd ps-lite
$make -j

then error fixed

**Comment by mli** [comment]
try `make clean_all` before building?

**Comment by qiaohaijun** [comment]
@mli I just make clean not clean_all
try it

**Comment by qiaohaijun** [comment]
@mli it worked
