### ISSUE TITLE
Instability at the end of a dataIter?

### ISSUE THREAD

**Issue by jimxinbo** [dmlc/mxnet#1014]
I have a DataIter whose the epoch_size is 156 (ceil(n_sample/batch_size)=156). I reset the iterator every time at the beginning, but when I do 

iter.reset()
for dbatch in iter: 
......

the iterator sometimes went though 156 batches but sometimes it went through 155 batches. 

I build up the iterator following regular examples of imagerecorditer. I have a feeling this may relate to the "last_batch_handle" optional in Dataiter, but it should be "pad" by default and to my understand there should be no instability.

**Comment by piiswrong** [comment]
which dataiter are you using?

**Comment by jimxinbo** [comment]
Imagerecorditer

**Comment by tqchen** [comment]
Interesting, this is not suppose to happen unless in round batch mode. Can you give an minimum reproducible example? So that the developers can take a look, alternatively, it would be great if you can help look into what is going on and make part of your wisdom to improve mxnet!

**Comment by jimxinbo** [comment]
Sure. Now that it is not a known issue, let me see what I can do first. I will send a minimum reproducible example if I cannot figure it out. Thx.

**Comment by tqchen** [comment]
closing for inactive status, feel free to reopen
