### ISSUE TITLE
problem in making with multi-machine supporting 

### ISSUE THREAD

**Issue by sofiawu** [dmlc/mxnet#1018]
I want to make the mxnet with multi-machine support, so I set USE_DIST_KVSTORE=1
But It seems that I need to download the zeromq.
The problem is my gpu server can not access the network, so I need to download the library on another computer and  then transfer it to the gpu server.
so what can i do ?

**Comment by qiaohaijun** [comment]
I think you can use squid to set up a proxy server for the gpu servers

**Comment by mli** [comment]
you can downloads the *.tar.gz manually and put it under the root of mxnet, and then comment out the `wget xxx` in 

https://github.com/dmlc/ps-lite/blob/master/make/deps.mk
