### ISSUE TITLE
[VOTE] Maillist Discussion Group for Support and Discussions

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#1020]
Related to #976  MXNet has grow to enough size and maybe we want a discussion group for dicussion, and use issue for bug and progress tracking of features. So this is a vote on what we will want:

Please vote in three days, and we will go with the option people like

Options

- 0. No maillist, stick with github issue for everything
- 1. google-group as maillist
- 2. disqus group.

**Comment by tornadomeet** [comment]
0
China,you know.

**Comment by wangg12** [comment]
0 is fine. 
Downvoting for 1.
It seems we can access disqus(2), so 2 is ok for me, but I'm not familiar with it.

**Comment by vchuravy** [comment]
I would prefer 2.

**Comment by qiaohaijun** [comment]
0

**Comment by xgastaldi** [comment]
1 or 2

**Comment by pluskid** [comment]
Alternatively, we could probably create a dummy repo mxnet-discuss and host general discussions with the github issues on that repo to avoid overflow in the main repo.

**Comment by Adesun** [comment]
1

**Comment by pineking** [comment]
1

google group is the best choice, I can access it although in China.

**Comment by zorksylar** [comment]
1
+1 for  I can access it although in China.

**Comment by hjk41** [comment]
2
Google group is not a good choice. It will stay blocked for some time.

On Wed, Dec 23, 2015 at 3:23 PM, Qingsong Liu <notifications@github.com>
wrote:

> 1
>
> google group is the best choice, I can access it although in China.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1020#issuecomment-166821754>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by wangg12** [comment]
Tensorflow guys use stackoverflow for discussion, is this a choice?

**Comment by pineking** [comment]
try proxy (via shadowsocks)

On Wed, Dec 23, 2015 at 3:43 PM, Chuntao Hong <notifications@github.com>
wrote:

> 2
> Google group is not a good choice. It will stay blocked for some time.
>
> On Wed, Dec 23, 2015 at 3:23 PM, Qingsong Liu <notifications@github.com>
> wrote:
>
> > 1
> >
> > google group is the best choice, I can access it although in China.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dmlc/mxnet/issues/1020#issuecomment-166821754>.
> >
>
>
>
> --
> HONG Chuntao
> System Research Group
> Microsoft Research Asia
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1020#issuecomment-166828604>.
>



-- 
---------------------------------------------
Qingsong Liu
liuqs.ustc@gmail.com
Univ. of Sci.& Tech. of China
----------------------------------------------

**Comment by hjk41** [comment]
I know. I use shadowsocks at home. But most people in China does not. And I
think the discussion group is mainly for common people...

On Wed, Dec 23, 2015 at 3:49 PM, Qingsong Liu <notifications@github.com>
wrote:

> try proxy (via shadowsocks)
>
> On Wed, Dec 23, 2015 at 3:43 PM, Chuntao Hong <notifications@github.com>
> wrote:
>
> > 2
> > Google group is not a good choice. It will stay blocked for some time.
> >
> > On Wed, Dec 23, 2015 at 3:23 PM, Qingsong Liu <notifications@github.com>
> > wrote:
> >
> > > 1
> > >
> > > google group is the best choice, I can access it although in China.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/dmlc/mxnet/issues/1020#issuecomment-166821754>.
> > >
> >
> >
> >
> > --
> > HONG Chuntao
> > System Research Group
> > Microsoft Research Asia
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dmlc/mxnet/issues/1020#issuecomment-166828604>.
> >
>
>
>
> --
> ---------------------------------------------
> Qingsong Liu
> liuqs.ustc@gmail.com
> Univ. of Sci.& Tech. of China
> ----------------------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1020#issuecomment-166829178>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by thyu** [comment]
2

As a newbie to mxnet I sometimes feel too embarrassed to ask dumb question in Github/issues, fearing that I would visually block some more important issues happening in Github/issues. 

Also, 2 would be a nice place for people to showcase their pet projects using mxnet...  hopefully you can find good apps with great potential, who knows?

**Comment by thirdwing** [comment]
2

**Comment by terrytangyuan** [comment]
2

**Comment by vchuravy** [comment]
Since there seem renewed interest, let me just quickly point out that discourse and not disqus would better fit our needs. https://github.com/dmlc/mxnet/issues/976#issuecomment-166829156

**Comment by hughperkins** [comment]
2. 还是一个人建议了威信？

**Comment by tqchen** [comment]
Setup a google group maillist here https://groups.google.com/forum/#!forum/mxnet

Mainly aim to use this as maillist purposes for discussions. The options such as issue still available
