### ISSUE TITLE
Mxnet takes unresonable long time to run a batch iteration of residual net

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#1022]
I have just coded a residual net according to Deep Residual Learning for Image Recognition at http://arxiv.org/abs/1512.03385, and the code is in https://github.com/shuokay/resnet/blob/master/resnet.py

However the code did not output anything after a very long time. I have visualized the net and checked the code for times, but I still cant find out the problem. Hoping someone here cant figure out the reason.

thanks in advance.

**Comment by piiswrong** [comment]
You need 
```Python
import logging
logging.basicConfig(level=logging.DEBUG)
```
At the beginning to see the log

**Comment by piiswrong** [comment]
Actually, it would be great if you can submit a PR with your Residual network code. Thanks.

**Comment by antinucleon** [comment]
Also, in your sample code, you use batch size of 5, which will kill performance. Please refer https://github.com/dmlc/mxnet/issues/990

If you want to run in less memory mode, run as ```MXNET_BACKWARD_DO_MIRROR=1 python run.py```

**Comment by shuokay** [comment]
@piiswrong @antinucleon thanks very much, now I can get the output. I am still trying to confirm the code is consistent with  Deep Residual paper, so I set small batch size. I will submit a PR when I think my code is consistent with the the paper.

**Comment by winstywang** [comment]
It may take about 2~3 weeks to train 152 layers resnet on 8 TitanX. @shuokay
