### ISSUE TITLE
mxnet and ocr

### ISSUE THREAD

**Issue by wanghaisheng** [dmlc/mxnet#1023]
we have a lot of jpg file which contain chinese characters and tables and so on.
can we use mxnet to get an ocr model to identify these words and characters in a new picture?
could someone give a little advice

**Comment by antinucleon** [comment]
You are using too small batch size: see also in https://github.com/dmlc/mxnet/issues/990

If you are limited by GPU memory, try to run as `MXNET_BACKWARD_DO_MIRROR=1 python run.py`

**Comment by piiswrong** [comment]
Which OCR model do you want to use?

**Comment by wanghaisheng** [comment]
i have read a presentation here 链接: http://pan.baidu.com/s/1kUoSyV1 密码: p92n
they claim to use CNN to identify chinese character and RNN to english characters.

**Comment by futurely** [comment]
There is a Torch 7 implementation which can be ported to MXNet. https://github.com/fchollet/keras/issues/383#issuecomment-166850153

**Comment by wanghaisheng** [comment]
@futurely  thx
