### ISSUE TITLE
dsb2 example missing cast to float of DICOM images

### ISSUE THREAD

**Issue by udibr** [dmlc/mxnet#1024]
line https://github.com/dmlc/mxnet/blob/master/example/kaggle-ndsb2/Preprocessing.py#L66
should be

               img = preproc(f.pixel_array.astype(float) / np.max(f.pixel_array))

**Comment by tqchen** [comment]
Nice catch, can you submit a PR on this? I guess this was python3/2 compatibility issue

**Comment by udibr** [comment]
ok managed to make a PR

**Comment by tqchen** [comment]
Merged, thanks for the catch:)
