### ISSUE TITLE
Questions and clarifications on the docs (was: SoftmaxOutput example and docs are inconsistent?)

### ISSUE THREAD

**Issue by SkidanovAlex** [dmlc/mxnet#1035]
Hi,
I'm looking at the latest docs here:
http://mxnet.readthedocs.org/en/latest/python/symbol.html#mxnet.symbol.SoftmaxOutput

and at a LSTM example here:
https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py#L93

In the example you pass a positional argument `label` into the SoftmaxOutput, however there's no docs for `label`. Are docs out of date? What is the meaning of `label`?

**Comment by tqchen** [comment]
Thanks for the catch, label is the label index of the multi-class to be predicted. Would you like to open a PR to fix this? We can add the line of document of label to here

https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_output.cc#L24

Then it will be automatically reflected. Thanks!

**Comment by SkidanovAlex** [comment]
@tqchen I will send a single PR with changes when I finish working on my model, so that I don't spam you with small changes.

I will also use this issue to ask other questions on documentation if you don't mind (I will rename it correspondingly).


Question:

In the docs for the `Embedding` layer, `input_dim` and `output_dim` seem to mean the shape of the corresponding dimentions, while in the `Concat` layer a parameter `dim` seems to mean the ordinal of the dimension. I assume it is too late to rename the arguments, but at least the docs can be more specific, because in both cases they explain parameter as "dimension". Can you confirm that my understanding is correct so that I can update the docs for `Embedding` layer to make it explicit that those parameters are sizes of the dimensions, not ordinals?

**Comment by tqchen** [comment]
@SkidanovAlex  small changes are welcomed as long as they stand as a integrated piece of fix :) (in this case it is)

I agree with you that we could be more specific in documenting these parameters, you can change the docstring here https://github.com/dmlc/mxnet/blob/master/src/operator/embedding-inl.h#L34

Again PR is more than welcomed

@antinucleon Can you comment on this? As Embedding was introduced quite recently, we can also consider to rename it to be input_size

**Comment by SkidanovAlex** [comment]
Another question:

Is it correct that SplitChannel splits on the 1-st (zero-based) dimension? If yes, I will add that too.

**Comment by tqchen** [comment]
Closing for inactive status. Yes SliceChannel splits on 1-st dim
