### ISSUE TITLE
Other layers and their documentation

### ISSUE THREAD

**Issue by Temmplar** [dmlc/mxnet#1040]
I have a few question:
1. Has **mxnet** additional layer types as merging and splitting layers for **CNNs**?
Can I find somewhere some documentation of them?
2. Has **mxnet** additional layer types for other kind of NNs like **RBM** for **DBN**?

Thank you for your efforts!

George

**Comment by piiswrong** [comment]
We have concat and split layers. You can find the docs with `help(mxnet.sym)`

**Comment by Temmplar** [comment]
@piiswrong Thank you!

**Comment by melissa1601** [comment]
I can't find split layer, is it SliceChannel?
Thank you
