### ISSUE TITLE
compile failed without root access

### ISSUE THREAD

**Issue by ouceduxzk** [dmlc/mxnet#1042]
Hi, how can I install mxnet on a server as a user. I got following error after make.

mkdir: cannot create directory `/build': Permission denied
make: *** [/build/tmp/gpu_global_mem_gpu.o] Error 1

**Comment by piiswrong** [comment]
did you set EXTRA_OPERATORS?

**Comment by ouceduxzk** [comment]
what is EXTRA_OPERATORS? The error is caused when it try to create a directory without root access.

**Comment by antinucleon** [comment]
I have never seen this situation if follow the guide https://mxnet.readthedocs.org/en/latest/build.html 
The makefile do create a ```build``` folder, but is in current path.

**Comment by ouceduxzk** [comment]
You are right, the build is created in the current path. But since I can not run
sudo apt-get update
sudo apt-get install -y build-essential git libatlas-base-dev libopencv-dev
this might be why I have this weird issue.

**Comment by piiswrong** [comment]
@antinucleon I it's probably due the EXTRA_OPERATORS feature I added a week ago. https://github.com/dmlc/mxnet/blob/master/Makefile#L101 It looks like his EXTRA_OPERATORS is NONE but some how passed the if

**Comment by piiswrong** [comment]
should be fixed once https://github.com/dmlc/mxnet/pull/1048 is merged. For now, you can fix it by adding `EXTRA_OPERATORS = NONE` to the end of your config.mk

**Comment by ouceduxzk** [comment]
Thanks, that fix the problem
