### ISSUE TITLE
Convert AlexNet caffemodel error

### ISSUE THREAD

**Issue by zhoubinxyz** [dmlc/mxnet#1045]
Convert AlexNet will encounter error below:

Swapping BGR of caffe into RGB in mxnet
converting layer conv1, wmat shape = (96, 3, 11, 11), bias shape = (96,)
converting layer conv2, wmat shape = (256, 48, 5, 5), bias shape = (256,)
Traceback (most recent call last):
  File "convert_model.py", line 99, in <module>
    main()
  File "convert_model.py", line 81, in main
    wmat = wmat.reshape(arg_shape_dic[weight_name])
ValueError: total size of new array must be unchanged

The reason is the group convolution of AlexNet discussed here:
https://github.com/BVLC/caffe/issues/778
It was there to implement the grouped convolution in Alex Krizhevsky's paper: when group=2, the first half of the filters are only connected to the first half of the input channels, and the second half only connected to the second half.
 
Any suggestion to solve the problem?

**Comment by mli** [comment]
before we implemented what caffe's alexnet required, you can

1. either train an alexnet, go examples/image-classification, `python train-imagenet --network alexnet ...`. it only takes several hours on 4 gpus.

2. or use vgg16/vgg19. we verified the results. e.g. `tools/caffe_converter/run.sh vgg16`

**Comment by winstywang** [comment]
Current implementation supports group when using mshadow convolution, but not cudnn. You may need to play with the weights a bit in the converter. Close this issue for now, please feel free to reopen it if you meet any problems in converting models.
