### ISSUE TITLE
Unknown data type csv (re-built and re-installed)

### ISSUE THREAD

**Issue by alzmcr** [dmlc/mxnet#1047]
I've pull and rebuild the latest change to get the new example running, but I ran into this problem when using the mx.io.CSVIter accessory. Any idea what may cause it?

```
>>> data_train = mx.io.CSVIter(data_csv="./train-64x64-data.csv", data_shape=(30, 64, 64),
                           label_csv="./train-diastole.csv", label_shape=(600,),
                           batch_size=batch_size)

[23:16:43] ./dmlc-core/include/dmlc/logging.h:208: [23:16:43] src/data.cc:43: Unknown data type csv
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/io.py", line 508, in creator
    ctypes.byref(iter_handle)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 76, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
MXNetError: [23:16:43] src/data.cc:43: Unknown data type csv
```

**Comment by piiswrong** [comment]
you probably need "git submodule update"

**Comment by alzmcr** [comment]
I've pulled all the modules, I'm on mobile so I can't  share the commit hash for each module. I've used  the solution here to pull from each submodule  http://stackoverflow.com/questions/1030169/easy-way-pull-latest-of-all-submodules

Are all if them in master branch?

**Comment by piiswrong** [comment]
do you see the line `DMLC_REGISTER_DATA_PARSER(uint32_t, csv, data::CreateCSVParser<uint32_t>);` at the end of dmlc-core/src/data.cc?

**Comment by antinucleon** [comment]
One of my copy of MXNet on my computer has similar problem. I deleted the folder, clone again and compile, then this problem disappeared.

**Comment by tqchen** [comment]
The problem is make clean did not cleanup the libdmlc.a, so you will need to manually type make clean in dmlc subfolder

**Comment by alzmcr** [comment]
indeed, running "make clean" in each subfolder worked out
