### ISSUE TITLE
mean.img error 

### ISSUE THREAD

**Issue by SSJchen** [dmlc/mxnet#1049]
I occur an error when using:
mean.img = as.array(mx.nd.load("Inception/mean_224.nd")[["mean_img"]])

Error in mx.nd.load("Inception/mean_224.nd")[["mean_img"]] : 
  object of type 'externalptr' is not subsettable

How could I fix it?

**Comment by piiswrong** [comment]
[["mean_img"]] - > ["mean_img"]
