### ISSUE TITLE
installation on cuda-6.5

### ISSUE THREAD

**Issue by mujtabahasan** [dmlc/mxnet#1052]
using cmake to install with cuda6.5, following error comes:
It can't find nvrtc.h
 """ /home/mujtaba/Documents/mxnet/include/mxnet/mxrtc.h:12:19: 
fatal error: nvrtc.h: No such file or directory #include ^ compilation terminated. """

**Comment by qiaohaijun** [comment]
can you find the location of the file "nvrtc.h" ?

**Comment by mujtabahasan** [comment]
No. I am not able to do so.. apparently it is not in cuda6.5. is there any macro to disable RTC

**Comment by qiaohaijun** [comment]
https://github.com/dmlc/mxnet/blob/master/Makefile#L117

and the code is 
src/common/mxrtc.cc

**Comment by qiaohaijun** [comment]
@mli  does mxnet support cuda 6.5?

**Comment by qiaohaijun** [comment]
maybe you should upgrade your cuda

**Comment by antinucleon** [comment]
@qiaohaijun Nothing is related to the Makefile. @piiswrong should have better solution

**Comment by piiswrong** [comment]
should be fixed after https://github.com/dmlc/mxnet/pull/1048 is merged
