### ISSUE TITLE
How to get the output of any layer?

### ISSUE THREAD

**Issue by sunshineInmoon** [dmlc/mxnet#1055]
I have successfully completed image-classification-predict.cc.
However,I want to get the output of inner layer using C++ API.
How I do?
Thanks!

**Comment by piiswrong** [comment]
use symbol.getInternals and group symbol

**Comment by sunshineInmoon** [comment]
Thanks!
I will try to do this.

**Comment by mli** [comment]
https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb

**Comment by sunshineInmoon** [comment]
I have learned the example.
But,I want to use C++ API or C API.
Thanks to your help.

**Comment by mli** [comment]
here is a c++ example to get the output 

https://github.com/dmlc/mxnet/tree/master/example/cpp/image-classification

you can use MXPredCreatePartialOut added on PR #1060 instead of MXPredCreate to get the output of any internal layers

**Comment by sunshineInmoon** [comment]
This is a pleasant surprise!
Thank you very much!
