### ISSUE TITLE
python import mxnet error

### ISSUE THREAD

**Issue by DaleSong89** [dmlc/mxnet#1056]
hi, all
       When I'm importing mxnet using Python 2.7 on Windows 7-64bit, error always comes with    "could not find    libgfortrain-3.dll". Could anyone help me out? (The libmxnet.dll is built by vs2013)

**Comment by antinucleon** [comment]
This dll is from OpenBLAS. You can download an OpenBLAS and copy it to System32

**Comment by DaleSong89** [comment]
Thanks a lot！
