### ISSUE TITLE
questions on using make_list.py and im2cc to create dataset

### ISSUE THREAD

**Issue by chandlerz** [dmlc/mxnet#1065]
I want to use the script train_imagenet.py in ./example/image-classification to train ILSVRC2012 dataset. I have downloaded the dataset and tried the instructions in page http://mxnet.readthedocs.org/en/latest/python/io.html to prepare the dataset.

After using the script make_list.py in ./tools to process the dataset, the command indeed generates a .lst file. However, the item format in the .lst is different from the format shown in the instruction page.

integer_image_index \t label_index \t path_to_image

The second segment label_index is 0 for all items in the .lst, but not the real label index. A sample file is attached. Is this correct?

Actually, I am quite curious how does the script make_list.py abstract the labab index for a jpeg image. 

Thanks for your help!
[sample_lst.txt](https://github.com/dmlc/mxnet/files/72098/sample_lst.txt)

**Comment by futurely** [comment]
`make_list.py` is inconsistent with `im2rec.py`. Try the latter one.

**Comment by qiaohaijun** [comment]
you should add a argument 'recursive'

**Comment by piiswrong** [comment]
you need --recursive=true
