### ISSUE TITLE
AttributeError of Mxnet Installation 

### ISSUE THREAD

**Issue by zhiplain** [dmlc/mxnet#1068]
The Error is as followers：

wm@wm:~/mxnet$ python example/image-classification/train_mnist.py 
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 89, in <module>
    net = get_mlp()
  File "example/image-classification/train_mnist.py", line 57, in get_mlp
    mlp  = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
AttributeError: 'module' object has no attribute 'SoftmaxOutput'

I want to know why this is.

**Comment by piiswrong** [comment]
try update to the newest code

**Comment by tqchen** [comment]
This can be solved by using the newest version of code, you might need to reinstall the package
