### ISSUE TITLE
pow returns nan

### ISSUE THREAD

**Issue by lukemetz** [dmlc/mxnet#1071]
x**2 returns nan when x is <= 0.
This is due to an optimization performed by use_fast_math flag.

For more info see: https://github.com/torch/DEPRECEATED-torch7-distro/issues/132

Short of removing the flag I am not sure of a good solution. Maybe remove it all together?

**Comment by piiswrong** [comment]
We should test the performance impact before removing it. Is this an isolated bug or does it also happen on other cuda math functions? Maybe we can fix it by using pow(abs(x), n) when ever we use pow

**Comment by lukemetz** [comment]
Sorry, I am not advocating to remove it, that is just one option.  It seems rather drastic.
I don't think any other functions are affected but I am not 100% sure.
Another option that could be taken would be to implement a version of pow that only accepts integers as exponent / automatically detects if there are integers in exponent and uses custom code.
