### ISSUE TITLE
Same performance with AWS g2.2xlarge vs g2.8xlarge using lenet.jl

### ISSUE THREAD

**Issue by Andy-P** [dmlc/mxnet#1072]
I have been experimenting with MXNet.jl on AWS. I'm testing using the lenet.jl MNIST examples. 
The GPU vs CPU had a 45x speedup on a g2.2xlarge instance ,but switching to the g2.8xlarge results in almost exactly the same performance.

I thought it might have to do with the environmental variables so I tried 

    export MXNET_GPU_WORKER_NTHREADS=8
but this did not change anything.

I'm I missing something? How can I get the most out of a g2.8xlarge instance?

**Comment by tqchen** [comment]
You do need to use multiple GPU explicitly. Otherwise it will only use one gpu. try pass 
```
[mx.gpu(i) for i in range(4)]
```
instead for devices. However, we may not get significant speedup on MNIST, but will do on other dataset

**Comment by tqchen** [comment]
loop in @pluskid for exact syntax in julia

**Comment by Andy-P** [comment]
@tqchen Thanks for the quick reply. 
That did the trick. As you pointed out the speed up was not that dramatic on MNIST (about 4s to 2.9s). 
The complete syntax for the command in Julia is:

    model = mx.FeedForward(lenet, context=[mx.gpu(i) for i = 0:3])

**Note to Julia users:** The index for GPUs begins at **0** not **1**.

**Comment by Andy-P** [comment]
Ran some tests on cost vs. Performance. About a x3.25 speedup which is quite good but it might be cheaper to run a few g2.2xlarge instead. Will try that next.
CIFAR-10 + MXNet.jl on #AWS
  g2.2xlarge = ~$0.07/h, 406s
  g2.8xlarge = ~$0.35/h,  126s
![cifar_10_using_1_gpu](https://cloud.githubusercontent.com/assets/831751/12005073/43626122-abd0-11e5-846d-a7a490d3aa3c.png)
![cifar_10_using_4_gpus](https://cloud.githubusercontent.com/assets/831751/12005074/454f6ed0-abd0-11e5-8f5f-712f113de6b3.png)

**Comment by pluskid** [comment]
* Yes, you need to construct GPU instances explicitly
* Yes, even in Julia, GPU counting starts with 0, as it corresponds to the native GPU ID, which starts with 0
* You could probably try to compare the CIFAR-10 speed here: https://github.com/dmlc/mxnet/tree/master/example/image-classification#cifar-10 . Just FYI, I could not get as good performance with our K80 GPUs. That is probably because of some local misconfigurations or something. But I do observe almost linear speedup with multiple GPUs.

**Comment by mli** [comment]
@pluskid what's your settings and results on k80s?

#1074 is trying to improve the performance

and you can just use allreduce_test to test your hardware bandwidth on allreduce https://github.com/NVIDIA/nccl

**Comment by pluskid** [comment]
Thanks! I'll try again when I got a chance. I tend to believe it is our cluster's problem. I tried the python version of cifar 10  script by disabling the IO completely and was with no luck.
