### ISSUE TITLE
shape inference wrong in lstm

### ISSUE THREAD

**Issue by yanyuxiaoxiao** [dmlc/mxnet#1073]
I over write char-lstm to wordVector-lstm, but meet some h2h_weight shape inference problem. At time step t, my input data shape is (128, 200), hidden_num is 800. h2h_weight shape should be (800, 800), but auto inference shape is (800, 200). Can anyone know how to deal the problem

**Comment by piiswrong** [comment]
Why should it be (800, 800)?

**Comment by starimpact** [comment]
strange, (800, 200) should be i2h_weight shape.
I suggest you to do double checks.

**Comment by yanyuxiaoxiao** [comment]
@piiswrong  @starimpact  the auto inference shape of h2h_weight is right, i mis understand the mx.sym.SliceChannel last time .But, I still have some problems. My lstm model has two layers and every layers has 512 lstm neuron. This is  my lsmt_unroll function code:

def lstm_unroll(num_lstm_layer, num_lstm_nerual, seq_len, input_size,
                num_hidden, num_embed, num_label, dropout=0.):
    """unrolled lstm network"""
    # initialize the parameter symbols
    embed_weight=mx.sym.Variable("embed_weight")
    cls_weight = mx.sym.Variable("cls_weight")
    cls_bias = mx.sym.Variable("cls_bias")
    param_cells = []
    last_states = []
    for i in range(num_lstm_layer):
        layer_params_cells = list()
        layer_states = list()
        for j in range(num_lstm_nerual):
            print "state name l%d n %d" % (i, j)
            layer_params_cells.append(LSTMParam(i2h_weight = mx.sym.Variable("l%d_n%d_i2h_weight" % (i, j)),
                                        i2h_bias = mx.sym.Variable("l%d_n%d_i2h_bias" % (i, j)),
                                        h2h_weight = mx.sym.Variable("l%d_n%d_h2h_weight" % (i, j)),
                                        h2h_bias = mx.sym.Variable("l%d_n%d_h2h_bias" % (i, j))))
            state = LSTMState(c=mx.sym.Variable("l%d_n%d_init_c" % (i, j)),
                            h=mx.sym.Variable("l%d_n%d_init_h" % (i, j)))
            layer_states.append(state)
        param_cells.append(layer_params_cells)
        last_states.append(layer_states)
    assert(len(last_states) == num_lstm_layer)

    label = mx.sym.Variable("label")
    last_hidden = []
    for seqidx in range(seq_len):
        # embeding layer
        data = mx.sym.Variable("t%d_data" % seqidx)

        # stack LSTM
        for i in range(num_lstm_layer):
            if i==0:
                dp=0.
                _indata=data
            else:
                dp = dropout
                _indata= last_states[i][j].h
            for j in range(num_lstm_nerual):
                next_state = lstm(num_hidden, indata=_indata,
                                  prev_state=last_states[i][j],
                                  param=param_cells[i][j],
                                  seqidx=seqidx, layeridx=i, nerualidx=j ,dropout=dp)
                last_states[i][j] = next_state
                hidden = next_state.h
            # decoder
                if i == (num_lstm_layer - 1):
                    if dropout > 0.:
                        hidden = mx.sym.Dropout(data=hidden, p=dropout)
                    last_hidden.append(hidden)
    # every last layer nerual to encode
    sm_list = list()
    print "last_hidden len ", len(last_hidden)
    for idx in range (num_lstm_nerual):
        _last_hidden = last_hidden[idx]
        concat = mx.sym.Concat(_last_hidden, dim = 0)
        fc = mx.sym.FullyConnected(data=concat,
                                  weight=cls_weight,
                                  bias=cls_bias,
                                  num_hidden=num_label)
        sm = mx.sym.SoftmaxOutput(data=fc, label=label, name="sm%d" % idx)
        sm_list.append(sm)
    out_prob = sm_list
    for i in range(num_lstm_layer):
        for j in range(num_lstm_nerual):
            state = last_states[i][j]
            state = LSTMState(c=mx.sym.BlockGrad(state.c, name="l%d_n%d_last_c" % (i, j)),
                              h=mx.sym.BlockGrad(state.h, name="l%d_n%d_last_h" % (i, j)))
            last_states[i][j] = state


    return mx.sym.Group(sm_list) 

When I want to initialze the lstm model, the lstm model don't have any my first layer params.  The error throw like this    KeyError: 'l0_n0_init_c'  . Is that i construct my netword wrong?

**Comment by yanyuxiaoxiao** [comment]
@piiswrong  @starimpact  
![image](https://cloud.githubusercontent.com/assets/12267543/12013750/6022c8ae-ad58-11e5-8e6d-3e30f175531c.png)
this is my networks reference figure which from  paper Beyond Short Snippets: Deep Networks for Video Classification
