### ISSUE TITLE
What should I do if my input is not images?

### ISSUE THREAD

**Issue by wsybupt** [dmlc/mxnet#1076]
I want to use MXNet to handle a regression problem, the input data of which is not images but a set of numbers. Which format of data should I use ? Someone has the examples?

**Comment by antinucleon** [comment]
There is CSVIterator, NumpyIterator for use.

**Comment by wsybupt** [comment]
@antinucleon Thank you very much! Could you tell me where I can find the usage of CSVIterator?

**Comment by antinucleon** [comment]
This is CSVIter example: https://github.com/dmlc/mxnet/tree/master/example/kaggle-ndsb2
This is Numpy Iter example: https://mxnet.readthedocs.org/en/latest/python/io.html#mxnet.io.NDArrayIter

**Comment by wsybupt** [comment]
@antinucleon Thank you! A problem is that I didn't find the CSVIter example's raw data.

**Comment by antinucleon** [comment]
The raw data for the iterator is a csv file
