### ISSUE TITLE
Debugging hint is not valid

### ISSUE THREAD

**Issue by SkidanovAlex** [dmlc/mxnet#1078]
If the server crashes (the easiest way to reproduce it is to feed a 2-dimensional input to the EmbeddingOp), it suggests the following:

```
you can try set environment variable MXNET_ENGINE_TYPE
to NaiveEngine and run with debugger (i.e. gdb).
This will force all operations to be synchronous and
backtrace will give you the series of calls that lead 
to this error. Remember to set MXNET_ENGINE_TYPE back to 
empty after debugging.
```

As a matter of fact, doing that does not help, because `gdb` doesn't stop in `LogMessageFatal`, and therefore one cannot see the backtrace.

Seems like the reason for that is that there are two implementations of `LogMessageFatal`, one that calls to `abort` and one that throws an exception. The latter is the one that is used by default, and `gdb` seems not to stop when the exception is thrown (may be it is caught to display the above mentioned hint?)

Locally to debug it I added the following flag to the mxnet Makefile C++ flags: ` -DDMLC_LOG_FATAL_THROW=0`. With this flag `LogMessageFatal` uses `abort`, and `gdb` does stop when it happens.

I would suggest one of the two fixes:

1. Set `-DDMLC_LOG_FATAL_THROW=0` by default in the mxnet Makefile, unless there's a strong reason to use exceptions

2. Enhance the error message to suggest to apply this change locally and recompile mxnet before attaching `gdb`.

**Comment by piiswrong** [comment]
I would suggest using -DDMLC_LOG_FATAL_THROW=0 when debug=1. @tqchen @antinucleon

**Comment by tqchen** [comment]
agree with @piiswrong

**Comment by piiswrong** [comment]
Basically we need to add -DDMLC_LOG_FATAL_THROW=0 when DEBUG=1 to CCFLAGS and NVCCFLAGS. @SkidanovAlex Would you like to contribute a PR?
