### ISSUE TITLE
how to zero padding on channels?

### ISSUE THREAD

**Issue by yuzcccc** [dmlc/mxnet#1082]
In He et. al 's deep residual network, the first shortcut in each stage may need to increase the dimensions (ref. to option A in there paper) with zero padding the channels. How to achieve this in mxnet?

**Comment by piiswrong** [comment]
You can use concat layer to concatenate with a zero array

**Comment by githubfragments** [comment]
That is inappropriate because it is hard to obtain the dims of the input array from the symbol API. That is so pity for mxnet!

**Comment by githubfragments** [comment]
Do you find a way? @yuzcccc
