### ISSUE TITLE
How to get layer shapes

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#1090]
Is there a method to get layer shapes? I find it is helpful if I can print layer shapes when designing a network.

**Comment by antinucleon** [comment]
You can use infer_shape: https://mxnet.readthedocs.org/en/latest/python/symbol.html#mxnet.symbol.Symbol.infer_shape

eg:

```
data = mx.sym.Variable("data")
fc = mx.sym.FullyConnected(data=data, num_hidden=256)

arg_shape, output_shape, aux_shape = fc.infer_shape(data=(1, 128))
```

**Comment by smorrel1** [comment]
The link above is broken. Use [this one](https://mxnet.incubator.apache.org/api/python/symbol/symbol.html?highlight=infer_shape#mxnet.symbol.Symbol.infer_shape)

**Comment by mrngbaeb** [comment]
that link is also broken :)
