### ISSUE TITLE
accuracy  of train_mnist.py are different on single gpu and multi-gpus 

### ISSUE THREAD

**Issue by chenjx1005** [dmlc/mxnet#1092]
I run the examples/image_classification/train_mnist.py on single gpu and double gpus. what out of my expectation is that accuracies are slightly different.(around 0.1% different). though it is not a big issue but still i am very confused because they should be completely equal in theory. can you explain what cause this slight difference? thank u!

**Comment by qiaohaijun** [comment]
why you think they should be equal in theory?

**Comment by piiswrong** [comment]
mxnet is not deterministic due to various in-determinism in dependencies. Even two runs on the same GPU are not guaranteed to give identical results. 0.1% sounds like a reasonable difference caused by randomness.

**Comment by tqchen** [comment]
The problem was due to indeterminism in CuDNN convolution, if you turn that off, they should be equivalent if you do not use dropout

**Comment by piiswrong** [comment]
also you need to fix seed for python, numpy and mxnet
