### ISSUE TITLE
DataIter.Next what is the exact datastructure that must be returned ?

### ISSUE THREAD

**Issue by juliandewit** [dmlc/mxnet#1093]
Hello I'm trying to make a DataIter for segmentation.
Based on this https://github.com/tornadomeet/mxnet/blob/seg/example/fcn-xs/data.py I was able to make something work for batchsize 1. Now I wanted to increase the batchsize but cannot make it work.

I have

    def next(self):
        ..
        return DataBatch(data=DATA label=LABEL, pad=self.getpad(), index=None)

When I have batchsize 1 DATA = an mx.nd.array of shape 1,1,128,128 wrapped in []. 
So a python array with 1 element of type mx.nd.array of shape 1,1,128,128

Now for bigger batch  sizes I tried (batchsize 10):
DATA is an mx.nd.array of shape 10,1,128,128. wrapped in []
So a python array with 1 element of type mx.nd.array of shape 10,1,128,128

Now I get the error:
Check failed: (shape_[0]) >= (end) Slice end index out of range

Then I thought I should put 10 elements in the python array of shape 1,1,128,128
But then I got the error : ndarray has not method copyto.

The error is in this piece of code:

    def _load_general(data, targets):
        """Load a list of arrays into a list of arrays specified by slices"""
        for d_src, d_targets in zip(data, targets):
        if isinstance(d_targets, nd.NDArray):
            d_src.copyto(d_targets)
        else:
            for slice_idx, d_dst in d_targets:
            d_src[slice_idx].copyto(d_dst)

What is the expected datastructure ?
Thanks.. mxnet looks very promising.

**Comment by pluskid** [comment]
The shape here should be consistent with what `provide_data` and `provide_label` return.

**Comment by juliandewit** [comment]
Got it! it. Copied too much code and provide_data and provide_label where fixed at batchsize 1.
It works now !

I tried the same idea with caffe and cxxnet with disappointing results without finding out why.
With mxnet I could write my own iterator and solver and really (easily) look what was going on in the net. Now I got it working in 2 days.

Great stuff !
