### ISSUE TITLE
simple_bind computes gradient for input by default

### ISSUE THREAD

**Issue by piiswrong** [dmlc/mxnet#1095]
simple_bind with 'write' will allocate and compute gradient for input by default, which is wasteful because they are not going to be used in most use cases. Should we change this behavior?

**Comment by winstywang** [comment]
Will it affect the performance significantly?

**Comment by piiswrong** [comment]
Mostly goes to saving memory

**Comment by tqchen** [comment]
The problem is we cannot distinguish which are data and which are not, so best way is still ask user to specify which gradient to compute via dict in simple bind

**Comment by piiswrong** [comment]
Ok. I changed model.py to set write_req to null for inputs.
