### ISSUE TITLE
questions on inception-bn and inception-bn-full networks

### ISSUE THREAD

**Issue by chandlerz** [dmlc/mxnet#1096]
I notice that train_imagenet supports several networks, and two of them are inception-bn and inception-bn-full, which are unfamiliar to me. Here are two questions about them.

First, it seems to me the “bn” means batch normalization. As far as I know, batch normalization plays its role by adding bn layer into traditional network (such as AlexNet, GoogleNet et al.) to accelerate the training speed. Is that true for inception-bn and inception-bn-full? If yes, what networks are inception-bn and inception-bn-full based on?

My second question is what are the differences between inception-bn and inception-bn-full?

Thanks!

**Comment by wangg12** [comment]
@chandlerz In my opinion, `inception-bn` comes from Google's paper [Batch Normalization](http://arxiv.org/abs/1502.03167) and `inception-bn-full` is the network dmlc modified to train the full ImageNet dataset.

**Comment by chandlerz** [comment]
@wangg12 Thank you for your reply. I still haven't got the points yet.

**Comment by mli** [comment]
@wangg12 is right, `-full` means the full imagenet dataset, see an example http://dmlc.ml/mxnet/2015/10/27/training-deep-net-on-14-million-images.html
