### ISSUE TITLE
undefined symbol: cblas_sdot

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#1098]
I tried to pull a new version of mxnet and reinstall, and get the following error when I use the python wrapper:

```
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/libmxnet.so: undefined symbol: cblas_sdot
```

In my atlas folder I have: 

```
libatlas.so.3    libcblas.so.3    libclapack.so.3    libf77blas.so.3    liblapack.so.3    libptcblas.so.3    libptf77blas.so.3
libatlas.so.3.0  libcblas.so.3.0  libclapack.so.3.0  libf77blas.so.3.0  liblapack.so.3.0  libptcblas.so.3.0  libptf77blas.so.3.0
```

In /usr/lib64 I have:

```
/usr/lib64/libblas.a  /usr/lib64/libblas.so  /usr/lib64/libblas.so.3  /usr/lib64/libblas.so.3.2
```

I am currently using blas in config.mk as opposed to the default, atlas. 

I remember that last time I had to strip the 3 from libcblas.so.3 to get it to install. I try this with both libcblas.so.3 and libcblas.3.0, and add the directory to LD_LIBRARY_PATH, but this does not resolve the issue. I have also added /usr/lib64 to my LD_LIBRARY_PATH. Can someone point me in the right direction? Thanks!

Edit: This isn't an issue with the new version, it was present the last time I tried to install, but I forgot how to fix it.

**Comment by piiswrong** [comment]
if you want to use atlas, you need to set USE_BLAS = atlas

**Comment by jmschrei** [comment]
I don't want to use atlas. I'd like to use blas, and had it working before.

**Comment by piiswrong** [comment]
try adding -L/usr/lib64 to ldflags?

**Comment by jmschrei** [comment]
That doesn't seem to work. I get the same error. When I switch to USE_BLAS = atlas, I get the following:

```
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1
```

**Comment by piiswrong** [comment]
This error with atlas should be easier to fix. Just add add path to your atlas folder to LDFLAGS.

**Comment by jmschrei** [comment]
Things work now using atlas. Perhaps I never got it to work with blas. Thanks for the help!
