### ISSUE TITLE
What is WaitToRead()?

### ISSUE THREAD

**Issue by sunshineInmoon** [dmlc/mxnet#1101]
Hi,everyone.
The ''this->WaitToRead()'' from NDArray::SyncCopyToCPU(real_t *data, size_t size) const { } takes a long time.However,I don't konw what it is waiting for.
Thanks!

**Comment by tqchen** [comment]
WaitToRead waits until the result of the ndarray is available. This takes a long time because all the computation are asynchronize, and it will block until the computation sequence that get to the result is available

**Comment by sunshineInmoon** [comment]
Thanks
