### ISSUE TITLE
Segmentation fault when loading a saved numpy-op model

### ISSUE THREAD

**Issue by zhaoxin19** [dmlc/mxnet#1102]
I create a new layer with python refered to the example [numpy_softmax.py](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/numpy_softmax.py.
The fit process is good. But when I tried to load the model from json file there is a segmentation fault. I have known it is caused by the serialization and deserialization of the native python object. What can I do to make sure I can load the model correctly?

**Comment by piiswrong** [comment]
This is expected behavior. You cannot load a numpyop. Instead, you can recreate the symbol and the model, then init the parameters by loading with with mx.initializer.Load
