### ISSUE TITLE
"libmxnet.so: undefined symbol: _ZN2ps4Meta6kEmptyE" when import mxnet

### ISSUE THREAD

**Issue by wsybupt** [dmlc/mxnet#1104]
I have just run the command "git pull" and " git submodule update", and then I make the mxnet and the python package. But when I run the example, there is the message:
```
>>> import mxnet
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "mxnet/__init__.py", line 7, in <module>
from .base import MXNetError
File "mxnet/base.py", line 43, in <module>
_LIB = _load_lib()
File "mxnet/base.py", line 35, in _load_lib
lib = ctypes.cdll.LoadLibrary(lib_path[0])
File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
self._handle = _dlopen(self._name, mode)
OSError: /home/spark/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _ZN2ps4Meta6kEmptyE
```

**Comment by piiswrong** [comment]
try make clean

**Comment by mli** [comment]
try `make clean_all` and then make which will rebuilt ps-lite

**Comment by jmschrei** [comment]
Which GCC version are you using? When I was using keras I know I get errors which looked like this because I was using the wrong version (GCC was too recent).

**Comment by wsybupt** [comment]
@piiswrong  I have run the command "make clean" but it doesn't work.

**Comment by wsybupt** [comment]
@piiswrong I will try make clean_all

**Comment by wsybupt** [comment]
@jmschrei Thank you! The GCC version is  4.8.4, is there something wrong?

**Comment by wsybupt** [comment]
@mli Thank you! The problem has been solved.
@piiswrong 'make clean_all' solved the problem.
