### ISSUE TITLE
The latest Release version 20151228_win64_gpu.7z run error

### ISSUE THREAD

**Issue by freepjf** [dmlc/mxnet#1108]
I run the latest Release lib, 20151228_win64_gpu.7z ， windows7 system
CHECK_EQ failed tensor_blob.h :line 530?

20151209_win64_gpu.7z can not run with multiple machine.

@hjk41

**Comment by hjk41** [comment]
The binary distributions are not compiled with multi machine support.

What application are you running? I cannot reproduce the problem with the
NDArray example.


On Wed, Dec 30, 2015 at 10:45 AM, freepjf <notifications@github.com> wrote:

> I run the latest Release lib, 20151228_win64_gpu7z ， windows7 system
> CHECK_EQ failed tensor_blobh :line 530?
>
> 20151209_win64_gpu7z can not run with multiple machine
>
> @hjk41 <https://github.com/hjk41>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1108>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by freepjf** [comment]
AlexNet  
python train_imagenet.py  --network=alexnet  --kv-store=local_allreduce_cpu  --data-dir=F:\DeepLearning\data\imagenet\  --model-prefix=F:\DeepLearning\data\imagenet\model\  --batch-size=1024  --gpus=0,1,2,3
