### ISSUE TITLE
Samples with different size

### ISSUE THREAD

**Issue by pevnak** [dmlc/mxnet#1112]
Hi,
I have a question related to use of mxnet, particularly if I can tweak it to my problem. I want to use the library for multi-instance learning, which means that each sample is composed of multiple instances, but the number of instances in each sample differs from sample to sample. You can imagine this as a 2D image, where each image has different height, but the width of all images is the same.
When the pooling operation is performed over the height, then we get sample of fixed size and one can follow the usual Neural Nets, where each sample has the same size. 
What I feel is that the usual data provider cannot be used here, as it assumes that all samples are of fixed size. Am I right?
Is there a way, how this can be fixed? 

Thank you very much for help and I apologise if this is not the right place to ask my question, though I do not know about any other.

**Comment by piiswrong** [comment]
This currently cannot be done in mxnet. you need to resize the network on each batch which is a missing feature.
One workaround is to bind with maximum possible instances and zero pad. then ignore extra padded examples when calculating loss.

**Comment by pevnak** [comment]
Do I understand correctly that tweaking would require a substantial change of the whole library? I am willing to code new layers change internals a little bit, but I would like to know, how big the change would be?

I was thinking about the solution with padding, but I do not like it since the difference in sizes is quite big in my case.

Thank you very much for the answer.

**Comment by piiswrong** [comment]
@pevnak https://github.com/dmlc/mxnet/pull/1408 added this feature. You are welcome to test it.
