### ISSUE TITLE
How to GPU-based mxnet in R?

### ISSUE THREAD

**Issue by maotong** [dmlc/mxnet#1114]
I installed the standard R mxnet package.
It just works for CPU device.
I want to run the tutorial using GPU.
What should I do?

**Comment by thirdwing** [comment]
@maotong Which operating system you are using?

**Comment by maotong** [comment]
@thirdwing  My experiments are running on Windows. 
Do you have any idea?

**Comment by thirdwing** [comment]
Please have a look at #1085

**Comment by maotong** [comment]
@thirdwing  
thanks for your advice.
 I have refered to #1085. 
The mxnet_0.5.tar.gz can be generated.
However, it can not pass the test phase and the following error is given:

C:\Users\Administrator\Documents\GitHub\mxnet> R CMD INSTALL --no-multiarch R-pa
ckage
* installing to library 'C:/Program Files/R/R-3.2.3/library'
* installing *source* package 'mxnet' ...
** libs
make: Nothing to be done for `all'.
 nstalling to C:/Program Files/R/R-3.2.3/library/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in namespaceExport(ns, exports) :
  undefined exports: mx.nd.max, mx.nd.min, mx.nd.sum
:

ERROR: loading failed
* removing 'C:/Program Files/R/R-3.2.3/library/mxnet'

**Comment by thirdwing** [comment]
Are you using the latest version?

**Comment by maotong** [comment]
@thirdwing 
Now it works. Thanks.
The libmxnet.dll was produced several days ago, while the codes in R-package in latest state.
Once I re-built the library, all things go smooth.
