### ISSUE TITLE
multiple lables format for single image in R

### ISSUE THREAD

**Issue by yib2** [dmlc/mxnet#1122]
Hi,

I am building a multiple-label model for image classification problem. In the documentation(http://mxnet.readthedocs.org/en/latest/python/io.html), 
integer_image_index \t label_1 \t label_2 \t label_3 \t label_4 \t path_to_image is the correct format for image.lst. I do not know how to construct the label part. Does it build with binary indicator?
For example,
integer label1 label2 label3 label4 path
2 1 0 0 1 2.jpg
5 1 0 1 1 5.jpg
...

Thanks,
Yi

**Comment by firearasi** [comment]
Guess it depends on whether you are dealing mith multiple labels(classfiers) in the first place

**Comment by thirdwing** [comment]
@yib2 

@CarlosUziel I am adding an R example for captcha recognition. https://github.com/dmlc/mxnet/pull/6443

Each image like below has 4 labels, and we trained a CNN over them.

![test](https://cloud.githubusercontent.com/assets/1547093/26460795/b6ed6b1e-412f-11e7-8cc5-61d3f56bb21e.png)

The `lst` file is like below:

```
0	8	1	4	7	test/ocr_0.png
1	6	7	9	2	test/ocr_1.png
2	9	6	1	9	test/ocr_2.png
3	4	7	7	8	test/ocr_3.png
```

I hope this example helps.
