### ISSUE TITLE
Problems with cblas.h for OSX Capitan 

### ISSUE THREAD

**Issue by aaronpolhamus** [dmlc/mxnet#1123]
Previously I was having a problem with sys/types.h but updating `ADD_CFLAGS` to `ADD_CFLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11` in osx.mk solves that issue. The problem I am having now is with cblas.h.  The commabd `cp make/osx.mk ./config.mk; make -j4` now results in the following error output:

    In file included from ./mshadow/mshadow/tensor.h:16:0,
                     from include/mxnet/base.h:13,
                     from src/resource.cc:8:
    ./mshadow/mshadow/./base.h:120:23: fatal error: cblas.h: No such file or directory
         #include <cblas.h>

I am attempting to install `mxnet` on OSX 10.11.2, Capitan. I have checked out the following posts--http://www.binwang.me/2015-11-08-install-blas-library-for-mxnet.html, https://github.com/dmlc/mxnet/issues/572--and they did not solve the issue. Any thoughts? Do I similarly need to update `ADD_LDFLAGS`?

Note: I have tried running osx.mk with `USE_BLAS` set to both `apple` and `openblas`. No combination of modifying `USE_BLAS` and `ADD_LDFLAGS`, `ADD_CFLAGS` has resolved this issue so far.

**Comment by piiswrong** [comment]
did you install blas? is it in path? can you find the file cblas.h in your system any where? if not you need to install a version of blas.

**Comment by aaronpolhamus** [comment]
So I made some progress passing multiple apps/paths to ADD_CFLAGS as follows: 

`ADD_CFLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11 -I/usr/local/opt/openblas/include`

The error I'm getting now, near the end of compilation, is: 

    /usr/local/include/c++/4.9.2/cstdio:42:19: fatal error: stdio.h: No such file or directory
     #include <stdio.h>

I attempted adding `/usr/local/include/c++/4.9.2/tr1`, which is where `stdio.h` is located, to `ADD_CFLAGS`, but this caused the compilation to error out right away. Th

`USE_BLAS` set to `apple` and `openblas` doesn't seem to make a difference. The installation seems to be looking for this header file in the `cstdio` subdirectory, but there's nothing in there on my machine. The relevant files are in `tr1`.

**Comment by aaronpolhamus** [comment]
So to be clear, I solved what was going on with `cblas.h`. The trouble now is with `stdio.h`. Not sure if we should close here and open a separate issue?

**Comment by aaronpolhamus** [comment]
Closing this issue and opening a new one related to stdio.h
