### ISSUE TITLE
Python import mxnet error

### ISSUE THREAD

**Issue by lvzhiqiang** [dmlc/mxnet#1124]
When import mxnet in python, the error occurs:
"OSError: /root/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _ZN5mxnet7ndarray4CopyIN7mshadow3cpuENS2_3gpuEEEvRKNS2_5TBlobEPS5_NS_7ContextES9_NS_10RunContextE"

I have tried to replace gcc with icc, atlas with openblas and updated ubuntu, still have the error.
I don't know why? Have anybody ran into the same problem?

**Comment by piiswrong** [comment]
1) use gcc. some people had difficulties with icc before
2) try `make clean_all && make`

**Comment by lvzhiqiang** [comment]
the two steps have been done and still have the problem

**Comment by SkidanovAlex** [comment]
Note that `make clean` will not clean mshadow. I would recommend trying

```
cd mshadow
git pull
make clean
make -j
cd ..
```

**Comment by SkidanovAlex** [comment]
Sorry can't edit comment from a phone. 

After pulling and recompiling mshadow you will need to recompile mxnet too.

**Comment by weichengkuo** [comment]
I fixed it by using Anaconda python.
