### ISSUE TITLE
The gpu cores actually in use do not match with what I set in command 

### ISSUE THREAD

**Issue by mazeLinx** [dmlc/mxnet#1127]
hi, 

I specific 2 gpus devices in command likes this,  `python train_mnist.py --gpus 3,2`. 
The file train_mnist.py is an example provided with source code.

Then I check the gpus status via command nvidia-smi,

it show likes,
![gpu](https://cloud.githubusercontent.com/assets/4373620/12064726/811420c6-b005-11e5-96fe-6bdaa550d571.png)

Those process name 'python' are issued by the command above.

Someone please help to look into this.

**Comment by piiswrong** [comment]
first nvidia-smi and cuda gpu numbering sometimes doesn't match. There is a mapping and you need to figure out your self.
second, could you show your GPU utilization?
