### ISSUE TITLE
Unrecognized csv data type for R and Python integrations

### ISSUE THREAD

**Issue by aaronpolhamus** [dmlc/mxnet#1129]
Using the `mxnet` R package for the Kaggle Data Science Bowl competition, the following command. 
 
    data_train <- mx.io.CSVIter(
      data.csv = "./train-64x64-data.csv", data.shape = c(64, 64, 30),
      label.csv = "./train-stytole.csv", label.shape = 600,
      batch.size = batch_size
    )

Produces the error: 

    [16:29:28] ./dmlc-core/include/dmlc/logging.h:208: [16:29:28] src/data.cc:43: Unknown data type csv
    Error: [16:29:28] src/data.cc:43: Unknown data type csv

I've successfully compiled the `mxnet` and built the R package on OSX Capitan. I am using `clang-omp` as my CC export and `clang-omp++` as my CXX export. Could this be causing my problem? 

(Quick update: `installpackages(mxnet)` method failed for me, so I built the package using option 2, from the command line, within the `mxnet` root folder)

**Comment by thirdwing** [comment]
It might be related to https://github.com/dmlc/mxnet/issues/1097

**Comment by aaronpolhamus** [comment]
Possibly. Seemed like it could also be related to #1047. The same problem with python. The funny thing is that after running `git submodule foreach git pull origin master` in root the line `MLC_REGISTER_DATA_PARSER(uint32_t, csv, data::CreateCSVParser<uint32_t>);` does indeed show up at the end of `dmlc-core/src/data.cc`. So it's definitely there. @tqchen suggested running make clean, but wasn't specific about what subfolder. I've run make clean across the subfolders of various levels in dmlc-core, as well as root, and that hasn't solved the problem either. Apparently that solved @alzmcr 's problem. Just hasn't worked for me yet.

**Comment by aaronpolhamus** [comment]
*Facepalm* needed to run `git submodule foreach git pull origin master` **prior** to `make -j4`. After correcting that order of operations the code now runs just fine. Thanks to all the project contributors for making this code available.
