### ISSUE TITLE
Unknown CMake command "cmake_parse_arguments".

### ISSUE THREAD

**Issue by hiraditya** [dmlc/mxnet#1131]
While compiling mxnet on Ubuntu 14.04, and when I disable CUDA, OPENCV, etc.
I found the solution which is to add:

diff --git a/cmake/Utils.cmake b/cmake/Utils.cmake
index 342689c..f34424d 100644
--- a/cmake/Utils.cmake
+++ b/cmake/Utils.cmake
@@ -1,3 +1,4 @@
+include(CMakeParseArguments)
 ################################################################################################
 # Command alias for debugging messages
 # Usage:

I found the solution here, please apply this patch if this is helpful. https://cmake.org/Bug/bug_relationship_graph.php?bug_id=14230&graph=dependency

**Comment by pluskid** [comment]
Thanks for providing the link to patch.
