### ISSUE TITLE
Unable to compile c++ exaxmple mlp.cpp

### ISSUE THREAD

**Issue by hiraditya** [dmlc/mxnet#1133]
I was able to build mxnet successfully as given in the installation guide. After doing 'make' in the examples/cpp/, I get the following error. However, I'm able to build examples/cpp/image-classification. 

Machine details: ubuntu 14.04, x86_64,
Compiler: g++ 4.9.2

/tmp/ccs5qVk6.o: In function `std::_Sp_counted_deleter<mxnet::NDArray::Chunk*, std::__shared_ptr<mxnet::NDArray::Chunk, (__gnu_cxx::_Lock_policy)2>::_Deleter<std::allocator<mxnet::NDArray::Chunk> >, std::allocator<mxnet::NDArray::Chunk>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
mlp.cpp:(.text._ZNSt19_Sp_counted_deleterIPN5mxnet7NDArray5ChunkENSt12__shared_ptrIS2_LN9__gnu_cxx12_Lock_policyE2EE8_DeleterISaIS2_EEES9_LS6_2EE10_M_disposeEv[_ZNSt19_Sp_counted_deleterIPN5mxnet7NDArray5ChunkENSt12__shared_ptrIS2_LN9__gnu_cxx12_Lock_policyE2EE8_DeleterISaIS2_EEES9_LS6_2EE10_M_disposeEv]+0x33): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZNSt19_Sp_counted_deleterIPN5mxnet7NDArray5ChunkENSt12__shared_ptrIS2_LN9__gnu_cxx12_Lock_policyE2EE8_DeleterISaIS2_EEES9_LS6_2EE10_M_disposeEv[_ZNSt19_Sp_counted_deleterIPN5mxnet7NDArray5ChunkENSt12__shared_ptrIS2_LN9__gnu_cxx12_Lock_policyE2EE8_DeleterISaIS2_EEES9_LS6_2EE10_M_disposeEv]+0xdb): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o: In function `std::_Function_handler<void (mxnet::RunContext), mxnet::NDArray::Chunk::~Chunk()::{lambda(mxnet::RunContext)#2}>::_M_invoke(std::_Any_data const&, mxnet::RunContext)':
mlp.cpp:(.text._ZNSt17_Function_handlerIFvN5mxnet10RunContextEEZNS0_7NDArray5ChunkD4EvEUlS1_E0_E9_M_invokeERKSt9_Any_dataS1_[_ZNSt17_Function_handlerIFvN5mxnet10RunContextEEZNS0_7NDArray5ChunkD4EvEUlS1_E0_E9_M_invokeERKSt9_Any_dataS1_]+0x5): undefined reference to `mxnet::Storage::Get()'
/tmp/ccs5qVk6.o: In function `mxnet::NDArray::~NDArray()':
mlp.cpp:(.text._ZN5mxnet7NDArrayD2Ev[_ZN5mxnet7NDArrayD5Ev]+0xb3): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN5mxnet7NDArrayD2Ev[_ZN5mxnet7NDArrayD5Ev]+0x193): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o: In function `mxnet::NDArray::Chunk::~Chunk()':
mlp.cpp:(.text._ZN5mxnet7NDArray5ChunkD2Ev[_ZN5mxnet7NDArray5ChunkD5Ev]+0x32): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN5mxnet7NDArray5ChunkD2Ev[_ZN5mxnet7NDArray5ChunkD5Ev]+0xd0): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o: In function `std::vector<mxnet::Symbol, std::allocator<mxnet::Symbol> >::~vector()':
mlp.cpp:(.text._ZNSt6vectorIN5mxnet6SymbolESaIS1_EED2Ev[_ZNSt6vectorIN5mxnet6SymbolESaIS1_EED5Ev]+0xc3): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o:mlp.cpp:(.text._ZNSt6vectorIN5mxnet6SymbolESaIS1_EED2Ev[_ZNSt6vectorIN5mxnet6SymbolESaIS1_EED5Ev]+0x244): more undefined references to `mxnet::Engine::Get()' follow
/tmp/ccs5qVk6.o: In function `mxnet::NDArray::NDArray(mshadow::TShape const&, mxnet::Context, bool)':
mlp.cpp:(.text._ZN5mxnet7NDArrayC2ERKN7mshadow6TShapeENS_7ContextEb[_ZN5mxnet7NDArrayC5ERKN7mshadow6TShapeENS_7ContextEb]+0x521): undefined reference to `mxnet::Storage::Get()'
mlp.cpp:(.text._ZN5mxnet7NDArrayC2ERKN7mshadow6TShapeENS_7ContextEb[_ZN5mxnet7NDArrayC5ERKN7mshadow6TShapeENS_7ContextEb]+0x5c1): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN5mxnet7NDArrayC2ERKN7mshadow6TShapeENS_7ContextEb[_ZN5mxnet7NDArrayC5ERKN7mshadow6TShapeENS_7ContextEb]+0x704): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o: In function `void std::vector<mxnet::Symbol, std::allocator<mxnet::Symbol> >::_M_emplace_back_aux<mxnet::Symbol const&>(mxnet::Symbol const&)':
mlp.cpp:(.text._ZNSt6vectorIN5mxnet6SymbolESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_[_ZNSt6vectorIN5mxnet6SymbolESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_]+0x692): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZNSt6vectorIN5mxnet6SymbolESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_[_ZNSt6vectorIN5mxnet6SymbolESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_]+0x843): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o: In function `void std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >::_M_emplace_back_aux<mxnet::NDArray const&>(mxnet::NDArray const&)':
mlp.cpp:(.text._ZNSt6vectorIN5mxnet7NDArrayESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_[_ZNSt6vectorIN5mxnet7NDArrayESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_]+0x580): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o:mlp.cpp:(.text._ZNSt6vectorIN5mxnet7NDArrayESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_[_ZNSt6vectorIN5mxnet7NDArrayESaIS1_EE19_M_emplace_back_auxIIRKS1_EEEvDpOT_]+0x744): more undefined references to `mxnet::Engine::Get()' follow
/tmp/ccs5qVk6.o: In function `MLP::FullyConnectedLayer(mxnet::Symbol, std::string, std::string)':
mlp.cpp:(.text._ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs[_ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs]+0x40): undefined reference to `mxnet::OperatorProperty::Create(char const*)'
mlp.cpp:(.text._ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs[_ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs]+0x24b): undefined reference to `mxnet::Symbol::Create(mxnet::OperatorProperty*)'
mlp.cpp:(.text._ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs[_ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs]+0x268): undefined reference to `mxnet::Symbol::operator()(std::vector<mxnet::Symbol, std::allocator<mxnet::Symbol> > const&, std::string const&) const'
mlp.cpp:(.text._ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs[_ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs]+0x2f3): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs[_ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs]+0x472): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs[_ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs]+0x7c4): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs[_ZN3MLP19FullyConnectedLayerEN5mxnet6SymbolESsSs]+0xa97): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o: In function `MLP::LeakyReLULayer(mxnet::Symbol, std::string)':
mlp.cpp:(.text._ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs[_ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs]+0x3d): undefined reference to `mxnet::OperatorProperty::Create(char const*)'
mlp.cpp:(.text._ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs[_ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs]+0x398): undefined reference to `mxnet::Symbol::Create(mxnet::OperatorProperty*)'
mlp.cpp:(.text._ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs[_ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs]+0x3b5): undefined reference to `mxnet::Symbol::operator()(std::vector<mxnet::Symbol, std::allocator<mxnet::Symbol> > const&, std::string const&) const'
mlp.cpp:(.text._ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs[_ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs]+0x443): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs[_ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs]+0x5c2): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs[_ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs]+0x914): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs[_ZN3MLP14LeakyReLULayerEN5mxnet6SymbolESs]+0xbe7): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o: In function `void std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> >::_M_emplace_back_aux<mxnet::NDArray>(mxnet::NDArray&&)':
mlp.cpp:(.text._ZNSt6vectorIN5mxnet7NDArrayESaIS1_EE19_M_emplace_back_auxIIS1_EEEvDpOT_[_ZNSt6vectorIN5mxnet7NDArrayESaIS1_EE19_M_emplace_back_auxIIS1_EEEvDpOT_]+0x521): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o:mlp.cpp:(.text._ZNSt6vectorIN5mxnet7NDArrayESaIS1_EE19_M_emplace_back_auxIIS1_EEEvDpOT_[_ZNSt6vectorIN5mxnet7NDArrayESaIS1_EE19_M_emplace_back_auxIIS1_EEEvDpOT_]+0x6e4): more undefined references to `mxnet::Engine::Get()' follow
/tmp/ccs5qVk6.o: In function `MLP::Train()':
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x4d): undefined reference to `mxnet::Symbol::CreateVariable(std::string const&)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0xdcd): undefined reference to `mxnet::OperatorProperty::Create(char const*)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0xe4a): undefined reference to `mxnet::Symbol::Create(mxnet::OperatorProperty*)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0xe6b): undefined reference to `mxnet::Symbol::operator()(std::vector<mxnet::Symbol, std::allocator<mxnet::Symbol> > const&, std::string const&) const'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x13b3): undefined reference to `mxnet::NDArray::SyncCopyFromCPU(float const*, unsigned long) const'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x13c2): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x13ef): undefined reference to `mxnet::NDArray::SyncCopyFromCPU(float const*, unsigned long) const'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x13fe): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x1525): undefined reference to `mxnet::NDArray::operator=(float)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x1535): undefined reference to `mxnet::NDArray::operator=(float)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x1549): undefined reference to `mxnet::NDArray::operator=(float)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x1559): undefined reference to `mxnet::NDArray::operator=(float)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x3531): undefined reference to `mxnet::Executor::Bind(mxnet::Symbol, mxnet::Context const&, std::map<std::string, mxnet::Context, std::less<std::string>, std::allocator<std::pair<std::string const, mxnet::Context> > > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x368d): undefined reference to `mxnet::NDArray::Copy(mxnet::Context) const'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x369b): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x3ad3): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x3bc6): undefined reference to `mxnet::operator*(mxnet::NDArray const&, float const&)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x3bd9): undefined reference to `mxnet::NDArray::operator-=(mxnet::NDArray const&)'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x3e0b): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x3f50): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x40ac): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x41ac): undefined reference to `mxnet::Engine::Get()'
mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x42f9): undefined reference to `mxnet::Engine::Get()'
/tmp/ccs5qVk6.o:mlp.cpp:(.text._ZN3MLP5TrainEv[_ZN3MLP5TrainEv]+0x45bb): more undefined references to `mxnet::Engine::Get()' follow

**Comment by hiraditya** [comment]
It turns out that the gnu linker is unable to find the symbols because in the Makefile, link flags are 'before' the object file mlp.o. So a small fix for reordering the LDFLAGS in the command line should be sufficient. Please apply this patch if useful. Thanks,

diff --git a/example/cpp/Makefile b/example/cpp/Makefile
index f8a8527..637c596 100644
--- a/example/cpp/Makefile
+++ b/example/cpp/Makefile

CC=g++
 mlp: ./mlp.cpp
-       g++ -std=c++0x $(CFLAGS) $(LDFLAGS) -o $@ $^
+       $(CC) -std=c++0x $(CFLAGS) -o $@ $^ $(LDFLAGS)
 
 use_ndarray: ./use_ndarray.cpp
-       g++ -std=c++0x $(CFLAGS) $(LDFLAGS) -o $@ $^
+       $(CC) -std=c++0x $(CFLAGS)-o $@ $^  $(LDFLAGS)

**Comment by winstywang** [comment]
@hiraditya Could you please make a pull request so that we could review and merge it in?

**Comment by hiraditya** [comment]
Done! https://github.com/dmlc/mxnet/pull/1145
