### ISSUE TITLE
error of asynchronous engine operation when using mx.init.Normal()

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#1146]
hi, when i use mx.init.Normal(0.01), it will output the error like this:
```
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [09:50:27] src/engine/./threaded_engine.h:295: [09:50:27] ./mshadow/mshadow/./random.h:320: Check failed: (status) == (CURAND_STATUS_SUCCESS) CURAND Gen Uniform failed
```
but when i use mx.init.Uniform(0.01), it will be correct without error. here is the reproducible code:
```python
import mxnet as mx
import numpy as np
ctx = mx.gpu(0)
if __name__ == "__main__":
    arr = mx.nd.zeros((3L, 1L, 5L, 5L), ctx)
    initializer = mx.init.Normal(0.01)
    # initializer = mx.init.Uniform(0.01)
    initializer("arr_weight", arr)
    arr.wait_to_read()
```
so is it a bug or something else which i missed?
thanks~

**Comment by piiswrong** [comment]
Curand normal generators require that the number of outputs be even. 3,1,5,6 would work fine. @tqchen We probably should try to get around this somehow?

**Comment by tqchen** [comment]
hah, yes, I didn't notice that CURAND did not do this fix, we can do a patch around @piiswrong to mshadow by rounding more data

**Comment by tornadomeet** [comment]
@tqchen @piiswrong , i fit it by ```size++``` when size is odd, and do some test, there is no error. here is my fix code: https://github.com/tornadomeet/mshadow/commit/ccd49ec93cc20a06d9412696eae33eb80aa37a50
so what do you think this? because we generate more one number in the memory,  is there any side effect?
