### ISSUE TITLE
Where did mxnet::resource::ResourceTempSpace::ResourceTempSpace function allocate memory?

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#1155]
I am not sure is here the right place to ask this kind question.
There days I am reading mxnet source code. When it comes to resource manage, I find it is a little hard to find where did mxnet "really" allocate memory.
https://github.com/dmlc/mxnet/blob/master/src/resource.cc#L143
```space[i] = new mshadow::TensorContainer<xpu, 1, real_t>();```
I can't find out which function did ```new mshadow::TensorContainer<xpu, 1, real_t>()``` eventually called to allocate memory or ```resource[i].var = Engine::Get()->NewVariable();``` did the allocation work?

thanks in advance.

**Comment by tqchen** [comment]
The allocation happens at Resource.Get which calls TensorContainer.Resize to allocate the memory

**Comment by tqchen** [comment]
https://github.com/dmlc/mxnet/blob/master/include/mxnet/resource.h#L89

**Comment by shuokay** [comment]
Got it, thanks.
