### ISSUE TITLE
how can I add k40m's perf result to the readme.md in the example dir

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#1156]
I am running a cluster of k40m (16 machines ), I think it is useful to add the perf result to the readme.md

can anyone give me some tips or I can follow the result of titan X?

**Comment by qiaohaijun** [comment]
@mli

**Comment by mli** [comment]
that's will be very nice. two kinds of results will be interesting, 

1. scalability numbers, such as the performance numbers

2. the convergence results. 

why not you first write down your results on a documents, such as google doc, then we can have a a discussion how to put the numbers there.

**Comment by mli** [comment]
it looks like cudnn 3 may have bugs which affect the convergence. also you may need to use the new updater to get to correct results, which is probably related to your issue #1144 @antinucleon @winstywang have the newest progress info.

**Comment by winstywang** [comment]
The latest codes should fix the val accuracy drop issue.

**Comment by qiaohaijun** [comment]
yes, the latest codes work fine @mli @winstywang
