### ISSUE TITLE
problem in training inception-v3

### ISSUE THREAD

**Issue by achao2013** [dmlc/mxnet#1169]
when i train the inception-v3 model, my train-accuracy and validation-accuracy stay at about 0.001, i slightly modify the model to adapt my input size 56x56(data from imagenet 2012), so where is the problem?

(ps:i try the lr from 0.1 to 0.0001 and i try to add rnd_type='gaussian' to initializer, but the result is the same)

**Comment by antinucleon** [comment]
Are you using newest version?

**Comment by piiswrong** [comment]
try using mxnet.monitor to display the outputs and weights and see if they are too big/small

**Comment by qiaohaijun** [comment]
56x56 are you mean 256x256

**Comment by achao2013** [comment]
no， i just mean 56, 56=224/4 @qiaohaijun

**Comment by achao2013** [comment]
yes ,it's the newest version @antinucleon

**Comment by achao2013** [comment]
i make a screenshot of one monitor data.begin:
![begin](https://cloud.githubusercontent.com/assets/5026576/12117269/a32d7e3e-b3fa-11e5-9513-790c996bfd53.jpg)


end:
![end](https://cloud.githubusercontent.com/assets/5026576/12117277/b402c318-b3fa-11e5-8cd9-f0057702949c.jpg)

it does have some values too big/small, so is it normal?how to fix it? @piiswrong

**Comment by superzrx** [comment]
@achao2013 
did you shuffle your train.list?

**Comment by achao2013** [comment]
yes, if i don't shuffle the train.list, the accuracy will start from 0.19 and appear a sustained downward trend @superzrx

**Comment by antinucleon** [comment]
I have trained several Inception-V3 networks and doesn't see this situation. Note the sample Inception-V3 symbol only accepts image in 3x299x299. For 3x56x56, you probably need to investigate the correct global pooling size

**Comment by achao2013** [comment]
i have print the tensor size of every layer， there are no errors. @antinucleon

**Comment by pluskid** [comment]
Closing for now due to inactivity.
