### ISSUE TITLE
[mxnetR] require(mxnet) failed

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/mxnet#1173]
I followed the instruction to install mxnetR using drat. Everything looks successfully until I `require(mxnet)` in R:
```
> require(mxnet)
Loading required package: mxnet
Error : .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/ttang/Library/R/3.2/library/mxnet/libs/libmxnet.so':
  dlopen(/Users/ttang/Library/R/3.2/library/mxnet/libs/libmxnet.so, 10): Library not loaded: /usr/local/lib/gcc/5/libgomp.1.dylib
  Referenced from: /Users/ttang/Library/R/3.2/library/mxnet/libs/libmxnet.so
  Reason: image not found
```
`ls  /Users/ttang/Library/R/3.2/library/mxnet/libs/` gives
`libmxnet.so mxnet.so` which is correct. 

Anything I missed? This worked before for me on another mac. 
Thanks.

**Comment by terrytangyuan** [comment]
Still cannot load it after trying some fixes...any suggestions? Any changes on recent mxnet distribution on drat?

**Comment by thirdwing** [comment]
You are lacking openmp support.

**Comment by terrytangyuan** [comment]
Thanks but it should still load properly without openmp, right, e.g. if openmp is not needed for the user?

**Comment by thirdwing** [comment]
I think you need the openmp support. No CUDA and no openmp support, the performance might be a problem.

**Comment by terrytangyuan** [comment]
I know but I meant in terms of the design. Anyways, thanks man.

**Comment by thirdwing** [comment]
You can compile package without OpenMP on your own machine.

Since only the CPU-version of pre-built package is provided, personally I think it is better to have OpenMP in it.

**Comment by terrytangyuan** [comment]
Gottcha, it's probably better to mention these in the build doc as R users typically don't have much experience on that.

**Comment by terrytangyuan** [comment]
It's probably also worth mentioning blog posts like this: https://medium.com/@lelayf/installing-mxnet-for-r-on-yosemite-291470055980#.3j69s3hbd
