### ISSUE TITLE
Error : object ‘create_graph’ is not exported by 'namespace:DiagrammeR'

### ISSUE THREAD

**Issue by hack-r** [dmlc/mxnet#1175]
> install.packages("drat", repos="https://cran.rstudio.com")
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/drat_0.1.0.zip'
Content type 'application/zip' length 70314 bytes (68 KB)
downloaded 68 KB

package ‘drat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	F:\temp\RtmpML1NAQ\downloaded_packages
> drat:::addRepo("dmlc")
> require(methods)
> install.packages("mxnet")
trying URL 'http://dmlc.github.io/drat/bin/windows/contrib/3.2/mxnet_0.5.zip'
Content type 'application/zip' length 13650694 bytes (13.0 MB)
downloaded 13.0 MB

package ‘mxnet’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	F:\temp\RtmpML1NAQ\downloaded_packages
> require(mxnet)
Loading required package: mxnet
Error : object ‘create_graph’ is not exported by 'namespace:DiagrammeR'

**Comment by thirdwing** [comment]
This has nothing to do with mxnet. You need to use a newer version of DiagrammeR.

**Comment by hack-r** [comment]
I am using the most recent version of DiagrammeR...

**Comment by thirdwing** [comment]
Can you show me the version of  DiagrammeR on your machine?

**Comment by thirdwing** [comment]
I am quite sure that in the latest version, `create_graph` has been exported.

https://github.com/rich-iannone/DiagrammeR/blob/master/NAMESPACE#L23
