### ISSUE TITLE
GPU R installation issue on Windows

### ISSUE THREAD

**Issue by msdw** [dmlc/mxnet#1177]
Hi
I follow https://github.com/dmlc/mxnet/blob/master/doc/build.md#build-mxnet-library to install GPU version for R on windows.
I have an error on last step
"Run R CMD INSTALL --no-multiarch R-package. Make sure that R is added to your PATH in Environment Variables. Running the command Where R in Command Prompt should return the location."

See log below :

R CMD INSTALL --no-multiarch R-package
* installing to library 'C:/Users/admin/Documents/R/win-library/3.2'
* installing *source* package 'mxnet' ...
** libs
C:/PROGRA~1/R/R-32~1.3/etc/x64/Makeconf:204: attention : écrasement des commandes pour la cible « .m.o »
C:/PROGRA~1/R/R-32~1.3/etc/x64/Makeconf:197: attention : anciennes commandes ignorées pour la cible « .m.o »
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c executor.cc -o executor.o
In file included from executor.cc:9:0:
./base.h: In function 'std::__cxx11::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
executor.cc: In static member function 'static void mxnet::R::Executor::UpdateArray(const char*, const List&, Rcpp::List*, bool, bool)':
executor.cc:37:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < from.size(); ++i) {
                          ^
executor.cc: In static member function 'static Rcpp::List mxnet::R::Executor::CloneArray(const List&)':
executor.cc:81:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < src.size(); ++i) {
                        ^
executor.cc: In function 'Rcpp::List* mxnet::R::CreateArrayList(const List&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, const RObjectType&, std::vector<void*>*)':
executor.cc:117:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < source_array.size(); ++i) {
                          ^
executor.cc: In function 'Rcpp::List* mxnet::R::CreateGradList(const List&, const List&, const std::vector<std::__cxx11::basic_string<char> >&, const RObjectType&, std::vector<void*>*, std::vector<unsigned int>*)':
executor.cc:145:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < grad_reqs.size(); ++i) {
                          ^
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c export.cc -o export.o
In file included from export.cc:9:0:
./base.h: In function 'std::__cxx11::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
export.cc: In static member function 'static void mxnet::R::Exporter::Export(const string&)':
export.cc:92:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < func_names.size(); ++i) {
                        ^
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c io.cc -o io.o
In file included from io.cc:8:0:
./base.h: In function 'std::__cxx11::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
io.cc: In static member function 'static void mxnet::R::ArrayDataIter::Convert(const NumericVector&, const std::vector<long long unsigned int>&, size_t, std::vector<mxnet::R::NDArray>*)':
io.cc:91:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size() - 1; ++i) {
                        ^
io.cc: In member function 'virtual SEXPREC* mxnet::R::DataIterCreateFunction::operator()(SEXPREC**)':
io.cc:178:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < kwargs.size(); ++i) {
                        ^
io.cc: In static member function 'static void mxnet::R::DataIterCreateFunction::InitRcppModule()':
io.cc:221:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < out_size; ++i) {
                     ^
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c kvstore.cc -o kvstore.o
In file included from kvstore.cc:9:0:
./base.h: In function 'std::__cxx11::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
kvstore.cc: In member function 'void mxnet::R::KVStore::Init(const std::vector<int>&, const List&)':
kvstore.cc:17:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   RCHECK(keys.size() == weights.size())
                      ^
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
kvstore.cc: In member function 'void mxnet::R::KVStore::Push(const std::vector<int>&, const List&, const std::vector<int>&)':
kvstore.cc:32:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < weight_lists.size(); ++i) {
                        ^
In file included from kvstore.cc:9:0:
kvstore.cc:36:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     RCHECK(list.size() == keys.size())
                        ^
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
kvstore.cc: In member function 'void mxnet::R::KVStore::Pull(const std::vector<int>&, const List&, const std::vector<int>&)':
kvstore.cc:62:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < out_lists.size(); ++i) {
                        ^
In file included from kvstore.cc:9:0:
kvstore.cc:66:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     RCHECK(src.size() == keys.size())
                       ^
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c mxnet.cc -o mxnet.o
In file included from mxnet.cc:8:0:
./base.h: In function 'std::__cxx11::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c ndarray.cc -o ndarray.o
In file included from ndarray.cc:7:0:
./base.h: In function 'std::__cxx11::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
ndarray.cc: In member function 'void mxnet::R::NDArrayPacker::Push(const RObjectType&)':
ndarray.cc:133:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     RCHECK(shape_.size() == rshape.size())
                          ^
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
ndarray.cc:136:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       RCHECK(shape_[i] == rshape[i])
                        ^
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
ndarray.cc: In member function 'Rcpp::NumericVector mxnet::R::NDArrayPacker::Get() const':
ndarray.cc:153:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   RCHECK(ret.size() == data_.size());
                     ^
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
ndarray.cc: In member function 'size_t mxnet::R::NDArray::Size() const':
ndarray.cc:194:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < dim.size(); ++i) {
                        ^
ndarray.cc: In static member function 'static const void* mxnet::R::NDArrayFunction::FindHandle(const string&)':
ndarray.cc:450:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < out_size; ++i) {
                     ^
In file included from ndarray.cc:7:0:
ndarray.cc: In function 'mxnet::R::NDArray::RObjectType mxnet::R::ndarray::Slice(const RObjectType&, mx_uint, mx_uint)':
ndarray.cc:595:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   RCHECK(dim[ndim - 1] >= end)
                        ^
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
ndarray.cc: In static member function 'static void mxnet::R::NDArrayFunction::InitRcppModule()':
ndarray.cc:629:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < out_size; ++i) {
                     ^
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.3/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.2/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wall  -mtune=core2 -c symbol.cc -o symbol.o
In file included from symbol.cc:9:0:
./base.h: In function 'std::__cxx11::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
symbol.cc: In member function 'void mxnet::R::Symbol::Compose(const List&, const string&)':
symbol.cc:64:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < kwargs.size(); ++i) {
                        ^
symbol.cc: In member function 'SEXPREC* mxnet::R::Symbol::InferShape(const List&) const':
symbol.cc:138:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < kwargs.size(); ++i) {
                        ^
symbol.cc: In static member function 'static mxnet::R::Symbol::RObjectType mxnet::R::Symbol::Group(const List&)':
symbol.cc:205:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < kwargs.size(); ++i) {
                        ^
symbol.cc: In member function 'virtual SEXPREC* mxnet::R::SymbolFunction::operator()(SEXPREC**)':
symbol.cc:265:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < kwargs.size(); ++i) {
                        ^
symbol.cc: In static member function 'static void mxnet::R::SymbolFunction::InitRcppModule()':
symbol.cc:349:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < out_size; ++i) {
                     ^
g++ -m64 -shared -s -static-libgcc -o mxnet.dll tmp.def executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lRblas -L../inst/libs/x64/ -llibmxnet -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lR
/usr/bin/sh: line 8: g++ -m64: command not found
aucune DLL n'a pas été créé
ERROR: compilation failed for package 'mxnet'
* removing 'C:/Users/admin/Documents/R/win-library/3.2/mxnet'

How to fix my issue ?
Thanks for your help
Mathurin

**Comment by thirdwing** [comment]
Which version of R and which version of Rtools you are using?

**Comment by msdw** [comment]
Hi Qjang,

 

Thanks for your fast mail.

I use R R-3.2.3 and Rtools version 3.3.0.1959

I need to use other versions ?

Thanks for your help

M.A.

 

De : Qiang Kou (KK) [mailto:notifications@github.com] 
Envoyé : mardi 5 janvier 2016 23:00
À : dmlc/mxnet <mxnet@noreply.github.com>
Cc : M. ACHE <msdw@free.fr>
Objet : Re: [mxnet] GPU R installation issue on Windows (#1177)

 

Which version of R and which version of Rtools you are using?

—
Reply to this email directly or view it on GitHub <https://github.com/dmlc/mxnet/issues/1177#issuecomment-169146944> .  <https://github.com/notifications/beacon/AERBSKgoh_DM08bR-d4QC7W9QLHz_y0bks5pXDRKgaJpZM4G_Kq5.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by thirdwing** [comment]
My suggestion is not using Rtools 3.3 if you are not a MinGW expert.

I am one of the people packaging the Rtools 3.3 and I know there are some issues.

Can you try to downgrade?

BTW ,it is **Qiang** not **Qjang**. But it doesn't matter.

**Comment by msdw** [comment]
Thank you Qiang (sorry for my mystake).

Your suggest is good. I try with Rtools 3.2 and mxnet compilation is ok now.

 

g++ -m64 -shared -s -static-libgcc -o mxnet.dll tmp.def executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lRblas -L../inst/libs/x64/ -llibmxnet -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.3/bin/x64 -lR

installing to C:/Users/admin/Documents/R/win-library/3.2/mxnet/libs/x64

** R

** demo

** inst

** preparing package for lazy loading

** help

*** installing help indices

** building package indices

** installing vignettes

** testing if installed package can be loaded

* DONE (mxnet)

 

Thank you very much, I can play with my graphics card GTX 980 Ti now.

 

Best regards Qiang

Mathurin

De : Qiang Kou (KK) [mailto:notifications@github.com] 
Envoyé : mardi 5 janvier 2016 23:11
À : dmlc/mxnet <mxnet@noreply.github.com>
Cc : M. ACHE <msdw@free.fr>
Objet : Re: [mxnet] GPU R installation issue on Windows (#1177)

 

My suggestion is not using Rtools 3.3 if you are not a MinGW expert.

I am one of the people packaging the Rtools 3.3 and I know there are some issues.

Can you try to downgrade?

BTW ,it is Qiang not Qjang. But it doesn't matter.

—
Reply to this email directly or view it on GitHub <https://github.com/dmlc/mxnet/issues/1177#issuecomment-169149803> .  <https://github.com/notifications/beacon/AERBSMjo6nIOzd3zCeY8QZFnzdqvt3KVks5pXDbngaJpZM4G_Kq5.gif> 



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
