### ISSUE TITLE
use HPC to train deep neural networks

### ISSUE THREAD

**Issue by fancyerii** [dmlc/mxnet#1179]
traditional HPC use MPI to do large scale computing intensive tasks. Is it possible to train using mpi interface?

**Comment by jermainewang** [comment]
For your question in general, I think the answer is yes. MPI is good in bandwidth but bad in latency, so it is suitable for blob data transmission which frequently happens in data parallelism.

You could use MPI to start parameter server and worker instance (your mxnet program) like [here](https://github.com/dmlc/ps-lite/blob/master/tracker/dmlc_mpi.py). But the underlying communication is not based on MPI.

@mli do you have any comments?

**Comment by vchuravy** [comment]
@jermainewang Latency depends largely on the underlying infrastructure and MPI implementation. On a HPC cluster with a good (infinband) interconnect MPI should have good performance.

**Comment by jermainewang** [comment]
@vchuravy gotcha. I think within current framework, what we could do is to implement two special dataflow operators: one for MPISend, one for MPIRecv. But this is only the first step. For MPIRecv task, there is no upstream task so it (and its memory space) will be created and stay there for a long time. One way to deal with it is the technique mentioned in tensorflow paper that delay the schedule of MPIRecv task until MPISend task is launched.

**Comment by vchuravy** [comment]
Also crossref #977.

I think what would be really interesting is CUDA aware MPI [1,2]. Using that could actually give quite a speedup to communication.

[1] http://devblogs.nvidia.com/parallelforall/introduction-cuda-aware-mpi/
[2] https://www.open-mpi.org/faq/?category=runcuda
