### ISSUE TITLE
How to train multi label classifier from a dataset that the num of label of each image is different

### ISSUE THREAD

**Issue by zhaoxin19** [dmlc/mxnet#1182]
I‘ve see the document that we can use im2rec to create a rec file for ImageRecordIter. But the num of class label has to be the same. What can I do to train with different num of class label?

**Comment by jermainewang** [comment]
I'm afraid you need to write your own code in `im2rec` to do this. If I do not understand it wrong, what you need is an extra int for each image that represents how many labels it has. So you need to modify the code to put this information together with the label information.

One hacky way I could think about within the current fixed-num-label setting is that you could encode the number of labels as part of labels. For example, suppose your `image.lst` file is like this:
```
path_to_img1 1
path_to_img2 3
path_to_img3 23
...
```
You could add another column to specify the number of labels.
```
path_to_img1 1 5
path_to_img2 3 5
path_to_img3 23 7
...
```
When using `img2rec`, use `label_width=2` to read the file.

**Comment by zhaoxin19** [comment]
I've read im2rec.cc and found that this tool simply take the first label and drop the others in multilabel case. And I've found the struct in image_recordio.cc. The label in the header is a float. But the annotation is intresting. It says I can just supply a list file that maps image id to new labels. What does it mean?
struct Header {
    /*!
     * \brief flag of the header,
     *  used for future extension purposes
     */
    uint32_t flag;
    /*!
     * \brief label field that returns label of images
     *  when image list was not presented,
     * 
     * NOTE: user do not need to repack recordio just to
     * change label field, just supply a list file that
     * maps image id to new labels
     */
    float label;
    /*!
     * \brief unique image index
     *  image_id[1] is always set to 0,
     *  reserved for future purposes for 128bit id
     *  image_id[0] is used to store image id
     */
    uint64_t image_id[2];
  };

**Comment by pluskid** [comment]
The [record io](http://mxnet.io/api/python/io.html#extension-multiple-labels-for-a-single-image) now support multi labels.
