### ISSUE TITLE
compiler error when including OpenCV

### ISSUE THREAD

**Issue by colinpriest** [dmlc/mxnet#1183]
While this problem was raised by another user in https://github.com/dmlc/mxnet/issues/744 it was never resolved. I have tried the suggested fix and it did not resolve my problem. I can confirm that I have OpenCV installed. When I run "pkg-config --libs opencv" I get:

/usr/lib/x86_64-linux-gnu/libopencv_calib3d.so -lopencv_calib3d /usr/lib/x86_64-linux-gnu/libopencv_contrib.so -lopencv_contrib /usr/lib/x86_64-linux-gnu/libopencv_core.so -lopencv_core /usr/lib/x86_64-linux-gnu/libopencv_features2d.so -lopencv_features2d /usr/lib/x86_64-linux-gnu/libopencv_flann.so -lopencv_flann /usr/lib/x86_64-linux-gnu/libopencv_gpu.so -lopencv_gpu /usr/lib/x86_64-linux-gnu/libopencv_highgui.so -lopencv_highgui /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so -lopencv_imgproc /usr/lib/x86_64-linux-gnu/libopencv_legacy.so -lopencv_legacy /usr/lib/x86_64-linux-gnu/libopencv_ml.so -lopencv_ml /usr/lib/x86_64-linux-gnu/libopencv_objdetect.so -lopencv_objdetect /usr/lib/x86_64-linux-gnu/libopencv_ocl.so -lopencv_ocl /usr/lib/x86_64-linux-gnu/libopencv_photo.so -lopencv_photo /usr/lib/x86_64-linux-gnu/libopencv_stitching.so -lopencv_stitching /usr/lib/x86_64-linux-gnu/libopencv_superres.so -lopencv_superres /usr/lib/x86_64-linux-gnu/libopencv_ts.so -lopencv_ts /usr/lib/x86_64-linux-gnu/libopencv_video.so -lopencv_video /usr/lib/x86_64-linux-gnu/libopencv_videostab.so -lopencv_videostab 

When I run apt-cache show libopencv-dev I get:

Package: libopencv-dev
Priority: optional
Section: universe/libdevel
Installed-Size: 653
Maintainer: Kubuntu Developers <kubuntu-devel@lists.ubuntu.com>
Original-Maintainer: Debian Science Team <debian-science-maintainers@lists.alioth.debian.org>
Architecture: amd64
Source: opencv
Version: 2.4.9+dfsg-1ubuntu6
Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libopencv-calib3d2.4v5, libopencv-core2.4v5, libopencv-highgui2.4v5, libopencv-imgproc2.4v5, libopencv-ml2.4v5, libopencv-objdetect2.4v5, libstdc++6 (>= 5.2), libopencv-core-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-ml-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-imgproc-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-video-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-objdetect-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-highgui-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-calib3d-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-flann-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-features2d-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-legacy-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-contrib-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-ts-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-photo-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-videostab-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-stitching-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-gpu-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-superres-dev (= 2.4.9+dfsg-1ubuntu6), libopencv-ocl-dev (= 2.4.9+dfsg-1ubuntu6), libopencv2.4-java (= 2.4.9+dfsg-1ubuntu6), libopencv2.4-jni (= 2.4.9+dfsg-1ubuntu6), libcv-dev (= 2.4.9+dfsg-1ubuntu6), libhighgui-dev (= 2.4.9+dfsg-1ubuntu6), libcvaux-dev (= 2.4.9+dfsg-1ubuntu6), pkg-config
Recommends: opencv-data
Breaks: libopencv-core-dev (<= 2.3.1-8)
Filename: pool/universe/o/opencv/libopencv-dev_2.4.9+dfsg-1ubuntu6_amd64.deb
Size: 167428
MD5sum: ecaf4191cf03536bff3e19cc1ddc424c
SHA1: d719e328151d771af7eaef054ee7edbbf803681d
SHA256: 0c7ec4a327a5c124ddcb6d5247a3e0a7421679a422aa005353830d59444d818e
Description-en: development files for opencv
 This is a metapackage providing development package necessary for
 development of OpenCV (Open Computer Vision).
 .
 The Open Computer Vision Library is a collection of algorithms and sample
 code for various computer vision problems. The library is compatible with
 IPL (Intel's Image Processing Library) and, if available, can use IPP
 (Intel's Integrated Performance Primitives) for better performance.
 .
 OpenCV provides low level portable data types and operators, and a set
 of high level functionalities for video acquisition, image processing and
 analysis, structural analysis, motion analysis and object tracking, object
 recognition, camera calibration and 3D reconstruction.
Description-md5: f9dc67381f1013c39fe59842c79cbddf
Homepage: http://opencv.org/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

I can successfully compile and run mxnet with USE_OPENCV = 0. When I compile with USE_OPENCV = 1, and run make clean all, I get the following error:

/tmp/ccYg0ncG.o: In function `main':
im2rec.cc:(.text.startup+0x2789): undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
Makefile:167: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

**Comment by tornadomeet** [comment]
do you configure the opencv lib path in your environment(maybe ~/.bashrc in linux)? like this:
export PKG_CONFIG_PATH=$YOUR_PATH/opencv/lib/pkgconfig
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OUR_PATH/opencv/lib

**Comment by colinpriest** [comment]
I don't have any directories called pkgconfig
I added /home/colin/mxnet/opencv-3.1.0/build/lib to my .bashrc but that didn't fix the problem
My /etc/ld.so.conf.d/opencv.conf contains /usr/local/lib

**Comment by tornadomeet** [comment]
try:
1. source ~/.bashrc before make
2. where is your opencv.pc path when you install opencv? the PKG_CONFIG_PATH is point to that directory.

**Comment by colinpriest** [comment]
Thanks. I was able to find the path after searching for opencv.pc. After setting those values in my .bashrc I'm still getting the same error message undefined reference to cv::imencode. 

Here is what I have done in response to your advice:

opencv.pc is located at:
/usr/lib/x86_64-linux-gnu/pkgconfig/opencv.pc

echo $PKG_CONFIG_PATH returns:
/usr/lib/x86_64-linux-gnu/pkgconfig

echo $LD_LIBRARY_PATH returns:
/usr/local/cuda-7.5/lib64:/usr/lib/x86_64-linux-gnu

**Comment by tornadomeet** [comment]
this problem should be cased by the opencv installation, your can refer to https://github.com/BVLC/caffe/issues/2288

**Comment by colinpriest** [comment]
Where do I add opencv_imgcodecs into the project? Which Makefile? Is the syntax LIBRARIES += opencv_imgcodecs?

**Comment by tornadomeet** [comment]
you can first try to write one test.cpp(use opencv function in it) to test whether you can  build and run it sucessfully.

**Comment by colinpriest** [comment]
Sorry but I'm too much of a newby to be able to do that simply. I shall just run mxnet without OpenCV.
