### ISSUE TITLE
Questions about distributed training.

### ISSUE THREAD

**Issue by kingder** [dmlc/mxnet#1186]
I have a small cluster (~10 machines running Ubuntu) without GPU, and I want to use mxnet to train a simple network (2 hidden layers) on this cluster. but the data (~500G for training, ~100G for validation) is not image, it's a simple binary data with about 600 features each sample.

I modified the train_mnist.py under example/image-classification a little bit to suit my needs on single machine, now I want to turn it to a distributed version, below are my questions:

+ In single machine, I use numpy.memmap + NDArrayIter as suggested in #791, since I also don't have a distributed file system, so for my case, I have to partition the data into smaller files, like 50G each, and put the partitioned file in the same folder on each machine, is that the proper way to go?

+ In each epoch, the trainer will calculate metrics for the given validation data against the model, this is straightforward for single machine, but how to deal with the distributed version? I mean, how can I get  an overall metrics for the validation data in each epoch?

**Comment by jermainewang** [comment]
For the first question, I think it is fine for your current setting. One thing I would suggest is to compress your data. If your data is highly compressable (like text), you could save a lot of space and maybe you could put all the data on each machine then. Basically, you pay the cost of decompression to the disk space which seems to be precious in your setting.

For the second question, a quick (and hacky) way is to
1. Calculate validation metrics on each machine (result is a real number).
2. Write the result to a shared file (maybe on NFS).
3. Read them on the first machine.
4. Sum them up and report.

**Comment by kingder** [comment]
Thanks for the reply!

what if the metrics can't be summed up, like AUC?

**Comment by jermainewang** [comment]
I'm not familiar with AUC measurement. But you could try decompose the calculation of AUC into several summable components and apply the similar idea above to it.

**Comment by kingder** [comment]
Thanks!
