### ISSUE TITLE
how to input  numerial value to mxnet?

### ISSUE THREAD

**Issue by leoli2012** [dmlc/mxnet#1187]
i want do some regression task under mxnet, but my data is  libsvm format,  like this (1:10,2:33,5:8.5,9:22)... i read example on mxnet, but seems mxnet  is prepare for image, would anybody tell me how to input these data to mxnet model??

**Comment by leoli2012** [comment]
is mxnet.io.CSVIter or mxnet.io.NDarray or mxnet.io.DataIter?

**Comment by jermainewang** [comment]
Yes, you could use `mxnet.io.NDArrayIter`. First load your data to a numpy array (or mxnet ndarray). Then feed it to a `mxnet.io.NDArrayIter`. You could then use it with your model in mxnet.

**Comment by leoli2012** [comment]
thanks ~
