### ISSUE TITLE
[hdfs] any one use hdfs for data storage?

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#1188]
did anyone succeed in load data from hdfs?

**Comment by jermainewang** [comment]
What problem did you meet?

**Comment by qiaohaijun** [comment]
set USE_HDFS=1 and complie mxnet succeed.

but can't load the data from hdfs.

**Comment by tqchen** [comment]
You might need to ```make clean_all``` as this need rebuild of dmlc-core,

**Comment by pzz2011** [comment]
where to set USE_HDFS=1,is the position in the dmlc-core/make/config.mk#line:22?
