### ISSUE TITLE
where is the definition of FullyConnected?

### ISSUE THREAD

**Issue by formath** [dmlc/mxnet#1190]
I saw the use of mx.symbol.FullyConnected in many examples. However, I can not find the definition of FullyConnected in symbol.py. Someone can help?

**Comment by javelinjs** [comment]
It is dynamically loaded by _init_symbol_module in symbol.py. More precisely, it is defined in src/operator/fully_connected-inl.h and registered as an operator, which can be discovered by c_api::MXSymbolListAtomicSymbolCreators, MXSymbolGetAtomicSymbolInfo, and invoked by MXSymbolCreateAtomicSymbol
