### ISSUE TITLE
[mxnetR] Thoughts about supported input data type 

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/mxnet#1192]
Following the MLP example here: http://dmlc.ml/rstats/2015/11/03/training-deep-net-with-R.html

Some thoughts: 
1. we should make `Sonar[,61]` work without converting `as.numeric(Sonar[,61])-1`. (numeric vs factor)
2. if `train.y` is one dimensional dataframe or datatable, it should also work. Currently only vector is supported. (vector vs dataframe vs datatable)
3. it is worth mentioning the types of data that's supported
4. similar logistics apply to `train.x`

cc: @thirdwing @hetong007 Great job on the R package.

**Comment by thirdwing** [comment]
I can update the documents for supported types.

But I don't think we should handle the type conversion, it should be users' work.

**Comment by terrytangyuan** [comment]
That's fine. It would be even better to note the type of elements in the array.
