### ISSUE TITLE
[mxnetR] Option to handle missing values

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/mxnet#1193]
Reproducible example: 
```
require(mlbench)
require(mxnet)

data(Sonar, package="mlbench")

Sonar[,61] = as.numeric(Sonar[,61])-1
train.ind = c(1:50, 100:150)
train.x = data.matrix(Sonar[train.ind, 1:60])
train.y = Sonar[train.ind, 61]
test.x = data.matrix(Sonar[-train.ind, 1:60])
test.y = Sonar[-train.ind, 61]

train.x[1, 1] <- NA

mx.set.seed(0)
model <- mx.mlp(train.x, train.y, hidden_node=10, out_node=2, out_activation="softmax",
                num.round=50, array.batch.size=15, learning.rate=0.07, momentum=0.9, 
                eval.metric=mx.metric.accuracy)
```
gives
```
Auto detect layout of input matrix, use rowmajor..
Start training with 1 devices
[1] Train-accuracy=NA
[2] Train-accuracy=NA
[3] Train-accuracy=NA
[4] Train-accuracy=NA
[5] Train-accuracy=NA
[6] Train-accuracy=NA
[7] Train-accuracy=NA
[8] Train-accuracy=NA
[9] Train-accuracy=NA
[10] Train-accuracy=NA
[11] Train-accuracy=NA
[12] Train-accuracy=NA
[13] Train-accuracy=NA
[14] Train-accuracy=NA
[15] Train-accuracy=NA
[16] Train-accuracy=NA
[17] Train-accuracy=NA
[18] Train-accuracy=NA
[19] Train-accuracy=NA
[20] Train-accuracy=NA
[21] Train-accuracy=NA
```

**Comment by terrytangyuan** [comment]
My thought is maybe provide some helper functions to let users easily handle this.

**Comment by viswaraavi** [comment]
I am new to mxnet. I am thinking to work on this problem. I have thought of three ways to deal with problem 1. one is omitting the rows with missing data 2. using mean for prediction 3. using EM algorithm before processing . I want to know how missing data is handled in other packages. Any guidance on how to proceed further?

**Comment by thirdwing** [comment]
Personally it is users' responsibility to decide how to handle missing data.

I think we can provide some functions, but we can't do that automatically.

**Comment by viswaraavi** [comment]
so what kind of functions might be helpful ?

**Comment by pommedeterresautee** [comment]
Usually in these situations, you are not supposed to use something like [matrix completion ](https://en.wikipedia.org/wiki/Matrix_completion) algo? What else can be done?

It can't be fixed as easily that in XGboost as we can't easily tell the #nnet NA is a special value. How to compute a partial derivative on it?

**Comment by thirdwing** [comment]
@pommedeterresautee I agree with you. We can give a warning, even an error, when the data set has NA. It is users who need to decide how to handle missing values.

**Comment by terrytangyuan** [comment]
Yeah probably just some warnings since new users might not be sure how to deal with NAs in the evaluation metrics. @thirdwing 

I was mistakenly thinking this can be handled like in xgboost. @pommedeterresautee thanks for correcting me.
