### ISSUE TITLE
[Question/ENH] Is stratefied/custom batching available? 

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/mxnet#1194]
Per title, maybe I missed it somewhere but I cannot seem to find this. 

One scenario is dealing with highly class imbalanced dataset, so there's a big chance that many batches only contain one class, which disables metrics like AUC that often require two classes in preds and labels in one batch. 

Any thoughts?

**Comment by piiswrong** [comment]
If it's only for metric, you can change the update function such that it stores result on update call and only start computing when more than one classes are available.

**Comment by terrytangyuan** [comment]
@piiswrong Got it. I'll try it. Thanks!

**Comment by terrytangyuan** [comment]
That solution is ok but it's better to have a way to do stratified batching, or at least make this part customizable. Any thoughts? Would this be easy given current structure?

**Comment by terrytangyuan** [comment]
Hmm, I think making some further twists in update function would be enough to achieve what I want. Closing this now. @piiswrong Thanks again.
