### ISSUE TITLE
travis sometimes suspend on threaded_engine_test.cc 

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#1198]
sometimes the travis breaked in cpp_test job in pr with the log: 
```
============= Test #4 ==============
tests/cpp/threaded_engine_test.cc:198: IO operator pushed, should wait for 2 seconds.
The fox says 42
```
but most of the time it is correct, so is due to the changed code or something else?
i met this problem a few times.

**Comment by tqchen** [comment]
This can  be safely ignored.

**Comment by tqchen** [comment]
be more specific, @hotpxl  and I have looked into it. we never be able to reproduced it locally, so not sure if this was due to travis hanging or some weird setups, so it can be ignored for now.
