### ISSUE TITLE
NaN in calculated gradient.

### ISSUE THREAD

**Issue by boliu68** [dmlc/mxnet#1202]
I am currently coding a multi-layer perceptron(MLP) using mxnet python. Instead of using Feedward module to automatically optimize MLP, I code my own MLP using forward() and backward(). 

The gradients obtained by backward(), however, are found to contain NaN. Particularly, only the gradient for the first hidden layer contains NaN. During debugging, I found that matplotlib seems to be the reason for such NaN problem. More specifically, as far as I have tested, "NaN" never occurs without using  matplotlib.figure(). As a result, **I suspect whether matplotlib package has conflicts with mxnet?** 

I write a demo code to demonstrate the problem. If plt.figure() is commented, no "NaN" will occur.

```python
import sys
import numpy as np
import mxnet as mx
import matplotlib.pyplot as plt

class mx_gp_mlp:

    def __init__(self):

        self.net = None

    def fit(self, X, y, hidden_unit):

        #####Make Neural Network
        net = mx.symbol.Variable("data")
        net = mx.symbol.FullyConnected(data=net, name="fc1", num_hidden=20)
        net = mx.symbol.Activation(data=net, name='relu1', act_type='relu')
        net = mx.symbol.FullyConnected(data=net, name="fc2", num_hidden=2)
        net = mx.symbol.SoftmaxOutput(data=net, name="softmax")
        self.net = net

        ####Bind the neural network
        self.net_exec = self.net.simple_bind(ctx=mx.cpu(0), data=X.shape, grad_req="write")

        data_name = "data"
        label_name = "softmax_label"
        self.data_arrays = self.net_exec.arg_dict[data_name]
        self.label_arrays = self.net_exec.arg_dict[label_name]

        self.data_arrays[:] = X
        self.label_arrays[:] = y

        for it in range(5):
            self.net_exec.forward(is_train=True)
            plt.figure()
            self.net_exec.backward()

            for i in range(len(self.net_exec.grad_arrays)):
                if self.net_exec.grad_arrays[i] != None:
                    if np.sum(np.isnan(self.net_exec.grad_arrays[i].asnumpy())) > 0:
                        print 'NaN'
                        sys.exit()

for i in range(10000):
    print i
    X = np.random.rand(187, 19993)
    y = np.random.randint(2, size=187)

    mx_mlp = mx_gp_mlp()
    mx_mlp.fit(X,y, hidden_unit=[20, 2])
```

**Comment by winstywang** [comment]
If you remove plt.figure(), is everything fine?

**Comment by boliu68** [comment]
Yep. I have test many times of demo code. And it is fine without plt.figure()

**Comment by sxjscience** [comment]
Should we add `self.net_exec.grad_arrays[i].wait_to_read()` before reading the content?

**Comment by boliu68** [comment]
Thanks for your suggestion. In my test, "NaN" occurs usually within 200 iternum.

**Comment by boliu68** [comment]
And "NaN" occurs quite randomly. Sometimes, it occurs in my first 5 iteration.

**Comment by sxjscience** [comment]
Will this revision help? Replacing `plt.figure()` to `fig = plt.figure()` and add `plt.close(fig)` at the end of the inner for?

**Comment by boliu68** [comment]
Thanks. I just tired to close the figure in each iteration and also tired to wait_to_read before read grad array. However, the "NaN" problem remains.
