### ISSUE TITLE
what the parameter mean of "data_shape" in mxnet.io.CSVIter ？

### ISSUE THREAD

**Issue by leoli2012** [dmlc/mxnet#1204]
i meet a issue, i use mxnet.io.CSVIter(data_csv,data_shape,label_csv,label_shape,batch_size), i tried with  my csv data,which shape is(440,5), label csv is 440 row,  i thinks, the data_shape parameter have the same meaning with data shape, however, i was  confused by my test~
FEA_NUM = 5
Test 1:
train_iter = mx.io.CSVIter(data_csv = train_data,data_shape =(train_num,FEA_NUM),label_csv = train_label,label_shape = (train_label_num,),batch_size = 1)
error messages
 ./dmlc-core/include/dmlc/logging.h:208: [18:48:23] src/io/iter_csv.cc:105: Check failed: (row.length) == (shape.Size()) The data size in CSV do not match size of shape: specified shape=(440, 5), the csv row-length=5
Test 2:
train_iter = mx.io.CSVIter(data_csv = train_data,data_shape =(FEA_NUM,),label_csv = train_label,label_shape = (train_label_num,),batch_size = BATCH_SIZE)
error messages:
./dmlc-core/include/dmlc/logging.h:208: [19:10:45] src/io/iter_csv.cc:105: Check failed: (row.length) == (shape.Size()) The data size in CSV do not match size of shape: specified shape=(440,), the csv row-length=1
Test 3:
train_iter = mx.io.CSVIter(data_csv = train_data,data_shape =(FEA_NUM,10),label_csv = train_label,label_shape = (train_label_num,),batch_size = BATCH_SIZE)
error messages:
./dmlc-core/include/dmlc/logging.h:208: [19:14:25] src/io/iter_csv.cc:105: Check failed: (row.length) == (shape.Size()) The data size in CSV do not match size of shape: specified shape=(5, 10), the csv row-length=5
i have no any idea about these........

**Comment by tqchen** [comment]
Each row of csv is can be viewed as vector of floating arries, and it will be reshaped into the ```data_shape```. 

In your case, we expect 400 features as data shape, but seems each row only contains 1 elements

**Comment by leoli2012** [comment]
@tqchen  hi, you meaning ,each row data in csv file will be reshaped into the data_shape? so if my data in csv file format like this..
first row:      1,2,3,4,5,6
second row:1,2,3,4,5,6
3 row          :1,2,3,4,5,6
.....
if data_shape parameter is (3,2), so each row will be reshaped like below
1,2
3,4
5,6
right?

**Comment by tqchen** [comment]
Yes

**Comment by leoli2012** [comment]
thanks~

**Comment by machuck** [comment]
How can we mix the matrix variable with scalar variables if it can be done?

example: 6 columns, with the first column being matrix ...
row1: [ [1,2]
            [3,4]
            [5,6]
          ]              , 0, 1, 0, 0, 0
