### ISSUE TITLE
OpenCV is unavailable when run MXNet Python Overview Tutorial

### ISSUE THREAD

**Issue by wanghaisheng** [dmlc/mxnet#1205]
ubuntu 15.10  64 bit
installation steps are as follows
```
Building on Ubuntu/Debian

On Ubuntu >= 13.10, one can install the dependencies by

sudo apt-get update
sudo apt-get install -y build-essential git libatlas-base-dev libopencv-dev

Then build mxnet

git clone --recursive https://github.com/dmlc/mxnet
cd mxnet; make -j4


```
when i run 
```
➜  python git:(master) python 
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
OpenCV is unavailable.

```
solution is [Python module for OpenCV requires a library that's unavailable to Ubuntu 14.04](http://stackoverflow.com/questions/25981807/python-module-for-opencv-requires-a-library-thats-unavailable-to-ubuntu-14-04)
```
sudo apt-get install --reinstall python-opencv

```

**Comment by qiaohaijun** [comment]
pip install cv2

**Comment by piiswrong** [comment]
This is a harmless error unless you want to use mxnet.recordio

**Comment by lorraine2015** [comment]
same problem on mac

**Comment by wangg12** [comment]
I met the same error but fixed after rebuilding openCV.

**Comment by bornfree** [comment]
Still a problem for me on mac with OpenCV3. I installed using brew. How did I get it working?
