### ISSUE TITLE
build failed on windows at lastest version project

### ISSUE THREAD

**Issue by xylcbd** [dmlc/mxnet#1209]
file : unary_function-inl.h 
line : 169

<code>
// Min
MXNET_REGISTER_TBLOB_FUN(min, XPU)
.set_function(XPU::kDevMask, Reduce<XPU, mshadow::red::minimum>, false, false)
.set_shape_infer(ScalarShape)
.describe("Take min of the src."
          "The result will be ndarray of shape (1,) on the same device.");
</code>

build error : "no instance of function template "mxnet::ndarray::Reduce" matches the required type	mxnet	.\mxnet\src\ndarray\unary_function-inl.h	171"

**Comment by xylcbd** [comment]
and a lot of other build error message. such as:
file : static_graph.cc
line : 417

<code>
helper.DeclareOptionalField("attr", &attr);
</code>

build error : "DeclareOptionalField not declared."

**Comment by piiswrong** [comment]
what is your compiler version? does it support c++11?

**Comment by xylcbd** [comment]
yes, visual studio 2015 community version.

**Comment by xylcbd** [comment]
and i cannot find any "DeclareOptionalField" in other files beside "static_graph.cc".

**Comment by xylcbd** [comment]
git commit id  of what i test project version is : 

<code>
SHA-1: 520e5c2c8baa4e067e1dc2819307541abd6f8479

* Merge pull request #1230 from freesouls/master

add a Deep Residual Network example for cifar10
</code>

**Comment by piiswrong** [comment]
try git submodule update

**Comment by xylcbd** [comment]
okay , it works now. thx !
