### ISSUE TITLE
R package - progress messages

### ISSUE THREAD

**Issue by colinpriest** [dmlc/mxnet#1210]
I have switched over from the python package to the R package and I'm running the Kaggle example. I'm running R from jupyter

When I'm fitting the network, the epoch progress messages do not appear until all of the epochs have finished running. Is there any way for me to see the results of each epoch as soon as that epoch is complete?

**Comment by thirdwing** [comment]
@colinpriest I have to admit that I have never tested it on Jupyter. Let me have a look and come back to you.

**Comment by thirdwing** [comment]
@colinpriest Just confirmed this problem. But to be frank, I think this is an issue in IR kernel.

I will talk with these people.

**Comment by colinpriest** [comment]
Thanks. I haven't been able to get the script to run in R Studio yet because it can't find the cudart.so library. I suppose I will need to figure out why IPython can find the library, but R Studio cannot, so that I can switch to running mxnet in R Studio.

**Comment by thirdwing** [comment]
I guess you must be using the GPU.

The simplest solution: startup RStudio from terminal. On Linux, just `rstudio`; on Mac, `/Applications/RStudio.app/Contents/MacOS/RStudio`

**Comment by tqchen** [comment]
I guess rstudio must have some configuration on env variables, maybe consider add this to  a new R package trouble shootting section in here ttps://github.com/dmlc/mxnet/blob/master/doc/build.md

**Comment by colinpriest** [comment]
Thanks. Starting R Studio that way works! :-)

**Comment by thirdwing** [comment]
Theoretically, the CUDA path can be added in `~/.Renviron`. When R starts, it will try to find `~/.Renviron` and load it.
