### ISSUE TITLE
weighted objective

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#1211]
I have a situation where I'd like positive samples to be more heavily weighted than negative ones, such that gettting a positive sample wrong is worse than getting a negative sample wrong (aka value precision over recall). What is the most intuitive way to do this in mxnet?

**Comment by piiswrong** [comment]
I think you need to write a new operator.

**Comment by jmschrei** [comment]
There's no way to weight samples?

**Comment by piiswrong** [comment]
Not generic way I think. However, depending on your loss, sometimes it's possible to archive weighting by scaling your label.

**Comment by tqchen** [comment]
Normally we can scale the gradient, but that does not cope well with SGD, building a DataIter that do the sample generation is a better way.

**Comment by jmschrei** [comment]
Thanks @piiswrong and @tqchen. What do you mean by sample generation; just adding a sample the same number of times as the weight?

**Comment by tqchen** [comment]
Yes, sample instance proportional to weight usually works better for sgd
type algorithms
