### ISSUE TITLE
compile on osx error: host compiler not supported

### ISSUE THREAD

**Issue by quocnle** [dmlc/mxnet#1212]
Hi, I get the following error when compiling mxnet on osx yosemite, using the setting below.

nvcc fatal   : The version ('70002') of the host compiler ('Apple clang') is not supported

Here are the settings I added to config.mk (osx.mk)

USE_CUDA=1
USE_CUDA_PATH=/usr/local/cuda
USE_CUDNN=1

And here is a little more error context:

/usr/local/cuda/bin/nvcc --use_fast_math -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=0" -M -MT build/ndarray/ndarray_function_gpu.o src/ndarray/ndarray_function.cu >build/ndarray/ndarray_function_gpu.d
nvcc fatal   : The version ('70002') of the host compiler ('Apple clang') is not supported
make: *** [build/ndarray/ndarray_function_gpu.o] Error 1

Any help appreciated, thanks!

**Comment by piiswrong** [comment]
Here is a hacky solution: https://gist.github.com/zchee/7833bf67013e83523181
Or you can try downgrading your clang

**Comment by quocnle** [comment]
Thank you!  I ended up just downgrading clang per your suggestion, and I am all set.  I appreciate your help.
