### ISSUE TITLE
How to install mxnet on Fedora 23?

### ISSUE THREAD

**Issue by NiranjanMudhiraj** [dmlc/mxnet#1214]
#when i installed mxnet on fedora 23 i am getting this error?
$git clone --recursive https://github.com/dmlc/mxnet
$cd mxnet; make -j4
......
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
Makefile:153: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
Makefile:167: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

**Comment by thirdwing** [comment]
You don't have blas installed on your machine.

Maybe try `sudo yum install atlas-devel`?

**Comment by NiranjanMudhiraj** [comment]
blas installed on my machine.still i am getting same error.

**Comment by yulijia** [comment]
Hi, @thirdwing 
The error has mentioned at here. http://yulijia.net/en/howto/2015/12/22/install-MXNet-on-Fedora.html

As names and content of atlas libraries have changed, we need change the complication command from `-lcblas` to `-lsatlas` or `-ltatlas` at mshadow/make/mshadow.mk, line 57.

**Comment by axlesor** [comment]
Is this an optimus laptop with bumblebee? If it is then Cblas does not sit in the proper place that build expects.
