### ISSUE TITLE
Error in the pre-trained Inception-v3 model

### ISSUE THREAD

**Issue by fengjunlv** [dmlc/mxnet#1218]
This small piece of code returns 1008
prob = model.predict(batch)[0]
print prob.shape

which means the dimension of the prob returned from model.predict() is 1008 instead of 1000.  There is no problem for the pre-trained model Inception-BN

**Comment by fengjunlv** [comment]
The json file also shows 1008 in the fully connect layer. Why is it 1008 instead of 1000?

      "op": "FullyConnected", 
      "param": {
        "no_bias": "False", 
        "num_hidden": "1008"

**Comment by antinucleon** [comment]
Because it is converted from Google's model. Google's model has 1008 output and I don't know what is the 8 classes either.

**Comment by fengjunlv** [comment]
Thanks.  I see.  The converted model would be more useful if the meaning of the output is clear :) 

Has anybody tried training the model from scratch and wanted to share with us information such as lr settings, training speed, total training time, etc.?

**Comment by yuzcccc** [comment]
+1, want to see the results trained from scratch!
