### ISSUE TITLE
can NDArrayIter read data from file?

### ISSUE THREAD

**Issue by yaguanghu** [dmlc/mxnet#1220]
I want do some other classification task with mxnet. But NDArrayIter seems only read data from memory.
Cause my data is very large, and cannot load in memory wholy. anybody could tell me how to read large data from file for mxnet input?

**Comment by piiswrong** [comment]
try numpy.mmap.

**Comment by jmschrei** [comment]
numpy memory maps will work, but only if you've saved them as memory maps before hand.

**Comment by piiswrong** [comment]
@jmschrei Yes, depending on your data format, you can try CVSIter.

**Comment by yaguanghu** [comment]
oh,yes. CSVIter solves my problem. thanks

**Comment by mcxkarakoc** [comment]
@mcxkarakoc
