### ISSUE TITLE
How to time MxNet test-time？like caffe's tool “time”？

### ISSUE THREAD

**Issue by wangzhangup** [dmlc/mxnet#1221]
Only use time.time()

**Comment by piiswrong** [comment]
we have callback.Speedometer. If you want wall clock time, time.time() should be good enough.

**Comment by lifeizhuhai** [comment]
@piiswrong caffe's tool "time" can see the time cost of each layer. So I can reduce the parameter of the layer which spend lots of time. Is there some way to see the cost of each layer from mxnet?

**Comment by wangzhangup** [comment]
@lifeizhuhai @piiswrong tool "time" very useful!

**Comment by piiswrong** [comment]
You mean profiler? It can be added to graph_executor. We are talking about adding this feature but no one has started working on it yet. You are welcomed to contribute.
