### ISSUE TITLE
R package is missing mx.model.FeedForward.load function

### ISSUE THREAD

**Issue by colinpriest** [dmlc/mxnet#1223]
I am using callback functions to save my parameters at each iteration. But when I try to load the model parameters from any of those iteration files I get:

systole_model = mx.model.FeedForward.load("systole", 3)
Error in eval(expr, envir, enclos): could not find function "mx.model.FeedForward.load"

systole_model = mx.model.load("systole", 3)
Error in eval(expr, envir, enclos): Parameter scalar is not presented

**Comment by thirdwing** [comment]
@colinpriest Can you send me your model file? I will look into this now.

**Comment by colinpriest** [comment]
It's the mxnet example for the Data Science Bowl, except that I have customised the following part of the R script.

mx.callback.early.stop <- function(period, prefix, logger=NULL) {
  function(iteration, nbatch, env) {
    if (nbatch %% period == 0 && !is.null(env$metric)) {
          result <- env$metric$get(env$train.metric)
          if (nbatch != 0)
                cat(paste0("Batch [", nbatch, "] Train-", result$name, "=", result$value, "\n"))
          if (!is.null(logger)) {
                # save a copy of the parameters
                mx.model.save(env$model, prefix, iteration)
                cat(sprintf("Model checkpoint saved to %s-%04d.params\n", prefix, iteration))
                # log the results
                if (class(logger) != "mx.metric.logger") {
                      stop("Invalid mx.metric.logger.")
                }
                logger$train <- c(logger$train, result$value)
                if (!is.null(env$eval.metric)) {
                     result <- env$metric$get(env$eval.metric)
                    if (nbatch != 0)
                        cat(paste0("Batch [", nbatch, "] Validation-", result$name, "=", result$value, "\n"))
                    logger$eval <- c(logger$eval, result$value)
                    iMin = which.min(logger$eval)
                    iAll = length(logger$eval)
                    if (iAll - iMin >= period / 2)
                        cat("*** Eval performance deteriorating\n")
                    if (iMin + period <= iAll) return(FALSE)
                }
          }
    }
    return(TRUE)
  }
}

set.seed(12345)
network <- get.lenet()
batch_size <- 16

# CSVIter is used here, since the data can't fit into memory
data_train <- mx.io.CSVIter(
  data.csv = file.path(workingPath, "local_train-64x64-data.csv"), data.shape = c(64, 64, 30),
  label.csv = file.path(workingPath, "local_train-stytole.csv"), label.shape = 600,
  batch.size = batch_size
)

data_test <- mx.io.CSVIter(
  data.csv = file.path(workingPath, "local_test-64x64-data.csv"), data.shape = c(64, 64, 30),
  label.csv = file.path(workingPath, "local_test-stytole.csv"), label.shape = 600,
  batch.size = batch_size
)

logger = mx.metric.logger()

mx.set.seed(0)
stytole_model <- mx.model.FeedForward.create(
    X = data_train,
    eval.data = data_test,
    ctx = mx.gpu(0),
    symbol = network,
    num.round = 5,
    learning.rate = 0.001,
    wd = 0.00001,
    momentum = 0.9,
    eval.metric = mx.metric.CRPS,
    epoch.end.callback = mx.callback.early.stop(8, paste0(workingPath, "/systole"), logger)
)

plot(1:length(logger$eval), logger$train, type = "l", col = "blue", main = "Systole Training Performance")
lines(1:length(logger$eval), logger$eval, type = "l", col = "red")
legend("topright", legend = c("train", "test"), lty=c(1,1), lwd=c(2.5,2.5), col = c("blue", "red"))

iBest = which.min(logger$eval)
print(paste0("Best iter = ", iBest, " scoring ", logger$eval[iBest]))

systole_model = mx.model.load(paste0(systole, iBest))

**Comment by colinpriest** [comment]
And the line systole_model = mx.model.load(paste0(paste0(workingPath, "/systole"), iBest)) is now giving me the error:

Error in eval(expr, envir, enclos): [04:42:06] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "/home/colin/data/Second-Annual-Data-Science-Bowl/working/systole5-symbol.json"

And that error is because that json file does not exist. But there is a similar file called systole-symbol.json in that path. If I make a copy of systole-symbol.json and call that copy systole5-symbole.json then I get a different error:

Error in eval(expr, envir, enclos): Parameter scalar is not presented

**Comment by thirdwing** [comment]
OK. That script is written by me. I will look into it.

**Comment by thirdwing** [comment]
@colinpriest Just found this is a very simple error. It seems our documents are not clear enough.

`mx.model.load` takes two parameters, one for prefix, one for iteration.

You are providing only one parameter by using `mx.model.load(paste0(paste0(workingPath, "/systole"), iBest))`.

Can you try `mx.model.load(prefix = paste0(workingPath, "/systole"), iteration = iBest)` ?

**Comment by colinpriest** [comment]
Sorry that code doesn't work for me. I get the following error:

Error in eval(expr, envir, enclos): Parameter scalar is not presented

**Comment by thirdwing** [comment]
close this right now. Feel free to reopen.
