### ISSUE TITLE
separate evaluation?

### ISSUE THREAD

**Issue by kingder** [dmlc/mxnet#1229]
I have a model saved by mxnet, I want use this modle to evaluate against a big dataset, how to do that use python? I know I can load model use mx.model.FeedForward.load(prefix, epoch, ...), then how to do next?
Thanks!

**Comment by piiswrong** [comment]
model = mx.model.FeedForward.load()
data = mx.io.your_data_iter
model.predict(data)

**Comment by kingder** [comment]
how to use custom metrics here? I wan't the same eval_metrics function passed to fit to calculate a metrics.

**Comment by piiswrong** [comment]
predict gives you the output. use metirc.update(output, label) and metric.get() to get the loss

**Comment by jonbakerfish** [comment]
Use the [`score`](http://mxnet.readthedocs.io/en/latest/packages/python/module.html#mxnet.module.base_module.BaseModule.score) function provided by `model.FeedForward`
