### ISSUE TITLE
[ScalaPackage] Looking for JNI c style suggestions

### ISSUE THREAD

**Issue by javelinjs** [dmlc/mxnet#1231]
We are developing Scala package, and trying to find out a C++ style for JNI codes (https://github.com/javelinjs/mxnet/blob/scala-package-l/scala-package/native/src/main/native/ml_dmlc_mxnet_native_c_api.cc)

As mentioned here, https://github.com/javelinjs/mxnet-scala/issues/6, we cannot simply use cpplint. Any suggestion for a suitable lint tool?

**Comment by tqchen** [comment]
The linter used by dmlc is customized in https://github.com/dmlc/dmlc-core/blob/master/scripts/lint.py

We can add a customized option to disable the warning(e.g. function name)

**Comment by javelinjs** [comment]
Thank you @tqchen ! I'll check it out.
