### ISSUE TITLE
[ScalaPackage] Symbol creation-API design

### ISSUE THREAD

**Issue by javelinjs** [dmlc/mxnet#1232]
I'm looking for suggestions for the way to create a symbol in scala-package (WIP). To take advantage of strong-typing, I exposed several ```create``` functions. To make it easy for users to write, I exposed ```createNoCheck``` and curried functions like ```FullyConnected```. See https://github.com/javelinjs/mxnet/blob/scala-package-l/scala-package/core/src/main/scala/ml/dmlc/mxnet/Symbol.scala and https://github.com/javelinjs/mxnet/blob/scala-package-l/scala-package/core/src/test/scala/ml/dmlc/mxnet/SymbolSuite.scala

I wonder whether it is a good design, e.g., will it be confusing when users find so many ways to create a symbol? Is ```kwargs: Map[String, Any]``` too flexible for ```createNoCheck``` (we will not even have a chance to tell what's going wrong when user passes illegal arguments) ? etc.

**Comment by javelinjs** [comment]
@tqchen

**Comment by tqchen** [comment]
I think the reflected functions like FullyConnected should be the recommended way of creating things. Let us keep others internal(which can be exposed when ready), and advocate one way that works for most users

**Comment by javelinjs** [comment]
https://github.com/dmlc/mxnet/pull/1592
