### ISSUE TITLE
Possible to specify argument num_epochs in R-package

### ISSUE THREAD

**Issue by kate-crosby** [dmlc/mxnet#1243]
Is it possible to specify the number of epochs with the R package in the model function? I know this is possible in python with num_epoch, but am unsure about this for the most recent R version.

```R
model <- mx.model.FeedForward.create(softmax, X=train.x, y=train.y,
                                     num.round=10,
                                     array.batch.size=128,
                                     learning.rate=2e-6, momentum=0.9,  
                                     eval.metric=mx.metric.accuracy,
                                     eval.data=list(data=val.x, label=val.y),
                                     initializer=mx.init.normal(0.1),
                                     epoch.end.callback=mx.callback.log.train.metric(10))
```

Thanks.

**Comment by freesouls** [comment]
@kate-crosby  I think ```num.round=10``` in your example codes is what you want

**Comment by kate-crosby** [comment]
@freesouls that is how I interpreted it - thanks for confirming. Would it be possible to keep argument naming both Python and R consistent?

**Comment by freesouls** [comment]
@kate-crosby at the very beginning python's argument is num-round, but later they change it to num-epoch, I guess they think num-epoch is more appropriate, while just forgetting to change the argument in R for consistency
