### ISSUE TITLE
Building error after setting USE_CUDNN=1, and USE_CUDA=1

### ISSUE THREAD

**Issue by katanaxu** [dmlc/mxnet#1245]
CPU compilation is successful. However, when compiling using GPU, the following errors occur.
--------------------------------
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_TORCH=0 -DMXNET_USE_NVRTC=0 -MM -MT build/src/resource.o src/resource.cc >build/src/resource.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_TORCH=0 -DMXNET_USE_NVRTC=0 -c src/resource.cc -o build/src/resource.o
In file included from ./mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:13,
                 from src/resource.cc:8:
./mshadow/mshadow/./base.h:145:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
Makefile:145: recipe for target 'build/src/resource.o' failed
make: *** [build/src/resource.o] Error 1

**Comment by piiswrong** [comment]
Where did you install cuda? did you set use_cuda_path?

**Comment by katanaxu** [comment]
thanks!
that was the issue.


On 1/12/2016 3:38 AM, Eric Junyuan Xie wrote:
>
> Where did you install cuda? did you set use_cuda_path?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dmlc/mxnet/issues/1245#issuecomment-170838552>.
>

-- 
felix-juefei-xu/phd-candidate/ece/cmu

**Comment by anxingle** [comment]
@piiswrong    sorry,I want to know how to set USE_CUDA_PATH .I install cuda in /usr/loca/cuda-7.5
