### ISSUE TITLE
stop on Distributed Training

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#1247]
When I try to test Distributed Training, my program seems like stop, Can you give me some hits?
../mxnet/tools/launch.py -n 2 -H hosts --sync-dir /tmp/mxnet python train_mnist.py --kv-store dist_sync
output and stop:
2016-01-12 16:53:34,701 INFO rsync /home/kevin/train/ -> 192.168.2.55:/tmp/mxnet
2016-01-12 16:53:34,850 INFO rsync /home/kevin/train/ -> 192.168.2.58:/tmp/mxnet

1 I run it on my server:192.168.2.51, 
2 mkdir ~/train and copy sync file just like: http://mxnet.readthedocs.org/en/latest/aws.html
3 my hosts file in ~/train is 
192.168.2.55
192.168.2.58 

4 and test ssh 3 server each other is ok 
5 I run192.168.2.55:/tmp/mxnet and 192.168.2.58:/tmp/mxnet on local is ok

**Comment by kandycs** [comment]
Hi Junran, 
I have the same issue as you reported. Have you resolved the problem ? and Can I ask how to resolve it ?

**Comment by 1TTT9** [comment]
same question +1,  any solution or magical function calls to stop it ?
