### ISSUE TITLE
How to finetune some specific layers of model converted from caffemodel

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#1248]
I am trying to reproduce the result of [Automatic Colorization](http://tinyclouds.org/colorize/).
I plan to finetune the net from vgg16 and have converted the vgg16 caffe model file and net file to mxnet format. Now the problem is I think if I want to change one layer's structure and finetune it, I must have a python file that defined the net structure which consist with the mxnet json format net file. How can I get the python file from json format net file?

**Comment by piiswrong** [comment]
under tools/caffe_converter there is a convert_symbol script. Use it to generate python script for creating the symbol.

**Comment by shuokay** [comment]
Generated successfully, thanks.
