### ISSUE TITLE
Running Adam optimizer error

### ISSUE THREAD

**Issue by rfarouni** [dmlc/mxnet#1253]
Hi,

When I change the optimizer to Adam. For example,
``` python
model = mx.model.FeedForward(
        ctx                = [mx.gpu(0)],
        num_epoch     = 60,
        symbol            = network,
        optimizer        =  'adam',
        initializer        = mx.init.Xavier(factor_type="in", magnitude=2.34))

model.fit(X= data_train)   
```
I get the following error message:

```python
  File "<ipython-input-6-3732cc3a7cd0>", line 2, in <module>
    X                  = data_train)
  File "/home/rick/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 641, in fit
    **(self.kwargs))
  File "/home/rick/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/optimizer.py", line 52, in create_optimizer
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'arg_names'
```
Isn't this the correct way of setting the optimizer?

**Comment by sxjscience** [comment]
Seems the `__init__` function of the Adam optimizer has no `arg_names` keyword.

Does the following revision help? In https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py#L348, add `arg_names = None` after `lr_schedule = None` and change https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py#L349 to `super(Adam, self).__init__(rescale_grad, arg_names)`

**Comment by rfarouni** [comment]
Now I get the following error instead:

```python
  File "<ipython-input-3-9b6e62614107>", line 2, in <module>
    X                  = data_train)
  File "/home/rick/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 641, in fit
    **(self.kwargs))
  File "/home/rick/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/optimizer.py", line 52, in create_optimizer
    **kwargs)
  File "/home/rick/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/optimizer.py", line 342, in __init__
    super(Adam, self).__init__(rescale_grad, arg_names)
TypeError: __init__() takes at most 2 arguments (3 given)
```

**Comment by sxjscience** [comment]
@rfarouni In my computer this revision solves the problem. Is it possible that you need to re-install the python package? Or update the rest part of MXNet to the latest version?

**Comment by darxriggs** [comment]
This is definitely an issue that should be fixed.

But you don't have to hotfix the mxnet code to use the Adam optimizer.
It's also possible to provide an optimizer object instead of a string:

```python
model = mx.model.FeedForward(
        ctx           = [mx.gpu(0)],
        num_epoch     = 60,
        symbol        = network,
        optimizer     = mx.optimizer.Adam(),
        initializer   = mx.init.Xavier(factor_type="in", magnitude=2.34))

model.fit(X=data_train)
```

**Comment by rfarouni** [comment]
After fixing the code and re-installing the python package, it worked. I think  I tried providing an  optimizer object but that didn't work.

**Comment by sxjscience** [comment]
@rfarouni I think it's worthwhile to make a pr for this issue. Would you like to pr?

**Comment by rfarouni** [comment]
I opened a pull request. Thanks
