### ISSUE TITLE
building error with torch

### ISSUE THREAD

**Issue by shuaitang** [dmlc/mxnet#1255]
There is no problem when I compile mxnet with USE_TORCH=0.

But when I set USE_TORCH=1, the problem turns out like this

~/torch/install/lib/libTH.so: undefined reference to `sgeqrf_'

~/torch/install/lib/libTH.so: undefined reference to `ssyev_'

~/torch/install/lib/libTH.so: undefined reference to `sgesvd_'

~/torch/install/lib/libTH.so: undefined reference to `dsyev_'

~/torch/install/lib/libTH.so: undefined reference to `dorgqr_'

~/torch/install/lib/libTH.so: undefined reference to `dpotri_'

~/torch/install/lib/libTH.so: undefined reference to `dgesv_'

~/torch/install/lib/libTH.so: undefined reference to `sgels_'

~/torch/install/lib/libTH.so: undefined reference to `dgels_'

~/torch/install/lib/libTH.so: undefined reference to `dtrtrs_'

~/torch/install/lib/libTH.so: undefined reference to `sorgqr_'

~/torch/install/lib/libTH.so: undefined reference to `spotrs_'

~/torch/install/lib/libTH.so: undefined reference to `dpstrf_'

~/torch/install/lib/libTH.so: undefined reference to `sgetri_'

~/torch/install/lib/libTH.so: undefined reference to `dpotrf_'

~/torch/install/lib/libTH.so: undefined reference to `dgetri_'

~/torch/install/lib/libTH.so: undefined reference to `sormqr_'

~/torch/install/lib/libTH.so: undefined reference to `dgeqrf_'

~/torch/install/lib/libTH.so: undefined reference to `strtrs_'

~/torch/install/lib/libTH.so: undefined reference to `dormqr_'

~/torch/install/lib/libTH.so: undefined reference to `dpotrs_'

~/torch/install/lib/libTH.so: undefined reference to `sgesv_'

~/torch/install/lib/libTH.so: undefined reference to `dgetrf_'

~/torch/install/lib/libTH.so: undefined reference to `dgeev_'

~/torch/install/lib/libTH.so: undefined reference to `sgetrf_'

~/torch/install/lib/libTH.so: undefined reference to `dgesvd_'

~/torch/install/lib/libTH.so: undefined reference to `spotrf_'

~/torch/install/lib/libTH.so: undefined reference to `spstrf_'

~torch/install/lib/libTH.so: undefined reference to `sgeev_'

~/torch/install/lib/libTH.so: undefined reference to `spotri_'

collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1

Is it caused by torch or mxnet?

Thank you

**Comment by antinucleon** [comment]
Repeat https://github.com/dmlc/mxnet/issues/1254
