### ISSUE TITLE
Why the name parameter in mxnet.symbol.SoftmaxOutput can only be set to 'softmax'

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#1263]
if I set ```symbol=mx.symbol.SoftmaxOutput(data=fc2, name='output')``` , get the error:
```
mxnet.base.MXNetError: [16:20:43] src/symbol/symbol.cc:121: Symbol.InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
        [0]data
        [1]convolution0_weight
        [2]convolution0_bias
        [3]convolution1_weight
        [4]convolution1_bias
        [5]fullyconnected0_weight
        [6]fullyconnected0_bias
        [7]fullyconnected1_weight
        [8]fullyconnected1_bias
        [9]output_label
```
this error can reproduced by setting ```name="output"```  in https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbol_inception-bn-28-small.py#L51

**Comment by tqchen** [comment]
Mainly because the default output label of DataIter  is softmax_label, we can either change the data label name, or change the label name provided by data

**Comment by shuokay** [comment]
@tqchen got it, thank you. Can you tell me the exact line that mxnet set the default output label? I have spend some time on it but did find out the exact line.

**Comment by piiswrong** [comment]
The only requirement is that the data/label name provided by your data iter matches the ones required by your network. You can change argument name in your network by making a Sym.Variable and pass it to softmax symbol

**Comment by shuokay** [comment]
@piiswrong thank you for your answer. According to your answer, I would like to ask:
1. I can get source code of ```mxnet.io.DataIter``` in mxnet/io.py, but can't find ```mxnet.io.ImageRecordIter```, can you tell me where is ```mxnet.io.ImageRecordIter```
2. Is the data iter in your answer means ```mxnet.io.ImageRecordIter``` in cifar10 example?
3. What is the relationship between ```mxnet.io.DataIter``` and ```mxnet.io.ImageRecordIter```?

**Comment by austingg** [comment]
ImageRecorderIter is implemented in C++.  you can reference src/io/iter_image_recordio.cc

**Comment by qigongsun** [comment]
softmax = mx.symbol.SoftmaxOutput(data = fc2, name = 'softmax')
