### ISSUE TITLE
Torch Normalize op returns incorrect results

### ISSUE THREAD

**Issue by lukemetz** [dmlc/mxnet#1267]
I was trying to pull torch's Normalize module as to not have to write my own L2Normalization and to test mxnet's torch suport. ReLU works fine, but Normalize doesn't appear to yielding seemingly random result.
My test code:
```python
import mxnet as mx
import numpy as np

data = mx.sym.Variable("data")
l2_feats = mx.symbol.TorchModule(data_0=data, lua_string="nn.Normalize(2)", num_data=1, num_params=0, num_outputs=1, name="l2normalize")

executor = l2_feats.simple_bind(data=(16, 16), ctx=mx.cpu())
executor.arg_arrays[0][:] = np.random.normal(size=(16,16))
i = executor.arg_arrays[0].asnumpy()
print np.min(i), np.max(i)

out = executor.forward()
o = executor.outputs[0].asnumpy()
print np.min(o), np.max(o)
```

On a cpu I get outputs of:
```
-3.01761 2.65684
0.0 0.0
```
On gpu I get seemingly garbage
```
-2.6326 2.93406
-69.4944 53.321
```
Any ideas? If I were to guess I would bet memory addresses are getting mixed up.

**Comment by piiswrong** [comment]
Do you mean torch op works on CPU but not GPU? Or did you compute cpu results manually.

**Comment by lukemetz** [comment]
Sorry. I am getting different (as in cpu returns 0's and gpu returns something nonzero ). Both of which are incorrect, or at least incorrect with my understanding of what Normalize should do. Both CPU and GPU appear to be broken but in different ways.

The min and max should be under 1 as this is a requirement of the L2 normalization.

**Comment by piiswrong** [comment]
I think I know why this happens: https://github.com/torch/nn/blob/master/Normalize.lua
we assume the output of a layer is stored in self.output, but normalize stores it in _output and output is just a view of it.
@mavenlin any ideas?

**Comment by piiswrong** [comment]
Should be fixed by https://github.com/dmlc/mxnet/pull/1270

**Comment by lukemetz** [comment]
Sweet thank you so much. Just tested and it produces the expected results.
