### ISSUE TITLE
Mxnet GPU on Ubuntu (Python) becomes irresponsive / goes into sleep mode

### ISSUE THREAD

**Issue by WDee** [dmlc/mxnet#1268]
I am trying to run Mxnet for the DBS Kaggle competition on an AWS EC2 G2x2 GPU instance (Ubuntu). 

The AWS instance had Nvidia drivers, CUDA and CUDAnn pre-installed. I subsequently re-installed to see whether it was a driver issue. 

I am encountering the following problem:
* Mxnet works for CPU setting, but not for the GPU setting.
* Mxnet gives the message INFO:root:Start training with [gpu(0)] - and then does not respond any more

I am new to Ubuntu, but ran the ps aux command - and saw that mxnet has gone into D mode

ubuntu    1765  0.0  0.8 1502308 133616 ?      D    19:43   0:01 python Traingpu.py

I am somewhat lost on how to resolve this issue, and why this occurs. i have tried to reinstall drivers, but to no avail. The script in question uses the mx.io.CSViter file - but i am not sure whether this is linked to the problem. What i did notice is that when i run the script while specifying an incorrect number of CPU units (e.g. 9 CPUs) i get the same behaviour. Mxnet goes into D / sleep mode, and cannot be killed.

Any help much appreciated, W

**Comment by piiswrong** [comment]
Can you run cuda sample code? Can you run x = mx.nd.ones((10,10), ctx=mx.gpu(0))?

**Comment by WDee** [comment]
Reinstalled everything (although without CudaNN - not installed yet - but don't think required for MxNet) and with code as per below. Gave me different error (see below)- but at the least the script was not hanging this time around. This might be completely unrelated error - and one that might be related to potentially an error in the installation of a BLAS library? 

git clone --recursive https://github.com/dmlc/mxnet
cd mxnet; cp make/config.mk .
echo "USE_CUDA=1" >>config.mk
echo "USE_CUDA_PATH=/usr/local/cuda" >>config.mk
echo "USE_BLAS=atlas" >> config.mk
echo "USE_DIST_KVSTORE = 1" >>config.mk
make -j8

Subsequently ran the script as per above (see below)

import find_mxnet
import mxnet as mx
x = mx.nd.ones((10,10), ctx=mx.gpu(0))
print(x)
print("done")

The output looked like this:

ubuntu@ip-172-31-4-241:~$ python testgpu.py
libdc1394 error: Failed to initialize libdc1394
OpenCV is unavailable.
<mxnet.ndarray.NDArray object at 0x7eff803d1610>
done
[18:11:15] ./dmlc-core/include/dmlc/logging.h[18:11:15] ./dmlc-core/include/dmlc/logging.h:215: [18:11:15] ./mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
:215: [18:11:15] ./mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
terminate called recursively
terminate called after throwing an instance of 'dmlc::Error'
Aborted (core dumped)

let me know any help

**Comment by phunterlau** [comment]
Can you show the AMI ID of your AWS? And, libdc1394 error is just a trivial one, and one can disable it by `sudo ln /dev/null /dev/raw1394` If you want to set up your new AMI from scratch, please follow my recent blog https://no2147483647.wordpress.com/2016/01/16/setup-amazon-aws-gpu-instance-with-mxnet/

**Comment by WDee** [comment]
that is good to know. the remainder of the code works fine - so will just disable libdc1394. for what it is worth - I had previously used ami-55deaf30 (which supposed to have caffe and cuda installed, but i had trouble getting this AMI to run with Mxnet). Did a clean reinstallation, and now everything is working well

**Comment by WDee** [comment]
one thing that you might want to add to your blog is that folks might want to make their AWS persistent (if they use spot instances). Secondly, they might have to add an additional EBS Volume to store the data. My instance was not big enough in base storage capacity to accomodate the files. If helpful - i am happy to send the code / instructions on how to attach / mount an EBS drive.

**Comment by phunterlau** [comment]
@WDee please send the github link to your code and I will update the blog (with special thanks and link to your github)

**Comment by WDee** [comment]
@phunterlau. I unfortunately don't have a github account yet (somewhat new to this field) - but maybe the text and code per below is helpful for copy and paste:

Some AWS instances might not have sufficient EBS or Instance memory to download and manipulate all the data. In that case, one could choose to launch a seperate EBS volume and attach this to your instance. The instructions below show how to do this: 

* Go in your EC2 management console to the Volumes tab in the Elastic Block Store (this should show in the dashboard on the left side of your screen as well)

* Press create volume and select and launch an EBS volume with sufficient size (e.g. 150GB)

* Attach this volume to your Instance

* Now log in to your instance (e.g. with Putty) to insert the next commands on the command line / bash: 

* The command "lsblk" should show you the volumes linked to your instance. your new drive should appear - but is potentially not attached to your instance

* To mount this drive you want the following the excellent instructions on http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html 

* For the purpose of this tutoral - you want to move the new drive on the directory data (assuming that this data does not exist yet and has no data in it (or put differently, that you are not overriding any existing data that you want to keep)
