### ISSUE TITLE
save training/test error during training in python

### ISSUE THREAD

**Issue by Gelu74** [dmlc/mxnet#1274]
My question is the same as https://github.com/dmlc/mxnet/issues/511 but to do it in python
I have tried
batch_end_callback = mx.callback.log.train.metric(5, err),
but I get the error
AttributeError: 'module' object has no attribute 'log'

In python, how can I save,  during training, the metrics so I can later plot training curves?

**Comment by sodabeta7** [comment]
it should be ``mx.callback.log_train_metric(5)`` in python.

**Comment by Gelu74** [comment]
Thankx
