### ISSUE TITLE
How to generate the image list for prediction?

### ISSUE THREAD

**Issue by paipai880429** [dmlc/mxnet#1284]
@tqchen The python tutorial has already showed us the way to generate the image list for training and validation images following the structure ``` integer_image_index \t label_index \t path_to_image
```. But it does not tell us the structure of image list for prediction purpose. What should we do for the ```label_index``` since we do not know?

**Comment by Gelu74** [comment]
65021   0       data/test/124622.jpg
12548   0       data/test/102436.jpg
123843  0       data/test/63243.jpg
74125   0       data/test/27629.jpg
62736   0       data/test/52015.jpg
82539   0       data/test/125052.jpg
62710   0       data/test/131116.jpg
80730   0       data/test/155461.jpg
92020   0       data/test/122485.jpg
34672   0       data/test/38935.jpg

**Comment by paipai880429** [comment]
@Gelu74  Are you sure?

**Comment by Gelu74** [comment]
Works for me and look at:
https://github.com/dmlc/mxnet/blob/master/example/kaggle-ndsb1/gen_img_list.py

**Comment by paipai880429** [comment]
@Gelu74 Thank you for you reply. After I generate the ```test.lst``` and ```test.rec``` following this method. I would like to load my previously trained model to predict the labels for these testing data. 

```
model = mx.model.FeedForward.load(...)
test_dataiter = mx.io.ImageRecordIter(
    path_imgrec = args.data_dir + "test.rec",
    mean_r      = 121.75,
    mean_g      = 122.54,
    mean_b      = 122.51,
    rand_crop   = False,
    rand_mirror = False,
    data_shape  = data_shape,
    batch_size  = args.batch_size,
    )

pred = model.predict(test_dataiter)
print pred
```
I am expecting that ```pred``` is a list of predicted labels showed on the screen. However, my program get stuck. 
![image](https://cloud.githubusercontent.com/assets/3724085/12377620/91507a00-bd5e-11e5-848f-39c8f78e78e4.png)

**Comment by Gelu74** [comment]
Well, I guess it depends on your network configuration but usually predict would return a vector of probabilities for each image giving the probability of belonging to each class.
For how long does it get stuck? if your test dataset is large and you are not using a gpu, prediction could take long... try with a reduced test set with very few examples.
you might want to look at the kaggle data science bowl example, I have made a pull request to incorporate prediction, you can have a look at the code at:
https://github.com/Gelu74/mxnet/tree/master/example/kaggle-ndsb1

**Comment by paipai880429** [comment]
@Gelu74 That's great! Thanks for providing this "new version" of ndsb1. Actually I attended this competition last year after learning the CNN for 1month. I only got 191th, using Lasagne. One more question, do you have any idea how to automatically compute the ```mean_image``` or ```mean_rgb```?

**Comment by Gelu74** [comment]
I am actually a marine biologist with interests in image classification for thing very similar to ndsb1, a newbie to deep learning. 191th is not bad, any insights you would share?
As for the mean_image, if you specify:
    train = mx.io.ImageRecordIter(                                                     |
        path_imgrec = args.data_dir + "train.rec",                                     |
        mean_img    = args.data_dir + "mean.bin",  ...
and there is no such file, mxnet will automatically generate the mean image for you, look at the cifar10 example.

**Comment by paipai880429** [comment]
@Gelu74 Thank god! You have make things clear for me. I actually read through the cifar10 when I was using mxnet for the first time. I was being wondered where the "mean.bin" came from and how to generate it from a image list. It turns out that it will be compute automatically. And Gelu, the document says the ```mean_img``` or ```mean_rgb``` are augmentation parameters. But, as far as I understand, they are used for normalized purposes so that the optimization process would be easier. What's your thought ?

![image](https://cloud.githubusercontent.com/assets/3724085/12381722/b6681f8e-bdca-11e5-8e28-7234f3987a18.png)

**Comment by Gelu74** [comment]
I would say that it is a parameter to the augmentation since it can be substracted to each augmented image and hence it should be passed as a parameter to the augmentation function. But I do know nothing about the insides of mxnet.
This is now unrelated to your original issue, you might get better amswer if you close this one and open a new issue.

**Comment by paipai880429** [comment]
@Gelu74 Thank you Gelu74. I have learned a lot from you !
