### ISSUE TITLE
Fails to make on CentOS

### ISSUE THREAD

**Issue by peterzcc** [dmlc/mxnet#1285]
The output looks like the text below, should I replace all the "-std=c++0x" to "-std=c++11" ?

g++4 -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I./ps-lite/include -I/csproject/dygroup2/czeng/venv/downloads/mxnet/deps/include -DMXNET_USE_NVRTC=0 -MM -MT build/src/resource.o src/resource.cc >build/src/resource.d
g++4 -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I./ps-lite/include -I/csproject/dygroup2/czeng/venv/downloads/mxnet/deps/include -DMXNET_USE_NVRTC=0 -MM -MT build/src/c_api/c_api.o src/c_api/c_api.cc >build/src/c_api/c_api.d
g++4 -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I./ps-lite/include -I/csproject/dygroup2/czeng/venv/downloads/mxnet/deps/include -DMXNET_USE_NVRTC=0 -MM -MT build/src/c_api/c_api_error.o src/c_api/c_api_error.cc >build/src/c_api/c_api_error.d
g++4 -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I./ps-lite/include -I/csproject/dygroup2/czeng/venv/downloads/mxnet/deps/include -DMXNET_USE_NVRTC=0 -MM -MT build/src/c_api/c_predict_api.o src/c_api/c_predict_api.cc >build/src/c_api/c_predict_api.d
g++4 -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I./ps-lite/include -I/csproject/dygroup2/czeng/venv/downloads/mxnet/deps/include -DMXNET_USE_NVRTC=0 -c src/c_api/c_api_error.cc -o build/src/c_api/c_api_error.o
g++4 -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I./ps-lite/include -I/csproject/dygroup2/czeng/venv/downloads/mxnet/deps/include -DMXNET_USE_NVRTC=0 -c src/resource.cc -o build/src/resource.o
g++4 -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I./ps-lite/include -I/csproject/dygroup2/czeng/venv/downloads/mxnet/deps/include -DMXNET_USE_NVRTC=0 -c src/c_api/c_api.cc -o build/src/c_api/c_api.o
g++4 -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=0 -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_DIST_KVSTORE -I./ps-lite/include -I/csproject/dygroup2/czeng/venv/downloads/mxnet/deps/include -DMXNET_USE_NVRTC=0 -c src/c_api/c_predict_api.cc -o build/src/c_api/c_predict_api.o
In file included from /usr/local/include/cuda_runtime.h:79:0,
                 from /usr/local/include/curand.h:59,
                 from ./mshadow/mshadow/./base.h:147,
                 from ./mshadow/mshadow/tensor.h:16,
                 from include/mxnet/base.h:13,
                 from src/resource.cc:8:
/usr/local/include/vector_functions.h:174:32: fatal error: vector_functions.hpp: No such file or directory
 #include "vector_functions.hpp"
                                ^
compilation terminated.
make: *** [build/src/resource.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /usr/local/include/cuda_runtime.h:79:0,
                 from /usr/local/include/curand.h:59,
                 from ./mshadow/mshadow/./base.h:147,
                 from ./mshadow/mshadow/tensor.h:16,
                 from include/mxnet/base.h:13,
                 from src/c_api/c_api.cc:11:
/usr/local/include/vector_functions.h:174:32: fatal error: vector_functions.hpp: No such file or directory
 #include "vector_functions.hpp"
                                ^
compilation terminated.
make: *** [build/src/c_api/c_api.o] Error 1
In file included from /usr/local/include/cuda_runtime.h:79:0,
                 from /usr/local/include/curand.h:59,
                 from ./mshadow/mshadow/./base.h:147,
                 from ./mshadow/mshadow/tensor.h:16,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/symbolic.h:17,
                 from src/c_api/c_predict_api.cc:9:
/usr/local/include/vector_functions.h:174:32: fatal error: vector_functions.hpp: No such file or directory
 #include "vector_functions.hpp"
                                ^
compilation terminated.
make: *** [build/src/c_api/c_predict_api.o] Error 1

**Comment by qiaohaijun** [comment]
I am using centos(6 and 7)
on centos 7, g++ is 4.8+
and on centos 6 I use devtoolset-3

**Comment by peterzcc** [comment]
@qiaohaijun 
Hi Haijun,

Thanks for your comment! I was using centos 6.7 and g++ 4.9.2. The devtoolset-3 is not installed and I don't have the root access to install it. I think I still need to figure out a way to fix it. Did you try g++ on centos 6 before?

**Comment by peterzcc** [comment]
It didn't help when I changed all the -std=c++0x to -std=c++11. Still the same Error.
Still can't figure out the problem. One reason might be that I didn't use the default g++, which was only g++4.4.7.

**Comment by thirdwing** [comment]
The compiler can't find `vector_functions.hpp`, which is part of cuda. This is the real reason.

**Comment by peterzcc** [comment]
Hi Qiang,

Thanks for your suggestions! Setting the cuda path solves the problem. 

Best regards,
Peter, Zeng Cancheng

**Comment by SevenGong** [comment]
@peterzcc    I have the same problems. Can you tell me how you set the cuda path?  
Thank you very much!
