### ISSUE TITLE
Compile errors on power processor

### ISSUE THREAD

**Issue by amithr1** [dmlc/mxnet#1289]
Hello all,

I am trying to compile mxnet on a power processor. Since it is not an intel, I get errors
of the form,

./mshadow/mshadow/././././extension/../packet/sse-inl.h:10:23: fatal error: emmintrin.h: No such file or directory

Is there any way to disable the sse inlines and use generic routines?

thank you
amithr

**Comment by tqchen** [comment]
You can disable sse by define the macro https://github.com/dmlc/mshadow/blob/master/mshadow/base.h#L121 to 0

Add it to ADD_CFLAGS in config.mk

**Comment by amithr1** [comment]
thanks..this works. Looks like I have an issue with numpy. The numpy installed is the python-numpy..I guess we would need python2.7-numpy. I may not get this package updated due to other constraints. 
I would want to use GPUs..is numpy required for running on GPUs? I have all other GPU packages including cuDNN..can I comment out the import numpy ?

**Comment by piiswrong** [comment]
numpy is required for python interface. If you doesn't have numpy, try R interface or C++ interface.

**Comment by amithr1** [comment]
I was able to get the python numpy installed
it runs on GPUs now. thanks for the pointers. 

However on the cpus, I get the following errors
2016-01-20 15:53:50,363 Node[0] Start training with [cpu(0)]
[15:53:50] ./dmlc-core/include/dmlc/logging.h:215: [15:53:50] ./mshadow/mshadow/./././dot_engine-inl.h:39: Not implmented!
[15:53:50] ./dmlc-core/include/dmlc/logging.h:215: [15:53:50] src/engine/./threaded_engine.h:295: [15:53:50] ./mshadow/mshadow/./././dot_engine-inl.h:39: Not implmented!
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [15:53:50] src/engine/./threaded_engine.h:295: [15:53:50] ./mshadow/mshadow/./././dot_engine-inl.h:39: Not implmented!
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted

**Comment by tqchen** [comment]
You will need to link a version of blas
