### ISSUE TITLE
Torch error: 'module' object has no attribute 'randn'

### ISSUE THREAD

**Issue by xgastaldi** [dmlc/mxnet#1293]
Hi everyone,

When I build with Torch I get the following error when I try to run x = mx.th.randn(2, 2, ctx=mx.cpu(0)):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'randn'

Any idea how to solve this?

**Comment by piiswrong** [comment]
You probably didn't build torch module correctly

**Comment by xgastaldi** [comment]
Unfortunately, the problem does not come from there. I can train networks with Torch without any particular problem.

**Comment by piiswrong** [comment]
What does dir(mx.th) and dir(mx.nd) show？

**Comment by xgastaldi** [comment]
>>> dir(mx.th)
['FunctionHandle', 'NDArray', 'NDArrayHandle', '_LIB', '_LUAJIT', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_init_torch_module', '_make_torch_function', '_new_empty_handle', 'absolute_import', 'c_array', 'check_call', 'ctypes', 'ctypes2docstring', 'mx_float', 'mx_uint', 'py_str', 'sys']
>>> dir(mx.nd)
['Context', 'FunctionHandle', 'NDArray', 'NDArrayHandle', '_DTYPE_MX_TO_NP', '_DTYPE_NP_TO_MX', '_LIB', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '_init_ndarray_module', '_make_ndarray_function', '_new_alloc_handle', '_new_empty_handle', 'abs', 'absolute_import', 'argmax_channel', 'array', 'c_array', 'c_str', 'ceil', 'check_call', 'choose_element_0index', 'clip', 'cos', 'ctypes', 'ctypes2buffer', 'ctypes2docstring', 'dot', 'empty', 'exp', 'floor', 'load', 'log', 'max', 'min', 'mx_float', 'mx_real_t', 'mx_uint', 'norm', 'np', 'numeric_types', 'onehot_encode', 'ones', 'py_str', 'round', 'rsqrt', 'save', 'sign', 'sin', 'sqrt', 'square', 'string_types', 'sum', 'sys', 'waitall', 'warnings', 'zeros']

**Comment by piiswrong** [comment]
Could you check if code in plugin/torch/torch_function.cc compiled? For example add an extra ) and see if it breaks build.
Also, what does dir(mx.nd.NDArray) show?

**Comment by xgastaldi** [comment]
The build is not broken by the addition of a bracket:
"namespace mxnet {(" instead of "namespace mxnet {" in plugin/torch/torch_function.cc

dir(mx.nd.NDArray)
['__add__', '__class__', '__del__', '__delattr__', '__dict__', '__div__', '__doc__', '__format__', '__getattribute__', '__getitem__', '__getstate__', '__hash__', '__iadd__', '__idiv__', '__imul__', '__init__', '__isub__', '__module__', '__mul__', '__neg__', '__new__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__rsub__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '_copyto', '_div', '_div_scalar', '_minus', '_minus_scalar', '_mul', '_mul_scalar', '_onehot_encode', '_plus', '_plus_scalar', '_random_gaussian', '_random_uniform', '_rdiv_scalar', '_rminus_scalar', '_set_value', '_slice', '_sync_copyfrom', 'asnumpy', 'asscalar', 'astype', 'context', 'copyto', 'dtype', 'shape', 'size', 'wait_to_read']

**Comment by piiswrong** [comment]
Looks like it's not compiled. Could you verify that torch_module.cc is compiled? I would suggest doing the following:
1) make clean_all and recompile
2) if it doesn't help, git clone a fresh repo from master and recompile.
3) If still not working, add `TORCH_SRC += plugin/torch/torch_function.cc` after `TORCH_SRC = $(wildcard plugin/torch/*.cc)` in plugin/torch/torch.mk.

**Comment by xgastaldi** [comment]
Unfortunately none of these options work.
After 3) I tried adding a bracket back in torch_function.cc but it still compiles without error

**Comment by piiswrong** [comment]
This is very strange. Did you verify that torch_module.cc actually compiled?

**Comment by xgastaldi** [comment]
I added a bracket in torch_module.cc, ran make clean_all and make -j8 and mxnet still compiles correctly

**Comment by piiswrong** [comment]
Are you sure you can use mx.symbol.TorchModule? Looks like the plugin is not activated at all. What's your config.mk setting?

**Comment by xgastaldi** [comment]
USE_CUDA=1
USE_CUDA_PATH=/usr/local/cuda
USE_CUDNN=1
USE_BLAS=atlas
USE_DIST_KVSTORE = 1
USE_S3=1
USE_TORCH = 1
TORCH_PATH = /home/ubuntu/torch

**Comment by piiswrong** [comment]
It's stale. Check make/config.mk and update. We are using MXNET_PLUGINS flag instead of USE_TORCH now.

**Comment by piiswrong** [comment]
Ok. I think this confusion is caused by out dated tutorial. I'm going to update it.

**Comment by xgastaldi** [comment]
Thanks. I now have another error when I compile:
#########
In file included from plugin/torch/./torch_base.h:21:0,
                 from plugin/torch/torch_base.cc:7:
/home/ubuntu/torch/install/include/THC/THCStorage.h:4:23: fatal error: THStorage.h: No such file or directory
 #include "THStorage.h"
##########

When I look at /home/ubuntu/torch/install/include/THC/ I see the following files:
ubuntu:~/torch/install/include/THC$ ls
generic         THCDeviceTensor.cuh           THCDeviceUtils.cuh     THCReduceAll.cuh         THCStorage.h     THCTensorMath.h
THCAllocator.h  THCDeviceTensor-inl.cuh       THCGeneral.h           THCReduceApplyUtils.cuh  THCTensorConv.h  THCTensorRandom.h
THCApply.cuh    THCDeviceTensorUtils.cuh      THCGenerateAllTypes.h  THCReduce.cuh            THCTensorCopy.h  THCTensorSort.h
THCBlas.h       THCDeviceTensorUtils-inl.cuh  THC.h                  THCStorageCopy.h         THCTensor.h

**Comment by piiswrong** [comment]
Try adding `-I$(TORCH_PATH)/install/include/TH -I$(TORCH_PATH)/install/include/THC` to ADD_CFLAGS in config.mk

**Comment by xgastaldi** [comment]
Yes! It works now :)

**Comment by xgastaldi** [comment]
Thanks a lot for your help!

**Comment by ruotianluo** [comment]
I met similar problem as above mentioned. However, the two CFLAGS have been added, and from my compiling command, the two directories are included. And I'm sure THStorage.h is in ~/rluo/torch/install/include/TH.

Here is the error information.
`g++ -std=c++11 -DMSHADOW_FORCE_STREAM -Wall -O3 -I/share/data/vision-greg/rluo/mxnet/mshadow/ -I/share/data/vision-greg/rluo/mxnet/dmlc-core/include -fPIC -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -msse3 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -I~/rluo/caffe/include -I~/rluo/caffe/build/src -I~/rluo/torch/install/include **-I~/rluo/torch/install/include/TH** -I~/rluo/torch/install/include/THC/ -DMXNET_USE_TORCH=1 -DMXNET_USE_NVRTC=0 -MM -MT build/plugin/torch/torch_base.o plugin/torch/torch_base.cc >build/plugin/torch/torch_base.d
In file included from plugin/torch/./torch_base.h:21:0,
                 from plugin/torch/torch_base.cc:7:
/share/data/vision-greg/rluo/torch/install/include/THC/THCStorage.h:4:23: fatal error: THStorage.h: No such file or directory
 #include "THStorage.h"
                       ^
compilation terminated.`

And files in ~/rluo/torch/install/include/TH:
`ls ~/rluo/torch/install/include/TH
generic        THDiskFile.h     THGenerateAllTypes.h    THLapack.h      THRandom.h          THTensor.h
THAllocator.h  THFile.h         THGenerateFloatTypes.h  THLogAdd.h      THStorage.h         THTensorMacros.h
THAtomic.h     THFilePrivate.h  THGenerateIntTypes.h    THMath.h        THTensorApply.h     THVector.h
THBlas.h       THGeneral.h      TH.h                    THMemoryFile.h  THTensorDimApply.h`
