### ISSUE TITLE
MXNet learning notes in chinese

### ISSUE THREAD

**Issue by zhubuntu** [dmlc/mxnet#1298]
最近在学习MXNet在C++下编程，发现可以用的资料很少，所以想做一个学习笔记项目，大家一起共同学习进步，项目地址在
https://github.com/zhubuntu/MXNet-Learning-Note

已经完成的内容有相关c++的配置和编写CNN网络及中间层输出结果，水平比较有限，所以可能感觉看起来很乱或者有错误，不过希望能给刚来的人一些帮助。
我用的md编辑器是haroopad，不知道为什么会出现换行问题，在电脑上看着好好的（windows），传上来就会换行出错。

不知道这种东西发在issue里算不算违规，刚开始用github，如果违反了相关规定管理员可以直接删啦，没关系的。

**Comment by qiaohaijun** [comment]
good idea, I make a pr

**Comment by cupermanrose** [comment]
I'm writing a lstm c++ sample.Could you manage your doc?I felt a little confused when I was reading.

**Comment by zhubuntu** [comment]
@cupermanrose Where are you confused with? This is my qq number:876814711,we can talk on QQ.

**Comment by tqchen** [comment]
You are welcomed to open a PR and add the link to https://github.com/dmlc/mxnet/tree/master/example#mxnet-examples-and-resources

**Comment by zhubuntu** [comment]
@qiaohaijun Can you make a PR as @tqchen said.The computer in my home can't install the github desktop so I can't make a pr.And I'll go back to school until 20 days later.Thank you very much.
