### ISSUE TITLE
How can I write a custom loss function with python API?

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#1300]
Can current python API do this? if so, is there any tutorial about this?

**Comment by vladfi1** [comment]
What was the solution? I too would like to write a custom loss function.

**Comment by RishabGargeya** [comment]
@vladfi1 I think you may have to create a new layer http://mxnet.readthedocs.org/en/latest/tutorial/new_op_howto.html?highlight=novel%20loss

**Comment by yuantangliang** [comment]
the link is  broken. @RishabGargeya @wangg12  can you tell me how to do this ? I also need to write custom loss function.

**Comment by YuHuangjie** [comment]
This maybe helpful.
http://mxnet.io/how_to/new_op.html

**Comment by salemmohammed** [comment]
@vladfi1 Have you implemented  loss function ? I am trying to do so but I need some suggestions
