### ISSUE TITLE
Draw Validation Curves

### ISSUE THREAD

**Issue by WDee** [dmlc/mxnet#1302]
(I am new to github and might be asking this question in the wrong forum / place. the original post was closed. Please give me feedback on appropriate posting) 

I am trying, for the kaggle competition, to draw the error curves (error on y-axis, epochs on the x-axis) to understand where the model might be under- / over-fitting.

I saw the closed post on https://github.com/dmlc/mxnet/issues/511 - but had some challenges in getting the code to run:

* This is probably a noob question - but the fact that there are a number of commits, and the issue has been closed out, does this mean that the validation curve feature is now part of the regular mxnet code? 
* I tried to run the example code - but got an error message saying that keyword can't be an expression (with regards to ctx=mx.cpu())

Any help and general feedback much appreciated

W

**Comment by thirdwing** [comment]
Hi, can you give us more info?

(1) Are you using R or python or Julia?

(2) The code you have run and the error message.

(3) The R `sessioninfo()`

**Comment by WDee** [comment]
Sorry. stupid mistake. i just realized that i was copying in R code in python. sorry. i come from a R background, and just in a hazy state of mind didnt realize my mistake. stupid mistake. is there a python example as well? Saw this https://github.com/dmlc/mxnet/blob/master/python/mxnet/callback.py but let me know if I should look somewhere else.

**Comment by thirdwing** [comment]
Have you checked #1274 ?

**Comment by WDee** [comment]
Thanks for this link. I adjusted the train.py kaggle script by inserting / editing the following lines: 

log_sys = mx.metric_logger.new()
stytole_model.fit(X=data_train, eval_metric = mx.metric.np(CRPS),batch.end.callback = mx.callback.log_train_metric(2, log_sys))

log_dia = mx.metric_logger.new()
diastole_model.fit(X=data_train, eval_metric = mx.metric.np(CRPS),batch.end.callback = mx.callback.log_train_metric(2, log_dia))

However, this stil gives me the following error: 

ubuntu@ip-172-31-4-241:~$ python train.py
  File "train.py", line 103
    stytole_model.fit(X=data_train, eval_metric = mx.metric.np(CRPS),batch.end.callback = mx.callback.log_train_metric(2, log_s                                     ys))
SyntaxError: keyword can't be an expression

I might have made an error with .vs. _? Any thoughts much appreciated

**Comment by WDee** [comment]
i think i know what i did wrong - changed the code to 

stytole_model.fit(X=data_train, eval_metric = mx.metric.np(CRPS),batch_end_callback = mx.callback.log_train_metric(32))

Currently looking at / trying to figure out how i can subsequently access the metrics for further analysis. Playing with this as we speak.

**Comment by antinucleon** [comment]
Here is how I draw curves by parsing log:
http://webdocs.cs.ualberta.ca/~bx3/mxnet/cifar-100.html

**Comment by WDee** [comment]
@antinucleon . that is super helpful. and do i understand correctly that you use the tee command (e.g. " python train.py | tee relu") to write the system output to the elu, relu, etc. files?

**Comment by antinucleon** [comment]
```python train.py 2>relu```

**Comment by WDee** [comment]
Thanks so much. i will customize this code for the kaggle competition and post on the forum

**Comment by antinucleon** [comment]
Thanks!

**Comment by ZhaoxiaZhang** [comment]
@antinucleon HI, I met a problem about how to save the training and validation accuracy and plot them. I  found your discussion. Unfortunately, I can't open your link http://webdocs.cs.ualberta.ca/~bx3/mxnet/cifar-100.html. Would you kindly help me how to do this?

**Comment by edmBernard** [comment]
an old thread, there is two solution now : 
1. parsing log as proposed here, with a script like that : 
```python
import argparse
import re

import matplotlib.pyplot as plt
import numpy as np


def main():
    plt.style.use('seaborn-whitegrid')
    parser = argparse.ArgumentParser()
    parser.add_argument("--file", help="log file", required=True)
    clo = parser.parse_args()

    res_train = []
    res_test = []
    with open(clo.file, 'r') as f:
        for line in f:
            match = re.search(r"mAP ([a-z]+).*:[\W]*([0-9\.]+)", line)
            if match:
                if match.group(1) == "train":
                    res_train += [float(match.group(2))]
                elif match.group(1) == "test":
                    res_test += [float(match.group(2))]

    fig, ax = plt.subplots()
    ax.plot(res_train, label="Train")
    ax.plot(res_test, label="Test")
    ax.set_xlabel("Iteration")
    ax.set_ylabel("mAP")
    ax.set_title("Accuracy")
    ax.set_ylim([0, 1])
    ax.set_xlim([0, len(res_train)])
    ax.legend(loc=4)
    plt.show()

if __name__ == '__main__':
    main()
```
The matching line have this form : 
`mAP train : 0.9876543` or `mAP test : 0.9876543`

2. the second method you can use tensorboard : https://github.com/dmlc/tensorboard

**Comment by ZhaoxiaZhang** [comment]
@edmBernard , thanks for that.  Just a quick question, based on my understanding, solution 1 is mainly for parsing and plotting the log. 
Before that, need we save the log into somewhere first? Is there any setup we need to do in mxnet like set the save-path , save-name and so on.

**Comment by edmBernard** [comment]
@ZhaoxiaZhang 
If mxnet print accuracy in console you can do something like `python train.py >> logfile.log` 
otherwise you need to add `print` in metric function.

**Comment by ZhaoxiaZhang** [comment]
@edmBernard OK. Let me have a try.

**Comment by ZhaoxiaZhang** [comment]
@edmBernard Sorry for bothering you again. I typed the similar command in my cmd as  python test2.py >>logfile.log I saw the log file generated. However, the traing information appears in my cmd window. The log file only saves other information like print output.
Is there something wrong with my operation?

**Comment by edmBernard** [comment]
that mean your code use a python logger. 
not sure if it will work but can you try : `python train.py >> logfile.log 2>&1`

**Comment by ZhaoxiaZhang** [comment]
@edmBernard It works! Amazing. Thanks again.

**Comment by jrosebr1** [comment]
If anyone else is interested I put together a tutorial on how to parse and plot mxnet logs, including training and validation loss, accuracy, top-k accuracy, etc.:

https://www.pyimagesearch.com/2017/12/25/plot-accuracy-loss-mxnet/

I hope it helps anyone who is looking to plot their logs.

**Comment by edmBernard** [comment]
I think tensorboard is more complete solution and was not so hard to use.
It allow to monitor accuracy and lots of other parameters like gradient etc ...
And it keep track of previous training without more work

**Comment by jrosebr1** [comment]
Can TensorBoard be used to plot mxnet loss and accuracy? I wasn't aware of this.

**Comment by edmBernard** [comment]
Yes
the standalone tensorboard maintained by dmlc: https://github.com/dmlc/tensorboard
documentation on python API with a mxnet example: https://github.com/dmlc/tensorboard/tree/master/python

**Comment by jrosebr1** [comment]
Thanks!

**Comment by edmBernard** [comment]
@jrosebr1 here a complete example (not mine) to log accuracy and gradient in tensorboard from mxnet and using Gluon. https://gist.github.com/skirdey/8b9bd6cc20e958bc57e76004410f17ff
