### ISSUE TITLE
Something Wrong with the fit and predict method

### ISSUE THREAD

**Issue by LiamZhuuu** [dmlc/mxnet#1304]
I am trying to do the fine tuning based on the [**Inception BN**](https://github.com/dmlc/mxnet-model-gallery/blob/master/imagenet-1k-inception-bn.md) model.
But I find that even given the same data iterator, the training an evaluation accuracy differs a lot, while the evaluation accuracy is always 1/#class, which means the model produces replicate results for different data.

I also tried to modify
```
self._pred_exec.forward(is_train=False)
```
to
```
self._pred_exec.forward(is_train=True)
```
in model.py
It works for NDArrayIter but not ImageRecordArray

**Comment by winstywang** [comment]
Looking into it. Possible bugs introduced in recent PRs

**Comment by sodabeta7** [comment]
Try to modify the value of ``fix_gamma`` in BatchNorm from defaulted ‘’True‘’ to ''False'', since the default value is changed in recent commits.
