### ISSUE TITLE
how to use Dropout?

### ISSUE THREAD

**Issue by ppaanngggg** [dmlc/mxnet#1305]
I use Dropout like this way. It seems not work... Any sample for Dropout?

In [2]: x_now = mx.sym.Variable('x_now')

In [3]: h_now = mx.sym
mx.sym     mx.symbol

In [3]: h_now = mx.sym.Dropout(data = x_now, p=0.5)

In [4]: x_now_value = mx.nd.one
mx.nd.onehot_encode  mx.nd.ones

In [4]: x_now_value = mx.nd.ones((5,10))

In [5]: x_now
x_now        x_now_value

In [5]: x_now_value.asnumpy()
Out[5]:
array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [6]: executor = h_now.bind(ctx = mx.cpu(), args={'x_now':x_now_value})

In [7]: executor.forward()

In [8]: executor.outputs[0].asnumpy()
Out[8]:
array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

**Comment by piiswrong** [comment]
you need exe.forward(is_train=True).
Dropout is only activated in training.

**Comment by ppaanngggg** [comment]
thank you :)

**Comment by liangfu** [comment]
Dropout is only activated at training stage. But what if i expect scaling the activation at test time? How can I scale the values at testing stage?
Reference: http://stats.stackexchange.com/questions/205932/dropout-scaling-the-activation-versus-inverting-the-dropout
