### ISSUE TITLE
How to make a smooth kernel in Convolution Neural Networks?

### ISSUE THREAD

**Issue by grass0916** [dmlc/mxnet#1306]
Hello everyone,

My datasets is MNIST, I used the CNN algorithm to practice ML.

And I found the reference tutorial, [page 6 and 7](http://web.pdx.edu/~jduh/courses/Archive/geog481w07/Students/Ludwig_ImageConvolution.pdf).

<img width="569" alt="2016-01-18 5 06 26" src="https://cloud.githubusercontent.com/assets/6274807/12387422/62b5a3e2-be07-11e5-8096-75c6f40987bc.png">

I guess the default kernel is all '1' instances in a matrix. How to make the smoothly kernel like above slide.

This is the MXNet code with R.

```
mx.symbol.Convolution(data=data, kernel=c(5,5), num_filter=20)
```

Best,
Salmon.

**Comment by zhangchen-qinyinghua** [comment]
you can init the kernel of convolution manually. And keep it invariant during the train.

**Comment by grass0916** [comment]
@zhangchen-qinyinghua  thanks for your reply. How could I set the initial kernel in MXNet? I didn't find it in document.

**Comment by antinucleon** [comment]
In python, I think it should be write in this way but I don't test yet. This is just a pseudo code. 
```
# real param
data_nd = ...
w_np = np.ones((3, 3)).reshape((1, 1, 3, 3))
w_nd = mx.nd.array(w_np)
# symbol
data = mx.sym.Variable("data")
weight = mx.sym.Variable("weight")
conv = mx.symbol.Convolution(data=data, weight=weight, no_bias=True, kernel=(3,3), num_filter=1, num_group=3) 
# note cudnn doesn't support group
# alternative: use mx.sym.SplitChannel
# bind
executor = conv.bind(ctx=mx.cpu(), args={"data":data_nd, "weight": w_nd}, args_grad=None, reqs=None)
```
