### ISSUE TITLE
Is there any way to achieve theano scan?

### ISSUE THREAD

**Issue by ppaanngggg** [dmlc/mxnet#1311]
rnn example only supports fixed length sequence.

Bind many executors for each length? Then how to train by batch? by bind a tmp sym of Group()?

**Comment by zhangchen-qinyinghua** [comment]
I think your method will do the work.
Every batch, bind a few groups of symbols with same Weights to a different executor, and average the gradient to update the Weights.

**Comment by antinucleon** [comment]
We are currently discussing ways to implement it. Bind many executor is an optional solution.

**Comment by ppaanngggg** [comment]
@antinucleon So there will be some APIs like theano's scan?

**Comment by piiswrong** [comment]
This is now handled with bucketing. See example/rnn
