### ISSUE TITLE
How to finetune mxnet model with a different net architecture?

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#1313]
Say I have a pretrained model in mxnet format. Now I want to change some specific layers architecture and finetune this new net. I want to ask:
How did mxnet load the old symbol and weights, and how did mxnet decide which layers use the old net structures and weights and which layers construct new structures and init their weight from scratch. Decided by the layers' name just like caffe?
Take the alexnet as an example, say I want to change the first full connect layer to a conv and finetune it.
I think it somehow like this:
1. load symbol and weights ```loaded = mx.model.FeedForward.load(prefix, epoch)```
2. Change net architecture by changing ```load.symbol```(how?)
3. reinit the new layers weights(how?)
3. ```finetune_model = mx.model.FeedForward(ctx, symbol=new_symbol, new_arg_params, new_aux_params)```
4. ```finetune_model.fix()```

**Comment by loweew** [comment]
I would also like to know this. An example as simple as reading in a pretrained inception network and changing the number of classes from 1000 to 200, and fine-tuning that final layer would be extremely helpful. I was hoping that using the train_imagenet.py with my own data.rec and setting num_classes would work, but this leads to:

mxnet.base.MXNetError: [13:51:13] src/ndarray/ndarray.cc:159: Check failed: from.shape() == to->shape() operands shape mismatch

Also tried setting the num_hidden in the symbol to 200, but still got the same error.

**Comment by piiswrong** [comment]
Changing the loaded symbol is doable, but it's a hassle.
Instead, I would create a new symbol and load parameters with mx.init.Load

**Comment by loweew** [comment]
doesn't this also cause a mismatch since params file has 1008 in the final layer and my desired symbol has 200? Or am I supposed to load them separately and use getinternals() to somehow attach a new layer and remove the 1008 layer?

**Comment by piiswrong** [comment]
If a layer has different dimensions, it should have a different name, then it will be initialized by default initializer instead of loaded.

**Comment by loweew** [comment]
That's what I was missing. Thanks a lot for clearing that up for me!

**Comment by caffeTao** [comment]
If the new model has fewer layers than the old one ,Does it matter?
