### ISSUE TITLE
Does mxnet support Convolution1D and Pooling1D?

### ISSUE THREAD

**Issue by leoli2012** [dmlc/mxnet#1314]
hi, i want create a cnn model  to deal with un-image date,like text classification.  I create a  conv 1D layer, like below:

conv1 = mx.symbol.Convolution(data=act1, kernel=(4,), num_filter=20)
tanh1 = mx.symbol.Activation(data=conv1, act_type="tanh")
pool1 = mx.symbol.Pooling(data=tanh1, pool_type="max",kernel=(2,), stride=(2,))

however, script run fail in line 3, seems conv1 is ok(i'm not sure), error messages as below:
Traceback (most recent call last):
 File "aes.py", line 216, in handle
    dl_lr_model(sample_data_npy,sample_label_npy)
  File "aes.py", line 152, in dl_lr_model
    pool1 = mx.symbol.Pooling(data=tanh1, pool_type="max",kernel=(2,), stride=(2,))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 963, in creator
    ctypes.byref(sym_handle)))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: value (2,)for Parameter kernel has wrong dimensions, expected dimension=2

As error message shows, pooling parameter expected 2 dim, but i given 1.
Does mxnet support cov 1d and pooling 1d?

**Comment by antinucleon** [comment]
```kernel=(1, 2)```` should work.

**Comment by leoli2012** [comment]
@antinucleon, hi, i don't know why you think pooling kerenal(1,2) is correct? why not (2,1)? i modify my code:
conv1 = mx.symbol.Convolution(data=act1, kernel=(4,), num_filter=20)
tanh1 = mx.symbol.Activation(data=conv1, act_type="tanh")
pool1 = mx.symbol.Pooling(data=tanh1, pool_type="max",kernel=(2,1), stride=(2,1))
it work now, but i am not sure it work  as my expect~
