### ISSUE TITLE
multi-class classification using mxnet.io.NDArrayIter to feed data

### ISSUE THREAD

**Issue by qianguih** [dmlc/mxnet#1317]
Hi, there,
    I am trying to do some multi-class classification work on mxnet. Basically, the label of an instance could be (0,1,0,0,1,0). So it may be impossible to convert a (8000,10) label array to (8000,1). Moreover, I am working on my own dataset and the input data is not image. So, I need to use the mxnet.io.NDArrayIter to feed data to models. I tried to feed a (8000,10) label array to mxnet.io.NDArrayIter, but it reported errors when training. Is there any other ways to accomplish this?

**Comment by piiswrong** [comment]
see example/multi-task
