### ISSUE TITLE
Compiling MxNet with GPU support in R

### ISSUE THREAD

**Issue by wwkong** [dmlc/mxnet#1325]
I'm having some trouble compiling the mxnet package in R with GPU support enabled on an Ubuntu machine in an AWS instance. Like many others before, I get the error 

````R
src/storage/storage.cc:44: Please compile with CUDA enabled
````

when I run any GPU algorithms in R. However, I know for sure that I have installed CUDA correctly and I compiled mxnet with the settings  

````bash
USE_CUDA=1
USE_CUDA_PATH=/usr/local/cuda
````

in the config.mk file (which sits in mxnet root) with no compilation errors as well as recompiled the R package with 

````R
sudo R CMD INSTALL mxnet_0.5.tar.gz
````

Is there something else that I'm missing here?

**Comment by thirdwing** [comment]
My suggestion is `make clean_all;make`. Pay attention to if `nvcc` is actually used.

Let me know if you still meet some errors.

**Comment by wwkong** [comment]
Thanks! This seems to have worked. Before I was only using ```` make clean```` instead of ```` make clean_all ````.
