### ISSUE TITLE
where is the definition of FullyConnected?

### ISSUE THREAD

**Issue by formath** [dmlc/mxnet#1328]
I can't find it in the python api. Some one to help？Thanks.

**Comment by tqchen** [comment]
http://mxnet.readthedocs.org/en/latest/python/symbol.html#mxnet.symbol.FullyConnected

**Comment by tqchen** [comment]
All the symbols are automatically generated during runtime, so there is no definition of the function in python code.

**Comment by piiswrong** [comment]
@tqchen maybe we can add reference to c++ side definition to doc strings of generated functions.
