### ISSUE TITLE
Highway Layers in MXNet

### ISSUE THREAD

**Issue by RishabGargeya** [dmlc/mxnet#1330]
I was just wondering if mxnet had an implementation for highway layers or how I would go about creating one. Thanks so much!

**Comment by piiswrong** [comment]
What's that? Could you give reference?

**Comment by RishabGargeya** [comment]
http://arxiv.org/abs/1505.00387
Also, here is an implementation in lasagne- https://github.com/Lasagne/Lasagne/blob/highway_example/examples/Highway%20Networks.ipynb

**Comment by piiswrong** [comment]
Looks like you don't need a new layer for it. Try composing existing layers. Should be straight forward.

**Comment by RishabGargeya** [comment]
Ah, just found the resnet example as a reference. You're right, thanks for the help!
