### ISSUE TITLE
WindowsError in windows pre-built packages working with Anaconda

### ISSUE THREAD

**Issue by ljie-PI** [dmlc/mxnet#1342]
I installed the pre-built package on my windows 10 64bit laptop following the README. But I got a WindowsError when I ran `import mxnet as mx` in the Python shell:

PS C:\MxNet> python
Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  7 2015, 14:10:42) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Python\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "C:\Python\Anaconda2\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Python\Anaconda2\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python\Anaconda2\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]

I was using the Anaconda 2.4.1 64bit version for Python env.

**Comment by ljie-PI** [comment]
I found a `cudnn` directory in `3rdparty` and thought the cudnn dll file was there. But actually it is not. That may cause the error. Sorry for disturbing.

I will download the cudnn library and try again. But it seems that I need approval to get it downloaded. May I download somewhere else?

**Comment by hjk41** [comment]
cudnn is license protected, that's why we didn't package it in. You need to
register an account and the download is free

On Sat, Jan 23, 2016 at 9:41 PM, Jie Liu <notifications@github.com> wrote:

> I found a cudnn directory in 3rdparty and thought the cudnn dll file was
> there. But actually it is not. That may cause the error. Sorry for
> disturbing.
>
> I will download the cudnn library and try again. But it seems that I need
> approval to get it downloaded. May I download somewhere else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1342#issuecomment-174187441>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by ljie-PI** [comment]
It works now. Thanks.
