### ISSUE TITLE
hidden-layer visualizations

### ISSUE THREAD

**Issue by WDee** [dmlc/mxnet#1353]
I really like Mxnet. I was wondering - is it possible with Mxnet to visualize the activations hidden layers to understand what kind of features the CNN is learning? (e.g. any of these methods - http://cs231n.github.io/understanding-cnn/) ? any thoughts much appreciated

**Comment by piiswrong** [comment]
There isn't an API for this. But example/adversary is a good reference.

**Comment by pluskid** [comment]
Tagging with `HowTo` and closing for now.
