### ISSUE TITLE
Contribution - rules question

### ISSUE THREAD

**Issue by jdukat** [dmlc/mxnet#1354]
Hi,
I didn't find any better place or method to ask this question...
Are there any guidelines for new contributors for MXNet project? I meany anything non-obvious, other than requirement to commit legal code and agree for it's distribution under an open source license?
To clarify: I'm not willing to become a committer for the master branch. Only asking about legal requirements for issuing pull-requests.

**Comment by Gelu74** [comment]
Have you seen this?:
https://mxnet.readthedocs.org/en/latest/contribute.html

**Comment by thirdwing** [comment]
@Gelu74 gave you all the rules we have. Actually it is mostly about coding style.

We don't have other specific rules. You can contribute just as other open-source projects.

My only suggestions are as follow:

(1) If you are fixing issues, just send the PR;

(2) When adding new features, please open an issue first. People can have discussions.

**Comment by jdukat** [comment]
Ok, all clear. Thanks for replies.
