### ISSUE TITLE
GPU based mxnet is not accessible in windows 

### ISSUE THREAD

**Issue by narayaba** [dmlc/mxnet#1358]
With the most recent windows binary build 20160120 GPU package the lenet produces correct CPU results. However, the results based on GPU are incorrect. The installation process completed successfully (see below).

F:\Projects\Gpulibs\formxnet\mxnet>R CMD INSTALL --no-multiarch R-package
* installing to library 'C:/Users/narayaba/Documents/R/win-library/3.2'
* installing *source* package 'mxnet' ...
** libs
make: Nothing to be done for `all'.
installing to C:/Users/narayaba/Documents/R/win-library/3.2/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (mxnet)

This is the case for all the 2016 built packages. If I use the 2015 package the installation fails
F:\Projects\Gpulibs\formxnet\mxnet>R CMD INSTALL --no-multiarch R-package
* installing to library 'C:/Users/narayaba/Documents/R/win-library/3.2'
* installing *source* package 'mxnet' ...
** libs
make: Nothing to be done for `all'.
installing to C:/Users/narayaba/Documents/R/win-library/3.2/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in namespaceExport(ns, exports) :
  undefined exports: mx.nd.argmax.channel
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/narayaba/Documents/R/win-library/3.2/mxnet'

Any idea how to resolve this?

**Comment by thirdwing** [comment]
The 2015 version failed because some functions are missing. Personally I think this is expected.

If you really need to use 2015 version of lib, you can edit the NAMESPACE file from https://github.com/dmlc/mxnet/blob/master/R-package/NAMESPACE

But you need to delete all missing functions manually.

**Comment by Quares** [comment]
In other words, it seems that as for the moment, the current GPU build for R is unavailable (if one does not move to the last 2015 version and edit the NAMESPACE manually). There were others reporting problems with incorrect GPU results on Windows build in other issues.

**Comment by thirdwing** [comment]
Hi, we have updated Windows libs, can you try again?

**Comment by Quares** [comment]
I have tried with the latest release (20160202) and still no success (had to revert back to the one that is working, i.e., 20151228). The problem starts with as simple command as
`mx.nd.ones(c(2,3), mx.gpu())`
which returns a matrix full of zeros instead of ones. By the way, the same erroneous behavior occurs with the windows version of python package build. Again, release 20151228 does not have this behavior.

Just for the reference, the other issues reported the same problem are: #1336, #1228

**Comment by thirdwing** [comment]
Thank you for the testing!

On Tue, Feb 2, 2016 at 1:56 PM, Kamil <notifications@github.com> wrote:

> I have tried with the latest release (20160202) and still no success (had
> to revert back to the one that is working, i.e., 20151228). The problem
> starts with as simple command as
> mx.nd.ones(c(2,3), mx.gpu())
> which returns a matrix full of zeros instead of ones. By the way, the same
> erroneous behavior occurs with the windows version of python package build.
> Again, release 20151228 does not have this behavior.
>
> Just for the reference, the other issues reported the same problem are:
> #1336 <https://github.com/dmlc/mxnet/issues/1336>, #1228
> <https://github.com/dmlc/mxnet/issues/1228>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1358#issuecomment-178757762>.
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by Quares** [comment]
Happy to help!

**Comment by hjk41** [comment]
@Quares Just tried build 20160202 with Python, simple test seems to work.
```
>>> import mxnet as mx
OpenCV is unavailable.
>>> a = mx.nd.ones((2,3), mx.gpu(0))
>>> a.asnumpy()
array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)
```
I will try with other examples.

**Comment by hjk41** [comment]
Let's move to #1228 for discussion. Closing this issue.

**Comment by alpop** [comment]
I had same issue with Windows x64. Rebuilt libmxnet.dll from scratch and it started working OK.
