### ISSUE TITLE
[R] NDArrayIter is missing in R

### ISSUE THREAD

**Issue by thirdwing** [dmlc/mxnet#1359]
Not very sure we really need this.

**Comment by shallyan** [comment]
hello, do you mean that NDArrayIter will receive the NDArray as input and be the same as ArrayDataIter in other aspects?
And we can convert NDArray to Array, thus using ArrayIter, so you say "Not very sure we really need this"?
Thank for your reply.
@thirdwing

**Comment by thirdwing** [comment]
This issue was opened when I port the autoencoder code

**Comment by shallyan** [comment]
I have seen the autoencoder example and fix a small error ([https://github.com/dmlc/mxnet/pull/1540](https://github.com/dmlc/mxnet/pull/1540)) btw.

I think the NDArrayIter in python works just the same as ArrayIter in R here, can't we just replace it with ArrayIter? 
@thirdwing
