### ISSUE TITLE
questions about image regression

### ISSUE THREAD

**Issue by attitudechunfeng** [dmlc/mxnet#1360]
I'd like to use MxNet for image regression, namely my input data is image and output is a number. How can I process my data? I have tried to process in the way as doing image classification, and I change to use a LinearRegressionOutput instead of SoftmaxOutput, but the Train-accuracy=0.00, Could someone tell me where's wrong?

**Comment by jmschrei** [comment]
You need to change your eval_metric from 'acc' to 'MAE', 'MSE', or 'RMSE' if you're using the Python package.

**Comment by attitudechunfeng** [comment]
Thanks a lot@jmschrei. But how to change the eval_metric?

**Comment by jmschrei** [comment]
If you're using python, add `eval_metric='rmse'` to the fit method.

**Comment by attitudechunfeng** [comment]
Thank u. I have solved the problem. And I have another question, how to visualize the learned filters in MxNet. I haven't found relative tutorials. Could you give me some advice for that?

**Comment by lincolnBush** [comment]
@attitudechunfeng  Could you please give me a little hint on how to use LinearRegressionOutput to do the image regression. My task is to give a regression y(x) from 0-1 and the one-dimensional x is from 0 -> + infinity. Thank you very much.
