### ISSUE TITLE
Error in FCN

### ISSUE THREAD

**Issue by ZhaoJianghua** [dmlc/mxnet#1363]
I changed the fcn model, but I got this error.

[13:48:42] ./dmlc-core/include/dmlc/logging.h:241: [13:48:42] include/mxnet/./ndarray.h:71: Unknown type enum 136
[13:48:42] ./dmlc-core/include/dmlc/logging.h:241: [13:48:42] src/engine/./threaded_engine.h:295: [13:48:42] include/mxnet/./ndarray.h:71: Unknown type enum 136
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [13:48:42] src/engine/./threaded_engine.h:295: [13:48:42] include/mxnet/./ndarray.h:71: Unknown type enum 136
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)

sometimes there is another error

terminate called after throwing an instance of 'std::out_of_range'
  what():  array::at
Aborted (core dumped)

**Comment by piiswrong** [comment]
What did you change?

**Comment by ZhaoJianghua** [comment]
I build a model based on alexnet and initialize its weights by my own method. It seams all ok and can do training for a few epochs.

**Comment by winstywang** [comment]
Is it OK to run the original FCN model?

**Comment by ZhaoJianghua** [comment]
it's ok when crop the data size into 128*128

**Comment by hjk41** [comment]
A strange enum value? Sounds like a memory access problem to me.

On Tue, Jan 26, 2016 at 11:33 PM, ZhaoJianghua <notifications@github.com>
wrote:

> it's ok when crop the data size into 128*128
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1363#issuecomment-175464675>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by ZhaoJianghua** [comment]
the enum value is different everytime

**Comment by austingg** [comment]
@tornadomeet  have ever met that error during training FCN for semantic segmentation?

**Comment by tornadomeet** [comment]
can you debug which line of your code suspend? the information is not enough here. i guess for 2 tips:
1. your crop_offset should change if you using your own model;  
2. your initialization should consider the context(gpu or cpu).

**Comment by piiswrong** [comment]
@ZhaoJianghua Please post a minimum reproducible code so other people can help you debug.

**Comment by martinbel** [comment]
I'm getting the same error:

```
import numpy as np
import mxnet as mx
from PIL import Image

img = '2007_000480.jpg'
seg = img.replace("jpg", "png")
model_previx = "FCN8s_VGG16"
epoch = 19
ctx = mx.cpu()  #ctx = mx.gpu(0)

def get_data(img_path):
    """get the (1, 3, h, w) np.array data for the img_path"""
    mean = np.array([123.68, 116.779, 103.939])  # (R,G,B)
    img = Image.open(img_path)
    img = np.array(img, dtype=np.float32)
    reshaped_mean = mean.reshape(1, 1, 3)
    img = img - reshaped_mean
    img = np.swapaxes(img, 0, 2)
    img = np.swapaxes(img, 1, 2)
    img = np.expand_dims(img, axis=0)
    return img


fcnxs, fcnxs_args, fcnxs_auxs = mx.model.load_checkpoint(model_previx, epoch)
fcnxs_args["data"] = mx.nd.array(get_data(img), ctx)
data_shape = fcnxs_args["data"].shape
label_shape = (1, data_shape[2]*data_shape[3])
fcnxs_args["softmax_label"] = mx.nd.empty(label_shape, ctx)
exector = fcnxs.bind(ctx, fcnxs_args ,args_grad=None, grad_req="null", aux_states=fcnxs_args)
exector.forward(is_train=False)
output = exector.outputs[0]

```

So far, it works fine. This generates the error.

`output.asnumpy()`

Any ideas?  I'm using the model files supplied via a dropbox link by @tornadomeet: 
- FCN8s_VGG16-0019.params
- FCN8s_VGG16-symbol.json

**Comment by tianhaijie** [comment]
@ZhaoJianghua Hi! I met the same problem....I wonder How u solve it,thanks!

**Comment by chowkamlee81** [comment]
Yeah i too met with the smae problem... Kindly let me know how u solved it..pls

**Comment by zhanghang1989** [comment]
Got the same error using Gluon, any updates?
