### ISSUE TITLE
List the todos publicly to finish them quickly

### ISSUE THREAD

**Issue by mebjas** [dmlc/mxnet#1369]
We should have `mxnet` on Todofy, I tried it on my fork and there are about `34 todos` in the `master branch`. Here's the link: https://todofy.org/r/fybot/mxnet

This will give clear visibility on what all need to be finished, and platform has various feature to assist the process.

**Comment by piiswrong** [comment]
@tqchen Looks like a good idea. Let's try it?

**Comment by tornadomeet** [comment]
+1

**Comment by mli** [comment]
enabled, have a check at 

https://todofy.org/r/dmlc/mxnet

**Comment by mebjas** [comment]
Thanks! :)
