### ISSUE TITLE
c++ interface for extracting feature

### ISSUE THREAD

**Issue by kingvision** [dmlc/mxnet#1370]
hi
  how i can extract feature by c++?

thanks

**Comment by zhangchen-qinyinghua** [comment]
You should bind your own Symbols with the trained parameters to extracting the features.

As for c++ interface, you can also try this (which is usable, but not completed):
https://github.com/hjk41/MxNet.cpp

**Comment by futurely** [comment]
The inability to do such simple things with simple API is one of the key reasons why MXNet is the simplest, the most powerful but not the most popular DL framework. User friendliness has never been a top priority.

**Comment by futurely** [comment]
I wish someday this could be done as easily as the same thing is done in Caffe.
```cpp
feature_extraction_net->Forward();
const boost::shared_ptr<Blob<Dtype> > feature_blob =
        feature_extraction_net->blob_by_name(feature_name);
```
