### ISSUE TITLE
Change default kv_store value to device

### ISSUE THREAD

**Issue by superzrx** [dmlc/mxnet#1371]
As metioned in #1260  and #858 , the default value 'local' for kv_store will reduce speed for small batchsize when trainning big networks like inception or resnet.
Maybe we should set 'device' as the detault value.
In my case, it raise the trainning speed from 50 samples/sec to 100 samples/sec using 4xK40 when training resnet.

**Comment by superzrx** [comment]
Additionally change sgd to ccsgd gives another 25 samples/sec promotion

**Comment by mli** [comment]
does `kvstore=device` solve #1260 ?

we didn't set to device in default because it improves some networks but degrades others. a better way is to heuristically set the best config.

**Comment by tqchen** [comment]
This also really depends on the PCI and card settings, it was not set to device mainly because it is also more memory consuming. However, you are welcomed to contribute a note on this in the docstring and documents

**Comment by tqchen** [comment]
closing for now
