### ISSUE TITLE
Is there a optimizer using Levenberg-Marquardt algorithm?

### ISSUE THREAD

**Issue by kjshao** [dmlc/mxnet#1373]
I'm now using MXnet for regression, the input data is a 7-dimension vector, and the output is a value of the function f(x1,...,x7). The dataset contains 100, 000 samples. I've got RMSE which is low enough with the another program using Levenberg-Marquardt algorithm. The network is a simple MLP with two hidden layers. But in mxnet I only found methods like SGD which can not achieve the accuracy that I want.
Is there an optimizer using Levenberg-Marquardt algorithm? How can I create a new optimizer.
And whether I can use another network such as CNN or another optimizer that can achieve high accuracy in regression?

**Comment by piiswrong** [comment]
Optimizers are in python/mxnet/optimizer.py.
It should be straight forward to create a new one.
