### ISSUE TITLE
How to move mxnet on Nvidia tk1?

### ISSUE THREAD

**Issue by gary30404** [dmlc/mxnet#1374]
I'm a deep learning beginner. Could anyone tell me how to modify Makefile to move mxnet on tk1?

**Comment by piiswrong** [comment]
@winstywang 
It should be straight forward. What error are you seeing?

**Comment by winstywang** [comment]
I have not tested it. I will try it on TX1 next week as soon as I get it.

**Comment by gary30404** [comment]
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_NVRTC=0 -MM -MT build/src/resource.o src/resource.cc >build/src/resource.d
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_NVRTC=0 -MM -MT build/src/c_api/c_api.o src/c_api/c_api.cc >build/src/c_api/c_api.d
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_NVRTC=0 -MM -MT build/src/c_api/c_api_error.o src/c_api/c_api_error.cc >build/src/c_api/c_api_error.d
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_NVRTC=0 -MM -MT build/src/c_api/c_predict_api.o src/c_api/c_predict_api.cc >build/src/c_api/c_predict_api.d
g++: error: unrecognized command line option '-msse3'
make: *** [build/src/resource.o] Error 1
make: *** Waiting for unfinished jobs....
g++: error: unrecognized command line option '-msse3'
g++: error: unrecognized command line option '-msse3'
make: *** [build/src/c_api/c_api.o] Error 1
make: *** [build/src/c_api/c_api_error.o] Error 1
g++: error: unrecognized command line option '-msse3'
make: *** [build/src/c_api/c_predict_api.o] Error 1

this is the error message when I make -j4. I think the reason is that tk1 doesn't support SSE but I don't know how to modify the makefile. Thank you for your response.

**Comment by piiswrong** [comment]
Try adding -DMSHADOW_USE_SSE=0 to ADD_CCFLAGS in config.mk and in mshadow/make/mshadow.mk:11, remove -msse3

**Comment by gary30404** [comment]
@piiswrong Do you mean this?
in config.mk(root directory of mxnet)
ADD_CCFLAGS = 
DMSHADOW_USE_SSE = 0
mshadow/make/mshadow.mk:11
MSHADOW_CFLAGS = -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas

and then `make`

g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_NVRTC=0 -MM -MT build/src/resource.o src/resource.cc >build/src/resource.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_NVRTC=0 -c src/resource.cc -o build/src/resource.o
In file included from ./mshadow/mshadow/././././extension/../packet-inl.h:203:0,
                 from ./mshadow/mshadow/././././extension/implicit_gemm.h:11,
                 from ./mshadow/mshadow/./././dot_engine-inl.h:11,
                 from ./mshadow/mshadow/././expr_engine-inl.h:374,
                 from ./mshadow/mshadow/./extension.h:10,
                 from ./mshadow/mshadow/tensor.h:793,
                 from include/mxnet/base.h:13,
                 from src/resource.cc:8:
./mshadow/mshadow/././././extension/../packet/sse-inl.h:10:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
                       ^
compilation terminated.
make: *** [build/src/resource.o] Error 1

**Comment by piiswrong** [comment]
`ADD_CCFLAGS = -DMSHADOW_USE_SSE=0`
Note the `-`

**Comment by gary30404** [comment]
I have tried but the error is still the same.
What's happened?

g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_NVRTC=0 -MM -MT build/src/resource.o src/resource.cc >build/src/resource.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_NVRTC=0 -c src/resource.cc -o build/src/resource.o
In file included from ./mshadow/mshadow/././././extension/../packet-inl.h:203:0,
                 from ./mshadow/mshadow/././././extension/implicit_gemm.h:11,
                 from ./mshadow/mshadow/./././dot_engine-inl.h:11,
                 from ./mshadow/mshadow/././expr_engine-inl.h:374,
                 from ./mshadow/mshadow/./extension.h:10,
                 from ./mshadow/mshadow/tensor.h:793,
                 from include/mxnet/base.h:13,
                 from src/resource.cc:8:
./mshadow/mshadow/././././extension/../packet/sse-inl.h:10:23: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
                       ^
compilation terminated.
make: *** [build/src/resource.o] Error 1

**Comment by mli** [comment]
i think we should use `ADD_CFLAGS = -DMSHADOW_USE_SSE=0` (only one C) while not `ADD_CCFLAGS`

**Comment by thirdwing** [comment]
I have compiled mxnet on Tk1.

Besides the `ADD_CFLAGS`, you also need to remove `-msse2` in https://github.com/dmlc/dmlc-core/blob/master/Makefile#L14

**Comment by mli** [comment]
@thirdwing nice! how is the performance of tk1 comparing to other common cards, such as k40 or gtx 750 ti?

**Comment by thirdwing** [comment]
It is a GPU for mobile devices (like Dji's quadrone), so not powerful.

**Comment by mli** [comment]
yeah, i know that. so my question is that how is it comparing to some come
nvidia gpu? for example, i guess tx1 is roughly equal to 15% k40? i just
want to get a sense how many frames we may get if run prediction on tx1.

another question is, is there anyone has put tk1 on dji successfully?

**Comment by thirdwing** [comment]
I can run some benchmarks later.

Tk1 is part of the official SDK https://developer.dji.com/manifold/

**Comment by mli** [comment]
many thanks for the link, i didn't know that before. have you heard any news that when dji will put tx1 onboard? tx1 is much more interesting since it's almost 4x faster than tk1 if using FP16.

**Comment by gary30404** [comment]
@thirdwing May I ask you what version of CUDA Toolkit do you have on tk1?
Thank you.

**Comment by thirdwing** [comment]
@mli I will let you know if heard anything.

@gary30404 CUDA 6.5

**Comment by gary30404** [comment]
Thank you all. 
I have succeeded by doing these:
ADD_CFLAGS = -DMSHADOW_USE_SSE=0
remove msse3 and msse2

**Comment by chqsark** [comment]
I'm following this thread to compile mxnet on TX1. I encountered this error:

g++: error: /home/nvidia/ml/mxnet/dmlc-core/libdmlc.a: No such file or directory
Makefile:189: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
g++: error: /home/nvidia/ml/mxnet/dmlc-core/libdmlc.a: No such file or directory
Makefile:205: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

Anyone had the same error previously?

**Comment by omauni** [comment]
Hello everyone,
I managed to compile mxnet 0.9.3 on galaxy 2 tablet. I had to change the folowing part of the config.mk (add armv8l in the processor list) : 
#----------------------------
# Settings for power and arm arch
#----------------------------
ARCH := $(shell uname -a)
ifneq (,$(filter $(ARCH), armv6l armv7l armv8l powerpc64le ppc64le aarch64))
        USE_SSE=0
else
...

Hope it will help.
