### ISSUE TITLE
How to change the batch size during forwarding?

### ISSUE THREAD

**Issue by GravApple** [dmlc/mxnet#1377]
I want to implement a layer that is capable of changing the batch size during forwarding, and C++/MShadow level would be my preference for performance consideration. I believe there must be a way of dealing with this requirement, can someone tell my how?
Any advice will be appreciated! Thanks in advance.

**Comment by piiswrong** [comment]
Runtime reshaping is difficult with current architecture. You need to change the GraphExecutor and memory allocator. A layer cannot modify it's in/out shape

**Comment by tornadomeet** [comment]
or you can write your own solver, and bind the symbol for every batch, which only change the input data and label.

**Comment by piiswrong** [comment]
@GravApple https://github.com/dmlc/mxnet/pull/1408 added this feature. You are welcome to test it.

**Comment by GravApple** [comment]
@piiswrong Thank you very much! I will try it.
