### ISSUE TITLE
Distributed Training:  Is there any method to balance the time consume on different workers?

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#1380]
Assume I have 2 different graphic cards K40 and gtx980 on two workers, these two card have significant different compute capability. If batch size on the two workers are the same, then gtx980 have to wait K40 to finish the compute. So I would ask is there any method to balance the time consume?

**Comment by piiswrong** [comment]
Use model.fit(ctx=[mx.gpu(slow), mx.gpu(fast)], work_load_list=[1, 9]). Tune the numbers until it's not blocking.

**Comment by shuokay** [comment]
@piiswrong I think this only can run on the same machine, but how if I have two cards on separated machines?

**Comment by piiswrong** [comment]
You can change the launch script to set different batch_size for each process.
