### ISSUE TITLE
How to load images with different size.

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1381]
Hi,
I am currently trying to do image segmentation using PASCAL dataset. The difficulty is the images in this dataset have different sizes, so I have to crop them into a fixed size for batch training. Here comes the question. How can I crop the images dynamically before creating the batch. I mean the images loaded can have different sizes, but after a preprocessing step, the images will get randomly cropped and then sent to the batch. Can I do this in MXNET? otherwise, I will have to do this in advance and randomly crop each training sample and generate many versions of them, which will end up with a very large database with much "redundant data". Any idea? I would really appreciate it.

**Comment by piiswrong** [comment]
You can write your custom data iterator. You can refer to io.DataIter and recordio.MXRecordIO

**Comment by piiswrong** [comment]
Another strategy is to modify iter_image_recordio.cc in src/io. There shouldn't be fundamental difficulty with supporting variable input size as long as the output images are croped to the same size.

**Comment by ascust** [comment]
I am still not very clear. I dont have much experience with mix programming in C++ and Python and dont know how it works. So can I just do it with pure python like extending a new class based on dataIter? or I have to modify iter_image like you said. I wish you could tell me a little bit more. I would appreciate it.

**Comment by piiswrong** [comment]
You can do either. Python solution will be slower but it's not necessarily going to be the bottle neck.
