### ISSUE TITLE
Problem running  RNN PTB sample on both Linux and Windows 

### ISSUE THREAD

**Issue by hanyh** [dmlc/mxnet#1383]
during running the RNN PTB sample lstm_ptb.py, it fails while calulcalting NLL due to zero len label vector here:  nll = -np.sum(np.log(seq_label_probs.asnumpy())) / len(X[0,:])

Logs:
Loading ./data/ptb.train.txt, size of data = 929590
Unique token: 10000
Loading ./data/ptb.valid.txt, size of data = 73761
Unique token: 10000
Vocab=10000
Training with train.shape=(46445, 20)
Training with val.shape=(3675, 20)
batch_size=20
seq_len=35
Epoch [28] Train: NLL=19.903, Perp=440413635.196
Epoch [56] Train: NLL=18.576, Perp=116847727.676
Epoch [84] Train: NLL=17.796, Perp=53529230.425
/home/hanyh/MXNet/mxnet/example/rnn/lstm.py:184: RuntimeWarning: divide by zero encountered in log
  nll = -np.sum(np.log(seq_label_probs.asnumpy())) / len(X[0,:])
Epoch [112] Train: NLL=inf, Perp=inf
Epoch [140] Train: NLL=inf, Perp=inf
Epoch [168] Train: NLL=inf, Perp=inf

**Comment by mcculloh** [comment]
I noticed this a well. For me on os x. But the issue is not that len(X) is 0, its that you are taking logs of zeros. The probabilities assigned by the output layer have lots of zeros in them so np.log(0) gives an error.

**Comment by mcculloh** [comment]
Looks like the same issue as https://github.com/dmlc/mxnet/issues/1322
