### ISSUE TITLE
problem with train_mnist.py

### ISSUE THREAD

**Issue by jiafeixiaoye** [dmlc/mxnet#1389]
When I try to run train_mnist.py I got some problems.
It prompts 
 ** On entry to SGEMM  parameter number  4 had an illegal value
 ** On entry to SGEMM  parameter number  4 had an illegal value
continuously when it running.It takes a long time to train, and the training result is poor,the Validation-accuracy is about 0.1.

I need run it on CPU,and my OS is Win8. I had delete USE_CUDNN when I build the project, and set devs = mx.cpu().
Is there somthing wrong when I build it,or some configuration I ignored?

**Comment by piiswrong** [comment]
Which blas library are you using.
Could you post your config.mk

**Comment by jiafeixiaoye** [comment]
I download the thirdparty library from BaiduYun: http://pan.baidu.com/s/1kTrQmn9,it includes OpenBlas.

the config.mk:
#---------------------
# choice of compiler
#--------------------

export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS =

# the additional compile flags you want to add
ADD_CFLAGS =

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 0

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = NONE

# whether use CuDNN R3 library
USE_CUDNN = 0

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 0

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =


#----------------------------
# plugins
#----------------------------

# whether to use torch integration. This requires installing torch.
# TORCH_PATH = $(HOME)/torch
# MXNET_PLUGINS += plugin/torch/torch.mk

# whether to use sframe integration. This requires build sframe
# git@github.com:dato-code/SFrame.git
# SFRAME_PATH = $(HOME)/SFrame
# MXNET_PLUGINS += plugin/sframe/plugin.mk

**Comment by piiswrong** [comment]
Are you building with visual studio or mingw?
I think on windows the standard is to build with cmake and visual studio.

**Comment by jiafeixiaoye** [comment]
Yes, I build with cmake and visual studio 2013.

**Comment by jiafeixiaoye** [comment]
I forgot configure the USE_BLAS choice yesterday and I have corrected all the relative choices to make sure the project build with openblas, but the problem still exist.
