### ISSUE TITLE
1px Zero-padding on one side of a picture 

### ISSUE THREAD

**Issue by xgastaldi** [dmlc/mxnet#1391]
Hi, I am trying to add an asymetrical zero padding on one side of a picture before a convolution. Any idea how to do that? I tried creating a 1px wide symbol and then concatenating it with mx.symbol.concatenate but couldn't make it work.

**Comment by piiswrong** [comment]
a) Do it with custom data iter as preprocessing.
b) do symetrical padding and crop your output with sym.Crop to throw away the extra outputs.

**Comment by xgastaldi** [comment]
Thanks, option a wouldn't work because I would like to do that on symbols inside the network.
Wrt to option b, I would like to do this before a convolution (e.g. add 1px and then perform a convolution) and I don't think that there is a standalone function in mxnet for padding. Is there a way to pad on a symbol without modifying it?

**Comment by xgastaldi** [comment]
Many thanks for your help. I managed to do it with Torch's nn.Padding function :). 
The Torch bindings are really helpful!
