### ISSUE TITLE
Cannot call mxnet.io.ImageRecordIter from io.py

### ISSUE THREAD

**Issue by rollingstone** [dmlc/mxnet#1393]
Hi,

It seems that mx.io.ImageRecordIter method is not implemented in the io.py. I am not sure what went wrong. Is there any updated version of io.py which includes ImageRecordIter method?

Thanks a lot

**Comment by jsusskin** [comment]
I noticed that too. It seems that the ImageRecordIter function generates a MXDataIter object with particular properties like random data augmentation, etc. Not sure why but I couldn't find the function definition anywhere -- probably just not understanding something about how the underlying code base works.

**Comment by piiswrong** [comment]
It's generated at the end of io.py from C++ code.

**Comment by jsusskin** [comment]
Ah. That explains it. Useful to know if anyone wants to generate variants similar to ImageRecordIter.

**Comment by rollingstone** [comment]
Thanks a lot. It's a nice trick. :)
