### ISSUE TITLE
Arguments to mx.callback.save_checkpoint

### ISSUE THREAD

**Issue by caprice-j** [dmlc/mxnet#1395]
What should I give to symbol, arg_params, and aux_params arguments of mx.model.fit()?

When I executed

model.fit(
   epoch_end_callback = mx.callback.save_checkpoint(prefix='mytest', epoch=1, symbol=net, arg_params=model.arg_params, aux_params=model.aux_params )
)

it returns:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-65-35a079083a7b> in <module>()
      5          eval_metric = mx.metric.RMSE(),
      6 #  epoch_end_callback = mx.callback.log_train_metric(5),                      # doesn't work
----> 7    epoch_end_callback = mx.callback.save_checkpoint(prefix='pzl8',epoch=1,symbol=net,arg_params=model.arg_params,aux_params=model.aux_params)  # doesn't work
      8 #  batch_end_callback = mx.callback.ProgressBar(98000)
      9 #  batch_end_callback = mx.callback.Speedometer(batch_size = minibatch_size, frequent = 10)

/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.pyc in save_checkpoint(prefix, epoch, symbol, arg_params, aux_params)
    315     """
    316     symbol.save('%s-symbol.json' % prefix)
--> 317     save_dict = {('arg:%s' % k) : v for k, v in arg_params.items()}
    318     save_dict.update({('aux:%s' % k) : v for k, v in aux_params.items()})
    319     param_name = '%s-%04d.params' % (prefix, epoch)

AttributeError: 'NoneType' object has no attribute 'items'

I searched examples but to no avail.

**Comment by piiswrong** [comment]
Don't specify those unless you know what you are doing.

**Comment by caprice-j** [comment]
But when I remove the last three arguments, it returns:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-66-c7afe2fd05af> in <module>()
      5          eval_metric = mx.metric.RMSE(),
      6 #  epoch_end_callback = mx.callback.log_train_metric(5),                      # doesn't work
----> 7    epoch_end_callback = mx.callback.save_checkpoint(prefix='pzl8',epoch=1)  # doesn't work
      8 #  batch_end_callback = mx.callback.ProgressBar(98000)
      9 #  batch_end_callback = mx.callback.Speedometer(batch_size = minibatch_size, frequent = 10)

TypeError: save_checkpoint() takes exactly 5 arguments (2 given)

**Comment by piiswrong** [comment]
Are you using the most recent mxnet? I don't see a save_checkpoint function in callback.py. It has been replaced by do_checkpoint

**Comment by caprice-j** [comment]
Sure. Thanks for the information.

Then, is there a way to save .params for every two or more epoch?
do_checkpoint() doesn't seem to have 'epoch' argument.

**Comment by pqn** [comment]
I tried helping with #1669.
