### ISSUE TITLE
predicting on random crops

### ISSUE THREAD

**Issue by loweew** [dmlc/mxnet#1402]
What is the preferred way to do this? I generate crops through sliding window or selective search, but predicting on each crop serially is obviously slow. So, I'd like to create a batch of these crops and then predict on that batch. What is the best way to do this? I couldn't find an example of using a list of images directly to predict. Should I create a rec object from the images and use that data iterator, or is there a better way?

**Comment by piiswrong** [comment]
Subclass DataIter and write your own data iterator
