### ISSUE TITLE
Multi-Label Training Problem in MXNET

### ISSUE THREAD

**Issue by paipai880429** [dmlc/mxnet#1404]
Hi, all. 
I referred to the mxnet/examples/ndsb2/Training.py, trying to solve a multi-label problem. However, I am running into the "no learning" problem.
![image](https://cloud.githubusercontent.com/assets/3724085/12771065/01a31286-ca61-11e5-86ec-bb9149c9fdfb.png)

My processing with MXNET is as follows:

1. I create the "train.lst" and "val.lst" as the  document shows. Speifically, I turned the labels to a binary vector (length=9).
![image](https://cloud.githubusercontent.com/assets/3724085/12771068/100dd194-ca61-11e5-95c3-41043050db77.png)

2. I use the "im2rec" tool to generate the "training_128x128.rec" and  "val_128x128.rec", with resize=128, label_width=9.

3. Build up a Residual Network ending with a "LogisticRegressionOutput" layer as ndsb2/Training.py. 
![image](https://cloud.githubusercontent.com/assets/3724085/12771980/74771742-ca68-11e5-892d-38d6b1aeafc1.png)

4. In the train_yelp.py, remember to set the label_width=9. And use the mxnet/example/image-classification/train_model.py as the training interface.
![image](https://cloud.githubusercontent.com/assets/3724085/12771989/7f59ca10-ca68-11e5-969a-825a62401e96.png)

5. Create the evaluation accuracy for multi-lables just as "CPRS(pred, label)" in the ndsb2.
![image](https://cloud.githubusercontent.com/assets/3724085/12771994/882aa7d6-ca68-11e5-9b20-1f0bab39d5a4.png)

![image](https://cloud.githubusercontent.com/assets/3724085/12772003/927f7b76-ca68-11e5-8129-df1a20a95282.png)

Then I run:
python train_yelp.py --lr 0.1 --num-epochs 50 --model-prefix /mnt/extend/chx/Kaggle_data/Yelp/models/res18 --num-examples 36187
The framework is not leaning at all (always 0.000000 as you can see). Please indicate my error. Thank you very much !

**Comment by piiswrong** [comment]
You probably need custom metric for multi label learning.

**Comment by paipai880429** [comment]
@piiswrong Would you please check the custom eval_metric for me (the last two pictures)?

**Comment by piiswrong** [comment]
Accuracy of 0 most likely means your metric is buggy. By chance it should be at least around 1/num_class.
Try debugging with pdb

**Comment by shenxiul** [comment]
It looks normal. Your accuracy layer is computing the accuracy that EVERY label is predicting correctly, which is effectively 2^9=512 class classification, and the training process should start with a low accuracy.

**Comment by shenxiul** [comment]
@paipai880429 This is the eval function you might want consider (tested):
```python
def ml_acc(label, pred, label_width=9):
  return float((label == np.round(pred)).sum()) / label_width / pred.shape[0]
```
Or you can use something makes more sense to you.

**Comment by paipai880429** [comment]
@shenxiul , thanks for you reply!!! Your are rounding ```pred``` here, thus you are assuming that pred is a vector of float numbers instead of 0s and 1s

**Comment by shenxiul** [comment]
@paipai880429 Yes, it is probability rather than predicting label, oh I didn't realize that you don't round it... Sorry I should state it earlier.

**Comment by paipai880429** [comment]
@shenxiul Really thank you for your quick response! And, happy new year.

**Comment by shenxiul** [comment]
@paipai880429 Happy new year, shall we close this issue?
