### ISSUE TITLE
Compiler error when building on Windows

### ISSUE THREAD

**Issue by magic282** [dmlc/mxnet#1407]
Hi,

I am trying to build mxnet under Windows. According to the docs, I used cmake-gui and no error was reported. The VS is 2013. And about the c++11 support, when I run the patch, it said that the patch was already installed. The OS is 64 bit Windows 10. The CUDA version is 7.5; cudnn version is v3, and the gpu is gtx 960. The compiler selected in cmake-gui is VS2013 win64.

The cmake screenshot:
![cmake](https://cloud.githubusercontent.com/assets/2285145/12780363/7447f5d0-caa8-11e5-9a5c-35205d481015.PNG)

The error is:
```
Error	13599	error C1001: An internal error has occurred in the compiler.	e:\projects\opensource\mxnet\src\ndarray\ndarray.cc	171	1	mxnet
Error	231	error C1001: An internal error has occurred in the compiler.	e:\projects\opensource\mxnet\src\operator\ndarray_op.cc	117	1	mxnet
Error	232	error C1001: An internal error has occurred in the compiler.	e:\projects\opensource\mxnet\src\operator\ndarray_op.cc	71	1	mxnet

```

Is there any hint about this error? Thanks.

**Comment by hjk41** [comment]
@magic282 could you try the latest code? And also if possible, reinstall VS2013 and CUDA.
