### ISSUE TITLE
cudnn v4 2-3x slower than v3 for predictions on inception style arch

### ISSUE THREAD

**Issue by lukemetz** [dmlc/mxnet#1409]
Hello,
I am experiencing a weird performance regression when predicting from an inception style convnet with cudnn V4.
My tests were all off of current master and a clean build and re init of all sub modules with cuda 7.0. I switch versions by deleting the cudnn files from my cuda directory (libs and headers) and replacing them with the new ones.
When V3 is enabled I am able to process 50 images a second across 4 gpus.
When V4 is enabled I am able to process 17 images a second across 4 gpus.
Everything minus this version switch is the same. All tests are using batchsize 72.
Not exactly sure what is going on here.

**Comment by piiswrong** [comment]
Could you try tuning the workspace size for convolutional layers? If it's too much trouble setting it for each layer in python, just change the default value in C++ code.
My guess is setting it smaller will be better

**Comment by mli** [comment]
i did a comparison between v3 and v4 on inception 7 using 4 x titan x. my results show v4 is still a little bit faster than v3.

**Comment by lukemetz** [comment]
I ran some numbers on my specific task taking into account workspace size. Here is the sweep:

cudnn v4:
workspace 128: 53 img/sec
workspace 256: 31 img/sec
workspace 512: 15 img/sec
workspace 1024: 16 img/sec

cudnn v3:
workspace 128: 53 img/sec
workspace 256: 50 img/sec
workspace 512: 51 img/sec
workspace 1024: 51 img/sec

I find it very strange how different the performance is from v3 to v4, but for now my issue is fixed with workspace.
Is there a reason mxnet doesn't use `CUDNN_CONVOLUTION_FWD_PREFER_FASTEST`? I imagine we could pass `None` or `'auto'` into workspace parameter and the cpp would manage.

**Comment by mli** [comment]
can you have a try with the `PREFER_FASTEST` flag? i tested last night but it decreases the performance, i guess it's probably due to incorrect workspace size. 

does 'auto' work?

**Comment by piiswrong** [comment]
Cudnn is being stupid and when allowed more workspace, picks an algorithm
thats both slow and memory consuming. We are going to change default
workspace to a smaller value to circumvent this.

**Comment by piiswrong** [comment]
Prefer fasted is the worst since its equivalent to allowing infinite
workspace.  We were using it before. I changed to limit workspace a while
back.

**Comment by lukemetz** [comment]
Well that's dumb of cudnn. It would be cool to do some sort of graph optimization like (http://benanne.github.io/2014/12/09/theano-metaopt.html) to auto pick. I will run the PREFER_FASTEST on my test when my gpu's are free again.

**Comment by lukemetz** [comment]
With PREFER_FASTEST enabled for everything in the convolution my speeds are:
16 examples a second. So exactly as @piiswrong suggested.
