### ISSUE TITLE
A issue happened when I make 

### ISSUE THREAD

**Issue by zhoususheng** [dmlc/mxnet#1417]
my opencv version is 3.1
![2016-02-04 16-08-38](https://cloud.githubusercontent.com/assets/9567903/12809414/c4fdf3a6-cb59-11e5-998e-5f21fd27aca2.png)

**Comment by thirdwing** [comment]
`libippicv` is part of opencv. Please make sure you installed opencv properly.

**Comment by zhoususheng** [comment]
Thank you. I have resolved!
