### ISSUE TITLE
[mxnet-R] More high-level APIs? 

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/mxnet#1420]
It would be nice to have some high level APIs that users can just  plug in and play with, e.g. RNN/LSTM since I don't think most R users would be able to implement it themselves. Imagine rewriting this Python implementation in R - https://github.com/dmlc/mxnet/tree/master/example/rnn

**Comment by thirdwing** [comment]
I am thinking about proposing this as a GSOC project. At least we can have someone to work on this.

**Comment by tqchen** [comment]
Sounds good. KK can you lead this issue?

**Comment by thirdwing** [comment]
I have post a drat at https://github.com/rstats-gsoc/gsoc2016/wiki/Deep-learning-with-mxnet

We can add more details later.

**Comment by terrytangyuan** [comment]
Looks good. Thanks!

**Comment by thirdwing** [comment]
@terrytangyuan BTW, are you willing to be a co-mentor?

**Comment by terrytangyuan** [comment]
Sure. :-)

**Comment by Puriney** [comment]
Here linked is a RNN model learning 8-digit binary addition, which is implemented in Rcpp. Though not high-level implementation, it might be helpful for some others who want to participate in this GSOC project, as Cpp/Rcpp is much involved.

See: https://gist.github.com/Puriney/072a37ea8a181f0b6168

I have great interest in GSOC. If possible, could your mentors list easy->medium->hard tests?

**Comment by thirdwing** [comment]
Maybe you can try an easy/medium/hard issue.

**Comment by terrytangyuan** [comment]
@thirdwing Looks like we are not registered as a organization for GSoC. We cannot co-mentor for one project.

**Comment by thirdwing** [comment]
We are under R project.

**Comment by terrytangyuan** [comment]
Oh I missed your last email. I will communicate with you there then.

**Comment by terrytangyuan** [comment]
@ziyeqinghan Any status update?

**Comment by terrytangyuan** [comment]
Sorry I missed the communications. I think I can close this now. Thanks! @ziyeqinghan
