### ISSUE TITLE
An fatal error occurred in asynchronous engine operation.

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1421]
I tried to modify fcn-xs example. Actually I am trying to implement a simplified version, so I replaced the deconvolution layer with an upsampling layer. But I got this error. Pretty sure this is due to the upsampling layer because I remove this layer and do several forward, nothing happened. The specific info is:
```
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
libc++abi.dylib: terminating with uncaught exception of type dmlc::Error: [10:21:37] src/engine/./threaded_engine.h:295: [10:21:37] src/operator/./deconvolution-inl.h:260: Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 176203776 Bytes
```
To simply the problem, I only used forward, and my symbol is defined as:
```
bigscore = mx.symbol.UpSampling(score, num_filter=21, scale=32, sample_type="bilinear", num_args=2, name="bigscore")
```
The last layer before this upsampling layer is a fully convolutional layer, which will generate a score map like b*21*w*h. So what is going on here?

**Comment by ascust** [comment]
The score map has shape "batchsize x 21 x heigh x width". This is what I want to upsample.

**Comment by piiswrong** [comment]
bilinear upsampling internally calls deconvolutional layer. You need larger workspace for deconvolutional layer. Currently there is no interface for  that. You need to change the c++ code.
