### ISSUE TITLE
mistakes in mxnet

### ISSUE THREAD

**Issue by 501177639** [dmlc/mxnet#1423]
https://github.com/dmlc/mxnet/blob/master/src/c_api/c_api.cc#L1308    line1308,  is *reinterpret_cast<NDArray*>(outputs[i]))); ? 

https://github.com/dmlc/mxnet/blob/master/src/operator/cudnn_batch_norm.cu#L132  line132
is cudnnbatchnorm::kGamma ?

**Comment by piiswrong** [comment]
NDArrayHandle is defined as void* so the first one is correct.
The second one is indeed a mistake. Thanks for reporting the error.

**Comment by 501177639** [comment]
the first one is inputs[i]?  I think it's outputs[i]

**Comment by 501177639** [comment]
*reinterpret_cast<NDArray*>(outputs[i])));

**Comment by piiswrong** [comment]
ok. I see what you mean.
