### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1427]
I tried to use fcn to do image segmentation. I got a "cuda out of memory" error. What's weird is that, I can do forward and backward without any error. Only when I do update to update weights. Then I narrowed the problem down to this update function, which in my case is a sgd optimizer update function. Then I continued to track the problem, I found as long as I did not update the layer " fc6", which is a fully convolutional layer with 4096 filters and 7x7 filer size. I can update the rest without any problem, and the memory usage is only aroung 3g (4g graphic card). Then I dag further, I found the problem was due to the update function where "mom[:] +=-lr*(grad+wd*weight)". If I update that layer, the program will pop up the error and the memory did get full. If I remove this, everything is fine. Below is the error info:
```
./dmlc-core/include/dmlc/logging.h:241: [16:53:53] ./mshadow/mshadow/./tensor_gpu-inl.h:44: Check failed: e == cudaSuccess CUDA: out of memory
[16:53:53] ./dmlc-core/include/dmlc/logging.h:241: [16:53:53] src/engine/./threaded_engine.h:295: [16:53:53] ./mshadow/mshadow/./tensor_gpu-inl.h:44: Check failed: e == cudaSuccess CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [16:53:53] src/engine/./threaded_engine.h:295: [16:53:53] ./mshadow/mshadow/./tensor_gpu-inl.h:44: Check failed: e == cudaSuccess CUDA: out of memory
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)
```
Does all of this make sense? In my opinion, if we can do forward and backward successfully, it means, the memory will be enough, so why this update function caused this out of memory error?

**Comment by piiswrong** [comment]
sgd need to store momentum, which basically double the memory needed by parameters. python sgd also need intermediate variables. using ccsgd might solve the problem as it doesn't need intermediate variable, but it still need to store momentum.
