### ISSUE TITLE
Error when loading image record with Chinese names

### ISSUE THREAD

**Issue by LiamZhuuu** [dmlc/mxnet#1448]
I always came across encoding error when loading image record with Chinese names.
But I solved this by changing line 91 in `base.py`
from
```
return ctypes.c_char_p(string.encode('utf-8'))
```
to
```
return ctypes.c_char_p(string)
```

**Comment by piiswrong** [comment]
Usually you don't want any non ascii character in your path specially if you are using windows. Dealing with this across platforms and python version is a nightmare so I don't think we are going to support it.
