### ISSUE TITLE
When to use wait_to_read()?

### ISSUE THREAD

**Issue by horserma** [dmlc/mxnet#1452]
Hi, 
I found in fcn-xs example, it calls a function "wait_to_read" at the end of a batch training. What is the point of using this. I read the document about this, but was still confused about where and when to use this. Could anyone explain this to me? Really appreciate it

**Comment by piiswrong** [comment]
It's for syncing with engine, which is asynchronous. You don't need to explicitly call it for most of the use cases.

**Comment by horserma** [comment]
Ok, but would you give me an example when to use this? Like the fcn-xs example, why is this called. If I dont call it, would there be any potential danger? Thank you @piiswrong

**Comment by tqchen** [comment]
```wait_to_read``` means block until results of the array is available. Usually you don't have to call it. 
Note that if you copy data out, e.g.
```
b = a.tonumpy()
```

```wait_to_read``` is automatically called. There is only one  reason you need to call this function: you are doing a loop, and you do not want to go too fast. Because mxnet is an async engine, and if there is no blockings, wait_to_read can be called so not too many ops will swarm the engine. 

Of course, even this can be eliminated if we limit the ops can be pushed to engine(which we did not yet do)

**Comment by tqchen** [comment]
In normal cases, after each iteration, usually we will do
```
pred = exec.output[0].copyto(mx.cpu()).asnumpy()
logging.info("evaluation=%g", evaluate(pred, label))
```
This means the blocking is already introduced and not explicit wait to read is needed

**Comment by horserma** [comment]
Ok, thanks

**Comment by horserma** [comment]
I still got a little confused about how this asyncing engine works. For example, if I just want to do forward , backward and update the arguments without getting the output and calculating the accuracy etc. Like this:
```
executor = net.simple_bind(...)
data in dataIter:
	executor.arg_dict['data'][:] = mx.nd.array(...)
	executor.arg_dict['label'][:] = mx.nd.array(...)
	executor.forward(is_train=True)
	executor.backard()
	for key in update_dict:
		updater(...)
	#dont take the output and update the metric.
```
The above code is what I mean. In this case, would it cause any problem? Since I found this could make the training much faster if I remove the updating metric, I am wondering if I could do this without messing up the training. @tqchen @piiswrong

**Comment by tqchen** [comment]
Yes, this is totally valid. However, this may not necessarily mean training is faster. Because no synchronization with engine is made, the timer metric only means these async calls are issued, but not necessarily finished. Having the metric update enforce the synchronization, so the timer metric is more reasonable

**Comment by horserma** [comment]
In my case, I do image segmentation using fully convolutional networks. For the memory reasons, I use batch size 1. I found if I calculate the accuracy after every batch, It would take 2s for each sample. However, if I remove the metric updating part and just forward, backward and update, it would increase the speed to 0.5s for each sample. It could make a big difference. so that is why I asked this question. It seems waiting for the engine to get synchronized takes too much time. Does it make sense?

**Comment by tqchen** [comment]
closing this issues. If computation overhead is indeed small, then avoid frequent sync makes sense.

**Comment by horserma** [comment]
@tqchen Since I am still confused about this async engine, may I ask you one more question? Like you said before, executor.outputs[0].copyto(mx.cpu()).asnumpy() will force the engine to sync. So if I have two parts in my network, which means two executors, e1 and e2. The whole training process can be described as:
e1.forward(is_train=True)
output1 = e1.outputs[0].copyto(mx.cpu()).asnumpy()
...process output1 and get input2 for e2...
e2.arg_dict["data"][:] = input2
e2.forward(is_train=True)
output2 = e2.outputs[0].copyto(mx.cpu()).asnumpy()
...calculate gradients for output2 say grad2...
e2.backward(mx.ndarray.array(grad2))
data_grad = e2.grad_dict["data"].copyto(mx.cpu()).asnumpy() //get gradients for data
...process data_grad and get grad_output1 for e1...
e1.backward(mx.ndarray.array(grad_outpu1))
for arg in update_list:
updater(...)

So is this the correct way of doing this? Since I used too many copyto(mx.cpu()) to force the sync, would this cause any slow-down? If this is non-optimal, what is the best way to implement this? Thank you very much.
