### ISSUE TITLE
Problem reproducing resnet

### ISSUE THREAD

**Issue by superzrx** [dmlc/mxnet#1456]
Hi guys,
    Recently I was trying to reproduce the result of resnet following configure from kaiming/fb but encountered some problem...

I tried two experiments with 50 layers resnet: 
1) network configure following kaiming, 192 batchsize on 6 gpus, bn before add, wd on weight only, muti-scale in [250,480], global shuffle. Change lr manually. Note as s0
2) network configure following fb, 256 batchsize on 4gpus, bn after add, wd on weight and bias, multi-scale in [250,480], global shuffle. Change lr every 30 epoch. Note as s1

![qq 20160213155740](https://cloud.githubusercontent.com/assets/9104795/13027225/296c9e36-d281-11e5-822f-ba14da734d88.png)

I encountered great overfitting when lr is changed from 0.1 to 0.01... Do anybody has some ideas?

**Comment by piiswrong** [comment]
@antinucleon

**Comment by tornadomeet** [comment]
@superzrx hello, i have reproduced resnet-50,  https://github.com/tornadomeet/ResNet, you can check that.

**Comment by superzrx** [comment]
@tornadomeet Great work!
