### ISSUE TITLE
I load a checkpoint showing GPU is not enabled.

### ISSUE THREAD

**Issue by horserma** [dmlc/mxnet#1471]
I trained a model with GPU. However, when I tried to load this model on another one without GPU support, it popped up the error that GPU is not enabled. It seems the model file encodes the context information. So to this end, what is a generally good solution? Should I copy everything from GPU to CPU and then save the model? or maybe I think there could be a parameter that can control this. After all, not every computer can use GPU. Looking forward to good advice.

**Comment by tornadomeet** [comment]
@horserma , you are wright, save funtion in ndarray contains the context information, which will bring pullze some time.
@tqchen @piiswrong how about change the design that save the model with ctx=mx.cpu() by default?

**Comment by piiswrong** [comment]
Saving NDArrays with ctx=cpu sounds good.
Some symbols however behaves differently on cpu vs gpu. I'm not sure if this will cause problems.

**Comment by horserma** [comment]
@tornadomeet @piiswrong I agree, I think it would be a good idea to separate context info and parameter values. Then we always load the parameters into cpu memory and initialise the model based on the specific context.

**Comment by tqchen** [comment]
This is not yet changed in spec. For temp solution, what we do is always explicitly copy to cpu before serialization
