### ISSUE TITLE
Multi-Label Training With Variable Label-width

### ISSUE THREAD

**Issue by twtygqyy** [dmlc/mxnet#1476]
I'm wondering if the current  Data Iterator could support flexible number of label for a single image, for example:
```
0 label1 path_to_image1
1 label1 label2 path_to_image2
2 label3 label4 label5 path_to_image3
```
or it is possible to fix the label-width while put NULL in none-label place,such as:
```
0 label1 NULL NULL NULL NULL path_to_image1
1 label1 label2 NULL NULL NULL path_to_image2
2 NULL NULL label3 label4 label5 path_to_image3
```

**Comment by piiswrong** [comment]
You need your own data iter with bucketing for this. Because the graph is different each time.

**Comment by twtygqyy** [comment]
@piiswrong Thanks for the reply, could your share me some more information about it? Any samples about how I can create it by myself?
