### ISSUE TITLE
New Issue in FCN-XS example!

### ISSUE THREAD

**Issue by Rafel-Mou** [dmlc/mxnet#1477]
Hi all,

I originally ran the fcn-xs example well, but I met the errors when I updated mxnet this morning. The issue is following:

INFO:root:Namespace(epoch=27, init_type='fcnxs', model='fcn8s', prefix='FCN16s_VGG16', retrain=False)
INFO:root:Start training with gpu(0)
Traceback (most recent call last):
  File "fcn_xs.py", line 73, in <module>
    main()
  File "fcn_xs.py", line 57, in main
    epoch_end_callback  = mx.callback.do_checkpoint(fcnxs_model_prefix))
  File "/home/x/xx/solver.py", line 71, in fit
    aux_states=self.aux_params)
  File "/home/xxx/mxnet/python/mxnet/symbol.py", line 718, in bind
    args_handle, args = self._get_ndarray_inputs('args', args, listed_arguments, False)
  File "/home/xxx/mxnet/python/mxnet/symbol.py", line 585, in _get_ndarray_inputs
    raise ValueError('Must specify all the arguments in %s' % arg_key)
ValueError: Must specify all the arguments in args

Could anyone please tell me what's wrong with it? Thanks a lot in advance!

**Comment by piiswrong** [comment]
@pluskid Possibly due to the recent executor manager refactor?

**Comment by pluskid** [comment]
I don't see a connection, it seems the fcn-xs example is not using the `FeedForward` model API. This might be due to incompatibility between the saved model in the checkpoint file and the model trying to use. Could you double check that `args.model` is the same as what you saved for checkpoints? If it doesn't resolve the issue, maybe before the line
```
raise ValueError('Must specify all the arguments in %s' % arg_key)
```
in `symbol.py`, add a line that `print(name)` could help diagnosing.

**Comment by Rafel-Mou** [comment]
@pluskid I add `print(name)` before ValueError line and it shows 'bigscore_bias'. What dose that mean? Thanks.

**Comment by pluskid** [comment]
@Rafel-Mou I'm not sure. It says that you are trying to initialize an executor but the variable `bigscore_bias` is not provided. Are you running from scratch or loading some existing models?

**Comment by tornadomeet** [comment]
@Rafel-Mou , do you use the original code in fcn-xs example? because big_score lie only in deconvolution operator, and bias is not included by default, so we there is no name bigsocre_bias, i think you may use your own code, pleanse refere this line: https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/symbol_fcnxs.py#L140

**Comment by Rafel-Mou** [comment]
@tornadomeet  Hi, Mr. OriginalAuthor. :D I use the original code in the example directly and do not make any changes. Formerly I can run the code well, but this error happens after I update mxnet the day before yesterday...

**Comment by Rafel-Mou** [comment]
@tornadomeet Hi, Mr. OriginalAuthor. :D I use the original code in the example directly and do not make any changes. Formerly I can run the code well, but this error happens after I updated mxnet the day before yesterday...

**Comment by Rafel-Mou** [comment]
@pluskid I'm running from scratch.

**Comment by tornadomeet** [comment]
@oh, i see it here: https://github.com/dmlc/mxnet/commit/27a338234cecdad0d1499f693974bc2749edc396
@piiswrong has changed the default no_bias from faluse to true, but in deconvolution, we usually not use bias like in caffe. so can you @Rafel-Mou give a pr for these, that is set no_bias = True?

**Comment by Rafel-Mou** [comment]
@tornadomeet  Could you please tell me which part of code that I should change? Thsnks!

**Comment by Rafel-Mou** [comment]
@tornadomeet  I get it done! I set `DMLC_DECLARE_FIELD(no_bias).set_default(true)` instead of `DMLC_DECLARE_FIELD(no_bias).set_default(false)` in `convolution-inl.h` and `deconvolution-inl.h` according to your suggestion. Thanks.

**Comment by tornadomeet** [comment]
@Rafel-Mou only need change in deconvolution-inl.h, not convolution.
because someone may changes the code in the newest mxnet, you may use my branch: https://github.com/tornadomeet/mxnet/tree/seg

**Comment by Rafel-Mou** [comment]
@tornadomeet  Okay, thank you. :)
