### ISSUE TITLE
error occured when make the mxnet

### ISSUE THREAD

**Issue by zjubxl123** [dmlc/mxnet#148]
In file included from src/engine/threaded_engine_pooled.cc:11:0:
src/engine/./threaded_engine.h:250:3: error:   overriding ‘virtual mxnet::engine::ThreadedEngine::~ThreadedEngine() noexcept (true)’
Makefile:94: recipe for target 'build/engine/threaded_engine_pooled.o' failed
make: *** [build/engine/threaded_engine_pooled.o] Error 1

**Comment by tqchen** [comment]
Can you check your compiler version? We need g++-4.8

**Comment by zjubxl123** [comment]
thanks, tqchen, that is the problem of g++ version. Now it is installed successfully
