### ISSUE TITLE
too slow for packing image in tools/im2rec.py?

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#1487]
hi,happy new year! I have a very large image dataset in my ssd filesystem( 6 core cpu), im2rec.py with thread pool (20 thread)run slowly(40 image /s), the cpu just only use one core,   can I modify it to true multiprocessing and feed back? my code can pack image more than 1000 image/s in ssd

**Comment by piiswrong** [comment]
Hi,
multi threading is difficult with Python due to GIL, so I didn't do it. You are welcome to submit a PR on this.

**Comment by junranhe** [comment]
ok, I submit it now~
