### ISSUE TITLE
example/numpy-ops/numpy_softmax.py seems not working properly?

### ISSUE THREAD

**Issue by shengwa** [dmlc/mxnet#1489]
I just tried this file, but it reports the following error:

`mxnet.base.MXNetError: [04:25:36] src/symbol/graph_executor.cc:887: Check failed: (info.ref_count) == (0) Because the last operator is not Loss function, head_gradient is required in calling backward.`

Since the `__init__` has set the `need_top_grad` as `False`, I don't understand why the last operator is still not a loss function.

**Comment by piiswrong** [comment]
This file works fine for me. Could you try git pull && git submodule update && make clean && make?

**Comment by shengwa** [comment]
@piiswrong Thank you so much...I tried this and it is working.
