### ISSUE TITLE
R package 'mxnet': shared object ‘libmxnet.so’ not found

### ISSUE THREAD

**Issue by UBod** [dmlc/mxnet#1491]
Hi,

I have tried to install the 'mxnet' R package on a Linux server running CentOS with cuda and cuDNN. After the necessary changes to `make/config.mk`, the compilation of the project and building of `libmxnet.so` went fine. Building the R package tarball `mxnet_0.5.tar.gz` also went fine and this tarball correctly contains `libmxnet.so` in `inst/libs`. However, when I try to run `R CMD INSTALL mxnet_0.5.tar.gz`, I get the following:

```
> g++ -I/system/apps/biosoft/R-3.2.2/lib64/R/include -I/system/apps/biosoft/R-3.2.2/lib64/R/include/x86_64 -DNDEBUG -I../inst/include -I/system/apps/biosoft/zlib-1.2.8/include -I/system/apps/biosoft/curl-7.45/include -I"/system/user/bodenhof/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"   -fpic  -g -O3 -m64  -c symbol.cc -o symbol.o
> g++ -shared -L/system/apps/biosoft/R-3.2.2/lib64/R/lib/x86_64 -L/system/apps/biosoft/acml4.4.0/gfortran64_mp/lib -lacml_mp -lacml_mv -L/system/apps/biosoft/curl-7.45/lib -o mxnet.so executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o -L/system/apps/biosoft/R-3.2.2/lib64/R/lib/x86_64 -lRlapack -L/system/apps/biosoft/R-3.2.2/lib64/R/lib/x86_64 -lRblas -L/system/apps/biosoft/R-3.2.2/lib64/R/lib/x86_64 -lR
> installing to /system/user/bodenhof/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs/x86_64
> ** R
> ** demo
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> Error : .onLoad failed in loadNamespace() for 'mxnet', details:
>   call: library.dynam("libmxnet", pkgname, libname, local = FALSE)
>   error: shared object ‘libmxnet.so’ not found
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing ‘/system/user/bodenhof/R/x86_64-pc-linux-gnu-library/3.2/mxnet’
> * restoring previous ‘/system/user/bodenhof/R/x86_64-pc-linux-gnu-library/3.2/mxnet’
> 
```

I also ran `R CMD INSTALL mxnet_0.5.tar.gz --no-test-install` to see if libmxnet.so is in the directory where the R package is stored, and it seems it's there. I also set `LD_LIBRARY_PATH` such that all cuda libs are in the right search path.

Any ideas what went wrong?

Thanks in advance,
Ulrich

**Comment by thirdwing** [comment]
Can you tell me what changes you have made and what you have done?

The information you provide here is not enough for us to find the problem.

**Comment by UBod** [comment]
Ok, I am trying to recover the exact sequence of what I have done. I basically followed the installation instructions for `mxnet` and the `mxnet` R package, plus some changes to `make/config.mk`:

1. I downloaded mxnet from github.
2. I made the following changes to `make/config.mk:` (a) `USE_CUDA = 1`, (b) `USE_CUDA_PATH = /usr/local/cuda,` (c) `USE_CUDNN = 1`, (d) `USE_OPENCV = 1`, (e) `USE_BLAS = mkl`, (f) `USE_INTEL_PATH = /system/apps/biosoft/intel/mkl-11.1/`
3. Then I ran make. It completed without any error.
4. Then I followed the instructions on R package installation. Everything went fine and `mxnet_0.5.tar.gz` was created without any error.
5. When I tried to run R` CMD INSTALL mxnet_0.5.tar.gz`, the error mentioned in my original post popped up.

Is that sufficient information? What else would you need? Should I send you my `mxnet_0.5.tar.gz` or `config.mk`?

Thanks in advance,
Ulrich

**Comment by UBod** [comment]
I'm not sure if that helps, but I tried to research a bit further into this. I installed the R package with option `--no-test-load` to check out where files are placed and what they look like. It turned out that the two shared objects are placed as follows:
```

> ~/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs/libmxnet.so
> ~/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs/x86_64/mxnet.so

```

Note that, on another system (a x86_64 laptop with Ubuntu and without cuda; everything works nicely on this one), it looks as follows:
```

> ~/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs/mxnet.so
> ~/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs/libmxnet.so

```
So it seems that, in contrast to the one system on which it works, the two shared objects are in different directories. I then made symbolic links such that both objects are found in both directories `~/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs/` and `~/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs/x86_64`. Voilá, the package could be loaded. I still have some issues related to the ACML library that is linked into my R version, but I will first try to solve those myself. And they are certainly unrelated to the problem discussed in this thread.

**Comment by thirdwing** [comment]
I have to say I don't why CentOS has a different directory structure from Ubuntu.

But this should be the reason that R can't find the lib.

**Comment by UBod** [comment]
Maybe it's because of the `r_arch` option that is used when R is built on that platform. I will talk to the guy who is in charge of that. Thanks so far for your kind help!

**Comment by thirdwing** [comment]
Really little experience on CentOS.

On Wed, Feb 17, 2016 at 10:48 AM, UBod <notifications@github.com> wrote:

> Maybe it's because of the r_arch option that is used when R is built on
> that platform. I will talk to the guy who is in charge of that. Thanks so
> far for your kind help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1491#issuecomment-185265590>.
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by thirdwing** [comment]
Closing this now. Feel free to reopen.
