### ISSUE TITLE
How to update input data in each iteration?

### ISSUE THREAD

**Issue by CNevd** [dmlc/mxnet#1496]
I want to update the input data along with the weights and bias in each iteration. how can i calculate the grad of input features and update them in each iteration?  any one has some suggestions?

**Comment by piiswrong** [comment]
Checkout the adversarial example.

**Comment by CNevd** [comment]
I found the data used for each iteration is ( for data, label in train_iter ), if i update some features in the first iteration will it change data in next iteration?  I want to represent each feature with a n-dim vector, and update the vector in  each iteration, so the follow-up data can be represented by the newest vector
