### ISSUE TITLE
[io] Segfault when a path do not exist

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#150]
When IO reader points to a path that do not exist, the result is a segfault instead of a dmlc::Error that throws out and catched by python env.

Need to check the cause, whether it is dmlc-core input split api, or doing loading in constructor that did not mark noexcept(false).

**Comment by sneakerkg** [comment]
We've already checked when GetPathInfo, but when the code runs into the check_fail, there will be a python error. Need check further.

**Comment by tqchen** [comment]
Could due to the error was throw by a child thread that opens the data. The exception throw in the child thread could not be automatically catched by the master thread
