### ISSUE TITLE
No "include" folder in 20160216_win64_gpu.7z

### ISSUE THREAD

**Issue by dave5556** [dmlc/mxnet#1501]
Hello,

I'm trying to install MXNet with GPU support in R. As per the installation instructions I need to take the include folder from 20160216_win64_gpu.7z and paste it in mxnet/R-package/inst. I tried using the include folder from the previous version but was having trouble. Am I missing something?

Thank you!

**Comment by hjk41** [comment]
Sorry about that... I just re-uploaded the packages. It is ok now.

On Thu, Feb 18, 2016 at 1:09 AM, dave5556 <notifications@github.com> wrote:

> Hello,
>
> I'm trying to install MXNet with GPU support in R. As per the installation
> instructions I need to take the include folder from 20160216_win64_gpu.7z
> and paste it in mxnet/R-package/inst. I tried using the include folder from
> the previous version but was having trouble. Am I missing something?
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1501>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by dave5556** [comment]
Thank you
