### ISSUE TITLE
Output different between GPU and CPU.

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [dmlc/mxnet#1506]
I am coding with c_api and I am trying to do feature extract with a pre-trained model (in the model gallery).

Everything seems good except that the output feature vectors changes when I change the global context(from GPU to CPU and vice versa).
And the differences are huge.

I've been debugging the code for a while and not be able to solve it.
Could someone tells me some possible causes?

Thanks a lot~

**Comment by piiswrong** [comment]
Which platform are you working on?
Could you try to locate the layer that is causing this?

**Comment by zhangchen-qinyinghua** [comment]
My platform:
Red Hat 4.4.7-4.
Linux version 2.6.32-431.el6.x86_64.

The only difference in the code is kCPU or kGPU.

I wondered it was because of the data copy between CPU and GPU,  so I add ndarray_wait_all() everywhere, but it seems not to be the answer.

**Comment by piiswrong** [comment]
Try running only the first layer, then the first two. See if you can locate the layer that cause mismatching results.

**Comment by zhangchen-qinyinghua** [comment]
@piiswrong 
Thanks for your suggestion.
I'll try that.

**Comment by zhangchen-qinyinghua** [comment]
Seems CPU are giving a wrong results?
The output of bn_conv1_output given by CPU are all -6.85604e+09.
While the GPU results are a lot more resonable.
(The output of conv_conv1_output of GPU and CPU are identical)

What will this mean?

The first few layers of the model:
```
[16:48:26] feature_extract.cpp:26: data
[16:48:26] feature_extract.cpp:26: conv_conv1_weight
[16:48:26] feature_extract.cpp:26: conv_conv1_bias
[16:48:26] feature_extract.cpp:26: conv_conv1_output
[16:48:26] feature_extract.cpp:26: bn_conv1_gamma
[16:48:26] feature_extract.cpp:26: bn_conv1_beta                                                                                                             
[16:48:26] feature_extract.cpp:26: bn_conv1_output
```

**Comment by zhangchen-qinyinghua** [comment]
So I find the cause.
I didn't load the aux parameters from the Model.

close the issue.

**Comment by MengWangTHU** [comment]
Hi，I am tring to use C++ to extract feature from middle layer,which is so easy in Python(such as API：get_internals), but I don't know how to implement it in C++. Could you please share your idea or code ?Thanks a lot!
