### ISSUE TITLE
Can I remove the union definition in struct LinkedList?

### ISSUE THREAD

**Issue by happynear** [dmlc/mxnet#151]
In object_pool.h, line 48, there is a struct with a union in it:
```
  struct LinkedList {
    union {
      LinkedList* next{nullptr};
      T t;
    };
  };
```
In my environment (VS2013), the compiler cannot accept a union containing a class with a copy constructor. Can I remove the union definition, such as 
```
  struct LinkedList {
      LinkedList* next{nullptr};
      T t;
  };
```
, or I must use boost::variant to replace it?

**Comment by tqchen** [comment]
No, you cannot remove the union def, I think you can move the type T ahead of the next, and see if that works for you. To change it to

```
 struct LinkedList {
      T t;
      LinkedList* next{nullptr};
  };
```

**Comment by happynear** [comment]
Thanks, now I come across an invalid pointer problem and it's difficult to debug. 
I will keep an eye on mxnet and try again after it is formally released.

**Comment by happynear** [comment]
I have found where the invalid pointer locates.
In `ndarray.h`, line `470`:
```
  inline NDArrayFunctionReg &set_function(void fsetvalue(const real_t &rhs,
                                                         NDArray *out)) {
    body = [fsetvalue] (NDArray **used_vars, real_t *s, NDArray **mutate_vars) {
      fsetvalue(s[0], mutate_vars[0]);
    };
```
When the program goes to `fsetvalue`, it seems that the `fsetvalue` is no longer the one registered to function list. When I replace the formal paramter with std::function, the problem solved. 
```
  inline NDArrayFunctionReg &set_function(std::function<void (const real_t &rhs,
    NDArray *out)> fsetvalue) {
    body = [=](NDArray **used_vars, real_t *s, NDArray **mutate_vars) {
      fsetvalue(s[0], mutate_vars[0]);
    };
```
I started to learn C++11 just a few days ago, so I don't know why it works.

**Comment by tqchen** [comment]
Interesting, Thanks for investigation! There is nothing that I am aware of preventing us using function pointer instead of std::function. This might due to the fact that the registered ScalatSetValueOp was an inline function. 

I updated the code in #160  Please check the updated code after it merged in

**Comment by happynear** [comment]
I am sadly to say, removing `inline` does not work. The two pointer adress are still different.

![qq 20150928212643](https://cloud.githubusercontent.com/assets/3897999/10136548/af853fd0-6627-11e5-923a-76d91904d604.png)
![qq 20150928212704](https://cloud.githubusercontent.com/assets/3897999/10136549/b17ecd92-6627-11e5-92e9-b933283ec4e2.png)

I have written some codes to replace the function pointer with std::function, however, in an inelegant way:
https://github.com/happynear/mxnet/blob/windows/include/mxnet/ndarray.h#L465
https://github.com/happynear/mxnet/blob/windows/src/ndarray/ndarray.cc#L508

I know you guys will find a better solution. I am waiting for it.

**Comment by tqchen** [comment]
OK, this could due to a fact that MSVC do not interpret function as function pointers I have pushed a change in https://github.com/tqchen/mxnet/commit/516a90a68f2d19812be8199a499668833330fe45 to fix  this . Please check if that works for you after it is merged in #181

**Comment by happynear** [comment]
Yes it works. Thank you.

**Comment by tqchen** [comment]
If you are interest, we would love to get your contribution to make mxnet windows compatible with minimum changes. @jermainewang is working on a CMake build script to generate windows solutions, which you may be interested in collaborating

**Comment by happynear** [comment]
I have sent a pull request https://github.com/dmlc/mxnet/pull/183. I created the visual studio solution with imitation of https://github.com/dmlc/cxxnet/tree/master/windows . Please check and merge it.
