### ISSUE TITLE
Is Forward supposed to take less time than Backward?

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1510]
Hi,
I am implementing a fully convolutional network. Unlike the one in the examples, I simply modify the vgg16 by removing the fully connected layers and adding a deconvolutional layer to guarantee the output has the same size as input. I do the simple_bind and everything by myself. Then I found a problem. During the training, it takes approximately 0.87s for each sample (in my case, the batch size is 1 and input size is 512 after random crop.). After training, I use the evaluation set to do inference. The speed is about 0.4s for each sample.
This makes me curious. In my opinion, the inference should be far faster than training since it doesnt need to calculate the derivatives. However, this seems the inference speed is not what I expected. Could anyone explain to me if it is normal or not?

**Comment by piiswrong** [comment]
yes forward is less expensive than backward.

**Comment by ascust** [comment]
so even "is_train=False"? So what is the point of setting this flag? @piiswrong

**Comment by piiswrong** [comment]
Some layer's behavior is different depending on this flag.
