### ISSUE TITLE
use mxnet model in spark

### ISSUE THREAD

**Issue by Yunrui** [dmlc/mxnet#1521]
Hi folks, 

Are there any examples/libs to be used to load mxnet model in spark and do classification? 

Actually, I have two computing clusters, smaller one has mxnet installed with GPU support, and the other is production spark/yarn cluster without GPU. I am using the smaller one to train mxnet models. And trying to figure out how to reload the model into my spark cluster to do real online classification job.

So, I think there should be a scala/java mxnet library, which I could include into my spark job. Can anyone forward me any examples or instructions?

Thanks in advance!

**Comment by tqchen** [comment]
I think this is related to #842

**Comment by Yunrui** [comment]
Yes, thanks, which check that issue.
