### ISSUE TITLE
MXNET requires computer with GPU installed

### ISSUE THREAD

**Issue by RishabGargeya** [dmlc/mxnet#1530]
Hi all,

This issue references issue #1385 wherein mxnet currently cannot be loaded on a computer that does not have a gpu installed if mxnet is compiled with the CUDA option.

Is there a possibility for a workaround or fix/update? It would be handy to be able to run the same installation of mxnet on a cpu only node when running tests on computing clusters where you have to reserve hardware.

**Comment by piiswrong** [comment]
It's very hard. I think the best way to handle this now is to compile both version under 2 folders and set path depending on whether the current machine has GPU.

**Comment by RishabGargeya** [comment]
Thanks for the advice, I guess that really is my only option.
