### ISSUE TITLE
Logging multiple metrics

### ISSUE THREAD

**Issue by RishabGargeya** [dmlc/mxnet#1531]
Hi,

I was just wondering if anyone could point me to an example of how to log multiple metrics when fitting a network. The fit function seems to only take one function in the eval_metric parameter, so I was wondering how to record multiple metrics.

Thanks for your time.

**Comment by shengwa** [comment]
You can modify the eval_metric in `model.py` and `callback.py` into python list so you can see multiple evaluation metrics.
Here is the link of the gist where I modified the two files, you can take a look.
[https://gist.github.com/shengwa/35f523c06ca978c2edbd](url)

**Comment by taoari** [comment]
I think making the metric allow composition would be more elegant. For example, we can use `mx.metric.Accuracy() + mx.metric.MSE()` to generate a new instance of `EvalMetric`. And hence it directly applies for current API.

**Comment by rohun-tripathi** [comment]
> You can modify the eval_metric in `model.py` and `callback.py` into python list so you can see multiple evaluation metrics.
> Here is the link of the gist where I modified the two files, you can take a look.
> https://gist.github.com/shengwa/35f523c06ca978c2edbd

This could work, but not without making changes to mxNet, which could be being used by others. Is there a cleaner solution
