### ISSUE TITLE
Function to Print Out Network Architecture

### ISSUE THREAD

**Issue by RishabGargeya** [dmlc/mxnet#1541]
Is there a convenient, general function to use for printing out the network architecture and data shapes as it passes through each layer?
If not, how would I go about creating one?

Thanks for your help. I greatly appreciate the work you guys have done on this project.

**Comment by piiswrong** [comment]
mxnet.viz.plot_network

**Comment by RishabGargeya** [comment]
Is there a way to maybe tabulate the output so it can be printed out?

**Comment by javelinjs** [comment]
How about symbol.tojson() ?
