### ISSUE TITLE
How to continue training in R?

### ISSUE THREAD

**Issue by slaweks17** [dmlc/mxnet#1543]
Hi, 
I would like to create a model, run it a bit, check how things are going, perhaps modify some parameters, like learning rate, and continue learning. Or alternatively load from a checkpoint and continue learning.
Is it possible? I am especially interested in R and C++.
I found something related in issue 379, but it the answers were referring to the Python interface.

**Comment by firearasi** [comment]
+1, this is still open?

**Comment by ziyeqinghan** [comment]
I have tried to solve this problem in PR #1571 and hope this will be helpful. :)
