### ISSUE TITLE
Can't use the "old data" to train alexnet.

### ISSUE THREAD

**Issue by jzxx** [dmlc/mxnet#1547]
I use the mxnet with "dmlc-core/src/io/input_split_base.cc" updated to train an alexnet model.
The data is packed with the old version mxnet's "im2rec.cc" which work well on the old version mxnet.
But when I try to use the new version mxnet to train the model, there are some errors occur.

> ./dmlc-core/include/dmlc/logging.h:241: [00:20:36] src/io/input_split_base.cc:157: Check failed: (files_.size()) != (0) Cannot find any files that matches the URI patternz ./data/train.rec

What should I do to solve this problem?
 Thanks a lot.

**Comment by piiswrong** [comment]
your path is '/data/train.rec'.
Try removing the leading '/' if it's not intended.

**Comment by jzxx** [comment]
Thanks for your reply. This is not the problem. I just write '/data/train.rec' to indicate my data-dir.
