### ISSUE TITLE
 CUDA: out of memory

### ISSUE THREAD

**Issue by zynbasil** [dmlc/mxnet#1550]
mxnet.base.MXNetError: [16:52:49] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory

**I check by inception_memcost.py:**

**************************
....
....
batch_size = 1
texec = softmax.simple_bind(ctx=mx.cpu(),
                            data=(batch_size, 3, 256, 256),
                            grad_req=grad_req)

**Total 9 MB allocated**
**************************
when I change cpu() to gpu()
....
....
batch_size = 1
texec = softmax.simple_bind(ctx=mx.gpu(),
                            data=(batch_size, 3, 256, 256),
                            grad_req=grad_req)

mxnet.base.MXNetError: [16:52:49] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory

why??help~~~

**Comment by tqchen** [comment]
The memory estimation is only on node cost, the actual cost can be higher than the node cost, because temp space are needed for convolution and cudnn
