### ISSUE TITLE
MxNet (pre-built packages) in Windows 10 cannot run "mnist".

### ISSUE THREAD

**Issue by Johnkuo** [dmlc/mxnet#1559]
I installed MxNet (pre-built packages) in c:\MxNet and Anaconda 2.5.0.
After the Python Package Installation ("import mxnet as mx", "a=mx.nd.zeros((2,3)", "print(a.asnumpy())" are no problem) and copy source code to c:\Mxnet, I used "python example/image-classification/train_mnist.py" to test it. However, I got results like that:

Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000)
命令语法不正确。
Traceback (most recent call last):
  File "train_mnist.py", line 130, in <module>
    train_model.fit(args, net, get_iterator(data_shape))
  File "C:\MxNet\example\image-classification\train_model.py", line 44, in fit
    (train, val) = data_loader(args, kv)
  File "train_mnist.py", line 63, in get_iterator_impl
    _download(args.data_dir)
  File "train_mnist.py", line 10, in _download
    os.chdir(data_dir)
WindowsError: [Error 2] : 'mnist/'

Did I miss something? Thanks very much!

**Comment by thyu** [comment]
I played with the example scripts before on Windows. It seems like that most of the scripts are Linux oriented. 

I guess you do not have the 'mnist' folder created automatically for the data download. Perhaps you can hack the script a bit (or create 'mnist' folder manually) for it to run in Windows.?

**Comment by hjk41** [comment]
right, you need to tweak it a bit. The script will try to find "mnist"
folder, and if it does not exist, it tries to download one with "wget". But
you know, wget does not exist on windows, thus the problem. You can look
into the script and copy the url of the data. Then use your browser to
download the data, extract it to mnist folder, and then it should run just
fine.

On Thu, Mar 3, 2016 at 2:13 AM, thyu <notifications@github.com> wrote:

> I played with the example scripts before on Windows. It seems like that
> most of the scripts are Linux oriented.
>
> I guess you do not have the 'mnist' folder created automatically for the
> data download. Perhaps you can hack the script a bit (or create 'mnist'
> folder manually) for it to run in Windows.?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1559#issuecomment-191355800>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by anxingle** [comment]
It is  a little  **bug **  and do not blame yourself !   The the 11th,12th,13th and other place  write the code :"train-images-idx3-ubyte".....but the database should be "train-images.idx3-ubyte" .<br>
Oh ,I just want to quit and feel so bad! Please give us rookie more code example  as more detailed as possible !

**Comment by Johnkuo** [comment]
After downloading and installing the mnist dataset manually, it works well right now.
Thanks very much!
