### ISSUE TITLE
Strange Reshape Symbol

### ISSUE THREAD

**Issue by oneengineer** [dmlc/mxnet#1564]
Assume the input data(X) is image, let say 3 channel image, then one image's could be (3,32,32).
If I have 1234 images, then X has shape (1234,3,32,32).

If I apply `mx.symbol.Reshape` on X, what I hope to reshape is the shape of one image,i.e. shape (3,32,32).
However `mx.symbol.Reshape` seems to ask to provide the shape of the whole batch.
If I want to flat the image(Just for an example, thought I should use Flatten Symbol), I have to write something like

`mx.symbol.Reshape(data=previous_symbol,target = (batch_size,3×32×32))`

But `batch_size` is unknown and undecided.

Should Reshape function be changing one entry instead of the whole batch shape?

**Comment by Godricly** [comment]
according to  [Doc](http://mxnet.readthedocs.org/en/latest/python/symbol.html?highlight=reshape#mxnet.symbol.Reshape) . U can set only the batch_size to zero and the Reshape can compute it given the remain 3 dimensions.
I hope this works for you if u are not trying to to resize your image.

**Comment by oneengineer** [comment]
@Godricly  Yes, you are right. I didn't notice that.
