### ISSUE TITLE
Core dumped when load xgboost after loading mxnet

### ISSUE THREAD

**Issue by NamLQ** [dmlc/mxnet#1566]
Hi! 
This is the error when I load package xgboost after loading mxnet.
```
library(mxnet)
library(xgboost)
```

> [16:59:21] ./dmlc-core/include/dmlc/logging.h:241: [16:59:21] include/dmlc/./registry.h:53: Check failed: (fmap_.count(name)) == (0) libsvm already registered
> terminate called after throwing an instance of 'dmlc::Error'
>   what():  [16:59:21] include/dmlc/./registry.h:53: Check failed: (fmap_.count(name)) == (0) libsvm already registered
> Aborted (core dumped)

Everything is OK when I load xgboost before loading mxnet.

edit: I am using Microsoft R Open 3.2.3, the OS is ubuntu 15.10

**Comment by thirdwing** [comment]
I am afraid that we can't help you if you are using Microsoft R Open. You need to talk with people from Microsoft.

**Comment by NamLQ** [comment]
OK, thanks for your feedback!

**Comment by NickShargan** [comment]
I had the same issue in python 2.7.12 (Ubuntu 16.04). Changing order of importing solve it.

`import xgboost as xgb
import mxnet as mx`
instead of:
`import mxnet as mxi
mport xgboost as xgb`

**Comment by zhanxw** [comment]
On my system, I have to use the revered order:

```
import xgboost as xib
import mxnet as mx

```

PS: I manually installed mxnet and then xgboost.
