### ISSUE TITLE
Input node is not  complete

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#1576]
Hi , I got this error when only using reshape and softmax. And I'm wondering why? 
my input is 
                data (batch_size, time, dim)
                label(batch_size, time)
time is changeable for different batch.

and net is like 
               rsdata= Reshape(data,shape=(0,dim))
               rslabel= Reshape(label,shape=(0,))
               out= softmaxoutput(rsdata,rslabel)

In order to call softmaxoutput, I reshaped them with (0,dim) and (0,) respectively. The reshaped ones are fed into softmax layer. I took dim here as label # to test infershape.
The C++ infershape function did compute the correct output size for both cases. But according the python code, sth is wrong when getting the shapes.

**Comment by piiswrong** [comment]
Could you post a minimal script that reproduces this error?

**Comment by Godricly** [comment]
@piiswrong 
I just checked [#1569](https://github.com/dmlc/mxnet/issues/1569) and found that feed forward net doesn't support 2nd label with 2nd dim greater than 1. I need to rewrite my data iterator and check if that works. I think that will work.
