### ISSUE TITLE
(R) What is the equivalent for mx.symbol.Concat(*[])

### ISSUE THREAD

**Issue by firearasi** [dmlc/mxnet#1578]
concat = mx.symbol.Concat(*[c1x1, c3x3, cd3x3, cproj], name='some name')
in R?
Thanks!

**Comment by thirdwing** [comment]
Please take a look at https://github.com/dmlc/mxnet/blob/master/example/kaggle-ndsb2/Train.R#L14-L19

This should be changed and exported.

Sorry for this.

**Comment by firearasi** [comment]
Thanks!

**Comment by firearasi** [comment]
@thirdwing 

Sorry to reopen again.
But I tried 
`con=list()
    con=c(con,c1x1,c3x3, cd3x3, cproj)
    con$num.args=4
    concat = mx.symbol.Concat(con)`

In place of 
` concat = mx.symbol.Concat(*[c1x1, c3x3, cd3x3, cproj])`

With no success

**Comment by firearasi** [comment]
Got it. The right call is
concat = mxnet:::mx.varg.symbol.Concat(con)

**Comment by thirdwing** [comment]
Let's keep this open since I think it is misleading and I need to change it.
