### ISSUE TITLE
Mac OS make failed

### ISSUE THREAD

**Issue by mindx0** [dmlc/mxnet#1579]
include/dmlc/omp.h:13:9: warning: Warning: OpenMP is not available, project will be compiled into single-thread code. Use
      OpenMP-enabled compiler to get benefit of multi-threading. [-W#pragma-messages]
#pragma message("Warning: OpenMP is not available, "                    \

...

NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/im2rec] Error 1

**Comment by sxjscience** [comment]
The default gcc in OS X installed by XCode command tool does not OpenMP. http://stackoverflow.com/questions/29057437/compile-openmp-programs-with-gcc-compiler-on-os-x-yosemite

My solution is to install the Intel® Parallel Studio XE Composer and change the compilation flags. https://software.intel.com/en-us/qualify-for-free-software/student

**Comment by victor128** [comment]
I installed OpenMP with command:  brew install clang-omp
now the warning disappeared, but I still have the same error massage:

  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/im2rec] Error 1

**Comment by sxjscience** [comment]
Seems to be OpenCV related, can you provide the detailed log?

**Comment by victor128** [comment]
Problem solved by editing config.mk like this

export CC = clang-omp
export CXX = clang-omp++
USE_OPENMP = 1

**Comment by celestesosmart** [comment]
I've got the same error. Can anyone provide some hints?

**Comment by pluskid** [comment]
I also got the same issue. A hacky solution that works for me is to edit `dmlc-core/make/dmlc.mk` and remove or commenting out the following lines:
```
ifndef NO_OPENMP
        DMLC_CFLAGS += -fopenmp
        DMLC_LDFLAGS += -fopenmp
endif
```

**Comment by sxjscience** [comment]
The compilation problem should be solved by https://github.com/dmlc/mxnet/pull/2407

**Comment by csaltos** [comment]
In my case the Xcode gcc was used on my computer, so I've just added:

export CC = gcc-7
export CXX = gcc-7

For using the homebrew gcc just installed, which includes support for OpenPM and now it works.

NOTE: Maybe at the mxnet installation instructions for mac we can include it some guidance about this minor tweak.

**Comment by csaltos** [comment]
In my case the Xcode gcc was used instead of the gcc installed by homebrew (which includes support for OpenMP), so I've just added this to the config.mk:

CC=gcc-7
CXX=gcc-7
SHLIB_OPENMP_CFLAGS=-fopenmp
SHLIB_OPENMP_CXXFLAGS=-fopenmp
SHLIB_OPENMP_FCFLAGS=-fopenmp
SHLIB_OPENMP_FFLAGS=-fopenmp

And so far it seems to work.

Another minor fix for building support for Scala, I have to edit the file:

mxnet/scala-package/macros/pom.xml

And replace ${platform} by osx-x86_64 and now the call to "make scalapkg" works.

IMPORTANT: all this "fixes" should be careful reviewed, these are only attempt to make mxnet work on my laptop.
