### ISSUE TITLE
Is it possible to have "fixed weights" ?

### ISSUE THREAD

**Issue by victor128** [dmlc/mxnet#1585]
What is the best way to have gradient decent only update part of weight vector and keep some part of weight fixed ?

**Comment by sbodenstein** [comment]
Use `mxnet.symbol.SliceChannel` to select the part of the weight + grad you want to update, and then do update.

**Comment by victor128** [comment]
Thank you,  could you give a sample code of using mxnet.symbol.SliceChannel ?
I still don't understand the meaning of SliceChannel.

**Comment by piiswrong** [comment]
It's probably easier to multiply the gradient matrix by a gate matrix and set the entries you want to update to 1 and others to 0
