### ISSUE TITLE
R-Package Install Fails - Cannot locate entry point in mxnet.dll

### ISSUE THREAD

**Issue by JeffHebert** [dmlc/mxnet#1588]
Hi, I am trying to install the R-Package with GPU support from the pre-built library. I am getting a generic failure when testing the build. If I skip testing, R can build and install the package. However, when I load the library('mxnet'), I get a message saying 

> The procedure entry point _ZNKSt7_cxx1112basic_stringlcSt11char_traits|cESa|cEE4findEPCcyy could not be located in the dynamic link library C:\..........\libs\x64\mxnet.dll.

Here are the session logs from the build. 

**Install fails**
```
jeff-@Jeff-Desktop MSYS /c/Users/jeff-/Downloads/mxnet_gpu2/mxnet-master
$ R CMD INSTALL --no-multiarch "R-package"                                      
* installing to library 'C:/Users/jeff-/Documents/R/library/3.2'
* installing *source* package 'mxnet' ...
** libs
make: Nothing to be done for `all'.
installing to C:/Users/jeff-/Documents/R/library/3.2/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
ERROR: loading failed
* removing 'C:/Users/jeff-/Documents/R/library/3.2/mxnet'
* restoring previous 'C:/Users/jeff-/Documents/R/library/3.2/mxnet'
```

**Install without test works, but R cannot find entry in mxnet.dll**
```
jeff-@Jeff-Desktop MSYS /c/Users/jeff-/Downloads/mxnet_gpu2/mxnet-master
$ R CMD INSTALL --no-multiarch --no-test-load "R-package"
* installing to library 'C:/Users/jeff-/Documents/R/library/3.2'
* installing *source* package 'mxnet' ...
** libs
make: Nothing to be done for `all'.
installing to C:/Users/jeff-/Documents/R/library/3.2/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
* DONE (mxnet)
```

**System Setup**
Microsoft Windows 10, Intel CPU
NVIDIA GeForce GTX 970 GPU 
NVIDIA CUDA 7.5 successfully installed and checked. 
NVIDIA cuDNN from cudnn-7.0-win-x64-v3.0-prod.zip
Rtools Collection 3.2.0.1948
MSYS2 - 64bit from msys2-x86_64-20160205.exe
MinGW - 64bit version 0.6.2
CMake 3.5 from cmake-3.5.0-rc3-win32-x86.msi

Thanks!

**Comment by thirdwing** [comment]
If you have Rtools installed, please remove `MSYS2` and `MinGW` from the system `PATH`.

**Comment by JeffHebert** [comment]
Thanks, I am one step closer, but still no joy. Now I get a message saying unable to load shared object. I think this is the same issue with mxnet.dll.

```
C:\Users\jeff-\Downloads\mxnet_gpu2\mxnet-master>R CMD INSTALL --no-multiarch "R-package"
* installing to library 'C:/Users/jeff-/Documents/R/library/3.2'
* installing *source* package 'mxnet' ...
** libs
make: Nothing to be done for `all'.
installing to C:/Users/jeff-/Documents/R/library/3.2/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'mxnet', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/jeff-/Documents/R/library/3.2/mxnet/libs/x64/mxnet.dll':
  LoadLibrary failure:  The specified module could not be found.

Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/jeff-/Documents/R/library/3.2/mxnet'
* restoring previous 'C:/Users/jeff-/Documents/R/library/3.2/mxnet'

```

Thanks!

**Comment by thirdwing** [comment]
Can you show me what's in your R-package folder in a tree-like manner?

On Sun, Mar 6, 2016 at 1:08 PM, Jeff Hebert <notifications@github.com>
wrote:

> Thanks, I am one step closer, but still no joy. Now I get a message saying
> unable to load shared object. I think this is the same issue with mxnet.dll.
>
> C:\Users\jeff-\Downloads\mxnet_gpu2\mxnet-master>R CMD INSTALL --no-multiarch "R-package"
> * installing to library 'C:/Users/jeff-/Documents/R/library/3.2'
> * installing *source* package 'mxnet' ...
> ** libs
> make: Nothing to be done for `all'.
> installing to C:/Users/jeff-/Documents/R/library/3.2/mxnet/libs/x64
> ** R
> ** demo
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> Error : .onLoad failed in loadNamespace() for 'mxnet', details:
>   call: inDL(x, as.logical(local), as.logical(now), ...)
>   error: unable to load shared object 'C:/Users/jeff-/Documents/R/library/3.2/mxnet/libs/x64/mxnet.dll':
>   LoadLibrary failure:  The specified module could not be found.
>
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing 'C:/Users/jeff-/Documents/R/library/3.2/mxnet'
> * restoring previous 'C:/Users/jeff-/Documents/R/library/3.2/mxnet'
>
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1588#issuecomment-192951326>.
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by JeffHebert** [comment]
Sure, see the attached filelist

[filelist.txt](https://github.com/dmlc/mxnet/files/160501/filelist.txt)

**Comment by JeffHebert** [comment]
This tree structure might come in handy

```
Folder PATH listing for volume Windows
Volume serial number is B290-1272
C:\USERS\JEFF-\DOWNLOADS\MXNET_GPU2\MXNET-MASTER\R-PACKAGE
├───demo
├───inst
│   ├───include
│   │   ├───dmlc
│   │   ├───mshadow
│   │   │   ├───cuda
│   │   │   ├───extension
│   │   │   └───packet
│   │   └───mxnet
│   └───libs
│       └───x64
├───man
├───R
├───src
├───tests
│   └───testthat
└───vignettes
```

**Comment by thirdwing** [comment]
Actually I just want to make sure what you have in `R-package\inst\libs\x64`.

I am sorry I have no idea what's wrong right now.

**Comment by thirdwing** [comment]
Close this for now. Feel free to reopen.
