### ISSUE TITLE
Save and Evaluate MXNet Model Between Full Epochs

### ISSUE THREAD

**Issue by RishabGargeya** [dmlc/mxnet#1593]
Hi all,

Currently for the dataset I am working with, epochs contain a very large number of images -- 
I would like to decrease the number of images my model sees each epoch in order to
a) save the model more frequently and 
b) call eval_metric to generate metric results on the validation data iterator more frequently

How should I approach this while still iterating through the full data iterator over multiple epochs? Thanks!

**Comment by piiswrong** [comment]
use epoch_size

**Comment by RishabGargeya** [comment]
Just to confirm, so if I define epoch size to be smaller than the number of examples I have in the entire training recorditerator, then the iterator rolls over at the start of the next epoch , and it only resets when all batches in the iterator have been processed, regardless of the end of an epoch? Thanks for the prompt response.

**Comment by RishabGargeya** [comment]
Just to confirm, so if I define epoch size to be smaller than the number of examples I have in the entire training recorditerator, then the iterator rolls over at the start of the next epoch , and it only resets when all batches in the iterator have been processed, regardless of the end of an epoch? Thanks for the prompt response.

**Comment by piiswrong** [comment]
If you are using the most recent code, yes.

**Comment by RishabGargeya** [comment]
Thanks for the help!

**Comment by RishabGargeya** [comment]
@piiswrong For some reason this solution is not working for me, even when I am using the latest commit of mxnet. The issue is as follows: epoch size is defined below
```
epoch_size = args.num_examples / args.batch_size
```
Yet, regardless of what I choose for num_examples, the epoch still only finishes when the data iterator makes a full pass through the data. For example, if I set num_examples = 32, and batch_size = 32, each batch should correspond to a single epoch correct? However, when calling fit, the model does not trigger epoch_callback until after the data iterator completes a full cycle. Is this a bug? or am I making a mistake somewhere? Thanks!

**Comment by piiswrong** [comment]
It's working for me. You can go into model.py and see why it's not breaking at model.py:260L

**Comment by RishabGargeya** [comment]
I finally figured out what wasn't working. I am using train_model.py from the image_classifications examples directory in my pipeline, but calling mx.FeedForward with the model_args keyword argument does not initialize epoch_size correctly for some odd reason. I added in the epoch_size parameter to the FeedForward function manually, and the model worked correctly. Is this issue working on your end?

**Comment by leehonglak** [comment]
The culprit line seems to be:
https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L50

It's missing something like this after the `epoch_size = args.num_examples / args.batch_size`
```
model_args['epoch_size'] = epoch_size
```

**Comment by piiswrong** [comment]
@leehonglak Thanks for catching this.
It's also weird that num_exmaples is not declared anywhere. 

@mli Could you look into this?
