### ISSUE TITLE
Kaggle ndsb reproducible results. Windows binary build.

### ISSUE THREAD

**Issue by juliandewit** [dmlc/mxnet#1594]
Hello I was playing with mxnet and a cool architecture for the kaggle ndsb 2.
At the moment I'm 3rd (with 1 single model) so there is a possibility of a prize now I was reading into what it took to win.
Results need to be reproducible. 

I seeded as much random things as possible but I still am having some problems.
mx.random.seed(1301)
random.seed(1301)
numpy.random.seed(1301)

1. Data input seems stable and reproducible
2. When learnrate == 0 everything is stable and reproducible with and without dropout
3. When I turn up the learnrate I get results that start to differ between runs.

I read about cudnn being non-deterministic (I'm on cudnn 3). Could that be the culprit ?
However.. I would expect weight updates to be deterministic.

Could anyone help me with this ?

Here are my test runs.

FIRST PREDICTIONS

RUN 1
array([[ 0.51068872,  0.49524814,  0.49289984, ...,  0.51171762,
         0.51438618,  0.50896013],
       [ 0.50962675,  0.48513001,  0.49781802, ...,  0.50200063,
         0.51084083,  0.50719506]], dtype=float32)
		 
RUN 2		 
array([[ 0.51068872,  0.49524814,  0.49289984, ...,  0.51171762,
         0.51438618,  0.50896013],
       [ 0.50962675,  0.48513001,  0.49781802, ...,  0.50200063,
         0.51084083,  0.50719506]], dtype=float32)		 
		 
		 
LEARN RATE 0.00 NO DROPOUT		 
		 
RUN 1		 
INFO:root:Epoch[0] Train-rmsecustom=0.505793
INFO:root:Epoch[0] Time cost=6.480
INFO:root:Epoch[0] Validation-rmsecustom=0.507493
INFO:root:Saved checkpoint to "model180_v2fold1-0001.params"
INFO:root:Epoch[1] Train-rmsecustom=0.505858
INFO:root:Epoch[1] Time cost=6.427
INFO:root:Epoch[1] Validation-rmsecustom=0.507927
INFO:root:Saved checkpoint to "model180_v2fold1-0002.params"		 

RUN 2
INFO:root:Epoch[0] Train-rmsecustom=0.505793
INFO:root:Epoch[0] Time cost=7.448
INFO:root:Epoch[0] Validation-rmsecustom=0.507493
INFO:root:Saved checkpoint to "model180_v2fold1-0001.params"
INFO:root:Epoch[1] Train-rmsecustom=0.505858
INFO:root:Epoch[1] Time cost=6.976
INFO:root:Epoch[1] Validation-rmsecustom=0.507927
INFO:root:Saved checkpoint to "model180_v2fold1-0002.params"

LEARN RATE 0.00 WITH DROPOUT		
 
RUN 1	
INFO:root:Epoch[0] Train-rmsecustom=0.505775
INFO:root:Epoch[0] Time cost=7.505
INFO:root:Epoch[0] Validation-rmsecustom=0.504496
INFO:root:Saved checkpoint to "model180_v2fold1-0001.params"
INFO:root:Epoch[1] Train-rmsecustom=0.505857
INFO:root:Epoch[1] Time cost=6.792
INFO:root:Epoch[1] Validation-rmsecustom=0.504597
INFO:root:Saved checkpoint to "model180_v2fold1-0002.params"

RUN 2
INFO:root:Epoch[0] Train-rmsecustom=0.505775
INFO:root:Epoch[0] Time cost=7.745
INFO:root:Epoch[0] Validation-rmsecustom=0.504496
INFO:root:Saved checkpoint to "model180_v2fold1-0001.params"
INFO:root:Epoch[1] Train-rmsecustom=0.505857
INFO:root:Epoch[1] Time cost=6.974
INFO:root:Epoch[1] Validation-rmsecustom=0.504597
INFO:root:Saved checkpoint to "model180_v2fold1-0002.params"

LEARN RATE 0.01 WITH DROPOUT	

RUN 1
INFO:root:Epoch[0] Train-rmsecustom=0.224680
INFO:root:Epoch[0] Time cost=7.455
INFO:root:Epoch[0] Validation-rmsecustom=0.170506
INFO:root:Saved checkpoint to "model180_v2fold1-0001.params"
INFO:root:Epoch[1] Train-rmsecustom=0.174495
INFO:root:Epoch[1] Time cost=6.874
INFO:root:Epoch[1] Validation-rmsecustom=0.215817
INFO:root:Saved checkpoint to "model180_v2fold1-0002.params"

RUN 2
INFO:root:Epoch[0] Train-rmsecustom=0.224966
INFO:root:Epoch[0] Time cost=7.566
INFO:root:Epoch[0] Validation-rmsecustom=0.170954
INFO:root:Saved checkpoint to "model180_v2fold1-0001.params"
INFO:root:Epoch[1] Train-rmsecustom=0.173524
INFO:root:Epoch[1] Time cost=6.765
INFO:root:Epoch[1] Validation-rmsecustom=0.260330
INFO:root:Saved checkpoint to "model180_v2fold1-0002.params"

**Comment by tqchen** [comment]
@juliandewit  The CUDNN is indeterministic, which means the gradient can vary a bit during runs and results in not reproducible weights. However, I feel this can be true for all libraries using CuDNN. 

One way to try is to turn off CuDNN, but I hope the rule won't interpret in that way :)  and the good model architecture and similar results should mean reproducibility

**Comment by juliandewit** [comment]
@tqchen 
Thanks for the fast reaction.
Would that mean rebuilding or is it a runtime option ?
I was using the windows binary release. This was very conveinient until now.. 

Yeah.. I don't think they can really hold this requirement esp. since in the future things will be more and more distributed and possibly "brain-like".

Anyway.. we'll see.
Thanks for mxnet by the way.. It was a breeze to work with.

**Comment by tqchen** [comment]
Unfortunately currently this need a rebuild, but I think we can go with CuDNN as every other deep learners do

**Comment by juliandewit** [comment]
Hello I rebuilt it without cudnn.
It cost me my last hairs but in the end it was all quite doable.. :)
The 1st epoch gives exactly the same results between runs so I think I'm good.

So thanks again for this great framework esp for targetting so many platforms. 
The prebuilt binaries etc are golden.

Perhaps after this comp is done I can make a contribution to your examples directory of my solution.

**Comment by tqchen** [comment]
cool! good luck on the comp!
