### ISSUE TITLE
Using the result of a dot product as the bias term of convolution: How to do?

### ISSUE THREAD

**Issue by ufukcbicici** [dmlc/mxnet#1596]
Hello.

I am trying to make experiments with a specific type of graph: Given a 4D data batch, the data goes through a convolution, nonlinearity and max-pooling. At that point (after pooling), the data goes through a flatten operation, where the 4D (A,B,C,D) shaped result of the pooling becomes 2D as (A,BxCxD). Here, A is the batch size, B is the number of filters and (CxD) is the filter size resulting from convolution and pooling. Now, at that point, I hold the resulting tensor of the non-flattened max-pooling (say X) and let the flattened 2D version go through a dot product, in which I apply to it a FullyConnected operator with 1 hidden unit. With that, I obtain a (A,1) shaped vector. Lets call that vector Y.  Now, what I finally want to do is to apply a new convolution operation to the 4D result tensor of the max-pooling, X, from the previous layer. But I want this time, for all A images in the batch, to use the corresponding element in the Y vector, as the bias term. Here is what I want to do:

     #4D batch tensor is given as the input. The batch size is A.
     data = mx.symbol.Variable(NETWORK_INPUT_NAME)
     #Convolution
     root_conv = mx.symbol.Convolution(data=data, kernel=(5,5), num_filter=20, name='Node1_Conv')
     root_nonlinearity = mx.symbol.Activation(data=root_conv, act_type="tanh")
     X = mx.symbol.Pooling(data=root_nonlinearity, pool_type="max",kernel=(2,2), stride=(2,2))
     #At this point, I obtained the (A,B,C,D) shaped 4D tensor X, resulting from pooling.

     #I transform X to a (A,BxCxD) shaped 2D matrix.
     flattened_feature = mx.symbol.Flatten(data=X)
     #Now I apply the dot product to the flattened X. 
     Y = mx.symbol.FullyConnected(data=flattened_feature, num_hidden=1,name=hyperPlaneProjectionName)
     conv2= mx.symbol.Convolution(data=X , bias=Y, kernel=(5,5), num_filter=50,name='DenemeConv')
    node_symbolic_network = mx.symbol.Group([conv2,Y,X,flattened_feature])
    #After that point, the network will actually continue but for the sake of simplicity, we stop now.

In this naïve approach, I get the "mxnet.base.MXNetError: InferShape Error in DenemeConv's bias argument" error when I try to call infer_shape on the node_symbolic_network, using the data batch shape as the input. The obvious reason should be that the bias term of 'DenemeConv' has the shape (50,) and Y has the shape (500,1), given a batch size A=500 and the shapes do not match. Another alternative which I thought was, to somehow clone each element of Y into a 3D  tensor of the shape (B',C',D'). This will produce Y' where the Y->Y' transform will be of the form (A,1)->(A,B',C',D'), where I clone that single dot product result into three dimensions, for each of the A samples. Then adding Y' to conv2 will do the same thing with the bias approach. But I am not sure if I can implement this with the existing operators of the MxNet.

So my question is, in the Python API of MxNet, how can I implement the network above correctly? Is there any possible way to do that with either the bias approach or the reshaping and then add approach? (I am aware of the Reshape operator but I am not sure whether it does the thing I need). Or do I need to implement a custom operator for that?

Thanks in advance!

**Comment by piiswrong** [comment]
I dont understand what exactly you are trying to do.
but using a output node as input to bias should work if the shape matches.

**Comment by ufukcbicici** [comment]
Let me ask that way then.
I have a vector, with the shape of (A,1), resulting from a one-hidden-unit FullyConnected layer. For each of the A values, I want to repeat that value, such that now a (A,B,C,D) shape is obtained, where when we fix the first dimension, say i, the other three dimensions have the same value repeated in a (B,C,D) shaped tensor.

For example, lets assume I have the fully connected result, X, with the shape (500,1). In the 30. entry, lets say I have the value 95. I want to transform this vector into a 4D tensor, say Y, of the shape (500,50,8,8), such that all entries will be Y[30,1,1,1]= ... = Y[30,49,7,7]=95.  And I want to do that using the symbolic operators in order to ensure correct forward and backward calculations. How can I do that?

**Comment by piiswrong** [comment]
reshape to (a, 1, 1, 1) then use deconvolution layer with weight initialized to 1 and fixed during training. Youll have to play with the kernel size a bit to get correct size

**Comment by piiswrong** [comment]
Actually no. You can use a fully connected layer to repeat and then do reshape.

**Comment by piiswrong** [comment]
Just remember to fix the weight and bias during training

**Comment by Godricly** [comment]
I think flatten operation gives u (AXBXC,D),maybe reshape is the one you want.
