### ISSUE TITLE
/usr/bin/ld: cannot find -lcuda

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1601]
Hi, I am trying to compile Mxnet on a cluster server. I got this problem. I have set the $PATH, $LIBRARY_PATH, $LD_LIBRARY_PATH. Add I also set the ADD_CFLAGS. Still it cannot find this library to link. The compilation was smooth, but it would give this error when linking the library. Any idea? How should I solve this?

**Comment by RishabGargeya** [comment]
Try linking the path where libcuda.so is located. So it would be -L/pathtolibcuda.so in the config.mk file
Also make sure put the location of your cuda library in USE_CUDA_PATH

**Comment by ascust** [comment]
Now I compiled it successfully, I also compiled the python package. But when I tried to import mxnet, I got this error:
```
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/apps/software/Python/2.7.11-foss-2015b/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/a1689670/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: cudnnBatchNormalizationForwardInference
```
The all previous steps were all successful except for this.

**Comment by tqchen** [comment]
You need to put CUDNN into LD_LIBRARY_PATH, as well as link it during compiltation
