### ISSUE TITLE
What happens if I give the same label value to equalize label_width for different instances?

### ISSUE THREAD

**Issue by erogol** [dmlc/mxnet#1602]
In case of different number of labels per instance, I ponder to use the same label value to fill the gap between instances. For instance my image list would be like this.

ID     LABELs ...      DATAPATH
0 	 1 	2     1     instance/path1 #last label filled by 1 to fill the gap
1 	 2     4     5     instance/path2
2 	 1 	2     4     instance/path3
3 	 2     4     2    instance/path4   #last label filled by 2 to fill the gap
4 	 1 	2     5     instance/path5
5 	 2     4     7    instance/path6
....

What would be the effect of this with label_width = 3, as suggested [here](https://github.com/dmlc/mxnet/blob/a6b4baf9824bb3f0bfb8ec804d333913b3bbc0c8/doc/python/io.md)?

**Comment by tqchen** [comment]
Yes, label_width = 3 should be the solution
