### ISSUE TITLE
driver shutting down exception in R

### ISSUE THREAD

**Issue by ziyeqinghan** [dmlc/mxnet#1611]
I trained on mnist. When I used the network of lenet with gpu, there would be aborted (core dumped) after training and validation finished.

My code is 
https://github.com/ziyeqinghan/mxnet/blob/master/R-package/demo/image-classification/train_mnist.R

When I run by the command ``Rscript train_mnist.R --network lenet --num-round 1 --gpus 0``
```
lytton1@Struct-Titanx:~/gsoc/my_mxnet/mxnet/R-package/demo/image-classification$ Rscript train_mnist.R --network lenet --num-round 1 --gpus 0
Loading required package: argparse
Loading required package: proto
Loading required package: mxnet
Loading required package: methods
[23:09:52] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(128,1,28,28)
[23:09:53] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(128,1,28,28)
Start training with 1 devices
Batch [50] Train-accuracy=0.81703125
Batch [100] Train-accuracy=0.8815625
Batch [150] Train-accuracy=0.904791666666667
Batch [200] Train-accuracy=0.9194140625
Batch [250] Train-accuracy=0.92909375
Batch [300] Train-accuracy=0.935833333333333
Batch [350] Train-accuracy=0.941383928571429
Batch [400] Train-accuracy=0.9459765625
Batch [450] Train-accuracy=0.949201388888889
[1] Train-accuracy=0.950314507494647
[1] Validation-accuracy=0.97666266025641
terminate called after throwing an instance of 'dmlc::Error'
  what():  driver shutting down
Aborted (core dumped)
```

How can I solve it? Thank you!

**Comment by thirdwing** [comment]
So there is no error in using CPU?

I think last time I saw `driver shutting down`, it is because memory is not enough.

**Comment by ziyeqinghan** [comment]
@thirdwing I think maybe this problem "Was due to cuda driver shutting down and some functions are called after the driver shutting down.", like in #1401. But I didn't figure out how to fix it.

**Comment by ziyeqinghan** [comment]
@thirdwing Yes, there is no error using CPU. I think maybe this problem "Was due to cuda driver shutting down and some functions are called after the driver shutting down.", like in #1401. But I didn't figure out how to fix it.

**Comment by javelinjs** [comment]
What version of mshadow are you using?

**Comment by ziyeqinghan** [comment]
@javelinjs The mshadow I use is "mshadow @ 1286bea". I find that "dmlc/mshadow" is 2 commits ahead of the mshadow used in mxnet. Maybe mxnet needs to update this submodule. Thanks!

**Comment by javelinjs** [comment]
@ziyeqinghan yeah, commit 6a9d036 fixed a potential uncaught error. Please let me know if it works, thank you.

**Comment by ziyeqinghan** [comment]
@javelinjs It solve the problem. Thank you so much :)

**Comment by kailiu9** [comment]
@yzhliu when I use NaiveEngine, this error still arise。
