### ISSUE TITLE
Pre-build Windows version GPU problem

### ISSUE THREAD

**Issue by taoari** [dmlc/mxnet#1628]
For the pre-build windows binary for 20160229 and 20160309, when I am finetuning the inception-bn model on a new dataset. The accuracy quickly increases for the CPU mode, however, it fails to increase for the GPU mode.

I also compiled directly from the source, and the GPU version does not encounter this problem. 

However, for the pre-build version, for the inception-bn model with batch size = 20, it only costs 1.35G GPU memory, yet for my compiled version (built on 20160229), it costs 1.85G GPU memory. The problem for my compiled version also lies in that the GPU memory consumption is not very stable. Although most of the time it is jumping around 1.85G, occasionally it could cost more than 2G. Is there any explanation for this?

**Comment by hjk41** [comment]
I guess it is caused by different OS/cuda version. Other people have
encountered similar issues. Currently, the binary packages are compiled on
Windows 10, x64, with CUDA 7.5. What are your configurations?

On Mon, Mar 14, 2016 at 10:41 AM, taoari <notifications@github.com> wrote:

> For the pre-build windows binary for 20160229 and 20160309, when I am
> finetuning the inception-bn model on a new dataset. The accuracy quickly
> increases for the CPU mode, however, it fails to increase for the GPU mode.
>
> I also compiled directly from the source, and the GPU version does not
> encounter this problem.
>
> However, for the pre-build version, for the inception-bn model with batch
> size = 20, it only costs 1.35G GPU memory, yet for my compiled version, it
> costs 1.85G GPU memory. The problem for my compiled version also lies in
> that the GPU memory consumption is not very stable. Although most of the
> time it is jumping around 1.85G, occasionally it could cost more than 2G.
> Is there any explanation for this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1628>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by taoari** [comment]
It is on Windows Server 2012, x64 with CUDA 7.5 driver. Maybe the system is the problem.

Will you provide the Windows Server version? I believe more people are working on the servers, rather than on their home computers. Since a GPU card is not affordable for everyone.

**Comment by hjk41** [comment]
:-)
I thought more people are working on Windows 7/10. Let's why we switched to
Windows 10. I will consider providing both in the next release.

On Mon, Mar 14, 2016 at 11:01 AM, taoari <notifications@github.com> wrote:

> It is on Windows Server 2012, x64 with CUDA 7.5 driver. Maybe the system
> is the problem.
>
> Will you provide the Windows Server version? I believe more people are
> working on the servers, rather than on their home computers. Since a GPU
> card is not affordable for everyone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1628#issuecomment-196117658>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by taoari** [comment]
Thanks!

**Comment by piiswrong** [comment]
@hjk41 Can we automate this?

**Comment by hjk41** [comment]
let me see if i can set it up on appveyor

On Mon, Mar 14, 2016 at 3:30 PM, Eric Junyuan Xie <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41> Can we automate this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1628#issuecomment-196182348>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia
