### ISSUE TITLE
Multi-GPU predictions with model.predict(...)

### ISSUE THREAD

**Issue by leehonglak** [dmlc/mxnet#1649]
`model.predict()` doesn't seem to be using multiple GPUs, even when model has been initialized with the appropriate contexts (e.g. `map(mx.gpu, range(2))`)

e.g. in https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb

What's the best way to be able to achieve this?

**Comment by piiswrong** [comment]
Since prediction doesn't change the model. You can load a model on each gpu and do it separately.

**Comment by leehonglak** [comment]
Thanks for your answer. The current `DataParallelExecutorManager` in `executor_manager.py` needs `train_data`, which doesn't make sense in this context. How would you go about implementing it?

**Comment by piiswrong** [comment]
Yes, it's for training and you can't call it directly (which is something we might want to fix). For now, a quick way of doing this is to change model._init_predictor to init one predictor on each gpu, and in model.predict, init data_array to have multiple slices like executor_manager:194L and call forward on all predictors

**Comment by piiswrong** [comment]
You can also add a is_train flag to executor_managers and turn off gradient related stuff and train_data in it. I think this is a better way of doing this.

**Comment by jmschrei** [comment]
You can also use joblib multiprocessing to load up the fit model in each process and calculate its predictions, then accumulate them into a single array.

**Comment by leehonglak** [comment]
As this been implemented or do I still need to use the suggested workaround?

**Comment by akturtle** [comment]
Anyone solved this question?
