### ISSUE TITLE
[New Operator] Special Parameters such as vector or array

### ISSUE THREAD

**Issue by ZhreShold** [dmlc/mxnet#1650]
I'm designing a new layer/operator in C++, where I encountered some confusion.

Based on some existing operators and their parameter list, e.g. 

```c++
struct FullyConnectedParam : public dmlc::Parameter<FullyConnectedParam> {
  int num_hidden;
  bool no_bias;
  DMLC_DECLARE_PARAMETER(FullyConnectedParam) {
    // TODO(bing) change to only set lower bound
    // add support for boolean
    DMLC_DECLARE_FIELD(num_hidden).set_range(1, 100000)
    .describe("Number of hidden nodes of the output.");
    DMLC_DECLARE_FIELD(no_bias).set_default(false)
    .describe("Whether to disable bias parameter.");
  }
};
```

Can I declare a std::vector<float> parameter *myvec* here:
```c++
struct FullyConnectedParam : public dmlc::Parameter<FullyConnectedParam> {
  int num_hidden;
  bool no_bias;
  std::vector<float> myvec; // I need an array or something

  DMLC_DECLARE_PARAMETER(FullyConnectedParam) {
    DMLC_DECLARE_FIELD(myvec).
    .describe("A vector of my designed parameters.");
  }
};
```

And create a symbol in python like this:

```python
l = mx.symbol.FullyConnected(data=xx, num_hidden=1000, myvec=[1,2,3,4,5,6], name="xxx")
```

Actually the most confusing part is how to **import** list or numpy array from python to the std::vector in C++ code.
Any advice would be great!

I intended to use the array as some properties for the layer. So declare an input is the last approach I would try. What I would like to know is whether there's something convenient or traditional way in mxnet to transfer a bunch of arguments like an array or something from python to c++ at layer initialization.

**Comment by Godricly** [comment]
Long time no see,Zhi. I think you can try passing in that vec as the input param of operator.

**Comment by ZhreShold** [comment]
@Godricly Lol, Yan. So long time no see. Did you mean I can use python list as input param?

**Comment by Godricly** [comment]
i mean you passed it in like the way data is passed.

**Comment by piiswrong** [comment]
What do you mean by import?

**Comment by ZhreShold** [comment]
@piiswrong I intended to use the array as some properties for the layer. So declare an input is the last approach I would try. What I would like to know is whether there's something convenient or *traditional* way in mxnet to transfer arguments from python to c++ at layer initialization.

**Comment by tqchen** [comment]
For shape like parameters, you can use TShape, which is only for vector of integer. For your own data structure, you can use it as long as you defined 

```
operator>>(istream&is, MyStruct& struct){
}
```

**Comment by tqchen** [comment]
it is recommended to define a special structure to do so

**Comment by tqchen** [comment]
note that though the parameters are passed by using toString and parse from String, so better suited for small arrays
