### ISSUE TITLE
Empty ps-lite directory

### ISSUE THREAD

**Issue by rsheppar** [dmlc/mxnet#1653]
Hello,
  I downloaded the latest release (.tar.gz) to try installing on a Cray.  When I went to build, I received these messages:
[rsheppar@h4 mxnet-20160309]$ make
Makefile:23: mshadow/make/mshadow.mk: No such file or directory
Makefile:24: dmlc-core/make/dmlc.mk: No such file or directory
Makefile:86: ps-lite/make/ps.mk: No such file or directory
make: *** No rule to make target `ps-lite/make/ps.mk'.  Stop.

When I look, the ps-lite directory is empty after untarring:
rsheppar@login1:/N/dc2/projects/ray/br2/mxnet/mxnet-20160309> ls -l ps-lite
total 0

That doesn't look right.  What did I do wrong?
Thanks in advance,
Ray

**Comment by tqchen** [comment]
You want to do a git clone with --recursive, because of the submodules , see http://mxnet.readthedocs.org/en/latest/build.html

**Comment by rsheppar** [comment]
Thanks.  Just a suggestion though, if you list a gzipped tar file under "Releases" for download, most all major installations will expect that file to be complete.  If it doesn't work, maybe it should not be posted to be downloaded.

**Comment by tqchen** [comment]
hmm, The source code zip in the release is automatically generated by github, so we get no control over that.. Anyway, thanks for the suggestion
