### ISSUE TITLE
issue with downloading FCN param files

### ISSUE THREAD

**Issue by rollingstone** [dmlc/mxnet#1654]
Hi  @starimpact @@tornadomeet ,

Thank you for the fcn implementation.

I tried to download the following files for using with fcn

VOC2012.rar 1.79G 2015-12-15 05:58
VGG_FC_ILSVRC_16_layers-0074.params 527.8M 2015-11-06 08:53
FCN8s_VGG16-0019.params 515.9M 2016-01-18 02:41
FCN8s_VGG16-0019-cpu.params

did not succeed in downloading the param files.  Always  timeout issue.....

would it be possible to upload the files to google drive?

Thanks a lot

**Comment by starimpact** [comment]
FCN is not implemented by me.

**Comment by rollingstone** [comment]
@starimpact thanks for the response... my mistake :S
