### ISSUE TITLE
Issue in amalgamation

### ISSUE THREAD

**Issue by saustar** [dmlc/mxnet#1660]
~/mxnet/amalgamation$ make

g++ -std=c++11 -Wno-unknown-pragmas -Wall -I/opt/OpenBLAS -fPIC -o mxnet_predict-all.o -c mxnet_predict-all.cc
mxnet_predict-all.cc:31:18: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
                  ^
compilation terminated.
make: *** [mxnet_predict-all.o] Error 1

I have built OpenBlas 0.2.16 . OpenBLAS root: /opt/OpenBLAS

**Comment by thirdwing** [comment]
I think this should be solved by adding `cuda_fp16.h` and `cuda.h` into blacklist in 
https://github.com/dmlc/mxnet/blob/master/amalgamation/amalgamation.py#L4

Just sent a PR.

**Comment by saustar** [comment]
No, I am not using this script. I am getting this issue when I am trying to execute 'make' command

**Comment by thirdwing** [comment]
`make` will call this script. See https://github.com/dmlc/mxnet/blob/master/amalgamation/Makefile#L35

**Comment by saustar** [comment]
Okay. Now I am getting another error:
Getting following error when trying to execute make 
:~/mxnet/amalgamation$ make
g++ -std=c++11 -Wno-unknown-pragmas -Wall -I/opt/openblas -shared -o pwd/../lib/libmxnet_predict.so mxnet_predict-all.o -L/opt/openblas -lopenblas -lrt
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
make: *** [pwd/../lib/libmxnet_predict.so] Error 1

**Comment by thirdwing** [comment]
The compiler can't find the openblas, please check the installation of openblas.
