### ISSUE TITLE
Broken links to pretrained models in documentation

### ISSUE THREAD

**Issue by michaelmior** [dmlc/mxnet#1663]
The [documentation](https://mxnet.readthedocs.org/en/latest/pretrained.html) has broken links to the pretrained models. It seems they got converted to Markdown and the links are now missing the `.md` extension.

**Comment by thirdwing** [comment]
Sorry for this. Fixed in #1664

**Comment by michaelmior** [comment]
No problem at all! Just figured I would point it out so it didn't go unfixed. Thanks!
