### ISSUE TITLE
The implementation of "mae" and "mse" in EvalMetric.scala may not be correct ?

### ISSUE THREAD

**Issue by Ldpe2G** [dmlc/mxnet#1665]
Hi,

line 79 to 80 of EvalMetric.scala, shouldn't it be 

    this.sumMetric += (labelArr zip predArr).map { case (l, p) => Math.abs(l - p) }.sum / labelArr.length
    this.numInst += 1

because if all the ndarrays have the same length, it is correct. But if not, the originally implementation may not be correct?

line 94 to 96 of EvalMetric.scala, shouldn't it be

    this.sumMetric +=
        (labelArr zip predArr).map { case (l, p) => (l - p) * (l - p) }.sum / labelArr.length
    this.numInst += 1

I had search for some relative materials of Mean Squared Error, and find that the originally implementation may be wrong?

Thanks.

**Comment by tqchen** [comment]
cc @javelinjs

**Comment by javelinjs** [comment]
Yeah, it is an implement bug. Thanks for pointing out. Could you make a PR for this ?

**Comment by Ldpe2G** [comment]
I have made a PR. Thanks.

**Comment by terrytangyuan** [comment]
@Ldpe2G Thanks!
