### ISSUE TITLE
Is it possible to make workspace larger than 4096?

### ISSUE THREAD

**Issue by horserma** [dmlc/mxnet#1671]
I dont quite understand what this workspace means, and why it is limited to 4096. If for example I have a very large input and I just want to do inference, it seems 4096 is not sufficient. Can I break this limit? Where can I hack it in the code. Thanks

**Comment by tqchen** [comment]
This can be fixed, @jermainewang can you follow up on this?

**Comment by vchuravy** [comment]
fixed in #944 this can be closed
