### ISSUE TITLE
Usage of `shared_exec` in Executor

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#1676]
Dear MXNet Developers,

Would you mind explaining more about the `shared_exec` parameter in `symbol.bind` https://github.com/dmlc/mxnet/blob/master/python/mxnet/symbol.py#L693-L696? For example, if we want to compile two executors **exe_a** and **exe_b** with different minibatch size but shared parameters, do we have to set the `shared_exec` of **exe_b** to be **exe_a** when binding the symbol? I find the `reshape` function https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor.py#L240 has used this feature and I'm not so sure how the engine will behave if we remove the `shared_exec` phrase. (Maybe the two executors will be run in parallel and will cause some synchronization problems?)

**Comment by tqchen** [comment]
- ```shared_exec``` is used, when you want to use two executors exclusively, but allowing them to share executors. 
- Normally you ***should not*** set this option, and new executor will be allocated, so you can use them concurrently.

- This is used say you want to do variable sequence length input, and you want to alternate between two executors, each handle one type of length.

**Comment by tqchen** [comment]
also cc @piiswrong We might want to improve the docstring to say the behavior. Not being able to use in parallel is vague. We should say that

```
exec1.forward(), exec1.backward(); exec2.forward(), exec2.backward() is ok
```
but
```

exec1.forward(), exec2.forward(); exec2.backward(), exec1.backward() is not
```

**Comment by sxjscience** [comment]
Thanks for the clear explanation~
