### ISSUE TITLE
Clear GPU memory when using sklearn api

### ISSUE THREAD

**Issue by nebw** [dmlc/mxnet#1677]
Is there any way to clear the GPU memory after training a model using the sklearn like api?

This does not work unfortunately:
```
model = mx.model.FeedForward(
     softmax,
     num_epoch=num_epoch,
     learning_rate=0.01)

model.fit(X=data_set)

del model
```

**Comment by tqchen** [comment]
Most training executes asynchronously, so after model.fit finishes, some of the memory could still be alive. However, they will indeed be eventually released and there is no need to directly call del
