### ISSUE TITLE
model split on multi-gpus

### ISSUE THREAD

**Issue by wp8619** [dmlc/mxnet#1684]
Training very deep model like deep residue net (with 150+layers) has high memory consumption and the training must be done on multiple gpus. So instead of data parallel, it seems necessary to do model split to split the model parameters into multiple gpus (e.g, putting different layers on different gpus) for distributed training. Is there any tutorials or examples showing how to implement this? Thank you.

**Comment by tqchen** [comment]
duplicated with https://github.com/dmlc/mxnet/issues/1639
