### ISSUE TITLE
issue in amalgamation make

### ISSUE THREAD

**Issue by saustar** [dmlc/mxnet#1685]
Getting following error when trying to execute make 
:~/mxnet/amalgamation$ make
g++ -std=c++11 -Wno-unknown-pragmas -Wall -I/opt/openblas -shared -o `pwd`/../lib/libmxnet_predict.so mxnet_predict-all.o -L/opt/openblas -lopenblas -lrt
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
make: *** [`pwd`/../lib/libmxnet_predict.so] Error 1

**Comment by saustar** [comment]
I have copied openblas so file to `/usr/lib`. It worked after that.

**Comment by sshuair** [comment]
where is the openblas file? I can not find it.
