### ISSUE TITLE
Relation to cxxnet ?

### ISSUE THREAD

**Issue by juliandewit** [dmlc/mxnet#169]
Since you are also running cxxnet and this one seems quite similar.. 
What horse should I bet on for the future ?
Is this basically cxxnet++ ?

**Comment by antinucleon** [comment]
We will deprecate CXXNET today. However MXNet is quite different to CXXNet. MXNet is more flexible and efficiency than CXXNET. We are still working on some final doc. Please check out [doc](https://mxnet.readthedocs.org/en/latest/faq.html#what-is-the-relation-between-mxnet-and-cxxnet-minerva-purine2) and [example](https://github.com/dmlc/mxnet/blob/master/example/notebooks/cifar-recipe.ipynb)

**Comment by tqchen** [comment]
See http://mxnet.readthedocs.org/en/latest/faq.html#what-is-the-relation-between-mxnet-and-cxxnet-minerva-purine2

**Comment by juliandewit** [comment]
Thanks for the lightening-quick reply :)
