### ISSUE TITLE
How to create a custom DataIter

### ISSUE THREAD

**Issue by madhurgoel** [dmlc/mxnet#1690]
I'm trying to load data and the format is not supported by methods available in the library(like CSVIter etc.). Should I convert my data into supported formats or make a new custom iterator? Also, the data is huge and can't be read into NDArray.
In case I need to define a new custom iterator, how should I go about it? To be specific, in what file should the method be defined and how to create a python binding for it (as it's done for CSVIter)?
Any help will be appreciated :)

Thank you.

**Comment by Godricly** [comment]
Check these 2 links:
[Python Data Loading API](http://mxnet.readthedocs.org/en/latest/python/io.html#create-a-data-iterator)
[bucketing](http://mxnet.readthedocs.org/en/latest/tutorial/bucketing.html)

If you are writting c++ DataIter, you can follow iter_image_recordio.cc.

**Comment by kishoreabhishek** [comment]
http://mxnet.readthedocs.org/en/latest/python/io.html#create-a-data-iterator
http://mxnet.readthedocs.org/en/latest/tutorial/bucketing.html

These links are broken
