### ISSUE TITLE
Support Addto in Gradient Requirement in Embedding

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#1693]
Currently the EmbeddingOp only support saveTo operation to gradient, and AddTo requirement is not correctly supported. 

See https://github.com/dmlc/mxnet/blob/master/src/operator/embedding-inl.h#L89

This can be extremely helpful to save memory consumption of LSTM models. @antinucleon can you add this support soon?

**Comment by chaoyuaw** [comment]
I haven't carefully tested it, but if we change this line
https://github.com/dmlc/mxnet/blob/master/src/operator/embedding-inl.h#L89
to
Assign(grad_in, req[embedding::kWeight], take_grad(data, grad_out, param_.input_dim));
it seems to do the "addto" behavior as expected.

**Comment by tqchen** [comment]
This sounds great, can you open a PR to fix this? Thanks!

**Comment by tqchen** [comment]
I think this line also need to be changed as well https://github.com/dmlc/mxnet/blob/master/src/operator/embedding-inl.h#L68

**Comment by chaoyuaw** [comment]
I just opened a PR for the one-line fix above. 
https://github.com/dmlc/mxnet/pull/1707
