### ISSUE TITLE
GPU not enabled error in neural_styles

### ISSUE THREAD

**Issue by piggsy** [dmlc/mxnet#1694]
Hi,

Sorry about this - I'm more into art than computers.  After about 8 hours of struggle I got Ubuntu 14.04 installed and the Neural Styles for Torch/lua working and generating images.  I've spent about another 6 hours of struggle trying to get mxnet to work after reading that it could generate higher resolution images than adam/cudnn on Torch and I've finally, finally, gotten it to work in CPU mode.  But : I'm getting this running it with -gpu 0

~/mxnet/example/neural-style$ python run.py --content-image input/IMG_4343.jpg --style-image input/starry_night.jpg --gpu 0
INFO:root:load the content image, size = (1000, 1500)
INFO:root:resize the content image to (400, 600)
[12:31:43] /home/piggy/mxnet/dmlc-core/include/dmlc/logging.h:241: [12:31:43] src/resource.cc:70: GPU is not enabled
Traceback (most recent call last):
  File "run.py", line 115, in <module>
    model_executor = importlib.import_module('model_' + args.model).get_model(size, dev)
  File "/home/piggy/mxnet/example/neural-style/model_vgg19.py", line 59, in get_model
    executor = out.bind(ctx=ctx, args=arg_dict, args_grad=grad_dict, grad_req="write")
  File "/home/piggy/miniconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 774, in bind
    ctypes.byref(handle)))
  File "/home/piggy/miniconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [12:31:43] src/resource.cc:70: GPU is not enabled

I'm feeling kind of defeated with this one error after a long (looooong) time getting to this point from a vanilla install and I'm wondering if anyone can help me diagnose what I might have done wrong or if there's any obvious line to check here.  I'm sure it's literally just one character or typo or wrong path in one line at this point but I can't seem to find it and after hours of installing packages and configuring things I'm just not seeing it.  

I'm using an Nvidia 970 with Ubuntu 14.04, CUDA 7.0 installed, and I have the Torch Neural Style version up and running using cudnn successfully.

**Comment by tqchen** [comment]
This means you have not compiled with the GPU enabled version. Check http://mxnet.readthedocs.org/en/latest/build.html#building-on-ubuntu-debian

You will need to switch USE_CUDA=1 on in the config.mk

**Comment by piggsy** [comment]
Yup, got that part.  Here's my config.mk if there's any obvious error here - 

`
export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS = -I /usr/local/cuda-7.0/targets/x86_64-linux/lib/

# the additional compile flags you want to add
ADD_CFLAGS = -I /usr/local/cuda-7.0/targets/x86_64-linux/lib/

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = /usr/local/cuda

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 0

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = blas
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =
`

am running it from the mxnet install folder and have tried make clean before remaking it.  Had set this to begin with and always gives GPU not found.  I've run into a few issues building it but it does so without errors now.  Only other stuff I can think of - had a typo giving "/usr/local//cuda-7.0/targets/x86_64-linux/lib/" for a few attempts but eventually found it and fixed, and have tried a few variants of setting the ldflags, cflags and cuda path, none of which have made any difference so far.

**Comment by tqchen** [comment]
please reinstall after you rebuild

**Comment by piggsy** [comment]
Ha-ha, I'm going to reveal my total lack of knowledge and ask - reinstall what? :D Do I need to re-clone the mx git package?

**Comment by tqchen** [comment]
After you successfuly rebuild, run ```python setup.py install again```  so these changes are reflected

**Comment by piggsy** [comment]
Excellent, thanks very much, works great :D
