### ISSUE TITLE
issue in caffe_converter: "mxnet.base.MXNetError: value (0,0)for Parameter kernel is invalid" when pooling layer with global pooling set to true

### ISSUE THREAD

**Issue by saustar** [dmlc/mxnet#1702]
Hi,
I am trying to convert a [caffe model] (https://github.com/DeepScale/SqueezeNet/blob/master/SqueezeNet_v1.0/train_val.prototxt) into mxnet. I am getting following error:

```
File "convert_model.py", line 99, in <module>
    main()
  File "convert_model.py", line 36, in main
    prob = proto2symbol(args.caffe_prototxt)
  File "/home/saurabh/mxnet/tools/caffe_converter/convert_symbol.py", line 151, in proto2symbol
    exec(sym)
  File "<string>", line 67, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 988, in creator
    ctypes.byref(sym_handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: value (0,0)for Parameter kernel is invalid, the input shape must be nonzero in all dimensions
```
I have able to figure it out:
```
layer {
  name: "pool10"
  type: "Pooling"
  bottom: "conv10"
  top: "pool10"
  pooling_param {
    pool: AVE
    global_pooling: true
  }
}
```
This is the layer where I am getting the error. There is no kernel_size parameter and by default (0,0) is being used. But global_pooling is true (alternate of FC layer). So this looks like an issue in converting to mxnet!!
So when global pooling is set to true, conversion of caffe model to mxnet will give this error:
`mxnet.base.MXNetError: value (0,0)for Parameter kernel is invalid, the input shape must be nonzero in all dimensions`

**Comment by saustar** [comment]
I was able to solve this by defining kernel_size based on previous layer output.

**Comment by Atraii** [comment]
I am also having this issue. As the previous user notes, editing the .prototxt file and removing the `global_pooling` under pool10 and replacing with `kernel_size: 13` (for the specific case of the SqueezeNet) works wonders. I feel that this issue should be able to be resolved by adding support for average pooling.
