### ISSUE TITLE
When will mxnet suppot dual stride in Pooling?

### ISSUE THREAD

**Issue by littleDing** [dmlc/mxnet#1706]
// TODO(bing): dual stride in mshadow   

I found the above comments in src/operator/pooling-inl.h. 
Is it impossible to do dual stride in mxnet now?

Something like below does not  works now.
pool = mx.symbol.Pooling(data=tanh, pool_type="max", kernel=(1,2), stride=(2,3))

**Comment by piiswrong** [comment]
It should work for CUDNN version

**Comment by littleDing** [comment]
Any plan for supporting on cpu?
Otherwise this can only stay in the lab.
Production environment needs to predict on cpu...

**Comment by tqchen** [comment]
It comes to support for dual stride in mshadow https://github.com/dmlc/mshadow/blob/master/mshadow/extension/spatial_pool.h#L38

should be a few lines to modify, you are more than welcomed to contribute the change

**Comment by horsepurve** [comment]
@tqchen would you please give some suggestions on how to modify it? I'm hoping for this function. Thanks.

**Comment by tornadomeet** [comment]
@horsepurve @littleDing  the newest mxnet has supported it.

**Comment by horsepurve** [comment]
@tornadomeet I really appreciate it!
