### ISSUE TITLE
NDArray serialization

### ISSUE THREAD

**Issue by christallire** [dmlc/mxnet#1708]
Hi, I was serializing NDArray and found that GPU enabled binary distribution version of NDArray is not compatible with CPU only version when pickling.

I think they should compatible each other regardless of GPU version or CPU version when serializing. except they can't serialize when if ndarray is allocated on graphics device and also we can retrieve data from graphics device when serialize ndarray but I think it's not feasible.

and I think it's because of GPU version of NDArray specific fields are not hidden to the serializer, we can hide it to make it compatible.

**Comment by tqchen** [comment]
Currently, the device information comes with ndarray during serialization. What you can do is always copy data to CPU before save them.
