### ISSUE TITLE
Unable to compile with vs2013 

### ISSUE THREAD

**Issue by yajiedesign** [dmlc/mxnet#1713]
`mxnet\mshadow\mshadow\./half.h(88): error : class "__half" has no suitable copy constructor`

**Comment by tqchen** [comment]
@hjk41 This was due to recent introduction of FP16, and possible compiler difference. Can you look into this?

**Comment by yajiedesign** [comment]
i am fix in https://github.com/dmlc/mshadow/pull/105

**Comment by yajiedesign** [comment]
it look like problem with volatile
