### ISSUE TITLE
Having trouble installing on Win 7 64 bit

### ISSUE THREAD

**Issue by andychao227** [dmlc/mxnet#1714]
Hello,

I am looking to install mxnet to use with python on my Windows 7 64bit computer, CPU only.

I'm using the Anaconda interpreter in the JetBrains Pycharm IDE

When I type python setup.py install it cannot find libmxnet.dll (and also that file does not exist)

Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "mxnet/libinfo.py", line 35, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
C:\....mxnet\python\mxnet\libmxnet.dll
C:\...\python\mxnet\../../lib/libmxnet.dll
C:\...\mxnet\python\mxnet\../../build\Release\libmxnet.dll
C:\....\mxnet\python\mxnet\../../windows/x64\Release\libmxnet.dll

Do I still need to use CMake? I have the program but I have no idea how to use it. 
I also do not have OpenCV/OpenBLAS. Would this fix the issue?

Any help would be appreciated. Thanks

**Comment by tqchen** [comment]
You can also try the weekly windows release http://mxnet.readthedocs.org/en/latest/build.html#installing-pre-built-packages-on-windows

**Comment by andychao227** [comment]
Wow. I actually had downloaded that too, and was looking everywhere for the setupenv.cmd file. Turns out I was in the wrong folder since I had downloaded the source. 

Thank you.

**Comment by schlichtanders** [comment]
@tqchen the url is no longer valid unfortunately
