### ISSUE TITLE
Strange problem when we run two mxnet programs on one GPU

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#1720]
I meet a really strange problem when I try to run two mxnet programs on the same GPU. For example, we first run a training program A on gpu0 and after a while run another program B on the same GPU. The parameters of program A will quickly diverge (finally to NaN) after the submission of B. I've tested it on a linux machine and same problem happens every-time. Anyone has idea about the cause?

**Comment by piiswrong** [comment]
@tqchen @antinucleon

**Comment by sxjscience** [comment]
I'm trying to get a minimum example.

**Comment by sxjscience** [comment]
Still working to get an example... In fact, I meet this problem when I'm testing my implementation of Deep Q Network. The training will be fine if I just run one DQN on a single GPU (I can repeat the results in the Nature paper for multiple Atari games). However, if I try to run two processes on the same GPU, the divergence problem occurs.

In my implementation, I generate two executors using the same set of QNet parameters, one for getting actions and another for updating the parameters. After one step of update using the updating executor, the action executor will need to generate actions using the updated parameters. I wonder if there are some asynchronous behaviors in the engine that cause the divergence...

**Comment by tqchen** [comment]
One thing you want to make sure is always use ndarray to pass around dependencies. If you have a reproducible example, we can have a better guess on what is going on.

Thanks very much!

**Comment by piiswrong** [comment]
Are you using one optimizer for both executors? That might be a problem.

**Comment by sxjscience** [comment]
@piiswrong @tqchen Thanks for your kind help. The problem disappears after I change the outputop of the Q network from NDArrayOp to NumpyOP. I'll try later to figure out the cause. Also, I'm using a single optimizer for two executors, but only one of them will do `forward(is_train=True)` and `backward()`. Another executor will only do `forward(is_train=False)`. Not sure whether this causes the problem...

**Comment by tqchen** [comment]
Thanks, please let us know when you have future findings

**Comment by zmonoid** [comment]
@tqchen Add `mx.nd.waitall()` after `mx.nd.choose_element_0index` will solve the problem.

It seems that when 2 mxnet processes running on one GPU, the planner will not wait NDAarray operation to finish before going to next statement, which will cause such problem.

**Comment by zmonoid** [comment]
Sorry... Not really will solve the problem... The parameter will still diverge... But at a lower speed.
