### ISSUE TITLE
How can I debug the project with GDB?

### ISSUE THREAD

**Issue by wsybupt** [dmlc/mxnet#1724]
I want to step through the abstract program code. When I use the GDB to debug the code, I can't see the source code. All I can see is that
`Breakpoint 1,0x00007ffff6d98190 in MXPredGetOutPutShape ()
from /mxnet/example/cpp/image-classification/../../../../mxnet/lib/libmxnet.so`

So, how can I step into the source code?

**Comment by piiswrong** [comment]
DEBUG ＝ 1 in config.mk

**Comment by wsybupt** [comment]
@piiswrong Thank you!
