### ISSUE TITLE
who can help me? what the error "TBlob.get_with_shape: new and old shape do not match total elements" means?

### ISSUE THREAD

**Issue by dushoufu** [dmlc/mxnet#1725]
09:48:32] ./dmlc-core/include/dmlc/logging.h:208: [09:48:32] ./mshadow/mshadow/./tensor_blob.h:530: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
[09:48:32] ./dmlc-core/include/dmlc/logging.h:208: [09:48:32] src/engine/./threaded_engine.h:295: [09:48:32] ./mshadow/mshadow/./tensor_blob.h:530: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
terminate called after throwing an instance of 'dmlc::Error'
  what():  [09:48:32] src/engine/./threaded_engine.h:295: [09:48:32] ./mshadow/mshadow/./tensor_blob.h:530: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
Aborted (core dumped)

**Comment by Godricly** [comment]
try printing out the shape and take a look.

**Comment by dushoufu** [comment]
@Godricly 
The first question is that I print the shape,the result shows equal,it is strange? what happened?

The second question is that,I add a line code to print,but the next line does work,I don't know why it is the case?  Actually before I add the printing code,the next line works well.

code is  below:
\mxnet\mshadow\mshadow\tensor_blob.h
  template<typename Device, int dim, typename DType>
  inline Tensor<Device, dim, DType> get_with_shape(const Shape<dim> &shape,
                                                   Stream<Device> *stream = NULL) const {
    CHECK(Device::kDevMask == dev_mask_ && DataType<DType>::kFlag == type_flag_)
      << "TBlob.get_with_shape: device type do not match specified type";
    CHECK_EQ(this->CheckContiguous(), true) << "TBlob.get_reshape: must be contiguous";
    CHECK_EQ(this->shape_.Size(), shape.Size())
      << "TBlob.get_with_shape: new and old shape do not match total elements";
    LOG(ERROR)<<"this"<<this->shape_.Size()<<"  input<<"<<shape.Size();
    return Tensor<Device, dim, DType>(static_cast<DType*>(dptr_),
                                      shape,
                                      shape[dim - 1],
                                      stream);
  }

printing result is below:
[11:04:40] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: ./test20160318.rec, use 4 threads for decoding..
[11:04:41] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: ./test20160318.rec, use 4 threads for decoding..
INFO:root:Auto-select kvstore type = local_update_cpu
INFO:root:Start training with [gpu(0), gpu(1)]
[11:04:43] ./dmlc-core/include/dmlc/logging.h:208: [11:04:43] ./mshadow/mshadow/./tensor_blob.h:532: this960  input<<960
[11:04:43] ./dmlc-core/include/dmlc/logging.h:208: [11:04:43] src/engine/./threaded_engine.h:295: [11:04:43] ./mshadow/mshadow/./tensor_blob.h:532: this960  input<<960
terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:04:43] src/engine/./threaded_engine.h:295: [11:04:43] ./mshadow/mshadow/./tensor_blob.h:532: this960  input<<960

**Comment by zhubuntu** [comment]
I have the same problem, did you solve it?

**Comment by tqchen** [comment]
It would be helpful to check give specific code that produces the problem. This indicates during execution, the shape mismatch happened

**Comment by rongrongxiangxin** [comment]
@dushoufu Have you solved the problem? I met the same error.

**Comment by dushoufu** [comment]
yes，i have，Mostly because your input picture  shape like（1，3，224，224）is not 

consistent with your rec format like grey or colour. To make sure they can match.
