### ISSUE TITLE
scala documents

### ISSUE THREAD

**Issue by mli** [dmlc/mxnet#1727]
please consider add scala documents into docs/ 
1. how to build the scala package http://mxnet.dmlc.ml/get_started/build.html
2. a quick overview of scala usage http://mxnet.dmlc.ml/get_started/index.html 
3. package document http://mxnet.dmlc.ml/packages/scala/index.html

**Comment by javelinjs** [comment]
Sure, I'll complete the scala parts

**Comment by hoaphumanoid** [comment]
Hi guys, 

The 3 links that @mli put are not working. Also if you go to the main mxnet page the documentation for scala is missing:
http://mxnet.readthedocs.io/en/latest/packages/scala/index.html

Please tell me how I can help

**Comment by leopd** [comment]
Scala docs are now online.  See http://mxnet.io/api/scala/index.html or http://mxnet.io/api/scala/docs/index.html for the API reference.  Thanks @andremoeller!
