### ISSUE TITLE
Problem with MXNet, Anaconda and Ubuntu

### ISSUE THREAD

**Issue by theinem** [dmlc/mxnet#1734]
Hi.

I have worked in Machine Learning with information provided by the Stanford University's Coursera course. I want to learn to manage the MXNet library.

First, I tried to install it in Windows, but did not work fine, then, I installed Ubuntu and Anaconda on my PC. Later, with help of the Installation Guide for MXNet, I installed it.

I am a noob in Ubuntu. I'm stuck on it. I have installed MXNet, but it isn't recognized by Python interpreter. Please, how can I fix it?

**Comment by piiswrong** [comment]
add /path/to/mxnet/python to your $PYTHONPATH

**Comment by wave-electron** [comment]
I also regard myself as  a novice trying to install mxnet on docker-machine with Ubuntu on a mac.  So far I got it working on my base Mac system, but as I'm running a Shiny server on the docker-machine with Ubuntu... I thought it would be neat to get it running on the server as well. 

When I try require(mxnet) the library mxnet its not being found after running thru the build stage. I then worked out it wasn't installed in the normal places my other R libraries are usually installed.

.libPaths() # all library trees R knows about

[1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"      
[3] "/usr/lib/R/library" 

 It seems to have install in my root directory "/mxnet/R-package/R"

I'm guessing I now need to add this to my .libPaths() but have never done this before and didn't want to screw up my R path configuration variable.

Would the command to append the mxnet path be the following? ... thanks in advance
.libPaths( c( .libPaths(), "~/mxnet/R-package/R") )

**Comment by wave-electron** [comment]
.libPaths(c('/mxnet/R-package',.libPaths()))  
> .libPaths()                                
[1] "/mxnet/R-package"              "/usr/local/lib/R/site-library"
[3] "/usr/lib/R/site-library"       "/usr/lib/R/library"       

I've tried this but, require(mxnet) is saying
Loading required package: mxnet
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘mxnet’

I also tried... 

library("mxnet", lib.loc="/mxnet/R-package/R")   
Error in library("mxnet", lib.loc = "/mxnet/R-package/R") : 
  there is no package called ‘mxnet’
> library("mxnet", lib.loc="/mxnet/R-package")  
Error in library("mxnet", lib.loc = "/mxnet/R-package") : 
  there is no package called ‘mxnet’

I'm not seeing a directory called mxnet like in pythons case. But I do see the R library files in a directory called R, which seem to match the python files.

I'm struggling to work out what to try next with my limited understanding of installing R packages from source.
