### ISSUE TITLE
Documentation broken link (minor issue)

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/mxnet#1735]
The link to "Tensorflow’s sequence training example" is broken in documentation for [Bucketing in MXNet](http://mxnet.readthedocs.org/en/latest/tutorial/bucketing.html). 

The updated link is  https://www.tensorflow.org/versions/r0.7/tutorials/seq2seq/index.html

**Comment by piiswrong** [comment]
Thanks for reporting this. Would you like to propose a PR on this?

**Comment by eric-haibin-lin** [comment]
PR Created. Please check when you're free

**Comment by tqchen** [comment]
https://github.com/dmlc/mxnet/pull/1736
