### ISSUE TITLE
why I couldn't found mxnet/example/mnist

### ISSUE THREAD

**Issue by ruobo** [dmlc/mxnet#1748]
is this example has been removed? Thanks for the reply.

**Comment by thirdwing** [comment]
Is the following what you are looking for?

https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_mnist.py

**Comment by ruobo** [comment]
thank you. but when I learn this url: http://www.infoq.com/cn/articles/use-mxnet-in-deep-learning-part01
it always said the python document is: mxnet/example/mnist/mlp.py .
I can't found this dir. where I can get that? thanks a lot.

**Comment by tqchen** [comment]
The example has been refactored, and the url @thirdwing points out is the updated place.
