### ISSUE TITLE
How to build handcraft network connectives and operations on networks ?

### ISSUE THREAD

**Issue by liubenyuan** [dmlc/mxnet#1749]
Hi, I am new to mxnet and nn, so the question might be off topic.

For example, I want pollute a networks with 10 nodes,
```python
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
```
and manually specify their connections, for example, in
```python
(1, 2, 6, 7)
(2, 4, 5)
(9, 10, 1)
```
then I would define some fancy computations on each row of connectives, for example,
```python
1*2 + mx.sigmod(6) + np.exp(7)
```
then call `mxnet` to compute this graph for me.

 - Could this be implemented using `mxnet` ? i.e., manually connectives and user defined operations.
 - If so, how could I compute the back propagation of this  `NN` ?

**Comment by piiswrong** [comment]
Look into example/image-classification/inception-*.py
It shows how to compose complicated networks.

**Comment by liubenyuan** [comment]
@piiswrong 

Thanks! I saw the demos in the examples folder. However all demos are **typical** neural networks, what about some non-typical needs, for example, in node-1, the data binded to is not a float, but a vector or a matrix, and the operation on node 1 and 2 may be the cross product `1 x 2` rather than simply `1 * 2` ?

**Comment by sxjscience** [comment]
@liubenyuan I think you need to write your own operators in this case. http://myungjun-youn-demo.readthedocs.org/en/latest/tutorial/new_op_howto.html?highlight=operator

**Comment by liubenyuan** [comment]
@sxjscience Thanks ! After I read the docs I think there is a long way to go before I implement this feature. Maybe I should try some mxnet demos first. XD
