### ISSUE TITLE
Segmentation fault when reading a Tensor variable in GPU mode

### ISSUE THREAD

**Issue by nicklhy** [dmlc/mxnet#1751]
I got a problem when implementing a custom operator in C++ level. I intend to read the input label values in forward phase like this:
```
Stream<xpu> *s = ctx.get_stream<xpu>();
Tensor<xpu, 1> label = in_data[xx_op_enum::kLabel].get_with_shape<xpu, 1, real_t>(Shape1(batch_size), s);
for(size_t i=0; i<batch_size; ++i) {
    int v = static_cast<int>(label[i]);
    \\ some other things ...
}
```
This code works well in the cpu mode. But it just crashed in the gpu mode with an error info "segmentation fault".
So, is there a different way to read tensor data in gpu mode?

**Comment by Godricly** [comment]
you need a kernel function to process GPU data. Check if MxNet can satisfy your need,otherwise you might need to implement gpu kernel code in .cu file.

**Comment by nicklhy** [comment]
@Godricly , actually I just need to get the values stored in this tensor.
For instance, from "Tensor<xpu, 1> label" to "std::vector<int> label_arrays".
I have no experience of writing CUDA before. Can I find some example codes in mxnet? Or could you kindly provide a detailed implementation here?
Really appreciate for that~

**Comment by Godricly** [comment]
you can access the element by label.dptr_[i] if the memory is continuous.  are you trying to pull out data to cpu and display?

**Comment by nicklhy** [comment]
Yes, I need to pull them to cpu memory and compute some diffs of the input features(data) according to them.
But I think label.dptr_[i] is just the same as label[i], isn't it?
And I also get "segmentation fault" after executing it just like before.

**Comment by Godricly** [comment]
you need to call NewTensor to create a CPU tensor and copy data there. After that you can do whatever you want on CPU. Be sure to free that temporary tensor after that, I crashed once before, LOL. If you are going use what you computed in future, I suggest you write some GPU code for better speed performance.

**Comment by nicklhy** [comment]
Thanks a lot.
My problem has been solved following your advice, though still not implemented in GPU code.
