### ISSUE TITLE
loading a json file failed, when the symbol contains op "_NDArray"

### ISSUE THREAD

**Issue by XHUJOY** [dmlc/mxnet#1752]
when runing 'symbol = sym.load('%s-symbol.json' % prefix)' in python/mxnet/model.py, it crashed and didn't give any information
my json file:
{
  "nodes": [
    {
      "op": "null", 
      "param": {}, 
      "name": "data", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "64", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv1_1", 
      "inputs": [[0, 0], [1, 0], [2, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu1_1", 
      "inputs": [[3, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_2_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_2_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "64", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv1_2", 
      "inputs": [[4, 0], [5, 0], [6, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu1_2", 
      "inputs": [[7, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Pooling", 
      "param": {
        "kernel": "(2,2)", 
        "pad": "(0,0)", 
        "pool_type": "max", 
        "stride": "(2,2)"
      }, 
      "name": "pool1", 
      "inputs": [[8, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv2_1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv2_1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "128", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv2_1", 
      "inputs": [[9, 0], [10, 0], [11, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu2_1", 
      "inputs": [[12, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv2_2_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv2_2_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "128", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv2_2", 
      "inputs": [[13, 0], [14, 0], [15, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu2_2", 
      "inputs": [[16, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Pooling", 
      "param": {
        "kernel": "(2,2)", 
        "pad": "(0,0)", 
        "pool_type": "max", 
        "stride": "(2,2)"
      }, 
      "name": "pool2", 
      "inputs": [[17, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv3_1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv3_1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "256", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv3_1", 
      "inputs": [[18, 0], [19, 0], [20, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu3_1", 
      "inputs": [[21, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv3_2_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv3_2_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "256", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv3_2", 
      "inputs": [[22, 0], [23, 0], [24, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu3_2", 
      "inputs": [[25, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv3_3_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv3_3_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "256", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv3_3", 
      "inputs": [[26, 0], [27, 0], [28, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu3_3", 
      "inputs": [[29, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Pooling", 
      "param": {
        "kernel": "(2,2)", 
        "pad": "(0,0)", 
        "pool_type": "max", 
        "stride": "(2,2)"
      }, 
      "name": "pool3", 
      "inputs": [[30, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv4_1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv4_1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "512", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv4_1", 
      "inputs": [[31, 0], [32, 0], [33, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu4_1", 
      "inputs": [[34, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv4_2_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv4_2_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "512", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv4_2", 
      "inputs": [[35, 0], [36, 0], [37, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu4_2", 
      "inputs": [[38, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv4_3_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv4_3_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "512", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv4_3", 
      "inputs": [[39, 0], [40, 0], [41, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu4_3", 
      "inputs": [[42, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Pooling", 
      "param": {
        "kernel": "(2,2)", 
        "pad": "(0,0)", 
        "pool_type": "max", 
        "stride": "(2,2)"
      }, 
      "name": "pool4", 
      "inputs": [[43, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv5_1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv5_1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "512", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv5_1", 
      "inputs": [[44, 0], [45, 0], [46, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu5_1", 
      "inputs": [[47, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv5_2_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv5_2_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "512", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv5_2", 
      "inputs": [[48, 0], [49, 0], [50, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "conv1_2", 
      "inputs": [[51, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv5_3_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv5_3_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(3,3)", 
        "no_bias": "False", 
        "num_filter": "512", 
        "num_group": "1", 
        "pad": "(1,1)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv5_3", 
      "inputs": [[52, 0], [53, 0], [54, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu5_3", 
      "inputs": [[55, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Pooling", 
      "param": {
        "kernel": "(2,2)", 
        "pad": "(0,0)", 
        "pool_type": "max", 
        "stride": "(2,2)"
      }, 
      "name": "pool5", 
      "inputs": [[56, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "fc6_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "fc6_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(7,7)", 
        "no_bias": "False", 
        "num_filter": "4096", 
        "num_group": "1", 
        "pad": "(3,3)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "fc6", 
      "inputs": [[57, 0], [58, 0], [59, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu6", 
      "inputs": [[60, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Dropout", 
      "param": {"p": "0.5"}, 
      "name": "drop6", 
      "inputs": [[61, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "fc7_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "fc7_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(1,1)", 
        "no_bias": "False", 
        "num_filter": "4096", 
        "num_group": "1", 
        "pad": "(0,0)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "fc7", 
      "inputs": [[62, 0], [63, 0], [64, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "relu"}, 
      "name": "relu7", 
      "inputs": [[65, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Dropout", 
      "param": {"p": "0.5"}, 
      "name": "drop7", 
      "inputs": [[66, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv8_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv8_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "Convolution", 
      "param": {
        "dilate": "(1,1)", 
        "kernel": "(1,1)", 
        "no_bias": "False", 
        "num_filter": "1", 
        "num_group": "1", 
        "pad": "(0,0)", 
        "stride": "(1,1)", 
        "workspace": "1536"
      }, 
      "name": "conv8", 
      "inputs": [[67, 0], [68, 0], [69, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "Activation", 
      "param": {"act_type": "sigmoid"}, 
      "name": "activation0", 
      "inputs": [[70, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "_NDArray", 
      "param": {"info": "0x121a850"}, 
      "name": "_ndarray0", 
      "inputs": [[71, 0]], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "loss_fst_label", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "_NDArray", 
      "param": {"info": "0x1279d60"}, 
      "name": "loss_fst", 
      "inputs": [[72, 0], [73, 0]], 
      "backward_source_id": -1
    }
  ], 
  "arg_nodes": [
    0, 
    1, 
    2, 
    5, 
    6, 
    10, 
    11, 
    14, 
    15, 
    19, 
    20, 
    23, 
    24, 
    27, 
    28, 
    32, 
    33, 
    36, 
    37, 
    40, 
    41, 
    45, 
    46, 
    49, 
    50, 
    53, 
    54, 
    58, 
    59, 
    63, 
    64, 
    68, 
    69, 
    73
  ], 
  "heads": [[74, 0]]
}

**Comment by tqchen** [comment]
This is expected behavior, as _NDArray is native operator that have something to do with scripting side  customization. What you can do is rebuild the symbol on the python or other language native side, and load the parameters. 

@piiswrong maybe we need a clear error message on this

**Comment by XHUJOY** [comment]
oK, thank you. I have rebuilt the symbol on the python, and load the parameters.
