### ISSUE TITLE
All mxnet processes crash when lacking memory

### ISSUE THREAD

**Issue by zhangyubing** [dmlc/mxnet#1768]
When I used mxnet to train CNN, I found the memory(4*8G, 32 GB in total in my PC) it needed was much larger (about 10x) than GPU memory(Titan x, 12 GB in total). 

For example, when I set batch size to 128, MXNet tended to allocate ~1GB GPU memory and 12 GB memory. If the actual memory does not meet such requirements, the following error would occur:
![image](https://cloud.githubusercontent.com/assets/6147325/14201326/be2db920-f823-11e5-91ee-02d4fc28ee7b.png)

Furthermore, if one mxnet instance could not start when lacking memory, it would make all other mxnet processes crash too. But when I used caffe and no enough GPU memory (not memory) could be used for the caffe instance, other caffe processes would go on well.

**Comment by piiswrong** [comment]
This is because mxnet allocates memory during training. Using ccSGD instead of SGD might alleviate this problem.

**Comment by zhangyubing** [comment]
Thanks for replying. I tried ccSGD but the memory MXNet allocated was still as high as SGD. Is it normal that MXNet tends to allocate such big memory during training as the screen shot shown below?
![image](https://cloud.githubusercontent.com/assets/6147325/14271113/e35fa756-fb27-11e5-92d5-a8b4150fae88.png)

![image](https://cloud.githubusercontent.com/assets/6147325/14271119/fd60089e-fb27-11e5-9807-8b3dfc98680a.png)

**Comment by tqchen** [comment]
If you are training on big image dataset, it is possible for mxnet to allocate some memory for caching and there are multiple layers of caching and pre-fetching.

This is likely to be caused by ImageRecordIter and it was fixed a bit by latest version. Some configurations can be fine tuned to reduce the memory consumption.

**Comment by tqchen** [comment]
You can try to set the following options to be smaller value (c.f. http://mxnet.readthedocs.org/en/latest/python/io.html#mxnet.io.ImageRecordIter)

- prefetch_buffer 
- preprocess_threads

**Comment by datha** [comment]
The URL gives 404

**Comment by martinbel** [comment]
See here: http://mxnet-tqchen.readthedocs.io/en/latest/packages/python/io.html
