### ISSUE TITLE
Any tools to convert pretrained caffe models into models in mxnet?

### ISSUE THREAD

**Issue by nicklhy** [dmlc/mxnet#177]
Any tools to convert pretrained caffe models into models in mxnet?

**Comment by antinucleon** [comment]
https://github.com/dmlc/mxnet/tree/master/tools/caffe_converter

**Comment by tqchen** [comment]
I am going to close this issue as the caffe converter is available here https://github.com/dmlc/mxnet/tree/master/tools/caffe_converter
