### ISSUE TITLE
Data Shape vs resize:

### ISSUE THREAD

**Issue by gaush123** [dmlc/mxnet#1785]
This is mostly related to the usage of mxnet, than reporting any issue. I am not sure if this is the place to ask this question.

I'd like to know the differnece between 'resize' (during conversion to rec format) and 'data_shape' in during data_iter process. Are they both different things? I have images size originally of ~800X300 order.
Should I resize it to 256 during creation of .rec format or may I change the value to (3, 256, 256) kind of value later on, during data_iter method?

Any help appreciated!

**Comment by piiswrong** [comment]
If you use the default image iterator, you need to resize the images.
If you wrote your own data_iter, you can do either. Depending on your use case.

**Comment by gaush123** [comment]
Ok, Thanks!
