### ISSUE TITLE
How to create shared NDArray in multiprocessing.Process in Python

### ISSUE THREAD

**Issue by peterzcc** [dmlc/mxnet#1791]
I'm trying to implement a locally multithreaded training of model, where different threads need to update the same parameter. I've found threading and kvstore("dist") to be slow and I want to use multiprocessing.Process to parallelize the training. 

I want to make an NDArray shared among different subprocesses using multiprocessing.sharedctypes or something like that. 

Could anyone suggest if it's possible to do that? Thanks!

**Comment by piiswrong** [comment]
It's not possible.
You don't need multithreaded training. Every operation on NDArrays is async. They are automatically parallelized by the engine.
