### ISSUE TITLE
Weight Filler and initialization in mxnet

### ISSUE THREAD

**Issue by gaush123** [dmlc/mxnet#1792]
I am trying to create an architecture along the lines of SqueezeNet [architecture.](https://github.com/DeepScale/SqueezeNet/blob/master/SqueezeNet_v1.0/train_val.prototxt) I need to set custom values for weight_filler in one of the convolution layers. How do I set these values in mxnet. 
`weight_filler {
      type: "gaussian"
      mean: 0.0
      std: 0.01 }`
Also, is gaussian method of initialization is different from Xavier's, as I can see in FeedForward in mxnet, 'gaussian' method seems to be a subset of 'Xavier' somehow, while in Caffe they appear to be different.

`initializer = mx.init.Xavier(rnd_type = "gaussian", factor_type = "in", magnitude = 2))`

**Comment by piiswrong** [comment]
Use mx.init.Mixed()

Xavier specify the range, you still need to pick a method that init each variable with that range.

**Comment by LaoAnchor** [comment]
@piiswrong How to initialize the weight of deconvolution filter to bilinear interpolati as you did In your newest paper "Deep3D: Automatic 2D-to-3D Video Conversion with CNNs"?

**Comment by LaoAnchor** [comment]
I got the answer by looking up the definition of class "initializer.py" in mxnet.
Thanks anyway.
