### ISSUE TITLE
Storing max pooling indices in MXNet

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#1793]
I find the MShadow side implementation of max pooling used the `==` logic to find the pooling indices. Is it possible to explicitly store the indices?

**Comment by tqchen** [comment]
is there any reason why the other policy is preferred?

**Comment by sxjscience** [comment]
I come to this question when I try to implement the ROIPooling layer used in Fast and Faster RCNN (https://github.com/rbgirshick/caffe-fast-rcnn/blob/fast-rcnn/src/caffe/layers/roi_pooling_layer.cu). The backward operation of ROIPooling may be easier to implement if we know the argmax indices. Also, when we pool over a large region, e.g global pooling, the current way of getting the pooled indices may not be efficient.

**Comment by piiswrong** [comment]
You can store the indexes as an second output, but remember to make it invisible.
Please refer to BatchNorm layer for example.

**Comment by sxjscience** [comment]
Thanks very much, I'll try on that.
