### ISSUE TITLE
Error when build with torch.

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#1794]
I built with torch and got errors as follows:
```
/usr/bin/ld: cannot find -lnn
/usr/bin/ld: cannot find -lcunn
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1
```
Then I use `locate libnn` and `locate libcunn`:
```
/data/wanggu/torch/extra/nnx/build/libnnx.so
/data/wanggu/torch/install/lib/lua/5.1/libnnx.so
/data/wanggu/torch/extra/cunnx/build/libcunnx.so
/data/wanggu/torch/install/lib/lua/5.1/libcunnx.so
```
So I modified the `lnn lcunn` in `torch.mk` to `lnnx lcunnx`. Then I continued the make procedure and got happy results. Maybe this is a small bug related to my torch installation. Hope this will be helpful to potential users.

**Comment by piiswrong** [comment]
It seems like torch renamed their libraries from nn to nnx in a recent update. We haven't figured out a way to support both versions.
