### ISSUE TITLE
the  gradients of second net are NaN,is there conflict when running two model successively, 

### ISSUE THREAD

**Issue by LaoAnchor** [dmlc/mxnet#1795]
I tried to modified the 'Neural-style' code to realize the paper,  "[Perceptual Losses for Real-Time Style Transfer and Super-Resolution](http://arxiv.org/abs/1603.08155)" to generate styled image in real time. However, **The gradients in Image Transform Net is NaN ** using executor.backward op when i had passed the gradients of generated image by VGG-19. 

```
model_executor.executor.backward(grad_array)  #model-executor bind VGG-19
generator_executor.executor.backward(mx.nd.clip(model_executor.data_grad,-10,10)*127.5)    #generator_executor bind the Image Transform Net
```

 
The gradients in Image Transform Net is Nan even when the out gradients are all zeros.

`generator_executor.executor.backward(mx.nd.zeros(model_executor.data_grad.shape,ctx=dev)) `

The gradients of generated image by VGG can be used to get styled image, which means that the gradient of generated image is correctly. When the Image Transform Net is defined in alone and backward with the gradients that is same as the gradients of generated image as above, the gradients in Image Transform Net is correctly. So i wanna ask that is there any conflict when running to model successively. If not, how can i do to detect and solve this problems?
    Thank you very much!

**Comment by LaoAnchor** [comment]
By test, i found the argument "is_train=True" in forward op is very crucial. When i setted "is_train=True", i can get the correct result, otherwise there were many mistakes. 
But i noticed that the argument "is_train"in forward op aren't set  "True" in example(Neural-style)code,  and the results are still correct. I'm very confused about this argument "is_train". So the question become what's the specific usage of argument "is_train" in forward op?
Thanks a lot!

**Comment by piiswrong** [comment]
If you want to call backward afterwards you should set is_train to True.
