### ISSUE TITLE
How can use im2rec to create a rec file with grey scale images as input.I mean how can i make a single channel Rec file?

### ISSUE THREAD

**Issue by dushoufu** [dmlc/mxnet#1797]
How can use im2rec to create a rec file with grey scale images as input.I mean how can i make a single channel Rec file?

**Comment by piiswrong** [comment]
im2rec should have a option to allow greyscale.

**Comment by dushoufu** [comment]
@piiswrong 
Yes,I do think this is the case,but I cann't find the option. Bellow are the option list.
Usage: <image.lst> <image_root_dir> <output.rec> [additional parameters in form key=value]\n"\
           "Possible additional parameters:\n"\
           "\tresize=newsize resize the shorter edge of image to the newsize, original images will be packed by default\n"\
           "\tlabel_width=WIDTH[default=1] specify the label_width in the list, by default set to 1\n"\
           "\tnsplit=NSPLIT[default=1] used for part generation, logically split the image.list to NSPLIT parts by position\n"\
           "\tpart=PART[default=0] used for part generation, pack the images from the specific part in image.list\n"
           "\tcenter_crop=CENTER_CROP[default=0] specify whether to crop the center image to make it rectangular.\n"
           "\tquality=QUALITY[default=80] JPEG quality for encoding, 1-100.\n");

**Comment by dushoufu** [comment]
OK. I understand I should get the latest version of mxnet.

**Comment by tqchen** [comment]
closing for now, please feel free to reopen it
