### ISSUE TITLE
Customise control towards the gradient flow

### ISSUE THREAD

**Issue by GravApple** [dmlc/mxnet#1801]
Dear all,
Just as the title indicats that I would like to customise the flow of the gradients.
For example,
```tensor_0 -> tensor_1```
```tensor_0 -> tensor_2```
when updating the parameters, I want to update ```tensor_0``` only according to the gradient from ```tensor_1``` while ignoring ```tensor_2```.
I notice that this might be done via utilising ```req``` array, but can anyone give me a specific instruction? Any level will be acceptable for me (python or c++).

Thanks in advance.

**Comment by tqchen** [comment]
use operator BlockGrad.

```
tensor_2 = mx.sym.BlockGrad(tensor_0)
```

**Comment by GravApple** [comment]
@tqchen This works. Thank you very much for your suggestion. 
Two remaining question: 
I notice that ```req``` array is always ```kWriteTo```. How can I modify it?
And will mxnet add both the gradients from ```tensor_1``` and ```tensor_2``` as a default behaviour if I do not use ```BlockGrad```?

**Comment by tqchen** [comment]
Yes

**Comment by tqchen** [comment]
grads in branches will be automatically added up, so there is no need to do this manually

**Comment by GravApple** [comment]
@tqchen Thank you again. Close for now.
