### ISSUE TITLE
Cannot compile libmxnet.so on OS X 10.11.4 (El Capitan)

### ISSUE THREAD

**Issue by AlexIoannides** [dmlc/mxnet#1802]
Hello,

I'm having some trouble here and I'd appreciate some guidance.

So far, I have:
```
brew install opencv
brew install openblas
```

And I have modified `config.mk` as follows:

```
ADD_LDFLAGS = '-L/usr/local/opt/openblas/lib'
ADD_CFLAGS = '-I/usr/local/opt/openblas/include'
USE_BLAS = openblas
```

[I have attached the full config.mk for reference: [config.txt](https://github.com/dmlc/mxnet/files/207945/config.txt) ]

I am, however, getting errors when I attempt to build:
```
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o line_split.o src/io/line_split.cc
clang: error: unsupported option '-fopenmp'
make[1]: *** [line_split.o] Error 1

...

clangclang: : errorerror: : no such file or directory: 'dmlc-core/libdmlc.a'no such file or directory: 'dmlc-core/libdmlc.a'
```

I don't know how to approach this one - any help would be greatly appreciated.

ADDITIONAL INFO:
- gcc & g++ -v = `Apple LLVM version 7.3.0 (clang-703.0.29)`
- I switched to using openblas to try and get around an error I was getting with the default 'apple' blas option `/Users/alexioannides/mxnet/mshadow/mshadow/./base.h:135:14: fatal error: 'cblas.h' file not found`
- I have tried `brew install clang-omp` and modifying config.mk to `export CC = clang-omp`, `export CC = clang-omp++` and `USE_OPENMP = 1`, but this yielded fatal errors when trying to locate headers files for `types`, `stdio` and `string`.

**Comment by Godricly** [comment]
Although I have no experience on this , I think you should use c++11 to compile MxNet.

**Comment by AlexIoannides** [comment]
As far as I can determine, the Apple c++ clang compiler supports c++11.

**Comment by pluskid** [comment]
Not sure why it got compiled with `-fopenmp` even though you disabled it in `config.mk`.

**Comment by AlexIoannides** [comment]
Just in case it helps, here's the full output from the terminal: [mxnet_bash_output.txt](https://github.com/dmlc/mxnet/files/208879/mxnet_bash_output.txt)

**Comment by pluskid** [comment]
It seems it is trying to compile dmlc-core with `-fopenmp`, even though openmp is disabled. I'm not sure what is happening here. As in `Makefile` we have
```
ifneq ($(USE_OPENMP), 1)
        export NO_OPENMP = 1
endif

# use customized config file
include $(config)
include mshadow/make/mshadow.mk
include $(DMLC_CORE)/make/dmlc.mk
unexport NO_OPENMP
```
and in `dmlc-core/make/dmlc.mk`, we have
```
ifndef NO_OPENMP
        DMLC_CFLAGS += -fopenmp
        DMLC_LDFLAGS += -fopenmp
endif
```
So `-fopenmp` should not be used. I am able to compile with Clang on OS X without problem. :-/

**Comment by pppoe** [comment]
Would this ``inexpert NO_OPENMP`` be the problem?

**Comment by pppoe** [comment]
@AlexIoannides comment out the line ``unexport NO_OPENMP`` works for me.
BTW, if you then get the ``ar: no archive members specified`` error, replace line 187 in Makefile 
``ar crv $@ $(filter %.o, $?)`` with ``ar crv $@ $(filter %.o, $^)`` works for me.

**Comment by AlexIoannides** [comment]
@pppoe thanks for the suggestion - I'll give that a go. I also tried commenting-out the following:

```
ifndef NO_OPENMP
        DMLC_CFLAGS += -fopenmp
        DMLC_LDFLAGS += -fopenmp
endif
```

And that seemed to do the trick as well.

**Comment by wave-electron** [comment]
Great thread,  just fixed my install error, for python on El Capitan. I basically 
commented out 'unexport NO_OPENMP'  
in the Makefile

**Comment by tmatas** [comment]
@tqchen, would it be better to do a commit in the makefile?
