### ISSUE TITLE
Does CSVIter support parallelization?

### ISSUE THREAD

**Issue by Yunrui** [dmlc/mxnet#1804]
Hi folks,

I have 10-machines cluster and trying to do distributed training against a large csv file. In the ImageIter example, seems that each work machine should explicitly set num_parts and part_index, but I didn't find similar configuration in CSVIter. So I am guessing CSVIter doesn't support data parallelization? And if I use CSVIter on my 10 machines, means all works are training on the exact same batch data? 
 
Image Parallelization Example:
   data = mx.io.ImageRecordIter(num_parts = kv.num_workers, part_index = kv.rank, ...)

**Comment by Yunrui** [comment]
Looks like CSVIter passes 0 and 1 as part_index and num_parts. Trying to modify the code to see whether it works. 

class CSVIter: public IIterator<DataInst> {
 public:
  CSVIter() {
    out_.data.resize(2);
  }
  virtual ~CSVIter() {}

  // intialize iterator loads data in
  virtual void Init(const std::vector<std::pair<std::string, std::string> >& kwargs) {
    param_.InitAllowUnknown(kwargs);
    data_parser_.reset(dmlc::Parser<uint32_t>::Create(param_.data_csv.c_str(), 0, 1, "csv"));
    if (param_.label_csv != "NULL") {
      label_parser_.reset(dmlc::Parser<uint32_t>::Create(param_.label_csv.c_str(), 0, 1, "csv"));
    } else {
      dummy_label.set_pad(false);
      dummy_label.Resize(mshadow::Shape1(1));
      dummy_label = 0.0f;
    }
  }

**Comment by tqchen** [comment]
CSVIter was not designed to support data parallelism. It is more for quick testing of inputs on a single node setting

**Comment by tqchen** [comment]
The main obstacle is that the partition of several csv files may not be identical.
