### ISSUE TITLE
build mxnet git with gcc 5.31 under Ubuntu 16.04 Beta 2c

### ISSUE THREAD

**Issue by jiapei100** [dmlc/mxnet#1808]
Hi, all, 
I just git the source and trying to build it. But, failed with the following error  message...
It looks like dmlc-core has some bugs? Or, it's NOT gcc 5.3.1 compatible?
I'm actually using gcc (Ubuntu 5.3.1-13ubuntu4) 5.3.1 20160405

Can anybody give me a hand?

Cheers
Pei

> /usr/local/cuda-7.5/bin/nvcc /home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/src/operator/softmax_output.cu -c -o /home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/build/CMakeFiles/cuda_compile.dir/src/operator/./cuda_compile_generated_softmax_output.cu.o -ccbin /usr/bin/cc -m64 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_USE_CUDA=1 -DUSE_CUDNN -DMXNET_USE_OPENCV=1 -DUSE_CUDNN -DMSHADOW_USE_CUDNN=1 -Xcompiler ,\"-O3\",\"-Wall\",\"-msse2\",\"-Wno-unknown-pragmas\",\"-fPIC\",\"-fopenmp\",\"-g\" -gencode arch=compute_52,code=sm_52 -Xcudafe --diag_suppress=cc_clobber_ignored -Xcudafe --diag_suppress=integer_sign_change -Xcudafe --diag_suppress=useless_using_declaration -Xcudafe --diag_suppress=set_but_not_used -Xcompiler -fPIC -DNVCC -I/usr/local/cuda-7.5/include -I/usr/include -I/usr/local/cuda-7.5/include -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/include -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/mshadow -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include -I/usr/local/include/opencv -I/usr/local/include
> /home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(247): error: expected a ";"
> 
> /home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(284): warning: parsing restarts here after previous syntax error
> 
> /home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(243): error: "buf_" is not a nonstatic data member or base class of class "dmlc::ostream"
> 
> /home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(244): error: class "dmlc::ostream" has no member "set_stream"
> 
> /home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(289): error: identifier "OutBuf" is undefined
> 
>

**Comment by jiapei100** [comment]
I think I can just type "make -j4" from mxnet directory.
However, I prefer using cmake to do the out-of-source building. It seems the current cmake doesn't work properly.


Cheers
Pei

**Comment by piiswrong** [comment]
cmake is for windows. Use config.mk for linux

**Comment by linkerlin** [comment]
I used cmake on a ubuntu box.

**Comment by jiapei100** [comment]
config.mk: same result...


> /home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/mshadow/mshadow/./expression.h:176:50:   required from ‘Container& mshadow::expr::RValueExp<Container, DType>::operator+=(const mshadow::expr::Exp<E, DType, etype>&) [with E = mshadow::expr::BinaryMapExp<mshadow::op::plus, mshadow::expr::BinaryMapExp<mshadow::op::plus, mshadow::Tensor<mshadow::cpu, 1>, mshadow::Tensor<mshadow::cpu, 1>, float, 1>, mshadow::Tensor<mshadow::cpu, 1>, float, 1>; int etype = 1; Container = mshadow::Tensor<mshadow::cpu, 1>; DType = float]’
src/kvstore/./kvstore_local.h:200:14:   required from here
/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/mshadow/mshadow/./tensor_cpu-inl.h:146:3: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/usr/local/cuda/bin/nvcc -c -o build/src/optimizer/sgd_gpu.o --use_fast_math -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/mshadow/ -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=1" src/optimizer/sgd.cu
/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(247): error: expected a ";"

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(284): warning: parsing restarts here after previous syntax error

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(243): error: "buf_" is not a nonstatic data member or base class of class "dmlc::ostream"

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(244): error: class "dmlc::ostream" has no member "set_stream"

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(289): error: identifier "OutBuf" is undefined

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(312): error: identifier "Stream" is undefined

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(317): error: expected a ";"

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(350): warning: parsing restarts here after previous syntax error

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(314): error: "buf_" is not a nonstatic data member or base class of class "istream"

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(315): error: class "istream" has no member "set_stream"

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(357): error: identifier "InBuf" is undefined

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(358): error: expected a declaration

/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include/dmlc/io.h(359): error: expected a declaration

/usr/include/c++/5/bits/stl_deque.h(131): error: identifier "_Ptr" is undefined

/usr/include/c++/5/bits/stl_deque.h(132): error: identifier "_Ref" is undefined

/usr/include/c++/5/bits/stl_deque.h(135): error: identifier "_Deque_iterator" is undefined

/usr/include/c++/5/bits/stl_deque.h(137): error: identifier "_Elt_pointer" is undefined

/usr/include/c++/5/bits/stl_deque.h(138): error: identifier "_Elt_pointer" is undefined

/usr/include/c++/5/bits/stl_deque.h(139): error: identifier "_Elt_pointer" is undefined

/usr/include/c++/5/bits/stl_deque.h(140): error: identifier "_Map_pointer" is undefined

/usr/include/c++/5/bits/stl_deque.h(142): error: identifier "_Elt_pointer" is undefined

/usr/include/c++/5/bits/stl_deque.h(142): error: identifier "_Map_pointer" is undefined

/usr/include/c++/5/bits/stl_deque.h(143): error: expected a "{"

/usr/include/c++/5/bits/stl_deque.h(147): error: expected a "{"

/usr/include/c++/5/bits/stl_deque.h(149): error: identifier "iterator" is undefined

/usr/include/c++/5/bits/stl_deque.h(150): error: expected a "{"

/usr/include/c++/5/bits/stl_deque.h(153): error: identifier "iterator" is undefined

/usr/include/c++/5/bits/stl_deque.h(154): error: a type qualifier is not allowed on a nonmember function

/usr/include/c++/5/bits/stl_deque.h(155): error: identifier "iterator" is undefined

/usr/include/c++/5/bits/stl_deque.h(158): error: a type qualifier is not allowed on a nonmember function

/usr/include/c++/5/bits/stl_deque.h(158): error: too few parameters for this operator function

/usr/include/c++/5/bits/stl_deque.h(158): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(162): error: "operator->" must be a member function

/usr/include/c++/5/bits/stl_deque.h(162): error: a type qualifier is not allowed on a nonmember function

/usr/include/c++/5/bits/stl_deque.h(166): error: too few parameters for this operator function

/usr/include/c++/5/bits/stl_deque.h(166): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(171): error: identifier "_M_set_node" is undefined

/usr/include/c++/5/bits/stl_deque.h(174): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(178): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(180): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(181): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(186): error: too few parameters for this operator function

/usr/include/c++/5/bits/stl_deque.h(186): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(190): error: identifier "_M_set_node" is undefined

/usr/include/c++/5/bits/stl_deque.h(194): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(198): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(200): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(201): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(206): error: too few parameters for this operator function

/usr/include/c++/5/bits/stl_deque.h(206): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(209): error: identifier "_S_buffer_size" is undefined

/usr/include/c++/5/bits/stl_deque.h(217): error: identifier "_M_set_node" is undefined

/usr/include/c++/5/bits/stl_deque.h(221): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(225): error: a type qualifier is not allowed on a nonmember function

/usr/include/c++/5/bits/stl_deque.h(225): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(227): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(232): error: too few parameters for this operator function

/usr/include/c++/5/bits/stl_deque.h(232): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(233): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(236): error: a type qualifier is not allowed on a nonmember function

/usr/include/c++/5/bits/stl_deque.h(236): error: nonmember operator requires a parameter with class or enum type

/usr/include/c++/5/bits/stl_deque.h(238): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(243): error: "operator[]" must be a member function

/usr/include/c++/5/bits/stl_deque.h(243): error: a type qualifier is not allowed on a nonmember function

/usr/include/c++/5/bits/stl_deque.h(244): error: "this" may only be used inside a nonstatic member function

/usr/include/c++/5/bits/stl_deque.h(252): error: identifier "_Map_pointer" is undefined

/usr/include/c++/5/bits/stl_deque.h(256): error: identifier "_S_buffer_size" is undefined

/usr/include/c++/5/bits/stl_deque.h(258): error: expected a declaration

/usr/include/c++/5/bits/stl_deque.h(265): error: overloaded function "_Deque_iterator" is not a template

**Comment by jiapei100** [comment]
My modified config.mk


`#-------------------------------------------------------------------------------
#  Template configuration for compiling mxnet
#
#  If you want to change the configuration, please use the following
#  steps. Assume you are on the root directory of mxnet. First copy the this
#  file so that any local changes will be ignored by git
#
#  $ cp make/config.mk .
#
#  Next modify the according entries, and then compile by
#
#  $ make
#
#  or build in parallel with 8 threads
#
#  $ make -j8
#-------------------------------------------------------------------------------

#---------------------
# choice of compiler
#--------------------

export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS =

# the additional compile flags you want to add
ADD_CFLAGS =

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
USE_CUDA_PATH = /usr/local/cuda
# USE_CUDA_PATH = NONE

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =


#----------------------------
# plugins
#----------------------------

# whether to use torch integration. This requires installing torch.
# TORCH_PATH = $(HOME)/torch
# MXNET_PLUGINS += plugin/torch/torch.mk

# whether to use sframe integration. This requires build sframe
# git@github.com:dato-code/SFrame.git
# SFRAME_PATH = $(HOME)/SFrame
# MXNET_PLUGINS += plugin/sframe/plugin.mk`

**Comment by jiapei100** [comment]
My modified config.mk

> #-------------------------------------------------------------------------------
#  Template configuration for compiling mxnet
#
#  If you want to change the configuration, please use the following
#  steps. Assume you are on the root directory of mxnet. First copy the this
#  file so that any local changes will be ignored by git
#
#  $ cp make/config.mk .
#
#  Next modify the according entries, and then compile by
#
#  $ make
#
#  or build in parallel with 8 threads
#
#  $ make -j8
#-------------------------------------------------------------------------------

#---------------------
# choice of compiler
#--------------------

export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS =

# the additional compile flags you want to add
ADD_CFLAGS =

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
USE_CUDA_PATH = /usr/local/cuda
# USE_CUDA_PATH = NONE

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =


#----------------------------
# plugins
#----------------------------

# whether to use torch integration. This requires installing torch.
# TORCH_PATH = $(HOME)/torch
# MXNET_PLUGINS += plugin/torch/torch.mk

# whether to use sframe integration. This requires build sframe
# git@github.com:dato-code/SFrame.git
# SFRAME_PATH = $(HOME)/SFrame
# MXNET_PLUGINS += plugin/sframe/plugin.mk

**Comment by tqchen** [comment]
This should be fixed in recent version. Please try to build from a clean clone from master

**Comment by jiapei100** [comment]
It's only about config.mk, pretty simple:

`export CC = gcc
export CXX = g++ -std=c++11 -D_FORCE_INLINES -D_MWAITXINTRIN_H_INCLUDED
export NVCC = nvcc
`

That is my solution...

Cheers
Pei
