### ISSUE TITLE
Mxnet prediction on cpu is very slow

### ISSUE THREAD

**Issue by rhythm9229** [dmlc/mxnet#1811]
i am trying get predictions for images using imagenet-21k-inception model through the cpp classification code but the prediction on cpu is very slow.
The prediction takes about 1.06 seconds for a single image and i tried to give images in batch but still there is no speed gain. I thought that giving images in batch will speed things up.
Is there something that i am doing wrong?
Is there a way to make predictions fast on cpu?

**Comment by linkerlin** [comment]
compile mxnet with openmp

**Comment by rhythm9229** [comment]
I compiled mxnet with USE_OPENMP = 1 
After some profiling i realized that MXPredForward takes only 0.04 seconds for a single image but
MXPredGetOutput takes a lot of time about 1 second for one image. This function copies the result data after prediction
( https://github.com/dmlc/mxnet/blob/5ff545f2345f9b607b81546a168665bd63d02d9f/src/c_api/c_predict_api.cc )

Any way to make this fast?

**Comment by piiswrong** [comment]
@tqchen

**Comment by tqchen** [comment]
there are several things that can be done to speed things up.

- Use openblas, which support multi-threading
- Use NaiveEngine, that eliminates the thread scheduling

**Comment by rhythm9229** [comment]
@tqchen thanks a lot for the help! 
 I used openblas with USE_OPENMP = 1  and used naive engine which speeded things up :)  The prediction now takes 0.55 seconds for a single image.

I have a few more questions - 

1. I want to make predictions for a batch of 8 images using imagenet-21k-inception model in under a second. Is that possible?

2. In the documentation of the predict api (http://mxnet.readthedocs.org/en/latest/doxygen/c__predict__api_8h.html) it is written that num_input_nodes = 1 for feedforward.
How can batching be done for feedforward prediction and will batching speed things up?

**Comment by tqchen** [comment]
When you create the operator, change the input shape to include batch dimension should enable batching. i.e.
instead of

```(1, channel, height, width)``` change it to  ```(batch_size, channel, height, width)```

**Comment by rhythm9229** [comment]
@tqchen  I am able to predictions for batch of images but it takes 4 seconds to get predictions for 8 images ie. i did not get any speed gain through batching.
Is there any way to get prediction results faster for batch of images in cpu mode?
Right now i am using the c prediction api , will using the cpp interface lead to better performance?

**Comment by tqchen** [comment]
The bottleneck is on the computation then. Using cpp interface won't speed things up. You can, however, try NaiveEngine. Note that 21k-inception is a bigger net than normal inception used in imagenet, so the speed could be justified

**Comment by rhythm9229** [comment]
okay thanks :) @tqchen

**Comment by careyjiang** [comment]
i have tested predict in cpp,and find MXPredGetOutput is very slow(200ms), but in python executor.forward and get out is very fast(4.5ms), why?@tqchen

**Comment by tqchen** [comment]
the python execution API is asynchronous, you can only measure the time after it is copied to numpy array

**Comment by careyjiang** [comment]
@tqchen but my timer methods is:
PYTHON: (in total use 4.5ms, get right class result)
    _start = time.time()_
    **outProb = model.forward(input_array) 
    label = np.argmax(outProb, axis=1)[0]**  
    dtLabel=codeDict[label]
    _useTime = (time.time() - start) / 1.0_
CPP:(use 230ms, get right class result)
    _getTimer.begin();_
    **MXPredGetOutput(out, output_index, &(data[0]), size);
    PrintOutputResult(data, synset);** 
    _useC = getTimer.end();_

in CPP api, the time-consuming function is SyncCopyToCPU (200ms).

**Comment by qt6636** [comment]
@careyjiang have your problem solved? Would you give me some advice?

**Comment by YunLexi** [comment]
@qt6636  
I solve this proble by change MXPredGetOutput(out, output_index, &(data[0]), size) to:
`MyPredictor* p = static_cast<MyPredictor*>(pred_hnd);//MyPredictor is the same as MXAPIPredictor in c_predict_api.cc
std::vector<mx_float> data(size);//here size is the length of output from your net
mxnet::NDArray& nd_out = p->out_arrays[output_index];
auto src = nd_out.data();
std::memcpy(&(data[0]), src.dptr_, size * sizeof(mx_float));`
this works for me, and the result is correct.

**Comment by patricianing** [comment]
@YunLexi When you did the code change, how did you update the include files and make files? In order to define the new struct, you need to include ndarray.h and all dependent header files, right? Among them, tensor.h try to include <mkl.h>. However I built mxnet with openblas, not sure why it is trying to look for mkl.h ...

**Comment by KeyKy** [comment]
@rhythm9229 could you tell me how to use openblas and naive engine?

**Comment by rhythm9229** [comment]
@KeyKy build multithreaded openblas on your system and set USE_OPENMP=1 , and set environment variable MXNET_ENGINE_TYPE to NaiveEngine
