### ISSUE TITLE
How to initialise BatchNorm by hand?

### ISSUE THREAD

**Issue by GravApple** [dmlc/mxnet#1814]
Dear all,
I want to initialise the parameters of BatchNorm by hand.
Here is how I initialise ```gamma``` and ```beta```:
```
for name, shape in zip(arg_names, arg_shapes):
    if name in ['bn_gamma']:
        fc_args[name] = mx.nd.array(np.ones(shape), ctx)
    if name in [bn_beta']:
        fc_args[name] = mx.nd.array(np.zeros(shape), ctx)
```
Yet I encounter the following error:
```TypeError: Only Accept list of NDArrays or dict of str to NDArray``` when checking the type of ```bn_moving_mean```. I notice it is in the aux, then I am wondering what is the proper way of initialising the parameters of BatchNorm?
Thanks in advance.

**Comment by LaoAnchor** [comment]
Maybe you can learn from the code example-"simple_bind" `https://github.com/dmlc/mxnet/blob/master/example/notebooks/simple_bind.ipynb`

the code to initialize the parameters of aux_states  is like this
```
aux_dict = dict(zip(aux_names, [mx.nd.zeros(shape, ctx=ctx) for shape in aux_shapes]))
for key, arr in aux_dict.items():
    if "gamma" in key:
        aux_dict[key][:] = 1
    elif "bias" in key:
        aux_dict[key][:] = 0
    elif "beta" in key:
        aux_dict[key][:] = 0
```

**Comment by GravApple** [comment]
@LaoAnchor It is my mistake of mis-initialising the aux. Anyway, thank you very much for your advice.
