### ISSUE TITLE
cannot find -lippicv

### ISSUE THREAD

**Issue by thesby** [dmlc/mxnet#1816]
ippicv is not installed by opencv, but in Makefile of mxnet, `pkg-config --libs opencv` will try to link it. So it causes an Error. I have used
`-L/usr/local/lib -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_shape -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_cudacodec -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_calib3d -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_video -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_cudaarithm -lopencv_core -lopencv_cudev` instead of `pkg-config --libs opencv` to fix the problem.

**Comment by zhangchen-qinyinghua** [comment]
This is not a mxnet problem but an opencv problem.
Try download the correct version of ippicv by yourself and move the ```libippicv.a``` to your opencv library path.

**Comment by jmerkow** [comment]
for others that come across this, i fixed this by using `locate libippicv`  then linking it to the directory in the pkg-confid file for opencv (/usr/local/lib/pkgconfig/opencv.pc), which is `/usr/local/lib`.  My command ended up being: `sudo ln -s /usr/local/share/OpenCV/3rdparty/lib/libippicv.a /usr/local/lib`

**Comment by thesby** [comment]
I think MXNet can just use what it needs.

**Comment by jordan-green** [comment]
@jmerkow I came to the same solution but limited the search to usr/local which may (or may not) be faster on large file systems:
`find /usr/local -name "libippicv.a"`

I can confirm @jmerkow's solution worked on Ubuntu 16.04
