### ISSUE TITLE
cmake has error

### ISSUE THREAD

**Issue by bjmajic** [dmlc/mxnet#1819]
i compile the mxnet in windows 7, but i found the cmake  has error ,one of the error message is 
"CMake Error at CMakeLists.txt:67 (detect_cuDNN):
  Unknown CMake command "detect_cuDNN".
i have no method to solve it , so i hope you can give me a help
thank you~!

**Comment by yajiedesign** [comment]
detect_cuDNN is in mshadow/cmake/Cuda.cmake,
Do you init and pull submodule "mshadow"?

**Comment by bjmajic** [comment]
thinks


At 2016-04-12 10:38:46, "Hu Shiwen" <notifications@github.com> wrote:


detect_cuDNN is in mshadow/cmake/Cuda.cmake,
Do you init and pull submodule "mshadow"?
