### ISSUE TITLE
what's the usage of  ' is_train' in forward?

### ISSUE THREAD

**Issue by LaoAnchor** [dmlc/mxnet#1822]
As @piiswrong  mentioned in another issue, if  i want to call backward afterwards, i should set is_train=True. But I noticed that backward op  works well  with is_train=False  in many example codes, such as "neural-style". 
On the other hand, when i just need the output. Forward op didn't work with is_train=False and worked well with is_train =True.
I'm confused with the usage of is_train parameter.

I want to ask how  is_train=True affect the output of forward Op?
Is it ok to set all is_train to True?

Anyone explaining this will be appreciated. 
Thanks in advance.

**Comment by LaoAnchor** [comment]
A guess about the design principle of is_train is that, if is_train is set to True, the intermediate results of intermediate layers will not be saved and if is_train is set to False, the intermediate results will be saved. This design principle could save memory, because forward computation doesn't need the intermediate?
Is the guess right?

**Comment by tqchen** [comment]
is_train was not related to memory saving, but will only affect some runtime behavior of operators. Currently it is mainly for things like dropout and batchnorm

**Comment by LaoAnchor** [comment]
Thank you very much. I guess i got that finally.
