### ISSUE TITLE
FCNXS parameter file download timeout

### ISSUE THREAD

**Issue by rollingstone** [dmlc/mxnet#1823]
@tornadomeet

Hi,

I am having quite some difficulty downloading the parameter files for fcnxs from baidu. It's always going timeout. Would it be possible to put the param files in other cloud drives like dropbox, box.com, which can be easily accessed from europe?

Thanks a lot

**Comment by tornadomeet** [comment]
@rollingstone ok, i'll try it today

**Comment by tornadomeet** [comment]
@rollingstone  dropbox link is here:https://www.dropbox.com/sh/578n5cxej7ofd6m/AACuSeSYGcKQDi1GoB72R5lya?dl=0
for only 2GB space in dropbox, the image set is too bigger to put there, so only the model.

**Comment by rollingstone** [comment]
@tornadomeet 

Thanks a lot :)
