### ISSUE TITLE
A question about update_params function in multi gpu mode

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1827]
I saw in model.py, the _update_params function is like this:
```
for k, p in enumerate(zip(arg_list, grad_list)):
            # faked an index here, to make optimizer create diff
            # state for the same index but on diff devs, TODO(mli)
            # use a better solution latter
            w, g = p
            updater(index*num_device+k, g, w)
```
For example if I have two gpus, and I want to update a weight based on gradients on two devices. In this way, do it mean it will run the update twice? including updating moment and other states. What if I sum the gradients up first and update the weight once using the result. Be specific, I copy the gradient from the other device and do the summation on one device, which applies to more gpus. Is this better? @tqchen @piiswrong

**Comment by Godricly** [comment]
My experience is that if you have 2 gpus, it goes to _update_params_kvstore. And arglist is the list maintaining all layers parameter, each element in arg_list will have 2 elements with respect 2 gpus in your case. grad_list is the same as arglist but storing gradient date. The _update_params_kvstore only runs once per iteration. The gradients are summed up(or averaging,I can't remember clearly) in kvstore before passing to optimizer, where the weight is updated.

**Comment by ascust** [comment]
This one is not _update_params_kvstore. It is the other one without using kvstore.

**Comment by Godricly** [comment]
Oh...I get your point. I think you are right. And I have question now. Are these weights synchronized in this case? It looks like that each device is updated in turns.

**Comment by tqchen** [comment]
The summation happens inside kvstore before applying the updater. Then the weight is pulled back to device local parameter by kvstore.pull

**Comment by ascust** [comment]
```
def _update_params(param_arrays, grad_arrays, updater, num_device,
                   kvstore=None):
    """ Perform update of param_arrays from grad_arrays not on kvstore."""
    for index, pair in enumerate(zip(param_arrays, grad_arrays)):
        arg_list, grad_list = pair
        if grad_list[0] is None:
            continue
        if kvstore:
            # push gradient, priority is negative index
            kvstore.push(index, grad_list, priority=-index)
            # pull back the sum gradients, to the same locations.
            kvstore.pull(index, grad_list, priority=-index)
        for k, p in enumerate(zip(arg_list, grad_list)):
            # faked an index here, to make optimizer create diff
            # state for the same index but on diff devs, TODO(mli)
            # use a better solution latter
            w, g = p
            updater(index*num_device+k, g, w)
```
What if the kvstore is None? So there is no push and pull. it seems there is nothing for synchronising the weights. The updater seems to update parameters on each gpu separately. @tqchen

**Comment by Godricly** [comment]
I think this function is only called when you have 1gpu on 1 machine. Try printing sth in your experiment should be helpful.

**Comment by tqchen** [comment]
Yes, kvstore can be None only when you are using one device as @Godricly suggested
