### ISSUE TITLE
face recognition with mxnet

### ISSUE THREAD

**Issue by sunbozhang** [dmlc/mxnet#1831]
how about face recognition with mxnet? anyone implements it!

**Comment by tornadomeet** [comment]
i plane to implement one recently(maybe VGG-Face or FaceNet or DeepID) for fun.

**Comment by tornadomeet** [comment]
@sunbozhang  i have trained a lightened cnn model on cascia webface, and the acc on lfw is 99.75%, you can use it for fun.  https://github.com/tornadomeet/mxnet-face

**Comment by tornadomeet** [comment]
@sunbozhang  i have trained a lightened cnn model on cascia webface, and the acc on lfw is 99.13%, you can use it for fun.  https://github.com/tornadomeet/mxnet-face

**Comment by tmatas** [comment]
@tornadomeet I've seen your project and it is very nice; moreover, the changed code does not affect the actual MxNet status, so I think it would be great if you could do a PR!

**Comment by tornadomeet** [comment]
hello @tmatas , i think it's better keep it as be independent  for 2 reasons: 1. face recognition is heavily depend on face detection and face alignment, so if give an example , it will bring in many other code. 2. the algorithm in mxnet-face currently is not very popular and some-part is  changed by myself, so if give in example in official example, it is better keep it as a standard, popular example.  
another, i'll add face detection and face alignment in mxnet-face in the further(when i have time), using deep learning totally.

**Comment by ysh329** [comment]
@tornadomeet 
Do you have DeepID MXNet model?
Recently I'm making a series of benchmark using MXNet.
