### ISSUE TITLE
mxnet-git building failure...

### ISSUE THREAD

**Issue by jiapei100** [dmlc/mxnet#1835]
Hi, all:

I'm trying to build mxnet-git with the this config.mak:

`
......
#---------------------
# choice of compiler
#--------------------

export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS =

# the additional compile flags you want to add
ADD_CFLAGS = -std=c++11 -D_FORCE_INLINES

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = NONE

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =

......
`

The errors:

> g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o data.o src/data.cc
> In file included from include/dmlc/data.h:16:0,
>                  from src/data.cc:5:
> include/dmlc/./registry.h:218:22: warning: ‘dmlc::__make_ParserFactoryReg_uint32_t_libsvm__’ defined but not used [-Wunused-variable]
>    static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
>                       ^
> include/dmlc/data.h:303:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
>    DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
>    ^
> src/data.cc:136:1: note: in expansion of macro ‘DMLC_REGISTER_DATA_PARSER’
>  DMLC_REGISTER_DATA_PARSER(uint32_t, libsvm, data::CreateLibSVMParser<uint32_t>);
>  ^
> include/dmlc/./registry.h:218:22: warning: ‘dmlc::__make_ParserFactoryReg_uint64_t_libsvm__’ defined but not used [-Wunused-variable]
>    static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
>                       ^
> include/dmlc/data.h:303:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
>    DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
>    ^
> src/data.cc:137:1: note: in expansion of macro ‘DMLC_REGISTER_DATA_PARSER’
>  DMLC_REGISTER_DATA_PARSER(uint64_t, libsvm, data::CreateLibSVMParser<uint64_t>);
>  ^
> include/dmlc/./registry.h:218:22: warning: ‘dmlc::__make_ParserFactoryReg_uint32_t_csv__’ defined but not used [-Wunused-variable]
>    static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
>                       ^
> include/dmlc/data.h:303:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
>    DMLC_REGISTRY_REGISTER(::dmlc::ParserFactoryReg<IndexType>,           \
>    ^
> src/data.cc:139:1: note: in expansion of macro ‘DMLC_REGISTER_DATA_PARSER’
>  DMLC_REGISTER_DATA_PARSER(uint32_t, csv, data::CreateCSVParser<uint32_t>);
>  ^
> In file included from include/dmlc/./registry.h:14:0,
>                  from include/dmlc/data.h:16,
>                  from src/data.cc:5:
> include/dmlc/././parameter.h:254:43: warning: ‘dmlc::data::__make__CSVParserParamParamManager__’ defined but not used [-Wunused-variable]
>    static ::dmlc::parameter::ParamManager &__make__ ## PType ## ParamManager__ = \
>                                            ^
> src/data.cc:93:1: note: in expansion of macro ‘DMLC_REGISTER_PARAMETER’
>  DMLC_REGISTER_PARAMETER(CSVParserParam);
>  ^
> g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o recordio.o src/recordio.cc
> g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o config.o src/config.cc
> ar cr libdmlc.a line_split.o recordio_split.o input_split_base.o io.o local_filesys.o data.o recordio.o config.o
> make[1]: Leaving directory '/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core'
> /usr/bin/nvcc --use_fast_math -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/mshadow/ -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1 -std=c++11 -D_FORCE_INLINES -DMXNET_USE_NVRTC=1" -M -MT build/src/ndarray/unary_function_gpu.o src/ndarray/unary_function.cu >build/src/ndarray/unary_function_gpu.d
> /usr/bin/nvcc -c -o build/src/ndarray/unary_function_gpu.o --use_fast_math -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/mshadow/ -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1 -std=c++11 -D_FORCE_INLINES -DMXNET_USE_NVRTC=1" src/ndarray/unary_function.cu
> /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h(436): error: identifier "nullptr" is undefined
> 
> /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h(436): error: expected a ";"
> 
> /usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h(200): error: expected a ";"
> 
> /usr/include/c++/5/exception(63): error: expected a ";"
> 
> /usr/include/c++/5/exception(68): error: expected a ";"
> 
> /usr/include/c++/5/exception(76): error: expected a ";"
> 
> /usr/include/c++/5/exception(83): error: expected a ";"
> 
> /usr/include/c++/5/exception(93): error: expected a "{"
> 
> /usr/include/c++/5/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"
> 
> /usr/include/c++/5/bits/exception_ptr.h(64): error: expected a "{"
> 
> /usr/include/c++/5/bits/exception_ptr.h(79): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(81): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(82): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(84): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(86): error: declaration is incompatible with previous "std::current_exception"
> (64): here
> 
> /usr/include/c++/5/bits/exception_ptr.h(86): error: use of a local type to declare a function
> 
> /usr/include/c++/5/bits/exception_ptr.h(86): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(87): error: use of a local type to declare a function
> 
> /usr/include/c++/5/bits/exception_ptr.h(90): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(92): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(95): error: incomplete type is not allowed
> 
> /usr/include/c++/5/bits/exception_ptr.h(95): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(116): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(126): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(143): error: use of a local type to declare a function
> 
> /usr/include/c++/5/bits/exception_ptr.h(144): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(147): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(152): error: use of a local type to declare a function
> 
> /usr/include/c++/5/bits/exception_ptr.h(153): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(156): error: use of a local type to declare a function
> 
> /usr/include/c++/5/bits/exception_ptr.h(157): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(160): error: use of a local type to declare a function
> 
> /usr/include/c++/5/bits/exception_ptr.h(161): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(169): error: expected a ";"
> 
> /usr/include/c++/5/bits/exception_ptr.h(195): error: expected a ";"
> 
> /usr/include/c++/5/bits/nested_exception.h(57): error: incomplete type is not allowed
> 
> /usr/include/c++/5/bits/nested_exception.h(60): error: expected a ";"
> 
> /usr/include/c++/5/bits/nested_exception.h(64): error: expected a ";"
> 
> /usr/include/c++/5/bits/nested_exception.h(66): error: expected a ";"
> 
> /usr/include/c++/5/bits/nested_exception.h(78): error: expected a ";"
> 
> /usr/include/c++/5/bits/nested_exception.h(73): error: identifier "rethrow_exception" is undefined
> 
> /usr/include/c++/5/bits/nested_exception.h(74): error: namespace "std" has no member "terminate"
> 
> /usr/include/c++/5/new(96): error: expected a "{"
> 
> /usr/include/c++/5/new(111): error: allocation operator may not be declared in a namespace
> 
> /usr/include/c++/5/new(113): error: allocation operator may not be declared in a namespace
> 
> /usr/include/c++/5/new(115): error: deallocation operator may not be declared in a namespace
> 
> /usr/include/c++/5/new(115): error: expected a "{"
> 
> /usr/include/c++/5/new(130): error: identifier "__p" is undefined
> 
> /usr/include/c++/5/new(131): error: allocation operator may not be declared in a namespace
> 
> /usr/include/c++/5/new(131): error: expected a "{"
> 
> /usr/include/c++/5/new(135): error: deallocation operator may not be declared in a namespace
> 
> /usr/include/c++/5/new(135): error: expected a "{"
> 
> /usr/include/c++/5/new(136): error: deallocation operator may not be declared in a namespace
> 
> /usr/include/c++/5/new(136): error: expected a "{"
> 
> /usr/include/c++/5/bits/cpp_type_traits.h(185): error: identifier "char16_t" is undefined
> 
> /usr/include/c++/5/bits/cpp_type_traits.h(192): error: identifier "char32_t" is undefined
> 
> /usr/include/c++/5/bits/cpp_type_traits.h(192): error: class "std::__is_integer<<error-type>>" has already been defined
> 
> /usr/include/c++/5/bits/cpp_type_traits.h(344): error: namespace "std::__gnu_cxx" has no member "__normal_iterator"
> 
> /usr/include/c++/5/bits/cpp_type_traits.h(344): error: expected a ">"
> 
> /usr/include/c++/5/ext/type_traits.h(159): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/ext/type_traits.h(160): error: declaration is incompatible with overloaded function "__gnu_cxx::__is_null_pointer"
> (150): here
> 
> /usr/include/c++/5/ext/type_traits.h(160): error: namespace "std" has no member "nullptr_t"
> 
> /usr/include/c++/5/ext/type_traits.h(161): error: expected a ";"
> 
> /usr/include/c++/5/ext/type_traits.h(173): error: a template argument list is not allowed in a declaration of a primary template
> 
> /usr/include/c++/5/ext/type_traits.h(177): error: __promote is not a template
> 
> /usr/include/c++/5/ext/type_traits.h(181): error: __promote is not a template
> 
> /usr/include/c++/5/ext/type_traits.h(185): error: __promote is not a template
> 
> /usr/include/c++/5/ext/type_traits.h(189): error: __promote is not a template
> 
> /usr/include/c++/5/ext/type_traits.h(189): error: expected a ">"
> 
> /usr/include/c++/5/ext/type_traits.h(189): error: the global scope has no "__type"
> 
> /usr/include/c++/5/ext/type_traits.h(197): error: __promote is not a template
> 
> /usr/include/c++/5/ext/type_traits.h(197): error: expected a ">"
> 
> /usr/include/c++/5/ext/type_traits.h(197): error: the global scope has no "__type"
> 
> /usr/include/c++/5/ext/type_traits.h(206): error: __promote is not a template
> 
> /usr/include/c++/5/ext/type_traits.h(206): error: expected a ">"
> 
> /usr/include/c++/5/ext/type_traits.h(206): error: the global scope has no "__type"
> 
> /usr/include/c++/5/cmath(80): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/cmath(80): error: expected a ";"
> 
> /usr/include/c++/5/cmath(105): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/cmath(105): error: variable "std::constexpr" has already been defined
> 
> /usr/include/c++/5/cmath(105): error: expected a ";"
> 
> /usr/include/c++/5/cmath(124): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/cmath(124): error: variable "std::constexpr" has already been defined
> 
> /usr/include/c++/5/cmath(124): error: expected a ";"
> 
> /usr/include/c++/5/cmath(143): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/cmath(143): error: variable "std::constexpr" has already been defined
> 
> /usr/include/c++/5/cmath(143): error: expected a ";"
> 
> /usr/include/c++/5/cmath(162): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/cmath(162): error: variable "std::constexpr" has already been defined
> 
> /usr/include/c++/5/cmath(162): error: expected a ";"
> 
> /usr/include/c++/5/cmath(183): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/cmath(183): error: variable "std::constexpr" has already been defined
> 
> /usr/include/c++/5/cmath(183): error: expected a ";"
> 
> /usr/include/c++/5/cmath(202): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/cmath(202): error: variable "std::constexpr" has already been defined
> 
> /usr/include/c++/5/cmath(202): error: expected a ";"
> 
> /usr/include/c++/5/cmath(221): error: inline specifier allowed on function declarations only
> 
> /usr/include/c++/5/cmath(221): error: variable "std::constexpr" has already been defined
> 
> /usr/include/c++/5/cmath(221): error: expected a ";"
> 
> /usr/include/c++/5/cmath(240): error: inline specifier allowed on function declarations only
> 
> Error limit reached.
> 100 errors detected in the compilation of "/tmp/tmpxft_00004c79_00000000-7_unary_function.cpp1.ii".
> Compilation terminated.
> Makefile:157: recipe for target 'build/src/ndarray/unary_function_gpu.o' failed
> make: *** [build/src/ndarray/unary_function_gpu.o] Error 4
> 

Does anybody meet the same errors? How to solve this issue?

Cheers
Pei

**Comment by piiswrong** [comment]
you need gcc 4.8 or 4.9

**Comment by jiapei100** [comment]
Any possibility for gcc 5.3.1 ??

**Comment by junlizhang** [comment]
I met the same nullptr error talked before and tried using gcc4.8.5/4.9.4/5.3.1 all of them do not give some help. After change "export NVCC = nvcc" to "export NVCC = '/usr/local/cuda/bin/nvcc -std=c++11'" in make/config.mk, the nullptr error sovled.
Meanwhile, because I'm on an RHEL7.3 ppc64le machine shipped with 4 P100 GPU which does not support sse but vsx, I have to use "sed -i -e 's:-msse2:-mvsx:g' $(grep -r -- '-msse2' *|cut -f1 -d':')" to replace the sse option to vsx.  Patch can be found at [patch.txt](https://github.com/dmlc/mxnet/files/678402/patch.txt)

[root@gp100 mxnet]# file bin/im2rec
bin/im2rec: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=15330b715f5d1f6b7ff9ca0847791f99cec9f648, not stripped

[root@gp100 mxnet]# ldd bin/im2rec
	linux-vdso64.so.1 =>  (0x00003fff96c70000)
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00003fff96be0000)
	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00003fff94350000)
	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00003fff905c0000)
	libopenblas.so.0 => /opt/openblas/lib/libopenblas.so.0 (0x00003fff8fa10000)
	librt.so.1 => /lib64/librt.so.1 (0x00003fff8f9c0000)
	libopencv_calib3d.so.2.4 => /lib64/libopencv_calib3d.so.2.4 (0x00003fff8f900000)
	libopencv_contrib.so.2.4 => /lib64/libopencv_contrib.so.2.4 (0x00003fff8f7f0000)
	libopencv_core.so.2.4 => /lib64/libopencv_core.so.2.4 (0x00003fff8f560000)
	libopencv_features2d.so.2.4 => /lib64/libopencv_features2d.so.2.4 (0x00003fff8f480000)
	libopencv_flann.so.2.4 => /lib64/libopencv_flann.so.2.4 (0x00003fff8f3e0000)
	libopencv_highgui.so.2.4 => /lib64/libopencv_highgui.so.2.4 (0x00003fff8f360000)
	libopencv_imgproc.so.2.4 => /lib64/libopencv_imgproc.so.2.4 (0x00003fff8f0d0000)
	libopencv_legacy.so.2.4 => /lib64/libopencv_legacy.so.2.4 (0x00003fff8ef70000)
	libopencv_ml.so.2.4 => /lib64/libopencv_ml.so.2.4 (0x00003fff8eec0000)
	libopencv_objdetect.so.2.4 => /lib64/libopencv_objdetect.so.2.4 (0x00003fff8ee10000)
	libopencv_photo.so.2.4 => /lib64/libopencv_photo.so.2.4 (0x00003fff8edd0000)
	libopencv_stitching.so.2.4 => /lib64/libopencv_stitching.so.2.4 (0x00003fff8ed40000)
	libopencv_superres.so.2.4 => /lib64/libopencv_superres.so.2.4 (0x00003fff8ecf0000)
	libopencv_ts.so.2.4 => /lib64/libopencv_ts.so.2.4 (0x00003fff8ec00000)
	libopencv_video.so.2.4 => /lib64/libopencv_video.so.2.4 (0x00003fff8eb90000)
	libopencv_videostab.so.2.4 => /lib64/libopencv_videostab.so.2.4 (0x00003fff8eb30000)
	libcudnn.so.5 => /usr/local/cuda/lib64/libcudnn.so.5 (0x00003fff89f40000)
	libcuda.so.1 => /usr/lib/nvidia/libcuda.so.1 (0x00003fff89700000)
	libnvrtc.so.8.0 => /usr/local/cuda/lib64/libnvrtc.so.8.0 (0x00003fff88390000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00003fff88200000)
	libm.so.6 => /lib64/libm.so.6 (0x00003fff88120000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00003fff880c0000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00003fff88080000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00003fff88040000)
	libc.so.6 => /lib64/libc.so.6 (0x00003fff87e60000)
	/lib64/ld64.so.2 (0x0000000023fa0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00003fff87e30000)
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00003fff87be0000)
	libz.so.1 => /lib64/libz.so.1 (0x00003fff87ba0000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00003fff87b20000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00003fff87ac0000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00003fff87a20000)
	libjasper.so.1 => /lib64/libjasper.so.1 (0x00003fff879a0000)
	libImath.so.6 => /lib64/libImath.so.6 (0x00003fff87970000)
	libIlmImf.so.7 => /lib64/libIlmImf.so.7 (0x00003fff87860000)
	libIex.so.6 => /lib64/libIex.so.6 (0x00003fff87820000)
	libHalf.so.6 => /lib64/libHalf.so.6 (0x00003fff877b0000)
	libIlmThread.so.6 => /lib64/libIlmThread.so.6 (0x00003fff87780000)
	libgtk-x11-2.0.so.0 => /lib64/libgtk-x11-2.0.so.0 (0x00003fff871a0000)
	libgdk-x11-2.0.so.0 => /lib64/libgdk-x11-2.0.so.0 (0x00003fff87090000)
	libatk-1.0.so.0 => /lib64/libatk-1.0.so.0 (0x00003fff87040000)
	libgio-2.0.so.0 => /lib64/libgio-2.0.so.0 (0x00003fff86e20000)
	libpangoft2-1.0.so.0 => /lib64/libpangoft2-1.0.so.0 (0x00003fff86de0000)
	libpangocairo-1.0.so.0 => /lib64/libpangocairo-1.0.so.0 (0x00003fff86db0000)
	libgdk_pixbuf-2.0.so.0 => /lib64/libgdk_pixbuf-2.0.so.0 (0x00003fff86d60000)
	libcairo.so.2 => /lib64/libcairo.so.2 (0x00003fff86be0000)
	libpango-1.0.so.0 => /lib64/libpango-1.0.so.0 (0x00003fff86b60000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00003fff86af0000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00003fff86a60000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00003fff868d0000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00003fff867f0000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00003fff867c0000)
	libgstbase-0.10.so.0 => /lib64/libgstbase-0.10.so.0 (0x00003fff86730000)
	libgstreamer-0.10.so.0 => /lib64/libgstreamer-0.10.so.0 (0x00003fff865f0000)
	libgmodule-2.0.so.0 => /lib64/libgmodule-2.0.so.0 (0x00003fff865c0000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00003fff86380000)
	libgstapp-0.10.so.0 => /lib64/libgstapp-0.10.so.0 (0x00003fff86350000)
	libgstvideo-0.10.so.0 => /lib64/libgstvideo-0.10.so.0 (0x00003fff86310000)
	libv4l1.so.0 => /lib64/libv4l1.so.0 (0x00003fff862e0000)
	libnvidia-fatbinaryloader.so.361.107 => /usr/lib/nvidia/libnvidia-fatbinaryloader.so.361.107 (0x00003fff86270000)
	libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00003fff86240000)
	libIexMath.so.6 => /lib64/libIexMath.so.6 (0x00003fff86210000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00003fff86080000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00003fff86050000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00003fff86020000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00003fff85ff0000)
	libXi.so.6 => /lib64/libXi.so.6 (0x00003fff85fb0000)
	libXrandr.so.2 => /lib64/libXrandr.so.2 (0x00003fff85f80000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00003fff85f50000)
	libXcomposite.so.1 => /lib64/libXcomposite.so.1 (0x00003fff85f20000)
	libXdamage.so.1 => /lib64/libXdamage.so.1 (0x00003fff85ef0000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00003fff85eb0000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00003fff85e80000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00003fff85e30000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00003fff85df0000)
	libharfbuzz.so.0 => /lib64/libharfbuzz.so.0 (0x00003fff85d70000)
	libpixman-1.so.0 => /lib64/libpixman-1.so.0 (0x00003fff85cc0000)
	libEGL.so.1 => /lib64/libEGL.so.1 (0x00003fff85c60000)
	libxcb-shm.so.0 => /lib64/libxcb-shm.so.0 (0x00003fff85c30000)
	libxcb-render.so.0 => /lib64/libxcb-render.so.0 (0x00003fff85c00000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00003fff85bb0000)
	libGL.so.1 => /lib64/libGL.so.1 (0x00003fff85ae0000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00003fff85a90000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00003fff85a30000)
	liborc-0.4.so.0 => /lib64/liborc-0.4.so.0 (0x00003fff85960000)
	libv4l2.so.0 => /lib64/libv4l2.so.0 (0x00003fff85930000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00003fff858c0000)
	libgraphite2.so.3 => /lib64/libgraphite2.so.3 (0x00003fff85870000)
	libX11-xcb.so.1 => /lib64/libX11-xcb.so.1 (0x00003fff85840000)
	libxcb-dri2.so.0 => /lib64/libxcb-dri2.so.0 (0x00003fff85810000)
	libxcb-dri3.so.0 => /lib64/libxcb-dri3.so.0 (0x00003fff857e0000)
	libxcb-present.so.0 => /lib64/libxcb-present.so.0 (0x00003fff857b0000)
	libxcb-randr.so.0 => /lib64/libxcb-randr.so.0 (0x00003fff85780000)
	libxcb-xfixes.so.0 => /lib64/libxcb-xfixes.so.0 (0x00003fff85750000)
	libxcb-shape.so.0 => /lib64/libxcb-shape.so.0 (0x00003fff85720000)
	libxcb-sync.so.1 => /lib64/libxcb-sync.so.1 (0x00003fff856f0000)
	libxshmfence.so.1 => /lib64/libxshmfence.so.1 (0x00003fff856c0000)
	libgbm.so.1 => /lib64/libgbm.so.1 (0x00003fff85690000)
	libdrm.so.2 => /lib64/libdrm.so.2 (0x00003fff85650000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00003fff85620000)
	libglapi.so.0 => /lib64/libglapi.so.0 (0x00003fff85590000)
	libxcb-glx.so.0 => /lib64/libxcb-glx.so.0 (0x00003fff85550000)
	libXxf86vm.so.1 => /lib64/libXxf86vm.so.1 (0x00003fff85520000)
	libv4lconvert.so.0 => /lib64/libv4lconvert.so.0 (0x00003fff85480000)
