### ISSUE TITLE
How can I initialize the weight with gaussian distribution?

### ISSUE THREAD

**Issue by dushoufu** [dmlc/mxnet#1838]
I see a api "class mxnet.initializer.Normal(sigma=0.01)",but i don't know how to use it in my program.
For example,
weight1 = mx.symbol.Variable('con1_weight')
conv1 = mx.symbol.Convolution(weight=weight1,bias=bias,
    data=input_data, kernel=(4, 4), stride=(1, 1), num_filter=20,workspace=1024)

How to initialise the weight1 using mxnet.initializer.Normal? I have not found any example about using it.

Thanks.

**Comment by Ldpe2G** [comment]
You can refer to  this example:
https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py
line 72

**Comment by dushoufu** [comment]
@Ldpe2G 
Do you mean like the blow? Can I initialise every convolution layer with different gaussian distribution parameters like caffe?
model = mx.model.FeedForward(
        ctx                = devs,
        symbol             = network,
        num_epoch          = args.num_epochs,
        learning_rate      = args.lr,
        momentum           = 0.9,
        wd                 = 0.00001,
        initializer        = mx.init.Xavier(factor_type="in", magnitude=2.34),
        **model_args)

**Comment by Ldpe2G** [comment]
You can do that, for example:


import mxnet as mx
import numpy as np

// define net 
data = mx.symbol.Variable(name='data')
conv1 = mx.symbol.Convolution(name='conv1', data=data , num_filter=64, kernel=(3,3), stride=(1,1))
conv2 = mx.symbol.Convolution(name='conv2', data=conv1 , num_filter=64, kernel=(3,3), stride=(1,1))

arg_names = conv2.list_arguments()
print arg_names
// ['data', 'conv1_weight', 'conv1_bias', 'conv2_weight', 'conv2_bias']

// infer network parameters shape and output shape
arg_shape, out_shape, aux_shape = conv2.infer_shape(data=(1, 3, 100, 100))
arg_dict = dict(zip(arg_names, [mx.nd.zeros(shape, ctx=mx.cpu()) for shape in arg_shape]))

// then you can init each layer with what ever you like
arg_dict['conv1_weight'][:] = np.random.uniform(-0.1, 0.1, arg_dict['conv1_weight'].shape) 

arg_dict['conv2_weight'][:] = np.random.normal(0, 1, arg_dict['conv2_weight'].shape) 


// last step
// Bind the Symbols with NDArray and Run
executor = conv2.bind(ctx=mx.cpu(), args=arg_dict)

more details:
http://mxnet.readthedocs.org/en/latest/python/tutorial.html

**Comment by dushoufu** [comment]
thank you! But it is a little complex. I would try!

**Comment by dushoufu** [comment]
I'm sorry. I wonder "in data=(1, 3, 100, 100)," , whether 1 is batchsize, 3 is dimension. @Ldpe2G

**Comment by dushoufu** [comment]
I think the (1, 3, 100, 100) is the shap of input data. Is it correct?@Ldpe2G

**Comment by dushoufu** [comment]
HI, I change it as bellow, the prompt is "AttributeError: 'Executor' object has no attribute 'FeedForward'" . Even though I understand this error, I still don't know how to modify my previous codes. Could you help   @Ldpe2G 

arg_dict['con1_weight'][:] = np.random.normal(0, 0.125, arg_dict['con1_weight'].shape)
arg_dict['con2_weight'][:] = np.random.normal(0, 0.2, arg_dict['con2_weight'].shape)
arg_dict['con3_weight'][:] = np.random.normal(0, 0.2, arg_dict['con3_weight'].shape)
arg_dict['con4_weight'][:] = np.random.normal(0, 0.5, arg_dict['con4_weight'].shape)
arg_dict['fullyconnected0_weight'][:] = np.random.normal(0, 0.0001, arg_dict['fullyconnected0_weight'].shape)

arg_dict['bias'][:] = np.zeros(arg_dict['bias'].shape)
arg_dict['convolution2_bias'][:] = np.zeros(arg_dict['convolution2_bias'].shape)
arg_dict['fullyconnected1_bias'][:] = np.zeros(arg_dict['fullyconnected1_bias'].shape)

## train
num_gpus = 2 
gpus = [mx.gpu(i) for i in range(num_gpus)]

executor = softmax.bind(ctx=gpus, args=arg_dict)

model = executor.FeedForward(
    ctx           = gpus,
    symbol        = softmax,
    num_epoch     = 20,
    learning_rate = 0.00001,
    momentum      = 0.9,
    initializer   = mx.initializer.Normal(sigma=0.01),
    wd            = 0.00001)

**Comment by Ldpe2G** [comment]
Executor class do not has  function "FeedForward",
https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor.py

**Comment by dushoufu** [comment]
Thanks you!  I see,but I just want to know how I can transform my original codes to the new codes after using executor only for initializing the weights of every layer. If i don't using Feedward", how can all of the parameters used by FeedWard be transfer to Executor?  @Ldpe2G

**Comment by Ldpe2G** [comment]
import mxnet as mx
import numpy as np

data = mx.symbol.Variable(name='data')
conv1 = mx.symbol.Convolution(name='conv1', data=data , num_filter=64, kernel=(3,3), stride=(1,1))
conv2 = mx.symbol.Convolution(name='conv2', data=conv1 , num_filter=64, kernel=(3,3), stride=(1,1))
fc1  = mx.symbol.FullyConnected(data = conv2, num_hidden=100)
softmax  = mx.symbol.SoftmaxOutput(data = fc1)


arg_names = softmax.list_arguments()
print arg_names

arg_shape, out_shape, aux_shape = softmax.infer_shape(data=(1, 1, 100, 100))
arg_dict = dict(zip(arg_names, [mx.nd.zeros(shape, ctx=mx.gpu()) for shape in arg_shape]))

arg_dict['conv1_weight'][:] = np.random.normal(0, 0.125, arg_dict['conv1_weight'].shape)
arg_dict['conv2_weight'][:] = np.random.normal(0, 0.2, arg_dict['conv2_weight'].shape)
arg_dict['fullyconnected0_weight'][:] = np.random.normal(0, 0.0001, arg_dict['fullyconnected0_weight'].shape)

grad_dict = dict(zip(arg_names, [mx.nd.zeros(shape, ctx=mx.gpu()) for shape in arg_shape]))


executor = softmax.bind(ctx=mx.gpu(), args=arg_dict, args_grad=grad_dict, grad_req="write")

lr = mx.lr_scheduler.FactorScheduler(step=10, factor=.9)
optimizer = mx.optimizer.SGD(
    learning_rate = 0.001,
    momentum = 0.9,
    wd = 0.005,
    lr_scheduler = lr,
    clip_gradient = 10)

optim_states_conv1 = optimizer.create_state(0, grad_dict['conv1_weight']) 
optim_states_conv2 = optimizer.create_state(1, grad_dict['conv2_weight']) 
optim_states_fully1 = optimizer.create_state(2, grad_dict['fullyconnected0_weight']) 

max_iters = 1000
for e in range(max_iters):
	executor.forward()
	executor.backward() 
	if e % 100 == 0:
		norm = np.linalg.norm(arg_dict['conv1_weight'].asnumpy())
		print norm
	optimizer.update(0, arg_dict['conv1_weight'], grad_dict['conv1_weight'], optim_states_conv1)
	optimizer.update(1, arg_dict['conv2_weight'], grad_dict['conv2_weight'], optim_states_conv2)
	optimizer.update(2, arg_dict['fullyconnected0_weight'], grad_dict['fullyconnected0_weight'], optim_states_fully1)

I figure it out by refer to the API and the examples provided,  but I am not sure it is right,

**Comment by dushoufu** [comment]
Thank you very much! I think the most difficult to use mxnet is that examples of api is limited. @Ldpe2G

**Comment by dushoufu** [comment]
Thank you very much! It's too complex,can you give me a contact number,like wechat or phone number,I can consult effectively. I think the most difficult to use mxnet is that examples of api is limited. @Ldpe2G @piiswrong

**Comment by Ldpe2G** [comment]
My e-mail liangdepeng33@163.com

**Comment by dushoufu** [comment]
This way is too complex. It seems we should control the detailed process of forward and backward.
How about fit ？ Can we directly use fit，because fit also has a parameter "optimizer". @Ldpe2G @piiswrong
model.fit(X = train, eval_data = val,
          batch_end_callback = mx.callback.Speedometer(batch_size=batch_size),
          epoch_end_callback = checkpoint)

**Comment by dushoufu** [comment]
I complete it by modifying the source code of mxnet, it seems to be simple and elegant.

**Comment by ngmanhei** [comment]
@Ldpe2G Your advice does help a lot!
