### ISSUE TITLE
running the test case failed

### ISSUE THREAD

**Issue by yuzcccc** [dmlc/mxnet#184]
In the instruction, to run the test case, it says:
cd ..; python example/mnist/mlp.py

However, directly running this will lead to the error of 'ImportError: No module named get_data'
When I use ' cd example/mnist/ ' and then python mlp.py, the script runs correctly.

**Comment by lfwin** [comment]
I also got this problem.

**Comment by antinucleon** [comment]
```mlp.py``` will use ```data.py``` to get MNIST data automatically. In the ```data.py```, we use a special script for test to download the data and it only be imported in this path. You can check ```data.py``` to see how it works.

**Comment by lfwin** [comment]
This can be solved by cope data.py in the file example/minist
