### ISSUE TITLE
Python submodule 'module' is not installed by 'python setup.py install'

### ISSUE THREAD

**Issue by zhangcx93** [dmlc/mxnet#1841]
In setup.py, there's only packages=['mxnet'], so after installation, the mxnet.module will not be copied to the installation folder, import it globally will raise Import Error.

so add packages=['mxnet', 'mxnet.module'] will solve this problem.

**Comment by pluskid** [comment]
Thanks for reporting this! I added a commit 6a9fcdde3a61ef382466a714fc459de14ce8c5b2 Should be able to fix this once #1833 is merged.
