### ISSUE TITLE
mxnet-git building failure...

### ISSUE THREAD

**Issue by jiapei100** [dmlc/mxnet#1844]
I'm using GCC 5.3.1, Cuda 7.5 under Ubuntu 16.04 beta 2.

My config.mk:

`
#---------------------
# choice of compiler
#--------------------

export CC = gcc
export CXX = g++ -std=c++11 -D_FORCE_INLINES
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS =

# the additional compile flags you want to add
ADD_CFLAGS = -std=c++11 -D_FORCE_INLINES

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = NONE

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =
`

This is my current error messages:

`
nvcc -c -o build/src/ndarray/unary_function_gpu.o --use_fast_math -g -O3 -ccbin g++ -std=c++11 -D_FORCE_INLINES  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/mshadow/ -I/home/jiapei/Downloads/machinelearning/deeplearning/dmlc/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1 -std=c++11 -D_FORCE_INLINES -DMXNET_USE_NVRTC=1" src/ndarray/unary_function.cu
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00002086_00000000-7_unary_function.cpp1.ii".
Makefile:157: recipe for target 'build/src/ndarray/unary_function_gpu.o' failed
make: *** [build/src/ndarray/unary_function_gpu.o] Error 2
`

Any suggestions?

Cheers
Pei

**Comment by izzz** [comment]
For anyone else coming across this. Setting 
`ADD_CFLAGS = -D_MWAITXINTRIN_H_INCLUDED -D__STRICT_ANSI__`
in make/config.mk solved it for me (based on [this](https://github.com/tensorflow/tensorflow/issues/1066#issue-133111577)).

**Comment by redger-au** [comment]
On ubuntu Xenial I experienced success by making the following 2 changes

- Change mxnet/Makefile   so that the line 
`CFLAGS = -DMSHADOW_FORCE_STREAM $(WARNFLAGS)`
becomes
`CFLAGS = -D_MWAITXINTRIN_H_INCLUDED -DMSHADOW_FORCE_STREAM $(WARNFLAGS)`

- Change mxnet/make/config.mk   so that the line 
`ADD_CFLAGS =`
becomes
`ADD_CFLAGS = -D_FORCE_INLINES`
