### ISSUE TITLE
cannot import mxnet with the latest version

### ISSUE THREAD

**Issue by George19890617** [dmlc/mxnet#1846]
I found cannot import mxnet in any path except $HOME/mxnet/python

. But I solved this my copy $HOME/mxnet/python/mxnet/module to python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ by hand.
Is there anything wrong with setup.py, however.

**Comment by piiswrong** [comment]
@pluskid 
Is module added to setup.py?

**Comment by pluskid** [comment]
It was added in a recent PR. See [here](https://github.com/dmlc/mxnet/blob/master/python/setup.py#L24). Can you try with the latest code? Thanks!

**Comment by pluskid** [comment]
Should be fixed now. Feel free to re-open if it still does not import correctly for you.
