### ISSUE TITLE
Is is possible to train mxnet on multi CPU cluster?

### ISSUE THREAD

**Issue by sunshineatnoon** [dmlc/mxnet#185]
The introduction says that mxnet can be trained on multi GPU, how about CPU cluster? Thx.

**Comment by antinucleon** [comment]
We will add distributed parameter sever support soon. Currently design is easy to extend to distributed case but we don't add it yet.

**Comment by sunshineatnoon** [comment]
Thanks, looking forward to it!

**Comment by zachmayer** [comment]
Has "distributed parameter sever support" been added yet?

**Comment by antinucleon** [comment]
Yes. Here is the doc:
https://mxnet.readthedocs.org/en/latest/distributed_training.html

**Comment by hsaputra** [comment]
Looks like it is returning 404?
