### ISSUE TITLE
Implementing XNOR-Net in MXNET

### ISSUE THREAD

**Issue by zencoding** [dmlc/mxnet#1867]
Hi,
    I am implemented XNOR-Net (http://arxiv.org/abs/1603.05279) by creating a new operator that does the weight modification and convolution modification as suggested in the paper at Equation 5 and Equation 1.  Authors claim 32x reduction in memory and this should also significantly speed up the convolution, however I don't see any evidence of claims of memory/power/speed improvements with the implementation.   I ran the CIFAR dataset through both models and they produce the exact model size, memory usage and time of execution in both GPU and CPU.  The only difference is in the accuracy of the predication, the XNOR-Net produces lesser accuracy as expected.  

My question is am I missing something in terms of benefits of memory/speed/model size when using XNOR-Net?, should I do try some other processing to take advantage of Binary values of weight matrix? or should I implement my own Convolution operation that operates on Binary values of weight matrix instead standard unpack/dot multiplication ?

Below are the changes I made to the Convolution Operator for implementing XNOR-Net

```
//Before Convolution is called, get average abs weight value per filter (Equation 5)
    Stream<cpu> *cpu_stream_ = NewStream<cpu>();
    Tensor<xpu,1> alpha_mat = NewTensor<xpu,real_t>(Shape1(wmat_shape[1]),0.0f,false,s);
    Tensor<cpu,1> alpha_cpu = NewTensor<cpu,real_t>(alpha_mat.shape_,0.0f,false,cpu_stream_);
    TensorContainer<xpu,3,real_t> wmat_b(wmat_shape);
    wmat_b.set_stream(s);
    alpha_mat += sumall_except_dim<1>(F<mshadow_op::abs>(wmat));
    alpha_mat /=wmat_shape.Size();

    //Copy to cpu in order to use value as index
    Copy(alpha_cpu,alpha_mat,s);
    wmat = F<mshadow_op::sign>(wmat);


//After Convolution is called, Equation 1
      TensorContainer<xpu,4,real_t> tmp_conv(mshadow::Shape4(param_.num_filter,
                                                  step,
                                                  out.size(2),
                                                  out.size(3)));
     tmp_conv.set_stream(s);
     tmp_conv = reshape(temp_dst,mshadow::Shape4(param_.num_filter,
                                                  step,
                                                  out.size(2),
                                                  out.size(3)));
           for(index_t filter_num =0 ; filter_num< alpha_cpu.size(0);++filter_num) {
                 real_t alpha = alpha_cpu[filter_num];
                tmp_conv[filter_num] = tmp_conv[filter_num]*alpha;
          wmat[filter_num] = wmat[filter_num]*alpha;
        }
```

Any insights or suggestions?

**Comment by tqchen** [comment]
To get speedup for binary input, I do think we need to have a customized convolution that simply do bit counts, as opposed to using the traditional floating points

**Comment by zencoding** [comment]
Thanks, I also assumed that I need to change the standard convolution to bit operations, how about storage of the model, do I need to implement some scheme to store compressed bit representation of Weight parameters in order to reduce the size of the model?

**Comment by changtimwu** [comment]
Related discussion in tensorflow https://github.com/tensorflow/tensorflow/issues/1592.

**Comment by AaronYKing** [comment]
Hi,
Do you have implemented XNOR-Net (http://arxiv.org/abs/1603.05279)? And what problems about it now?
