### ISSUE TITLE
LSTM shared weights ?

### ISSUE THREAD

**Issue by hack1nt0** [dmlc/mxnet#1869]
I noticed that the lstm-cell implemetation in [example/rnn/lstm.py] is using shared weights, in which the input (h_{h-1}, x_t) of lstm-cell all do the same affine transformation before going to the forget gate, update gate and output gate. This is different from the separate weights implementation I saw, include the one in [colah](http://colah.github.io/posts/2015-08-Understanding-LSTMs/) and [WildML](http://colah.github.io/posts/2015-08-Understanding-LSTMs/)

Am I wrong, or the SliceChannel do something behind? @antinucleon @pluskid

**Comment by sxjscience** [comment]
The hidden states have been multiplied by 4 https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py#L24. The SliceChannel Op will do the splitting job. LSTM without peephole connection can be implemented this way I think (Similar to http://deeplearning.net/tutorial/lstm.html).

**Comment by hack1nt0** [comment]
Great, it's really an interesting and matrix-style implementation. Thx @sxjscience 

Btw, why the SliceChannel don't accept a formal argument which specifies the size of outputs, which may produce different shape output ?
