### ISSUE TITLE
Using the recently added reduce/broadcasting symbols

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#1872]
It seems that these symbols https://github.com/dmlc/mxnet/blob/master/src/operator/broadcast_reduce_op-inl.h cannot be found in the python side by using `mx.symbol`. I'm using the latest version of MXNet.

**Comment by piiswrong** [comment]
git submodule update && make clean && make

**Comment by sxjscience** [comment]
Thanks @piiswrong . It seems to be related to the `kNotRegisterSymbolic`  flag  https://github.com/dmlc/mxnet/blob/master/src/operator/broadcast_reduce_op-inl.h#L169 , which turns off the symbolic part of these operators.
