### ISSUE TITLE
"Segmentation fault" on checkpoint read with custom loss

### ISSUE THREAD

**Issue by ZEMUSHKA** [dmlc/mxnet#1887]
Hi!

I've trained model with custom loss inherited from mx.operator.NumpyOp as in example folder.
After training, with epoch_end_callback=[mx.callback.do_checkpoint("yelp/New-Inception")] I cannot load any checkpoint of that model, it fails with segfault.

What seems strange to me is the following lines in yelp/New-Inception-symbol.json:

`{
      "op": "_Native",
      "param": {
        "info": "0x3d54b10",
        "need_top_grad": "False"
      },
      "name": "softmax",
      "inputs": [[593, 0], [594, 0]],
      "backward_source_id": -1
}`

I think it's wrong to store anything like "0x3d54b10" in symbol params.

**Comment by piiswrong** [comment]
numpy op doesn't support checkpoint loading. You need to reconstruct the model and use mx.init.Load to load it
