### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by mklf** [dmlc/mxnet#1898]
Hi all,
I am new to mxnet, and I find some links in` README.md` are broken,this is the list of  them :
* Embedding Torch layers and functions in MXNet
* MXNet on Mobile Device
* Distributed Training
* Guide to Creating New Operators (Layers)
* Training Deep Net on 14 Million Images on A Single Machine
* Installation
* Contribute to MXNet
* Frequent Asked Questions

**Comment by tqchen** [comment]
Thanks for reporting this. these are now fixed
