### ISSUE TITLE
Packing format for .params file

### ISSUE THREAD

**Issue by Piyush3dB** [dmlc/mxnet#1899]
Hello,

I'd like to understand in a bit detail the weights packing format used by MXNet when constructing a .params file?  Are there any resources I can quickly skim over to gather this info?  If not which source files should I look at to understand this?

Many thanks,
Piyush.

**Comment by piiswrong** [comment]
ndarray.cc: save

**Comment by Piyush3dB** [comment]
Thanks @piiswrong 

For the record I also found the Caffe Converter at [tools/caffe_converter/convert_model.py] useful to understand how the .params file is constructed.  Thanks.
