### ISSUE TITLE
kv_store multi-machine support

### ISSUE THREAD

**Issue by kandycs** [dmlc/mxnet#1900]
Hi everybody,
I met an issue when building the mxnet with USE_DIST_KVSTORE=1, 
It reported "error: ‘ps::Environment’ has not been declared". I checked ps-lite library 
but did not find "Environment" members. How can I resolve this problem ?

**Comment by piiswrong** [comment]
git pull && git submodule update && make clean && make

**Comment by kandycs** [comment]
Thanks piiswrong, it is resolved.
