### ISSUE TITLE
Random scaling in image augmentation

### ISSUE THREAD

**Issue by vincentfung13** [dmlc/mxnet#1905]
Hi all,

I am new to mxnet (to deep learning in general), and in my project I am in a situation where I need to do some scaling on the images for augmentation.

I was using the provided ImageAugmenter class for this - setting the min_random_scale and max_random_scale parameters when initialising the ImageRecordIter. However, after some digging into the source code I found what the augmenter actually does is to scale the image then crop it to fit the predefined data_shape. What I want is to randomly scale the image while retaining its content, which means an image is first scaled, then resized again to the predefined data_shape.

I managed to change the original ImageAugmenter class so it now does what I wanted, but I am not sure if it is the best place to put the changes in (potential merge conflicts if something new is added to the augmenter in the future). I can think of implementing my own augmenter but it looks like I will need to implement a new ImageRecordIter and a ImageIOParser as well, I am not sure if the effort is worth it if all I want is just to add a new augmentation approach. 

Can someone point me to a right direction? Any help is much appreciated. :)

Cheers,
Vincent

**Comment by tqchen** [comment]
there is a recent refactor that enables you to plugin your own augmenter by registering it.

see https://github.com/dmlc/mxnet/pull/1956

So now you can build your augmenter class in a new file, register it as aug_default.cc and switch to your augmenter by setting ```aug_seq``` in ImageRecordIter

**Comment by vincentfung13** [comment]
Thank you for making the refactor, this looks much more feasible now. :)

**Comment by shipeng-uestc** [comment]
Hi, how do you make your own augmenter.Can you share it with me ?

**Comment by TccccD** [comment]
Hi, @vincentfung13 @shipeng-uestc @tqchen 
This seems a bit confusing, is there a simple example of using aug_seq? I want to use like"random crop - > resize", this resize method stretches the image to a square.

**Comment by thomelane** [comment]
Hi @TccccD,

I've just replied to a similar post [here](https://github.com/apache/incubator-mxnet/issues/12671) which hopefully clarifies things a little more.

Aside from implementing your own augmenter and using in `aug_seq`, you should take a look at [Gluon's Transforms](https://mxnet.incubator.apache.org/api/python/gluon/data.html#vision-transforms). You can [`Compose`](https://mxnet.incubator.apache.org/api/python/gluon/data.html#mxnet.gluon.data.vision.transforms.Compose) augmentations in the order you need.
