### ISSUE TITLE
compile problem in Jetson TX1

### ISSUE THREAD

**Issue by ShawnXuan** [dmlc/mxnet#1916]
When I use "make -j4" in Jetson TX1, first error is:
"g++: error: unrecognized command line option ‘-msse3’"
then I remove flag "-msse3" in "mshadow.mk", and repeat "make -j4",
the new error is:
"fatal error: emmintrin.h: No such file or directory"

I'm new to Ubuntu, g++, makefile... just follow some instructions from google.
Pease help, thanks!

**Comment by tqchen** [comment]
We need to disable SSE in mshadow add -DMSHADOW_USE_SSE=0

**Comment by ShawnXuan** [comment]
Hi, 

Thanks a lot!

this one is fixed by add "ADD_CFLAGS = -DMSHADOW_USE_SSE=0" into "mshadow.mk".
also I remove "-msse2" in "/dmlc-core/Makefile" and add " -DMSHADOW_USE_SSE=0".
but after "make -j4", at last I just got "ar crv lib/libmxnet.a" in the command line, no more promotion.
then I run  "make -j4 -B" to rebuild all. I'm not sure, the installation is good or not.

I tried the train_mnist.py, it worked, but very slow:
2016-04-21 16:04:06,950 Node[0] Epoch[0] Batch [400]	Speed: **12626.68** samples/sec
my laptop can reach 40000 samples/sec with CPU only.

I will keep playing with it.
Thanks!

**Comment by tqchen** [comment]
glad it works for you.Note that MNIST uses cpu by default. We need to check how fast TX1 GPU was.

**Comment by liangfu** [comment]
Note that I have to add 
````
CUDA_NVCC_FLAGS:STRING="-arch=sm_20;-std=c++11;-O2;-DVERBOSE"
````
to `CMakeCache.txt` with latest `dmlc-core` source code update, otherwise the compiler complains about "nullptr" is not defined. See also: http://stackoverflow.com/questions/29121211/cuda-compilation-issue-with-cmake
