### ISSUE TITLE
train on generator

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#1918]
Is there a way to train on a generator which returns a batch of data at a time? I have a dataset of pairs of points, of which the points themselves can fit easily in memory but the pairs will take up a huge amount of space. I know I could subclass the dataiter, but I was wondering if there was a builtin way to do this already.

**Comment by pluskid** [comment]
Yes you can. You can checkout the `__iter__` function in the [bucket-io.py](https://github.com/dmlc/mxnet/blob/master/example/rnn/bucket_io.py#L200) for example, it uses the generator.

**Comment by jmschrei** [comment]
Sure, but this involves overriding the dataiter object, which I already knew I could do, but was too lazy to do myself.

**Comment by pluskid** [comment]
@jmschrei Writing a wrapper that handles an iterator should be quite straightforward. You are very welcome to contribute such a wrapper to the mxnet IO library so that other (lazy) people can also benefit from it. :P

**Comment by jmschrei** [comment]
Contributing to open source projects? Ugh what a burden.

**Comment by tqchen** [comment]
A generator based iterator would be  great to have @jmschrei

**Comment by jmschrei** [comment]
So I have the following rough implementation for training on a generator: 

```Python
class GeneratorIter(DataIter):
        """"comments removed""""

	def __init__(self, generator, data_shapes={}, label_shapes={}, batch_size=1, max_iterations=100):
		# pylint: disable=W0201

		super(GeneratorIter, self).__init__()

		self.generator = generator
		self.data_shapes = data_shapes
		self.label_shapes = label_shapes
		self.batch_size = batch_size
		self.max_iterations = max_iterations
		self.iterations = 0

	@property
	def provide_data(self):
		"""The name and shape of data provided by this iterator"""
		return [(k, tuple([self.batch_size] + list(v))) for k, v in self.data_shapes.items()]

	@property
	def provide_label(self):
		"""The name and shape of label provided by this iterator"""
		return [(k, tuple([self.batch_size] + list(v))) for k, v in self.label_shapes.items()]

	def next(self):
		if self.iterations < self.max_iterations:
			data, label = next(self.generator)

			data = [ array(data[l]) for l in self.data_shapes.keys() ]
			label = [ array(label[l]) for l in self.label_shapes.keys() ]

			return DataBatch(data=data, label=label, pad=0, index=None)
		else:
			raise StopIteration
```

When I run this, it appears to be working until I get to the end of an epoch (with epoch_size=1000 in the model definition), at which it prints out the following:

```
INFO:root:Auto-select kvstore type = local_update_cpu
INFO:root:Start training with [gpu(0), gpu(1), gpu(2), gpu(3)]
INFO:root:Epoch[0] Batch [50]	Speed: 2750.93 samples/sec	Train-roc_auc_score=0.648943
INFO:root:Epoch[0] Batch [100]	Speed: 2740.40 samples/sec	Train-roc_auc_score=0.681282
INFO:root:Epoch[0] Batch [150]	Speed: 2684.58 samples/sec	Train-roc_auc_score=0.696818
INFO:root:Epoch[0] Batch [200]	Speed: 2669.95 samples/sec	Train-roc_auc_score=0.708660
INFO:root:Epoch[0] Batch [250]	Speed: 2668.76 samples/sec	Train-roc_auc_score=0.719490
INFO:root:Epoch[0] Batch [300]	Speed: 2861.38 samples/sec	Train-roc_auc_score=0.728193
INFO:root:Epoch[0] Batch [350]	Speed: 2725.35 samples/sec	Train-roc_auc_score=0.735111
INFO:root:Epoch[0] Batch [400]	Speed: 2727.48 samples/sec	Train-roc_auc_score=0.741463
INFO:root:Epoch[0] Batch [450]	Speed: 2769.91 samples/sec	Train-roc_auc_score=0.746258
INFO:root:Epoch[0] Batch [500]	Speed: 2729.70 samples/sec	Train-roc_auc_score=0.750542
INFO:root:Epoch[0] Batch [550]	Speed: 2752.45 samples/sec	Train-roc_auc_score=0.754559
INFO:root:Epoch[0] Batch [600]	Speed: 2821.23 samples/sec	Train-roc_auc_score=0.757877
INFO:root:Epoch[0] Batch [650]	Speed: 2903.97 samples/sec	Train-roc_auc_score=0.760836
INFO:root:Epoch[0] Batch [700]	Speed: 2738.13 samples/sec	Train-roc_auc_score=0.763201
INFO:root:Epoch[0] Batch [750]	Speed: 2835.84 samples/sec	Train-roc_auc_score=0.765435
INFO:root:Epoch[0] Batch [800]	Speed: 2794.14 samples/sec	Train-roc_auc_score=0.767574
INFO:root:Epoch[0] Batch [850]	Speed: 2835.68 samples/sec	Train-roc_auc_score=0.769683
INFO:root:Epoch[0] Batch [900]	Speed: 2671.31 samples/sec	Train-roc_auc_score=0.771387
INFO:root:Epoch[0] Batch [950]	Speed: 2771.24 samples/sec	Train-roc_auc_score=0.772851
INFO:root:Epoch[0] Batch [1000]	Speed: 2802.95 samples/sec	Train-roc_auc_score=0.774428
INFO:root:Epoch[0] Train-roc_auc_score=0.774428
INFO:root:Epoch[0] Time cost=372.802
INFO:root:Epoch[0] Validation-roc_auc_score=0.744083
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Resetting Data Iterator
...
```

and it doesn't stop printing out that it's resetting the data iterator. Any insight into how to fix this?

**Comment by pluskid** [comment]
Thanks! I believe you need to implement a `reset` function to rewind the iteration to 0 to start another different epoch. Also as I mentioned in a comment above, if you look at bucket-io, you can actually implement your `DataIter` *as a generator*: you can write a for loop with `yield` for example.

**Comment by jmschrei** [comment]
I want the DataIter to hold a generator which will infinitely produce data. I don't want to rewind it back to 0. I mean, as long as the next function produces data and there's a reset function (which my in case doesn't do anything), I don't understand why I'm getting these errors.

**Comment by jmschrei** [comment]
Implementing the DataIter as a generator seemed to work. I guess people will have to pass in the generator function and a dictionary of keywords so that it can be rebuilt each time? That seems very inefficient though, especially if they start the generator by doing some sort of preprocessing.

Basically, what I imagine is that a person will pass in a generator for an unlimited amount of data (say, you have a finite set but it randomly returns batch_size images from it), and then you specify the epoch size using epoch_size. You should only have to set up the generator once, and constantly get data from it, rather than rewind it (which you can't really do for arbitrary generators). Is this possible?

**Comment by piiswrong** [comment]
If you don't want it to stop and reset to beginning, simply remove raise StopIteration

**Comment by pluskid** [comment]
You can set number of epoch to 1 for training. Then the model will not try to rewind the iterator to do another epoch. Assuming you have "infinitely many" (or a very large amount of) data in one epoch, going over one epoch should be enough to train the model well.
