### ISSUE TITLE
Build fail with Mac OS X (Yosemite, gcc 4.9 from homebrew with openMP, open CV, Blas)

### ISSUE THREAD

**Issue by phunterlau** [dmlc/mxnet#192]
After following the build instruction by checking out the latest mxnet recursively, and installing c++, open cv, open blas, make gives this error on `isnan` in the ndarray_function from mshadow (latest mxnet commit 61558808118aa6099065dc494e3afde0125f0ea0 ):

```
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 -fopenmp  -MM -MT build/ndarray/ndarray.o src/ndarray/ndarray.cc >build/ndarray/ndarray.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 -fopenmp  -c src/ndarray/ndarray.cc -o build/ndarray/ndarray.o
In file included from src/ndarray/ndarray.cc:13:0:
src/ndarray/./ndarray_function.h: In static member function 'static mxnet::real_t mxnet::ndarray::Clip::mshadow_op::Map(mxnet::real_t, mxnet::real_t)':
src/ndarray/./ndarray_function.h:43:18: error: 'isnan' was not declared in this scope
       if (isnan(a)) return 0.0f;
                  ^
src/ndarray/./ndarray_function.h:43:18: note: suggested alternative:
In file included from /usr/local/Cellar/gcc49/4.9.3/include/c++/4.9.3/random:38:0,
                 from /usr/local/Cellar/gcc49/4.9.3/include/c++/4.9.3/bits/stl_algo.h:66,
                 from /usr/local/Cellar/gcc49/4.9.3/include/c++/4.9.3/algorithm:62,
                 from ./dmlc-core/include/dmlc/./parameter.h:18,
                 from ./dmlc-core/include/dmlc/registry.h:14,
                 from src/ndarray/ndarray.cc:8:
/usr/local/Cellar/gcc49/4.9.3/include/c++/4.9.3/cmath:632:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
In file included from src/ndarray/ndarray.cc:8:0:
src/ndarray/ndarray.cc: At global scope:
./dmlc-core/include/dmlc/registry.h:194:22: warning: 'mxnet::__make_NDArrayFunctionReg__set_value__' defined but not used [-Wunused-variable]
   static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/mxnet/ndarray.h:580:3: note: in expansion of macro 'DMLC_REGISTRY_REGISTER'
   DMLC_REGISTRY_REGISTER(::mxnet::NDArrayFunctionReg, NDArrayFunctionReg, name)
   ^
src/ndarray/ndarray.cc:508:1: note: in expansion of macro 'MXNET_REGISTER_NDARRAY_FUN'
 MXNET_REGISTER_NDARRAY_FUN(_set_value).set_function(SetValueOp);
 ^
```

Can you suggest some fix so I can test on my mac? Thanks.

**Comment by antinucleon** [comment]
try```std::isnan```?

**Comment by tqchen** [comment]
add using namespace std should work,  @antinucleon  I think we want to remove isnan check

**Comment by tqchen** [comment]
We cannot do ```std::isnan``` because that code is supposed to run on CUDA as well

**Comment by antinucleon** [comment]
k...will remove nan check

**Comment by mli** [comment]
that happens before. Can we auto pick the right isnan based on the device?

**Comment by antinucleon** [comment]
I removed isnan already

**Comment by pluskid** [comment]
Also just a side note for OSX compilation: if we add `-I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/` to `ADD_CFLAGS` then there is no need to install third-party BLAS.

**Comment by tqchen** [comment]
Yes, this is already enabled by setting ```USE_BLAS=apple``` @antinucleon  We should add that in build note for OSX

**Comment by pluskid** [comment]
@tqchen Thanks! Good to know that. I think it is definitely good to have recommended ways of installing the dependency packages on Linux and OS X separately  in the INSTALL document.

**Comment by phunterlau** [comment]
@pluskid After upgrading to El Capitan, this default BLAS from apple has just gone, if you need BLAS, don't upgrade :-) Meanwhile, I am trying to find a way to have BLAS in the new system

**Comment by pluskid** [comment]
@phunterlau I still have them in the original place after upgrading to EI Capitan.

**Comment by mli** [comment]
my suggestion is USE_BLAS=AUTO in default

if osx, then set it to apple, otherwise probably just blas, or auto check what is available.

**Comment by pluskid** [comment]
I second the idea for "auto" BLAS. I saw cmake related stuff in the repo recently. Are we going to switch to cmake soon?

**Comment by tqchen** [comment]
the cmake is already ready to use. I think we will keep both approaches ,
both Makefile and cmake. Cmake is good for windows and being auto in
choosing libs. Except that itself is a dependency.

**Comment by phunterlau** [comment]
fixed my local BLAS installation from upgrading to El Capitan. Compiled and tested OK after fixing nan problem. I am trying to finish the pip installation soon.
