### ISSUE TITLE
Declare shared memory dynamic array inside a kernel when create new operations

### ISSUE THREAD

**Issue by shuangjiexu** [dmlc/mxnet#1922]
Hi all,

I am trying to create a new operation with declaring shared memory using dynamic array.In cuda,I will use this,push the size of the allocation as an argument to the kernel call:
```
__global__  void sgemm(const float *A, const float *B, float *C)
{
   extern __shared__ float As[];
}

size_t blocksize = BLOCK_SIZE * BLOCK_SIZE;
sgemm2<<< gridDim, blockDim, sizeof(float)*blocksize >>>(....);
```
But in Mxnet python,the function Rtc.push : 
```
push(self, inputs, outputs, grid_dims, block_dims)
```
there is no argument about this.How can I declare dynamic array in Mxnet?

Thanks so much for your help!

**Comment by piiswrong** [comment]
Currently the RTC module doesn't support this. You need to modify the code.

**Comment by shuangjiexu** [comment]
I see.Thanks so much for your help.
