### ISSUE TITLE
inconsistent comments in optimizer.py

### ISSUE THREAD

**Issue by yzhang87** [dmlc/mxnet#1931]
Hi, @piiswrong 

After the refactor of optimizer, comments was mismatched with the actual code:

e.g in Adam:
```
464     learning_rate : float, optional
465         Step size.
466         Default value is set to 0.002.
```
but in the actual code, it grab from the base class (learning_rate=0.01) directly. I think it is too huge for some optimizer.

**Comment by piiswrong** [comment]
Thx for pointing out. I'll fix it later.
