### ISSUE TITLE
model-parallel lstm on multi machine

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#1933]
@tqchen 
Is the model parallel lstm compatible with multi-machine case? I didn't find the kvstore setup in the example code, so I guess maybe not?  I see layers are spread to different devices? How is the communication handled between different devices?

I'm facing the same embedding layer problem as #1237 and #1716 , so I'm looking at this model-parallel solution. Or is there any sparse matrix solution for embedding to save backward gradient memory cost? (Maybe we don't need to do this as CUDA is providing page faulting in future wtih  [pascal](https://devblogs.nvidia.com/parallelforall/inside-pascal/)?)

**Comment by tqchen** [comment]
No it is for single machine so far. Usually we want to use data par between machines, as copy state is more costly than copy params. A copy operator is inserted between layers with different devices.

**Comment by Godricly** [comment]
Could it be possible to view this single machine as one device(or more) with full model by adding kvstore? I think it is possible to follow the update_on_kvstore function on manipulating arg_list and grad_list. The list shape will be the same, while the ctxs are disordered.

**Comment by feiyulv** [comment]
Is that possible  to support model par within a machine, and data par across machines?

**Comment by feiyulv** [comment]
@tqchen 
Is that possible to support model par within a machine, and data par across machines?

**Comment by tqchen** [comment]
@feiyulv Yes that is what I mean in my last comment
