### ISSUE TITLE
Get NN architecture from .json

### ISSUE THREAD

**Issue by iluvatar593** [dmlc/mxnet#1936]
Is there any automated way to get the python get_symbol function (i.e. the `symbol_alexnet.py` in the image-classification example folder ) starting from a json file? My question arises since sometimes there are pretrained models that I would like to train with my dataset.

(Maybe was better to put this question in the pull requests?)

**Comment by piiswrong** [comment]
You can load the json to get a symbol, but not code like in get_symbol functions.

**Comment by tqchen** [comment]
http://mxnet.readthedocs.org/en/latest/packages/python/symbol.html#mxnet.symbol.load_json

**Comment by iluvatar593** [comment]
Thank you, so then I can pass it to a fit function to perform the training? I mean something like

```
net = mx.symbol.load_json(path)
model.fit(args, net, iterator)
```

and then pass `net` as the `symbol` parameter in a `mx.model.FeedForward` call?

**Comment by tqchen** [comment]
yes
