### ISSUE TITLE
Undefined reference to `mxnet::op::SimpleOpRegistry::__REGISTER_OR_FIND__(std::string const&)`

### ISSUE THREAD

**Issue by bonsairobo** [dmlc/mxnet#1942]
I am trying to build libmxnet.so on Ubuntu 15.10 using CUDA 7.5 and CUDNN. The full error message is:

build/src/operator/elementwise_unary_op_gpu.o: In function `__static_initialization_and_destruction_0(int, int) [clone .constprop.507]':
/home/duncan/code/mxnet/src/operator/./elementwise_unary_op-inl.h:84: undefined reference to `mxnet::op::SimpleOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
/home/duncan/code/mxnet/src/operator/./elementwise_unary_op-inl.h:89: undefined reference to `mxnet::op::SimpleOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
/home/duncan/code/mxnet/src/operator/./elementwise_unary_op-inl.h:94: undefined reference to `mxnet::op::SimpleOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
/home/duncan/code/mxnet/src/operator/./elementwise_unary_op-inl.h:98: undefined reference to `mxnet::op::SimpleOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
/home/duncan/code/mxnet/src/operator/./elementwise_unary_op-inl.h:102: undefined reference to `mxnet::op::SimpleOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
build/src/operator/elementwise_unary_op_gpu.o:/home/duncan/code/mxnet/src/operator/./elementwise_unary_op-inl.h:106: more undefined references to `mxnet::op::SimpleOpRegistry::__REGISTER_OR_FIND__(std::string const&)' follow
collect2: error: ld returned 1 exit status
Makefile:203: recipe for target 'bin/im2rec' failed

I have tried compiling with gcc-4.9 and gcc-4.8 by making symbolic links /usr/local/cuda/bin/{gcc,g++}, both with the same issue.

Any help?

**Comment by piiswrong** [comment]
git pull && git submodule update && make clean && make

**Comment by bonsairobo** [comment]
Thanks for the quick response! Just tried that command and I get the same error. I don't think the `git pull && git submodule update` changed anything.

**Comment by piiswrong** [comment]
Try a fresh clone with git clone https://github.com/dmlc/mxnet.git --recursive

**Comment by piiswrong** [comment]
> I have tried compiling with gcc-4.9 and gcc-4.8 by making symbolic links /usr/local/cuda/bin/{gcc,g++}, both with the same issue.

This isn't the right way to setup gcc version. Your compiler and linker might have different version

**Comment by bonsairobo** [comment]
Is there a recommended way for setting the default GCC version of NVCC?

**Comment by bonsairobo** [comment]
Using clang fixed it.

**Comment by Xiaoming-Zhao** [comment]
Hi, I met a similar problem here. My OS is Ubuntu 15.10 x86_64. My gcc is 4.9.3. My CUDA is 7.5.17, my OpenCV is 2.4.9. If I `make -j4` with "OpenCV=0" everything goes well. However, if I `make -j4` with "OpenCV=1", I met a error ```
Makefile:203: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1
``` I search for google for several days but no answer solve this problem. Could anyone help me? thanks!
