### ISSUE TITLE
Cannot reclaim GPU memory using garbage collector in Python or Julia

### ISSUE THREAD

**Issue by bonsairobo** [dmlc/mxnet#1946]
I have a straightforward test for this in Julia:

    using MXNet

    x = mx.zeros((100,100), mx.gpu())
    # see output from `nvidia-smi`

    x = 0
    gc()
    # see that output from `nvidia-smi` has not changed

The python equivalent behaves the same for me. Is there any way to reclaim unused GPU memory using the interfaces for these languages? I can only free the memory when the Julia/Python process exits.

**Comment by tqchen** [comment]
The memory goes back to mxnet's internal memory pool, which will be reused for new arrays. But they are not freed to cuda runtime because cuda's runtime was slow
