### ISSUE TITLE
memory is exploded when using varient size images.

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#1952]
```python
def create():
......
    hw = np.random.randint(500, 1000, (2,))
    my_exec = halfFCN_net.simple_bind(ctx=mx.gpu(0),
                                       data=(1, 1, hw[0], hw[1]), 
                                        grad_req='null')
......
```
and do
```python
    for i in xrange(1000)
         my_exec = create()
         my_exec.forward()
```
the memory of gpu will explode.
it will ok when the image size of ```hw``` retains same.

**Comment by starimpact** [comment]
@tqchen @piiswrong

**Comment by sxjscience** [comment]
Is it caused by the fact that the executors haven't been deleted? (Multiple executors may maintain different temporary space?)

**Comment by starimpact** [comment]
the executors should have been deleted automatically.

**Comment by piiswrong** [comment]
you didn't wait for the forward to finish. thus there will be 1000 execs running in parallel

**Comment by starimpact** [comment]
how to wait for the forward to finish?

**Comment by tqchen** [comment]
was due to the exact match memory pooling strategy used in mxnet so far. @hotpxl @jermainewang We might want to have a function to manually release all paged memory.

https://github.com/dmlc/mxnet/issues/1176 also offers a solution

**Comment by starimpact** [comment]
I still don't know how to solve.
I just want A solution to let mxnet support variant sized images.
I remember @piiswrong said he has solved the problem.

**Comment by starimpact** [comment]
@piiswrong ```my_exec.outputs[0].wait_to_read()``` cannot solve it.

**Comment by tqchen** [comment]
if you use reshape of executor directly, it is likely they will share memory.

**Comment by starimpact** [comment]
I just want variant sized input. Sharing memory is OK.

**Comment by starimpact** [comment]
@tqchen there is no ```reshape``` method in executor. so where can i do it?

**Comment by tqchen** [comment]
https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor.py#L242

**Comment by starimpact** [comment]
is there any example of how to use it?

**Comment by starimpact** [comment]
I looked into the reshape of executor, and found that, it handles the variant size problem by reallocating memory for nd array. Are you sure it can solve the problem like this?
