### ISSUE TITLE
Bug in the GPU Embedding Layer

### ISSUE THREAD

**Issue by sbodenstein** [dmlc/mxnet#1955]
The derivative of the embedding layer is broken on GPU's. For example, the Embedding layer UnitTest:

```
def test_embedding():
    ctx = mx.Context(mx.cpu)
    in_dim = 10
    out_dim = 4
    batch = 24
    
    data = mx.sym.Variable("data")
    embed = mx.sym.Embedding(data=data, input_dim=in_dim, output_dim=out_dim, name="embed")
    exe_test = embed.simple_bind(ctx, grad_req={'data': 'null', 'embed_weight': 'write'}, data=(batch,))
    arg_map = dict(zip(embed.list_arguments(), exe_test.arg_arrays))
    grad_map = dict(zip(embed.list_arguments(), exe_test.grad_arrays))
    np_data = np.random.randint(low=0, high=in_dim, size=batch)
    np_weight = np.random.uniform(-0.01, 0.01, arg_map["embed_weight"].shape)
    np_onehot = np.zeros((batch, in_dim))
    np_onehot[np.arange(batch), np_data] = 1.0
    # forward
    arg_map["data"][:] = np_data
    arg_map["embed_weight"][:] = np_weight
    exe_test.forward()
    assert reldiff(exe_test.outputs[0].asnumpy(), np.dot(np_onehot, np_weight)) < 1e-6
    # backward
    np_grad = np.random.uniform(-1, 1, exe_test.outputs[0].shape)
    grad = mx.nd.zeros(np_grad.shape, ctx)
    grad[:] = np_grad
    exe_test.backward([grad])
    print grad_map["embed_weight"].asnumpy()
    assert reldiff(grad_map["embed_weight"].asnumpy(), np.dot(np_onehot.T, np_grad)) < 1e-6
```

runs correctly for `ctx = mx.Context(mx.cpu)` but not `ctx = mx.Context(mx.gpu)`.

The issue seems to be a bug in the CUDA version of `AddTakeGrad`. Looking at the implementation, there seems to be a simple mistake in mshadow/cuda/tensor_gpu-inl.cuh: `dim3 dimGrid(dst.size(1) >> kUnitBits);` should be `dim3 dimGrid(dst.size(1) << kUnitBits);`

**Comment by sbodenstein** [comment]
Also out of curiosity: there is no flag in your test suite to run your unit tests on GPU. Was this a conscious choice?

**Comment by tqchen** [comment]
cc @antinucleon

**Comment by tqchen** [comment]
need to change the line to 
```c++
 dim3 dimGrid((dst.size(1) + (1<<kUintBits)-1) >> kUnitBits);
```

**Comment by tqchen** [comment]
@sbodenstein thanks for reporting this, you mind to open a PR to fix this?

Most of testcase was written for travis test thus not considered gpu when we wrote them. But I do agree that expose a flag to be able to test on gpu is much a better choice

**Comment by sbodenstein** [comment]
Sure, will do.
