### ISSUE TITLE
why i need cuda.h?

### ISSUE THREAD

**Issue by pzz2011** [dmlc/mxnet#1958]
This version is named win64_cpu_only. Why I need the cuda.h header file when i build the app MXnetTestApp in this pre-built version. 

I am confused...
hope to receive your answer.

zhenzhong

**Comment by mli** [comment]
@hjk41

**Comment by hjk41** [comment]
@pzz2011 which binary release are you using? I think the latest releases don't include the test app. We have moved to MxNet.cpp for the cpp examples.

Regarding to the header file problem, remember to select x64 as the platform. We didn't set the compiler flags in x86 mode, so it lacks flags like DMLC_USE_CUDA, which would lead to the error.

**Comment by pzz2011** [comment]
windows binary build 20160113 in the pre-build list.
And
you are right, I setted the platform win32 only =_= @hjk41
