### ISSUE TITLE
implement a locally-connect layer? 

### ISSUE THREAD

**Issue by Yunrui** [dmlc/mxnet#1962]
Hi folks, 

My training data is hosted in a cvs file, which has 400 columns. And I want to have a network, in which the first hidden layer is locally-connected. Means, separating 400 columns into 4 groups equally, and then each group in the input layer fully connected to a group of neurons in the first hidden layer (also has 4 group respectively). 

I did not find any example of this kind of local-connected network in mxnet. Could you please shed some light?

**Comment by rldotai** [comment]
This sounds like a composite/graph architecture, if I understand correctly.
Does your desired network look something like this?

```
group1 ---> layer1 -----\
group2 ---> layer2 -----|
                                   | -----> rest of network
group3 ---> layer3 -----|
group4 ---> layer4 -----/
```

If so, [the documentation provided here](https://github.com/dmlc/mxnet/blob/f317c960be2282b0bf7c217fc5163b4211df76ff/docs/packages/python/symbol_in_pictures.md) might be a good starting point, or see [this for an example of more general graph-like architecture](https://github.com/dmlc/mxnet/blob/5ff545f2345f9b607b81546a168665bd63d02d9f/example/notebooks/composite_symbol.ipynb)

You will probably have to split your data into separate iterators as well, or [use something like SliceChannel](https://mxnet-bing.readthedocs.org/en/latest/python/symbol.html#mxnet.symbol.SliceChannel).

**Comment by piiswrong** [comment]
SliceChannel will work for this

**Comment by Yunrui** [comment]
Thanks all, SliceChannel is what I want.
