### ISSUE TITLE
Compile failed on latest version

### ISSUE THREAD

**Issue by wangxianliang** [dmlc/mxnet#1966]
ubuntu 14.04 LTS

src/operator/./broadcast_reduce_op-inl.h:71:60: error: 'broadcast_scalar' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
                       broadcast_scalar(mscale, igrad.shape_));

Any idea? Thanks a lot.

**Comment by Jerrylu5683** [comment]
I get the same compile error. I don't know how it occurs. Did you solve this problem?

**Comment by Jerrylu5683** [comment]
I solved this problem. It is a project dependency problem. Same as #1870 .
I just re-download the project with commond: git clone --recursive https://github.com/dmlc/mxnet.
Copy the old config.mk to new diretory and recomplile it.

**Comment by pluskid** [comment]
`git submodule update --recursive` will also do the thing.
