### ISSUE TITLE
will there be a windows version

### ISSUE THREAD

**Issue by caffeTao** [dmlc/mxnet#198]
i wonder wether you will release the project file for windows or wether cxxnet project file can do this.

**Comment by tqchen** [comment]
Yes, actually @happynear  already created on on his fork. We are looking into using CMake solution so the dependency is more maintainable

**Comment by happynear** [comment]
@caffeTao You may checkout this repo https://github.com/happynear/mxnet before CMake script is written done.

**Comment by erfannoury** [comment]
Great to see that mxnet is coming to Windows, too. I can help with the testing.

**Comment by tqchen** [comment]
I think we are already windows compatible as  #254 

Hopefully we can get the instructions here #250

**Comment by tqchen** [comment]
I am going to close this question, let us move further discussion to #250

**Comment by xylcbd** [comment]
@happynear https://github.com/happynear/mxnet  , does this repo work now ?

**Comment by antinucleon** [comment]
You can either use happynear's or use master repo. Master repo can be
configured by CMake

**Comment by xylcbd** [comment]
@antinucleon thanks ! I'll try this master branch.
