### ISSUE TITLE
How to debug into the MXRTC generated code.

### ISSUE THREAD

**Issue by jonbakerfish** [dmlc/mxnet#1980]
I follow the [Python/NDArray(MXRtc)](http://mxnet.readthedocs.io/en/latest/how_to/new_op.html#python-ndarray-mxrtc) and create a custom layer. However, during model training. I get the following error:
```
INFO:root:Start training with [gpu(0)]
[18:47:22] src/common/mxrtc.cc:69: Check failed: (cuerr = cudaStreamSynchronize(rctx.get_stream<mshadow::gpu>()->stream_)) == (cudaSuccess) CudaError: 77
Aborted (core dumped)
```

How can I debug into the MXRTC generated code using the gdb/cuda-gdb?

**Comment by tqchen** [comment]
you can hook python into gdb, I am not very sure about cuda-gdb though
