### ISSUE TITLE
cifar10_mirror memory example consumption increased after mirroring

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#1981]
Hi, I tested the cifar10_mirror.py example. But I found my memory consumption is doubled while I am able to run memonger examples correctly.  By using environment variable, the consumption  get even larger.
@pluskid

**Comment by Godricly** [comment]
I think the GPU callback result is not accurate. I'll do some experiments tomorrow. btw, can I call the get_cost function in memonger to give an estimation?

**Comment by Godricly** [comment]
Here is some result we got in the experiment.

1. For the cifar10 example, the GPU memory is not released after model.fit finishing because of python gc system. The example memory is increased as the 2nd and 3rd fiting run. Calling del model in train_model.py is not working for me.

2. we apply memonger get_cost to estimate the size. The net_mirror without environment(CASE2)  needs large memory than without mirror case (CASE1). While the net_mirror with environment setup (CASE3) needs less than CASE1. 

3. we further modified the symbol_inception_bn.py for image net following cifar10 example. the get_cost result shares same pattern in cifar10, i.e. memory consumption: CASE2> CASE1> CASE3

4. we apply memonger on imagenet following resnet example in memonger, we get CASE1> CASE2> CASE3. We reduced about half the memory needed according to the get_cost result.

**Comment by pluskid** [comment]
@Godricly Yes, it is very tricky to get the memory cost from external world. First of all, the function I called in that example is a very inaccurate total estimation of all memory on all GPU cards. Then there are several layer of things going on. For example, Python GC (though it is ref-counter based, so should be relative immediate), and MXNet has internal memory pool that tries to minimize calling to CUDA allocation API by retaining some memory and re-using them.

I think maybe the best way to test the memory usage (in case the result from `get_cost` should be verified empirically) is simply try to add up layers and see how deep you can go before your program crashes with out-of-memory error.

**Comment by Godricly** [comment]
I tried running one fit at one time for all cases. And the nvidia-smi displayed CASE2> CASE1> CASE3 result. Also memonger behaves different from mxnet its own mirror setup. Adding up layers is frustrating, we always want an estimation of network so we can do sth.

**Comment by tqchen** [comment]
closing for now
