### ISSUE TITLE
NativeOp doesn't support `AddTo` for output

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#1983]
I meet this problem when I try to implement a variant of RNN whose loss is given by a NumpyOp. Would anyone give me some guidance on how to solve this problem? @piiswrong @tqchen @pluskid 

https://github.com/dmlc/mxnet/blob/master/src/operator/native_op-inl.h#L62
https://github.com/dmlc/mxnet/blob/master/src/operator/native_op-inl.h#L96

**Comment by sxjscience** [comment]
Currently I need to disable the AddTo optimizer.

**Comment by tqchen** [comment]
@piiswrong is it possible for us to make a quick fix on this?

**Comment by piiswrong** [comment]
The custom op already support this

**Comment by sxjscience** [comment]
@piiswrong That's great! I'll try the custom op. Could I directly transfer the current NumpyOp to CustomOp?

**Comment by piiswrong** [comment]
You just need to split forward/backward into a new class

**Comment by tqchen** [comment]
closing for now if CustomOp already solved the problem
