### ISSUE TITLE
cudnn pooling sum not implemented

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#1984]
for this code
`mx.symbol.Pooling(data=tanh1, pool_type="sum",`
the following error...
`[11:44:24] C:\Users\chuaf\Downloads\mxnet\dmlc-core\include\dmlc/logging.h:235: [11:44:24] c:\users\chuaf\downloads\mxnet\src\operator\./cudnn_pooling-inl.h:32: Not implmented`

**Comment by Godricly** [comment]
cudnn has no sum pooling.
