### ISSUE TITLE
no CUDA-capable device is detected in windows

### ISSUE THREAD

**Issue by abalfazl** [dmlc/mxnet#1987]
hi.
i download "**windows binary build 20160419 - gpu version**" and install **python package** it.
but it gives an error when ] use the gpu:
MXNetError: [11:52:59] D:\chhong\mxnet\src\storage\storage.cc:42: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: no CUDA-capable device is detected

**I use the cuda 7.5.18 and my gpu is GT 550M too**.

thanks

**Comment by Godricly** [comment]
maybe check your cuda using devicequery first?

**Comment by piiswrong** [comment]
gt 550 sounds too old
