### ISSUE TITLE
Example on plain csv data

### ISSUE THREAD

**Issue by rz1988** [dmlc/mxnet#1990]
Hi, 

I am new to mxnet ( and python too) but have experience in mlp in R in the past. Browsing the examples I find many of them are to classify an image. Can any one point to me a quick example on how to use mxnet to run a regression/classification on plain csv kind data? 

I installed mxnet on a windows box with CUDA/cnDNN enabled.

Many thanks,
Ryan

**Comment by piiswrong** [comment]
See the kaggle examples

**Comment by rz1988** [comment]
Thanks. Can you point to me a specific example?

**Comment by rldotai** [comment]
[See here](https://github.com/dmlc/mxnet/tree/master/example/kaggle-ndsb2), particularly `Train.py` or `Train.R`. 

For future reference, it was also the first result in Google when searching for "mxnet kaggle", usually you only need a few keywords to get the right results.
Alternatively, you could bank on the fact that Python's module for dealing with CSV files is `csv`, so searching the repository for `csv` while restricting the search to files in the Python language would've also exposed some good candidates for further investigation.

**Comment by rz1988** [comment]
Thanks I will take a look at it.
