### ISSUE TITLE
Error: Train MLP with NDArrays 

### ISSUE THREAD

**Issue by rz1988** [dmlc/mxnet#1991]
Hi,

I am trying to run the code on the tutorial MXNet Python Model API. Since the data_set in the sample code was not given, I created my artificial data set using mx.NDArray. However, I run to this error. Any thoughts?

The code:

import mxnet as mx
data_set = mx.random.normal(0, 1, (10, 5))
label = mx.nd.ones((10, 10))
# configure a two layer neuralnetwork
data = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data, name='fc1', num_hidden=128)
act1 = mx.symbol.Activation(fc1, name='relu1', act_type='relu')
fc2 = mx.symbol.FullyConnected(act1, name='fc2', num_hidden=64)
softmax = mx.symbol.SoftmaxOutput(fc2, name='sm')
# create a model using sklearn-style two step way
model = mx.model.FeedForward(
     softmax,
     num_epoch= 10,
     learning_rate=0.01)
model.fit(X=data_set, y=label)

Error:
import mxnet as mx
data_set = mx.random.normal(0, 1, (10, 5))
label = mx.nd.ones((10, 1))
# configure a two layer neuralnetwork
data = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data, name='fc1', num_hidden=128)
act1 = mx.symbol.Activation(fc1, name='relu1', act_type='relu')
fc2 = mx.symbol.FullyConnected(act1, name='fc2', num_hidden=64)
softmax = mx.symbol.SoftmaxOutput(fc2, name='sm')
# create a model using sklearn-style two step way
model = mx.model.FeedForward(
     softmax,
     num_epoch= 10,
     learning_rate=0.01)
model.fit(X=data_set, y=label)

So it seems to relate to the label, which is a NDArray instance. I change it to numpy instance. But got this error.

model.fit(X=data_set, y=label.asnumpy())

MXNetError: [16:31:58] src/symbol/symbol.cc:121: Symbol.InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]sm_label

**Comment by piiswrong** [comment]
You need to create iterators from the arrays with mx.io.NDArrayIter

**Comment by rz1988** [comment]
Thank you @piiswrong . So I changed my code to load the data using the mx.io.NDArrayIter. But I got a new error with regarding the shape of the label.

Code:
import mxnet as mx 
data_set = mx.random.normal(0, 1, (10, 5))
label = mx.nd.ones((10, 2))
train_iter = mx.io.NDArrayIter(data_set, label, batch_size = 1)

data = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data, name='fc1', num_hidden=128)
act1 = mx.symbol.Activation(fc1, name='relu1', act_type='relu')
fc2 = mx.symbol.FullyConnected(act1, name='fc2', num_hidden=64)
softmax = mx.symbol.SoftmaxOutput(fc2, name='softmax')

model = mx.model.FeedForward(
softmax,
num_epoch= 10,
learning_rate=0.01)

model.fit(X = train_iter)

Error:

MXNetError: InferShape Error in softmax's label argument
Corresponding keyword of symbol: softmax_label
Shape inconsistent, Provided =(1,2), inferred shape=(1,)

**Comment by tqchen** [comment]
SoftmaxOutput takes label index, so if you set batch_size equals 1, you should provide labels in shape (1,), as in the error message
