### ISSUE TITLE
Example on Logistic Regression or Linear Regression output?

### ISSUE THREAD

**Issue by rz1988** [dmlc/mxnet#1992]
As the title states, is there any logistic regression or linear regression MLP examples? I tried to search within the repository and have no luck. Many thanks.

**Comment by antinucleon** [comment]
Multi-logistic regression: https://github.com/dmlc/mxnet/tree/master/example/kaggle-ndsb2
Multi-linear regression: http://blog.kaggle.com/2016/04/28/yelp-restaurant-photo-classification-winners-interview-1st-place-dmitrii-tsybulevskii/

**Comment by rz1988** [comment]
Many thanks @antinucleon . I will take a look at both examples.
