### ISSUE TITLE
How do I reproduce imagenet training results ?

### ISSUE THREAD

**Issue by gosha1128** [dmlc/mxnet#1993]
Hi,

The imagenet training performance looks impressive.  I have a multi- GPU system, I have downloaded imagenet, and I have mxnet installed with GPU support.

I see there is a train_imagenet.py script.  Do I just use the "data-dir" command line switch and the path to the imagenet directory as is ?  Or, do i also need to also create a recordio file ?  Thanks !

**Comment by piiswrong** [comment]
you need to create recordio with im2rec.py
