### ISSUE TITLE
请问R中的CHAR_LSTM报错如何处理？

### ISSUE THREAD

**Issue by wyjzz** [dmlc/mxnet#1996]
Error in setup.rnn.model(ctx = mx.cpu(), num.lstm.layer = num.lstm.layer,  : 
  could not find function "mx.exec.update.grad.arrays"

**Comment by thirdwing** [comment]
Please give more info, including which OS you are using, which version of mxnet you are using, you are using the precompiled or you compile by yourself.

Thanks.

**Comment by lothc** [comment]
Hello,

I am having the same issue. OS: Win8, mxnet ver 0.5, using the precompiled version installed from CRAN. It looks the cran repo does not include the latest update on the R package.

Thank you for your help!

**Comment by thirdwing** [comment]
Yes, the Windows pre-built version is a little old. I don't have a Windows machine by hand.

I will update it soon.

**Comment by thirdwing** [comment]
I have just uploaded a new version to drat repo.

Please try again.

**Comment by lothc** [comment]
Thank you very much, it works now (with R version 3.3).
