### ISSUE TITLE
Source Code for mxnet.symbol.SoftmaxOutput function

### ISSUE THREAD

**Issue by rz1988** [dmlc/mxnet#1998]
Hi,

This might be a dumb question but I am wondering where I can find the source code for the SoftmaxOuptut function. I used inspect.getsourcelines(mx.symbol.SoftmaxOutput) but it pointed to me to a creator function. 

Thanks,
Ryan

**Comment by piiswrong** [comment]
src/operator/softmax_output-inl.h
