### ISSUE TITLE
Inferred label shape of SoftmaxOutput function

### ISSUE THREAD

**Issue by rz1988** [dmlc/mxnet#1999]
There seems to be a bug in the SoftmaxOuput function. No matter how many neurons I select in the last layer, the output shape is always (num of rows, ).

### The code:

input_shape = (10, 5)
label_dim = 2

data_set = mx.random.normal(0, 1, input_shape)
label = mx.nd.ones((input_shape[0], label_dim))
train_iter = mx.io.NDArrayIter(data_set, label, batch_size = 1)

val_training = mx.random.normal(0, 1, input_shape)
val_label = mx.nd.ones((input_shape[0], label_dim))
val_iter = mx.io.NDArrayIter(val_training, val_label, batch_size = 1)

data = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data, name='fc1', num_hidden=128)
act1 = mx.symbol.Activation(fc1, name='relu1', act_type='relu')
fc2 = mx.symbol.FullyConnected(act1, name='fc2', num_hidden= label_dim)
softmax = mx.symbol.SoftmaxOutput(fc2, name='softmax')

arg_shape, out_shape, aux_shape = softmax.infer_shape(data = (10, 6))

dict(zip(softmax.list_arguments(), arg_shape))

out_shape

### Code Output:

In [421]: dict(zip(softmax.list_arguments(), arg_shape))
Out[421]:
{'data': (10L, 6L),
 'fc1_bias': (128L,),
 'fc1_weight': (128L, 6L),
 'fc2_bias': (2L,),
 'fc2_weight': (2L, 128L),
 'softmax_label': (10L,)}

In [422]:

In [422]: out_shape
Out[422]: [(10L, 2L)]

**Comment by piiswrong** [comment]
label contains integer class indicators. So it's always (batch_size,)

**Comment by rz1988** [comment]
Thanks @piiswrong . But when I change the output layer to other functions, for example, linear output, why is the label shape (batch_size, num of last layer's hidden units) ?

Code:
softmax = mx.symbol.LogisticRegressionOutput(fc2, name = 'softmax')

arg_shape, out_shape, aux_shape = softmax.infer_shape(data = (10, 6))

dict(zip(softmax.list_arguments(), arg_shape))

out_shape

Output:
{'bn1_beta': (100L,),
 'bn1_gamma': (100L,),
 'data': (10L, 6L),
 'fc1_bias': (100L,),
 'fc1_weight': (100L, 6L),
 'fc2_bias': (100L,),
 'fc2_weight': (100L, 100L),
 'softmax_label': (10L, 100L)}

In [46]:

In [46]: out_shape
Out[46]: [(10L, 100L)]

**Comment by tqchen** [comment]
It is different definition of the output objective. 
For logistic regression, it is per element loss, so label shape equals the output shape. 
For softmax, the label gives the index of the class, so it is always batch_size
