### ISSUE TITLE
LogisticRegression operator is not right implemented in theoretically.

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#2001]
I think your LogisticRegression operator is not right.
the right one should be:
```python
cost = -(y*log(P)+(1-y)*log(1-P))
```
and ```P``` is from the pre layer's sigmoid output.
but yours is just like a ```||sigmoid(pre_out)-y||```. It is a strange linear regression.

**Comment by tqchen** [comment]
It is correct. If you directly take differentiation with loss you pointed our, you will need to also multiply  by factor ```sigmoid(pred_out) (1-sigmoid(pred_out)) ```

**Comment by starimpact** [comment]
oh,  the ```sigmoid(pred_out)``` and ```1-sigmoid(pred_out)``` can be eliminated separately.
