### ISSUE TITLE
Mxnet can only do classified job?

### ISSUE THREAD

**Issue by joyivan** [dmlc/mxnet#2007]
I have read the Doc. and example in web,I think this model  can only do some classified job,eg. cifar,mnist, but I want to some function fitting job,like this  :  x=[1,2,3,4,5,6,.....]  y_prediction[3,6,4,6,6]  ,Did anyone like the job using Mxnet ?  Sorry about my poor English.! :)

**Comment by antinucleon** [comment]
MXNet supports classification, regression, multi-in, multi-out problems. I am sorry I don't know what is your problem exactly.

**Comment by joyivan** [comment]
@antinucleon thank for your reply,I need multi-in multi-out method,which example I can follow?
