### ISSUE TITLE
Error occurs when create ndarray on GPU

### ISSUE THREAD

**Issue by zhuangbohan** [dmlc/mxnet#2008]
When I run the command c = mx.nd.empty((2, 3), mx.gpu(1)), it works well. 
But when I run b = mx.nd.zeros((2, 3), mx.gpu(1)), error occurs:

"/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.pyc in zeros(shape, ctx, dtype)
    676     """
    677     arr = empty(shape, ctx, dtype)
--> 678     arr[:] = 0.0
    679     return arr
    680 

/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.pyc in __setitem__(self, in_slice, value)
    201                 value.copyto(self)
    202         elif isinstance(value, numeric_types):
--> 203             NDArray._set_value(float(value), out=self)
    204         elif isinstance(value, (np.ndarray, np.generic)):
    205             self._sync_copyfrom(value)

/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.pyc in generic_ndarray_function(*args, **kwargs)
   1117                 ctypes.c_int(len(kwargs)), \
   1118                 c_array(ctypes.c_char_p, kwargs.keys()), \
-> 1119                 c_array(ctypes.c_char_p, [str(i) for i in kwargs.values()])))
   1120         if n_mutate_vars == 1:
   1121             return mutate_vars[0]

/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 def c_str(string):

MXNetError: [14:27:07] src/ndarray/ndarray.cc:173: GPU is not enabled
"
I don't know what's the problem....So SOS!!!

**Comment by piiswrong** [comment]
turn on CUDA in config.mk. The installation guide discribes how

**Comment by zhuangbohan** [comment]
My config.mk is like this:
#---------------------
# choice of compiler
#--------------------

export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS = -L/opt/openblas/lib -lopenblas

# the additional compile flags you want to add
ADD_CFLAGS = -I/opt/openblas/include

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = /usr/local/cuda-7.5

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = openblas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 1

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =


#----------------------------
# plugins
#----------------------------

# whether to use torch integration. This requires installing torch.
# TORCH_PATH = $(HOME)/torch
# MXNET_PLUGINS += plugin/torch/torch.mk

# whether to use sframe integration. This requires build sframe
# git@github.com:dato-code/SFrame.git
# SFRAME_PATH = $(HOME)/SFrame
# MXNET_PLUGINS += plugin/sframe/plugin.mk

I have turned on CUDA and passed the compilation, but it still doesn't work....

**Comment by zhuangbohan** [comment]
I have set USE_CUDA=1 in config.mk and passed the compilation, but it still doesn't work...
