### ISSUE TITLE
Getting Started example(MNIST) does not work

### ISSUE THREAD

**Issue by wdx04** [dmlc/mxnet#2010]
This is a documentation issue.
[http://mxnet.readthedocs.io/en/latest/get_started/index.html]

In the Python example, the line
``
mlp  = mx.symbol.SoftmaxOutput(data = fc3)
``
should be changed into
``
mlp=mx.symbol.SoftmaxOutput(data=fc3, name='softmax')
``
Otherwise, the following error occurs when fitting the model:
MXNetError: [15:51:57] D:\chhong\mxnet\src\symbol\symbol.cc:121: Symbol.InferSha
peKeyword argument name softmax_label not found.
Candidate arguments:
        [0]data
        [1]fullyconnected0_weight
        [2]fullyconnected0_bias
        [3]fullyconnected1_weight
        [4]fullyconnected1_bias
        [5]fullyconnected2_weight
        [6]fullyconnected2_bias
        [7]softmaxoutput0_label

Other language versions probably have the same problem.
I'm using the 20160419 binary release on Windows.
Thanks.

**Comment by tqchen** [comment]
You are Thanks for reporting this. It is now fixed
