### ISSUE TITLE
how to set the top_k accuracy when training or testing?

### ISSUE THREAD

**Issue by frank2wang87** [dmlc/mxnet#2019]
I can find the TopKAccuracy function in python/mxnet/metric.py from Line 144 to Line 155. The code is listed as following. 
class TopKAccuracy(EvalMetric):
    """Calculate top k predictions accuracy"""

    def __init__(self, **kwargs):
        super(TopKAccuracy, self).__init__('top_k_accuracy')
        try:
            self.top_k = kwargs['top_k']
        except KeyError:
            self.top_k = 1
        assert(self.top_k > 1), 'Please use Accuracy if top_k is no more than 1'
        self.name += '_%d' % self.top_k

But to a specialized training or testing, how should I set the top_k accuracy? For example, if I want to test the top_2 accuracy in the mnist example(example/image-classification/train_mnist.py), what should I do ?

**Comment by piiswrong** [comment]
at train_model.py: 84
```
for top_k in [5, 10, 20]:
        eval_metrics.append(mx.metric.create('top_k_accuracy', top_k = top_k))
```
replace [5, 10, 20] with the ks you want
