### ISSUE TITLE
Do the two arguments (num_parts and part_index) of DataIter have impact on the performance of distributed training?

### ISSUE THREAD

**Issue by tjuzhao111** [dmlc/mxnet#2021]
I noticed that the MNISTIter and ImageRecordIter have these two arguments. I wonder if they influence the data loading in distributed training on multiple machines. 

However, the NDArrayIter doesn't have these two arguments. Is there any problem if I use NDArrayIter directly for data loading in distributed training on multiple machines?

**Comment by piiswrong** [comment]
Recordio iters like mnist and imagerecorditer use these to determine which partition of the data to use
NDArrayIter doesn't do partition automatically. You need to write you own code for it.

**Comment by tqchen** [comment]
If you use NDArrayIter, you need to make sure you load the corresponding data shard properly
