### ISSUE TITLE
Incorrect SoftmaxActivation Derivative

### ISSUE THREAD

**Issue by sbodenstein** [dmlc/mxnet#2028]
The new CPU version of the SoftmaxActivation calculates the derivative incorrectly: 
```
m_out_grad * m_out_data * (1.0f - m_out_data)
``` 
This formula is wrong (it simply gives the diagonal terms of the input gradient matrix). You can also verify that the CPU derivative now differs from the GPU version (which uses the cuDNN implementation). 

I have a non-MShadow CPU implementation of the gradient, but it requires temporary memory to be assigned. Should I submit a PR, or do you want to fix this in some other way?

**Comment by piiswrong** [comment]
@antinucleon

**Comment by antinucleon** [comment]
@piiswrong The machine I am using doesn't have CuDNN. Seems I made a mistake. Let me see whether we can fix by using mshadow, otherwise we need both CPU and GPU code for non-mshadow version.

**Comment by piiswrong** [comment]
The correct formula is d/dy_i y_i - \sum_j d/dy_j y_i y_j.
So we can do it with mshadow like this:
```m_out_data*(m_out_grad- broad_cast(reduce<sum>(m_out_grad*m_out_data)))```

**Comment by piiswrong** [comment]
actually, the current broadcast op will cause the reduce to be computed N times...

**Comment by antinucleon** [comment]
We can use tmp resource to calculate reduce first.

**Comment by piiswrong** [comment]
do we have to? The cudnn version doesn't seem to need that

**Comment by piiswrong** [comment]
@sbodenstein Could you PR your code?

**Comment by sbodenstein** [comment]
Sure. Should it use MShadow + a temporary, or should it use a C + CUDA + temporary? (is there any advantage to the latter?)

**Comment by piiswrong** [comment]
If your code already works with mxnet you can submit it as is first and we can figure out how to proceed

**Comment by sbodenstein** [comment]
Ok, I'll do this later today.
