### ISSUE TITLE
为什么我用480*480的灰度图片做train，预测时候data_shape写data_shape = (1, 480,480)总报错，而写data_shape = (1, 256, 256) 才能运行 

### ISSUE THREAD

**Issue by ruobo** [dmlc/mxnet#2031]
import find_mxnet  
import mxnet as mx  
import logging  
import argparse  
import os, sys  
import train_model  
import numpy as np  
import scipy.io as sio    

prefix = 'model/480-inv3'
iteration = 10  
model_load = mx.model.FeedForward.load(prefix, iteration)  
data_shape = (1, 256, 256) 
val = mx.io.ImageRecordIter(  

        path_imgrec = "5.4-480-image/validate.rec",
        mean_img    = "5.4-480-image/validate.bin",

        rand_crop   = False,  
        rand_mirror = False,  
        data_shape  = data_shape,  
        batch_size  = 1)  
  
[prob, data1, label1] = model_load.predict(val, return_data=True)

代码如上，非常奇怪的问题。
总报这个错：/mxnet/mshadow/mshadow/././expr_engine-inl.h:367: Check failed: (shape1) == (shape2) BinaryMapExp: Shapes of operands are not the same

**Comment by antinucleon** [comment]
Seems you are loading a pre-trained model. For pretrained model, the shape info is in the symbol. If you like to finetune, you need to create model by using symbol, then initialize with ```Load``` initializer.

**Comment by ruobo** [comment]
@antinucleon thank you very much. but I'm sorry I'm still not clear, I pretrained model using Inception-v3 symbol, I copyed from symbol_inception-v3.py file, how to adjust? can you give me some examples?

**Comment by Ldpe2G** [comment]
@ruobo you can refer to the neural-style examples to see how to init the network with pretrained-model
and different input size.
https://github.com/dmlc/mxnet/blob/master/example/neural-style/model_vgg19.py
