### ISSUE TITLE
obtain pointer to raw data of a NDArray

### ISSUE THREAD

**Issue by amithr1** [dmlc/mxnet#2033]
Hi All,

How do I obtain pointer to the raw data of a NDArray.  I check that it is contiguous by doing *.data().CheckContiguous() and I try to get it by data().dptr_. But, when I try to print the internal values returned by this pointer, I get all zeroes

**Comment by piiswrong** [comment]
Is your array on cpu or gpu? You cannot directly access gpu memory

**Comment by amithr1** [comment]
Its in the CPU..

**Comment by amithr1** [comment]
I do float* A = buf.data().dptr_ and then tried to access A[0] ..but I always get 0 though it was a ndarray of ones.

**Comment by piiswrong** [comment]
you need to call buf.wait_to_read()

**Comment by tqchen** [comment]
Usually you want to use SyncCopyToCPU instead. Note that NDArray represents an asynchronize computation object, whose content may not be available then

**Comment by Line290** [comment]
Hi amithr1,

Do you know how I can get the pointer as your mentioned in Python code, just like the numpy array ctypes.data.
[numpy.ndarray.ctypes](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ctypes.html)

**Comment by khaotik** [comment]
@Line290 I've figured out a [hacky way](https://stackoverflow.com/questions/53987847/avoid-copying-during-array-conversion-between-numpy-and-mxnet/53989546#53989546) to obtain pointer. Allowing sharing CPU `NDArray` with numpy without copying.
