### ISSUE TITLE
Question regarding runtime comparism.

### ISSUE THREAD

**Issue by ThomasHooser** [dmlc/mxnet#205]
Great work with your package guys!

I have a small question regarding your runtime comparism on Cifar 10:

cxxnet	362 img/sec	675 img/sec	1282 img/sec
mxnet	467 img/sec	923 img/sec	1820 img/sec
mxnet + cudnn v3	842 img/sec	1640 img/sec	2943 img/sec

where does the great speedup over cxxnet come from? From what I understood from your tutorial, if memory is no concern, cxxnet should be able to matchup speedwise with mxnet.

**Comment by antinucleon** [comment]
Sorry what is your question?

**Comment by ThomasHooser** [comment]
Sry, postet accidently too early, my question is edited in my first post.

**Comment by antinucleon** [comment]
Mainly, it comes from：

1. Symbolic computing graph makes aggressive inplace optimization possible, and reduces extra copy,eg we don't need explicit ```split``` layer anymore.
2. Resource manager  make it possible to allocate more temp memory to each conv layer.

**Comment by ThomasHooser** [comment]
Thank you!
