### ISSUE TITLE
softmax_cross_entropy

### ISSUE THREAD

**Issue by lightingghost** [dmlc/mxnet#2050]
Hi,

I have a problem when using `mx.sym.softmax_cross_entropy`. It gives an error of 

`mxnet.base.MXNetError: [00:18:36] src/symbol/graph_executor.cc:920: Check failed: (info.ref_count) == (0) Because the last operator is not Loss function, head_gradient is required in calling backward.
`

When I use `mx.sym.SoftmaxOutput`, everything was fine. But when I change 

`sm = mx.sym.SoftmaxOutput(data=pred, label=label, name='softmax')`

to 

`sm = mx.sym.softmax_cross_entropy(lhs=pred, rhs=label, name='softmax')
`
it gives the error above

Thanks

**Comment by tqchen** [comment]
softmax_cross_entropy outputs the entropy values, you will need to backprop a head_gradient value. Alternatively, you can stack it with a http://mxnet.readthedocs.io/en/latest/packages/python/symbol.html#mxnet.symbol.MakeLoss operator

**Comment by tqchen** [comment]
Note that since softmax_cross_entropy outputs the loss values, it might not be compatible with the evaluation metrics provided. In normal cases softmaxOutput is better
