### ISSUE TITLE
A few broken links on developer guide in documentation

### ISSUE THREAD

**Issue by precedenceguo** [dmlc/mxnet#2061]
The link to developer guide - operators in [how to create new operator](http://mxnet.readthedocs.io/en/latest/how_to/new_op.html) is down. The operator documentation is [here](http://mxnet.readthedocs.io/en/latest/system/operator.html).
The link to doxygen api in [system design](http://mxnet.readthedocs.io/en/latest/system/index.html#list-of-other-resources) is down. Actually where is doxygen documentation?
The API reference part of [execution engine](http://mxnet.readthedocs.io/en/latest/system/engine.html) is down. Also related to doxygen.
I am also interested in expanding the C++ operator developing guide to the new unified API defined in `operator_utils.h`. Any other resources to look at?

**Comment by tqchen** [comment]
Thanks for bring this up. These should be fixed by https://github.com/dmlc/mxnet/pull/2065

You are more than welcomed to add guide of newly added operator_util.h I can help review and answer any of your questions. Thanks!

**Comment by precedenceguo** [comment]
Please see pr #2136 for the new doc.
