### ISSUE TITLE
Building fail on mac 10.10, "dynamic module does not define init function"

### ISSUE THREAD

**Issue by toothacher17** [dmlc/mxnet#207]
hi all,

I tried to install on my mac 10.10 to first run a demo on small datasets. I deleted the -fopenmp as suggested in XGBoost. I got the libmxnet.so and libmxnet.a in the lib/ folder. But I still failed to run the example/mnist.py as suggested by the tutorial. It reported "dynamic module does not define init function". What should I do next to solve this problem? Do you guys have a tutorial for installing on mac? Thanks a lot

**Comment by mli** [comment]
mxnet works fine on my mbp with max os x 10.10. could you please double check your python version? this error is often due to inconsistent of python version (installed mxnet by one python, while run it by another python)

**Comment by toothacher17** [comment]
Thanks a lot, my python version was 2.7.10 but my g++ version was 4.7. Sorry about that I should check the g++ version before I asked. I change g++ to 4.8 and python to 3.5 and It works now. Really thanks a lot.
