### ISSUE TITLE
Mac OS make failure with set USE_OPENMP = 0

### ISSUE THREAD

**Issue by stupid-coder** [dmlc/mxnet#2078]
# problem
mxnet compile failure with instruction in http://mxnet.readthedocs.io/en/latest//how_to/build.html
the error is dmlc-core make failure of USE_OPENMP in osx.mk seem useless in dmlc-core.

make error:

> cd /Users/stupid-coder/Documents/Codes/DMLC/mxnet/dmlc-core; make libdmlc.a
config=/Users/stupid-coder/Documents/Codes/DMLC/mxnet/config.mk; cd /Users/stupid-coder/Documents/Codes/DMLC/mxnet
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o line_split.o src/io/line_split.cc
clang: error: unsupported option '-fopenmp'
make[1]: *** [line_split.o] Error 1

# solved

change mxnet/Makefile(17-25):
```
ifneq ($(USE_OPENMP), 1)
        export NO_OPENMP = 1
endif

# use customized config file
include $(config)
include mshadow/make/mshadow.mk
include $(DMLC_CORE)/make/dmlc.mk
unexport NO_OPENMP
```

to 
```
include $(config)

ifneq ($(USE_OPENMP), 1)
        export NO_OPENMP = 1
endif

# use customized config file
include mshadow/make/mshadow.mk
include $(DMLC_CORE)/make/dmlc.mk
# unexport NO_OPENMP
```

mv `inlcude $(config)` before `export NO_OPENMP=1`, make sure the USE_OPENMP=0 before the `ifneq` and comment the `unexport NO_OPENMP`

**Comment by szad670401** [comment]
i got same problem but it doesn't work even changed the makefile

**Comment by qiaohaijun** [comment]
I counter the same problem, I will try your solution

**Comment by stupid-coder** [comment]
The Sample Wap:

> export NO_OPENMP=1 

> #unexport NO_OPENMP

before run the `make`

**Comment by sxjscience** [comment]
The compilation problem should be solved by https://github.com/dmlc/mxnet/pull/2407
