### ISSUE TITLE
problem to install of mxnet package in R v.3.3.0

### ISSUE THREAD

**Issue by RogerBorras** [dmlc/mxnet#2079]
I have a problem to install mxnet package in R v.3.3.0 on windows 10.  When I follow the steps I have this warning:

Warning in install.packages :
  cannot open URL 'http://dmlc.github.io/drat/bin/windows/contrib/3.3/PACKAGES.gz': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'http://dmlc.github.io/drat/bin/windows/contrib/3.3/PACKAGES': HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://dmlc.github.io/drat/bin/windows/contrib/3.3:
  cannot open URL 'http://dmlc.github.io/drat/bin/windows/contrib/3.3/PACKAGES'

**Comment by thirdwing** [comment]
Oh, sorry for this. There is no package for R 3.3.0 right now. I will update soon.

**Comment by RogerBorras** [comment]
Great, thanks!!! :)

**Comment by thirdwing** [comment]
I have just uploaded a new version to drat repo.

Please try again.
