### ISSUE TITLE
[help] mx.symbol.ElementWiseSum

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#2081]
I look for the doc and search the net, but I dont find the correct way of using this symbol, can anyone give a tip?

**Comment by antinucleon** [comment]
Here is an example for element wise op:
https://github.com/dmlc/mxnet/blob/master/example/kaggle-ndsb2/Train.py#L22

On Mon, May 9, 2016 at 8:15 AM qiao hai-jun <notifications@github.com>
wrote:

> I look for the doc and search the net, but I dont find the correct way of
> using this symbol, can anyone give a tip?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2081>
>
-- 
Sent from mobile phone

**Comment by qiaohaijun** [comment]
thx
