### ISSUE TITLE
Convert googlenet from caffe to mxnet 

### ISSUE THREAD

**Issue by carlosb1** [dmlc/mxnet#2095]
I am trying to test the performance of  the same neural network among different frameworks.. I downloaded the googlenet in order to do it... I tried to use the mxnet script (tools/caffe_converter/convert_model.py) to export this caffe network, but it is giving an error and I don't exactly how I could fix it...
  

```
 wmat = np.array(layer_blobs[0].data).reshape(layer_blobs[0].num, layer_blobs[0].channels, layer_blobs[0].height, layer_blobs[0].width)
ValueError: total size of new array must be unchanged
```

layer_blogs seems that it is empty, I don't know exactly how I should repair it...

The problem happens with its first layer: (name : conv1_7x7_s2 type:Convolution)

**Comment by EasonD3** [comment]
Haven't encountered before. Not sure if it's related to #1553

**Comment by carlosb1** [comment]
I was debugging my code, the problem are in the layer_blobs parameters (num, channels, height and width). The deserialization didn't work correctly, The parameters are set 0...

**Comment by carlosb1** [comment]
I had misconfigured the pycaffe module, it is not a related problem with mxnet... I updated the numpy package and set the PYTHONPATH correctly for caffe...
