### ISSUE TITLE
Bug in c_api.h

### ISSUE THREAD

**Issue by sbodenstein** [dmlc/mxnet#2097]
In the function `MXExecutorBindEX` in `c_api.h`, there seems to be a mistake: `ExecutorHandle *shared_exec` should be `ExecutorHandle shared_exec`. It can also be seen in in they Python API in `symbol.py` that the handle `shared_handle` is not being passed in by reference.

Can I fix this, or is it as designed?

**Comment by piiswrong** [comment]
good catch. You are welcome to submit a pr

**Comment by sbodenstein** [comment]
Will do.

**Comment by pluskid** [comment]
Wonder what was the effect on bucketing?

**Comment by piiswrong** [comment]
This actually does have any effect

**Comment by tqchen** [comment]
there is no effect because the pointer is cased anyway (change from ```void* to void **```) But nevertheless we should fix it
