### ISSUE TITLE
mxnet imagenet filelist

### ISSUE THREAD

**Issue by linnanwang** [dmlc/mxnet#2101]
Hello,

Is there a provided ilsvrc12 filelist in mxnet so that we can quickly create imagenet data source? Thank you.

One more question, mxnet is able to train using asyn SGD. Is this correct? Many thanks.

**Comment by piiswrong** [comment]
use tools/make_list.py to make a list

**Comment by linnanwang** [comment]
Thanks, but is mxnet able to use multiple GPUs to async update network parameters?

**Comment by antinucleon** [comment]
MXNet is able to use multiple GPUs, multiple GPUs on many machines in both
sync and async way. Please check our document for detail usage.


On Tue, May 10, 2016 at 10:40 PM linnan wang <notifications@github.com>
wrote:

> Thanks, but is mxnet able to use multiple GPUs to async update network
> parameters?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2101#issuecomment-218366819>
>
-- 
Sent from mobile phone

**Comment by linnanwang** [comment]
Could you please point me to the right documentation using ASGD to train on multiGPUs on 1 machine? Thank you.

I'm asking because I'm not sure if asyn updates also function on the single node.  Thanks.

**Comment by tqchen** [comment]
on single machine, only sync SGD is supported. Note that it is now understood that sync SGD is always better than ASGD.

**Comment by linnanwang** [comment]
Thanks for clarifying this point. It saves me a lot of time.
