### ISSUE TITLE
Low running speed when run with kv-store

### ISSUE THREAD

**Issue by tjuzhao111** [dmlc/mxnet#2102]
Hi, I used a simple 2 layers MLP, the input feature vector has 20 dimensionalities. 
First, I use a NDArrayIterator for data loading. I found that when I ran it with kv-store, the running speed declines heavily. I have thought the problem was the dataloading. 
So I rewrite my input data into a binary file with a mnist format. I write a new iterator similar to the MNISTIterator by c++ and rebuild the mxnet. However the performance was still poor on kv-store.
Then I followed the suggestion by tqchen, replace the iterator with a DummyIter, while nothing changes. It seems that the kv-store is the problem rather than data loading.
Do you have any suggestions or solutions?

**Comment by Godricly** [comment]
try larger net

**Comment by tqchen** [comment]
there is no guanrantee that multiple GPU will help, especially in small nets, where the communication cost overwhelms the computation.

**Comment by pluskid** [comment]
I think we should put this in some kind of FAQ, as it is being asked too many times.
