### ISSUE TITLE
How to save a symbol with custom layer/operator?

### ISSUE THREAD

**Issue by JeffDong** [dmlc/mxnet#2103]
I use the symbol mlp in [this example](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/numpy_softmax.py), so the operator code is correct.
If I run `mlp.save('mlp.json')`, and run `mx.symbol.load('mlp.json')` in the same kernel, it works fine.
But if I first save it and start a new kernel to run
`mx.symbol.load('mlp.json')`
the kernel will die immediately, which is corresponding to a segmentation fault in terminal.
What's the problem here? Should I use something else to save custom operator?

**Comment by vchuravy** [comment]
#2051 introduces a custom operator that can be saved and loaded.

**Comment by JeffDong** [comment]
@vchuravy Thank you. The new CustomOp is exactly what I want.
