### ISSUE TITLE
Any Roadmap available?

### ISSUE THREAD

**Issue by tmatas** [dmlc/mxnet#2119]
Hello everybody,
as I understand Mxnet is moving faster, but I am not able to understand what are the main feature that the near future will bring.

Is there any roadmap available?

Many thanks for your work,
T.

**Comment by tqchen** [comment]
check the issues under https://github.com/dmlc/mxnet/milestones/v0.7.1 and https://github.com/dmlc/mxnet/labels/Roadmap
