### ISSUE TITLE
Amalgamation module does not compile

### ISSUE THREAD

**Issue by carlosb1** [dmlc/mxnet#2120]
I downloaded mxnet:
`git clone --recursive  https://github.com/dmlc/mxnet.git
`
I compiled all the package how it is explained (make -j4) and I tried to compile the amalgamation module (following README)  to use the python binding... but it is not working..:

```
g++ -std=c++11 -Wno-unknown-pragmas -Wall -I`pwd`/OpenBLAS -MD -MF mxnet_predict0.d \
	-I /home/carlos/javascript-workspace/test-mxnet/mxnet/ -I /home/carlos/javascript-workspace/test-mxnet/mxnet/mshadow/ -I /home/carlos/javascript-workspace/test-mxnet/mxnet/dmlc-core/include \
	-I /home/carlos/javascript-workspace/test-mxnet/mxnet/include -c mxnet_predict0.cc
mxnet_predict0.cc:20:41: fatal error: src/ndarray/unary_function.cc: No such file or directory
 #include "src/ndarray/unary_function.cc"

```

**Comment by tqchen** [comment]
@antinucleon We might need to update amalgamation includes to reflect latest changes in the code

**Comment by antinucleon** [comment]
OK. Will check it

**Comment by carlosb1** [comment]
Do you know which previous tagged versions compile in? I tried with a tagged version (20160202)  and It had compilation errors.

**Comment by antinucleon** [comment]
Compiling is fixed in https://github.com/dmlc/mxnet/pull/2135
