### ISSUE TITLE
Problems about image classification using MXNet

### ISSUE THREAD

**Issue by Xiaoming-Zhao** [dmlc/mxnet#2123]
Hi, I met a problem when using MXNet to train models for image classification. There are some characteristics about company's image dataset, namely one image has several tag. However, the number of tags are not identical, for example, image A has tag a, b, c and image B has tag b, d. 

I think I should treat this as a single tag task. My question is whether I should copy image A and B for  three times and twice respectively?  Or it is OK for me to just use **the same image path** in **ImageRecord**?

Thanks a lot !

**Comment by EasonD3** [comment]
You may consider your problem as a multi-label one and prepare the training data by following #1404

**Comment by Xiaoming-Zhao** [comment]
@EasonD3  
Hi, thanks a lot for your kind reply. However, I think multi-label option in MXNet is made for fixed number of labels for the example [here](http://mxnet.readthedocs.io/en/latest/packages/python/io.html#parameters-for-data-iterator):  

`integer_image_index \t label_1 \t label_2 \t label_3 \t label_4 \t path_to_image`

However, my problem here is that the number of tags for each image is not the same.

**Comment by EasonD3** [comment]
@Xiaoming-Zhao you can simply use a lengthy binary vector to represent the labels/tags of each image. In this case, the label vector of each image will be of size 4. As a result, A's label will be [1, 1, 1, 0], and B's [0, 1, 0, 1].

**Comment by Xiaoming-Zhao** [comment]
@EasonD3 
Hi, thaks a lot for the advice. It sounds like a really great idea. I will try it.
Thank you agian!
