### ISSUE TITLE
How to combine multiple data iters into one?

### ISSUE THREAD

**Issue by EasonD3** [dmlc/mxnet#2126]
I've been digging for the solution for quite a while. I came across these related issues #617 and #1269. However, there was no conclusion made or at least no clear solution.

Can someone please conclude if it is possible to combine multiple data iters into one, say two `ImageRecordIter`s? And what if the types of the data iters are different, e.g., a `ImageRecordIter` and a `MNISTIter`?

The combination of multiple data iters will be very helpful to implement siamese-network-like structures.

Thanks.

**Comment by piiswrong** [comment]
you can write a simple dataiter to wrap around the two

**Comment by tornadomeet** [comment]
currently, ImageRecordIter only support one input dataiter, so you should write your own dataiter and put the data in one list, you'd better do it in the python side for simple.

**Comment by EasonD3** [comment]
Thank you for the replies. I ended up using a customized `PrefetchingIter` for my use case.
