### ISSUE TITLE
Fail to run custom op example in python3

### ISSUE THREAD

**Issue by JeffDong** [dmlc/mxnet#2130]
I found two problems when trying to run the [custom op](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/custom_softmax.py) example code in python3.

1. There are multiple `xrange` in operator.py which is not defined in python3. Changing them all to `range` fixes this.

2. The assert `assert op_type == reg_name` in line 567 of operator.py will fail. When reg_name is 'softmax', op_type is a byte string b'softmax'. Changing this line to `assert op_type.decode('utf-8') == reg_name` works for me.

I'm not sure if this is the best way to fix these so I just report here.

**Comment by piiswrong** [comment]
Thanks for reporting. I didn't test for python3 compatibility. Could you open a PR with your fixes?

**Comment by tqchen** [comment]
@piiswrong We need to change and fix this, better add a testcase for python3 compatiblity. To get the results from ctypes, also use ```py_str``` function

**Comment by antinucleon** [comment]
@piiswrong I suggest we use Python3 as default. Python2 is too old and Python3 will become majority soon.

**Comment by JeffDong** [comment]
@piiswrong Sure. See #2143
