### ISSUE TITLE
Error : Expecting a four-dimensional array

### ISSUE THREAD

**Issue by khudebhakti** [dmlc/mxnet#2131]
When I try to run the Shiny app, I get this error
Error:Expecting a four-dimensional array
![issue](https://cloud.githubusercontent.com/assets/8778134/15243027/ec97547e-1916-11e6-8fd0-860d1a7bda86.jpg)

**Comment by hoaphumanoid** [comment]
This is related to #2150

**Comment by hoaphumanoid** [comment]
You just need to install imager version 0.20 (version 0.14 does not work with Inception code)

```bash
wget https://cran.r-project.org/src/contrib/imager_0.20.tar.gz
R CMD INSTALL image_0.20.tar.gz
```

**Comment by thirdwing** [comment]
@khudebhakti I think I have fixed the `imager`-related code, but please wait for the new inception-bn model.

**Comment by thirdwing** [comment]
This has been fixed already. Feel free to reopen it.
