### ISSUE TITLE
module 'mxnet.symbol' has no attribute 'sum'

### ISSUE THREAD

**Issue by lasandcris** [dmlc/mxnet#2137]
Hi all,

it might be an easy fix. i'm trying to run the neural-style example but getting the above error right after parsing the input images on the run.py at line 118. I did a dir(mx.sym) and indeed, sum is not listed as a attribute. Is this a typo in the code?

thanks,
Laszlo

edit_1:
had to change line 118 and 120 from:
mx.sym.sum
to:
mx.sym.numpy.sum

not sure of the consequences of this yet.  

edit_2:
not sure if this problem is relating to the above (that's why I didn't open a new issue). But I'm now getting a 'Shapes of operands are not the same' error. check failed: shape1 == shape2. And as a result python crashes.

**Comment by piiswrong** [comment]
You need to pull the most recent code

**Comment by lasandcris** [comment]
I pulled it about 6 hours ago. Was there any change since? I'll pull again to try. thanks

**Comment by fredove** [comment]
I am facing the same problem. Does anyone have solutions right now? 
Thank you very much!!!

**Comment by piiswrong** [comment]
pull the most recent code and compile

**Comment by lasandcris** [comment]
It was my mistake, I mixed up between versions. I by the way used the windows prebuilt libs but mixed up the sources and that was the problem. its all working as it should. thanks

**Comment by lasandcris** [comment]
I'm closing this as its resolved.

**Comment by yech1990** [comment]
@piiswrong 
it doesn't work!

**Comment by yech1990** [comment]
@piiswrong  
After recompiling, the error still exist.
```python
Traceback (most recent call last):
  File "run.py", line 166, in <module>
    style_loss, content_loss = get_loss(gram, content)
  File "run.py", line 118, in get_loss
    gram_loss.append(mx.sym.sum(mx.sym.square(gvar - gram[i])))
AttributeError: 'module' object has no attribute 'sum
```

I search the source code, but can't find any lines that define the class `symbol.sum`

**Comment by lasandcris** [comment]
@yech1990 
just pulled the repo, and did a clean compile in linux, run the neural example and I can confirm that there is no problems with it. I think you have different libs mixed up like i did before. Try to remove all your mxnet and recompile.

**Comment by yech1990** [comment]
@lasandcris 
I did that, but still failed.

Do you change the model with GPU? The GPU is disabled in my script.

**Comment by lasandcris** [comment]
@yech1990 
yes, I did:
python run.py --gpu -1

this executes the processing on the cpu - and sets all the other variables to default.
