### ISSUE TITLE
I am confused about 'SHUFFLE' in mxnet.io.ImageRecordIter

### ISSUE THREAD

**Issue by AlecWong** [dmlc/mxnet#2142]
Since my input .rec is not shuffled... So, I set:
def get_iterator(args, kv): 
    data_shape = (1, 64, 64)
    train = mx.io.ImageRecordIter(
        path_imgrec = args.data_dir + "train.rec",
        mean_img    = args.data_dir + "mean.bin",
	data_shape  = data_shape,
        batch_size  = args.batch_size,
	shuffle	    = True,
        rand_crop   = True,
        rand_mirror = False,
        num_parts   = kv.num_workers,
        part_index  = kv.rank)

Is this shuffle all the data set? or only batch by batch?

**Comment by dsqx71** [comment]
mx.io.ImageRecordIter shuffle data by chunks

**Comment by tqchen** [comment]
@dsqx71 answers the question precisely

**Comment by knwng** [comment]
@dsqx71 @tqchen Hello, I'm new to mxnet and I find out the shuffle options both in mx.io.ImageRecordIter and im2rec.py are chunk-wise(please correct me if I'm wrong), which makes shuffling inadequate. 
Currently I'm shuffling the data list manually before create Record but it's kind of annoying. Is there any way to shuffle within the whole dataset using mxnet API? Thank you in advance!

**Comment by guker** [comment]
> mx.io.ImageRecordIter shuffle data within chunks

prefect

**Comment by guker** [comment]
> mx.io.ImageRecordIter shuffle data within chunks
what is chunk？ is it prefetched data？
