### ISSUE TITLE
Building Shiny app error

### ISSUE THREAD

**Issue by tomtran90** [dmlc/mxnet#2150]
When I run this code, I got the error "Expecting a four-dimensional array"

> shiny::runGitHub("thirdwing/mxnet_shiny")

Downloading https://github.com/thirdwing/mxnet_shiny/archive/master.tar.gz

Listening on http://127.0.0.1:6690
trying URL 'http://webdocs.cs.ualberta.ca/~bx3/data/Inception.zip'
Content type 'application/zip' length 42488449 bytes (40.5 MB)
downloaded 40.5 MB

[18:49:08] d:\chhong\mxnet\src\operator\./softmax_output-inl.h:225: Softmax symbol is renamed to SoftmaxOutput. This API will be deprecated in Dec, 2015
**Warning: Error in eval: Expecting a four-dimensional array**
Stack trace (innermost first):
    75: <Anonymous>
    74: stop
    73: resize
    72: preproc.image [C:\Users\thanh\AppData\Local\Temp\RtmpQjGnme\shinyapp12f0429a6d0d\mxnet_shiny-master/server.R#30]
    71: renderText [C:\Users\thanh\AppData\Local\Temp\RtmpQjGnme\shinyapp12f0429a6d0d\mxnet_shiny-master/server.R#102]
    70: func
    69: output$res
     3: runApp
     2: runUrl
     1: shiny::runGitHub

**Comment by tomtran90** [comment]
It can be traced back to these line:

> model = mx.model.load("Inception/Inception_BN", iteration=39)
[18:29:50] d:\chhong\mxnet\src\operator\./softmax_output-inl.h:225: Softmax symbol is renamed to SoftmaxOutput. This API will be deprecated in Dec, 2015

 > normed <- preproc.image(im, mean.img)
  Error: Expecting a four-dimensional array

**Comment by thirdwing** [comment]
This is due to `imager`. It changes some APIs we use.
