### ISSUE TITLE
any bucketing tutorial update?

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#2153]
Hi All,
  Is there any updated [tutorial](http://mxnet.readthedocs.io/en/latest/how_to/bucketing.html) on bucketing? By Browsing the example folder, I noticed  that bucket_io.py is added, while the link is still pointing to the old removed file. @pluskid

**Comment by pluskid** [comment]
Bucket io is still very specific to each particular user application or task. That file could be used as an reference or example when writing your own io. Yes, I think at least some links in the old tutorial should be updated.
