### ISSUE TITLE
How to use Image to predict coordinate?

### ISSUE THREAD

**Issue by haria** [dmlc/mxnet#2154]
Hi All,

I have a dataset saved images and its coordinate.  like below.

00001.jpg, (0.0, 0.0)
00002.jpg, (0.0, 0.1)
00003.jpg, (1.0, 0.0)

you can treat image as a screen capture from football game, and the coordinate is the position player will move to.

my task is given a test image, network output a coordinate.
the image is a 120x120 RGB channel image.
the valid range of coordinate x and y is a float number from 0.0 to 1.0.

It might be a regression problem, I would like to know how can I realize it by using MXNET.

Thank you!

**Comment by zhangchen-qinyinghua** [comment]
This looks to me a region detection problem task.
As the RCNN suggests, 
maybe you should divide the picture into regions, with the center of each region the coordinate you want, use CNN to extract the features, and use some other classifier, such as SVM, to find the wanted region.

**Comment by haria** [comment]
Hi @zhangchen-qinyinghua 

The coordinate is not extract from image but captured from controller such as XBOX controller or PS4 dualshock.

I found solution already. Linear Regression accept N-dim input and 2-dim output, anyway, thank you all the same!

**Comment by humpyreddy96** [comment]
Hi Hariag, I have a similar problem I’m trying to solve. Is there anyway we could connect???
