### ISSUE TITLE
a error! Mxnet will crash!

### ISSUE THREAD

**Issue by dushoufu** [dmlc/mxnet#2157]
[15:43:22] /homedsf/mxnet/mxnet20160407/dmlc-core/include/dmlc/logging.h:245: [15:43:22] /homedsf/mxnet/mxnet20160407/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR
terminate called after throwing an instance of 'dmlc::Error'
  what():  [15:43:22] /homedsf/mxnet/mxnet20160407/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR

**Comment by piiswrong** [comment]
It's very hard for people to help you without knowing what you did and where the crash happened.
If possible, always post a minimal script that reproduce your error

**Comment by dushoufu** [comment]
Now,I just ignore it,because if i open a new terminal it will be OK.

**Comment by ptsinganos** [comment]
Did you solve this issue? I have the same problem as well.
