### ISSUE TITLE
realtive change returns 0.00 using GPU on neural-style example

### ISSUE THREAD

**Issue by lasandcris** [dmlc/mxnet#2168]
I noticed this problem that when running the neural-style example, on gpu (gtx 760), the relative change returns 0.00 at epoch 0, right after loading the default images and variables, and stops. Running the same defaults on the cpu, works. This is running on windows. Has anyone come across with this before?

edit:
just checked this using a titan x in the same env, and has returned the same problem.

thanks
laszlo

**Comment by piiswrong** [comment]
@hjk41 There seems to be problems with running on windows under specific version

**Comment by lasandcris** [comment]
Thanks, I re-built it for win7, and it works as it should.
