### ISSUE TITLE
How to construct a special CNN used in the area of person re-identification?

### ISSUE THREAD

**Issue by dingningbuaa** [dmlc/mxnet#2173]
I'm trying to construct a CNN using MXNet, but the structure is a little strange like the picture below:
![image](https://cloud.githubusercontent.com/assets/10806428/15347896/43e4dc12-1cf8-11e6-8903-d92eabc65f8b.png)
There are two input pictures and each goes through two convolution layers and two pooling layers. Then the two flow will be combined into one and the computation process following the paper:
![image](https://cloud.githubusercontent.com/assets/10806428/15347999/47e29754-1cf9-11e6-8fd8-0a0158874419.png)
![image](https://cloud.githubusercontent.com/assets/10806428/15348003/5b40912a-1cf9-11e6-9daf-84d2ef12cd96.png)
I looked through the document and cannot find a solution. 
My problems are mainly two respects:
a. do I need to write the operators by myself? and how?
b. if so, what is the best way to construct the data as the input?. Cause the picture in the dataset I use only has a label telling which person it belongs to, but the CNN I hope to construct should give an output that indicates whether two input pictures belongs to the same person.

**Comment by tmatas** [comment]
Hi,
a) I'm quite sure the answer is yes, you need to write the operator by yourself. [Here](http://mxnet-tqchen.readthedocs.io/en/latest/how_to/new_op.html) you can find how to write a new layer.
b)Seems like your problem is the dataset. In the same paper there are some references to Re-ID Databases, like CUHK03, CUHK01, VIPeR

Hope it helps.
Cheers!

**Comment by clcarwin** [comment]
a) You can try to use mx. symbol.Concat mx.symbol.maximum + - * / and [other symbol](http://mxnet.readthedocs.io/en/latest/packages/python/symbol.html), to implement "cross-input neighborhood difference". If it is impossible, you have to write the operator.

b) You can combine the pair of two image to one 120x160 image. If the two image is same person set the train label to 1, else set train label to 0. Then use mx.symbol.SliceChannel to slice 120x160 image to two 60x160 data, at the begin of the network.

**Comment by dingningbuaa** [comment]
Thank you guys!!! I will try to make the operator by myself and construct the dataset used for this issue. Sorry for the late reaction because of  the tough busy time recently. I really appreciate your answers!
