### ISSUE TITLE
One-hot input to embedding layer of lstm

### ISSUE THREAD

**Issue by xlvector** [dmlc/mxnet#2176]
In example/rnn/lstm.py, there is following code:

`
embed = mx.sym.Embedding(data=data, input_dim=input_size,
                             weight=embed_weight, output_dim=num_embed, name='embed')
`

From document, it says embedding receive one-hot vector. But from bucket_io.py, I does not see one-hot encode for input data. I just see input data is generate from following code:

`
def default_text2id(sentence, the_vocab):
    words = sentence.split(' ')
    words = [the_vocab[w] for w in words if len(w) > 0]
    return words
`

So, where is code about one-hot encode of input data.

**Comment by Jerrylu5683** [comment]
This question has an answer in issue #892 .
The input data is not a standard one-hot vector, but a vector(or matrix) contains vocabulary index.
I quaoted from @pluskid "Say if you have an input of shape (10, 20), each element is the index of the word in the vocabulary. Then the output will be of shape (10, 20, D) where D is the embedding dimension."

**Comment by xlvector** [comment]
Where is the code doing such transform. I does not find code in embedding-inl.h

**Comment by tqchen** [comment]
there is not an explicit transform, instead it runs a sparse matrix multiplication implicitly

**Comment by xlvector** [comment]
@tqchen  this sparse matrix multiplication is done by GPU or CPU?

**Comment by tqchen** [comment]
This is done on the GPU side by a cuda kernel

**Comment by xlvector** [comment]
Thanks. Seems this is better than tensorflow.

tf always use following code to do embeding:

with tf.device("/cpu:0"):
      embedding = tf.get_variable("embedding", [vocab_size, size])
      inputs = tf.nn.embedding_lookup(embedding, self._input_data)
