### ISSUE TITLE
Amalgamation without BLAS

### ISSUE THREAD

**Issue by SlipknotTN** [dmlc/mxnet#2178]
I have a problem completing the amalgamation process without BLAS (make MIN=1).
My target is to compile an updated mxnet javascript version.

I manage to complete amalgamation from mxnet.js github version, but not from more recent versions.

In particular i can obtain the js files, but I get this runtime error:

> Check failed: eshape[0] == 0 || eshape == dshape Assignment: Shape of Tensors are not consistent with target

I get the same runtime error on Android compiling without BLAS (make ANDROID=1 MIN=1), so I think it's a problem related to BLAS absence.

For example, if I print the tensor shapes this is the results:

Correct version (with BLAS):

> 1)
Eshape 0 147
Eshape 1 12321
Dshape 0 147
Dshape 1 12321
2)
Eshape 0 1
Eshape 1 96
Eshape 2 111
Eshape 3 111
Dshape 0 1
Dshape 1 96
Dshape 2 111
Dshape 3 111
3)
...

Without BLAS:

> 1)
Eshape 0 147
Eshape 1 12321
Dshape 0 147
Dshape 1 12321
2) This is wrong
Eshape 0 96
Eshape 1 12321
Dshape 0 12321
Dshape 1 96
3) ...

Other kinds of errors (inverted dimensions) that I get with default fastpoor model:

> Eshape 0 x
Eshape 1 y
Dshape 0 y
Dshape 1 x

Is there some missing functions that can cause this runtime problem?

My files:
[mxnet_predict-all.cc.zip](https://github.com/dmlc/mxnet/files/270317/mxnet_predict-all.cc.zip)
[mxnet_predict0.cc.zip](https://github.com/dmlc/mxnet/files/270318/mxnet_predict0.cc.zip)

**Comment by SlipknotTN** [comment]
I have found a solution debugging side by side mxnet.js github version and up-to-date version.

The solution was present in the past and is related to mshadow, see
https://github.com/dmlc/mshadow/commit/9105cd1c7ab4a50434bb5fdcfdff00d1719bc06c#diff-b24ff3303361719029d8b48321546c91
but it was broken by this commit
https://github.com/dmlc/mshadow/commit/c17a9af09b27a3df57e539080a0b618c735ac986#diff-b24ff3303361719029d8b48321546c91

So you need to change file mshadow/dot_engine-inl.h from line 434, inserting

>#if` MSHADOW_STAND_ALONE
if (xpu::kDevMask == cpu::kDevMask && scale == 1.0f) {
if (!transpose_left && !transpose_right) {
dst = expr::implicit_dot(lhs, rhs); return;
} else if (!transpose_left && transpose_right) {
dst = expr::implicit_dot(lhs, rhs.T()); return;
} else if (transpose_left && !transpose_right) {
dst = expr::implicit_dot(lhs.T(), rhs); return;
}
}
#endif

after
> Tensor<xpu, 2, DType> &dst = *p_dst;

**Comment by tqchen** [comment]
@SlipknotTN Do you mind to send a PR to fix this? Thanks!

**Comment by SlipknotTN** [comment]
Ok

**Comment by saustar** [comment]
@SlipknotTN How can I build it for android without blas? Running `make ANDROID=1 MIN=1` is giving following error:
```
g++ -std=c++11 -Wno-unknown-pragmas -Wall -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -O3 -fPIC -o jni_libmxnet_predict.o -c jni/predictor.cc
jni/predictor.cc:1:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated
```

**Comment by SlipknotTN** [comment]
Hi, first of all I cannot compile with ANDROID=1 and MIN=1, but only with MIN=1 for JavaScript and only with ANDROID=1.
Anyway in your case you need to compile with an android toolchain, not with standard g++.
https://github.com/dmlc/mxnet/tree/master/amalgamation , see instructions about creating standalone toolchain and set:

> export PATH = <toolchain_install_dir>/bin:$PATH
export CC = arm-linux-androideabi-gcc # or arm-linux-androideabi-clang
export CXX = arm-linux-androideabi-g++ # or arm-linux-androideabi-clang++

**Comment by zhangqianhui** [comment]
@SlipknotTN 
When i compile amalgamation project with ANDROID=1 i got this error?

#include <bits/c++config.h>
 not found

Can you explain it ?
