### ISSUE TITLE
[Archlinux] R-Package install Fails

### ISSUE THREAD

**Issue by liuyadong** [dmlc/mxnet#2185]
Hi, I am trying to install the R-package after building the shared library. It returns

`/usr/lib64/R/etc/Makeconf:139: recipe for target 'ndarray.o' failed`
`make: *** [ndarray.o] Error 1`
`ERROR: compilation failed for package ‘mxnet’`

**Comment by thirdwing** [comment]
@liubenyuan Can you show the full log? The info is too little.

**Comment by liuyadong** [comment]
This is the full log.
```
* installing to library ‘/home/yadong/R/x86_64-pc-linux-gnu-library/3.3’
* installing *source* package ‘mxnet’ ...
** libs
g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c executor.cc -o executor.o
In file included from executor.cc:9:0:
././symbol.h: In destructor ‘mxnet::R::Symbol::~Symbol()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
././symbol.h:104:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXSymbolFree(handle_));
     ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
././symbol.h:104:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXSymbolFree(handle_));
     ^
./executor.h: In destructor ‘mxnet::R::Executor::~Executor()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./executor.h:139:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXExecutorFree(handle_));
       ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./executor.h:139:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXExecutorFree(handle_));
       ^
./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c export.cc -o export.o
g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c io.cc -o io.o
In file included from io.cc:8:0:
././ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
././ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
././ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./io.h: In destructor ‘virtual mxnet::R::MXDataIter::~MXDataIter()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./io.h:65:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXDataIterFree(handle_));
     ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./io.h:65:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXDataIterFree(handle_));
     ^
g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c kvstore.cc -o kvstore.o
In file included from kvstore.cc:9:0:
./kvstore.h: In destructor ‘mxnet::R::KVStore::~KVStore()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./kvstore.h:73:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXKVStoreFree(handle_));
     ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./kvstore.h:73:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXKVStoreFree(handle_));
     ^
./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c mxnet.cc -o mxnet.o
In file included from mxnet.cc:8:0:
./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./symbol.h: In destructor ‘mxnet::R::Symbol::~Symbol()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./symbol.h:104:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXSymbolFree(handle_));
     ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./symbol.h:104:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXSymbolFree(handle_));
     ^
./executor.h: In destructor ‘mxnet::R::Executor::~Executor()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./executor.h:139:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXExecutorFree(handle_));
       ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./executor.h:139:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXExecutorFree(handle_));
       ^
./io.h: In destructor ‘virtual mxnet::R::MXDataIter::~MXDataIter()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./io.h:65:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXDataIterFree(handle_));
     ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./io.h:65:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXDataIterFree(handle_));
     ^
./kvstore.h: In destructor ‘mxnet::R::KVStore::~KVStore()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./kvstore.h:73:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXKVStoreFree(handle_));
     ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./kvstore.h:73:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXKVStoreFree(handle_));
     ^
g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c ndarray.cc -o ndarray.o
In file included from ndarray.cc:7:0:
./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
ndarray.cc: In static member function ‘static void mxnet::R::NDArray::Save(const List&, const string&)’:
ndarray.cc:220:32: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<std::__cxx11::basic_string<char> >’ and ‘Rcpp::NamesProxyPolicy<Rcpp::Vector<19> >::const_NamesProxy’)
     lst_names = data_lst.names();
                                ^
In file included from /usr/include/c++/6.1.1/vector:69:0,
                 from /home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/RcppCommon.h:59,
                 from /home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp.h:27,
                 from ndarray.cc:6:
/usr/include/c++/6.1.1/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]
     vector<_Tp, _Alloc>::
     ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/6.1.1/vector:64:0,
                 from /home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/RcppCommon.h:59,
                 from /home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp.h:27,
                 from ndarray.cc:6:
/usr/include/c++/6.1.1/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]
       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
       ^~~~~~~~
/usr/include/c++/6.1.1/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]
       operator=(initializer_list<value_type> __l)
       ^~~~~~~~
/usr/lib64/R/etc/Makeconf:139: recipe for target 'ndarray.o' failed
make: *** [ndarray.o] Error 1
ERROR: compilation failed for package ‘mxnet’
* removing ‘/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/mxnet’

```

**Comment by thirdwing** [comment]
This is really weird.

The log indicates the error is from Rcpp, but Rcpp can compile without
error with GCC 6.

On Thu, May 19, 2016 at 11:45 PM, Yadong Liu <notifications@github.com>
wrote:

> This is the full log.
>
> * installing to library ‘/home/yadong/R/x86_64-pc-linux-gnu-library/3.3’
> * installing *source* package ‘mxnet’ ...
> ** libs
> g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c executor.cc -o executor.o
> In file included from executor.cc:9:0:
> ././symbol.h: In destructor ‘mxnet::R::Symbol::~Symbol()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ././symbol.h:104:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXSymbolFree(handle_));
>      ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ././symbol.h:104:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXSymbolFree(handle_));
>      ^
> ./executor.h: In destructor ‘mxnet::R::Executor::~Executor()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./executor.h:139:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXExecutorFree(handle_));
>        ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./executor.h:139:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXExecutorFree(handle_));
>        ^
> ./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c export.cc -o export.o
> g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c io.cc -o io.o
> In file included from io.cc:8:0:
> ././ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ././ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ././ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> ./io.h: In destructor ‘virtual mxnet::R::MXDataIter::~MXDataIter()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./io.h:65:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXDataIterFree(handle_));
>      ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./io.h:65:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXDataIterFree(handle_));
>      ^
> g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c kvstore.cc -o kvstore.o
> In file included from kvstore.cc:9:0:
> ./kvstore.h: In destructor ‘mxnet::R::KVStore::~KVStore()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./kvstore.h:73:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXKVStoreFree(handle_));
>      ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./kvstore.h:73:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXKVStoreFree(handle_));
>      ^
> ./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c mxnet.cc -o mxnet.o
> In file included from mxnet.cc:8:0:
> ./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> ./symbol.h: In destructor ‘mxnet::R::Symbol::~Symbol()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./symbol.h:104:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXSymbolFree(handle_));
>      ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./symbol.h:104:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXSymbolFree(handle_));
>      ^
> ./executor.h: In destructor ‘mxnet::R::Executor::~Executor()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./executor.h:139:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXExecutorFree(handle_));
>        ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./executor.h:139:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXExecutorFree(handle_));
>        ^
> ./io.h: In destructor ‘virtual mxnet::R::MXDataIter::~MXDataIter()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./io.h:65:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXDataIterFree(handle_));
>      ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./io.h:65:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXDataIterFree(handle_));
>      ^
> ./kvstore.h: In destructor ‘mxnet::R::KVStore::~KVStore()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./kvstore.h:73:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXKVStoreFree(handle_));
>      ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./kvstore.h:73:5: note: in expansion of macro ‘MX_CALL’
>      MX_CALL(MXKVStoreFree(handle_));
>      ^
> g++ -I/usr/include/R/ -DNDEBUG -I../inst/include -D_FORTIFY_SOURCE=2 -I"/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"   -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong  -c ndarray.cc -o ndarray.o
> In file included from ndarray.cc:7:0:
> ./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
> ./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> ./base.h:83:45: note: in C++11 destructors default to noexcept
>        throw Rcpp::exception(MXGetLastError());                     \
>                                              ^
> ./ndarray.h:34:7: note: in expansion of macro ‘MX_CALL’
>        MX_CALL(MXNDArrayFree(handle));
>        ^
> ndarray.cc: In static member function ‘static void mxnet::R::NDArray::Save(const List&, const string&)’:
> ndarray.cc:220:32: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<std::__cxx11::basic_string<char> >’ and ‘Rcpp::NamesProxyPolicy<Rcpp::Vector<19> >::const_NamesProxy’)
>      lst_names = data_lst.names();
>                                 ^
> In file included from /usr/include/c++/6.1.1/vector:69:0,
>                  from /home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/RcppCommon.h:59,
>                  from /home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp.h:27,
>                  from ndarray.cc:6:
> /usr/include/c++/6.1.1/bits/vector.tcc:167:5: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]
>      vector<_Tp, _Alloc>::
>      ^~~~~~~~~~~~~~~~~~~
> In file included from /usr/include/c++/6.1.1/vector:64:0,
>                  from /home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/RcppCommon.h:59,
>                  from /home/yadong/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp.h:27,
>                  from ndarray.cc:6:
> /usr/include/c++/6.1.1/bits/stl_vector.h:450:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::vector<_Tp, _Alloc>&&) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]
>        operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
>        ^~~~~~~~
> /usr/include/c++/6.1.1/bits/stl_vector.h:471:7: note: candidate: std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(std::initializer_list<_Tp>) [with _Tp = std::__cxx11::basic_string<char>; _Alloc = std::allocator<std::__cxx11::basic_string<char> >]
>        operator=(initializer_list<value_type> __l)
>        ^~~~~~~~
> /usr/lib64/R/etc/Makeconf:139: recipe for target 'ndarray.o' failed
> make: *** [ndarray.o] Error 1
> ERROR: compilation failed for package ‘mxnet’
> * removing ‘/home/yadong/R/x86_64-pc-linux-gnu-library/3.3/mxnet’
>
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2185#issuecomment-220510451>
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by dickoa** [comment]
I do have the same error using GCC 6 on ArchLinux too.
@liuyadong Did you find any workaround ? 
cc @thirdwing

**Comment by liuyadong** [comment]
No. @dickoa

**Comment by thirdwing** [comment]
Close this for now. Feel free to reopen.

**Comment by valerioa** [comment]
I ran into the same issue. The solution appears to be replacing, in ndarray.cc

`
  std::vector<std::string> lst_names;
  if (HasName(data_lst)) {
    lst_names = (std::vector<std::string>) data_lst.names();
  }
`

with
`
  std::vector<std::string> lst_names;
  if (HasName(data_lst)) {
    Rcpp::CharacterVector cv = data_lst.names();
    lst_names = Rcpp::as<std::vector<std::string>>(cv);
  }
`

**Comment by liuyadong** [comment]
Refer to the solution, I installed the R package  successfully. Thank you. @valerioa @dickoa

**Comment by lbilli** [comment]
Same issue here on openSUSE and gcc6.
Solved with similar change in ndarray.cc:

    std::vector<std::string> lst_names;
    if (HasName(data_lst)) {
      lst_names = Rcpp::as<std::vector<std::string>>(data_lst.names());
    }

Versions:
openSUSE 42.2
gcc 6.1.1
R 3.3.2
Rcpp 0.12.8
mxnet 0.7

**Comment by vincentstoliaroff** [comment]
The same solution worked for me as well on debian sid, gcc 6.2.0

**Comment by thirdwing** [comment]
I will test it with GCC6 and fix this.

**Comment by thirdwing** [comment]
Hi, everyone, I pushed the change you suggest in https://github.com/dmlc/mxnet/pull/4160

Please try nnvm branch.
