### ISSUE TITLE
gpu memory consumption kept increasing all the time when just did executor.forward operation

### ISSUE THREAD

**Issue by xzqjack** [dmlc/mxnet#2186]
I made a file recorder following the example code "example/fcn-xs/data.py/FileIter" dataiter. Gpu memory consumption kept increasing all the time till out of memory error, when  the data of dataiter is passed   into executor and only did `executor.forward()` operation circularly. Bellow code could reproduce the error.
```
import mxnet as mx
import mxlib
import model_vgg19

args = mxlib.config(root_path = "/home/gpu2/separate-reflection/dataset", 
                 input_shape = (8,3,256,256),
                 flist_name = "../dataset/train_img.lst", 
                 prefix='../model/sepRef',
                 save_iteration = 200,
                 load_iteration = 0,              
  test_img="../test/mix/COCO_train2014_000000001764_COCO_train2014_000000078380.jpg")
                 
dataiter = mxlib.ImageIter(args.root_path, args.flist_name, batch_size=args.input_shape[0],show_rf=True)
vgg_model = model_vgg19.get_model(args.input_shape,ctx=args.ctx)#model definition from "example/neural-style"

for e in range(args.max_num_epochs):
    dataiter.reset()
    for data in dataiter:      #data is numpy array
        vgg_model.data[:] = mx.nd.array(data["mix"],ctx=args.ctx)
        vgg_model.executor.forward()  
```
Is there any problem in my code? If yes, please show some hints about how to solve it.
Or is this a bug needs to fixed?
Any information will be appreciated.

**Comment by xzqjack** [comment]
The code has been running well after i replaced the code `vgg_model.data[:] = mx.nd.array(data["mix"],ctx=args.ctx)` with `vgg_model.data[:] = mx.nd.array(data["mix"])`.
That means the operation, `mx.nd.array(data,ctx=mx.gpu(0))` will create a new variable that occupy memory. Is this interpretation right?

**Comment by piiswrong** [comment]
Because there is no synchronization point, you are pushing too many operations into the engine. Add a executor.outputs[0].wait_to_read() before forward

**Comment by xzqjack** [comment]
Thanks for your reply @piiswrong.  The code is running successfully now. 
I found another way to make code running without memory error by replacing `vgg_model.data[:] = mx.nd.array(data["mix"],ctx=args.ctx)` with `vgg_model.data[:] = data["mix"])`. But i don't know the second way is right or not.

**Comment by tqchen** [comment]
assign from or to numpy array is always synchronization. Usually you will always want to copy data out to CPU, and that will be a synchronization and it is good to do so
