### ISSUE TITLE
Tag a New Release

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#2189]
There has been a lot of changes since the first release. We need to adopt release cycle as @pluskid suggested and keep track of list of changes being made.

- [x] Add a NEWS.md file to briefly list changes that has been made since 0.5
- [x] Make sure all the known bug fix are checked in 
- [x] Tag a new release version, the aimed version is v0.7 since a lot has been added since them.

@pluskid @antinucleon @piiswrong 
Please reply to this issue to add a list of changes that you have done.

**Comment by piiswrong** [comment]
When was v0.5?

**Comment by tqchen** [comment]
It was the first release of mxnet

**Comment by pluskid** [comment]
I think it is good to also have a NEWS.md or ChangLog.md to summarize the release dates and main changes in each release.

Btw: why skipping 0.6? 

Also I think it is good to have convention of the version number. Julia kind of have major.minor.issue convention. Maybe we can look around and adopt a convention.

**Comment by pluskid** [comment]
Also the Sphinx doc can be versioned, we need to remember updating the version number there.

**Comment by tqchen** [comment]
@pluskid I agree that a NEWS.md is needed.  The version number just jumps out as there is a lot of things happening since the first release, so we feel maybe that worth more than 0.1

**Comment by tqchen** [comment]
@pluskid @piiswrong @antinucleon @mli I have created news.md here https://github.com/dmlc/mxnet/blob/master/NEWS.md

Please help fill in things that you find missing. Let us tag a new version once the change list are ready and change our way of versioning starting this point

**Comment by tqchen** [comment]
I think @pluskid have quite a lot of experience in versioning. Maybe you can give a proposal on how we should do versioning and we can keep the rule as we move on

**Comment by pluskid** [comment]
Thanks @tqchen ! Let's do major.minor.issue then. Let us call the next release v0.7.0.

- major: for major releases (e.g. when we feel ready to have a v1.0.0 release) or big breaking changes
- minor: some big updates
- issue: mostly for bugfixing quick releases

**Comment by tqchen** [comment]
sounds good. I also find the milestone tag could be useful to group possible roadmaps needed fro minor version updates.

**Comment by tqchen** [comment]
@piiswrong @antinucleon @pluskid Please check the NEWS.md and update your part accordiningly. Let us tag a release this week

**Comment by pluskid** [comment]
Also I think we can disable some heavy tests for PRs and then explicitly run a full load test suite before each release.

**Comment by tqchen** [comment]
https://github.com/dmlc/mxnet/releases/tag/v0.7.0
