### ISSUE TITLE
[DOC] Dependency order example

### ISSUE THREAD

**Issue by bryandeng** [dmlc/mxnet#219]
Hi DMLCers:

I'm reading https://github.com/dmlc/mxnet/blob/master/doc/developer-guide/note_engine.md.

In this figure
https://github.com/dmlc/dmlc.github.io/blob/master/img/mxnet/engine/dep_simple.png,
do you actually mean `D = B * C` because it seems that `D = A * C` doesn't depend on `B`?

**Comment by tqchen** [comment]
Sorry for the delayed reply. Yes you are right. Thanks for the catch!

**Comment by tqchen** [comment]
The figure has been updated. Thanks! 
 I have added you to the  https://github.com/dmlc/mxnet/blob/master/CONTRIBUTORS.md .
Hope we can get more of your contribution to mxnet

**Comment by bryandeng** [comment]
If you like, I can help update the documentation, as well as fix some typos and wording issues. So you can focus on development.

**Comment by tqchen** [comment]
That will be really awesome. We think the notes and ideas are as(more) important as the code itself, and it is really nice if you like to share your piece of wisdom with the community

**Comment by tqchen** [comment]
Please feel free to send the pull request.

**Comment by bryandeng** [comment]
Solved by https://github.com/bryandeng/mxnet/commit/a3542fd48a66e8f9a78bd4e1c643c65159e5ba46 and #280.
