### ISSUE TITLE
make rebuild is not working

### ISSUE THREAD

**Issue by carlosb1** [dmlc/mxnet#2190]
I was trying to rebuild  the porting to javascript to project to fix another issue but I couldn't.
I installed emscripten as It is explained in its web, and I tried to run the `make` file. I got an error about cblas, but I have installed this library in my computer, It should be work. This is the stacktrace:

```
emcc -std=c++11  -O2 -D__MXNET_JS__  -o libmxnet_predict.js mxnet_predict-all.cc -s DISABLE_EXCEPTION_CATCHING=0 -s EXPORTED_FUNCTIONS="['_MXPredCreate', '_MXPredGetOutputShape', '_MXPredSetInput', '_MXPredForward', '_MXPredPartialForward', '_MXPredGetOutput', '_MXPredFree', '_MXNDListCreate', '_MXNDListGet', '_MXNDListFree']" -s ALLOW_MEMORY_GROWTH=1
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those
mxnet_predict-all.cc:24:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
make[1]: *** [libmxnet_predict.js] Error 1
make[1]: Leaving directory `/home/carlos/javascript-workspace/test-mxnet/mxnet.js/mxnet/amalgamation'
/home/carlos/javascript-workspace/test-mxnet/mxnet.js
cp mxnet/amalgamation/libmxnet_predict.js* .
cp: cannot stat ‘mxnet/amalgamation/libmxnet_predict.js*’: No such file or directory
```

**Comment by SlipknotTN** [comment]
You have to comment the line "#include <cblas.h>" in file mxnet_predict-all.cc and run make again. Furthermore Javascript version doesn't use cblas, i successfully compile JS version with make MIN=1. Probably a clean solution is to modify amalgamation.py excluding the cblas include with MIN=1.

In case of runtime errors see this issue that I've recently encountered with mxnet.js #2178

**Comment by carlosb1** [comment]
@SlipknotTN , if you add the MIN=1, will it be necessary to add Openblas dependencies?

**Comment by SlipknotTN** [comment]
When you compile JS lib with emscripten you don't add openblas dependencies. OpenBLAS is used for Android and iOS version with MIN=0.
So JS version should work also without BLAS.
