### ISSUE TITLE
does mx.sym.sum take batch size into account ?

### ISSUE THREAD

**Issue by juliandewit** [dmlc/mxnet#2192]
Hello I wanted to do something with mx.sym.sum.

I have 2 outputs that I want to diff and sum.
leg1 and leg2 are outputs of FullyConnected
minibatch size = 128

```
diff1 = mx.sym.sum(mx.sym.square(leg1 - leg2))
shape of diff1 returns a shape of 1 instead of 128,1 
```

How can I tell the sum symbol to take into account to sum per row instead of summing the whole matrix ?

**Comment by tqchen** [comment]
it sums over the entire tensor, including the batch dimension

**Comment by juliandewit** [comment]
Hello, is there an alternative ? 
I'm trying to compose various layers by low-level primitives. Sum seems to be indispensible.
The only thing I can come up with now is a FullyConnectedLayer with weights fixed at 1.
But that seems to be overkill.

**Comment by juliandewit** [comment]
Or could I do Reshape to (128, Layeroutput, 1)
And then do sum_mid_internal and after that a reshape to 128, 1

Still a bit cumbersome but this might work.

**Comment by juliandewit** [comment]
FYI 
```
Reshape to (128, Layeroutput, 1)
sum_mid_internal
Reshape to (128, 1)
```
Worked.
Not ideal but manageble

**Comment by tqchen** [comment]
We should work out a solution for sum with axis argument. Please stay tuned
