### ISSUE TITLE
how can I load symbol file with my python op just like load with default cpp ops?

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#2194]
as title,  when load my python op  symbol file , coredump...

**Comment by tqchen** [comment]
this should be fixed by moving to recent customOp by @piiswrong

**Comment by antinucleon** [comment]
Use custom op instead of python op

On Thu, May 19, 2016 at 9:21 PM Tianqi Chen <notifications@github.com>
wrote:

> this should be fixed by moving to recent customOp by @piiswrong
> <https://github.com/piiswrong>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2194#issuecomment-220513933>
>
-- 
Sent from mobile phone

**Comment by junranhe** [comment]
well, thanks for reply!
