### ISSUE TITLE
ndarray_softmax.py and numpy_softmax.py are deprecated?

### ISSUE THREAD

**Issue by EasonD3** [dmlc/mxnet#2195]
As mentioned in [How to Create New Operations](http://mxnet.readthedocs.io/en/latest/how_to/new_op.html), it seems the two files [`ndarray_softmax.py`](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/ndarray_softmax.py) and [`numpy_softmax.py`](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/numpy_softmax.py) have been deprecated. Does that mean we're encouraged to use CustomOp or C++/Mshadow to create customized operators?

Actually, the two files, [`ndarray_softmax.py`](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/ndarray_softmax.py) and [`numpy_softmax.py`](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/numpy_softmax.py), can still be successfully executed.

**Comment by piiswrong** [comment]
Yes, it's encouraged to move to customop. ndarrayop and numpyop works as of now but will not be maintained anymore

**Comment by EasonD3** [comment]
I see. Thanks~
