### ISSUE TITLE
[OP] Sum with axis

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#2197]
As mentioned in several places #2192 https://github.com/dmlc/mxnet/pull/2141 , We need to enhance sum with property axis support.

I am opening this issue to look for volunteer who want can help to take a stab. Please reply to this issue if you are interested

 @sxjscience @piiswrong @mli

**Comment by sxjscience** [comment]
I can have a try.

**Comment by tqchen** [comment]
sounds great! thanks!

**Comment by tqchen** [comment]
Thanks to @sxjscience This feature is fully implemented

**Comment by tqchen** [comment]
@sxjscience I feel that we can now directly replace sum_axis-> sum , while maintaining compatiblity, right? Maybe it is a good idea to do that

**Comment by sxjscience** [comment]
@tqchen, Yes, we can do that. 
The current `sum_axis` only supports reducing over a single axis (or reducing over the whole tensor if axis =-1). In order to support multi-axis, I've combined multiple `sum_axis`s in the python side to construct the `sum` operator. 
It would be better to have a `sum` operator in C++ that can reduce/broadcast over multiple axes. I'll work on that.

**Comment by tqchen** [comment]
this sounds good to me

**Comment by tqchen** [comment]
let us change the sum_axis->sum after the changes are done

**Comment by tqchen** [comment]
@sxjscience One comment on using (axis==-1) as summing over all. 

- This can be a bit incompatible with numpy's behavior on allowing axis to be negative. Although this is a minor thing, we might want to think a bit on how it can be avoided for future compatiblity.
- One way we can do is to support a nullable type in int setting. So user can pass in axis=None, while it get parsed as a special integer setted through configuration. 

Let me know about your thoughts

**Comment by piiswrong** [comment]
Does dmlcparameter have an explicit missing indicator?

**Comment by tqchen** [comment]
the missing field is not presented in the structure.

**Comment by sxjscience** [comment]
@tqchen I'm thinking to directly implement `sum` Op in C++ with full numpy compatibility (multiple axes + keepdims). The new sum op may take two parameters, axis (TShape) and keepdims (bool). For the axis param, I can set the default to `TShape()` similar to https://github.com/dmlc/mxnet/blob/master/src/operator/matrix_op-inl.h#L22-L28. However, the new Op will support limited NDIM if the reducing axes are not contiguous.

**Comment by tqchen** [comment]
sounds good to me. However, it would be nice if axis can also support integer as opposed to only support tuple, maybe some customized parser is needed. Or change parsing of TShape to accept integers

**Comment by sxjscience** [comment]
Yes, accepting integers directly will be helpful. I'll try to achieve that. Also, the second solution seems better since other OPs will also benefit from this functionality.

**Comment by tqchen** [comment]
The parsing of TShape is in the mshadow. Need to change change the overload of operator>> to TShape to achieve this. Use peek to decide if it is tuple or int

**Comment by tqchen** [comment]
@sxjscience any update on this? I think it is helpful to change sum_axis->sum as soon as possible, even though sum_axis do not support multiple axis now. As this is the right convention and it will cause less future compatibility problem

**Comment by sxjscience** [comment]
@tqchen Sorry for the delay. I'm busy with individual meeting these days... I'll begin work on this today.

**Comment by tqchen** [comment]
no problem, please take your pace
