### ISSUE TITLE
Profiling compute time for individual operators in a graph

### ISSUE THREAD

**Issue by Piyush3dB** [dmlc/mxnet#2203]
Hello,

I'm trying to work out the compute times for every operator in my computation graph when I do a forward pass.  Is it possible to obtain this information for GPU and CPU modes?  If not, is it possible I can instrument the code in some way to retrieve this information?

Thanks,
Piyush3dB

**Comment by piiswrong** [comment]
we currently don't have a profiler. You can try adding it in graph_executor.

**Comment by sxjscience** [comment]
Related to https://github.com/dmlc/mxnet/issues/406, tianqi has given some helpful instructions. I was not familiar with MXNet at that time so I had not continued.

**Comment by Piyush3dB** [comment]
ok, thanks for the pointer. @sxjscience, I'm not too familiar with that part of the MXNet code.  I'll have a look and work out what to do.  Did you have a better idea about it now?  Thanks.

**Comment by sxjscience** [comment]
@Piyush3dB We can possibly insert timer in the execution logic. I need more tests to confirm the idea. Also, timing may not be trivial due to the asynchronous executions.

**Comment by vchuravy** [comment]
Also timing of operations executed on the gpu will need special consideration

**Comment by zorksylar** [comment]
Any news of this feature? Is it merged into the master branch?

**Comment by piiswrong** [comment]
see examples/profiler
