### ISSUE TITLE
performance question with numpy array

### ISSUE THREAD

**Issue by guileryu01** [dmlc/mxnet#2204]
I'm training a convolutional network with data loaded into numpy array and NDArrayIter. When I tried to profile the script, I found that over 90% time is spent calling asnumpy() in metric.update function. Is this normal or am I am doing something wrong? Accuracy is the only metric I pass in as eval_metrics.
I compared this with same network implemented with Theano, but the other one is about twice as fast.

Thanks,

![mx2](https://cloud.githubusercontent.com/assets/19419399/15448577/fe8b8d12-1f33-11e6-8041-328a0de2ec9e.png)

**Comment by tqchen** [comment]
It is normal, because most mxnet operator are asynchronous, which means they do not block until the operation finishes. Instead, there dependency is tracked.

asnumpy introduce a synchronization, which need to wait all previous operations to finish

**Comment by guileryu01** [comment]
Thanks. So if I still want to report training accuracy without significant performance hit, like only report every x batches, is there an easy way to do that?

**Comment by tqchen** [comment]
usually the speedup you observe was not really speedup, but the asynchronous executions that are pushed but not finished get counted as finished. It is usually fine to use the default evaluation metric provided.
