### ISSUE TITLE
installing package: void links

### ISSUE THREAD

**Issue by lorismichel** [dmlc/mxnet#2205]
I am a mac user, I tried loading your package following the three commands you listed (through drat) and I obtain an error due to void links. Thank you for your help in advance.

Attached a screen-shot of the problem.

<img width="871" alt="problempackage" src="https://cloud.githubusercontent.com/assets/12015679/15450065/36170b3c-1f91-11e6-8fec-1b83ac927e7e.png">

**Comment by lorismichel** [comment]
I forgot to point out that I am under Captain.

**Comment by thirdwing** [comment]
I forgot upload the package for 3.3. Please try again now.

**Comment by lorismichel** [comment]
Now I can install it, but when I load it I obtain the following error message

<img width="952" alt="ptoblempackage2" src="https://cloud.githubusercontent.com/assets/12015679/15461309/3d06ff86-20ba-11e6-9e9d-0a5d50266960.png">

**Comment by thirdwing** [comment]
OK. You don't have opencv installed on you Mac.

Maybe we need to remove opencv dependency from Mac R package.

Let me think.

On Mon, May 23, 2016 at 1:46 AM, lorismichel <notifications@github.com>
wrote:

> Now I can install it, but when I load it I obtain the following error
> message
>
> [image: ptoblempackage2]
> <https://cloud.githubusercontent.com/assets/12015679/15461309/3d06ff86-20ba-11e6-9e9d-0a5d50266960.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2205#issuecomment-220892114>
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by thirdwing** [comment]
Please try again. I just upload the latest version.

**Comment by lorismichel** [comment]
I successfully loaded the package, many thanks!
