### ISSUE TITLE
mx.operator.CustomOp AttributeError: 'module' object has no attribute 'CustomOp'

### ISSUE THREAD

**Issue by fungtion** [dmlc/mxnet#2208]
I followed the [instruction] (https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/custom_softmax.py) to define a new layer, but it pops a error: ' 'module' object has no attribute 'CustomOp'', I've no idea how to fix it

**Comment by piiswrong** [comment]
You need to pull the most recent code.
