### ISSUE TITLE
Problem with MXNet, R-package and Ubuntu

### ISSUE THREAD

**Issue by wave-electron** [dmlc/mxnet#2212]
I  regard myself as a novice trying to install mxnet on docker-machine with Ubuntu on a mac. So far I got it working on my base Mac system, but as I'm running a Shiny server on the docker-machine with Ubuntu... I thought it would be neat to get it running on the server as well.

When I try require(mxnet) the library mxnet its not being found after running thru the build stage. I then worked out it wasn't installed in the normal places my other R libraries are usually installed.

    .libPaths() # all library trees R knows about

    [1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"

    [3] "/usr/lib/R/library"

It seems to have install in my root directory "/mxnet/R-package/R"

I'm guessing I now need to add this to my .libPaths() 

    .libPaths(c('/mxnet/R-package',.libPaths()))

    .libPaths()
    [1] "/mxnet/R-package" "/usr/local/lib/R/site-library"
    [3] "/usr/lib/R/site-library" "/usr/lib/R/library"

I've tried this but, require(mxnet) is saying

    Loading required package: mxnet
    Warning message:
    In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
    there is no package called ‘mxnet’

I also tried...

    library("mxnet", lib.loc="/mxnet/R-package/R")
    Error in library("mxnet", lib.loc = "/mxnet/R-package/R") : 
    there is no package called ‘mxnet’
    library("mxnet", lib.loc="/mxnet/R-package")
    Error in library("mxnet", lib.loc = "/mxnet/R-package") : 
    there is no package called ‘mxnet’

I'm not seeing a directory called mxnet like in pythons case. But I do see the R library files in a directory called R, which seem to match the python files.

I'm struggling to work out what to try next with my limited understanding of installing R packages from source.

**Comment by ainhoa2** [comment]
Hi, why did you close this issue? I'm having a similar one on Windows 10 (I've tried to install this on Windows 7 as well with other errors) and I can't figure out how to solve it. Would appreciate any hints!

**Comment by wave-electron** [comment]
Are you running docker on windows? I was running docker-machine on a Mac.
