### ISSUE TITLE
cudnn version

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#2216]
How can I check to see which version of cudnn mxnet is using? I think I have v5 working but I'm not positive.

**Comment by antinucleon** [comment]
We support V5, and we always support newest CUDNN so feel free to use
newest.

On Mon, May 23, 2016 at 2:27 PM Jacob Schreiber <notifications@github.com>
wrote:

> How can I check to see which version of cudnn mxnet is using? I think I
> have v5 working but I'm not positive.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2216>
>
-- 
Sent from mobile phone

**Comment by jmschrei** [comment]
I mean, I have multiple versions of cudnn installed, and I'd like to make sure mxnet is using the right version. Is there a way to confirm this from within mxnet?

**Comment by antinucleon** [comment]
If you like you can print ```CUDNN_MAJOR``` while compiling.
CUDNN Version support code is at:
https://github.com/dmlc/mxnet/blob/master/src/operator/cudnn_convolution-inl.h#L78


On Mon, May 23, 2016 at 3:48 PM Jacob Schreiber <notifications@github.com>
wrote:

> I mean, I have multiple versions of cudnn installed, and I'd like to make
> sure mxnet is using the right version. Is there a way to confirm this from
> within mxnet?
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2216#issuecomment-221119005>
>
-- 
Sent from mobile phone

**Comment by piiswrong** [comment]
so basically add `LOG(INFO) << "CUDNN" << CUDNN_MAJOR;` somewhere and see if it's 5

**Comment by jmschrei** [comment]
Great. Thanks for the help.
