### ISSUE TITLE
Mxnet is not working fine with mxnet.js

### ISSUE THREAD

**Issue by carlosb1** [dmlc/mxnet#2221]
I am trying to use in mxnet.js  and a googlenet model which we created via Caffe. Unfortunately, It seems mxnet.js doesn't accept this updated version from the inception model (This model works fine with mxnet and python)... 

I downloaded mxnet.js and the last updated version for mxnet, and I received this error if I apply the test test_on_node.js with my inception model.

carlos@carlos-ubuntu7 ~/javascript-workspace/test-mxnet/mxnet.js $ nodejs test_on_node.js 
missing function: _ZN5mxnet2op16SimpleOpRegistry3GetEv
-1
-1

```
/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require===
abort(-1) at Error
    at jsStackTrace (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:1:18243)
    at stackTrace (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:1:18426)
    at abort (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:18:17965)
    at __ZN5mxnet2op16SimpleOpRegistry3GetEv [mxnet::op::SimpleOpRegistry::Get()] (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:1:42036)
    at lY (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:10:264603)
    at asm.__GLOBAL__sub_I_mxnet_predict_all_cc (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:18:6401)
    at __ATINIT__.push.func (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:1:27394)
    at callRuntimeCallbacks (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:1:22340)
    at ensureInitRuntime (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:1:22840)
    at doRun (/home/carlos/javascript-workspace/test-mxnet/mxnet.js/libmxnet_predict.js:18:16456)
```

**Comment by carlosb1** [comment]
It seems, the mxnet is not compiling fine with mxnet.js, the error is with: 
this: missing function: _ZN5mxnet2op16SimpleOpRegistry3GetEv

**Comment by piiswrong** [comment]
Did you try make clean and make again?

**Comment by carlosb1** [comment]
I included  src/operator/operator_util.cc  in  mxnet_predict0.cc

 #include "src/symbol/static_graph.cc"
 #include "src/symbol/symbol.cc"
 #include "src/operator/operator.cc"
+#include "src/operator/operator_util.cc"
 #include "src/operator/activation.cc"
 #include "src/operator/batch_norm.cc"
 #include "src/operator/block_grad.cc"

Now, It seems  compiles fine... (first step accomplished) but I am testing with test_on_node.js ... and it gives me another  error / warning:

[09:31:14] mxnet_predict-all.cc:550: [09:31:14] mxnet_predict-all.cc:7571: Check failed: eshape[0] == 0 || eshape == dshape Assignment: Shape of Tensors are not consistent with target
I don't know exactly what problem is (It could be a problem with my model...), But if someone has any idea, I would appreciate it... 

My inception model was tested with an python example for mxnet and it works fine... For this reason, I would discard a problem with my model...

**Comment by carlosb1** [comment]
Also, I checked the fastpoor.json model which it is included in the repository and it doesn't work...

**Comment by SlipknotTN** [comment]
Same error as https://github.com/dmlc/mxnet/issues/2178

I've just send a PR to fix the problem. You need to change mshadow/dot_engine-inl.h
https://github.com/dmlc/mshadow/pull/120/commits/cc506b69f465c26c38c1e3a50ff7de1f5f508e2c

**Comment by carlosb1** [comment]
Thanks @SlipknotTN , it is compiling fine but It doesn't work fine... I compare result with the fastpoor.json model (before and after) and they are giving strange results...

This is my output if I execute `test_on_node.js` with the new compiled version (I analyse `cat.png` and I load the `fastpoor.json`)

```
Warning: Enlarging memory arrays, this is not fast! 16777216,33554432

enlarged memory arrays from 16777216 to 33554432, took 6 ms (has ArrayBuffer.transfer? false)
Max=1000
Top: n02127052 lynx, catamount , value=0.48860809206962585
Top: n03958227 plastic bag , value=0.07041524350643158
Top: n02123045 tabby, tabby cat , value=0.07001253962516785
Top: n02124075 Egyptian cat , value=0.06479660421609879
Top: n02909870 bucket, pail , value=0.057837821543216705
```

**Comment by SlipknotTN** [comment]
Mhm... this is strange, I have exactly the same results as before. The fix

> +#include "src/operator/operator_util.cc"

is correct and I have used it. I have also added

> #include "src/operator/elementwise_unary_op.cc"

and removed 

> #include "src/ndarray/unary_function.cc"
#include "src/common/tblob_op_registry.cc"

On Google Chrome, fastpoor and cat.png I get this results:

Top-1:n02123159 tiger cat, value=0.32267525792121887
Top-2:n02123045 tabby, tabby cat, value=0.2338210940361023
Top-3:n02124075 Egyptian cat, value=0.18019989132881165
Top-4:n02909870 bucket, pail, value=0.1256609559059143
Top-5:n03958227 plastic bag, value=0.032655153423547745

**Comment by carlosb1** [comment]
I am going to check it.. It can be my problem, the web example with the classifier_image.js seems fine

**Comment by carlosb1** [comment]
The browser example is working fine..., but the nodejs example test_on_nodesj, It doesn't work me... I will close the ticket, and I will try to get time to understand why it is not working.. Will someone apply this change in a pull request?? I
