### ISSUE TITLE
Segfault when ndarray shape is empty

### ISSUE THREAD

**Issue by mavenlin** [dmlc/mxnet#2223]
The following code segfaults,
`import mxnet`
`mxnet.nd.zeros(())`
I think the segfault happens when trying to assign 0 to ndarray.
Preferably it should raise an exception.
Any thoughts to proper handle this problem? As it may happen in other places too.

**Comment by piiswrong** [comment]
normally it should check if the array is initialized. We should fix this

**Comment by piiswrong** [comment]
numpy seems to treat empty array as scalars
