### ISSUE TITLE
Support/optimization for 16-bit floating point?

### ISSUE THREAD

**Issue by novog** [dmlc/mxnet#2227]
According to the MXNet.jl documentation:

> There is no generics in NDArray, the eltype is always mx.MX_float. Because for applications in machine learning, single precision floating point numbers are typical a best choice balancing between precision, speed and portability. Also since libmxnet is designed to support multiple languages as front-ends, it is much simpler to implement with a fixed data type.

If I understand correctly, MXNet currently cannot take advantage of the 2x half-precision performance of the upcoming NVidia Pascal-based cards. Is this correct? If so, are there plans to add the ability to leverage this feature in the future?

**Comment by piiswrong** [comment]
python package does support fp16. julia package doesn't

**Comment by vchuravy** [comment]
@novog I am currently working on supporting this https://github.com/dmlc/MXNet.jl/pull/97. I hope to have this ready in the coming weeks.

**Comment by novog** [comment]
Good to hear, thanks!
