### ISSUE TITLE
Why update_metrics utilizes so much of time.

### ISSUE THREAD

**Issue by kandycs** [dmlc/mxnet#2228]
I am trying to run train_imagenet.py on task3 from imagenet 2012.  
I prepared the data set to recordIO format with 256*256*3 data shape. 
with 25080 training samples, it takes around 20 hours to finish 20 epochs training with VGG network
And I found most of time, around 98% is spend by update_metrics function. 
I also checked train_minst.py, and train_cifar10.py, both of them spend around 98% time on update_metrics too. 

I utilized default update metrics functions provided by scripts. 

I sounds really unreasonable, is there something wrong with my runnings ?

**Comment by tqchen** [comment]
this is because mxnet runs asynchronizely, and update_metrics is the only point where the process block and wait for the prediction. So the time spent on update_metrics contains the time needed for forward operations, as well as previous backward updates

**Comment by guileryu01** [comment]
This is the same problem I had in #2204. 

Is it that this metric is for information only and doesn't affect training at all? In my case I got 10x speed up by replacing the default accuracy metric with a dummy one.
If waiting for the prediction is where the program gets blocked, can this metric be evaluated asynchronously as well?

**Comment by tqchen** [comment]
usually the speedup you observe was not really speedup, but the asynchronous executions that are pushed but not finished get counted as finished. It is usually fine to use the default evaluation metric provided.

**Comment by kandycs** [comment]
tqchen,
Thanks for your feedback. How about _LIB.MXKVStorePush call, is it also working asynchronous ? 
When I run on single node with local kvstore, it seems that the execution time of _LIB.MXKVStorePush (inside push method of kvstore.py) is much smaller than the execution time of MXKVStorePush (measured at c_api.cc). Why could this happen ?

**Comment by tqchen** [comment]
I guess that was simply due to inaccurate estimate. The kv store ops are also async

**Comment by kandycs** [comment]
Hi Tianqi, 
Thanks for getting back to me. 
I looked at kvstore codes under `src/kvstore` folder. 
the kvstore defined in `kvstore_local.h` is utilized, It seems everything in this file works synchrony. 
I think `MXKVStorePush` at `c_api.cc` is simple an wrapper to the Push method defined in `kvstore_local.h`. They have similar execution time, around 3 seconds for 1 epoch. To my understanding, `_LIB.MXKVStorePush` in python is to call MXKVStorePush in `c_api.cc` directly, as `_LIB` is just a `ctypes` class. But its execution time is much smaller, around 0.8 seconds. I think `_LIB.MXKVStorePush` should have similar execution time to `MXKVStorePush` at `c_api.cc`, despite whether async op or sync ops are used inside `kvstore_local.h` . Am I right ?
