### ISSUE TITLE
AssertionError occured in a customized iterator based on PrefetchingIter

### ISSUE THREAD

**Issue by EasonD3** [dmlc/mxnet#2229]
I'm working on assigning a pre-defined weight for each training instance in weighted Softmax loss. The image data and labels are loaded by using `ImageRecordIter`, and the weights are loaded by using `CSVIter`. To merge the two iters into one, I created a customized iterator based on `PrefetchingIter` (see the code [here](https://github.com/EasonD3/mxnet-test/blob/master/custom_iters.py)). Compared with the original `PrefetchingIter` code, in my customized iterator I modified `self.provide_data`, `self.provide_label` and `self.current_batch` as follows:
```
## In Line 26
# set provide_data and provide_label
self.provide_data = [('data', iters[0].provide_data[0][1]), ('weight', iters[1].provide_data[0][1])]
self.provide_label = iters[0].provide_label

...

## In Line 88
self.current_batch = mx.io.DataBatch(
    # two parts: data and weight
    self.next_batch[0].data + self.next_batch[1].data,
    # only the first iter has label
    self.next_batch[0].label,
    self.next_batch[0].pad,
    self.next_batch[0].index
)

...
```

For the weighted Softmax loss, I created a new based on `CustomOp`, which can be found in [test_instance_weighted_softmax.py](https://github.com/EasonD3/mxnet-test/blob/master/test_instance_weighted_softmax.py). This file also provides a runnable test by using the MNIST dataset. When training the model, the code throws an error (which I have no clue on what's going on there):
```
AssertionError: Number of entry mismatches between iterators
```
I put everything in [this repo](https://github.com/EasonD3/mxnet-test). If you have installed MXNet, you can directly run [test_instance_weighted_softmax.py](https://github.com/EasonD3/mxnet-test/blob/master/test_instance_weighted_softmax.py) to reproduce the error.

Can someone please advise on how to solve that? And what causes that error?

Thanks.

**Comment by piiswrong** [comment]
the iterators you are combining has different number of entries per epoch. i.e. when one iter has finished the other is still going. They need to have the same length

**Comment by EasonD3** [comment]
@piiswrong Thanks for the reply. Actually both image data and weights contain 60000 entries (or rows). And for both the iters, I set the batch size as the same. So I don't think it's due to the different length issue.

**Comment by piiswrong** [comment]
try write a simple loop to check for data/label consistency

**Comment by EasonD3** [comment]
I discovered that it was due to a strange behavior of `iter.reset()` for the CSVIter. Basically, in my machine, it does not reset the CSVIter to the beginning. Anyway, I'll have some more debug to figure out. Thanks
