### ISSUE TITLE
gpu not enabled error

### ISSUE THREAD

**Issue by westpilgrim** [dmlc/mxnet#2234]
hi I modify the example in cpp image-classification-predict.cc to use my own dnn model .But got the error at 'MXPredCreate" ,it returned -1 and gives the following error:

[13:55:10] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [13:55:10]D:\chhong\mxnet\src\ndarray\ndarray.cc:283: GPU is not enabled

I did not forget to set int dev_type = 1;
and I use the mxnet cpu-only binaries from you: 20160419_win10_x64_cpu_only.7z

so what's the problem?

**Comment by piiswrong** [comment]
since you are using cpu-only binary you can't use gpu

**Comment by westpilgrim** [comment]
so how do I disable gpu? I already set dev_type to 1 ,which means use cpu only,is this not enough?

**Comment by piiswrong** [comment]
1 is gpu, 0 is cpu

**Comment by westpilgrim** [comment]
I edited the variable to 0 ,but the error was the same

**Comment by westpilgrim** [comment]
Actually I didnt change anything in the cpp example image-classification-predict.cc apart from the model  path and the pic size .

**Comment by Jinnaouc** [comment]
Have you solved this problem? If you have solved this problem, can you share the solution with me?
