### ISSUE TITLE
关于windows的预编译版本。

### ISSUE THREAD

**Issue by mhzdlm** [dmlc/mxnet#2237]
windows的预编译版实在是太好用了。

不过有点不方便的地方是，因为例子里面下载数据都是用的wget，所以windows下的例子，都是没办法直街运行的。

后来我发现wget原来有windows版，http://www.interlog.com/~tcharron/wgetwin.html
我在3dpart文件夹下面加了一个wget文件夹，然后加入path，例子就能正常运行了。

所以下一个预编译版本能否考虑加入wget呢？

@hjk41

**Comment by mhzdlm** [comment]
刚发现啊，不只是需要wget，还要unzip
http://gnuwin32.sourceforge.net/packages/unzip.htm

**Comment by hjk41** [comment]
thanks for the suggestion. I will include these files in the next release.

On Thu, May 26, 2016 at 1:07 PM, mhzdlm <notifications@github.com> wrote:

> 刚发现啊，不只是需要wget，还要unzip
> http://gnuwin32.sourceforge.net/packages/unzip.htm
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2237#issuecomment-221778474>
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia
