### ISSUE TITLE
Will MXnet support lua interface?

### ISSUE THREAD

**Issue by cjfan** [dmlc/mxnet#2240]
I see there is a torch version, but it can not build on window. Will MXnet support lua interface?

**Comment by piiswrong** [comment]
why can't it build on windows? what error are you getting?

**Comment by cjfan** [comment]
The mxnet can build on window well, but I want use it directly in the Lua script.
From the Doc,I suppose it can working with torch as a plugin.But the offical torch7 can't build on windows, only if with mingw and no GPU support? I'm not sure of that.

**Comment by piiswrong** [comment]
ok so torch doesn't work on windows...

I don't think anyone is doing a full function lua interface because it's a huge project.
Any reason why you need lua?

**Comment by cjfan** [comment]
Our project use a c++ engine with luajit script interface last several years.
Recently, we are trying some DL method.
With a direct lua api, it will be more convenience.
so maybe I need to try something like call python from lua or by communication with data exchange, or even export some necessary API from c++.

**Comment by qiaohaijun** [comment]
I am reading the mxnet code, and try to make a lua binding

**Comment by qiaohaijun** [comment]
@cjfan  you can try mxnet.cpp this project is c++ wrapper of mxnet
https://github.com/dmlc/mxnet.cpp

**Comment by cjfan** [comment]
Thank you, the OpWrapperGenerator.py seem like a good way and can have a Lua version.
Now, I just want to have some try in our progrom, and benefit from fast iteration of script and data exchange online, I have find a work around from https://github.com/bastibe/lunatic-python.
By building a dll to be requied in lua and communicate with python, I think it can meet my need in a short term.

**Comment by tqchen** [comment]
@qiaohaijun a possible interface to lua is more than welcomed.
