### ISSUE TITLE
Cannot find node slicechannel1's 29-th output

### ISSUE THREAD

**Issue by lightingghost** [dmlc/mxnet#2257]
If I create a slicechannel with 30 outputs, and I only use 29 of them, the runtime checking will give an error of:

`
/home/odin/local/mxnet/dmlc-core/include/dmlc/logging.h:235: [14:38:09] src/symbol/static_graph.cc:502: Check failed: it != grad_map.end() bad graph: Cannot find node slicechannel1's 29-th output
`

I don't know whether it is designed to behave like that or not, but it seem to me that it should be legal to use only part of the slicechannel output.

**Comment by tornadomeet** [comment]
would you give the minimize code to produce it?

**Comment by piiswrong** [comment]
You have to use all of them, otherwise on backward the last one won't have gradient from above.
You can feed the last one to blockGrad and group it with the original output

**Comment by lightingghost** [comment]
Thanks. I have figured out a trick to solve it.

**Comment by jiumem** [comment]
@lightingghost I meet a seem problem as you. How did you do it?

**Comment by lightingghost** [comment]
@jiumem I multiply the output that I haven't used by a vector and add the result to the loss..
