### ISSUE TITLE
InferType for simple op (for types other than Float32)

### ISSUE THREAD

**Issue by vchuravy** [dmlc/mxnet#2260]
InferType fails for NDarray with element type other than `Float32`. In https://github.com/dmlc/mxnet/blob/f5f18b2297c581bb53bdaf1e407151f91336675d/include/mxnet/operator.h#L265, while https://github.com/dmlc/mxnet/blob/e63f7a6d0065f6b2d5fae71fd5d5ff70786b0d20/src/operator/elementwise_binary_op-inl.h#L22 seems to indicate that it supports all DTypes that mshadow supports.

**Comment by piiswrong** [comment]
@tqchen Why was there a check?

**Comment by tqchen** [comment]
I think this was mainly designed when most operators do not support other types, we can remove that check as long as the bindEx is used

**Comment by vchuravy** [comment]
@piiswrong The problem is that the default `InferType` makes the assumption that `input_type` and `out type` are all `Float32`. Whereas simple op requires that `input_type == out_type` so just dropping the check doesn't solve the problem.

I think the correct way of handling this is to require all ops to implement `InferType` and no longer rely on the implicit assumption that `Float32` is correct.

**Comment by piiswrong** [comment]
A default InferType that assumes uniform type for all input/output should work for most cases
