### ISSUE TITLE
Memory error when iterating over HDF5 file

### ISSUE THREAD

**Issue by guileryu01** [dmlc/mxnet#2264]
I have training data saved in an HDF5 file of a few GB. The size is too big to fit into a numpy array in memory, so I wrote a DataIter class that takes h5py Dataset object and getdata method just returns a slice of it based on batch size. It is almost the same as how NDArrayIter works, except that it doesn't load the entire data into memory upfront.

When I pass this iterator to model.fit and run training with it, the memory consumption continuously grows until I get the memory error. I was suspecting some other objects are holding referencess to the Databatches and preventing them from garbage collected, but is not clear to me what those could be. I also tested my DataIter outside of training by just iterating over the entire Dataset, for which I don't see uncontrolled memory growth. Any suggestions no where I should check more closely?

Or I would appreciate any suggestions on alternative approach to work with large HDF5 dataset.

**Comment by sxjscience** [comment]
Have you tested random iteration over the whole HDF5 file?

**Comment by guileryu01** [comment]
Yes, I tested both with and without random shuffle and the result is the same.

**Comment by guileryu01** [comment]
I did some further tests and got very puzzled by the results. It turns out that this has nothing to do with hdf5 file at all, but the memory problem only occurs for deeper networks. I tried to strip the part of training code that is relevant to this problem to reproduce, and here is what I've got:


```

import logging
import mxnet as mx
import numpy
import win32process
from   mxnet.executor_manager import _bind_exec
from   mxnet.ndarray import array

def get_symbol( nDepth = 3):
    data        = mx.symbol.Variable( 'data', shape = ( 40, 28, 28 ) )
    for i in xrange( nDepth - 1 ):
        data    = mx.symbol.Convolution( data = data, kernel = ( 3, 3 ), pad = ( 2, 2 ),
                                         num_filter = 128 )
        data    = mx.symbol.Activation( data = data, act_type = 'relu' )
    collapsed   = mx.symbol.Convolution( data = data, kernel = ( 1, 1 ), num_filter = 1 )
    flatten     = mx.symbol.Flatten( data = collapsed )
    softmax     = mx.symbol.SoftmaxOutput( data = flatten, name = 'softmax' )
    return softmax

def run():
    batch_size  = 32
    nPlane      = 40
    nDepth      = 4
    #nDepth      = 3
    width       = 28
    height      = 28
    symbol      = get_symbol( nDepth )

    param_names = [ name for name in symbol.list_arguments() if name not in [ 'data', 'softmax_label' ] ]
    data_shapes = { 'data'          : (batch_size, nPlane, width, height),
                    'softmax_label' : (batch_size,)}
    train_exec  = _bind_exec( symbol, mx.cpu(), data_shapes, param_names,
                             need_grad=True, base_exec=None,
                             shared_data_arrays={})
 
    logging.getLogger().setLevel( logging.INFO )
    for i in xrange( 200 ):
        data_source     = array( numpy.random.binomial(1,0.5, batch_size * nPlane * width * height ).reshape( batch_size, nPlane, width, height ) )
        label_source    = array( numpy.random.choice( width * height, batch_size ) )
        data_source.copyto( train_exec.arg_dict[ 'data' ] )
        label_source.copyto( train_exec.arg_dict[ 'softmax_label' ] )
        train_exec.forward(is_train=True)
        memUsed         = float( win32process.GetProcessMemoryInfo(-1)[ 'PagefileUsage' ] ) / ( 1024. * 1024. )
        logging.info( 'Memory used: %s MB' % memUsed )

if __name__ == '__main__':
    run()

```

When I run the above code, I see uncontrolled memory consumption growth. However, if I change the number of convolutional layers nDepth to 3, everything is ok. What am I missing here? Is there anything wrong with the way my symbol is generated?

**Comment by sxjscience** [comment]
I've run the code and I can confirm that the memory keeps increasing. Also, no such problem if I bind the executor in GPU. It seems that `data_source` and `label_source` haven't deallocated automatically. @piiswrong @tqchen

**Comment by tqchen** [comment]
could due to the async loop. Try to add train_exec.output[0].wait_to_read() or add a copyto to copy data out

**Comment by guileryu01** [comment]
Thanks, I will test that tonight when I get hold of my pc. However, if the problem is due to async loop, why does it take unlimited memory? E.g., for a longer loop this script will run out of memory, like the one in my training case. Also I still need the async loop for the benefit of parallelization.

**Comment by guileryu01** [comment]
Indeed, the memory problem goes away by waiting for each minibatch to finish. Any recommended way to balance data feeding and network evaluation from training api?
