### ISSUE TITLE
[R] how to train model with mutli-input

### ISSUE THREAD

**Issue by rogerchen1226** [dmlc/mxnet#2266]
Hello,
I try almost a week still cannot find the solution, please give me some guide.
I'm trying to do input two data to do the different layer, I follow the tutorial code like:
`data<- mx.symbol.Variable("data")`
`net <- mx.symbol.FullyConnected(data=data, name="fc1", num_hidden=2)`
`data2<- mx.symbol.Variable("data2")`
`net2 <- mx.symbol.FullyConnected(data=data2, name="net2", num_hidden=2)`
`con <- list(net,net2)`
`con$num.args = 2`
`concat <- mxnet:::mx.varg.symbol.Concat(con)`
`soft<- mx.symbol.SoftmaxOutput(data=concat)`
print graph didn't see two inputs
`print(graph.viz(soft$as.json()))`
if this is right, what should I write the model X with two input data?
`mx.model.FeedForward.create(soft, X=???,y=???)`
and I try another way to do,
input  one data which combine all different data and try to separate them by their type, than do the each layer, But I don't know what function can do it. How can I implement this? 
Thank you very much!

**Comment by thirdwing** [comment]
I am so sorry I don't have time to finish this now. It is the same with https://github.com/dmlc/mxnet/issues/1269

**Comment by rogerchen1226** [comment]
@thirdwing  Thanks for your reply. I got it.
Did the Python library work for that?  
Thanks.

**Comment by qiaohaijun** [comment]
the python framework is for single input and single output

**Comment by rogerchen1226** [comment]
@qiaohaijun  thanks for your information.
I think I should try the other way like one single input and separate them by the rule, then do the layers.
Is it possible to make it? I try the `mx.slice.channel`, it seem to like duplicate the data. Not I want.
Any suggestions? 
Very Thankful!

**Comment by tmatas** [comment]
@qiaohaijun I recently had an issue about using a model with two outputs. 
Are there any plans to extend the python framework to MIMO systems?

**Comment by thirdwing** [comment]
I think this can be fixed by #6673
