### ISSUE TITLE
The training accuracy is not shown in 'mx.model.FeedForward.fit' ?

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#2267]
I just use numpy array to train a feedforward model without eval data. I wonder why the training accuracy is not shown in logs?

The log looks like this:
```
INFO:root:Start training with [gpu(0)]
INFO:root:Epoch[0] Resetting Data Iterator
INFO:root:Epoch[0] Time cost=54.835
INFO:root:Epoch[1] Resetting Data Iterator
INFO:root:Epoch[1] Time cost=50.008
```

**Comment by piiswrong** [comment]
you need to set batch_end_callback. Look into mx.callback to see options
