### ISSUE TITLE
[R] Take care of the input type of mx.nd.array in the R's interface

### ISSUE THREAD

**Issue by hetong007** [dmlc/mxnet#227]
In the R's interface, I suggest to wrap up the `as.array` operation in `mx.nd.array`, so users can simply write

```r
mat = mx.nd.array(1:10, mx.cpu(0))
mat = mx.nd.array(matrix(1:4,2,2), mx.cpu(0))
```
instead of 
```r
x = as.array(c(1,2,3))
mat = mx.nd.array(x, mx.cpu(0))
```
in the current demo like https://github.com/dmlc/mxnet/blob/master/R-package/demo/basic_ndarray.R.

**Comment by tqchen** [comment]
@thirdwing I think we can do a type version check in rcpp side?

**Comment by tqchen** [comment]
I now started to think that we should do such change on R's side as rewrap the mx.nd.array is fairly easy from R's side. Let us move ```mx.nd.array``` to ```mx.nd.internal.array``` and create the wrapper as tong suggested.

@hetong007 Can you do that? You only need to change https://github.com/dmlc/mxnet/blob/master/R-package/src/ndarray.cc#L387 On cpp side to mx.nd.internal.array

**Comment by hetong007** [comment]
I think so. I think I will modify things tmr, e.g. travis ci, this wrapper and the symbolic ones.

**Comment by tqchen** [comment]
Great. thanks tong
