### ISSUE TITLE
I wonder if there is a trained caffe model using mxnet.

### ISSUE THREAD

**Issue by Geekking** [dmlc/mxnet#2274]
Currently, I want to use alexnet for finetuning, but I could not find any trained model under mxnet. What's more, I have try to convert the caffe_net from the caffe, but the code provided by mxnet seems doesnot work in these files. Could anybody uploading an alexnet model that can be use in mxnet?
Thanks.

**Comment by antinucleon** [comment]
Check: https://github.com/dmlc/mxnet-model-gallery
And: https://github.com/dmlc/mxnet/tree/master/tools/caffe_converter

**Comment by Geekking** [comment]
@antinucleon the model gallery currently does not provide the Alexnet model, and the caffe_converter doesn't work with the `bvlc_reference_caffenet.caffemodel`. I decide to use the vgg16 model,. Thanks.
