### ISSUE TITLE
mxnet prints weird output

### ISSUE THREAD

**Issue by ianxxiao** [dmlc/mxnet#2276]
Hi there - for some reasons, mxnet is printing out weird output like this. It fills "why" in spaces ... anyone know why and how to fix this?

```
model <- mx.model.FeedForward.create(softmax, X=train.x, y=train.y,
                                     ctx=devices, num.round=10, array.batch.size=100,
                                     learning.rate=0.07, momentum=0.9,  eval.metric=mx.metric.accuracy,
                                     initializer=mx.init.uniform(0.07),
                                     epoch.end.callback=mx.callback.log.train.metric(100))

```
![image](https://cloud.githubusercontent.com/assets/5623823/15633852/f9daa620-2584-11e6-8f19-03e83891e2d9.png)

**Comment by piiswrong** [comment]
@antinucleon Seems like your debug print...

**Comment by antinucleon** [comment]
I can't remember it? It looks like in R package, could you please remove
it? I don't have access to computer now.
On Sun, May 29, 2016 at 10:28 Eric Junyuan Xie <notifications@github.com>
wrote:

> @antinucleon <https://github.com/antinucleon> Seems like your debug
> print...
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2276#issuecomment-222372297>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13meLLz3p00qjB2MUJmejU5dJMgUhks5qGczTgaJpZM4IpTBA>
> .
>
-- 
Sent from mobile phone

**Comment by antinucleon** [comment]
@piiswrong I can't locate the debug string, so probably it is not mine.

**Comment by antinucleon** [comment]
@thirdwing Could you take a look?

**Comment by thirdwing** [comment]
This has been fixed four weeks before. So please use the latest version.
