### ISSUE TITLE
Running on multi-gpu is slower than single gpu

### ISSUE THREAD

**Issue by xlvector** [dmlc/mxnet#2277]
I find for some tasks, using multi-gpu will be slower than single GPU. What may be the main reason for this?

For example. I try to use mxnet to solve image caption problem. I find two strange results:

1. using large batch size (100) will be much slower than small batch size (4)
2. using 4 GPU will be much slower than use 1 GPU.

I other tasks, I does not find similar phenomenon.

**Comment by piiswrong** [comment]
It depends on computation to parameter ratio. Basically conv layers are good for multi gpu, fully connected layers are bad

**Comment by xlvector** [comment]
Is this because reduce speed is slow when parameter is too large?

**Comment by qiaohaijun** [comment]
you should find the bottleneck of your task. for example, I find that the alexnet is not suitable for multi gpu but inception is suitable

**Comment by xiangqiaolxq** [comment]
maybe network is a bottleneck.Also some times the computer is not stable,one or more gpus work slow in a while time and use synchronize way to update parameter. (I/O rate and  unstable power supply)

**Comment by xlvector** [comment]
Yes, I do nvprof and find most time are cost on reduce. Increase batch size will reduce this time.
