### ISSUE TITLE
Having problems with CUDA=1 on El Capitan 10.11.2

### ISSUE THREAD

**Issue by wave-electron** [dmlc/mxnet#2287]
I've have mxnet working fine with USE_CUDA=0

However, I recently setup an external GPU on my mac mini and wanted to reconfigure with the eGPU. The eGPU is installed and coming up in systems report -> graphics/Displays as a second video card. 

NVIDIA Chip Model:

  Chipset Model:	NVIDIA Chip Model
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x4
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x17c8
  Revision ID:	0x00a1
  ROM Revision:	preset 1.0.0

I've installed CUDA Toolkit 7.5

I've modified my osx.mk file with the following CUDA flags.

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
 USE_CUDA_PATH = /usr/local/cuda

I do a make clean

then make 

I've also reinstalled my python package after doing all this. 

But I'm stilling getting errors that CUDA is not compiled when running a script. 

This is also the initial output from running make

g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I/usr/local/mxnet/mshadow/ -I/usr/local/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv`  -DMXNET_USE_NVRTC=0 -MM -MT build/src/resource.o src/resource.cc >build/src/resource.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/usr/local/mxnet/mshadow/ -I/usr/local/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv`  -DMXNET_USE_NVRTC=0 -c src/resource.cc -o build/src/resource.o
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I/usr/local/mxnet/mshadow/ -I/usr/local/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv`  -DMXNET_USE_NVRTC=0 -MM -MT build/src/c_api/c_api.o src/c_api/c_api.cc >build/src/c_api/c_api.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/usr/local/mxnet/mshadow/ -I/usr/local/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv`  -DMXNET_USE_NVRTC=0 -c src/c_api/c_api.cc -o build/src/c_api/c_api.o

**Comment by piiswrong** [comment]
you need to copy your modified osx.mk to root as config.mk, like this:
cp make/osx.mk config.mk

**Comment by wave-electron** [comment]
Thank you for the help. 

Do you know if mxnet with external GPU is working on El Captian 10.11.2 ?

I've noticed a few threads where others seem to be having compiling issues like me... but didn't see any definitive roadmap for getting this working. 

I've been using this how-to for installing my external GPU. 

[tutorial step 1](http://udibr.github.io/using-external-gtx-980-with-macbook-pro.html)  (read this one first)
[tutorial step 2 with automated script](http://udibr.github.io/using-external-gtx-980-with-macbook-pro-and-el-capitan.html)

To get my external GPU (NVIDIA GTX 980 Ti) working on a thunderbolt port... I used automate-eGPU which is an automated script for setting up external GPU's on OSX. 

[](https://github.com/goalque/automate-eGPU)

The only hassle was Mac's built in security, which means you have to 
`reboot into recovery, disable csrutil, reboot into OSX, install the script, reboot into recovery, enable csrutil, reboot into OSX:`

But after doing all that the external GPU install seem to work because my  NVIDIA GTX card is detected by OS  This Mac->System Report...->Hardware->Graphics/Displays

I also installed the CUDA 7.5 toolkit, following this how-to

https://www.quantstart.com/articles/Installing-Nvidia-CUDA-on-Mac-OSX-for-GPU-Based-Parallel-Computing

however, after carrying out some tests   ./deviceQuery

I got the following error

 ```
CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL
```
So at this stage I need to try and find out why my CUDA install failed first and then re-try again.

**Comment by wave-electron** [comment]
I've solved all my CUDA install problems!
```
./deviceQuery
./bandwidthTest

both pass OK
```
I had to reinstall my NVIDIA driver again using the automated script I mentioned earlier. https://github.com/goalque/automate-eGPU

Can anyone help me with configuring these flags in osx.mk ?

```
 CUDA_PATH= 
ADD_LDFLAGS = 
ADD_CFLAGS = 
```

I have installed the CUDA 7.5 toolkit and the path is:

`/Developer/NVIDIA/CUDA-7.5`

I also have CUDA files in

`/usr/cuda/lib`

I've read all the relevant threads on here, but still unsure about what these should be set to.

**Comment by wave-electron** [comment]
Finally got it to work with USE_CUDA = 1

The configuration did have alot of warnings but I had these flags still set to 0

`# whether use CUDNN R3 library
USE_CUDNN = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iteraor
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

In the end I setup my osx.mk  following this as a guide https://github.com/dmlc/mxnet/issues/843
