### ISSUE TITLE
different batch size for different GPUs

### ISSUE THREAD

**Issue by neiledgard** [dmlc/mxnet#2293]
I am running a network in parallel on 2 GPUs. The GPUs and therefore their performances differ, and when training a network, the batch size is (assumedly) distributed evenly amongst the cards. When the faster card finished its current batch, it waits for the other card to finish.

Is there a way to assign different batch sizes for GPU 0 and 1, so that I can maximize their performance?
Thanks!

**Comment by piiswrong** [comment]
There is a work_load_list param that does this
