### ISSUE TITLE
is there concept about multiplecpu in mxnet

### ISSUE THREAD

**Issue by liumilan** [dmlc/mxnet#2296]
As we know, there is concept about multiplegpu in mxnet,when specify -gpu in command.And if we don't specify gpu,it will run it on cpu.How many cpus do it run ?Can it possible to specify multiple cpu?

**Comment by antinucleon** [comment]
On CPU, OpenBLAS usually will occupy all CPU cores. In MXNet, engine will occupy one or two cores, and OpenBLAS will take all remained.

**Comment by qiaohaijun** [comment]
blas is a good tool
