### ISSUE TITLE
Supported version of cuDNN is out of date in docs

### ISSUE THREAD

**Issue by alexwan2011** [dmlc/mxnet#2298]
Hi,

I just noticed that the instruction of how to build mxnet in both [github](https://github.com/dmlc/mxnet/blob/master/docs/how_to/build.md) and [mxnet.readthedocs.io](http://mxnet.readthedocs.io/en/latest/get_started/) say only cuDNN V3 is supported, which I believe cuDNN V3, V4 and the latest V5 can work well with mxnet. 

I found related questions in [pull#1466](https://github.com/dmlc/mxnet/pull/1466) and [issue#2216](https://github.com/dmlc/mxnet/issues/2216), so maybe the docs can be updated, in case there will be some confusion for beginners.

Thanks!

**Comment by piiswrong** [comment]
Thanks for pointing out this. Would you like to propose a PR?

**Comment by alexwan2011** [comment]
Sure. Just proposed.

**Comment by marugari** [comment]
This page also says MXNet support only cuDNN v3.
https://developer.nvidia.com/deep-learning-frameworks
