### ISSUE TITLE
Questions about KVStoreDistServer

### ISSUE THREAD

**Issue by feiyulv** [dmlc/mxnet#2301]
When running mxnet on multiple nodes, mxnet should divide models into several parts, each server maintains only one part of the original model. However when I run mxnet on two nodes, the value of  req_data.lens[0]  equals to the size of each layer, I expected it should be divided by 2. Did I misunderstand something? I used the following command to run the example:
python launch.py  -n 2 --launcher ssh -H hosts python test.py --kv-store dist_sync

**Comment by feiyulv** [comment]
I add "-s 2" to the command, but no difference

**Comment by feiyulv** [comment]
I add "-s 2" to the command, but no difference

**Comment by feiyulv** [comment]
I add "-s 2" to the command, but no difference

**Comment by feiyulv** [comment]
I add "-s 2" to the command, but no difference

**Comment by feiyulv** [comment]
@mli l

**Comment by qiaohaijun** [comment]
mxnet does not divide model into serveral parts. You can think that you have more replica of model to run.

**Comment by mli** [comment]
for a parameter, e.g. the weight for a layer, if its size is less than MXNET_KVSTORE_BIGARRAY_BOUND, we randomly assign it to a node. otherwise, we evenly divided it to multiple nodes.

**Comment by feiyulv** [comment]
thx @mli @qiaohaijun
