### ISSUE TITLE
Adaptive make command in docs

### ISSUE THREAD

**Issue by koallen** [dmlc/mxnet#2304]
Hi all,

I've noticed that the `make` command in various docs sets the number of threads as a hardcoded number, such as `-j8` or `-j4`. In my opinion, this is not very effective when we have different core counts  on different machines. I think we should instead use `make -j$(nproc)` which sets the number of threads according to the processor core count on the machine. I've used it on linux based machines and it works fine.

What do you guys think?

**Comment by qiaohaijun** [comment]
good idea!

**Comment by mli** [comment]
good idea. but it doesn't work on mac

**Comment by koallen** [comment]
Yeah, that's true. For Mac we need to use `sysctl -n hw.ncpu`. I don't know if you think this would complicate the compilation steps. Anyway, I think at least we can change the Dockerfiles for MXNet, since docker can only run in Linux.

**Comment by mli** [comment]
totally agree we can update the dockfile. we may also mention to use
-$(npoc) for linux for best compilation performance in docs. can you please
make a PR for it?

**Comment by koallen** [comment]
Sure, no problem. I'll make a PR later. Have you tried `make -j$(sysctl -n hw.ncpu)`? Does it work? I think Homebrew uses that to detect the number of cores.

**Comment by mli** [comment]
yeah, $(sysctl -n hw.ncpu) works well on my mbp with os x 10.11.4
