### ISSUE TITLE
Integrate with baidu warp-ctc

### ISSUE THREAD

**Issue by xlvector** [dmlc/mxnet#2305]
I want to integrate mxnet with warp-ctc https://github.com/baidu-research/warp-ctc .

I find that, warp-ctc only provide one interface called:

ctcStatus_t compute_ctc_loss(const float* const activations,
                             float* gradients,
                             const int* const flat_labels,
                             const int* const label_lengths,
                             const int* const input_lengths,
                             int alphabet_size,
                             int minibatch,
                             float *costs,
                             void *workspace,
                             ctcComputeInfo info);

For CTC Loss layer, its forward is same as Softmax. The only difference is calculate grad in backward.

I find in mshadow/tensor_c(g)pu-inl.h , there is SoftmaxGrad. So, I think the easiest way to do this is implement an CTCGrad and use this in backward function to calculate grad.

This is my main idea. But I do not know how to do it in detail. For example, mxnet use expression template, but warp-ctc is different. So, how can I mix them together?

**Comment by xlvector** [comment]
Another way may be write an python layer to use ctypes to call libwarpctc.so according to http://mxnet-tqchen.readthedocs.io/en/latest/how_to/new_op.html

However, I hope I can use mshadow to integrate it.

**Comment by tqchen** [comment]
Since it is from C++, the best way will be integrate from c++.

The expression template is not a must for mxnet, but rather a convenient way to do so. The TBlob support directly fetching out raw pointers, and from there there is not much difference of writing a kernel. See the implementations of calling CuDNN kernels might help

**Comment by antinucleon** [comment]
see ROI pooling will be more helpful.
On Wed, Jun 1, 2016 at 09:31 Tianqi Chen <notifications@github.com> wrote:

> Since it is from C++, the best way will be integrate from c++.
>
> The expression template is not a must for mxnet, but rather a convenient
> way to do so. The TBlob support directly fetching out raw pointers, and
> from there there is not much difference of writing a kernel. See the
> implementations of calling CuDNN kernels might help
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2305#issuecomment-223049537>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13n_JajIts6S8hcgL7yshvU3FsH9Uks5qHbPkgaJpZM4IrRnq>
> .
>
-- 
Sent from mobile phone

**Comment by tqchen** [comment]
see http://mxnet.dmlc.ml/en/latest/system/operator_util.html

**Comment by piiswrong** [comment]
This can be done as a plugin. Check plugin/torch for example

**Comment by xlvector** [comment]
Thanks all, I will try your suggestions today!

**Comment by xlvector** [comment]
When I get int labels, I use following code:

TBlob label = in_data[warpctc_enum::kLabel];
int* flat_labels = static_cast<int*>(label.dptr_);

However, I find label is always a float array, only 

float *flat_labels = static_cast<float*>(label.dptr_)

return right results.

When I pass data in DataIter, I use 

label_all = [mx.nd.array(label, dtype = np.int32)]

but it does not work. Label is alwarys a float array...

**Comment by piiswrong** [comment]
you need to add a InferType function to your operator property to specify the type of your input/output. and you need to bind your input to the right type

**Comment by piiswrong** [comment]
@tqchen @antinucleon @pluskid currently module doesn't support specifying type. adding a data_type is probably not a good solution since there will be data_ctx for model parallel support.
Should we change data_shapes to (name, shape, type, ctx)? However the name data_shapes is miss leading.
Is a noncompatible change to data_info acceptible?

**Comment by pluskid** [comment]
I am personally ok with this change, or maybe keep both fields and if info is available use info first? Although it do feel a little bit strange to ask the data iter to specify the context.

**Comment by tqchen** [comment]
I think we should not change the data_shapes. 

Instead, trying to specify the type in a similar way as context, or either via a seperate mapping or attributes in graph might be a better idea
