### ISSUE TITLE
Questions on the C++ code of graph_executor.cc

### ISSUE THREAD

**Issue by zjubxl123** [dmlc/mxnet#2315]
I have a question with the following code:
void GraphExecutor::InitDataEntryInfo(const std::vector<NDArray> &in_args,
                                      const std::vector<NDArray> &arg_grad_store,
                                      const std::vector<OpReqType> &grad_req_type,
                                      const std::vector<NDArray> &aux_states) {
......
      StaticGraph::DataEntry &grad_source = arg_grads_[i];
      DataEntryInfo &info = op_nodes_[grad_source.source_id].outputs[grad_source.index];
      info.type = kBindByExternal;
      info.op_req = grad_req_type[i];
      info.data = arg_grad_store[i];

...}

the arg_grad_store is used to store the gradients of the model parameters and should be changed by the operators after each iteration. So, why the input arguments "&arg_grad_store" of the above function is of const type, which means no data can be written to it?

**Comment by thirdwing** [comment]
`InitDataEntryInfo` is for initialization, right?

**Comment by piiswrong** [comment]
the vector is const. it's contents are not
