### ISSUE TITLE
Efficiency of stacking symbols

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#2316]
Currently we can achieve the `broadcast_plus` functionality by two ways. The first is to use the built-in C++ operator and the second is to manually broadcast the input using `broadcast_axis` and then use the original add OP. Will the second solution be much slower? I previously thought that the symbol side would also benefit from the expression template and there might not be much performance loss.

**Comment by piiswrong** [comment]
It will use more memory because need to store the boardcasted array. Also can be slower because of one more read/write to the main ram
