### ISSUE TITLE
mx.symbol.Variable shape specification

### ISSUE THREAD

**Issue by novog** [dmlc/mxnet#2318]
The mx.symbol.Variable class constructor accepts a "shape" parameter:

>shape : tuple
>Optionally, one can specify the shape of a variable. This will be used during
>shape inference. If user specified a different shape for this variable using
>keyword argument when calling shape inference, this shape information will be ignored.

This parameter is not working for me. Using the following Python code:

    input_x = mx.symbol.Variable('data')
    input_y = mx.symbol.Variable('softmax_label', shape=(100L, 2L))
    h1 = mx.symbol.FullyConnected(data=input_x, name='h1', num_hidden=2)
    net = mx.symbol.SoftmaxOutput(data=h1, label=input_y, name='softmax_output')
    print(net.infer_shape(data=(100L,2L)))

The last line produces the following error at line 513 in _infer_shape_impl:

>MXNetError: Invalid Parameter format for `__shape__` expect Shape(tuple) but value='(100L, 2L)'

The constructor of Variable appears to be saving `__shape__` as a string, rather than as the actual value that it received:

    attr['__shape__'] = str(shape)

Should Variable be saving the actual shape rather than the string, or am I doing something wrong? Thanks!

**Comment by piiswrong** [comment]
(100, 2)
get rid of the L

**Comment by novog** [comment]
Okay, that works. I had been using the long suffix because in python 2.7, that is what I get back from functions like infer_shape. Thanks!

**Comment by induparkavi** [comment]
I installed R version 3.3.2. and installed mxnet from cran. But I get error.

>install.packages("drat", repos="https://cran.rstudio.com")
> drat:::addRepo("dmlc")
> install.packages("mxnet")
> library(mxnet)
data <- mx.symbol.Variable('data')
Error: could not find function "mx.symbol.Variable"
what to do?

**Comment by novog** [comment]
In python, it is common to alias the mxnet package as "mx". I don't use R, but I don't see you doing so in your code; try using "mxnet" instead of "mx". If that isn't the problem, you should probably create a separate issue, since this issue was on an unrelated matter and is already closed.
