### ISSUE TITLE
InferShape Error in conv_conv1

### ISSUE THREAD

**Issue by kvazipushka** [dmlc/mxnet#2324]
Hello everyone! 

I'm trying to create inception-bn network and  train on my pictures dataset using R language (RStudio, windows 10). But when I call mx.model.FeedForward.create I recieve following message: 
`[17:32:06] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:241: [17:32:06] d:\chhong\mxnet\src\operator\./convolution-inl.h:337: Check failed: ksize_x <= dshape[3] && ksize_y <= dshape[2] kernel size exceed input
Error: InferShape Error in conv_conv1: [17:32:06] d:\chhong\mxnet\src\operator\./convolution-inl.h:337: Check failed: ksize_x <= dshape[3] && ksize_y <= dshape[2] kernel size exceed input`

The steps to reproduce are following: 
1) I create imgrec.rec file using python im2rec.py (provided in mxnet/tools/ as described in http://mxnet-tqchen.readthedocs.io/en/latest/packages/python/io.html#before-you-start) with a command ./bin/im2rec image.lst image_root_dir output.bin resize=256 
2) I create iterator over images with command: 
`val <-  mx.io.ImageRecordIter(
  path.imglist = 'datadir/image_list.lst',
  path.imgrec = 'datadir/imgrec.rec',
  mean.r      = 123.68,
  mean.g      = 116.779,
  mean.b      = 103.939,
  data.shape  = c(3,256,256),
  batch.size  = 32)`
3) I create network structure of inception-bn (i rewrote in R mxnet/example/image-classification/symbol_inception-bn.py) with 172 classes, where 172 is number of classes of my images. 
4) Now I try to call: 
`model3 <-  mx.model.FeedForward.create(
  symbol = sym,
  X = val,
  ctx = mx.cpu(),
  eval.metric = mx.metric.accuracy,
  learning.rate = 0.1,
  momentum = 0.9,
  wd = 0.00001,
  array.batch.size = 32,
  batch.end.callback = mx.callback.log.train.metric(50))`
where sym is a structure, created in 3). And I get error message, descrided above. 

With a debug I figured out that a problem is in the following code: 
`input.shape <- dim((val$value())$data)

slist <- mx.symbol.infer.shape(sym, data = input.shape)`

Could please anyone suggest, how to correct this problem? 
Thanks in advance.

**Comment by piiswrong** [comment]
@thirdwing

**Comment by thirdwing** [comment]
@kvazipushka Can you share your code to reproduce this error?

**Comment by thirdwing** [comment]
Close this for now. Feel free to reopen.
