### ISSUE TITLE
How to load ndarray directly to a specific device?

### ISSUE THREAD

**Issue by JeffDong** [dmlc/mxnet#2330]
I think nd.save method also saves the device information is unreasonable. In my case, when I train a model at gpu(7) on a server with 16 gpus, save all params, and load them to my desktop which has only one gpu, I will get a invalid device error.
I know I can just copy to cpu --> save --> load to cpu--> copy to gpu, but it's not the best solution I think..
Is there a simpler way to load ndarrays directly to a device? If not I suggest that you could add this load to device function which is simple but useful.

**Comment by Godricly** [comment]
if u r trying to create a ndarray on a specific gpu, you can follow ndarray Creation in this [link.](http://mxnet.readthedocs.io/en/latest/packages/python/tutorial.html)
