### ISSUE TITLE
Bind is quadratic in number of nodes in the graph (and it doesn't need to be)

### ISSUE THREAD

**Issue by SkidanovAlex** [dmlc/mxnet#2333]
Hi,
I noticed that my models are very slow to bind. I traced it to the toposort of backward nodes in `GraphExecutor::InitGraph`, which I found to be taking quadratic times, which for my graphs of 100K nodes was several minutes. The issue is so simple it will take me more effort to create the PR than for you guys to just push it.

      [=](uint32_t n)->uint32_t {  // InDegree
        if (finished.count(n) == 1) { return 0; }
        const StaticGraph::Node& node = graph_.nodes[n];
        return node.inputs.size() + static_cast<uint32_t>(node.is_backward());
      },
      [=](uint32_t n, uint32_t index)->uint32_t {  // GetInput
        const StaticGraph::Node& node = graph_.nodes[n];
        if (index < node.inputs.size()) {
          return node.inputs.at(index).source_id;
        } else {
          return node.backward_source_id;
        }

These lambdas are capturing everything they use by value and not changing it. In particular, they are capturing `finished` by value, and the entire `graph_` by value, and both of them have linear length.

**Both `[=]` captures need to be replaced with `[&]`.**

(also, the fact that my graph has 100K nodes is probably also a bug, I will open a separate bug and/or PR when I get to the cause of it)

**Comment by SkidanovAlex** [comment]
Same bug is in `std::vector<uint32_t> StaticGraph::PostDFSOrder`

**Comment by piiswrong** [comment]
@tqchen Could you fix it?

**Comment by tqchen** [comment]
I am traveling so cannot touch the code. cc @mavenlin on this issue

**Comment by mavenlin** [comment]
fixed in https://github.com/dmlc/mxnet/pull/2335
