### ISSUE TITLE
CNN for Text -- Reshape(), Flatten() issues

### ISSUE THREAD

**Issue by bdlacree** [dmlc/mxnet#2339]
Hello again --- 

I am training a CNN for a text classification task. I have documents, each with a maximum n_words, and I am calling pretrained word2vec vectors of dimension D for each word.

I am trying to pass documents to the network, which are (padded to) n_words by D. I am only using one type of embedding, so I only have one channel.

Unlike the canonical MNIST examples, I want the convolutions to happen over words taken over the entire word2vec embedding width D. If I try to set the kernel=c(5,D), though, I get the error: "kernel size exceed input". If I instead pass kernel=c(5,D,1,1), the code runs without error.

Is this the way to make sure that the kernel is being taken over a window of words (i.e., 5 words) but over all 100 dimensions of the word embedding vectors? Or am I seriously misunderstanding how to pass data to the CNN?

Thanks!

**Comment by tqchen** [comment]
https://github.com/dmlc/mxnet/tree/master/example/cnn_text_classification this example might be quite related

**Comment by bdlacree** [comment]
Thanks! That is related. I've been basing my model on the one in that example. In fact, I basically just copied it and changed the python conventions to R. 

Here's the issue I'm having: when I get to the 

```
total_filters = num_filter * length(filter_list)
concat = mx.symbol.Concat(pooled_outputs, num.args=length(filter_list), dim=1)
h_pool = mx.symbol.Reshape(data=concat, target_shape=c(batch_size, total_filters))
```

The last line, using Reshape(), gives me an error, `from.shape() == to->shape() operands shape mismatch` I've tried changing the arguments to the Reshape() and nothing works.

If, instead, I use the `mx.symbol.Flatten(concat)` (as in the MNIST examples), the model will run, but the results are also way off. But that could just be my data or the untuned model parameters.

I can't seem to find what "Flatten" is doing, or if it's accomplishing what the text classification example was trying to do with Reshape(). If not, how do I use Reshape() correctly? 

If it's helpful, here's the model code. The input data is an array, 50 (sentence length) by 300 (word2vec embeddings) by 1 (channel) by 30000 (training samples). The target is dichotomous. 

```
# fit the CNN
library(mxnet)
pooled_outputs = c()
sent_length = 50
data = mx.symbol.Variable("data")
filter_list = c(3,4,5); 
batch_size=100; 
num_filter=100
for(f in 1:length(filter_list))
{
  convi = mx.symbol.Convolution(data=data, kernel=c(filter_list[f],300),num_filter=num_filter)
  relui = mx.symbol.Activation(data=convi, act_type='relu')
  pooli = mx.symbol.Pooling(data=relui, pool_type='max', kernel=c((sent_length-filter_list[f]+1),1))
  pooled_outputs = c(pooled_outputs,pooli)
}
total_filters = num_filter * length(filter_list)
concat = mx.symbol.Concat(pooled_outputs, num.args=length(filter_list), dim=1)
#h_pool = mx.symbol.Reshape(data=concat, target_shape=c(100, total_filters)) # Doesn't work?
h_pool = mx.symbol.Flatten(data=concat)
h_drop = mx.symbol.Dropout(data=h_pool,p=0.2)
fc1 = mx.symbol.FullyConnected(data=h_drop, num_hidden=100)
act1 = mx.symbol.Activation(fc1,act_type='sigmoid')
drop1 = mx.symbol.Dropout(act1,p=0.2)
fc2 = mx.symbol.FullyConnected(drop1, num_hidden=2)
# softmax output
sm = mx.symbol.SoftmaxOutput(data=fc2, name='softmax')
mx.set.seed(0)
devices=mx.cpu()
model = mx.model.FeedForward.create(sm, X=x, 
                                    y=as.numeric(as.factor(subideoForCNN)),
                                    ctx=devices,num.round=200,array.batch.size=batch_size,
                                    learning.rate=0.005,momentum=0.9,
                                    wd=0.00001,eval.metric=mx.metric.accuracy,
                                    initializer=mx.init.uniform(0.01),
                                    lr_scheduler=FactorScheduler(step=batch_size*50, factor = 0.95),
                                    eval.data=list(data=xt,
                                                   label=as.numeric(as.factor(subideoTest))))
```

**Comment by Ldpe2G** [comment]
@bdlacree  does your input_shape is (100, 1, 50, 300) ?

**Comment by bdlacree** [comment]
The total data input shape is (50,300,1,30000), with batchsize 100. The model seems to work on training and test data, but I just want to be sure that the Flatten() is doing what it should.

**Comment by Ldpe2G** [comment]
@bdlacree  could you provide the dataiter code? I think your input shape may be wrong, 
you can run the following code to see what Flatten is doing:

import mxnet as mx
import numpy as np

x = mx.symbol.Variable('data')
shape = (2, 2, 3, 4)
data_tmp = np.ones(shape)
arr_data = mx.nd.array(data_tmp)
arr_grad = mx.nd.empty(shape)

test = mx.symbol.Flatten(data=x)
exe_test = test.bind(mx.cpu(), args=[arr_data], args_grad=[arr_grad])
exe_test.forward()
print exe_test.outputs[0].shape

**Comment by safai** [comment]
@bdlacree: Did you manage to replicate the example in R? I'm having a hard time doing so and would love to see your version if you managed to do it?

Kr,

Daniel

**Comment by pluskid** [comment]
Closing for now. Please feel free to reopen if the needed.
