### ISSUE TITLE
how to use nvprof command to debug mxnet

### ISSUE THREAD

**Issue by liumilan** [dmlc/mxnet#2343]
I'd like to use nvprof command to debug why mulitiple gpu is not much faster than 1 Gpu.As I read nvprof help, the usage about nvprof should be nvprof ./progress. But mxnet is started by python command.If using nvprof,it will report ======== Warning: No CUDA application was profiled, exiting.

**Comment by Godricly** [comment]
r u using cmdline or nvvp?
u can use nvprof python srcipt.py --params
My last experiment with my multiprocess Dataiter using nvvp is not doing well,but the nvprof works. I was testing lstm using only one gpu, I think it should be the same for multiple gpu. I hope this is useful for you.

**Comment by liumilan** [comment]
yes,i use nvprof  launch.py -H hosts -n2 python train.py --kv-store dist_async like that
And no gpu info output.It report 
======== Warning: No CUDA application was profiled, exiting at the end.

**Comment by Godricly** [comment]
ah...I guess you are testing multi machine case. 
what I do was like nvprof python train.py --gpus=0,1 ....
maybe you should check [nvprof ](http://docs.nvidia.com/cuda/profiler-users-guide/index.html#axzz4AmERlJUk)for remote profiling.

**Comment by liumilan** [comment]
not i just tried one machie.What is your test result?

**Comment by Godricly** [comment]
I used default setup, so I got pretty much the main thread function calling info and time cost. Such as cudasync. u can try nvprof with a small model first, then move one more step to ur real application.

**Comment by piiswrong** [comment]
Don't use the launch script if you are using single machine. It will start another process and that's why you are not seeing any output from nvprof
