### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#2344]
Visual Studio 2013, Win64
```
Error	101	error : identifier "transpose" is undefined	c:\users\chuaf\downloads\mxnet\src\operator\matrix_op-inl.h	39	1	mxnet
Error	116	error : no instance of function template "mshadow::expr::slice" matches the argument list	c:\users\chuaf\downloads\mxnet\src\operator\matrix_op-inl.h	257	1	mxnet
Error	141	error : identifier "flip" is undefined	c:\users\chuaf\downloads\mxnet\src\operator\matrix_op-inl.h	334	1	mxnet
```

**Comment by Godricly** [comment]
U need to update your mshadow too. It was added recently. check your mshadow.

**Comment by freddycct** [comment]
thanks.

**Comment by cjfan** [comment]
Today I update the code, use cmake to generate new solution & project under VS2013,win64
I meet the same problem ,and several weeks ago the build is ok.
Any other thing should I do?

**Comment by cjfan** [comment]
I clone a clean one and re-configure it, then the compilation is ok.
