### ISSUE TITLE
drop layer

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#2347]
Hi, 
   Is it possible to drop part of layers(skip the computation) in mxnet. I read FractalNet recently and want to give it a try. I think stochastic deep network need this too. Any instruction on this?

**Comment by sxjscience** [comment]
Similar to dropout?

**Comment by Godricly** [comment]
ye, it's similar. In the paper, they used a drop-path approach to drop some path. And their implementation is based on Caffe. Since these layers give no info,can we skip them randomly? Or produce some info for later layer.

[Link](https://arxiv.org/abs/1605.07648) to paper.

**Comment by sxjscience** [comment]
I think we can implement a choice operator similar to theano. http://deeplearning.net/software/theano/tutorial/conditions.html

**Comment by piiswrong** [comment]
Just use bucketing.

**Comment by hjchen2** [comment]
e, it's a bit difficult...

**Comment by Godricly** [comment]
Do u mean we can manually expand the entire network for different paths?  That's a great idea if we can share the weights like lstm and use the bucket key to handle random path. But creating all those paths is somehow painful. I'll think about it.

**Comment by Godricly** [comment]
The FractalNet is too memory consuming if the input image is large, so I stop trying to do it right now.

**Comment by antinucleon** [comment]
You should try https://github.com/dmlc/mxnet-memonger

With your symbol
On Tue, Jun 7, 2016 at 23:00 Yan Li <notifications@github.com> wrote:

> Closed #2347 <https://github.com/dmlc/mxnet/issues/2347>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2347#event-685326361>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABM13m6LTzJkEMbO1dKLkEW8sFsH4KtVks5qJlqKgaJpZM4IukDk>
> .
>
-- 
Sent from mobile phone

**Comment by Godricly** [comment]
That's an optional memory saving stuff. I followed resnet starting with a 7x7 conv and 3x3 max pooling then 3 blocks of fractal unit. I can get the network trained without memonger, but the main issue I have here is the path-pruning dynamically. #1492 could be a choice, but I don't want to waste time on computing stuffs which are not used at all.
