### ISSUE TITLE
dlmc domain is outdated

### ISSUE THREAD

**Issue by harryprince** [dmlc/mxnet#2350]
I fail to install mxnet in R using the official tutorial, because the domain of dlmc is outdate.

**Comment by thirdwing** [comment]
@phunterlau

**Comment by phunterlau** [comment]
Weird, let me check with my register today, sorry for inconvenience

**Comment by phunterlau** [comment]
just submitted a support ticket to my domain register. The reason was that, the register sent me an cancellation email yesterday (Sunday) due to some unknown reasons from their review team, and the email dropped to my spam folder, so I didn't see it. Sorry about that.

Meanwhile, we might want to think of moving to `dmlc.ai` which is a paid domain with better customer service. Currently `dmlc.ai` is redirecting to `dmlc.ml`. Any ideas please @tqchen @mli @antinucleon ?

**Comment by phunterlau** [comment]
`dmlc.ml` uses a free service from DNSPod as name server, so the DNS parsing might be slow if this service is overloaded. I can upgrade to a paid service (paid service is always good!). Let's solve the registration problem firstly, hope the support ticket works.

**Comment by phunterlau** [comment]
P.S. `dmlc.ai` is owned by us up to 2018. It can be a good backup solution anyway, and the TLD `.ai` is good :-)

**Comment by Pennisetum** [comment]
Still cannot install the package...

**Comment by Pennisetum** [comment]
Still can't install the package...Is it because the domain of dlmc is outdate?Thank you.

**Comment by Pennisetum** [comment]
Still can't install the package...Is it because the domain of dlmc is outdate? Thank you.

**Comment by phunterlau** [comment]
@Pennisetum I have submitted ticket to my register in Netherland, hope they can help. We have a backup solution of switching everything to `dmlc.ai` if my register can't help. Sorry for inconvenience.

**Comment by harryprince** [comment]
I find this bug, when I follow the official guide to install mxnet using r.

**Comment by Pennisetum** [comment]
@phunterlau Thank you! Could you tell me wether I can install the package now?

**Comment by thirdwing** [comment]
You can install it "manually" if you really want.

The package for OSX and Windows is here https://github.com/dmlc/drat/tree/gh-pages/bin

You can install all dependencies (https://github.com/dmlc/drat/blob/gh-pages/src/contrib/PACKAGES#L3-L4) manually, then download the `mxnet` package and install it locally.

**Comment by phunterlau** [comment]
After a couple of rounds P0 tickets with my register, `dmlc.ml` is back online. Thanks to my register (well, surely I agreed putting a paid auto renew, paid service is much better than the free one) Please check. and, @Pennisetum yes, you can install package now. Sorry for inconvenience.

**Comment by phunterlau** [comment]
@thirdwing I think we can close this ticket since `dmlc.ml` is back online. Thanks.

**Comment by antinucleon** [comment]
I think we have several things need to be fixed before close this issue:

1. Some of data is stored at my website in ualberta, I think university
will shutdown my homepage in a few month. We'd better move it to somewhere
more stable.
2. I do think free domain name is a risk. I think dmlc.ai may be better.

We should fix these as soon as possible. If we fix it later, there will be
more problems.

On Tue, Jun 7, 2016 at 3:27 PM Hongliang Liu <notifications@github.com>
wrote:

> @thirdwing <https://github.com/thirdwing> I think we can close this
> ticket since dmlc.ml is back online. Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2350#issuecomment-224433699>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13ujOwOLS3EpdniaceQlzq5RZ7qcWks5qJfBYgaJpZM4Iu1T8>
> .
>
-- 
Sent from mobile phone

**Comment by thirdwing** [comment]
On Tue, Jun 7, 2016 at 5:35 PM, Bing Xu <notifications@github.com> wrote:

> I think we have several things need to be fixed before close this issue:
>
> 1. Some of data is stored at my website in ualberta, I think university
> will shutdown my homepage in a few month. We'd better move it to somewhere
> more stable.
>

Totally agree.


> 2. I do think free domain name is a risk. I think dmlc.ai may be better.
>
> We should fix these as soon as possible. If we fix it later, there will be
> more problems.
>
> On Tue, Jun 7, 2016 at 3:27 PM Hongliang Liu <notifications@github.com>
> wrote:
>
> > @thirdwing <https://github.com/thirdwing> I think we can close this
> > ticket since dmlc.ml is back online. Thanks.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/dmlc/mxnet/issues/2350#issuecomment-224433699>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ABM13ujOwOLS3EpdniaceQlzq5RZ7qcWks5qJfBYgaJpZM4Iu1T8
> >
> > .
> >
> --
> Sent from mobile phone
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2350#issuecomment-224435312>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABebVbaPDEq6ho4fmtVbqkfm19WeCD-kks5qJfI2gaJpZM4Iu1T8>
> .
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by phunterlau** [comment]
Agree @antinucleon @thirdwing `dmlc.ml` now is a paid domain with auto renew every year, no more problem. Since github only allows a single domain where we have to choose either `dmlc.ml` or `dmlc.ai`, I prefer staying with `dmlc.ml` for now, and keep `dmlc.ai` as backup (http redirect right now).

As to storage, let's take this chance to move them to a paid storage. I can contribute some $$ for it.
