### ISSUE TITLE
Stream of output gradient in unitary operator

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#2360]
I find the current implementation of unitary operator seems to be using the default stream for ograd. https://github.com/dmlc/mxnet/blob/master/src/operator/elementwise_unary_op-inl.h#L57 Should we use `out_grad.data.FlatTo2D<xpu, DType>(s)` instead of `out_grad.data.FlatTo2D<xpu, DType>()` ?

**Comment by piiswrong** [comment]
It probably doesn't matter because it will use the first one's stream (?)

But we should fix it nontheless
