### ISSUE TITLE
multiple gpu is not  as fast as I imagine when run train_minst.py

### ISSUE THREAD

**Issue by liumilan** [dmlc/mxnet#2363]
I found 4 gpus is not as fast as I imagine when run on my data,the speed ratio only can be up to 1.5。
My network is mlp,no any convolution.
So I tried to run minst datas in example folders.But when run it ,4 gpus are the same as single gpu.
Is it a issue?How can it make possible to accelerate when using 4 gpus.

**Comment by piiswrong** [comment]
small networks doesn't benefit from multi gpu due to communication cost. Try bigger networks like inception or use a very large batch size

**Comment by liumilan** [comment]
I have tried bigger networks and bigger batchsize in my work.But the speed raito is only 1.5.And I've tried to debug using nvprof command.
Here is the 1 gup output
==13156== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 43.77%    5e+03s    522660  9.1269ms  20.472us  106.29ms  cudaMemcpy2DAsync
 38.15%    4e+03s   9002163  461.91us  8.8080us  100.61ms  cudaLaunch
 15.21%    2e+03s   6941616  238.85us  2.9410us  3.8387ms  cudaStreamSynchronize
  1.97%  214.897s    234840  915.08us  16.025us  85.512ms  cudaMemsetAsync
  0.31%  34.2274s  59479312     575ns     171ns  10.093ms  cudaSetupArgument
  0.21%  22.6694s  11272351  2.0110us     433ns  1.2894ms  cudaSetDevice
  0.10%  10.8445s   1369878  7.9160us     760ns  6.6984ms  cudaEventRecord
  0.09%  9.89906s   9002163  1.0990us     221ns  4.7842ms  cudaConfigureCall

4gpus output

==53185== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 66.79%    5e+03s   9605552  532.99us  7.6460us  463.35ms  cudaMemcpy2DAsync
 22.27%    2e+03s  16494176  103.51us  3.0010us  2.1129ms  cudaStreamSynchronize
  7.53%  577.109s  16699600  34.558us  9.3840us  446.26ms  cudaLaunch
  1.08%  83.0077s  1.54e+08     537ns     176ns  1.5361ms  cudaSetupArgument
  0.86%  66.0404s    939360  70.303us  13.680us  442.35ms  cudaMemsetAsync
What is the bottleneck from the above output?cudaStreamSynchronize?
Can it pipepline between copy data from cpu to gpu and gpu compution?
@piiswrong

**Comment by tqchen** [comment]
try examples like cifar or imagenet, you will likely to get a better speedup

**Comment by liumilan** [comment]
I‘ve run cifar,The speed ratio is 3.Seem better speedup.
4gpus:Time cost=40.951
1gpus:Time cost=122.265
So gpu accelation can only be fit to conlution layers?

Could you help to give some advice why my mlp network can't speedup.How can I debug?
@tqchen

**Comment by tqchen** [comment]
Usually it depends on communication cost(parameter size) vs computation.

If it takes more time to copy the parameters than computation, you cannot get speedup.  This is what happens in the mlp case

For speeding up data parallel code in MLP mechanisms like gradient compression will be needed, but not yet available in mxnet.

**Comment by liumilan** [comment]
So what u mean is that mxnet havn't supported pipeline between communication and computaion yet?
Can it possbile to support it in future?
BTW,how can I get the time about copy the parameters and computation?And commands?
I can't get it by nvprof command.
@tqchen

**Comment by tqchen** [comment]
It support the overlapping of communication and computation. But the case
is when communication costs more than computation, it can slow things down

**Comment by liumilan** [comment]
how can I can get the communication costs durning trainning in mxnet?
Could u give me some commands?
@tqchen

**Comment by tqchen** [comment]
unfortunately we do not have the exact code to get the cost on the communication side due to the async nature of the two operations

**Comment by liumilan** [comment]
I'd like to make sure one things. 
does mxnet support pipeline between cpu copy data to gpu and gpu computaion default? or does it need to add some configuration in mxnet code?
@tqchen

**Comment by tqchen** [comment]
yes, make sure everything starts in mxnet's array, then everything will happen concurrently

**Comment by liumilan** [comment]
hi,tianqi
 i have tried to do more experiment. There are costs during one epoch in every case as below:

Time cost=164.686  1 machine 1gpu
Time cost=81.730    2 machine 1 gpu
Time cost=121.668  1 machnine 2gpus(gpu0,gpu1)
Time cost=117.28     1 machine  4gpus
And 2 gpu ,the ratio can be 1.35,it seemed also ok. 
And 4gpus,the ratio is the same as 2 gpus.
And 2 machine 1 gpu, the ratio can also be reduced to half.I guess it is becasue every machine load half data,so the time should be reduced.

But why it can't be occured in 4gpus? every gpu has also load its data in fact.
as you pointed copy parameters will take some time.And 2 machines also need to take some time?
Could you give me some more explanation? i am still so confused.
@tqchen

**Comment by liumilan** [comment]
i think i find the root.
The root cause is nothing to do with parameters copy and computaion.This time are only take 10% in my network.The most of time are taken in io read in this funtion for data_batch in train_data:
 The time in 4gpus is the same as 1 gpu .But in face 4gpus ,every gpus load 1/4 data,it should be reduce to 1/4 when io reading.
Could you give some more advice on this?Is it possible to optimize it?
@tqchen
