### ISSUE TITLE
Questions about the data format for non-image machine learning problems

### ISSUE THREAD

**Issue by ngmanhei** [dmlc/mxnet#2370]
Hello, 
Recently, I attempted to use mxnet to train a fully connected NNs, a simple network, followed by a softmax classifier. As I all known, mxnet uses a specialized data format to store the data. However, almost every example I can refer to is the image task, while my task is non-image one and its trainning data just a simple 1-d data vector, like [0, 15.34, -182.36, 1, ..., 87]. Could you please tell me how to convert this kind of data to the mxnet-specialized data format?
Any advice will be much appreciated.
thx~

**Comment by piiswrong** [comment]
You don't need to convert. You can use any format you want.
Try using NDArryIter with numpy data array

**Comment by ngmanhei** [comment]
@piiswrong Thanks a lot !
