### ISSUE TITLE
search not working in readthedocs

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#2374]
Hi,
    Is that search in [readthedocs ](http://mxnet.readthedocs.io/en/latest/)working? Or I am doing wrong with it.

**Comment by mli** [comment]
it's a known bug but unfortunately not fixed yet, blame on me

**Comment by kikoqiu** [comment]
@mli 
I don't know if the bug is fixed or not. But FYR, I found that `Search.init()` is called in _readthedocs-doc-embed.js_ when the doc is ready in other sites.
So I add it here in the code and the search works.
`  <script type="text/javascript">
    jQuery(function() { Search.loadIndex("searchindex.js"); Search.init();});
  </script>`

**Comment by tmatas** [comment]
Moreover, I think it would be useful to list the subclasses functions in the docs.

i.e: If you look at the list on the left In [Python NDArray API](http://mxnet.readthedocs.io/en/latest/packages/python/ndarray.html)s,  you will find `ndarray.NDArray` but neither one of its methods is listed
