### ISSUE TITLE
Initialize Weights in Embedding

### ISSUE THREAD

**Issue by bdlacree** [dmlc/mxnet#2389]
Hello folks ---

Yet again, thanks for the wonderful software and support. I'm trying to use word embeddings for a text classification task. To this point I've just used the vanilla Word2Vec pre-trained vectors. 

If I wanted to train my own, but *initialize them* with the Word2Vec values, how can I do that? In other words, how can I provide initial values for the embedding only, and not for the rest of the network?

Thanks!

**Comment by linmx0130** [comment]
Maybe you can find how to do that in the example of cnn-text-classification.
https://github.com/dmlc/mxnet/tree/master/example/cnn_text_classification

**Comment by bdlacree** [comment]
Thanks, linmx0130. I've been using that example all along, but I just don't see where they initialize the embeddings. (They seem to initialize weights using `mx.init.Uniform(0.01)`. 

I was hoping to find out how to set the initial values for this one particular part of the model. (i.e., initialize the weights to the word2vec values). Do you know if that's possible?

**Comment by linmx0130** [comment]
The lookup tabel seems different to other part of the network. In the example the embeddings are used as the input of the network, but not a real part of the network. You can find more details in [data_helpers.py](https://github.com/dmlc/mxnet/blob/master/example/cnn_text_classification/data_helpers.py). But if you want to set the initial values for other particualr part of the model, I think you'd better try to hack the initializer.
