### ISSUE TITLE
Neural Art Example

### ISSUE THREAD

**Issue by ryanphjohnson** [dmlc/mxnet#2391]
I'm interested in creating a Neural Art C++ implementation. I'm very familiar with C++, and somewhat familiar with python (what the current neural art example is in), but I only know some about how CNNs work. I've read [this wiki article](https://en.wikipedia.org/wiki/Convolutional_neural_network), but this is about the limit of my knowledge. Does anyone have any tips on how I might try to implement this in C++?

I'd love to learn more about CNNs and Neural Art, and this should be an excellent learning opportunity, but I may need some guidance along the way. Thanks!

**Comment by Ldpe2G** [comment]
I have successfully implemented the neural-style in Scala #1821 #2100 。
From my experience, if you what to transfer from one language to others, you need to figure out what actually the original code is doing. For me, it takes about a week to transfer python to scala by running the python code many times to figure what each function is doing.

**Comment by Ldpe2G** [comment]
@ryanphjohnson  I have successfully implemented the neural-style in Scala #1821 #2100 。
From my experience, if you what to transfer from one language to others, you need to figure out what actually the original code is doing. For me, it takes about a week to transfer python to scala by running the python code many times to figure what each function is doing.

**Comment by ryanphjohnson** [comment]
@Ldpe2G Thanks for the tip! I was a bit concerned about following the python version too closely. I feared the interface with MXNet would be significantly different from language to language. Its comforting to know that you were able to take the python and in a week or so able to convert it to Scala. You give me hope!
