### ISSUE TITLE
does mxnet support pipeline between cpu copy data to gpu and gpu computation by default?

### ISSUE THREAD

**Issue by liumilan** [dmlc/mxnet#2400]
I'd like to ask for one thing:does mxnet support pipeline between cpu copy data to gpu and gpu computation by default? if not default,does it need to add some configuration ,make it pipeline.
I can't get the pipeline from code,maybe i miss sth.

**Comment by antinucleon** [comment]
a = mx.nd.zeros(..., mx.cpu())
b = mx.nd.zeros(..., mx.gpu())

Both

a.copyto(b)

and

b[:] = a

Are doing this
On Sun, Jun 12, 2016 at 08:22 liumilan <notifications@github.com> wrote:

> I'd like to ask for one thing:does mxnet support pipeline between cpu copy
> data to gpu and gpu computation by default? if not default,does it need to
> add some configuration ,make it pipeline.
> I can't get the pipeline from code,maybe i miss sth.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2400>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABM13lz8gnejjjGTdLLfWKmfdDmCHFCTks5qLCQUgaJpZM4Iz0MJ>
> .
>
-- 
Sent from mobile phone
