### ISSUE TITLE
data iterator without labels for RNN

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#2403]
Is it possible to provide input data that does not have a label in some timesteps for RNN? An example as shown in the figure below.

![untitled drawing](https://cloud.githubusercontent.com/assets/1184555/15993042/e55bfac6-308f-11e6-9041-d386992ec75f.png)

**Comment by freddycct** [comment]
but for time steps without labels, I will not connect a softmaxoutput to the RNN cell. Can does dataiter need a label for every input data?

**Comment by Godricly** [comment]
U can give some dummy label and skip their computation,which is easier for you to implement.

**Comment by freddycct** [comment]
It will certainly work but sounds like a hack to me. I will try this thanks. Meanwhile, I also hope there will be more elegant solution in the future.

**Comment by freddycct** [comment]
Re-opening this because I realized that mx.symbol.LinearRegressionOutput does not have ignore_label.

I am trying to build a RNN with real-valued outputs instead of discrete labels
