### ISSUE TITLE
is _LIB.MXKVStorePush at kvstore.py an async call  to C API

### ISSUE THREAD

**Issue by kandycs** [dmlc/mxnet#2404]
Hi everybody,
is _LIB.MXKVStorePush called by push method inside kvstore class (kvstore.py) an async call to C API
MXKVStore when local type kvstore is utilized. When I do the profiling, the execution time of push method at kvstore.py  is much smaller then execution time of MXKVStorePush function at c_api.cc. for example, push method from kvstore.py executed around 0.9 secs for 1 epoch, but MXKVStorePush executed 3.5 seconds. However, around 3.2 seconds are consumed by updater_ function called by push (kvstore_local.h). Therefore, it seems to me that every operation is serial inside MXKVStorePush, except _LIB.MXKVStorePush. If _LIB.MXKVStorePush is an async operation, how async is achieved? I did not clearly find dependency engine or other async operation are involved during the execution path of _update_params_on_kvstore (model.py) function . What I missed here ? 

I am a little curious about updater_ (from kvstore_local.h) procedure too. As its core function is from optimizer.py, e.g. SGD.update, which takes only 0.6 seconds for one epoch. But after python ctypes callback function wrapper, its execution time is more than 3.2 seconds ( I measured it inside std::function object, which is defined inside MXKVStoreSetUpdater ( c_api.cc). What I missed here too ? 

In kvstore.py, I used time.time() to measure the execution time, and in MXKVStorePush, I used clock() function to measure the execution time.  

Thanks for help !

**Comment by mli** [comment]
all functions are async. they just push the operations into the backend engine for execution.
