### ISSUE TITLE
Data Iterator for Text (BucketSentenceIterator)

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#2411]
I am trying to understand how to create my own DataIter class to feed text data into an RNN. I looked through BucketSentenceIterator but doesn't understand why it works. 

Because BucketSentenceIterator inherits the interface DataIter, yet it does not implement the functions

getData(), getLabel(), iter_next(), next(), etc...

I wonder if someone can write a more comprehensive tutorial of how to create our own dataiter. The current tutorial shows an example for images instead of sequential data.

**Comment by Godricly** [comment]
I don't think you need to take care of those getData() stuffs. I followed the tutorial and got a functional audio bucketing dataiter. 
The trick is to get the provided_data,provided_label and simple databatch in __iter__() right. Also don't forget the bucket_key. If u are using lstm which has a state, take care of it too.

After u finish implementation, go debug around model.py and execute_manager.py. A default bucket is created with default bucket_key at init. Then on each data batch, a bucket is created if no existed before(The creation takes time, u are expecting low GPU usage at first epoch). 

The most important thing is to update your MxNet before testing. ;) good luck.

**Comment by freddycct** [comment]
Which tutorial did you follow? I cannot find a tutorial that talks about provide_data, provide_label and databatch.

**Comment by Godricly** [comment]
The one in example/rnn.
Also, check this tutorial [link](http://mxnet.readthedocs.io/en/latest/how_to/bucketing.html).

**Comment by freddycct** [comment]
I have this error 
```
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-54-139a6aace18a> in <module>()
----> 1 model.fit(X = sequenceiter)

C:\Users\chuaf\AppData\Local\Continuum\Miniconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\model.py in fit(self, X, y, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, logger, work_load_list, monitor, eval_batch_end_callback)
    743 
    744         arg_names, param_names, aux_names = \
--> 745                 self._init_params(dict(data.provide_data+data.provide_label))
    746 
    747         # setup metric

C:\Users\chuaf\AppData\Local\Continuum\Miniconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\model.py in _init_params(self, input_shapes, overwrite)
    483     def _init_params(self, input_shapes, overwrite=False):
    484         """Initialize weight parameters and auxiliary states"""
--> 485         arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
    486         assert(arg_shapes is not None)
    487 

C:\Users\chuaf\AppData\Local\Continuum\Miniconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\symbol.py in infer_shape(self, *args, **kwargs)
    451             The order is in the same order as list_auxiliary()
    452         """
--> 453         return self._infer_shape_impl(False, *args, **kwargs)
    454 
    455     def infer_shape_partial(self, *args, **kwargs):

C:\Users\chuaf\AppData\Local\Continuum\Miniconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\symbol.py in _infer_shape_impl(self, partial, *args, **kwargs)
    511             ctypes.byref(aux_shape_ndim),
    512             ctypes.byref(aux_shape_data),
--> 513             ctypes.byref(complete)))
    514         if complete.value != 0:
    515             arg_shapes = [

C:\Users\chuaf\AppData\Local\Continuum\Miniconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 def c_str(string):

MXNetError: InferShape Error in t0_sm's label argument
Corresponding keyword of symbol: label/0
Shape inconsistent, Provided =(1,1000), inferred shape=(1,)
```

Am I supposed to place my labels in self.label? Is self.label supposed to be a list or dict?

**Comment by Godricly** [comment]
It seems that your label is 2d but what it computed is 1d.
