### ISSUE TITLE
Monitor bucket debug info solution?

### ISSUE THREAD

**Issue by gmyofustc** [dmlc/mxnet#2414]
Hi all,
       I'm using bucket for my full sequence lstm experiments, and I want to watch the parameters during the training.
      First, I tried use [Monitor](https://github.com/dmlc/mxnet/blob/master/python/mxnet/monitor.py) for debug, but Mxnet tells me "monitor does not support bucket now"
      So, I follow[./example/numpy-ops/custom_softmax.py](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/custom_softmax.py) to write a python-based operator(DebugOperator), whoes output is the same as the input. Inside the DebugOperator, I can print out the parameters I want to see.

Here is the code:

```python
import mxnet as mx

class DebugOperator(mx.operator.CustomOp):
    def forward(self, is_train, req, in_data, out_data, aux):
        ###Here One Can Print Out The Debug Info
        print "here is the debug info"
        print in_data[0].asnumpy()
        self.assign(out_data[0], req[0], in_data[0])

    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
        self.assign(in_grad[0], req[0], out_grad[0])

@mx.operator.register("debug_info")
class DebugOperatorProp(mx.operator.CustomOpProp):
    def __init__(self):
        super(DebugOperatorProp, self).__init__(need_top_grad=True)
    
    def list_arguments(self):
        return ['data']

    def list_outputs(self):
        return ['output']

    def infer_shape(self, in_shape):
        data_shape = in_shape[0]
        output_shape = in_shape[0]
        return [data_shape], [output_shape], []

    def create_operator(self, ctx, shapes, dtypes):
        return DebugOperator()

```
I use the customed operator in this way:
```python
#to print out the test_symbol
test_symbol = mx.sym.Custom(data=test_symbol, name='debug', op_type='debug')
```
When I used this customed operator, I get this error:

```shell
Traceback:
File "_ctypes/callbacks.c", line 313 in "calling callback function"
File "../mxnet/python/mxnet/operator.py", in line 600, in creator
        op_prop = prop_cls(**kwargs)
Type Error: __init__() got an unexpected keyward argument 'data'
Segmentation fault
```
Since I'm new to mxnet, I'm not sure if I defined this operator in the right way. But I do believe this is a solution for debuging bucket info, which is not supported in current version.

**Comment by 5urprise** [comment]
As you have registered your custom operator with the name "debug_info", you have to reference it with the same name when calling it, so 
`test_symbol = mx.sym.Custom(data=test_symbol, name='debug', op_type='debug_info')`

**Comment by gmyofustc** [comment]
@5urprise  thx, actually, I passed a list of symbol to this function
```python
test_symbol = mx.sym.Custom(data=test_symbol, name='debug', op_type='debug')
```
the **test_symbol** I feed in should be a symbol
