### ISSUE TITLE
build mxnet on mac os 10.10.5 "ld: symbol(s) not found for architecture x86_64"

### ISSUE THREAD

**Issue by GuohongLi** [dmlc/mxnet#2415]
g++-4.8 -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/liguohong01/Code/ml/dl/mxnet/mshadow/ -I/Users/liguohong01/Code/ml/dl/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -I/usr/local/opt/openblas/include -I/usr/local/Cellar/opencv/2.4.13/include -DMXNET_USE_NVRTC=0 -shared -o lib/libmxnet.so build/src/resource.o build/src/c_api/c_api.o build/src/c_api/c_api_error.o build/src/c_api/c_predict_api.o build/src/common/mxrtc.o build/src/engine/engine.o build/src/engine/naive_engine.o build/src/engine/threaded_engine.o build/src/engine/threaded_engine_perdevice.o build/src/engine/threaded_engine_pooled.o build/src/io/image_aug_default.o build/src/io/io.o build/src/io/iter_csv.o build/src/io/iter_image_recordio.o build/src/io/iter_mnist.o build/src/kvstore/kvstore.o build/src/ndarray/ndarray.o build/src/ndarray/ndarray_function.o build/src/operator/activation.o build/src/operator/batch_norm.o build/src/operator/block_grad.o build/src/operator/broadcast_reduce_op.o build/src/operator/cast.o build/src/operator/concat.o build/src/operator/convolution.o build/src/operator/crop.o build/src/operator/cross_device_copy.o build/src/operator/cudnn_batch_norm.o build/src/operator/custom.o build/src/operator/deconvolution.o build/src/operator/dropout.o build/src/operator/elementwise_binary_broadcast_op.o build/src/operator/elementwise_binary_op.o build/src/operator/elementwise_binary_scalar_op.o build/src/operator/elementwise_sum.o build/src/operator/elementwise_unary_op.o build/src/operator/embedding.o build/src/operator/fully_connected.o build/src/operator/identity_attach_KL_sparse_reg.o build/src/operator/l2_normalization.o build/src/operator/leaky_relu.o build/src/operator/loss_binary_op.o build/src/operator/lrn.o build/src/operator/make_loss.o build/src/operator/matrix_op.o build/src/operator/native_op.o build/src/operator/ndarray_op.o build/src/operator/operator.o build/src/operator/operator_util.o build/src/operator/pooling.o build/src/operator/regression_output.o build/src/operator/reshape.o build/src/operator/roi_pooling.o build/src/operator/slice_channel.o build/src/operator/smooth_l1_unary.o build/src/operator/softmax_activation.o build/src/operator/softmax_output.o build/src/operator/swapaxis.o build/src/operator/upsampling.o build/src/optimizer/optimizer.o build/src/optimizer/sgd.o build/src/storage/storage.o build/src/symbol/graph_executor.o build/src/symbol/graph_memory_allocator.o build/src/symbol/static_graph.o build/src/symbol/symbol.o /Users/liguohong01/Code/ml/dl/mxnet/dmlc-core/libdmlc.a -pthread -lm  `pkg-config --libs opencv` -L/usr/local/opt/openblas/lib -L/usr/local/Cellar/opencv/2.4.13/lib -lstdc++
g++-4.8 -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/liguohong01/Code/ml/dl/mxnet/mshadow/ -I/Users/liguohong01/Code/ml/dl/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -I/usr/local/opt/openblas/include -I/usr/local/Cellar/opencv/2.4.13/include -DMXNET_USE_NVRTC=0 -std=c++0x  -o bin/im2rec tools/im2rec.cc build/src/resource.o build/src/c_api/c_api.o build/src/c_api/c_api_error.o build/src/c_api/c_predict_api.o build/src/common/mxrtc.o build/src/engine/engine.o build/src/engine/naive_engine.o build/src/engine/threaded_engine.o build/src/engine/threaded_engine_perdevice.o build/src/engine/threaded_engine_pooled.o build/src/io/image_aug_default.o build/src/io/io.o build/src/io/iter_csv.o build/src/io/iter_image_recordio.o build/src/io/iter_mnist.o build/src/kvstore/kvstore.o build/src/ndarray/ndarray.o build/src/ndarray/ndarray_function.o build/src/operator/activation.o build/src/operator/batch_norm.o build/src/operator/block_grad.o build/src/operator/broadcast_reduce_op.o build/src/operator/cast.o build/src/operator/concat.o build/src/operator/convolution.o build/src/operator/crop.o build/src/operator/cross_device_copy.o build/src/operator/cudnn_batch_norm.o build/src/operator/custom.o build/src/operator/deconvolution.o build/src/operator/dropout.o build/src/operator/elementwise_binary_broadcast_op.o build/src/operator/elementwise_binary_op.o build/src/operator/elementwise_binary_scalar_op.o build/src/operator/elementwise_sum.o build/src/operator/elementwise_unary_op.o build/src/operator/embedding.o build/src/operator/fully_connected.o build/src/operator/identity_attach_KL_sparse_reg.o build/src/operator/l2_normalization.o build/src/operator/leaky_relu.o build/src/operator/loss_binary_op.o build/src/operator/lrn.o build/src/operator/make_loss.o build/src/operator/matrix_op.o build/src/operator/native_op.o build/src/operator/ndarray_op.o build/src/operator/operator.o build/src/operator/operator_util.o build/src/operator/pooling.o build/src/operator/regression_output.o build/src/operator/reshape.o build/src/operator/roi_pooling.o build/src/operator/slice_channel.o build/src/operator/smooth_l1_unary.o build/src/operator/softmax_activation.o build/src/operator/softmax_output.o build/src/operator/swapaxis.o build/src/operator/upsampling.o build/src/optimizer/optimizer.o build/src/optimizer/sgd.o build/src/storage/storage.o build/src/symbol/graph_executor.o build/src/symbol/graph_memory_allocator.o build/src/symbol/static_graph.o build/src/symbol/symbol.o /Users/liguohong01/Code/ml/dl/mxnet/dmlc-core/libdmlc.a -pthread -lm  `pkg-config --libs opencv` -L/usr/local/opt/openblas/lib -L/usr/local/Cellar/opencv/2.4.13/lib -lstdc++
Undefined symbols for architecture x86_64:
  "_GOMP_parallel_end", referenced from:
      dmlc::Parser<unsigned int>* dmlc::data::CreateLibSVMParser<unsigned int>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int, unsigned int) in libdmlc.a(data.o)
      dmlc::Parser<unsigned long long>* dmlc::data::CreateLibSVMParser<unsigned long long>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int, unsigned int) in libdmlc.a(data.o)
      dmlc::data::CSVParser<unsigned int>::CSVParser(dmlc::InputSplit*, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, int) in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long long> > >*) in libdmlc.a(data.o)
  "_GOMP_parallel_start", referenced from:
      dmlc::Parser<unsigned int>* dmlc::data::CreateLibSVMParser<unsigned int>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int, unsigned int) in libdmlc.a(data.o)
      dmlc::Parser<unsigned long long>* dmlc::data::CreateLibSVMParser<unsigned long long>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int, unsigned int) in libdmlc.a(data.o)
      dmlc::data::CSVParser<unsigned int>::CSVParser(dmlc::InputSplit*, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, int) in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long long> > >*) in libdmlc.a(data.o)
  "_cblas_dgemm", referenced from:
      mxnet::op::ConvolutionOp<mshadow::cpu, double>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in convolution.o
      mxnet::op::ConvolutionOp<mshadow::cpu, double>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in convolution.o
      mxnet::op::DeconvolutionOp<mshadow::cpu, double>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in deconvolution.o
      mxnet::op::DeconvolutionOp<mshadow::cpu, double>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in deconvolution.o
      mxnet::op::FullyConnectedOp<mshadow::cpu, double>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in fully_connected.o
      mxnet::op::FullyConnectedOp<mshadow::cpu, double>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in fully_connected.o
  "_cblas_sdot", referenced from:
      void mxnet::op::L2Norm<mshadow::cpu>(mshadow::TBlob const&, mxnet::op::EnvArguments const&, mshadow::TBlob*, mxnet::OpReqType, mxnet::RunContext) in broadcast_reduce_op.o
      void mxnet::op::DotForward_<mshadow::cpu>(mshadow::TBlob const&, mshadow::TBlob const&, mxnet::op::EnvArguments const&, mshadow::TBlob*, mxnet::OpReqType, mxnet::RunContext) in matrix_op.o
  "_cblas_sgemm", referenced from:
      mxnet::op::ConvolutionOp<mshadow::cpu, float>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in convolution.o
      mxnet::op::ConvolutionOp<mshadow::cpu, float>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in convolution.o
      mxnet::op::DeconvolutionOp<mshadow::cpu, float>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in deconvolution.o
      mxnet::op::DeconvolutionOp<mshadow::cpu, float>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in deconvolution.o
      mxnet::op::FullyConnectedOp<mshadow::cpu, float>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in fully_connected.o
      mxnet::op::FullyConnectedOp<mshadow::cpu, float>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in fully_connected.o
      void mxnet::op::DotBackward_<mshadow::cpu>(mxnet::op::OutputGrad const&, mxnet::op::Input0 const&, mxnet::op::Input1 const&, mxnet::op::EnvArguments const&, mshadow::TBlob*, mshadow::TBlob*, mxnet::OpReqType, mxnet::OpReqType, mxnet::RunContext) in matrix_op.o
      ...
  "_omp_get_num_procs", referenced from:
      dmlc::data::TextParserBase<unsigned int>::TextParserBase(dmlc::InputSplit*, int) [clone ._omp_fn.4] in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::TextParserBase(dmlc::InputSplit*, int) [clone ._omp_fn.5] in libdmlc.a(data.o)
  "_omp_get_num_threads", referenced from:
      dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) [clone ._omp_fn.0] in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long long> > >*) [clone ._omp_fn.2] in libdmlc.a(data.o)
  "_omp_get_thread_num", referenced from:
      dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) [clone ._omp_fn.1] in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long long> > >*) [clone ._omp_fn.3] in libdmlc.a(data.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
Undefined symbols for architecture x86_64:
  "_GOMP_parallel_end", referenced from:
      dmlc::Parser<unsigned int>* dmlc::data::CreateLibSVMParser<unsigned int>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int, unsigned int) in libdmlc.a(data.o)
      dmlc::Parser<unsigned long long>* dmlc::data::CreateLibSVMParser<unsigned long long>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int, unsigned int) in libdmlc.a(data.o)
      dmlc::data::CSVParser<unsigned int>::CSVParser(dmlc::InputSplit*, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, int) in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long long> > >*) in libdmlc.a(data.o)
  "_GOMP_parallel_start", referenced from:
      dmlc::Parser<unsigned int>* dmlc::data::CreateLibSVMParser<unsigned int>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int, unsigned int) in libdmlc.a(data.o)
      dmlc::Parser<unsigned long long>* dmlc::data::CreateLibSVMParser<unsigned long long>(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, unsigned int, unsigned int) in libdmlc.a(data.o)
      dmlc::data::CSVParser<unsigned int>::CSVParser(dmlc::InputSplit*, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, int) in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long long> > >*) in libdmlc.a(data.o)
  "cv::imencode(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)", referenced from:
      _main in ccYkg0yX.o
  "_cblas_dgemm", referenced from:
      mxnet::op::ConvolutionOp<mshadow::cpu, double>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in convolution.o
      mxnet::op::ConvolutionOp<mshadow::cpu, double>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in convolution.o
      mxnet::op::DeconvolutionOp<mshadow::cpu, double>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in deconvolution.o
      mxnet::op::DeconvolutionOp<mshadow::cpu, double>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in deconvolution.o
      mxnet::op::FullyConnectedOp<mshadow::cpu, double>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in fully_connected.o
      mxnet::op::FullyConnectedOp<mshadow::cpu, double>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in fully_connected.o
  "_cblas_sdot", referenced from:
      void mxnet::op::L2Norm<mshadow::cpu>(mshadow::TBlob const&, mxnet::op::EnvArguments const&, mshadow::TBlob*, mxnet::OpReqType, mxnet::RunContext) in broadcast_reduce_op.o
      void mxnet::op::DotForward_<mshadow::cpu>(mshadow::TBlob const&, mshadow::TBlob const&, mxnet::op::EnvArguments const&, mshadow::TBlob*, mxnet::OpReqType, mxnet::RunContext) in matrix_op.o
  "_cblas_sgemm", referenced from:
      mxnet::op::ConvolutionOp<mshadow::cpu, float>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in convolution.o
      mxnet::op::ConvolutionOp<mshadow::cpu, float>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in convolution.o
      mxnet::op::DeconvolutionOp<mshadow::cpu, float>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in deconvolution.o
      mxnet::op::DeconvolutionOp<mshadow::cpu, float>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in deconvolution.o
      mxnet::op::FullyConnectedOp<mshadow::cpu, float>::Forward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in fully_connected.o
      mxnet::op::FullyConnectedOp<mshadow::cpu, float>::Backward(mxnet::OpContext const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&, std::vector<mshadow::TBlob, std::allocator<mshadow::TBlob> > const&) in fully_connected.o
      void mxnet::op::DotBackward_<mshadow::cpu>(mxnet::op::OutputGrad const&, mxnet::op::Input0 const&, mxnet::op::Input1 const&, mxnet::op::EnvArguments const&, mshadow::TBlob*, mshadow::TBlob*, mxnet::OpReqType, mxnet::OpReqType, mxnet::RunContext) in matrix_op.o
      ...
  "_omp_get_num_procs", referenced from:
      dmlc::data::TextParserBase<unsigned int>::TextParserBase(dmlc::InputSplit*, int) [clone ._omp_fn.4] in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::TextParserBase(dmlc::InputSplit*, int) [clone ._omp_fn.5] in libdmlc.a(data.o)
  "_omp_get_num_threads", referenced from:
      dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) [clone ._omp_fn.0] in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long long> > >*) [clone ._omp_fn.2] in libdmlc.a(data.o)
  "_omp_get_thread_num", referenced from:
      dmlc::data::TextParserBase<unsigned int>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned int>, std::allocator<dmlc::data::RowBlockContainer<unsigned int> > >*) [clone ._omp_fn.1] in libdmlc.a(data.o)
      dmlc::data::TextParserBase<unsigned long long>::FillData(std::vector<dmlc::data::RowBlockContainer<unsigned long long>, std::allocator<dmlc::data::RowBlockContainer<unsigned long long> > >*) [clone ._omp_fn.3] in libdmlc.a(data.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1

**Comment by thirdwing** [comment]
From the lines
```
Undefined symbols for architecture x86_64:
"GOMP_parallel_end", referenced from:
```

It seems your compiler dosn't have openmp support.
