### ISSUE TITLE
NDarray API mismatch with the scource code?

### ISSUE THREAD

**Issue by zdltheone** [dmlc/mxnet#2422]
When I tried to ues NDarray to realize a python operator, I found that the NDarray API given by (http://mxnet.readthedocs.io/en/latest/packages/python/ndarray.html#slice-operations) seems mismatch with the source code.

for example:

(cmd)>>> z = mx.nd.ones((3,4),mx.gpu(0))
(cmd)>>> z.context
(cmd)gpu(0)
(cmd)>>> mx.nd.max(z).asnumpy()
(cmd)array([ 1.], dtype=float32)
(cmd)>>> mx.nd.max(z)
(cmd)  mxnet.ndarray.NDArray object at 0x000000001B9CD6A0
(cmd)>>> mx.nd.max(z,axis = 1)
(cmd)Traceback (most recent call last):
(cmd)  File "<stdin>", line 1, in <module>
(cmd)TypeError: unary_ndarray_function() got an unexpected keyword argument 'axis'
(cmd)>>> mx.nd.max_axis(z,axis = 1)
(cmd)Traceback (most recent call last):
(cmd)  File "<stdin>", line 1, in <module>
(cmd)AttributeError: 'module' object has no attribute 'max_axis'
(cmd)>>> mx.ndarray.max_axis(z,axis = 1)
(cmd)Traceback (most recent call last):
(cmd)  File "<stdin>", line 1, in <module>
(cmd)AttributeError: 'module' object has no attribute 'max_axis'

while the API shows:
**mxnet.ndarray.max(arr,** axis=None, keepdims=False)**
Take the maximum of the array along given axises. The semantic strictly follows numpy’s document.

Parameters:	
arr (Array) – the array to be reduced
**axis** (int or list(int), optional) – along which axis to do reduction
keepdims (bool) – whether the reduced axis should be kept in the final shape
Returns:	
out – The reduced NDArray.

**So how can I write a python operator that can benefit from GPU?**

**Comment by zdltheone** [comment]
@mli

**Comment by sxjscience** [comment]
@zdltheone Are you using the latest version of MXNet? `max_axis` is some newly added feature.

**Comment by zdltheone** [comment]
I pulled the source code in May 22nd, and complied it with vs2013 .
In fact I don't find the max_axis function in ndarray.py ...

I'm new to mxnet and there's few doc to help me, so I beg your pardon if disturded you.
@sxjscience

**Comment by zdltheone** [comment]
when use cpu version,like:
(cmd)>>> z = mx.nd.ones((3,4),mx.gpu(0))
(cmd)>>> z.context
(cmd)gpu(0)
(cmd)>>> z = z.asnumpy()
(cmd)>>> z.max(axis = 1)
(cmd)array([ 1.,  1.,  1.], dtype=float32)

It sems everything goes ok, but when using GPU, problem occurs.
@sxjscience

**Comment by sxjscience** [comment]
@zdltheone Thanks for reporting! I'm checking locally for these operators. `sum_axis`, `max_axis` and `min_axis` are introduced in June. https://github.com/dmlc/mxnet/blob/master/src/operator/broadcast_reduce_op-inl.h#L360-L385 and they are operators written in the C++ side.

**Comment by zdltheone** [comment]
Ok, I'll try the latest version. And if  the mxnet.ndarray.max() function don't have parameter axis, I think the API on website(http://mxnet.readthedocs.io/en/latest/packages/python/ndarray.html#slice-operations) should be modified :)

**Comment by sxjscience** [comment]
@zdltheone The `mxnet.ndarray.max()` has parameter `axis`. Would you help try the latest version?

**Comment by zdltheone** [comment]
Ok, many thanks to you!

**Comment by Godricly** [comment]
@sxjscience latest one works for me.

**Comment by zdltheone** [comment]
Everything goes well with the latest version :) @sxjscience
