### ISSUE TITLE
Cannot Import mxnet from graphlab

### ISSUE THREAD

**Issue by amrfarid140** [dmlc/mxnet#2426]
Hi ,

I am trying to execute : 
`from graphlab import mxnet `
which is giving the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name mxnet

```

but when I do : 

`import mxnet`

it imports mxnet but gets stuck at : 

```
dataiter = mx.io.SFrameIter(data, data_field=features, label_field='output',
                            data_name='data', label_name='lr_label',
                            batch_size=1)
```

giving error : 

`AttributeError: 'module' object has no attribute 'SFrameIter'`

**Comment by antinucleon** [comment]
For graphlab support, please ask in graphlab forum. Thank you.
