### ISSUE TITLE
Why is the gpu version of mlp.py in example/mnist slower than the cpu verision?

### ISSUE THREAD

**Issue by loveisp** [dmlc/mxnet#244]
I change mx.cpu() in 
model = mx.model.FeedForward(
    ctx = mx.cpu(), symbol = mlp, num_round = 20,
    learning_rate = 0.1, momentum = 0.9, wd = 0.00001)
to mx.gpu(), but it makes 3x slower than the original version. Why?

**Comment by antinucleon** [comment]
What is your CPU type and what is your GPU type?

**Comment by loveisp** [comment]
My CPU is i7 4790, GPU is GTX 970.

**Comment by antinucleon** [comment]
Should not be. What is your system and is your GPU occupied by other task? While running program, you can type ```nvidia-smi``` to see the GPU-Util value

**Comment by antinucleon** [comment]
Also, have you tested other example? As mlp.py is a tiny example, it won't fully use GPU. Please check CIFAR-10 example and report the speed.

**Comment by loveisp** [comment]
My system is Win 8. I think my GPU is not occupied by other task. I just compiled it and tested it with mlp. I'll test other examples and give some feedback later.

**Comment by antinucleon** [comment]
OK. Thanks. We don't have Windows computer so once we can touch WIndows computer we will have a look too. Thanks for your info.

**Comment by loveisp** [comment]
Thanks. I will try it on Ubuntu too.

**Comment by mli** [comment]
Can you report the performance number for cifar?

**Comment by loveisp** [comment]
Sorry for my late reply. I tested cifar-10 in example/cifar10, GPU is much faster than CPU on this data set.
GPU gets the speed of about 460 samples/sec, CPU only 6 samples/sec.
So as @antinucleon said, mlp.py is too tiny to fully use GPU.
Thank you both for helping @mli @antinucleon .

**Comment by tqchen** [comment]
I am glad it works our for you.

**Comment by mli** [comment]
we'd better have a detailed doc about the performance

**Comment by pluskid** [comment]
I agree. Providing a reference number (e.g. how many samples/sec on a specific CPU / GPU type, etc.) in the doc or just comments of each example should be very helpful for users to digest whether they are able to run the system properly.
