### ISSUE TITLE
'undefined symbol: cblas_sgemm' error when running mnist example

### ISSUE THREAD

**Issue by sunshineatnoon** [dmlc/mxnet#245]
Hi, I have successfully build mxnet and install python package, but when I try to run the mnist example:
```
python example/mnist/mlp.py
```
I got this error:
```
Traceback (most recent call last):
  File "example/mnist/mlp.py", line 2, in <module>
    from data import mnist_iterator
  File "/home/xuetingli/Documents/dmlc/mxnet/example/mnist/data.py", line 9, in <module>
    import mxnet as mx
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 438, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/libmxnet.so: undefined symbol: cblas_sgemm
```
I'm on CentOS 7 and I have installed blas and atblas via:
```
sudo yum install blas blas-devel atlas atlas-devel
```
Does anyone know how to solve this? Thx!

**Comment by tqchen** [comment]
This is likely due to an linker error. Try to change the BLAS options in config.mk to atlas, or blas to see what works for you

**Comment by sunshineatnoon** [comment]
@tqchen Do I need to change the variable USE_BLAS to the path of my atblas or do I have to add a new variable USE_BLAS_PATH to my atblas path?

**Comment by tqchen** [comment]
I think only changing USE_BLAS should be fine. As lonng as the atlas is in LD_LIBRARY_PATH

**Comment by sunshineatnoon** [comment]
I changed the config.mk file like this:
```
# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
USE_STATIC_MKL = NONE
USE_BLAS = atlas
```
Then set the LD_LIBRARY_PATH to  `/usr/lib4/atlas`
But when I rebuild mxnet, I got this error:
```
/usr/bin/ld: cannot find -lcblas
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1
```

**Comment by tqchen** [comment]
You might also want to set LIBRARY_PATH as well. LD_LIBRARY_PATH is used for runtime search of libraries, LIBRARY_PATH is used for compile time search

**Comment by sunshineatnoon** [comment]
Tried this too, no luck:
```
export LIBRARY_PATH=/usr/lib64/atlas
```
I also tried openblas, which I installed at /usr/local/lib and /usr/local/include, this time the make command doesn't give me any error, but when running the mnist example, I still get this error:
```
OSError: /usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/libmxnet.so: undefined symbol: cblas_sgemm
```

**Comment by sunshineatnoon** [comment]
By using Openblas and running `cd python; python setup.py develop --user` again, now I can run the mnist example. Thanks for your help~

**Comment by raygit** [comment]
Hi guys, i'm using this mxnet and ran into this same incident; was wondering if there was a note on that, would be very helpful
