### ISSUE TITLE
How to make matrix multiplication in Python without numpy

### ISSUE THREAD

**Issue by cherishlc** [dmlc/mxnet#2453]
In [how to create new layers](http://mxnet.readthedocs.io/en/latest/how_to/new_op.html), there is an example to do define a new layer, but it uses numpy to calculate the result and convert it back to mxnet format. 
Is there any way to do it within mxnet framework in Python？

And where is  the matrix multiplication operation for Python？ Since deep learning need affine layer which uses matrix multiplication， there must be the operation both for CPU and GPU. Why not create an interface for Python?

**Comment by piiswrong** [comment]
mx.nd.dot

**Comment by Godricly** [comment]
The data are stored as ndarray in those operators, so u can handle them with ndarray functions. go check mshadow documents.

**Comment by cherishlc** [comment]
Thanks,,  mx.nd.dot   works,, but I can't find it in the python file.
Is there something like  matrix inverse?    And document for these functions?

Hope that these functions could be  used like  A.dot(B);


The mshalow document I find is all about C++ and expression template,  is there any document  about the Python interface?

**Comment by Godricly** [comment]
[guide](https://github.com/dmlc/mshadow/tree/master/guide) in github.

**Comment by sxjscience** [comment]
@cherishlc Check the doc here http://mxnet.readthedocs.io/en/latest/packages/python/ndarray.html

**Comment by cherishlc** [comment]
thanks~ @sxjscience

**Comment by cherishlc** [comment]
I saw that,, but it's hard to read. Just want to be an end user. @Godricly
