### ISSUE TITLE
Docs of SimpleOp with extra arguments

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#2461]
The current doc system has some problem in generating descriptions for these simple OPs. E.g, http://mxnet.readthedocs.io/en/latest/packages/python/symbol.html#mxnet.symbol.transpose, http://mxnet.readthedocs.io/en/latest/packages/python/symbol.html#mxnet.symbol.sum_axis. Is there a fix?

**Comment by tqchen** [comment]
yes, there is a fix, see https://github.com/dmlc/mxnet/blob/master/src/operator/sample_op-inl.h#L108

**Comment by sxjscience** [comment]
Great!
