### ISSUE TITLE
Incremental Forward

### ISSUE THREAD

**Issue by zeeeyang** [dmlc/mxnet#2481]
Hi all, 

Currently, **Executor.Forward** always forward from the beginning nodes to the last node of the symbolic graph. Is it possible to support **incremental forward** which forwards from the last executed node to the last node of current graph?

For example,  here are two heavily overlapped forward in code below. 
```python
import mxnet as mx
A = mx.sym.Variable('A')
B = mx.sym.Variable('B')
C = A * B
D = mx.sym.Variable('D')
E = C + D
G = mx.sym.Group([E, C])
a = mx.nd.empty(1)
b = mx.nd.ones(1)
d = mx.nd.ones(1)
executor = G.bind(ctx=mx.cpu(), args={'A': a, 'B': b, 'D': d})
executor.forward() # Foward1
a[:] = 10
executor.forward()
e_out = executor.outputs[0]
c_out = executor.outputs[1]
print e_out.asnumpy()
print c_out.asnumpy()
F = E * C
executor = F.bind(ctx=mx.cpu(), args={'A': a, 'B': b, 'D': d})
executor.forward() #Forward2
print executor.outputs[0].asnumpy()
``` 

Currently,  the executor will evaluate `C` and `E` twice, which is not efficient in some situations. By using **incremental forward**, the executor can directly forward from `C` and `E` to `F`.  

This mechanism is supported by a very popular neural network programming toolkit [clab/cnn](https://github.com/clab/cnn) in NLP community.  With the help of incremental forward, it might become easier for MXNet to build dynamic graph depending on the intermediate evaluations.  For example, 

1.  We can decide to compose `F` depending on the output of `E`.  If `E` is greater than 10, we can let `F = E * C`, otherwise we can set `F = E * E`. 
2.  We can support sequence to sequence learning more flexibly. Currently, MXNet is no problem for the Encoder side. However, using current api is not convenient (or efficient) for the Decoder LSTM  since the Decoder depends on dynamic probability outputs to choose the next input, which involves a  forward request in every generation step.   
3.  We can support more advanced requests, such as beam-search and tree-structured LSTMs, in a efficient way.

**Comment by Godricly** [comment]
check this issue #2462. I think its on the todo list.

**Comment by piiswrong** [comment]
Instead of 
```
F = E * C
executor = F.bind(ctx=mx.cpu(), args={'A': a, 'B': b, 'D': d})
```
Use
```
F = mx.sym.Variable('C') * mx.sym.Variable('E')
executor = F.bind(ctx=mx.cpu(), args={'E': executor.outputs[0], 'C': executor.outputs[1]})
```
Decompose the graphs so you can forward each separately

**Comment by tqchen** [comment]
What you can do is to break the graph into parts, and use the imperative API to generate the sequence. So you can directly unroll on the imperative API. Take LSTM decoder for example, what we can do is to build a LSTM cell and dynamically unroll it like in torch.

The module API can help doing this. For example https://github.com/tqchen/mxnet-gan uses two modules to form a generator model. One for generator, another for discriminator, and alternate between the two

**Comment by zeeeyang** [comment]
@piiswrong  Thank you.  This solution makes sense. However, it slightly damages the benefits of AutoDiff. We need to manually do backward twice here instead of just calling backward of the last executor.

**Comment by zeeeyang** [comment]
@tqchen  Thank you. I got the main idea and will try.
