### ISSUE TITLE
 how to predict the datasets, I have trained cifar-10. Need your help!!!

### ISSUE THREAD

**Issue by zhenzhen1022** [dmlc/mxnet#2484]
I have successfully trained the cifar-10, then how to predict? I have no idea, Thx for your help!!!

**Comment by CNevd** [comment]
load your model and use mode.predict(X=test)

**Comment by zhenzhen1022** [comment]
I am newer for mxnet or say DL. so can you explain more details, where I can find the model and what can I do to run the code? write a new script? thx!!

**Comment by CNevd** [comment]
see here https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L40 to save model when training and here https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L29 to load model and then you can do predict with model.predict(X=test) where test is the dataiter

**Comment by zhenzhen1022** [comment]
thx so much! another question is what's .ipynb file for?

**Comment by zhenzhen1022** [comment]
I trained cifar-10 successfully like this 'python train_cifar10.py --batch-size 128 --lr 0.1 --lr-factor .94 --num-epoch '  so I think I have saved model and loaded model. and next how to predict with model.predict(X=test)?

**Comment by zhenzhen1022** [comment]
thx for your help, now i can use 'cifar10.ipynb' step by step and predict successfully. and the next is I need to find out the predict result, as i know in mxnet the format of images is '.rec', so what's the output format, and what I need to do to convert to one format such as '.jpg' or '.bmp', that represent the result we can see directly? waiting for your help, THx.

**Comment by pluskid** [comment]
Closing for now. Please feel free to re-open if needed.
