### ISSUE TITLE
[R] Setup Travis Test

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#249]
See reference of xgboost repo https://github.com/dmlc/xgboost

Because R-travis requires sudo. Let us only do it on OSX(I know this sounds strange:), where we have the sudo right. Current linux build uses container build that disables sudo

**Comment by tqchen** [comment]
@hetong007 Let us know if you could help. Since you setup the travis for xgboost

**Comment by tqchen** [comment]
related to #457

**Comment by terrytangyuan** [comment]
Oh should've seen this issue earlier. Yes there must be a `sudo` during linux build. Is it that if we enable `sudo` then some other builds could fail?

**Comment by tqchen** [comment]
If sudo is disabled, then travis uses [container based build](http://docs.travis-ci.com/user/workers/container-based-infrastructure/), which caches the data and make things faster.
 
Unfortunately we cannot partially enable sudo, and I guess OSX test should be sufficient for most cases(usually OSX is the place to fail easier)

**Comment by terrytangyuan** [comment]
Got it. Yeah let's stick with just OSX for now.
