### ISSUE TITLE
[Windows] Build Instruction

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#250]
@happynear Now that the cmake has been checked in. Are you interested in try it out and contribute  an instruction on windows build to https://github.com/dmlc/mxnet/blob/master/doc/build.md ?

Thanks

**Comment by happynear** [comment]
Problems you may come across when configuring mxnet in Visual Studio
--------------------
1. MXNet uses lots of C++11 features, which is not totally supported by Visual Studio 2013. Visual Studio 2015 provides better support for C++11/14, but it cannot work with any version of CUDA. 

Fortunately, Microsot has provided a patch, allowing VS2013 to support more C++11/14 features. The official page is [here](http://www.microsoft.com/en-us/download/details.aspx?id=41151). 

Someone has reported that the patch cannot be installed successfully on their computer. I have archived and uploaded the files installed on my computer. You can download it from [OneDrive](http://1drv.ms/1RApcXr) or [BaiduYun](http://pan.baidu.com/s/1dVnJo).

2. There are three third-party libraries should be installed, including [OpenCV](http://sourceforge.net/projects/opencvlibrary/files/opencv-win/3.0.0/opencv-3.0.0.exe/download), [CuDNN](https://developer.nvidia.com/cudnn) and [OpenBlas](http://sourceforge.net/projects/openblas/files/v0.2.14/). You can download and install them from the official sites, or directly download them from [OneDrive](http://1drv.ms/1hzq9Cq).

It is suggested to create a `3rdparty` or `thirdparty` folder in the root of mxnet, and put the thirdparty libraries in each subfoldes, such as `./3rdparty/OpenBLAS`. 

3. If your GPU's compute capability is less or equal to 2.1, you should remove `USE_CUDNN` when configuring CMake. 

Be careful that CMake will not give any warning or error if you haven't set the path of CUDNN.

4. When you are using Debug mode, please modify the variable `vs_configuration` defined in `./python/mxnet/libinfo.py` from `Release` to `Debug`.

5. [PTVS](https://github.com/Microsoft/PTVS/releases) is a very powerful tool for using python in Visual Studio. I suggest you to intall it.

**Comment by mli** [comment]
very nice instructions. thanks! we can provide a link on build.md to refer it.

**Comment by ommiissyu** [comment]
I use cmake to build mxnet with cuda 7.0 and visual studio 2013. I got the error:

nvcc error : 'ptxas' died with status 0xC0000005

@happynear , did you get the same error message?

**Comment by hjk41** [comment]
We seem to have trigger a bug in NVCC. Let me try to reproduce.

On Tue, Oct 13, 2015 at 4:37 PM, Leo Xiao <notifications@github.com> wrote:

> I use cmake to build mxnet with cuda 7.0 and visual studio 2013. I got the
> error:
>
> nvcc error : 'ptxas' died with status 0xC0000005
>
> @happynear <https://github.com/happynear> , did you get the same error
> message?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/250#issuecomment-147648178>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by happynear** [comment]
@ommiissyu 
I haven't seen this. But I got this error when I was configuring cxxnet. 
Add `-Xptxas -O1` to `CUDA C/C++ -> Command Line`, can solve this problem.

**Comment by hjk41** [comment]
It seems that OpenBLAS does not provide static library on Windows. And libopenblas.dll depends on libgcc_s_seh-1.dll, which is part of MinGW gcc. @happynear how did you solve the problem? I do have Cygwin, but I can't find that file. Plus, I don't think it is a good idea to force user to install Cygwin just to use mxnet.

**Comment by antinucleon** [comment]
I remember Openblas provided libgcc file, so there is no need to install
cgwin or mingw. I tested Cxxnet before,

**Comment by happynear** [comment]
@hjk41,
You can download ming32 dlls form http://sourceforge.net/projects/openblas/files/v0.2.14/ . It is at the bottom of the list.
I will add them to the `mxnet_thirdparty.zip`, too.

**Comment by tqchen** [comment]
Thanks for the discussions, the current build instruction is now here http://mxnet.readthedocs.org/en/latest/build.html#windows

**Comment by gouchangjiang** [comment]
I have acrossed the error "OpenBLAS\include\cblas.h(60):error: identifier "openblas_complex_float" is undefined" when compiled in VS, I have compiled OpenBLAS, I don't know how to solve it. Thanks in advance for any help.

**Comment by hjk41** [comment]
*openblas_complex_float* should have been defined in line 113 of
OpenBLAS/include/openblas_config.h. Could you check if you have this file,
and if the "#ifdef" macros function properly?

On Sun, Nov 22, 2015 at 5:34 PM, gouchangjiang <notifications@github.com>
wrote:

> I have acrossed the error "OpenBLAS\include\cblas.h(60):error: identifier
> "openblas_complex_float" is undefined" when compiled in VS, I have compiled
> OpenBLAS, I don't know how to solve it. Thanks in advance for any help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/250#issuecomment-158740070>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by gouchangjiang** [comment]
thanks for your help. I have changed my OS to ubuntu. So I don't know whether your suggestion is a good solution. Anyway, thanks.

**Comment by bianliangpai** [comment]
Which folder should I extract the "Microsoft Visual C++ Compiler Nov 2013 CTP.zip" file to? 
Thanks in advance for any help.

**Comment by hjk41** [comment]
you are supposed to copy the contents of that zip file into your VC 2013
folder and replace the existing files

**Comment by bianliangpai** [comment]
@hjk41 thanks
