### ISSUE TITLE
L1 regularization

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#2509]
Hi, 

is there any way to get L1 regularization? 

There is this mxnet.symbol.IdentityAttachKLSparseReg but I cannot replicate the same accuracy as I did with the LogisticRegression in Scikit Learn with L1 regularization..

**Comment by piiswrong** [comment]
you can write a new optimizer. Like in mx.optimizer.sgd

**Comment by freddycct** [comment]
Can I use it in the high level API by changing the default optimizer, e.g. model = mx.model.FeedForward, model.fit

or do I have to use the mod = mx.mod.Module(symbol), mod.fit(...) ?

**Comment by freddycct** [comment]
I almost implemented L1 regularization, the final thing I need now is to set the weights that are close to 0 to be zero. What's the best way to do it for mx.ndarray without converting back and forth to numpy array?
