### ISSUE TITLE
param_ in CustomOp

### ISSUE THREAD

**Issue by chenjx1005** [dmlc/mxnet#2512]
I want to write a customop like `example/numpy-ops/custom_softmax.py`. How can I add some param_ in my subclass of `mx.operator.CustomOp`? @piiswrong

**Comment by tqchen** [comment]
see examples in https://github.com/tqchen/mxnet-gan/blob/master/mxgan/custom_ops.py

**Comment by chenjx1005** [comment]
thank you for your quick reply! I will try it.

**Comment by tqchen** [comment]
in short, the property will receive the keyword arguments as you passed to customop, however, the values are converted to string, so you need to convert them back.
