### ISSUE TITLE
No operator like batch_matmul in tensorflow

### ISSUE THREAD

**Issue by jennyzhang0215** [dmlc/mxnet#2515]
Now there exists only one operator 'dot' for matrix multiplication, i.e.,  https://github.com/dmlc/mxnet/blob/master/src/operator/matrix_op-inl.h#L197-L227 .

When I tried to implement MemN2N using mxnet, I found there is no operator like batch_matmul in tensorflow, https://github.com/carpedm20/MemN2N-tensorflow/blob/master/model.py#L71 , https://www.tensorflow.org/versions/r0.9/api_docs/python/math_ops.html#batch_matmul .

Is there any plan to implement this operator?

**Comment by tqchen** [comment]
@sxjscience do you have any idea how we can implement it natively with the blas kernels we have? The simplest way will do explicitly slice then matrix mult, but I wonder if there are better approaches

**Comment by antinucleon** [comment]
I have done similar things before, we can use cublas batch function, should
not be hard.

On Thu, Jun 23, 2016 at 10:38 AM Tianqi Chen <notifications@github.com>
wrote:

> @sxjscience <https://github.com/sxjscience> do you have any idea how we
> can implement it natively with the blas kernels we have? The simplest way
> will do explicitly slice then matrix mult, but I wonder if there are better
> approaches
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2515#issuecomment-228124984>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13kgFc8DSvVckUhJQeQOBL6Pryu_2ks5qOsSjgaJpZM4I89fd>
> .
>
-- 
Sent from mobile phone

**Comment by sxjscience** [comment]
@tqchen @antinucleon Yes, I'm thinking to directly call the BLAS kernels. I can ask @jennyzhang0215 to do that if it's not very hard.

**Comment by sxjscience** [comment]
Supported by https://github.com/dmlc/mxnet/pull/2615
