### ISSUE TITLE
DType initial

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#2522]
In [model.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L483), the parameters are initialized using nd.zeros with default mx_real_t. then it calls ndarray member function to init those values(I don't find these functions so I assumes they are from mshadow). So now it shares same problem in dropout layer in needing DType random number generation [issue](https://github.com/dmlc/mshadow/issues/138).
The first one can be fixed using infertype return values.

**Comment by piiswrong** [comment]
yes infertype should be used

**Comment by Godricly** [comment]
I think I can fix this issue in _init_param, but other problems rises. To be able to infer the  parameters type, you need to pass in data and label type. So some changes like provide_type or sth are needed in dataIter.

I'll try to fix fit and __train_multi_machine fucntion in model.py, but I'm not sure with score, predict and model save&load.
Also the executor_manager.py needs some modifications to get DType works.

I'm not familiar with new module api, so I'm not sure what changes are need for that part. 

We need to create a TODO list after some evaluation.

I see some people are using pascal GPU in issues list, so more FP16 issues are coming. 
@tqchen @pluskid @vchuravy

**Comment by Godricly** [comment]
Half random number issue is bypassed.
