### ISSUE TITLE
how to ignore padded data when using bucketing in RNN

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#2527]
for sequences that does not fill up the whole RNN in some buckets, how does the layers know how to ignore the padded data? My padded data are all zeros.

**Comment by Godricly** [comment]
It all depends how your last layer handles ur padded label.

**Comment by freddycct** [comment]
Oh, only softmaxoutput allows ignore labels, but other output layer e.g. LinearRegression and LogisticRegression does not allow ignore labels.

**Comment by Godricly** [comment]
Ye...So if ur using those layers, u need to do some modification. I think the padded labels are also not  considered in metric. I mentioned it in #2410, maybe u need to double check on that part and correct me please if I made it wrong.

**Comment by freddycct** [comment]
solved by #3016
