### ISSUE TITLE
install mxnet on ubuntu errors

### ISSUE THREAD

**Issue by xtuyaowu** [dmlc/mxnet#2530]
make -j4                                                                                                                                                                  g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [build/src/operator/elementwise_binary_broadcast_op.o] Error 4
make: *** Waiting for unfinished jobs....

**Comment by jonasrla** [comment]
I don't remember running having problems installing on Ubuntu. What version are you using?
Try running one or another
* make -j
* make

the -j allows make to process in parallel. In your case it limits to 4 jobs in parallel.

**Comment by xtuyaowu** [comment]
hi jonasrla,
   try make is ok
thanks
