### ISSUE TITLE
Switching label encoding

### ISSUE THREAD

**Issue by jonasrla** [dmlc/mxnet#2533]
Wouldn't it be nice to have a quick way to switch labels from single lined encoding to matrix encoding, like 
[1,0,2,3,3,1]
to
[[0, 1, 0, 0],
 [1, 0, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 1, 0],
 [0, 1, 0, 0]]

That would be really useful to implement #1810.

**Comment by sxjscience** [comment]
There is currently an NDArray function called `onehot_encode`. You can do the following
```python
import mxnet.ndarray as nd

encoding_out = nd.empty((6, 4))
a = nd.array([1,0,2,3,3,1])
nd.onehot_encode(a, encoding_out)
print(encoding_out.asnumpy())
```

**Comment by jonasrla** [comment]
awesome! I didn't new the keywords. Thank you for the heads up!
