### ISSUE TITLE
[caffe_converter]why is it only softmax layer can be specified as output layer?

### ISSUE THREAD

**Issue by voidrank** [dmlc/mxnet#2543]
I want to know why output layer must be specified as softmax ?
https://github.com/dmlc/mxnet/blob/f857c1ebfbf1e1d6fd289e8a5f24bd8bb37e00b5/tools/caffe_converter/convert_symbol.py#L133
Many structures such like FCN(fully convolution network ends with crop layer) ends with other type layer.
Is there any special reason for that?

**Comment by piiswrong** [comment]
That's due to the converter doesn't cover all cases yet. You are welcome to add features to it.

**Comment by ozabluda** [comment]
I think this was fixed.
