### ISSUE TITLE
Run MXNET with Muti-machine

### ISSUE THREAD

**Issue by fhowen** [dmlc/mxnet#255]
HI，Is it possible to show some examples of how to run mxnet on multi-machines？
Thx

**Comment by mli** [comment]
will be there next week

**Comment by fhowen** [comment]
Looking forward to it

**Comment by tqchen** [comment]
Here is the example, https://mxnet.readthedocs.org/en/latest/distributed_training.html

we are also actively look for contributors to try and improve it #533
