### ISSUE TITLE
BatchNorm error

### ISSUE THREAD

**Issue by ommiissyu** [dmlc/mxnet#2560]
hi,

I use mxnet with cudnn v5 to train a model, I find that if I use gpu, the result is right, but if i use cpu, the result is totally wrong. I checked layer by layer, I found that it was caused by cudnn v5's BatchNorm implementation. If I use cudnn v4, the cpu and gpu's result are the same.

**Comment by sxjscience** [comment]
Related to https://github.com/dmlc/mxnet/issues/2553. Have you used GPU (with CuDNN-V5) for training and CPU for testing? The current BatchNorm operator may choose different implementations for these two cases.
