### ISSUE TITLE
Problem building MXNET with MINGW on windows

### ISSUE THREAD

**Issue by cisou98** [dmlc/mxnet#2570]
Hi, I am trying to build MXNET with MINGW on windows, but I run into an error :

[err.txt](https://github.com/dmlc/mxnet/files/339082/err.txt)

Any ideas on how I can prevent that ?

Thanks.

**Comment by freddycct** [comment]
I think it can only be compiled on Visual Studio 2013.

**Comment by thirdwing** [comment]
MXNet can be compiled using MinGW, but it is a little time-consuming and requires some knowledge of MinGW.

I don't recommend doing this unless you have much experience in MinGW.

Is there any reason that you want to use MinGW?

**Comment by cisou98** [comment]
Yes, actually I built all my other librairies with MinGW. If you don't mind, I am interested in a way to build MXNet that way. Thanks.

**Comment by thirdwing** [comment]
The reason I don't recommend using MinGW is the different distributions of MinGW are somewhat inconsistent with each other and normally I build MinGW by myself.

From your log, maybe you can comment out the line below and try again.

https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/base.h#L114

BTW, please use `make` not `make -j4`. We can have a more clear log in case you met new problems

**Comment by cisou98** [comment]
I tried to comment out the line you specified. I was functional for my previous error. Unfortunately I ran into another error.. I am afraid building with MinGW is impossible 
[err.txt](https://github.com/dmlc/mxnet/files/344443/err.txt)

**Comment by thirdwing** [comment]
Using MinGW, you can only compile the CPU version. This is the constraint from Nividia. Not from us.
