### ISSUE TITLE
mxnet install problem on R3.3.1 

### ISSUE THREAD

**Issue by luoruisichuan** [dmlc/mxnet#2572]
hi, I install R3.3.1 on C:\program files, and then use follow command on R console
"
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")
"
it is OK.
and then I use follow commands in DOS command enviroment ,
"
Rscript -e "install.packages('devtools', repo = 'https://cran.rstudio.com')"
"
and it is OK at the beginning, the log like this

> 
C:\Program Files\R\R-3.3.1\bin\x64>Rscript -e "install.packages('devtools',
 = 'https://cran.rstudio.com')"
'mime', 'curl', 'openssl', 'R6', 'httr', 'memoise', 'whisker', 'rstudioapi',
t2r', 'withr'

  :
           binary source needs_compilation
rstudioapi    0.5    0.6             FALSE

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/mime_0.4.zip'
Content type 'application/zip' length 37402 bytes (36 KB)
==================================================
downloaded 36 KB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/curl_0.9.7.zip'
Content type 'application/zip' length 4394464 bytes (4.2 MB)
==================================================
downloaded 4.2 MB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/openssl_0.9.4.zip'
Content type 'application/zip' length 3001944 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/R6_2.1.2.zip'
Content type 'application/zip' length 271200 bytes (264 KB)
==================================================
downloaded 264 KB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/httr_1.2.0.zip'
Content type 'application/zip' length 281275 bytes (274 KB)
==================================================
downloaded 274 KB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/memoise_1.0.0.zip'
Content type 'application/zip' length 23310 bytes (22 KB)
==================================================
downloaded 22 KB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/whisker_0.3-2.zip'
Content type 'application/zip' length 64713 bytes (63 KB)
==================================================
downloaded 63 KB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/git2r_0.15.0.zip'
Content type 'application/zip' length 3040289 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/withr_1.0.2.zip'
Content type 'application/zip' length 41155 bytes (40 KB)
==================================================
downloaded 40 KB

URLhttps://cran.rstudio.com/bin/windows/contrib/3.3/devtools_1.12.0.zip'
Content type 'application/zip' length 431842 bytes (421 KB)
==================================================
downloaded 421 KB

'mime'MD5
'curl'MD5
'openssl'MD5
'R6'MD5
'httr'MD5
'memoise'MD5
'whisker'MD5
'git2r'MD5
'withr'MD5
'devtools'MD5

        C:\Users\Administrator\AppData\Local\Temp\RtmpGa9X3W\downloaded_pack

'rstudioapi'

URLhttps://cran.rstudio.com/src/contrib/rstudioapi_0.6.tar.gz'
Content type 'application/x-gzip' length 12024 bytes (11 KB)
==================================================
downloaded 11 KB

but then there is problem like following,

> downloaded 421 KB

'mime'MD5
'curl'MD5
'openssl'MD5
'R6'MD5
'httr'MD5
'memoise'MD5
'whisker'MD5
'git2r'MD5
'withr'MD5
'devtools'MD5

        C:\Users\Administrator\AppData\Local\Temp\RtmpGa9X3W\downloaded_packages

'rstudioapi'

URLhttps://cran.rstudio.com/src/contrib/rstudioapi_0.6.tar.gz'
Content type 'application/x-gzip' length 12024 bytes (11 KB)
==================================================
downloaded 11 KB

'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

        'C:\Users\Administrator\AppData\Local\Temp\RtmpGa9X3W\downloaded_package
s'
Warning messages:
1: '"C:/Program Files/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R
-3.3.1\library" C:\Users\ADMINI~1\AppData\Local\Temp\RtmpGa9X3W/downloaded_packa
ges/rstudioapi_0.6.tar.gz'1
2: In install.packages("devtools", repo = "https://cran.rstudio.com") :
  'rstudioapi'B0

and then I can't find the R-package, and of course can't use the following commands
"
Rscript -e "install.packages('devtools', repo = 'https://cran.rstudio.com')"
cd R-package
Rscript -e "library(devtools); library(methods); options(repos=c(CRAN='https://cran.rstudio.com')); install_deps(dependencies = TRUE)"
cd ..
make rpkg
"

what is the problem?

futthermore , may I downloat the file "mxnet_0.7.zip" directly(https://github.com/dmlc/drat/tree/gh-pages/bin/windows/contrib/3.2) and install it in R dispite above commands?

thank you help very much!

**Comment by luoruisichuan** [comment]
@thirdwing 
may I download the file "mxnet_0.7.zip" directly(https://github.com/dmlc/drat/tree/gh-pages/bin/windows/contrib/3.2) and install it in R dispite above commands? just like install  other packages  from local files

**Comment by thirdwing** [comment]
Sorry I don't understand your problem.

You said
>hi, I install R3.3.1 on C:\program files, and then use follow command on R console
>"
>install.packages("drat", repos="https://cran.rstudio.com")
>drat:::addRepo("dmlc")
>install.packages("mxnet")
>"
>it is OK.

Since you can install it using `drat`, why did you try to install again using `devtools`?

Any specific reason?

**Comment by luoruisichuan** [comment]
I install Mxnet following the procedure of "http://mxnet.readthedocs.io/en/latest/how_to/build.html"(the part of R package installation), but get above problem.
and I get some information  from the following address "http://stackoverflow.com/questions/37110169/issue-in-installation-of-mxnet-package-in-r" , and get the following content 
"I was able to install it successfully by first downloading its zip file from the following link

https://github.com/dmlc/drat/tree/gh-pages/bin/windows/contrib/3.2

and then installing it using RStudio."

so,  my question is that may I download the file "mxnet_0.7.zip" directly(https://github.com/dmlc/drat/tree/gh-pages/bin/windows/contrib/3.2) and install it in R after Installing pre-built packages on Windows,  just like installing other packages from local files.
thanks for your help very much!

**Comment by thirdwing** [comment]
I think you misunderstood something.

If you installed the package using drat, everything is done.

You don't need to do anything more.

**Comment by luoruisichuan** [comment]
thanks for your help !

**Comment by yib2** [comment]
Warning in install.packages :
  URL 'http://dmlc.ml/drat/src/contrib/mxnet_0.7.tar.gz': status was '404 Not Found'

**Comment by thirdwing** [comment]
We don't host the R package for Linux. Only prebuilt package for Windows and OSX are host here.

**Comment by yib2** [comment]
Never mind. I have figured it out.
