### ISSUE TITLE
mxnet-git building error UBUNTU 16.04

### ISSUE THREAD

**Issue by StevenLOL** [dmlc/mxnet#2577]
git clone https://github.com/dmlc/mxnet.git
cd mxnet/
make
Makefile:23: mshadow/make/mshadow.mk: No such file or directory
Makefile:24: /data/gits/mxnet/dmlc-core/make/dmlc.mk: No such file or directory
Makefile:85: /data/gits/mxnet/ps-lite/make/ps.mk: No such file or directory
make: *** No rule to make target '/data/gits/mxnet/ps-lite/make/ps.mk'.  Stop.

**Comment by Godricly** [comment]
are those folders empty?

**Comment by zhangqianhui** [comment]
git again .

**Comment by antinucleon** [comment]
git clone --recursive https://github.com/dmlc/mxnet.git

**Comment by wyz2016** [comment]
I re-git mxnet.git and used --recursive , but it doesn't works. Then, I find an answer:
link: https://stackoverflow.com/posts/48272520/edit, and it works for me.
```
git clone --no-checkout https://github.com/apache/incubator-mxnet
cd incubator-mxnet
git checkout v0.7.0 -b v0.7.0
git submodule update --init
```

**Comment by srividyaketharaju** [comment]
It means you have not cloned mxnet properly.
use git clone --recursive https://github.com/apache/incubator-mxnet.git
