### ISSUE TITLE
ndarray dot product, in batch

### ISSUE THREAD

**Issue by kxf8608** [dmlc/mxnet#2581]
Hi, I know ndarray does dot product by

out_product = mx.ndarray.dot(left,right)

it works when the inputs are 2D or 1D. However, now I wish to compute dot product between a batch of input and weights in batch (e.g. [100, 4,5] * [100, 5, 8]). Is there any good idea how to do it in parallel without writing a loop function please? Thanks.

**Comment by sxjscience** [comment]
We are going to add the operator, see https://github.com/dmlc/mxnet/issues/2515 .

**Comment by kxf8608** [comment]
Thank you for your potential helps. Looking forward to your great contribution. @sxjscience

**Comment by sxjscience** [comment]
@kxf8608 Should be supported by https://github.com/dmlc/mxnet/pull/2615

**Comment by kxf8608** [comment]
so cool!! you really helped a lot! Thank you @sxjscience @jennyzhang0215

**Comment by kxf8608** [comment]
Could you also implement it on ndarray please? I actually wish to do mx.ndarray.batch_dot(left,right) in the forward function of my customized layer. Sorry to bother you again and thanks a lot! @sxjscience
