### ISSUE TITLE
Suggestion: num.round parameter for mxnet predict function

### ISSUE THREAD

**Issue by rfcv** [dmlc/mxnet#2584]
Hello,

Would it be possible to implement a `num.round` parameter for the mxnet `predict` function? By saving the model weights and biases at each round (I don't know if this is already done, but I assume it would not add time to the fitting process nor much size to the model file. Of course it can be made an option as well.), you can then specify the training round at which to stop for fitting the model on new data. This makes it easy to do a gridsearch on the `num.round` parameter, which is why I suggest it.

**Comment by tqchen** [comment]
Unlike in scenarios like gbm, it is not possible to support this option in deep nets
