### ISSUE TITLE
run example/warpctc/lstm_ocr.py

### ISSUE THREAD

**Issue by Yang507** [dmlc/mxnet#2587]

**Comment by Yang507** [comment]
when I `sudo pip install -U Pillow`,I correct my mistake

**Comment by everal** [comment]
@Yang507 
I compiled warp-ctc and mxnet successful.
I add warp-ctc in config.mk, 
but when I run lstm_ocr.py, the problem disapper
/*
sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)
AttributeError: 'module' object has no attribute 'WarpCTC'
*/
Did you have idea about this?

**Comment by Yang507** [comment]
You install warp-catch in which directory, I installed it in my home path,$warp-ctc=/home/user/warp-ctc, the path should match with your path of config.mk, then make mxnet again !

发自我的 iPad

**Comment by everal** [comment]
@Yang507 
I am not install in $HOME path, but I modify the path in the config.mk.

**Comment by Yang507** [comment]
$Home maybe /home/user/, you can try to modify the path in the config.mk. You can follow with me installed warp in your home path and don't change the path in the config.mk if the problem is not be solved.

发自我的 iPad

**Comment by everal** [comment]
@Yang507 
Thanks for you advice, I solve the problem already.
my path is right, but i am not notice that I need copy the config.mk to mxnet_root.
Thank you very much.
