### ISSUE TITLE
Pretrained issue

### ISSUE THREAD

**Issue by Orange15** [dmlc/mxnet#2589]
https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb

this code always give result:
('Top1: ', 'n03000247 chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour')
prob are 0 except an element is 1.

**Comment by piiswrong** [comment]
@antinucleon

**Comment by antinucleon** [comment]
I think it is ```fix_gamma```'s issue. I have updated one but not all.

On Fri, Jul 1, 2016 at 11:20 AM Eric Junyuan Xie <notifications@github.com>
wrote:

> @antinucleon <https://github.com/antinucleon>
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dmlc/mxnet/issues/2589#issuecomment-230015119>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABM13iVSsTRVHWgCCDXd_RonJT7RCzbiks5qRVpggaJpZM4JC4zo>
> .
>
-- 
Sent from mobile phone

**Comment by antinucleon** [comment]
Should be fixed now

**Comment by Orange15** [comment]
@antinucleon yeah, it is ok now.
