### ISSUE TITLE
lower speed on gpu with mxnet-0.7.0 than before

### ISSUE THREAD

**Issue by li-haoran** [dmlc/mxnet#2595]
when i build mxnet successful by CMake + VS 2013(Cudnn v3), i run some examples. but the speed is lower than mxnet-0.5.0?  train cifar10 only 450 examp/second. when i use GPU-Z to see the GPU load, the graph is Serious fluctuation ,not stable than before. when i train on GPU,the CPU use is 100%, what's wrong?

**Comment by tqchen** [comment]
can you give two hashtags of versions that we can compare on? So it is faster for others to reproduce if it is the problem. Thanks

**Comment by li-haoran** [comment]
it is the latest version, i just download a day ago,  the previous version is Dec,2015,i don't remember.

the problem is that the **CPU use is 100%**, so the GPU load is very unstable.

**Comment by tqchen** [comment]
again, it would be nice if you can give two hashtags from commit history https://github.com/dmlc/mxnet/commits/master to help reproduce this problem so it can be investigated in   more detailed way

There are some CPU usages on preprocessors for max throughput so maybe it pressures servers with few cores, here are some possibilities:

-  The Enable of OpenMP in this line, you can try rebuild by removing this line https://github.com/hjk41/mshadow/blob/12299cb06edea97678be96ea359bca5172fe2362/mshadow/tensor_cpu-inl.h#L145

- The number of preprocessing threads in your ImageRecordIter, preprocess_threads which can be reduced

**Comment by li-haoran** [comment]
the latest is: commit 048546d6aff3cd61a5d15755b3a33c936e9f3211

the previous  i don't have the repo,  i just download the zip. sorry  
because the previous version don't have the module and share_mem excutor, so i update.

**Comment by li-haoran** [comment]
thanks for your tips. i remove the line 145   **#pragma omp parallel for ** and the program run well the cifar10 speed is 500+sample/sec on titanx with cudnn v3. the cpu use is stable.

**Comment by li-haoran** [comment]
i also have a problem. when i USE_CUDNN(cudnn v3), train cifar10, thespeed is 500+sample/sec, but when train a FCN model, the loss operator  i write by **numpyOP**, the speed only 0.15 sample/sec.
if i don't use cudnn, train cifar10, the speed only 400 sample/sec, but train my FCN model, the speed is   3.0 samples/sec.  i don't known why

the previous mxnet version (0.5.0)version, i don't use cudnn just follow the bappynear's set, train cifar10 speed is 500+ samples/sec, train my FCN model is 2.8 samples/sec.

**Comment by tqchen** [comment]
Thanks for confirming the problem. Let us move the FCN question to another issue. Maybe some detailed timing is needed
