### ISSUE TITLE
CuDNNConvolution Crash

### ISSUE THREAD

**Issue by yajiedesign** [dmlc/mxnet#2596]
when i use Convolution with CuDNNConvolution, kernel=(3,100),nv driver is crash,some times system is down.
when i set kernel=(3,10).it work fine.
my driver is titan x with 362.00 and 368.39 and cudnnv4 and v5 is all crash.
i am use network is cnn_text_classification

**Comment by piiswrong** [comment]
You mean the system level nvidia driver crashes? This sounds like a cuda/cudnn bug. Let's confirm and report to them.

**Comment by yajiedesign** [comment]
yes, nvidia driver crashes

**Comment by yajiedesign** [comment]
ok .fixed in cudnn 5.1. it now work fine.
