### ISSUE TITLE
Finetune Network

### ISSUE THREAD

**Issue by zmonoid** [dmlc/mxnet#2598]
Is there an good example for finetune a network?

I do something like:
```

optimizer = mx.optimizer.create('sgd',
    rescale_grad=(1.0/32),
    learning_rate      = 0.01,
    momentum           = 0.9,
    wd                 = 0.00001,)


model = mx.model.FeedForward(
    ctx                = mx.gpu(0),
    symbol             = net,
    num_epoch          = 50,
    initializer        = mx.init.Load('../tmp/model/Inception-7-0001.params',default_init mx.init.Xavier(factor_type="in", magnitude=2.34)),
    optimizer          = optimizer)

model.fit(
    X                  = train,
    eval_data          = val,
    kvstore            = kv,
    batch_end_callback = mx.callback.Speedometer(32, 50),
    epoch_end_callback = mx.callback.do_checkpoint('save/inception-finetune'))
model.save(args.dataset)
```

But still got errors:

> Parameter fc1_weight cannot be initialized from loading. Shape mismatch, target (10L, 2048L) vs loaded (1008L, 2048L)

I searched on Google, very few usable cases. Could anyone gives some guideline about how to do this?

Thanks!

**Comment by piiswrong** [comment]
your loaded network doesn't match the network you defined

**Comment by zmonoid** [comment]
@piiswrong  Yes, I want  to change the last FC layer from 1008 to 10.
I tried this way:

```
model = mx.model.FeedForward.load('../tmp/model/Inception-7', 1, ctx=devs)  
print model.arg_params['fc1_weight'].asnumpy().shape

model_new = mx.model.FeedForward.load('./save/inception-v3', 1)
for name, arr in model_new.arg_params.items():
    if 'fc' not in name:
        model_new.arg_params[name] = model.arg_params[name]
    else:
        print arr.asnumpy().shape, model.arg_params[name].asnumpy().shape
```
Then I tried to fit the network:

```
eval_metrics = ['accuracy']

batch_end_callback = []
batch_end_callback.append(mx.callback.Speedometer(batch, 50))
checkpoint = mx.callback.do_checkpoint('save/inception-v3-finetune')
eval_metrics = ['accuracy']

model_new.fit(
    X                  = train,
    eval_data          = val,
    eval_metric        = eval_metrics,
    kvstore            = kv,
    batch_end_callback = batch_end_callback,
    epoch_end_callback = checkpoint)
```

But still got error:

> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-134-42147761fac9> in <module>()
     16     kvstore            = kv,
     17     batch_end_callback = batch_end_callback,
---> 18     epoch_end_callback = checkpoint)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.pyc in fit(self, X, y, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, logger, work_load_list, monitor, eval_batch_end_callback)
    782                             logger=logger, work_load_list=work_load_list, monitor=monitor,
    783                             eval_batch_end_callback=eval_batch_end_callback,
--> 784                             sym_gen=self.sym_gen)
    785 
    786 

/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.pyc in _train_multi_device(symbol, ctx, arg_names, param_names, aux_names, arg_params, aux_params, begin_epoch, end_epoch, epoch_size, optimizer, kvstore, update_on_kvstore, train_data, eval_data, eval_metric, epoch_end_callback, batch_end_callback, logger, work_load_list, monitor, eval_batch_end_callback, sym_gen)
    211     # Now start training
    212     train_data.reset()
--> 213     for epoch in range(begin_epoch, end_epoch):
    214         # Training phase
    215         tic = time.time()

TypeError: range() integer end argument expected, got NoneType.

---

Could you help me to find you why?

**Comment by zmonoid** [comment]
Another problem is that, how to change the learning rate for convolutional layer?

**Comment by piiswrong** [comment]
It's impossible to assign a (1008,2048) matrix to a (10,2048) matrix. You need to init from random. Use mx.init.Mixed.
Per layer learning rate can be set with attr={'lr_mult': '0.01'} in that layer

**Comment by zmonoid** [comment]
Thank you, problem solved :-)
