### ISSUE TITLE
All variables are sliced into batch size when training

### ISSUE THREAD

**Issue by lightingghost** [dmlc/mxnet#2599]
In executor_manager.py line 219, all input variables are sliced into batch-sized tensors. This might cause an error when providing some supporting variables that are not batch-sized. 

For example, If setting the batch_size to 20, and data has shape of (20, 256), while having a supporting variable with shape of (50, 300), the supporting variable will be sliced into (20, 300).

I don't know whether this is a bug or a feature, but it will be good to show that in documents.

**Comment by piiswrong** [comment]
what do you mean by support variable? If they are constants, they shouldn't be provided as input

**Comment by lightingghost** [comment]
For example, I have a matrix as a memory for each batch, the matrix participates in the computation and is not a constant.

**Comment by piiswrong** [comment]
you can duplicate it for n times
