### ISSUE TITLE
issue running on GPU (Ubuntu, cuda 7.5)

### ISSUE THREAD

**Issue by TELSER1** [dmlc/mxnet#260]
I'm trying to run MLP.py in the MNIST example, and it throws an error when run with the GPU context:
```
model = mx.model.FeedForward(
    ctx = mx.gpu(), symbol = mlp, num_round = 20,
    learning_rate = 0.1, momentum = 0.9, wd = 0.00001)
```
```
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 72, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:53:11] src/storage/storage.cc:43: Please compile with CUDA enabled
```

I'm pretty sure I have compiled with CUDA enabled. I copied over config file to the main directory (and modified it as is, just to make sure).

I set 

```
USE_CUDA=1
```
```
USE_CUDA_PATH=/usr/local/cuda
```
I also set USE_CUDNN to both 0 and 1 on various attempts.

At this point, I'm not sure where to go. Is there something else I should be setting?

Thanks for any assistance.

**Comment by tqchen** [comment]
Please make sure you ```make clean``` before you make. Also watch for the compile logs. see if -DMSHADOW_USE_CUDA=1 is printed during the compilation. Re-install with the setup.py

**Comment by TELSER1** [comment]
Rerunning setup.py did it,thanks; looking forward to playing with it. As a sanity check on my GPU setup, does a 13 sec Titan X vs 37 sec CPU mode (12 cores) seem reasonable?

**Comment by antinucleon** [comment]
Please use more complex example, eg, cifar-10 instead of mnist to check
speed as mnist is too small

**Comment by randomrandom** [comment]
I ran into the same problem - I did a gitclone of the repo, then make clean, then make. I saw DMSHADOW_USE_CUDA=0 in the logs, however I still get the same message. Any ideas?

**Comment by randomrandom** [comment]
If anyone else runs into problems with the setup - I used this detailed tutorial to get it to work: https://no2147483647.wordpress.com/2015/12/07/deep-learning-for-hackers-with-mxnet-1/
