### ISSUE TITLE
Failed loading Op conv_conv1 of type Convolution: Cannot find argument 'cudnn_tune'

### ISSUE THREAD

**Issue by mjamroz** [dmlc/mxnet#2604]
Hi, 
I trained inception-bn using cudnn/CUDA and wanted to use the trained model on CPU-only machine, but I am getting following error:

> RuntimeError: Failed loading Op conv_conv1 of type Convolution: Cannot find argument 
'cudnn_tune', Possible Arguments:                                                                                         
17 ----------------                                    
16 kernel : Shape(tuple), required       
15     convolution kernel size: (y, x)    
14 stride : Shape(tuple), optional, default=(1,1)
13     convolution stride: (y, x) 
...                                                    
3     Tmp workspace for convolution (MB).   
2 no_bias : boolean, optional, default=False  
1     Whether to disable bias parameter.  

that is a problem in *.json file, I think, but I am not sure how to fix it - do you have any ideas?
Should mention that before (about month ago) I don't get abovementioned errors - cudnn/cuda trained inception-bn works like a charm on the same CPU-only machine.

**Comment by piiswrong** [comment]
try git pull && git submodule update && make clean && make

**Comment by mjamroz** [comment]
@piiswrong thank you for attention! I tried to pull/update, and copied new libmxnet.so to my working dir, but still get the same error:

>    raise RuntimeError(py_str(_LIB.MXGetLastError()))
RuntimeError: Failed loading Op conv_conv1 of type Convolution: Cannot find argument 'cudnn_tune', Possible Arguments:
----------------
kernel : Shape(tuple), required
    convolution kernel size: (y, x)
stride : Shape(tuple), optional, default=(1,1)
    convolution stride: (y, x)
dilate : Shape(tuple), optional, default=(1,1)
    convolution dilate: (y, x)
pad : Shape(tuple), optional, default=(0,0)
    pad for convolution: (y, x)
num_filter : int (non-negative), required
    convolution filter(channel) number
num_group : int (non-negative), optional, default=1
    Number of groups partition. This option is not supported by CuDNN, you can use SliceChannel to num_group,apply convolution and concat instead to achieve the same need.
workspace : long (non-negative), optional, default=512
    Tmp workspace for convolution (MB).
no_bias : boolean, optional, default=False
    Whether to disable bias parameter.

**Comment by zihaolucky** [comment]
@javelinjs I got same issue when using MXNet through Scala and maven dependency. 

> Exception in thread "main" ml.dmlc.mxnet.MXNetError: Failed loading Op convolution0 of type Convolution: Cannot find argument 'cudnn_tune', Possible Arguments:

Could you give me a hint? Did I need others installed or just add a maven dependency?

```scala
  def predict(flat: Array[Float], shape: Array[Int]): Array[NDArray] = {
    println(flat.size)
    println(shape.size)
    val ndArray = NDArray.array(flat, Shape(shape), Context.cpu(0))
    println(ndArray.shape)
    println(ndArray.toString)

    val data: IndexedSeq[NDArray] = IndexedSeq(ndArray)
    val label: IndexedSeq[NDArray] = IndexedSeq()
    val valData: NDArrayIter = new NDArrayIter(data, label)

    val model = FeedForward.load("checkpoint/cnn", 100)
    val prediction = model.predict(valData)
    prediction
  }
```

**Comment by javelinjs** [comment]
@zihaolucky  Did you compile mxnet with cudnn? and have you installed cudnn on the machine where you run mxnet?

**Comment by zihaolucky** [comment]
@javelinjs Nope. >< So I must install the pre-requisites before deployment? Sorry, my bad.

**Comment by javelinjs** [comment]
@zihaolucky If you compiled with cudnn then you must have it on the machine you deployed.

**Comment by zihaolucky** [comment]
@javelinjs Yep, that's true. I have another issue on loading the model's `json` file. 

(Now MXNet compiled without cndnn) I trained a model using Python and try to use its params and json in Scala. But got this error: 

> Exception in thread "main" ml.dmlc.mxnet.MXNetError: Failed loading Op pooling0 of type Pooling: Cannot find argument 'global_pool', Possible Arguments:
kernel : Shape(tuple), required
    pooling kernel size: (y, x)
pool_type : {'avg', 'max', 'sum'}, required
    Pooling type to be applied.
stride : Shape(tuple), optional, default=(1,1)
    stride: for pooling (y, x)
pad : Shape(tuple), optional, default=(0,0)
    pad for pooling: (y, x)

Isn't the `json` and `params` file are language-agnostic which can be easily used somewhere else? Or have I miss something?

**Comment by zihaolucky** [comment]
I guess it is the `global_pool` argument in Python's API cause this error, as we don't have this argument in Scala-pkg. 

```json
    {
      "op": "Pooling", 
      "param": {
        "global_pool": "False", 
        "kernel": "(19,1)", 
        "pad": "(0,0)", 
        "pool_type": "max", 
        "stride": "(1,1)"
      }, 
      "name": "pooling0", 
      "inputs": [[4, 0]], 
      "backward_source_id": -1
    },
```

**Comment by javelinjs** [comment]
@zihaolucky Seems that you built python and scala api with different `libmxnet.so`

**Comment by zihaolucky** [comment]
@javelinjs Thank you. I shall update them.

**Comment by zihaolucky** [comment]
Hi @javelinjs 

I still encountered the `cudnn` issue. In my `config.mk` I've already turned off the `cudnn` option. 

```bash
 40 # whether use CUDA during compile
 41 USE_CUDA = 1
 42
 43 # add the path to CUDA library to link and compile flag
 44 # if you have already add them to environment variable, leave it as NONE
 45 USE_CUDA_PATH = /usr/local/cuda-7.5
 46 # USE_CUDA_PATH = NONE
 47
 48 # whether use CuDNN R3 library
 49 USE_CUDNN = 0
```

But still have this problem.

**Comment by javelinjs** [comment]
Are you loading model which is trained with cudnn?

**Comment by zihaolucky** [comment]
@javelinjs Sorry for bothering you, I've skip this cudnn problem by remove this element in my json. Another question after that, I got some problem in reshape. The input shape and target shape always can not be matched.

**Comment by zihaolucky** [comment]
My input shape should be (128, 20), then embedding should get (128, 1, 20, 128), which is 327680; but I always got:

> [20:49:45] /Users/lewis/Workspace/source-codes/release/mxnet/dmlc-core/include/dmlc/logging.h:245: [20:49:45] src/operator/./reshape-inl.h:122: Check failed: oshape.Size() == dshape.Size() Target shape size is different to source. Target: 327680
Source: 16384

I use scala-pkg by simply add a maven dependency in IntelliJ, I was success in runing a cnn4text with pretrain-embedding before, in which its input is (128, 1, 20, 128); but when I change to this(without embedding) setting, it's wrong. 

```json
  1 {
  2   "nodes": [
  3     {
  4       "op": "null",
  5       "param": {},
  6       "name": "data",
  7       "inputs": [],
  8       "backward_source_id": -1
  9     },
 10     {
 11       "op": "null",
 12       "param": {},
 13       "name": "word_embedding_nonstatic_weight",
 14       "inputs": [],
 15       "backward_source_id": -1
 16     },
 17     {
 18       "op": "Embedding",
 19       "param": {
 20         "input_dim": "1002366",
 21         "output_dim": "128"
 22       },
 23       "name": "word_embedding_nonstatic",
 24       "inputs": [[0, 0], [1, 0]],
 25       "backward_source_id": -1
 26     },
 27     {
 28       "op": "Reshape",
 29       "param": {
 30         "keep_highest": "False",
 31         "shape": "()",
 32         "target_shape": "(128,1,20,128)"
 33       },
 34       "name": "reshape_after_embedding",
 35       "inputs": [[2, 0]],
 36       "backward_source_id": -1
 37     },
 38     {
 39       "op": "null",
 40       "param": {},
 41       "name": "convolution0_weight",
 42       "inputs": [],
 43       "backward_source_id": -1
 44     },
```

**Comment by javelinjs** [comment]
@zihaolucky Could you post the network definition in scala?

**Comment by zihaolucky** [comment]
@javelinjs I use Python to train the model. Then use its outputs(symbol & params) in java env, in which I write some simple scala-code and use java to call them.


### Python code in training - Network definition.

```python
111 # single non-static network
112 def get_non_static_net(vocab_size, embedding_size, sentence_size, batch_size, num_intent_classes, with_embedding, dropout=0.0, filter_list=[1,2,3], num_filter=100):
113     """
114     CNN with multichannel.
115     """
116
117     data = mx.symbol.Variable('data')
119     label_intent = mx.symbol.Variable('softmax_label_intent')
120
121     # embedding layer. non-static
122     word_embed_nonstatic = mx.symbol.Embedding(data=data, input_dim=vocab_size,
123                                                output_dim=embedding_size,
124                                                name='word_embedding_nonstatic')
125     word_embed_nonstatic = mx.symbol.Reshape(data=word_embed_nonstatic, name='reshape_after_embedding',
126                                              shape=(batch_size, 1, sentence_size, embedding_size))  # convolution layer needs 4D input.
127     # concat them as conv_input
128     conv_input = word_embed_nonstatic
129
130     # convolution and pooling layer
131     pooled_outputs = []
132     for i, filter_size in enumerate(filter_list):
133         convi = mx.symbol.Convolution(data=conv_input, kernel=(filter_size, embedding_size), num_filter=num_filter)
134         acti  = mx.symbol.Activation(data=convi, act_type='relu')
135         pooli = mx.symbol.Pooling(data=acti, pool_type='max', kernel=(sentence_size - filter_size + 1, 1), stride=(1,1))  # max pooling on entire sentence feature ma    p.
136         pooled_outputs.append(pooli)
137
138     # combine all pooled outputs
139     num_feature_maps = num_filter * len(filter_list)
140     concat = mx.symbol.Concat(*pooled_outputs, dim=1)  # max-overtime pooling. concat all feature maps into a long feature before feeding into final dropout and full    y connected layer.
141     h_pool = mx.symbol.Reshape(data=concat, shape=(batch_size, num_feature_maps))  # make it flat/horizontal
142
143     # dropout
144     if dropout > 0.0:
145         logging.info('use dropout.')
146         drop = mx.symbol.Dropout(data=h_pool, p=dropout)
147     else:
148         logging.info('Do not use dropout.')
149         drop = h_pool
150
151     # fully connected and softmax output.
153     fc_intent = mx.symbol.FullyConnected(data=drop, num_hidden=num_intent_classes, name='fc_intent')
155     softmax_intent = mx.symbol.SoftmaxOutput(data=fc_intent, label=label_intent)
156
157     return softmax_intent
```

### Python code in training - Saving model.
```python
414     model.fit(X                  = data_train,
415               eval_data          = data_eval,
416               eval_metric        = eval_metrics,
417               batch_end_callback = mx.callback.Speedometer(args.batch_size, 50),
418               epoch_end_callback = mx.callback.do_checkpoint(model_prefix, 1))  # save model every 10 epoch.
```


### Serving side - Use Scala and Java

Create a MXNetPredictor.scala to provide `predict` function. Then use Java to pass features/data.

```scala
class MXNetPredictor (prefix: String, epoch: Int, batchSize: Int) {

  private val logger = LoggerFactory.getLogger(classOf[MXNetPredictor])

  val model = FeedForward.load(prefix, epoch)

  /**
    * predict
    *
    * @param flat A flat feature input vector.
    * @param shape Shape of input data.
    * @return
    */
  def predict(flat: Array[Float], shape: Array[Int]): Array[NDArray] = {
    val ndArray = NDArray.array(flat, Shape(shape))

    val data: IndexedSeq[NDArray] = IndexedSeq(ndArray)
    val label: IndexedSeq[NDArray] = IndexedSeq()

    val inputBatchSize = shape(0)
    if (inputBatchSize != batchSize) {
      logger.error("Input data shape should be consistent with your batchSize.")
      logger.error("batchSize: " + batchSize)
      logger.error("Input data shape: " + inputBatchSize)
    } else {
      val valData: NDArrayIter = new NDArrayIter(data, label, batchSize)
      val prediction = model.predict(valData)
      return prediction
    }
    null
  }
```

At Java side, I also provide a prediction API.

```java
public String predict(String utterance) {
        float[] features = generateFeature(utterance);
        int[] shape = {batchSize, 1, sentenceSize, embeddingSize};
        NDArray prediction = predictor.predict(features, shape);  // predictor is MXNetPredictor.scala

        int index = (int) prediction.toArray()[0];
        return xxx;
    }
```

### Issues.

I use scala-pkg by simply add a maven dependency in IntelliJ, I was success in running a CNN for text classification with pretrain-embedding with the same code above, in which its input is (batch_size, 1, sentence_size, embedding_size); but when I change to this(without embedding) setting, input shape is (batch_size, sentence_size), it's wrong.

The only difference is their network definition and their input shape.

> [20:49:45] /Users/lewis/Workspace/source-codes/release/mxnet/dmlc-core/include/dmlc/logging.h:245: [20:49:45] src/operator/./reshape-inl.h:122: Check failed: oshape.Size() == dshape.Size() Target shape size is different to source. Target: 327680
Source: 16384

16834 = 128*128; I guess it only use first dimension to embedding layer.
327680 = 128 * 1 * 20 * 128

**Comment by zihaolucky** [comment]
@javelinjs I've solved all these problems by building latest scala-pkg on my own. Thank you again!

**Comment by javelinjs** [comment]
@zihaolucky Cool. You may find that we've slightly changed the scala symbol api in the latest version, please let us know if you encounter any problem.
