### ISSUE TITLE
How to implement the 'Bounded Delay' consistency model in MXNet?

### ISSUE THREAD

**Issue by blazerygy** [dmlc/mxnet#2608]
'Bounded Delay' consistency model is mentioned in the paper "Scaling Distributed Machine Learning with the Parameter Server". How to implement it in MXNet? Can give some tips? Thx.

**Comment by piiswrong** [comment]
You can do it in the submodule ps-lite.
However, we find it not necessary for gpu training. Sync SGD works best for less than a couple hundred gpu machines

**Comment by blazerygy** [comment]
@piiswrong Thank you for your answer,but I want to test this consistency model on MXNet which is a deep learning system. If I want to implement it, just modify the code of ps-lite enough? Can you give the consistency model code which you tested before? Thx.

**Comment by tqchen** [comment]
Yes, this will involve modification in ps-lite, as far as I know, only sync and no bounded async is supported so far
