### ISSUE TITLE
ndarray.argmax_channel function location

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#2609]
Hi ,
could anyone tell me where the [ndarray.argmax_channel](https://github.com/dmlc/mxnet/blob/master/python/mxnet/metric.py#L137) is defined? I got some type issue and stuck here.
Thanks

**Comment by sxjscience** [comment]
@Godricly https://github.com/dmlc/mxnet/blob/master/src/operator/broadcast_reduce_op-inl.h#L460-L465

**Comment by Godricly** [comment]
ah.. Thank you. I was looking for it under ndarray folder. One more question on this, how is the result memory allocated? I got a exception of different type on some kind of memory copy between different devices.

**Comment by sxjscience** [comment]
@Godricly I think it should be allocated on the same context as the input?

**Comment by Godricly** [comment]
The problem I have not is that asnumpy function. Somehow, it's trying to give a float type ndarray while I'm using double now. And  this [exception ](https://github.com/dmlc/mxnet/blob/master/src/ndarray/ndarray_function.cu#L32)is given. I tried to add some print and nothing was printed after this [WaitToRead](https://github.com/dmlc/mxnet/blob/master/src/ndarray/ndarray.cc#L690).
The most confusing thing is that I won't counter this problem when using one GPU. It only fails when I'm using more GPUs.

**Comment by Godricly** [comment]
kvstore issue.
