### ISSUE TITLE
Evaluate on validation dataset and do checkpoint every N batch

### ISSUE THREAD

**Issue by zmonoid** [dmlc/mxnet#2614]
Hi,

May I ask is there anyway to do evaluation on validation dataset every N batch and do checkpoint?

**Comment by piiswrong** [comment]
mx.io.resizeiter

**Comment by zmonoid** [comment]
Thank you so much!

**Comment by zmonoid** [comment]
Internal reset should be disabled in order to continuing the training on the rest of data:
test_res = mx.io.ResizeIter(test, num_batches, reset_internal = False)

**Comment by zmonoid** [comment]
@piiswrong
Just to add, it seems that using ResizeIter will reset the data iterator every time it does the evaluation instead of continuing training the rest data.

Following the below issue will solve the problem.
https://github.com/dmlc/mxnet/issues/1593
