### ISSUE TITLE
R documentation with roxygen2

### ISSUE THREAD

**Issue by hetong007** [dmlc/mxnet#262]
Currently the functions are documented in the style of `roxygen2`, while no actual docs/NAMESPACE file generated by the package.

Hopefully this issue tracks the progress on automatic documentation generation with `roxygen2` for the R package.

**Comment by tqchen** [comment]
cc @thirdwing  I think we need to resolve some of the issues mentioned at #242

**Comment by tqchen** [comment]
The roxygen style generator is checked in #296
