### ISSUE TITLE
how to read PARAMS file and JSON file?

### ISSUE THREAD

**Issue by luoruisichuan** [dmlc/mxnet#2623]
I use the command  " epoch.end.callback = mx.callback.save.checkpoint(path)", and get the following files ,
studyfolder-0001      (file type: PARAMS file )
studyfolder-symbol.json     (file type:JSON file )

How to read these files?

thanks.

**Comment by luoruisichuan** [comment]
I use the mxnet R packages.

**Comment by piiswrong** [comment]
there should be a mx.model.load_checkpoint

**Comment by thirdwing** [comment]
@luoruisichuan I think you can find an example of loading model from https://github.com/thirdwing/mxnet_shiny/blob/master/server.R#L13

**Comment by luoruisichuan** [comment]
but I use the command in R console

model <<- mx.model.load(file.choose(), iteration = 3)

and then select file 'studyfolder-symbol.json'  or  'studyfolder-0003' and all have the following problem

> model <<- mx.model.load(file.choose(), iteration = 3)
错误: [22:10:03] D:\chhong\mxnet\dmlc-core\src\io\local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "E:\studyfolder\studyfolder-symbol.json-symbol.json"
> model <<- mx.model.load(file.choose(), iteration = 3)
错误: [22:10:28] D:\chhong\mxnet\dmlc-core\src\io\local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "E:\studyfolder\studyfolder-0003.params-symbol.json"
> model <<- mx.model.load(file.choose(), iteration = 1)
错误: [22:14:42] D:\chhong\mxnet\dmlc-core\src\io\local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "E:\studyfolder\studyfolder-0003.params-symbol.json"
> model <<- mx.model.load(file.choose(), iteration = 1)
错误: [22:16:47] D:\chhong\mxnet\dmlc-core\src\io\local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "E:\studyfolder\studyfolder-symbol.json-symbol.json"
> 


what is the problem?
thank you

**Comment by thirdwing** [comment]
The first parameter is the prefix, not the file name. Your prefix should be `studyfolder`.
