### ISSUE TITLE
possible bug in python function model.fit() when eval_data and X are the same

### ISSUE THREAD

**Issue by wshenx** [dmlc/mxnet#2633]
When eval_data and X point to the same dataiter, training will not be performaned after the second epoch. I traced the code and found a possible solution by adding `eval_data.reset()` at the end of the evaluation code in `_train_multi_device()` function. Hope this is helpful to others encountering the same problem.

**Comment by piiswrong** [comment]
Would you like to propose a PR with your fix?

**Comment by wshenx** [comment]
@piiswrong I'd like to propose a PR but I'm not sure if there is anything needed to be fixed in mx.module. Could you point it out at your convenience because I'm still new to mxnet. Thank you!
