### ISSUE TITLE
attention-based encoder decoder cost huge gpu memory

### ISSUE THREAD

**Issue by gmyofustc** [dmlc/mxnet#2634]
Hi all,
    Recently, I'm trying to use mxnet to build attention-based encoder-decoder network, but I found this network cost huge gpu memory. I checked the memory cost of each layer and found the problem.
    The network can be described as follows
<img width="164" alt="att" src="https://cloud.githubusercontent.com/assets/7859276/16608272/a34f1c9e-437c-11e6-8c52-99a445a02846.png">

But, I found the sequence[X1,X2,X3,X4,...Xt] cost huge memory. It shows that, for each time step of **y_t**, the network will hold one new encoder output matrix of  [X1,X2,X3,X4,...Xt]. As **y_t** may been very long(see, 2000), the network will hold 2000 pairs of  [X1,X2,X3,X4,...Xt]. 

This issue confused me a lot, as I described above, all the 2000 pair matrices  [X1,X2,X3,X4,...Xt] can be inplace during the training, however, what I found is that, these matrices do not inplace during training, thus results in huge gpu memory cost. 

Does anyone have done the same related work and give me some advice, thanks a lot.

**Comment by piiswrong** [comment]
Why do you think they can be stored inplace? I'm not sure what layer you are using but usually you need a layer's input/output to compute gradient.

https://github.com/dmlc/mxnet-memonger this might be able to help you though

**Comment by sxjscience** [comment]
@gmyofustc I think this will not happen if you use the same symbol of the state output `h_1.. h_T` of the encoder LSTM. You can first build a bidirectional LSTM and keep the state symbols `h_1.. h_T`. After that you can compute the attention weight using `s_t` and `h_1..h_T`.

**Comment by gmyofustc** [comment]
OK, I find the issue, there exists a mask matrix during the training, which can't be inplaced during training. I'wll write a c operator to solve this problem, thanks you very much @sxjscience @piiswrong i .
