### ISSUE TITLE
Embedding without full connected layer

### ISSUE THREAD

**Issue by xlvector** [dmlc/mxnet#2638]
When I use mxnet to do SVD in recommender system:

r(u,i) = dot(p(u), q(i))

following net will not converge

user = mx.symbol.Embedding(data = user, dim = 100)
item = mx.symbol.Embedding(data = item, dim = 100)
pred = user * item
pred = mx.symbol.sum(pred)

But after I add to FC layer, it will converge

user = mx.symbol.Embedding(data = user, dim = 100)
user = mx.symbol.FullyConnected(data = user, dim = 100)
item = mx.symbol.Embedding(data = item, dim = 100)
item = mx.symbol.FullyConnected(data = item, dim = 100)
pred = user * item
pred = mx.symbol.sum(pred)

I do not know why?

**Comment by piiswrong** [comment]
Try using monitor to look at the gradients?

**Comment by xlvector** [comment]
How to use monitor? Is there some env to open monitor?

**Comment by xlvector** [comment]
I find an example https://github.com/dmlc/mxnet/blob/master/example/autoencoder/solver.py, thanks
