### ISSUE TITLE
max_axis() and min_axis() backward not implemented

### ISSUE THREAD

**Issue by gmyofustc** [dmlc/mxnet#2639]
Hi all,
     I want to use `max_axis` and `min_axis` in[ broadcast_reduce_op-inl.h](https://github.com/dmlc/mxnet/blob/master/src/operator/broadcast_reduce_op-inl.h#L429).
    And I find these functions do not implement the backward function? 
    Does anyone have plan to work on this issue?

**Comment by sxjscience** [comment]
Backward is supported in NNVM branch
