### ISSUE TITLE
Why does "reshape" of executor become so slow?

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#2649]
Hi,
I found this issue after I updated mxnet to the latest one. When I was trying to train a network using dynamical input size, which means I reshape the executor in every iteration, I found the cost of reshaping is ridiculously large. Before, it was very fast. I use the following code to reproduce the issue:
```
import mxnet as mx
import time
import random

input_data = mx.symbol.Variable(name="data")
# stage 1
conv1 = mx.symbol.Convolution(
    data=input_data, kernel=(11, 11), stride=(4, 4), num_filter=96)
relu1 = mx.symbol.Activation(data=conv1, act_type="relu")
pool1 = mx.symbol.Pooling(
    data=relu1, pool_type="max", kernel=(3, 3), stride=(2,2))
lrn1 = mx.symbol.LRN(data=pool1, alpha=0.0001, beta=0.75, knorm=1, nsize=5)
# stage 2
conv2 = mx.symbol.Convolution(
    data=lrn1, kernel=(5, 5), pad=(2, 2), num_filter=256)
relu2 = mx.symbol.Activation(data=conv2, act_type="relu")
pool2 = mx.symbol.Pooling(data=relu2, kernel=(3, 3), stride=(2, 2), pool_type="max")
lrn2 = mx.symbol.LRN(data=pool2, alpha=0.0001, beta=0.75, knorm=1, nsize=5)
# stage 3
conv3 = mx.symbol.Convolution(
    data=lrn2, kernel=(3, 3), pad=(1, 1), num_filter=384)
relu3 = mx.symbol.Activation(data=conv3, act_type="relu")
conv4 = mx.symbol.Convolution(
    data=relu3, kernel=(3, 3), pad=(1, 1), num_filter=384)
relu4 = mx.symbol.Activation(data=conv4, act_type="relu")
conv5 = mx.symbol.Convolution(
    data=relu4, kernel=(3, 3), pad=(1, 1), num_filter=256)
relu5 = mx.symbol.Activation(data=conv5, act_type="relu")
pool3 = mx.symbol.Pooling(data=relu5, kernel=(3, 3), stride=(2, 2), pool_type="max")
softmax = mx.symbol.SoftmaxOutput(data=pool3, multi_output=True)



executor = softmax.simple_bind(ctx=mx.gpu(0),
							grad_req="write",
							data=(1, 3, 1000, 1000)
							)
for i in range(10):
	shape = (1, 3, random.randint(400, 1000), random.randint(400, 1000))
	s = time.time()
	temp_e = executor.reshape(data=shape, partial_shaping=True)
	print time.time() - s
```
Using the latest version, I got 1.1s or even 2.1s for an iteration. But using an old version, I got 0.0008 or 0.001s for an iteration. What is the reason behind it. @tqchen @piiswrong

**Comment by tqchen** [comment]
can you provide version of a previous hastag that can confirm the difference. Thanks!

**Comment by ascust** [comment]
@tqchen How am I supposed to check the hashtag? I only have the directory containing all the files. Is there a file that records the hashtag? The only i can tell so far is that it was one of the 0.5.0 versions.

**Comment by piiswrong** [comment]
git log should display the commit hash

**Comment by ascust** [comment]
```
commit afb92dbbfe4c969fc8d3f9cde3edbec2d8cd9cdc
Author: Rajat Shah <rajat.shah200792@gmail.com>
Date:   Thu May 19 14:17:15 2016 -0700

    Fixed typo in Readme (#2191)

commit 65d7dca9e9767424f0afe6379e8a598139f7001c
Author: David Rex <5urprise@users.noreply.github.com>
Date:   Thu May 19 20:15:08 2016 +0200

    Fix small network visualization bug (#1970)
    
    * Fix small network visualization bug
    
    Fix a small plot_network bug with multi-line-descriptions with "\n" leading to wrong tree-generation and error messages like "string ran past end of line", originating in o
    
    * Fix small network visualization bug
    
    Fix a small plot_network bug with multi-line-descriptions with "\n" leading to wrong tree-generation and error messages like "string ran past end of line", originating in o

commit 0aa3f86726f54800bb75842beb9b72cf7217c1b5
Merge: 3669ed1 00a7d06
Author: Tianqi Chen <tqchen@users.noreply.github.com>
Date:   Thu May 19 10:54:29 2016 -0700

    Merge pull request #2165 from sxjscience/broadcast-op
    
    Broadcast op + Update Submodules
```

**Comment by tqchen** [comment]
seems that was pretty recent version. If you can ,do you mind do a binary search on the versions to see which version cause the problem? i.e. checkout the version between the working one and the latest, to see which one slows down things.

Thanks

**Comment by tqchen** [comment]
You can also find commit history here https://github.com/dmlc/mxnet/commits/master

**Comment by ascust** [comment]
@tqchen I just cloned the very latest one, and the problem still exists. So what am saying is that it is the current one (latest one) that slows down things. The version I posted in the last reply has no slow-down.

**Comment by tqchen** [comment]
Yes, what I am meant is that if would be nice if we can narrow it down to which commit causes the problem, to do so, what we can do is gradually move the version toward the latest one, and find the commit that causes the problem, so we can take detailed look on exact what change bring that in

**Comment by tqchen** [comment]
You can do git checkout hashtag to switch the branch to specific hashtag version

**Comment by ascust** [comment]
Sorry I am not quite familiar with git commands. Do you mean using "git checkout 4fbc8ff" for example? after I switch to a specific commit, I compile and test it right? It seems, there is always an error after I switch it and compile it. Could you tell me how to do that more specifically?

**Comment by tqchen** [comment]
yes, you can do ```git checkout hashtag; git update submodule ``` ,, make clean and recompile.

**Comment by ascust** [comment]
@tqchen @piiswrong 
I found the one that caused problem. "0ad34c9" is the one we are looking for. The previous commit "1bf1337" is normal. One thing worth noting that this issue only happends when CuDNN is used. Since "0ad34c9" is something about CuDNN, I suspect there is somehow a connection between these. Hope you could figure out what the problem is. Thanks.

**Comment by tqchen** [comment]
oh, could it be related to the tuner @piiswrong ?

**Comment by tqchen** [comment]
Thanks for helping us looking into it @ascust !

It is highly likely due to recently introduced auto tuner, that automatically tunes the CuDNN kernels every time a graph get executed, Since in your case you get a new graph each time, the tuner runs again. I think the tuner can be optionally turned of. It is also likely to be fine if you cache your reshaped executor.

In the future, this makes a good reason for tuner to store the previously tuned results @piiswrong
