### ISSUE TITLE
code in C++ backend vs. script front end

### ISSUE THREAD

**Issue by pluskid** [dmlc/mxnet#265]
Hi! I'm planning to add optimizer and model to the julia frontend next. But since now we already have at least 3 frontends, I just want to pause a bit and ask about what is the design philosophy of mxnet. Specifically, what level of code do you think should live in the backend and what should live in the frontend?

I think the advantage of keeping code in the backend is to avoid code redundancy in multiple frontends. They might gradually evolve into slightly different shape or even inconsistent with each other.

On the other hand, writing some non-critical programming logic in the frontend script language is more flexible and easier for user to extend. Optimizer might be a good example.

Kind of a related question, what is the plan for supporting user-defined layers? Are we going to enrich the API for `Symbol` and `NDArray` so that the end user could easily define their own layers (though maybe less efficiently) in the target script language? Or are the users always encouraged to write things in C++ in the backend if new layers are to be added?

**Comment by antinucleon** [comment]
In design, I think we should left all in dynamic way (front end) if it doesn't hurt performance. I plan to move optimizer back because there is a problem of unstable speed. I am not sure whether is the optimizer made it. If so, definitely we should move it back

**Comment by pluskid** [comment]
> a problem of unstable speed
Do you mean something like #223 ?

**Comment by antinucleon** [comment]
Yes, my guess is optimizer brings too much load to engine, but need experiment to support the guess. will do it maybe in next week.

**Comment by tqchen** [comment]
Most of the design reflects [Amdahl'law](https://en.wikipedia.org/wiki/Amdahl%27s_law). In summary, we should being able to support a "mixed way" and allow seamless shift between the two.

The optimizer problem @antinucleon mentioned is kinda like "solved" in a sense that we make the multi-gpu speed roughly linear. There are multiple reasons for slow down, while the stabilized speed is still quite reasonable.

As we advocate for being "mixed", the current design enables both, and we should keep doing so. I think idea of putting optimizer on front-end is valuable, and it won't change even we allow expose c++ level optimizer (allow user to switch between the two).

**Comment by tqchen** [comment]
For operators, It is definitely important to support customization, whether it is native Julia, or via composition of fine-grained symbols and ndarray, to enable user to do things efficiently. 

As some common pattern occur, it may be reasonable to bring some of new big operators to backend. I guess slight divergence won't be a big problem, as long as we have a fixed set of common modules, and interchangeable format.

**Comment by pluskid** [comment]
Thanks for the clarification!

**Comment by mli** [comment]
i also think the current way of model.py is not effective. it makes maintaining similar things on different bindings harder. it will be great if we can make these codes shared to all languages.

**Comment by pluskid** [comment]
Yes, I think most of the time users won't need to customize the logic in model.py. For optimizers, even if we ignore computational performance issue, it might be better to put common optimizers in C++ backend because the code in each front end will be essentially duplicated. As long as we still leave the interface open so that the users are able to define their own optimizers when needed, this should not be a problem.

**Comment by antinucleon** [comment]
I think keep C++ side in minimal way is correct. model.py should rely on language. In this way we can make our library in small size. Eg, if we plan to make mobile version, we only need a minimal core in size of 3-6 MB, instead of 20MB

**Comment by mli** [comment]
mobile is another case, we only need to pack the model prediction codes into it. but the short-term question is that we need to write almost identical codes for python/R/julia

**Comment by tqchen** [comment]
Let us being optimistic about this :) There will be common patterns and eventually common patterns goes back to the c++.   It is also about a thin layer of interface. i.e. limited number of simple parameters that can be passed through a C API and how much flexibility to offer. 

In that sense, making a common model interface requires quite a lot of thoughts than expected. For example, how to keep the python callbacks that evaluates the state. How to adapt to multiple in, multiple out case, and how to make these arguments plain C types.  In that sense, the optimizer is a cleaner cut.

As we are also exposing the low level interface, i.e. symbolic execution and ndarray. The model code is more like a battle test case of all the low level modules, which is fun to write :)  It also serves an example on how to deeply customize the code.

It is likely the complicated use-cases will still occur, and we will keep improve the way we think about the model.py   When we have a good idea of where is the clean and effective common pattern that we want to cut, we can definitely bring it down to c++
