### ISSUE TITLE
R's mx.nd.load wraps the array in a list

### ISSUE THREAD

**Issue by hetong007** [dmlc/mxnet#266]
The following result is observed:

```r
> mat = mx.nd.ones(10)
> mx.nd.save(mat,'~/temp.mat')
> as.array(mat)
 [1] 1 1 1 1 1 1 1 1 1 1
> as.array(mx.nd.load('~/temp.mat'))
[[1]]
 [1] 1 1 1 1 1 1 1 1 1 1
```

The problem could be in `mx.nd.internal.load`.

**Comment by tqchen** [comment]
This is expected behavior, nd.load and nd.save should only take list of arrays. @thirdwing Maybe we can simply not support save a single array

**Comment by hetong007** [comment]
Can you give an example of saving a list of objects?

**Comment by hetong007** [comment]
I suggest to make the save/load interface consistent with each other: If I save a list, then I should get a list back from load; if I save an `mx.nd.array` object, I should get an `mx.nd.array` object from load.

Besides, I haven't found the way to save `mx.nd.array`s so that I can load back a list of more than one `mx.nd.array`.

**Comment by tqchen** [comment]
The mx.nd.save is suppose to save a list of ndarrays. Because  there is no way to tell if the saved object is a list or array. We need to resort to two functions. For example Use ```mx.nd.save.list``` and ```mx.nd.load.list``` for current save and load
