### ISSUE TITLE
compile mxnet failed with CUDA 8.0

### ISSUE THREAD

**Issue by Ldpe2G** [dmlc/mxnet#2672]
I just checkout the version 5532511e1c9411494d1891cd0ae1e37993543daf,
And got the following compile error:

/usr/local/cuda/bin/nvcc -c -o build/src/operator/activation_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/ldpe2g/Mxnet/mxnet_scala/mxnet2/mshadow/ -I/home/ldpe2g/Mxnet/mxnet_scala/mxnet2/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=1" src/operator/activation.cu
/usr/include/c++/4.8/ext/new_allocator.h(99): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7537

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00000a94_00000000-7_block_grad.cpp1.ii".
Compilation aborted.
/usr/include/c++/4.8/ext/new_allocator.h(99): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7537

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00000a9e_00000000-7_batch_norm.cpp1.ii".
Compilation aborted.
/usr/include/c++/4.8/ext/new_allocator.h(99): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7537

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00000aac_00000000-7_activation.cpp1.ii".
Compilation aborted.
Aborted (core dumped)
make: *** [build/src/operator/block_grad_gpu.o] 错误 134
make: *** 正在等待未完成的任务....
Aborted (core dumped)
make: *** [build/src/operator/batch_norm_gpu.o] 错误 134
Aborted (core dumped)
make: *** [build/src/operator/activation_gpu.o] 错误 134
/usr/include/c++/4.8/ext/new_allocator.h(99): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7537

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00000a99_00000000-7_ndarray_function.cpp1.ii".
Compilation aborted.
Aborted (core dumped)
make: *** [build/src/ndarray/ndarray_function_gpu.o] 错误 134

I am using the GTX 1070 GPU and my driver verion is 367.27.

But I can successfully compile the lastest version using cuda 7.5.

**Comment by Ldpe2G** [comment]
I have tried to roll back the dmlc-core version 
from 25e80e916b8bb42e2f027ce352970904389ba76b 
to  67259fa8c600c04c9e1d067012ece7fdeb87158e
and the problem was solved.

**Comment by piiswrong** [comment]
@tqchen

**Comment by tqchen** [comment]
@piiswrong can you confirm this on your machine?

**Comment by piiswrong** [comment]
works fine for me. Seems like a gcc 5.0 issue

**Comment by Ldpe2G** [comment]
@piiswrong  I am using gcc 4.8.

**Comment by piiswrong** [comment]
@tqchen I can confirm the error and it was introduced by 25e80e916b8bb42e2f027ce352970904389ba76b

**Comment by piiswrong** [comment]
should be fixed by https://github.com/dmlc/mxnet/pull/2679

**Comment by Ldpe2G** [comment]
It's fixed. Thanks
