### ISSUE TITLE
Example/cpp/image-classification-predict not work

### ISSUE THREAD

**Issue by SJTUzhanglj** [dmlc/mxnet#2676]
f:\mxnet\src\operator\./softmax_output-inl.h:292: Softmax symbol is renamed to SoftmaxOutput. This API will be deprecated in Dec, 2015

is it because of my outdated mxnet version? But predict with Python is OK

**Comment by sxjscience** [comment]
Yes. Softmax is depreciated.

**Comment by thirdwing** [comment]
@SJTUzhanglj In the `Inception_BN-symbol.json`, you can see the below content around line 4415.

```
     {         
       "op": "Softmax",                                               
       "param": {"grad_scale": "1"},
       "name": "softmax",
       "inputs": [[510, 0], [511, 0]],
       "backward_source_id": -1
     }
```
If you change `Softmax` into `SoftmaxOutput `, the warning should disappear.
