### ISSUE TITLE
Why mx.viz.plot_network(mlp) can't Show

### ISSUE THREAD

**Issue by lucheng07082221** [dmlc/mxnet#2681]
I want to ask why I use the code mx.viz.plot_network(mlp)。but it doesn't  Show the network figure
the code is:
data = mx.symbol.Variable('data')
# first conv
conv1 = mx.symbol.Convolution(data=data, kernel=(5,5), num_filter=20,name="conv1")
bn1 = mx.symbol.BatchNorm(data = conv1, name="bn1")
tanh1 = mx.symbol.Activation(data=bn1, act_type="tanh",name="tanh1")
pool1 = mx.symbol.Pooling(data=tanh1, pool_type="max",
                          kernel=(2,2), stride=(2,2),name='pool1')
# second conv
conv2 = mx.symbol.Convolution(data=pool1, kernel=(5,5), num_filter=50)
bn2 = mx.symbol.BatchNorm(data = conv2, name="bn2")
tanh2 = mx.symbol.Activation(data=bn2, act_type="tanh")
pool2 = mx.symbol.Pooling(data=tanh2, pool_type="max",
                          kernel=(2,2), stride=(2,2))
# first fullc
flatten = mx.symbol.Flatten(data=pool2)
fc1 = mx.symbol.FullyConnected(data=flatten, num_hidden=500)
tanh3 = mx.symbol.Activation(data=fc1, act_type="tanh")
# second fullc
fc2 = mx.symbol.FullyConnected(data=tanh3, num_hidden=10)
# loss
lenet = mx.symbol.SoftmaxOutput(data=fc2, name='softmax')

mx.viz.plot_network(lenet,title='plot')

**Comment by piiswrong** [comment]
plot_network returns an graph object. You can call .view() on it to see the graph

**Comment by lucheng07082221** [comment]
Sorry,which function shoud I call? I think  graph=mx.viz.plot_network(lenet,title='plot')  graph.show(),Right?

**Comment by lucheng07082221** [comment]
I call the function 
a=mx.viz.plot_network(lenet,title='plot')
a.view()
but get an error 
Connected to pydev debugger (build 145.844)
Traceback (most recent call last):
  File "D:\Program Files (x86)\JetBrains\PyCharm 2016.1.2\helpers\pydev\pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files (x86)\JetBrains\PyCharm 2016.1.2\helpers\pydev\pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:/python/mxnet/mnist/Test.py", line 96, in <module>
    a.view()
  File "D:\Anaconda\lib\site-packages\graphviz\files.py", line 248, in view
    rendered = self.render()
  File "D:\Anaconda\lib\site-packages\graphviz\files.py", line 226, in render
    'are on your systems\' path' % cmd)

**Comment by lucheng07082221** [comment]
@piiswrong I put the dot.exe to the python directory.My python directory is D:\Anaconda. then I resolution this problem
