### ISSUE TITLE
issue in write my own data iterator

### ISSUE THREAD

**Issue by benwu232** [dmlc/mxnet#2689]
Hi,

Thank you for providing Mxnet!

I'm trying to write my own data iterator. I want to use some meta data to generate batch data for training.  The generated data is much bigger than the meta data. 

Here is a very simple example:
```python
class DataGen(mx.io.DataIter):
    def next(self):
        data = np.ones(shape=(2,98))
        label = np.ones(98)
        data_batch = mx.io.DataBatch(data, label)
        return data_batch
```

In my test, I got this error:
  File "/home/wb/.pyenv/versions/anaconda2-2.4.1/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 745, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
AttributeError: 'DataGen' object has no attribute 'provide_data'

Actually there is no 'provide_data' in DataIter class.

I did similar task in Keras, which is pretty easy. In Keras, the fit_generator function only need a data iterator which returns (training_data, training_target). In Mxnet, it is much harder to do this. Would you please provide similar api? or tell me how to implement customized data iterator?

Many thanks again!
Ben

**Comment by Godricly** [comment]
Check if [this](https://github.com/dmlc/mxnet/blob/master/example/rnn/bucket_io.py#L179-L180) help.

**Comment by benwu232** [comment]
Thanks! @Godricly 

I'm reading some examples in the example folder. 
Still don't know what does 'provide_data' mean? I'll read them all.

**Comment by Godricly** [comment]
The provided_data is giving the shape info of your data. you can try with rnn example and print them out to have an idea of what they are.

**Comment by benwu232** [comment]
That makes sense. Thanks!
