### ISSUE TITLE
issues in example warp-ctc

### ISSUE THREAD

**Issue by sinmaystar** [dmlc/mxnet#2695]
I have installed mxnet successfully and I have ran image-classification/train_minist.py successfully.
I want to run warp-ctc/lstm_ocr.py and I have installed baidu warp-ctc, then follow the document comment out WARPCTC_PATH MXNET_PLUGINS, when I rebuild mxnet by make clean && make -j4 it occurs an error 

plugin/sframe/iter_sframe.cc:16:36: fatal error: unity/lib/image_util.hpp: No such file or directory
#include <unity/lib/image_util.hpp>
                                                          ^
compilation terminated 
make: *** [build/plugin/sframe/iter_sframe.o] Error 1
make: *** Waiting for unfinished jobs...

how can I correct this problem?

**Comment by SDASDASA** [comment]
i encounter the same error，have you solved this error？
