### ISSUE TITLE
about the Multi-label

### ISSUE THREAD

**Issue by DrustZ** [dmlc/mxnet#270]
hi~
how to implement a network which has multi-label or multi-loss-layer?
i can't find the correspond solution in the document.

**Comment by antinucleon** [comment]
You can [play with symbol](https://github.com/dmlc/mxnet/blob/master/example/notebooks/simple_bind.ipynb) directly, and I will post a LSTM example today or tomorrow to show similar idea. 

eg
```
data = mx.sym.Variable("data")
fc1 = mx.sym.FullyConnected(data=data, xxx)
fc2_1 = mx.sym.FullyConnected(data=fc1, xxx)
fc2_2 = mx.sym.FullyConnected(data=fc1, xxx)
sm1 = mx.sym.Softmax(data=fc2_1, name="sm1")
sm2 = mx.sym.Softmax(data=fc2_2, name="sm2")
```
after bind, you need to set
args["sm1_label"][:] = xx
args["sm2_label"][:] = xxx

**Comment by pluskid** [comment]
It is already possible with the current `FeedForward` model. Just group your multiple loss into one symbol should work. Feel free to re-open the issue if there is any further problem.

**Comment by ChrisYang** [comment]
@antinucleon i was wondering how to set the labels if we use 
mx.io.ImageRecordIter
in mx.io.ImageRecordIter there is one argument label_width but there is no related item to label_name(s) setting. How can it be associated with your 'xx'  and 'xxx' in your example.
