### ISSUE TITLE
should mxnet do 1-class image classification?

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#2700]
I have only one class in my training data ,for example every image has a label  = 0 . 
And I don't have any negative  samples .
我的训练样本只有1个类别，比如所有的image 都属于0分类，没有负样本。

I just  want to training a model which can give me a prediction of  image should be  label =0 or not.Or give me a prob that can show me How close to this category。
我想通过cnn训练一个模型，输入一张图，然后告诉我输入的这张图，是不是属于0分类；或者可以输出一个概率，告诉我这个图和0分类多接近（如果不是这个分类，概率肯定会很低）
 
Could mxnet solve this problem?If so ,could some one give me a example here?
不知道用mxnet可以实现吗，如果可以可以给我一个实际的例子么，谢谢！
thank you !

PS:sorry about my english!  
非常抱歉，英文很糟糕：）

**Comment by piiswrong** [comment]
This is a very difficult machine learning problem. MXNet is only a toolkit. You can implement all kinds of algorithms with it. But first you have know what algorithm you want to use.
https://en.wikipedia.org/wiki/One-class_classification

**Comment by albertyou2** [comment]
@piiswrong
 thanks !我原来以为比较简单，看样子要换一个思路了！感谢！！！
