### ISSUE TITLE
how to write backward function?

### ISSUE THREAD

**Issue by yuantangliang** [dmlc/mxnet#2703]
I want to learn how to write operator in Mxnet,but backward function stop me. I have readed and understood [How the backpropagation algorithm works](http://neuralnetworksanddeeplearning.com/chap2.html) and [Calculus on Computational Graphs: Backpropagation](http://colah.github.io/posts/2015-08-Backprop/),but I still have no idea when I write backward function in Mxnet.I just don't know what to read and learn.Could anyone help and give  me material to learn?Any help is grateful.

**Comment by piiswrong** [comment]
Look into the the operators in src/operator
