### ISSUE TITLE
For some complicated  networks, why cpu mode is way faster than gpu mode?

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#2714]
I got a very confusing problem. For some complicated networks, which have many nodes and relationships, cpu mode seems way faster. I will show this in a working example.
```
data = mx.symbol.Variable("data")
layer_dict = {}
NUM = 80
for i in range(NUM):
	for j in range(NUM):
		temp_name = "%d_%d_0" % (i, j)
		temp_layer = mx.symbol.FullyConnected(data, num_hidden=2, name=temp_name)
		layer_dict[temp_name] = temp_layer
output_list = []
for i in range(NUM):
	for j in range(NUM):
		temp_name = "%d_%d_1" % (i, j)
		layer_list = []
		for k in range(NUM):
			layer_list.append(layer_dict["%d_%d_0"%(k, i)])
		temp_layer = mx.symbol.ElementWiseSum(*layer_list)
		temp_layer = mx.symbol.FullyConnected(mx.symbol.Concat(*[temp_layer, data]), num_hidden=2, name=temp_name)
		output_list.append(temp_layer)
net = mx.symbol.Concat(*output_list)




e = net.simple_bind(ctx=mx.cpu(0),
					grad_req="null",
					data=(1, 512))

for i in range(10):
	s = time.time()
	e.forward(is_train=True)
	output = e.outputs[0].copyto(mx.cpu()).asnumpy()
	print (time.time()-s)
```

So please ignore the details of the network because it does not make any sense. The point is to see why cpu is faster than gpu for 3.5 times in my case. gpu takes 2.5s for each iteration while cpu takes only 0.7s for an iteration. @tqchen @piiswrong

**Comment by ascust** [comment]
any thoughts on this, is this related to the internal mechanism of Mxnet? @tqchen @piiswrong

**Comment by piiswrong** [comment]
Your layers are too small and there are too many of them. Kernel launch overhead is dominating.

**Comment by ascust** [comment]
but why cpu mode is way faster? @piiswrong

**Comment by piiswrong** [comment]
Because cpu doesn't need to launch gpu kernels

**Comment by ascust** [comment]
Thanks, that kind of makes sense.
