### ISSUE TITLE
Anything wrong with CSVIter? 

### ISSUE THREAD

**Issue by Lisz1024** [dmlc/mxnet#2720]
I have two csv file : feature.csv and label.csv , with only ten samples.
the feature.csv is :

>1,1
>2,2
>3,3
>4,4
>5,5
>6,6
>7,7
>8,8
>9,9
>10,10

the label.csv is :

>1
>2
>3
>4
>5
>6
>7
>8
>9
>10

I write a python script to load data using CSVIter.

```
import mxnet as mx
import numpy as np

train = mx.io.CSVIter(
	data_csv="./feature.csv" ,
	label_csv="./label.csv" ,
	data_shape = (2,) ,
	label_shape = (1,) ,
	batch_size = 3 
)

for batch in train :
    array = batch.data[0].asnumpy()
    for line in array :
        print ",".join([str(i) for i in line])

train.reset()

for batch in train :
    array = batch.label[0].asnumpy()
    for item in array :
        print item
```

the output is 
>1.0,1.0
2.0,2.0
3.0,3.0
4.0,4.0
5.0,5.0
6.0,6.0
7.0,7.0
8.0,8.0
9.0,9.0
10.0,10.0
1.0,1.0
2.0,2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
1.0

it can be seen from the output , there are 12 lines from feature.csv , it is right .
But there are only 9 lines from label.csv and not begin with 1.0.
Are there anything wrong with csvIter or anything bug in my script ?

**Comment by R1ncy** [comment]
have you solved your problem? i have the same problem.

**Comment by pluskid** [comment]
This is because by default, the CSVIter has `round_batch` being True. Which means with batch size 3, and total instance 10, two more examples are consumed at the first round. When you call `reset`, the call is ignored because the second round has already begun due to the round padding. As a result, you got fewer examples in the second round.

**Comment by Lisz1024** [comment]
@pluskid thank you very much.
@R1ncy By set `round_batch = False` , we can get same sample each round.

```
train = mx.io.CSVIter(
    data_csv="./feature.csv" ,
    label_csv="./label.csv" ,
    data_shape = (2,) ,
    label_shape = (1,) ,
    batch_size = 3 ,
    round_batch = False
)
```

**Comment by R1ncy** [comment]
@Lisz1024 @pluskid  thank you! :)
is there any difference between i set the data_shape=(1,2) and data_shape=(2,)?

i saw "each row data in csv file will be reshaped into the data_shape" on #1204
