### ISSUE TITLE
How can I monitor the weight matrix and gradient?

### ISSUE THREAD

**Issue by were** [dmlc/mxnet#2722]
I add a monitor parameter fix, but I cannot comprehend the output log.
Why there is only one value for the weight matrix of certain layer?
And how can I monitor the gradient of every algorithm pass?

**Comment by piiswrong** [comment]
by default a statistic is computed for each tensor. You can return the tensor itself as the stat and all its content will be printed. However thats usually too much printint

**Comment by were** [comment]
How can I get the tensor? Do I have to modify the source code of mxnet.py?

**Comment by sxjscience** [comment]
@were For an executor `exe`, you can use `arg_dict` and `grad_dict`. For example

```python
for k, v in exe.arg_dict.items():
   print(k, v.asnumpy())
for k, v in exe.grad_dict.items():
   print(k, v.asnumpy())
```

**Comment by were** [comment]
How can I find a executor in `model.fit`?

**Comment by were** [comment]
@piiswrong How to see the tensor when `fit`

**Comment by were** [comment]
OK, I think I have done. Close this issue.
