### ISSUE TITLE
about using the im2rec.py

### ISSUE THREAD

**Issue by luoruisichuan** [dmlc/mxnet#2727]
@tmatas 
I am not sure about using the im2rec.py,
 for example, the file 'im2rec.py' in the folder 'D:/test' and the two class of trainning images(for two classification) in the folders 'D:/test/train1' and 'D:/test/train2', respectively, and the image file is jpeg format.
as for as the example, how to create the rec file for  mx.io.ImageRecordIter with  im2rec.py?  
thanks for your help very much.

**Comment by thirdwing** [comment]
From https://github.com/phunterlau/kaggle_statefarm/tree/master/inception , you can find a complete example for (1) creating the image list; (2) creating rec files; (3) training using mxnet.

The training set is from https://www.kaggle.com/c/state-farm-distracted-driver-detection .I hope this helps.

**Comment by luoruisichuan** [comment]
for the two steps of creating REC file, it is OK, but now, 'make_list.py'  is deleted, and just 'im2rec.py' is used for creating REC file, as for as this one step of creating REC file is concerned, how to use  'im2rec.py' ?
thanks for your help.

**Comment by thirdwing** [comment]
https://github.com/phunterlau/kaggle_statefarm/blob/master/inception/gen_rec_bin.sh#L10

**Comment by luoruisichuan** [comment]
Deleted make_list.py, fixed a typo in im2rec.py by tmatas · Pull Request #2463 · dmlc/mxnet https://github.com/dmlc/mxnet/pull/2463

so I cannot download ' make_list.py' and use it now, what can I do?
thanks for your help.

**Comment by changingivan** [comment]
you can find a older version here [https://github.com/imistyrain/mxnet-mr](url)

**Comment by changingivan** [comment]
you can find a older version here[https://github.com/imistyrain/mxnet-mr/blob/master/make_list.py](url)

**Comment by changingivan** [comment]
you can find a older version here [github.com/imistyrain/mxnet-mr/blob/master/make_list.py](url)

**Comment by changingivan** [comment]
you can find a older version ov make_list.py here [](https://github.com/imistyrain/mxnet-mr/blob/master/make_list.py)

**Comment by changingivan** [comment]
you can find a older version of make_list.py here [https://github.com/imistyrain/mxnet-mr/blob/master/make_list.py](https://github.com/imistyrain/mxnet-mr/blob/master/make_list.py)

**Comment by luoruisichuan** [comment]
thanks.
