### ISSUE TITLE
auto training test on gpus

### ISSUE THREAD

**Issue by mli** [dmlc/mxnet#273]
travis is nice for unittest, but i see the importance to run more testing codes. for example, training conv-net (lenet on mnist, inception on cifar10) on gpus, all various of local kvstore, and the distributed version. 

my current thought is letting a gpu machine (either a local one or ec2) pull mxnet every n hour (probably not for every push), run the all (probably expensive) tests, and send an email if fails. it would be even better to ship it on docker.

**Comment by Kaixhin** [comment]
I've created [CPU](https://hub.docker.com/r/kaixhin/mxnet/) and [CUDA](https://hub.docker.com/r/kaixhin/cuda-mxnet/) Docker images - the source and documentation is [here](https://github.com/Kaixhin/dockerfiles). If these are suitable then you can add them to the docs or I can do it and submit a PR.

I've only done basic tests - running a [MNIST example](https://github.com/dmlc/mxnet/blob/master/example/mnist/mlp.py) and [creating a GPU array](http://mxnet.readthedocs.org/en/latest/R-package/ndarrayAndSymbolTutorial.html#ndarray-vectorized-tensor-computations-on-cpus-and-gpus), so you probably will want to do more.

**Comment by mli** [comment]
Hi Kaixhin,

That an awesome news. Can you put instructions on https://github.com/dmlc/mxnet/blob/master/doc/build.md and add a link https://github.com/dmlc/mxnet#contents (probably on the same line with Installation)
