### ISSUE TITLE
ValueError: Only 2D matrix is allowed to be transposed

### ISSUE THREAD

**Issue by camel007** [dmlc/mxnet#2733]
`def get_iterator(batch_size, data_shape):

    train = mx.io.ImageRecordIter(
        path_imgrec = "./example/ocr/train.bin",
        data_shape  = data_shape,
        batch_size  = batch_size,
        shuffle = True,
        label_width = 4,
        preprocess_threads = 8,
        verbose = True,
        scale = 0.003921569)

    val = mx.io.ImageRecordIter(
        path_imgrec = "./example/ocr/val.bin",
        data_shape  = data_shape,
        batch_size  = batch_size,
        shuffle = True,
        label_width = 4,
        preprocess_threads = 8,
        verbose = True,
        scale = 0.003921569)
    return (train, val)

class Multi_ocr_iterator(mx.io.DataIter):
    '''multi label ocr iterator'''

    def __init__(self, data_iter):
        super(Multi_ocr_iterator, self).__init__()
        self.data_iter = data_iter
        self.batch_size = self.data_iter.batch_size

    @property
    def provide_data(self):
        return self.data_iter.provide_data

    @property
    def provide_label(self):
        provide_label = self.data_iter.provide_label[0]
        # Different labels should be used here for actual application
        return [('softmax1_label', (self.batch_size,)), \
                ('softmax2_label', (self.batch_size,)),\
                ('softmax3_label', (self.batch_size,)),\
                ('softmax4_label', (self.batch_size,))]

    def hard_reset(self):
        self.data_iter.hard_reset()

    def reset(self):
        self.data_iter.reset()

    def next(self):
        batch = self.data_iter.next()
        label = batch.label[0]
        label1,label2,label3,label4 = label.T.asnumpy() 
        label1=mx.nd.array(label1)
        label2=mx.nd.array(label2)
        label3=mx.nd.array(label3)
        label4=mx.nd.array(label4)
        return mx.io.DataBatch(data=batch.data, label=[label1, label2, label3, label4], \
                pad=batch.pad, index=batch.index)

def get_ocrnet():
    data = mx.symbol.Variable('data')
    # label = mx.symbol.Variable('softmax_label')
    conv1 = mx.symbol.Convolution(data=data, kernel=(5,5), num_filter=32)
    pool1 = mx.symbol.Pooling(data=conv1, pool_type="max", kernel=(2,2), stride=(1, 1))
    relu1 = mx.symbol.Activation(data=pool1, act_type="relu")

    conv2 = mx.symbol.Convolution(data=relu1, kernel=(5,5), num_filter=32)
    pool2 = mx.symbol.Pooling(data=conv2, pool_type="avg", kernel=(2,2), stride=(1, 1))
    relu2 = mx.symbol.Activation(data=pool2, act_type="relu")

    conv3 = mx.symbol.Convolution(data=relu2, kernel=(3,3), num_filter=32)
    pool3 = mx.symbol.Pooling(data=conv3, pool_type="avg", kernel=(2,2), stride=(1, 1))
    relu3 = mx.symbol.Activation(data=pool3, act_type="relu")

    conv4 = mx.symbol.Convolution(data=relu3, kernel=(3,3), num_filter=32)
    pool4 = mx.symbol.Pooling(data=conv4, pool_type="avg", kernel=(2,2), stride=(1, 1))
    relu4 = mx.symbol.Activation(data=pool4, act_type="relu")
    
    flatten = mx.symbol.Flatten(data = relu4)
    fc1 = mx.symbol.FullyConnected(data = flatten, num_hidden = 256)
    fc21 = mx.symbol.FullyConnected(data = fc1, num_hidden = 62)
    sm1 = mx.symbol.SoftmaxOutput(data = fc21, name = 'softmax1')
    fc22 = mx.symbol.FullyConnected(data = fc1, num_hidden = 62)
    sm2 = mx.symbol.SoftmaxOutput(data = fc22, name = 'softmax2')
    fc23 = mx.symbol.FullyConnected(data = fc1, num_hidden = 62)
    sm3 = mx.symbol.SoftmaxOutput(data = fc23, name = 'softmax3')
    fc24 = mx.symbol.FullyConnected(data = fc1, num_hidden = 62)
    sm4 = mx.symbol.SoftmaxOutput(data = fc24, name = 'softmax4')

    softmax = mx.symbol.Group([sm1, sm2, sm3, sm4])
    return softmax

class Multi_Accuracy(mx.metric.EvalMetric):
    """Calculate accuracies of multi label"""

    def __init__(self, num=None):
        super(Multi_Accuracy, self).__init__('multi-accuracy', num)

    def update(self, labels, preds):
        mx.metric.check_label_shapes(labels, preds)

        if self.num != None:
            assert len(labels) == self.num

        for i in range(len(labels)):
            pred_label = mx.nd.argmax_channel(preds[i]).asnumpy().astype('int32')
            label = labels[i].asnumpy().astype('int32')

            mx.metric.check_label_shapes(label, pred_label)

            if i == None:
                self.sum_metric += (pred_label.flat == label.flat).sum()
                self.num_inst += len(pred_label.flat)
            else:
                self.sum_metric[i] += (pred_label.flat == label.flat).sum()
                self.num_inst[i] += len(pred_label.flat)

if __name__ == '__main__':
    network = get_ocrnet()

    batch_size = 100
    input_shape = (3, 30, 80)

    train, val = get_iterator(batch_size, input_shape)
    train = Multi_ocr_iterator(train)
    val = Multi_ocr_iterator(val)

    save_model_prefix = 'ocr_model'
    checkpoint = mx.callback.do_checkpoint(save_model_prefix)

    model = mx.model.FeedForward(ctx   = mx.gpu(0),
                                 symbol = network,
                                 num_epoch = 10000,
                                 learning_rate = 0.005,
                                 wd = 0.00001,
                                 initializer = mx.init.Xavier(factor_type="in", magnitude=2.34),
                                 momentum = 0.9)
    

    import logging
    head = '%(asctime)-15s %(message)s'
    logging.basicConfig(level=logging.DEBUG, format=head)
    
    model.fit(X = train, eval_data = val, eval_metric = Multi_Accuracy(num=4),
            batch_end_callback = mx.callback.Speedometer(batch_size, 50),
            epoch_end_callback = checkpoint)`

ERROR:
Traceback (most recent call last):
  File "example/ocr/train_ocr_offline.py", line 159, in <module>
    epoch_end_callback = checkpoint)
  File "/home/nd/mxnet/python/mxnet/model.py", line 789, in fit
    sym_gen=self.sym_gen)
  File "/home/nd/mxnet/python/mxnet/model.py", line 221, in _train_multi_device
    for data_batch in train_data:
  File "example/ocr/train_ocr_offline.py", line 65, in next
    label1,label2,label3,label4 = label.T.asnumpy() 
  File "/home/nd/mxnet/python/mxnet/ndarray.py", line 386, in T
    raise ValueError('Only 2D matrix is allowed to be transposed')
ValueError: Only 2D matrix is allowed to be transposed

**Comment by piiswrong** [comment]
You are trying to transpose a matrix that has more than 2 dimensions. It's not supported.

**Comment by camel007** [comment]
Thank you
