### ISSUE TITLE
Add the smooth_l1 loss function into mshadow_op

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#2741]
```
/*!\ \brief used for generate element smooth l1 */
struct smooth_l1 {
  MSHADOW_XINLINE static real_t Map(real_t a) {
    real_t ret = 0.0f;
    real_t abs_a = fabs(a);
    if (abs_a < 1.0f) {
      ret = 0.5f * a * a;
    }
    else {
      ret = abs_a - 0.5f;
    }
    return ret;
  }
};

struct smooth_l1_grad {
  MSHADOW_XINLINE static real_t Map(real_t a) {
    real_t ret = 0.0f;
    real_t abs_a = fabs(a);
    if (abs_a < 1.0f) {
      ret = a;
    }
    else {
      ret = a < 0.f ? -1.5f : 0.5f;
    }
    return ret;
  }
};
```

**Comment by antinucleon** [comment]
I can't see any reason for moving this to mshadow

**Comment by starimpact** [comment]
it is not a bad thing to enrich the loss function family.

**Comment by antinucleon** [comment]
We will refactor all operators soon,

**Comment by tqchen** [comment]
The idea is that we always add new ops to mshadow if it is general and can shorten the code(needed by multiple places), as it is not yet the case, we can do it when we find the need comes

**Comment by tqchen** [comment]
Thanks for the suggestion

**Comment by starimpact** [comment]
it is used in region proposal network.

**Comment by tqchen** [comment]
If it is used in some of the ops, one way would be proposing this op together with the operator definition with a PR
