### ISSUE TITLE
How much memory is required for rcnn？

### ISSUE THREAD

**Issue by fang289040324** [dmlc/mxnet#2751]
Hi, I was running in CPU, but the 70G of memory is not enough.
Modified code：
train.py
#ctx = mx.gpu(args.gpu_id)
ctx = mx.cpu()
We need to modify the other place?
Thank you very much.

**Comment by precedenceguo** [comment]
Actually I don't even have a machine with memory more than 70G. Running in cpu requires changes in workspace for convolution. Please see the documentation for this.

**Comment by jonbakerfish** [comment]
When I ran `python test.py --has_rpn` using NVIDIA K40, I got out-of-memory error when:

    testing 170/4952
    testing 180/4952
    [16:39:29] /home/x/Code/mxnet_latest/dmlc-core/include/dmlc/logging.h:235: [16:39:29] src/operator/roi_pooling.cu:120: Check failed: (error) == (cudaSuccess)  out of memory
    [16:39:29] /home/x/Code/mxnet_latest/dmlc-core/include/dmlc/logging.h:235: [16:39:29] src/engine/./threaded_engine.h:306: [16:39:29] src/operator/roi_pooling.cu:120: Check failed: (error) == (cudaSuccess)  out of memory
    An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
    terminate called after throwing an instance of 'dmlc::Error'
      what():  [16:39:29] src/engine/./threaded_engine.h:306: [16:39:29] src/operator/roi_pooling.cu:120: Check failed: (error) == (cudaSuccess)  out of memory
    An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
    Aborted (core dumped)

**Comment by precedenceguo** [comment]
@antinucleon As a pooling operation, ROIPooling did not request any temporary space. From roi_pooling.cu:120, we can see ROIPoolForwardKernel failed with out of memory. Any idea why this happened?

**Comment by jonbakerfish** [comment]
I'm using the latest mxnet repo. When changing to the cpu mode for `python test.py --has_rpn`, the program stop running after a few seconds.

**Comment by fang289040324** [comment]
Thank you for your answer.
I've put the workspace of the convolution layer is set to the "workspace = 2048".
Because if it is not set, will be an error.
But the situation did not change, memory is very serious

**Comment by jonbakerfish** [comment]
@precedenceguo have you encountered similar problems? The gpu memory usage is much bigger after a while.

**Comment by tornadomeet** [comment]
@jonbakerfish  when i using the newest code i just met the same problem. the older rcnn example is ok. i'll check what's wrong.

**Comment by precedenceguo** [comment]
@piiswrong Could it be related to the new policy on gpu memory allocation? Inference uses full image so binding process happens a lot. As a pooling operation, roipooling doesn't need any temp space. However there are some temp variable in kernel and that causes OOM during the kernel launch.

**Comment by tornadomeet** [comment]
@precedenceguo i just found the newest pr #2927 by @tqchen  will fix the memory problem, the training is ok now, so wait it merged.
