### ISSUE TITLE
import mxnet<report errore>Reason: image not found

### ISSUE THREAD

**Issue by pjpan** [dmlc/mxnet#2754]
OSError: dlopen(//anaconda/lib/python3.5/site-packages/mxnet-0.7.0-py3.5.egg/mxnet/libmxnet.so, 6): Library not loaded: /usr/local/lib/libHalf.12.dylib
  Referenced from: /usr/local/opt/openexr/lib/libIlmImf-2_2.22.dylib
  Reason: image not found

**Comment by ForoughA** [comment]
Hey did you figure out how to solve this?

**Comment by pjpan** [comment]
@ForoughA   no.

**Comment by grainw** [comment]
Hey did you figure out how to solve this?@pjpan
