### ISSUE TITLE
MXNet re-use the internal memory buffers among all executors??

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#2757]
In the "http://myungjun-youn-demo.readthedocs.io/en/latest/how_to/bucketing.html".
I noticed that "MXNet re-use the internal memory buffers among all executors", this means that mxnet can't be used with threads at all? Am I right?

**Comment by tqchen** [comment]
If you do not use shared memory binding explicitly, they won't share the memory.

**Comment by starimpact** [comment]
:smile:
