### ISSUE TITLE
Ignore all communication overheads of the GPU cluster，It is means more machines will need less time overhead when training a deep model，right? Is it also right that we need not too many machines to train a deep model，or more manchines cannot give us greater benefits,vgg model,Imagnet1000 for example?

### ISSUE THREAD

**Issue by boyflytobeman** [dmlc/mxnet#2762]

**Comment by piiswrong** [comment]
Scaling depends on network architecture and your hardware configuration, including PCIe BUS, router, etc.
You need to do experiment youself

**Comment by jack-liuquan** [comment]
Is anyone who has experiment on more than 20 machines deep learning training and have a good performance speed up?
