### ISSUE TITLE
ImageNet图片生成RecordIO文件后的失真问题

### ISSUE THREAD

**Issue by dengdan** [dmlc/mxnet#2765]
在生成imagenet的recordio文件后, 出于好奇, 我从recordio文件中读出了图片并显示出来, 结果发现与原图明显不同, 例如(原图后是对应的失真图片):
![](https://github.com/dengdan/blog_posts/blob/master/github_issue/original/n01484850_95.JPEG?raw=true)
![](https://github.com/dengdan/blog_posts/blob/master/github_issue/showed/2.png?raw=true)
![](https://github.com/dengdan/blog_posts/blob/master/github_issue/original/n01484850_17.JPEG?raw=true)
![](https://github.com/dengdan/blog_posts/blob/master/github_issue/showed/1.png?raw=true)
![](https://github.com/dengdan/blog_posts/blob/master/github_issue/original/n01484850_114.JPEG?raw=true)
![](https://github.com/dengdan/blog_posts/blob/master/github_issue/showed/3.png?raw=true)

生成recordio的命令:
```
~/github/mxnet/bin/im2rec  data/train.lst imgs/ data/train.rec center_crop=1 resize=224
```
从recordio中读取并显示图片的代码, 在jupyter notebook中运行
```
import mxnet as mx;
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

train_iter = mx.io.ImageRecordIter(
    path_imgrec = 'data/train.rec',
    data_shape  = (3, 224, 224),
    batch_size  = 3)

data = train_iter.getdata().asnumpy()

for i in range(len(data)):
    img = data[i].transpose((1, 2, 0))
    plt.figure()
    plt.axis('off')
    plt.imshow(img)
```

忽略center crop与resize造成的影响, 请问颜色失真的原因是什么?

**Comment by tornadomeet** [comment]
https://github.com/dmlc/mxnet/issues/2161

**Comment by dengdan** [comment]
> 非常感谢. 
总结下, 有两种解决办法. 
```
for i in range(len(data)):
    X = data[i].transpose((1, 2, 0))
    plt.figure()
    plt.axis('off')
    plt.imshow(X.astype(np.uint8))
```
或
```
for i in range(len(data)):
    X = data[i].transpose((1, 2, 0))
    X = cv2.cvtColor(X, cv2.COLOR_RGB2BGR)
    cv2.imwrite("result%d.png"%(i), X)
```
