### ISSUE TITLE
CNN prediction without dropout ? 

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#2776]
Some article says that we do NOT need dropout layer  in prediction.
Could mxnet do this job and if it could, would some one show  me how to do this job ?Thanks!
Here is my prediction code :
# prediction
from __future__ import division

import find_mxnet  
import mxnet as mx  
import logging  
import argparse  
import os, sys  
import train_model  
import numpy as np  
import cv2

parser = argparse.ArgumentParser(description='load model trained befor and give prediction for .rec file')
parser.add_argument('--prefix', type=str, default='./saved_model/jd_50_vgg_all' ,
                    help='load model structure by name which has a prefix')
parser.add_argument('--iter', type=int, default=33,
                    help='load model weight from iteration')
parser.add_argument('--shape', type=int, default=50,
                    help='data shape of .rec files')
parser.add_argument('--rgb', type=int, default=3,
                    help='color , 1 for gray,3 for color image')
parser.add_argument('--data-file', type=str, default='./data/pred4_50.rec',
                    help='prediction .rec file path')
parser.add_argument('--min-file', type=str, default='./data/pred4_50.min',
                    help='prediction images mean file')
parser.add_argument('--list-file', type=str, default='./data/pred4.lst',
                    help='prediction images mean file')
args = parser.parse_args()

prefix     = args.prefix
iteration  = args.iter
model_load = mx.model.FeedForward.load(prefix, iteration)  
data_shape = (args.rgb, args.shape,args.shape)  
  
# 数据准备  batch_size = 1.    
pred = mx.io.ImageRecordIter(  
        path_imgrec = args.data_file,
        mean_img    = args.min_file,  
        rand_crop   = False,  
        rand_mirror = False,  
        data_shape  = data_shape,  
        batch_size  = 1) 
 
[prob, data, label_o] = model_load.predict(pred, return_data=True)
print prob

**Comment by piiswrong** [comment]
Dropout is turned off for prediction. The layer is there but it doesn't function

**Comment by albertyou2** [comment]
@piiswrong  Great!Thanks

**Comment by albertyou2** [comment]
@piiswrong thanks !
