### ISSUE TITLE
A Bug?Very strange gpu occupation problem  when using thread !

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#2781]
the following code will cause a strange problem:
environment: 4 TitanX.
mxnet version: v0.7.0
cudnn version: v3.
I copy data to the Second GPU. but the programme always occupy the first GPU memory, and the memory is always 119MB.
But, the problem is disappeared when I do not use the thread.
Is it a bug in MXNet? How to solve it?
```CPP
#include <iostream>
#include <string>
#include <fstream>
#include "unistd.h"

#include "c_api.h"
void *thread(void *pParam);

int main()
{
  NDArrayHandle hData;
	const mx_uint aShape[2] = {10, 10};
	int dwDev_Type = 2,  dwDev_ID = 1;
	MXNDArrayCreate(aShape, 2, dwDev_Type, dwDev_ID, 0, &hData);

	for (int dwTI = 0; dwTI < 100000; dwTI++)
	{
	  pthread_t tid;
	  int ret = pthread_create(&tid, NULL, thread, (void*)&hData); 
		pthread_join(tid, NULL);
	}

	MXNDArrayFree(hData);
  
  return 0;
}

void *thread(void *pParam)
{
  NDArrayHandle *phData = (NDArrayHandle*)pParam;
	float *pfData = (float*)malloc(10*10*sizeof(float));

	MXNDArraySyncCopyFromCPU(*phData, pfData, 10*10);
	
	MXNDArrayWaitAll();

	free(pfData);

	sleep(1);

	return 0;
}

```

**Comment by piiswrong** [comment]
If you create your own threads you have to handle cuda context yourself. Otherwise cuda will use the default context. The engine usually handles all threading. Instead of creating threads try pushing op to the engine

**Comment by starimpact** [comment]
Can you tell me how to solve it step by step?

**Comment by starimpact** [comment]
using cudaSetDevice in eatch thread can sovle it.
oh, my god.
haha.....
