### ISSUE TITLE
mac osx run warpctc/lstm_ocr.py error 

### ISSUE THREAD

**Issue by sinmaystar** [dmlc/mxnet#2786]
I have install baidu warp-ctc and rebuild mxnet but it occurs an error
AttributeError: 'module' object has no attribute 'WarpCTC'
how can I solve this problem?

**Comment by Hidayat786** [comment]
Hi Sinmaystar,

I got the Same what you did to resolve the error.
I build warp-ctc 
i did changes in Config.mk after that i rebuild mxnet
but when i run the Code i get the same error

thanks,
