### ISSUE TITLE
Using target_shape will be deprecated

### ISSUE THREAD

**Issue by George19890617** [dmlc/mxnet#2788]
I got the exception as the issue title when I run char-rnn.py

2016-07-21 11:33:19 (47.6 KB/s) - 已保存 “lab_data.zip” [22078106/22078106])

Archive:  lab_data.zip
  inflating: obama.txt               
  inflating: obama-0075.params       
  inflating: obama-symbol.json       
Summary of dataset ==================
bucket of len 129 : 8290 samples
[11:33:20] /data2/rd/George_Xia/mxnet/src/operator/./reshape-inl.h:249: Using target_shape will be deprecated.
11:33:20 INFO:Start training with [gpu(2)]
[11:33:20] /data2/rd/George_Xia/mxnet/src/operator/./reshape-inl.h:249: Using target_shape will be deprecated.
[11:33:21] /data2/rd/George_Xia/mxnet/src/operator/./reshape-inl.h:249: Using target_shape will be deprecated.
[11:33:21] /data2/rd/George_Xia/mxnet/src/operator/./reshape-inl.h:249: Using target_shape will be deprecated.
11:33:44 INFO:Epoch[0] Batch [50]	Speed: 70.43 samples/sec	Train-Perplexity=28.766350
11:34:07 INFO:Epoch[0] Batch [100]	Speed: 69.15 samples/sec	Train-Perplexity=22.018372
11:34:30 INFO:Epoch[0] Batch [150]	Speed: 69.16 samples/sec	Train-Perplexity=21.669704
11:34:53 INFO:Epoch[0] Batch [200]	Speed: 69.23 samples/sec	Train-Perplexity=21.578391
11:35:16 INFO:Epoch[0] Batch [250]	Speed: 69.04 samples/sec	Train-Perplexity=21.549267
11:35:21 INFO:Epoch[0] Resetting Data Iterator
11:35:21 INFO:Epoch[0] Time cost=119.653
11:35:21 INFO:Saved checkpoint to "obama-0001.params"
11:35:44 INFO:Epoch[1] Batch [50]	Speed: 70.55 samples/sec	Train-Perplexity=21.455769
11:36:07 INFO:Epoch[1] Batch [100]	Speed: 69.14 samples/sec	Train-Perplexity=21.325100
11:36:30 INFO:Epoch[1] Batch [150]	Speed: 69.03 samples/sec	Train-Perplexity=21.328372
11:36:53 INFO:Epoch[1] Batch [200]	Speed: 69.14 samples/sec	Train-Perplexity=21.413074
11:37:16 INFO:Epoch[1] Batch [250]	Speed: 69.20 samples/sec	Train-Perplexity=21.151758
11:37:20 INFO:Epoch[1] Resetting Data Iterator
11:37:20 INFO:Epoch[1] Time cost=119.610
11:37:21 INFO:Saved checkpoint to "obama-0002.params"
The jokes of them. And while California, from Bush to three political points. Districts would have succeeded in her values and even job from corporate sacgifice, acan their government.The one of the world's rooms, and far was the catastrophe to achieve the same tird courage to bet the moment this service most importantly, it has to pay for the last sixteen - years that we know how during the rising cost of people, and epilepsy after generation has helped racial bracelets, and a problem that can pay for our chancents and both sides of the welcaper car can't promise that we're making important as a day. Where we need to get there. And on hybrid cars was your kids and make the easiest to careforces on idech of a story and she lost himany times we're not simply anything else."I didnt standing on their own high-priced lobbyists and through my 26st century. Time again, that we are the hope of the sort of political divo do with her cost of new resources to compromise. Already we have seen that chemical future, then at this debate that in discussion, we must ndea have no chance to private accordance off the stiff, we have the face of this means - or not will during this small market

Seems the output is not correct. (different from the one given in notebook).

what does "[11:33:21] /data2/rd/George_Xia/mxnet/src/operator/./reshape-inl.h:249: Using target_shape will be deprecated." mean? though my program is not collapsed.

**Comment by sxjscience** [comment]
@George19890617 Use `shape` instead of `target_shape`

**Comment by flyi** [comment]
I had the same problem.How to solve it? 
@sxjscience Where do I use `shape` instead of `target_shape`?
In `mxnet/src/operator/./reshape-inl.h`?

**Comment by zihaolucky** [comment]
@flyi it's an argument name in reshape

**Comment by CodePothunter** [comment]
I don't understand. @sxjscience I haven't use target_shape in rnn-char.py, so where should I replace target_shape using shape ? Thanks for your time.

**Comment by sxjscience** [comment]
@CodePothunter Try to find all the `mx.sym.Reshape` operations and replace the old onew with `mx.sym.Reshape(..., shape=(...))`

**Comment by CodePothunter** [comment]
@sxjscience Thank you very much!

**Comment by yuramalna** [comment]
@CodePothunter can you tell me how did you solve this problem?
I'm facing same problem while trying to train my model in R

**Comment by CodePothunter** [comment]
@yuramalna Hi, actually I solved by updating the code :((

**Comment by Garglesoap** [comment]
Is it a problem with the mxnet build version? I'm getting same error and do not have reShape or Shape anywhere in my code.
