### ISSUE TITLE
SliceChannel problem

### ISSUE THREAD

**Issue by liuzhi136** [dmlc/mxnet#2789]
I'm trying to use SliceChannel to split the data Variable and get SliceChannel's output. 
That's what I did:

import mxnet as mx
import numpy as np

data_sym1 = mx.symbol.Variable('data1')
data_sym2 = mx.symbol.Variable('data2')
data_sym3 = data_sym1 + data_sym2

data3_slice = mx.symbol.SliceChannel(data = data_sym3, num_outputs=5)

data1 = mx.nd.array([1,2,3,4,5])
data2 = mx.nd.array([1,2,3,4,6])

exe = data3_slice.bind(ctx = mx.gpu(), args = {'data1':data1, 'data2':data2})
exe.forward()
res = exe.outputs[0]
print(type(res))
print(res.asnumpy())

I get the error as below:
D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [13:43:12] d:\chhong\mxnet\mshadow\mshadow\./tensor_blob.h:647: Check failed: (this->shape_.Size()) ==(shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements

I want to know why this error hanppen. Does any one can explain it for me? Any explain will be appreciated!
@pluskid @xlvector

**Comment by sxjscience** [comment]
@liuzhi136 You need to set the `axis`, which is 1 by default. Change the line to
```
data3_slice = mx.symbol.SliceChannel(data = data_sym3, num_outputs=5, axis=0)
```

**Comment by liuzhi136** [comment]
@sxjscience Thanks for your reply. I just try it. It does make sense. When I print the result, I always get only one output. Now I realize there are five outputs in the exe.outputs. So exe.outputs[0] is one result. Thanks a lot!

**Comment by liuzhi136** [comment]
@sxjscience Do you know the meaning about squeeze_axis parameter? I realy do not understand the explaination of it  in the doc page.

**Comment by sxjscience** [comment]
@liuzhi136 Suppose you have a tensor with shape (3, 10, 5). If you slice it using `SliceChannel(data, num_outputs=10, squeeze_axis=True)`, you can get ten (3, 5) tensors. If `squeeze_axis=False`, you will get ten (3, 1, 5) tensors.

**Comment by liuzhi136** [comment]
@sxjscience  I get it. Thank you so much! This parameter just form data into concise way, right?

**Comment by sxjscience** [comment]
@liuzhi136 Yes. It can be useful in slicing the time-series data used in RNN.
