### ISSUE TITLE
python numpy [:,:,]  to  scala NDArray 

### ISSUE THREAD

**Issue by rightwaitforyou** [dmlc/mxnet#2801]
in python 
    boxes = np.reshape(output[1078:],(7,7,2,4))
   boxes[:,:,:,0] += offset
   boxes[:,:,:,1] += np.transpose(offset,(1,0,2))
   boxes[:,:,:,0:2] = boxes[:,:,:,0:2] / 7.0
   boxes[:,:,:,2] = np.multiply(boxes[:,:,:,2],boxes[:,:,:,2])
  boxes[:,:,:,3] = np.multiply(boxes[:,:,:,3],boxes[:,:,:,3])
 
How to convert the scala NDArray code ?
     the  boxes[:,:,:,0]  the NDArray scala not provide the function

**Comment by rightwaitforyou** [comment]
@tqchen @Ldpe2G

**Comment by rightwaitforyou** [comment]
@piiswrong

**Comment by Ldpe2G** [comment]
@rightwaitforyou In my opinion, suppose boxes is the scala NDArray object, then I will use boxes.toArray
to get the data, for examle boxesArray, then I can do all the operation on this array, finally just do
boxes.set(boxesArray).
