### ISSUE TITLE
MXNet throw 'vector iterator not dereferencable' error in DEBUG version

### ISSUE THREAD

**Issue by dianyancao** [dmlc/mxnet#2810]
When I try to debug MXNet with lstm bucketing example(and I tested some others) by vs2013,
MXNet throw 'vector iterator not dereferencable' error in DEBUG version,
but it does not occur in RELEASE version.
The error is from function
'GraphExecutor::CachedSegOpr GraphExecutor::CreateCachedSegOpr' at 1086 line
I use the test code at this link:
https://github.com/dianyancao/mxnet/blob/master/example/rnn/lstm_bucketing.py

How to fix this error?

**Comment by piiswrong** [comment]
@tqchen

**Comment by horsepurve** [comment]
I have the same problem while compiling with OpenBLAS on windows, but with MKL it's fine.

**Comment by dianyancao** [comment]
Thanks to https://github.com/dmlc/mxnet/issues/2879,change 1084 line in 'graph_executor.cc' to
‘’‘if (wit == write_vars.end() || *wit != *rit) {’‘’ will fix this error.@horsepurve
