### ISSUE TITLE
GPU memory of NDArray cannot be cleared

### ISSUE THREAD

**Issue by wshenx** [dmlc/mxnet#2827]
A simple script would be 

    int shape[]={1000,1000}    
    Context ctx=Context::Create(static_cast<Context::DeviceType>(dev_type), dev_id);    
    NDArray* nd = new NDArray(TShape(shape, shape+2), ctx);    
    delete nd

`delete` doesnot clear the GPU memory.  Any suggestions?

**Comment by piiswrong** [comment]
memory deallocation is async. If will be cleared afterwards

**Comment by wshenx** [comment]
@piiswrong I look into the code and I find that after `PooledStorageManager::ReleaseAll()` `used_memory_` equals 0. However, `nvidia-smi` still reports memory occupied. I'm confused and not sure which is correct.

**Comment by wshenx** [comment]
update: GPU memory is only recycled when my `main` function is over and this is not surprising. However, the automatically called `GPUDeviceStorage::Free()` due to the deconstrction of `PooledStorageManager` at the end of the `main` function reports `cudaErrorCudartUnloading` and thus the allocated GPU memory is not released. 
Just for a test, I manually delete the storage manager before the `main` function ends. The allocated memory is freed as expected. So I'm wondering is it a potential bug in `PooledStorageManager` in releasing GPU memory? @piiswrong @tqchen

**Comment by wshenx** [comment]
@piiswrong @tqchen Do you think we should have an interface to clear GPU memory since there are situations users want to release all the memory allocated (#1946,#1677, #1432, #1301). Though it might be contrary to the memory usage scheme of mxnet engine, a force clear of all the memory is sometimes worthwhile.

**Comment by juguangliang** [comment]
@wshenx how do you manually delete the storage manager, can you show your codes,thanks!

**Comment by wshenx** [comment]
@juguangliang Well, the code is a little complex. You need to modified several files. The central trick is about the `ReleaseAll` function in pooled_storage_manager. The hacking steps are as follows:
1. move the ReleaseAll function to public
2. write a correspoding `void RealeaseAll(int dev_id, int dev_type)` function in storage.cc. my code is 

    void StorageImpl::ReleaseAll(int dev_id, int dev_type) {
        auto&& device = storage_managers_.at(dev_type);
        storage::StorageManager *maneger = device.Get(
                dev_id, []() {
                LOG(FATAL) <<  "Cannot Free space to a device you have not allocated";
                return nullptr;
            });
    maneger->ReleaseAll();
    }
yes, it is quite like the `Free` function, but `int dev_id, int dev_type` is easier to understand and it really frees memory rather than recycles memory.
3. use `Storage::Get()->ReleaseAll(som_dev_id, some_dev_type)` to free memory.
I have tested the code under some simple situations, like creating a NDArray an then deleting it. The code works. But when I wrote a python wrapper and used it in python ,it threw a memory exception. I didn't know why. As you see, this thread doesn't attract much attention of the core MXNet developers, so there might not be a perfect solution. Also, I think manually releasing the memory is not very safe in a very complex situation, so leting mxnet take the control maybe better. I suggest you the following way of getting rid of the memory problem.
1. use python to write your mxnet code
2. train the net using `commands.getstatusoutput('python your_model_file.py')`
you don't need to modified any source code and it also works.

**Comment by tornadomeet** [comment]
https://github.com/dmlc/mxnet/pull/2927

**Comment by wshenx** [comment]
closing. #2927 looks great
