### ISSUE TITLE
How to generate te .lst

### ISSUE THREAD

**Issue by yechaochen** [dmlc/mxnet#2829]
I have bulided the mxnet successfully and run the ~/mxnet/example/image-classification/train_mnist.py.

When I follow the introduction on the Internet  to generate the file with my data. I can't find the make_list.py in the folde ~/mxnet/tools . 

Can someone tell me how can I generate the lst file!

**Comment by luoruisichuan** [comment]
for the new verision of mxnet, make_list.py is deleted, you can get it from the old version, for instance 20160202.

**Comment by yechaochen** [comment]
@luoruisichuan Can you tell me how to run im2rec.py successfully. I have saw the code about make_list.py is insert in it. Which parameter I should set when I try to run im2rec.py.
my files structure:
images---1---
       |         |
       |         |- 1.jpg
       |         |
       |         |- 2.jpg
       |         |
       |         |- ...
       |
       |- 2 --- ...
       |
       |- 3 --- ...

**Comment by luoruisichuan** [comment]
to get .lst file
python make_list.py images/  images/train --recursive=True
then you can get train.lst in file folder images/.
to get .rec file

**Comment by luoruisichuan** [comment]
to get .lst file
python make_list.py images/  images/train --recursive=True
then you can get train.lst in file folder images/
to get .rec file
python im2rec.py images/train images/train
then you can get train.rec in file folder images/

**Comment by luoruisichuan** [comment]
to get .lst file
python make_list.py images/   images/train  --recursive=True
then you can get train.lst in file folder images/
to get .rec file
python im2rec.py images/train   images/train
then you can get train.rec in file folder images/
