### ISSUE TITLE
The runtime results of the MNIST example may be incorrect

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#283]
The [current results](https://github.com/dmlc/mxnet/tree/master/example/mnist) show that running mlp.py on 2 GPUs is slower than on 1 GPU and running lenet.py with cuDNN v3 is slower than without it. Both are very counter-intuitive and contradict with the results of the [ImageNet example](https://github.com/dmlc/mxnet/tree/master/example/imagenet) and the [CIFAR 10 example](https://github.com/dmlc/mxnet/tree/master/example/cifar10). Are the MNIST example's results incorrectly documented?

 	val accuracy 	2 x E5-2680 	1 x GTX 980 	2 x GTX 980
mlp.py MKL + CUDA 7 	97.8% 	40K img/sec 	103K img/sec 	60K img/sec
lenet.py MKL + CUDA 7 	99% 	368 img/sec 	22.5K img/sec 	33K img/sec
lenet.py MKL + CUDA 7 + CUDNN v3 	- 	- 	19K img/sec 	29 K img/sec

**Comment by antinucleon** [comment]
Since these MNIST networks are  extremely tiny, the performance number means almost nothing
