### ISSUE TITLE
Implementation of Recurrent Attention Model(RAM)

### ISSUE THREAD

**Issue by minazou** [dmlc/mxnet#2831]
Hi, I am a torch user. I want to use mxnet to implement Recurrent Attention Model layer[1]. 
After surveying, I only got "[Survey of existing interfaces and implementations](http://mxnet.readthedocs.io/en/latest/system/rnn_interface.html)."
I can't figure out how to do that. Can anyone give me some tips or advices?
Thank you so much.

[1] V. Mnih and et. al., [Recurrent Models of Visual Attention](https://papers.nips.cc/paper/5542-recurrent-models-of-visual-attention.pdf), NIPS'14.

**Comment by piiswrong** [comment]
look into examples/rnn

**Comment by liangfu** [comment]
I was interested in implementing this, and found code under `examples/reinforcement-learning` may also helpful

**Comment by minazou** [comment]
It's nice news for me.
I am being stuck by my job.
I will try to implement this after finishing my job.
Thank you.

**Comment by yufengwhy** [comment]
@minazou @liangfu @piiswrong 
Had you implemented this [1]? 
I am doing something about hard attention and policy gradient, Can anyone give me some tips or advices?

[1] V. Mnih and et. al., Recurrent Models of Visual Attention, NIPS'14.
