### ISSUE TITLE
How to use mxnet to do the multi-lable(float) regression task

### ISSUE THREAD

**Issue by yechaochen** [dmlc/mxnet#2834]
I'm a new comer of mxnet
1.The lastest version of mxnet has merge the make_list.py with im2rec.py.But there no code about lable in the im2rec.py.Where the lable information show in the training program.And how can I do it.
2.My teacher gives me multi-lable regression task.And the type of lable is float.I don't know how to do the task with mxnet.

**Comment by AlecWong** [comment]
You can refer to the code in `im2rec.py`, it supports multi-label regression. Indeed, it uses  `float(x)` to convert x from string to float-number(even x is a label).

**Comment by yechaochen** [comment]
@AlecWong I have generate the train.lst and the structrue of this file is:

**Comment by AlecWong** [comment]
http://mxnet.readthedocs.io/en/latest/packages/python/io.html
Details can be referred to in this web.

**Comment by yechaochen** [comment]
@AlecWong Thank you for your answer. The code you show `item = [int(line[0])] + [line[-1]] + [float(i) for i in line[1:-1]]`.Does this code shows that the lable could be the float type.

**Comment by AlecWong** [comment]
@yechaochen  I think even your labels are integers, it will also be converted into float-type.  You'd better try it, and to see whether or not.

**Comment by yechaochen** [comment]
@AlecWong WOW....!How do you always online!
I meet a problem after I creat lst file with im2rec.py.
My images is like this:
`20090909_033109.jpg
 20090909_034115.jpg
 20090909_035131.jpg
 20090909_040120.jpg
 20090909_042113.jpg
 20090909_043144.jpg
 20090909_044122.jpg
 20090909_045112.jpg
 20090909_050124.jpg
 20090909_051120.jpg
 20090909_053128.jpg
 20090909_054137.jpg
`
You can observed that it is ordered.After I have run im2rec.py and creat the lst file and the deatails show like:
`0       0       one/20090909_043144.jpg
1       0       one/20090909_034115.jpg
2       0       one/20090909_040120.jpg
3       0       one/20090909_051120.jpg
4       0       one/20090909_035131.jpg
5       0       one/20090909_045112.jpg
6       0       one/20090909_033109.jpg
7       0       one/20090909_044122.jpg
8       0       one/20090909_054137.jpg
9       0       one/20090909_050124.jpg
10      0       one/20090909_053128.jpg
11      0       one/20090909_042113.jpg
`
Its disordered.I this case,I don't know how to copy my lable in the file.My lable is ordered and I have thousand of labels.WTF!!!

**Comment by AlecWong** [comment]
@yechaochen  im2rec `make_list` will shuffle the data.
If you do not want to disorder your data, u'd better to create the lst file by yourself. Or simply modify the codes in im2rec.py. 

```
def make_list(prefix_out, root, recursive, exts, num_chunks, train_ratio):
    image_list = list_image(root, recursive, texts
    random.seed(100)
    random.shuffle(image_list) #<- this line.
    N = len(image_list)
    chunk_size = (N+num_chunks-1)/num_chunks
    for i in xrange(num_chunks):
        chunk = image_list[i*chunk_size:(i+1)*chunk_size]
        if num_chunks > 1:
            str_chunk = '_%d'%i
        else:
            str_chunk = ''
        if train_ratio < 1:
            sep = int(chunk_size*train_ratio)
            write_list(prefix_out+str_chunk+'_train.lst', chunk[:sep])
            write_list(prefix_out+str_chunk+'_val.lst', chunk[sep:])
        else:
            write_list(prefix_out+str_chunk+'.lst', chunk)
```)

**Comment by yechaochen** [comment]
@AlecWong I have set -shuffle False.

**Comment by yechaochen** [comment]
@AlecWong I insert the code `print image_list` under the second line of `make_list` function. And the output shows that the image_list is disordered
