### ISSUE TITLE
mac osx use gpu occurs problem

### ISSUE THREAD

**Issue by sinmaystar** [dmlc/mxnet#2837]
I have modify config.mk file,
USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda
USE_CUDNN = 1
USE_NVRTC = 1
and then make the mxnet successfully, install python package successfully
but when I run train_mnist.py it occurs a problem

mxnet.base.MXNetError: [21:34:53] src/storage/storage.cc:43: Please compile with CUDA enabled

how can solve this problem?

**Comment by piiswrong** [comment]
you need to `cp make/osx.mk config.mk` then modify the config.mk in root folder

**Comment by sinmaystar** [comment]
I have already do it，and compile successfullyyou need to cp make/osx.mk config.mk then modify the config.mk in root folder

**Comment by piiswrong** [comment]
make clean and recompile

**Comment by sinmaystar** [comment]
I have recompile many times，but still have this problem，I can use gpu on keras code
            在2016年07月26日 08:17，Eric Junyuan Xie 写道:make clean and recompile
