### ISSUE TITLE
BroadcastDivBackward_ not safe with 0

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#2843]
Hi,
 I got some issue in [BroadcastDiv ](https://github.com/dmlc/mxnet/blob/master/src/operator/elementwise_binary_broadcast_op-inl.h#L357-#L359)when trying FP16. I noticed that the numerator in BroadcastDivBackward_  is computed using `mshadow_op::square` and not checking if zero is given.

**Comment by sxjscience** [comment]
@Godricly Division should be non-differentiable when the denominator is zero.

**Comment by Godricly** [comment]
In my case, the value are small before square takes action. I think the square is returning sth with zero, which leads NaN in my case.

**Comment by sxjscience** [comment]
@Godricly I see. We can add another eps value to the denominator when calling `broadcast_div`. Like `c = mx.sym.broadcast_div(a, b + 1E-6)`

**Comment by Godricly** [comment]
1e-6 is too small for FP16 case. I'll give it a try with bigger value though.  It looks good for me now if using float type.

**Comment by sxjscience** [comment]
Yes. We can tune the eps value. Let's keep the inner logic of this operator first and adopts this solution.
