### ISSUE TITLE
How to create Dataset Using RecordIO when the model's output is image?

### ISSUE THREAD

**Issue by bertjiazheng** [dmlc/mxnet#2846]
In the image classification task, the model's output is a label. So image list file's format is
`integer_image_index \t label_index \t path_to_image`
But when the model's output is a image, such as image restoration, how can I create my dataset using RecordIO.

**Comment by metorm** [comment]
Hi bro, have you found how to do this? I think I am faced with the same problem

**Comment by bertjiazheng** [comment]
You can refer to [fcn](https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/data.py)

**Comment by metorm** [comment]
Thank you ~
So, I have to manage my data by my own instead of using RecordIO. Maybe using a database is a good idea ...
