### ISSUE TITLE
Does the /mxnet/bin/im2rec support the float type label?

### ISSUE THREAD

**Issue by yechaochen** [dmlc/mxnet#2851]
I can't see the code about /mxnet/bin/im2rec, I don't know whether the program support the float type label or not!
And I have two label in my task.Should I run the program like:
`./im2rec /path/to/lst /path/to/image/folder output_path/***.rec resize=256 label_width=2`?

**Comment by bertjiazheng** [comment]
[#2834](https://github.com/dmlc/mxnet/issues/2834)

**Comment by tornadomeet** [comment]
@yechaochen yes, it support. your command is right.

**Comment by yechaochen** [comment]
@tornadomeet Thank you for your answer!
I have see that we can change the code in the function named `read_list` definded in the `/mxnet/tools/im2rec.py`which can support the float lable.
But I run the program failed.So I use /mxnet/bin/im2rec to transform my data but I don't know whether this program support the float type lable.

**Comment by tornadomeet** [comment]
i always use im2rec.cc, it support, you can refer to https://github.com/tornadomeet/mxnet-face/blob/master/attribute/run.sh#L54
