### ISSUE TITLE
PReLU problem

### ISSUE THREAD

**Issue by taoari** [dmlc/mxnet#2856]
I am wondering if https://github.com/dmlc/mxnet/blob/master/src/operator/leaky_relu-inl.h#L179-L180 is a bug for the PReLU. Because for the other activation types, the format is like `Assign(gdata, req[leakyrelu::kData], ...)`, while for PReLU, it uses `gdata=...`. 

My problem is that when I am replacing ReLU with PReLU in a network, the performance gets much lower.

![figure_1](https://cloud.githubusercontent.com/assets/3815006/17169582/bae8876a-541a-11e6-8766-1076b0ac078b.png)

And the PReLU gamma parameters can grow very large:

![figure_2](https://cloud.githubusercontent.com/assets/3815006/17169775/a9c5d27a-541b-11e6-958a-e380a31df469.png)

This is different from what https://arxiv.org/abs/1502.01852 has described. As the PReLU version should work better than the ReLU version, and the PReLU gamma parameters should roughly stay around 0.25 even without bounding the parameters.

**Comment by taoari** [comment]
@sxjscience I am changing it to:

```
Assign(grad_weight, req[leakyrelu::kGamma], sumall_except_dim<1>(F<prelu_grad>(data) * grad));
Assign(gdata, req[leakyrelu::kData], F<mshadow_op::xelu_grad>(output, broadcast<1>(weight, data.shape_)) * grad);
```

The gamma of prelu is still growing to very large values. 

The above place should not be the reason for the divergence of the gamma values, as the default is "write" gradreq, and it will not affect the results.

**Comment by sxjscience** [comment]
@taoari Yes, this should not be the cause.

**Comment by taoari** [comment]
@sxjscience I am wondering that this problem may be caused by the channel sharing of the PReLU parameters. And I am trying to add the `channel_shared` parameter to the PReLU. However, I am encountering a problem to sum of the all elements. It seems that mshadow does not contain a `sumall` function. Will you give me some advice to how to implement the `sumall` function?

More specificly, https://github.com/dmlc/mxnet/blob/master/src/operator/leaky_relu-inl.h#L179-L180 is changed to:

```
if (!param_.channel_shared) {
  Assign(grad_weight, req[leakyrelu::kGamma], sumall_except_dim<1>(F<prelu_grad>(data) * grad));
  Assign(gdata, req[leakyrelu::kData],
    F<mshadow_op::xelu_grad>(output, broadcast<1>(weight, data.shape_)) * grad);
} else {
  Assign(grad_weight, req[leakyrelu::kGamma], sumall(F<prelu_grad>(data) * grad)); // sumall?
  Assign(gdata, req[leakyrelu::kData],
    F<mshadow_op::xelu_grad>(output, weight[0]) * grad); // broadcast<1>(weight, data.shape_)) * grad);
}
```

But how can I write the `sumall` function?

**Comment by bradcar** [comment]
Hi taoari, I have been unable to find out how to properly use prelu in MXNet: 
        x = F.LeakyReLU(self.conv4(x), act_type='prelu')
I get this error:
[[11:04:52] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [11:04:52] src/c_api/c_api_ndarray.cc:76: Check failed: num_inputs == infered_num_inputs (1 vs. 2) Operator LeakyReLU expects 2 inputs, but got 1 instead.

any insights?
