### ISSUE TITLE
How to access an entry of a Tensor in mshadow when using GPU mode?

### ISSUE THREAD

**Issue by morningpig917** [dmlc/mxnet#2862]
I want to create a new operator to implement hierarchical softmax by writing C++ code. At the moment, the operator works fine in CPU mode, but will crash in GPU mode. One cause of this issue is that I need to access an entry in a Tensor, i.e.,

`Tensor<xpu, 2, DType> label = in_data[hsoft::kLabel].get<xpu, 2, DType>(s);`
...

`if(label[m][n]==2.0){//crashes here`

....
`}`
....

So what is the correct way to access one entry in GPU mode? Thanks.

**Comment by piiswrong** [comment]
You can't directly access memory on GPU.

**Comment by morningpig917** [comment]
Yes. Finally solved by copying data to host.
