### ISSUE TITLE
Does the mx.symblo.LineaRregressionOutput surpot the multi-lable?

### ISSUE THREAD

**Issue by yechaochen** [dmlc/mxnet#2863]
I am building my net in symbol.***.py. And the task I do is a multi-lable regression task.
I think the LinearRegressionOuput can surport the regression task. But I don't know whether it surpport the multi-lable?
The output of my net is a 2 dimension feature. Can the LinearRegressionOuput recognize it?

If the function does't work. Which function should I use?

**Comment by tornadomeet** [comment]
yes, it support.
