### ISSUE TITLE
issues downloading pretrained models for example/fcn-xs

### ISSUE THREAD

**Issue by martinbel** [dmlc/mxnet#2864]
First of all congrats for the great library and variety of examples!! I'm having trouble downloading the pre-trained models from the current location (the connection just crashes and it's extremely slow). Perhaps this is because my current location (Argentina), a bit far from baidu servers. 

A few ideas:
- Add or Move the VGG models to another server. The dmlc server works fine for me, I can upload them from my google drive if needed. 
- Use the original link for VOC2102. I believe this is the [data link](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar)

**Comment by tornadomeet** [comment]
@martinbel hello, here is the dropbox link: https://github.com/dmlc/mxnet/issues/1823  i made the example but i have no permission to upload the model/data, so sorry for the inconvenience.

**Comment by tornadomeet** [comment]
your data link is correct.

**Comment by martinbel** [comment]
thanks!!
