### ISSUE TITLE
How to build input data in prediction when using trained model with Embedding layer in example/cnn_text_classification

### ISSUE THREAD

**Issue by GuohongLi** [dmlc/mxnet#2865]
In example/cnn_text_classification/text_cnn.py
`    # embedding layer
    if not with_embedding:
        embed_layer = mx.sym.Embedding(data=input_x, input_dim=vocab_size, output_dim=num_embed, name='vocab_embed')
        conv_input = mx.sym.Reshape(data=embed_layer, target_shape=(batch_size, 1, sentence_size, num_embed))`

After training with embedding layer, I cannot get the right way to use model to predict new input data. 
Can I just build the one-hot vector input and model in it self will infer the embedding vector for prediction,just like this?
`x = np.array([[vocabulary[word] for word in sentence] for sentence in sentences])
 tmp_model = mx.model.FeedForward.load(prefix, load_epoch, ctx=mx.cpu())
model = mx.model.FeedForward(symbol=tmp_model.symbol, ctx=mx.cpu(), numpy_batch_size=1, arg_params=tmp_model.arg_params, aux_params=tmp_model.aux_params)
prediction = model.predict(x)`

**Comment by GuohongLi** [comment]
@qcl6355  Looking forward

**Comment by zihaolucky** [comment]
After load the model. Get its params and find the embedding layer, you can get its parameter there.

**Comment by GuohongLi** [comment]
@zihaolucky Can u paste a code here ? thanks
