### ISSUE TITLE
Difference between argmax() and sample in lstm

### ISSUE THREAD

**Issue by liuzhi136** [dmlc/mxnet#2866]
I'm still confused when I read the follow code.
# we can use random output or fixed output by choosing largest probability
def MakeOutput(prob, vocab, sample=False, temperature=1.):
    if sample == False:
        idx = np.argmax(prob, axis=1)[0]
    else:
        fix_dict = [""] + [vocab[i] for i in range(1, len(vocab) + 1)]
        scale_prob = np.clip(prob, 1e-6, 1 - 1e-6)
        rescale = np.exp(np.log(scale_prob) / temperature)
        rescale[:] /= rescale.sum()
        return _choice(fix_dict, rescale[0, :])
    try:
        char = vocab[idx]
    except:
        char = ''
    return char
usually, I think we should choose the largest probability of a word in output. Why it have another way to  choose a random word? What's that mean(I also see the same way in Andrej Karpathy's blog)? Could any one explain it for me? Any explanation will be grateful!

**Comment by starimpact** [comment]
what is the "_choice"?

**Comment by liuzhi136** [comment]
@starimpact this is a help function to sample word randomly.
def _choice(population, weights):
    assert len(population) == len(weights)
    cdf_vals = _cdf(weights)
    x = random.random()
    idx = bisect.bisect(cdf_vals, x)
    return population[idx]

**Comment by starimpact** [comment]
what is the "_cdf"?

**Comment by sxjscience** [comment]
@liuzhi136 That is to sample from $p(x_{t+1} | \hat{x}_{1:t})$. This may be helpful for multi-step prediction. You can refer to the theory of Sequential Monte-Carlo (https://en.wikipedia.org/wiki/Particle_filter).

**Comment by starimpact** [comment]
@sxjscience cannot see the formula.

**Comment by liuzhi136** [comment]
@sxjscience It's difficult for me to understand the article in (https://en.wikipedia.org/wiki/Particle_filter).  Formula's meaning is word's prob of x_t+1 given first t words. Is that right?

**Comment by sxjscience** [comment]
@liuzhi136 Yes. Assume we want to predict the next k words, i.e, x_{t+1:t+k}. The estimator can be $\arg\max_{x_{t+1:t+k}} p(x_{t+1:t+k}) \mid \hat{x}_{1:t})$. The rest problem is how to solve this optimization problem based on our model for one-step prediction, which is given by the RNN. One observation is that for every specific $x_{t+1:t+k}$, we can easily compute its probability. However, it would be impossible for us to enumerate all the combinations and we need to find some approximate solutions. There are two possible ways for that, Beam Search (deterministic) and Sequential Monte-Carlo (probabilistic). For beam search, the idea is to always keep the word trajectories that have the highest likelihood. For sequential monte-carlo, the idea is to give a particle approximation of the distribution and update these particles.

**Comment by liuzhi136** [comment]
@sxjscience Thank you so much. I think I got the main idea after reading your explanation.
