### ISSUE TITLE
Windows Binary Distribution

### ISSUE THREAD

**Issue by hjk41** [dmlc/mxnet#287]
1. **[Python]** support *pip install*
2. **[R]** provide R package
3. **[C++ Linux]** packing mxnet.a?
4. **[C++ Windows]** it is best if we can pack everything into mxnet.lib. However, OpenBLAS does not provide static library on Windows. So maybe a redistribution of the dependent libraries is needed. Is @happynear interested in contributing?

**Comment by tqchen** [comment]
@hjk41 We do not want to pack a binary lib file, mainly for License issues. I

For now, we are fine with a windows binary dll file, and have a script(or provide instruction) to help user to download the other dependent dll from their official site.

All the python and R binary distribution can dependent on this one. We do not need to distribute binary for now on linux

**Comment by hjk41** [comment]
@tqchen now we have both CPU and GPU version of binary distribution on Windows. I also wrote a script that will setup the environmental variables (MXNET_HOME and PATH). 

Due to dynamic linkage of cuda runtime, the size of GPU version is huge. Don't know if we can trim it down further.

**Comment by thirdwing** [comment]
I will test the R package using your dll right now.

**Comment by tqchen** [comment]
@hjk41 I guess we can simply not provide CUDNN and CUDA runtime, and dynamically link to them. Since most CUDA users should have already installed them somewhere in the PATH

**Comment by hjk41** [comment]
I am not sure if it will work with different CUDA runtime version.
Currently I use 7.5. Since CUDA runtime can be packaged in our distribution
without any license issue, I just packed it in.

On Wed, Oct 21, 2015 at 12:00 AM, Tianqi Chen <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41> I guess we can simply not provide CUDNN
> and CUDA runtime, and dynamically link to them. Since most CUDA users
> should have already installed them somewhere in the PATH
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/287#issuecomment-149615881>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by tqchen** [comment]
I see, let us keep it as it is then.

**Comment by tqchen** [comment]
But maybe not hurt to check. I guess it might be runtime independent, as long as you compile with compile compatibility. i.e. sm_xx  Maybe others who are more familiar can confirm this.

@happynear

**Comment by hjk41** [comment]
updated setupenv.cmd
