### ISSUE TITLE
Embedding layers that share `weight` still allocate their matrices separately?

### ISSUE THREAD

**Issue by SkidanovAlex** [dmlc/mxnet#2877]
Hi, I have a question regarding the embedding layers. Consider the following code:

```
import mxnet as mx
import os

test_embeddings = True
test_concat = True

ctx = mx.gpu(0)
in_dim = 200000
out_dim = 10

weight = mx.sym.Variable(name='moo_weight')
inp = mx.sym.Variable(name='inp')

if test_embeddings:
    f1 = mx.sym.Embedding(data=inp, weight=weight, input_dim=in_dim, output_dim=out_dim)
    f2 = mx.sym.Embedding(data=inp, weight=weight, input_dim=in_dim, output_dim=out_dim)
else:
    f1 = mx.sym.FullyConnected(data=inp, weight=weight, no_bias=True, num_hidden=out_dim)
    f2 = mx.sym.FullyConnected(data=inp, weight=weight, no_bias=True, num_hidden=out_dim)

if test_concat:
    f = mx.sym.Concat(f1, f2)
else:
    f = f1

arg_names = f.list_arguments()
arg_shape, out_shape, aux_shape = f.infer_shape(inp = (128, in_dim))
print arg_shape

arg_arrays = [mx.nd.zeros(shape, ctx) for shape in arg_shape]

f.bind(ctx=ctx, args=arg_arrays)

os.system("nvidia-smi")
```

Note the two flags at the beginning, `test_embeddings` and `test_concat`. The logic here is the following: I create a very simple graph, consisting of an input layer with 100000 features, then either one (if `test_concat` is False) or two (if `test_concat` is True) parallel embeddings, that **share their weights** (this is important), optionally followed by a Concat (only if there are two embeddings). `test_embeddings` controls whether I use `Embedding` layer for embeddings or a `FullyConnected` layer.

I then bind the symbol and trace the memory consumption.

Now, here's the behavior that I would expect:

1. FullyConnected layer and Embedding layer should consume the same amount of GPU memory
2. Having two Embedding or FullyConnected layers in the graph that share weights should not increase the memory consumption.

This is what I observe:

1. Fully connected layers:
One: 314MB
Two: 314MB

2. Embedding layers:
One: 1290MB
Two: 4220MB

Note that not only single embedding consumes significantly more memory than FullyConnected layer (I can potentially explain it by alignment, since Embedding's weight shape is (1000000, 10), while FullyConnected's one is (10, 100000)), but also introducing the second Embedding **more than doubles** the memory consumption.

Is it the expected behavior of the `Embedding` layer? It is a show stopper for LSTM language models with large vocabularies, because in such a model I would have dozens of `Embedding` layers sharing the weight matrix, and having the input dimension of 70K. If each of them allocates separately, I can't fit any reasonably sized LSTM on my Titan X. Moreover, I would then question if such Embedding layers share their weights at all, and if they actually learn together in such case.

**Comment by sxjscience** [comment]
@SkidanovAlex In this test case, the shape of `inp` is  (128, 200000). The embedding layer will output a tensor with shape (128, 200000, 10) while the FC layer will output a (128, 10) tensor. The output tensor dominates the memory consumption, which explains the doubling behavior.

Also, for the embedding layer, the input are integers before one-hot encoding.

**Comment by starimpact** [comment]
why do we need embedding_layer?

**Comment by sxjscience** [comment]
@starimpact E.g word embedding

**Comment by SkidanovAlex** [comment]
@sxjscience, I trace the shapes in the script provided, and they are consistent with what I originally posted:
1. FC layer will have shape `(10, 200000)`, not `(128, 10)`.
2. Embedding layer has shape `(200000, 10)`, moreover it asserts in the `embedding-imp.h`  that the weight tensor is two dimensional :)

But I agree that my example overall is wrong, since the input shape for the embedding layer should be one-dimensional. When I fix it by changing this line:

`arg_shape, out_shape, aux_shape = f.infer_shape(inp = (128, in_dim))`

with

`arg_shape, out_shape, aux_shape = f.infer_shape(inp = (128,) if test_embeddings else (128, in_dim))`

It stops exploding memory, so I guess it is somehow specific to providing 2d input to the Embedding tensor. I would still consider the original issue posted as worth investigating (it is not obvious why should memory double if the input to the Embedding layer is two dimensional), but since it works properly for the 1d input, which is the intended use case, I guess my original suspicion that Embedding layers do not share weights is incorrect.

**Comment by sxjscience** [comment]
@SkidanovAlex Embedding layer supports 2D input. You can print the out_shape and the out_shape of embedding layer should be (128, 200000, 10) while the out_shape of fc layer should be (128, 10). That should be the cause.

**Comment by sxjscience** [comment]
@SkidanovAlex  My previous explanation is not so clear. What I mean is that the total memory consumption consists of both the allocation of network arguments (e.g the embedding weight) and the allocation of input/output tensors. For the embedding layer, the shape of the output tensor will be (128, 400000, 10) after concatenation, which is two times larger than the non-concatenation case. Since the output tensor is much larger than the embedding weight whose shape is (200000, 10), it will dominate the memory consumption.

**Comment by SkidanovAlex** [comment]
@sxjscience thanks, it makes perfect sense.
