### ISSUE TITLE
segmentation fault during compilation

### ISSUE THREAD

**Issue by JohanCao** [dmlc/mxnet#2881]
Hi all,

When I tried to compile the mxnet I got the following errors:
--------------------------------------------------------------------
.
.
.
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o local_filesys.o src/io/local_filesys.cc
/usr/local/cuda/bin/nvcc -c -o build/src/operator/cast_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/johancao/tools/mxnet/mshadow/ -I/home/johancao/tools/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=0" src/operator/cast.cu
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o data.o src/data.cc
Segmentation fault (core dumped)
make: *** [build/src/ndarray/ndarray_function_gpu.o] Error 139
make: g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o recordio.o src/recordio.cc
*** Waiting for unfinished jobs....
Segmentation fault (core dumped)
make: *** [build/src/operator/activation_gpu.o] Error 139
g++ -c -O3 -Wall -msse2  -Wno-unknown-pragmas -Iinclude  -std=c++0x -fopenmp -fPIC -DDMLC_USE_HDFS=0 -DDMLC_USE_S3=0 -DDMLC_USE_AZURE=0 -o config.o src/config.cc
ar cr libdmlc.a line_split.o recordio_split.o input_split_base.o io.o local_filesys.o data.o recordio.o config.o
make[1]: Leaving directory `/home/johancao/tools/mxnet/dmlc-core'
Segmentation fault (core dumped)
make: *** [build/src/operator/batch_norm_gpu.o] Error 139
Segmentation fault (core dumped)
make: *** [build/src/operator/block_grad_gpu.o] Error 139
Segmentation fault (core dumped)
make: *** [build/src/operator/cast_gpu.o] Error 139
Segmentation fault (core dumped)
make: *** [build/src/operator/broadcast_reduce_op_gpu.o] Error 139
---------------------------------------------------------------------------------------------------------------

Here is the info of my machine:
System: Ubuntu 14.04
gcc: 4.8.4
cuda: tried on both 7.0 & 7.5

Has anyone got any idea? Many thanks!!!

Best,
Johan

**Comment by piiswrong** [comment]
Looks like your OS/toolchain is corrupted

**Comment by JohanCao** [comment]
But I have tried erase disk and re-install OS several times, the errors still exist

**Comment by JohanCao** [comment]
Problem solved, turned out to be a hardware problem
