### ISSUE TITLE
How to generate the mean file of a dataset used in the iterator.

### ISSUE THREAD

**Issue by yechaochen** [dmlc/mxnet#2883]
I notice that some experiments should use the mean_img file and set the path of the mean_img in the iterator.But I can't find a tool in the mxnet that generate the mean file.
Can someone tell me how to do it ?

**Comment by ApprenticeZ** [comment]
If you are using `io.ImageRecordIter`, mean img will be automatically created if it is missing, as indicated  by the source code [here](https://github.com/dmlc/mxnet/blob/master/src/io/iter_normalize.h#L216)
