### ISSUE TITLE
Installing R package on windows

### ISSUE THREAD

**Issue by R1ncy** [dmlc/mxnet#2892]
Hi, thanks for your attention. I'm in troubles with installing R package.
I've tried Building the package in Windows, using Cmake to get the solution and compile it. After that, I get the "libmxnet.dll" in "/build/Release/".

Then I followed http://mxnet.readthedocs.io/en/latest/how_to/build.html#r-package-installation 
to get R package. 

![d ar 08g yz5 n1 2ez9 7](https://cloud.githubusercontent.com/assets/20101618/17288149/140e47c8-5806-11e6-97c4-544b99466c1a.png)

What should I do to get the R-package? Thanks a lot.

**Comment by R1ncy** [comment]
then i use: mingw32-make rpkg
here is the output:

process_begin: CreateProcess(NULL, uname -s, ...) failed.
mingw32-make: make/config.mk:65: pipe: No error
Rscript -e "require(roxygen2); roxygen2::roxygenise(\"R-package\")"
roxygen2
Error in file.path(path, "man") : 'R'
Calls: <Anonymous> -> first_time -> dir -> file.path

Makefile:225: recipe for target 'roxygen' failed
mingw32-make: *** [roxygen] Error 1

**Comment by thirdwing** [comment]
Is there any specific reason for not using the pre-built R package?

**Comment by R1ncy** [comment]
@thirdwing  thanks for your reply.
I have installed these R package in Rstudio by using:

install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")

And the version of roxygen2 package is  5.0.1.
Then I used these at root folder:

Rscript -e "install.packages('devtools',repo = 'https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
cd R-package
Rscript -e "library(devtools); library(methods); options(repos=c(CRAN='https://mirrors.tuna.tsinghua.edu.cn/CRAN/')); install_deps(dependencies = TRUE)"
cd ..
mingw32-make rpkg

But it prints:

D:\mxnet-new\mxnet-master>mingw32-make rpkg
process_begin: CreateProcess(NULL, uname -s, ...) failed.
mingw32-make: make/config.mk:65: pipe: No error
Rscript -e "require(roxygen2); roxygen2::roxygenise(\"R-package\")"
roxygen2
Error in file.path(path, "man") : 'R'
Calls: <Anonymous> -> first_time -> dir -> file.path

Makefile:225: recipe for target 'roxygen' failed
mingw32-make: *** [roxygen] Error 1

**Comment by thirdwing** [comment]
```r
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")
```

After these three lines of code, you have `mxnet` installed. So why you keep trying to compile from source by yourself?

**Comment by R1ncy** [comment]
@thirdwing the mxnet package installed by these three lines is not the latest. I can't use some new functions and params.

**Comment by R1ncy** [comment]
it seems there is something wrong with the roxygen2 package. i try to use it in version 5.0.0 and 5.0.1, but the output is the same.

**Comment by R1ncy** [comment]
@thirdwing  sorry to disturb again.  I get the R package mxnet_0.7.tar.gz now.
but when i used "R CMD INSTALL" or "R CMD INSTALL --no-multiarch" , met with new difficulties.

D:\mxnet-new\mxnet-master>R CMD INSTALL mxnet_0.7.tar.gz
* installing to library 'D:/R-3.2.5/library'
* installing *source* package 'mxnet' ...
** libs
g++ -m64 -I"D:/R-3.2.5/include" -DNDEBUG -I../inst/include   -I"D:/R-3.2.5/libra
ry/Rcpp/include" -I"d:/RCompile/r-compiling/local/local323/include"     -O2 -Wal
l  -mtune=core2 -c executor.cc -o executor.o
In file included from executor.cc:9:0:
./base.h:12:23: fatal error: dmlc/base.h: No such file or directory
compilation terminated.
make: *** [executor.o] Error 1
Warning: 'make -f "Makevars.win" -f "D:/R-3.2.5/etc/x64/Makeconf" -f "D:/R-3.2.5
/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_C
XXLD)' SHLIB="mxnet.dll" WIN=64 TCLBIN=64 OBJECTS="executor.o export.o io.o kvst
ore.o mxnet.o ndarray.o symbol.o"'2
ERROR: compilation failed for package 'mxnet'
* removing 'D:/R-3.2.5/library/mxnet'
* restoring previous 'D:/R-3.2.5/library/mxnet'

what should i do to fix it? thank you !

**Comment by thirdwing** [comment]
Missing files are from https://github.com/dmlc/mxnet/tree/master/include/mxnet and https://github.com/dmlc/dmlc-core/tree/master/include/dmlc

Windows pre-built pkg should be updated, but I don't have access to a Windows machine. But for common usage, it should be OK.
