### ISSUE TITLE
Does mxnet support cuda 8.0?

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#2899]
I wonder if  version windows 20160223 of mxnet support cuda 8.0? Thank you

**Comment by wangg12** [comment]
seems not

**Comment by albertyou2** [comment]
@wangg12 Thanks for reply! My display card is Geforce GTX 1070. You mean mxnet does NOT support this device? Because  CUDA 7.5 may not  support   Geforce GTX 1070.
Am i right?

**Comment by wangg12** [comment]
@albertyou2 I can use mxnet(the latest windows version) on windows with cuda 7.5 and GTX 1060 but I can't use cuda 8.0.

**Comment by piiswrong** [comment]
8.0 should be supported. At least for linux

**Comment by thirdwing** [comment]
GTX 1080, ubuntu 16.04, CUDA8.

mxnet works without any problems.

**Comment by wangg12** [comment]
Cuda 8.0 works for ubuntu but on windows may need to build from source.

**Comment by albertyou2** [comment]
@wangg12    Which  version  of mxnet  you are using on windows?The Binary version windows20160531 ? And does cuda7.5 support gtx 1070? 
@thirdwing  Thank you.Which  version  of mxnet  you are using on linux? the lasted clone of master?

**Comment by wangg12** [comment]
@albertyou2   I can use the windows version 20160531 and this(#2813). Cuda7.5 should supportgtx 1070 on windows(remember not to install the old version driver when install cuda toolkit).

**Comment by albertyou2** [comment]
@wangg12 Thank you very much! I 'll try this

**Comment by starimpact** [comment]
just work with ubuntu :laughing:

**Comment by wangg12** [comment]
@starimpact It is easy to use cuda 8.0 on Ubuntu, but not on windows.

**Comment by antinucleon** [comment]
It is because prebuild Windows is not for CUDA 8.0. You can try to build Windows version manually with CUDA 8.0

**Comment by wangg12** [comment]
@albertyou2 I am able to build mxnet with cuda 8.0/cudnn v5 with gtx1060 on windows 10 64bit . Refer to [this](http://www.cnblogs.com/guwang/p/5738733.html)(But it is written in Chinese).

**Comment by albertyou2** [comment]
@wangg12 Thanks a lot! I will finally try build mxnet on windows 10!Thank you for your information!

**Comment by gauenk** [comment]
@thirdwing Would you mind sharing what lead to your successful installation of MXNET? I am having issues and I can't find solutions online... I am hoping you found some sort of help/guide to install it.
