### ISSUE TITLE
mxnet_0.7_tar.gz is absent in drat/src/contrib/

### ISSUE THREAD

**Issue by statist-bhfz** [dmlc/mxnet#2900]
Hi,
I have a trouble when installing mxnet R package on Ubuntu. It is absent in https://github.com/dmlc/drat/tree/gh-pages/src/contrib
Installation using `install.packages("nxnet")` also fails with error
`URL 'http://dmlc.ml/drat/src/contrib/mxnet_0.7.tar.gz': status was '404 Not Found'`

**Comment by thirdwing** [comment]
In the document,

> For Windows/Mac users, we provide pre-built binary package using CPU.

So there is no pre-built pkg for any Linux distribution. Please compile it by yourself.

**Comment by statist-bhfz** [comment]
Thanks, I have successfully built the package.

**Comment by thirdwing** [comment]
Compiling on Linux should be quite smooth.
