### ISSUE TITLE
a question about mx.symbol.Concat in 'composite_symbol.ipynb'

### ISSUE THREAD

**Issue by luoruisichuan** [dmlc/mxnet#2908]
in the script of 'composite_symbol.ipynb', there is 
'concat = mx.symbol.Concat(*[c1x1, c3x3, cd3x3, cproj], name='ch_concat_%s_chconcat' % name)'
but the archetecture of network is as this,
c1x1         64×28×28
c3x3         64×28×28
cd3x3       96×28×28
cproj        32×28×28
on other hand, for 'mx.symbol.Concat( )',  'dim (int, optional, default='1') – the dimension to be concated.'
if we represent the shape of two symbols(symbol1 and symbol2) to be concated as a×b×c and d×e×f,   
symbol1  a×b×c 
symbol2  d×e×f
and if  'concat = mx.symbol.Concat(*[symbol1, symbol2],  so 'a' must equal to 'd' and 'c' must equal to 'f', becacuse 'dim (int, optional, default='1') – the dimension to be concated.', but the above network archetecture doesnot  satisfy this requirement , what is wrong?
by the way, where can I find the source code of  'mx.symbol.Concat'?
thanks.
@wangg12

**Comment by wangg12** [comment]
@luoruisichuan  You can find the doc in ipython by `?mx.symbol.Concat`.

 The concat code is in c++, you can find it by searching the github(for example: [https://github.com/dmlc/mxnet/search?utf8=%E2%9C%93&q=Concat&type=Code](https://github.com/dmlc/mxnet/search?utf8=%E2%9C%93&q=Concat&type=Code)).

**Comment by luoruisichuan** [comment]
thanks. 
but for two symbols, just as cd3x3 and cproj ,
cd3x3    96×28×28
cproj      32×28×28
I think,  the two symbls can only be concated on the dim=0, i.e., 
concat=mx.symbol.Concat(*[cd3x3, cproj], dim=0),  and concat=mx.symbol.Concat(*[cd3x3, cproj], dim=1) is not correct,  is there any problem?
thanks.

**Comment by wangg12** [comment]
@luoruisichuan You can just verify it in several lines of code in ipython.
```
import numpy as np
import mxnet as mx
a= np.ones((96,28,28))
b=np.ones((32,28,28))
a1 = mx.nd.array(a)
b1 = mx.nd.array(b*2)
aV = mx.sym.Variable('a')
bV = mx.sym.Variable('b')
cat = mx.sym.Concat(aV, bV, dim=0)
cat1 = mx.sym.Concat(aV, bV, dim=1)
exe = cat.bind(ctx=mx.cpu(), args={'a':a1, 'b':b1})
exe.outputs[0].shape  # this is rught
exe1 = cat1.bind(ctx=mx.cpu(), args={'a':a1, 'b':b1}) # this would be wrong
```
So the answer of your question is correct.

**Comment by luoruisichuan** [comment]
thanks.
I get the reason.  batchsize dim is omited, and the actual symbol are 
cd3x3    batchsize×96×28×28
cproj     batchsize×32×28×28
so,   concat=mx.symbol.Concat([cd3x3, cproj], dim=1) is correct.
