### ISSUE TITLE
src/operator/./embedding-inl.h:116:26: error: ‘range’ was not declared in this scope

### ISSUE THREAD

**Issue by yourwanghao** [dmlc/mxnet#2914]
OS: Ubuntu 16.04
Compiler: g++ 4.9.3, nvcc V8.0.26
CUDA: 8.0
cuDNN: 5.0

Issue:
clone latest mxnet, and do build but failed. 

error report:
src/operator/./embedding-inl.h:116:26: error: ‘range’ was not declared in this scope

**Comment by Godricly** [comment]
try updating your shadow submodule

**Comment by yourwanghao** [comment]
Thank you, problem solved.
