### ISSUE TITLE
I try to import my data. but the error occurs "Input node is not complete"

### ISSUE THREAD

**Issue by szad670401** [dmlc/mxnet#2917]
> def test2():
    data_shape = [("data", (1, 3, 30, 120))]
    input_shapes = dict(data_shape)
    sym = getnet()
    executor = sym.simple_bind(ctx = mx.cpu(), **input_shapes)
if __name__ == '__main__':
    test2();

> Traceback (most recent call last):
  File "/Users/yujinke/learning cpp/untitled5/ete.py", line 76, in <module>
    test2();
  File "/Users/yujinke/learning cpp/untitled5/ete.py", line 72, in test2
    executor = sym.simple_bind(ctx = mx.cpu(), **input_shapes)
  File "/Library/Python/2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 675, in simple_bind
    raise ValueError("Input node is not complete")
ValueError: Input node is not complete

**Comment by piiswrong** [comment]
you need to specify shape of all inputs to sym.simple_bind

**Comment by szad670401** [comment]
I have specified the shape 

> data_shape = [("data", (1, 3, 30, 120))]
but it still does't work.

**Comment by ba9els** [comment]
does this issue have an answer??
