### ISSUE TITLE
How can I predict a image use lstm_ocr.py trained model

### ISSUE THREAD

**Issue by sinmaystar** [dmlc/mxnet#2920]
I have ran lstm_ocr.py and trained a model, but I have try some methods to predict an image, its all failed, who can help me to predict an image use trained lstm_ocr model?can anyone give me a step by step method to predict an image?
thanks very much

**Comment by zt706** [comment]
The writer does not write prediction in the example. see #2938 for more infomation and the issue is help for me.

**Comment by SDASDASA** [comment]
@zt706 
hi，i also can not predict the image by the lstm_ocr model，can you open your prediction code？ thanks a lot.

**Comment by SDASDASA** [comment]
@zt706
when i refer the rnn_model.py， i  counter the error:
ValueError: ValueErr...mplete'
__init__（）
-> self.executor = self.sym.simple_bind（ctx=[mx.context.gpu）]， **input_shapes）

the predict code  as follows:


        batch_size = 1
        num_hidden = 100
        num_lstm_layer = 2
        seq_len = 80
        sym = lstm_unroll（num_lstm_layer，seq_len，num_hidden，num_label ）

        init_c = [（'l%d_init_c'%l，（batch_size， num_hidden）） for l in range（num_lstm_layer）]
        init_h = [（'l%d_init_h'%l， （batch_size， num_hidden）） for l in range（num_lstm_layer）]
        init_states = init_c + init_h
        data_input = [（"data"， （batch_size，））] 
        input_shapes = dict（init_c + init_h + data_input）
        self.executor = self.sym.simple_bind（ctx=[mx.context.gpu（2）]， **input_shapes）


Do you have any idea about this error？ thanks very much.
