### ISSUE TITLE
Matching multiple labels to multiple outputs

### ISSUE THREAD

**Issue by novog** [dmlc/mxnet#2929]
Hi, just getting started with mxnet. Either I am missing something, or the multi-label feature of NDArrayIter isn't being leveraged properly in model.py. As referenced in #647, you can provide multiple inputs and/or labels to an NDArrayIter, associating each with a string key:

```
iter = mx.NDArrayIter({'data1': nd_data1, 'data2': nd_data2}, {'label1': nd_label1, 'label2': nd_label2})
```

The NDArrayIter has four members of interest:
- data - a list of input name/input matrix pairs
- provide_data - a list of input name/input matrix shape pairs
- label - a list of name/label matrix pairs
- provide_label - a list of label name/label matrix shape pairs

When you iterate over an NDArrayIter, you get a DataBatch. A DataBatch has two members of interest:
- data - a list of input matrices
- label - a list of label matrices

Note that when going from the NDArrayIter to the DataBatch, the name associations were lost. When training, the items in DataBatch.label are zipped with the predictions in Executor.outputs for comparison. The problem is that the predictions are ordered according to their position in the Group Symbol, whereas the labels come out in whatever order you happen to get by iterating over the hashed items in NDArrayIter, so the two sequences will not be properly aligned in most cases.

Here is some example code to demonstrate the issue:

```
data = {'data1':np.zeros(shape=(100,1)), 'data2':np.zeros(shape=(100,2)), 'data3':np.zeros(shape=(100,3))}
labels = {'label4':np.zeros(shape=(100,4)), 'label5':np.zeros(shape=(100,5)), 'label6':np.zeros(shape=(100,6)), 'label7':np.zeros(shape=(100,7)), 'label8':np.zeros(shape=(100,8))}
trainIt = mx.io.NDArrayIter(data, labels, 10)
testIt = mx.io.NDArrayIter(data, labels, 10)
data1 = mx.sym.Variable('data1')
data2 = mx.sym.Variable('data2')
data3 = mx.sym.Variable('data3')
net = mx.sym.Concat(data1, data2, data3)
net = mx.sym.FullyConnected(net, num_hidden=10)
output4 = mx.sym.LinearRegressionOutput(net, mx.sym.Variable('label4'), name='output4')
#output4 = mx.sym.LinearRegressionOutput(net, mx.sym.Variable('labl4'), name='output4')
output5 = mx.sym.LinearRegressionOutput(net, mx.sym.Variable('label5'), name='output5')
output6 = mx.sym.LinearRegressionOutput(net, mx.sym.Variable('label6'), name='output6')
fc7 = mx.sym.FullyConnected(net, num_hidden=7)
output7 = mx.sym.LogisticRegressionOutput(fc7, mx.sym.Variable('label7'), name='output7')
fc8 = mx.sym.FullyConnected(net, num_hidden=8)
output8 = mx.sym.LogisticRegressionOutput(fc8, mx.sym.Variable('label8'), name='output8')
net = mx.sym.Group([output4, output5, output6, output7, output8])
model = mx.model.FeedForward(net, num_epoch=1, epoch_size=10)
model.fit(trainIt, testIt)`
```

The names of the NDArrayIter's labels are clearly being checked against the names of the output Variables, as using the commented-out version of output4 results in a "Symbol.InferShapeKeyword argument name label4 not found" error. So, I would expect the labels to be matched to the appropriate outputs. However, for the reasons described above, the following error is produced in RMSE.update in metric.py:

> ValueError: operands could not be broadcast together with shapes (10,8) (10,4)

Is there any reason that the relevant code in _train_multi_device in model.py shouldn't be updated to pass along named labels in the correct order for evaluation? Thanks!

**Comment by happygds** [comment]
Did you find the solution ?

**Comment by novog** [comment]
At the time, I had ended up creating my own modified versions of _train_multi_device and FeedForward to support this functionality. However, I believe that the Model interface was more recently deprecated in favor of the new [Module](http://mxnet.io/api/python/module.html) interface. I am now using mx.mod.Module, and did not need to make any modifications to it in order to provide multiple inputs and outputs from an NDArrayIter.
