### ISSUE TITLE
./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed

### ISSUE THREAD

**Issue by NoListen** [dmlc/mxnet#2933]
I have trouble in executing the simple code using
`python demo.py`
 in Ubuntu 14.04.

demo.py
```
import mxnet as mx
a = mx.nd.ones((10,10), mx.gpu())
```

`[[12:54:07] /path/to/mxnet/dmlc-core/include/dmlc/logging.h:235: [12:54:07] /path/to/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
12:54:07] /path/to/mxnet/dmlc-core/include/dmlc/logging.h:235: [12:54:07] /path/to/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
terminate called after throwing an instance of 'dmlc::Error'
terminate called recursively
  what():  [12:54:07] /path/to/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
Aborted (core dumped)
`

However, it work using interactive processing, like
```
>>>import mxnet as mx
>>>a = mx.nd.ones((10,10), mx.gpu())
```

It also work when I use ipython notebook.

[https://github.com/dmlc/mxnet/issues/1137](https://github.com/dmlc/mxnet/issues/1137) doesn't work for me even though I set it to be 60 seconds.

I try on another machine with TITAN X and find the same problems.
There may be something wrong, but I can't figure it out.

**Comment by winstywang** [comment]
Please try it with normal use? such test is meaningless

**Comment by NoListen** [comment]
@winstywang I'm sorry. I just follow the neural art in the examples and there is one step of initializing the parameters to 0. Even the white noise image as a container is initialized as `mx.nd.zeros(content_np.shape, ctx=dev)`

I initialize the image and find the error. However, I can run the neural-art program with no error just now.  I think you are right. Thank you, I will close it.
