### ISSUE TITLE
Does mxnet share memory in forward and backward phase?

### ISSUE THREAD

**Issue by magic282** [dmlc/mxnet#2934]
Hi,

Just a simple question.
I am curious about if mxnet could share memory for forward and backward phase. According to [this](https://github.com/dmlc/mxnet/blob/f786095665790ba3b877e8e3f7916361e6e2e3b1/docs/zh/note_memory.md), mxnet is using different graphs during forward and backward. But if they could use the same graph, some of the forward and gradient nodes can share the same memory right? Does this method save more memory?

Thanks.

**Comment by Godricly** [comment]
It depends on the behalf of your operators. [memonger](https://github.com/dmlc/mxnet-memonger) is an extension of MxNet with some extra time cost if you can tolerate.

**Comment by magic282** [comment]
@Godricly I tried the script. The output is:
```
Search threshold=0 MB, cost=6051 MB
Search threshold=0 MB, cost=6051 MB
Search threshold=0 MB, cost=6051 MB
Find best plan with threshold=0, cost=6051 MB
Old feature map cost=7632 MB
New feature map cost=6051 MB
```
I am using python 3.
The model is s2s with attention.
```
Encoder: bidirectional LSTM
Decoder: LSTM
source_vocab_size = 100000
target_vocab_size = 50000
source_unroll_length: 350
target_unroll_length: 30
batch_size = 64
```

In the above setting, I will get a OOM error on GPU. The key problem here is the unroll length, which is much longer than others.
Any idea to reduce the memory cost?
Thanks.

**Comment by piiswrong** [comment]
Try reduce batchsize

**Comment by tqchen** [comment]
To answer the question, mxnet indeed share memory between forward and backward pass
