### ISSUE TITLE
build a multi-input net

### ISSUE THREAD

**Issue by R1ncy** [dmlc/mxnet#2935]
hi, I have read http://mxnet.readthedocs.io/en/latest/packages/python/symbol_in_pictures.html#example-of-multi-input-net
and wanted to build a similar net.

here is the code I used in Rstudio:
src = mx.symbol.Variable("src_input")
tar = mx.symbol.Variable("tar_input")
h11 = mx.symbol.FullyConnected(src, num_hidden = 512)
h21 = mx.symbol.FullyConnected(tar, num_hidden = 512)
eg=h11+h21
graph.viz(eg$as.json())
![Img One](http://chuantu.biz/t5/25/1470385365x3738746601.png)

tar is missing in the graph
but tar is connected with h21 before "eg".
graph.viz(h21$as.json())
![Img Two](http://chuantu.biz/t5/25/1470385514x3738746559.png)
what should i do if i want to build such multi-input net?
thanks for your attention.

**Comment by kxf8608** [comment]
You can use simple_bind() and some manual code to initialize the weights and fill in your input variables. Read this tutorial https://github.com/dmlc/mxnet/blob/5ff545f2345f9b607b81546a168665bd63d02d9f/example/notebooks/simple_bind.ipynb
particularly the "in [5]" line and use some code like this to input your multiple inputs:

executor = eg.simple_bind(ctx=ctx, data = data_shape, grad_req = 'write')
arg_arrays = executor.arg_arrays
grad_arrays = executor.grad_arrays
aux_arrays = executor.aux_arrays
args = dict(zip(eg.list_arguments(),arg_arrays))
grads = dict(zip(eg.list_arguments(),grad_arrays))
aux_states = dict(zip(eg.list_auxiliary_states(),aux_arrays))

input1 = mx.nd.ones(data_shape)   # or read something from your data
input2 = mx.nd.ones(data_shape) 
args["src_input"][:] = input1
args["tar_input"][:] = input2

**Comment by R1ncy** [comment]
thanks for your reply, @kxf8608 
i use this code in R and meet new trouble.

my dataset is a matrix. each row is a sample and each column is a feature.
so I think the "data_shape" is the dim of the dataset. (for example, c(500, 6000))

> data_shape = c(500,6000)
> executor = mx.simple.bind(eg, data = data_shape,grad_req = "write")
**Error: not compatible with requested type**
> executor = mx.simple.bind(eg, data = data_shape,grad_req = "null")
**Error: not compatible with requested type**

I know very little about python. Is there any difference between the param grad_req's value of R and python?

**Comment by kxf8608** [comment]
data_shape should be the batch data's dimension. For example, (64,3,256,128) means a batch of 64 3-channel images (RGB) with spatial dimension of 256 height and 128 width. For fully connected layer, it only accepts (batch, length) data.

grad_req should be 'write' most of the time. If you set it as NULL the model will not learn.

About your question, sorry about my previous reply and I did not find the actual solution. I suggest 1) use single input and then a mxnet.symbol.SliceChannel layer to cut it into two pieces. Alternatively, 2) use bind() rather than simple_bind(). See http://mxnet.readthedocs.io/en/latest/packages/python/symbol_in_pictures.html#bind-and-execute-symbol

**Comment by R1ncy** [comment]
thank you @kxf8608 , I use the code the same with http://mxnet.readthedocs.io/en/latest/packages/python/symbol_in_pictures.html#example-of-multi-input-net

in1 = mx.symbol.Variable('data')
fc1 = mx.symbol.FullyConnected(data = in1,num_hidden=128,name='fc1')
in2 = mx.symbol.Variable('data2')
fc2 = mx.symbol.FullyConnected(data=in2,num_hidden=128,name='fc2')
combined = fc1+fc2
graph.viz(combined$as.json())

I think "graph.viz(combined$as.json())" should return me a graph with similar structure:
![graph one](http://chuantu.biz/t5/25/1470623568x1948221155.png)
but it actually returns:
![graph two](http://chuantu.biz/t5/25/1470624143x1948221110.png)
**in2 is not in it.**
what's wrong with it?

**Comment by kxf8608** [comment]
Perhaps the visualizer does not support multiple input. It only recognized your "data" as the only input. Never mind about the visualizer.

**Comment by R1ncy** [comment]
so the in2 really exists in the net structural, but the visualizer doesn't draw it.

**Comment by kxf8608** [comment]
yes, it is there. Just not shown in the graph
