### ISSUE TITLE
How to speicify the path of CUDNN? 

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#2936]
I can't find how to set the path of CUDNN in the Installation.
I only knows  that I have to set USE_CUDNN_PATH . But I don't know which path should I put in this VAR.
I first extract cudnn5 into this path: /home/sojoyoo/cuda

Then I modified this line to ' USE_CUDNN_PATH= /home/sojoyoo/cuda' .
But I got a fatal error : 

/home/sojoyoo/mxnet/mshadow/mshadow/./base.h:152:21: fatal error: cudnn.h: 没有那个文件或目录
compilation terminated.
Makefile:151: recipe for target 'build/src/resource.o' failed
make: *** [build/src/resource.o] Error 1
make: *** 正在等待未完成的任务....
In file included from /home/sojoyoo/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/io.h:15,
                 from src/io/io.cc:3:
/home/sojoyoo/mxnet/mshadow/mshadow/./base.h:152:21: fatal error: cudnn.h: 没有那个文件或目录
compilation terminated.
Makefile:151: recipe for target 'build/src/io/io.o' failed
make: *** [build/src/io/io.o] Error 1
In file included from /home/sojoyoo/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:13,
                 from src/io/image_aug_default.cc:6:
/home/sojoyoo/mxnet/mshadow/mshadow/./base.h:152:21: fatal error: cudnn.h: 没有那个文件或目录
compilation terminated.
In file included from /home/sojoyoo/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/io.h:15,
                 from src/io/iter_csv.cc:6:
/home/sojoyoo/mxnet/mshadow/mshadow/./base.h:152:21: fatal error: cudnn.h: 没有那个文件或目录
compilation terminated.
Makefile:151: recipe for target 'build/src/io/iter_csv.o' failed
make: *** [build/src/io/iter_csv.o] Error 1
Makefile:151: recipe for target 'build/src/io/image_aug_default.o' failed
make: *** [build/src/io/image_aug_default.o] Error 1

Does some know how to handle this ?

**Comment by Godricly** [comment]
U can copy cudnn.h and its lib into corresponding cuda path, i.e. cuda/include, cuda/lib64.
check make/config.mk

**Comment by albertyou2** [comment]
@Godricly  Thank you ! I sovled this issue just now 

step1 : 
(download cudnn first,then extract)

cd cuda  (the extract cudnn path,not the cuda path )

sudo cp lib64/* /usr/local/cuda/lib64/
sudo cp include/cudnn.h /usr/local/cuda/include/

step 2: 
just set USE_CUDNN=1 in  config.mk file .

step 3:
make

It is no need to set USE_CUDNN_PATH right now .
I think this should be helpful for someone else.

**Comment by ysh329** [comment]
same problem
