### ISSUE TITLE
mxnet make faild on  last step 'make im2rec.cc'  

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#2937]
ubuntu 16.04 gcc/g++ 4.9, cuda 8.0,cudnn5 for cuda 8.0.

opencv 2.4.9.1(I installed opencv follow the mxnet official install instructions )

mxnet is cloned just few hours ago.
I first downgrade gcc/g++ from 5.4.0 to 4.9.3
I got this error when making : 
/tmp/cc8g0vH0.o：在函数‘main’中：
im2rec.cc:(.text.startup+0x28e8)：对‘cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:205: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

‘cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)’未定义的引用

**Comment by piiswrong** [comment]
try make clean and make again

**Comment by albertyou2** [comment]
@piiswrong I  tried 'make clean' and 'make ' again but has no effect.

**Comment by austingg** [comment]
@albertyou2  you'd better check your opencv dependency whether there is the 'libopencv_imgcodecs' .
maybe you can use **pkg-config --libs opencv ** to verify

**Comment by thirdwing** [comment]
This is a little tricky. I also met this once.

The problem is you are using gcc4.9 with cuda, but your opencv is built using gcc5. You can't link at the last step.

You can try to set gcc5 in `config.mk` and `make`

**Comment by albertyou2** [comment]
@austingg  I have followed the instructions which is similar to yours,but it does't work.Thank you for reply!

@thirdwing  thank you for reply! You mean that  I should re-install gcc/g++ 5.0 and re-build mxnet again?

**Comment by thirdwing** [comment]
I am not sure if you remove GCC5 or not.

You can set `CC` and `CXX` in https://github.com/dmlc/mxnet/blob/master/make/config.mk#L23 , then `make`.

Don't `make clean` .

**Comment by albertyou2** [comment]
when i download the up-to-date code and rebuild it again, the issue is gone!

**Comment by khalida** [comment]
I have run into this issue installing mxnet on Ubuntu whilst trying to follow the instructions [here](http://mxnet.io/get_started/ubuntu_setup.html#quick-installation).

As far as I can tell (and I'm far from an expert) this is to do with an incorrect installation of openCV. To get it working again I needed to:

1. Install openCV following the instructions [here](http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html)
2. Update my dynamic library configuration by running `sudo ldconfig`

Thought I would write this down here in case it's of help to someone else, or me in the future.
