### ISSUE TITLE
Warp CTC predict produces errors:"Input node is not complete "

### ISSUE THREAD

**Issue by zt706** [dmlc/mxnet#2938]
I run the example in example/warpctc, and train/load the model, then I try to call the predict method, which gives me "Input node is not complete" error. I have readed  #1576 and debuged the code, but I have no idea what to do.
```python
    # my code to load the model
    num_hidden = 100
    num_lstm_layer = 2
    num_epoch = 1
    num_label = 4
    def sym_gen(seq_len):
        return lstm_unroll(num_lstm_layer, seq_len,
                           num_hidden=num_hidden,
                           num_label = num_label)
    net = sym_gen(80)
    print net.list_arguments()
    model = net.simple_bind(\
            mx.gpu(3), \
            grad_req='null', \
            **dict([('data', (1, 2400)), ('label', (1, 4))]))
            #**dict([('data', (1, 2400))]))
 ```

when I debug the code, I found the ./src/symbol/static_graph.cc:76 return a false due to the error info. The node name is "t0_l0_h2h" and the nid is 8 when the code return false early. 
The C++ code: 
```c++
// mxnet/src/symbol/static_graph.cc
bool StaticGraph::InferNodeShapes(const std::vector<uint32_t> &topo_order,
                                  std::vector<std::vector<TShape> > *node_out_shapes,
                                  std::vector<std::vector<TShape> > *node_aux_shapes,
                                  bool partial_infer) const {
  for (uint32_t nid : topo_order) {
    const Node& node = nodes[nid];
    if (node.is_forward()) {
      std::vector<TShape> in_shape;
      for (const DataEntry& e : node.inputs) {
        in_shape.push_back((*node_out_shapes)[e.source_id][e.index]);
      }
      try {
        if (!node.op->InferShape(&in_shape,
                                 &(*node_out_shapes)[nid],
                                 &(*node_aux_shapes)[nid])) {
          if (partial_infer)
            continue;
          return false;  // here return early
        }
      } catch (const op::InferShapeError &err) { }

```
but I print the node name when train/predict in the lstm.py:70, I can not find the node which named "t0_l0_h2h"
```python
    # example/warpctc/lstm.py
    # embeding layer
    data = mx.sym.Variable('data')
    label = mx.sym.Variable('label')
    wordvec = mx.sym.SliceChannel(data=data, num_outputs=seq_len, squeeze_axis=1)

    hidden_all = []
    for seqidx in range(seq_len):
        hidden = wordvec[seqidx]
        for i in range(num_lstm_layer):
            next_state = lstm(num_hidden, indata=hidden,
                              prev_state=last_states[i],
                              param=param_cells[i],
                              seqidx=seqidx, layeridx=i)
            hidden = next_state.h
            last_states[i] = next_state
            # print node name
            print i, last_states[i].c.list_arguments(), last_states[i].h.list_arguments() 
        hidden_all.append(hidden)

    hidden_concat = mx.sym.Concat(*hidden_all, dim=0)
    pred = mx.sym.FullyConnected(data=hidden_concat, num_hidden=11)
```
If you have any idea about this, please point it out. Thanks~

**Comment by anxingle** [comment]
This may be helpful. [CTC input node is not complete](https://github.com/dmlc/mxnet/issues/2217) @xlvector       I met the same problem.

**Comment by xlvector** [comment]
I does not write prediction in the example.

Do you write it by yourselves?

You can refer to rnn/rnn_mode.py and rnn/char-rnn.ipynb

**Comment by zt706** [comment]
The refer is helpful and I write the prediction, thank you very much. -_-!!

**Comment by melody-rain** [comment]
@zt706
Hi could you pls open-source your prediction code? I followed  rnn/rnn_mode.py to write lstm_inference_symbol(), but I do not know how to add WarpCTC to it. Below is the code I am trying to write:
`def lstm_inference_symbol(num_lstm_layer, seq_len, num_hidden, num_label):
    seqidx = 0
    param_cells = []
    last_states = []
    for i in range(num_lstm_layer):
        param_cells.append(LSTMParam(i2h_weight=mx.sym.Variable("l%d_i2h_weight" % i),
                                     i2h_bias=mx.sym.Variable("l%d_i2h_bias" % i),
                                     h2h_weight=mx.sym.Variable("l%d_h2h_weight" % i),
                                     h2h_bias=mx.sym.Variable("l%d_h2h_bias" % i)))
        state = LSTMState(c=mx.sym.Variable("l%d_init_c" % i),
                          h=mx.sym.Variable("l%d_init_h" % i))
        last_states.append(state)
    assert (len(last_states) == num_lstm_layer)

    data = mx.sym.Variable('data')

    for i in range(num_lstm_layer):
        next_state = lstm(num_hidden, indata=hidden,
                          prev_state=last_states[i],
                          param=param_cells[i],
                          seqidx=seqidx, layeridx=i)
        hidden = next_state.h
        last_states[i] = next_state

    fc = mx.sym.FullyConnected(data=hidden, num_hidden=11)
    sm = mx.sym.SoftmaxOutput(data=fc, name='softmax')

    # label = mx.sym.Reshape(data=label, shape=(-1,))
    # label = mx.sym.Cast(data=label, dtype='int32')
    # sm = mx.sym.WarpCTC(data=pred, label=label, label_length=num_label, input_length=seq_len)
    return sm`

**Comment by SDASDASA** [comment]
@zt706 
hi，i also can not predict the image by the  lstm_ocr model，can you open your prediction code？ thanks a lot.

**Comment by SDASDASA** [comment]
@zt706
when i refer the rnn_model.py， i  counter the error:
ValueError: ValueErr...mplete'
__init__（）
-> self.executor = self.sym.simple_bind（ctx=[mx.context.gpu）]， **input_shapes）

the predict code is as:
        batch_size = 1
        num_hidden = 100
        num_lstm_layer = 2
        seq_len = 80
        sym = lstm_unroll（num_lstm_layer，seq_len，num_hidden，num_label ）

        init_c = [（'l%d_init_c'%l，（batch_size， num_hidden）） for l in range（num_lstm_layer）]
        init_h = [（'l%d_init_h'%l， （batch_size， num_hidden）） for l in range（num_lstm_layer）]
        init_states = init_c + init_h
        data_input = [（"data"， （batch_size，））] 
        input_shapes = dict（init_c + init_h + data_input）
        self.executor = self.sym.simple_bind（ctx=[mx.context.gpu（2）]， **input_shapes）

**Comment by SDASDASA** [comment]
@melody-rain 
hi，have you solved the problem？i counter the same problem.

**Comment by melody-rain** [comment]
@SDASDASA 
pls refer to https://github.com/melody-rain/mxnet/commit/bda09ec358212f8e02a8fb04c0326072ab272689

**Comment by SDASDASA** [comment]
@melody-rain 
thx a lot，i predict the image success. thank you very much.

**Comment by sinmaystar** [comment]
@SDASDASA can u open source your predict code ? I have met some problem, I can't predict image, thanks a lot

**Comment by melody-rain** [comment]
@sinmaystar 
check this:
https://github.com/melody-rain/mxnet/tree/infer_lstm

**Comment by sinmaystar** [comment]
I'm sorry to reply u too late, thanks for your help, I have predict successfully
            On 10/11/2016 18:37, Jin Ma wrote:@sinmaystar 
check this:
https://github.com/melody-rain/mxnet/tree/infer_lstm

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dmlc/mxnet","title":"dmlc/mxnet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dmlc/mxnet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@melody-rain in #2938: @sinmaystar \r\ncheck this:\r\nhttps://github.com/melody-rain/mxnet/tree/infer_lstm"}],"action":{"name":"View Issue","url":"https://github.com/dmlc/mxnet/issues/2938#issuecomment-252875341"}}}
