### ISSUE TITLE
Is Reshape a InPlace OP?

### ISSUE THREAD

**Issue by magic282** [dmlc/mxnet#2939]
Hi,

I found that doing reshape in a for loop and outsides will result in huge memory cost difference.

If I do reshape inside the attention, the feature map will cost 7632 MB. If outside the attention, the memory cost will be 5094 MB.

Thanks.

related: https://github.com/dmlc/mxnet/issues/2934

**Comment by tqchen** [comment]
Yes, but inplace will only be done if its source has not been used by another operator
