### ISSUE TITLE
do multiple "batch_dot" in loop can cause the layer unable to be linked with Convolution layer

### ISSUE THREAD

**Issue by kxf8608** [dmlc/mxnet#2945]
Hi, I created a Custom Layer which involves batch_dot( ) in for loops. When I link this layer  with another convolution layer and forward, the computation will be "stuck". However, if I link the layer with other types of layers such as softmax or directly set it as output, the result is correct. This suspicious bug appears when the batch_dot executes more than 3 times.

Here is the code 
[mxnet_issue_multiple_batch_dot.txt](https://github.com/dmlc/mxnet/files/405017/mxnet_issue_multiple_batch_dot.txt)
that can reproduce the error. Thanks.

**Comment by piiswrong** [comment]
add 
```
import os
os.environ["MXNET_EXEC_PREFER_BULK_EXEC"] = "0"
```
to the beginning of your code and it works.
There are some compatibility issues with customop

**Comment by kxf8608** [comment]
@piiswrong I am afraid the error is still there even I added the command to disable the bulk execution. May you check again please?

**Comment by kxf8608** [comment]
I think it is not about the custom layer. I opt to the old mx.operator.NDArrayOp instead but it still goes stuck. Here is the code
[mxnet_issue_batch_dot_convolution.txt](https://github.com/dmlc/mxnet/files/405332/mxnet_issue_batch_dot_convolution.txt)

**Comment by piiswrong** [comment]
I figured it out. It's a very complicated bug. Not sure how to fix it yet.
As a temporary fix, add MXNET_ENGINE_TYPE=NaiveEngine to your environment variables.
But you need to be very careful not to do any synchronization in CustomOp. i.e. don't use asnumpy() in custom op.

**Comment by kxf8608** [comment]
Thanks for your help! @piiswrong 
Wish you the best fixing the bug. Good luck!

**Comment by kxf8608** [comment]
Thanks for your help! @piiswrong 
Wish you the best fixing the bug. Good luck!

**Comment by ajtulloch** [comment]
@piiswrong what was the bug?

**Comment by antinucleon** [comment]
@ajtulloch  cyclic dependency, see https://github.com/dmlc/mxnet/issues/2944

**Comment by sxjscience** [comment]
@antinucleon @piiswrong Still not so clear about the bug... Could you explain more about it?
