### ISSUE TITLE
resnet 224*224 cost 31G memory 

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#2948]
@
The number of images is 370000,batch_size = 32,data shape = (3,224,224),network = resnet
And I put all the images into 1 record file which size is 4G.

When I trained them with my GTX 1070 which has 8G memory I got allocate memory error(out of memory)
Then I trained them with cpu .I saw mxnet use about 31G  memory.
1 . Is there any method or settings could help me to use resnet?

2.@tqchen 
I saw you have committed your code which was resoled the CUDA memory issue one day ago.
How to use this code ? Should I checkout the mxnet master now or clone your repo and checkout the latest commit? !Thank you

**Comment by piiswrong** [comment]
CPU memory contains things other than the network. Try reduce batch_size until it fits. I guess 8 should work

**Comment by albertyou2** [comment]
@piiswrong OK!
I 'll try batch_size = 8 first . I 'll give the result here after I do that .

you mentioned that : ' Also, you can turn on MIRROR ' . Unfortunately I don't know how to do this .  Could you please give a short instruction to do that? 
Thank you very much !!!

**Comment by winstywang** [comment]
Please refer to this issue: https://github.com/dmlc/mxnet/issues/3055
