### ISSUE TITLE
Bug in NDArrayIter when last_batch_handle="discard"

### ISSUE THREAD

**Issue by ArtanisCV** [dmlc/mxnet#2951]
The NDArrayIter defined in [`io.py`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py) has the following codes (Lines 359-369):

    if last_batch_handle == 'discard':
        new_n = self.data_list[0].shape[0] - self.data_list[0].shape[0] % batch_size
        data_dict = OrderedDict(self.data)
        label_dict = OrderedDict(self.label)
        for k, _ in self.data:
            data_dict[k] = data_dict[k][:new_n]
        for k, _ in self.label:
            label_dict[k] = label_dict[k][:new_n]
        self.data = data_dict.items()
        self.label = label_dict.items()
    self.num_data = self.data_list[0].shape[0]

It seems that `self.num_data` is not updated to the correct shape (which should be `self.data[0][1].shape[0]`). As a result, a dimension-mismatch error may occur at runtime.

**Comment by piiswrong** [comment]
Thanks for reporting. Would you like to propose a PR?
