### ISSUE TITLE
multi-nodes training with dmlc-core

### ISSUE THREAD

**Issue by feiyulv** [dmlc/mxnet#2954]
It will be ok if I submit  a multi-nodes job using launcher.py under  ps-lite dir.  However, when I use the dmlc-submit provided by dmlc-core, the program will exit.
script with ps-lite:
 `python launcher.py -n 2 --launcher ssh -H hosts python test.py --kv-store dist_sync`
script  with dmlc-core
`python dmlc-submit  --cluster ssh --num-wokers 2 --host-files hosts  python test.py --kv-store dist_sync`

If I remove the argument `kv-store dist_sync`, the dmlc-core will work.
Log info as follows:
![image](https://cloud.githubusercontent.com/assets/18651286/17468454/c591b4cc-5d5a-11e6-936f-ef1486a2137b.png)

**Comment by mli** [comment]
can you give more detailed logs?

**Comment by feiyulv** [comment]
I forget to specify the num-servers when using dmlc-submit. This will be ok
`python dmlc-submit --cluster ssh --num-wokers 2 --num-servers=2 --host-files hosts python test.py --kv-store dist_sync`
By the way, the multi-node program still can't be canncelled with new dmlc-submit. Is there any way to avoid it ? @mli

**Comment by feiyulv** [comment]
My mistake, the program can be terminated
