### ISSUE TITLE
How to multiply symbol with a scalar?

### ISSUE THREAD

**Issue by JohanCao** [dmlc/mxnet#2956]
Hi all,

I am trying to multiply the output of a convolution layer with a scalar and update the scalar during backpropagation.  However the "arg_shapes" indicates that the shape of this scalar is equal to the shape of convolutional feature map it multiplies, so as the shape of the gradient of this scalar. I used the arithematic multiplication between the symbols (which is elementwise multiplication). Is there anyone knows how to multiply a symbol with a scalar? Many thanks!

Best,
Johan

**Comment by Godricly** [comment]
How about conv it with a 1x1x1 conv kernel? It could be a bypass.

**Comment by piiswrong** [comment]
Create a variable and set its shape to (1,1,1,1)

**Comment by JohanCao** [comment]
@Godricly 
I get a shape inconsistent error, because the dimension of the conv feature map is not 1.

**Comment by JohanCao** [comment]
@piiswrong 
Still not working, here is the code I tried:
In [44]: input=mx.symbol.Variable("input")
In [45]: a = mx.symbol.Variable("a")
In [46]: out = mx.symbol.SoftmaxOutput(data=a*input,multi_output=True,name="softmax")
In [47]: out.list_arguments()
Out[47]: ['a', 'input', 'softmax_label']
In [48]: out.infer_shape(input=(1,3,5,5))
Out[48]: ([(1L, 3L, 5L, 5L), (1L, 3L, 5L, 5L), (1L, 25L)], [(1L, 3L, 5L, 5L)], [])
In [49]: out.infer_shape(input=(1,3,5,5),a=(1,1,1,1))
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-49-d01828eafd9f> in <module>()
----> 1 out.infer_shape(input=(1,3,5,5),a=(1,1,1,1))

/home/johancao/tools/mxnet/python/mxnet/symbol.pyc in infer_shape(self, *args, **kwargs)
    451             The order is in the same order as list_auxiliary()
    452         """
--> 453         return self._infer_shape_impl(False, *args, **kwargs)
    454 
    455     def infer_shape_partial(self, *args, **kwargs):

/home/johancao/tools/mxnet/python/mxnet/symbol.pyc in _infer_shape_impl(self, partial, *args, **kwargs)
    511             ctypes.byref(aux_shape_ndim),
    512             ctypes.byref(aux_shape_data),
--> 513             ctypes.byref(complete)))
    514         if complete.value != 0:
    515             arg_shapes = [

/home/johancao/tools/mxnet/python/mxnet/base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 def c_str(string):

MXNetError: InferShape Error in _mul3's rhs argument
Corresponding keyword of symbol: input
Shape inconsistent, Provided =(1,3,5,5), inferred shape=(1,1,1,1)

**Comment by piiswrong** [comment]
try broadcast_mul instead of *

**Comment by JohanCao** [comment]
@piiswrong   broadcast_mul solved this problem, thank you!
