### ISSUE TITLE
The new operator CaffeOp doesn't support layers with multiple outputs?

### ISSUE THREAD

**Issue by NoListen** [dmlc/mxnet#2958]
It seems like that the [Caffe API ](http://dmlc.ml/mxnet/2016/07/29/use-caffe-operator-in-mxnet.html)dosen't support layer with multiple outputs.

I have my original work with a new layer implemented in caffe. It seems the multiple outputs cause the program to interrupt.

**Comment by piiswrong** [comment]
@HrWangChengdu Looks like you didn't implement NumOutput and ListOutput in CaffeOpProp. Could you fix it?

**Comment by HrWangChengdu** [comment]
@piiswrong Sorry for this. Already fixed in pr, please check.

**Comment by HrWangChengdu** [comment]
@NoListen Please let me know if your caffe-op still interrupts after master has merged that PR.

**Comment by HrWangChengdu** [comment]
@NoListen It's merged now. Please have a try.

**Comment by NoListen** [comment]
@HrWangChengdu Thank you very much and it doesn't interrupt again. Moreover, I think that it's necessary to add `num_weight num_out` arguments when there is many weights and many outputs. Very nice work! I was lucky to use the `CaffeOp` as soon as it was delivered.
