### ISSUE TITLE
单机多GPU的neural-style如何工作

### ISSUE THREAD

**Issue by Aspirinkb** [dmlc/mxnet#2961]
clone了mxnet到本地，试着运行了neural-style的例子，可是只能指定单个GPU（k40），能正常工作，但是训练时间大概需要45秒/100次，比torch+lua的22秒要慢一倍？？？怎么会这么慢？之前看的对比结果是mxnet版本的要比torch版本的快啊。。。求解答。另外如何设置同时使用4个GPU训练呢？

**Comment by antinucleon** [comment]
First please check whether you compile with CuDNN. Another issue is check default size of image. To use multi-GPU, you probably need to change gram symbol by using batch-dot.

**Comment by Aspirinkb** [comment]
谢谢你的回答，但是"change gram symbol by using batch-dot"指什么？可以具体讲一下吗？或者具体如何实施？

**Comment by Aspirinkb** [comment]
@antinucleon 谢谢你的回答，但是"change gram symbol by using batch-dot"指什么？可以具体讲一下吗？或者具体如何实施？
