### ISSUE TITLE
what scenario will be happened in tracker.py

### ISSUE THREAD

**Issue by liumilan** [dmlc/mxnet#2965]
In traker.py code
  def accept_slaves(self, nslave):
        # set of nodes that finishs the job
        shutdown = {}
        # set of nodes that is waiting for connections
        wait_conn = {}
        # maps job id to rank
        job_map = {}
        # list of workers that is pending to be assigned rank
        pending = []
        # lazy initialize tree_map
        tree_map = None

        while len(shutdown) != nslave:
           logging.info("do while")
            fd, s_addr = self.sock.accept()
             logging.info("do while_accept")
            s = SlaveEntry(fd, s_addr)
           
when launch multiple-machines,it can't print do do while_accept. What scenario will be printed?What is used for accept_slaves function?

**Comment by mli** [comment]
it's used by the dmlc/rabbit project

**Comment by liumilan** [comment]
got it now,thanks.
