### ISSUE TITLE
How can I construct the params for ImageRecordioIter in cpp?

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#297]
Hi, I want to develop some tools to manage my dataset(split,merge,append,global shuffle or something), and I found the interface to init the Iter: Init(vector< pair<string, string>>& args), How to construct this params, some param is complex just like TShape，
BTW, the api ImagerRecordIter in python is prefectcher in cpp , and ImageRecoredIoIter in cpp is another class...It is so easy to mix

**Comment by tqchen** [comment]
All the parameters are in string format. We have some easy util to help you convert the strings to the target shape, and give you the desired parameters and do type checking.

Checkout https://github.com/dmlc/dmlc-core/blob/master/test/parameter_test.cc for example.
