### ISSUE TITLE
I'm confused When I read the examples in image-classifications

### ISSUE THREAD

**Issue by liuzhi136** [dmlc/mxnet#2971]
As we all know, the kernel should have 3 dimensions. The kernel's depth should equal to its input's depth. But I saw the kernel's dimension is 2 when I watch the example in image-calssification. Even when training the cifar10 dataset whose image is a color image, the kernel's dimension is still 2. I'm so confused about that. Does any one could help me? Could any one tell me why the code be written in this way? Any explanation will be grateful!
@pluskid @tqchen

**Comment by liuzhi136** [comment]
Could any one can explain this for me? I read the convolution-inl.h in folder src/operator and found a sentence:
if (param_.kernel.ndim() > 2) {
      LOG(FATAL) << "Volume convolution is not implmented in mshadow";
 }
That's why all the kernel only has 2 dimensions, am I right?
If it's true, how mxnet assume each feature map computed correctly. 
@tqchen

**Comment by winstywang** [comment]
For spatial conv kernel dim is of course 2, just like you set in the symbol, kernel = (7, 7) etc. I don't see anything wrong here

**Comment by feiyulv** [comment]
For a convolution layer with `f ` feature maps out  and `c`  feature maps in, the total kernel shape is (f, c, k, k). Kernel size is (k, k). You may mistake that (c, k, k) is a kernel.

**Comment by liuzhi136** [comment]
May be I didn't say it clearly. I know what you say.  Let me say the input image is a 32x32x3, so the depth is 3. For the first conv layer, each kernel's spatial 3x3 and the depth is equal to the layer in front of these kernels, so the kernel's depth is also 3. For a general case: the input is WxHxD, if the kernel's spital size is 3x3, then the shape of these kernels in current conv layer is 3x3xD. The more detialed explanation in https://cs231n.github.io/convolutional-networks/ @winstywang @feiyulv

**Comment by tornadomeet** [comment]
@liuzhi136  ```D``` is determined by the input channel number, so the kernel need not set it explicitly.

**Comment by liuzhi136** [comment]
@tornadomeet Thank you. Do you know where is the code that automatically set the D parameter? I want to see how does it work. Thank your for your reply.

**Comment by tornadomeet** [comment]
@liuzhi136 https://github.com/dmlc/mxnet/blob/master/src/operator/convolution-inl.h#L98 wmat_shape is the kernel shape, just consider num_group=1 for better understanding.

**Comment by liuzhi136** [comment]
@tornadomeet Thank you. I have read it. It make sense if the data.shape_[1] is the depth of the input. One more question, how many dimensions the data have? Is it 2? the first dimension is W * H and second one is D? Is that right?

**Comment by tornadomeet** [comment]
strictly speaking, the weight shape is (c_out, c_in, k_h, k_w), but it's only the  continuous address in the memory, so don't need too care about these, you can reshape it to any shape size.

**Comment by liuzhi136** [comment]
@tornadomeet c_in is the number of channel of input and c_out is the number of channel of output in current conv layer?

**Comment by tornadomeet** [comment]
yes

**Comment by liuzhi136** [comment]
@tornadomeet  I appreciate your explanation. Thank you so much.
