### ISSUE TITLE
Is there any DataIter example for distributed training ?

### ISSUE THREAD

**Issue by CNevd** [dmlc/mxnet#2973]
my data is libsvm format or can be converted to csv,  so how to write  a dataiter for distributed training?

**Comment by piiswrong** [comment]
mx.io.CSVIter

**Comment by CNevd** [comment]
@piiswrong Thanks for your reply!
does mx.io.CSVIter distributed reading? I fund mxnet.io.ImageRecordIter has parameters： ```num_parts  part_index```  and mx.io.CSVIter has no such parameters

**Comment by piiswrong** [comment]
You need to shard your data across machines and use different input file for each machine

**Comment by CNevd** [comment]
thanks

**Comment by niuchenglei** [comment]
I get the same problem, i have only libsvm formatted train data cause it is sparse, and there are no LIBSVMIter to load data, and i'm confuse how to load hdfs data with part of it.

**Comment by formath** [comment]
@piiswrong @CNevd I met the same problem. My data is on hdfs and can not be distributed to each machine because worker nodes can not hold such a big data. Could CSVIter directly read data from hdfs on minbatch-wise? Any solutions welcomed.
