### ISSUE TITLE
a question about rcnn exmaple, why set aux to zero when testing?

### ISSUE THREAD

**Issue by neodooth** [dmlc/mxnet#2975]
https://github.com/dmlc/mxnet/blob/master/example/rcnn/rcnn/rpn/generate.py#L30

For BN layers, this will erase the moving_mean and moving_var in aux, which will lead to wrong results; I don't know if there are any special reasons to do this? @precedenceguo

**Comment by precedenceguo** [comment]
There is not. Please ignore this line and supply aux_params as saved in training.
