### ISSUE TITLE
Training / Testing / Live usage of Network on my own data

### ISSUE THREAD

**Issue by JonBoyle87** [dmlc/mxnet#2977]
Hi,

I've come to mxnet after looking at a few other libraries for Deep Learning, and quite like the API compared to others; however, there are a few things I'm uncertain of. Would someone be able to point my in the right direction on a few points? Even if it's just pointing to some examples (although, I haven't quite found any that I think explains them, but maybe I'm just misunderstanding).

These are all questions related to the Python API.

- I've got my own data that is of a fixed size, but are not images and need their own pre-processing. I understand I the best way would to store this in a database file for use in mxnet?
- Is it possible to use data in memory (e.g. numpy matrices) for training/testing without saving to disk? I don't necessarily plan to do this, but I'm interested all the same.
- How can I run a trained network on a single item? i.e. a numpy matrix or some form or another.

Thanks

**Comment by VoVAllen** [comment]
Please refer to mx.io.NDArrayIter with this example (https://github.com/dmlc/mxnet/blob/master/example/notebooks/tutorial.ipynb)

**Comment by JonBoyle87** [comment]
Thanks for the pointers. A quick look-through seems to answer all my points! I'll have a look through the rest of the notebooks just for safe measure.

Thanks!
