### ISSUE TITLE
Why memory usage increased to 30G when I changed the pool layer's strider from (2,2) to (1,1)    

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#2982]
This is my network : 

    data     = mx.symbol.Variable('data')  
    label    = mx.symbol.Variable('label')  
    conv1    = mx.symbol.Convolution(data=data, kernel=(3,3), pad=(1,1),stride=(1,1),num_filter=128)
    relu1    = mx.symbol.Activation(data=conv1, act_type=act_type)   
    conv2    = mx.symbol.Convolution(data=relu1, kernel=(3,3), pad=(1,1),stride=(1,1), num_filter=128)
    relu2    = mx.symbol.Activation(data=conv2, act_type=act_type)  
    pool1    = mx.symbol.Pooling(data=relu2, pool_type="max",kernel=(2,2),stride=(2,2))
 
    conv3    = mx.symbol.Convolution(data=pool1, kernel=(3,3),  pad=(1,1),stride=(1,1),num_filter=128)
    relu3    = mx.symbol.Activation(data=conv3, act_type=act_type)
    conv4    = mx.symbol.Convolution(data=relu3, kernel=(3,3),  pad=(1,1),stride=(1,1),num_filter=128)
    relu4    = mx.symbol.Activation(data=conv4, act_type=act_type)   
    pool2    = mx.symbol.Pooling(data=relu4, pool_type="max",kernel=(2,2),stride=(2,2))
    conv5    = mx.symbol.Convolution(data=pool2, kernel=(3,3),  pad=(1,1),stride=(1,1),num_filter=128)
    relu5    = mx.symbol.Activation(data=conv5, act_type=act_type)
    pool3    = mx.symbol.Pooling(data=relu5, pool_type="max",kernel=(2,2),stride=(2,2))
    flatten  = mx.symbol.Flatten(data=pool3)    
    fc1      = mx.symbol.FullyConnected(data=flatten, num_hidden=4096)  
    relu5    = mx.symbol.Activation(data=fc1, act_type=act_type)
    dropout3 = mx.symbol.Dropout(data=relu5, p=0.5) 
    #
    fc2      = mx.symbol.FullyConnected(data=dropout3, num_hidden=4096)  
    relu5    = mx.symbol.Activation(data=fc2, act_type=act_type)
    dropout3 = mx.symbol.Dropout(data=relu5, p=0.5) 
    #
    fc8 = mx.symbol.FullyConnected(data=dropout3, num_hidden=num_classes, name="fc8")
    softmax  = mx.symbol.SoftmaxOutput(data=fc2, name='softmax') 
    return  softmax

when I changed strider to (1,1) for all pool layers ,the memory usage increase to 30G.If strider is (2,2) it only takes about 2G~4G memory.
Is that normal?

**Comment by Godricly** [comment]
If u used (1,1), your pooling kernel will move with step size of 1. The output size is almost the same with feature map before pooling.
