### ISSUE TITLE
How to transfer model file(.params) trained by mx.gpu to mx.cpu using for test

### ISSUE THREAD

**Issue by pinglforever** [dmlc/mxnet#2992]
I trained the model to generate .params and .json on my gpu(mx.gpu(0)), I know there will be error when loaded with cpu, so, How to transfer it to a file that can be used under cpu context? thanks!

**Comment by tornadomeet** [comment]
i have write one: https://github.com/tornadomeet/mxnet-face/blob/master/util/chdevice.py

**Comment by tornadomeet** [comment]
i have write one: https://github.com/tornadomeet/mxnet-face/blob/master/util/chdevice.py

**Comment by tornadomeet** [comment]
i have write one script: https://github.com/tornadomeet/mxnet-face/blob/master/util/chdevice.py

**Comment by tornadomeet** [comment]
i have write one script: https://github.com/tornadomeet/mxnet-face/blob/master/util/chdevice.py

**Comment by tornadomeet** [comment]
i have write one script: https://github.com/tornadomeet/mxnet-face/blob/master/util/chdevice.py

**Comment by tornadomeet** [comment]
i have write one script: https://github.com/tornadomeet/mxnet-face/blob/master/util/chdevice.py

**Comment by tornadomeet** [comment]
i have write one script: https://github.com/tornadomeet/mxnet-face/blob/master/util/chdevice.py

**Comment by pinglforever** [comment]
@tornadomeet  Great, that' s help me a lot! , thanks!
