### ISSUE TITLE
How to use torch io and mxnet symbol to train model?

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#2993]
Hello, just see the document http://mxnet.readthedocs.io/en/latest/how_to/torch.html for use torch tensor and modules in mxnet, so how to use torch io + mxnet's symbol to train the model?  thanks~

**Comment by piiswrong** [comment]
You can wrap torch's io in a torch module

**Comment by winstywang** [comment]
Not implemented for now...
