### ISSUE TITLE
Under CPU model, convert Caffe model to MXNET using convert tool failed

### ISSUE THREAD

**Issue by ChenFengAndy** [dmlc/mxnet#2997]
I have a lot of caffe model file which I trained before.  When I convert it into MXNET format with the model convert tools. googlnet trained from caffe show similar problem under CPU mode. 
It report following error
I0811 13:42:19.532551 20173 net.cpp:228] conv1 does not need backward computation.
I0811 13:42:19.532557 20173 net.cpp:228] input does not need backward computation.
I0811 13:42:19.532563 20173 net.cpp:270] This network produces output prob
I0811 13:42:19.532578 20173 net.cpp:283] Network initialization done.
I0811 13:42:19.540653 20173 net.cpp:761] Ignoring source layer data
I0811 13:42:19.543014 20173 net.cpp:761] Ignoring source layer loss
Swapping BGR of caffe into RGB in mxnet
converting layer conv1, wmat shape = (32, 3, 7, 7), bias shape = (32,)
converting layer conv2, wmat shape = (64, 32, 5, 5), bias shape = (64,)
converting layer conv3, wmat shape = (128, 64, 3, 3), bias shape = (128,)
converting layer fc6, wmat shape = (512, 6272), bias shape = (512,)
Traceback (most recent call last):
  File "../convert_model.py", line 108, in <module>
    main()
  File "../convert_model.py", line 90, in main
    wmat = wmat.reshape(arg_shape_dic[weight_name])
ValueError: total size of new array must be unchanged

It looks to me that the CPU mode code process the CONV and POOLING in a way different from Caffe.

**Comment by ChenFengAndy** [comment]
I made a pull request   https://github.com/dmlc/mxnet/pull/2999

**Comment by winstywang** [comment]
Let's move to that PR for discussion. Close for now.
