### ISSUE TITLE
How to register python operator to be used in C++ calling

### ISSUE THREAD

**Issue by qingswu** [dmlc/mxnet#3002]
Is it possible to load a customized python operator in c++ while using the cpp classification example? I tried to save the net into json, but when loading in C++, it says cannot find custom operator.

**Comment by tornadomeet** [comment]
i think it should not, c++ cannot call python code, you need to write it in the c++ side.

**Comment by piiswrong** [comment]
It doesn't work that way. You can only register python op from python
