### ISSUE TITLE
mxnet start training procedure very slowly

### ISSUE THREAD

**Issue by austingg** [dmlc/mxnet#3012]
hi, guys
When I start a process to train some model with mxnet, the process waits a long time to really start to train, even though I use very small data input such as cifar10. Sometime it takes more than one mintue.

**Comment by tornadomeet** [comment]
i also met it  these days, but occasionally,  never met it before.

**Comment by austingg** [comment]
some settings of my environment
cuda version: 7.5 
cudnn version: 5.1
GPU: M40
System: CentOS 7.1

Seems  Caffe and Torch start training process instantly.

**Comment by VoVAllen** [comment]
It would be helpful if your provide your network structure

**Comment by piiswrong** [comment]
Disable opencv or compile opencv without gpu support

**Comment by austingg** [comment]
@VoVAllen  I just use the train_cifar10_resnet.py in the example directory.

**Comment by winstywang** [comment]
This is caused by the GPU memory allocation of opencv. Disable GPU support of opencv should resolve this issue. 

Please reopen it if you find this solution does not work.
