### ISSUE TITLE
error:mxnet/mshadow/mshadow/./base.h:136:23: fatal error: cblas.h: No such file or directory

### ISSUE THREAD

**Issue by SevenGong** [dmlc/mxnet#3013]
When I do the command "make -j8", it shows error:

In file included from /home/congleng/work/deeplearning-tools/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:13,
                 from src/c_api/c_api.cc:11:
/home/congleng/work/deeplearning-tools/mxnet/mshadow/mshadow/./base.h:136:23: fatal error: cblas.h: No such file or directory
     #include <cblas.h>
                       ^
compilation terminated.

What should I do to solve the problem?

**Comment by SevenGong** [comment]
My system is ubuntu14.04.

**Comment by zihaolucky** [comment]
@SevenGong How did you slove the problem?

**Comment by SevenGong** [comment]
@zihaolucky Download mxnet again using offical command.
