### ISSUE TITLE
neural-style doesn't support multi-gpus

### ISSUE THREAD

**Issue by zsefvlol** [dmlc/mxnet#3033]
I'm trying neural-style demo on 4 GPUs. But when passing `--gpu 0,1,2,3`, it goes wrong.
I found this:
In 'example/neural-style/run.py':
`parser.add_argument('--gpu', type=int, default=0,
                    help='which gpu card to use, -1 means using cpu')`
and changed `type=int` to `type=str`, still not working. Could you fix that? 
Thanks.

**Comment by winstywang** [comment]
How would you expect neural style work on multi-gpu? Data parallel or Model parallel? You may need to first know the technical details before asking for new features.

**Comment by zsefvlol** [comment]
Thanks for reply. I saw an [article(in Chinese)](http://phunter.farbox.com/post/mxnet-tutorial2) by Phunter, which mentioned multi-gpus are supported. I'm trying to find a way to reduce every epoch/iteration time, so that to finish processing image more quickly.
I'm new to ML. Using multi-gpu on forward/backward may fit my needs.
Thanks again.

**Comment by winstywang** [comment]
You can use data parallel to run several images together on multi-gpu. It will not speed up the calculation of single image. It is equivalent to run them individually on different GPUs, since there is no model parameter update.
