### ISSUE TITLE
different output_shape in two machines

### ISSUE THREAD

**Issue by JohanCao** [dmlc/mxnet#3034]
Hi All,

I was running the fully convlutional network for semantic segmentation and the network structure is based on vgg16 net. When the input size is 500*500, the output shape (last layer is softmax) is different in two machines. One is 34 * 34 and the other is 35 * 35, the codes are exactly the same in the two machines. Anyone can help please?

Regards
Johan

**Comment by winstywang** [comment]
Do you use the same MXNet version? The behavior of Pooling Op has been changed in one PR to make it compatible with CuDNN

**Comment by JohanCao** [comment]
@winstywang  Yes, it's all 0.7.0

**Comment by winstywang** [comment]
No, please check the commit id. Sorry for this confusion.

**Comment by JohanCao** [comment]
That's the problem! Thank you!
