### ISSUE TITLE
mx.nd.zeros() slow on GPU

### ISSUE THREAD

**Issue by zsefvlol** [dmlc/mxnet#3039]
It seems that mx.nd.zeros() runs pretty slow on GPU, rather than CPU.
Tested on my 980Ti and AWS g2.8xlarge instance (K520 GPU). CUDA 7.0/cudnn R5.
Python codes and results commented:

    import mxnet as mx
    import time
    shapes = [[100, 100]] * 10

    start_time = time.time()
    result = [mx.nd.zeros(shape, mx.cpu()) for shape in shapes]
    stop_time = time.time()
    print 'mx.nd.zeros(cpu):' + str(stop_time-start_time)
    # mx.nd.zeros(cpu):0.000483989715576

    start_time = time.time()
    result = [mx.nd.zeros(shape, mx.gpu(0)) for shape in shapes]
    stop_time = time.time()
    print 'mx.nd.zeros(gpu):' + str(stop_time-start_time)
    # mx.nd.zeros(gpu):0.752362966537

**Comment by pluskid** [comment]
There seem to be some issue causing the first CUDA api call to be very slow. Can you make a call of `zeros` on both GPU and CPU first to warm up, and then measure the call time?

**Comment by zsefvlol** [comment]
I ran it 4 times. Results in seconds.

On 980Ti:

mx.nd.zeros(cpu):0.000653982162476
mx.nd.zeros(gpu):0.963800907135
mx.nd.zeros(cpu):0.000212907791138
mx.nd.zeros(gpu):0.00437688827515
mx.nd.zeros(cpu):0.000227928161621
mx.nd.zeros(gpu):0.000316143035889
mx.nd.zeros(cpu):0.000238180160522
mx.nd.zeros(gpu):0.000317096710205

On K520 (AWS g2.8xlarge instance):

mx.nd.zeros(cpu):0.000871896743774
mx.nd.zeros(gpu):77.7828960419
mx.nd.zeros(cpu):0.000491857528687
mx.nd.zeros(gpu):0.000550031661987
mx.nd.zeros(cpu):0.00060510635376
mx.nd.zeros(gpu):0.000512838363647
mx.nd.zeros(cpu):0.000540971755981
mx.nd.zeros(gpu):0.000426054000854

**Comment by pluskid** [comment]
There are [many issues](https://github.com/dmlc/mxnet/issues?utf8=%E2%9C%93&q=opencv%20GPU%20slow) that seem to be related. Recompiling openCV withOUT GPU support seem to resolve those issues.

**Comment by winstywang** [comment]
Building Opencv without GPU should solve this issue. Please reopen it if you find it do not work.

**Comment by mli** [comment]
confirmed on my side. if you build opencv from scratch, it will enable gpu in default. we need to have a FAQ for all these things.

**Comment by mli** [comment]
there are instructions for how to build opencv without gpu:

https://github.com/dmlc/mxnet/blob/master/docs/how_to/build.md#build-opencv-from-source

related issue https://github.com/dmlc/mxnet/issues/3012
