### ISSUE TITLE
[R] Memory problem when implementing a CNN in R

### ISSUE THREAD

**Issue by hoaphumanoid** [dmlc/mxnet#3041]
I'm trying to implement the paper: Very Deep Convolutional Networks for Natural Language Processing, ([Conneau et al., 2016](http://arxiv.org/abs/1606.01781)). I'm having problems when feeding the data to the network.

Firt I create fake data. Each input is a matrix of 0 and 1 of size 69x1014. The dataset is just 256 inputs (the real one is much bigger)
```R
vocab_size <- 69  
feature_len <- 1014
number_examples <- 256
input_fake <- as.integer(sample(c(0,1), replace=TRUE, size=vocab_size*feature_len*number_examples))
output_fake <- as.integer(sample(c(0,1), replace=TRUE, size=number_examples))
train.array <- input_fake
dim(train.array) <- c(vocab_size, feature_len, 1, number_examples)
train.y <- output_fake
dim(train.array)
length(train.y)
format(object.size(train.array),units='auto')
```
The size of `train.array` is 68Mb.

Then I create a model (the real one of the paper is much more complex, but just to try):
```R
data <- mx.symbol.Variable('data')
conv0 <- mx.symbol.Convolution(data=data, kernel=c(3,3), num_filter=64)
norm1 <- mx.symbol.BatchNorm(data=conv0)
act1 <- mx.symbol.Activation(data=norm1, act_type="relu")
pool1 <- mx.symbol.Pooling(data=act1, pool_type="max", kernel=c(3,3), stride=c(2,2))
flatten <- mx.symbol.Flatten(data=pool1)
fc3 <- mx.symbol.FullyConnected(data=flatten, num_hidden=2)
network<- mx.symbol.SoftmaxOutput(data=fc3)
```

Then I train the model
```R
model <- mx.model.FeedForward.create(network, X=train.array, y=train.y,
                                     ctx=devices, num.round=10, array.batch.size=100,
                                     learning.rate=0.07, momentum=0.9,  eval.metric=mx.metric.accuracy,
                                     wd=0.00001,
                                     epoch.end.callback=mx.callback.log.train.metric(100))
```

My memory goes up like a rocket. Everything crashes, there are a lot of explotions and I get this error:

Error: [19:24:46] d:\chhong\mxnet\src\storage\./cpu_device_storage.h:44: Check  notnull: ptr 

Any idea?

**Comment by thirdwing** [comment]
First, your code is not runnable, we don't define `conv1`;

Second, please try smaller `array.batch.size`.

**Comment by hoaphumanoid** [comment]
I edited the comment, it was wrong because the actual network is much more bigger. I will try the batch size and tell you what happens. Thanks @thirdwing

**Comment by hoaphumanoid** [comment]
It is working now, even with a batch size of 128. However it's taking around 9Gb of memory. I'm not GPU but CPU.

**Comment by anargyri** [comment]
It looks like some kind of memory deallocation issue. I ran Miguel's code above several times without a problem (set devices to one GPU). Then I ran the code starting below the assignment of conv0. This crashes the R GUI. 
So, every time you need to reassign conv0; otherwise the program crashes.

**Comment by lichen11** [comment]
What do you mean by reassign conv0?
