### ISSUE TITLE
The number of bands for images

### ISSUE THREAD

**Issue by zhqshen** [dmlc/mxnet#3048]
Hi, all
 My images have 4 bands, when I use im2rec.py to pack these images with option --color=-1, there is still only 3 bands for packed images in .rec file, the cv2.imread reads all 4 bands from images, how to pack all 4 bands into .rec file?

**Comment by winstywang** [comment]
You mean channels? Try to use RGBA png

**Comment by zhqshen** [comment]
Yes, I use the png format, and the cv2.imread returns 4 bands (for example, the shape is (300,300,4)), and after im2rec packed, the data shape will be (3,300,300), so, the im2rec can only pack 3 bands?

**Comment by winstywang** [comment]
Yes, you may need to modify it a bit. It should not be complicated.

**Comment by winstywang** [comment]
You can also refer to this issue: https://github.com/dmlc/mxnet/issues/2987

**Comment by zhqshen** [comment]
ok, thanks.
