### ISSUE TITLE
understanding update_on_kvstore

### ISSUE THREAD

**Issue by KeyKy** [dmlc/mxnet#3051]
I saw the function _create_kvstore in https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py
def _create_kvstore(kvstore, num_device, arg_params):
....
'''detect whether or not update weight on kvstore'''
update_on_kvstore = True
if not kv or 'local_allreduce' in kv.type:
       update_on_kvstore = False

why does local_allreduce not update weight on kvstore, while local_update_cpu update weight on kvstore?
Thanks!

**Comment by piiswrong** [comment]
because it's a switch for controlling that behavior

**Comment by KeyKy** [comment]
Thanks
