### ISSUE TITLE
Memory leak of NDArray when initializing with numpy arrays of different shapes

### ISSUE THREAD

**Issue by neodooth** [dmlc/mxnet#3055]
Here's an example to reproduce the problem. You can watch the memory grows a lot in htop when executing the third section (from 100m+ to ~6.4G)

```python
import mxnet as mx
import numpy.random as npr

raw_input('enter to test same shape')
for i in range(500):
    shape = (2000, 2000)
    nouse = mx.nd.array(npr.random(shape))

raw_input('enter to test random shape np.array')
for i in range(500):
    shape = (2000, npr.randint(1500, 2500))
    nouse = npr.random(shape)

raw_input('enter to test random shape mx.nd.array')
for i in range(500):
    shape = (2000, npr.randint(1500, 2500))
    nouse = mx.nd.array(npr.random(shape))

raw_input('enter to exit')
```

As I saw in #2981 and #2827 , the GPU memory release is async, then #2927 is merged to resolve that issue. Now this seems to be a CPU version of that issue.

**Comment by piiswrong** [comment]
Memory isn't really 'leaked'. It's released to a pool. The pool will only be emptied when an allocation returns out of memory.
You can run this forever and it won't fail with OOM.

**Comment by neodooth** [comment]
@piiswrong Actually the rcnn example is killed by the os because it used all the memory(128g). I think this is because the allocation algorithm, i.e. https://github.com/dmlc/mxnet/blob/b7df20d6bea07a191552c89e4b14021eeedd5504/src/storage/pooled_storage_manager.h#L54 .

It seems this line looks for free space in the pool according to the __exact__ size, while in practical there are a lot of different but similar sizes allocated. For example, in the rcnn example, the images are all resized to a shorter size of 600px, so basically the sizes are (~600, ~600), but they are __all different sizes__, so this leads to a collapse of the program, since (600, 600), (600,601), (600,602)...(600, xxxx) will all be individually allocated. I think this part needs some refactoring...

Related: https://github.com/dmlc/mxnet/issues/1176 and https://github.com/dmlc/mxnet/issues/1952

For now I'll try to add a threshold, which is removed in https://github.com/dmlc/mxnet/commit/b7df20d6bea07a191552c89e4b14021eeedd5504

**Comment by mistycheney** [comment]
I also encountered this problem. As @neodooth suggested, reverting `pooled_storage_manager.h` and `storage.cc` to the status before https://github.com/dmlc/mxnet/commit/b7df20d6bea07a191552c89e4b14021eeedd5504 successfully prevented out-of-memory from occuring again.
I guess one can set `kPoolThreshold` to a larger value than `4096 * 1024 * 1024` if a larger RAM is available.

**Comment by winstywang** [comment]
@piiswrong Could you revert this changes? It affects a lot of users.

**Comment by piiswrong** [comment]
@winstywang Should be fixed by this https://github.com/dmlc/mxnet/pull/3075

**Comment by winstywang** [comment]
@neodooth Could you verify that this PR fixes this issue?

**Comment by neodooth** [comment]
@winstywang yes, cpu memory now remains in a stable range
