### ISSUE TITLE
why symbol name?

### ISSUE THREAD

**Issue by umichyiwan** [dmlc/mxnet#3057]
I am the beginner of mxnet. Now I am trying to create shared weights layers. My questions are:
1. for shared weights convolution layers, do they have to use different names?
2. why do we need name attribute? If I don't explicitly declare the name, what will happen.
Thank you!

**Comment by xiaomaxiao** [comment]
http://blog.csdn.net/qq_25491201/article/details/51277817
maybe helpful to you

**Comment by winstywang** [comment]
Solved by personal communication.
