### ISSUE TITLE
how to output loss

### ISSUE THREAD

**Issue by xiaomaxiao** [dmlc/mxnet#3058]
how to output loss \ accuray \ or others log info.
if have any  tutorial or demo?
I search fo a long time ,no harvest.
tks.

**Comment by neodooth** [comment]
https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L82

**Comment by xiaomaxiao** [comment]
@neodooth tks ,   alse loss?  is  there  documents in detail?

**Comment by neodooth** [comment]
I didn't find any docs. To print these in the log you need to supply corresponding metrics to `fit`. You can also take a look at https://github.com/dmlc/mxnet/blob/master/example/rcnn/rcnn/metric.py and https://github.com/dmlc/mxnet/blob/master/example/rcnn/tools/train_rpn.py#L78

**Comment by xiaomaxiao** [comment]
tks

**Comment by ysh329** [comment]
mark. 
There're a lot of invalid links.

**Comment by LeonJWH** [comment]
@neodooth 
I also want to output loss and speed information in the terminal when training my own data, but i cannot find and docs in the apache/incubator-mxnet repo. The links above are now invalid. Can you give me some advices?

**Comment by neodooth** [comment]
@LeonJWH 
Hi, the links should be around the commit 83dc0b4d46383ef63b2731f12663aa947d96c2ad.
https://github.com/apache/incubator-mxnet/blob/83dc0b4d46383ef63b2731f12663aa947d96c2ad/example/image-classification/train_model.py#L82
https://github.com/apache/incubator-mxnet/blob/83dc0b4d46383ef63b2731f12663aa947d96c2ad/example/rcnn/rcnn/metric.py#L7
https://github.com/apache/incubator-mxnet/blob/83dc0b4d46383ef63b2731f12663aa947d96c2ad/example/rcnn/tools/train_rpn.py#L78

I haven't been using mxnet for quite a while and it looks like some major updates has taken place... but the ideas should still be the same, those metrics (for computing accuracy or loss) will be called when an iter is finished, and add some print there should do. I used to infer speed by reading the default logs and compute the intervals of the lines and iter numbers, but if you really want to print the speed, you might need to modify the code beneath the ```fit``` method; there must be a ```for``` or ```while``` somewhere to launch each iteration.

The metrics thing is from my experience of running the rcnn example, I don't know if it's the same if you're running something else.

**Comment by LeonJWH** [comment]
@neodooth 
I have solved my problem by set "**eval_metric = 'ce'**" in **mod.fit**, to print cross entropy loss after each iter in the terminmal. According to **Evaluation Metric API**
[http://mxnet.io/api/python/metric.html](url)
