### ISSUE TITLE
crashed when execute "example/warpctc/lstm_ocr.py"

### ISSUE THREAD

**Issue by xylcbd** [dmlc/mxnet#3065]
commit id : 8cc25600cf2b26bd9324baaf2da55c38e449e1d8
execute command : python example/warpctc/lstm_ocr.py
error message : 

```
begin fit
2016-08-19 10:35:44,641 Start training with [gpu(1)]
iter
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: compute_ctc_loss, stat = execution failed
Aborted (core dumped)
```

ADD:
I download http://www.webpagepublicity.com/free-fonts/x/Xerox%20Sans%20Serif%20Narrow%20Bold.ttf to mxnet/data/Xerox.ttf , and then run the command.Mxnet is build with CUDA enabled.

**Comment by winstywang** [comment]
@xlvector

**Comment by xlvector** [comment]
Have you build baidu-warpctc and include warpctc plugin?

**Comment by piiswrong** [comment]
This maybe relevent https://github.com/baidu-research/warp-ctc/issues/40

**Comment by xylcbd** [comment]
mxnet is built with baidu-warpctc , and the warpctc library is loaded success.

YES , it build with CUDA 8.0. And I will try the solution of https://github.com/baidu-research/warp-ctc/issues/40. thx!
