### ISSUE TITLE
Error when import .mat format data

### ISSUE THREAD

**Issue by lyjday** [dmlc/mxnet#3066]
train sample:1500,test sample:13500，使用CNN网络，输入数据5*5*12，

`# data
data = sio.loadmat(args.data_dir + 'data.mat')
train_data = data['train_data']
test_data = data['test_data']
train_label = data['train_label']
test_label = data['test_label']
train_data = nu.reshape(train_data,(1500,5,5,12))
test_train = nu.reshape(test_data,(13500,5,5,12))
train_label = nu.reshape(train_label,1500)
test_label = nu.reshape(test_label,13500)`

我将这些处理好的数据直接送入到了NDArrayIter,
`
def get_iterator(args,kv):
#def get_iterator(args,kv):
     #data_dir = args.data_dir
    train = mx.io.NDArrayIter(
        data = train_data,
        label =  train_label,
        batch_size = args.batch_size,
        shuffle = True,
        last_batch_handle = 'pad'
        )

    val = mx.io.NDArrayIter(
        data = test_data,
        label =  test_label,
        batch_size = args.batch_size,
        shuffle = True,
        last_batch_handle = 'pad'
        )

    return (train, val)`

结果，迭代了一次，训练准确率21%，没有测试准确率，就直接出现检查错误。
[11:12:06] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch
我第一次导.mat数据，不知道怎么解决，有没有人可以指导一下啊？ 谢谢！

**Comment by winstywang** [comment]
It does not relate to mat. You should carefully check whether the output shape of the network matches the label shape you provided.

BTW, it is better to use English next time to raise new issues, since we still have many users who do not speak Chinese :)

**Comment by lyjday** [comment]
@winstywang  Thank you,I will check it.
