### ISSUE TITLE
[Bug] CPU mode have different result with the model trained on GPU

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#3068]
I am training a image retrieval model using mxnet, the output (full connect layer) is a 128-dim vector. 
The model is trained on GPU mode and the GPU forward can get a reasonable output, however when I load the model and run a CPU forward I get a very different output.

OS: Ubuntu 16.04 LTS
CUDA: 8
cudnn: 5.1
mxnet: 13facf065fcef5d745865a590cc5a669405594bb
OpenCV: 3.1.0

------------------
Here is a little more information that may help:
If the net have a BatchNorm layer, the output is very different,  the magnitude is about 10e8 to 10e10. and if the net don't have the BatchNorm layer, the magnitude is about 10e-1 to 10e-2.

**Comment by winstywang** [comment]
Is it correct without BN layer?

**Comment by shuokay** [comment]
Without BN layer, the two output vector is not exactly the same. To one image, if both train and test run on GPU, the Euclidean distance of output vectors is exactly zero, if train on GPU and test on CPU, the distance is about 10e-1 to 10e-2. If with BN layer, the distance is about 10e8 to 10e10.

**Comment by shuokay** [comment]
sorry everyone, it's my fault. I did not pass the `aux_params` to the `executor` correctly. Now the difference between cpu mode and gpu mode is about `10e-8`, I think it is reasonable.
