### ISSUE TITLE
mxnet workspace size error (crepe model) in python/windows

### ISSUE THREAD

**Issue by ilkarman** [dmlc/mxnet#3071]
I am trying to run the [Crepe model ](https://github.com/zhangxiangxiao/Crepe) for sentiment analysis on a Windows Server 2012 machine with 32 cores and 444GB of RAM. However I can't use the same parameters as the above model ...

```
BATCH_SIZE = 128  
NUM_FILTERS = 256  
EPOCHS = 5000
```
Crashes my machine with the following error:

```
[07:10:06] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [07:10:06] d:\chhong\mxnet\src\operator\./convolution-inl.h:279: Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 2816000000 Bytes
Given: 536870912 Bytes
[07:10:06] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [07:10:06] d:\chhong\mxnet\src\engine\./threaded_engine.h:306: [07:10:06] d:\chhong\mxnet\src\operator\./convolution-inl.h:279: Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 2816000000 Bytes
Given: 536870912 Bytes
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
```

It seems there is some memory issue when implementing convolutional layers on a CPU?

My full code is [here](https://github.com/ilkarman/Bangalore_Sentiment/blob/master/mxnet/cnn.py).

**Comment by piiswrong** [comment]
set workspace to a bigger value in sym.Convolution

**Comment by ilkarman** [comment]
piiswrong I can find that [variable in the R code](https://github.com/dmlc/mxnet/blob/master/R-package/man/mx.symbol.Convolution.Rd), however not in the python code. Would you mind linking me to it?

**Comment by hoaphumanoid** [comment]
Hi I tried to use a bigger workspace value (1024) but I'm getting the same error as @ilkarman. Also I tried to problem with a gpu but I get the following error:

`mxnet.base.MXNetError: [17:30:52] d:\chhong\mxnet\src\storage\./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
`

I reduced the batch_size to 16. Any ideas???

**Comment by piiswrong** [comment]
124 is too small. try 2048 or bigger

**Comment by wkcw** [comment]
@ilkarman Have you solved the problem? I met the same problem and tuning the layers' workspace didn't work
