### ISSUE TITLE
Any idea for this with multi-GPUs?

### ISSUE THREAD

**Issue by Trangle** [dmlc/mxnet#3078]
When I use only one gpu, the speed and memory usage was liked this:
![1](https://cloud.githubusercontent.com/assets/3235116/17819494/bb5ed06a-667a-11e6-8903-392150bfd8c7.png)

Then when two, the speed and memory usage was liked these respectively.
![2](https://cloud.githubusercontent.com/assets/3235116/17819493/bae7373a-667a-11e6-9666-42c292ea543d.png)
![3](https://cloud.githubusercontent.com/assets/3235116/17819492/baa8ecc8-667a-11e6-92c3-ee577d2d3aee.png)

**Comment by mli** [comment]
it may be your network is small, it already runs quite fast. there is extra communication cost for using two gpus. it's only worth if your network is large.

**Comment by Trangle** [comment]
@mli Thank you for your reply, I got it.
