### ISSUE TITLE
[R] custom CSVIter in R

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#3079]
I'm working in a sentiment analysis problem where I have to read textual data from a csv in batches and then transform it into a matrix. 

This is an example of the data. The first column is the sentiment, positive or negative and the second column is the comment:

``` csv
1,"This is good"
0,"This is bad"
```

After reading each line, I have to map each comment into a matrix of a fixed size. I have a dictionary of 69 characters. Supposing that the maximum length of  each sentence is 10, then I will have a matrix of 10x69. Then I encode each letter with the dictionary. So for example the first letter is a T, which is the 20th position in the dictionary. Therefore the in the position [1,20] I will put a 1. Like this:

``` R
alphabet <- c("abcdefghijklmnopqrstuvwxyz0123456789-,;.!?:'\"/\\|_@#$%^&*~`+ =<>()[]{}")
sentiment_matrix <- matrix(0,10,69)
sentiment_matrix[1,20] <- 1
...
```

What I'm trying to do is to create a custom iterator similar to `mx.io.CSVIter`. However, for each batch of data I read, I need to the previous transformation. Afterwards the iterator goes directly into `mx.model.FeedForward.create`.

Any ideas how to create the iterator?

**Comment by ilkarman** [comment]
If you created a custom iterator (without wrapping it in the proper class), would you be able to use R's equivalent to the [executor function](http://mxnet.io/packages/python/symbol.html#module-mxnet.executor) - to avoid having to use the FeedForward wrapper?

**Comment by hoaphumanoid** [comment]
@ilkarman I'm trying to do the oposite, change the CSVIter in order to only use the FeedForward wrapper. If I'm not able to do a custom version of the iter I would try the other method. I expect the first to be more optimal and spend less memory, though I'm not sure about this.

**Comment by hoaphumanoid** [comment]
I found that CSVIter doesn't take strings. I have `fake.csv`:

```csv
99,0.9,'good',"This is good"
77,0.7,'bad',"This is bad"
```
If I use CSVIter:

```R
it <- mx.io.CSVIter(
  data.csv = 'fake.csv',
  data.shape = c(1,4),
  batch.size = 1
)
it$iter.next()
dlist <- it$value()
dlist$data
```

I get:

```R
, , 1

     [,1] [,2] [,3] [,4]
[1,]   99  0.9    0    0
```
Is there a workaround to parse strings?

Also, I saw issue #1804 saying that CSVIter does not support data parallelism, does this mean that it will not support computation with several GPUs?

**Comment by hoaphumanoid** [comment]
I made some advances:

```R
CustomIter <- function (data.csv, data.shape, batch.size, shuffle=FALSE) 
{
  vocab_size <- data.shape[1]
  feature_len <- data.shape[2]
  csv_iter <- mx.io.CSVIter(data.csv=data.csv, data.shape=c(1,feature_len), batch.size=batch.size)
  csv_iter$iter.next()
  vect <- as.array(csv_iter$value()$data)
  data <- array(0, dim=c(vocab_size,feature_len,1, batch.size))
  format(object.size(data),units='auto')
  for(b in 1:batch.size){
    for(f in 1:feature_len){
      data[vect[1,f,b],f,1,b] <- 1
    }
  }
  label <- array(0, c(1,batch.size) )
  custom_iter <- mx.io.arrayiter(data=data, label=label, batch.size=batch.size, shuffle=shuffle) 
}
```
This returns a custom iterator, it is not very efficient. However, I'm having problems when training the net. I got `[1] Train-accuracy=NaN`. Am I doing the right thing?

**Comment by miguelgfierro** [comment]
Example of a similar solution can be found in https://github.com/dmlc/mxnet/issues/4105
