### ISSUE TITLE
Issue installing mxnet R package with drat

### ISSUE THREAD

**Issue by ssoi** [dmlc/mxnet#3087]
I followed the installation instructions and received the following error
```
> library(drat)
> drat:::addRepo("dmlc")
> install.packages("mxnet")
Installing package into ‘/home/ssoi/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
downloaded 0 bytes

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot download all files
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'http://dmlc.ml/drat/src/contrib/mxnet_0.7.tar.gz': status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘mxnet’ failed
> 
```

**Comment by hoaphumanoid** [comment]
Got the same error today, I had to compile from code. But I had to use a previous version of the repo. It is possible that there is some error in the compilation and that's why the  method with drat is now working

**Comment by thirdwing** [comment]
@ssoi You got this error because we don't provide pre-built package for linux.

**Comment by ssoi** [comment]
Sorry I missed that in the installation instructions. Thanks!

**Comment by michaelsbradleyjr** [comment]
I'm getting the same 404, even though I'm running R / R Studio on a mac laptop.
