### ISSUE TITLE
build mxnet with error " error: ‘CUBLAS_DATA_HALF’ was not declared in this scope"

### ISSUE THREAD

**Issue by pinglforever** [dmlc/mxnet#3093]
After execute make command, there occurs the error:
```
make -j8 |& grep -E "warning|error"
/mshadow/mshadow/./././dot_engine-inl.h:277:20: error: ‘CUBLAS_DATA_HALF’ was not declared in this scope
```
How can I solve this error? Thanks!

**Comment by piiswrong** [comment]
git pull && git submodule update && make clean && make

**Comment by pinglforever** [comment]
I find the issue is about the cuda8.0 environment and I use a early version to build. So change some code can solve this issue, thanks!
