### ISSUE TITLE
import mxnet error with caffe plugin 

### ISSUE THREAD

**Issue by xzqjack** [dmlc/mxnet#3108]
* ubuntu 14.04
* cuda 7.5
* the newest caffe and mxnet

Hi, i try to reinstall mxnet with caffe plugin, just described as [http://dmlc.ml/mxnet/2016/07/29/use-caffe-operator-in-mxnet.html](http://dmlc.ml/mxnet/2016/07/29/use-caffe-operator-in-mxnet.html).
The compilation of caffe and mxnet are both successful.
But some errors occured 
```
OSError: libcaffe.so.1.0.0-rc3: cannot open shared object file: No such file or directory
```
when I run
```
import mxnet
```

While Running bellow code is ok. Running example code of caffe works too.
```
import caffe 
import mxnet
```
There maybe some errors about link of lib. Any hits to solve this?
@HrWangChengdu

**Comment by HrWangChengdu** [comment]
hi @xzqjack 
As mentioned in https://github.com/dmlc/mxnet/blob/master/make/config.mk#L115,  please add caffe/build/lib path to LD_LIBRARY_PATH written in ~/.bashrc.
Then run "source ~/.bashrc" in terminal, problem should be solved.

**Comment by xzqjack** [comment]
@HrWangChengdu 
Sorry for ignoring the notice. It works.

**Comment by HrWangChengdu** [comment]
@xzqjack No problem. :-). Any further problems are welcomed.
