### ISSUE TITLE
Will im2rec.py automatic convert gray image to color image ?

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#3109]
These days I  checked my dataset and  found that some of the images are gray (some of them are broken).

I didn't realize this because the dataset is crawled from internet and it is too large to check . I created rec file by using im2rec.py (set the --color=1,for color image) with hole dataset.
When both creating and training ,there was not any log for that.
When I read image date by myself ,I found this problem.

I just  want to know :
1.Will im2rec.py automatic convert gray image to color image ?
2.If it will not, why mxnet could train the dataset  which has 2 different shapes(3,width,height and 1,width,height ) normally?
3.Will this cause validation accuracy  bad?

ps: The im2rec.py also could not recognize some kinds of broken images too.(It could recognize some kind of broken images,but not all the kind)

thank you !

**Comment by piiswrong** [comment]
depends on the cmdline arguments you use.
im2rec.py's usage explains it

**Comment by mli** [comment]
it depends how `cv2.imread` handles such situations, see

https://github.com/dmlc/mxnet/blob/master/tools/im2rec.py#L77

**Comment by albertyou2** [comment]
@piiswrong @mli OK i see.
