### ISSUE TITLE
Is the iterator asychronous?

### ISSUE THREAD

**Issue by ilkarman** [dmlc/mxnet#3114]
I can't figure out if the standard mx.io.ndarrayiter will load another batch before it is required by (e.g.) the GPU. Also I see there is an mx.io.csviter -> is that IO asynchronous and will get the data from disk whilst the previous batch is running?

**Comment by mli** [comment]
in python you can stack a `PrefetchingIter` to do prefetch. other iterators implemented in c++ such as recordioiter do prefetch in default
