### ISSUE TITLE
mxnet (python) very slow compared to Torch

### ISSUE THREAD

**Issue by ilkarman** [dmlc/mxnet#3120]
I have been trying to replicate the [crepe model](https://github.com/zhangxiangxiao/Crepe) in mxnet. And I think [my model](https://github.com/ilkarman/Bangalore_Sentiment/blob/master/mxnet/crepe_v2.ipynb) set-up is correct (this should run if you wanted to replicate).

However, even after trying out various methods (cpu, 1 gpu, 4 gpus, mx.mod.Module, mx.simple_bind, mx.FeedForward, etc) the best speed I can get is 10 hours per epoch (of around 2.5 million words). This means to do 50,000 epochs - it would take me 57 years.

I think it took Zhang a week:

> When I did the experiments, there was no CuDNN, no Titan X and the experiment for dbpedia takes about a week for 10 eras, each era being 5000 epoches.

And others have mentioned:

> For the record when I train the network on a Titan X (Maxwell) using CuDNN library and Torch in DIGITS on DBPedia dataset it takes ~15 minutes per epoch (498400 training samples, 56000 validation samples, with samples truncated to max 1024 characters).

I made a post [here](https://github.com/zhangxiangxiao/Crepe/issues/20).

I am not sure if I am doing something wrong, perhaps not using full power of mxnet - or if mxnet is just much slower than Torch and the module is complicated.

**Comment by mli** [comment]
if i understand the output at the end of your notebook, it process about 6k examples per second. according to the answer at the end of https://github.com/zhangxiangxiao/Crepe/issues/20, each epoch has around 500k examples. so it should only 1.5min to process an epoch. 

btw, i think xiangxiao uses different items than us: 

xiangxiao,  mxnet
eras => epoch
epoch => batch

**Comment by ilkarman** [comment]
Thank you @mli, I see what you're saying:

My batch-size is 128; and it does 50 batches (6400 samples) in around 105 seconds. Which is the same speed for my whole epoch of 2,100,000 reviews * (105/6500) = 565 minutes. So to do 10 epochs will cost me 4 days ... which is similar to the reported run-time of the model.

The per second rate is 6400/105 which is 60 so I'm not sure why the speedometer is giving that speed in the log?

What's a bit worrying is that I am on the 2nd epoch (lets say out of 10) and my accuracy on training is 0.51 ... I don't think it's realistic to assume it will hit 0.95 by epoch 10:

```
2016-08-24 10:19:14,630 - root - INFO - Epoch[2] Batch [5800]	Speed: 6059.23 samples/sec	Train-accuracy=0.500156
2016-08-24 10:21:01,582 - root - INFO - Epoch[2] Batch [5850]	Speed: 5984.89 samples/sec	Train-accuracy=0.512344
2016-08-24 10:22:46,565 - root - INFO - Epoch[2] Batch [5900]	Speed: 6096.17 samples/sec	Train-accuracy=0.511563
```

**Comment by ilkarman** [comment]
Turns out I have misspecified the model and forgot to add a stride of 3 to the max-pooling which created much higher dimensions than necessary. Everything works fine now and I have posted the diagram [here](https://github.com/ilkarman/Bangalore_Sentiment/blob/master/mxnet/README.md).

**Comment by mli** [comment]
nice document
