### ISSUE TITLE
Manipulating a network that is only giving by a `symbol.json`

### ISSUE THREAD

**Issue by vchuravy** [dmlc/mxnet#3123]
If one loads a pre-defined network like Inception-v3 from the MXNet model zoo, you don't normally have the code that generated the graph.

Now I would like to take parts of the network and use it for my own purposes. Do we have currently tools to do that, besides manipulating the json file directly? If not that should maybe be on the road-map.

The only reference to this that I could find is this https://github.com/dmlc/mxnet/issues/2657#issuecomment-231419750

@tqchen Could you maybe elaborate or did you actually mean recreating the model definition or manipulating the symbol graph after the fact?

**Comment by tqchen** [comment]
- what I mean is use symbol.load_json to load them in, 
- use symbol.get_internals to get the internal parts
- recompose the later parts that you need to change

**Comment by vchuravy** [comment]
Perfect thank you. That was what I was looking for.
