### ISSUE TITLE
warp-ctc can not work on gtx1080

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#3135]
error test_gpu:
```
Running GPU tests
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: compute_ctc_loss in small_test, stat = execution failed
Aborted (core dumped)
```

**Comment by piiswrong** [comment]
Looks like baidu ctc's problem. See if you can run their test successfully

**Comment by starimpact** [comment]
as I said, running test_gpu is failed.

**Comment by piiswrong** [comment]
Then this is a baidu ctc issue, not warp ctc. Please post on their repo.

**Comment by starimpact** [comment]
@piiswrong I suggest warpctc to only use cpu side function. baidu's ctc is not stable on gpu side. 
I have changed the plugin/warpctc to support only cpu side ctc. Do you need it?
