### ISSUE TITLE
[Windows] DLL Path and Name

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#314]
@hjk41 Is it possible to make the windows dll ```libmxnet.dll``` instead of ```mxnet.dll```? Since the later will be used by R libraries.

**Comment by tqchen** [comment]
@yajiedesign 

It is also great if we can point the build result path to lib/libmxnet.dll so it is consistent with linux/osx

**Comment by hjk41** [comment]
ok

On Sun, Oct 18, 2015 at 11:59 AM, Tianqi Chen <notifications@github.com>
wrote:

> @yajiedesign <https://github.com/yajiedesign>
>
> It is also great if we can point the build result path to lib/libmxnet.dll
> so it is consistent with linux/osx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/314#issuecomment-148975929>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by thirdwing** [comment]
@hjk41  Can you share the dll with me? Or can you help test the R package on Windows? I can tell you the steps.

**Comment by hjk41** [comment]
https://github.com/dmlc/mxnet/releases/download/untagged-3801d7b98bea4a33b21c/mxnet_0.9_win64_cpu_only.zip

This is a draft and is very large: ~600MB. I am now working to shrink the
size. Please use it for now and I will post the refined package soon.

On Mon, Oct 19, 2015 at 11:48 AM, Qiang Kou (KK) <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41> Can you share the dll with me? Or can
> you help test the R package on Windows? I can tell you the steps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/314#issuecomment-149089233>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
I have just compiled a version with statically linked opencv:

https://github.com/dmlc/mxnet/releases/download/untagged-175e0487d0d7aaff577b/mxnet_0.9_win64_cpu_only.7z

Please use this one and see if it works with R.

On Mon, Oct 19, 2015 at 12:34 PM, Chuntao HONG <chuntao.hong@gmail.com>
wrote:

>
> https://github.com/dmlc/mxnet/releases/download/untagged-3801d7b98bea4a33b21c/mxnet_0.9_win64_cpu_only.zip
>
> This is a draft and is very large: ~600MB. I am now working to shrink the
> size. Please use it for now and I will post the refined package soon.
>
> On Mon, Oct 19, 2015 at 11:48 AM, Qiang Kou (KK) <notifications@github.com
> > wrote:
>
>> @hjk41 <https://github.com/hjk41> Can you share the dll with me? Or can
>> you help test the R package on Windows? I can tell you the steps.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dmlc/mxnet/issues/314#issuecomment-149089233>.
>>
>
>
>
> --
> HONG Chuntao
> System Research Group
> Microsoft Research Asia
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by tqchen** [comment]
Thanks @hjk41  The file size is great. Do you think if you can give a script to "INSTALL" the library? I.e. put it in some location and have a script to setup Path automatically

**Comment by tqchen** [comment]
As far as I understand, mxnet_shell.cmd only works for this command line, but did not setup env for the system

**Comment by hjk41** [comment]
ok... I can make a installer for this.

On Mon, Oct 19, 2015 at 2:46 PM, Tianqi Chen <notifications@github.com>
wrote:

> As far as I understand, mxnet_shell.cmd only works for this command line,
> but did not setup env for the system
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/314#issuecomment-149117928>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by tqchen** [comment]
I think we like to have the zip version, so advanced user can put things wherever they like and setup path manually. And a additional setup script in the zip to help user to install things when they donnot know what to do

**Comment by thirdwing** [comment]
@hjk41 Hi, just a small problem. R on Windows is compiled using `sjlj` and you are using `seh`.

Besides, it seems to depend on `VCOMP120.dll`. (I have really little knowledge about Windows, so I don't know what it is.)

Can you give some instructions on how to compile it on Windows using MinGW-w64?

**Comment by tqchen** [comment]
@thirdwing The dll might be VS 2013 runtime. The exception handling mechanism should be fine, as we catch most exceptions in the libmxnet.dll and return a 0 in the C API. So exception would not cross the dll boundary

**Comment by thirdwing** [comment]
After switching to `sjlj`, we don't need to include `libgcc_seh.dll`.

**Comment by hjk41** [comment]
libgcc_seh.dll is the dependency introduced by openblas.

On Tue, Oct 20, 2015 at 6:42 AM, Qiang Kou (KK) <notifications@github.com>
wrote:

> After switching to sjlj, we don't need to include libgcc_seh.dll.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/314#issuecomment-149368054>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by thirdwing** [comment]
So you are using precompiled openblas? It will be better if you can compile it using sjlj. But it doesn't matter, I think.

**Comment by tqchen** [comment]
move to #287
