### ISSUE TITLE
How to free GPU momory of DataIter

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#3140]
I am trying to prefetch data when training. the DataIter  python code is somehow like this:
```python
class DataIter(mx.io.DataIter):
    def __init__(self, names, batch_size):
        super(DataIter, self).__init__()
        self.started = True
        self.q = multiprocessing.Queue(2)
        self.pw = multiprocessing.Process(target=self.write,)
        self.pw.start()

    def write(self):
        while True:
            if not self.started:
                break
            data_batch = DataBatch(data_all, label_all)
            self.q.put(data_batch)

    def __del__(self):
        self.started = False
        self.pw.join()
```
When training, there are two processes on GPU and when I terminate the training process with `Ctrl-C`, only one process is terminated(which occupied more memory). The left process always occupied about 102M memory.

**Comment by piiswrong** [comment]
This is a python signal handling problem. You need to register a signal handler that kill all processes on ctrl-c.
I forgot how to do it exactly but should be easy to google

**Comment by shuokay** [comment]
Problem solved according to your suggests, thanks a lot @piiswrong
