### ISSUE TITLE
[R] should we use the consistent syntax/parameter handling with Python side?

### ISSUE THREAD

**Issue by thirdwing** [dmlc/mxnet#3152]
I think we need to have some discussion on this.

Right now there are some difference in the syntax/data handling/parameter handling between R and python side, which leads to https://github.com/dmlc/mxnet/issues/3097 .

Since we are using the same C API, it is possible to provide consistency between R and python.

I want to hear some opinions on this. @terrytangyuan @maxkazmsft @hoaphumanoid @hetong007

**Comment by hoaphumanoid** [comment]
Could anybody list the differences? I think it would be highly beneficial for those of us learning to use the library

**Comment by predict-r** [comment]
I think it should be consistent, to increase the re-use of documentation.
