### ISSUE TITLE
[R] CSVIter parsing strings in R

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#3162]
I found that CSVIter doesn't take strings. I have `fake.csv`:

``` csv
99,0.9,'good',"This is good"
77,0.7,'bad',"This is bad"
```

If I use CSVIter:

``` R
it <- mx.io.CSVIter(
  data.csv = 'fake.csv',
  data.shape = c(1,4),
  batch.size = 1
)
it$iter.next()
dlist <- it$value()
dlist$data
```

I get:

``` R
, , 1

     [,1] [,2] [,3] [,4]
[1,]   99  0.9    0    0
```

Is there a workaround to parse strings?

This issue is related to #3079

**Comment by ilkarman** [comment]
Potentially stupid idea what if you load it all as a [label](https://github.com/dmlc/mxnet/blob/master/R-package/man/mx.io.CSVIter.Rd)? 

```
\item{label.csv}{string, optional, default='NULL'
Dataset Param: Label csv path. If is NULL, all labels will be returned as 0}
```

Since that seems to accept strings?

**Comment by miguelgfierro** [comment]
Example of a similar solution can be found in https://github.com/dmlc/mxnet/issues/4105
