### ISSUE TITLE
Any convinient way to judge whether it is first layer convolution in backward function of operators?

### ISSUE THREAD

**Issue by xmchen1987** [dmlc/mxnet#3167]
In the backward function of operators, if the layer is first convolution layer of CNN model, there is no need to calculate the gradient of data, as the input data is the input image data. 
So is there any convinient way to judge whether it is first convolution layer or not? Or can you add some information to indicate that there is no need to do backward data, just like caffe do?

**Comment by piiswrong** [comment]
Please refer to the doc on the 'req' argument of backward.
