### ISSUE TITLE
can not run /example/image-classifition/train_cifar10.py

### ISSUE THREAD

**Issue by SevenGong** [dmlc/mxnet#3168]
When I do the command ' python train_cifar10.py', it starts to download cifar.zip , and then shows error:

`raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in concat2: [12:06:24] src/operator/./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[1]: (128,80,13,13). (first input shape: (128,160,14,14))
`

How can I solve this problem?

**Comment by pluskid** [comment]
What arch are you using? Is this due to the change of padding in pooling? @piiswrong @antinucleon

**Comment by antinucleon** [comment]
I think maybe is Downsample Factory.

**Comment by pluskid** [comment]
@antinucleon Could this be fixed now that nnvm is in place.

**Comment by SevenGong** [comment]
@pluskid @antinucleon  it will not shows this error when I use the latest mxnet.

**Comment by pluskid** [comment]
@SevenGong Do you mean it is running correctly now?

**Comment by SevenGong** [comment]
@pluskid  Yes.

**Comment by pluskid** [comment]
Great! Then I'm closing this issue now.

**Comment by SevenGong** [comment]
@pluskid  Thank you!
