### ISSUE TITLE
[R] Reduce memory consumption when training with big matrix

### ISSUE THREAD

**Issue by hoaphumanoid** [dmlc/mxnet#3170]
I have a matrix that occupies 68.4 Gb. When I feed that into the training function the size doubles and I get an out of memory.
```R
devices <- list(mx.gpu(0), mx.gpu(1), mx.gpu(2), mx.gpu(3))
batch_size <- 128*4
model <- mx.model.FeedForward.create(symbol=network, 
                                     X=data_train$X, 
                                     y=data_train$y, 
                                     ctx=devices,
                                     num.round=number_epochs, 
                                     array.batch.size=batch_size,
                                     learning.rate=learning_rate, 
                                     momentum=momentum,  
                                     eval.metric=mx.metric.accuracy, 
                                     wd=0.00001,
                                     epoch.end.callback=mx.callback.save.checkpoint(prefix = "crepe_"),
                                     batch.end.callback=mx.callback.log.train.metric(100)
                                     )
```

Any idea how to reduce the size? Or can I use any other training method to reduce memory consumption?

**Comment by ilkarman** [comment]
I guess you have cast the matrix as ints or bools and the FeedForward function casts it back to floats? Perhaps you can just copy 389-455 from [here](https://github.com/dmlc/mxnet/blob/master/R-package/R/model.R) and adjust appropriately?

**Comment by hoaphumanoid** [comment]
yes, I think that's my next step

**Comment by hoaphumanoid** [comment]
What I did at the end is to do a custom loop and control the memory release. 

Also instead of using integers, that occupies 32 bits, I use [raw ](http://stat.ethz.ch/R-manual/R-patched/library/base/html/raw.html)vectors, that occupies only 8.
