### ISSUE TITLE
How to read flexible data from csv format file

### ISSUE THREAD

**Issue by zhangjiulong** [dmlc/mxnet#3172]
I extracted features from wav files and saved as csv format
each frame has 120-dimensional feature
each line saved  a whole wav's features,  it's size is frame num * 120
that is maybe first line in the csv is 120 * 1000 dimensions
the second line maybe has 120 * 1000 dimensions
and the total size of the features is 52G
I used csv iterator to read the file 
```
    data_train = mx.io.CSVIter(data_csv=train_feats, data_shape=(-1, feat_dim),
                               label_csv=train_labels, label_shape = (-1, 1),
                               batch_size=batch_size)
```
but it reports errors as follows:
```
row.length) == (shape.Size()) The data size in CSV do not match size of shape: specified shape
```
Please give me some suggestion on how should I read the csv file, thx.

**Comment by hoaphumanoid** [comment]
If each line is 120*1000 then you have to set `data_shape=(1,120000)`. Also, if you have labels in the CSV you have to put the same shape. But the label tag is optional. Then the csv will read in every iternation a number of lines equals to `batch_size`.

**Comment by zhangjiulong** [comment]
@hoaphumanoid thx
