### ISSUE TITLE
Where is the documentation now?

### ISSUE THREAD

**Issue by JohanCao** [dmlc/mxnet#3176]
Hi all,

Is there a link that I can look up all the functions? It used to have one but now I can't find it anywhere, seems like that the links is not very stable and always disappear!

**Comment by shuokay** [comment]
You can generate it by `make doc`

**Comment by vchuravy** [comment]
The documentation for python lives under http://mxnet.io/packages/python/index.html

**Comment by JohanCao** [comment]
Thank you!
