### ISSUE TITLE
There's no source in source.jar for scala package 0.1.1  

### ISSUE THREAD

**Issue by Brill-Wang** [dmlc/mxnet#3177]
@javelinjs     Hi, I use the mxnet-full_2.10-linux-x86_64-cpu  artifact but after I download the relative source.jar on maven repo, I didn't see any source code in jar.
Can you check the jar file? Or do I make some mistake?
Because if there's no source file, it is hard for me to debug.
Thanks.

**Comment by javelinjs** [comment]
It is a known issue, due to some problems with the maven settings. We'll fix it later. Thanks for pointing out.
