### ISSUE TITLE
Some caffe op like augmentation  can not do backward  will cause error

### ISSUE THREAD

**Issue by dsqx71** [dmlc/mxnet#3178]
some error 
F0830 18:43:16.734480   558 downsample_layer.cu:135] DownsamplingLayer cannot do backward.

How to deal with this problem?

**Comment by piiswrong** [comment]
Caffe doesn't support it. Modify caffe or use other ops

**Comment by dsqx71** [comment]
I solved this problem by using a empty backward function and mx.sym.Block_Grad
