### ISSUE TITLE
OOM when allocating too fast

### ISSUE THREAD

**Issue by hotpxl** [dmlc/mxnet#3179]
I have a tight loop that allocates and deallocates arrays immediately, and sleeps between iterations. Code shown below.

```python
import mxnet as mx
import time

context = mx.gpu(5)

for i in range(100):
    a = mx.nd.ones((10000, 10000), context)
    time.sleep(1)
```

Each array is around 600 MiB. Program runs smoothly. I can sense that every second allocation uses the space freed by previous deallocation (since arrays gets to ref count 0 and could be freed immediately).

But if I remove that `time.sleep` line and let it run, it throws OOM exception. I guess it's because allocations went before deallocations of previous arrays. So it's allocating instead of reusing every iteration.

I wonder if there is a way to strictly specify the order of allocation and deallocation so it would behave exactly in function call order.

**Comment by tqchen** [comment]
Since there is no dependency between the de-allocation and other allocations.
- Currently later issued operations are allowed to happen before previously issued operations, if there are no dependencies. 
- The order cannot be enforced because there is no dependencies between these, unless we change the programming model, which could restrict the ability to do out of order computation

**Comment by piiswrong** [comment]
We can actually have a variable for each device and make all alloc/dealloc write to that variable.

**Comment by tqchen** [comment]
what @piiswrong suggested is correct, again that will serialize all the imperative operations, as opposed to execute them out of order

**Comment by piiswrong** [comment]
Not necessarily. For example we can have all alloc read from the common variable and dealloc write to it. Then as long as you are not deallocating nothing will be serialized

**Comment by piiswrong** [comment]
Another thing we can do is to sync engine whenever alloc fails. This will wait for all pending dealloc to finish before alloc

**Comment by piiswrong** [comment]
For now the best fix is to call wait_to_read once in a while

**Comment by hotpxl** [comment]
@tqchen I understand that it is still computationally correct to put alloc before dealloc. In fact we issue non-dependent operations out of order to achieve maximum parallelism. What I'm encountering here is a corner case where out of order execution might hurt usability. I think @piiswrong suggestion of calling sync when allocation fails is a good fix for now. It doesn't serialize most of the operations while still providing correct OOM behavior.

**Comment by tqchen** [comment]
closing for now as the alternative discussed, we can open an issue when we want to do a real fix
