### ISSUE TITLE
Doc build broken for Python model API

### ISSUE THREAD

**Issue by leopd** [dmlc/mxnet#3182]
The official docs build at http://mxnet.readthedocs.io/en/latest/packages/python/model.html is missing the API reference.

When I do the build locally following the instructions in docs/README.md using docker, the docs build correctly.  I'm not sure how else to debug this.  Either readthedocs (RTD) is having problems, or there's a discrepency between the docker based build and RTD.

**Comment by piiswrong** [comment]
Doc build on readthedocs has been broken for a while due to time out.
Let's move it to EC2...

**Comment by mli** [comment]
The up-to-date documents are available at http://mxnet.io. it is built on an ec2 machine, see mxnet.io:8080 for the status
