### ISSUE TITLE
“ImportError: cannot import name base” how to solve it?

### ISSUE THREAD

**Issue by blazerygy** [dmlc/mxnet#3204]
when I run “python example/image-classification/train_mnist.py”, An error occurred:
```
Traceback (most recent call last):
  File "train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/yegeyan/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
    import mxnet as mx
  File "/home/yegeyan/mxnet/python/mxnet/__init__.py", line 8, in <module>
    from . import base
ImportError: cannot import name base
```
how to solve it?

**Comment by tornadomeet** [comment]
mxnet is not successfully installed or not in your enviroment. 
just try ```import mxnet``` to verity this.

**Comment by blazerygy** [comment]
@tornadomeet thank you for your help, I sloved it.

**Comment by chandlerz** [comment]
@tornadomeet I got the same issue. How did you solve it?

**Comment by chandlerz** [comment]
@blazerygy I got the same issue. How did you solve it? Thanks!

**Comment by guoguicheng** [comment]
@chandlerz 我也遇到了这问题，好像是因为安装numpy使用的是ubuntu的apt包管理工具安装导致的，我执行apt-get autoremove python-numpy  && pip install -U numpy 就解决了
