### ISSUE TITLE
How do you correctly shape arrays for NDArrayIter in Python?

### ISSUE THREAD

**Issue by JonBoyle87** [dmlc/mxnet#3209]
I'm trying to format my own data for use with NDArrayIter, and I'm currently having a few issues figuring out how to correctly do this.

I've currently loaded in my data into numpy arrays via opencv2 and processed them as I need to before creating the NDArrayIter. I've placed them in a standard python [ ] list for the moment, with each exemplar having the shape (85, 200, 3). I think this is where the real problem is, but I'll continue to describe the rest of what I have done.

I've created a numpy array with all the labels, from 0 to 8. It's shape is (7878,) (the number of exemplars). I realise this is a bit inconsistent at the moment, but I'm still in early testing on how to use the library.

Now, when I create the NDArrayIter, I now get the following error.

> Traceback (most recent call last):
>   File "./mxnet-test.py", line 114, in <module>
>     test_iter = mxnet.io.NDArrayIter(exemplars_test, labels_test, 86)
>   File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/io.py", line 371, in __init__
>     "batch_size need to be smaller than data size."
> AssertionError: batch_size need to be smaller than data size.

In my testing of why this was happening, I realised that mxnet must be thinking that the height of an image is the number of data items (as the height is 85, and errors on 86). So my points/questions are as follows:

- I presume my primary issue here is how I'm providing the exemplars to NDArrayIter. In the code comments of io.py, it says it takes "a list of them", so I presumed that it meant a standard python list of the exemplars; however, it appears that I was wrong. How might I shape this correctly?

- Are the labels in this case specified correctly? Could I just provide them in a standard python list, or would it have to be in some form of numpy/mxnet array?

Thanks.

**Comment by piiswrong** [comment]
data = np.asarray(data)
