### ISSUE TITLE
Does the motherboard need the SLI technology to support multiple gpus in mxnet?

### ISSUE THREAD

**Issue by chenboheng** [dmlc/mxnet#3212]
My motherboard is Intel B85 which doesn't support SLI technology and has two PCIE interfaces, and I have two gtx1080 gpu cards to construct my mxnet system. But I found the utilizations of two gtx1080 are very slow, the speed of two gtx1080 is slower than single gtx1080. Although I increased the batch sizes, the speed of two gpus is still lower than one gpu. How can I solve this problem?

**Comment by piiswrong** [comment]
not sli is for gaming
