### ISSUE TITLE
No synset.txt and preprocess description in pretrained resnet networks

### ISSUE THREAD

**Issue by yourwanghao** [dmlc/mxnet#3226]
I notice that there are two pretrained resnet networks in http://data.dmlc.ml/mxnet/models/imagenet/resnet/. And I would like to use them to try some experitment.

However there is no synset.txt and preprocess description (or function) in the directories as the one in pretrained inception models. Would you please provide the necessary information?

**Comment by tornadomeet** [comment]
@yourwanghao hello, resnet is from https://github.com/tornadomeet/ResNet, and you can found the synset.txt in the readme, ref. https://pan.baidu.com/s/1o8GnUxO#path=%252Fresnet or https://www.dropbox.com/sh/681xbcj0oh1jlez/AAA8B7KvcJJXxfwMbXSblGPMa?dl=0

**Comment by yourwanghao** [comment]
Thank you very much, this issue can be closed.  Regarding the "not the best" usage to predict an unknown image (directly resize to 224x224), I will create another issue to  https://github.com/tornadomeet/ResNet.
