### ISSUE TITLE
usage about the symbol RNN

### ISSUE THREAD

**Issue by ba9els** [dmlc/mxnet#3231]
I'm trying to use the built-in symbol mx.sym.RNN, I encountered a shape issue, any help is appreciated.
Here's a part of my script:
```
data = mx.sym.Variable('data')
gru = mx.sym.RNN(data=data, state_size=1, num_layers=1, mode='gru')
sm = mx.sym.SoftmaxOutput(data=gru, name='softmax')
init = mx.initializer.Xavier()
model = mx.model.FeedForward(ctx=mx.context.gpu(), num_epoch=1, symbol=sm)
train_data = mx.nd.zeros((3, 1, 10))
y = np.zeros((3, 1))
model.fit(X=train_data, y=y)
```
It complains the shape is not consistent, does that mean I have to reshape the label all the time?
> 
> MXNetError: InferShape Error in softmax's label argument
> Corresponding keyword of symbol: softmax_label
> Shape inconsistent, Provided =(3,), inferred shape=(3,1)

**Comment by ba9els** [comment]
okay, I should specify the shape of label

**Comment by ShixiangWan** [comment]
Hi, I meet the same problem and have no idea on how to fix it. Excuse me, how do you "specify the shape of label"?
