### ISSUE TITLE
Performance of multi-machine is worse than one-machine

### ISSUE THREAD

**Issue by llizi** [dmlc/mxnet#3232]
I used example/image-classification/train_cifar10.py on two computers, which were directedly connected by wire. The speed of net is about 100MB/s.
Could anyone tell me how much net bandwidth do I need? Should I use infiniband?

Sincere Thanks

**Comment by tornadomeet** [comment]
the model in train_cifar10.py is two small.  
it's better for multi-machine when you are training large model, like vgg/resnet model on imagenet.

**Comment by winstywang** [comment]
Besides, please try the latest PR https://github.com/dmlc/mxnet/pull/3241
