### ISSUE TITLE
[R] Bottle neck in metrics$update

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#3234]
I've been doing some profiling in the [training ](https://github.com/dmlc/mxnet/blob/master/R-package/R/model.R#L94)function in R. I realised that this line is the most expensive in terms of time:

``` R
      # Update the evaluation metrics
        #FIXME: time bottleneck
        for (i in 1 : ndevice) {
          train.metric2 <- metric$update(slices[[i]]$label, out.preds[[i]], train.metric)
        }
      }
```

The bottleneck is in the [update ](https://github.com/dmlc/mxnet/blob/master/R-package/R/metric.R#L8)function. How could we optimize this code?

**Comment by thirdwing** [comment]
@hoaphumanoid Can you show me a little more profiling results? How slow?

The update is in purely R, which might be a problem.

**Comment by miguelgfierro** [comment]
I haven't seen again the issue. Feel free to open again if it is needed.
