### ISSUE TITLE
Convolution - Converting RGB Image from OpenCV Shape

### ISSUE THREAD

**Issue by JonBoyle87** [dmlc/mxnet#3236]
I'm trying to shape my data correctly to pass to a convolution layer, but I keep getting the following error:

> [14:50:27] src/operator/./convolution-inl.h:370: Check failed: ksize_y <= dshape[2] + 2 * param_.pad[0] && ksize_x <= dshape[3] + 2 * param_.pad[1] kernel size exceed input

The size of the training set is (7878, 256, 256, 3). The images have been loaded in via cv2 and had some operations prior to being added to the training set array.

The convolution layer is as follows:
`conv1 = mx.symbol.Convolution(data=input_data, kernel=(11, 11), stride=(4, 4), num_filter=96)`

Does the convolution layer have a different ordering of dimensions to the cv2 ordering?

**Comment by shuokay** [comment]
I think the data shape should be (count, channel, height, width)

**Comment by JonBoyle87** [comment]
Thanks for the response. For reference, I used numpy's rollaxis as follows:

`ex_img = numpy.rollaxis(ex_img, axis=2, start=0)`

This managed to get the network training!

**Comment by shuokay** [comment]
`rollaxis` is ok, but the more straight forward way is `ex_img.transpose(2, 0, 1)`
