### ISSUE TITLE
pre-built packages windows10 gpu not working properly

### ISSUE THREAD

**Issue by birolkuyumcu** [dmlc/mxnet#3237]
windows binary build 20160531
>>> import mxnet as mx
>>> a = mx.nd.ones((2, 3)) * 2
>>> b = mx.nd.ones((2, 3), mx.gpu()) * 3
>>> c = a.copyto(mx.gpu()) * b
>>> print c.asnumpy()
[[ 0.  0.  0.]
 [ 0.  0.  0.]]

**Comment by auroralinan** [comment]
See #1228, not fix yet.

**Comment by birolkuyumcu** [comment]
Thanks
i solved my problem  by using @yajiedesign prebuilt releases
https://github.com/yajiedesign/mxnet/releases

 download  build windows update 20160909
copy and overwrite offical package binary build 20160531
remove installed  python package mxnet from  .../lib/site-packages/
at consol go to /mxnet/python/ directory
python setup.py install

https://github.com/dmlc/mxnet/issues/2813
https://github.com/yajiedesign/mxnet/releases
problem folved for me 
i think @yajiedesign prebuilt releases merged to main repo
at least give link for alternatieves for prebuild package
