### ISSUE TITLE
Compiling with gcc-5 on mac with OpenMP support, ld error on symbols architecture x86_64

### ISSUE THREAD

**Issue by phunterlau** [dmlc/mxnet#324]
I am trying to use `brew` installed gcc-5 on Mac OS X for adding OpenMP support, but I got ld errors on 
`ld: symbol(s) not found for architecture x86_64` because:

```
g++-5 -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp   -o bin/im2rec tools/im2rec.cc dmlc-core/libdmlc.a -pthread -lm  `pkg-config --libs opencv` -I/usr/local/include -L/usr/local/lib -std=c++11 -I/usr/local/
Undefined symbols for architecture x86_64:
  "cv::imencode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)", referenced from:
      _main in ccP3GYLI.o
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(char const*) const", referenced from:
      dmlc::io::FileSystem::GetInstance(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libdmlc.a(io.o)
......
```

Current `.mk` file from my fork is (with USE_OPENMP=1 and additional LDFLAGS for brew installed headers and libs): <https://github.com/phunterlau/mxnet/blob/master/make/osx_openmp.mk>

The same environment with Apple LLVM clang++ works very fine, but only with single thread. `g++-4.9` didn't work either. I have googled for multiple link environment setup but none worked.

**Comment by tqchen** [comment]
Seems was due to opencv installation problem, guess was because opencv was compiled under LLVM toolchain. I guess LLVM toolchain might be better for us.

You can simply disable openmp, as it is only used for parallel data loading. This only matters when you have two or more TitanX and GPU speed outruns the data loading.

**Comment by phunterlau** [comment]
@tqchen Just re-installed opencv from brew and confirmed:
```
Warning: homebrew/science/opencv dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```
Looks like we should stay with clang LLVM for OSX.

**Comment by mli** [comment]
there are two options:

- use the system installed clang and get opencv from brew/port
- use an installed gcc and then build opencv from source using gcc (takes a few minutes...)

**Comment by phunterlau** [comment]
Looks like the first choice is the most common, and installing OpenCV from brew is much easier, so I will stay for the first choice for making pip installation.
