### ISSUE TITLE
Pkg.test on v 0.6 succeeds, but fails on 0.4.6

### ISSUE THREAD

**Issue by colbec** [dmlc/mxnet#3244]
I have checked out the latest master in both Julia 0.4.6 and latest 0.6. Pkg.test runs correctly in 0.6, but fails in 0.4.6 at:

```
INFO: SymbolicNode::Attributes
INFO: SymbolicNode::Functions
INFO: SymbolicNode::dot
/usr/bin/julia: symbol lookup error: /home/colin/.julia/v0.4/MXNet/deps/usr/lib/libmxnet.so: undefined symbol: cblas_sgemm
=============================================[ ERROR: MXNet ]=============================================

failed process: Process(`/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/colin/.julia/v0.4/MXNet/test/runtests.jl`, ProcessExited(127)) [127]

==========================================================================================================
ERROR: MXNet had test errors
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
```
My LD_LIBRARY_PATH was empty, but changing it to /usr/lib64/blas was ineffective. I can echo the contents of $LD_LIBRARY_PATH in the system shell, but inside Julia in both versions the content of this variable is not visible/defined.
Using:
```
Julia Version 0.6.0-dev.524
Commit 442af7b* (2016-09-07 03:35 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

```

**Comment by vchuravy** [comment]
Thanks for reporting this. The Julia code lives at https://github.com/dmlc/MXNet.jl which is the right place for issues with the Julia binsings.

How have you build MXNet? Did you build it yourself or with `Pkg.build`? What is the result of `Pkg.status("MXNet")`?

**Comment by colbec** [comment]
OK, must have been confused by the upper/lower case and thought I was in the right place. Shall I close the comment and repost over there? I checked out the master with Pkg.checkout followed by Pkg.build. Pkg.status shows the same in both 0.6 and 0.4.6:
```
Pkg.status("MXNet")
 - MXNet                         0.0.8+             master
```

**Comment by vchuravy** [comment]
Let's leave it here for now. Can you send me the `versioninfo()` from 0.4? Did you install julia `v"0.4"` from source or via the package manager? What does `Libdl.dlpath(Libdl.dlopen(Base.libblas_name))` and `Base.blas_vendor()`, return?

**Comment by colbec** [comment]
```
versioninfo()
Julia Version 0.4.6
Commit 2e358ce* (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: liblapack.so.3
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Julia 0.4.6 is from an openSUSE yast repo, and Julia 0.6 is from github.
Again in Julia 0.4.6:
```
julia> Libdl.dlpath(Libdl.dlopen(Base.libblas_name))
"/usr/lib64/liblapack.so.3"

julia> Base.blas_vendor()
:unknown
```

**Comment by vchuravy** [comment]
`Pkg.build("MXNet")` only supports Julia builds with openblas. Your source build fro v"0.6" uses openblas and so that works without a problem. 
This is sadly an upstream problem with openSUSE, so your best bet is to manually build MXNet (http://dmlc.ml/MXNet.jl/latest/user-guide/install/) or use the generic linux binaries from julialang.org.

**Comment by colbec** [comment]
OK I will inform openSUSE that there is an issue with their 0.4.6. Thanks much.

**Comment by tkelman** [comment]
opensuse really shouldn't be building against reference blas, but they might be doing some funny naming with calling openblas libblas to make it switchable with update-alternatives? That mess isn't really worth the hassle IMO, since openBLAS is so much better or more mature than any other open-source option.

**Comment by colbec** [comment]
@tkelman @vchuravy I went to the openSUSE forum and found other people complaining of problems with -lcblas and failed builds. I also investigated the utility 
```
# update-alternatives --config liblapack.so.3 
There are 4 choices for the alternative liblapack.so.3 (providing /usr/lib64/liblapack.so.3).

  Selection    Path                                  Priority   Status
------------------------------------------------------------
* 0            /usr/lib64/lapack/liblapack.so.3       50        auto mode
  1            /usr/lib64/atlas/libsatlas.so.3        20        manual mode
  2            /usr/lib64/atlas/libtatlas.so.3        20        manual mode
  3            /usr/lib64/lapack/liblapack.so.3       50        manual mode
  4            /usr/lib64/libopenblas_pthreads.so.0   20        manual mode
```
But I have no information about what might be more suitable in the circumstances.
Julia 0.6 works well with MXNet so at this point I am quite happy to blaze away up there, even if the version is a bit unstable.

**Comment by tkelman** [comment]
We can move this discussion elsewhere since it's not a mxnet issue, but the opensuse package for julia should declare a hard dependency on openblas, since building with one implementation and switching to another would likely not work with multithreading. atlas and the reference have not very good performance, and mkl isn't open source so you can't get it from a linux distro.

**Comment by colbec** [comment]
I will transfer this discussion to Julia.
