### ISSUE TITLE
NNVM Branch Windows CMake

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#3250]
We are having a progressive refactor on NNVM branch  https://github.com/dmlc/mxnet/tree/nnvm. Currently we have upgraded the make system to build this branch. However, CMake is not yet updated, it would be great if some one can take over and make the cmake system work, in particular for windows

@yajiedesign @sxjscience @hjk41 @Trangle

**Comment by yajiedesign** [comment]
i am pr 
https://github.com/dmlc/nnvm/pull/40
https://github.com/dmlc/mxnet/pull/3255

**Comment by yajiedesign** [comment]
but. i have some problem.
the nnvm lib "LinkLibraryDependencies" and "UseLibraryDependencyInputs" must set to true.
but cmake can't set it. only can manually set in the visual studio.
put this into the install doc. or I try to use a python script to set it.

**Comment by tqchen** [comment]
One way we can solve the problem is that potentially simply not compile nnvm lib but make it part of source code tree in mxnet? So they are compiled as one library

**Comment by tqchen** [comment]
@yajiedesign any updated comments on this?

**Comment by yajiedesign** [comment]
@tqchen yes

**Comment by yajiedesign** [comment]
@tqchen no

**Comment by tqchen** [comment]
You mentioned that some flags need to be set true. One way to resolve that is that we avoid compilation of nnvm library via the cmake subproject but simply include nnvm compilation rules in cmake of mxnet, will that resolve the problem?

**Comment by yajiedesign** [comment]
I used the way you said. directly contains the code into the mxnet code tree.it work fine.

**Comment by tqchen** [comment]
The new updates is now merged in
