### ISSUE TITLE
What does group symbol treat with shared gradients ndarray?

### ISSUE THREAD

**Issue by JeffDong** [dmlc/mxnet#3253]
For example, I have `c = mx.sym.group([a, b])`, where a and b are two output symbols. And they share some internal symbols. What happened when I do a single backprop with exe binding c ? Are two grads from a and b are added for a shared ndarray when `grad_req == 'write'`. Or I should explicitly bind the exe with `grad_req = 'add'` ?

**Comment by piiswrong** [comment]
they are auto aggregated
