### ISSUE TITLE
fatal error: unity／lib／image_util.hpp

### ISSUE THREAD

**Issue by SDASDASA** [dmlc/mxnet#3256]
I have installed mxnet and baidu warp-cdc successfully， then follow the document comment，add "SFRAME_PATH = $（HOME)）／SFrame
MXNET_PLUGINS += plugin／frame／plugin.mk" to config.mk. when I rebuild mxnet by make clean && make -j4 it occurs an error

plugin／frame／iter_sframe.cc:16:36: fatal error: unity／lib／image_util.hpp: No such file or directory
#include <unity/lib/image_util.hpp>

how can I correct this problem？

**Comment by piiswrong** [comment]
why are you adding SFRAME_PATH?
you should add MXNET_PLUGIN

**Comment by SDASDASA** [comment]
yes，you are right。Before i opened and closed the two lines，this time i opened wrong on account of my careless. thanks a lot. i make it correctly now.
