### ISSUE TITLE
Cross-build the scala package to scala 2.11

### ISSUE THREAD

**Issue by ctongfei** [dmlc/mxnet#3268]

**Comment by javelinjs** [comment]
Mind giving more details?

**Comment by ctongfei** [comment]
Currently the scala-package of mxnet only supports Scala 2.10.
The newest version of Scala is 2.11, and 2.12 will be out in a few months. Scala 2.10/11/12 are NOT binary compatible, meaning the jars cannot be shared across Scala versions.
It's good if something can be set in the pom.xml or build.sbt to enable cross-building to Scala 2.11 (and potentially 2.12 in the near future).

**Comment by javelinjs** [comment]
We have switched scala version to 2.11.8 recently. Also you can use `scala-package/dev/change-scala-version.sh` to change the scala version easily.

**Comment by ctongfei** [comment]
Thanks. I suppose that I can build it myself then.
On Maven Central the only version listed there is still 2.10.
It'd be good if mxnet for Scala 2.11 is pushed to Maven Central.

**Comment by javelinjs** [comment]
We're still working on some new features, will push it soon.

**Comment by ctongfei** [comment]
thanks :-)
