### ISSUE TITLE
self defined operator if immigrate to Android platform

### ISSUE THREAD

**Issue by charleslipku** [dmlc/mxnet#3295]
I have successfully compiled the amalgamation for android. But when I train the model on PC, I use the self-defined operator, I am wondering whether the compiled libmxnet_predict.so can support this self-defined operator or not after immigrating to Android platform.

**Comment by tqchen** [comment]
The customized python operator was not supported, but the c++ operator can be supported as long as you include these files in the amalgamation file list here https://github.com/dmlc/mxnet/blob/master/amalgamation/mxnet_predict0.cc#L49
