### ISSUE TITLE
i encounted an issue when building mxnet on ubuntu 16.04 ,and here is the error information

### ISSUE THREAD

**Issue by KeithYin** [dmlc/mxnet#3297]
/home/keithyin/Downloads/mxnet1/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
In file included from /home/keithyin/Downloads/mxnet1/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/mxrtc.h:9,
                 from src/common/mxrtc.cc:7:
/home/keithyin/Downloads/mxnet1/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
In file included from /home/keithyin/Downloads/mxnet1/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:13,
                 from src/resource.cc:9:
/home/keithyin/Downloads/mxnet1/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
In file included from /home/keithyin/Downloads/mxnet1/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/io.h:15,
                 from src/io/iter_mnist.cc:6:
/home/keithyin/Downloads/mxnet1/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
In file included from /home/keithyin/Downloads/mxnet1/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/io.h:15,
                 from src/io/iter_image_recordio.cc:6:
/home/keithyin/Downloads/mxnet1/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
In file included from /home/keithyin/Downloads/mxnet1/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/io.h:15,
                 from src/io/iter_csv.cc:6:
/home/keithyin/Downloads/mxnet1/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
In file included from /home/keithyin/Downloads/mxnet1/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:13,
                 from src/io/image_aug_default.cc:6:
/home/keithyin/Downloads/mxnet1/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
In file included from /home/keithyin/Downloads/mxnet1/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/io.h:15,
                 from src/io/io.cc:3:
/home/keithyin/Downloads/mxnet1/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
   #include <cuda.h>
                    ^
compilation terminated.
Makefile:151: recipe for target 'build/src/ndarray/ndarray_function.o' failed
make: **\* [build/src/ndarray/ndarray_function.o] Error 1
make: **\* Waiting for unfinished jobs....
Makefile:151: recipe for target 'build/src/io/iter_csv.o' failed
make: **\* [build/src/io/iter_csv.o] Error 1
Makefile:151: recipe for target 'build/src/common/mxrtc.o' failed
make: **\* [build/src/common/mxrtc.o] Error 1
Makefile:151: recipe for target 'build/src/io/iter_image_recordio.o' failed
make: **\* [build/src/io/iter_image_recordio.o] Error 1
Makefile:151: recipe for target 'build/src/resource.o' failed
make: **\* [build/src/resource.o] Error 1
Makefile:151: recipe for target 'build/src/io/iter_mnist.o' failed
make: **\* [build/src/io/iter_mnist.o] Error 1
Makefile:151: recipe for target 'build/src/io/image_aug_default.o' failed
make: **\* [build/src/io/image_aug_default.o] Error 1
Makefile:151: recipe for target 'build/src/io/io.o' failed
make: **\* [build/src/io/io.o] Error 1

**Comment by piiswrong** [comment]
Your cuda sdk isn't installed properly. Set USE_CUDA=0 in config.mk

**Comment by KeithYin** [comment]
@piiswrong it can be solved with setting USE_CUDA=0  and gcc-5.4.0. but with gcc-4.9, it didn't work either.

**Comment by hoaphumanoid** [comment]
The system is not finding cuda headers. Apart from setting cuda flag to 1, you have to set the correct path. Check this guide for detailed info: https://blogs.technet.microsoft.com/machinelearning/2016/09/15/building-deep-neural-networks-in-the-cloud-with-azure-gpu-vms-mxnet-and-microsoft-r-server/

**Comment by kleinash** [comment]
Setting CUDA flag to 1 and running this: `sudo ln -s /usr/bin/gcc-4.4 /usr/local/cuda/bin/gcc` may help (http://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version) depending on your gcc version.

**Comment by malhotraa** [comment]
@KeithYin I am facing a similar issue. Can you please specify how you solved this issue? Thanks in advance!

Here is output I get when running make -j12 in the ~/mxnet directory:
```
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./elemwise_unary_op.h:9,
                 from src/operator/tensor/elemwise_binary_broadcast_op_basic.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/elemwise_binary_broadcast_op_basic.o' failed
make: *** [build/src/operator/tensor/elemwise_binary_broadcast_op_basic.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./elemwise_unary_op.h:9,
                 from src/operator/tensor/elemwise_binary_op_extended.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:19,
                 from src/operator/mkl/../operator_common.h:13,
                 from src/operator/mkl/mkl_memory.cc:22:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/elemwise_binary_op_extended.o' failed
make: *** [build/src/operator/tensor/elemwise_binary_op_extended.o] Error 1
Makefile:202: recipe for target 'build/src/operator/mkl/mkl_memory.o' failed
make: *** [build/src/operator/mkl/mkl_memory.o] Error 1
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./elemwise_unary_op.h:9,
                 from src/operator/tensor/elemwise_binary_scalar_op_logic.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:19,
                 from src/operator/tensor/./../operator_common.h:13,
                 from src/operator/tensor/./elemwise_sum.h:13,
                 from src/operator/tensor/elemwise_sum.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./broadcast_reduce_op.h:9,
                 from src/operator/tensor/broadcast_reduce_op_index.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/elemwise_sum.o' failed
make: *** [build/src/operator/tensor/elemwise_sum.o] Error 1
Makefile:202: recipe for target 'build/src/operator/tensor/broadcast_reduce_op_index.o' failed
make: *** [build/src/operator/tensor/broadcast_reduce_op_index.o] Error 1                                                                                                                     [7/1960]
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/base.h:13,
                 from src/operator/tensor/./init_op.h:9,
                 from src/operator/tensor/init_op.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/init_op.o' failed
make: *** [build/src/operator/tensor/init_op.o] Error 1
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./elemwise_unary_op.h:9,
                 from src/operator/tensor/elemwise_binary_broadcast_op_extended.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./elemwise_unary_op.h:9,
                 from src/operator/tensor/elemwise_binary_scalar_op_logic.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/elemwise_binary_broadcast_op_extended.o' failed
make: *** [build/src/operator/tensor/elemwise_binary_broadcast_op_extended.o] Error 1
Makefile:202: recipe for target 'build/src/operator/tensor/elemwise_binary_scalar_op_logic.o' failed
make: *** [build/src/operator/tensor/elemwise_binary_scalar_op_logic.o] Error 1
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./broadcast_reduce_op.h:9,
                 from src/operator/tensor/broadcast_reduce_op_value.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/broadcast_reduce_op_value.o' failed
make: *** [build/src/operator/tensor/broadcast_reduce_op_value.o] Error 1
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./elemwise_unary_op.h:9,
                 from src/operator/tensor/elemwise_binary_op_basic.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/elemwise_binary_op_basic.o' failed
make: *** [build/src/operator/tensor/elemwise_binary_op_basic.o] Error 1
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./elemwise_unary_op.h:9,
                 from src/operator/tensor/elemwise_unary_op.cc:6:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/elemwise_unary_op.o' failed
make: *** [build/src/operator/tensor/elemwise_unary_op.o] Error 1
In file included from /home/plexadmin/mxnet/mshadow/mshadow/tensor.h:16:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator_util.h:24,
                 from src/operator/tensor/./ordering_op-inl.h:9,
                 from src/operator/tensor/ordering_op.cc:7:
/home/plexadmin/mxnet/mshadow/mshadow/./base.h:146:20: fatal error: cuda.h: No such file or directory
compilation terminated.
Makefile:202: recipe for target 'build/src/operator/tensor/ordering_op.o' failed
make: *** [build/src/operator/tensor/ordering_op.o] Error 1
```

**Comment by ilovin** [comment]
similar issue.

**Comment by NamLQ** [comment]
Anyone has solved the issue?
