### ISSUE TITLE
make error when compile with CUDA

### ISSUE THREAD

**Issue by finlay-liu** [dmlc/mxnet#3298]
Hello

when i make with (CUDA = 0), it everything ok.
then make CUDA = 1, some error about make

`/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
`

it seems gcc5 do not match cuda, but i already make caffe with success. what can i do ? . Thx.

my PC Ubuntu: CUDA7.5 cudnn 5.1.3 gcc5.4 gtx960

**Comment by tqchen** [comment]
This is a problem of NVCC not MXNet, please note that CUDA7.5 does not support gcc-5 and you can do CUDA8.0rc which comes with a patch for gcc-5

**Comment by captainpete** [comment]
Try `ADD_CFLAGS = -D_MWAITXINTRIN_H_INCLUDED` in config.mk.
