### ISSUE TITLE
setup.py error

### ISSUE THREAD

**Issue by KeithYin** [dmlc/mxnet#3300]
keithyin@keithyin-PC:~/Downloads/mxnet1/python$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "mxnet/libinfo.py", line 36, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.

here is my error information ,what should i do correct it?

**Comment by tqchen** [comment]
This was because you did not build mxnet, please follow the instruction to build mxnet first before doing installation

**Comment by KeithYin** [comment]
@tqchen  thanks any way,  i solved this issue with using gcc-5.4.0 to build mxnet. gcc-4.9.3 didn't work.

**Comment by kleinash** [comment]
This is still an issue - which I am dealing with this morning. Is there a clear solution somewhere?
