### ISSUE TITLE
Is there any method to save weights after N epoch?(not a issue)

### ISSUE THREAD

**Issue by albertyou2** [dmlc/mxnet#3310]
The size of the weights file for my custom CNN is about 1GB .  So after about 300 epoch the hard disk will be full and the training process will be killed . 
I 'm wondering if  there is a method that could save the weights file after N epoch , not every epoch.
Thanks

**Comment by wushouchuan** [comment]
mx.callback.do_checkpoint(xxx, N epoch)

**Comment by albertyou2** [comment]
@wushouchuan thanks I will try
