### ISSUE TITLE
Moving all language bindings to new NNVM interface

### ISSUE THREAD

**Issue by piiswrong** [dmlc/mxnet#3312]
@pluskid @javelinjs @thirdwing 
NNVM refactor is almost done and CAPI is now stable. Please help move other language bindings to the new CAPI.
The difference is mostly in imperative api. Please read the code in `python/mxnet/_ctypes/ndarray.py` and `python/mxnet/_ctypes/symbol.py` and adapt it to R, Scala and Julia.
Specifically, `_init_ndarray_module` and `_make_ndarray_function` in are changed in `ndarray.py` and `_init_symbol_module` and `_make_atomic_symbol_function` are changed in `symbol.py`
1. You should now use `MXListAllOpNames` to get the `NAMES` of all ops and then use `NNGetOpHandle` to get the corresponding handle (instead of directly listing handle as before). 
2. Use `MXImperativeInvoke` instead of `MXFuncInvoke` to call imperative ops. To support variable number of output, `num_output` and `output_vars` should now be passed by reference. Also returned `NDArrayHandle` can be different from the ones passed in. **So always create new `NDArray` objects from returned handle**.
3. Note that we now support alias for symbol and ndarray funcs. The name returned by mxdescribe is alway is original name, instead of the alias. So you need to register ops under the name returned by mxlist to support alias in frontend

**Comment by pluskid** [comment]
It seems that now NDArray ops and Symbol ops are mixed together. Is it true that all those ops are now transparently call-able with either Symbol or NDArray? There seem to be some specific NDArray ops like `_copyto`, etc. Also the auto gen docs need to be refined, as NDArray and Symbol are mixed.

**Comment by tqchen** [comment]
all symbolic ops are automatically available as ndarray ops, but not vice versa

**Comment by pluskid** [comment]
@tqchen Is there currently an API to query this info?

**Comment by javelinjs** [comment]
do all these special op names start with _ ?

**Comment by sbodenstein** [comment]
@piiswrong: you mention that:

> Also returned NDArrayHandle can be different from the ones passed in. So always create new NDArray objects from returned handle.

However, in the Python wrapper, the passed in output NDArrays are simply [being returned](https://github.com/dmlc/mxnet/blob/3a820bf7526d5c78f418a0ec2b01d4cd9977bbe7/python/mxnet/_ctypes/ndarray.py#L132) after calling `MXImperativeInvoke`. Am I misunderstanding something?
