### ISSUE TITLE
Blocking gradients on a sample by sample basis

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#3313]
Hello! I have a multitask network, but only have labels for a subset of these tasks for each example. Is it possible to block the gradient for the tasks I don't have labels for in mxnet on a sample by sample basis? Thanks!

**Comment by piiswrong** [comment]
See mask in softmax_output

**Comment by jmschrei** [comment]
Thanks for the quick response. I searched the github repo for softmax_output, and don't see mask relating to it at all. I searched for softmax_output and mask and didn't get anything. Can you point me more specifically to what you mean? It's a bit vague.

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_output-inl.h#L32
This only applies to multi_output softmax now, but it shouldn't be too hard to modify it to support single output

**Comment by jmschrei** [comment]
Thanks for the link. I imagine it wouldn't be too hard for someone who is familiar with all of the DMLC code to make the modification, but I have no idea what's going on in that script or how to relate it to the python level wrapper. To be clear, there is no current support for this?

**Comment by jmschrei** [comment]
For people looking at this in the future, you can set `ignore_label=-1` in SoftmaxOutput and `use_ignore=True` and then when that label is passed in it will ignore that sample.
