### ISSUE TITLE
[R] Vote for Memory Layout

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#332]
I just noticed this, and I think we might want to change. Currently python and C++ use row major ordering while Julia/R use column major ordering. In current R package, the behavior is doing col/row order conversion when going from R's native array to internal one, and vise versa. 

In Julia pkg  @pluskid used a another [convention](https://github.com/dmlc/MXNet.jl/blob/master/src/ndarray.jl#L25) Which seems to be more natural. So shape is reversed, while the other things do not change.

I like to call for a vote between the R core devs, @thirdwing @hetong007 . Others are welcomed to participate. Whether we want to make R pkg follow the Julia way. So the memory layout of image is
 (width, height, channel, num), and memory layout of normal input examples (num_feature, num_inst) by default 

Options:
- 1. Do col/row major conversion. So a c++ array (num, channel, height, width) remains (num, channel, height, width) in R
   - This is the current way in R. This keeps arrays consistent, but layout not "native"
- 2. Do not do row/col major conversion a c++ array (num, channel, height, width) becomes  (width, height, channel, num)
    - This is the current way in Mocha.jl
    - This layout might be more natural for R users, as R's images are loaded in this layout normally.

**Comment by tqchen** [comment]
For reference [Mocha.jl](https://github.com/pluskid/Mocha.jl) also used (with, height, channel, num) layout. 

This may also mean for all the shape related parameters, like stride, kernel size, should also follow a (width, height) convention, and we need to do conversion when pass things into the backend.

**Comment by mli** [comment]
+1, reserving the shape seems more nature.

**Comment by tqchen** [comment]
@mli  Your vote is confusing, let me list the options

**Comment by tqchen** [comment]
@mli Plase vote which option you like

**Comment by mli** [comment]
+1 for 2. a typo: reserving -> reversing

**Comment by hetong007** [comment]
I vote for 2 to not confuse other R users.

**Comment by mli** [comment]
i'm not a R user, but i'm thinking in the column major when using matlab. i'll probably switch to julia later, mxnet.jl quite makes sense for me

**Comment by pluskid** [comment]
Though not R dev, I vote for 2. It is more natural for R/Julia (and potentially matlab) users to think in that way. And it cause less confusion when working with language's native Array types. 

There is caveat though: the API needs to be careful when passing parameters back to libmxnet. Currently what MXNet.jl does is to assume all parameters of type `Tuple{N,Int}` should be shape, and it gets reversed before dumping into string (primarily when constructing new `Symbol` or `DataIter`). The assumption is definitely not true but at least up to now seems valid. If we are to adopt this convention for both R and Julia binding, we might need to extend the underlying libmxnet API a bit to at least allow the frontend to know which parameter corresponds to a *shape* parameter that should be reversed.

**Comment by thirdwing** [comment]
As far as I know, very very few people are using R for image processing. I will switch to other tools for images. 

Actually no *traditional* or *natural* way in R for this problem. Keeping consistent with other tools will be a better solution.

**Comment by tqchen** [comment]
Here are some potential problem in doing 2(which we need to address), 
- The json format did not involve shape conversion, this means interpretation json shape should be reverse in native bindings.
- The code for building symbols will not be directly copy-pastable between python and R/julia with non rectangle shapes (this is a less problem)

**Comment by tqchen** [comment]
One remaining question for you guys, when doing simple MLP training, is it natural to use 
features x examples in R/Julia as opposed to examples x features?

**Comment by tqchen** [comment]
Since going column major means we adopt nfeature x nexamples in the input layout. We can still potentially do a conversion manually though.

**Comment by pluskid** [comment]
@tqchen I prefer feature x examples in Julia. This is just a personal preference. I think for matrices, it is not really a problem. But when each data point has higher order dimension, it could get quite confusing if one is not following the native convention in the language. For example, for MNIST batch tensor, shape (28,28,1,100) clearly makes sense in Julia because each data point (28,28,1,1) is a continuous piece of memory.

**Comment by mli** [comment]
if doing doing sgd, most people (should) use the format features x example (in matlab). but i need to say, in most cases, example x feature is the default way...

**Comment by pluskid** [comment]
Also if we want to support HDF5 (supported by Caffe, Torch, Mocha.jl, pylearn2, etc, and with standard libraries to read/write from Matlab,numpy,Julia,etc.), the basic data types in HDF5 are general tensors, the same file when loading from Python and Julia, will reads to "reversed" shape, for the same reason.

**Comment by tqchen** [comment]
It is clear we will go for option 2, (use the default memory layout). 

The question remains whether support example x feature vs feature x example in simple MLP case. I think we are fine as long as we are consistent. Most classifier packages seems still follows example x features because this is what will be loaded from csv file. So maybe we need to do a bit smart conversion for such case.

**Comment by pluskid** [comment]
We could detect which dimension is samples by looking at the labels. But that would fail for some special cases, e.g. when multi-dimension regression and Y has the same number of dimensions as the input. Maybe "a clear documentation and a warning when detected that the user might be supplying the transpose of X" is better than trying to figure out automatically all the situations?

**Comment by tqchen** [comment]
Yes, I agree for a warning solution

**Comment by tqchen** [comment]
Fixed by #333 
For auto detect layout, here is the proposed approach in #339 

Add a parameter array.layout(default to auto) to fit and predict. Auto mode will try to detect layout when input is a matrix. If there is ambiguity(square input matrix, which can be rare), ask user to explicitly specify this parameter.

This can benefit potential data science user who are used to put data into a classifier in row major, as read from csv

**Comment by pluskid** [comment]
I was looking at saving and loading JSON interface today. Since the JSON encoding and decoding is completely handled in the libmxnet backend, it seems there is no need to reverse the shape, and the saved json should be able to load correctly from any language binding. However, this also means that the users are discouraged to manually edit the JSON file unless he knows what he is doing.

**Comment by tqchen** [comment]
Yes, that is what I mean, if user need to implement a visualization of nets in the native side, he need to remember to reverse the shape
