### ISSUE TITLE
error in "Classify Real-World Images with Pre-trained Model"

### ISSUE THREAD

**Issue by puneetjindal** [dmlc/mxnet#3322]
http://mxnet.readthedocs.io/en/latest/packages/r/classifyRealImageWithPretrainedModel.html

After running the code from the above link, I am getting the following error:
[19:43:58] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [19:43:58] d:\chhong\mxnet\src\operator./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (1,320,15,15). (first input shape: (1,576,14,14))
Error: InferShape Error in ch_concat_3c_chconcat: [19:43:58] d:\chhong\mxnet\src\operator./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (1,320,15,15). (first input shape: (1,576,14,14))

**Comment by piiswrong** [comment]
@antinucleon Model not updated?

**Comment by hoaphumanoid** [comment]
Make sure imager library version is > 0.20

**Comment by winstywang** [comment]
It should be the pooling infershape issue. The pretrained model will be updated soon.

**Comment by thirdwing** [comment]
Just another thought: the windows dll might be too old

**Comment by chhamso** [comment]
+1  Identical error as Puneet

**Comment by miguelgfierro** [comment]
Another source of error can come from the mxnet version. When the model has been trained with an old mxnet version, you have to use that version. I had the same error but in the opposite case, I trained a model and then I tried to predict with an older version and I got the error you reported, when I updated mxnet to a recent one, the error went way

**Comment by thirdwing** [comment]
It is just because the prebuilt Windows R package is too old.

I just try the latest version of mxnet and pretrained model. Everything works well.

**Comment by chhamso** [comment]
@thirdwing 
the prebuilt windows R package is too old? what is the recommended solution?
use Linux? Let me know if possible.

**Comment by thirdwing** [comment]
@chhamso I am sorry that I don't have access to any Windows machine now.

You need to considering compiling the mxnet and R-package from the source.

**Comment by thirdwing** [comment]
The Windows pkg has been updated. It works well on Win 10 machine.
