### ISSUE TITLE
(Website) Packages->Scala documentation link broken

### ISSUE THREAD

**Issue by zdwolfe** [dmlc/mxnet#3330]
http://mxnet.io/packages/scala/index.html is empty

**Comment by piiswrong** [comment]
@mli

**Comment by mli** [comment]
we don't have webpages for scala doc yet. one needs to go https://github.com/dmlc/mxnet/tree/master/scala-package directly

**Comment by zdwolfe** [comment]
The Julia doc page simply has a link (http://mxnet.io/packages/julia/index.html). Would it make sense to follow that precedent?

**Comment by zdwolfe** [comment]
This was fixed by @andremoeller in https://github.com/dmlc/mxnet/commit/7812647ef714eedf314750c8a520fa346ae8bb66
