### ISSUE TITLE
[R-package] Minimum Source File

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#3343]
Currently, the R package contains mxnet_generated.R, NAMESPACE and Rd files in man folder. Update of NAMESPACE need to be manually done by first installing a version, then call rcppexport and roxygen.

Sometimes installation can fail when the exported function changes, and no longer exists in the namespace. I would like to automate this process by the follows
-  Remove mxnet_genenrated.R, and Rd files in the man folder
- Have a minimum NAMESPACE file, in R-package, say NAMESPACE.init 
  - This namespace only exports the rcpp export function
- in make rpkg script, first call rcppexport(either by minimum install, or some other way without installation), then roxygen, finally, build the r package.

@thirdwing can you look into this?

**Comment by thirdwing** [comment]
I just finished one paper and will look into this now.

**Comment by tqchen** [comment]
Let us do the changes to NNVM branch after this PR https://github.com/dmlc/mxnet/pull/3334

**Comment by tqchen** [comment]
@thirdwing #3334 is now merged, please see if you can do a followup PR on this

**Comment by thirdwing** [comment]
Fixed in https://github.com/dmlc/mxnet/pull/3421
