### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Jeffery921** [dmlc/mxnet#335]
Hi, I'm now in programing, 

How to Copy make/osx.mk to project root config.mk ?

I copy this [cp make/osx.mk config.mk] to commit line, it shows 'No such file or directory.'

Thanks!

**Comment by tqchen** [comment]
It is here https://github.com/dmlc/mxnet/blob/master/make/osx.mk

**Comment by Jeffery921** [comment]
Thanks,

Now, I'm in "R Package Installation", error shows:

Jeff-2:mxnet urAD_Jeff$ R CMD INSTALL R-package
-bash: R: command not found

How to fix it?

**Comment by tqchen** [comment]
You need to install R if you are using the R package. If you have installed it and it is not find, try to find it in your system add add path/to/R/bin to the PATH env variable
