### ISSUE TITLE
can mxnet add a function for image raw data to ndarray?

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#336]
opencv imdecode return numpy.array data format just like: (width, height, channel(rgb)),
but mxnet's image data load and train from rec just like (channel(gbr), width, height),  
When I code my program to extract features online(inputs are some raw image data, not load from rec), It seem not easy to code, and I don't want to code the data conversion with python, It seems run slowly ;(

**Comment by pluskid** [comment]
If necessary, the numpy.transpose function could be called. It is general enough to permute dimensions of a high order tensor.

**Comment by junranhe** [comment]
thanks
