### ISSUE TITLE
Use symbol.infer_shape return [None, None, None], LSTM example

### ISSUE THREAD

**Issue by guolinke** [dmlc/mxnet#3365]
I am working on benchmark for DNN tools. For fair comparison, I need to check the network shapes among these tools. 

And MXNet perform excellent speed except in RNN ( my benchmark result ), so I want to double check about this.

I searched for the solutions, and it says I should use the symbol.infer_shape(...)

However, when i use it in LSTM examples, it returns [None, None, None].

```
print symbol.infer_shape(data=(args.batch_size, args.seq_len))
```

Here is my source code (clone from mxnet's example):
https://github.com/guolinke/deep-learning-benchmarks/blob/master/mxnet/rnn/lstm_bucketing.py

Thanks!

**Comment by magic282** [comment]
Observed the same "not very good" performance issue for recurrent nets.

**Comment by guolinke** [comment]
Fixed. The reason is the LSTM model don't only contain 'data' input.
