### ISSUE TITLE
Link error when compliling with intel mkl

### ISSUE THREAD

**Issue by JeffDong** [dmlc/mxnet#3371]
Got a link error when compile with mkl on ubuntu 14.04.

`/usr/bin/ld: cannot find -liomp5`

My config.mk file is as follows:
```
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = mkl
endif

USE_INTEL_PATH = /opt/intel
```
I tried `source /opt/intel/bin/compilervars.sh` and adding  `/opt/intel/lib/intel64_lin` (where the file `libiomp5.so `located) to LD_LIBRARY_PATH, but the error still exists.

**Comment by hoaphumanoid** [comment]
You could create a symbolic link to /lib like:
`ln -s /opt/intel/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64_lin/libiomp5.so /lib/libiomp5.so`

**Comment by JeffDong** [comment]
That works! Thank you.
