### ISSUE TITLE
Is it possible to parallize differen layers on different GPUs?

### ISSUE THREAD

**Issue by tangjianpku** [dmlc/mxnet#338]
Hi,
   Is it possible to use mxnet to parallize different layers to different GPUS. For example, the first layer is running on the first GPU, and the second layer on the second GPU.

Jian

**Comment by tqchen** [comment]
Yes, currently you need to do it using the symbolic interface. You can bind different part of graph into different devices, and using executor forward/backward to chain them.  
We should add a path in future to support different devices in the same graph in future. Let us know if you are interested

**Comment by qiaohaijun** [comment]
I think this is a other of model parallel

**Comment by tqchen** [comment]
this is enabled by #690

**Comment by tqchen** [comment]
Though the higher level interface might still need some discussion
