### ISSUE TITLE
Any way to get classifier score before normalization?

### ISSUE THREAD

**Issue by zihaolucky** [dmlc/mxnet#3388]
Hi, everyone.

I trained a k-class softmax classifier with SoftmaxOutupt as output-layer, and handle 'unknown' class by simply using thresholding. But SoftmaxOutput already normalized its log-probability for users in which thresholding is not easy to achieve.

I'm wondering whether I can get origin score before normalization.

**Comment by pluskid** [comment]
You can use the symbol before you compose it with `SoftmaxOutput`

**Comment by zihaolucky** [comment]
@pluskid Thank you! I can create a new model using internal symbols and parameters.
