### ISSUE TITLE
Mask for RNN symbol

### ISSUE THREAD

**Issue by magic282** [dmlc/mxnet#3390]
Hi,

I noticed that mxnet has supported RNN symbol for a while. How to mask the padded zeros?

And I also found this: https://github.com/dmlc/mxnet/pull/3016
what is `element_mask`? Doc says 
`mxnet.symbol.element_mask(*args, **kwargs)
rhs elmentwise mask lhs with broadcast`. 
What does this `elmentwise  mask` mean? Multiply by zero?

**Comment by piiswrong** [comment]
have a look at this https://github.com/dmlc/mxnet/pull/3338
It would be great if you can help review it and make sure it's correct
