### ISSUE TITLE
add symbol name to error message

### ISSUE THREAD

**Issue by yajiedesign** [dmlc/mxnet#3391]
when has some  InferShape or InferType error.
I got the wrong message like
> [15:40:35] g:\deeplearn\mxnet\src\operator\./convolution-inl.h:431: Check failed: (in_type->size()) >= (1)

There is not enough information to tell me which symbol is wrong if I have more than one symbol of the same type.
I think it should be add the name of the symbol in the error message.like
 >[15:40:35] g:\deeplearn\mxnet\src\operator\./convolution-inl.h:431: Check failed: (in_type->size()) >= (1) **with convolution0**

**Comment by piiswrong** [comment]
You can catch the error, append name and re throw in infer_shape_pass I think.

**Comment by winstywang** [comment]
Could you contribute a PR on this? @yajiedesign

**Comment by yajiedesign** [comment]
@winstywang ok pr https://github.com/dmlc/mxnet/pull/3494

**Comment by winstywang** [comment]
Thanks for your work!
