### ISSUE TITLE
No set_gpu_data when installing caffe plugin

### ISSUE THREAD

**Issue by ruotianluo** [dmlc/mxnet#3396]
I tried to install mxnet with caffe. However I got the following errors.

plugin/caffe/caffe_blob.cc:40:14: error: ‘class caffe::Blob<float>’ has no member named ‘set_gpu_data’
     (*blob)->set_gpu_data(data_ptr);
              ^
plugin/caffe/caffe_blob.cc:42:14: error: ‘class caffe::Blob<float>’ has no member named ‘set_gpu_diff’
     (*blob)->set_gpu_diff(data_ptr);

I check the caffe code, and I actually don't find these two functions in Blob class. Are you doing something to fix it?

**Comment by piiswrong** [comment]
please follow the readme carefully. There is a patch that you need to apply to caffe

**Comment by ruotianluo** [comment]
@piiswrong Sorry, I didn't notice there is a separate doc for adding caffe plugin. Thank you for you reference.

**Comment by HrWangChengdu** [comment]
@piiswrong Please check pr list

**Comment by n1kt0** [comment]
hello everybody, the patch doesn't apply any more :/

error: patch failed: include/caffe/blob.hpp:218
error: include/caffe/blob.hpp: patch does not apply

**Comment by zhengxiawu** [comment]
hello everybody, the patch doesn't apply any more :/

error: patch failed: include/caffe/blob.hpp:218
error: include/caffe/blob.hpp: patch does not apply

**Comment by piiswrong** [comment]
@HrWangChengdu Can we get that PR merged into caffe?

**Comment by zhengxiawu** [comment]
here is a branch I fork from caffe and made some change for mxnet , I had test it .
@n1kt0  
https://github.com/zhengxiawu/caffe-for-mxnet

**Comment by MyYaYa** [comment]
@piiswrong Is There any solution for patch applying error? 

I got the same problem with you, @n1kt0 , did you solve it?

**Comment by chowkamlee81** [comment]
dear all, the patch doesn't apply any more :/

error: patch failed: include/caffe/blob.hpp:218
error: include/caffe/blob.hpp: patch does not apply
