### ISSUE TITLE
data.dmlc.ml is down causing the example script (example/image-classification/train_mnist.py) to fail

### ISSUE THREAD

**Issue by anirudh2290** [dmlc/mxnet#3398]

**Comment by mli** [comment]
should be fixed now

**Comment by anirudh2290** [comment]
I am able to download the zip file now but the zip file structure has changed.

I dont think they were inside a mnist directory before.

unzip -l mnist.zip
Archive:  mnist.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  09-29-2016 04:41   mnist/
  7840016  07-21-2000 18:19   mnist/t10k-images-idx3-ubyte
    10008  07-21-2000 18:20   mnist/t10k-labels-idx1-ubyte
 47040016  07-21-2000 18:20   mnist/train-images-idx3-ubyte
    60008  07-21-2000 18:20   mnist/train-labels-idx1-ubyte
---------                     -------
 54950048                     5 files 

This breaks the train_mnist.py script.

**Comment by mli** [comment]
thanks, i'll fix it in a minute

**Comment by mli** [comment]
should be fixed now

**Comment by anirudh2290** [comment]
@mli thank you !
