### ISSUE TITLE
Is the LSTM example out ?

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/mxnet#340]
Hi all,
I wonder if the lstm example is out? also is there C++ code examples? I've realized that most examples are in python : )

**Comment by antinucleon** [comment]
Please check https://github.com/dmlc/mxnet/tree/master/example/rnn

**Comment by Kublai-Jing** [comment]
seems that it only supports fixed seq_len ? And the compute graph has to ben pre-compiled with fixed sequence length. Is there a suggested solution for variable length model ?

**Comment by tqchen** [comment]
One way to deal with that is unroll to maximum length you want to deal with,  do padding on left over so batching is still enabled.

We can probably enable a condition on the internal nodes to stop execution until the maximum length of current batch

**Comment by tqchen** [comment]
Another way is simply compile a executor for one time-step, and use the imperative API to do the unrolling, this might actually be the easier way, and can be achieved in current API

**Comment by Kublai-Jing** [comment]
but in that case, does backprop through time still works ? When we proceed, the gradient will overwrite the gradient for previous step, right?

**Comment by tqchen** [comment]
More specific about previous comment. The problem is when to stop so not waste computation on things that are not needed. What can be done is compile a executor for every time step, say t0, t1, t2, t3.

And use imperative API to chain them up, so the control of stop goes into python side.

**Comment by tqchen** [comment]
We still need a different executor for each time stamp, but use python side to decide when to stop.

**Comment by Kublai-Jing** [comment]
does that  mean we need to compile an executor every time? instead of current solution which compiles once

**Comment by tqchen** [comment]
No, compile executor for each time-stamp say t0, t1, t2, and you can reuse t0, t1, t2 next time, but if you need t3, then compile a new one.

**Comment by tqchen** [comment]
@Kublai-Jing Interested in contribute a improved version?

**Comment by Kublai-Jing** [comment]
yeah~ need some time to understand the whole mxnet though...

**Comment by tqchen** [comment]
Hope the explanation makes sense to you. There are [documents](http://mxnet.readthedocs.org/en/latest/) explaining things, but be sure to ask if we miss something, or even better contribute to the things so others can benefit from the answer.

**Comment by tqchen** [comment]
This approach can also be generalized a bit, for example, unroll an executor every T step where T is a small number that we might not care about. And use imperative way to chain things up

**Comment by Kublai-Jing** [comment]
yes. I might wanna contribute some examples I thought useful for newbie like me.

**Comment by tqchen** [comment]
That is awesome

**Comment by sxjscience** [comment]
Will MXNet support something like the `scan` operator in Theano in the future? It would be really great to have one so that coding RNN will get much easier.

**Comment by Kublai-Jing** [comment]
@tqchen 
I assume that you are meaning to compile a list of LSTM cell : 
LSTM[i] = LSTM for t_i , instead of having one unrolled LSTM with fixed sequence length. This should be more flexible and allow more control from the python side. 

Aside from efficiency, if we use minibatch, what happens if some data already reaches its end of sequence ? If we pad zeros to those data, I believe they will still contribute to the gradient signals, which seems wrong.

**Comment by tqchen** [comment]
Yes,that was what I mean. The padding trick should be ok. As there is already a EOF tag introduced, and we can simply pad future labels to be EOF, and input to be EOF.  The encoder/decoder will catch that EOF follows EOF, and thus no need to depend on previous result, and basically less gradient will be propagated back. This is not perfect solution, but should work

**Comment by Kublai-Jing** [comment]
yeah ! we still get wrong gradient, but let the network learns to that...lol

**Comment by pluskid** [comment]
I'm not sure what would be the standard way of dealing with LSTM. But it seems if along with the labels, we provide a stream of `is_end_of_seq` masks. And multiply `1-is_end_of_seq` (maybe with an index shift) with the `prev_hidden_states`. Then it will allow variable-length sequences and automatically reset state propagation over time at the end of the sequence. A minor issue is if the underlying sequence is longer than the un-rolled seq length of the architecture, back-propagate-over-time will get truncated. But I think this won't be a too big issue if we un-roll for a large enough sequence size.

**Comment by tqchen** [comment]
Yes, This is the correct way I think. A harder problem is have the executor to figure out when to stop computation in a transparent way

**Comment by pluskid** [comment]
If the data provider just put each sequence one after another consecutively then it seems there is no need to stop computation. But this is at the cost of higher rate of sequence getting truncated gradients.

**Comment by philipskokoh** [comment]
@tqchen: I saw about EOF tag mentioned in this thread. Is the EOF symbol implemented? Because the Bucketing Tutorial did not mention much about padding the inputs with the EOF symbol..
