### ISSUE TITLE
use intranet IP to run MXNet on multiple machines with data parallel 

### ISSUE THREAD

**Issue by blazerygy** [dmlc/mxnet#3400]
My machine has two IPs,eth0 uses extranet IP(211.69.198.x) and eth1 uses intranet IP(192.168.0.x), and I want to run MXNet on multiple machines with data parallel using internet IP,
the hosts file is:(use intranet IP)
```
192.168.0.1
192.168.0.2
```
but when I run MXNet，it uses extranet IP，
```
[10:43:21] src/van.cc:65: Bind to role=scheduler, id=1, ip=211.69.198.225, port=9091
[10:43:21] src/van.cc:191: assign rank=9 to node role=worker, ip=211.69.198.228, port=33383
[10:43:21] src/van.cc:191: assign rank=11 to node role=worker, ip=211.69.198.225, port=35058
[10:43:21] src/van.cc:191: assign rank=8 to node role=server, ip=211.69.198.225, port=47632
[10:43:21] src/van.cc:206: the scheduler is connected to 2 workers and 1 servers
```
so how can I use the intranet IP? thx

**Comment by mli** [comment]
add `export DMLC_INTERFACE=eth1` between `launch.py` and your scripts

**Comment by hfutxrg** [comment]
What do you mean "between"? 
I have the same issue. Each of my node has an Ethernet interface eno1 and an Infiniband interface ib0. I want to use ib0, but the launcher always binds to ethernet eno1.

I am using two nodes node001 and node002. The eno1 address of node002 is 10.141.0.2 and its ib0 address is 10.149.0.2. I executed the launch.py directly from node001. The hosts file contains
node001
10.149.0.2

I used the following command:
export DMLC_INTERFACE=ib0 ../../launch.py -H hosts -n 2 --launcher ssh python train_imagenet.py ...

But the log still shows it binds to eno1 address. 

What is the correct way to bind to the correct infiniband interface? Thanks.

**Comment by mli** [comment]
../../launch.py -H hosts -n 2 --launcher ssh  export DMLC_INTERFACE=ib0;
python train_imagenet.py ...

**Comment by mli** [comment]
the idea is that we need to set DMLC_INTERFACE for every running  process.
the previous one only set it for the scheduler process.

**Comment by hfutxrg** [comment]
It is still not working.

I tried the following command:
../../tools/launch.py -H hosts -n 2 --launcher ssh export DMLC_INTERFACE=ib0; python train_imagenet.py --network inception-bn --gpus 0,1,2,3 --batch-size 256 --num-epochs 1 --data-shape 224 --data-dir ../../data/ilsvrc12/ --kv-store dist_async

then it has the following error:
mxnet/dmlc-core/include/dmlc/logging.h:235: [12:26:17] src/postoffice.cc:16: Check notnull: Environment::Get()->find("DMLC_NUM_WORKER")

Then I tried to specify DMLC_NUM_WORKER, but it asked for more environment variables. So I specified all of them:
../../tools/launch.py -H hosts -n 2 --launcher ssh export DMLC_INTERFACE=ib0; export DMLC_NUM_WORKER=2; export DMLC_NUM_SERVER=2; export DMLC_ROLE=worker; python train_imagenet.py --network inception-bn --gpus 0,1,2,3 --batch-size 256 --num-epochs 1 --data-shape 224 --data-dir ../../data/ilsvrc12/ --kv-store dist_async

but again has the following error:
terminate called after throwing an instance of 'std::logic_error'
6 what(): basic_string::_S_construct null not valid
7 ./run.sh: line 18: 36014 Aborted python train_imagenet.py --network inception-bn --gpus 0,1,2,3 --batch-size 256 --num-epochs 1 --data-shape 224 --data -dir ../../data/ilsvrc12/ --kv-store dist_async

The errors are the same no matter I use dist_sync or dist_async.

**Comment by blazerygy** [comment]
I tried
```
../../launch.py -H hosts -n 2 --launcher ssh  export DMLC_INTERFACE=eth1;
python train_imagenet.py ...
```
it failed. the errors are same to yours. @hfutxrg 
and then I imitated the code of parameter ‘num_workers’ to create parameter 'dmlc_interface', and set it to 'eth1', it set DMLC_INTERFACE=eth1 for every running  process and it worked.
(the code is in the file '../../launch.py' and some of files it call)
```
[22:26:27] src/van.cc:69: Bind to role=scheduler, id=1, ip=192.168.0.1, port=9091, is_recovery=0
[22:26:28] src/van.cc:229: assign rank=9 to node role=worker, ip=192.168.0.2, port=52537, is_recovery=0
[22:26:28] src/van.cc:229: assign rank=8 to node role=server, ip=192.168.0.1, port=52183, is_recovery=0
[22:26:28] src/van.cc:229: assign rank=11 to node role=worker, ip=192.168.0.1, port=59643, is_recovery=0
```
thank you for your help. @mli

**Comment by hfutxrg** [comment]
Hi @blazerygy, I am not very familiar with python, could you explain more about which parts in launch.py and other files are chaged and how did you change them? Thanks.

**Comment by hfutxrg** [comment]
Hi @mli, since all of us have these errors, could you help fix this bug?

**Comment by hfutxrg** [comment]
Just let other people know that I have solved this issue in a non-elegant way.
in mxnet/ps-lite/src/van.cc file
I changed the line
if (itf) interface = std::string(itf);
to
interface = std::string("ib0"); // use whatever port you want to use.

Then recompile mxnet and install python library.
It seems the line 
const char*  itf = Environment::Get()->find("DMLC_INTERFACE");
is a bug, because its value is empty although I set the DMLC_INTERFACE environment variable.

@mli, maybe you can fix this bug later.
