### ISSUE TITLE
Multi device training

### ISSUE THREAD

**Issue by hoaphumanoid** [dmlc/mxnet#3406]
I trying to do multi device training in several GPUs. I'm following the example you have [here](http://mxnet.readthedocs.io/en/latest/how_to/multi_devices.html). 

If I try to synchronize the [directory](http://mxnet.readthedocs.io/en/latest/how_to/multi_devices.html#synchronize-directory) and copy the folders.
```bash
cp -r ../../python/mxnet .
cp -r ../../lib/libmxnet.so mxnet
../../tools/launch.py -n 2 -H hosts --sync-dst-dir /tmp/mxnet python train_mnist.py --network lenet --kv-store dist_sync --model-prefix mnist_dist --gpus 0
```
I get:
```bash
2016-09-28 16:21:28,912 INFO rsync /home/hoaphumanoid/installer/mxnet/example/image-classification/ -> 13.65.102.83:/tmp/mxnet
[16:21:29] src/van.cc:69: Bind to role=scheduler, id=1, ip=10.0.0.4, port=9100, is_recovery=0
2016-09-28 16:21:31,058 INFO rsync /home/hoaphumanoid/installer/mxnet/example/image-classification/ -> 40.84.145.237:/tmp/mxnet
```
but it does nothing, however in the hosts the folder /tmp/mxnet is created with all the content of the folder from where I launch the script. How can I debug this? I have the last version of mxnet.

**Comment by mli** [comment]
can other machines access 10.0.0.4 on port 9100. often it is due to the firewall

**Comment by hoaphumanoid** [comment]
They are not in the same network. There are independent machines. Is is possible to work with a configuration like that?

**Comment by hoaphumanoid** [comment]
I solved the problem by using `ssh-copy-id username@remote_host` to add the correct ssh key between the hosts.
