### ISSUE TITLE
Sample speed with and without MKL in GPU VM

### ISSUE THREAD

**Issue by hoaphumanoid** [dmlc/mxnet#3407]
I'm training Imagenet in python with 4 GPUs. In one machine I have installed MKL and in the other one I haven't. The one with MKL has a speed of 200 samples/sec while the one without MKL has 50 samples/sec. 

I don't understand this behavior since I'm computing with GPU. Can anybody explain to me how MKL affects the computation in CPU and GPU?

**Comment by hfutxrg** [comment]
I also want to know the answer. Since the GPU is using cuBLAS library for BLAS operation, I don't know what MKL is used for. We need to do BLAS operations on both CPU and GPU?

**Comment by mli** [comment]
try `--kv-store device` ? when `--kv-store local`, we run the weight update on cpu.

**Comment by hoaphumanoid** [comment]
In the same computer, with MKL, same dataset, same code, when using `--kv-store local` I get around 160 samples/sec, when using `--kv-store device` I get around 140 samples/sec. I'm using 4 GPUs
