### ISSUE TITLE
what's the meaning of the error

### ISSUE THREAD

**Issue by rongrongxiangxin** [dmlc/mxnet#3408]
![screenshot from 2016-09-29 17 32 39](https://cloud.githubusercontent.com/assets/10111386/18948928/b03631b8-866b-11e6-871f-c1908f79a6e3.png)

**Comment by zihaolucky** [comment]
`symbol.list_arguments()` would help you debug.

**Comment by winstywang** [comment]
That means you use a symbol like y = a + b, however the shape of a and b are not equal.
