### ISSUE TITLE
404 not found in downloading mnist.zip in the example

### ISSUE THREAD

**Issue by philipskokoh** [dmlc/mxnet#3410]
The url for `mnist.zip` file is changed. The quick test example in the installation page 
http://mxnet.readthedocs.io/en/latest/how_to/build.html#python-package-installation
can't find the file `http://data.dmlc.ml/mxnet/data/mnist.zip`.

This issue breaks the quick test.

**Comment by mli** [comment]
can you try it again? our previous data server is down last night.

**Comment by philipskokoh** [comment]
It works now! Thanks!
