### ISSUE TITLE
OP request: argmax

### ISSUE THREAD

**Issue by magic282** [dmlc/mxnet#3411]
Hi,

I am implementing [Pointer Networks](https://arxiv.org/abs/1506.03134), it seems that an argmax OP will help a lot.

Thanks.

**Comment by sxjscience** [comment]
@magic282 We can simply do nothing in the backward path of the argmax operator. We can register it as output node.

**Comment by sxjscience** [comment]
backward of these two operators are supported in the latest version. (simply passing back zero). https://github.com/dmlc/mxnet/blob/master/src/operator/tensor/broadcast_reduce_op_index.cc#L10-L24
