### ISSUE TITLE
If the input data is features (not original images), how to train the network?

### ISSUE THREAD

**Issue by chenboheng** [dmlc/mxnet#3426]
mx.io.ImageRecordIter can produce the image batch (like the dimension: (16,3,224,224)) from the data.rec. In my new model, the input data is the features (the dimension of the features is (16,512,30,30)) produced from another network. I want to train a new network from those features? How to introduce the features as the input data of a network

**Comment by piiswrong** [comment]
use mx.io.NDArrayIter
