### ISSUE TITLE
Anyway to avoid the requirement of using CXXABI_1.3.8

### ISSUE THREAD

**Issue by ruotianluo** [dmlc/mxnet#3427]
Hi, I'm trying to install mxnet on our cluster sever. And when I try to import mxnet in python, I got error:

OSError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home-nfs/rluo/rluo/mxnet/python/mxnet/../../lib/libmxnet.so)

I have checked, our libstdc++ does not have CXXABI_1.3.8. However since it's a server, it's relatively hard for me to update the gcc.

Is there anyway to bypass this problem?

**Comment by piiswrong** [comment]
did you compile on the server or did you copy compiled .so to the server?

**Comment by ruotianluo** [comment]
@piiswrong I compiled on the server. The gcc version is 4.9. However the libstdc++ is 19.

**Comment by piiswrong** [comment]
http://stackoverflow.com/questions/23494103/version-cxxabi-1-3-8-not-found-required-by

**Comment by ruotianluo** [comment]
@piiswrong Actually I tried this, but due to some stupid reason, I failed last time. It works now, thank you very much. Sorry for bothering again.

**Comment by msiraj83** [comment]
@ruotianluo  i also face  the same problem.. i follow  @piiswrong  command and found that the gcc version 4.9 found in /usr/lib/x86_64/libstdc++.so.6. So i create soft link from  /usr/local/MATLAB/MATLAB_Production_Server/R2015a/sys/os/glnxa64/libstdc++.so.6 to /usr/lib/x86_64/libstdc++.so.6.0.17....
This solve my problem..
