### ISSUE TITLE
About the docs

### ISSUE THREAD

**Issue by George19890617** [dmlc/mxnet#3431]
I found the docs is much more simplified than old version, why some useful info deleted? for example, there are detail informations for use of each layer, dataiter, and so on. but now, it's gone? why? I think   the old one is much more friendly to freshman, however, I can find the use of detail in source code.

**Comment by piiswrong** [comment]
docs have been moved to mxnet.io

**Comment by pluskid** [comment]
@mli It seems the doc building is failing. No doc for operators is currently listed here: http://mxnet.io/packages/python/symbol.html

**Comment by mli** [comment]
the log at http://mxnet.io:8080/ seems normal. but definitely there is something wrong..

**Comment by mli** [comment]
moved to #3446
