### ISSUE TITLE
OSError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name

### ISSUE THREAD

**Issue by WellyZhang** [dmlc/mxnet#3432]
Hi all,

I followed the installation process on the official web site, but when I tried to import mxnet in Python:

```python
OSError                                   Traceback (most recent call last)
<ipython-input-1-cb88d04c42ec> in <module>()
----> 1 import mxnet as mx

/home/my/mxnet/python/mxnet/__init__.py in <module>()
      5 
      6 from .context import Context, current_context, cpu, gpu
----> 7 from .base import MXNetError
      8 from . import base
      9 from . import ndarray

/home/my/mxnet/python/mxnet/base.py in <module>()
     41 __version__ = libinfo.__version__
     42 # library instance of mxnet
---> 43 _LIB = _load_lib()
     44 
     45 # type definitions

/home/my/mxnet/python/mxnet/base.py in _load_lib()
     33     """Load libary by searching possible path."""
     34     lib_path = libinfo.find_lib_path()
---> 35     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     36     # DMatrix functions
     37     lib.MXGetLastError.restype = ctypes.c_char_p

/home/my/anaconda2/lib/python2.7/ctypes/__init__.pyc in LoadLibrary(self, name)
    441 
    442     def LoadLibrary(self, name):
--> 443         return self._dlltype(name)
    444 
    445 cdll = LibraryLoader(CDLL)

/home/my/anaconda2/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    363 
    364         if handle is None:
--> 365             self._handle = _dlopen(self._name, mode)
    366         else:
    367             self._handle = handle

OSError: /usr/lib/libgdal.so.1: undefined symbol: sqlite3_column_table_name
```

I did this on my laptop without GPU support in Anaconda IPython Console under Ubuntu 15.04.

Any idea to fix this?

**Comment by sxjscience** [comment]
A strange error. You can use `otool -L lib/libmxnet.so` to view the library dependencies.

**Comment by WellyZhang** [comment]
As I find out, libgdal.so.1 is bound with some libs of OpenCV, so I suspect the problem has something to do with the building of OpenCV.

As a workaround, just disable OpenCV binding when compiling MXNet.

Might close the issue, but still confused what goes wrong since I just follow the instructions.

**Comment by ibyte2011** [comment]
I have the same problem.Anyone have idea?

**Comment by WellyZhang** [comment]
You might compile MXNet using libgdal of a certain version while trying to
run it with another. This happened when I was using Anaconda. If you are
also using Anaconda, link Anaconda's local version of libgdal to the one
you used for building MXNet.

On Wed, Apr 5, 2017, 17:24 Byte <notifications@github.com> wrote:

I have the same problem.Anyone have idea?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/dmlc/mxnet/issues/3432#issuecomment-291803170>, or mute
the thread

**Comment by ibyte2011** [comment]
Thanks @WellyZhang !
I Use the method ，enter the conda mxnet enviorment first then 
` make clean;make -j$(nproc) ` 
and
 `cd python`.
Type the commd 
`python setup.py install `.
At last the problem sloved.
Thanks

**Comment by khurramHazen** [comment]
' If you are also using Anaconda, link Anaconda's local version of libgdal to the one you used for building MXNet.'
@WellyZhang I am using Anaocnda and have installed libgdal using 'sudo apt-get install libgdal' as well as using 'conda install gdal' and I have also compiled opencv manually. Can you please explain how to do I link opencv with conda installed libgdal ?

**Comment by WellyZhang** [comment]
@khurramHazen If you build OpenCV and MXNet using system lib but run with Anaconda IPython, you might have this problem. Try to be consistent in building and running, link libs necessary for MXNet in your Anaconda lib folder to system libs, or build the packages using libs in your Anaconda folder. But I definitely recommend the first.

**Comment by cipri-tom** [comment]
@WellyZhang That is good advice ! How would I know which Anaconda libs need to be linked to the system ones ? Is there any shortcut to do so ? Thank you!

**Comment by WellyZhang** [comment]
@cipri-tom Generally, most Anaconda libs should work (some are actually just links to sys libs) and you don't need to worry too much about it. Just link libs in Anaconda to sys libs when Python complains about an error.

**Comment by Kongsea** [comment]
In conda environment, run:
```
make clean

> rm -rf 3rdparty/
> git checkout 3rdparty
> git submodule update --init --recursive

make -j$(nproc)
cd python
python setup.py install
conda install gdal
```
