### ISSUE TITLE
Error running prediction example on Inception-BN

### ISSUE THREAD

**Issue by ernestbofill** [dmlc/mxnet#3433]
I am trying to run the [Use Pretrained Inception-BatchNorm Network][1] in python. The execution throws and error on line: `prob = model.predict(batch)[0]` with the error message:

    MXNetError: InferShape Error in ch_concat_3c_chconcat: [14:35:56] src/operator/./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (1,320,15,15). (first input shape: (1,576,14,14))

I tried downloading the Inception-BN model again to make sure it was up to date but it didn't make a difference. I do suspect the problem could be on line: `model = mx.model.FeedForward.load(prefix, num_round, ctx=mx.gpu(), numpy_batch_size=1)` where I had to change **gpu** for **cpu** since my server is not equiped with a gpu. Nevertheless the error doesn't seem to point on that direction.

Any idea how to fix it? Is using a cpu instead of a gpu a problem other than a lower performance?

Finally here is the complete error information:

    ---------------------------------------------------------------------------
    MXNetError                                Traceback (most recent call last)
    <ipython-input-7-98e51e4226e1> in <module>()
          1 # Get prediction probability of 1000 classes from model
    ----> 2 prob = model.predict(batch)[0]
          3 # Argsort, get prediction index from largest prob to lowest
          4 pred = np.argsort(prob)[::-1]
          5 # Get top1 label
    
    /users/CREATE/olb/mxnet/python/mxnet/model.pyc in predict(self, X, num_batch, return_data, reset)
        589         data_shapes = X.provide_data
        590         data_names = [x[0] for x in data_shapes]
    --> 591         self._init_predictor(data_shapes)
        592         batch_size = X.batch_size
        593         data_arrays = [self._pred_exec.arg_dict[name] for name in data_names]
    
    /users/CREATE/olb/mxnet/python/mxnet/model.pyc in _init_predictor(self, input_shapes)
        520         # for now only use the first device
        521         pred_exec = self.symbol.simple_bind(
    --> 522             self.ctx[0], grad_req='null', **dict(input_shapes))
        523         pred_exec.copy_params_from(self.arg_params, self.aux_params)
        524 
    
    /users/CREATE/olb/mxnet/python/mxnet/symbol.pyc in simple_bind(self, ctx, grad_req, type_dict, **kwargs)
        623         if type_dict is None:
        624             type_dict = {k: mx_real_t for k in self.list_arguments()}
    --> 625         arg_shapes, _, aux_shapes = self.infer_shape(**kwargs)
        626         arg_types, _, aux_types = self.infer_type(**type_dict)
        627         if arg_shapes == None or arg_types == None:
    
    /users/CREATE/olb/mxnet/python/mxnet/symbol.pyc in infer_shape(self, *args, **kwargs)
        410             The order is in the same order as list_auxiliary()
        411         """
    --> 412         return self._infer_shape_impl(False, *args, **kwargs)
        413 
        414     def infer_shape_partial(self, *args, **kwargs):
    
    /users/CREATE/olb/mxnet/python/mxnet/symbol.pyc in _infer_shape_impl(self, partial, *args, **kwargs)
        470             ctypes.byref(aux_shape_ndim),
        471             ctypes.byref(aux_shape_data),
    --> 472             ctypes.byref(complete)))
        473         if complete.value != 0:
        474             arg_shapes = [
    
    /users/CREATE/olb/mxnet/python/mxnet/base.pyc in check_call(ret)
         75     """
         76     if ret != 0:
    ---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
         78 
         79 def c_str(string):
    
    MXNetError: InferShape Error in ch_concat_3c_chconcat: [14:35:56] src/operator/./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (1,320,15,15). (first input shape: (1,576,14,14))

  [1]: https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb
  [2]: https://github.com/dmlc/mxnet

**Comment by winstywang** [comment]
Stay tuned. We have already trained a new Inception-BN model. Will make it public soon.

**Comment by arnocandel** [comment]
I can confirm that the googlnet/inception symbols don't work with the current top of tree.

For example this script https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbol_inception-bn.py

src/operator/./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (32,320,13,13). (first input shape: (32,576,14,14)

**Comment by winstywang** [comment]
@arnocandel @ernestbofill Please check the latest pretrained model.

**Comment by ernestbofill** [comment]
What has been updated?
https://github.com/dmlc/mxnet-model-gallery
It says last commit 8 month ago

**Comment by arnocandel** [comment]
The current symbol generator scripts for Inception/Googlenet family of models are broken. To get a valid graph similar to the latest pretrained bundles, a pad (1,1) needs to be added to the last Pooling layer.

**Comment by arnocandel** [comment]
To answer your question: the backend went through a change that broke backward compatibility.

**Comment by winstywang** [comment]
@ernestbofill Please download the latest pretrained model from data.dmlc.ml/mxnet/models/imagenet/

**Comment by thirdwing** [comment]
@winstywang Can you double check the url(http://data.dmlc.ml/mxnet/models/imagenet)? I can't access it.

**Comment by ernestbofill** [comment]
Hi. I downloaded the new model. But the same example that I initially posted about now crashes at a previous step:

The crashing code is: 
`# Load the pre-trained model
prefix = base_dir + model_prefix
num_round = 126
model = mx.model.FeedForward.load(prefix, num_round, ctx=mx.cpu(), numpy_batch_size=1)`

And the error:
` MXNetError: Failed loading Op conv_1 of type Convolution: Cannot find argument 'cudnn_off', Possible Arguments:
----------------
kernel : Shape(tuple), required
    convolution kernel size: (y, x)
stride : Shape(tuple), optional, default=(1,1)
    convolution stride: (y, x)
dilate : Shape(tuple), optional, default=(1,1)
    convolution dilate: (y, x)
pad : Shape(tuple), optional, default=(0,0)
    pad for convolution: (y, x)
num_filter : int (non-negative), required
    convolution filter(channel) number
num_group : int (non-negative), optional, default=1
    Number of groups partition. This option is not supported by CuDNN, you can use SliceChannel to num_group,apply convolution and concat instead to achieve the same need.
workspace : long (non-negative), optional, default=512
    Tmp workspace for convolution (MB).
no_bias : boolean, optional, default=False
    Whether to disable bias parameter. `

**Comment by winstywang** [comment]
@thirdwing The URL works for me.

**Comment by huanyu-liao** [comment]
@winstywang I have download the latest model, but it still reports that 

MXNetError: InferShape Error in ch_concat_3c_chconcat: [18:35:35] d:\chhong\mxnet\src\operator\./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (1,320,15,15). (first input shape: (1,576,14,14))
