### ISSUE TITLE
mxnetR 0.7 bug?

### ISSUE THREAD

**Issue by rflai** [dmlc/mxnet#3447]
mx.symbol.Convolution instruction from the R documentation indicated that weight and bias parameters can be added.
###### 

mx.symbol.Convolution {mxnet}   R Documentation
Apply convolution to input then add a bias.

Description

Apply convolution to input then add a bias.

Usage

mx.symbol.Convolution(...)
Arguments

data  
Symbol Input data to the ConvolutionOp.
weight  
Symbol Weight matrix.
bias  
Symbol Bias parameter.
kernel  
Shape(tuple), required convolution kernel size: (y, x)
stride  
Shape(tuple), optional, default=(1,1) convolution stride: (y, x)
dilate  
Shape(tuple), optional, default=(1,1) convolution dilate: (y, x)
pad 
Shape(tuple), optional, default=(0,0) pad for convolution: (y, x)
num.filter  
int (non-negative), required convolution filter(channel) number
num.group  
int (non-negative), optional, default=1 Number of groups partition. This option is not supported by CuDNN, you can use SliceChannel to num_group,apply convolution and concat instead to achieve the same need.
workspace  
long (non-negative), optional, default=512 Tmp workspace for convolution (MB).
no.bias 
boolean, optional, default=False Whether to disable bias parameter.
name  
string, optional Name of the resulting symbol.
Value

out The result mx.symbol
###### 

but when add weight and bias in this command, the error pop out.
conv1 <- mx.symbol.Convolution(data = input_data, kernel = c(5, 5), pad = c(2, 2), weight = 0.001, num_filter = 32, name = "conv1")
## Error: Cannot find argument 'weight', Possible Arguments:

kernel : Shape(tuple), required
    convolution kernel size: (y, x)
stride : Shape(tuple), optional, default=(1,1)
    convolution stride: (y, x)
dilate : Shape(tuple), optional, default=(1,1)
    convolution dilate: (y, x)
pad : Shape(tuple), optional, default=(0,0)
    pad for convolution: (y, x)
num_filter : int (non-negative), required
    convolution filter(channel) number
num_group : int (non-negative), optional, default=1
    Number of groups partition. This option is not supported by CuDNN, you can use SliceChannel to num_group,apply convolution and concat instead to achieve the same need.
workspace : long (non-negative), optional, default=512
    Tmp workspace for convolution (MB).
no_bias : boolean, optional, default=False
    Whether to disable bias parameter.

**Comment by starimpact** [comment]
weight and bias should be a mx.sym.Variable.

**Comment by rflai** [comment]
thank you so much, what is the weight and bias arguments for the attached pic ?

Mac Lai

**Comment by starimpact** [comment]
i am not sure what do you mean?

**Comment by rflai** [comment]
so sorry, i send this through email with a pic, but can be uploaded to github. let me try to understand your comments, to add weight parameter into the mx.symbol.Convolution() function, we need use mx.symbol.Variable() function to define the weight, then add into the mx.symbol.Convolution() function, am i right? like the following:
first_weight <- mx.symbol.Variable("0.001"), first_bias <- mx.symbol.Variable("0.002")
conv1 <- mx.symbol.Convolution(data = input_data, weight = first_weight, bias = first_bias, kernel = c(5, 5), pad = c(2, 2), num_filter = 32, name = "conv1")

**Comment by thirdwing** [comment]
@starimpact is correct. `weight` and `bias` are both variables not values.

You should use it like

```
data <- mx.symbol.Variable('data')
w <- mx.symbol.Variable('w')
conv1 <- mx.symbol.Convolution(data=data, kernel=c(5,5), weight = w, num_filter=20)
```

**Comment by rflai** [comment]
so if want define different weights and bias for different convolutional layer, like weight = 0.0001, bias = 0.0002 for first convolutional layer, weight = 0.001, bias = 0.002 for second convolutional layer, how should I write the script to achieve this?


Mac Lai

**Comment by thirdwing** [comment]
The `fixed.param` has been added  in https://github.com/dmlc/mxnet/pull/6922
