### ISSUE TITLE
why mxnet do not have split layer like caffe

### ISSUE THREAD

**Issue by lingyanz** [dmlc/mxnet#3454]
Caffe use InsertSplits to add split layer implicit ， why mxnet do not have it for googlenet
I need to know to accelerate the split proedure

**Comment by starimpact** [comment]
mxnet supports split a layer.

**Comment by lingyanz** [comment]
the question is mxnet hwo to support split a layer, I debug but not found ?

**Comment by zhenlinluo** [comment]
To be more specific, concat backward will call Split explicitly. But in googlenet, even pooling to inception module will require split implicitly because multiple top. Does Mxnet support the implicitly insert split layers? How?

**Comment by piiswrong** [comment]
mxnet doesn't split in forward as it's not needed. In backward gradient from multiple paths are aggregated automatically

**Comment by zhenlinluo** [comment]
Eric, where is the code to trigger what to be called for aggregation in backward? It should not be automatic. If I implemented a MKL elementwise-sum, it will be called. But I don't know how it is being called, actually I want to use another API to do that split bwd, but don't know where to put the code...

**Comment by piiswrong** [comment]
in executor it uses ElementWiseSum for this
