### ISSUE TITLE
Fail to load model in a cpu-only machine 

### ISSUE THREAD

**Issue by ChenKQ** [dmlc/mxnet#3467]
Sorry for disturbing!
I trained a model in a gpu server,where the mxnet is compiled with cuda and cudnn4 and I want to deploy it in a cpu-only machine.I do not know what exactly should I do?Should I change something in the json file?
When I loaded the model directly with this comman 
### ldNet,ldargs,ldaux=mx.model.load_checkpoint(prefix,nepoch) ###
,I met the problem following. What shoul I do?
##Error Promotion##
MXNetError: Failed loading Op conv1_1 of type Convolution: Cannot find argument 'cudnn_off', Possible Arguments:
----------------
kernel : Shape(tuple), required
    convolution kernel size: (y, x) or (d, y, x)
stride : Shape(tuple), optional, default=(1,1)
    convolution stride: (y, x) or (d, y, x)
dilate : Shape(tuple), optional, default=(1,1)
    convolution dilate: (y, x)
pad : Shape(tuple), optional, default=(0,0)
    pad for convolution: (y, x) or (d, y, x)
num_filter : int (non-negative), required
    convolution filter(channel) number
num_group : int (non-negative), optional, default=1
    Number of groups partition. This option is not supported by CuDNN, you can use SliceChannel to num_group,apply convolution and concat instead to achieve the same need.
workspace : long (non-negative), optional, default=1024
    Tmp workspace for convolution (MB).
no_bias : boolean, optional, default=False
    Whether to disable bias parameter.
cudnn_tune : {'fastest', 'limited_workspace', 'off'},optional, default='off'
    Whether to find convolution algo by running performance test.Leads to higher startup time but may give better speed.auto tune is turned off by default.Set environment varialbe MXNET_CUDNN_AUTOTUNE_DEFAULT=1 to turn on by default.

### End Promotion##

**Comment by ChenKQ** [comment]
I found that the answer may be here #1051

**Comment by winstywang** [comment]
Close for now. The device info is stored in params. You could transfer it to cpu and then save it.

**Comment by NuoerSwift** [comment]
please delete the line in josn it can't find,such as  "cudnn_off",and  if  it still has errors,continue to delete the line it cannot find.
