### ISSUE TITLE
Error AttributeError: 'module' object has no attribute 'SpatialTransformer'

### ISSUE THREAD

**Issue by buraksarica** [dmlc/mxnet#3469]
I got the error on title on the second line with python (2.7)
```
data = mx.symbol.Variable('data')
tdata = mx.symbol.SpatialTransformer(data=data, loc=get_loc(data), target_shape = (28,28),transform_type="affine", sampler_type="bilinear")
```

Is it a breaking change?

**Comment by tornadomeet** [comment]
@buraksarica what's your def of get_loc(),  would you provide the minimum code for reproduce your problem?  
or you can go to example/image-classification and run `python -u train_mnist.py --gpu 0 --network lenet-stn` to test the stn operator.

**Comment by buraksarica** [comment]
Moved on another direction. Thanks indeed.
