### ISSUE TITLE
unable to load mxnet in Rstudio using GPU

### ISSUE THREAD

**Issue by mpearmain** [dmlc/mxnet#347]
changed config.mk

\# whether use CUDA during compile
USE_CUDA = 1

\# add the path to CUDA libary to link and compile flag
\# if you have already add them to enviroment variable, leave it as NONE
USE_CUDA_PATH = /usr/local/cuda
\#USE_CUDA_PATH = NONE

everything builds and R-package installs

Compiles and can load via CLI
> library(mxnet)
> 

Within Rstudio fails

> library(mxnet)
Error : .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/mpearmain/R/x86_64-pc-linux-gnu-library/3.2/mxnet/libs/libmxnet.so':
  libcudart.so.7.0: cannot open shared object file: No such file or directory
Error: package or namespace load failed for ‘mxnet’

**Comment by tqchen** [comment]
You want to add the path to /usr/local/cuda to LD_LIBRARY_PATH on your environment variable

**Comment by dselivanov** [comment]
On my ubuntu machine I added following strings to `.profile`:
```sh
export CUDA_HOME=/usr/local/cuda 
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
```
Works for me.

**Comment by Sat9443321** [comment]
I did the same in windows platform. but it returns the same error enable the cuda. Please suggest how to proceed the gpu computing with windows platform.

**Comment by thirdwing** [comment]
@Sat9443321 Can you give more info on  error "enable the cuda"?
