### ISSUE TITLE
/ndarray.h:244: Check failed: (shape_[0]) >= (end) Slice end index out of range

### ISSUE THREAD

**Issue by rayjs** [dmlc/mxnet#3474]
Hi @piiswrong ,
Can you please help me with this.

I have a data iterator that returns the following, self.data and self.label are numpy arrays

`mx.io.DataBatch(data=mx.nd.array(self.data), label=mx.nd.array(self.label), 
                                   pad=0, index=self.batch_index)`
`self.batch_size =`120
`self.data.shape =`(120, 8, 32, 32)
`self.label.shape=`(120, 1)

I am using the FeedForward model implementation.
I am getting the slicing error, can you please help me with this. Thank you.

---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-3-f2ebcff16884> in <module>()
     15          kvstore = kv,
     16          logger  = logger,
---> 17          epoch_end_callback = epoch_end_callback)

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.pyc in fit(self, X, y, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, logger, work_load_list, monitor, eval_batch_end_callback)
    787                             logger=logger, work_load_list=work_load_list, monitor=monitor,
    788                             eval_batch_end_callback=eval_batch_end_callback,
--> 789                             sym_gen=self.sym_gen)
    790 
    791 

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.pyc in _train_multi_device(symbol, ctx, arg_names, param_names, aux_names, arg_params, aux_params, begin_epoch, end_epoch, epoch_size, optimizer, kvstore, update_on_kvstore, train_data, eval_data, eval_metric, epoch_end_callback, batch_end_callback, logger, work_load_list, monitor, eval_batch_end_callback, sym_gen)
    220             do_reset = True
    221             for data_batch in train_data:
--> 222                 executor_manager.load_data_batch(data_batch)
    223 
    224                 if monitor is not None:

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.pyc in load_data_batch(self, data_batch)
    392             self.curr_execgrp = self.execgrp
    393 
--> 394         self.curr_execgrp.load_data_batch(data_batch)
    395 
    396     def forward(self, is_train=False):

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.pyc in load_data_batch(self, data_batch)
    243     def load_data_batch(self, data_batch):
    244         """ load data and labels into arrays """
--> 245         _load_data(data_batch, self.data_arrays)
    246         _load_label(data_batch, self.label_arrays)
    247 

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.pyc in _load_data(batch, targets)
     86 def _load_data(batch, targets):
     87     """Load data into sliced arrays"""
---> 88     _load_general(batch.data, targets)
     89 
     90 def _load_label(batch, targets):

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.pyc in _load_general(data, targets)
     82         else:
     83             for slice_idx, d_dst in d_targets:
---> 84                 d_src[slice_idx].copyto(d_dst)
     85 
     86 def _load_data(batch, targets):

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.pyc in __getitem__(self, in_slice)
    234             raise ValueError('NDArray only support continuous slicing on axis 0')
    235         if in_slice.start is not None or in_slice.stop is not None:
--> 236             return self._slice(in_slice.start, in_slice.stop)
    237         else:
    238             return self

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.pyc in _slice(self, start, stop)
    274         stop = mx_uint(stop) if stop else mx_uint(self.shape[0])
    275         check_call(_LIB.MXNDArraySlice(
--> 276             self.handle, start, stop, ctypes.byref(handle)))
    277         return NDArray(handle=handle, writable=self.writable)
    278 

/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 if sys.version_info[0] < 3:

MXNetError: [22:59:51] include/mxnet/ndarray.h:244: Check failed: (shape_[0]) >= (end) Slice end index out of range

**Comment by rayjs** [comment]
Got it resolved by putting the `mx.nd.array` objects in a `list` in the `next()` method:
`return mx.io.DataBatch(data=[mx.nd.array(self.data)], label=[mx.nd.array(self.label)], 
                                   pad=0, index=self.batch_index)'

The error was being thrown because the `next()` method was returning:
` return mx.io.DataBatch(data=mx.nd.array(self.data), label=mx.nd.array(self.label), 
                                   pad=0, index=self.batch_index)`

**Comment by xplorld** [comment]
thank you!
