### ISSUE TITLE
Is there any easy way to monitor internal output of each layers?

### ISSUE THREAD

**Issue by allankevinrichie** [dmlc/mxnet#3475]
One can easily access weights, biases and gradient of each layer in a DNN through the 'arg_dict' and 'grad_dict' attribute of a executor object, but I can't find anything like 'internal_output_dict' that I can use to access the internal output of each layer. I wander if there exists any easy way to monitor internal output of each layers, just like how I monitor weights and biases of each layers. Thanks!

**Comment by tornadomeet** [comment]
using `mx.mon.Monitor`, ref. https://github.com/dmlc/mxnet/tree/master/example/python-howto

**Comment by allankevinrichie** [comment]
@tornadomeet Thanks! But what if I don't use any high level api like model or module, instead, only use custom training loop?

**Comment by tornadomeet** [comment]
then u should use function `get_internals()`, and bind the symbol by yourself, also do fp/bp and print the internal output value by yourself.

**Comment by piiswrong** [comment]
@allankevinrichie It's easy to use monitor in your own training loop.
```
monitor = Monitor(...)

for i in batch:
   monitor.tic()
   exec.forward()
   exec.backward()
   exec.update()
   monitor.toc_print()
```

**Comment by allankevinrichie** [comment]
@tornadomeet @piiswrong Thanks both of you, your solutions are very helpful ! I will close this issue.

**Comment by miraclewkf** [comment]
Is it the right way to create monitor: monitor = Monitor(...), it doesn't work for me.
