### ISSUE TITLE
Issue when build with CUDNN, CentOS 6.5

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/mxnet#348]
HI thanks for mxnet for great package !
When I am trying to build with CUDNN, I've got the following error when running the mnist example

--------------------------------------------------------------------------------------------------

INFO:root:Start training with [gpu(0)]
[09:38:18] ./dmlc-core/include/dmlc/logging.h:208: [09:38:18] ./mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_NOT_INITIALIZED[
09:38:18] ./dmlc-core/include/dmlc/logging.h:208: [09:38:18] ./mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_NOT_INITIALIZED
terminate called recursively
terminate called after throwing an instance of 'dmlc::Error'
  what():  [09:38:18] ./mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_NOT_INITIALIZED

--------------------------------------------------------------------------------------------------
However, it works with context = CPU.

CentOS 6.5
G++ 4.8.4
CUDA 6.5
CUDNN is 7.0
CUDA enabled 
K40 Testla.

**Comment by fhowen** [comment]
the cudnn need cuda 7.0 at least.
