### ISSUE TITLE
The problems appear at run time!! mxnet/nnvm/include/nnvm/op.h:448: Check failed: p.second != plevel Attribute ... ... 

### ISSUE THREAD

**Issue by wuzhijiexia** [dmlc/mxnet#3514]
Now, when I use new mxnet(nnvm branch), I always run into troubles. These troubles appear at run time, though compiling can work normally. 
For example:
mxnet/nnvm/include/nnvm/op.h:448: Check failed: p.second != plevel Attribute FInferShape of operator argmax is already registered with same plevel=10
mxnet/nnvm/include/nnvm/op.h:448 Check failed: p.second != plevel Attribute FCompute<cpu> of operator softmax_cross_entropy is already registered with same plevel=10

**Comment by aaronzs** [comment]
I have the same issue on [v0.9rc1](https://github.com/dmlc/mxnet/tree/v0.9rc1) branch.
My `libmxnet.so` was built with CUDA8, cuDNN5.1 on Ubuntu16.04.

**Comment by piiswrong** [comment]
Sorry it was a typo.
It should now be fixed.
