### ISSUE TITLE
What happened to old tutorials?

### ISSUE THREAD

**Issue by jimxinbo** [dmlc/mxnet#3524]
E.g. I am looking for how to create rec files from your own dataset. All the old links are missing.

http://mxnet.readthedocs.io/en/latest/system/note_data_loading.html

http://mxnet.readthedocs.io/en/latest/packages/python/io.html#create-dataset-using-recordio

Any help?

**Comment by piiswrong** [comment]
http://mxnet.dmlc.ml/architecture/note_data_loading.html
@sandeep-krishnamurthy Please fix broken link

**Comment by sandeep-krishnamurthy** [comment]
Looking in to it.

**Comment by sandeep-krishnamurthy** [comment]
@jimxinbo We moved all contents from "system" to "architecture" and "package" to "supported_languages". Below links will help to get going. In the meantime I will fix all broken links:

http://mxnet.readthedocs.io/en/latest/supported_languages/python/io.html#create-dataset-using-recordio
http://mxnet.dmlc.ml/architecture/note_data_loading.html

**Comment by jimxinbo** [comment]
@sandeep-krishnamurthy 

Great, thanks.
