### ISSUE TITLE
Dose mxnet has scalar symbol element-wise operation?

### ISSUE THREAD

**Issue by chenboheng** [dmlc/mxnet#3532]
I want to train a scalar paramter from the data.
like this:
data=mx.symbol.Variable('data') # data.shape=(100,10,15,15)
par=mx.symbol.Variable('parm') # par is a scalr
par_broad=mx.symbol.broadcast_to(par,shape=(100,10,15,15))
out=data*par_broad

If the batch size=100,the above code is Ok.
however, if the batch size is not 100. Those code can't work. 
how can I do the element wise multiplication like: out=data*par # data and par are symbol, data is feature map, and par is a scalar symbol.

**Comment by pluskid** [comment]
checkout [broadcast operators](http://mxnet.io/api/python/symbol.html#mxnet.symbol.broadcast_mul)

**Comment by chenboheng** [comment]
@pluskid 
Thanks a lot.
The following bind test code can ran successfully:
data=mx.symbol.Variable('data')
par=mx.symbol.Variable('param')
da=mx.nd.round(20*mx.random.normal(loc=0,scale=1,shape=(2,3,3,3)))
parv=mx.nd.array([[[[3]]]])
print da.asnumpy()
print '-'*20
out=mx.symbol.broadcast_mul(lhs=data,rhs=par)
out_exe=out.bind(ctx=mx.cpu(),args={'data':da,'param':parv})
out_exe.forward()
print out_exe.outputs[0].asnumpy()

However, when I use broadcast_mul to construct my network, an error will happen.
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 744, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 485, in _init_params
    assert(arg_shapes is not None)
AssertionError

I found when mxnet infer the shape of network, arg_shape will be None. So the above error will be happen. I test the following simple code, arg_shape will also be None:

data=mx.symbol.Variable('data')
par=mx.symbol.Variable('param')
out=mx.symbol.broadcast_mul(lhs=data,rhs=par)
print out.list_arguments()
arg_shape,out_shape,aux_shape=out.infer_shape(data=(2,3,3,3))
print arg_shape

['data', 'param']
None

How can I modify the code so that the network can ran successfully when using broadcast_mul. Thank you very much.

**Comment by pluskid** [comment]
You can try this:
```
par=mx.symbol.Variable('param', shape=(1,)) 
```
or 
```
par=mx.symbol.Variable('param', shape=(1,1,1,1))
```

**Comment by chenboheng** [comment]
Thanks a lot. Problem solved.

**Comment by pluskid** [comment]
@tqchen Can you create a HowTo or FAQ label? We could attach to some of the issues, and then periodically we can scan those issues to add useful entries to our doc for common problems.

**Comment by tqchen** [comment]
@pluskid Done
