### ISSUE TITLE
compiling error with the latest git checkout code

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/mxnet#354]
I just checkout the code and issue make -j4 to compile  on my ubuntu machine (14.04).
It gives me the following errors:

g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -c src/ndarray/unary_function.cc -o build/ndarray/unary_function.o
In file included from src/ndarray/./unary_function-inl.h:9:0,
                 from src/ndarray/unary_function.cc:7:
src/ndarray/./../common/tblob_op_registry.h:86:16: error: ‘function’ in namespace ‘std’ does not name a template type
   typedef std::function<void (const std::vector<TBlob> &in,
                ^
src/ndarray/./../common/tblob_op_registry.h:90:3: error: ‘OpType’ does not name a type
   OpType op;
   ^
src/ndarray/./../common/tblob_op_registry.h:96:3: warning: ‘mxnet::ndarray::__make_TBlobOpRegEntry_square__DEVICE__’ defined but not used [-Wunused-variable]
   __make_ ## TBlobOpRegEntry ## _ ## Name ## __ ## DEV ##__ =           \
   ^
src/ndarray/./unary_function-inl.h:33:3: note: in expansion of macro ‘MXNET_REGISTER_TBLOB_FUN’
   MXNET_REGISTER_TBLOB_FUN(Name, DEVICE)            \
   ^
src/ndarray/./unary_function-inl.h:38:1: note: in expansion of macro ‘REGISTER_MSHADOW_UNARY’
 REGISTER_MSHADOW_UNARY(square, op::mshadow_op::square)
 ^
src/ndarray/./../common/tblob_op_registry.h:96:3: warning: ‘mxnet::ndarray::__make_TBlobOpRegEntry_sqrt__DEVICE__’ defined but not used [-Wunused-variable]
   __make_ ## TBlobOpRegEntry ## _ ## Name ## __ ## DEV ##__ =           \
   ^
src/ndarray/./unary_function-inl.h:33:3: note: in expansion of macro ‘MXNET_REGISTER_TBLOB_FUN’
   MXNET_REGISTER_TBLOB_FUN(Name, DEVICE)            \
   ^
src/ndarray/./unary_function-inl.h:41:1: note: in expansion of macro ‘REGISTER_MSHADOW_UNARY’
 REGISTER_MSHADOW_UNARY(sqrt, op::mshadow_op::square_root)
 ^
Makefile:104: recipe for target 'build/ndarray/unary_function.o' failed
make: *** [build/ndarray/unary_function.o] Error 1
make: *** Waiting for unfinished jobs....

Appreciate if someone can fix the above issue

Thanks,

Kaishi

**Comment by antinucleon** [comment]
Please update mshadow, dmlc-core, ps-lite to newest version too.

**Comment by tqchen** [comment]
I think it was due std::function was not included in default namespace. I will push a fix soon.

**Comment by tqchen** [comment]
@kaishijeng This should be fixed, can you check again?

**Comment by kaishijeng** [comment]
TQ,

  It is OK now.

Thanks,
Kaishi
