### ISSUE TITLE
About the implement of LSTM

### ISSUE THREAD

**Issue by whr94621** [dmlc/mxnet#3541]
When I read the example of lstm.py, I am confused that the example build as many LSTMParams as the length of input . Shouldn't  all the LSTM layer share a single set of parameters? Could I only build one LSTMParam and recursively feed if into lstm layer? 
```python
for i in range(num_lstm_layer):
        param_cells.append(LSTMParam(i2h_weight=mx.sym.Variable("l%d_i2h_weight" % i),
                                     i2h_bias=mx.sym.Variable("l%d_i2h_bias" % i),
                                     h2h_weight=mx.sym.Variable("l%d_h2h_weight" % i),
                                     h2h_bias=mx.sym.Variable("l%d_h2h_bias" % i)))
```
That's the part where I am confused.

Thanks for any help ^_^

**Comment by piiswrong** [comment]
num_lstm_layer is the number of stacked lstm layers

**Comment by whr94621** [comment]
@piiswrong 
Okay, my fault to treat it as seq_len, thank you!
