### ISSUE TITLE
Failed running mxnet faster rcnn end to end training example

### ISSUE THREAD

**Issue by tanger830** [dmlc/mxnet#3542]
After convert caffe vgg16 model and link voc data, i run python train_end2end.py and get the following error message:
`INFO:root:########## TRAIN FASTER-RCNN WITH APPROXIMATE JOINT END2END #############
providing maximum shape [('data', (1, 3, 1000, 1000))] [('label', (1, 34596)), ('bbox_target', (1, 36, 62, 62)), ('bbox_inside_weight', (1, 36, 62, 62)), ('bbox_outside_weight', (1, 36, 62, 62)), ('gt_boxes', (1, 500))]
voc_2007_trainval gt roidb loaded from /home/cc/mxnet/example/rcnn/data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
Traceback (most recent call last):
  File "train_end2end.py", line 170, in <module>
    args.work_load_list, args.resume, not args.no_flip, args.factor_step)
  File "train_end2end.py", line 117, in end2end_train
    arg_params=args, aux_params=auxs, begin_epoch=begin_epoch, num_epoch=num_epoch)
  File "/home/cc/mxnet/python/mxnet/module/base_module.py", line 334, in fit
    for_training=True, force_rebind=force_rebind, layout_mapper=layout_mapper)
TypeError: bind() got an unexpected keyword argument 'layout_mapper'
`
does i missed anything?

**Comment by piiswrong** [comment]
@sxjscience

**Comment by piiswrong** [comment]
try `git revert 23bf60cab87ff0e4cf02deccdbc2ca9791d9d821` for now

**Comment by tanger830** [comment]
thanks, after checkout new version, it works!

**Comment by darrylbobo** [comment]
I am still having the same problem even after checkout new version.
