### ISSUE TITLE
the probability of prediction on the same test data based on three different framework

### ISSUE THREAD

**Issue by rongrongxiangxin** [dmlc/mxnet#3559]
only test on the data with label=1. 
1. VGG feature and SVM
![image](https://cloud.githubusercontent.com/assets/10111386/19470590/ab50483c-9552-11e6-8b2a-6fc72bb007b8.png)
2. lasagne framwork with googlenet
![image](https://cloud.githubusercontent.com/assets/10111386/19470649/e5a9c3f0-9552-11e6-88e0-41d70a5daa20.png)
3. mxnet framwork with resnet
![image](https://cloud.githubusercontent.com/assets/10111386/19470456/384489a2-9552-11e6-80a0-f96dd4fc238d.png)

 Why the distribution is so different? Especially, mxnet's prediction results is polarized  badly.
@tqchen @tornadomeet @winstywang @mli @piiswrong @phunterlau

**Comment by thirdwing** [comment]
@rongrongxiangxin I think you need to show your scripts

**Comment by piiswrong** [comment]
The networks are different. So it's natural that the results are different too

**Comment by rongrongxiangxin** [comment]
@piiswrong I have thought someone will say the networks are different. So I tried the googlenet with mxnet, the distribution of prediction results is also polarized badly.

**Comment by tornadomeet** [comment]
what does x-axis and y-axis mean?

**Comment by rongrongxiangxin** [comment]
@tornadomeet  x-axis is the prediction probability of the trained model based on the same test data. y-axis is hist of the test data based on the  probability .

**Comment by tornadomeet** [comment]
i do not understand what's exact mean of this figures.
so you have many samples in your test data, and you use your test data for classification, but only classify the samples which their label=1?

**Comment by rongrongxiangxin** [comment]
@tornadomeet yes, two-class classification. I just use the test data with label=1 as a example. I want to show that the probability distribution is so different for different framework .

**Comment by tornadomeet** [comment]
if i understand the figure right, then i think these figures with mxnet is better than other dl framwork, because the label = 1, and the output probability of class_label =1 should be higher(near 1.0) if the model is good enough, and from your figure with mxnet model, most of samples is classify to label=1 near1.0.  

the different directly comes from the final weight in the model, and  indirect comes from the training hper-parameter.

**Comment by rongrongxiangxin** [comment]
@tornadomeet from the figures, we can not say mxnet is better than others. Because the label=1, though most is near 1.0,  there are also many near 0.0. The desirable result is most near 1.0, others distribute in (0.5,1.0).

**Comment by tornadomeet** [comment]
i do not agree.  if you want to measure, you should use topk result.

**Comment by rongrongxiangxin** [comment]
@tornadomeet just two classes, how to use topk?

**Comment by tornadomeet** [comment]
k=1
