### ISSUE TITLE
broken link to "MXNet R Package Document"

### ISSUE THREAD

**Issue by madpower2000** [dmlc/mxnet#3561]
http://mxnet.readthedocs.io/en/latest/packages/r/index.html
- This page does      not exist yet

**Comment by thirdwing** [comment]
@madpower2000 Sorry for this. It seems someone breaks the link. We will fix it soon.

You can also find the docs in https://github.com/dmlc/mxnet/tree/master/docs/tutorials/r

**Comment by piiswrong** [comment]
@sandeep-krishnamurthy

**Comment by thirdwing** [comment]
This has been fixed.
