### ISSUE TITLE
slowness with new code

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#3568]
I know this is vague question, but I recently pulled the latest code and all of my models runs half as fast or worse now during training with the same code. My last version came from early March. I was wondering if something about training has been changed which could explain why this happened. I'm using convolutional, pooling, batch normalization, and dense layers with ReLU activations. Thanks!

**Comment by tornadomeet** [comment]
multi-gpu or one gpu?

**Comment by jmschrei** [comment]
Both. Multi-gpu will still provide a speedup compared to single GPU though.

**Comment by tornadomeet** [comment]
just try `kv-store='device'` when using multi-gpu

**Comment by feiyulv** [comment]
try set the cudnn_tune=kOff in convolution operator

**Comment by jmschrei** [comment]
Using the two above suggestions sped up my code back to the original amount. Thank you!
