### ISSUE TITLE
Fastest way to evaluate a big amount of data

### ISSUE THREAD

**Issue by hoaphumanoid** [dmlc/mxnet#3575]
I have a pretrained cnn model and I want to evaluate 50000 images. I have two methods for prediction but they take about 1 day to evaluate. I'm wondering if there is a way to do it faster.

Sumary of the code:

```python
batch_size = 144
eval_data = mx.io.ImageRecordIter(
...
    batch_size          = batch_size,
    data_shape          = (3, 224, 224),
)
ctx = mx.cpu()
prefix = 'model-cnn'
epoch = 1
eval_data.reset()
eval_data.next()
eval_batch_x = eval_data.getdata()
print(eval_batch_x.shape) # -> (144, 3, 224, 224)
```
First method with the executor:
```python
symbol, arg_params, aux_params = mx.model.load_checkpoint(prefix, epoch)
arg_params, aux_params = params_update(arg_params, aux_params, ctx=ctx) #update the params and put them in the correct form
exe = symbol.bind(ctx, arg_params ,args_grad=None, grad_req="null", aux_states=aux_params)
exe.forward(data=eval_batch_x, is_train=False)
prob = exe.outputs[0].asnumpy()
```
Time of first method:
```bash
CPU times: user 5min 31s, sys: 15.6 s, total: 5min 47s
Wall time: 4min 29s
```
Second method with FeedForward:
```python
model = mx.model.FeedForward.load(prefix, epoch, ctx=ctx, numpy_batch_size=batch_size)
pred = model.predict(X = eval_batch_x)
```
Time of second method:
```bash
CPU times: user 5min 24s, sys: 28.1 s, total: 5min 52s
Wall time: 4min 41s
```
So it takes around 4 min to evaluate 144 images, so for 50000 images it will take around a day. Is there a faster way?

**Comment by piiswrong** [comment]
use gpu?

**Comment by hoaphumanoid** [comment]
I tried to use `mx.model.FeedForward.load` with `ctx = [mx.gpu(0), mx.gpu(1), mx.gpu(2), mx.gpu(3)]` and `ctx = mx.gpu(0)` but the time is even worse. 

Any idea?

**Comment by hoaphumanoid** [comment]
I added `ctx=mx.gpu(0)` and it was faster. 50000 images would take around 13h. I tried with 4 gpus but I think it only takes one. Thanks!
