### ISSUE TITLE
Symbol slicing with symbolic slice index

### ISSUE THREAD

**Issue by thulas** [dmlc/mxnet#3577]
Is there a way to slice a symbolic input, where the slice index is also symbolic? I am aware of the following method
`mxnet.symbol.slice_axis(*args, **kwargs)`

but this requires the slice index to be an integer. I have a situation where the slice index isn't known a priori.  Theano has this feature where the slice indices can also be symbolic variables. Any existing methods/tricks I can use to do this in mxnet?

Thanks.

**Comment by piiswrong** [comment]
You need to write your own op for this.
Look at src/operators/crop-inl.h for example

**Comment by fedorzh** [comment]
@thulas did you write the op? Would be convenient to have some implementation

**Comment by sxjscience** [comment]
`slice_axis` is supported
