### ISSUE TITLE
Fast(poor)net pretrained model

### ISSUE THREAD

**Issue by flash1293** [dmlc/mxnet#3580]
Hi,

is there the Fast(poor)net from the mxnet.js demo available for download anywhere? I just found this broken link: https://turi.com/products/create/docs/graphlab.mxnet.pretrained_image_model.html

**Comment by shuokay** [comment]
Maybe you can find something useful in the [model zoo](https://github.com/dmlc/mxnet-model-gallery)

**Comment by flash1293** [comment]
It's not listed there.

**Comment by antinucleon** [comment]
I will check my computer to see whether I have a backup this evening.

**Comment by flash1293** [comment]
Nevermind, I managed to extract the original model from the mxnet.js demo (https://github.com/dmlc/mxnet.js/tree/master/model).

Is there a paper or something that explains the rationale behind the network architecture?

**Comment by antinucleon** [comment]
@flash1293 The key idea is removing fully connected layer with global averaging pooling. Otherwise it is a simplified version of AlexNet.

**Comment by flash1293** [comment]
Cool, thank you.

**Comment by Piyush3dB** [comment]
@antinucleon Do you have a fastpoor model trained using recent version of MXNet?  Unfortunately the old saved parameters doesn't seem to work correctly with recent MXNet amalgamation version.  Would you be able to provide the training script if you haven't had the chance to train it recently?  Thanks.
