### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by zhengxiawu** [dmlc/mxnet#3582]
I complie mxnet with cuda sucessfully and installed python mxnet ,after that I import mxnet it raise an undefined symbol problem

> OSError: /home/sherwood/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _ZN5mxnet2op8CreateOpIN7mshadow3gpuEEEPNS_8OperatorENS0_15ROIPoolingParamEi

**Comment by zhengxiawu** [comment]
and the whole error message is 

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sherwood/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _ZN5mxnet2op8CreateOpIN7mshadow3gpuEEEPNS_8OperatorENS0_15ROIPoolingParamEi

**Comment by zhengxiawu** [comment]
I had sucessed after I delete all the blanket in config.mk

**Comment by tfygg** [comment]
I have the same problem, can you tell me more about it? And what does blanket mean?

**Comment by zhengxiawu** [comment]
check your config.mk file carefully and delete the blanket like this |a=b |  to |a=b|
