### ISSUE TITLE
element-wise variable and matrix product

### ISSUE THREAD

**Issue by Zhaoyang-XU** [dmlc/mxnet#3587]
I find there is no operation that supporting  ndarray and variable production, is there any other solution?
`
vae = mx.sym.Variable("vae")

data = mx.sym.SliceChannel(data = vae, num_outputs = 2)
mean = data[0]
stddev = data[1]
label = mx.sym.Variable("label")
epsilon = mx.random.normal(0,1,(batch_size,16,))
stddev2 = mx.sym.sqrt(mx.sym.exp(stddev))
input_data = mean+ stddev2*epsilon
//input_data = mean+ mx.sym.broadcast_mul(stddev2,epsilon)`

**Comment by pluskid** [comment]
You can declare epsilon to be a shape (1,) variable, and generate that random number from your data iter.

**Comment by Zhaoyang-XU** [comment]
@pluskid many thanks. So that mean mxnet has no such kind of operation by now?

**Comment by piiswrong** [comment]
use mx.sym.normal
use can use random in symbol graphs
