### ISSUE TITLE
More elegant way to set specific initial value?

### ISSUE THREAD

**Issue by zhreshold** [dmlc/mxnet#3588]
For many times I have encountered a trivial problem: how to set specific initial value to weights/bias.
I used to ignore this since random initialization is somewhat enough in many situations.

The last time when I trying to implement a simple layer *Scale*, which in brief scales the input by a factor, the initial value of this factor is very important, also it should be learned overtime.  Thus it should be something very similar to weight/bias, stored as input argument. Again, there is no elegant way to initialize this value as in my opinion.

Hack 1(not working for multi-gpu, so this is actually useless):
```
# store the initial value in parameter
# use a variable in auxiliary states
if (is_train) {
  init_status = get aux state value
  if (!init_status) {
    scale = value;
    init_status = true;
  }
}
```
This hack worked very well in single gpu system, however, multi-gpu won't synchronize the value at the first batch, so this hack won't work.

Hack 2 (what I'm using now)
```
# set the name of Scale symbol as xxx_value_xxx
# in initializer, read the value from name, set the initial value according to it
if name.endswith('xxx'):
  try:
    value = parse the value from string
    arr[:] = value
  except:
    self._init_one(name, arr)
```
Dirty but works. However, I don't think this hack is very reliable.

Seems like attribute is very promising, but initializer can only access name.

**Comment by piiswrong** [comment]
Try mx.init.Mixed, it supports pattern matching

**Comment by zhreshold** [comment]
But still through matching string in symbol.name right?

**Comment by piiswrong** [comment]
yes. I'm not entirely happy with this but haven't come up with ideas for backward compatible fix. 
If you have ideas you are welcome to contribute

**Comment by zhreshold** [comment]
Totally understand
