### ISSUE TITLE
some minor errors in the doc "Symbolic Configuration and Execution in Pictures"

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#359]
Hello,

there are some minor erros in the picture of doc [Symbolic Configuration and Execution in Pictures](http://mxnet.readthedocs.org/en/latest/python/symbol_in_pictures.html), because i cannot change the picture directly, so no PR, and just paste it here:  

Configure Neural Nets
---------------------
in=mx.sym.Variable('data'), we can not use symbol "in" here, because "in" is the key word in python.   

Example of Multi-Input Net
--------------------------
in=mx.sym.Variable('data'), "in" should be changed for the same reason.
Calculate Gradient
------------------
ga=mx.empty(1), should be ga=mx.nd.empty(1) 
executor = E.bind(ctx=mx.cpu(), args={'A':a,'B':b,'D':d}, arg_grads={'A':ga}), should change "arg_grads" to "args_grad"
executor.backward(output_grads=ge), should change "output_grads" to "out_grads"  

these may be helpful for newers, ths~

**Comment by tqchen** [comment]
Thanks for the contribution! This has now been corrected
