### ISSUE TITLE
In R prediction is running only on CPU very sow

### ISSUE THREAD

**Issue by boofhead** [dmlc/mxnet#3591]
I have quite a deep net trained on 4 gpus which all works fine.

But when I try and run predict it is very very slow. only 1-cpu is doing anything (out of 16) and the GPUs are doing nothing. Looks like the model is loaded in gpu memory and actually I think it was never unloaded after training. Not sure if that should happen automatically or not.

How do I force the predict to run on GPU?

**Comment by thirdwing** [comment]
`predict(model, X, mx.gpu())`

**Comment by boofhead** [comment]
too easy. Perfect, thanks.
