### ISSUE TITLE
How to directly access Tensor element in a c++ gpu Operator?

### ISSUE THREAD

**Issue by dianyancao** [dmlc/mxnet#3594]
I try to access Tensor element in Forward function in my new c++ gpu Operator,but got violation access error.
Following is code snippet:
```
...
auto scale_data = out_data[CTCLoss_enum::k_scale_data].get<xpu, 4, DType>(s);
auto max_prob = out_data[CTCLoss_enum::k_max_prob].get<xpu, 3, DType>(s);
DType epsilon = 1.0 / std::sqrt(std::numeric_limits<float_t>::max());
...
for (int n = 0; n < scale_data.size(0); ++n)
{
	for (int y = 0; y < scale_data.size(2); ++y)
	{
		for (int x = 0; x < scale_data.size(3); ++x)
		{
			max_prob[n][y][x] = epsilon;// this will cause violation access error
			...
		}
	}
}
```
I am new to cuda programming.In this case,I prefer to access Tensor element directly,shoud I write a new mshadow_op to do this?
The code runs well in cpu mode.

**Comment by piiswrong** [comment]
you can't access gpu memory from cpu. write a kernel instead

**Comment by dianyancao** [comment]
If I write a mshadow_op expression to compute result and assign it to the destination,then will mshadow_op generate cuda kernel for me?
I look at the other mxnet operator but there I don't know how to write a gpu operator kernel in Forward function that both for cpu and gpu. @piiswrong

**Comment by dianyancao** [comment]
Thanks,I just write a <<<1,1>>> kernel to do the computation,and will optimize it later.
