### ISSUE TITLE
Error - cifar10-recipe notebook

### ISSUE THREAD

**Issue by DCYN** [dmlc/mxnet#3595]
When I tried to run cifar10-recipe in iPython, I got below error. Would you please help to solve? Thanks. (Ubuntu 16.04LTS)

MXNetError                                Traceback (most recent call last)
<ipython-input-13-c482f3d68edb> in <module>()
      2           eval_data=test_dataiter,
      3           eval_metric="accuracy",
----> 4           batch_end_callback=mx.callback.Speedometer(batch_size))
      5 
      6 # if we want to save model after every epoch, we can add check_point call back

/home/dc/mxnet/python/mxnet/model.pyc in fit(self, X, y, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, logger, work_load_list, monitor, eval_batch_end_callback)
    742 
    743         arg_names, param_names, aux_names = \
--> 744                 self._init_params(dict(data.provide_data+data.provide_label))
    745 
    746         # setup metric

/home/dc/mxnet/python/mxnet/model.pyc in _init_params(self, input_shapes, overwrite)
    482     def _init_params(self, input_shapes, overwrite=False):
    483         """Initialize weight parameters and auxiliary states"""
--> 484         arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
    485         assert(arg_shapes is not None)
    486 

/home/dc/mxnet/python/mxnet/symbol.pyc in infer_shape(self, *args, **kwargs)
    456             The order is in the same order as list_auxiliary()
    457         """
--> 458         return self._infer_shape_impl(False, *args, **kwargs)
    459 
    460     def infer_shape_partial(self, *args, **kwargs):

/home/dc/mxnet/python/mxnet/symbol.pyc in _infer_shape_impl(self, partial, *args, **kwargs)
    516             ctypes.byref(aux_shape_ndim),
    517             ctypes.byref(aux_shape_data),
--> 518             ctypes.byref(complete)))
    519         if complete.value != 0:
    520             arg_shapes = [

/home/dc/mxnet/python/mxnet/base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 if sys.version_info[0] < 3:

MXNetError: InferShape Error in concat2: [02:25:49] src/operator/./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[1]: (128,80,13,13). (first input shape: (128,160,14,14))

**Comment by tornadomeet** [comment]
@DCYN should be fixed with https://github.com/dmlc/mxnet/pull/3599

**Comment by DCYN** [comment]
Many thanks! It works!
