### ISSUE TITLE
NameError: name 'CNNModel' is not defined

### ISSUE THREAD

**Issue by amitkb3** [dmlc/mxnet#3604]
Hi,
         I am getting an error in the cnn text classification example. I believe the error is how the return statement is defined as i was able to run the setup_cnn_model function step by step. I am new to python so i am not able to catch the issue.

**error:**
---

NameError                                 Traceback (most recent call last)
<ipython-input-79-41ff8a3dd1cd> in <module>()
----> 1 cnn_model = setup_cnn_model(mx.cpu(), batch_size, sentence_size, num_embed, vocab_size, dropout=0.5, with_embedding=False)

<ipython-input-78-d7501af934ba> in setup_cnn_model(ctx, batch_size, sentence_size, num_embed, vocab_size, dropout, initializer, with_embedding)
     36     label = cnn_exec.arg_dict['softmax_label']
     37 
---> 38     return CNNModel(cnn_exec=cnn_exec, symbol=cnn, data=data, label=label, param_blocks=param_blocks)

NameError: name 'CNNModel' is not defined

**code:**

def setup_cnn_model(ctx, batch_size, sentence_size, num_embed, vocab_size,
        dropout=0.5, initializer=mx.initializer.Uniform(0.1), with_embedding=True):

```
cnn = make_text_cnn(sentence_size, num_embed, batch_size=batch_size,
        vocab_size=vocab_size, dropout=dropout, with_embedding=with_embedding)
arg_names = cnn.list_arguments()

input_shapes = {}
if with_embedding:
    input_shapes['data'] = (batch_size, 1, sentence_size, num_embed)
else:
    input_shapes['data'] = (batch_size, sentence_size)

arg_shape, out_shape, aux_shape = cnn.infer_shape(**input_shapes)
arg_arrays = [mx.nd.zeros(s, ctx) for s in arg_shape]
args_grad = {}
for shape, name in zip(arg_shape, arg_names):
    if name in ['softmax_label', 'data']: # input, output
        continue
    args_grad[name] = mx.nd.zeros(shape, ctx)

cnn_exec = cnn.bind(ctx=ctx, args=arg_arrays, args_grad=args_grad, grad_req='add')

param_blocks = []
arg_dict = dict(zip(arg_names, cnn_exec.arg_arrays))
for i, name in enumerate(arg_names):
    if name in ['softmax_label', 'data']: # input, output
        continue
    initializer(name, arg_dict[name])

    param_blocks.append( (i, arg_dict[name], args_grad[name], name) )

out_dict = dict(zip(cnn.list_outputs(), cnn_exec.outputs))

data = cnn_exec.arg_dict['data']
label = cnn_exec.arg_dict['softmax_label']

return CNNModel(cnn_exec=cnn_exec, symbol=cnn, data=data, label=label, param_blocks=param_blocks)
```

cnn_model = setup_cnn_model(mx.cpu(), batch_size, sentence_size, num_embed, vocab_size, dropout=0.5, with_embedding=False)

**Comment by amitkb3** [comment]
@qcl6355 i am getting following error. I am not using pretrainned embeddings.

I appreciate all your help.

Regards,
Amit Bothra

**Comment by qcl6355** [comment]
@amitkb3 `CNNModel` is defined in line 18 `CNNModel = namedtuple("CNNModel", ['cnn_exec', 'symbol', 'data', 'label', 'param_blocks'])`, and also notice that `namedtuple` is import from collections library (line 10).

**Comment by amitkb3** [comment]
@qcl6355 I apologies. This is again an issue of my partially copying and pasting code. Github doesnot allow to download these files. I will have to download entire mxnet to get these files.

I appreciate all your help.
Regards,
Amit Bothra
