### ISSUE TITLE
infer_shape of mx.sym.Concat

### ISSUE THREAD

**Issue by R1ncy** [dmlc/mxnet#3623]
Thanks for your attention.
I am studying the mxnet/example/cnn_text_classification/text_cnn.py example. I want to know some shape information about the Concat Layer. So I add this code after
[https://github.com/dmlc/mxnet/blob/master/example/cnn_text_classification/text_cnn.py#L44](url)

`input_shapes={}`
`input_shapes['data'] = [(100,1,), (100,1,), (100,1,)]`
`arg_shape, out_shape, aux_shape = concat.infer_shape(**input_shapes)`

I think the shape of every max-pooling outputs is (100,1,), but im not sure about that.
but the arg_shape, out_shape and aux_shape it returns are all **None**.
Is the input_shapes wrong? How could i get the shape info of the concat?

Thanks a lot!

**Comment by piiswrong** [comment]
look at concat.list_arguments()
your shape dict needs to correspond to that

**Comment by R1ncy** [comment]
@piiswrong  thank you. 
I use `arg = concat.list_arguments()`, and the value of it is:
<class 'list'>: ['data', 'vocab_embed_weight', 'convolution0_weight', 'convolution0_bias', 'convolution1_weight', 'convolution1_bias', 'convolution2_weight', 'convolution2_bias']

there is no max-pooling or relu params but the concat is after the relu.  how to get the args of infer_shape()?

**Comment by R1ncy** [comment]
i changed model structure, put the concat as the last layer, use this code could get the shape of its output.
`m.cnn_exec.forward()`
`outputs = m.cnn_exec.outputs[0]`
`print(outputs.shape)`

the shape is (500,300,1,1)
but i think this way is too complex. Is there any simple one? 
thanks a lot!
