### ISSUE TITLE
when will mxnet 1.0 release?

### ISSUE THREAD

**Issue by zhangjiulong** [dmlc/mxnet#3636]
when will mxnet 1.0 release?

**Comment by RogerBorras** [comment]
And the R version?? :)

**Comment by piiswrong** [comment]
0.9rc1 has most of the features. You can try the v0.9rc1 branch or the nnvm branch

**Comment by feiyulv** [comment]
It seems the lstm inplace grad addto feature is still missing in the nnvm branch. Is there any agenda to add these features? @piiswrong

**Comment by tqchen** [comment]
@feiyulv It is already been added to NNVM branch

**Comment by feiyulv** [comment]
@tqchen thx
