### ISSUE TITLE
Result given by mxnet.model.FeedForward.predict() in Wrong Size

### ISSUE THREAD

**Issue by II-Matto** [dmlc/mxnet#364]
It seems that when the number of data points is not divisible by the `numpy_batch_size`, `mxnet.model.FeedForward.predict()` will give results in wrong size - either larger or smaller. In order to get the right result, I can only load model by specifying `numpy_batch_size = 1`. Is this a bug?

In addition, when using `mxnet.io.NDArrayIter`, if the `numpy_batch_size` does not equal to that of the loaded model, it will result in errors. It is kind of weird that one has to specify a "batch size" when loading a model or creating a data iter and the two sizes have to be the same.

**Comment by tqchen** [comment]
Hmm, this seems to be not the right behavior. I guess it was a bug in the arrayiter. 

Thanks for the catch. Can you check if you change https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py#L192 to ```self.current_batch == self.batch_num``` instead, the result will become correct. If so, please submit a PR :)

**Comment by II-Matto** [comment]
@tqchen Line 192 is correct and shouldn't be changed. The problem is line 160 https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py#L160. The correct padding size is `self.num_pad = batch_size - data.shape[0] % batch_size`. This should be clear with very simple calculation :)

Besides, the `if` condition may not be necessary, since `batch_size - data.shape[0]` equals to `batch_size - data.shape[0] % batch_size` when `data.shape[0] <= batch_size`.

If the above is agreed, I will submit a PR then.

**Comment by tqchen** [comment]
Yes you are right! Please submit a PR on this. Thanks!

**Comment by II-Matto** [comment]
I am so happy finding the following useful links:

1. [How do you update a GitHub repo fork in the web interface?](http://webapps.stackexchange.com/questions/28998/how-do-you-update-a-github-repo-fork-in-the-web-interface)
2. [Development workflow with Git: Fork, Branching, Commits, and Pull Request](https://github.com/sevntu-checkstyle/sevntu.checkstyle/wiki/Development-workflow-with-Git:-Fork,-Branching,-Commits,-and-Pull-Request)
3. [Create a new branch with git and manage branches](https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches)

I am accumulating experiences of contributing in Github. ^_^

I will try to update contribute-to-mxnet steps some time later.

**Comment by tqchen** [comment]
That is great. Thanks for the contribution. I am closing this due to #372

**Comment by II-Matto** [comment]
I am more than pleased to be able to make some contributions.

Sure, I was waiting for you to close this issue :-)
