### ISSUE TITLE
import mxnet error with caffe plugin in Pycharm

### ISSUE THREAD

**Issue by fungtion** [dmlc/mxnet#3643]
I encountered the same problem with #3108 ,and I fixed it as @HrWangChengdu , it's ok in command line, but when I import mxnet in Pycharm, it reported the same error: **OSError: libcaffe.so.1.0.0-rc3: cannot open shared object file: No such file or directory**, Can anyone help me?

**Comment by HrWangChengdu** [comment]
It's the same issue as https://github.com/dmlc/mxnet/issues/3108.
Please check https://github.com/dmlc/mxnet/blob/master/make/config.mk#L131 to add caffe/build/lib to LD_LIBRARY_PATH in ~/.bashrc (if OS is linux) or ~/.bash_profile (if MAC OS X).
Then run "source ~/.bashrc" in terminal, problem should be solved.

**Comment by fungtion** [comment]
@HrWangChengdu import mxnet in command line can be fixed, but Pycharm not

**Comment by HrWangChengdu** [comment]
This link might help http://stackoverflow.com/questions/33812902/pycharm-cannot-find-library

**Comment by fungtion** [comment]
Thank you, It fixes the problem, I followed the solution 2,  Run->Edit Configurations->Defaults->Python, add  LD_LIBRARY_PATH to Environment variables.
