### ISSUE TITLE
generate train.lst from VOCdevkit in example/fcn-xs

### ISSUE THREAD

**Issue by animebing** [dmlc/mxnet#3653]
i download the VOC2012 from http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar, when i extract the tar file, i don't find the *.lst file. because i am a greenhand in segmentation, i don't know how to generate these lst file, i would really appreciate it if there is anyone who can tell me how to make it, thanks

**Comment by tornadomeet** [comment]
from https://github.com/dmlc/mxnet/tree/master/example/fcn-xs#how-to-train-fcn-xs-in-mxnet we can go to https://pan.baidu.com/s/1bgz4PC#list/path=%2Ffcn-xs

**Comment by animebing** [comment]
@tornadomeet I find it in that page, but it seems to be slow to download from Baidu Yun, so i download the original data from http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar first, which is much faster than Baidu Yun. but the situation now is that i have to generate the .lst file on my own

**Comment by tornadomeet** [comment]
@animebing  i see. i just put the list file in https://pan.baidu.com/s/1bgz4PC#list/path=%2Ffcn-xs, it's only 160kb, so you can download.

**Comment by animebing** [comment]
@tornadomeet Thank you very much, it helps me greatly

**Comment by tornadomeet** [comment]
@animebing be careful with newest mxnet, https://github.com/dmlc/mxnet/pull/3654
