### ISSUE TITLE
Logical errors in CNN for Text Classification example

### ISSUE THREAD

**Issue by amitkb3** [dmlc/mxnet#3670]
Hi,
      I am new to Github. Please provide me a way to reach the author of the [CNN for text classification example](https://github.com/dmlc/mxnet/tree/master/example/cnn_text_classification)   as i have found logical issued with the code:

1. The [build_vocab](https://github.com/dmlc/mxnet/blob/master/example/cnn_text_classification/data_helpers.py) function splits the sentences into characters rather than words

I have the suggested code change. I would like to know how i can offer the code.

I appreciate the author in providing the example. Its been really helpful in learning about cnn.

Regards,
Amit

**Comment by piiswrong** [comment]
@qcl6355

**Comment by amitkb3** [comment]
sorry i am really new to this system. How would i use @qcl6355 to communicate with the author.

I appreciate your hand holding.

Regards,
Amit

**Comment by qcl6355** [comment]
@amitkb3 The code assume training and testing file were segmented. line 41 in the `data_helpers.py` we use space as separator. In line 122 we use `build_vocab` to prepare vocabulary, notice that variable `sentences_padded ` is a list of words.

**Comment by amitkb3** [comment]
@qcl6355 you are right. When i copied data helper.py manually i omitted line 41. I have spend 2 weeks trying to modify other functions because of this mistake. 

I appreciate your efforts in  providing an example to use cnn for text classification. Thank you.
