### ISSUE TITLE
How to point mshadow to the latest commit?

### ISSUE THREAD

**Issue by zhenlinluo** [dmlc/mxnet#3676]
@piiswrong , I noticed that the mshadow still point to older commit. How to point to the latest commit?

**Comment by shuokay** [comment]
`git submodule update`

**Comment by sxjscience** [comment]
```
cd mshadow
git checkout master
git pull
cd ..
git add mshadow
git commit
```

**Comment by zhenlinluo** [comment]
thanks, it point to the right commit now. Someone did that. :)
