### ISSUE TITLE
R package core dumped

### ISSUE THREAD

**Issue by szilard** [dmlc/mxnet#3677]
After training some simple net on MNIST I get this when I quit R/when the script finishes:
```
terminate called without an active exception
Aborted (core dumped)
```

Quick google shows what the issue might be: http://stackoverflow.com/questions/7381757/c-terminate-called-without-an-active-exception

The code I was running is here:
https://github.com/szilard/benchm-dl/blob/master/cnn-mnist/2-mxnet.R
and the output here:
https://github.com/szilard/benchm-dl/blob/master/cnn-mnist/2a-mxnet-run.txt
I was running on EC2 P2 (Tesla K80), software versions here:
https://github.com/szilard/benchm-dl/blob/master/versions.txt

**Comment by thirdwing** [comment]
I saw an error in libdc1394 from https://github.com/szilard/benchm-dl/blob/master/cnn-mnist/2a-mxnet-run.txt#L88

This is an opencv error, can you try the solution in http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394 and rerun the script?

**Comment by szilard** [comment]
`sudo ln /dev/null /dev/raw1394` fixed the libdc1394 warning, but the above error still the same. I'm trying to see if I can make the error go away if I take out bits of code.

**Comment by szilard** [comment]
Btw the error appears only when I quit R, so all the code runs (seems to run) OK.

**Comment by thirdwing** [comment]
Can you try `detach("package:mxnet", unload=TRUE)` before the quit?

**Comment by szilard** [comment]
The error goes away if I take out Dropout.

**Comment by szilard** [comment]
Same with detach:

```
> detach("package:mxnet", unload=TRUE)
[1] "Start unload"
Warning message:
.onUnload failed in unloadNamespace() for 'mxnet', details:
  call: fun(...)
  error: could not find function "mx.internal.notify.shutdown" 
> 
Save workspace image? [y/n/c]: n
Loading required package: mxnet
terminate called without an active exception
Aborted (core dumped)
```

**Comment by szilard** [comment]
The error goes away if I take out Dropout.

**Comment by thirdwing** [comment]
I think #6773 will also fix this. @cjolivier01

**Comment by thirdwing** [comment]
@szilard I confirmed on a  p2.xlarge instance with CUDA 7.5 and cuDNN 5.1

You should be able to quit R without any errors.

I am closing this now. Feel free to reopen if necessary.
