### ISSUE TITLE
Error launching distributed mxnet on EC2 - invalid command

### ISSUE THREAD

**Issue by Luo-Liang** [dmlc/mxnet#3682]
When I ran the command as directed in the website, http://mxnet.io/how_to/cloud.html.
 
    ../**mxnet**/tools/launch.py -n 2 -H hosts --sync-dir /tmp/mxnet python train_mnist.py --kv-store dist_sync
 
I get an error:
 
    CalledProcessError: Command '/tmp/mxnet python train_mnist.py --sync-dir --kv-store dist_sync' returned non-zero exit status 126
 
Which looks like the command is concated incorrectly. It should be 
 
    python train_mnist.py --sync-dir /tmp/mxnet --kv-store dist_sync

Kindly let me know if there was a clear mistake.

**Comment by piiswrong** [comment]
--sync-dst-dir instead of --sync-dir

**Comment by Luo-Liang** [comment]
It will be the same problem if I change the command to what you indicated.

**Comment by piiswrong** [comment]
Could you post the command and the error?

**Comment by Vogen** [comment]
@piiswrong  I find a command on the bottom of the following page still use --sync-dir
http://mxnet.io/tutorials/computer_vision/image_classification.html
