### ISSUE TITLE
why mxnet doesn't have api reference like tensorflow?

### ISSUE THREAD

**Issue by zhangjiulong** [dmlc/mxnet#3689]

**Comment by VoVAllen** [comment]
What do you mean _api reference like tensorflow_?

**Comment by zhangjiulong** [comment]
when using tensorflow you can find all the api's reference,it's api page like:
```
add_to_collection
as_dtype
container
control_dependencies
convert_to_tensor
convert_to_tensor_or_indexed_slices
device
DeviceSpec
Dimension
DType
get_collection
```
very clear
but i can not find a page like this.
also i can not find any reference to some api like mx.sym.SliceChannel

**Comment by zhangjiulong** [comment]
tensorflow's api page
https://www.tensorflow.org/versions/r0.11/api_docs/python/index.html

**Comment by VoVAllen** [comment]
http://mxnet.io/api/python/symbol.html#mxnet.symbol.SliceChannel

**Comment by zhangjiulong** [comment]
thanks.
