### ISSUE TITLE
Distributed training on single machine error?

### ISSUE THREAD

**Issue by xlvector** [dmlc/mxnet#3691]
I use a 4 card machine to test distributed training.

If I start 3 workers, 1 server, 1 scheduler, every worker use different card. Everything works OK.

If I start 4 workers instead of 3, there will be randomly a worker have following error:

[13:34:50] /data00/tiger/mxnet_build/dmlc-core/include/dmlc/logging.h:235: [13:34:50] /data00/tiger/mxnet_build/mshadow/mshadow/./str
eam_gpu-inl.h:45: Check failed: e == cudaSuccess CUDA: an illegal memory access was encountered
[13:34:50] /data00/tiger/mxnet_build/dmlc-core/include/dmlc/logging.h:235: [13:34:50] src/engine/./threaded_engine.h:306: [13:34:50]
/data00/tiger/mxnet_build/mshadow/mshadow/./stream_gpu-inl.h:45: Check failed: e == cudaSuccess CUDA: an illegal memory access was en
countered
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment vari
able MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrac
e will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [13:34:50] src/engine/./threaded_engine.h:306: [13:34:50] /data00/tiger/mxnet_build/mshadow/mshadow/./stream_gpu-inl.h:45:
 Check failed: e == cudaSuccess CUDA: an illegal memory access was encountered
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment vari
able MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrac
e will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

**Comment by xlvector** [comment]
When I monitor with nvidia-smi, it will have following log (GPU 0000:83:00.0: Detected Critical Xid Error)

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     32413    C   python                                        5817MiB |
|    1     32497    C   python                                        5817MiB |
|    2     32581    C   python                                        5817MiB |
|    3     32668    C   python                                        5817MiB |
+-----------------------------------------------------------------------------+
# GPU 0000:83:00.0: Detected Critical Xid Error
Wed Nov  2 16:17:32 2016
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.35                 Driver Version: 367.35                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:02:00.0     Off |                  N/A |
| 27%   37C    P2    86W / 180W |   5833MiB /  8113MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:03:00.0     Off |                  N/A |
| 27%   42C    P2   101W / 180W |   5833MiB /  8113MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 0000:82:00.0     Off |                  N/A |
| 27%   36C    P2    39W / 180W |   5819MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 0000:83:00.0     Off |                  N/A |
| 27%   36C    P0    37W / 180W |      0MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     32413    C   python                                        5831MiB |
|    1     32497    C   python                                        5831MiB |
|    2     32581    C   python                                        5817MiB |
+-----------------------------------------------------------------------------+

@mli

**Comment by xlvector** [comment]
OK, it seems is card problem. One card have hardware problem....

**Comment by luhaofang** [comment]
Hi @xlvector , I met the same problem. Is the GPU's hardware problem? How did you fix it?
