### ISSUE TITLE
Inconsistent iterator interface in regards to label names.

### ISSUE THREAD

**Issue by leezu** [dmlc/mxnet#3692]
The interface of the different iterators in https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py is inconsistent in regards to the handling of label names.

While for `ImageRecordIter` and `MNISTIter` the label name is specified via the `label_name` argument, `NDArrayIter` takes a more general approach and accepts a dictionary made up of `{ label_name : labels }`.

It might be desirable to use the more general interface in all cases.

**Comment by piiswrong** [comment]
This is by design. ndarray iter is a general wrapper while the others are specific to certain data source.
