### ISSUE TITLE
Creat a NDarray in GPU and return zeros?Prebuilt in win10

### ISSUE THREAD

**Issue by QuantumLiu** [dmlc/mxnet#3696]
import mxnet as mx
>>> a = mx.nd.ones((2, 3),
... mx.gpu())

print (a * 2).asnumpy()
[[ 0.  0.  0.]
 [ 0.  0.  0.]]

import mxnet as mx
>>> a = mx.nd.ones((2, 3),
... mx.cpu())

print (a * 2).asnumpy()
[[ 2.  2.  2.]
 [ 2.  2.  2.]]

But the ndarray in cpu is correct.
i'm using the prebuilt version in win10,vs2015,cuda8.0,cudnn v4.

**Comment by piiswrong** [comment]
it's tricky to use windows prebuilds with cuda. Your driver and system version have match exactly.

Try building it from source
