### ISSUE TITLE
backword_source_id =-1 is missed in resnet152 json file

### ISSUE THREAD

**Issue by zhenlinluo** [dmlc/mxnet#3698]
When running pretrained resnet152 json file, the error report that backword_source_id is not defined. When looking at resnet50 json file, it is defined as -1 for all layers. But resnet152 does not have that param, anyone tried resnet152 before? @mli @piiswrong

**Comment by mli** [comment]
the json file is broken @tornadomeet

**Comment by piiswrong** [comment]
it's saved with nnvm branch and cannot be loaded with master

**Comment by zhenlinluo** [comment]
Is there quick way to convert to make it work on master? BTW, what is nnvm branch used for?

**Comment by mli** [comment]
grab
http://data.mxnet.io/models/imagenet-11k/resnet-152/resnet-152-symbol.json

then replace 11221 to 1000 in the json.

**Comment by rongqi79** [comment]
we got the new json file and tried again. 
if we did not replace 11221 to 1000 in the json, the program would run but accuracy was 0.
if we replaced 11221 to 1000, there would be error like: Check failed: from.shape() == to->shape() operands shape mismatch. Thanks

**Comment by tornadomeet** [comment]
@zhenlinluo @mli @rongqi79 i have updated the json file, and test in my machine, it's should be ok now.

**Comment by rongqi79** [comment]
Thanks!
