### ISSUE TITLE
CNN Text Classification Example Error

### ISSUE THREAD

**Issue by amitkb3** [dmlc/mxnet#3700]
@qcl6355,  I am successful in running CNN Text Classification example upto 8 iterations, then it error's out. I think it is due to this line " m.symbol.save('checkpoint/%s-symbol.json' % prefix)" in the train_cnn function. I am using python 3 and mxnet cpu version. I have already changed all print statements to be python 3 compliant:
I appreciate all the help.

**error:**
Iter 0 Train: Time: 118.9245674610138 , Training Accuracy: 64.60103626943005 , Dev Accuracy thus far: 73.0 
Iter 1 Train: Time: 123.77794885635376 , Training Accuracy: 82.02072538860104 , Dev Accuracy thus far: 74.1 
Iter 2 Train: Time: 126.14777970314026 , Training Accuracy: 90.92227979274611 , Dev Accuracy thus far: 74.0 
Iter 3 Train: Time: 126.88927102088928 , Training Accuracy: 94.48704663212435 , Dev Accuracy thus far: 75.7 
Iter 4 Train: Time: 122.98363375663757 , Training Accuracy: 95.96891191709845 , Dev Accuracy thus far: 75.3 
Iter 5 Train: Time: 123.61021280288696 , Training Accuracy: 97.35751295336787 , Dev Accuracy thus far: 75.9 
Iter 6 Train: Time: 123.61346220970154 , Training Accuracy: 97.28497409326425 , Dev Accuracy thus far: 75.0 
Iter 7 Train: Time: 123.4625952243805 , Training Accuracy: 97.69948186528498 , Dev Accuracy thus far: 76.4 
Iter 8 Train: Time: 123.22590136528015 , Training Accuracy: 98.54922279792746 , Dev Accuracy thus far: 76.6 
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-26-fef1d47d8af8> in <module>()
----> 1 train_cnn(cnn_model, x_train, y_train, x_dev, y_dev, batch_size)

<ipython-input-24-7617b641ca21> in train_cnn(model, X_train_batch, y_train_batch, X_dev_batch, y_dev_batch, batch_size, optimizer, max_grad_norm, learning_rate, epoch)
    162         if (iteration + 1) % 10 == 0:
    163             prefix = 'cnn'
--> 164             m.symbol.save('checkpoint/%s-symbol.json' % prefix)
    165             save_dict = {('arg:%s' % k) :v  for k, v in m.cnn_exec.arg_dict.items()}
    166             save_dict.update({('aux:%s' % k) : v for k, v in m.cnn_exec.aux_dict.items()})

C:\Users\amitb\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\symbol.py in save(self, fname)
    559         if not isinstance(fname, string_types):
    560             raise TypeError('fname need to be string')
--> 561         check_call(_LIB.MXSymbolSaveToFile(self.handle, c_str(fname)))
    562 
    563     def tojson(self):

C:\Users\amitb\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 def c_str(string):

MXNetError: [13:04:03] D:\chhong\mxnet\dmlc-core\src\io\local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "checkpoint/cnn-symbol.json"

**code:**
def train_cnn(model, X_train_batch, y_train_batch, X_dev_batch, y_dev_batch, batch_size,
        optimizer='rmsprop', max_grad_norm=5.0, learning_rate=0.0005, epoch=200):
    m = model
    # create optimizer
    opt = mx.optimizer.create(optimizer)
    opt.lr = learning_rate

    updater = mx.optimizer.get_updater(opt)

    for iteration in range(epoch):
        tic = time.time()
        num_correct = 0
        num_total = 0
        for begin in range(0, X_train_batch.shape[0], batch_size):
            batchX = X_train_batch[begin:begin+batch_size]
            batchY = y_train_batch[begin:begin+batch_size]
            if batchX.shape[0] != batch_size:
                continue

            m.data[:] = batchX
            m.label[:] = batchY

            # forward
            m.cnn_exec.forward(is_train=True)

            # backward
            m.cnn_exec.backward()

            # eval on training data
            num_correct += sum(batchY == np.argmax(m.cnn_exec.outputs[0].asnumpy(), axis=1))
            num_total += len(batchY)

            # update weights
            norm = 0
            for idx, weight, grad, name in m.param_blocks:
                grad /= batch_size
                l2_norm = mx.nd.norm(grad).asscalar()
                norm += l2_norm * l2_norm

            norm = math.sqrt(norm)
            for idx, weight, grad, name in m.param_blocks:
                if norm > max_grad_norm:
                    grad *= (max_grad_norm / norm)

                updater(idx, grad, weight)

                # reset gradient to zero
                grad[:] = 0.0

        # decay learning rate
        if iteration % 50 == 0 and iteration > 0:
            opt.lr *= 0.5
            #print >> logs, 'reset learning rate to %g' % opt.lr
            print('reset learning rate to {}' .format(opt.lr), file=logs)

        # end of training loop
        toc = time.time()
        train_time = toc - tic
        train_acc = num_correct * 100 / float(num_total)

        # saving checkpoint
        if (iteration + 1) % 10 == 0:
            prefix = 'cnn'
            m.symbol.save('checkpoint/%s-symbol.json' % prefix)
            save_dict = {('arg:%s' % k) :v  for k, v in m.cnn_exec.arg_dict.items()}
            save_dict.update({('aux:%s' % k) : v for k, v in m.cnn_exec.aux_dict.items()})
            param_name = 'checkpoint/%s-%04d.params' % (prefix, iteration)
            mx.nd.save(param_name, save_dict)
            #print >> logs, 'Saved checkpoint to %s' % param_name
            print('Saved checkpoint to {}' .format(param_name), file=logs)

        # evaluate on dev set
        num_correct = 0
        num_total = 0
        for begin in range(0, X_dev_batch.shape[0], batch_size):
            batchX = X_dev_batch[begin:begin+batch_size]
            batchY = y_dev_batch[begin:begin+batch_size]

            if batchX.shape[0] != batch_size:
                continue

            m.data[:] = batchX
            m.cnn_exec.forward(is_train=False)

            num_correct += sum(batchY == np.argmax(m.cnn_exec.outputs[0].asnumpy(), axis=1))
            num_total += len(batchY)

        dev_acc = num_correct * 100 / float(num_total)
        #print >> logs, 'Iter [%d] Train: Time: %.3fs, Training Accuracy: %.3f \
                #--- Dev Accuracy thus far: %.3f' % (iteration, train_time, train_acc, dev_acc)
        print('Iter {} Train: Time: {} , Training Accuracy: {} , Dev Accuracy thus far: {} '
              .format(iteration, train_time, train_acc, dev_acc), file=logs)

**Comment by jellchou** [comment]
you may make  a checkpoint directory

**Comment by amitkb3** [comment]
@jellchou , I created  a folder for checkpoint but still get error:

**error**
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-9-fef1d47d8af8> in <module>()
----> 1 train_cnn(cnn_model, x_train, y_train, x_dev, y_dev, batch_size)

<ipython-input-5-1cd0772208bc> in train_cnn(model, X_train_batch, y_train_batch, X_dev_batch, y_dev_batch, batch_size, optimizer, max_grad_norm, learning_rate, epoch)
    162         if (iteration + 1) % 10 == 0:
    163             prefix = 'cnn'
--> 164             m.symbol.save('"C:/Users/amitb/learnpython/TextClassification/checkpoint/%s-symbol.json' % prefix)
    165             save_dict = {('arg:%s' % k) :v  for k, v in m.cnn_exec.arg_dict.items()}
    166             save_dict.update({('aux:%s' % k) : v for k, v in m.cnn_exec.aux_dict.items()})

C:\Users\amitb\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\symbol.py in save(self, fname)
    559         if not isinstance(fname, string_types):
    560             raise TypeError('fname need to be string')
--> 561         check_call(_LIB.MXSymbolSaveToFile(self.handle, c_str(fname)))
    562 
    563     def tojson(self):

C:\Users\amitb\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 def c_str(string):

MXNetError: [10:51:52] D:\chhong\mxnet\dmlc-core\src\io\local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open ""C:/Users/amitb/learnpython/TextClassification/checkpoint/cnn-symbol.json"

**Comment by amitkb3** [comment]
there was a extra double quote in the path to checkpoint folder which caused the error.

Thanks for all the help.
Regards,
Amit
