### ISSUE TITLE
symbo.Group don't support return ?

### ISSUE THREAD

**Issue by nopattern** [dmlc/mxnet#3704]
I am trying to run example/rcnn/demo.py on windows.   when run the following code:
        `group = mx.symbol.Group([rois, cls_prob, bbox_pred])
        return group`
an error occured : "node == e.source.get() Symbol.GetName only works for non-grouped symbol
"
    It seems symbol.group  don't support return ? How to fix this?

**Comment by piiswrong** [comment]
this is a known bug and is already fixed. Please update

**Comment by nopattern** [comment]
thank you .
