### ISSUE TITLE
computing image mean

### ISSUE THREAD

**Issue by TELSER1** [dmlc/mxnet#371]
I recall, from version 1 of Cxxnet, that there was a utility for creating the .bin for the image mean; I can iterate through the dataset, compute the mean image, save it as a jpg, and then convert it with ./bin/im2rec, but I was wondering if there was a utility to do this that I missed in the documentation?

**Comment by TELSER1** [comment]
On the subject of preprocessing, I'm currently getting some sort of memory allocation I issue I don't understand when  trying to read my own train/test .rec files:

```
mxnet.base.MXNetError: [21:18:51] src/storage/./cpu_device_storage.h:48: Check failed: (ret) == (0) Allocation failed
```

My train.lst looks like this (all images are 1024x1024x3):

```
0	222	w_7812.jpg
1	44	w_4598.jpg
```

I create the train/test records like so:

```
./bin/im2rec train.lst /home/user/Desktop/train/ train.rec
```
and everything seems to work fine. My iterators are defined as follows:
```
train_dataiter = mx.io.ImageRecordIter(
    path_imgrec="train.rec",
    rand_crop=False,
    rand_mirror=True,
    data_shape=(3,1024,1024),
    batch_size=64,
    preprocess_threads=1)
test_dataiter = mx.io.ImageRecordIter(
    path_imgrec="test.rec",
    rand_crop=False,
    rand_mirror=False,
    data_shape=(3,1024,1024),
    batch_size=64,
    preprocess_threads=1)
```
And the remainder is just a truncation of the Cifar10 network example

```
data = mx.symbol.Variable(name="data")
conv1 = ConvFactory(data=data, kernel=(3,3), pad=(1,1), num_filter=96, act_type="relu")
in3a = SimpleFactory(conv1, 32, 32)
in3b = SimpleFactory(in3a, 32, 48)
in3c = DownsampleFactory(in3b, 80)
in4bb =mx.symbol.Dropout(in3c) 
in4c = SimpleFactory(in4bb, 80, 80)
in4cc= mx.symbol.LeakyReLU(in4c)
in4d = SimpleFactory(in4cc, 48, 96)
pool = mx.symbol.Pooling(data=in4cc, pool_type="avg", kernel=(7,7), name="global_pool")
flatten = mx.symbol.Flatten(data=pool, name="flatten1")
fc = mx.symbol.FullyConnected(data=flatten, num_hidden=447, name="fc1")
softmax = mx.symbol.Softmax(data=fc, name="loss")

gpus=mx.gpu(0)
model=mx.model.FeedForward(ctx=gpus,symbol=softmax,num_round=2,learning_rate=0.05,momentum=.9,wd=0.0001,initializer=mx.init.Uniform(0.07))
model.fit(X=train_dataiter,eval_data=test_dataiter,epoch_end_callback=mx.callback.Speedometer(64))
```

**Comment by tqchen** [comment]
Hmm, this could due to the allocation of too large memory chunk being requested. Can you check what was the size being requested on your side https://github.com/dmlc/mxnet/blob/master/src/storage/cpu_device_storage.h#L47

**Comment by TELSER1** [comment]
I can check when I get home; is the output of posix_memalign produced at some point in the run?  I'm not entirely clear on how to check the size of the request.

**Comment by tqchen** [comment]
You can change this line https://github.com/dmlc/mxnet/blob/master/src/storage/cpu_device_storage.h#L48 to
```
  CHECK_EQ(ret, 0) << "Allocation failed, " << "requested size = "<< size;
```

**Comment by TELSER1** [comment]
Do I need to recompile anything?

**Comment by tqchen** [comment]
Yes, you will need to rebuild libmxnet.so, and re-install the python.

**Comment by TELSER1** [comment]
It was trying to allocate 73 GB, and I cap out at 32 GB; I'm somewhat surprised, though, as it only looked like it was taking up 16 GB when I loaded them all as numpy arrays.  I suppose  I'm going to have to do segmentation instead of trying to feed them in as is; thank you for the diagnostic help.

Re: the original question, is there an existing tool for computing the image mean, or do I need to build that utility?

**Comment by antinucleon** [comment]
The image iterator will automatically calculate/load mean file if you set ```mean_file=mean.nd```. Personally, I set ```mean_r=117```, ```mean_g=117```, ```mean_b=117``` instead of such a mean file. There is no performance hurt.

**Comment by TELSER1** [comment]
Is there a GPU equivalent line for the requested CPU memory? Just to make sure I could get it working, I resized all my images to 256x256; even with a batch size of 2, it's throwing 
```
mxnet.base.MXNetError: [10:57:24] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
```
The fully loaded 256x256 takes up 1.6 GB or so of CPU RAM, and my GPU is a titan X, so it seems unlikely that it genuinely can't find the memory for that.  I've also tried converting to greyscale (1x512x512), although it seemed to have difficulty loading it.

**Comment by tqchen** [comment]
There is no limit on how much memory to get. As everything is cutting the edge of memory, maybe you can check the memory requested, maybe the input size is indeed too large for this configuration(it was used for cifar, which means it expects a small input size). Try to use the one for imagenet, which might solve your probem

**Comment by tqchen** [comment]
I am going to close this for now as the original question of mean image get answered, please feel free to re-open this if there is future questions.

**Comment by paipai880429** [comment]
@antinucleon Could you please detail "The image iterator will automatically calculate/load mean file if you set mean_file=mean.nd."? How to write an image iterator to have such functionality?

```
    train_dataiter = mx.io.ImageRecordIter(
        path_imgrec = args.data_dir + "train.rec",
        data_shape  = data_shape,
        batch_size  = args.batch_size,
        rand_crop   = True,
        rand_mirror = True,
        shuffle     = True, # Note that it will only shuffle in the batch!
        num_parts   = kv.num_workers,
        part_index  = kv.rank)
```

Besides, will the ```mean_image``` or ```mean_r, mean_g, mean_b``` also be conducted on the validation and testing data? The document says that they are only augmentation parameters. 

![image](https://cloud.githubusercontent.com/assets/3724085/12377662/266f89fe-bd60-11e5-9072-beb3fbd9d770.png)

**Comment by kperkins411** [comment]
Put this line in your training ImageRecordIter (call it what you want, put it where you want)
mean_img           = "../recordIO_dir/mean.bin"   
Its not there to start.  But when you fit your model it will be **created for you**.  (I think after the first epoch but am not positive).  Then when the validation set is run its there and used, same with your test set.

**Comment by jackyblackme** [comment]
Yeah, Put mean_img="path/to/mean.nd". If the file does not exist, ImageRecordIterator will first create this file and calculate mean value, store result in the file. And then start training. Detail can be seen in file "iter_image_recordio_2.cc", the new version of recordio data iterator under "mxnetRoot/src/io/iter_image_recordio_2.cc". Maybe from line 216, the Normalize init and the CreateMeanImg function.
