### ISSUE TITLE
how to deal with the unlabel data with the dataiter?

### ISSUE THREAD

**Issue by R1ncy** [dmlc/mxnet#3710]
hi, I want to load some labeled and unlabeled data into mxnet.  
I follow the example [https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/data.py#L96](url) to create a dataiter.
how to implement the `provide_label` method for unlabel data?
Thanks for your attention.

**Comment by winstywang** [comment]
Just return a dummy one

**Comment by R1ncy** [comment]
@winstywang  Thank you. could you please me some example  of that? :)

**Comment by winstywang** [comment]
I don't see the need of example for this. Just return anything you want, and do not use it later.

**Comment by jellchou** [comment]
I am also in trouble with this when I try to predict the text label.
In example, https://github.com/dmlc/mxnet/blob/master/example/cnn_text_classification/text_cnn.py#L124, the data was bind into the model in training.  But in prediction, the loaded model need to take DataIter type  data as input.

**Comment by R1ncy** [comment]
thank you
1. if my labels are 0 and 1,  so I could set the label = -1 for the unlabeled  data.
I want to put the label and unlabeled data to the model and only use the label of labeled data at the final layer.
2. I see #2403 said need to use the "ignore label". Is it an attr of sym?  How to use it?

**Comment by winstywang** [comment]
@R1ncy you can set ignore_label in softmax loss, if the sample is with label=ignore_label, it will contribute to the gradient.

**Comment by R1ncy** [comment]
is it `mx.sym.SoftmaxOutput(..use_ignore = True, ignore_label = -1)`?
what if I want to use `mx.sym.SVMOutput` ?
seems svmoutput doesn't have ignore_label
