### ISSUE TITLE
Can't use self-defined optimizer when training with multiple nodes

### ISSUE THREAD

**Issue by FreemanX** [dmlc/mxnet#3713]
When I try the example https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_cifar10_resnet.py with multiple nodes, the error shows as follows:

File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/kvstore_server.py", line 38, in server_controller
    optimizer = pickle.loads(cmd_body)
  File "/usr/lib64/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib64/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib64/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib64/python2.7/pickle.py", line 1126, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'Nesterov'

How to pass the self-defined optimizer to kv store server?  Thanks!

**Comment by piiswrong** [comment]
@mli I also had this problem. Looks like if your optimizer definition is not in mx.optimizer it won't be loaded by pslite server

**Comment by mli** [comment]
Yes, the current pickle load/save is limited, for complex optimizer we need
to let the server node load it at the beginning

**Comment by FreemanX** [comment]
@mli How to  let the server node load it at the beginning? I manually added an optimizer Class in mxnet/python/mxnet/optimizer.py didn't work...

**Comment by piiswrong** [comment]
it should work if you do that.
make sure to sync your mxnet to all nodes

**Comment by FreemanX** [comment]
Didn't work...  I have reinstall mxnet python package on all of our nodes. @piiswrong

**Comment by piiswrong** [comment]
I worked for me. make sure that you are using the one defined in mxnet/python/mxnet/optimizer.py

**Comment by mli** [comment]
you just need to sync mxnet/python/mxnet/optimizer.py on all nodes,

such as

cat hosts | xargs -I{} scp ~/mxnet/python/mxnet/optimizer.py {}:~/
mxnet/python/mxnet/optimizer.py

**Comment by FreemanX** [comment]
It worked... Somehow the environment PYTHONPATH of my own has lower priority than the system's default python path and I was using the unchanged optimizer.py all the time. I override sys.path and the ball can roll~
Thank you guys for your help!

**Comment by nicklhy** [comment]
Do we have a better solution now ? I do not think it is a good idea to modify mxnet source code file `mxnet/python/mxnet/optimizer.py`.
