### ISSUE TITLE
Windows 10 Pro Install Problems

### ISSUE THREAD

**Issue by alvinjamur** [dmlc/mxnet#3718]
Am following the procedure to install the GPU version of MXNET for useage in R but I'm not even
able to find the setupenv file.....

**Comment by piiswrong** [comment]
try building from source

**Comment by alvinjamur** [comment]
"Installing Pre-built Packages on Windows.....install the package by double-clicking 
setupenv.cmd"

 ****  above....the file does not even show up after unzipping the gpu version


"To build and install MXNet yourself, you need the following dependencies:

Microsoft Visual Studio 2013
Visual C++ Compiler Nov 2013 CTP (to provide C++ support)
OpenCV (for computer vision operations)
OpenBlas (for linear algebraic operations)
CuDNN (to provide a Deep Neural Network library)"

*** ms vidual c++ compiler 2013 wont work on windows 10

**Comment by thirdwing** [comment]
I don't think you really need `setupenv.cmd` for R package.

Please try to follow https://github.com/dmlc/mxnet/blob/master/docs/get_started/setup.md#installing-mxnet-on-a-gpu

**Comment by alvinjamur** [comment]
Does not help. I'm now following directions to the T and am still not able to do it...for instance.
I'm able to get MXNET work fine on the CPU version downloaded from CRAN but not on a GPU.
The instructions are not clear....if people have managed to install it, am wondering if someone could 
please write up steps in gory detail....

==
4. Download the most recent GPU-enabled MXNet package from the Releases tab. Unzip this file and navigate to the /nocudnn folder. Note: We will be copying some of these extracted files in to MXNet’s R-package folder. We are now working two folders, R-package/ and nocudnn/.
==
There is no /nodudnn folder there....

**Comment by thirdwing** [comment]
The instruction has been updated in https://github.com/dmlc/mxnet/pull/6841

I am closing this now. Feel free to reopen.
