### ISSUE TITLE
cpp example "image-classification-predict.cc" can't be debug in vs2013 on win7

### ISSUE THREAD

**Issue by dianyancao** [dmlc/mxnet#3725]
I try the cpp example "image-classification-predict.cc",when I add MXPredCreate to cpp main function,the program can't run into first step with a break point.
How to solve this problem,I want to use the c++ interface rather than python. 
Following is test code:
```
int main()
{
	std::string test_file;
	test_file = std::string("D:/CR/SamplesTrain/0000A226-C05D-4155-AD65-94B20070F482_pbdb.jpg");

	// Models path for your model, you have to modify it
	BufferFile json_data("D:/CR/CR/RNN/model/-symbol.json");
	BufferFile param_data("D:/CR/CR/RNN/model/-0011.params");

	// Parameters
	int dev_type = 2;  // 1: cpu, 2: gpu
	int dev_id = 0;  // arbitrary.
	mx_uint num_input_nodes = 1;  // 1 for feedforward
	const char* input_key[1] = { "data" };
	const char** input_keys = input_key;

	// Image size and channels
	int width = 128;
	int height = 64;
	int channels = 1;

	const mx_uint input_shape_indptr[2] = { 0, 4 };
	// ( trained_width, trained_height, channel, num)
	const mx_uint input_shape_data[4] = { 1,
		static_cast<mx_uint>(channels),
		static_cast<mx_uint>(width),
		static_cast<mx_uint>(height) };
	
	PredictorHandle out = 0;  // alias for void *
	
	//-- Create Predictor
	
	MXPredCreate((const char*)json_data.GetBuffer(),
		(const char*)param_data.GetBuffer(),
		static_cast<size_t>(param_data.GetLength()),
		dev_type,
		dev_id,
		num_input_nodes,
		input_keys,
		input_shape_indptr,
		input_shape_data,
		&out);
	
	return 0;
}
```

**Comment by dianyancao** [comment]
I use win api to load the dll function dynamiclly,now it works,Thanks.

**Comment by arlose** [comment]
I have the same problem, which win api did you load? how? thanks

**Comment by arlose** [comment]
@dianyancao

**Comment by zhyj3038** [comment]
can you geive an example on how to load libmxnet.dll daynamiclly?

**Comment by dianyancao** [comment]
Sorry for late reply,mxnet now have fix this,see example\image-classification\predict-cpp
About how to load a windows dll dynamiclly:
http://www.cnblogs.com/lhbssc/archive/2012/02/08/2342853.html

**Comment by jstzsjw** [comment]
@dianyancao Could you show me more details on how to build image-classification-predict.cc?
I have tried many times to build it with vs2013+win7+opencv3.1, but failed. And I'm really upset about it.
Looking forward to your reply, thx.^-^

**Comment by zhyj3038** [comment]
@jstzsjw  mxnet do not support VS2013 yet, VS2015 works.

**Comment by jstzsjw** [comment]
@zhyj3038 I rebuild with VS2015, and it works. Thank you!!

**Comment by tianqiangxing** [comment]
@dianyancao "Sorry for late reply,mxnet now have fix this,see example\image-classification\predict-cpp"
has this bug fixed? Using the lastest version, this bug still occured, and I had tried many times without any result. Could show me how to solve this problem,  thanks for your help.

**Comment by tqx0808** [comment]
@dianyancao "Sorry for late reply,mxnet now have fix this,see example\image-classification\predict-cpp"
has this bug fixed? Using the lastest version, this bug still occured, and I had tried many times without any result. Could show me how to solve this problem, thanks for your help.

**Comment by dianyancao** [comment]
@tqx0808 try vs2015 with proper cuda version 8.0.44
