### ISSUE TITLE
mx.io.ImageRecordIter For Regression?

### ISSUE THREAD

**Issue by zmonoid** [dmlc/mxnet#3731]
On classification images, mxnet provide very good IO for training classification model, including very good data augmentation.

However, for linear regression model (label be continuous variables), for example, the steer angle prediction from camera images, there is no such IO.

Is there any tutorial on how to make it?

Best,
zmonoid

**Comment by piiswrong** [comment]
tools/im2rec.py supports packing multi label data. use --label-width and --pack-label
then set label_width in imagerecorditer

**Comment by zmonoid** [comment]
@piiswrong Thanks, but it is no about multi label data.
It is about regression problem when the output is **LinearRegressionOutput** but the input is still image.
How to implement such IO?

**Comment by piiswrong** [comment]
labels are floats anyway so there are no difference in terms of io. only the symbol is different

**Comment by zmonoid** [comment]
@piiswrong Thanks, I got your point.

The one hot encoding of classification label is done in **SoftmaxOutput** Layer.
I thought it was in **ImageRecordIter**

Thanks very much!!!

**Comment by zmonoid** [comment]
@piiswrong It is not working...

In the train.lst:

> ....
37	0.000000	37.jpg
38	-160.940000	38.jpg
39	-160.130000	39.jpg
40	-159.130000	40.jpg
41	-157.710000	41.jpg
42	-155.900000	42.jpg
43	-153.680000	43.jpg
44	-150.860000	44.jpg
45	-149.340000	45.jpg
46	-144.910000	46.jpg
47	-141.780000	47.jpg
48	-138.760000	48.jpg
49	-134.820000	49.jpg
50	-130.390000	50.jpg
51	-127.260000	51.jpg
52	-124.440000	52.jpg
53	-122.220000	53.jpg
54	-120.500000	54.jpg
55	-119.090000	55.jpg
56	-117.880000	56.jpg
57	-117.480000	57.jpg
58	-117.380000	58.jpg
59	-117.280000	59.jpg
60	-117.280000	60.jpg
61	-116.370000	61.jpg
62	-114.960000	62.jpg
63	-113.140000	63.jpg
64	-111.630000	64.jpg
65	-108.300000	65.jpg
66	-105.180000	66.jpg
67	-102.350000	67.jpg
68	-99.630000	68.jpg
69	-97.310000	69.jpg
....


In my symbol_drive.py:

```python
    ....
    flatten = mx.sym.Flatten(data=pool, name="flatten")
    fc1 = mx.symbol.FullyConnected(data=flatten, num_hidden=1, name='fc1_')
    output = mx.symbol.LinearRegressionOutput(data=fc1, name='softmax')
```

My train iterator:

```python
    train = mx.io.ImageRecordIter(
        path_imgrec = os.path.join(args.data_dir, args.train_dataset),
        mean_r      = 123.68,
        mean_g      = 116.779,
        mean_b      = 103.939,
        data_shape  = data_shape,
        batch_size  = args.batch_size,
        #mean_img    = os.path.join(args.data_dir, "mean_%d.bin" % args.data_shape),
        rand_crop   = True,
        rand_mirror = True,
        shuffle     = True,
        #random_h    = 36,
        #random_s    = 50,
        #random_l    = 50,
        #max_rotate_angle    = 10,
        num_parts   = kv.num_workers,
        part_index  = kv.rank)
```


This will report error:

>    prob = pred[numpy.arange(label.shape[0]), numpy.int64(label)]
IndexError: index -150 is out of bounds for axis 1 with size 1


Which means the model still takes our label as classification label, not for linear regression label.
Is there any way to fix this problem?
If I change output layer name to:
>output = mx.symbol.LinearRegressionOutput(data=fc1, name='linear')


The error would be:
>  Symbol.InferShapeKeyword argument name softmax_label not found

**Comment by zmonoid** [comment]
The problem is... If I warp DataIter, I cannot use the default data augmentation for ImageRecordIter,

And if I warp ImageRecordIter like:

```python
class ImageRegressionIter(mx.io.ImageRecordIter):
...
```

It will also report error...

**Comment by zmonoid** [comment]
I got the solution:

It is the metric problem, for regression, you cannot use classification metrics like accuracy...
You need to change metrics to 'rmse' or 'mse'
