### ISSUE TITLE
install error in ubuntu 16.04 

### ISSUE THREAD

**Issue by Struggle-YD** [dmlc/mxnet#3732]
dear team
 when i try to install mxnet on ubuntu 16.04 with R language, i encounter some problems as follows
  
~/mxnet/R-package$ Rscript -e "library(devtools); library(methods); options(repos=c(CRAN='https://cran.rstudio.com')); install_deps(dependencies = TRUE)"

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot download all files
此外: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 131072 != reported length 3505013
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/src/contrib/DiagrammeR_0.8.4.tar.gz': status was 'Failure when receiving data from the peer'
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘DiagrammeR’ failed
Error in download.packages(x$name, destdir = dest_dir, repos = x$repos,  : 
  下标出界
Calls: install_deps ... FUN -> remote_download -> remote_download.cran_remote
停止执行
 best!

**Comment by thirdwing** [comment]
From the error message, the error has nothing to do with mxnet.

> URL 'https://cran.rstudio.com/src/contrib/DiagrammeR_0.8.4.tar.gz': status was 'Failure when receiving data from the peer'

Please check your network setting.
