### ISSUE TITLE
mxnet under docker

### ISSUE THREAD

**Issue by xlvector** [dmlc/mxnet#3740]
I meet two problems,

If I use nvidia image with cuda8/cudnn5, I will get error about driver version less than runtime version.

If I use nvidia image with cuda7.5/cudnn4, the init step will be very slow and It will fail with following errors:

[05:22:46] /mxnet/dmlc-core/include/dmlc/logging.h:235: [05:22:46] /mxnet/mshadow/mshadow/./random.h:344: Check failed: (status) == (CURAND_STATUS_SUCCESS) CURAND Gen Uniform float failed. size = 131072
[05:22:46] /mxnet/dmlc-core/include/dmlc/logging.h:235: [05:22:46] src/engine/./threaded_engine.h:306: [05:22:46] /mxnet/mshadow/mshadow/./random.h:344: Check failed: (status) == (CURAND_STATUS_SUCCESS) CURAND Gen Uniform float failed. size = 131072
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [05:22:46] src/engine/./threaded_engine.h:306: [05:22:46] /mxnet/mshadow/mshadow/./random.h:344: Check failed: (status) == (CURAND_STATUS_SUCCESS) CURAND Gen Uniform float failed. size = 131072
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

@mli

**Comment by piiswrong** [comment]
are you using docker or nvidia-docker?
I remember you need >367 for cuda8. and if you are using docker (instead of nvidia-docker) your host nv driver version need to match driver version inside docker

**Comment by mli** [comment]
update the docker's cudnn version to 5.1?

**Comment by xlvector** [comment]
@piiswrong use nvidia-docker. Seems my driver version is just 367.... But the host machine can use cuda8 without docker :(

@mli I use docker image from nvidia's build (https://hub.docker.com/r/nvidia/cuda/) , you mean I create an image from an os base image and install cuda/cudnn by myself?

**Comment by piiswrong** [comment]
The first issue is a generic issue with using cuda with docker. I think you can find solutions online

The second is a bug with cuda 7.5 where it has restrictions on the size of random array you can create. You can work around it by using np.random instead of mx.random in mx.init

**Comment by xlvector** [comment]
@piiswrong There is no driver version > 367?

<img width="542" alt="2016-11-06 2 24 04" src="https://cloud.githubusercontent.com/assets/100203/20035770/c3358afa-a42c-11e6-95a8-827ca2848dd7.png">

**Comment by piiswrong** [comment]
https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

seems they have 370 now. 367 should work. try stackoverflow and see if other people had the same problem
