### ISSUE TITLE
How to uninstall mxnet thoroughly and reinstall it again on Ubuntu?

### ISSUE THREAD

**Issue by QuantumLiu** [dmlc/mxnet#3746]
I had  installed mxnet in Quick Installation way.But it couldn't use gpu.
I thought that there must be sth wrong in installation.And I installed it again without reading the doc which introduced how to edit config.mk.
And i found two same lines
:
PYHONPATH......
In the end of my .bashrc
And then my Theano didn't work too.After i deleted those two lines,Theano worked again.
But when I make the config.mk,it got erro.
I want to.reinstall.mxnet thoroughly,but I don't know what had been edited by mxnet in my system.
What can I do?

**Comment by VoVAllen** [comment]
I think pip uninstall mxnet could work. Then make clean before you rebuild the mxnet

**Comment by VoVAllen** [comment]
Also could you provide what's the two lines?

**Comment by QuantumLiu** [comment]
:~/MXNet/mxnet$ make -j32
cd /home/quantumliu/MXNet/mxnet/dmlc-core; make libdmlc.a USE_SSE=1 config=/home/quantumliu/MXNet/mxnet/config.mk; cd /home/quantumliu/MXNet/mxnet
make[1]: Entering directory '/home/quantumliu/MXNet/mxnet/dmlc-core'
make[1]: 'libdmlc.a' is up to date.
make[1]: Leaving directory '/home/quantumliu/MXNet/mxnet/dmlc-core'
