### ISSUE TITLE
Where is the declaration of "ctcComputeInfo"?

### ISSUE THREAD

**Issue by kites520** [dmlc/mxnet#3747]
When I rebuild mxnet, there is an error occurred.

plugin/warpctc/./warpctc-inl.h:129:5: error: 'ctcComputeInfo' was not declared in this scope.

So I need someone give me a little help, thx.

**Comment by flyingmouse** [comment]
Same problem! waiting for answers...

**Comment by terrychenism** [comment]
use ctcOptions instead of ctcComputeInfo
