### ISSUE TITLE
python import error

### ISSUE THREAD

**Issue by fangli1992** [dmlc/mxnet#375]
I have installed mxnet successfully in my computer with os : ubuntu12.04; Then I install it on centos,I build it successfully, but after I installed python using'python setup.py install --prefix /home/myhome/local'(no error occurred!), when I import mxnet, I got error:
'''
  File "<stdin>", line 1, in <module>
  File "mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/zwfang/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: cblas_sgemm
'''
I have install atlas etc.

**Comment by tornadomeet** [comment]
make sure that in your config.mk, the set is : USE_BLAS = atlas
and make sure your atlas is in your environment; then make clean && make -j4 and install python lib.
if not set USE_BLAS correctly, it can be build successfully, but can't  import  mxnet.

**Comment by tqchen** [comment]
I am going to close this for now as there is no updates on this, but feel free to reopen it if you have more questions

**Comment by vchuravy** [comment]
I run into the same problem if I don't add to `cblas` to the MSHADOW flags

````
else ifeq ($(USE_BLAS), blas)
    MSHADOW_LDFLAGS += -lblas -lcblas
````

The blas version installed is the archlinux one from http://www.netlib.org/blas/ & https://www.archlinux.org/packages/extra/x86_64/cblas/
