### ISSUE TITLE
Comparison of routine in 1 GPU vs 4 GPUs

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#3754]
I'm working with the ImageNet dataset in R. I was comparing the performance with 1 GPU vs 4 GPUs, assuming the rest of the parameters are the same. Using 1 GPU 1 iteration takes 6.30h, while with 4 GPUs 1 iteration takes 2h. Therefore using n GPU is not n times faster.

I would be interested in understanding what are the botlenecks in the [training function](https://github.com/dmlc/mxnet/blob/master/R-package/R/model.R#L94). Can somebody give some clarity on this?

**Comment by piiswrong** [comment]
what network are you using?

**Comment by miguelgfierro** [comment]
ResNet, I'm going to do a PR as I promised @thirdwing but we are cleaning the code and preparing other things. Do you think it has to do with the network? What about the data communication between GPUs using kvstore?

**Comment by piiswrong** [comment]
try kvstore='device'

**Comment by miguelgfierro** [comment]
It is already with device, if fact I did test with device and with the default option and the difference is small. With device you can gain between 5 to 10 min in a process of 2h.

**Comment by miguelgfierro** [comment]
I have been reading how mxnet share memory compares with other deep learning libraries. It looks that the bottleneck is in the data transmission between GPUs.
