### ISSUE TITLE
Windows 10 Pro & MXNET GPU (For R Environment)

### ISSUE THREAD

**Issue by alvinjamur** [dmlc/mxnet#3758]
If someone here has successfully installed the GPU version of MXNET (gpu version for R) could please post instructions....the instructions for install do not work...

**Comment by VoVAllen** [comment]
https://github.com/dmlc/mxnet/issues/3644#issuecomment-258770447

Scroll to the bottom

**Comment by alvinjamur** [comment]
We were able to build it!!! Now running with Titan X.
Will post detailed instructions for build under Windows 10 in short order.....
