### ISSUE TITLE
Simplify the LSTM API

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#376]
In the newly added LSTM examples, the LSTM implementation seems not as modular as it could be. The API can be improved to [composite more easily with other symbols](https://github.com/dmlc/mxnet/blob/master/example/notebooks/composite_symbol.ipynb). 

Some other popular deep learning libraries with Python API also provided LSTM examples with simpler API.

[Keras](https://www.google.com/?gws_rd=ssl#newwindow=1&q=keras+lstm)
https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py
```python
model = Sequential()
model.add(LSTM(512, return_sequences=True, input_shape=(maxlen, len(chars))))
model.add(Dropout(0.2))
model.add(LSTM(512, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(len(chars)))
model.add(Activation('softmax'))
```
https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py
```python
model = Sequential()
model.add(Embedding(max_features, 128, input_length=maxlen))
model.add(LSTM(128))  # try using a GRU instead, for fun
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))
```
[Lasagne](https://www.google.co.in/?gws_rd=ssl#newwindow=1&q=lasagne+lstm)
https://github.com/Lasagne/Lasagne/blob/master/examples/recurrent.py
```python
    l_in = lasagne.layers.InputLayer(shape=(N_BATCH, MAX_LENGTH, 2))
    l_mask = lasagne.layers.InputLayer(shape=(N_BATCH, MAX_LENGTH))
    l_forward = lasagne.layers.RecurrentLayer(
        l_in, N_HIDDEN, mask_input=l_mask, grad_clipping=GRAD_CLIP,
        W_in_to_hid=lasagne.init.HeUniform(),
        W_hid_to_hid=lasagne.init.HeUniform(),
        nonlinearity=lasagne.nonlinearities.tanh)
    l_backward = lasagne.layers.RecurrentLayer(
        l_in, N_HIDDEN, mask_input=l_mask, grad_clipping=GRAD_CLIP,
        W_in_to_hid=lasagne.init.HeUniform(),
        W_hid_to_hid=lasagne.init.HeUniform(),
        nonlinearity=lasagne.nonlinearities.tanh, backwards=True)
    l_forward_slice = lasagne.layers.SliceLayer(l_forward, -1, 1)
    l_backward_slice = lasagne.layers.SliceLayer(l_backward, 0, 1)
    l_sum = lasagne.layers.ConcatLayer([l_forward_slice, l_backward_slice])
    l_out = lasagne.layers.DenseLayer(
        l_sum, num_units=1, nonlinearity=lasagne.nonlinearities.tanh)
```
[Neon](https://www.google.co.in/?gws_rd=ssl#newwindow=1&q=neon+lstm)
https://github.com/NervanaSystems/neon/blob/master/examples/imdb_lstm.py
```python
layers = [
    LookupTable(vocab_size=vocab_size, embedding_dim=embedding_dim, init=init_emb),
    LSTM(hidden_size, init_glorot, activation=Tanh(),
         gate_activation=Logistic(), reset_cells=True),
    RecurrentSum(),
    Dropout(keep=0.5),
    Affine(2, init_glorot, bias=init_glorot, activation=Softmax())
]
```
https://github.com/NervanaSystems/neon/blob/master/examples/word_lstm.py
```python
if rlayer_type == 'lstm':
    rlayer1 = LSTM(hidden_size, init, Logistic(), Tanh())
    rlayer2 = LSTM(hidden_size, init, Logistic(), Tanh())
elif rlayer_type == 'gru':
    rlayer1 = GRU(hidden_size, init, activation=Tanh(), gate_activation=Logistic())
    rlayer2 = GRU(hidden_size, init, activation=Tanh(), gate_activation=Logistic())
else:
    raise NotImplementedError('%s layer not implemented' % rlayer_type)

layers = [
    rlayer1,
    rlayer2,
    Affine(len(train_set.vocab), init, bias=init, activation=Softmax())
]
```

**Comment by antinucleon** [comment]
Thanks for your suggestion! We are still designing the general RNN model
API, so we put current LSTM in example folder but not in Python folder.

Please stay tune for a more friendly multi gpu LSTM :)

**Comment by tqchen** [comment]
@futurely Thanks for the helpful suggestions.  If you have ideas on how things can be done, you are more than welcomed to contribute your wisdom to the project :)

**Comment by futurely** [comment]
The creator of Keras has proposed a new RNN API to support dual-backend of TensorFlow and Theano aiming to be "[the best solution for RNNs going forward](https://github.com/fchollet/keras/issues/1014#issuecomment-158136484)".

**Comment by shwetamore1295** [comment]
I am new to mxnet but I have functional idea of LSTM. Can I take this issue?

**Comment by pluskid** [comment]
@shwetamore1295 Your contributions are most welcome! FYI we already have a bucketing API as [described here](http://mxnet.readthedocs.org/en/latest/tutorial/bucketing.html).

**Comment by rohit12** [comment]
@pluskid I know about LSTMs and how to construct them. However, I only have a basic understanding of these networks. I would be happy if you could expand more on what exactly needs to be done.

**Comment by shwetamore1295** [comment]
@rohit12 I was hoping to take up this issue.

**Comment by pluskid** [comment]
We have a bucketing API that is flexible for handling complicated over-time models. But we need more examples on this. So if you could help create more RNN examples with this, that could be helpful.

On the other hand, we will need to have back-propagate-through-time implementation that saves memory, that use a Python for loop to carry the computation and state-copying. This is still need to be done, and is needed for scenarios where RNNs architectures are simple but the sequences in the data might be too long to unroll.

**Comment by javelinjs** [comment]
+1 Looking forward to more RNN examples based on bucketing API

**Comment by shwetamore1295** [comment]
@pluskid I am familiar with backpropagation through time. I guess I could implement. Also what sort of RNN examples are you looking for? I am familiar with the common example of text generation. I could probably modify it to suit the bucketing API with a bit of help.
The thing is, I am looking at this through a GSoC perspective and I need to show a bug fix to the R org admins before I can apply for improving mxnet.

**Comment by pluskid** [comment]
@shangjingbo1226 Any non-trivial RNN example should be fine. Just keep in mind that we already have a ptb text generation RNN example [here](https://github.com/dmlc/mxnet/tree/master/example/rnn). And there is also one version of it adapted to bucketing API in the same folder.

Implementing BPTT involves some interface designing and thinking about how to let recurrent nodes interact with non-recurrent nodes nicely. We have some preliminary design document. We can share you this or make the doc public when you decided to work on this (e.g. via GSoC).

**Comment by shwetamore1295** [comment]
@pluskid I will try to think of a non trivial example and port it to RNN. Can I port existing RNN example to Python? There are some interesting examples that I have read.
I will study more about BPTT and let you know.

**Comment by pluskid** [comment]
@shwetamore1295 Yes, definitely. Existing do you mean some existing implementation in other library / language?

**Comment by shwetamore1295** [comment]
@pluskid Yes, there are some blog posts in other libraries related to RNN which I remember reading. I can port over the non trivial ones to mxnet.

**Comment by pluskid** [comment]
@shwetamore1295 Yes, that is perfectly fine.

**Comment by shwetamore1295** [comment]
@pluskid [This](http://deeplearning.net/tutorial/rnnslu.html) is an example of RNN for Spoken Language Understanding. Should I port it?

**Comment by pluskid** [comment]
Sure!
