### ISSUE TITLE
Directly provide pre-trained models

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#377]
MXNet's recent development was several times more active than Caffe's. Pull requests in this project were reviewed and merged in days instead of in months.

https://github.com/dmlc/mxnet/pulse/monthly
https://github.com/BVLC/caffe/pulse/monthly
September 22, 2015 – October 22, 2015

Metrics | MXNet | Caffe
------------ | ------------- | -------------
Active Pull Requests | 154 | 52
Merged Pull Requests | 153 | 38
Proposed Pull Requests | 1 | 14
Authors Pushed Commits | 25 | 37
Commits Pushed to master | 422 | 48
Commits Pushed to All Branches | 1000 | 103
Files Changed on Master | 324 | 237
Additions on Master | 25,233 | 4,463
Deletions on Master | 2,904 | 1,896

On the other hand, Caffe had 6480 stars and 3714 forks with a fork vs. star ratio of 0.57 while MXNet had 669 stars and 186 forks with a ratio of 0.28 as of the time of writing. MXNet's active user conversion rate was only half of Caffe's.

Being able to easily download pre-trained models from a [centralized place](https://github.com/dmlc/mxnet/search?utf8=%E2%9C%93&q=model+zoo) was one of the key factors why Caffe became [so popular](https://github.com/search?o=desc&q=language%3Acpp&s=forks&type=Repositories&utf8=%E2%9C%93) because it greatly saved the user's time to get near the state of the art baseline feature extractors for further fine-tuning on their own datasets. Unfortunately, there's not yet a similar model zoo for MXNet. All that can be found now is just [a simple tool to convert Caffe models](https://github.com/dmlc/mxnet/blob/d8a619a6f96e2fc178c14c3fd42bceacc1c703e0/tools/caffe_converter/README.md).

MXNet should setup a model zoo as soon as possible to quickly increase the active users.

**Comment by antinucleon** [comment]
Thanks for advice! It's very valuable and informative.

We will move the pretrained model from [notebook](https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb) to some kind of model zoo this week. What's more, we will release a model trained on 21k classes.

**Comment by antinucleon** [comment]
Update: mxnet.readthedocs.org/en/latest/pretrained.html

**Comment by futurely** [comment]
Christian Szegedy, Julian Ibarz, and VincentVanhoucke. [Scene Classificationwith Inception-7](http://lsun.cs.princeton.edu/slides/Christian.pdf). [CVPR Large-scale Scene Understanding Challenge Workshop 2015](http://lsun.cs.princeton.edu/).
