### ISSUE TITLE
Multi-Loss on Model API

### ISSUE THREAD

**Issue by II-Matto** [dmlc/mxnet#381]
One may want to have several different losses for a network, e.g. k outputs for classification with softmax loss and m outputs for regression with Euclidean loss.

I guess it will also be desirable that weights of different losses can be adjusted. (Maybe even on the fly?)

**Comment by tqchen** [comment]
The multi loss is already supported in the symbolic API, the question is more on what can be done to make it easily available in the fit function.

**Comment by pluskid** [comment]
Multiple loss is already supported in the current `FeedForward` with the updated data iter API. Setting weights should also be possible by simply tweaking the `rescale_grad` parameter for each loss symbol.

**Comment by II-Matto** [comment]
@pluskid Thanks, I will try them in a few days!

**Comment by denghw** [comment]
I tryed multi-loss by adding another softmax layer. I name the two loss layers "softmax1" and "softmax2" respectively, and then I used mx.symbol.Group to combine them together. However, an error will occur saying that "argument name softmax_label not found" . I traced the error and found that the dataiter.provide_data contains "softmax_label" and I guess it's the problem. How could I get it over? 
@tqchen 

Another question: I used the parameter "rescale_grad" but the program advised me to use "grad_scale". Are they the same?
@pluskid 

Thanks a lot

**Comment by pluskid** [comment]
So the logic is if you have multiple loss, like "softmax1", and "softmax2", then you will need to provide labels for them in your data iterator, like "softmax1_label" and "softmax2_label". Otherwise, it does not know how to evaluate the losses.

**Comment by cocorecoco** [comment]
I try to add  another loss to the googlenet, but when I use the api of ImageRecordIO ,I found
ImageRecordIO only can  input one label_name , maybe "softmax1_label" or "softmax2_label",
but how can I add the two at the same time,  with the same label but different label name?
@pluskid
Thanks

**Comment by tqchen** [comment]
See https://github.com/dmlc/mxnet/blob/master/doc/python/io.md#extension-mutliple-labels-for-a-single-image

**Comment by ice-pice** [comment]
@tqchen as you pointed out, is it now possible to give grouped multi-loss to fit function?
I am trying to do the following:
`net1 = softmax_out(scores_aux, multi_output=True) 
net2 = softmax_out(scores, multi_output=True) 
net = mx.sym.Group((net1, net2)) 
mod = mx.mod.Module(net, context=contexts) `

After this when I call mod.fit, it gives me this error
>   File "issegm/voc_aux.py", line 459, in _train_impl
    mod.fit(
  File "/usr/local/mxnet/python/mxnet/module/base_module.py", line 388, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/mxnet/python/mxnet/module/module.py", line 345, in bind
    grad_req=grad_req)
  File "/usr/local/mxnet/python/mxnet/module/executor_group.py", line 187, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/mxnet/python/mxnet/module/executor_group.py", line 279, in bind_exec
    shared_group))
  File "/usr/local/mxnet/python/mxnet/module/executor_group.py", line 484, in _bind_ith_exec
    assert arg_shapes is not None, "shape inference failed"
AssertionError: shape inference failed

It seems fit function runs infer_shape internally which is failing here. 
If it's not supported yet, what other alternatives do I have to run multi-loss? 
I am fairly new to mxnet.

**Comment by ice-pice** [comment]
Answering my own question.
User should first make appropriate dataiter following https://github.com/haria/mxnet-multi-task-example/blob/master/multi-task.ipynb.

Since `FeedForward` has been deprecated, data_names and label_names can be specified this way:
```
mod = mx.mod.Module(net,data_names=('data',),label_names=('softmax_aux_label','softmax_label',), context=contexts);
```
The above is essential as mxnet by default recongnizes `softmax_label` as the only label layer.
