### ISSUE TITLE
Anyone can help on issue #3625

### ISSUE THREAD

**Issue by rflai** [dmlc/mxnet#3818]
i already shared the data website where i downloaded the CIFAR-10 binary data, and my R script by transfer the binary data into R array format and feed into a CNN model, the accuracy just couldn't go up, was always around 0.1. #3625

**Comment by rflai** [comment]
@mli @tqchen @thirdwing can you help to take a look? either it is a issue or some mistake i made for this. thanks in advance.

**Comment by thirdwing** [comment]
#3625 has been fixed. I am closing this now. Feel free to reopen.
