### ISSUE TITLE
How to predict with dropout on? (to simulate ensemble for uncertainty)

### ISSUE THREAD

**Issue by CharlieKirkwood** [dmlc/mxnet#3821]
Hi all, 

I would like to make predictions with dropout turned on - this will allow repeat predictions to build up a conditional probability distribution (http://mlg.eng.cam.ac.uk/yarin/blog_3d801aa532c1ce.html), providing information on prediction uncertainty. This would be extremely useful! 

It seems that dropout is turned off for prediction (predict.MXFeedForwardModel) by default. How can I turn it on for prediction? I'm using MXNet R package on windows. 

Many thanks.

**Comment by sxjscience** [comment]
Try to turn the training flags on when forwarding, i.e, use `forward(is_train=True)`

**Comment by CharlieKirkwood** [comment]
Thanks sxjscience, I'm afraid I'm fairly new to this and can't work out where to use that statement. I see in the R executor code we have:

>#' Peform an forward on the executors
>#' This function will MUTATE the state of exec
>#'
>#' @export
>mx.exec.forward <- function(exec, is.train=TRUE) {
>  exec$forward(is.train, list())
>}

But I don't know which is my 'exec' to perform the function on. My simplified code is as follows:

># Define the input data and network
>data <- mx.symbol.Variable("data")
>fc1 <- mx.symbol.FullyConnected(data, name="fc1", num_hidden=176)
>act1 <- mx.symbol.Activation(fc1, name="ReLU1", act_type="relu")
>drop1 <- mx.symbol.Dropout(act1, p=0.5)
>fcfinal <- mx.symbol.FullyConnected(drop1, name="fcfinal", num_hidden=1)

># Use linear regression for the output layer
>lro <- mx.symbol.LinearRegressionOutput(fcfinal)

># Train model
>model <- mx.model.FeedForward.create(*params*)

># Make predictions
>preds <- predict(model, testdata)[1,]

Where should I add 'forward(is_train=TRUE)'? 

Many thanks.

**Comment by sxjscience** [comment]
I'm not familiar with the R API and I suggest you look into the implementation of predict, which will call the `mx.exec.forward`. You can do that by chaning the `is.train` flag to true.

**Comment by CharlieKirkwood** [comment]
Your advice was exactly right, thank you very much. For anyone else using R, the procedure was as follows:

#See code behind predict:
getAnywhere(predict.MXFeedForwardModel)

#Create modified predict function:
predict.MXFeedForwardModel**Dropout** <- function (identical to predict.MXFeedForwardModel but with 'mx.exec.forward(pexec, is.train = **TRUE**)'

#Add the modified function to the mxnet namespace:
environment(predict.MXFeedForwardModel**Dropout**) <- asNamespace("mxnet")

#Then specify modified function when predicting:
preds <- predict.MXFeedForwardModel**Dropout**(model, testdata)[1,]

Predictions are now different realisations each time.
