### ISSUE TITLE
How to enable GPU P2P

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#3823]
When I train with several GPUs I get this warning:

```bash
src/kvstore/././comm.h:290: only 0 out of 12 GPU pairs are enabled direct access. It may affect the perofmrance. You can set MXNET_ENABLE_GPU_P2P=0 to turn it off
```
How can I enable the GPUs to have direct access?

**Comment by shuokay** [comment]
Try `export MXNET_ENABLE_GPU_P2P=1`

**Comment by miguelgfierro** [comment]
I tried that but is not working, I also tried to compile puting this flag in the `config.mk` but wasn't lucky either.

**Comment by piiswrong** [comment]
This means your GPU or motherboard doesn't support P2P

**Comment by miguelgfierro** [comment]
Thanks

**Comment by kli-nlpr** [comment]
[20:45:45] src/kvstore/././comm.h:577: only 4 out of 12 GPU pairs are enabled direct access. It may affect the performance. You can set MXNET_ENABLE_GPU_P2P=0 to turn it off

should I set  MXNET_ENABLE_GPU_P2P=0 ？

**Comment by SumNeuron** [comment]
I have 8 gpus and I get the message `only 32 out of 56 GPU pairs are enabled direct access. It may affect the performance. You can set MXNET_ENABLE_GPU_P2P=0 to turn it off`
so what do I do?
