### ISSUE TITLE
SSD example make error

### ISSUE THREAD

**Issue by zt706** [dmlc/mxnet#3830]
When I compiled mxnet with the ssd example, I got erro :

example/ssd/operator/./multibox_target-inl.h:129:179: 错误：对重载的‘VarsInfo(<brace-enclosed initializer list>)’的调用有歧义
DMLC_DECLARE_FIELD(variances).set_default(VarsInfo({0.1, 0.1, 0.2, 0.2}))

It looks like it is in my machine std::vector initialization method is not correct. I put the code into the following：
float my[] = {0.1,0.1,0.2,0.2};
std::vector<float> four (my, my + sizeof(my) / sizeof(float));
DMLC_DECLARE_FIELD(variances).set_default(VarsInfo(four))

If I'm wrong, please let me know.

My machine : 
g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)

**Comment by nopattern** [comment]
改成  VarsInfo({0.1f, 0.1f, 0.2f, 0.2f}

**Comment by piiswrong** [comment]
Could you confirm if the fix works? Would you like to submit a fix?

**Comment by nopattern** [comment]
This error existed in mxnet-ssd branch. I have tested. Could you tell me how to submit a fix ?

**Comment by zt706** [comment]
@nopattern 
This method does not work on my machine：
example/ssd/operator/./multibox_target-inl.h:129:137: 错误：对重载的‘VarsInfo(<brace-enclosed initializer list>)’的调用有歧义
 DMLC_DECLARE_FIELD(variances).set_default(VarsInfo({0.1f, 0.1f, 0.2f, 0.2f}))

The  definition of VarsInfo:
```cpp
struct VarsInfo {
    VarsInfo() {}
    explicit VarsInfo(std::vector<float> in) : info(in) {}
 
    std::vector<float> info;
  };  // struct VarsInfo
```

And the similar situations occur on : example/ssd/operator/multibox_detection-inl.h:115 and 
example/ssd/operator/multibox_prior-inl.h:117 and example/ssd/operator/multibox_prior-inl.h:120

I think construct from arrays should like this. (http://www.cplusplus.com/reference/vector/vector/vector/)
```cpp
// constructing vectors
#include <iostream>
#include <vector>

int main ()
{
  // constructors used in the same order as described above:
  std::vector<int> first;                                // empty vector of ints
  std::vector<int> second (4,100);                       // four ints with value 100
  std::vector<int> third (second.begin(),second.end());  // iterating through second
  std::vector<int> fourth (third);                       // a copy of third

  // the iterator constructor can also be used to construct from arrays:
  int myints[] = {16,2,77,29};
  std::vector<int> fifth (myints, myints + sizeof(myints) / sizeof(int) );

  std::cout << "The contents of fifth are:";
  for (std::vector<int>::iterator it = fifth.begin(); it != fifth.end(); ++it)
    std::cout << ' ' << *it;
  std::cout << '\n';

  return 0;
}
```
Where have I got it wrong?

**Comment by nopattern** [comment]
you may update your gcc.

**Comment by zhreshold** [comment]
This is related to the vector initialization, seems like some compiler are complaining about it.
DMLC_DECLARE_FIELD(variances).set_default(VarsInfo({0.1f, 0.1f, 0.2f, 0.2f})) should fix it.
I will submit a PR to solve it.

**Comment by zhreshold** [comment]
@piiswrong Is C++ 11 style initialization allowed in XXXOpParam ? Otherwise I have to change it.

**Comment by piiswrong** [comment]
It should be. But gcc 4.8 and 4.9 seem to have different level of error threshold

**Comment by zhreshold** [comment]
#3840 Submitted, should fix it.

**Comment by zt706** [comment]
I used cuda-7.0 on 1080 card, this is an error and 1080 card should use cuda-8.0.
I did not use new gcc
When I use cuda-8.0, the new code and old code are correct.
Thank you
-----
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
cuda-8.0
1080
