### ISSUE TITLE
Question about load_checkpoint/save_checkpoint

### ISSUE THREAD

**Issue by htung0101** [dmlc/mxnet#384]
I am using mx.model.load_checkpoint and save_checkpoint to store/restore my model. It seems like the gpu/cpu information will also be stored in the .params file. 
When I try to load it (probably on other machine or gpu), I basically create a mx.ndarray and then use "copyto" to pass the value I just loaded. So:

1. How can I load it by assigning them a device number? I cannot load it if I had trained it on gpu=3 and try to load it on a machine that has only one gpu (gpu = 0). 

2. How can delete the old value? So I won't touch the gpu that I am not planning to use. 

3. Sometime when I reload the model and try to use .asnumpy() to print out the results, it will cause segmentation fault on some servers (and some does not have this problem). Error message:

Program received signal SIGSEGV, Segmentation fault.
0x00000036ee8897cb in memcpy () from /lib64/libc.so.6

I can still print out .context and .shape, but asnumpy doesn't work. Thanks!!

**Comment by tqchen** [comment]
The checkpoint ndarrays are all on CPU, so you should be able to load them back.
I am not aware of the problem your mentioned in asnumpy, it would be nice if you can help provide more information. For example, Is the error reproducible? , what is the size of memory copy when the memcpy happend etc.

You can make local modification to the project, either reinstall the python, or simply add path to mxnet/python to python path so the recompiled project directly take effect

Thanks!

**Comment by htung0101** [comment]
Model parameter is about 500Mb, gpu is tesla k40 with 11519MiB. os is CentOS
Regarding the first question: does it mean I need to copy my parameter to cpu ndarrays before storing them? 

For the ndarray crash problem, I have tried to rebuild the code (with gcc 4.8.5 and gcc 4.9 for the previous version) and run it again, but it still produce the same result. But I Don't have this problem on a Ubuntu 4.8.2 machine.

**Comment by tqchen** [comment]
If the parameters are returned by fit, they are already in CPU, so you don't have to copy them. If you are training using low level interface, then probably you need to do the copy

**Comment by tqchen** [comment]
@htung0101 do you have any updates on this? If you can give us more information with the updated version of the mxnet, for example, use gdb to print the stack trace, maybe we could help figure out what is going on the failure case.
