### ISSUE TITLE
Use python six library?

### ISSUE THREAD

**Issue by leopd** [dmlc/mxnet#3857]
I just ran into an incompatibility between python 2 & 3.  In this case it was easy enough to work-around without any performance issues.  But in general these kinds of things are easier to deal with by using the python library "six" which gives a bunch of simple helper functions that work in both py2 & py3.

Any concerns with taking a dependency on six?  It's another library that people will need.  Or, because it's a single file, we could conceivably just be copy it into our codebase.  It's MIT licensed.

**Comment by piiswrong** [comment]
I considered using it but didn't want to add another dependency.
If you are sure the license permit us to put it in our repo I say we do it

**Comment by leopd** [comment]
I agree about an extra dependency.  I'll look into the licensing issues to see if we can just include the file directly.  If it looks like that's gonna work, I'll submit a PR.

**Comment by tqchen** [comment]
We do not have a lot of issues with python3 so far, and most of them could get around by using the helper functions defined in the _base.py

So let us see what are the functions that are get needed, if they are indeed helpful, we can always bring it in, or write a wrapper of ours

**Comment by leopd** [comment]
I might add a helper in `_base.py` next time I need something.  Thanks for the pointer.

I hit the fact that py3 doesn't have `dict.iteritems()` any more.  They both have `dict.items()` which works fine, but in py2 is slow for large dictionaries since it materializes the list.  But most of our dictionaries are config not data, so they're not big.
