### ISSUE TITLE
Access NDArray beyond axis 0

### ISSUE THREAD

**Issue by chaoyuaw** [dmlc/mxnet#3858]
I got segmentation fault when accessing entries in 2D nd-array, but couldn't figure out why. Can anyone help on this? Many thanks. 

>>> a = mx.nd.ones((100, 100))
>>> a[2][3]
<NDArray  @cpu(0)>
>>> a[2][3].asnumpy()
zsh: segmentation fault  python2.7

>>> a = mx.nd.ones((100, 100))
>>> b = a.reshape((10000,))
>>> b[200]
<NDArray  @cpu(0)>
>>> b[200].asnumpy()
zsh: segmentation fault  python2.7

Thanks.

**Comment by piiswrong** [comment]
This is a known bug and is fixed in the nnvm branch

**Comment by chaoyuaw** [comment]
I see. Thank you.
