### ISSUE TITLE
[Windows] compile error C2062

### ISSUE THREAD

**Issue by yunge** [dmlc/mxnet#386]
Win10 64bit, vs2013 update5, with Visual C++ Compiler Nov 2013 CTP, just followed Installation Guide.

error C2062: type 'const char' unexpected	...\include\mxnet\c_api.h	58
error C2062: type 'int' unexpected	...\include\mxnet\c_api.h	68
.....

cmake output:
-- The C compiler identification is MSVC 18.0.21114.0
-- The CXX compiler identification is MSVC 18.0.21114.0
-- Check for working C compiler using: Visual Studio 12 2013 Win64
-- Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64
-- Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Atlas: D:/weiyun/software/dev/OpenBLAS-v0.2.14-Win64-int32/include
-- Found Atlas (include: D:/weiyun/software/dev/OpenBLAS-v0.2.14-Win64-int32/include, library: D:/weiyun/software/dev/OpenBLAS-v0.2.14-Win64-int32/lib/libopenblas.dll)
-- CUDA detected: 7.5
-- Added CUDA NVCC flags for: sm_52
-- OpenCV found (D:/software/opencv/build)
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: /openmp
-- Found PythonInterp: C:/Python35/python.exe (found suitable version "3.5", minimum required is "2")
-- Found PythonInterp: C:/Python35/python.exe (found suitable version "3.5", minimum required is "3")
-- Found PythonInterp: C:/Python35/python.exe (found suitable version "3.5", minimum required is "2")
-- Found PythonInterp: C:/Python35/python.exe (found suitable version "3.5", minimum required is "3")
-- Configuring done
-- Generating done
-- Build files have been written to: c:/mxnetbuild

Please help, thanks.

**Comment by yang1fan2** [comment]
I met the same problem.
(In the file include/mxnet/c_api.h from line 16 to line 18, remove "__cdecl".)
i.e. change from
"
#define MXNET_DLL MXNET_EXTERN_C __cdecl __declspec(dllexport)
#else
#define MXNET_DLL MXNET_EXTERN_C __cdecl __declspec(dllimport)
"
to
"
#define MXNET_DLL MXNET_EXTERN_C __declspec(dllexport)
#else
#define MXNET_DLL MXNET_EXTERN_C __declspec(dllimport)
"

Hope this will help.

**Comment by tqchen** [comment]
hmm @hjk41 Can you look into this? Maybe the __cdel is not needed here?

**Comment by hjk41** [comment]
Let me check it out. I am assuming you are using VS 2013?

On Sun, Oct 25, 2015 at 1:13 PM, Tianqi Chen <notifications@github.com>
wrote:

> hmm @hjk41 <https://github.com/hjk41> Can you look into this? Maybe the
> __cdel is not needed here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/386#issuecomment-150892629>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by yunge** [comment]
Delete "__cdecl" works, thanks.

I use vs2013 update5 under win10 64bit.

Unfortunately, I got another compile problem, I'll report it later.

**Comment by hjk41** [comment]
fixed in #396 <https://github.com/dmlc/mxnet/pull/396>

On Mon, Oct 26, 2015 at 10:45 AM, Fu YunGe <notifications@github.com> wrote:

> Delete "__cdecl" works, thanks.
>
> I use vs2013 update5 under win10 64bit.
>
> Unfortunately, I got another compile problem, I'll report it later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/386#issuecomment-151006327>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
YunGe,

Could you pull the latest version and see if it fixes your problem?

Thanks,
chuntao

On Mon, Oct 26, 2015 at 11:28 AM, Chuntao HONG <chuntao.hong@gmail.com>
wrote:

> fixed in #396 <https://github.com/dmlc/mxnet/pull/396>
>
> On Mon, Oct 26, 2015 at 10:45 AM, Fu YunGe <notifications@github.com>
> wrote:
>
>> Delete "__cdecl" works, thanks.
>>
>> I use vs2013 update5 under win10 64bit.
>>
>> Unfortunately, I got another compile problem, I'll report it later.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dmlc/mxnet/issues/386#issuecomment-151006327>.
>>
>
>
>
> --
> HONG Chuntao
> System Research Group
> Microsoft Research Asia
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by sxjscience** [comment]
@hjk41 I've faced similar problem as @yunge and the new version fixes the issue. Now I'm able to compile and run MXNet on Windows (Only CPU).

I use Intel Parallel Studio Xe 2016 + VS2013 + OpenCV3.0 + Canopy. The `cmake` command should be like `cmake -DOpenCV_DIR=YOUR_OPENCV_DIR -DBLAS=MKL ..` and the resulting VS2013 project should be configured to 64 bit. Also, to make the python package find the dll, the [dll path generation code](https://github.com/dmlc/mxnet/blob/master/python/mxnet/libinfo.py#L18-L29) should be changed accordingly.  Moreover, since EPD has a pre-install openmp library that conflicts with the new MKL, I use the solution described [here](https://github.com/JoFrhwld/FAVE/wiki/Troubleshooting-FAVE-extract). 

Hope my experience can help others who are installing MXNet on Windows.

**Comment by hjk41** [comment]
Thanks @sxjscience, for the great summary!

On Mon, Oct 26, 2015 at 4:18 PM, sxjscience <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41> I've faced similar problem as @yunge
> <https://github.com/yunge> and the new version fixes the issue. Now I'm
> able to compile and run MXNet on Windows (Only CPU).
>
> I use Intel Parallel Studio Xe 2016 + VS2013 + OpenCV3.0 + Canopy. The
> cmake command should be like cmake -DOpenCV_DIR=YOUR_OPENCV_DIR
> -DBLAS=MKL .. and the resulting VS2013 project should be configured to 64
> bit. Also, to make the python package find the dll, the dll path
> generation code
> <https://github.com/dmlc/mxnet/blob/master/python/mxnet/libinfo.py#L18-L29>
> should be changed accordingly. Moreover, since EPD has a pre-install openmp
> library that conflicts with the new MKL, I use the solution described here
> <https://github.com/JoFrhwld/FAVE/wiki/Troubleshooting-FAVE-extract>.
>
> Hope my experience can help others who are installing MXNet on Windows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/386#issuecomment-151056975>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by yunge** [comment]
Hi, @hjk41 , everything is ok now, with openblas/cuda7.5, thanks!
