### ISSUE TITLE
MXNET R : GPU Build on Windows (EASY SETUP)

### ISSUE THREAD

**Issue by alvinjamur** [dmlc/mxnet#3860]
My friend build MXNET from scratch on Windows 10 for the GPU. 

You can download the zip file here

https://dl.dropboxusercontent.com/u/3153215/MXNET/mxnet_0.7.zip

All you have to do is go into R Studio then point at file and install package..... 
It should work....

**Comment by ameshkoff** [comment]
@alvinjamur I have tested your build. It works for me in CPU mode (as well as my own build) but crashes in GPU mode. R encounters a fatal error and crashes without any error message.
Which version of CUDA does it require? I tried both 7.5 and 8.0 with no success.

**Comment by alvinjamur** [comment]
Please try this file..

https://www.dropbox.com/s/5lnkd9ofz8akp2s/mxnet_0.7.zip?dl=0

**Comment by alvinjamur** [comment]
Please try this file..

https://www.dropbox.com/s/5lnkd9ofz8akp2s/mxnet_0.7.zip?dl=0

**Comment by ameshkoff** [comment]
@alvinjamur The same result, sorry. If you have tested it in GPU mode and it works, could you provide detail instructions? I have described my steps leading to (half)succesfull build [here](https://github.com/dmlc/mxnet/issues/3808#issuecomment-260743115) but my build works only in CPU mode.

@thirdwing Thanks for reply. The problem is I cannot build R-Package running with GPU on my own too. As I said it works only in CPU mode. I have tested CUDA samples and they work good so it cannot be a CUDA problem per se, rather of my own build.

With my build I encounter some warnings, these are the first lines. I cannot understand how to deal with it but maybe you can tell me what it could mean and where to dig.

> In file included from executor.cc:9:0:
> ./base.h: In function 'std::string mxnet::R::toPyString(const string&, const RObject&)':
> ./base.h:276:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
> ./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
> ./base.h:340:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
> executor.cc: In static member function 'static void mxnet::R::Executor::UpdateArray(const char*, const List&, Rcpp::List*, bool, bool)':
> executor.cc:43:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
> executor.cc: In static member function 'static Rcpp::List mxnet::R::Executor::CloneArray(const List&)':
> executor.cc:87:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
> executor.cc: In function 'Rcpp::List* mxnet::R::CreateArrayList(const List&, const string&, const std::vector<std::basic_string<char> >&, const RObjectType&, std::vector<void*>*)':
> executor.cc:123:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
> executor.cc: In function 'Rcpp::List* mxnet::R::CreateGradList(const List&, const List&, const std::vector<std::basic_string<char> >&, const RObjectType&, std::vector<void*>*, std::vector<unsigned int>*)':
> executor.cc:155:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>

**Comment by thirdwing** [comment]
I am afraid all lines you provided are warnings not errors.

**Comment by ameshkoff** [comment]
@thirdwing Yes they are. But is it OK to have these warnings during installations? Can they relate to GPU failure? I really don't know.

**Comment by ameshkoff** [comment]
OK, it looks like I figured out a problem. Actually it was not the installation problem but GPU out of memory. I should switch to NaiveEngine to catch errors and get "CUDA out of memory". Smaller datasets work fine both with NaiveEngine and multithreading.
