### ISSUE TITLE
Should I set label_shapes to None or [] when calling mx.module.bind if the network does not need label?

### ISSUE THREAD

**Issue by nicklhy** [dmlc/mxnet#3877]
If I set label_shapes to None, I get an error like:
```
File "/path-to-mxnet/mxnet/python/mxnet/module/module.py", line 269, in bind
    for item in label_shapes:
TypeError: 'NoneType' object is not iterable
```
If I set label_shapes to an empty list, I get an error when the DataParallelExecutorGroup attempts to slice this empty label shape list in "/path-to-mxnet/mxnet/python/mxnet/module/executor_group.py", line 170
```
if label_shapes is not None:
    self.label_layouts = self.decide_slices(label_shapes)
```

**Comment by piiswrong** [comment]
set it to None

the error is a bug that will be fixed by https://github.com/dmlc/mxnet/pull/3861
