### ISSUE TITLE
How do I set BucketingModule to make true that the input gradients can be computed?

### ISSUE THREAD

**Issue by yoosan** [dmlc/mxnet#3878]
I implement seq2seq learning with mxnet and I found that it is difficult to get the gradients of initial **h** and initial **c**, for the reason that **Embedding layer doesn't support calculate data gradient**.

We know the inputs of the decoder are **indices of input sequences** and the **initial hidden states**, which is the last hidden states of the encoder. So we want get the gradients of initial hidden states to make backpropagation for encoder. I have carefully read the BucketingModule but I can't find a way to get a good solution. 

HERE is my code:

    def build_lstm_decoder( self, is_train=True, bef_args=None):

        def gen_dec_sym( seq_len ):
            sym = lstm_unroll(1, seq_len,len(vocab),
                               num_hidden=self.hidden_size,
                               num_embed=self.embed_size,
                               num_label=len(vocab))
            data_names = ['data'] + ['l0_init_c', 'l0_init_h']
            label_names = ['softmax_label']
            return (sym, data_names, label_names)

        if is_train:
            decoder = mx.mod.BucketingModule(gen_dec_sym, default_bucket_key=self.seq_len+1, context=self.ctx)
            decoder.bind(data_shapes=[('data', (self.batch_size, self.seq_len + 1)),
                                      ('l0_init_c', (self.batch_size, self.hidden_size)),
                                      ('l0_init_h', (self.batch_size, self.hidden_size))],
                         label_shapes=[('softmax_label',(self.batch_size, self.seq_len + 1))],
                         for_training=is_train,inputs_need_grad=True)

            decoder.init_params(initializer=mx.init.Xavier(factor_type="in", magnitude=2.34), arg_params=bef_args)
            decoder.init_optimizer(
                optimizer='adam',
                optimizer_params={
                    'learning_rate': 0.02,
                    'wd': 0.,
                    'beta1': 0.5,
                })

and I test it by

    dec = model.build_lstm_decoder(is_train=True)
    init_h, init_c = mx.nd.zeros((10, 150)), mx.nd.zeros((10, 150))
    inp = mx.nd.ones((10, 26), ctx)
    tar = mx.nd.ones((10, 26), ctx)

    dec.forward(SimpleBatch(data_names=['data','l0_init_c', 'l0_init_h'], data=[inp, init_c, init_h],
                            label_names=['softmax_label'], label=[tar], bucket_key=inp.shape[1]))
    dec.backward()
    print dec.get_input_grads()[0].asnumpy()

**Comment by piiswrong** [comment]
pass grad_req to module.bind
specify 'write' for weights and h/c
specify 'null' for embeding layer input

**Comment by yoosan** [comment]
Thanks, but sadly say, the module.bind doesn't accept the grad_req as the argument. The error is 

TypeError: bind() got an unexpected keyword argument 'grad_req'

I have used the way of symbol.bind(grad_req=my_grad_req), it actually works. But the module does not support it...  
So I wonder why the inputs should be the args in MXNet. A network should be considered as a function, the inputs and outputs is external part and the parameters of network is internal part.

**Comment by piiswrong** [comment]
please update your code

**Comment by yoosan** [comment]
Great... I found it. 
I will close this issue. Thanks!!!

**Comment by yoosan** [comment]
Hi @piiswrong 

I still get the the error **Embedding layer doesn't support calculate data gradient** when I call backward of the decoder.

Here is my code, is there some wrong?

    def build_lstm_decoder( self, is_train=True, bef_args=None):
        basic_sym = lstm_unroll(1, self.seq_len,len(vocab), num_hidden=self.hidden_size,
                                num_embed=self.embed_size, num_label=len(vocab))
        grad_names = basic_sym.list_arguments()

        def gen_dec_sym( seq_len ):
            sym = lstm_unroll(1, seq_len,len(vocab),
                              num_hidden=self.hidden_size,
                              num_embed=self.embed_size,
                              num_label=len(vocab))
            data_names = ['data'] + ['l0_init_c', 'l0_init_h']
            label_names = ['softmax_label']
            return (sym, data_names, label_names)

        grad_req = {}
        for name in grad_names:
            if name in ['softmax_label', 'data']:
                grad_req[name] = 'null'
            else:
                grad_req[name] = 'write'
        if is_train:
            decoder = mx.mod.BucketingModule(gen_dec_sym, default_bucket_key=self.seq_len+1, context=self.ctx)
            decoder.bind(data_shapes=[('data', (self.batch_size, self.seq_len + 1)),
                                      ('l0_init_c', (self.batch_size, self.hidden_size)),
                                      ('l0_init_h', (self.batch_size, self.hidden_size))],
                         label_shapes=[('softmax_label',(self.batch_size, self.seq_len + 1))],
                         grad_req=grad_req,
                         for_training=is_train,inputs_need_grad=True)

            decoder.init_params(initializer=mx.init.Xavier(factor_type="in", magnitude=2.34), arg_params=bef_args)
            decoder.init_optimizer(
                optimizer='adam',
                optimizer_params={
                    'learning_rate': 0.02,
                    'wd': 0.,
                    'beta1': 0.5,
                })
