### ISSUE TITLE
How to get the output of other layers on Android?

### ISSUE THREAD

**Issue by flyingzhao** [dmlc/mxnet#3883]
I load my own model on android but i want to get features from the model instead of the last layer. I do this as following:

```
final float[] result = predictor.getOutput(-1);
or
final float[] result = predictor.getOutput(1);
```

But something wrong happens:

`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 23311 (AsyncTask #1)`

I also test in project "WhatThis", the same error occurs.

Could anyone give me some suggestions?

**Comment by tqchen** [comment]
You will need to rebuild the symbol, in python, use get internals api to get the corresponding output as output.  Get output only include the output nodes in the net.

**Comment by flyingzhao** [comment]
This means predictor.getOutput() can only get the last layer of the network. If i want to get other layer output, i need to modify the model in python so as to generate features in the last layer. Am i right?

**Comment by leopd** [comment]
I think we should make this easier from the high-level interfaces.  I've also found myself wanting to get different outputs from the computational graph for different reasons.

**Comment by tqchen** [comment]
see last block of https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb on how to do that in python.

You donot have to rebuild the model via python, but simply use get_internals to get that, and save the new json file.

**Comment by tqchen** [comment]
@leopd see last comment, this is indeed supported in high level api

**Comment by flyingzhao** [comment]
I will try.Thanks.

**Comment by flyingzhao** [comment]
I have tried again. That works for me. Thanks ! @tqchen @leopd

**Comment by leopd** [comment]
Thanks for the pointer, @tqchen.  I think that'll work for me too.  We should pull that up into some of the other tutorials.
