### ISSUE TITLE
Infer shape error in rhs argument

### ISSUE THREAD

**Issue by Andrjusha** [dmlc/mxnet#3886]
Hi guys, 

I'm composing a resnet model on the basis of "symbol_resnet.py" code. I added some pooling layers between the resnet blocks and now I got the following error:  InferShape Error in _plus4's rhs argument. When I change pad option in pooling layers or change number of filters in the conv layer, the number in the error message changes to another one (e.g. _plus8). With a certain number of the filters and pad option the error disappears. This is very strange, I don't understand why I can not choose those number of filters and padding which I want. It shouldn't be a problem. Could you please help me with this issue?

**Comment by piiswrong** [comment]
because when you add two tensors they need to have the same shape.
You need certain pad size to ensure that.

**Comment by Andrjusha** [comment]
Yes, thank you, finally all the problems were due to that, I've already figured that out
