### ISSUE TITLE
Instructions: Building MXnet on Windows with CUDA 8 and R support

### ISSUE THREAD

**Issue by flammit** [dmlc/mxnet#3902]
I put together a quick gist with instructions on how to get a working R package using CUDA 8 (for all of you who have Pascal architecture devices): https://gist.github.com/flammit/24a5e8b29c63f7fd5c9900176ad04062.  

Please let me know if there are any problems / clarifications and I can update it.

**Comment by alvinjamur** [comment]
Thank you, Francis!!

**Comment by piiswrong** [comment]
@sandeep-krishnamurthy Can we follow up on this?
Ideally we want a .bat script to build the latest master on windows with R

**Comment by sandeep-krishnamurthy** [comment]
Thanks Francis. I will follow up on this.

**Comment by thirdwing** [comment]
@sandeep-krishnamurthy Please follow my latest instruction from https://gist.github.com/thirdwing/89aa9bfc588ade138496e6932072152c

We have changed the R installation last year.

**Comment by sandeep-krishnamurthy** [comment]
@thirdwing - Can we get this instructions to our install page - http://mxnet.io/get_started/install.html ? I think you have added for CPU, similarly can you add for GPU?

**Comment by thirdwing** [comment]
@sandeep-krishnamurthy I will do that.
