### ISSUE TITLE
rcnn example: smooth L1 loss tends to be nan?

### ISSUE THREAD

**Issue by meanmee** [dmlc/mxnet#3904]
well, I don't understand why the codes in helper/dataset/load_pascal_annotation.py(load_pascal_annotation) need to be like this:

 for ix, obj in enumerate(objs):
            bbox = obj.find('bndbox')
            # Make pixel indexes 0-based
            x1 = float(bbox.find('xmin').text)  - 1
            y1 = float(bbox.find('ymin').text)  - 1
            x2 = float(bbox.find('xmax').text)  - 1
            y2 = float(bbox.find('ymax').text)  - 1
            cls = class_to_index[obj.find('name').text.lower().strip()]
            boxes[ix, :] = [x1, y1, x2, y2]
            gt_classes[ix] = cls
            overlaps[ix, cls] = 1.0

My question is why we need to -1 here, In my experiments it will generate some weird 65535 as the xmin number(not test the other three yet) into ***gt_roidb.pkl file. and then the training smooth L1 loss tends to be nan because of the codes below(helper/peocessing/bbox_transform.py(bbox_transform)):

    ex_widths = ex_rois[:, 2] - ex_rois[:, 0] + 1.0
    ex_heights = ex_rois[:, 3] - ex_rois[:, 1] + 1.0
    ex_ctr_x = ex_rois[:, 0] + 0.5 * (ex_widths - 1.0)
    ex_ctr_y = ex_rois[:, 1] + 0.5 * (ex_heights - 1.0)

    gt_widths = gt_rois[:, 2] - gt_rois[:, 0] + 1.0
    gt_heights = gt_rois[:, 3] - gt_rois[:, 1] + 1.0
    gt_ctr_x = gt_rois[:, 0] + 0.5 * (gt_widths - 1.0)
    gt_ctr_y = gt_rois[:, 1] + 0.5 * (gt_heights - 1.0)

    targets_dx = (gt_ctr_x - ex_ctr_x) / (ex_widths + 1e-14)
    targets_dy = (gt_ctr_y - ex_ctr_y) / (ex_heights + 1e-14)
    targets_dw = np.log(gt_widths / ex_widths)

    print gt_rois[:, 2]
    print gt_rois[:, 0]
    print gt_widths
    print ex_widths
    print gt_widths / ex_widths
    print targets_dw
    print '=' * 60
    targets_dh = np.log(gt_heights / ex_heights)

So I delete -1 in the previous codes and it works. but another problem is when it come to flip the dataset, the assert command tiggered(helper/peocessing/roidb.py(append_flipped_images))：

        for i in range(self.num_images):
            boxes = roidb[i]['boxes'].copy()
            oldx1 = boxes[:, 0].copy()
            oldx2 = boxes[:, 2].copy()
            boxes[:, 0] = widths[i] - oldx2 - 1
            boxes[:, 2] = widths[i] - oldx1 - 1
            assert (boxes[:, 2] >= boxes[:, 0]).all()
            entry = {'boxes': boxes,
                     'gt_classes': roidb[i]['gt_classes'],
                     'gt_overlaps': roidb[i]['gt_overlaps'],
                     'flipped': True}
            roidb.append(entry)

**Comment by meanmee** [comment]
@precedenceguo

**Comment by precedenceguo** [comment]
VOCdevkit is matlab code. matlab starts from 1. numpy starts from 0. UCar competition data starts from zero.

**Comment by meanmee** [comment]
that make sense!
