### ISSUE TITLE
Multi-task cnn model for sentences classification

### ISSUE THREAD

**Issue by R1ncy** [dmlc/mxnet#3908]
Hi, thanks for your attention. I use cnn to do some sentences classification.
The model structure is the same as /example/cnn_text_classification.
I try to modify it for multi-task classification following the #647.
There are two inputs and outputs of the model and share the hidden layers.

The acc is always around 50% for both train and test but it's nearly 77% when I use it for single task(#3776).
Under the guidance of paper "A Sensitivity Analysis of (and Practitioners’ Guide to) Convolutional Neural Networks for Sentence Classification", I change some params mentioned in it.
But the result almost has no change.
So I think whether the way I use the multi-task is wrong. 
Here is the code, could you please help me find out what's wrong with it?
Many thanks!
https://github.com/R1ncy/MxnetStudy/blob/master/cnn_model.py

**Comment by zihaolucky** [comment]
I suggest using high-level api to do this.
