### ISSUE TITLE
Table of contents redundantly displays title

### ISSUE THREAD

**Issue by andremoeller** [dmlc/mxnet#3910]
Example: http://mxnet.io/tutorials/index.html

"Tutorials" is under the table of contents, which is also the title of the page, making the Table of Contents crowded.

This looks especially weird on pages with a sparse Table of Contents: http://mxnet.io/api/python/index.html

**Comment by piiswrong** [comment]
BTW, I think on this page http://mxnet.io/tutorials/index.html we should make language the first level title and application categories the second level

**Comment by andremoeller** [comment]
Resolved.
