### ISSUE TITLE
Can mxnet support data slice ,as caffe used Slice(Slice_point)

### ISSUE THREAD

**Issue by liumilan** [dmlc/mxnet#3918]
data------> /data1------->fc layer1--------\
                                                                     \
                \   data2------->fc layer2----------->loss

i'd like to split data to 2 parts, and then concat in softmaxlayer
how can i split data? SliceChannel didn't offer the slice_point like caffe?

**Comment by piiswrong** [comment]
try slice_axis

**Comment by liumilan** [comment]
i can't find implement about slice_axis in new code.Where can i find?
https://github.com/dmlc/mxnet/issues/3577
from this link ,it said it is supported?
@piiswrong

**Comment by Ldpe2G** [comment]
@liumilan 
https://github.com/dmlc/mxnet/blob/master/src/operator/matrix_op-inl.h
line 843
