### ISSUE TITLE
could the webpage http://mxnet.io has a search engine?

### ISSUE THREAD

**Issue by JianboTang** [dmlc/mxnet#3919]
maybe I  miss something, but I have  tried to look after the search engine
search engine saves a lot of time,
would you mind adding a search engine to http://mxnet.io?

**Comment by kevinthesun** [comment]
Yes. How would we serve our backend? PHP?

**Comment by thesby** [comment]
lucene is a good choice, I think.

**Comment by pluskid** [comment]
How about using google directly? Like this:
https://www.google.com/search?newwindow=1&client=safari&rls=en&q=Embedding+site%3Amxnet.io&oq=Embedding+site%3Amxnet.io&gs_l=serp.3...12593.12777.0.13054.2.2.0.0.0.0.88.149.2.2.0....0...1c.1.64.serp..0.0.0.UJYjT2KgkaM

**Comment by piiswrong** [comment]
That's a quick thing we can do now. @Yao could you include it?

**Comment by kevinthesun** [comment]
Yes. I'll deal with this.

**Comment by kevinthesun** [comment]
Actually the search function has already been built in the index page. We only need to adjust the css to make it look nice.
