### ISSUE TITLE
onehot_encode dense format ?

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/mxnet#394]
Hi mxnet,

It seems that the current implementation of onehot_encode is to convert the indices to a DENSE one-hot representation. Should we change it to represent directly the embedding ?

Right now it seems that handle it using numpy directly and feed that embedding into NDArray is more efficient.

**Comment by tqchen** [comment]
Yes! This is something we should do

**Comment by pluskid** [comment]
Yes, some variant of `FullyConnected` as `Embedding` that takes directly one-hot index would be better. Something like [this](http://lasagne.readthedocs.org/en/latest/modules/layers/embedding.html) for example.

**Comment by Kublai-Jing** [comment]
where could I start working on this issue ? as what @pluskid  suggests ? Current implementation prevents us from creating long sequences lstm (memory will blow)

**Comment by antinucleon** [comment]
@Kublai-Jing I am working on taking embeding directly. Will PR back today or tomorrow.

**Comment by Kublai-Jing** [comment]
awesome !

**Comment by antinucleon** [comment]
After https://github.com/dmlc/mxnet/pull/654 merge, embedding problem seems will be solved.

**Comment by tqchen** [comment]
fixed by #654  Please check updated LSTM examples

**Comment by Kublai-Jing** [comment]
Actually I found that the embedding version is about 2 times slower than the original one. Is that normal ?
