### ISSUE TITLE
Why mxnet need all of Tensor, TBlob, TensorContainer and NDArray?

### ISSUE THREAD

**Issue by shuokay** [dmlc/mxnet#3951]
There are Tensor, TBlob, TensorContainer in mshadow, NDArray in mxnet what used for somehow the same purpose, is there anyone can explain why mxnet need all these four classes and when will we use them separately?

**Comment by tqchen** [comment]
They are different. here is the abstraction from highest to lowestly level

- NDArray is a data container that can be scheduled asynchronizely
- TBlob is a "pointer" reference to the content of the data, which is convenient to define synchronize kernels

Both NDArray and TBlob are essential to the project. The use of mshadow::Tensor and TensorContainer is for quickly implement the operator kernels. They are not essential part of the project if the kernels are implemented directly in CUDA/C++, but they are helpful to do these implementations

**Comment by shuokay** [comment]
Got it, thanks
