### ISSUE TITLE
Use node name instead of node id to configure operator inputs

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#397]
Compared with `"inputs": [[461, 0], [475, 0], [496, 0], [504, 0]]`, `"inputs": [["relu_5b_double_3x3_reduce", 0], ["conv_5b_double_3x3_0", 0], ["relu_5b_double_3x3_1", 0], ["max_pool_5b_pool", 0]]` would be much more readable and easier to debug. Even simpler usage is `"inputs": ["relu_5b_double_3x3_reduce", "conv_5b_double_3x3_0", "relu_5b_double_3x3_1", "max_pool_5b_pool"]`.

**Comment by tqchen** [comment]
The json file was not meant to be edited manually. Instead the symbolic API can be used to load things in and compose these structures. For configuration files, if we want something related, we might want to support a more readable format

**Comment by futurely** [comment]
https://github.com/Yangqing/caffe2/blob/master/caffe/proto/caffe.proto
