### ISSUE TITLE
libhdfs.so.0.0.0 can't be located when install mxnet package on R-3.3.1

### ISSUE THREAD

**Issue by alexwwang** [dmlc/mxnet#3974]
I compiled a mxnet with hdfs support and it seems successful when installed on python but while I tried to install on R, in the final step error rose and said libhdfs.so.0.0.0 cannot open when load libmxnet.so in libPaths. Detailed is illustrated as the screenshot below.

![image](https://cloud.githubusercontent.com/assets/856746/20614406/13a4a706-b309-11e6-9f90-743df4497e84.png)

I did these on Ubuntu16.04 with locally compiled R-3.3.1 and mkl linked. Also linked mkl to mxnet while compiling the libmxnet.so.

I've export $HADOOP_HOME/lib/native in which libhdfs.so.0.0.0 located to LD_LIBRARY_PATH in both the system vars and Rprofile.site but does not work.

Hope for a solution.
Thx.

**Comment by alexwwang** [comment]
curiously I've solved it.
Should set LD_LIBRARY_PATH=/usr/local/hadoop/lib/native without var evaluation expression such as $HADOOP_HOME/lib/native, later doesn't work in Rprofile.site

Meanwhile I have no idea if I could cp this compiled package to system lib such as /usr/local/lib64/R/library and if the GPU edition mxnet R could be built and installed on ubuntu since I didn't find issues referred in the online manual or instruction.

**Comment by alexwwang** [comment]
update 3:
although it was installed without error but the same one occurred while I load it. See as follow:
![image](https://cloud.githubusercontent.com/assets/856746/20614627/b74f6894-b30b-11e6-8998-3bf047a26b64.png)

it's really confusing.

**Comment by miguelgfierro** [comment]
I would try to do a symbolic link to `libhdfs.so` and `libhdfs.so.0`. Also I would make sure that the library is in the `LD_LIBRARY_PATH`.

**Comment by alexwwang** [comment]
thanks but the fact is I have made sure the library is in the LD_LIBRARY_PATH when launch R, maybe file is not under the direct level but sub-direction, however the error still came out.
I have to disable this feature while compilation now.

**Comment by miguelgfierro** [comment]
Sometimes the library path of the system is different to the R environment, do you have the library when you do: `Sys.getenv('LD_LIBRARY_PATH')`?

**Comment by alexwwang** [comment]
Yes. I checked it. That's why I'm confused.

**Comment by miguelgfierro** [comment]
In that case I would do a symbolic link to `/lib`. There errors are very common but usually solvable.

**Comment by alexwwang** [comment]
So is it. I will have a try later. Thank you for your kindly advising. :)
One more thing, should I set LD_LIBRARY_PATH in this case and how? Thanks
again.
