### ISSUE TITLE
Flipped images in the provided Cifar10 dataset 

### ISSUE THREAD

**Issue by zlmzju** [dmlc/mxnet#3975]
I find that the images in http://data.mxnet.io/mxnet/data/cifar10.zip were vertically flipped, which are different from my generated `rec` data.

Here is my code for visualization:

```python
def get_iterator(data_dir):
    data_iter = mx.io.ImageRecordIter(
        data_shape=(3, 32, 32),
        path_imgrec = data_dir,
        batch_size=128,
    )
    return data_iter

train_iter=get_iterator(data_dir='cifar10/train.rec')

X_data = train_iter.getdata().asnumpy()
print X_data.shape

plt.figure(figsize=(10,2))
for i in range(5):
    plt.subplot(1,5,i+1)
    X = X_data[i].transpose((1, 2, 0))
    plt.axis('off')
    plt.imshow(X.astype(np.uint8))
```

Then outputs:
![y e 3u54t 7gp44hlg](https://cloud.githubusercontent.com/assets/10279606/20615066/d5f0f484-b310-11e6-9973-1ba90af4240a.jpg)

I think it's better to use the original data for training.
Please help to check it. @piiswrong @tornadomeet

**Comment by zhreshold** [comment]
Confirmed. All images are upside-down in the rec files, including train.rec and test.rec

**Comment by zlmzju** [comment]
Thanks, @zhreshold . Should we fix the problem? The examples on Cifar10 probably could achieve better results with the original data. My generated `rec` files are available [here](https://drive.google.com/drive/folders/0By55MQnF3PHCQmRhRTBuWk5DRkk).

**Comment by tornadomeet** [comment]
thanks, i'll check it tody.
@zlmzju what's the quality of your `.rec` file? i'll replace it with your file after i check.

**Comment by zlmzju** [comment]
@tornadomeet , I use the `png` format with  `cv2.IMWRITE_PNG_COMPRESSION=0`.

**Comment by tornadomeet** [comment]
@zlmzju hello, can you put the rec in baidu yun? download from google is too slow!

**Comment by zlmzju** [comment]
@tornadomeet , ok, I will upload the files to baidu yun. It will take some time because the network gateway in the company is not located in China

**Comment by zlmzju** [comment]
@tornadomeet http://pan.baidu.com/s/1c2EB6hU

**Comment by tornadomeet** [comment]
@zlmzju  thanks , i have upload it to http://data.dmlc.ml/mxnet/data/
