### ISSUE TITLE
Question about distributed training

### ISSUE THREAD

**Issue by mzmssg** [dmlc/mxnet#3978]
The official [tutorials](http://mxnet.io/how_to/multi_devices.html)  says we can train one net with multi machine by the commond
`../../tools/launch.py -n 2 -H hosts --sync-dst-dir /tmp/mxnet 
   python train_mnist.py --network lenet --kv-store dist_sync
`
Does that means we don't need compile the code on every machine? I do all the steps as tutorials, but mxnet will report errors unless the version of library strictly match on every machine. 
So I recompile mxnet on every machine, it don't report errors neither work, just stuck the shell,  I check the process by `ps aux` and there is indeed process whose command is `python train_mnist.py --network lenet --kv-store dist_sync` but its status is Sl. Could anyone give me more detailed information about training distributed

**Comment by piiswrong** [comment]
launch.py copies mxnet installation to all machines. You need to make sure PYTHONPATH point to /tmp/mxnet/python on all machiens

**Comment by mzmssg** [comment]
Sorry, I have tried your method but it doesn't work. I read `ssh.py` in `dmlc_core` and I find it will export the `LD_LIBRARY_PATH` on master to the slaves' env. And I check the `libmxnet.so` by command `ldd`, which shows `libmxnet.so` need many `xx.so` files such as `libcudnn.so`, `libprotobuf.so`. Doesn't that mean `/tmp/mxnet/python` isn't integral? And I try to copy all `xx.so` files `libmxnet.so` needs from master to slave, it react same as the scene I recompile mxnet on slave machine. Can you give me more tips about the problem? Thank you for your further help.

**Comment by mli** [comment]
libcudnn.so is not copied in default. i think you can put it on the same folder as libmxnet.so. so it will be synced to all worker machines
