### ISSUE TITLE
what is the definition of shape in mxnet

### ISSUE THREAD

**Issue by liumilan** [dmlc/mxnet#3979]
In caffe,it is defined N*C*W*H
In mxnet it seemed different?
For example,i just passed the data iterator(200,)data dim is 200
and then it will log as  (100,1,200) 100 means batchsize
why it is not 100,200,1,1?

**Comment by antinucleon** [comment]
It is NCHW. But in future we will support NHWC as well. In your case it is (100, 200, 1, 1)

**Comment by liumilan** [comment]
I am still some confused.if it is NCHW,why it will log (100L, 1L, 200L) when i add some logs in symbol.py _infer_shape_impl function ,
for k, v in kwargs.items():
                if isinstance(v, tuple):
                    logging.info(k)
                    logging.info(v)
it should logging (100L,200L,1L,1L)
could you help to explain it?
@antinucleon
