### ISSUE TITLE
what is the usage of concat?

### ISSUE THREAD

**Issue by liumilan** [dmlc/mxnet#3980]
Here is my network
 input=mx.symbol.Variable('data')
    input1=mx.symbol.slice_axis(data=input,axis=2,begin=0,end=187)
    input2=mx.symbol.slice_axis(data=input,axis=2,begin=188,end=287)

    ip1=mx.symbol.FullyConnected(data=input1, name="ip1", num_hidden=200)
    relu1=mx.symbol.Activation(data=ip1, act_type="relu", name="relu1")
    ip2=mx.symbol.FullyConnected(data=relu1, name="ip2", num_hidden=100)
    relu2=mx.symbol.Activation(data=ip2, act_type="relu", name="relu2")
    ip3=mx.symbol.FullyConnected(data=relu2, name="ip3", num_hidden=16)
    relu3=mx.symbol.Activation(data=ip3, act_type="relu", name="relu3")
    #concat layer
    concat_input = mx.symbol.Concat(*[relu3,input2],dim=2)
    ip5=mx.symbol.FullyConnected(data=concat_input, name="ip5", num_hidden=2)
    net=mx.symbol.SoftmaxOutput(data=ip5, name="softmax")
and it report 
[21:19:46] /search/data/mxnet/dmlc-core/include/dmlc/logging.h:235: [21:19:46] src/operator/./concat-inl.h:144: Check failed: (static_cast<index_t>(
param_.dim)) < (dshape.ndim()) the dimension to be concated is not in the range of input's dimension
how can i correct it?

**Comment by piiswrong** [comment]
Your input is two dimensional, you can only concat on dim 0 or 1

**Comment by liumilan** [comment]
if it was specified 1 ,it will report [21:22:31] src/engine/./threaded_engine.h:306: [21:22:31] include/mxnet/././tensor_blob.
h:742: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
if it is specified to 0,it will report 
src/operator/./concat-inl.h:153: Check failed: (d
shape[j]) == (tmp[j]) Incorrect shape[1]: (80000,1,99). (first input shape: (160000,16))

what is the defination of shape? N*C*W*H?
@piiswrong
