### ISSUE TITLE
Question about mshadow::broadcast_to

### ISSUE THREAD

**Issue by feiyulv** [dmlc/mxnet#3982]
I find broadcast_to function in the extension dir [https://github.com/dmlc/mshadow/blob/bb0f8c7b8e5411299b01cf888970be2230fdf762/mshadow/extension/broadcast_with_axis.h](url)
I want to use it like this:
```
Tensor<gpu, 1> a = NewTensor<gpu, 1>(Shape1(1), 0.0f)
Tensor<gpu, 2> b = NewTensor<gpu,2>(Shape2(100,100), 0.0f)
Vector(a, b, b)
b /= broadcast_to(a, b.shape_)
```
However this code can't work. Is there any other way to broadcast a Tensor with Shap1(1) to various shape?

**Comment by piiswrong** [comment]
broadcast then reshape

**Comment by feiyulv** [comment]
@piiswrong , thx, make shape2(1,1) still desn't work. It seems `broadcast_to` accept TShape as its parameter. Currently, I use the `broadcast` function instead.

**Comment by sxjscience** [comment]
@feiyulv Try TShape(Shape2(1, 1))
