### ISSUE TITLE
Error running train_mnist.py

### ISSUE THREAD

**Issue by john7farrell** [dmlc/mxnet#3988]
Hey, I'm new to mxnet, and when I'm running *mxnet/example/image-classification/train_mnist.py*, I got following error messages:
> $ python train_mnist.py
> 2016-11-26 19:30:44,409 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000, save_model_prefix=None)
> [19:30:46] D:\chhong\mxnet\src\io\iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
> [19:30:47] D:\chhong\mxnet\src\io\iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
> Traceback (most recent call last):
>   File "train_mnist.py", line 164, in <module>
>     train_model.fit(args, net, get_iterator(data_shape))
>   File "C:\mxnet-gpu\example\image-classification\train_model.py", line 92, in fit
>     if args.benchmark:
> AttributeError: 'Namespace' object has no attribute 'benchmark'

So I add a line in function *parse_args()*:
> def parse_args():
> ...
>     parser.add_argument('--benchmark', type=bool, default=False, help='to avoid the error')
> return parser.parse_args()

and it works for now:
> $ python train_mnist.py
> 2016-11-26 20:53:49,938 Node[0] start with arguments Namespace(batch_size=128, benchmark=False, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000, save_model_prefix=None)
> [20:53:52] D:\chhong\mxnet\src\io\iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
> [20:53:52] D:\chhong\mxnet\src\io\iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
> 2016-11-26 20:53:52,700 Node[0] Start training with [cpu(0)]
> 2016-11-26 20:53:52,896 Node[0] Epoch[0] Batch [50]     Speed: 34312.04 samples/sec     Train-accuracy=0.719063
> 2016-11-26 20:53:52,896 Node[0] Epoch[0] Batch [50]     Speed: 34312.04 samples/sec     Train-top_k_accuracy_5=0.943594
> 2016-11-26 20:53:52,896 Node[0] Epoch[0] Batch [50]     Speed: 34312.04 samples/sec     Train-top_k_accuracy_10=1.000000
> 2016-11-26 20:53:52,896 Node[0] Epoch[0] Batch [50]     Speed: 34312.04 samples/sec     Train-top_k_accuracy_20=1.000000
> 2016-11-26 20:53:53,085 Node[0] Epoch[0] Batch [100]    Speed: 34038.16 samples/sec     Train-accuracy=0.896406
> 2016-11-26 20:53:53,085 Node[0] Epoch[0] Batch [100]    Speed: 34038.16 samples/sec     Train-top_k_accuracy_5=0.993750
> 2016-11-26 20:53:53,085 Node[0] Epoch[0] Batch [100]    Speed: 34038.16 samples/sec     Train-top_k_accuracy_10=1.000000
> 2016-11-26 20:53:53,085 Node[0] Epoch[0] Batch [100]    Speed: 34038.16 samples/sec     Train-top_k_accuracy_20=1.000000

And if change it to *default=True*, the result will be very bad.
Still I don't understand the reason behind this.

**Comment by madcarrot** [comment]
Thanks for posting the solution! I met the exact same problem and your solution works for me.

**Comment by john7farrell** [comment]
@madcarrot 
Please follow the latest commit of *mxnet/example/image-classification/*. 
It should be addressed now : )
