### ISSUE TITLE
A problem about parameter passing in train_model.py

### ISSUE THREAD

**Issue by wanderingpj** [dmlc/mxnet#3991]
In train_model.py , we create a object named model using "mx.model.FeedForward ", and we pass these parameters : learning_rate , momentum , wd . But in model.py , there is no initialization of these 3 parameters in "def __init__ "of class FeedForward. And I cannot find the parameters anywhere in model.py. So how do these parameters work in model.py?

**Comment by zlmzju** [comment]
@wanderingpj , they are used in the optimizer, please see https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L793

**Comment by wanderingpj** [comment]
@zlmzju ，since we have passed the parameter **model_args which include the learning_rate , why do we pass learning_rate again?

**Comment by zlmzju** [comment]
@wanderingpj so this is another question, right? And please tell me the evidence or the url.

**Comment by wanderingpj** [comment]
@zlmzju  https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L84

**Comment by wanderingpj** [comment]
we use model_args in line 84 , but never use learning_rate in line 80.

**Comment by zlmzju** [comment]
Ok, I know what you mean.  I suggest that you can first study to [understand what `**kwargs` means in Python](http://stackoverflow.com/questions/1769403/understanding-kwargs-in-python).

**Comment by wanderingpj** [comment]
@zlmzju Fine , I will learn it first . I have one more question . We use

"        model_args['lr_scheduler'] = mx.lr_scheduler.FactorScheduler(
            step = max(int(epoch_size * args.lr_factor_epoch), 1),
            factor = args.lr_factor)
"
to update lr , but we didn't pass the parameter of lr to FactorScheduler , how does it get the base_lr and change it?
https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L64

**Comment by wanderingpj** [comment]
@zlmzju  After reading what you suggest , I know the answer of my second question . Thank you very much !
