### ISSUE TITLE
[R] Install latest version on Windows with GPU: onLoad failed

### ISSUE THREAD

**Issue by ameshkoff** [dmlc/mxnet#3992]
Trying to install latest version of MXNet R-Package on Windows I get en error `.onLoad failed in loadNamespace() for 'mxnet'` on the final step (testing if installed package can be loaded). I read some older issues here and set environment variable LD_LIBRARY_PATH but it didn't help.

I use [this](https://github.com/yajiedesign/mxnet/releases/tag/20161125) source code + binaries + my CUDA CUDnn files (cudnn library and some others). Configuration: Windows 10 x64 Home.

The exact error message (with some my translation to English):

> c:\mxnet-20161125>R CMD INSTALL --no-multiarch R-package
> * installing to library 'C:/Users/[home dir]/Documents/R/win-library/3.3'
> * installing *source* package 'mxnet' ...
> ** libs
> make: Nothing to be done for `all'.
> installing to C:/Users/[home dir]/Documents/R/win-library/3.3/mxnet/libs/x64
> ** R
> ** demo
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
> ** building package indices
> ** installing vignettes
> ** testing if installed package can be loaded
> Error : .onLoad failed in loadNamespace() for 'mxnet', details:
>   call: inDL(x, as.logical(local), as.logical(now), ...)
>   error: cannot load shared object 'C:/Users/[home dir]/Documents/R/win-library/3.3/mxnet/libs/x64/libmxnet.dll':
>   LoadLibrary failure:  Not found
> 
> Error: loading failed
> Execution stopped
> ERROR: loading failed
> * removing 'C:/Users/[home dir]/Documents/R/win-library/3.3/mxnet'
> * restoring previous 'C:/Users/[home dir]/Documents/R/win-library/3.3/mxnet'
> 

Previously I successfully compiled and installed R-Package stable version from 31. May 2016 but with newest versions I for some reasons run in troubles.

Thanks for advance.

**Comment by piiswrong** [comment]
@thirdwing @tqchen @miguelgfierro

**Comment by miguelgfierro** [comment]
Hi @ameshkoff, the variable `LD_LIBRARY_PATH` is for Linux, not windows. In my experience with precompiled versions, one source of problems is that you might not be using the same external libraries version as the person who compiled the original (i.e. same CUDA version). Also, please note that in the [precompiled](https://github.com/yajiedesign/mxnet/releases/tag/20161125) there is not `3rdparty` folder, while in the official mxnet release there is.

**Comment by ameshkoff** [comment]
Hi @miguelgfierro 

I got libraries from `3rdparty` directory from the official release. I tried replacing not only cudnn library but  a couple of other CUDA libraries (cudart etc.) with no success.

Also, I tried different versions of CUDA (7.5, 8.0) and CUDnn as well (from 3 to 5.1). What looks especially odd for me, I have successfully compiled R-package from 2016-05-31 release and even with different CUDA versions (both 7.5 and 8.0).

Should I compile libmxnet.dll library by myself before compiling R-Package?

P.S. In the log placed above "libs" are compiled in previous tryings. This step (compiling itself) was always successful although with a bunch of warnings. But with 2016-05-31 release I got many warnings as well and all works pretty good.

**Comment by miguelgfierro** [comment]
I would try to compile myself. Another idea is to ask the author for the details

**Comment by ameshkoff** [comment]
Sorry for so long waiting time. I just compiled libmxnet.dll but I stil got the same error trying install R-Package.

> Error : .onLoad failed in loadNamespace() for 'mxnet', details:
> call: inDL(x, as.logical(local), as.logical(now), ...)
> error: cannot load shared object 'C:/Users/[home dir]/Documents/R/win-library/3.3/mxnet/libs/x64/libmxnet.dll':
> LoadLibrary failure: Not found

Please please please help!

**Comment by thirdwing** [comment]
Can you show your folder structure in your package?

On Dec 17, 2016 10:08 AM, "Aleksandr Meshkov" <notifications@github.com>
wrote:

Sorry for so long waiting time. I just compiled libmxnet.dll but I stil got
the same error trying install R-Package.

Error : .onLoad failed in loadNamespace() for 'mxnet', details:
call: inDL(x, as.logical(local), as.logical(now), ...)
error: cannot load shared object 'C:/Users/[home
dir]/Documents/R/win-library/3.3/mxnet/libs/x64/libmxnet.dll':
LoadLibrary failure: Not found

Please please please help!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dmlc/mxnet/issues/3992#issuecomment-267767559>, or mute
the thread

**Comment by ameshkoff** [comment]
@thirdwing 

R-package/inst/
R-package/inst/include
R-package/inst/include/dmlc (here some .h C files)
R-package/inst/include/mshadow (here some .h C files)
R-package/inst/include/mxnet (here some .h C files)
R-package/inst/libs
R-package/inst/libs/x64

R-package/inst/libs/x64 files:

12.09.2016  23:49        40 744 896 cublas64_80.dll
05.09.2016  17:51           366 016 cudart64_80.dll
18.11.2016  22:28        78 389 760 cudnn64_5.dll
05.09.2016  17:51        47 985 208 curand64_80.dll
26.11.2016  20:50            82 432 libgcc_s_seh-1.dll
26.11.2016  20:50         1 279 488 libgfortran-3.dll
17.12.2016  17:51       170 027 520 libmxnet.dll
26.11.2016  20:50        38 340 126 libopenblas.dll
26.11.2016  20:50           331 776 libquadmath-0.dll
05.09.2016  17:51        14 936 576 nvrtc64_80.dll
26.11.2016  20:49           162 816 unzip32.dll
26.11.2016  20:50           137 376 vcomp120.dll

**Comment by ameshkoff** [comment]
Fantastic! I removed `--no-multiarch` from the installation command and all worked like a charm. So my `cmd` command was: `R CMD INSTALL R-package`. Maybe we should try both variants with and without `multiarch` to find out which one fits.
