### ISSUE TITLE
did not find the train.lst from the package 

### ISSUE THREAD

**Issue by liyin2015** [dmlc/mxnet#4004]
No such file or directory: 'VOCdevkit/VOC2012/train.lst'

**Comment by tornadomeet** [comment]
which example? fcn-xs or faster-rcnn?   
if you mean fcn-xs, then you can download `train.lst` from https://pan.baidu.com/s/1bgz4PC#list/path=%2Ffcn-xs .  
if mean faster-rcnn, then there is no need `train.lst`

**Comment by liyin2015** [comment]
Yea, I fixed this one by downloading those files. However, I got another problem. I am not sure how to refill these two parameters. fcnxs_model_prefix = "model_pascal/FCN32s_VGG16" and flist_name = "train.lst"

**Comment by liyin2015** [comment]
my gpu only has 4GB memory. Now it tells me that its out of memory. I wonder how could I solve this problem?

**Comment by miguelgfierro** [comment]
You can try to reduce the batch size
