### ISSUE TITLE
No attribute ‘CuDNNBatchNorm’

### ISSUE THREAD

**Issue by Hatuw** [dmlc/mxnet#4010]
Hi, I want to run the demo "mxnet/example/gan/dcgan.py", but an AttributeError occured : "‘module’ object has no attribute 'CuDNNBatchNorm'". But I think the mxnet had build successfully(I tried to run the demo "image-classification", it worked). How should I fixed this error?tks~

**Comment by tqchen** [comment]
you can change that to BatchNorm

**Comment by tqchen** [comment]
Thanks for pointing this out.the example is updated to reflect this change
