### ISSUE TITLE
how communication overlapped with computing 

### ISSUE THREAD

**Issue by qianglan** [dmlc/mxnet#402]
Hi, 
I have tried using GPU to train, and using computeprof tool to profile the performance of MXnet, and I found that when I use one GPU, there is no communication and computation overlapped, however when I used 2 GPUs or 4 GPUs, there are communication and computation overlapped. I want to know 
1) why there are no communication and computation overlapped in on GPU case?
2) what kind of communication(trained batch or gradient array or model parameters) and what kind of computation which are overlapped in two GPUs?

**Comment by mli** [comment]
on the multiple gpus case, each gpu computes the gradient for batch_size / num_gpu examples in an iteration, then gradient are aggregated by communication. https://github.com/dmlc/mxnet/blob/master/doc/developer-guide/multi_node.md#multiple-devices-on-a-single-machine

**Comment by qianglan** [comment]
Thanks
