### ISSUE TITLE
Referencing and Slicing Elements of NDArray

### ISSUE THREAD

**Issue by WellyZhang** [dmlc/mxnet#4020]
Hey guys,

Any way to reference a single element or slice an NDArray? I got an error runing the following code.

```python
t = mx.nd.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]])
print t[1, 1]
print t[1, :]
```

```python
ValueError                                Traceback (most recent call last)
<ipython-input-9-fc95744a9ebc> in <module>()
----> 1 print t[1, 1]

/home/data/czhangbr/anaconda2/lib/python2.7/site-packages/mxnet/ndarray.pyc in __getitem__(self, in_slice)
    297             return self._at(in_slice)
    298         if not isinstance(in_slice, slice) or in_slice.step is not None:
--> 299             raise ValueError('NDArray only support continuous slicing on axis 0')
    300         if in_slice.start is not None or in_slice.stop is not None:
    301             return self._slice(in_slice.start, in_slice.stop)

ValueError: NDArray only support continuous slicing on axis 0
```

**Comment by piiswrong** [comment]
use asnumpy() to copy it to cpu first.

**Comment by sxjscience** [comment]
@piiswrong Should we plan to support it in the future?

**Comment by WellyZhang** [comment]
I know this as workaround. But actually, I was considering assignment on GPU on the fly.

**Comment by piiswrong** [comment]
It's imposible. You cannot directly access memory on gpu

**Comment by WellyZhang** [comment]
In fact, it was not the print that causes my problem. 

It's the following case:

code like
```python
t[0, 1] = 1
t[0, :] = 1
```
works

while code like
```python
q = t[0, 1]
q = t[0, :]
```
fails

Sorry not to make it clear in the beginning.

**Comment by sxjscience** [comment]
@WellyZhang __setitem__ support this but __getitem__  does not https://github.com/dmlc/mxnet/blob/master/python/mxnet/ndarray.py#L210-L298

**Comment by WellyZhang** [comment]
Well noted with thanks.
