### ISSUE TITLE
How to obtain L2 norm of a ndarray?

### ISSUE THREAD

**Issue by yang1fan2** [dmlc/mxnet#403]
Hi,
I am trying to clip the norm of the gradients, when training rnn. Is there a convenient way to get norm of a ndarray (except converting to numpy)?

thanks;

**Comment by tqchen** [comment]
add by #405

**Comment by tqchen** [comment]
@yang1fan2 can u try it it now works for you?
```
# This gives an (1,) mx.ndarray
a = mx.nd.norm(array)
# This gives you scalar
a.asscalar()
```

**Comment by yang1fan2** [comment]
@tqchen sorry for late reply
mx.nd.norm works fine for cpu. But it crushed when running gpu version
"
[20:59:04] G:\XXX\DeepLearning\mxnet\dmlc-core\include\dmlc/logging.h:208: [20:59:04] g:\XXX\deeplearning\mxnet\mshadow\ms
hadow\./stream_gpu-inl.h:65: Default GPU stream was used when MSHADOW_FORCE_STREAM was on
[20:59:04] G:\XXX\DeepLearning\mxnet\dmlc-core\include\dmlc/logging.h:208: [20:59:04] g:\XXXX\deeplearning\mxnet\src\engine
\./threaded_engine.h:295: [20:59:04] g:\XXXX\deeplearning\mxnet\mshadow\mshadow\./stream_gpu-inl.h:65: Default GPU stream was us
ed when MSHADOW_FORCE_STREAM was on
"
Thanks;

**Comment by tqchen** [comment]
Thanks for the catch! should be fixed after #418 is merged

**Comment by yang1fan2** [comment]
GPU norm works!!
thanks;

**Comment by tqchen** [comment]
Glad it works out for you, thanks for using mxnet
