### ISSUE TITLE
Operator Proposal and Progress

### ISSUE THREAD

**Issue by antinucleon** [dmlc/mxnet#404]
- [x] L2 Norm op
- [ ] Slice op
- [x] Take op
- [ ] Sum op
- [x] SoftmaxTransform
- [x] Swapaxes

**Comment by pluskid** [comment]
maybe also support (explicit) broadcasting along some dimensions when doing elementwise operation of two (or more) ndarrays?

**Comment by tqchen** [comment]
Reference on how to add new operators http://mxnet.readthedocs.org/en/latest/developer-guide/operator.html

**Comment by lygstate** [comment]
What's going on with Slice operator？

**Comment by tqchen** [comment]
we already have a slice_axis operator, which should serve most of the purpose
