### ISSUE TITLE
'module' object has no attribute 'MultiBoxPrior'

### ISSUE THREAD

**Issue by PhanTask** [dmlc/mxnet#4050]
When I try example/ssd/demo.py, I got this:
example/ssd/symbol/common.py      line 164 in multibox_layer
anthor = mx.symbol.MultiBoxPrior(from_layer……
AttributeError: 'module' object has no attribute 'MultiBoxPrior'
I just gitted the latest version of mxnet and maked it with setting 'NNPACK' & 'openblas' enabled.
Then I entered mxnet/python and run 'python setup.py install'
How can I solve this?

====================================
Oh...HOW CAN I JUST FORGET TO ADD EXTRA_OPERATORS...
Forget me...I'm going to close this stupid issue...

**Comment by lightningsoon** [comment]
Excuse me.
What happened to you？
I met the same problem.

**Comment by lightningsoon** [comment]
@PhanTask

**Comment by PhanTask** [comment]
@lightningsoon As I said, I just forgot to add ssd extra_operators in config.mk.
```EXTRA_OPERATORS += example/ssd/operator``` will solve the problem.

**Comment by lightningsoon** [comment]
if I would like to utilize it on windows.
How could I make config.mk?
Thank you for your comment.

**Comment by PhanTask** [comment]
@lightningsoon I think it is supposed to be the same, but I haven't tried that on Windows yet, sorry can't help you.
http://mxnet.io/get_started/windows_setup.html for more details.
