### ISSUE TITLE
Profiling the execution time of each OP

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#406]
Thanks very much for the great project! I'm trying to use MXNet for my research and is there any way to profile the running time of different operations like that in [Theano](http://deeplearning.net/software/theano/tutorial/profiling.html)? This functionality will be really helpful for debugging the implementation of new networks/OPs.

**Comment by tqchen** [comment]
This was not yet possible, but is an interesting feature to add to. 
I think what can be done is add timing function to
-  https://github.com/dmlc/mxnet/blob/master/src/symbol/graph_executor.cc#L235
And record time info into op_node here https://github.com/dmlc/mxnet/blob/master/src/symbol/graph_executor.cc#L218

It would really be great if you like to take a look and add this :)

**Comment by sxjscience** [comment]
Thanks @tqchen, I'll try that.

**Comment by tqchen** [comment]
Cool Thanks!

**Comment by Piyush3dB** [comment]
@sxjscience did you manage to get anywhere with this?

**Comment by sxjscience** [comment]
@Piyush3dB No, I'm working on other stuffs and need to investigate this later.
