### ISSUE TITLE
mx.nd.array can't be asnumpy() in the evaluation metric

### ISSUE THREAD

**Issue by R1ncy** [dmlc/mxnet#4064]
Hi, I build a multi-input output net and write a dataiter for it.
Here is the dataiter code.
https://github.com/R1ncy/MxnetStudy/blob/master/monolingual_multiinput_iter.py

I use the Multi_Accuracy in the /example/multi-task/example_multi_task.py as the eva metric.
But it was stuck in this line.
https://github.com/R1ncy/MxnetStudy/blob/master/monolingual_multiinput_iter.py#L22

And when I tried to transform the preds to np, it also get stuck.
But the `label = labels[i].asnumpy().astype('int32')` runs normally.
So I think there's something wrong with my dataiter.
Could you help me find out what's wrong with the dataiter?
Many thanks!

**Comment by piiswrong** [comment]
how long did you wait? try waiting for a few minutes. Could be slow startup

**Comment by R1ncy** [comment]
@piiswrong about 20 minutes. I debuged it and found the 
`pred_label = preds[i].asnumpy()` or
`pred_label = mx.nd.argmax_channel(preds[i]).asnumpy().astype('int32')`
get stuck.

But the `label = labels[i].asnumpy().astype('int32')`, forward(), backward() and other things runs normally.

**Comment by R1ncy** [comment]
code runs normally on ubuntu16.04...
solve it
