### ISSUE TITLE
mxnet编译问题，no conversion from 'const int' to 'void *const ' 

### ISSUE THREAD

**Issue by PoisonBOx** [dmlc/mxnet#4068]
在windows下进行配置。在编译的过程中，出现以下错误。请教一下，这是什么问题？？？

Error	50	error C2446: '!=' : no conversion from 'const int' to 'void *const ' (D:\projects\mxnet\src\engine\threaded_engine.cc)	D:\projects\mxnet\dmlc-core\include\dmlc\logging.h	95	1	mxnet
Error	51	error C2040: '!=' : 'void *const ' differs in levels of indirection from 'const int' (D:\projects\mxnet\src\engine\threaded_engine.cc)	D:\projects\mxnet\dmlc-core\include\dmlc\logging.h	95	1	mxnet
Error	52	error C2446: '!=' : no conversion from 'const int' to 'void *const ' (D:\projects\mxnet\src\engine\threaded_engine_perdevice.cc)	D:\projects\mxnet\dmlc-core\include\dmlc\logging.h	95	1	mxnet
Error	53	error C2040: '!=' : 'void *const ' differs in levels of indirection from 'const int' (D:\projects\mxnet\src\engine\threaded_engine_perdevice.cc)	D:\projects\mxnet\dmlc-core\include\dmlc\logging.h	95	1	mxnet
Error	60	error C2446: '!=' : no conversion from 'const int' to 'void *const ' (D:\projects\mxnet\src\engine\threaded_engine_pooled.cc)	D:\projects\mxnet\dmlc-core\include\dmlc\logging.h	95	1	mxnet
Error	61	error C2040: '!=' : 'void *const ' differs in levels of indirection from 'const int' (D:\projects\mxnet\src\engine\threaded_engine_pooled.cc)	D:\projects\mxnet\dmlc-core\include\dmlc\logging.h	95	1	mxnet
Error	68	error C1001: An internal error has occurred in the compiler.	d:\projects\mxnet\src\ndarray\ndarray.cc	175	1	mxnet
Error	72	error D8040: error creating or communicating with child process	D:\projects\mxnet\build\cl	mxnet

**Comment by piiswrong** [comment]
Try pull the latest code. Should be fixed

**Comment by PoisonBOx** [comment]
感谢回复，我拉了代码，重新cmake->编译，仍然存在以下问题：
Error	50	error C1001: An internal error has occurred in the compiler.	d:\projects\mxnet\src\engine\threaded_engine.cc	298	1	mxnet
Error	51	error D8040: error creating or communicating with child process	D:\projects\mxnet\build\cl	mxnet

**Comment by piiswrong** [comment]
@yajiedesign Any ideas?

**Comment by yajiedesign** [comment]
@PoisonBOx  i am test no problem.do you have  update submodule?

**Comment by PoisonBOx** [comment]
问题已解决。需要把Microsoft Visual C++ Compiler Nov 2013 CTP的内容覆盖到vs2013的VC路径下。

**Comment by ee2ace** [comment]
I've encountered the same problem.
How you override the path? From where and to where?
Thanks in advanced....

**Comment by PoisonBOx** [comment]
If you encountered problem "no conversion from 'const int' to 'void *const '", update your code.
If you encountered problem "Error 50 error C1001: An internal error has occurred in the compiler. ", maybe you should download "Microsoft Visual C++ Compiler Nov 2013 CTP" and copy to your VS2013/VC path.
Hope it helps.

**Comment by changcheng1987** [comment]
I use the latest release "mxnet-0.9.3". The cmake is successful. But in VS2013, when I compile the codes under win64-release, the fatal error c1001 keeps coming(:
**error C1001: 编译器中发生内部错误。	\mxnet-0.9.3\nnvm\src\pass\order_mutation.cc (line 114)**

I have copied all the file under "Microsoft Visual C++ Compiler Nov 2013 CTP" to the VS2013 VC folder and the submodule of nnvm is the latest (nnvm-97727ac7cd73619aad620ab204a5a1881a51e048)

Any suggestion? @piiswrong 
Thanks!

**Comment by yajiedesign** [comment]
@changcheng1987 please use vs2015

**Comment by changcheng1987** [comment]
Thanks a lot! VS2015 works!!! @yajiedesign

**Comment by louiskoo520** [comment]
I encountered problem "Error 50 error C1001: An internal error has occurred in the compiler ". Then I install Microsoft Visual C++ Compiler Nov 2013 CTP:
![image](https://cloud.githubusercontent.com/assets/4961164/24319877/e2ea0fc0-1163-11e7-9d76-8b26f2347ea8.png)

What should I do next to fix this problem?

**Comment by yajiedesign** [comment]
@louiskoo520 use vs2015

**Comment by louiskoo520** [comment]
VS2015 error:
D:\Python\MXNet\mxnet1\mxnet\nnvm\src\pass\order_mutation.cc(114): fatal error C1001: 编译器中发生内部错误。
3>  (编译器文件“f:\dd\vctools\compiler\cxxfe\sl\p1\c\trees.h”，第 884 行)

**Comment by yajiedesign** [comment]
@louiskoo520 what is f:\dd\vctools\compiler\cxxfe\sl\p1\c\trees.h?

**Comment by louiskoo520** [comment]
@yajiedesign  I don't know and I don't even have f in my computer.

**Comment by yajiedesign** [comment]
@louiskoo520 Try reinstalling vs2015,You may need to reinstall the system.and not install "Microsoft Visual C++ Compiler Nov 2013 CTP"

**Comment by louiskoo520** [comment]
I used cmake of  VS2013 compiler to get  mxnet.sln and then used vs2015 to try to compile to get libmxnet.dll.     @yajiedesign

**Comment by yajiedesign** [comment]
@louiskoo520 you can cmake of vs2015
