### ISSUE TITLE
A question about symbol and sym_gen.

### ISSUE THREAD

**Issue by wanderingpj** [dmlc/mxnet#4087]
What's the meaning of this line? 
https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L762
And what's the difference between symbol and sym_gen?

**Comment by sxjscience** [comment]
@wanderingpj May be related to the discussion here https://github.com/dmlc/mxnet/issues/3203.

**Comment by wanderingpj** [comment]
thanks @sxjscience
