### ISSUE TITLE
A question about parameter updating.

### ISSUE THREAD

**Issue by wanderingpj** [dmlc/mxnet#4090]
In model.py , what's the difference between these 2 functions : 
    def _update_params_on_kvstore(param_arrays, grad_arrays, kvstore)
    def _update_params(param_arrays, grad_arrays, updater, num_device, kvstore=None)
https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L87
Both of these 2 functions have kvstore.push , kvstore.pull.

**Comment by tornadomeet** [comment]
this is because when  ```kvstore is not None``` in ```_update_params()``` , which means ```kvstore='local'``` and the model parameters is too big to push, then it will update the model in the local device, ref. https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L63-L69, so at this time, push and pull on kvstore is equivalence to ```updater(index*num_device+k, g, w)``` i think.

**Comment by wanderingpj** [comment]
Since the model parameters is too big to push ,and it's equivalence to updater() ,why do we have these lines:
https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L105-L109 ?  Is 't it unnecessary?

**Comment by tornadomeet** [comment]
@wanderingpj  i just read the code and found my previous commit is a little wrong.  

your question is: why `_update_parmas` still need kvstore to push and pull?

first, when `kvstore="local"`, then it will copy all grdict to cpu and update the params on cpu, this is done by two stage, not one stage.   

then if the model params is too big, update the params using optimizer on cpu will be very costly, so in ```model.py``` it only aggregate gradient to cpu, not update paramters on cpu, and need copy the summed gradient back to device and update model params on device.   

last you can found if `update_on_kvstore=False`, then kvstore will have no function of optimization(only copy gradient), just ref. https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L222-L223  

so you can read the code in https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L105-L115, there is a two stage processe, no `else` there.

**Comment by wanderingpj** [comment]
I'm clear now , thank you!@tornadomeet
