### ISSUE TITLE
Must the input variable be named with 'data'?

### ISSUE THREAD

**Issue by back2yes** [dmlc/mxnet#4094]
I wrote a simple network with one hidden layer. 

net = mx.sym.Variable('v1')
fc1 = mx.sym.FullyConnected(data=net, name='fc1', num_hidden=10)
act1 = mx.sym.Activation(data=fc1, name='act1', act_type='relu')
fc2 = mx.sym.FullyConnected(data=act1, name='fc2', num_hidden=3)
soft2 = mx.sym.SoftmaxOutput(data=fc2, name='soft3')
ctx = mx.gpu(1)
batch_size = 128
data_shape = (batch_size, 256)
executor = soft3.simple_bind(ctx=ctx, grad_req='write', data=data_shape)

However, an error was raised: Symbol.InferShapeKKeyword argument name data not found

I found out that the error derived from line 676 in 'symbol.py': arg_shapes, _, aux_shapes = self.infer_shape(**kwargs)
It seemed that the 'infer_shape' only worked when the name of the input variable was exactly 'data', ...?
Maybe I was wrong, because fixing the name of the input was not elegant at all. What if there were more input variables than one?

But I could not find out a way to tackle this. Could someone tell me how to specify a different (user-defined) variable name for inputs?
THX.

**Comment by tornadomeet** [comment]
```python

net = mx.sym.Variable('v1')
fc1 = mx.sym.FullyConnected(data=net, name='fc1', num_hidden=10)
act1 = mx.sym.Activation(data=fc1, name='act1', act_type='relu')
fc2 = mx.sym.FullyConnected(data=act1, name='fc2', num_hidden=3)
soft2 = mx.sym.SoftmaxOutput(data=fc2, name='soft2')

ctx = mx.gpu(1)
batch_size = 128
data_shape = (batch_size, 256)
executor = soft2.simple_bind(ctx=ctx, grad_req='write', v1=data_shape)
```
because you set `data` in simple_bind, but in your symbol, no `data` there, but only `v1`, so you should use ```v1=data_shape```, then will be ok.

**Comment by back2yes** [comment]
@tornadomeet 
THX, that really solved my issue! And a really quick reply.....!!
