### ISSUE TITLE
Invalid URL in R Package ‘mxnet’ PDF Manual

### ISSUE THREAD

**Issue by XD-DENG** [dmlc/mxnet#4095]
@thirdwing 
Hi Kou Qiang, thanks a lot for your great works so that we can try mxnet within R.

I found that the URL included in the PDF manual (http://mxnet.io/api/r/mxnet-r-reference-manual.pdf) is invalid. At the moment, it is  [https://github.com/dmlc/mxnet/R-package](https://github.com/dmlc/mxnet/R-package) and it doesn't work. Maybe it should be [https://github.com/dmlc/mxnet/tree/master/R-package](https://github.com/dmlc/mxnet/tree/master/R-package) instead.

Thanks!

**Comment by thirdwing** [comment]
Fixed in https://github.com/dmlc/mxnet/pull/4160
