### ISSUE TITLE
How to pass parameters into CustomOp

### ISSUE THREAD

**Issue by nicklhy** [dmlc/mxnet#4098]
I am trying to implement a new operator(loss function) in Python following the instructions [here](http://mxnet.io/how_to/new_op.html). But different from the example in this page, my new operator need some extra parameters like "kernel", "stride" or "num_filter" in mx.sym.Convolution . Is it possible to pass such parameters into a CustomOp like

```
class AwesomeOp:
    def __init__(self, arg1, arg2):
        self.arg1 = arg1
        self.arg2 = arg2
        ... ...

data = mx.sym.Variable('data')
awesome_op = AwesomeOp(data=data, arg1=arg1, arg2=arg2)
```

**Comment by CNevd** [comment]
yes, just used in [k-max pooling](https://github.com/CNevd/DeepLearning-MXNet/blob/master/DCNN/dcnn_train.py#L15)

**Comment by nicklhy** [comment]
@CNevd , thanks a lot. That is exactly what I want !
