### ISSUE TITLE
Simple offsetting way for image preprocess

### ISSUE THREAD

**Issue by Primus-zhao** [dmlc/mxnet#4099]
Hi guys, 

Heard the news that Amazon on board now, well done!
By the way, for ImageRecordIter, mxnet can do scaling with "scale" argument. Is there a simple way for offsetting(ie. transform data from range[0, 2] to [-1, 1]) as well? Can't find it in the tutorial.

**Comment by piiswrong** [comment]
mean_r mean_g mean_b

**Comment by Primus-zhao** [comment]
thks! @piiswrong
