### ISSUE TITLE
[R] Data augmentation with basic MNIST example

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#4105]
I want to create a custom iterator in R. As an initial example I will use the MNIST data. 

What I would like to do is an iterator that gets as input the raw data, that would be a matrix of 60000 examples times 784 which is each image expanded in a vector:
```R
dim(train.x)
[1] 59999   784
``` 
and whose output, in every iteration, would be a matrix of `28x28x1xbatch_size`:

```R
dim(train.x)
[1]  28  28   1 100
``` 
The only operation that I have to do inside the iterator is the following:

```R
dim(train.x) <- c(28, 28, 1, ncol(train.x))
``` 
I don´t know if there is a way to reimplement the operator `iter.next()` or `value()` in R. I know that that can be done in python and C++, but not sure how to do it in R. 

The interface should be something like:

```R
custom.iter <- function(X, y, batch.size, is.train){
#my magical transformation...???...???
return(Xiter)
}

#data definition
dim(train.x)
[1] 59999   784

#Iterator instantiation
Xiter <- custom.iter(train.x, train.y, 100, TRUE)
Xiter$iter.next()
[1] TRUE
data <- Xiter$value()$data
dim(data)
[1]  28  28   1 100
``` 

Any help appreciated :) @piiswrong @thirdwing

**Comment by thirdwing** [comment]
@miguelgfierro This can be done as a reference class in R. I give a very prototype below.

```r
cus_iter <-setRefClass("Custom.Iter", fields = "x")
cus_iter$methods(iter.next = function() {return(TRUE)})

iter <- cus_iter$new(x = 123)
iter$iter.next()
```

**Comment by miguelgfierro** [comment]
@thirdwing what you are suggesting is to implement a reference class from scratch that copies the behavior of the C++ iterator class?

I want to reimplement the method `value` in `mx.io.arrayiter`. So what you are suggesting is to do:

```R
cus_iter <-setRefClass("Custom.Iter", fields = c("data", "label","batch.size", "shuffle"))
cus_iter$methods(iter.next = function() {
#code here
})
cus_iter$methods(value = function() {
#code here
})
```
Could this class be used as an input to `mx.model.FeedForward.create`?

Ideally what I would like is to inhereit from a `MXArrayDataIter` and reimplement only the method `value`. If I create an instance of `mx.io.arrayiter`, it has everything that I want but I don't know how to modify the `value`.
```R
array.iter.mx <- mx.io.arrayiter(data = train.x, label = train.y, batch.size = 100, shuffle = TRUE)
is(array.iter.mx)
[1] "Rcpp_MXArrayDataIter" "C++Object"           
[3] "envRefClass"          ".environment"        
[5] "refClass"             "environment"         
[7] "refObject"
mxnet:::is.MXDataIter(array.iter.mx)
[1] TRUE
```
In python you can create a custom iterator if you inhereit from `mx.io.DataIter` and reimplement  `provide_data(), provide_label(), next()`. How can this be done in R? 


How could I reimplement this

**Comment by thirdwing** [comment]
I think you can try something like below:

```r
> setRefClass("Custom.Iter", contains = "Rcpp_MXArrayDataIter")
> 
> cus_iter <-setRefClass("Custom.Iter", contains = "Rcpp_MXArrayDataIter")
> cus_iter$methods(`iter.next` = function() {return(TRUE)})
> 
> cus_iter
Generator for class "Custom.Iter":

No fields defined

Class Methods: 
     "iter.next#Rcpp_MXArrayDataIter", "import", ".objectParent", 
     "usingMethods", "show", "getClass", "untrace", "export", ".objectPackage", 
     "callSuper", "copy", "initFields", "getRefClass", "trace", "field", 
     "iter.next", "num.pad", "reset", "value", "finalize", "initialize"

Reference Superclasses: 
     "Rcpp_MXArrayDataIter", "envRefClass"

> 
> it <- cus_iter$new()
> 
> it$iter.next()
[1] TRUE
```

**Comment by miguelgfierro** [comment]
The problem with that is that it's not taking the methods from the c++ class. The class has `value, reset`. We are  just creating `iter.next()` that every time is called it returns `TRUE` but it is not counting the number of batches. And it won't return a batch of values...

**Comment by thirdwing** [comment]
@miguelgfierro I might try to find some time to give a more complete example.

This is still doable through a reference class. We only need to provide a RC `iter`.

**Comment by miguelgfierro** [comment]
@thirdwing look, this could be a solution to overload the CSVIter using MNIST data in csv format:

```R
CustomCSVIter <- setRefClass("CustomCSVIter",
                             fields=c("iter", "data.csv", "data.shape", "batch.size", "shuffle"),
                             methods=list(
                               initialize=function(iter, data.csv, data.shape, batch.size, shuffle){
                                 feature_len <- data.shape*data.shape + 1
                                 csv_iter <- mx.io.CSVIter(data.csv=data.csv, data.shape=c(feature_len), batch.size=batch.size)
                                 .self$iter <- csv_iter 
                                 .self
                               },
                               inter.next=function(){
                                 .self$iter$iter.next()
                               },
                               value=function(){
                                 .self$iter$value()
                               }
                             )
)
cc <- CustomCSVIter$new(iter = NULL, data.csv = train_file, data.shape = 28, 
                        batch.size = 2, shuffle = FALSE)  
cc$inter.next()
cc_value <- cc$value()
```
I'll try to do an example to show this and do a PR. Thanks buddy!!!

**Comment by thirdwing** [comment]
This should work.When sending the PR, please send to the nnvm branch. Thank you.
