### ISSUE TITLE
Question about multiple parameter servers

### ISSUE THREAD

**Issue by blazerygy** [dmlc/mxnet#4117]
when using multiple parameter servers, how does the worker choose which parameter push to which parameter server? where is the code? thx

**Comment by feiyulv** [comment]
If parameter size is smaller than `MXNET_KVSTORE_BIGARRAY_BOUND`, it will send to one of the servers according to a hash function, otherwise parameter will be divided averagely into all servers. see code here
https://github.com/dmlc/mxnet/blob/master/src/kvstore/kvstore_dist.h#273

**Comment by blazerygy** [comment]
@feiyulv thanks for your help
I found push parameter will call "Send" finally
[https://github.com/dmlc/ps-lite/blob/4a060e4e8aa40c3a931a0f8af9211279e012f8a2/include/ps/kv_app.h#L463](url)

why it uses "slice_" to divide parameter again? 
[https://github.com/dmlc/ps-lite/blob/4a060e4e8aa40c3a931a0f8af9211279e012f8a2/include/ps/kv_app.h#L466](url)

what is the relationship between "slice_" and "EncodeKey"? 
thx

**Comment by mli** [comment]
EncodeKey converts a mxnet/kvstore key into a ps-lite key. slice is used to cut a big array into multiple parts, each part goes to one server node

**Comment by blazerygy** [comment]
@mli I got it, thanks for your help.
