### ISSUE TITLE
OneHot Layer

### ISSUE THREAD

**Issue by sbodenstein** [dmlc/mxnet#4119]
@piiswrong: we would really like to support a one-hot encoding symbol (so one can easily switch between using `mx.Embedding` layer and one-hot in ones computational graph). Can I add this? Or is there a reason you want to avoid using it? (and hence won't merge this layer)

@taliesinb

**Comment by piiswrong** [comment]
I'm not familiar with this. Whats the difference between one-hot encoding and embedding?
If its a general layer (not specific to one project) and it can't be done with current layers we should definately add it.

**Comment by sbodenstein** [comment]
Its equivalent to the NDArray op `mx.nd.onehot_encode(mx.nd.array(indices), out=arr)`. Its input obviously has no gradient, just like `Embedding`, but also has no weights.

**Comment by piiswrong** [comment]
Then why do we need to add a layer instead of just using nd.onehot_encode?

**Comment by sbodenstein** [comment]
Ah, I was under the (mistaken) impression that all symbol ops could automatically be called to do NDArray ops, but didn't know that they other way round also held. Thanks!

**Comment by jmacglashan** [comment]
@piiswrong this doesn't seem true to me or I'm misunderstanding. There is no mx.sym.onehot_encode reference and trying to apply mx.nd.onehot_encode fails if you pass it symbols instead of NDArrays.
