### ISSUE TITLE
there is something wrong about the main() function in mxnet/tools/caffe_converter/convert_symbol.py

### ISSUE THREAD

**Issue by animebing** [dmlc/mxnet#4121]
In the main() function,  the return of proto2script(sys.argv[1]) should be 3 values, not 2 values

**Comment by oura-fj** [comment]
proto2script(sys.argv[1]) returns 3 values, so I think you should chage the code
`symbol_string, output_name = proto2script(sys.argv[1])`
to
`symbol_string, output_name, input_dim = proto2script(sys.argv[1])`

**Comment by animebing** [comment]
@oura-fj Thanks, this is what I have done. Maybe the code in github should be modified to avoid the mistake

**Comment by oura-fj** [comment]
@animebing Yes, I think so too. I modified the code in github and sent a pull request.

**Comment by piiswrong** [comment]
should have been fixed
