### ISSUE TITLE
Are there some performance benchmark examples or tutorials?

### ISSUE THREAD

**Issue by pineking** [dmlc/mxnet#4130]
@piiswrong 
I want to run some experiments for performace benchmark to figure out and compare the speed of mxnet in different conditions (e.g. 1 GPU，2 GPUs，...，multi-GPUs on multi-machines).  are there some existing examples which I can repeat?

**Comment by piiswrong** [comment]
example/image-classification

also repo dmlc/mxnet-deepmark

**Comment by pineking** [comment]
Good, Thanks!
