### ISSUE TITLE
mxnet example in go

### ISSUE THREAD

**Issue by songtianyi** [dmlc/mxnet#4154]
There is no go example in mxnet examples directory. Why? go hasn't been support yet?

**Comment by zhreshold** [comment]
You are right, Go bindings not supported in this official repo yet, check this out https://github.com/jdeng/gomxnet
instead. Besides, you are not going to get any high lever APIs other than the very fundamental ones.

**Comment by songtianyi** [comment]
Is it on schedule for go-package?
