### ISSUE TITLE
GPU memory consumption 

### ISSUE THREAD

**Issue by Andrjusha** [dmlc/mxnet#4161]
Hi guys,

could you please clarify the following question concerning gpu memory consumption by mxnet. The thing is that it looks like when I train a model written on Lasagne/Theano the gpu memory consumption is much smaller then when I use mxnet. E.g. I can train the model written on lasagne with around 30 millions of trainable parameters with input size of the images 3x512x512 and batch_size=128 on 4GB GPU. On the other hand on the same GPU when I use mxnet I can train a model (based on symbol_resnet.py) with 10 millions of parameters with the same input size of the images and batch size=45. So it looks like mxnet consumes much memory then lasagne. Is it normal?

Thank you in advance!

**Comment by back2yes** [comment]
In my case MXNet consumed less memory than lasagne... I guess this was related to the model structure.

**Comment by Andrjusha** [comment]
Could you specify what you mean? Because I think that if the number of parameters is smaller then the model should consume less memory, it's kind of logical...

**Comment by Andrjusha** [comment]
I think I understood the problem, I miscounted some parameters
