### ISSUE TITLE
How to add attributes to an existing symbol?

### ISSUE THREAD

**Issue by back2yes** [dmlc/mxnet#4165]
I am using a python version of MXNet on Ubuntu 16.04 OS.

I wanted to fine-tune the VGG-16 model. The symbols loaded from vgg16-symbol.json did not have the 'lr_mult' attributes. I know how to set the attributes when creating the variables: 
v1=mx.sym.Variable('v1', attr={'attr1':'value1'})

But how to add an attribute to an existing variable?

THX.

**Comment by kevinthesun** [comment]
One option might be adding "lr_mult" entry to json file and load the modified json.

**Comment by back2yes** [comment]
@shuokay @kevinthesun 
Thanks for your quick reply.
Finally I managed to add the attributes by explicitly calling the 'self._add_attr()' method of each symbol in a loop.
