### ISSUE TITLE
Possibility of a new release ?

### ISSUE THREAD

**Issue by mdpradeep** [dmlc/mxnet#4168]
Is it possible to make a new release since the current [release](https://github.com/dmlc/mxnet/releases/tag/20160531) version is ~6 months old and does not have  some new functions that we are looking at (e.g. `MXSymbolGetAtomicSymbolName`) ? If not what is the earliest possible date when a new release can be made ? I could use the nightly version but it is missing the dependent libraries.

**Comment by VoVAllen** [comment]
https://github.com/yajiedesign/mxnet/releases

Hope this would help. You may need to search the related topic to figure out how to install it.

**Comment by miguelgfierro** [comment]
Working on it -> https://github.com/dmlc/mxnet/issues/4044
