### ISSUE TITLE
How can I make a predict with a lstm-ctc checkpoint ?

### ISSUE THREAD

**Issue by BobLiu20** [dmlc/mxnet#4169]
I following example/warpctc/lstm_ocr.py to training a model. Now I had saved a checkpoint mymodel-0100.params and mymodel-symbol.json.
So, How can I make a predict with this checkpoint use only one image?

I had tired to use Predictor interface, code below:
```
# Load the pre-trained model
symbol_file = "mymodel-symbol.json"
param_file = "mymodel-0100.params"
predictor = Predictor(open(symbol_file).read(),
                      open(param_file).read(),
                      {'data':(80, 30)})
```
But data shape always raise error and I don't know how to set this value. Anybody help me thank you.

**Comment by BobLiu20** [comment]
Sorry I would like to repeat my question in Chinese:
我按照example/warpctc/lstm_ocr.py训练出一个模型，包括：mymodel-0100.params and mymodel-symbol.json。现在不知道怎样使用这个模型来识别一个图片的文字。
我尝试使用Predictor这个接口，如下：
```
# Load the pre-trained model
symbol_file = "mymodel-symbol.json"
param_file = "mymodel-0100.params"
predictor = Predictor(open(symbol_file).read(),
                      open(param_file).read(),
                      {'data':(80, 30)})
```
但是那个data里的shape好像总是报错，不知道应该如何写。想了很久没想明白，谢谢

**Comment by BobLiu20** [comment]
I had tried another interface, add one line code in the end of example/warpctc/lstm_ocr.py:
```
    model = mx.model.FeedForward(ctx=contexts,
                                 symbol=symbol,
                                 num_epoch=num_epoch,
                                 learning_rate=learning_rate,
                                 momentum=momentum,
                                 wd=0.00001,
                                 initializer=mx.init.Xavier(factor_type="in", magnitude=2.34))

    model.fit(X=data_train, eval_data=data_val,
              eval_metric = mx.metric.np(Accuracy),
              batch_end_callback=mx.callback.Speedometer(BATCH_SIZE, 50),)

    model.save("ocr")

    # add new line for predict
    model.predict(data_val)
```
But it is always error output:
```
Traceback (most recent call last):
  File "lstm_ctc_ocr.py", line 211, in <module>
    training_all()
  File "lstm_ctc_ocr.py", line 188, in training_all
    model.predict(data_val)
  File "/home/bobliu/Work/code/DL/mxnet/python/mxnet/model.py", line 618, in predict
    self._init_predictor(data_shapes, type_dict)
  File "/home/bobliu/Work/code/DL/mxnet/python/mxnet/model.py", line 541, in _init_predictor
    self.ctx[0], grad_req='null', type_dict=type_dict, **dict(input_shapes))
  File "/home/bobliu/Work/code/DL/mxnet/python/mxnet/symbol.py", line 685, in simple_bind
    arg_types, _, aux_types = self.infer_type(**type_dict)
  File "/home/bobliu/Work/code/DL/mxnet/python/mxnet/symbol.py", line 417, in infer_type
    ctypes.byref(complete)))
  File "/home/bobliu/Work/code/DL/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferType Error in reshape0: [21:39:03] src/operator/./reshape-inl.h:345: Check failed: (dtype) != (-1) First input must have specified type
```

**Comment by lji72** [comment]
You can refer to  
'https://github.com/dmlc/mxnet-notebooks/blob/master/python/how_to/predict.ipynb'.
That may work.

**Comment by BobLiu20** [comment]
Finally, I know what's wrong with me after reading source code of mxnet python model. It seems a bug appear in mxnet python model predict function to support multi-output. I will try to pull a bug fix request when I am free.

**Comment by BobLiu20** [comment]
Anyway, if somebody want to know solution detail, Please check [answer](http://stackoverflow.com/questions/41071422/how-can-i-make-a-predict-with-a-lstm-ctc-checkpoint-in-mxnet)

**Comment by oyxhust** [comment]
@BobLiu20 I do not understand your answer for this question. Can you share the code of predicting with a lstm-ctc checkpoint. Thank you a lot!

**Comment by BobLiu20** [comment]
@oyxhust  Hi, I am going to add a predict sample code to example/warp-ctc folder. But it is still waiting to merge. Please check it in [here](https://github.com/dmlc/mxnet/pull/4365) for now.  #4365
