### ISSUE TITLE
gradient clip with l2norm in mxnet

### ISSUE THREAD

**Issue by feiyulv** [dmlc/mxnet#4177]
I'm trying to implement a gradient clip with l2norm using the c++ optimizer. The standard gradient clip needs to calculate the  l2norm value over all the parameters, and use a global scale for every parameter, like follows:
![default](https://cloud.githubusercontent.com/assets/18651286/21070885/c3847148-beca-11e6-97c3-f33968a57144.PNG)

However in mxnet's optimizer, I can only access one parameter. Currently, I calculate a scale for each parameter, but it seems the model can't converge as good as the theano baseline.  Is there any good idea to implement a standard gradient clip over all parameters?

**Comment by sxjscience** [comment]
@feiyulv I suggest using imperative NDArray API to do that.
```python
def norm_clipping(params_grad, threshold):
    assert isinstance(params_grad, dict)
    norm_val = numpy.sqrt(sum([nd.norm(grad).asnumpy()[0]**2 for grad in params_grad.values()]))
    # print('grad norm: %g' % norm_val)
    ratio = 1.0
    if norm_val > threshold:
        ratio = threshold / norm_val
        for grad in params_grad.values():
            grad *= ratio
    return norm_val
```

**Comment by shivarajugowda** [comment]
Wouldn't this be expensive since the calculations happens in Python, rather than on the GPU? Or is it that the whole operation in `sum([nd.norm(grad).asnumpy()[0]**2 for grad in params_grad.values()]))` is somehow pushed down to GPU?

**Comment by sxjscience** [comment]
@shivarajugowda The strategy is to use `nd.norm`, which is computed using GPU with cuBLAS, to get a scalar output and copy it to the CPU side and do the summation.

**Comment by sxjscience** [comment]
Also, my experience is that `nd.norm(x)`, which calls the BLAS API, is much faster than `nd.sqrt(nd.sum(nd.square(x)))`.

**Comment by sxjscience** [comment]
The reason I suggest using imperative API for norm-clipping is that it'll be much easier to debug the code by visualizing the norm of the gradient. We've been using this trick for tuning recurrent neural networks.

**Comment by sxjscience** [comment]
For example, if we have K parameter gradient. The code computes the norm(norm is a scalar) of each gradient on GPU and sum these K values on CPU.

**Comment by shivarajugowda** [comment]
@sxjscience got it, thanks.

**Comment by feiyulv** [comment]
@sxjscience thanks very much
