### ISSUE TITLE
error in as.array.MXNDArray in R

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#4184]
When converting form array to MXNDArray I get the following error:

```R
cc <- array(c(1,2,3,4))
cc_mxnet <- mxnet:::as.array.MXNDArray(cc)
Error in eval(substitute(expr), envir, enclos) : 
  expecting an external pointer
```

Any idea? @thirdwing

**Comment by thirdwing** [comment]
I think what you want is 

```r
> library(mxnet)
> cc <- array(c(1,2,3,4))
> cc_mxnet <- mx.nd.array(cc)
> str(cc_mxnet)
Class 'MXNDArray' <externalptr>
```

**Comment by thirdwing** [comment]
Just one more thing. The `as.array.MXNDArray()` will be called when we apply `as.array` over a `MXNDArray`. It is for converting `MXNDArray` to `array`.

**Comment by miguelgfierro** [comment]
Awesome @thirdwing!! I already have the custom iterator example. Tomorrow I'll do a PR. I was thinking to add the example [here](https://github.com/dmlc/mxnet/blob/nnvm/R-package/vignettes/mnistCompetition.Rmd), what do you think?

**Comment by thirdwing** [comment]
You can do what you like.

Personally I might prefer also adding a separate doc on "How to write your iter". We already have "How to write your own callback function" and "How to use your own loss function". 

https://github.com/dmlc/mxnet/blob/master/docs/tutorials/r/CallbackFunctionTutorial.md

**Comment by miguelgfierro** [comment]
Ok, it make sense
