### ISSUE TITLE
Fix the "default" CI build.

### ISSUE THREAD

**Issue by shivarajugowda** [dmlc/mxnet#4192]
After every checkin there seems to be 3 sets of tests triggered. One of them("default") always fails. It looks most of the developers are aware of it. But for a new comer it is confusing, I guess it is confusing even for others. This is task to fix it or remove the test set if appropriate.

**Comment by piiswrong** [comment]
Yeah I've been too lazy to do it. 
commenting out these lines in tests/jenkins/run_test.sh should work
```
echo "BUILD julia_test"
export MXNET_HOME="${PWD}"
/home/ubuntu/julia/bin/julia -e 'try Pkg.clone("MXNet"); catch end; Pkg.checkout("MXNet"); Pkg.build("MXNet"); Pkg.test("MXNet")' || exit -1
```

**Comment by shivarajugowda** [comment]
I understand. This is worth fixing it soon though since the project seems to be scaling to many new developers.

**Comment by shivarajugowda** [comment]
I think this is fixed now.
