### ISSUE TITLE
im2rec.py's parameter made me confusing

### ISSUE THREAD

**Issue by kernel8liang** [dmlc/mxnet#4197]
when I try to use im2rec.py to make rec, it confused me.

1, build the list, I need to use:

```
python im2rec.py /data1/ILSVRC2012/train/ILSVRC2012  /data1/ILSVRC2012/train_raw --list=True --recursive=True --resize=227
```

2. create the rec, i need to use:

```
python im2rec.py /data1/ILSVRC2012/train/  /data1/ILSVRC2012/train_raw --num-thread=28  --recursive=True --resize=227
```

use the same command, but with different prefix ```/data1/ILSVRC2012/train/ILSVRC2012``` and ```/data1/ILSVRC2012/train/ILSVRC2012```. 

I think, it's better to make them the same. just in my opinion.

**Comment by piiswrong** [comment]
no. You should use the same prefix.

**Comment by kernel8liang** [comment]
i know the issue, i should use prefix like ```/data1/ILSVRC2012/train/``` which include ```/```at the end, or in the ```make_list``` it will construct filename like ```/data1/ILSVRC2012/train_xxx_xxx.lst``` rather than ```/data1/ILSVRC2012/train/xxx_xxx_.lst```.

**Comment by kernel8liang** [comment]
i have a mistake in my previous comment, even i included ```/``` in the end, it still doesn't output files in the directory i want, i use command:

```
python im2rec.py /data1/ILSVRC2012/train/  /data1/ILSVRC2012/train_raw --train-ratio=0.7 --test-ratio=0.2 --list=True --recursive=True --resize=227
```

then i get output files:

```/data1/ILSVRC2012/train_test.lst```
```/data1/ILSVRC2012/train_train.lst```
```/data1/ILSVRC2012/train_val.lst```

which didn't in directory ```/data1/ILSVRC2012/train/```.

when to build rec files, i need input prefix with ```/data1/ILSVRC2012```
