### ISSUE TITLE
Run error:(status) == (CURAND_STATUS_SUCCESS) CURAND Gen Uniform float failed

### ISSUE THREAD

**Issue by nerddd** [dmlc/mxnet#4198]
When I run python train.py with gpu,this error will come out as follows:

> [16:27:45] /home/cliu/mxnet/dmlc-core/include/dmlc/logging.h:235: [16:27:45] /home/cliu/mxnet/mshadow/mshadow/./random.h:344: Check failed: (status) == (CURAND_STATUS_SUCCESS) CURAND Gen Uniform float failed. size = 4096
> [16:27:45] /home/cliu/mxnet/dmlc-core/include/dmlc/logging.h:235: [16:27:45] src/engine/./threaded_engine.h:306: [16:27:45] /home/cliu/mxnet/mshadow/mshadow/./random.h:344: Check failed: (status) == (CURAND_STATUS_SUCCESS) CURAND Gen Uniform float failed. size = 4096
> An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
> terminate called after throwing an instance of 'dmlc::Error'
>   what():  [16:27:45] src/engine/./threaded_engine.h:306: [16:27:45] /home/cliu/mxnet/mshadow/mshadow/./random.h:344: Check failed: (status) == (CURAND_STATUS_SUCCESS) CURAND Gen Uniform float failed. size = 4096
> An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
> 已放弃 (核心已转储)

I've updated the cuda version from 7.5 to 8.0,but still remain this problem.
When I ran the train_mnist.py in example/image-classification  with gpu,it works fine.But when I ran my own train file with gpu,the error above occured,while with cpu works ok.
I wonder if this has something to do with cuda?Any help will be appreciated.
PS:GTX1070 ubuntu16.04

**Comment by nerddd** [comment]
Done

**Comment by haosirong** [comment]
How did you resolve the question, I have also encoutnered this under nvidia-docker. and my nvcc is 7.5
