### ISSUE TITLE
How can I set the loss weight with mult_outputs?

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#421]
Hi all,  My network has mult outputs, I just set the different loss weight for each loss layer just like caffe, How can I do it?

**Comment by antinucleon** [comment]
Yes, there is a grad_scale parameter for softmax (
https://mxnet.readthedocs.org/en/latest/python/symbol.html). Also it
supports manually setting different gradient back by using low level
symbolic bind API, where you can do whatever you want in gradient outside
MXNet

**Comment by junranhe** [comment]
I see, thanks for reply:)
