### ISSUE TITLE
The comparison operators(>, >=, < and <=) for scalar inputs are not complete.

### ISSUE THREAD

**Issue by shivarajugowda** [dmlc/mxnet#4215]
If RHS input is a scalar we might get incorrect results since the input for non-commutative operations is not set.

**Comment by jermainewang** [comment]
Is this completed in afda136da63d3dc8f9b2223608293677d1e32e6e ?

**Comment by shivarajugowda** [comment]
yes it is completed in  afda136 . @piiswrong thought we might have had a problem with scalar RHS, but that doesn't look to be the case. I have added unit test to cover that in pull request #4229. For details see also comments pull request #4190
