### ISSUE TITLE
how to train image with correct augmentation

### ISSUE THREAD

**Issue by kernel8liang** [dmlc/mxnet#4216]
I wanted to train ILSVRC data set, preprocessed the data set with ```im2rec.py center-crop=True --resize=227```.  when train the data get error:

```
/home/liang/workspace/mxnet1212/mxnet1212/dmlc-core/include/dmlc/logging.h:235: [13:31:47] src/io/image_aug_default.cc:254: Check failed: static_cast<index_t>(res.rows) >= param_.data_shape[1] && static_cast<index_t>(res.cols) >= param_.data_shape[2] input image size smaller than input shape
```

i debug around, found this is because in the dataset there is picture‘s pixels less 227 (x < 227 or y < 227 or).

so, i want to ask is there a argument to make these picture with the size i want ?

**Comment by kernel8liang** [comment]
debug around again, found there are same augment be set in ```train_imagenet.py```, this cause my issue, 

in ```train_imagenet.py```
```
data.set_data_aug_level(parser, 0)
min_random_scale = 0.533
```

**Comment by lincolneejdk** [comment]
Could you tell me how to resolve this issue? Thank you very much!

**Comment by kernel8liang** [comment]
comment 

```
#data.set_data_aug_level(parser, 3)
#min_random_scale = 0.533
```

in train_imagenet.py

**Comment by lincolneejdk** [comment]
Thank you very much!
