### ISSUE TITLE
MXNDArray for strings in R

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#4222]
I'm trying to implement a custom iterator that uses text data. In one of the parts I need to create a `MXNDArray` of strings. However, I get an error.
```r
> arr <- array(c("a","b","c"))
> mxarr <- mx.nd.array(arr)
Error in eval(substitute(expr), envir, enclos) : 
  not compatible with requested type
> arr2 <- c(1,2,3)
> mxarr2 <- mx.nd.array(arr2)
> is(mxarr2)
[1] "MXNDArray"
```
Is there a way to do this?

**Comment by piiswrong** [comment]
I don't think ndarray can hold string... @thirdwing

**Comment by thirdwing** [comment]
I am afraid you need to build a vocabulary first, like what has been done in 
https://github.com/dmlc/mxnet/blob/master/example/rnn/char-rnn.ipynb

**Comment by miguelgfierro** [comment]
Ok, Thanks!!
