### ISSUE TITLE
how to print values of a tensor？

### ISSUE THREAD

**Issue by achao2013** [dmlc/mxnet#4223]
i want to print some values of specified locations of a tensor in forward or backward op， is there some function to call or how to implement this function？

**Comment by kevinthesun** [comment]
Would you like to print the value of a of some ndarray?

**Comment by achao2013** [comment]
no ，i want to print some values of a Tensor in forward or backward operation of
 a operator in .cpp or .cu @kevinthesun

**Comment by zihaolucky** [comment]
@achao2013 Could you put your code snippets?

**Comment by achao2013** [comment]
Tensor<gpu, 4, DType> tmp_gwmat=mshadow::NewTensor(gwmat.shape_,DType(0),true,s);
tmp_gwmat=tmp_gwmat*mshadow::expr::F<mshadow_op::trunc>(wmat);
Assign(gwmat, req[conv::kWeight], tmp_gwmat);

it's a code snippet in my cudnn_convolution-inl.h
As shown above，i want to see the middle result of tmp_gwmat and gwmat @zihaolucky

**Comment by feiyulv** [comment]
You can print value like this
```
Tensor<cpu, 4> cpu_gwmat=mshadow::NewTensor<cpu, 4>(gwmat.shape_,DType(0),true,s);
Copy(cpu_gwmat, tmp_gwmat,s);
cout<<cpu_gwmat.dptr_[0];
```

**Comment by achao2013** [comment]
the type of s is stream<gpu>, can it be used directly to construct tensor fron cpu? @feiyulv  @zihaolucky

**Comment by achao2013** [comment]
just discard s, that's ok ,thx @feiyulv

**Comment by sriharikarnam** [comment]
@achao2013:

Can you pls help me in printing  the value of some tensors in the Forward operation of convolution-inl.h .

Here is the code snippet  in convolution-inl.h

    Tensor<xpu, 3, DType> weight_3d = in_data[conv::kWeight].get_with_shape<xpu, 3, DType>(
      Shape3(group_, M, K), s);
    Tensor<xpu, 3, DType> col_buffer_3d = col_buffer.get_with_shape<xpu, 3, DType>(
      Shape3(group_, K, N), s);
    Tensor<xpu, 4, DType> output_4d = out_data[conv::kOut].get_with_shape<xpu, 4, DType>(
      Shape4(num_, group_, M, N), s);

Can i use the Copy function as suggested above. The definition of Copy function?
