### ISSUE TITLE
Is "graphviz" part of mxnet library or should we need to install it ourselves

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [dmlc/mxnet#4228]
I am trying to visualize networks using "mx.viz.plot_network" on notebook, I got import error for graphviz. However, after doing pip install graphviz, I was able to import graphviz.

Should we ask users to install graphviz library and add it to system path? 

I get below error when I try to plot graph in notebook:

RuntimeError: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' path

Should we add a step, in installation guide, to add path to graphviz lib in "ADD_LDFLAGS"?

**Comment by piiswrong** [comment]
yeah you need to install graphviz to use mx.viz
Probably add it to installation guide somewhere.
also in the automatic scripts

**Comment by bearnshaw** [comment]
@sandeep-krishnamurthy I'm running into the same error.  Installing graphviz in my python environment doesn't fix the issue, and I'm trying to build mxnet with the graphviz dependency but without any luck.  Any advice?

**Comment by inflation** [comment]
@bearnshaw You need to add graphviz's binary path into your PATH. It seems that mxnet is calling external commands about graphviz.

**Comment by bearnshaw** [comment]
thanks @inflation, turns out that `conda install graphviz` only gets the c libraries, and not the python bindings.  Following this up with `pip install graphviz` gets the python bindings.

**Comment by sandeep-krishnamurthy** [comment]
Correct. Installing will only get the binaries. But, we need pip install to get python bindings and lib path added correctly to PYTHONPATH.

This issue can be closed as I have submitted fix in this PR - https://github.com/dmlc/mxnet/pull/4240
