### ISSUE TITLE
How can I set the names of mx.sym like '+' or '*'

### ISSUE THREAD

**Issue by yang1fan2** [dmlc/mxnet#423]
Hi
      The last two operator in lstm layer is '+' and '*'. And I want to set the names of lstm's outputs.
Thanks;

**Comment by antinucleon** [comment]
```+``` and ```-``` are coding sugars, the full name will be ```mx.sym.Symbol._Plus```, ```mx.sym.Symbol._Mul```, so it should be like ```gates = mx.sym.Symbol._Plus(*[i2h, h2h], name="gates")```

**Comment by yang1fan2** [comment]
It is really helpful. Thanks!
