### ISSUE TITLE
How to use fastpoornet params and json file from WhatIsThis?

### ISSUE THREAD

**Issue by PhanTask** [dmlc/mxnet#4231]
## Environment info
Operating System:Ubuntu desktop 14.04 64bit
Compiler: g++
MXNet version:  v0.7
Python version and distribution: python2.7

## Error Message:
I took the params and symbol.json files of fastpoornet from WhatIsThis project and loaded them for a simple image classification ,but the result is incorrect. 
I'm sure that the code works since I tried other network files. Should I modify something in the code or the files?
(BTW I set allow_missing=True to avoid "RuntimeError: softmax0_label is not presented")

## Minimum reproducible example
import os
import mxnet as mx

f = open('synset.txt', 'r')
synsets = [l.rstrip() for l in f]

sym, arg_params, aux_params = mx.model.load_checkpoint(os.path.join(os.getcwd(), 'model', 'fastpoornet'), 0)

mod = mx.mod.Module(symbol=sym, context=mx.cpu())
mod.bind(for_training=False, data_shapes=[('data', (1,3,224,224))])
mod.set_params(arg_params, aux_params, allow_missing=True)

import matplotlib
matplotlib.rc("savefig", dpi=100)
import matplotlib.pyplot as plt
import cv2
import numpy as np
from collections import namedtuple
from tools.image_processing import transform
Batch = namedtuple('Batch', ['data'])

def predict(filename, mod, synsets):
    img = cv2.cvtColor(cv2.imread(filename), cv2.COLOR_BGR2RGB)
    if img is None:
        return None
    img = cv2.resize(img, (224, 224))
    data = transform(img, (117.0,117.0,117.0))
    img = np.swapaxes(img, 0, 2)
    img = np.swapaxes(img, 1, 2) 
    img = img[np.newaxis, :] 
    
    mod.forward(Batch([mx.nd.array(img)]))
    prob = mod.get_outputs()[0].asnumpy()
    prob = np.squeeze(prob)

    a = np.argsort(prob)[::-1]    
    for i in a[0:5]:
        print(i)
        print('probability=%f, class=%s' %(prob[i], synsets[i]))

print("ready")
predict("cat.jpg", mod, synsets)

## What have you tried to solve it?

I import transform from tools.image_processing to apply mean_pixels (117,117,117) but it doesn't work.

**Comment by thirdwing** [comment]
My suggestion is to use the latest inception model

**Comment by PhanTask** [comment]
@thirdwing Thanks very much! Could you tell me where to download the model you mentioned?

**Comment by thirdwing** [comment]
You can get the latest Inception model from http://data.mxnet.io/models/imagenet/inception-bn/

**Comment by PhanTask** [comment]
@thirdwing Thank you! I will try it.
