### ISSUE TITLE
Can mxnet be compiled by `gcc -xc++`?

### ISSUE THREAD

**Issue by songtianyi** [dmlc/mxnet#4235]
like gcc -xc++ ?

**Comment by DamonDeng** [comment]
Not sure what exactly you want by asking this question, as you know, there are many Nvidia CUDA code in mxnet project, and CUDA code has to be compiled by nvcc. That means you can't compile mxnet project only with c++ compiler if you want CUDA support.

And , you can find the compiler choice code in the make/config.mk file as below:

`export CC = gcc`
`export CXX = g++`
`export NVCC = nvcc`

Did you meant that you want to choose gcc as c++ compiler by `export CXX = gcc`? 
And why you want to use gcc as c++ compiler?

**Comment by songtianyi** [comment]
The difficulties i have met when trying to write go binding for mxnet told me the answer.
It's **NO**.
