### ISSUE TITLE
how to  find the max value of a tensor

### ISSUE THREAD

**Issue by achao2013** [dmlc/mxnet#4236]
i want to find the max value of a tensor.
i think of a method as follows:
Tensor<xpu, 2, DType> data = in_data[activation::kData].FlatTo2D<xpu, DType>(s);
Shape<1> maxshape=Shape<1>(1);
Tensor<xpu, 1, DType> out_max=NewTensor<xpu,DType,2>(maxshape,Dtype(0),false);
out_max=pool<mshadow::red::maximum>(pad(data,0,0),Shape<1>,data.shape_[0],data.shape_[1],1,1);

Are there any concise way?
And if i want to use the max value to the following calculation in gpu ,i can't access it using out_max[0] in cpu kernal, so how to solve it?

**Comment by jermainewang** [comment]
I think you could move this issue to [mshadow](http://github.com/dmlc/mshadow) repo since it is more relevant (and the question won't be flooded by other questions in this repo).
