### ISSUE TITLE
Add Swapaxes to Symbol

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#424]
like dimshuffle function in theano, or swapaxes in numpy, how can I do it in symbol?

**Comment by tqchen** [comment]
This is not yet in the symbols. It can be added with no knowledge of CUDA, by adding a new operator. MXNet C++ is based on mshadow, and in mshadow it can be done by

```c++
out = swapaxis<dim1, dim2>(src);
```

So the general idea is create a new operator [here](https://github.com/dmlc/mxnet/tree/master/src/operator)  which is backed by mshadow implementations.

Some reference:
- http://mxnet.readthedocs.org/en/latest/developer-guide/operator.html

Please let us know if you want to take a stab

**Comment by starimpact** [comment]
cool, i am very interested in it.
let me have a try.
by the way, does what i did in mshadow will be applied in gpu automatically?

**Comment by tqchen** [comment]
Yes

**Comment by starimpact** [comment]
CTC is also a popular algorithm for sequence data training. ^_^

**Comment by starimpact** [comment]
I found that the swapaxis supports template only, that means I need to enumerate all possible groups of swapaxis functions.for example:
swap 0 and 1, then swapaxis<1, 0>(....)
swap 0 and 2, then swapaxis<2, 0>(....)
swap 0 and 3, then swapaxis<3, 0>(....)
swap 2 and 3, then swapaxis<3, 2>(....)
........

**Comment by tqchen** [comment]
Thanks for point it out. Yes. These could be reduced to two possible cases by use it with together reshape. For example, say X is 3 dimension (c, t, h, w), what and we want to swap c and w, what we can do is 

Swap that involves the lowest dimension
```c++
reshape(swapaxis<0, 2>(reshape(X, (c, t *h, w))), (w, t, h, w))
```

General swap dim1, dim2
```c++
swapaxis<1, 3>(reshape(X, (prod(shape[0:dim1]), dim1, prod(shape[dim1:dim2]), dim2, prod(dim2:end]))
```

So you can use get_with_shape function in TBlob, which allows you to convert any TBlob contiguously into 4D Tensor using above rule,m and do swap axis on 1 and 3

**Comment by starimpact** [comment]
I try it with numpy of python and it works, this is really a tricky one.
Thank you very much.

**Comment by tqchen** [comment]
Thanks! Please open a PR for this

**Comment by starimpact** [comment]
I will do PR after I implement it in mxnet.

**Comment by starimpact** [comment]
Traceback (most recent call last):
  File "/home/mzhang/work/end-to-end/MXNetProject/swapaxis_test.py", line 8, in <module>
    import mxnet as mx
  File "/home/mzhang/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/mzhang/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/mzhang/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/mzhang/anaconda/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/home/mzhang/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/mzhang/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/libmxnet.so: undefined symbol: _ZTVN5mxnet2op12SwapAxisPropE

how to fix it ?

**Comment by tqchen** [comment]
Likely you forget to implement some function you declared in SwapAxisProp

**Comment by starimpact** [comment]
thanks, I fix it out.

**Comment by starimpact** [comment]
Hi, 
It still has a problem, can not work well in python. Can I send my SwapAxis code files to you and ask you to fix  the problem ?
what's your email ?

**Comment by tqchen** [comment]
You can open a PR with WIP flag, and I can help review it if you like

**Comment by starimpact** [comment]
I got the following error when I push, 
remote: Permission to dmlc/mxnet.git denied to starimpact.
fatal: unable to access 'https://github.com/dmlc/mxnet/': The requested URL returned error: 403

**Comment by tqchen** [comment]
You will need to do a fork, and send a pull request

**Comment by antinucleon** [comment]
Please refer: https://mxnet.readthedocs.org/en/latest/contribute.html

**Comment by starimpact** [comment]
i did the fork

**Comment by tqchen** [comment]
You want to clone the repo from your fork, instead of the dmlc's repo and push to your repo, something like
```
git clone git@github.com/startimpact/mxnet
```

**Comment by starimpact** [comment]
mxnet has child repository mshadow, how do i commit all changes in mxnet and mshadow?

**Comment by starimpact** [comment]
I found that what I forked mxnet is not the newest one.

**Comment by tqchen** [comment]
There are information here that can help you https://mxnet.readthedocs.org/en/latest/contribute.html

If you have changes made to mshadow, you want to clone mshadow separately and create a PR to https://github.com/dmlc/mshadow

**Comment by starimpact** [comment]
hi, please check my github, you can see the swapaxis.please check it.
thanks very much.

**Comment by tqchen** [comment]
Made the comments there

**Comment by starimpact** [comment]
there is 3 files in operator folder: swapaxis.cu, swapaxis.cc, swapaxis-inl.h.
add a Shape5 function in tensor.h in mshadow/mshadow

**Comment by starimpact** [comment]
the following is my test file.
the question is the 'print 5' will not be executed.
----------------------
A = mx.symbol.Variable('A')
a = mx.nd.ones((3, 4, 5))
print a
swap = mx.symbol.SwapAxis(A, dim1=0, dim2=2)
print 2
c_exec = swap.bind(ctx=mx.cpu(), args={'A' : a})
print 3
c_exec.forward()
print 4
rlt = c_exec.outputs[0].asnumpy()
print 5
print 'after swap:', rlt
---------------------------

**Comment by starimpact** [comment]
the following is my test file.
the question is the 'print 5' will not be executed.
```
A = mx.symbol.Variable('A')
a = mx.nd.ones((3, 4, 5))
print a
swap = mx.symbol.SwapAxis(A, dim1=0, dim2=2)
print 2
c_exec = swap.bind(ctx=mx.cpu(), args={'A' : a})
print 3
c_exec.forward()
print 4
rlt = c_exec.outputs[0].asnumpy()
print 5
print 'after swap:', rlt
```

**Comment by starimpact** [comment]
the following is my test file.
the question is the 'print 5' will not be executed.
```python
A = mx.symbol.Variable('A')
a = mx.nd.ones((3, 4, 5))
print a
swap = mx.symbol.SwapAxis(A, dim1=0, dim2=2)
print 2
c_exec = swap.bind(ctx=mx.cpu(), args={'A' : a})
print 3
c_exec.forward()
print 4
rlt = c_exec.outputs[0].asnumpy()
print 5
print 'after swap:', rlt
```

**Comment by tqchen** [comment]
Can you run a bit debug on this ? You can likely print out the messages in the forward function to see if things get executed. I also made a few comments on your impelemtnation

**Comment by starimpact** [comment]
Forward function is not be executed!

```
2
hello swapaxis CreateOperator!
hello swapaxis SwapAxisOp!
3
4
```

**Comment by tqchen** [comment]
Made a few more comment that you might want to fix. I guess will need your help in making the operator work

**Comment by starimpact** [comment]
As you see , I put the `printf` in the front of the `Forward` function.
```c++
  virtual void Forward(const OpContext &ctx,
                       const std::vector<TBlob> &in_data,
                       const std::vector<OpReqType> &req,
                       const std::vector<TBlob> &out_data,
                       const std::vector<TBlob> &aux_args) {
    using namespace mshadow;
    using namespace mshadow::expr;
    Stream<xpu> *s = ctx.get_stream<xpu>();
#if SWAPAXIS_DBG
    printf("hello swapaxis Forward!\n");
#endif
    uint32_t dim1 = param_.dim1;
    uint32_t dim2 = param_.dim2;
```

**Comment by starimpact** [comment]
Do you have QQ(47474167) or FB?

**Comment by starimpact** [comment]
delivery of parameter is ok.
but somewhere is corrupted.
```python
 11 A = mx.symbol.Variable('A')
 12 a = mx.nd.ones((3, 4, 5))
 13 print a
 14 swap = mx.symbol.SwapAxis(A, dim1=0, dim2=2)
 15 print 2
 16 c_exec = swap.bind(ctx=mx.cpu(), args={'A' : a})
 17 print 3
 18 c_exec.forward()
 19 print 4
 20 rlt = c_exec.outputs[0].asnumpy()
 21 print 5
 22 print 'after swap:', rlt
```
```
2
hello swapaxis CreateOperator!
hello swapaxis SwapAxisOp:dim1:0, dim2:2!
3
4
Segmentation fault (core dumped)
```

**Comment by starimpact** [comment]
I putted it into lenet.py, still can not work well.
```python 
 14 # second conv
 15 conv2 = mx.symbol.Convolution(data=pool1, kernel=(5,5), num_filter=50)
 16 tanh2 = mx.symbol.Activation(data=conv2, act_type="tanh")
 17 pool2 = mx.symbol.Pooling(data=tanh2, pool_type="max",
 18                           kernel=(2,2), stride=(2,2))
 19 pool2 = mx.symbol.SwapAxis(data=pool2, dim1=0, dim2=2)
```

**Comment by starimpact** [comment]
Yeah, I solved the problem.:smile:

**Comment by tqchen** [comment]
Great, can you cleanup the code and create a PR?

**Comment by starimpact** [comment]
But I come across another problem, still in progress.

**Comment by starimpact** [comment]
problem is solved, can run now, but still need more work.

**Comment by starimpact** [comment]
I have finished the new code based on your suggestions.
And the Backward is also completed.
Please check the code for me.Give me more suggestions.
Thank you very much.:smile:

**Comment by starimpact** [comment]
function is ready to go. please check it.
maybe there is a little code style problem.
:laughing: :smile: :smile_cat: :smiling_imp:

**Comment by starimpact** [comment]
I come across a problem:
```SwapAxis(..., dim1=2, dim2=3)```can work well on both cpu and gpu.
```SwapAxis(..., dim1=3, dim2=2)```only work well on cpu, but fail on gpu with the following error:
```
INFO:root:Start training with [gpu(0)]
[13:46:12] ./dmlc-core/include/dmlc/logging.h:208: [13:46:12] ./mshadow/mshadow/./tensor_blob.h:530: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
[13:46:12] ./dmlc-core/include/dmlc/logging.h:208: [13:46:12] src/engine/./threaded_engine.h:295: [13:46:12] ./mshadow/mshadow/./tensor_blob.h:530: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
terminate called after throwing an instance of 'dmlc::Error'
  what():  [13:46:12] src/engine/./threaded_engine.h:295: [13:46:12] ./mshadow/mshadow/./tensor_blob.h:530: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
Aborted (core dumped)
```
