### ISSUE TITLE
The program get stuck in check_call func when run rcnn demo.py on macbook Pro

### ISSUE THREAD

**Issue by universewill** [dmlc/mxnet#4244]
I use macbook Pro, so i modify the demo.py to use cpu.
Then i run "python demo.py --prefix final --epoch 0 --image myimage.jpg". However, the program got stuck in detector.py, line 89:

> scores = executor.output_dict['cls_prob_reshape_output'].asnumpy()[0]

i print the  executor.output_dict and the output seems to be ok:

> {'cls_prob_reshape_output': <NDArray 1x300x21 @cpu(0)>, 'bbox_pred_reshape_output': <NDArray 1x300x84 @cpu(0)>, 'rois_output': <NDArray 300x5 @cpu(0)>}

How can i solve this problem?

The tutorial link:
http://mxnet.io/tutorials/computer_vision/detection.html

It gets stuck when  run .asnumpy() function. Further, I find it gets stuck in the "check_call" function in .asnumpy() func.
I create a ndarray in python command console, However, the code runs correctly.
I don't know why it get stuck in Pycharm

Here is my test code in console:

>>> import mxnet as mx
>>> a = mx.nd.ones((1,300,21))
>>> a
<NDArray 1x300x21 @cpu(0)>
>>> print a.asnumpy()
[[[ 1.  1.  1. ...,  1.  1.  1.]
  [ 1.  1.  1. ...,  1.  1.  1.]
  [ 1.  1.  1. ...,  1.  1.  1.]
  ...,
  [ 1.  1.  1. ...,  1.  1.  1.]
  [ 1.  1.  1. ...,  1.  1.  1.]
  [ 1.  1.  1. ...,  1.  1.  1.]]]

**Comment by universewill** [comment]
It gets stuck when  run .asnumpy() function. 
I create a ndarray in python command console, However, the code runs correctly.
I don't know why it get stuck in Pycharm

Here is my test code in console:

> >>> import mxnet as mx
>>> a = mx.nd.ones((1,300,21))
>>> a
<NDArray 1x300x21 @cpu(0)>
>>> print a.asnumpy()
[[[ 1.  1.  1. ...,  1.  1.  1.]
  [ 1.  1.  1. ...,  1.  1.  1.]
  [ 1.  1.  1. ...,  1.  1.  1.]
  ...,
  [ 1.  1.  1. ...,  1.  1.  1.]
  [ 1.  1.  1. ...,  1.  1.  1.]
  [ 1.  1.  1. ...,  1.  1.  1.]]]

**Comment by jermainewang** [comment]
Does this only happen with Pycharm? How about directly run it with commandline?

**Comment by universewill** [comment]
I run "python demo.py", and it also stucks. @jermainewang

**Comment by universewill** [comment]
I reinstalled mxnet, but the problem still exists

**Comment by universewill** [comment]
This problem is the same as #3724
