### ISSUE TITLE
Mac OS setup config tutorial has incorrect code

### ISSUE THREAD

**Issue by liungkejin** [dmlc/mxnet#4257]
## Environment info
Operating System:
`Mac OS X EI Capitan 10.11.6`

Compiler:
`clang`

Description:
[Mac os setup](http://mxnet.io/get_started/osx_setup.html)
```bash
echo "ADD_LDFLAGS += -L/usr/local/opt/openblas/lib:/usr/local/lib/graphviz/" >> ./config.mk
```
在我的系统上，这种方式会把 `/usr/local/opt/openblas/lib:/usr/local/lib/graphviz/` 整个当成一个路径，出现路径不存在错误，无法编译通过, 所以需要分开写
```bash
echo "ADD_LDFLAGS += -L/usr/local/opt/openblas/lib" >> ./config.mk
echo "ADD_LDFLAGS += -L/usr/local/lib/graphviz/" >> ./config.mk
```

**Comment by thirdwing** [comment]
You can submit a PR. We appreciate your help.

**Comment by piiswrong** [comment]
@sandeep-krishnamurthy

**Comment by sandeep-krishnamurthy** [comment]
I will fix it. Thanks for pointing out.
