### ISSUE TITLE
Compilation error: "error: identifier 'mask' is undefined"

### ISSUE THREAD

**Issue by JonBoyleCoding** [dmlc/mxnet#4259]
I'm trying to compile mxnet on an Ubuntu 16.04 machine, and I've been getting multiple instances of this error when compiling (I pulled earlier today)

> mxnet/src/operator/./broadcast_mask_op-inl.h(50): error: identifier "mask" is undefined

This is when it's trying to compile the broadcast_mask_op.cu file (when compiling it for CUDA). It's happening during the macro expansions mentioned below.

Line 50 - ElementwiseMaskForward
```
  MSHADOW_TYPE_SWITCH(ret->type_flag_, DType, {
    mshadow::Tensor<xpu, 2, DType> out = ret->FlatTo2D<xpu, DType>(s);
    ASSIGN_DISPATCH(out, req,
      // TODO(bing): swap because requirement of inplace, change mshadow later
      mask(rhs.get<xpu, 1, DType>(s), lhs.FlatTo2D<xpu, DType>(s)));
  });
```

Line 72 - ElementwiseMaskBackward
```
  MSHADOW_TYPE_SWITCH(lhs_grad->type_flag_, DType, {
    mshadow::Tensor<xpu, 2, DType> mout_grad = out_grad.data.FlatTo2D<xpu, DType>(s);
    mshadow::Tensor<xpu, 2, DType> mlhs_grad = lhs_grad->FlatTo2D<xpu, DType>(s);
    mshadow::Tensor<xpu, 1, DType> mrhs_data = rhs.data.get<xpu, 1, DType>(s);
    ASSIGN_DISPATCH(mlhs_grad, req_lhs_grad,
      // TODO(bing): swap because requirement of inplace, change mshadow later
      mask(mrhs_data, mout_grad));
  });
```

I've had a look around the source code myself, but I'm unable to determine what this 'mask' may be (I presume it's meant to be a function).

Any ideas/help would be appreciated.

**Comment by piiswrong** [comment]
http://mxnet.io/get_started/ubuntu_setup.html

**Comment by JonBoyleCoding** [comment]
That helped, might suggest sorting out the CMakeLists.txt file to use all the necessary libraries and error if it can't find them in Linux.
