### ISSUE TITLE
Scala: bad default value in NDArrayIter constructor

### ISSUE THREAD

**Issue by benqua** [dmlc/mxnet#4261]
In [the NDArrayIter constructor ](https://github.com/dmlc/mxnet/blob/master/scala-package/core/src/main/scala/ml/dmlc/mxnet/io/NDArrayIter.scala#L26), the default value for label is null (`label: IndexedSeq[NDArray] = null`). 
If a user doesn't set label and keep the default value, then a scala.MatchError exception will be thrown at [ml.dmlc.mxnet.io.NDArrayIter.<init>(NDArrayIter.scala:33](https://github.com/dmlc/mxnet/blob/master/scala-package/core/src/main/scala/ml/dmlc/mxnet/io/NDArrayIter.scala#L33) because null cannot be cast to an IndexedSeq.

Default value for IndexedSeq could be IndexedSeq.empty.  Or, maybe better, label could be an Option[IndexedSeq] with default value set to None.

To reproduce, just try to intialize a NDArrayIter with:
`def iterFromNDArray(nda: NDArray): NDArrayIter = new NDArrayIter(IndexedSeq(aNDArray))`
It will fail with:
`[error] (run-main-2) scala.MatchError: (Vector(ml.dmlc.mxnet.NDArray@dfb083e0),null) (of class scala.Tuple2)
scala.MatchError: (Vector(ml.dmlc.mxnet.NDArray@dfb083e0),null) (of class scala.Tuple2)
	at ml.dmlc.mxnet.io.NDArrayIter.<init>(NDArrayIter.scala:33)
	at name.benq.ImageUtils$.iterFromNDArray(ImageUtils.scala:30)
`

For prediction, a user should not need to set the label.

**Comment by Ldpe2G** [comment]
@javelinjs I have confirm the error. @benqua or may be you could make a pr on this ?

**Comment by benqua** [comment]
@Ldpe2G , sure, I can make a PR about this.

First, if you agree, I will just change the default value IndexedSeq.empty because this way, it doesn't change / break the API of NDArrayIter.

In the long term, I think it would be better the use an Option[IndexedSeq] with a default of None; it is the idiomatic Scala way to express optional values. This would change the NDArrayIter API.

I should be able to do this in the next few days (but not before Monday).

**Comment by Ldpe2G** [comment]
@benqua  I think may be you can change to IndexedSeq.empty first, and it would be better to add a test case.  
@javelinjs what't your opinion?

**Comment by benqua** [comment]
I did a PR [here](https://github.com/dmlc/mxnet/pull/4280).

Not sure about what we should test exactly.
Right now, the tests fails with:
- train mnist *** FAILED ***
  0.9483 was not greater than 0.95 (ConvSuite.scala:94)

But I don't see how this is related to my changes.

**Comment by benqua** [comment]
I mess the commit merge. I redo the PR

**Comment by benqua** [comment]
@javelinjs I added the "require" to the PR. I not used to work with null in Scala.
@Ldpe2G I added a few more tests.
