### ISSUE TITLE
Fail to Run FCN Example with FCN8s or with "retrain" Flag On

### ISSUE THREAD

**Issue by II-Matto** [dmlc/mxnet#4267]
@tqchen @piiswrong @tornadomeet 
I tried to train an FCN8s with the FCN example provided in `example/fcn-xs`, but it always failed with OOM after 1 or 2 epochs. The error message is like below:

`INFO:root:Epoch[1] Batch [1980] Speed: 2.75 samples/sec Train-accuracy=0.692035
[17:38:03] /home/user_name/lib/mxnet/dmlc-core/include/dmlc/./logging.h:235: [17:38:03] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory
Traceback (most recent call last):
  File "/home/user_name/lib/mxnet/example/fcn-xs/fcn_xs.py", line 78, in <module>
    main()
  File "/home/user_name/lib/mxnet/example/fcn-xs/fcn_xs.py", line 62, in main
    epoch_end_callback  = mx.callback.do_checkpoint(fcnxs_model_prefix))
  File "/home/user_name/lib/mxnet/example/fcn-xs/solver.py", line 73, in fit
    aux_states=self.aux_params)
  File "/home/user_name/lib/mxnet/python/mxnet/symbol.py", line 852, in bind
    ctypes.byref(handle)))
  File "/home/user_name/lib/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:38:03] src/storage/./pooled_storage_manager.h:79: cudaMalloc failed: out of memory`

I have tried `mxnet-memonger` and called the `search_plan()` function before creating the `train_dataiter` in `example/fcn-xs/fcn_xs.py`. The inserted line is given below:
`fcnxs = memonger.search_plan(fcnxs, data=(1, 3, 2000, 2000))`
Data shapes of 1000, 1200, 1600, and 2000 were tried but none of them worked. The `mxnet-memonger` solved the problem with FCN32s with data shape of 1000 - FCN32s trained with over 40 epochs without reporting error. During all experiments, the `cut_off_size` is not set. Some relevant information I posted few days ago can be found in issue https://github.com/dmlc/mxnet/issues/3638#issuecomment-265673009.

Another Problem is that I cannot train an FCN with `retrain` flag set on. It reported error of `operands context mismatch`. When I set `ctx` to `gpu(3)` (https://github.com/dmlc/mxnet/blob/master/example/fcn-xs/fcn_xs.py#L14), the program reported `mxnet.base.MXNetError: [10:37:36] src/operator/operator_util.cc:886: Check failed: lhs.ctx() == rhs.ctx() operands context mismatch 2 3 vs. 1 0`.
More information posted by me can be found in issue https://github.com/dmlc/mxnet/issues/1935#issuecomment-265920113.

I used the latest MXNet on Ubuntu 14.04 with 12G-memory Titan X.

**Comment by II-Matto** [comment]
@tornadomeet @piiswrong @tqchen Hi, the OOM problem may be fixed by PR https://github.com/dmlc/mxnet/pull/4356.

**Comment by II-Matto** [comment]
Can someone help me with the `operands context mismatch` problem? This looks like an MXNet bug.

**Comment by tornadomeet** [comment]
thanks @II-Matto to solve the OOM problem of MXNet.

**Comment by II-Matto** [comment]
Thanks @tornadomeet for providing a good FCN example based on MXNet ^_^
