### ISSUE TITLE
How can I compile mxnet with nnpack support ?

### ISSUE THREAD

**Issue by erogol** [dmlc/mxnet#4271]
I saw that mxnet supports nnpack in the make config file but there is not documentation to help how to compile them together. Could you please help me to do so?

**Comment by u1234x1234** [comment]
You can do this with the following steps:
1. [Compile NNPACK](https://github.com/Maratyszcza/NNPACK#building)
2. set environment variables(CPATH, LIBRARY_PATH, LD_LIBRARY_PATH) to your NNPACK installation
3. set `USE_NNPACK = 1` in mxnet config.mk
4. build mxnet

**Comment by erogol** [comment]
where CPATH needs to point ?

**Comment by u1234x1234** [comment]
To the directory with header file nnpack.h
Something like that:
`export CPATH=/path/to/your/NNPACK/include`

**Comment by erogol** [comment]
Really thx. Yeap I finally compiled it. Do I need to call any thing extra to use NNPACK backend or it is on automatically when I call on CPU?

**Comment by u1234x1234** [comment]
Nope. It should work automatically.

**Comment by erogol** [comment]
I've not seen improvement over the normal run unfortunately with resnet 152 model. It takes ~0.003 for a single image in any ways.
