### ISSUE TITLE
On prediction mxnet requires same batch size as on training?

### ISSUE THREAD

**Issue by Strateus** [dmlc/mxnet#4275]
I want to predict from trained model:

    import mxnet as mx
    ...
    sym, arg_params, aux_params = mx.model.load_checkpoint(net_path, 9)
    mod = mx.mod.Module(symbol=sym, context=mx.gpu())

And after i put this:

    mod.bind(for_training = False, data_shapes=[('data', (1, 3, 384, 384))])

It fails with error:

    MXNetError: InferShape Error in reshape0: [03:12:50] src/operator/./reshape-inl.h:288: Check failed: (new_size % proposed_dim) == (0) Illegal dim setting, can't be divided.

If i set batch size to 96, 3, 384, 384 (which i used for training) - it works.
I want to predict several images, not 96, how can i do this?

**Comment by piiswrong** [comment]
please post your symbol

**Comment by Strateus** [comment]
[symbol.gz](https://github.com/dmlc/mxnet/files/659257/symbol.gz)

**Comment by piiswrong** [comment]
you hard coded shape in Reshape op.
```
"op": "Reshape", 
      "param": {
        "keep_highest": "False", 
        "reverse": "False", 
        "shape": "(96,7,10)", 
```
change shape to (0, 7, 10) instead

**Comment by Strateus** [comment]
thank you for the help! it worked!
