### ISSUE TITLE
Bug in "adam" optimizer in R

### ISSUE THREAD

**Issue by lbilli** [dmlc/mxnet#4282]
The following code generates an error:

    library(mxnet)
    w <- mx.nd.ones(c(2,3))
    x <- mx.opt.create("adam")
    state <- x$create.state(1, w)

    t2 <- "Something"
    new <- x$update(2, w, 1, state)

    Error in t + 1 : non-numeric argument to binary operator

The issue can be fixed by changing line 215 in optimizer.R

    if (!exists(envir = adam, x = time.key)){

with

    if (!exists(envir = adam, x = time.key, inherits=FALSE)){

The problem arises from the fact that the functions `exists()` and `get()` by default search also all parent environments. In this case a variable `t2` is found in the global environment, which is not what is expected.

Unfortunately, it looks like this technique of accessing variables inside environments by means of `assign/get/exists` is used in many other places of the code and possibly in other optimizers as well, so a more extensive fix is required.

A modest suggestion could be to leverage more the `$` and `[[` operators to access environments.
Instead of

    assign(x=name, envir=env, value=z)
    z <- get(x=name, envir=env, inherits=FALSE)

it's also possible to write

    env[[name]] <- z
    z <- env[[name]]

**Comment by thirdwing** [comment]
Thank you for reporting this.
