### ISSUE TITLE
New MXNetR version for windows 10 is much more slower :(

### ISSUE THREAD

**Issue by RogerBorras** [dmlc/mxnet#4283]
Hi,

I'm doing a project with MXNetR version for windows 10 and I downloaded the last update version. I found that this new version in much more slower than the previous ones... :( 
Is possible to adress this problemis with a new update??? mxnet version 0.9 it will be available soon?

Thanks,

**Comment by thirdwing** [comment]
As I said yesterday, I think the reason is blas.

BTW, can you provide some details on how slow it is now?

**Comment by RogerBorras** [comment]
Yes, you said one possible reason, but not if this can be adressed in the future :) I can't compare exactly, but I think is about 3 o 4 times slower (or more) in my CNN models and my dataset. I use MXNeR in windows 10, and the cpu is i7-6700HQ and 16GB RAM.

**Comment by thirdwing** [comment]
I suggest you compile mxnet from source after we merge the Windows instruction: https://github.com/dmlc/mxnet/pull/4256

**Comment by RogerBorras** [comment]
Thanks @thirdwing, I will try!!

**Comment by thirdwing** [comment]
@RogerBorras I have upload a new Windows pkg with the help from @jeremiedb 

This is built against openblas and should fix the speed problem. Please test it.

I am closing this now. Feel free to reopen if it is still slow.

**Comment by RogerBorras** [comment]
Thanks @thirdwing, fantastic job!!
