### ISSUE TITLE
Parameter conversion for calling auto-imported libmxnet APIs

### ISSUE THREAD

**Issue by pluskid** [dmlc/mxnet#429]
Similar question arise before when we were talking about row-major vs column-major in C/C++/Python vs. in R/Julia. That means the shape `(2,3,4)` in Julia/R side means the shape `(4,3,2)` in C++ backend. We did not come up with a very satisfactory solution. The current workaround is just to reverse all tuples passed to libmxnet APIs.

Another issue, due to the (unfortunate) design of Julia, is that it's array is 1-based. So for example, when calling `choose_element` function on `NDArray`, people should use 0-based indexing instead of 1-based. This could be confusing. Solutions could be

1. Easiest fix: just document it. Asking people to be careful when calling APIs.
2. Or we could augment the exporting API, to include a little bit more meta data. We could define some type hints for each parameters, like it should be a `Shape` or an `Index`. Then the frontend could do necessary preprocessing automatically.

**Comment by tqchen** [comment]
- I think for the shape convention, we should to the hint(```Shape```), the current way is OK for now, and we will be backward compatible in future.

- For ```choose_element```, this boils down to the question of how do we solve the convention of ```label```
   - This function is used to calculate loglikelihood as ```sum(log(choose_element(prob, label)))```
   - Since this is not frequently used, maybe consider name this function as ```choose_element_0index```

**Comment by pluskid** [comment]
OK, I see, I think it is fine to enforce the labels are 0,...,K-1.

**Comment by tqchen** [comment]
Yes, then I guess we either do the explicit API documentation, or even safer provide such information in name. Say change ```choose_element``` to ```choose_element_0index````

**Comment by pluskid** [comment]
Yes I think an explicit naming should be OK, as this is an low to intermediate level API and most users probably will not call it directly.

**Comment by tqchen** [comment]
Updated in #443
