### ISSUE TITLE
PLZ remove go from support list

### ISSUE THREAD

**Issue by songtianyi** [dmlc/mxnet#4290]
PLZ remove go from support list  which is described in repository description and README.md
Because **it's not true**.
The outdated repo [gomxnet](https://github.com/jdeng/gomxnet) is just wasting our time.

**Comment by mli** [comment]
hi songtian,

i noticed that you are working on the repo `go-mxnet-predictor`. will you be interested in contributing a go package for mxnet?

**Comment by songtianyi** [comment]
@mli 
I would finish **go-mxnet-predictor** first, it's on testing now.
c_predict_api is c api，it's easy to do go binding. But c_api is not. Maybe swig will be a solution.
I wish i could do that for mxnet. But i'm not sure i have enough time. If i have time i will.

**Comment by songtianyi** [comment]
@mli 
Hi,
I have finished my [go-mxnet-predictor](https://github.com/songtianyi/go-mxnet-predictor) project.
A Dockerfile is provided to build development environment. But meet some troubles with travis-ci.
I will fix it later, and sumbit a PR for adding it to mxnet  README :)
