### ISSUE TITLE
performence have problem

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#430]
training number:50000, validation number:10000, test number:10000
batch size:500
structure:
C:5x5, 20, P:2x2
C:5x5, 50, P:2x2
H:500, H:10
time cost:
theano(convolutional_mlp.py) 1 epoch: 7.00s
mxnet(lenet.py) 1 epoch: 8.989s

**Comment by starimpact** [comment]
platform: GT750m

**Comment by antinucleon** [comment]
lenet.py is training on 60000 images so there are 20% more computation.

**Comment by antinucleon** [comment]
Sorry accidentally close it. First, lenet is not a good benchmark. You can try larger net such as inception or alexnet. Second, you are counting IO time into it, where in MXNet, there is some real time optimization, where theano did in compiling time. Lastly, for single epoch, caching and buffering is time consuming but no significant effect.

**Comment by mli** [comment]
@antinucleon we probably give more information on the doc about how do the benchmarks

**Comment by starimpact** [comment]
thanks for your reply.
mxnet is the best structure I've ever seen.
I'm learning it on the way.
