### ISSUE TITLE
Speed information has problem

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#431]
Bug:
train, val = mnist_iterator(batch_size=500, input_shape=(1,28,28)) -> INFO:root:Iter[0] Batch [50]    Speed: 1315.65 samples/sec
train, val = mnist_iterator(batch_size=1000, input_shape=(1,28,28)) -> INFO:root:Iter[0] Batch [50]    Speed: 680.13 samples/sec

**Comment by antinucleon** [comment]
The Speedometer parameter is batch size, you need to change accordingly. Please change accordingly.

**Comment by starimpact** [comment]
got it.
