### ISSUE TITLE
why does it announce no exp?

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#432]
Traceback (most recent call last):
  File "/home/mzhang/work/end-to-end/MXNetProject/test2.py", line 14, in <module>
    D = mx.symbol.exp(C)
AttributeError: 'module' object has no attribute 'exp'

**Comment by antinucleon** [comment]
Please refer the document https://mxnet.readthedocs.org/en/latest/python/symbol.html .Note MXNet is not same theano

**Comment by tqchen** [comment]
This was added quite recently, so you might want to update the code and reinstall

**Comment by starimpact** [comment]
thank you all!
I am learning your structure and trying to add self stuff to mxnet, wish successful !
Maybe need one month to finish it.

**Comment by tqchen** [comment]
Please feel free to open issue if you find questions
