### ISSUE TITLE
tools/caffe_converter/convert_model.py should be updated

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#433]
line 54 in [convert_model.py](https://github.com/dmlc/mxnet/blob/master/tools/caffe_converter/convert_model.py),  should change num_round as num_epoch.

**Comment by tqchen** [comment]
@tornadomeet can you push a quick PR on this? :)

**Comment by tqchen** [comment]
oh,  i see it is already fixed :)
