### ISSUE TITLE
use simple_bind can't make continuous predictions

### ISSUE THREAD

**Issue by kyocen** [dmlc/mxnet#4330]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

**ubuntu 14.04**

MXNet version:
installed from source:  

**branch master**

If you are using python package, please provide

**Anaconda 4.2.0 (64-bit)**

Python version and distribution:

**Python 2.7.12**

## Error :

**I train a OCR model use CNN Multi-label net,when I predict a pic one time, the result is correct，but run twice,the first is correct and the second is wrong.**

***

code:

def TestRecognizeOne(file):
       
    ....
    batch_size = 1
    sym, arg_params, aug_params= mx.model.load_checkpoint("ocr", 0)
    data_shape = [("data", (batch_size, 3, 50, 200))]
    input_shapes = dict(data_shape)
    sym = getnet()
    executor = sym.simple_bind(ctx = mx.gpu(), **input_shapes)
    for key in executor.arg_dict.keys():
        if key in arg_params:
            arg_params[key].copyto(executor.arg_dict[key])

    executor.forward(is_train = False, data = mx.nd.array([img]))
    probs = executor.outputs[0].asnumpy()
    
    a=np.argmax(probs[0])
    b=np.argmax(probs[2])
    print a,b

and 

def getnet()
    
    data = mx.symbol.Variable('data')
    label = mx.symbol.Variable('label')
    conv1 = mx.symbol.Convolution(data=data, kernel=(5,5),pad=(2,2), num_filter=96)
    relu1 = mx.symbol.Activation(data=conv1, act_type="relu")
    pool1 = mx.symbol.Pooling(data=relu1, pool_type="max", kernel=(3,3), stride=(2, 2))
    
    conv2 = mx.symbol.Convolution(data=pool1, kernel=(3,3),pad=(1,1), num_filter=128)
    relu2 = mx.symbol.Activation(data=conv2, act_type="relu")
    pool2 = mx.symbol.Pooling(data=relu2, pool_type="max", kernel=(3,3), stride=(2, 2))
    
    flatten = mx.symbol.Flatten(data = pool2)
    fc1 = mx.symbol.FullyConnected(data = flatten, num_hidden = 2048)
    relufc1=mx.symbol.Activation(data=fc1, act_type="relu")
    dropout1 = mx.symbol.Dropout(data=relufc1, p=0.5)

    fc2 = mx.symbol.FullyConnected(data = dropout1, num_hidden = 1024)
    relufc2=mx.symbol.Activation(data=fc2, act_type="relu")
    dropout2 = mx.symbol.Dropout(data=relufc2, p=0.5)

    fc21 = mx.symbol.FullyConnected(data = dropout2, num_hidden = 35)
    fc22 = mx.symbol.FullyConnected(data = dropout2, num_hidden = 35)
    
    fc3 = mx.symbol.Concat(*[fc21, fc22], dim = 0)
    label = mx.symbol.transpose(data = label)
    label = mx.symbol.Reshape(data = label, target_shape = (0, ))
    return mx.symbol.SoftmaxOutput(data = fc3, name = "softmax")
***
when run

 testRecognizeOne("0.jpg")
 testRecognizeOne("0.jpg")

***
the output:
2,3
0,0

the probs:

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]

[ 0.02857143 0.02857143 0.02857143 0.02857143 0.02857143 0.02857143
0.02857143 0.02857143 0.02857143 0.02857143 0.02857143 0.02857143
0.02857143 0.02857143 0.02857143 0.02857143 0.02857143 0.02857143
0.02857143 0.02857143 0.02857143 0.02857143 0.02857143 0.02857143
0.02857143 0.02857143 0.02857143 0.02857143 0.02857143 0.02857143
0.02857143 0.02857143 0.02857143 0.02857143 0.02857143]

In addition
when I use simple_bind in lstm-ctc, cnn-ctc, I found the same problem.

**Comment by HHself** [comment]
I have the same problem.

**Comment by kyocen** [comment]
@piiswrong @kevinthesun

**Comment by piiswrong** [comment]
which warpctc version are you using? I think you need this commit 5bfb46e

**Comment by piiswrong** [comment]
I can't reproduce your problem. The following script:
```python
import mxnet as mx
import numpy as np

def getnet():
    data = mx.symbol.Variable('data')
    label = mx.symbol.Variable('label')
    conv1 = mx.symbol.Convolution(data=data, kernel=(5,5),pad=(2,2), num_filter=96)
    relu1 = mx.symbol.Activation(data=conv1, act_type="relu")
    pool1 = mx.symbol.Pooling(data=relu1, pool_type="max", kernel=(3,3), stride=(2, 2))

    conv2 = mx.symbol.Convolution(data=pool1, kernel=(3,3),pad=(1,1), num_filter=128)
    relu2 = mx.symbol.Activation(data=conv2, act_type="relu")
    pool2 = mx.symbol.Pooling(data=relu2, pool_type="max", kernel=(3,3), stride=(2, 2))

    flatten = mx.symbol.Flatten(data = pool2)
    fc1 = mx.symbol.FullyConnected(data = flatten, num_hidden = 2048)
    relufc1=mx.symbol.Activation(data=fc1, act_type="relu")
    dropout1 = mx.symbol.Dropout(data=relufc1, p=0.5)

    fc2 = mx.symbol.FullyConnected(data = dropout1, num_hidden = 1024)
    relufc2=mx.symbol.Activation(data=fc2, act_type="relu")
    dropout2 = mx.symbol.Dropout(data=relufc2, p=0.5)

    fc21 = mx.symbol.FullyConnected(data = dropout2, num_hidden = 35)
    fc22 = mx.symbol.FullyConnected(data = dropout2, num_hidden = 35)

    fc3 = mx.symbol.Concat(*[fc21, fc22], dim = 0)
    label = mx.symbol.transpose(data = label)
    label = mx.symbol.Reshape(data = label, target_shape = (0, ))
    return mx.symbol.SoftmaxOutput(data = fc3, name = "softmax")

def test():
    data_shape = [("data", (2, 3, 50, 200))]
    input_shapes = dict(data_shape)
    sym = getnet()
    executor = sym.simple_bind(ctx = mx.gpu(), **input_shapes)
    for key in executor.arg_dict.keys():
        executor.arg_dict[key][:] = np.random.uniform(-1, 1, size=executor.arg_dict[key].shape)

    executor.forward(is_train = False, data = mx.nd.array(np.random.uniform(-1, 1, size= (2, 3, 50, 200))))
    probs = executor.outputs[0].asnumpy()
    print 'probs'
    print probs

test()
test()
```
gives output
```
probs
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
probs
[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
```
which looks fine

**Comment by kyocen** [comment]
@piiswrong I try your way, and  I found the same problem.   
You use random.uniform funtion,  so continuous predictions have different weights and outputs.
If you use pretrian model, you will get the problem.  

my test:  

    batch_size = 2
    _, arg_params, _ = mx.model.load_checkpoint("cnn-ctc", 30)
    data_shape = [("data", (batch_size, 3, 30, 100))]
    input_shapes = dict(data_shape)
    sym = get_ocrnet()
    executor = sym.simple_bind(ctx=mx.gpu(), **input_shapes)
    for key in executor.arg_dict.keys():
        if key in arg_params:
            executor.arg_dict[key][:] = arg_params[key]

    executor.forward(is_train=False, data = mx.nd.array(np.random.uniform(-1, 1, size= (2, 3, 30, 100))))
    probs = executor.outputs[0].asnumpy()
    print "probs"
    print probs[1]


test()
test()  
and out:

probs
[  3.93073746e-19   1.46699641e-02   2.93299945e-05   7.28891743e-03
   2.37810407e-02   8.35087709e-03   8.80187005e-02   6.82246029e-01
   8.13545473e-03   6.83218464e-02   8.97907615e-02   3.38167933e-06
   2.60647794e-05   4.16573982e-07   2.37366658e-05   5.05172920e-07
   7.42944621e-06   1.35100354e-05   3.32285777e-09   3.11700266e-09
   1.36838807e-09   1.15453185e-08   2.69324807e-09   4.00096396e-05
   4.06483050e-05   3.83347398e-09   1.27943513e-05   5.79223292e-09
   1.82321997e-08   2.70072764e-09   3.04716741e-09   5.75748160e-09
   1.77627300e-08   6.51105694e-08   2.34668907e-08   1.34857302e-07
   8.35137026e-09   9.72221824e-05   1.40983239e-03   1.65687516e-06
   1.29104053e-04   1.73651861e-05   3.86384272e-05   2.67458909e-05
   1.79124265e-06   7.49877836e-06   1.31085308e-05   6.08216906e-05
   1.15468547e-05   2.64929440e-05   1.87843943e-05   1.52559423e-05
   3.51799396e-03   1.34349815e-04   3.61144636e-03   1.14672662e-06
   2.63678317e-06   5.05045762e-07   2.95765108e-06   3.53589229e-07
   5.07219738e-05   4.11070431e-08   2.92843225e-07]
probs
[ 0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302  0.01587302
  0.01587302  0.01587302  0.01587302]

**Comment by fengqilr** [comment]
I have the same question, but I have solved it with tensorflow @piiswrong @kyocen

**Comment by anuoeattoomuch** [comment]
i have the same problem!Wait 4 solve！ @kyocen

**Comment by piiswrong** [comment]
still can not reproduce:
```python
import mxnet as mx
import numpy as np

def getnet():
    data = mx.symbol.Variable('data')
    label = mx.symbol.Variable('label')
    conv1 = mx.symbol.Convolution(data=data, kernel=(5,5),pad=(2,2), num_filter=96)
    relu1 = mx.symbol.Activation(data=conv1, act_type="relu")
    pool1 = mx.symbol.Pooling(data=relu1, pool_type="max", kernel=(3,3), stride=(2, 2))

    conv2 = mx.symbol.Convolution(data=pool1, kernel=(3,3),pad=(1,1), num_filter=128)
    relu2 = mx.symbol.Activation(data=conv2, act_type="relu")
    pool2 = mx.symbol.Pooling(data=relu2, pool_type="max", kernel=(3,3), stride=(2, 2))

    flatten = mx.symbol.Flatten(data = pool2)
    fc1 = mx.symbol.FullyConnected(data = flatten, num_hidden = 2048)
    relufc1=mx.symbol.Activation(data=fc1, act_type="relu")
    dropout1 = mx.symbol.Dropout(data=relufc1, p=0.5)

    fc2 = mx.symbol.FullyConnected(data = dropout1, num_hidden = 1024)
    relufc2=mx.symbol.Activation(data=fc2, act_type="relu")
    dropout2 = mx.symbol.Dropout(data=relufc2, p=0.5)

    fc21 = mx.symbol.FullyConnected(data = dropout2, num_hidden = 35)
    fc22 = mx.symbol.FullyConnected(data = dropout2, num_hidden = 35)

    fc3 = mx.symbol.Concat(*[fc21, fc22], dim = 0)
    label = mx.symbol.transpose(data = label)
    label = mx.symbol.Reshape(data = label, target_shape = (0, ))
    return mx.symbol.SoftmaxOutput(data = fc3, name = "softmax")

def test():
    data_shape = [("data", (2, 3, 50, 200))]
    input_shapes = dict(data_shape)
    sym = getnet()
    mod = mx.mod.Module(sym)
    mod.bind(data_shapes=data_shape)
    mod.init_params(initializer=mx.init.Uniform(1.0))
    mx.model.save_checkpoint('test', 0, sym, *mod.get_params())
    _, arg_params, _ = mx.model.load_checkpoint('test', 0)
    executor = sym.simple_bind(ctx = mx.gpu(), **input_shapes)
    for key in executor.arg_dict.keys():
        if key in arg_params:
            executor.arg_dict[key][:] = arg_params[key]

    executor.forward(is_train = False, data = mx.nd.array(np.random.uniform(-1, 1, size=(2, 3, 50, 200))))
    probs = executor.outputs[0].asnumpy()
    print 'probs'
    print probs

test()
test()
```

**Comment by piiswrong** [comment]
still not reproducing:
```python
import mxnet as mx
import numpy as np

def getnet():
    data = mx.symbol.Variable('data')
    label = mx.symbol.Variable('label')
    conv1 = mx.symbol.Convolution(data=data, kernel=(5,5),pad=(2,2), num_filter=96)
    relu1 = mx.symbol.Activation(data=conv1, act_type="relu")
    pool1 = mx.symbol.Pooling(data=relu1, pool_type="max", kernel=(3,3), stride=(2, 2))

    conv2 = mx.symbol.Convolution(data=pool1, kernel=(3,3),pad=(1,1), num_filter=128)
    relu2 = mx.symbol.Activation(data=conv2, act_type="relu")
    pool2 = mx.symbol.Pooling(data=relu2, pool_type="max", kernel=(3,3), stride=(2, 2))

    flatten = mx.symbol.Flatten(data = pool2)
    fc1 = mx.symbol.FullyConnected(data = flatten, num_hidden = 2048)
    relufc1=mx.symbol.Activation(data=fc1, act_type="relu")
    dropout1 = mx.symbol.Dropout(data=relufc1, p=0.5)

    fc2 = mx.symbol.FullyConnected(data = dropout1, num_hidden = 1024)
    relufc2=mx.symbol.Activation(data=fc2, act_type="relu")
    dropout2 = mx.symbol.Dropout(data=relufc2, p=0.5)

    fc21 = mx.symbol.FullyConnected(data = dropout2, num_hidden = 35)
    fc22 = mx.symbol.FullyConnected(data = dropout2, num_hidden = 35)

    fc3 = mx.symbol.Concat(*[fc21, fc22], dim = 0)
    label = mx.symbol.transpose(data = label)
    label = mx.symbol.Reshape(data = label, target_shape = (0, ))
    return mx.symbol.SoftmaxOutput(data = fc3, name = "softmax")

data_shape = [("data", (2, 3, 50, 200))]
input_shapes = dict(data_shape)
sym = getnet()
mod = mx.mod.Module(sym)
mod.bind(data_shapes=data_shape)
mod.init_params(initializer=mx.init.Uniform(1.0))
mx.model.save_checkpoint('test', 0, sym, *mod.get_params())
x = mx.nd.array(np.random.uniform(-1, 1, size=(2, 3, 50, 200)))

def test():
    _, arg_params, _ = mx.model.load_checkpoint('test', 0)
    executor = sym.simple_bind(ctx = mx.gpu(), **input_shapes)
    for key in executor.arg_dict.keys():
        if key in arg_params:
            executor.arg_dict[key][:] = arg_params[key]

    executor.forward(is_train = False, data = x)
    probs = executor.outputs[0].asnumpy()
    print 'probs'
    print probs

test()
test()
```

outputs
```
probs
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]
probs
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]
```

**Comment by kyocen** [comment]
@piiswrong I try your way to init a new weights and solve the problem. I think my model weights or .json file have something wrong.  I will train a new model weights this week .thank you.

**Comment by kyocen** [comment]
@piiswrong I try your way in my model last weekend and find the same problem in my mxnet. but I found the reason.
if I load a pretrain model file use _ _,arg_params, _ = mx.model.load_checkpoint('cnn-ctc', 30)_  
the first conv layer weights name is **'convolution0_weight'**,
when I init a executor  
_executor = sym.simple_bind(ctx = mx.gpu(), **input_shapes)_  
_for key in executor.arg_dict.keys():_  
the executor that first used has the same name of fist conv layer weights.
but when I use executor continuous the **executor.arg_dict.keys()** changed.

pretrain model weights name:  
['convolution2_weight', 'convolution0_bias', 'fullyconnected0_weight', 'fullyconnected0_bias', 'convolution1_bias', 'convolution1_weight', 'convolution0_weight', 'convolution2_bias']  

when I use continuous predict,the weigths name of executor.arg_dict.keys():  
['convolution26_bias', 'convolution24_bias', 'fullyconnected8_weight', 'data', 'softmax_label', 'convolution26_weight', 'convolution24_weight', 'fullyconnected8_bias', 'convolution25_weight', 'convolution25_bias']

I use a dict of weigths shape to bind different names . I think this problem can be solved by same better way.
