### ISSUE TITLE
Some hard time compiling mxnet on mac :(

### ISSUE THREAD

**Issue by alinagithub** [dmlc/mxnet#4332]
Operating System: macOS Sierra
Following the installation steps goes well.
Finally when executing "make -j$(sysctl -n hw.ncpu)", I get the following errors:

clang: error: no such file or directory: '/usr/local/lib/libopencv_calib3d.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_contrib.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_core.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_features2d.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_flann.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_gpu.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_highgui.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_imgproc.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_legacy.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_ml.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_nonfree.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_objdetect.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_ocl.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_photo.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_stitching.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_superres.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_video.dylib'
clang: error: no such file or directory: '/usr/local/lib/libopencv_videostab.dylib'

if looking in my directory, I see my libs all have the 2.4.7 suffix, such as: libopencv_calib3d.2.4.7.dylib

Any thought? Either changing the make or the names of the libs would work?
Many thanks !

**Comment by kevinthesun** [comment]
Try reinstalling opencv?

**Comment by piiswrong** [comment]
how did you install opencv? homebrew?
what's the output of `pkg-config --cflags --libs opencv`?

**Comment by alinagithub** [comment]
I used "brew install opencv"... but I also updated my Anaconda install. Could be this.

pkg-config --cflags --libs opencv
-I/usr/local/include/opencv -I/usr/local/include /usr/local/lib/libopencv_calib3d.dylib /usr/local/lib/libopencv_contrib.dylib /usr/local/lib/libopencv_core.dylib /usr/local/lib/libopencv_features2d.dylib /usr/local/lib/libopencv_flann.dylib /usr/local/lib/libopencv_gpu.dylib /usr/local/lib/libopencv_highgui.dylib /usr/local/lib/libopencv_imgproc.dylib /usr/local/lib/libopencv_legacy.dylib /usr/local/lib/libopencv_ml.dylib /usr/local/lib/libopencv_nonfree.dylib /usr/local/lib/libopencv_objdetect.dylib /usr/local/lib/libopencv_ocl.dylib /usr/local/lib/libopencv_photo.dylib /usr/local/lib/libopencv_stitching.dylib /usr/local/lib/libopencv_superres.dylib /usr/local/lib/libopencv_ts.a /usr/local/lib/libopencv_video.dylib /usr/local/lib/libopencv_videostab.dylib

I will try re-installing opencv... even if from that, everything seems ok, no?
Many thanks for your help !

**Comment by alinagithub** [comment]
Ah actually I get the following message:

brew install opencv
Warning: homebrew/science/opencv-2.4.13.2 already installed, it's just not linked.

**Comment by alinagithub** [comment]
OK got it. 
Permission issue - pretty tough to find out how to overcome the brew limitations to link in the root...
Again many thanks for your inputs!
AL
