### ISSUE TITLE
Installation file removed from repository

### ISSUE THREAD

**Issue by lfdmotta** [dmlc/mxnet#4338]
When trying to install mxnet as an R package:

> Warning in install.packages :
>   URL 'http://dmlc.ml/drat/src/contrib/mxnet_0.7.tar.gz': status was '404 Not Found'
> Error in download.file(url, destfile, method, mode = "wb", ...) : 
> 

R `sessionInfo()`:
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] drat_0.1.2       RevoUtils_10.0.2 tools_3.3.2

**Comment by thirdwing** [comment]
We don't host the Linux pkg.

**Comment by thirdwing** [comment]
My mistake: if you brew installed the R on OSX. Please try to use 

```r
install.package("mxnet", type="mac.binary")
```

This is due to the non-standard configuration by brew maintainers.

**Comment by lfdmotta** [comment]
Hi thirdwing,

Thanks for your comment.

I installed Microsoft R Open. 

When I try

`drat:::addRepo("dmlc")`
`install.packages("mxnet", type="mac.binary")`

it also does not work:

> Warning in install.packages :
>   URL 'http://dmlc.ml/drat/bin/macosx/contrib/3.3/PACKAGES.gz': status was '404 Not Found'
> Warning in install.packages :
>   URL 'http://dmlc.ml/drat/bin/macosx/contrib/3.3/PACKAGES': status was '404 Not Found'
> Warning in install.packages :
>   unable to access index for repository https://dmlc.github.io/drat/bin/macosx/contrib/3.3:
>   cannot download all files
>    package ‘mxnet’ is available as a source package but not as a binary
> 
> Warning in install.packages :
>   package ‘mxnet’ is not available (as a binary package for R version 3.3.2)
>

**Comment by thirdwing** [comment]
This seems due to you are using the new OSX.

The package is here: https://github.com/dmlc/drat/tree/gh-pages/bin/macosx/mavericks/contrib/3.3

You can download and install it locally.

**Comment by lfdmotta** [comment]
@thirdwing Thanks!
