### ISSUE TITLE
ImageRecordIter on multi-label rec file failed

### ISSUE THREAD

**Issue by GestaltzerFall** [dmlc/mxnet#4347]
hi,
I'm trying to follow the multi-task example using my own data, I use im2rec to make the multi-label rec file like

`im2rec train.txt train_imgs/ ./data/imgrec.rec label_width=2`

and get the rec file successfully, but when I am trying to use mx.io.ImageRecordIter to load the recfile and make a dataIter,

```
train_iter = mx.io.ImageRecordIter(
	path_imgrec="./data/imgrec.rec",
	data_shape=(1, 28, 28),
	batch_size=2)
```

can pass and 

```
train_iter = mx.io.ImageRecordIter(
	label_width = 2,
	path_imgrec="./data/imgrec.rec",
	data_shape=(1, 28, 28),
	batch_size=2)
```
will return

> [04:58:12] src/io/iter_image_recordio.cc:318: Check failed: (param_.label_width) == (1) label_width must be 1 unless an imglist is provided or the rec file is packed with multi dimensional label

who knows how to solve this problem?

**Comment by piiswrong** [comment]
path_imglist = './data/imgrec.lst'
