### ISSUE TITLE
Memory Leak Problem in c_api: MXAPIThreadLocalEntry *ret = MXAPIThreadLocalStore::Get()

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#4357]
@piiswrong @tqchen 
I noticed that the memory will leak when I use c_api functions.
the reason is the ```MXAPIThreadLocalEntry *ret = MXAPIThreadLocalStore::Get()```. It will create a static class object MXAPIThreadLocalStore for every c_api functions who call it. 
obviously, static object only be released when the program is exited.
this is a big BUG!! Am I right?
I wrote a simulation to check it:
```cpp
#include <vector>
#include <iostream>
using namespace std;


class Hello
{
public:
  Hello(){cout << "create!\n";}
  ~Hello(){cout << "destroyed!\n";}
public:
  static int *Get()
  {
    static Hello obj;
    int *p = new int[10];
    obj.data_.push_back(p);
    cout << "data size:" << obj.data_.size() << endl;
    return p;
  }

private:
  vector<int*> data_;
};

main()
{
  for (int i = 0; i < 100; i++)
  {
    int *p = Hello::Get();
  }
}
```
the out put is:
```
create!
data size:1
data size:2
data size:3
data size:4
data size:5
data size:6
data size:7
data size:8
data size:9
data size:10
data size:11
data size:12
data size:13
data size:14
data size:15
data size:16
data size:17
data size:18
data size:19
data size:20
data size:21
data size:22
data size:23
data size:24
data size:25
data size:26
data size:27
data size:28
data size:29
......
```
the upper result verifies my opinion.

**Comment by tqchen** [comment]
static variable is initialized once, the content of static function will be executed multiple times, as you can see from your program, Hello is only created once despite so many calls. There is no code(such as new or delete as you did) in the static function

**Comment by starimpact** [comment]
oh.... yes, I should see the static ptr.
```
  static T* Get() {
    static MX_TREAD_LOCAL T* ptr = nullptr;
    if (ptr == nullptr) {
      ptr = new T();
      Singleton()->RegisterDelete(ptr);
    }
    return ptr;
  }
```
