### ISSUE TITLE
What is the right and 100% working configuration under Ubuntu 16.04LTS?

### ISSUE THREAD

**Issue by motypas** [dmlc/mxnet#4358]
Hi,

anyone can tell me the right, TESTED and 100%  WORKING configuration under Ubuntu for **deep3d**?

**This config is work???**
Ubuntu 16.04LTS -64bit
Cuda 8
DNN 5.1
Nvidia 1080-8gb
mxnet from git
deep3d from git

Thank You So So much and Merry Christmas!!!

Best
Moty

**Comment by andremoeller** [comment]
Do you mean working values in your config.mk? I'm running on Ubuntu 16.04, Cuda 8.0, CUDNN 5.1, with an Nvidia GTX 1080.

Did you try following the deep3d readme? If so, what went wrong (error output would be great). It says:
```
Please open mxnet/config.mk and set USE_CUDA and USE_CUDNN to 1. Then, append EXTRA_OPERATORS=path/to/deep3d/operators to path/to/mxnet/config.mk and recompile MXNet.
```

To build MXNet with CUDA and CUDNN support, you also need to copy make/config.mk to the mxnet base directory, and set USE_CUDA_PATH to your CUDA installation path (like /usr/local/cuda), and make sure you've put the CUDNN header in /usr/local/cuda/include and libraries in /usr/local/cuda/lib64.

**Comment by motypas** [comment]
Hi, thanks I know the installation guide... but I read some issue what cuda and DNN combination has a great quality for deep3d.  And on other forum has report problem with 7.5- 5.0 combination quality and bug for gtx 1070 and 1080 and python compatibility problem under cuda 8, other user says the great combination is cuda7 and dnn4  under 14.04 so... now then Im a little bit confuse. So You say under 16.04 cuda8 and dnn5.1 work fine with deep 3d?

**Comment by motypas** [comment]
Now the installation is complete no error. Can You tell me how can I test the deep3d for example how can I convert to 3d the demo.jpg?
