### ISSUE TITLE
Proposal on new data augmenter pipeline

### ISSUE THREAD

**Issue by howard0su** [dmlc/mxnet#4366]
Current implementation is implemented augmenter as a add-on of certain iterator implementation. This approach is very close to what Caffe is implementing. From my point of view, this is not the best way to implement a flexible data augmenter.

In MXNet iterator implementation, it is common that we stack one iterator over another. For example, put a prefetch iterator over recordio iterator. I would suggest to implement data augmenter as a set of iterators. We can implement scale, crop, color distort, padding, rotate as a set of iterators.

Benefits:
1. more flexible pipeline.
This can satisfied more different requirement on data augmenter.

2. Reuse the pipe between image classification and detection
In order to data augment the data for detection, label have to do the transform related to image's transform. for example, scale. current implementation will require this either using a option to state detection or classification, or implement another data augmenter for detection. If we go with the new approach, we can just write one additional data augmenter for label. this data augmenter can do the corresponding transform for label. (each image data augmenter need expose the actual argument to do the image transform through an additional variable?)

Love to hear your suggestions or options before I do actual coding.

**Comment by piiswrong** [comment]
mx.image.ImageIter is doing something similar to that.
However its hard to reuse large chunk of code from recognition for detection due to the coupling of image and label processing.
You can still reuse functions like random_crop.

**Comment by howard0su** [comment]
I am exactly proposing to solve this by decoupling. The image processing iter should expose the parameter how it process the image and another label processing iter consume it. even for random_crop, the logic to process label still need the random_crop_offsetx, random_crop_offsety to process bbox.

**Comment by piiswrong** [comment]
Seems overly complicated. I think we just need to have enough helper functions so that it's easy to write a coupled iterator that process data and label together

**Comment by howard0su** [comment]
Let me think about this bit more. i am looking at consolidate ssd sample with rcnn sample.
