### ISSUE TITLE
KVStore API in CUDA-enabled MxNet does not work without GPU.

### ISSUE THREAD

**Issue by mcxkarakoc** [dmlc/mxnet#4368]
I'm not sure if this is a bug. Maybe intentional.

After I compiled MxNet source with USE_CUDA=1, I tried KVStore API on a Linux machine without GPU. When I use the example in Mxnet docs, CUDA error below is raised after kv.init. 
"... src/storage/storage.cc:38: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error "

Example:
`>>> kv = mx.kv.create('local') # create a local kv store.`
`>>> shape = (2,3)`
`>>> kv.init(3, mx.nd.ones(shape)*2)  # CUDA error is raised after this line`
`>>> a = mx.nd.zeros(shape)`
`>>> kv.pull(3, out = a)`

For USE_CUDA=0, there is no problem.

**Comment by howard0su** [comment]
This blocks MXNet to release as binary package

**Comment by mli** [comment]
should be fixed by #4550

**Comment by mcxkarakoc** [comment]
#4550 confirmed. Just for information: "NVIDIA: no NVIDIA devices found" message is still displayed. Maybe useful.
