### ISSUE TITLE
Predict using GPU

### ISSUE THREAD

**Issue by No41Name** [dmlc/mxnet#4379]
How can I predict on my validation dataset using GPU, after loading a model?
I've trained my model on GPU and then I saved it from terminal, but when I load the model for doing predictions only CPU is used:

`model_loaded = mx.model.FeedForward.load(prefix, iteration)
 preds=model_loaded.predict(validation_dataset)
`

How can I predict with GPU instead of CPU, since there are no ctx parameters in the predict function?
Thanks!

**Comment by u1234x1234** [comment]
```
model_loaded = mx.model.FeedForward.load(prefix, iteration, ctx=mx.gpu())
preds=model_loaded.predict(validation_dataset)
```

**Comment by No41Name** [comment]
Thanks!!
