### ISSUE TITLE
Amalgamation for Android Changes Model Behavior

### ISSUE THREAD

**Issue by d4wud** [dmlc/mxnet#4385]
I am running amalgamation for Android and noticed some strange behavior.  I wrote a unit test for [Leliana/WhatsThis](https://github.com/Leliana/WhatsThis) and discovered that the `libmxnet_predict.so` amalgamated from the most recent master branch changes the behavior of the model.  

For the same model, params and input, feedforward results in different output using the freshly amalgamated `.so`.  I am using an image of a guinea pig, which resulted in 'hamster' using the WhatsThis model, but now outputs 'nematode.  In fact, updating the `.so` for WhatsThis outputs 'nematode' for most images.

master branch amalgamated: 1ff820a03846b84fc370850ed3770ce52d8169dd

Can anyone help me find out if this is my issue, an amalgamation issue, or simply an artifact of the WhatsThis model?  I can upload my test if needed.

Thanks!

**Comment by piiswrong** [comment]
@antinucleon add a test for amalgamation like tests/python/gpu/test_forward.py?

**Comment by d4wud** [comment]
@piiswrong @antinucleon Update: the issue only appears when using the `model.params` and `symbol.json` from WhatsThis.  I have gotten [squeezenet_v1.1](https://github.com/dmlc/mxnet-model-gallery/blob/master/imagenet-1k-squeezenet.md) working successfully using the amalgamated `.so` from the now current dc1a36064d7166c359110bc297ef9ec174eb63d0. 

I have complete unit tests (Android) for WhatsThis that I am happy to contribute.  Please let me know if you can use my help.

**Comment by ydmo** [comment]
@d4wud Hi， I have the same problem, did you solve this, please help me!!! Thanks a lot~

**Comment by d4wud** [comment]
@ydmo I believe the problem is that the model in Leliana/WhatsThis is incompatible with the current state of mxnet amalgamation.  Re-amalgamate and replace the `params` and `symbol.json` with those from [Squeezenet v1.1](https://github.com/dmlc/mxnet-model-gallery/blob/master/imagenet-1k-squeezenet.md) and it should work.

**Comment by ydmo** [comment]
@d4wud yeah! it works! Thanks a lot!

**Comment by d4wud** [comment]
@piiswrong should I close this issue?
