### ISSUE TITLE
Development based on v0.9rc1

### ISSUE THREAD

**Issue by itsarbit** [dmlc/mxnet#4389]
We are currently developing based on MXNet and can be benefitted from severals commits on [v0.9 rc1](https://github.com/dmlc/mxnet/tree/v0.9rc1), such as MXProfiler and optimizer changes. However, the difference between the branch and master branch is extremely large. Therefore, in order to leverage those advantages for development, I am wondering if there is any potential issue based on this branch? In addition, do you have any updated schedule to release next stable release?

**Comment by piiswrong** [comment]
0.9 will be released in a few days. Possibly tomorrow

**Comment by itsarbit** [comment]
That's definitely a good news for us! Thanks.
