### ISSUE TITLE
windows cmake problem

### ISSUE THREAD

**Issue by wangxianliang** [dmlc/mxnet#439]
I put protobuf under the mxnet directory and successfully built the binary protoc.exe and set PROTOBUF_SRC_ROOT_FOLDER  to  .\mxnet\protobuf-master\install
however, when I configure mxnet project using cmake, it pops up the following errors:

Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY) 
CMake Error at ps-lite/cmake/ProtoBuf.cmake:13 (message):
  Could not find PROTOBUF Compiler
Call Stack (most recent call first):
  ps-lite/CMakeLists.txt:16 (include)

Could anybody help? Thanks a lot.

**Comment by tqchen** [comment]
You can disable the protobuf dep by simply not compile with ps-lite by default. @mli Maybe we want to switch off ps-lite dep on default compile on windows?

**Comment by loveisp** [comment]
You can just uncheck the option "USE_DIST_KVSTORE" in CMake GUI. But this error is disgusting for me and  take me a few hours.

**Comment by yajiedesign** [comment]
use advanced mode ,you can set PROTOBUF_*.and it work ok

**Comment by wangxianliang** [comment]
Thanks! advanced mode works for me.

**Comment by cupermanrose** [comment]
@tqchen  I had the same problem in windows.Can Mxnet  compile with ps-lite\camke\ProtoBuf.cmake in windows now?(check the option"USE_DIST_KVSTORE")
