### ISSUE TITLE
support variable length instances in a mini-batch 

### ISSUE THREAD

**Issue by formath** [dmlc/mxnet#4399]
1. In rnn and other sparse input examples, each instance in a mini-batch must have the same length. I saw this is because of embedding layer just support this manner of mini-batch input. The solution in rnn example is to split data into buckets where each bucket has a unique instance length. However, if the data num in a bucket is less than batch_size, all data in this bucket will been discarded. 
2. I don't find solution that can read libsvm data directly. The solution I found is to transform the original data into dense data firstly. But it is absolutely not right when feature num is very very large. I think this restriction is also related to current implementation of embedding layer.
So, is there any solutions to resolve those problems like embedding_lookup_sparse in tensorflow? Thanks.
@piiswrong

**Comment by piiswrong** [comment]
@pluskid

**Comment by pluskid** [comment]
@formath For the case of RNN with variable sequence length, the support is via masking or indicating the sequence length. For example, the loss layer support `ignore_label`, which you can use to ignore parts of the tails in each sequence in your mini batch. Other RNN operators also takes something like `seq_len` to indicate the exact sequence length of each sample.

It is true that you need to pad all sequence to be the same (maximum) length in a minibatch, and the tails will be discarded. This is why we need bucketing to avoid too huge wasting when some sequences might be very long.

**Comment by formath** [comment]
@pluskid thanks. About the second problem, namely directly reading libsvm data where each instance has hundreds sparse features but the whole feature num may be a hundred million, can you give some suggestions? Maybe bucketing is not appropriate there.

**Comment by pluskid** [comment]
No bucketing is not for this problem. I'm not sure what would be a better way to handle this (and I'm not even sure if deep networks will work better in this case than traditional methods). One way is always to convert that to dense vectors, and use smaller mini-batch. That is of course very wasteful. Maybe one can implement some custom layer like the `Embedding` layer, that could handle sparse vector with multiple non-zeros (instead of only one non-zero entry).
