### ISSUE TITLE
problem building mxnet

### ISSUE THREAD

**Issue by wangxianliang** [dmlc/mxnet#440]
1>..\mxnet\ps-lite\include\ps/kv_app.h(401): error C2061: syntax error: identifier 'SlicedKVs'
1>..\mxnet\ps-lite\include\ps/kv_app.h(453): error C2244: 'ps::KVWorker<Val>::DefaultSlicer': unable to match function definition to an existing declaration

visual studio 2015 x64, any idea?

**Comment by yajiedesign** [comment]
now,the windows building is use visual studio 2013,because CUDA not supported 2015.

**Comment by wangxianliang** [comment]
I built mxnet without CUDA support. If I remove ps-lite module, mxnet can be successfully built with visual studio 2015.

**Comment by tqchen** [comment]
@yajiedesign can you push a PR to disable the PS build in windows by default? Thanks

**Comment by yajiedesign** [comment]
@tqchen  ok  https://github.com/dmlc/mxnet/pull/442

**Comment by tqchen** [comment]
Thanks! I am going to close this as it is considered to be "fixed" by #442
