### ISSUE TITLE
infer_type error when using mx.sym.expand_dims on an internal variable

### ISSUE THREAD

**Issue by nicklhy** [dmlc/mxnet#4402]
The example code below is a simple network for linear regression. Weight and bias are defined as internal variables. The only difference between get_symbol1 and get_symbol2 is the shape of sym_w.

I am not sure if it is a bug or something. The symbol from get_symbol2 is not able to execute infer_type successfully. The error message is `mxnet.base.MXNetError: InferType Error in expand_dims0: [16:48:25] src/operator/operator_util.cc:402: At least one input type needs to be specified.`

Change mx.sym.expand_dims to mx.sym.Reshape doesn't work either.

```
import mxnet as mx
import numpy as np

def get_symbol1(M=1024):
    sym_x = mx.sym.Variable('data')
    sym_w = mx.sym.Variable('w_weight', shape=(M, 1))
    sym_b = mx.sym.Variable('b_bias', shape=(1, 1))
    sym_pred = mx.sym.broadcast_plus(mx.sym.dot(sym_x, sym_w), sym_b)
    loss = mx.sym.LinearRegressionOutput(data=sym_pred, label=mx.sym.Variable('label'), name='loss')
    return loss

def get_symbol2(M=1024):
    sym_x = mx.sym.Variable('data')
    sym_w = mx.sym.Variable('w_weight', shape=(M,))
    sym_b = mx.sym.Variable('b_bias', shape=(1, 1))
    sym_pred = mx.sym.broadcast_plus(mx.sym.dot(sym_x, mx.sym.expand_dims(data=sym_w, axis=1)), sym_b)
    loss = mx.sym.LinearRegressionOutput(data=sym_pred, label=mx.sym.Variable('label'), name='loss')
    return loss

sym1 = get_symbol1()
sym2 = get_symbol2()

print 'sym1 types:'
print sym1.infer_type(data=np.float32)

print 'sym2 types:'
print sym2.infer_type(data=np.float32)
```

**Comment by piiswrong** [comment]
This needs backward inference, which is available in nnvm branch

**Comment by nicklhy** [comment]
@piiswrong , The problem is sym_w and sym_b are not input data. Thus, the data_iter can not provide their shapes and types explicitly when creating the corresponding mx.sym.Module. It will cause an error if I execute module.fit afterwards.
For instance, the code is like
```
data_iter = xxx # provide_data=[('data', data_shape)], provide_label=[('label', label_shape)]
mod = mx.sym.Module(data_names=('data', ), label_names=('label',), context=mx.gpu())
mod.bind(data_shapes=data_iter.provide_data, label_shapes=data_iter.provide_label)
mod.init_params(xxx)
mod.init_optimizer(xxx)
mod.fit(xxx)
```

**Comment by piiswrong** [comment]
This should work with the nnvm branch

**Comment by nicklhy** [comment]
@piiswrong, OK, I will have a try.
By the way, are there any differences between nnvm and master for a up-level user? Will the nnvm branch become the master branch someday?

**Comment by tornadomeet** [comment]
@nicklhy  merged just now! for users,  there is almost no difference, but for develops, nnvm branch will be more convenience to write c++ code, such as operation.

**Comment by nicklhy** [comment]
Thanks. I have moved to nnvm branch and solved the infer_type problem. But another problem about using memonger to save GPU memory appears.

```
y = mx.sym.BatchNorm(data=mx.sym.Variable('data'), attr={'mirror_stage': 'True'}
\# "MXNetError: Cannot find argument 'mirror_stage', Possible Arguments: ..."
```

Replace BN with other operators would also produce this error.
