### ISSUE TITLE
How to get online GPU memory usage with python for linux?

### ISSUE THREAD

**Issue by Primus-zhao** [dmlc/mxnet#4412]
Hi guys, 

want to get gpu memory info to adjust batch size. Is there any python api to get gpu memory info for linux system(Ubuntu 14.04)?

**Comment by piiswrong** [comment]
use nvidia-smi

**Comment by jermainewang** [comment]
Nop, we don't expose cuda APIs in python side. You might need to write your own API or call nvidia-smi in python and parse the output as the above suggested.

**Comment by Primus-zhao** [comment]
@piiswrong @jermainewang 
Thanks. Have redirected nvidia-smi output stream to file to achieve this, but the solution seems ugly since i had to create one additional thread for tracking GPU mem info, maybe i should try to create one batch_end_callback instead.
