### ISSUE TITLE
How the weight is initialized when using Caffe plugin?

### ISSUE THREAD

**Issue by qingqing01** [dmlc/mxnet#4416]
The code in this line  https://github.com/dmlc/mxnet/blob/master/plugin/caffe/caffe_op-inl.h#L111  will reset Caffe's blob by mxnet's data structure in the first forward.  But, in the training phase and there is no initialized model,  whether this line will cover the weight initialization in Caffe's SetUp function?

**Comment by piiswrong** [comment]
It's initialized the same way mxnet ops weights are initalized, with initializers

**Comment by qingqing01** [comment]
For example, the inner_product_layer and batch_norm_layer have different initialization methods, how to ensure proper initialization by using mxnet's initializers?  I'm sorry that I'm not familiar with mxnet code.

**Comment by jermainewang** [comment]
@HrWangChengdu

**Comment by HrWangChengdu** [comment]
@qingqing01 Yes. It's initialized as how mxnet ops' weights are done. http://mxnet.io/api/python/model.html#initializer-api-reference explains the api for initializer.

**Comment by qingqing01** [comment]
Ok, that's to say, I should init the weights by myself rather than based on the settings in CaffeOp. Thanks!
