### ISSUE TITLE
Lots of API references missing from the docs site

### ISSUE THREAD

**Issue by back2yes** [dmlc/mxnet#4427]
What happened to the docs site http://mxnet.io/?
I could not find lots of API references such as `Deconvolution` or `FullyConnected` there, as they used to be. Are they missing or moved to somewhere else?

**Comment by kevinthesun** [comment]
@piiswrong Is this intentional? My local branch still shows all the APIs. Maybe some changes in symbol.py results in the missing?

**Comment by andremoeller** [comment]
Seems the R reference manual also got truncated in 0.9.1

http://mxnet.io/api/r/mxnet-r-reference-manual.pdf

**Comment by piiswrong** [comment]
@mli @tqchen Any ideas? It doesn't seem to be building properly

**Comment by mli** [comment]
build log is here: http://mxnet.io:8080/job/mxnet/312/console

btw, we should also host document for previous releases.

**Comment by piiswrong** [comment]
will be fixed after https://github.com/dmlc/mxnet/pull/4429/files is merged

**Comment by back2yes** [comment]
It's good to see that the references back! And admirable that you are working so hard in holidays!
There is still a minor problem on the website now. The 'API' link on the top navigation bar shows no response to clicking. The address to API references has to be typed by hand..
