### ISSUE TITLE
Error Message: GPU is not enabled

### ISSUE THREAD

**Issue by Walid-Ahmed** [dmlc/mxnet#4431]
Hi,
I am trying to execute the foloowing statment "$ python demo.py --prefix final --epoch 0 --image myimage.jpg --gpu 0" 

The demo.py file is at example/rcnn

## Error Message:
mxnet.base.MXNetError: [16:33:57] src/ndarray/ndarray.cc:296: GPU is not enabled

I want to to execute on a CPU as I am not sure My graphics card supports Cuda or not

## Environment info
Operating System:
Mac OS sierra 10.12.1
my graphics card is Intel Iris Pro 1536 MB

Package used (Python):

MXNet version:
0.9

Python version and distribution:
2.7

Thanks

**Comment by piiswrong** [comment]
drop the --gpu 0 part

**Comment by piiswrong** [comment]
if __name__ == '__main__':
    args = parse_args()
    ctx = mx.gpu(args.gpu_id)

in demo.py replace  mx.gpu(args.gpu_id) with mx.cpu(0)

**Comment by Walid-Ahmed** [comment]
@piiswrong 
It is still not working.
I got the following message
"
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.



Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x000000010a2242d8 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010a7e1783 _ZN5mxnet6engine14ThreadedEngine15ExecuteOprBlockENS_10RunContextEPNS0_8OprBlockE + 1059
[bt] (2) 2   libmxnet.so                         0x000000010a7e33be _ZNSt3__110__function6__funcIZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS3_8OprBlockEbENKUlvE_clEvEUlvE_NS_9allocatorIS8_EEFvvEEclEv + 62
[bt] (3) 3   libmxnet.so                         0x000000010a7e1af8 _ZNSt3__114__thread_proxyINS_5tupleIJNS_8functionIFvvEEEEEEEEPvS6_ + 104
[bt] (4) 4   libsystem_pthread.dylib             0x00007fff9184eaab _pthread_body + 180
[bt] (5) 5   libsystem_pthread.dylib             0x00007fff9184e9f7 _pthread_body + 0
[bt] (6) 6   libsystem_pthread.dylib             0x00007fff9184e221 thread_start + 13

libc++abi.dylib: terminating with uncaught exception of type dmlc::Error: [09:44:25] src/engine/./threaded_engine.h:334: [09:44:25] src/operator/./convolution-inl.h:317: Check failed: param_.workspace >= required_size (268435456 vs. 317568000) 
Minimum workspace size: 1270272000 Bytes
Given: 1073741824 Bytes

"

**Comment by yasenvlsim** [comment]
Hi, 
did you managed to fix your problem? I'm having the same issue

**Comment by Olivia-fsm** [comment]
> Hi,
> did you managed to fix your problem? I'm having the same issue

Hi, have you solve this issue? I have the same problem...

**Comment by R2D2oid** [comment]
I have a similar issue where mxnet is unable to use GPU. (note: I was able to successfully switch to CPU by simply setting `context = mexnet.cpu()` and run things without any issues!) 

As for the GPU issue, in my case I have cuda installed and I'm able to successfully use it with torch **outside of the virtualenv that I have setup for mxnet**. 

Outside of my virtualenv, `torch.cuda.is_available()` returns `True` while it returns `False` within my mxnet virtualenv.
If you are also using virtualenv, this may be caused by inability of virtualenv in using cuda rather than an issue mxnet.
