### ISSUE TITLE
Amalgamation for Android broken in v0.9.1pre

### ISSUE THREAD

**Issue by d4wud** [dmlc/mxnet#4436]
I tested out amalgamation on v0.9.1pre and couldn't get it to work.  My environment amalgamates perfectly in v0.8.0.

The initial error I get is 
`[...]/mxnet/amalgamation/../dmlc-core/include/dmlc/logging.h:18:22: fatal error: execinfo.h: No such file or directory`

After commenting that out, I tried to manually change paths and comment out headers not located in the source.  One issue I had is that `nnvm` files are linked incorrectly, e.g. 
`#include <nnvm/op.h>` -> `#include <nnvm/include/nnvm/op.h>`
And several elementwise operators were missing from `mxnet_predict0.cc`:
```
#include "src/operator/elementwise_unary_op.cc"
#include "src/operator/elementwise_binary_op.cc"
#include "src/operator/elementwise_sum.cc"
#include "src/operator/elementwise_binary_scalar_op.cc"
#include "src/operator/elementwise_unary_op.cc"
#include "src/operator/embedding.cc"
#include "src/operator/reshape.cc"
```

Eventually amalgamation simply fails without explanation:
`make: *** [mxnet_predict0.d] Error 1`

Has something significant change in the requirements for amalgamation?

## Environment info
Operating System:
Android (amalgamation)

MXNet commit hash (`git rev-parse HEAD`):
84e5155fc26563ef8bebc08f201e8a88d4c3845e

**Comment by piiswrong** [comment]
@antinucleon

**Comment by d4wud** [comment]
Still a problem as of today: d4af261c485e418090d3d864b8ec7eafb417c89c

**Comment by xu6148152** [comment]
I built mxnet with v0.8.0 also met this problem

**Comment by piiswrong** [comment]
This should be fixed for v0.9.3 and later

**Comment by d4wud** [comment]
This is not fixed in v0.9.3.  Amalgamation still breaking:

```
from mxnet_predict0.cc:3:
[...]/mxnet/mxnet/amalgamation/../dmlc-core/include/dmlc/logging.h:18:22: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h>
                      ^
compilation terminated.
make: *** [mxnet_predict0.d] Error 1
```

**Comment by d4wud** [comment]
Commenting out that `#include <execinfo.h>` creates the further error:

```
In file included from mxnet_predict0.cc:4:0:
[...]/mxnet/amalgamation/../src/ndarray/ndarray.cc:16:30: fatal error: opencv2/opencv.hpp: No such file or directory
 #include <opencv2/opencv.hpp>
                              ^
compilation terminated.
make: *** [mxnet_predict0.d] Error 1
```

It looks like the `USE_OPENCV = 0` is being ignored?

**Comment by d4wud** [comment]
Ive opened a new issue:

https://github.com/dmlc/mxnet/issues/4783

**Comment by piiswrong** [comment]
git submodule update && make clean

Dawud Gordon <notifications@github.com>于2017年1月23日 周一下午5:37写道：
