### ISSUE TITLE
symbol set attribute error

### ISSUE THREAD

**Issue by nicklhy** [dmlc/mxnet#4437]
I just updated the code to the latest version and changed it to the nnvm branch.  Since my model is a large network, I need to set some attributes and use memonger to save GPU memory cost.

If I set the attribute when creating a symbol:
`y = mx.sym.BatchNorm(data=mx.sym.Variable('data'), attr={'mirror_stage': 'True'})`
it will incur an error like
```
MXNetError: Cannot find argument 'mirror_stage', Possible Arguments:
----------------
eps : float, optional, default=0.001
...
```
However, if I set the attribute after creating that symbol,
```
y = mx.sym.BatchNorm(data=mx.sym.Variable('data'))
y._set_attr(mirror_stage='True')
```
everything works fine.

(Since mx.sym.load uses the first method to set attributes, it's not possible to load a json file with 'mirror_stage' attributes now.)

**Comment by piiswrong** [comment]
fixed by https://github.com/dmlc/mxnet/pull/4441
