### ISSUE TITLE
compile error of new nnvm version

### ISSUE THREAD

**Issue by achao2013** [dmlc/mxnet#4438]
i compile the new version updated this morning, it appears some cudnn errors,as follows:
![image](https://cloud.githubusercontent.com/assets/5026576/21559224/3f4ca15c-ce83-11e6-86e7-887e654da0f0.png)
i always use cuda7.5 and cudnn7.5-v5.0, i don't know if new version of mxnet don't support it again?

**Comment by piiswrong** [comment]
it's working for me. Try 5.1?

**Comment by achao2013** [comment]
that's ok, thank you. but the compile time is too long. @piiswrong
