### ISSUE TITLE
Is Symbol.grad implemented?

### ISSUE THREAD

**Issue by back2yes** [dmlc/mxnet#4453]
Hello, I was trying to compute some gradients in the model. In the reference manual I found a function called `mxnet.symbol.Symbol.grad(wrt)`. It seemed to be pretty like the auto differentiation function in THEANO. However, when I tried it a `not implemented` error was raised. By tracing the codes, I found the following codes in `src/c_api/c_api_symbolic.cc`:
``` c++
int MXSymbolGrad(SymbolHandle sym, mx_uint num_wrt, const char** wrt, SymbolHandle* out) {
  API_BEGIN();
  LOG(FATAL) << "not implemented";
  API_END();
}
```
However, I still believe the symbolic auto differentiation must have been implemented in MXNet.
Could someone help me with this? THX in advance.

**Comment by shivarajugowda** [comment]
@back2yes I see this function being implemented in the master but not in the NNVM branch. Not sure if there are any limitations to enable it in NNVM branch.

**Comment by back2yes** [comment]
@shivarajugowda 
Thanks for your information.

**Comment by GaiYu0** [comment]
I do not think Symbol.grad is implemented currently.
![image](https://cloud.githubusercontent.com/assets/17979843/23823450/f2d2f710-069d-11e7-8c3c-dfbee5c5e2fe.png)
