### ISSUE TITLE
the big code expansion after 0.9.1

### ISSUE THREAD

**Issue by yajiedesign** [dmlc/mxnet#4455]
after 0.9.1.the full gpu complie(cuda arch is all) dll size more than 300mb, compression also more 100mb with vs2013 and vs2015. befor 0.9.1,it only 100mb and after compression 8mb.Is there a problem?

**Comment by howard0su** [comment]
before 0.9.1, cuda arch is not used. so it is empty. can u try to set cuda arch to empty and compare size again?

**Comment by howard0su** [comment]
I noticed that if your final binary contains symbols when you enabled DEV=1. Try run strip libmxnet.so to see if it goes back to original size as your baseline.

**Comment by yajiedesign** [comment]
I seem to have found the problem.seems it to be my own pot.
