### ISSUE TITLE
[docs] R-packages/man not generated

### ISSUE THREAD

**Issue by andremoeller** [dmlc/mxnet#4456]
The R reference manual is missing most of its content: http://mxnet.io/api/r/mxnet-r-reference-manual.pdf

This is where the R docs are generated: https://github.com/dmlc/mxnet/blob/master/docs/sphinx_util.py#L19

The files in R-packages/man are generated using roxygen2::roxygenize(), which are then used to make the reference manual. You may need to install the packages "roxygen2" on the docs build host, but without access to the host or logs I'm not sure.

**Comment by piiswrong** [comment]
the man files are generated by make in the root folder I think

**Comment by andremoeller** [comment]
I think the man files in the root folder you're referring to are unrelated (that is, not these .Rd files). Building the docs locally by running build-preview.sh shows R-package/man full of .Rd files after running R -e "roxygen2::roxygenize()" as part of the sphinx_util script and a full PDF after Rd2PDF, as expected.

Besides running install.packages("roxygen2"), I'm not sure how else to troubleshoot the docs build without access to the host or logs -- @kevinthesun has some experience building the R docs, and I think only @mli has access to the host.

Previously, the R-package/man files were just committed in the repo -- as a stopgap, I could check in the .Rd files, but the right way would be to generate these.

**Comment by piiswrong** [comment]
@andremoeller I just did 
sudo R
> install.packages("roxygen2")
and exit.
Is it enough to fix this?

**Comment by andremoeller** [comment]
Unless the build hasn't run yet (I think it's hourly?), then it didn't seem to fix it -- there should be tons of .Rd files in R-packages/man after sphinx_util.py runs, and a PDF with 43 pages in docs_/build/api/r/.

As a stopgap I'll send a PR that commits the .Rd files, though they should be generated or R doc changes won't get picked up automatically

**Comment by andremoeller** [comment]
All good now: http://mxnet.io/api/r/mxnet-r-reference-manual.pdf
