### ISSUE TITLE
Lack of control flow operators: functionally inferior to Tensorflow and Theano

### ISSUE THREAD

**Issue by xuancong84** [dmlc/mxnet#4471]
After going through so much inconveniences in Tensorflow and Theano, now I am trying MXNET.
I have read through the MXNET API, there is no control flow operation, i.e., functionally equivalent to tf.select/tf.cond or theano.switch/theano.ifelse . This missing functionality will limit the toolkit's capability in handling variable-length sequences.

Take note that without control flow operators, you can still perform LSTM-based variable-sequence-length prediction using masking. However, there is still something that you cannot do. For example, in training a RNN language model, I would like to reset the state vector to some specific trainable parameter whenever I encounter a sentence begin, i.e., `<s>`.

So I hereby hope the developer can implement this important function. Thanks!

**Comment by shivarajugowda** [comment]
@xuancong84 I have also felt a need for tf.select()/tf.switch kind of operation. I will probably implement it if no one else picks it up in the next few days.

**Comment by piiswrong** [comment]
select is easy to add, it's just a tenary operator.
cond is better done imperatively by combining Modules

**Comment by piiswrong** [comment]
It should be pretty easy to do cond with custom operators

**Comment by xuancong84** [comment]
Glad to hear that you are going to add in for that!
However, do not think it is easy to implement especially during the back-propagation or weight update, where you don't want to propagate the error along all paths from the conditional junction.

In addition, there is an advanced issue which I am not sure whether Theano and Tensorflow has implemented or not. It is the derivative w.r.t the conditional statement. For simple cases like whether the time index has exceeded the sequence length (for variable-length sequence input), there is no problem. However, if the conditional statement is a function of the input, say f(input)>0, it might be better to collect some statistics to decide which output choice is preferred, so that the conditional statement part of the network, f(), can be trained and updated as well. Sometimes, it might also be possible to update both paths according to their posterior likelihood, say 70% vs 30% respectively, instead of a boolean junction update where the winning branch takes all.

Bear in mind, things can go really tricky at the conditional branch.

**Comment by xuancong84** [comment]
Just curious, so has this feature been implemented? Thanks!

**Comment by zheng-da** [comment]
We are trying to add control flow operators.
https://cwiki.apache.org/confluence/display/MXNET/Add+flow+control+operators+in+MXNet
