### ISSUE TITLE
Makefile:259: recipe for target 'bin/im2rec' failed

### ISSUE THREAD

**Issue by skywalkerytx** [dmlc/mxnet#4480]
Config.mk attached( renamed to config.mk.txt to upload)
[config.mk.txt](https://github.com/dmlc/mxnet/files/679927/config.mk.txt)

## Environment info
Operating System:

Kubuntu16.04LTS

Compiler:

export CC = gcc-5/4.9

export CXX = g++-5/4.9

export NVCC = nvcc

Package used (Python/R/Scala/Julia):
shared Library

MXNet commit hash (`git rev-parse HEAD`):
c3c21715bb1f603865608dd903d60a0ee0be3610

## Error Message:

###For export CC = gcc-4.9:

> im2rec.cc:(.text.startup+0x1ac5): undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
Makefile:259: recipe for target 'bin/im2rec' failed

seems gcc-4.9 can't find `libopencv-dev` which is installed through apt, where

`pkg-config --cflags opencv`

> -I/usr/include/opencv

###For export CC = gcc-5:
>build/src/operator/tensor/indexing_op_gpu.o: In function `nnvm::Op& nnvm::Op::set_attr<std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)> >(std::string const&, std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)> const&, int)':
/home/nova/mxnet/nnvm/include/nnvm/./op.h:426: undefined reference to `nnvm::Op::UpdateAttrMap(std::string const&, std::function<void (dmlc::any*)>)'
collect2: error: ld returned 1 exit status
Makefile:259: recipe for target 'bin/im2rec' failed

this time the `nnvm` became the problem

## Steps to reproduce

make -B -j8

## What have you tried to solve it?

change gcc-5 to gcc-4.9, failed for some other errors

**Comment by skywalkerytx** [comment]
after such command a new error rised

>error: identifier "__builtin_ia32_monitorx" is undefined

solved with `-D_MWAITXINTRIN_H_INCLUDED`. then compiler says

`std::__iterator_traits<_Iterator, void> [with _Iterator=int]` is not part of `std::`

error message:

>/usr/include/c++/5/bits/stl_iterator_base_types.h(154): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" 
(163): here
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" 
src/operator/./sequence_reverse-inl.h(91): here
            implicit generation of "mxnet::op::SequenceReverseOp<xpu, DType>::~SequenceReverseOp() [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of class "mxnet::op::SequenceReverseOp<xpu, DType> [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of "mxnet::op::SequenceReverseOp<xpu, DType>::SequenceReverseOp(mxnet::op::SequenceReverseParam) [with xpu=mxnet::gpu, DType=float]" 
src/operator/sequence_reverse.cu(14): here

> /usr/include/c++/5/bits/stl_iterator_base_types.h(155): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" 
(163): here
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" 
src/operator/./sequence_reverse-inl.h(91): here
            implicit generation of "mxnet::op::SequenceReverseOp<xpu, DType>::~SequenceReverseOp() [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of class "mxnet::op::SequenceReverseOp<xpu, DType> [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of "mxnet::op::SequenceReverseOp<xpu, DType>::SequenceReverseOp(mxnet::op::SequenceReverseParam) [with xpu=mxnet::gpu, DType=float]" 
src/operator/sequence_reverse.cu(14): here

>/usr/include/c++/5/bits/stl_iterator_base_types.h(156): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" 
(163): here
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" 
src/operator/./sequence_reverse-inl.h(91): here
            implicit generation of "mxnet::op::SequenceReverseOp<xpu, DType>::~SequenceReverseOp() [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of class "mxnet::op::SequenceReverseOp<xpu, DType> [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of "mxnet::op::SequenceReverseOp<xpu, DType>::SequenceReverseOp(mxnet::op::SequenceReverseParam) [with xpu=mxnet::gpu, DType=float]" 
src/operator/sequence_reverse.cu(14): here

> /usr/include/c++/5/bits/stl_iterator_base_types.h(157): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" 
(163): here
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" 
src/operator/./sequence_reverse-inl.h(91): here
            implicit generation of "mxnet::op::SequenceReverseOp<xpu, DType>::~SequenceReverseOp() [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of class "mxnet::op::SequenceReverseOp<xpu, DType> [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of "mxnet::op::SequenceReverseOp<xpu, DType>::SequenceReverseOp(mxnet::op::SequenceReverseParam) [with xpu=mxnet::gpu, DType=float]" 
src/operator/sequence_reverse.cu(14): here

> /usr/include/c++/5/bits/stl_iterator_base_types.h(158): error: name followed by "::" must be a class or namespace name
          detected during:
            instantiation of class "std::__iterator_traits<_Iterator, void> [with _Iterator=int]" 
(163): here
            instantiation of class "std::iterator_traits<_Iterator> [with _Iterator=int]" 
src/operator/./sequence_reverse-inl.h(91): here
            implicit generation of "mxnet::op::SequenceReverseOp<xpu, DType>::~SequenceReverseOp() [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of class "mxnet::op::SequenceReverseOp<xpu, DType> [with xpu=mxnet::gpu, DType=float]" 
src/operator/./sequence_reverse-inl.h(45): here
            instantiation of "mxnet::op::SequenceReverseOp<xpu, DType>::SequenceReverseOp(mxnet::op::SequenceReverseParam) [with xpu=mxnet::gpu, DType=float]" 
src/operator/sequence_reverse.cu(14): here

>5 errors detected in the compilation of "/tmp/tmpxft_00006c75_00000000-13_sequence_reverse.compute_50.cpp1.ii".
Makefile:206: recipe for target 'build/src/operator/sequence_reverse_gpu.o' failed
make: *** [build/src/operator/sequence_reverse_gpu.o] Error 2

relevant command:

`/usr/local/cuda/bin/nvcc -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_50,code=compute_50 -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/nova/mxnet/mshadow/ -I/home/nova/mxnet/dmlc-core/include -fPIC -I/home/nova/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMSHADOW_USE_CUDNN=1 -D_MWAITXINTRIN_H_INCLUDED -DMXNET_USE_NVRTC=1" -M -MT build/src/operator/sequence_reverse_gpu.o src/operator/sequence_reverse.cu >build/src/operator/sequence_reverse_gpu.d
/usr/local/cuda/bin/nvcc -c -o build/src/operator/sequence_reverse_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_50,code=compute_50 -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/nova/mxnet/mshadow/ -I/home/nova/mxnet/dmlc-core/include -fPIC -I/home/nova/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/include/opencv -fopenmp -DMSHADOW_USE_CUDNN=1 -D_MWAITXINTRIN_H_INCLUDED -DMXNET_USE_NVRTC=1" src/operator/sequence_reverse.cu`

**Comment by thirdwing** [comment]
@skywalkerytx I met similar errors in the summer. My suggestion is to compile opencv using GCC4.9 from source.

**Comment by skywalkerytx** [comment]
@thirdwing then also use 4.9 as cc for mxnet?

**Comment by skywalkerytx** [comment]
Cause and final solution to this problem:

16.04LTS moved a LOT of libraries to different places and some libraries from apt source is somewhat strange.

so the final solution to this problem:

1. back up your code

2. reinstall 14.04 LTS

3. everything works fine.
