### ISSUE TITLE
多机器分布式部署

### ISSUE THREAD

**Issue by yanshengli** [dmlc/mxnet#4488]
请问下，有没有比较详细的帮助手册，关于mxnet在多机器的部署介绍。

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/tree/master/example/image-classification

**Comment by zxfzqf** [comment]
According to the tutorial of official website , can be configured successfully,  tutorial :http://mxnet.io/how_to/multi_devices.html, 
Of course，piiswrong mean  was right so. This is very simple，maybe  will be some problems of ssh，If you are not familiar with SSH。
