### ISSUE TITLE
Can mxnet add np.argsort operation?

### ISSUE THREAD

**Issue by chenboheng** [dmlc/mxnet#4489]
I want to sort the elements of the matrix.
However, I haven't found the sort operation in mx.symbol. Can mxnet add the np.argsort operation or how can I easily implement the sort operation by python interface (directly use the np.argsort maybe too slow)

**Comment by sxjscience** [comment]
@chenboheng Stay tuned after I fix https://github.com/dmlc/mxnet/pull/4403

**Comment by sxjscience** [comment]
argsort, sort, topk are supported now. https://github.com/dmlc/mxnet/blob/master/src/operator/tensor/ordering_op.cc
