### ISSUE TITLE
API menu item does not work in mxnet.io

### ISSUE THREAD

**Issue by mcxkarakoc** [dmlc/mxnet#4490]
It cannot be opened. It was working two days ago.

**Comment by piiswrong** [comment]
@kevinthesun 
Its working for me. Probably browser version issue?

**Comment by mcxkarakoc** [comment]
Maybe but I've tried it at both home and work by using Chrome and Firefox.

**Comment by kevinthesun** [comment]
It's working for me on chrome but not safari or firefox.

**Comment by kevinthesun** [comment]
Also when I build it locally, it works fine for chrome, safari and firefox.

**Comment by piiswrong** [comment]
probably due to sphinx upgrade on the build server
@yao could you update your local sphinx to 1.5.1 and try again

**Comment by kevinthesun** [comment]
Sphinx 1.5.1 will update JQuery to 3.1.0, while Bootstrap requires JQuery 1.9.1 to 3.0.0. 
I fixed this issue by using JQuery version 1.11.1, which is the version for current website.
Fixed in PR https://github.com/dmlc/mxnet/pull/4501

**Comment by kevinthesun** [comment]
Still issue there. JQuery 1.11.1 is not generated by sphinx 1.5.1

**Comment by kevinthesun** [comment]
Fixed in https://github.com/dmlc/mxnet/pull/4503
