### ISSUE TITLE
[Cython compilation] Cannot declare pointer to ‘void*&’

### ISSUE THREAD

**Issue by AdrienMorvan** [dmlc/mxnet#4491]
Hello,

I tried to install MXnet on an amazon ubuntu
The installation fails on 
sudo python setup.py install with  

> Cannot declare pointer to ‘void*&

I followed the script install-mxnet-ubuntu-python.sh
Can someone guide me on the instructions to follow to fix this ?
Thanks in advance

## Environment info
Operating System:

ubuntu 14.04.3

Compiler:

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)

Package used : Python 2.7.6 from system

Cython version : 0.22.1

MXNet version: master b5988bdb45d2bbcd19ef5bdb11e7c6a0dc6d5f45 (latest)

## Error Message:

Compiling mxnet/cython/ndarray.pyx because it changed.
Compiling mxnet/cython/symbol.pyx because it changed.
Cythonizing mxnet/cython/ndarray.pyx
Cythonizing mxnet/cython/symbol.pyx
running install
running bdist_egg
running egg_info
writing requirements to mxnet.egg-info/requires.txt
writing mxnet.egg-info/PKG-INFO
writing top-level names to mxnet.egg-info/top_level.txt
writing dependency_links to mxnet.egg-info/dependency_links.txt
reading manifest file 'mxnet.egg-info/SOURCES.txt'
writing manifest file 'mxnet.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'mxnet/_cy2/.ndarray' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I../include/ -I../nnvm/include -I/usr/include/python2.7 -c mxnet/cython/ndarray.cpp -o build/temp.linux-x86_64-2.7/mxnet/cython/ndarray.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
mxnet/cython/ndarray.cpp: In function ‘PyObject* __pyx_pf_7ndarray_22_make_ndarray_function_generic_ndarray_function(PyObject*, PyObject*, PyObject*)’:
mxnet/cython/ndarray.cpp:2512:36: error: cannot declare pointer to ‘void*&’
   __pyx_t_7ndarray_NDArrayHandle &*__pyx_t_15;

## GCC config : 
COLLECT_GCC=x86_64-linux-gnu-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix

**Comment by Iflier** [comment]
I also meet some errors:
Cython.Compiler.Errors.CompileError: mxnet/cython/ndarray.pyx
Now, I try to uninstall cython, and  then try to install again. I hope everything goes well.

**Comment by Iflier** [comment]
OK, i am so happy! I successed install mxnet after upgrade cython (in python2.x).

**Comment by AdrienMorvan** [comment]
Thanks for the pointer.
Of course it was super obvious, the system was using the apt python package and not the pip one.
Now it works fine for me !
