### ISSUE TITLE
A problem of RMSProp

### ISSUE THREAD

**Issue by sunke123** [dmlc/mxnet#4493]
Hi contributors,
I used mxnet recently. It's very cool.
There is a problem of RMSProp. Maybe you can take into consideration.
In mxnet, torch and caffe, all have a parameter epsilon to avoid division by zero.
But there is a difference.

In torch and caffe, the formula like this:
w is weight.
dfdx is gradient.
decay is the param of RMSProp.
default of eps is 1e-8.
delta = (1-decay) * dfdx**2 + decay*delta
w += -lr * dfdx / (    sqrt(delta)+eps     )

In mxnet, eps is equal to 1e-4.
w += -lr * dfdx / (    sqrt(delta+eps)     )

At the beginning of training, delta is initialized as zero.
It's possible that dfdx**2  << eps, which leads to that the denominator depends on eps.

Maybe, you can set a new parameter for eps or replace sqrt(delta + eps) with sqrt(delta) + eps.

In my case, the input is 0~1, the label is 0~1 and loss is L2_Norm.
There is a big gap between them.

**Comment by piiswrong** [comment]
It should be changed to w += -lr * dfdx / ( sqrt(delta)+eps ). No need for a new parameter.
Would you like to propose a fix?

**Comment by sunke123** [comment]
@piiswrong ,Sure. Thanks for your quick response.
