### ISSUE TITLE
Need Advice: Bernoulli Sampling operator for RBM

### ISSUE THREAD

**Issue by metrofun** [dmlc/mxnet#4500]
Hi, I am trying to dive into mxnet and was thinking about contributing an RBM example. 
As a result, I am thinking of adding a Bernoulli operator to sample visible/hidden layers.

So I am seeking your advice on the design part. Should I just add "Bernoulli" operator or more generic "Sample" operator or maybe extend operator/tensor/sample_op.

**Comment by piiswrong** [comment]
how about mx.random.uniform(0, 1) > 0.5

**Comment by metrofun** [comment]
Can be done. Also my initial approach was try to do it declaratively with symbols. Maybe as for now I will try and play with Custom Operators in Python using your approach. Thanks
