### ISSUE TITLE
shape_[0] > idx (1 vs. 1) index out of range error when passing group symbol output.

### ISSUE THREAD

**Issue by HBkunn** [dmlc/mxnet#4504]
I've been trying DCGAN sample in the example.
I used Group symbol to group two symbols together, then return it.
Then I use this group symbol to create a module.
In each iteration I called one of them as output ndarray to pass through a discriminator.

If I returned only the called symbol in my function, it worked just fine.

by this
```
outG = modG.get_outputs()
modD.forward(mx.io.DataBatch(outG, [label]), is_train=True)
```

If I return a two-symbol group symbol in my network definition function, and then called it like this, the error occurred.

```
outG = modG.get_outputs()[0]
modD.forward(mx.io.DataBatch(outG, [label]), is_train=True)
```

Traceback (most recent call last):
  File "d:\newwork\workspace\gan\test_with_mnist.py", line 284, in <module>
    modD.forward(mx.io.DataBatch(outG, [label]), is_train=True)
  File "D:\Anaconda\lib\site-packages\mxnet\module\module.py", line 448, in forward
    self._exec_group.forward(data_batch, is_train)
  File "D:\Anaconda\lib\site-packages\mxnet\module\executor_group.py", line 313, in forward
    _load_data(data_batch, self.data_arrays, self.data_layouts)
  File "D:\Anaconda\lib\site-packages\mxnet\module\executor_group.py", line 43, in _load_data
    _load_general(batch.data, targets, major_axis)
  File "D:\Anaconda\lib\site-packages\mxnet\module\executor_group.py", line 17, in _load_general
    for d_src, d_targets, axis in zip(data, targets, major_axis):
  File "D:\Anaconda\lib\site-packages\mxnet\ndarray.py", line 315, in __getitem__
    return self._at(in_slice)
 File "D:\Anaconda\lib\site-packages\mxnet\ndarray.py", line 374, in _at
    self.handle, idx, ctypes.byref(handle)))
  File "D:\Anaconda\lib\site-packages\mxnet\base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
MXNetError: [13:23:09] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\include\mxnet/ndarray.h:276: Check failed: shape_[0] > idx (1 vs. 1) index out of range

the latest version called different error from the previous ones.
the previous versions said dshape mismatch.

And is there any good way to print out one of the internal symbol value in an iteration instead of defining a Group symbol in the function??? I've been searching of documents of module API, Is there any good way to get internal ndarray value after each forward/backward procedure?

**Comment by piiswrong** [comment]
data needs to be a list of ndarrays. You should use [outG]

**Comment by HBkunn** [comment]
thank you it works just fine!
but still another question. If I called for backward function like this.

```
diffD = modD.get_input_grads()
modG.backward(diffD)
```

diffD is the diff passing through from Discriminator, the error occurred like this.

MXNetError: [14:15:45] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\src\executor\graph_executor.cc:44: Check failed: i < head_grads.size() && !head_grads[i].is_none() Because the last operator is not Loss function, head_gradient is required in calling backward.

Is it due to that the group symbol is my last operator?
How can I make it work? I want the diff pass through the last tanh activative function of generator, and only to record the changing of encoder sequence output.

**Comment by piiswrong** [comment]
I think it's the same problem. Make sure diffD matches modG's output

**Comment by HBkunn** [comment]
Yes, things like this can do.
```
diff_null = mx.nd.zeros((1,512,1,1), ctx=ctx)
modG.backward([diffD[0],diff_null])
```

But still both the grouped symbols should have a head_gradients. I cannot find some way to blind one of them to prevent extra computation. And still I think Group symbol can be misleading somehow...

Thanks for helping! You're so kind and helpful. MXnet is still my favorite!
