### ISSUE TITLE
MXNet doc website search function issue

### ISSUE THREAD

**Issue by kevinthesun** [dmlc/mxnet#4511]
#After updating sphinx to version 1.5.1, some errors will happen when using search function. 
Open the web console it shows the following information:

Uncaught TypeError: Cannot read property 'length' of undefined
    at displayNextItem (searchtools.js:543)
    at Object.query (searchtools.js:574)
    at Object.setIndex (searchtools.js:362)
    at /Users/wayao/Documents/MXNetDoc/mxnet/docs/_build/html/searchindex.js:1

It seems that searchtools.js has been updated and there are errors in it.

@piiswrong @mli

**Comment by piiswrong** [comment]
you can try downgrading sphinx but then we need to fix the problem that docs for operators are not generated

**Comment by kevinthesun** [comment]
Maybe we can copy the elder version of searchtools.js and statically link to it.
