### ISSUE TITLE
mxnet support grained operation: matrix's math operation?

### ISSUE THREAD

**Issue by moveforever** [dmlc/mxnet#4514]
If factorization machine  and other network structure are united to train, it need matrix's operations , for example, pow.
So how to implement it?

Can you help me

**Comment by piiswrong** [comment]
x = mx.sym.Variable('a')
y = mx.sym.Variable('b')
x**y

**Comment by moveforever** [comment]
@piiswrong ,tks.
Matrix multiply is like this? 
x = mx.sym.Variable('a')
y = mx.sym.Variable('b')
x*y

**Comment by sxjscience** [comment]
@moveforever You can directly use +, -, *, / for the elementwise add/minus/... 
```python
x = mx.sym.Variable('a')
y = mx.sym.Variable('b')
z = x*y
```

**Comment by moveforever** [comment]
@sxjscience , tks.
not elementwise operation, but I mean matrix multiplication, for example, matrix A and matrix B, how to get result of A multiplied by B?  

Another question: matrix A, how to implement mx.sym.transpose(A) multiply by A?

**Comment by sxjscience** [comment]
@moveforever Use `mx.sym.dot`. Also, the symbol API is here http://mxnet.io/api/python/symbol.html#symbol-creation-api-reference

**Comment by moveforever** [comment]
@sxjscience  thank you very much.
