### ISSUE TITLE
Custom-Op Bug when using multiple custom-ops

### ISSUE THREAD

**Issue by lyttonhao** [dmlc/mxnet#4521]
I found that when using multiple output custom-ops, the program got stuck. It seems that the engine is suffering from the deadlock. This problem will occur when the custom-op contains the codes like `mx.nd.xx( xx ).asnumpy()'. This problem does not occur when using NaiveEngine.

I have written an example to reproduce this bug. You can put [this file](https://gist.github.com/lyttonhao/e4bb8f99029eed71fc39e6c275505ccb) on the path of 'exmple/numpy-ops' and then run it. If we add [line 15](https://gist.github.com/lyttonhao/e4bb8f99029eed71fc39e6c275505ccb#file-test_custom-py-L15), the program will get stuck. Otherwise it works fine. 

MXNet version: test two versions.
1. the newest master: ceb9f0187a31d528e5566f810d933cf4834d3282
2. an older master: 01cde15b5611d3add9a103abd7979c3272693625

**Comment by sxjscience** [comment]
I've tried and the script runs well. I'm using the latest dmlc/master. Also, I've compiled using the master version of nnvm + mshadow + dmlc-core

**Comment by piiswrong** [comment]
os.environ["MXNET_CPU_WORKER_NTHREADS"] = "4"
Add this to the beginning.

**Comment by lyttonhao** [comment]
It has been fixed by #4528
