### ISSUE TITLE
nnvm c++ predict example failed with msg check failed: op != nullptr 

### ISSUE THREAD

**Issue by feiyulv** [dmlc/mxnet#4522]
MXNet version:
0.9.1

MXNet commit hash (`git rev-parse HEAD`):
 ceb9f01

## Error Message:
`src/core/op.cc:55:  check failed: op != nullptr Operator Convolution is not registered`

## Minimum reproducible example
example/image-classification/predict-cpp

##  Phenomenon
1. The nnvm version c++ predict api failed when load json file
https://github.com/dmlc/mxnet/blob/master/src/c_api/c_predict_api.cc#L87
2.  The python api is ok when loading the last epoch model and json file to continue training, like
`python train_imagnet.py --load-epoch=1`
3. I add the following debug code in https://github.com/dmlc/nnvm/blob/master/src/core/op.cc#L55
```
const Op* Op::Get(const std::string& name) {
  auto names = dmlc::Registry<Op>::ListAllNames();
  for (auto str: names) LOG(INFO)<<str;
  const Op* op = dmlc::Registry<Op>::Find(name);
  CHECK(op != nullptr)
      << "Operator " << name << " is not registered";
  return op;
}
```
Using c++ predict api,  only operators refactoring to nnvm are in Registry. When using python api all operators can be printed

**Comment by howard0su** [comment]
Thank you for reporting. I will look at this.

**Comment by piiswrong** [comment]
We need to add this line to the beginning
 mxnet::op::RegisterLegacyOpProp();

**Comment by feiyulv** [comment]
@piiswrong where to add?

**Comment by feiyulv** [comment]
It seems this function should be called  first
```
/*!
 * \brief list all the available operator names, include entries.
 * \param out_size the size of returned array
 * \param out_array the output operator name array.
 * \return 0 when success, -1 when failure happens
 */
MXNET_DLL int MXListAllOpNames(mx_uint *out_size,
                               const char ***out_array);
```
I'm not very clear about how to use this api, will this be ok?
```
int size;
char *out;
MXListAllOpNames(&size, &out);
```

**Comment by feiyulv** [comment]
After fix this bug, the predict example still fails with msg
```
src/c_api/c_predict_api.cc:171: Check failed: infer_complete The shape information of is not enough to get the shapes
```

**Comment by feiyulv** [comment]
@howard0su It's ok now, thx

**Comment by anguoyang** [comment]
i have the same error in ssd/c++, could anyone tell me how to solve it? than you

**Comment by jmanela** [comment]
@anguoyang did you ever get this working?
