### ISSUE TITLE
install error on ubuntu 

### ISSUE THREAD

**Issue by Struggle-YD** [dmlc/mxnet#4532]
dear team:
  i want to know the install guide on your home page for mxnet-0.7.0 holds for mxnet-0.8.0?  when i download the mxnet on github, the file of mshadow is empty?
thank you very much!

best!

**Comment by luoyetx** [comment]
You can use `git submodule update --init` to download submodules.

**Comment by danimateos** [comment]
If I understand your problem correctly, you can also use the `--recursive` flag when you clone mxnet to download everything like so:

```bash
git clone --recursive git@github.com:dmlc/mxnet.git
```
