### ISSUE TITLE
Scala example on website doesn't compile

### ISSUE THREAD

**Issue by danimateos** [dmlc/mxnet#4539]
I don't know if this is the best place to communicate this, but I tried copy-pasting the only Scala [example](http://mxnet.io/tutorials/scala/mnist.html) in the website and it doesn't compile. 

I got it to compile by doing what's described below. I'm not sure whether that was the right fix (later I get a core dumped that I'll post in a separate issue). This is just a heads up for you guys to be aware of the problem with the website.

## Environment info
Operating System:
Ubuntu 16.10 amd64

Compiler:
sbt

Package used (Python/R/Scala/Julia):
Scala package
scalaVersion 2.11.8

MXNet version:
"ml.dmlc.mxnet" % "mxnet-full_2.10-linux-x86_64-gpu" % "0.1.1"

## Error Message:
```
sbt compile ~/repos/mxnet-playground 0 10:56:28
[info] Loading global plugins from /home/dani/myconfigs/.sbt/0.13/plugins
[info] Set current project to mxnet-playground (in build file:/home/dani/repos/mxnet-playground/)
[info] Compiling 1 Scala source to /home/dani/repos/mxnet-playground/target/scala-2.11/classes...
[error] /home/dani/repos/mxnet-playground/src/main/scala/playground/MRE.scala:7: not enough arguments for method apply: (v1: Map[String,Any])ml.dmlc.mxnet.Symbol in trait Function1.
[error] Unspecified value parameter v1.
[error]   val fc1 = Symbol.FullyConnected(name = "fc1")()(Map("data" -> data, "num_hidden" -> 128))
[error]                                                ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed Jan 5, 2017 10:56:43 AM
```
## Minimum reproducible example
```scala
import ml.dmlc.mxnet._

object MRE extends App {
  val data = Symbol.Variable("data")
  val fc1 = Symbol.FullyConnected(name = "fc1")()(Map("data" -> data, "num_hidden" -> 128))
}
```

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Clone https://github.com/danimateos/mxnet-playground/tree/broken
2. `sbt compile`

## What have you tried to solve it?

I removed the `()` in
```scala
  val fc1 = Symbol.FullyConnected(name = "fc1")()(Map("data" -> data, "num_hidden" -> 128))
  val act1 = Symbol.Activation(name = "relu1")()(Map("data" -> fc1, "act_type" -> "relu"))
  val fc2 = Symbol.FullyConnected(name = "fc2")()(Map("data" -> act1, "num_hidden" -> 64))
  val act2 = Symbol.Activation(name = "relu2")()(Map("data" -> fc2, "act_type" -> "relu"))
  val fc3 = Symbol.FullyConnected(name = "fc3")()(Map("data" -> act2, "num_hidden" -> 10))
  val mlp = Symbol.SoftmaxOutput(name = "sm")()(Map("data" -> fc3))
```
and got it to compile.

**Comment by Ldpe2G** [comment]
try to use the lastest mxnet version

**Comment by javelinjs** [comment]
The api has been updated.
I'll deploy the latest scala pkg to maven repository soon.

**Comment by javelinjs** [comment]
@danimateos This weekend or next week.
