### ISSUE TITLE
can't require(mxnet) --with CPU

### ISSUE THREAD

**Issue by amilyk** [dmlc/mxnet#4545]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:windows 10

Compiler:R studio  R version 3.3.1

Package used (Python/R/Scala/Julia):R

MXNet version:don't know.I just use the command in R studio.
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
载入需要的程辑包：mxnet
Error : 'namespace:DiagrammeR'没有出口‘combine_edges’这个对象

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
set up:
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")

require:
require(mxnet) or library(mxnet)

## What have you tried to solve it?

1.install.packages add a parameter,dependency = TRUE
2.search with google,can't find answer either.
3.I try to download the mxnet package,and install the local file.It doesn't work either

**Comment by thirdwing** [comment]
The same with https://github.com/dmlc/mxnet/issues/4574

**Comment by amilyk** [comment]
thanks so much ,when I use your advice in #4574. install DiagrammeR. It does work.!
>require(devtools)
install_version("DiagrammeR", version = "0.8.1", repos = "http://cran.us.r-project.org")

**Comment by thirdwing** [comment]
This has been fixed. Feel free to reopen if necessary.
