### ISSUE TITLE
CPP inference example is broken

### ISSUE THREAD

**Issue by indhub** [dmlc/mxnet#4553]
I tried to build and run https://github.com/dmlc/mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc and I get the following error:

pretrained_models/inception_bn/Inception-BN-symbol.json ... 116922 bytes
pretrained_models/inception_bn/Inception-BN-0126.params ... 45284780 bytes
[21:26:38] include/dmlc/./logging.h:300: [21:26:38] src/core/op.cc:55: Check failed: op != nullptr Operator Convolution is not registered

Stack trace returned 14 entries:
[bt] (0) /home/ubuntu/mxnet/lib/libmxnet.so(_ZN4nnvm2Op3GetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x38a) [0x7f83791543da]
[bt] (1) /home/ubuntu/mxnet/lib/libmxnet.so(+0x19d166c) [0x7f837912b66c]
[bt] (2) /home/ubuntu/mxnet/lib/libmxnet.so(+0x19d1b03) [0x7f837912bb03]
[bt] (3) /home/ubuntu/mxnet/lib/libmxnet.so(_ZN4dmlc20JSONObjectReadHelper13ReadAllFieldsEPNS_10JSONReaderE+0x12a) [0x7f8379133e3a]
[bt] (4) /home/ubuntu/mxnet/lib/libmxnet.so(+0x19cfeb4) [0x7f8379129eb4]
[bt] (5) /home/ubuntu/mxnet/lib/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataOS1_+0x111) [0x7f83784e0ca1]
[bt] (6) /home/ubuntu/mxnet/lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x342) [0x7f837913e932]
[bt] (7) /home/ubuntu/mxnet/lib/libmxnet.so(_ZN4nnvm4pass8LoadJSONERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x986) [0x7f83787f9bc6]
[bt] (8) /home/ubuntu/mxnet/lib/libmxnet.so(MXPredCreatePartialOut+0x118) [0x7f83787efce8]
[bt] (9) /home/ubuntu/mxnet/lib/libmxnet.so(MXPredCreate+0x1d) [0x7f83787f4e2d]
[bt] (10) src/Inference(_ZN14MXNetPredictor7predictERKN2cv3MatESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EERS4_IS4_IfSaIfEESaISE_EE+0x214) [0x40d26c]
[bt] (11) src/Inference(main+0x26d) [0x410707]
[bt] (12) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f837631b830]
[bt] (13) src/Inference(_start+0x29) [0x40cc99]

Segmentation fault (core dumped)

This used to work before the nnvm merge.

## Environment info
Operating System: Ubuntu

Compiler: gcc

MXNet commit hash (`git rev-parse HEAD`): 1ae2905cc3c2e35541d45edab18ddffb9cf455da

## Error Message:
pretrained_models/inception_bn/Inception-BN-symbol.json ... 116922 bytes
pretrained_models/inception_bn/Inception-BN-0126.params ... 45284780 bytes
[21:26:38] include/dmlc/./logging.h:300: [21:26:38] src/core/op.cc:55: Check failed: op != nullptr Operator Convolution is not registered

Stack trace returned 14 entries:
[bt] (0) /home/ubuntu/mxnet/lib/libmxnet.so(_ZN4nnvm2Op3GetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x38a) [0x7f83791543da]
[bt] (1) /home/ubuntu/mxnet/lib/libmxnet.so(+0x19d166c) [0x7f837912b66c]
[bt] (2) /home/ubuntu/mxnet/lib/libmxnet.so(+0x19d1b03) [0x7f837912bb03]
[bt] (3) /home/ubuntu/mxnet/lib/libmxnet.so(_ZN4dmlc20JSONObjectReadHelper13ReadAllFieldsEPNS_10JSONReaderE+0x12a) [0x7f8379133e3a]
[bt] (4) /home/ubuntu/mxnet/lib/libmxnet.so(+0x19cfeb4) [0x7f8379129eb4]
[bt] (5) /home/ubuntu/mxnet/lib/libmxnet.so(_ZNSt17_Function_handlerIFN4nnvm5GraphES1_EPS2_E9_M_invokeERKSt9_Any_dataOS1_+0x111) [0x7f83784e0ca1]
[bt] (6) /home/ubuntu/mxnet/lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x342) [0x7f837913e932]
[bt] (7) /home/ubuntu/mxnet/lib/libmxnet.so(_ZN4nnvm4pass8LoadJSONERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x986) [0x7f83787f9bc6]
[bt] (8) /home/ubuntu/mxnet/lib/libmxnet.so(MXPredCreatePartialOut+0x118) [0x7f83787efce8]
[bt] (9) /home/ubuntu/mxnet/lib/libmxnet.so(MXPredCreate+0x1d) [0x7f83787f4e2d]
[bt] (10) src/Inference(_ZN14MXNetPredictor7predictERKN2cv3MatESt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISA_EERS4_IS4_IfSaIfEESaISE_EE+0x214) [0x40d26c]
[bt] (11) src/Inference(main+0x26d) [0x410707]
[bt] (12) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f837631b830]
[bt] (13) src/Inference(_start+0x29) [0x40cc99]

Segmentation fault (core dumped)

## Minimum reproducible example
https://github.com/dmlc/mxnet/blob/master/example/image-classification/predict-cpp/image-classification-predict.cc

**Comment by piiswrong** [comment]
will be fixed by https://github.com/dmlc/mxnet/pull/4537
