### ISSUE TITLE
In the mxnet, how to implement a column vector with a matrix dot multiplication?

### ISSUE THREAD

**Issue by whaozl** [dmlc/mxnet#4571]
for example, a colum vector :

```python
import numpy as np
import mxnet as mx
a=np.array([1,2,3,4])
b=np.array([
[1,2,3,4,5,6,7,8,9,10],
[2,3,4,5,6,7,8,9,10,10],
[12,12,3,4,5,6,7,12,11,10],
[13,12,13,14,15,16,17,18,19,10]
])
#I want the element of a with every element of every row  of b dot multiplication
```

**Comment by sxjscience** [comment]
You can perform dot product by mx.sym.dot

**Comment by whaozl** [comment]
@sxjscience ,But I use the mx.sym.broadcast_mul, the error is dimension problem, but I try the follow code, this o of the result is different in every run.

```python
import numpy as np
import mxnet as mx

A=mx.sym.Variable('A')
B=mx.sym.Variable('B')
result=mx.sym.broadcast_mul(A,B)

a =mx.nd.array(np.array([1,2]))
b =mx.nd.array(np.array([[2],[4]]))
#a=mx.nd.array(np.array([1,2,3,4]))
#b=mx.nd.array(np.array([[1,2,3,4,5,6,7,8,9,10],[2,3,4,5,6,7,8,9,10,10],[12,12,3,4,5,6,7,12,11,10],[13,12,13,14,15,16,17,18,19,10]]))

result_exec = result.bind(ctx=mx.cpu(),args={'A':a, 'B':b})
o=result_exec.outputs[0].asnumpy()
o
```

the result in every run is :
```
array([[  7.37727998e+28,   1.05974542e-38],
       [  2.10194770e-44,   0.00000000e+00]], dtype=float32)
```
ohter:
```
array([[  6.74210166e+22,   1.68155816e-43],
       [  0.00000000e+00,   0.00000000e+00]], dtype=float32)
```

**Comment by sxjscience** [comment]
@whaozl you need to add the `result_exec.forward()` in order to get the outputs.
Change the code to the following:
```
import numpy as np
import mxnet as mx

A=mx.sym.Variable('A')
B=mx.sym.Variable('B')
result=mx.sym.broadcast_mul(A,B)

a =mx.nd.array(np.array([1,2]))
b =mx.nd.array(np.array([[2],[4]]))
#a=mx.nd.array(np.array([1,2,3,4]))
#b=mx.nd.array(np.array([[1,2,3,4,5,6,7,8,9,10],[2,3,4,5,6,7,8,9,10,10],[12,12,3,4,5,6,7,12,11,10],[13,12,13,14,15,16,17,18,19,10]]))

result_exec = result.bind(ctx=mx.cpu(),args={'A':a, 'B':b})
result_exec.forward()
o=result_exec.outputs[0].asnumpy()
o
```

**Comment by whaozl** [comment]
Thank you very much, Can I bother you one more thing? 
```python
import numpy as np
import mxnet as mx

A=mx.sym.Variable('A')
B=mx.sym.Variable('B')
result=A+B
a =mx.nd.array(np.array([1,2]))
b =mx.nd.array(np.array([2,4]))
result_exec = result.bind(ctx=mx.cpu(),args={'A':a, 'B':b})
o=result_exec.outputs[0].asnumpy()
o
```

This work well, But I Change mx.cpu to mx.gpu:
```python
result_exec = result.bind(ctx=mx.cpu(),args={'A':a, 'B':b})
```
This have a error about executor graph problem in the mxnet0.9.1.

But in the mxnet0.7.0 of window, it work well.

Thank you very much!

**Comment by sxjscience** [comment]
May try to use
```python
a =mx.nd.array(np.array([1,2]), ctx=mx.gpu())
b =mx.nd.array(np.array([2,4]), ctx=mx.gpu())
```

**Comment by Eshter** [comment]
after adding the "result_exec.forward()", the code  still has mistake, the error is as follows :


MXNetError                                Traceback (most recent call last)
<ipython-input-12-db51680d21cf> in <module>()
     11 #b=mx.nd.array(np.array([[1,2,3,4,5,6,7,8,9,10],[2,3,4,5,6,7,8,9,10,10],[12,12,3,4,5,6,7,12,11,10],[13,12,13,14,15,16,17,18,19,10]]))
     12 
---> 13 result_exec = result.bind(ctx=mx.cpu(),args={'A':a, 'B':b})
     14 result_exec.forward()
     15 o=result_exec.outputs[0].asnumpy()

c:\python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.pyc in bind(self, ctx, args, args_grad, grad_req, aux_states, group2ctx, shared_exec)
    850                                          aux_args_handle,
    851                                          shared_handle,
--> 852                                          ctypes.byref(handle)))
    853         executor = Executor(handle, self, ctx, grad_req, group2ctx)
    854         executor.arg_arrays = args

c:\python27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.pyc in check_call(ret)
     75     """
     76     if ret != 0:
---> 77         raise MXNetError(py_str(_LIB.MXGetLastError()))
     78 
     79 if sys.version_info[0] < 3:

MXNetError: InferShape Error in broadcast_mul5: [16:19:10] c:\deeplearning\mxnet\src\operator\./elementwise_binary_broadcast_op-inl.h:58: Check failed: (lhs.ndim()) == (rhs.ndim()) lhs:(2,) rhs:(2,1)

**Comment by whaozl** [comment]
@sxjscience  Thank you very much! You are right!

**Comment by Eshter** [comment]
`
a =mx.nd.array(np.array([1,2]), ctx=mx.gpu())
b =mx.nd.array(np.array([2,4]), ctx=mx.gpu())
`
