### ISSUE TITLE
element_mask is removed. who know how to use *mask.reshape((mask.size, 1, 1, ..., 1)) ?

### ISSUE THREAD

**Issue by whaozl** [dmlc/mxnet#4573]
element_mask is removed. Please use src*mask.reshape((mask.size, 1, 1, ..., 1)) directly as binary ops now support broadcasting.

I update the mxnet version to 0.9.1 in the window. I play the lstm, but 'module' object has no attribute 'element_mask'.

please help me for a hint and code example in python to use *mask.reshape((mask.size, 1, 1, ..., 1)) , replace the element_mask.

**Comment by ZiJianZhao** [comment]
I also want ask why the element_mask is removed? Then how can we mask the padding data to 0 in rnn model.

**Comment by whaozl** [comment]
@ZiJianZhao yes, why remove the element_mask ? element_mask  is very good to use!

**Comment by ZiJianZhao** [comment]
@whaozl you can use broadcast_mul as a substitution of the element_mask.

**Comment by whaozl** [comment]
thank you very much for the hint!

**Comment by morusu** [comment]
how to use broadcast_mul,.... i tried , but wrong

**Comment by ZiJianZhao** [comment]
You can follow the api instruction in the mxnet.io website. if you can't get it right, then maybe you mxnet version is not right or anything else. I'm not sure.
