### ISSUE TITLE
MXnet - can install but not load

### ISSUE THREAD

**Issue by pauldubose** [dmlc/mxnet#4574]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows 7 Professional

Compiler: R for Windows 3.3.2

Package used (Python/R/Scala/Julia): R for Windows 3.3.2

MXNet version: package ‘mxnet’ version 0.7

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] igraph_1.0.1       Rcpp_0.12.8        rstudioapi_0.6     magrittr_1.5       munsell_0.4.3     
 [6] colorspace_1.3-2   R6_2.2.0           brew_1.0-6         stringr_1.1.0      plyr_1.8.4        
[11] dplyr_0.5.0        visNetwork_1.0.3   Rook_1.1-1         tools_3.3.2        grid_3.3.2        
[16] gtable_0.2.0       DBI_0.5-1          influenceR_0.1.0   DiagrammeR_0.9.0   htmltools_0.3.5   
[21] lazyeval_0.2.0     digest_0.6.11      assertthat_0.1     tibble_1.2         gridExtra_2.2.1   
[26] RColorBrewer_1.1-2 ggplot2_2.2.1      htmlwidgets_0.8    viridis_0.3.4      rgexf_0.15.3      
[31] stringi_1.1.2      scales_0.4.1       XML_3.98-1.5       jsonlite_1.2  

## Error Message:
Please paste the full error message, including stack trace.

I can install mxnet package but I can't make it available for use, problem with version 0.9.0 DiagrammeR

> library("mxnet", lib.loc="~/R/win-library/3.3")
Error : object ‘combine_edges’ is not exported by 'namespace:DiagrammeR'
Error: package or namespace load failed for ‘mxnet’

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.  Unistalled DiagrammeR_0.9.0 and tried to install earlier version with following commands

remove.packages("DiagrammeR")
install_version("DiagrammeR", version = "0.8.1", repos = "cran.us.r-project.org")

response to install_version command:

Warning: unable to access index for repository cran.us.r-project.org/src/contrib:
  scheme not supported in URL 'cran.us.r-project.org/src/contrib/PACKAGES'
Error in package_find_repo(package, repos) : 
  couldn't find package 'DiagrammeR'

2.
3.

**Comment by thirdwing** [comment]
This has already been fixed in https://github.com/dmlc/mxnet/pull/4549

The Windows pkg hasn't be update yet.

**Comment by pauldubose** [comment]
Thanks for the update! Glad to hear about the progress.


________________________________

**Comment by RogerBorras** [comment]
I have the same problem. @thirdwing The MxnetR update for windows will be available soon? Thanks a lot for this fantastic package for R users!

**Comment by thirdwing** [comment]
Before we update the Windows pkg, you can try the following solution:

```
require(devtools)
install_version("DiagrammeR", version = "0.8.1", repos = "http://cran.us.r-project.org")
```

The latest version of `DiagrammeR` breaks many APIs.

**Comment by pauldubose** [comment]
Thanks for the code snippet


I ran the second line, but not the first line.  Good to know.


Paul


________________________________

**Comment by RogerBorras** [comment]
Thx @thirdwing !

**Comment by thirdwing** [comment]
This has been fixed. Feel free to reopen if necessary.
