### ISSUE TITLE
[R] error in file io

### ISSUE THREAD

**Issue by thirdwing** [dmlc/mxnet#458]
```r
> mat = mx.nd.array(1:20)
> mx.nd.save(mat, 'temp.mat')
Error: could not convert using R function : as.list
```

@terrytangyuan You should fail the unit test in R. Let me fix this first.

**Comment by tqchen** [comment]
@thirdwing Let us only support saving list of ndarray for now, and report error for single ndarray. As discussed with @hetong007

**Comment by thirdwing** [comment]
You can just wrap the single one in a list: https://github.com/thirdwing/mxnet/blob/master/R-package/R/ndarray.R#L36

**Comment by hetong007** [comment]
Users might be confused if they saved an ndarray but got a list after loaded back.

**Comment by tqchen** [comment]
As user will get confused by getting a list after loading back, so we can disable it for now. 

Special treatment might could be done to encode a special list, say the first element is a 1x1 ndarray with key="__ndarray_workspace__", then the behavior indicates load ndarray back
