### ISSUE TITLE
how to use mx.sym.Reshape, a row matrix Copy four times according to the direction of the row

### ISSUE THREAD

**Issue by whaozl** [dmlc/mxnet#4580]
I have the mx.sym.Reshape introduction and using method, But I don't know the other using method, for example `B = mx.sym.Reshape(data=A,shape=(-1,))`, the shape=(-2,) -3 -4 and so on. In the [mxnet official website about symbol Reshape](http://mxnet.io/api/python/symbol.html), `it doesn't have any using code example`.

This following code which I konw:

```python
import numpy as np
import mxnet as mx
A = mx.sym.Variable('A')
B = mx.sym.Reshape(data=A,shape=(-1,))
a = mx.nd.array(np.array([[1,2,3,4],[5,6,7,8]]))
b_exec = B.bind(ctx=mx.cpu(),args={'A':a})
b_exec.forward()
o=b_exec.outputs[0].asnumpy()
o.shape#(8,1)
```

But I don't know how to use `mx.sym.Reshape`, make `a row matrix` copy to a `Multi row matrix`. For example:

```python
import numpy as np
import mxnet as mx
a=mx.nd.array(np.array([1,2,3,4,5,6]))
#By using mx.sym.Reshape, I hope the result is 
#result=[[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]
#This measns a row matrix Copy four times according to the direction of the row
#
```

**Comment by kevinthesun** [comment]
http://mxnet.io/api/python/symbol.html?highlight=broadcast#mxnet.symbol.broadcast_to
broadcast_to can be used to copy.

a=mx.nd.array(np.array([1,2,3,4,5,6]))
b = a.broadcast_to((4, 6))

**Comment by Eshter** [comment]
@kevinthesun thank  you very much~

**Comment by whaozl** [comment]
Thank you very much @kevinthesun , But Can you tell me about the using method of mx.sym.Reshape? Sorry, Please allow me to disturb you again.

**Comment by sxjscience** [comment]
@whaozl Reshape can only be used when the overall dimensionality remains the same. For changing the dimensionality, you will need to use [broadcasting] (https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

**Comment by whaozl** [comment]
@sxjscience  Sorry, But I want to implement the using of the `element_mask`, So , I have to copy the row matrix for four times. Because of the `element_mask` is removed.
Thank you very much for a lot help!

**Comment by morusu** [comment]
the same problem
