### ISSUE TITLE
MXNET gpu memory usage issue

### ISSUE THREAD

**Issue by animebing** [dmlc/mxnet#4582]
there is one net definition below, the gpu memory required i computed is different from that from memonger, i can't figure out why, below is net definition

    num_class = 19
    data = mx.sym.Variable('data')
    ctx_conv1_1 = mx.sym.Convolution(data=data, kernel=(3, 3), pad=(1, 1), num_filter=num_class, name='ctx_conv1_1', workspace=2048)
    ctx_relu1_1 = mx.sym.Activation(data=ctx_conv1_1, act_type='relu', name='ctx_relu1_1')
    ctx_conv1_2 = mx.sym.Convolution(data=ctx_relu1_1, kernel=(3, 3), pad=(1, 1), num_filter=num_class, name='ctx_conv1_2', workspace=2048)
    ctx_relu1_2 = mx.sym.Activation(data=ctx_conv1_2, act_type='relu', name='ctx_relu1_2')
    ctx_conv2_1 = mx.sym.Convolution(data=ctx_relu1_2, kernel=(3, 3), pad=(2, 2), num_filter=num_class, dilate=(2, 2), name='ctx_conv2_1', workspace=2048)
    ctx_relu2_1 = mx.sym.Activation(data=ctx_conv2_1, act_type='relu', name='ctx_relu2_1') 
    ctx_conv3_1 = mx.sym.Convolution(data=ctx_relu2_1, kernel=(3, 3), pad=(4, 4), num_filter=num_class, dilate=(4, 4), name='ctx_conv3_1', workspace=2048)
    ctx_relu3_1 = mx.sym.Activation(data=ctx_conv3_1, act_type='relu', name='ctx_relu3_1') 
    ctx_conv4_1 = mx.sym.Convolution(data=ctx_relu3_1, kernel=(3, 3), pad=(8, 8), num_filter=num_class, dilate=(8, 8), name='ctx_conv4_1', workspace=2048)
    ctx_relu4_1 = mx.sym.Activation(data=ctx_conv4_1, act_type='relu', name='ctx_relu4_1')
    ctx_conv5_1 = mx.sym.Convolution(data=ctx_relu4_1, kernel=(3, 3), pad=(16, 16), num_filter=num_class, dilate=(16, 16), name='ctx_conv5_1', workspace=2048)
    ctx_relu5_1 = mx.sym.Activation(data=ctx_conv5_1, act_type='relu', name='ctx_relu5_1')
    ctx_conv6_1 = mx.sym.Convolution(data=ctx_relu5_1, kernel=(3, 3), pad=(32, 32), num_filter=num_class, dilate=(32, 32), name='ctx_conv6_1', workspace=2048)
    ctx_relu6_1 = mx.sym.Activation(data=ctx_conv6_1, act_type='relu', name='ctx_relu6_1')
    ctx_conv7_1 = mx.sym.Convolution(data=ctx_relu6_1, kernel=(3, 3), pad=(64, 64), num_filter=num_class, dilate=(64, 64), name='ctx_conv7_1', workspace=2048)
    ctx_relu7_1 = mx.sym.Activation(data=ctx_conv7_1, act_type='relu', name='ctx_relu7_1')
    ctx_fc1 = mx.sym.Convolution(data=ctx_relu7_1, kernel=(3, 3), pad=(1, 1), num_filter=num_class, name='ctx_fc1', workspace=2048)
    ctx_fc1_relu1 = mx.sym.Activation(data=ctx_fc1, act_type='relu', name='ctx_fc1_relu1') 
    ctx_final = mx.sym.Convolution(data=ctx_fc1_relu1, kernel=(1, 1), num_filter=num_class, name='ctx_final', workspace=2048)
    softmax= mx.sym.SoftmaxOutput(data=ctx_final, multi_output=True, use_ignore=True, ignore_label=255, name="softmax")

when the input shape is (1, 3, 1024, 1024), i use memonger.get_cost to compute the memory used for feature map as below 

    cost = memonger.get_cost(softmax, data=(1, 3, 1024, 1024))

cost is 1596MB, then i compute that by hand as below

    input: 3*1024*1024*4 bytes = 12MB
    all ctx output and label: (19*1024*1024*11+1024*1024)*4 bytes = 840MB
    12+840=852 MB

852MB is much less than 1596MB, which confuses me a lot. i hope someone can help me figure out why, thanks

**Comment by tqchen** [comment]
The cost include the cost for calculating the back propagation and the one used to store gradient

**Comment by animebing** [comment]
@tqchen thank you, i realize that i forgot to compute the memory used to store the gradient of feature maps

**Comment by animebing** [comment]
@tqchen i am still not sure whether the result of memonger.get_cost includes the gradient of feature map, is that true? thank you

**Comment by mcxkarakoc** [comment]
.
