### ISSUE TITLE
[R] Add support for Drat Packages

### ISSUE THREAD

**Issue by hetong007** [dmlc/mxnet#459]
As we can see so far, `mxnet` is not so likely to appear on CRAN for it might violates the policy. Still we want to offer different releases of the package and host them on github as a CRAN-like repository, so that users can install and manage the packages easier.

The `Drat` pacakge seems to be a good option for this purpose. DMLC has already got a repository to host the packages(if I understand it correctly) : https://github.com/dmlc/drat. Please use this issue to track the progress of "drating" `mxnet`. 

cc @tqchen @thirdwing .

**Comment by thirdwing** [comment]
Actually it is not hard: https://github.com/thirdwing/drat

Problems to discuss:

(1) No Windows machine by hand;

(2) It will be a little tricky to host both CPU and GPU package in one repo;

**Comment by tqchen** [comment]
- I think we can point GPU user to advanced build for now
- Alternatively, allow separate build of libmxnet and R package as in Julia
   - c.f. https://github.com/dmlc/MXNet.jl/blob/master/deps/build.jl
   - The build can detect the existence of mxnet library, via MXNET_HOME env variable
   - If not exist, it will try to build a cpu only version.

**Comment by tqchen** [comment]
In terms of windows, I think some of us have windows machine, so @thirdwing if you can create an instruction(better script) to pack the things, some of us could help building that

**Comment by thirdwing** [comment]
(1) For windows, CPU version can be built using GCC toolchain and I didn't see any problems;

(2) For Mac and Linux, the building is quite easy: `make all && R CMD INSTALL R-package`

**Comment by thirdwing** [comment]
To install on Mac/Linux:
```
install.packages("drat")
drat:::addRepo("dmlc")
install.packages("mxnet")
```

**Comment by thirdwing** [comment]
Windows package is in drat repo now and demo works well.

![screenshot from 2015-11-21 14 27 57](https://cloud.githubusercontent.com/assets/1547093/11320191/493852f6-905e-11e5-91a4-1798eefae76e.png)

**Comment by tqchen** [comment]
@thirdwing  Can you update the document and README in R package to point to these instructions?
