### ISSUE TITLE
how to output the value of the eval_data for each epoch

### ISSUE THREAD

**Issue by wanderingpj** [dmlc/mxnet#4592]
I output the eval_batch in this line:
https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L299
but it prints like this:
![image](https://cloud.githubusercontent.com/assets/24189081/21750242/d2ce5e76-d5e9-11e6-9ba0-c430ff2d69f4.png)
it shows the address of the data batch, so how to output the value of the eval_data.

**Comment by piiswrong** [comment]
print label[0].asnumpy()

**Comment by wanderingpj** [comment]
thank you @piiswrong
