### ISSUE TITLE
Suggestions for MKL_README 

### ISSUE THREAD

**Issue by mcxkarakoc** [dmlc/mxnet#4593]
1st suggestion:
4. Set LD_LIBRARY_PATH=$LD_LIBRARY_PATH:**$MKLML_ROOT**/lib.

2nd suggestion:
If MKL2017 full package is already installed and MKL2017_ML will be used for MxNet compilation, do not execute compilervars.sh script before MxNet compilation. Otherwise, MKL2017 may conflict with MKL2017_ML and MxNet may not be compiled.

**Comment by piiswrong** [comment]
@glingyan

**Comment by glingyan** [comment]
https://github.com/dmlc/mxnet/pull/4599 :)
thanks

**Comment by mcxkarakoc** [comment]
You are welcome :)
