### ISSUE TITLE
GraphExecutor::Print output INFO

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#4601]
Where does this '11' come from? Is this a typo?

```
  os << "Total " << 11 << " TempSpace resource requested\n";
```

https://github.com/dmlc/mxnet/blob/master/src/executor/graph_executor.cc#L60

**Comment by tqchen** [comment]
This is a dummy information that is used for backward compatibility reason on the memonger. Should be changed to more meaningful information later when possible
