### ISSUE TITLE
how to adapt char_lstm for a time series prediction

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/mxnet#461]
I plan to use lstm for time series prediction and not sure whether mxnet is a good framework for this.
Is lstm.py in example/rnn only usable for char_lstm?
If it can be used for time series prediction, what changes need to be done in char_lstm.ipynb?

Thanks,

Kaishi

**Comment by antinucleon** [comment]
You can use it. The only thing to change is replace onehot input to your feature vector.

**Comment by kaishijeng** [comment]
I don't see onehot input in  char_lstm.ipynb. Can you tell me which part of the code has onehot encoding?

My input data is sequence of float numbers and like to use LSTM to predict output, x(n+1) when input is x(n).

Thanks,

**Comment by Kublai-Jing** [comment]
It's in lstm.py
