### ISSUE TITLE
Fix conv layers and train only FC layers

### ISSUE THREAD

**Issue by No41Name** [dmlc/mxnet#4616]
What I would to do is loading a pre-trained model (on imagenet) and train only its last fully connected layers on a new dataset, maintaining fixed all the weights of the convolutional layers (in order to use the first part of the network as a feature extractor). Can someone explain me how can I do this, in particular fix the conv layers?
Thanks!

**Comment by howard0su** [comment]
Check fine-tune.py under example/image-classification

**Comment by No41Name** [comment]
Thanks!

**Comment by jrosebr1** [comment]
@howard0su @No41Name I took a look at the `fine-tune.py` example and got it working for my own dataset. However it wasn't clear how to freeze/unfreeze particular layers. Perhaps I missed something?
