### ISSUE TITLE
lstm和rnn的io脚本中，如果batch_size设置太大是不是会丢掉很多凑不成整数的训练样本

### ISSUE THREAD

**Issue by janelu9** [dmlc/mxnet#4619]
如下：
bucket_n_batches = []
        for i in range(len(self.data)):
            bucket_n_batches.append(len(self.data[i]) / self.batch_size)
            self.data[i] = self.data[i][:int(bucket_n_batches[i]*self.batch_size)]

**Comment by formath** [comment]
Yes.
