### ISSUE TITLE
Example of ndarray.Convolution?

### ISSUE THREAD

**Issue by Primus-zhao** [dmlc/mxnet#4629]
Hi guys, 

Always got segmentation error when using ndarray.Convolution operator, especially when providing kwargs. Is there any official guide or code for its usage? Thks!

**Comment by piiswrong** [comment]
Could you post your code?

**Comment by piiswrong** [comment]
fixed by https://github.com/dmlc/mxnet/pull/4643/files

**Comment by Primus-zhao** [comment]
@piiswrong,
thks! i'll try the merged one
