### ISSUE TITLE
[IO] Enable Image Index in IO

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#463]
Hi, My network has multi outputs(just like faster-rcnn), every output has more than one label, but im2rec.cc and inter_prefetcher just handle one label per image, How can I train network with multi labels image easily?Can mxnet add the image index into DataBatch so I can get the other information of image in python?

**Comment by tqchen** [comment]
Yes, I think this is the way to go, expose the image index into the python side, that was what image index was originally designed for. This would involve a bit addition to the C API as index is best exposed as numpy integer array without being lazily stored.

Are you interested in contribution?

**Comment by tqchen** [comment]
cc @sneakerkg

**Comment by junranhe** [comment]
ok, I will try it~
