### ISSUE TITLE
Reshape failed to use memonger

### ISSUE THREAD

**Issue by fiona0827** [dmlc/mxnet#4630]
We try to use memonger to save memory in LSTM network with NNVM version,but when set attribute "force_mirroring" to Reshape symbol,there throws an error"cannot find argument "force_mirroring".Other operators like FullyConnected seem ok. I found that Reshape operator has been moved to src/tensor/matrix-op.cc ,and register switch to NNVM_REGISTER_OP,does this cause the problem?

**Comment by piiswrong** [comment]
mx.sym.Reshape(mx.sym.Variable('a'), force_mirroring='a')

**Comment by fiona0827** [comment]
After updating code to the newest version,it runs smoothly.Thank you!
