### ISSUE TITLE
[R] Add some example data to the package to be able to have example code in function documentation

### ISSUE THREAD

**Issue by pommedeterresautee** [dmlc/mxnet#464]
Most functions have no example code provided in their documentation.
For that purpose, the R package may include some raw data to process.

There are 3 possibilities:
- add some custom data directly in the package (like in XGBoost R package)
- add a dependency to a package which contains some data. Right now, **mlbench** is used in the RMarkdown documents.
- It is also possible to include some example without the data and mark the example code as not executable (so during the package compilation the example is not tested).

@tqchen @hetong007 @thirdwing What do you think we should do?

**Comment by hetong007** [comment]
I prefer the first one. Example should be the first code piece that helps a user to learn the way to call the function. So the more convenience the better.

**Comment by pommedeterresautee** [comment]
Do you think the same dataset than XGBoost is Ok? (the one with mushroom)
If yes should be easy to copy paste and we are sure it works...
Moreover, it would make it possible to compare results from both packages.

**Comment by thirdwing** [comment]
BTW, in the current building process, all examples are not tested

**Comment by hetong007** [comment]
@tqchen do we support sparse matrix input, or we need to do sparse -> dense conversion first? 
For the latter case, I now prefer to use two data sets to represent regression and classification respectively. They could be the `Sonar` and `BostonHousing` as in the document or other "easier" data sets.

**Comment by predict-r** [comment]
You can also generate some data like this: 

```
#GENERATE DATA

N = 100 # number of points per class
D = 2 # dimensionality
K = 3 # number of classes
num_examples = N*K
X = matrix(0,num_examples,D) # data matrix (each row = single example)
y = matrix(0,num_examples) # class labels

for (j in 0:(K-1)){
  ix = seq(N*j+1,N*(j+1))
  r = seq(0.0,1,length.out=N) # radius
  t = seq(j*4,(j+1)*4,length.out=N) + rnorm(N)*0.2 # theta
  X[ix,1] = r*sin(t)
  X[ix,2]= r*cos(t)
  y[ix] = j +1
}
# lets visualize the data:
plot(X[, 1], X[, 2], col=rainbow(3)[y])
```

**Comment by thirdwing** [comment]
I am closing this now, since example data has been provided during the unit test: https://github.com/dmlc/mxnet/blob/master/R-package/tests/testthat/get_data.R
