### ISSUE TITLE
[R] [API] Changing the way the model is saved

### ISSUE THREAD

**Issue by pommedeterresautee** [dmlc/mxnet#465]
Right now, the way the model/parameters is saved on R is not obvious:
- the filenames are not free
- the path are not provided

Is there some reasons for that?
If not, may I rewrite the function?

Kind regards,
Michaël

**Comment by tqchen** [comment]
Can you be a bit specific? The major reason is that there are two files in the model(symbol json and parameters) and the current API is designed to save them in consistent way.

**Comment by pommedeterresautee** [comment]
If I have correctly understood, with the current implementation of `mx.model.save`, there is no way to provide a folder path. Therefore the model and the parameters are saved in the working directory.

Moreover, I feel it is unusual to force the way the file name is built. May be the user have a specific idea of what he wants.

In both cases, I feel the API is slightly unnatural for no obvious reasons.

**Comment by thirdwing** [comment]
@pommedeterresautee We can provide an optional parameter for the folder path.

I think it is still better to let symbol and parameter files have the same prefix.

**Comment by tqchen** [comment]
It does not have to be in current path, the prefix can be path to say model folder plus the file name

**Comment by thirdwing** [comment]
@tqchen Yes, but I don't users know they can do something below:

```r
mx.model.save(model, prefix="~/Desktop/test", iteration=1)
```

Let's make this clear in documents if a new parameter is not necessary.

@pommedeterresautee Do you think this is enough for your point?

**Comment by pommedeterresautee** [comment]
I also think it is not obvious that prefix may be used for that purpose too.

There are two possibilities:
- improving documentation
- adding a new parameter

I would prefer the second option.
@thirdwing @hetong007 @tqchen Let me know what you prefer.

**Comment by thirdwing** [comment]
@pommedeterresautee Sorry for the late reply.

Actually I prefer a new parameter, maybe you can send a PR.

**Comment by pommedeterresautee** [comment]
no pb. 
I am traveling right now but will try to do it next weel.

Kind regards,
Michael

**Comment by tqchen** [comment]
Let us know if there is update on this, going to close this for now
