### ISSUE TITLE
Raising num_args bound ?

### ISSUE THREAD

**Issue by Kublai-Jing** [dmlc/mxnet#467]
When I try to compile LSTM with quite a long time steps (200), following error occurs,

         71     """
         72     if ret != 0:
    ---> 73         raise MXNetError(py_str(_LIB.MXGetLastError()))
         74 
         75 def c_str(string):
   
    MXNetError: value 100for Parameter num_args exceed bound [1,100)

It seems that for whatever reason, 100 is a hard limit on the number of args that can be compiled ? I wonder whether we can change this bound (if we have more memory)

Thanks !

**Comment by tqchen** [comment]
Please submit a PR for this, this was due to some choices in the parameters side. You should be able to locate the num_args in the operators you performed. Instead of  using ```DECLARE_PARAMETER(num_args).set_range(1,100)``` change it to ```DECLARE_PARAMETER(num_args).set_lower_bound(1)```

**Comment by tqchen** [comment]
cc @antinucleon

**Comment by Kublai-Jing** [comment]
Thx ! Given that we can set this using that command, what you suggest the PR is for ?

**Comment by tqchen** [comment]
Oh, this is the code on C++ side, not python. for example https://github.com/dmlc/mxnet/blob/master/src/operator/concat-inl.h#L31

**Comment by tqchen** [comment]
This being said, I do not know in which specific operator this num_args constraint sits, so will need a bit of your help in catching it:)

**Comment by Kublai-Jing** [comment]
Can we treat it as a global environment variable ?

**Comment by tqchen** [comment]
The idea is by default we should have no limit in num_args. The previous settings are quite arbitrary and should be corrected

**Comment by Kublai-Jing** [comment]
seems that the only place where this hard limit is placed is 

    struct ElementWiseSumParam : public dmlc::Parameter<ElementWiseSumParam> {
    30	  int num_args;
    31	  DMLC_DECLARE_PARAMETER(ElementWiseSumParam) {
    32	    DMLC_DECLARE_FIELD(num_args).set_range(1, 100)

in src/operator/elementwise_sum-inl.h 

It seems suffices to just remove that constraint there

**Comment by tqchen** [comment]
Yes, pls go ahead to do so

**Comment by tqchen** [comment]
Thanks to @Kublai-Jing fixed by #469
