### ISSUE TITLE
[Scala] FeedForward: shouldn't symbol by public? Or: how to build one net from an existing one

### ISSUE THREAD

**Issue by benqua** [dmlc/mxnet#4675]
I would like to use the convolution par of a pre-trained VGG-16 network and retrained the fully connected classification layers.
However, after importing the VGG model from https://github.com/dmlc/mxnet-model-gallery, I see no way in FeedForward.scala to built a network with only the CNN layers (with their trained weights) and a new set of top fully connected layers.
FeedForward.symbol is necessary to build a new network but it is private.

Is there a way to fulfill this quite common use case with mxnet-scala? Did I miss something?

**Comment by Ldpe2G** [comment]
@benqua you can refer to https://github.com/dmlc/mxnet/blob/master/example/image-classification/fine-tune.py to see how to do the finetuning in python, I think it should be easy to implement in Scala.

**Comment by benqua** [comment]
@Ldpe2G thanks for your quick answer.
So, if I understand it right, I should not start from the FeedForward class since I cannot get the symbol from there but use the model.load_checkpoit method to get the symbol.

i will try this, thanks.

**Comment by javelinjs** [comment]
Or, you can 1) build the network structure (symbol) manually; 2) use `Symbol.bind` to get an `Executor`; 3) copy model params to `Executor.argDict`.

**Comment by benqua** [comment]
Nice, thank you.

And how do I "lock" the CNN layers so they don't get trained again?

**Comment by javelinjs** [comment]
You can do it using `module` api. For Scala, it is still in progress: https://github.com/dmlc/mxnet/pull/4583

**Comment by benqua** [comment]
Ok. I will closely follow on #4583 because it is really something I would like to be able to do in mxnet-scala.

I will close this issue as there is no issue /  bug with the code. By the way, is there another place to ask this kind of question? I couldn't find the answer in the documentation and I feel that github issues are not the right place for this kind of question. Is there somewhere a mailing list or irc channel (I couldn't find)?
Generally speaking, I don't understand how such an amazing project get so few attention in social media and internet in general! Keep up the good work!
