### ISSUE TITLE
what does the mx.sym.SliceChannel means?

### ISSUE THREAD

**Issue by janelu9** [dmlc/mxnet#4693]
such as：
 slice_gates = mx.sym.SliceChannel(gates, num_outputs=4,
                                      name="t%d_l%d_slice" % (seqidx, layeridx))
Does this function slice the gates'  dim to 4 little dims?

such as:
[0,1,2,3,4,5,6,7]--->>[[0,1],[2,3],[4,5],[6,7]]

**Comment by moveforever** [comment]
yes, it's right

**Comment by janelu9** [comment]
In fact  my example is not  very accurate ,
exactly, it slice the input data by the width
such as : 
shape(32,50,20)--->>50 pieces of shape(32,20) or shape (32,1,20)

**Comment by moveforever** [comment]
mx.symbol.SliceChannel(data = data, num_outputs=2, axis = 0)
parameter axis can control which axis

**Comment by moveforever** [comment]
if target shape is (32,1,20), mx.symbol.SliceChannel(data = data, num_outputs=50, axis = 1)
