### ISSUE TITLE
More informative debug info for errors in engine

### ISSUE THREAD

**Issue by piiswrong** [dmlc/mxnet#470]
The current error message for errors in the engine is very cryptic, for example:
[15:38:38] src/engine/./threaded_engine.h:295: [15:38:38] ./mshadow/mshadow/./tensor_blob.h:508: Check failed: Device::kDevMask == dev_mask_ && DataType<DType>::kFlag == type_flag_ TBlob.get: device type do not match specified type
It's not clear which operation/tensor caused this error and due to the separate executor/engine design, it's hard to figure out by debugging.

We can probably improve this by making a global operation/tensor registry for debug mode only. When an error occurs we can print out the name of the tensor or the operation that generated this error.

=======================
If this is too complicated, we can at least have a "common errors and how to fix them" page

**Comment by Ericargus** [comment]
i @piiswrong  hello, i met this error:
mxnet.base.MXNetError: [22:01:36] include/mxnet/././tensor_blob.h:235: Check failed: Device::kDevMask == this->dev_mask() TBlob.get: device type do not match specified type
can you help me what can i do.Thanks
