### ISSUE TITLE
mxnet won't load

### ISSUE THREAD

**Issue by jaredlander** [dmlc/mxnet#4710]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:  Windows

Compiler: Using precompiled binaries

Package used (Python/R/Scala/Julia): R

MXNet version: R Package version 0.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
```
library(mxnet)
Error : object ‘combine_edges’ is not exported by 'namespace:DiagrammeR'
Error: package or namespace load failed for ‘mxnet’
```

But when using `require` only the error message about `combine_edges` is displayed.
```
require(mxnet)
Loading required package: mxnet
Error : object ‘combine_edges’ is not exported by 'namespace:DiagrammeR'
```

```
traceback()
2: stop(gettextf("package or namespace load failed for %s", sQuote(package)), 
       call. = FALSE, domain = NA)
1: library(mxnet)
```

Either way, `mxnet` never gets loaded.

## What have you tried to solve it?

1. Tried installing again
2. Rebooted

`xgboost` recently had problems due to breaking changes in `DiagrammeR` and it was fixed.  Perhaps the changes in `DiagrammeR` has caused issues with `mxnet`.

``` r
sessionInfo()
```

    ## R version 3.3.2 (2016-10-31)
    ## Platform: x86_64-w64-mingw32/x64 (64-bit)
    ## Running under: Windows 10 x64 (build 14393)
    ## 
    ## locale:
    ## [1] LC_COLLATE=English_United States.1252 
    ## [2] LC_CTYPE=English_United States.1252   
    ## [3] LC_MONETARY=English_United States.1252
    ## [4] LC_NUMERIC=C                          
    ## [5] LC_TIME=English_United States.1252    
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] igraph_1.0.1       Rcpp_0.12.8        rstudioapi_0.6    
    ##  [4] knitr_1.15.1       magrittr_1.5       munsell_0.4.3     
    ##  [7] colorspace_1.3-1   R6_2.2.0           brew_1.0-6        
    ## [10] dplyr_0.5.0        stringr_1.1.0      plyr_1.8.4        
    ## [13] visNetwork_1.0.2   Rook_1.1-1         tools_3.3.2       
    ## [16] grid_3.3.2         gtable_0.2.0       DBI_0.5-1         
    ## [19] influenceR_0.1.0   DiagrammeR_0.9.0   htmltools_0.3.5   
    ## [22] assertthat_0.1     yaml_2.1.14        lazyeval_0.2.0    
    ## [25] rprojroot_1.1      digest_0.6.11      tibble_1.2        
    ## [28] gridExtra_2.2.1    RColorBrewer_1.1-2 ggplot2_2.2.0     
    ## [31] htmlwidgets_0.8    viridis_0.3.4      evaluate_0.10     
    ## [34] rgexf_0.15.3       rmarkdown_1.3      stringi_1.1.2     
    ## [37] scales_0.4.1       backports_1.0.4    XML_3.98-1.5      
    ## [40] jsonlite_1.2

**Comment by piiswrong** [comment]
Yes it was due to the DiagrammeR update. It has been fixed. Please update mxnet.

**Comment by jaredlander** [comment]
Looks like the version on the dmlc repo is `0.7` and the one on GitHub is `0.9`.  Will the repo be updated soon?

**Comment by RogerBorras** [comment]
I have the same problem too. It will be nice if you can update mxnetR for windows users. Thx for this amazing R library.

**Comment by piiswrong** [comment]
@thirdwing @hetong007 Could you update it?

**Comment by thirdwing** [comment]
I will upload the 0.9 R pkg for Windows in the weekend.

**Comment by jaredlander** [comment]
Any luck with this?  Just tried again and it's still 0.7.

**Comment by asinga1982** [comment]
I am also stuck with 0.7, will be great if you can upload the fix.

**Comment by asinga1982** [comment]
If you are stuck with this error, then you can downgrade the DiagrammeR version to resolve the issue. 
Check: https://github.com/dmlc/mxnet/issues/4527

**Comment by thirdwing** [comment]
This has been fixed. Feel free to reopen if necessary.
