### ISSUE TITLE
Scalar Symbol Operator

### ISSUE THREAD

**Issue by zgbdsg** [dmlc/mxnet#473]
I want to change the structure of LSTM using a paper in 2014. One of the formulation is h=(1-z)*h~ + z*h,  is there a good solution to represent the "1" ?

**Comment by tqchen** [comment]
This should be able to be implemented by elementwise-scalar symbol as in the ndarray ops. The idea is to implement a ScalarOp that takes a scalar and symbol. It should be straight forward to implement this like https://github.com/dmlc/mxnet/blob/master/src/operator/activation-inl.h

Then we can do operator overloading on python side to support the elementwise ops with scalars.
Please let us know if you are interested in take a stab.

**Comment by pluskid** [comment]
Closing since PR already merged.
