### ISSUE TITLE
how can i use neural style on ios

### ISSUE THREAD

**Issue by lsy17096535** [dmlc/mxnet#4743]
I am run an mxnet example on ios, but it can only use predict. The API has four functions, could you tell me  how to add new APIs and use backward on ios?

**Comment by DiaG48** [comment]
On mobile device SGD will be very slow if you will use naive style transfer implementation. Actualy, you don't need backprop-pass for style transfer, only forward pass. There is a lot of articles, that describe how to implement fast version of style transfer (for example https://arxiv.org/abs/1603.08155 and https://arxiv.org/abs/1610.07629) in feed-forward model.
