### ISSUE TITLE
Does the docker support distributed computation

### ISSUE THREAD

**Issue by janelu9** [dmlc/mxnet#4765]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by pineking** [comment]
The answer is YES, I have successfully run the distributed experiments with docker environment.

**Comment by janelu9** [comment]
@pineking  how did you do it successfully？
i don’t find a ssh in the docker

**Comment by pineking** [comment]
@janelu9 what's the meaning of 'can not find a ssh', could you describe your question in more detail?

**Comment by janelu9** [comment]
@pineking  ssh ip  Connection refused 
I don't know why,  this ip is the docker's , need i start the ssh server in the docker at first

**Comment by pineking** [comment]
this is the question of docker rather than mxnet.
you can add `--net=host` option when running docker container,
or try to read the documents of docker.

**Comment by janelu9** [comment]
@pineking 
is the reason that my docker container does not contain a ssh server?

**Comment by janelu9** [comment]
@pineking 
is your docker downloaded from the mxnet's offical web

**Comment by janelu9** [comment]
the docker attached on the official web doesn't support, i create one available at http://pan.baidu.com/s/1cb3Ctg

**Comment by pineking** [comment]
@janelu9, sorry for the late reply.
For distributed training, you need to compile with `USE_DIST_KVSTORE=1`, since this option is false for official docker image, that's why you need to build it by yourself.

**Comment by tobegit3hub** [comment]
Is that possible to enable `USE_DIST_KVSTORE=1` by default in the official docker image?

This could really help for anyone who wants to try MXNet.

**Comment by eric-haibin-lin** [comment]
I think dist-kvstore is enabled in pip. ping @szha for further confirmation

**Comment by szha** [comment]
@tobegit3hub yes, all pip variants starting from 0.11.1 (currently only in nightly pre-releases) are built with ps-lite now.
