### ISSUE TITLE
Creating new cost with the symbolic API ?

### ISSUE THREAD

**Issue by jrabary** [dmlc/mxnet#478]
Hi all,

Is it possible to create a new cost with the symbolic API as one can do with Theano ? For example,
I would like to train a triplet network with the following hinge loss `max(0, d(a,p)^2 - d(a,n)^2 + alpha)` .
Can this be done in python API level or should I implement the loss insinde libmxnet in C++ ?

More generally, what is the mxnet way to add a new layer ?

**Comment by pluskid** [comment]
See #436

**Comment by vchuravy** [comment]
@pluskid can we do the same thing from Julia?

**Comment by pluskid** [comment]
Not yet, but that is the next thing to add. Should be fairly straightforward. Hopefully I could find some time to add that this week. But you are also very welcome to contribute if interested in.

**Comment by vchuravy** [comment]
I will see if I find time this week to do that.
