### ISSUE TITLE
What does node_row_ptr stands for in the symbol json file?

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#4785]
Hi, does anyone know what the  node_row_ptr list stands for in the created json when the model is saved? 

The nodes defines 33 total nodes for me, but the node_row_ptr contains 36 elements.

**Comment by KeyKy** [comment]
@Godricly Did you find the meaning of node_row_ptr?

**Comment by Godricly** [comment]
I don't remember it. It was so long time ago. Sorry.

**Comment by BUG1989** [comment]
@KeyKy 
https://docs.tvm.ai/dev/nnvm_json_spec.html#node-row-ptr

**Comment by lizhenfengfeng** [comment]
stores the history of forward path, so you can skip constructing the entire graph in inference tasks.
but I also can't understand how to get node_row_ptr

**Comment by AlexanderSerov** [comment]
https://github.com/dmlc/nnvm/blob/master/docs/json_spec.rst
