### ISSUE TITLE
Unit test examples

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#482]
感觉修改代码的时候容易忽略了改examples哦，例如 imagenet alexnet.py 以前num_round 改为了num_epoch没有跟着改，对第一次的朋友使用mxnet有点不必要的麻烦。。。

**Comment by yajiedesign** [comment]
could put the example in the unit test?

**Comment by mli** [comment]
the examples are too expensive for testing. even moving the imagenet dataset is not easy.

we might let a gpu machine run the examples once every day for testing

**Comment by tqchen** [comment]
Thanks for the suggestion. Most examples are too heavily weighted, to be added to the testcase. But you are right that we need to be more careful about examples when API changes are introduced. 

Most API should be stablized and we would expect a few changes in IO to make it more general, hopefully such thing will happen less in the future
