### ISSUE TITLE
Amalgamation on iOS

### ISSUE THREAD

**Issue by PetroWu** [dmlc/mxnet#4820]
I generate the `mxnet_predict-all.cc` and add it to WhatIsThis-iOS project, which throws the errors:
`Unknown type name '__m128'`
`Use of undeclared identifier '_mm_set1_ps'`
`...`
I can find no solution about sse2 on iOS, but what should I do for this?

## Environment info
Operating System: OSX

MXNet version: 0.9.3

**Comment by piiswrong** [comment]
Try adding adding DEFS+=-DMSHADOW_USE_SSE=0 here https://github.com/dmlc/mxnet/blob/master/amalgamation/Makefile#L22

**Comment by PetroWu** [comment]
I have added it but the error still exists. I edited the setting in mxnet_predict-all.cc from
`/*! \brief whether use SSE */
#ifndef MSHADOW_USE_SSE
  #define MSHADOW_USE_SSE 1
#endif`
to
`/*! \brief whether use SSE */
#ifndef MSHADOW_USE_SSE
  #define MSHADOW_USE_SSE 0
#endif`
and compile successfully.
