### ISSUE TITLE
Configure AttoBot for MXNet.jl

### ISSUE THREAD

**Issue by pluskid** [dmlc/mxnet#4821]
Could someone with admin permission of the dmlc org help setting up the [attobot](https://github.com/attobot/attobot) for our MXNet.jl repo? It is a tool to help automating Julia package releasing. The setup should be straightforward, as stated in the [README](https://github.com/attobot/attobot). One just need to login with the dmlc managing permission and add that repo, at this URL: https://github.com/integration/attobot

**Comment by piiswrong** [comment]
done https://github.com/organizations/dmlc/settings/installations/7009

**Comment by pluskid** [comment]
Thanks!
