### ISSUE TITLE
Difficulty training RCNN on other datasets adhering to VOC format: RPNL1Loss=nan

### ISSUE THREAD

**Issue by krosaen** [dmlc/mxnet#4831]
I'm having a hard time training [RCNN](https://github.com/dmlc/mxnet/tree/master/example/rcnn) on other datasets besides VOC.

Our approach is to convert our dataset to VOC format (e.g the expected directory structure, xml files) and then map this dataset into the docker container expects the dataset to live. More details about our container and how we run it [here](https://github.com/umautobots/nn-dockerfiles/tree/master/mxnet-rcnn).

This approach works when using VOC itself, but when we pass it our dataset (which we had successfully trained a much older version of MXNet RCNN on) we immediately get `RPNL1Loss=nan`

```
num_images 10000
wrote gt roidb to /media/ngv/output/cache/voc_2012_trainval_gt_roidb.pkl
append flipped images to roidb
filtered 0 roidb entries: 20000 -> 20000
providing maximum shape [('data', (2, 3, 600, 1000)), ('gt_boxes', (2, 100, 5))] [('label', (2, 20646)), ('bbox_target', (2, 36, 37, 62)), ('bbox_weight', (2, 36, 37, 62))]
output shape
{'bbox_loss_reshape_output': (1L, 128L, 84L),
 'blockgrad0_output': (1L, 128L),
 'cls_prob_reshape_output': (1L, 128L, 21L),
 'rpn_bbox_loss_output': (2L, 36L, 35L, 62L),
 'rpn_cls_prob_output': (2L, 2L, 315L, 62L)}
lr 0.001 lr_epoch_diff [7] lr_iters [70000]
[20:38:08] src/operator/./cudnn_convolution-inl.h:55: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
/root/mxnet/example/rcnn/rcnn/processing/bbox_transform.py:71: RuntimeWarning: invalid value encountered in log
  targets_dw = np.log(gt_widths / ex_widths)
INFO:root:Epoch[0] Batch [20]	Speed: 8.09 samples/sec	Train-RPNAcc=0.741579,	RPNLogLoss=0.691406,	RPNL1Loss=nan,	RCNNAcc=0.888951,	RCNNLogLoss=0.697838,	RCNNL1Loss=0.849134,	
INFO:root:Epoch[0] Batch [40]	Speed: 7.63 samples/sec	Train-RPNAcc=0.755859,	RPNLogLoss=0.690261,	RPNL1Loss=nan,	RCNNAcc=0.923685,	RCNNLogLoss=0.466046,	RCNNL1Loss=0.664377,	
```

and the training fails to converge.

We also tried training on KITTI in voc format with the same issues.

Note that what we have been able to do is to test/evaluate a VOC trained model on the KITTI in VOC format, so that points to our conversion process being ok.

So what I'm wondering if there's anything I might look into that could make this work. It would be very convenient to be able to use the existing `PascalVOC` image database with any VOC-like dataset so as not to have to write a custom loader (as with the COCO example). 

One things we investigated: we thought that having a different number of classes could have caused the issue (our dataset only has `car` and `person` as classes). Modifying the source file and the NUM_CLASSES configuration so that it only expected these two classes didn't seem to make any difference. On further consideration, it seems like as long as the classes in the dataset are a subset of the original VOC dataset classes, it should work just fine.

If anyone has any tips or places to investigate, please advise, I will report back if we get to the bottom of the issue, as I think having a reproducible way to train and evaluate on datasets in VOC-like format would be useful to many.

**Comment by krosaen** [comment]
We traced it back to the fact that VOC has 1-based bounding box offsets leading to:

```
            # Make pixel indexes 0-based
            x1 = float(bbox.find('xmin').text) - 1
            y1 = float(bbox.find('ymin').text) - 1
            x2 = float(bbox.find('xmax').text) - 1
            y2 = float(bbox.find('ymax').text) - 1
```

subtracting 1 from an unsigned int whenever x1 or y1 is zero. After fixing our conversion script to user 1-based bounding box offsets, things are working.

Thank you rubber-ducky :)

**Comment by PCML-WangZhe** [comment]
but after you delete "-1", it will make a new problem:
INFO:root:voc_2020_trainval append flipped images to roidb
Traceback (most recent call last):
  File "/home/lab3/wz/incubator-mxnet-master/example/rcnn/train_end2end.py", line 195, in <module>
    main()
  File "/home/lab3/wz/incubator-mxnet-master/example/rcnn/train_end2end.py", line 192, in main
    lr=args.lr, lr_step=args.lr_step)
  File "/home/lab3/wz/incubator-mxnet-master/example/rcnn/train_end2end.py", line 56, in train_net
    for image_set in image_sets]
  File "/home/lab3/wz/incubator-mxnet-master/example/rcnn/rcnn/utils/load_data.py", line 30, in load_gt_roidb
    roidb = imdb.append_flipped_images(roidb)
  File "/home/lab3/wz/incubator-mxnet-master/example/rcnn/rcnn/dataset/imdb.py", line 190, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError

in these code:
    def append_flipped_images(self, roidb):
        """
        append flipped images to an roidb
        flip boxes coordinates, images will be actually flipped when loading into network
        :param roidb: [image_index]['boxes', 'gt_classes', 'gt_overlaps', 'flipped']
        :return: roidb: [image_index]['boxes', 'gt_classes', 'gt_overlaps', 'flipped']
        """
        logger.info('%s append flipped images to roidb' % self.name)
        assert self.num_images == len(roidb)
        for i in range(self.num_images):
            roi_rec = roidb[i]
            boxes = roi_rec['boxes'].copy()
            oldx1 = boxes[:, 0].copy()
            oldx2 = boxes[:, 2].copy()
            boxes[:, 0] = roi_rec['width'] - oldx2 - 1
            boxes[:, 2] = roi_rec['width'] - oldx1 - 1
            # boxes[:, 0] = roi_rec['width'] - oldx2
            # boxes[:, 2] = roi_rec['width'] - oldx1
            assert (boxes[:, 2] >= boxes[:, 0]).all()
            entry = {'image': roi_rec['image'],
                     'height': roi_rec['height'],
                     'width': roi_rec['width'],
                     'boxes': boxes,
                     'gt_classes': roidb[i]['gt_classes'],
                     'gt_overlaps': roidb[i]['gt_overlaps'],
                     'max_classes': roidb[i]['max_classes'],
                     'max_overlaps': roidb[i]['max_overlaps'],
                     'flipped': True}
            roidb.append(entry)
how to fix it?
delete "-1" as before?

**Comment by Ram124** [comment]
@PCML-WangZhe assert (boxes[:, 2] >= boxes[:, 0]).all()
add these lines before the above line

for b in range(len(boxes)):
                if boxes[b][2] < boxes[b][0]:
                    boxes[b][0]=0
