### ISSUE TITLE
Exploring the graph programmatically

### ISSUE THREAD

**Issue by jmacglashan** [dmlc/mxnet#4871]
Something I'd like to be able to do is explore the operator and variable graph from any symbol within the Python API. Such a functionality enables programmatic replication of subsets of input graphs. However, the only way I see to acquire this information in Python is the tojson method of the Symbol class, which while doable, is not necessarily an ideal format. 

It would be great if there was a python API for more directly exploring/exposing the graph structure.

**Comment by howard0su** [comment]
can u explain a bit more what feature you are trying to achieve? and what's blocking you to do it in C/C++ using nnvm api?

**Comment by jmacglashan** [comment]
I believe I could do it C/C++ since this functionality has to exist to do autodiff and graph plotting and the tojson method visible in Python, but I would like it to be part of the Python API because that's what I'm coding in for my projects.

Here is a simple example. Suppose some client code created a simple MLP:

```
data = mx.sym.Variable('data')
fc1 = mx.sym.FullyConnected(data=data, name='fc1', num_hidden=100)
act1 = mx.sym.Activation(data=fc1, name='act1', act_type='relu')
fc2 = mx.sym.FullyConnected(data=act1, name='fc2', num_hidden=10)
out = mx.sym.SoftmaxOutput(data=fc2)
```

Then we have some host code we're writing that will receive a symbol. In this case, out. What I would like to be able to do, is from that single symbol received determine what the input symbols are. If I call list_arguments() on out, what it will give me is data and the labels, because those are the variables in the graph. But I want the input symbols; that is, I want it a minimum to return me fc2 (and the internally created softmax labels symbol). And if it returns me fc2, that means I could similarly query it for its input symbols, which would return act1; and so on.

Being able to explore the symbol graph, along with reflection, facilitates programmatic adaptation of graphs. Here's one possible way I might use that. Suppose I have a non standard RNN structure (not LSTM or the usual layers). With the ability to explore the graph, I could create a function that took an arbitrary zero-time step graph with a specification of any cyclic edges and have it automatically unroll the graph to an arbitrary time horizon. But there are other things that could be done too.

**Comment by piiswrong** [comment]
This feature has been added https://github.com/dmlc/mxnet/pull/5141

**Comment by jmacglashan** [comment]
Great, thanks!
