### ISSUE TITLE
Is it possible to split an embedding layer across multiple gpus?

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#4872]
I am toying around with a matrix factorization problem where one of my embedding layers has 115 million possible input values and ~100 outputs. Obviously this causes a memory error. I saw the tutorial on how to split a model which has many layers across GPUs, but is it possible to split the embedding layer itself across multiple GPUs?

**Comment by piiswrong** [comment]
So your embedding layer weight is 115M x 100?
There are two ways you can split it: by 115M and split by 100
To split by 100, create 2 embeding layer on 2 gpus each 115M x 50.
To split by, create 2 embedding layer with 57M x 100 each and sort your input, then send higher input to 2nd gpu.

That being said. I think you are much better off putting embedding layer on CPU. Host memory is cheap after all.

You can see example/model-parallel-lstm for illustration

**Comment by piiswrong** [comment]
Updating an embedding layer like this is crazy though. I think you should do the embedding manually, then set input_needs_grad=True for module, and do sparse update manually by your self.

**Comment by jmschrei** [comment]
Okay, thanks for your suggestion. I think I've found a solution on the splitting 115M side of things.

**Comment by HaoLiuHust** [comment]
@jmschrei Could you share about how you solve this?
