### ISSUE TITLE
Platform-dependent parsing of args

### ISSUE THREAD

**Issue by sbodenstein** [dmlc/mxnet#4876]
Consider the symbol:
```
mx.symbol.SequenceMask(value="INF")
```
On OSX: this is a valid symbol, with the value correctly parsed as a float of value Inf (it seems to use `std::stof`, which supports NaN's and Inf's etc). However, on Linux, the same code produces an error
```
mxnet.base.MXNetError: Invalid Parameter format for value expect float but value='INF' in operator SequenceMast(...)
```
It would be very useful to support Inf values for the mask (for example, this allows SoftmaxActivation to act on variable length sequences. Finite masking values are never 100% safe).

@piiswrong: how would you recommend handling this, and guaranteeing the same behaviour across platforms?

**Comment by piiswrong** [comment]
I think it's a difference in stdc++ implementation in clang and gcc. You
may need to override operator<<(iostream, float)

Sebastian Bodenstein <notifications@github.com>于2017年2月3日 周五下午3:56写道：

**Comment by sbodenstein** [comment]
Yes, that is the issue. One solution for `SequenceMask` is to migrate this op to NNVM interface, and have access to `set_attr_parser` where `std::stof` can we used. First, this won't cause any problems, right? Second, is this solution preferred to overloading ops etc?

**Comment by piiswrong** [comment]
That works too.

Overriding has the benefit of fixing it for all ops. You can also specialize FieldEntry<float> and FieldEntry<double> to get the same behavior

**Comment by sbodenstein** [comment]
@piiswrong: This PR (https://github.com/dmlc/dmlc-core/pull/217) should resolve this, if it is correct. It would be great if you could have a look ASAP, as we are releasing very soon and would greatly prefer if this issue could be fixed upstream.
