### ISSUE TITLE
Compare the performace with other tools on LSTM task

### ISSUE THREAD

**Issue by pineking** [dmlc/mxnet#4878]
This link http://dlbench.comp.hkbu.edu.hk/ shows the benchmark of some DL tools.

I‘m wondering the reason for the performance on LSTM task, which is not good as MXNet does on CNN task. As @mli has said before on Weibo, one of the reason is that the kernel fusion is not implemented. 
I also found a repo about kernel fusion: https://github.com/dmlc/nnvm-fusion

Does anyone else have other comments? or then we can make the roadmap of improving the performance of LSTM task.

**Comment by piiswrong** [comment]
LSTM will be much faster after this is merged https://github.com/dmlc/mxnet/pull/4618

It's basically due to some mistakes in the lstm example (assuming the benchmark used the example code)

**Comment by pineking** [comment]
@piiswrong Great job，when could this PR be merged?

BTW, I am not sure whether the benchmark has the same mistakes in their scripts.
It seems that the commit which the benchmark is MXNet: 0.7(34b2798), perhaps it is not the latest code, and the test scripts are here:
https://github.com/hclhkbu/dlbench/tree/master/tools/mxnet/rnn

**Comment by feiyulv** [comment]
@piiswrong  Great,  but why the new lstm interface is much faster?  I can't find much difference between the new version and the old one

**Comment by piiswrong** [comment]
Perplexity used to be calculated in numpy, which is slow

**Comment by feiyulv** [comment]
Got it

**Comment by mz24cn** [comment]
老版本rnn_cell_demo.py我能跑到**1000**个samples/s，新版本lstm_bucketing.py我只能跑到**70** samples/s（把默认batch_size调整到128以便与老版本对比）。收敛速度更是慢不少。

@piiswrong 认为快很多的结论，我认为是不严谨且没有依据的。解释如下：
1，@pineking给出的测试，我看了mxnet用的测试脚本，使用的就是PTB语料，基于cuDNN RNN的Op。而新版本用的是自己Unroll出来的用symbol graph搭出来的，就是跟char-rnn.ipynb的代码实质是一样的。所以这两者没有可比性。我测试是差了十几倍，如果你CPU性能高GPU性能低，差别可能没这么大，但差几倍没问题；
2，解同志搞的这个#4618基本上就是一个refactor，没有新的东西，所以不可能比之前的unroll或者cudnn的版本快。如果要快，我这个#4819倒是真的在原来这个快的cudnn版本基础上，收敛速度更快一些，这是改进初始化方法带来的好处。但是迭代速度并没有变化，这是当然的，因为用的还是那个黑盒cudnn；
3，dlbench.comp.hkbu.edu.hk的测试用的是mxnet 0.7版本，如果用最新版0.9.3，性能会更低，应该跟引入NNVM有关（#4673 ）；
4，提升性能的正确方向，就是如题主所说的nnvm-fusion。cudnn的实质就是fusion，实际上，现在异质计算的瓶颈之一就是CPU-GPU的数据交互。如果nnvm-fusion能够做的很好，相当于一个可塑的cudnn在手，这对于别的DL来说才是真正的独家杀手级武器。不过在目前的dmlc/mxnet中并没有包含nnvm-fusion这个插件，只是在dmlc/nnvm中才有；
5，#4618只是做了一个unroll版本的重构，cudnn的初始化参数名的问题（#4819）没有涉及；因为涉及层层封装的python类抽象，我相信比原版unroll性能只会低不会高，所以这是一个对于unroll和cudnn版本的RNN性能都没有改进的PR。可能只是代码结构上看起来舒服一点了。但也只惠及python。

综上所述，nnvm-fusion才是有价值的努力方向。@tqchen @mli

**Comment by piiswrong** [comment]
We'll release numbers in a week or two.

**Comment by mz24cn** [comment]
Perplexity只是用来打印收敛情况而已，并不是用来控制网络运行的损失函数，即便没有Perplexity网络运行也照旧，不知道@piiswrong 为何得此结论“Perplexity used to be calculated in numpy, which is slow”？
