### ISSUE TITLE
Fail to make -j4 on Mac, all dependencies are installed already

### ISSUE THREAD

**Issue by yib2** [dmlc/mxnet#488]
You may see the output below when i make -j4.
 

>build/common/tblob_op_registry.d
In file included from src/common/tblob_op_registry.cc:6:
In file included from include/mxnet/ndarray.h:17:
In file included from include/mxnet/./base.h:13:
In file included from ./mshadow/mshadow/tensor.h:16:
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
In file included from src/c_api/c_predict_api.cc:9:
In file included from include/mxnet/symbolic.h:17:
In file included from include/mxnet/./base.h:13:
In file included from ./mshadow/mshadow/tensor.h:16:
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
In file included from src/c_api/c_api.cc:11:
In file included from include/mxnet/base.h:13:
In file included from ./mshadow/mshadow/tensor.h:16:
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
    #include <cblas.h>
             ^
    #include <cblas.h>
             ^
    #include <cblas.h>
             ^
In file included from src/resource.cc:8:
In file included from include/mxnet/base.h:13:
In file included from ./mshadow/mshadow/tensor.h:16:
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
    #include <cblas.h>
             ^
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make: *** [build/common/tblob_op_registry.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [build/c_api/c_predict_api.o] Error 1
make: *** [build/resource.o] Error 1
make: *** [build/c_api/c_api.o] Error 1

**Comment by piiswrong** [comment]
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
You didn't have blas or didn't set the path to it in config.mk

**Comment by tqchen** [comment]
Closing for now, please feel free to re-open, seems to be problem of not installing BLAS

**Comment by Yunrui** [comment]
Met exactly the same issue in EI Capitan. 

I installed openblas thru brew, and changed USE_BLAS = openblas. Also tried the following, but no luck. Any way to troubleshoot? 

export LIBRARY_PATH=/usr/local/Cellar/openblas/0.2.15/include/
