### ISSUE TITLE
some problem about implementing ftrl

### ISSUE THREAD

**Issue by moveforever** [dmlc/mxnet#4880]
ftrl steps are as followed in picture
![ftrl](https://cloud.githubusercontent.com/assets/5248288/22618365/480c6986-eb15-11e6-95e2-b6a1b2d3325a.png)
when update weight, there exist sign judgement, and i don't know how to assign weight through judging the sign of z
small help will welcome.

**Comment by piiswrong** [comment]
(z>0)*w

**Comment by moveforever** [comment]
@piiswrong , tks.

**Comment by moveforever** [comment]
@piiswrong , i came across a problem like this:
```
File "/data0/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/optimizer.py", line 817, in update
    weight[:] = -(z - (z>0) * self.lamda1 + (z < 0) * self.lamda1) / ((self.beta + sqrt(n))/self.alpha + self.lamda2)(z > self.lamda1) 
TypeError: 'NDArray' object is not callable
```


My implemention is as followed:
`@register
class Ftrl(Optimizer):

    def __init__(self, lamda1=0.90, lamda2=0.90, alpha=0.1, beta=0.2, epsilon=1e-5, **kwargs):
        super(Ftrl, self).__init__(**kwargs)
        self.lamda1 = lamda1
        self.lamda2 = lamda2
        self.alpha = alpha
        self.beta = beta


    def create_state(self, index, weight):
        return (zeros(weight.shape, weight.context),  # sigma
                zeros(weight.shape, weight.context),  # z
                zeros(weight.shape, weight.context))  # n

    def update(self, index, weight, grad, state):
        assert(isinstance(weight, NDArray))
        assert(isinstance(grad, NDArray))
        wd = self._get_wd(index)
        self._update_count(index)

        # preprocess grad
        grad *= self.rescale_grad
        if self.clip_gradient is not None:
            grad = clip(grad, -self.clip_gradient, self.clip_gradient)

        # accumulated g and delta initlization
        sigma, z, n = state


        #update sigma, z, n
        sigma[:] = (sqrt(n + grad) -sqrt(n)) / self.alpha
        z[:] += grad - sigma * weight * wd
        n[:] += grad * grad

        # update weight
        weight[:] = -(z - (z>0) * self.lamda1 + (z < 0) * self.lamda1) / ((self.beta + sqrt(n))/self.alpha + self.lamda2)(z > self.lamda1)`

**Comment by piiswrong** [comment]
you are missing a *
zheng <notifications@github.com>于2017年2月5日 周日下午8:00写道：

**Comment by moveforever** [comment]
yeah, it is.

another problem:  when use operation z>0(type of z is ndarray), type of the result is  True or False, it's not ndarray type.
```
  File "/data0/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/optimizer.py", line 818, in update
    print "operation of sign z ", ((z>0) * self.lamda1 + (z < 0) * self.lamda1).asnumpy(), "grad = ", z.asnumpy()
AttributeError: 'int' object has no attribute 'asnumpy'
```
so it seems it is not element-sign judgement. Is there other solutions? @piiswrong

**Comment by moveforever** [comment]
The last two question:
1.  i know it need reload ndarray ‘>’ operation, where to implement
2.  i want to use u = (z.asnumpy()>0)*alpha + (z.asnumpy()<0)*beta, how to transform type numpy about u into ndarray.
tks, @piiswrong

**Comment by moveforever** [comment]
question 2 is solved as followed:
```
weight[:] = -(z - array((z.asnumpy() > 0) * self.lamda1 + (z.asnumpy() <= 0) * self.lamda1 * (-1))) / ((self.beta + sqrt(n))/self.alpha + self.lamda2) * array(abs(z).asnumpy() > self.lamda1)
```
The remaining questions are question 1 above. 
tks, @piiswrong

**Comment by moveforever** [comment]
i have seen ndarray support more operation, so i reimplement ftrl aglorithm, and code is https://github.com/moveforever/mxnet-project/blob/master/src/ftrl.py,
@piiswrong  can i merge ftrl into mxnet master?

**Comment by piiswrong** [comment]
yes. please submit a pr

zhongyi zheng <notifications@github.com>于2017年4月12日 周三下午9:08写道：
