### ISSUE TITLE
ImportError: cannot import name rnn

### ISSUE THREAD

**Issue by Techro-Raj** [dmlc/mxnet#4883]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: macOS Sierra

Compiler: Apple LLVM version 8.0.0 (clang-800.0.42.1)

Package used (Python/R/Scala/Julia): Python

## Error Message:
After running my program I get this error:
```Traceback (most recent call last):
  File "neuralnet.py", line 1, in <module>
    import mxnet as mx
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mxnet-0.9.3-py2.7-macosx-10.6-intel.egg/mxnet/__init__.py", line 58, in <module>
    from . import rnn
ImportError: cannot import name rnn
```

## Steps to reproduce

1. $`git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive`
2. $`cd ~/mxnet/setup-utils`
3. $`bash install-mxnet-osx-python.sh`

After running the steps, I know I installed mxnet because of the output: 
`SUCCESS: MXNet test passed`
`SUCCESS: MXNet is successfully installed and works fine!`

Any ideas what I'm doing wrong/missing? Thanks!

**Comment by fhieber** [comment]
Same problem for me with latest commit.

**Comment by piiswrong** [comment]
Should be fixed https://github.com/dmlc/mxnet/commit/90a0327dce08b7efbd7a5b6b60f10a4a16994098

**Comment by Techro-Raj** [comment]
I reinstalled it and it works now. @piiswrong Thank you!
