### ISSUE TITLE
prediction service

### ISSUE THREAD

**Issue by mli** [dmlc/mxnet#489]
we already have several pre-trained models achieving the state-of-the-art performance, it would be nice we can make an online service so that users can have a quick look. an example is

http://www.clarifai.com/#demo

making a simple service should be easy:

- the service is able to accept POST request. using any language should be fine. for example, we can use http://docs.cherrypy.org/ if using python. to easy the deployment, we can pack things into docker
- a html client should be fine at this moment, once a user click a submit button, it issues a POST request to the server, and then display the results. the results can be in a json format.

i will start to work on it at end of this week if nobody is planed to do a similar thing.

**Comment by piiswrong** [comment]
do we have a server ready?
Maybe we can also use it to host pretrained model files?

**Comment by mli** [comment]
either renting ec2 instances or finding one at cmu works for me. machine resource is not a problem

**Comment by mli** [comment]
but i'm not sure to use that to hosts pretrained models. github might be more stable, but lfs is definitely not the solution, it's too expensive...

**Comment by piiswrong** [comment]
Is ec2 practical for hosting 50~500MB files for download?
A model zoo would really be nice.

**Comment by winstywang** [comment]
I have a VPS can be used to host models.

**Comment by mli** [comment]
then s3 could be cheaper and easier. at most $0.03 / GB vs $.1 / GB for LFS

https://aws.amazon.com/s3/pricing/

**Comment by mli** [comment]
@winstywang do you need to pay the bandwidth for VPS?

**Comment by winstywang** [comment]
@mli No need. But I remember it has CPU limit. It is the standard bluehost service.

**Comment by mli** [comment]
@winstywang thanks. but let's use lfs at this moment, since it's stable and easier to use. we may switch to s3 later since i'm going to apply an aws gif grant.

**Comment by futurely** [comment]
Cherrypy is only suitable for very small projects. Flask is a much more powerful and popular light weight web framework. Uber developed its RESTful web service framework [Clay](https://github.com/uber/clay) based on Flask. The [hello world example](http://clayframework.com/) is extremely simple.
```python
from __future__ import absolute_import
from clay import app

@app.route('/', methods=['GET'])
def hello():
    '''
    Ensures that the world is still there.
    '''
    return 'Hello World!'
```

Alibaba's cloud computing service [Aliyun](http://www.aliyun.com/) is offering price-off promotions right now as a part of the 11.11 global shopping festival.

**Comment by formath** [comment]
@mli Is there any java examples loading model trained using other languages and doing prediction?
