### ISSUE TITLE
cannot install latest (20170206) gpu version r package on windows 10

### ISSUE THREAD

**Issue by mangos47** [dmlc/mxnet#4896]
Hi,

I tried to install the latest gpu version of mxnet r package on my windows machine but encounter some problems.

First, the instruction on the website (http://mxnet.io/get_started/windows_setup.html) doesn't match with actual downloaded package. For one, the link to "the most recent GPU-enabled MXNet package from the Releases tab" doesn't contain what is said to be there, but rather provide to another location (https://github.com/yajiedesign/mxnet/releases), which does provide nightly windows release. however, the release doesn't follow same folder structure as indicated by the installation instruction.

Second, there is no NAMESPACE file in the latest release package, which produces an error when try to install from source. I tried copy NAMESPACE from an older version (20161125), after which the installation produce the current error as listed below.

Another question: the installation instruction mention having MS visual studio 2013 as a pre-requisite. But the actual installation for R section doesn't mention when it is used, since the library is pre-built (.dll). what is MS VS 2013 required for here? also does it must be 2013? can I use 2015?

In general, I feel the installation manual section requires some major update, at least for R GPU version. For example, I'm now using an older version (20161125) which installs ok after some tweaking, and runs a few of the examples fine. But to make it work, I also have to resort to some manual tweaking, in particular, find out the correct .dll dependency and manually put the correct ones in place (mostly the correct cuda libraries)

Please help!
Thank you!

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
windows 10 Pro x64
Compiler:
Rtools 3.4
Package used (Python/R/Scala/Julia):
R 3.3.2, Rstudio 1.0.136
MXNet version:

Or if installed from source:
installed from source (prepared as instructed in http://mxnet.io/get_started/windows_setup.html)
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252    LC_MONETARY=English_Singapore.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Singapore.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2
## Error Message:
Please paste the full error message, including stack trace.
* installing *source* package 'mxnet' ...
** libs
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.2/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c executor.cc -o executor.o
In file included from ./executor.h:13:0,
                 from executor.cc:10:
././symbol.h:11:24: fatal error: nnvm/c_api.h: No such file or directory
 #include <nnvm/c_api.h>
                        ^
compilation terminated.
make: *** [executor.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mxnet.dll" WIN=64 TCLBIN=64 OBJECTS="executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o"' had status 2
ERROR: compilation failed for package 'mxnet'
* removing 'C:/Users/admin/Documents/R/win-library/3.3/mxnet'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL --no-multiarch -l "C:\Users\admin\Documents\R\win-library\3.3" "c:/users/admin/Downloads/mxnet/mxnet-master20170206/R-package/"' had status 1
Warning in install.packages :
  installation of package 慶:/users/admin/Downloads/mxnet/mxnet-master20170206/R-package/?had non-zero exit status
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by mangos47** [comment]
The previous error was that it cannot find 'nnvm/c_api.h'
So I tried two things: First is to comment out this include line in 'ndarry.h' and 'symbol.h'. Second is to manually create a fold 'nnvm' next to 'mxnet' in the 'R-package\inst\include' folder and copy c_api.h over.
Both method will now lead to the following error when I tried to install in R from source:

* installing *source* package 'mxnet' ...
** libs
c:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-33~1.2/include" -DNDEBUG -I../inst/include   -I"C:/Users/admin/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c executor.cc -o executor.o
In file included from executor.cc:9:0:
./base.h: In function 'std::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
In file included from ./executor.h:13:0,
                 from executor.cc:10:
././symbol.h: At global scope:
././symbol.h:187:36: error: expected ')' before 'handle'
   explicit SymbolFunction(OpHandle handle, std::string name);
                                    ^
././symbol.h:189:3: error: 'OpHandle' does not name a type
   OpHandle handle_;
   ^
In file included from executor.cc:11:0:
./ndarray.h:244:10: error: 'OpHandle' does not name a type
   static OpHandle FindHandle(const std::string& hname);
          ^
./ndarray.h:248:37: error: expected ')' before 'handle'
   explicit NDArrayFunction(OpHandle handle, std::string name);
                                     ^
./ndarray.h:250:3: error: 'OpHandle' does not name a type
   OpHandle handle_;
   ^
executor.cc: In static member function 'static void mxnet::R::Executor::UpdateArray(const char*, const List&, Rcpp::List*, bool, bool)':
executor.cc:43:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < from.size(); ++i) {
                          ^
executor.cc: In static member function 'static Rcpp::List mxnet::R::Executor::CloneArray(const List&)':
executor.cc:87:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < src.size(); ++i) {
                        ^
executor.cc: In function 'Rcpp::List* mxnet::R::CreateArrayList(const List&, const string&, const std::vector<std::basic_string<char> >&, const RObjectType&, std::vector<void*>*)':
executor.cc:123:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < source_array.size(); ++i) {
                          ^
executor.cc: In function 'Rcpp::List* mxnet::R::CreateGradList(const List&, const List&, const std::vector<std::basic_string<char> >&, const RObjectType&, std::vector<void*>*, std::vector<unsigned int>*)':
executor.cc:155:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < grad_reqs.size(); ++i) {
                          ^
make: *** [executor.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mxnet.dll" WIN=64 TCLBIN=64 OBJECTS="executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o"' had status 2
ERROR: compilation failed for package 'mxnet'
* removing 'C:/Users/admin/Documents/R/win-library/3.3/mxnet'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL --no-multiarch -l "C:\Users\admin\Documents\R\win-library\3.3" "c:/users/admin/Downloads/mxnet/mxnet-master20170206/R-package/"' had status 1
Warning in install.packages :
  installation of package 慶:/users/admin/Downloads/mxnet/mxnet-master20170206/R-package/?had non-zero exit status

please help!
Thanks!

**Comment by mangos47** [comment]
I made another attempt to try to install gpu version mxnet in r.

I downloaded the latest repo from https://github.com/dmlc/mxnet, latest windows build from https://github.com/yajiedesign/mxnet/releases. I then prepared the folders as instructed by http://mxnet.io/get_started/windows_setup.html. Then I run install.packages() from Rstudio.

This time it appears to be building ok, but then it produce the following error about DiagrammeR:
installing to C:/Users/admin/Documents/R/win-library/3.3/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'DiagrammeR' 0.8.1 is being loaded, but >= 0.9.0 is required
ERROR: lazy loading failed for package 'mxnet'
* removing 'C:/Users/admin/Documents/R/win-library/3.3/mxnet'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL --no-multiarch -l "C:\Users\admin\Documents\R\win-library\3.3" "c:/users/admin/Downloads/mxnet/mxnet-master20170208/R-package/"' had status 1
Warning in install.packages :
  installation of package 慶:/users/admin/Downloads/mxnet/mxnet-master20170208/R-package/?had non-zero exit status

So I remove DiagrammeR 0.8.1 and install the latest 0.9. Then when I tried to install, it produce this error:
* installing *source* package 'mxnet' ...
** libs
make: Nothing to be done for `all'.
installing to C:/Users/admin/Documents/R/win-library/3.3/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
Error : object 'combine_edges' is not exported by 'namespace:DiagrammeR'
ERROR: lazy loading failed for package 'mxnet'
* removing 'C:/Users/admin/Documents/R/win-library/3.3/mxnet'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL --no-multiarch -l "C:\Users\admin\Documents\R\win-library\3.3" "c:/users/admin/Downloads/mxnet/mxnet-master20170208/R-package/"' had status 1
Warning in install.packages :
  installation of package 慶:/users/admin/Downloads/mxnet/mxnet-master20170208/R-package/?had non-zero exit status

which is the known issue that can be solved by downgrade DiagrammeR to 0.8.1. So I'm stuck.

sessionInfo():
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Singapore.1252  LC_CTYPE=English_Singapore.1252    LC_MONETARY=English_Singapore.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Singapore.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.2

Please help!
Thanks!

**Comment by thirdwing** [comment]
Please follow my instruction from https://gist.github.com/thirdwing/89aa9bfc588ade138496e6932072152c

The installation has been test on a Windows Server machine with GPU. It will be merged into the documents later.
