### ISSUE TITLE
dlopen failed: cannot locate symbol "cblas_sgemm" referenced by "libmxnet_predict.so"...

### ISSUE THREAD

**Issue by nihilityworld** [dmlc/mxnet#4902]
Operating System:ANDROID
Compiler:ANDROID NDKr13 using api 21(also 19)
I tried to build the mxnet to android using 'make  ANDROID=1' and finally get the 'libmxnet_predict.so'. But when I tried to use it in an android project, it coulde not run  throw this EXCEPTION: `'java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "cblas_sgemm" referenced by "libmxnet_predict.so"...'.`
How can I solve this problem? Did I make some mistakes in compiling?
MXNet version:
I have tried the newest vision and the 0.8.0 vision, and all got that EXCEPTION.

**Comment by nihilityworld** [comment]
Can anyone help me compiling the android Library or give me the library directly?

**Comment by zhenglaizhang** [comment]
Hi, i think i may meet with the same issue with you, have you found the root cause for the issue? thanks in advance!
