### ISSUE TITLE
 OSError:mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: ATL_ssyreflect

### ISSUE THREAD

**Issue by wsstriving** [dmlc/mxnet#4922]
> I installed the latest mxnet following http://mxnet.io/get_started/ubuntu_setup.html,  I compiled mxnet with atlas and there is no compilation error, and libmxnet.so was generated. Then I executed `python setup.py install --user` in the python directory, when I wanted to import mxnet, the error was reported

 OSError:mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: ATL_ssyreflect

## I have tried
1. make clean_all and make again
2. remove the whole directory and git clone a new one

Thanks

**Comment by piiswrong** [comment]
try openblas instead of atlas

**Comment by wsstriving** [comment]
I also tried openblas, a similar error was reported,
Finally mkl works.

Thanks!
