### ISSUE TITLE
CMake on Windows 10

### ISSUE THREAD

**Issue by xmuhcd** [dmlc/mxnet#494]
Hi, I downloaded the MXNet Source, and tried to build it on Windows 10 using VS 2015. I first use CMake GUI to load the source folder, then press configure(I know I need to set the third-party path, I have CUDA 7.5, CUDNN v3, and OpenBlas). But i got the following errors:

CMake Error at CMakeLists.txt:16 (include):
  include could not find load file:

    mshadow/cmake/mshadow.cmake

CMake Error at CMakeLists.txt:17 (include):
  include could not find load file:

    mshadow/cmake/Utils.cmake

CMake Error at CMakeLists.txt:18 (include):
  include could not find load file:

    mshadow/cmake/Cuda.cmake

CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CUDA: Found unsuitable version "7.5", but required is exact
  version "6.0" (found C:/Program Files/NVIDIA GPU Computing
  Toolkit/CUDA/v7.5)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:372 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindCUDA.cmake:845 (find_package_handle_standard_args)
  E:/OpenCV249/OpenCVConfig.cmake:215 (find_package)
  CMakeLists.txt:39 (find_package)

PS: It seems something is missing. Any idea?

**Comment by hjk41** [comment]
You need those submodules like mshadow, ps-lite and dmlc-core.

It is suggested that you use git to get the code (git clone --recursive
https://github.com/dmlc/mxnet), github download does not handle submodules
properly.

Or you can also try to download the submodules yourself. They are located
under github.com/dmlc/

On Thu, Nov 5, 2015 at 3:08 PM, Chunde <notifications@github.com> wrote:

> Hi, I downloaded the MXNet Source, and tried to build it on Windows 10
> using VS 2015. I first use CMake GUI to load the source folder, then press
> configure(I know I need to set the third-party path, I have CUDA 7.5, CUDNN
> v3, and OpenBlas). But i got the following errors:
>
> CMake Error at CMakeLists.txt:16 (include):
> include could not find load file:
>
> mshadow/cmake/mshadow.cmake
>
> CMake Error at CMakeLists.txt:17 (include):
> include could not find load file:
>
> mshadow/cmake/Utils.cmake
>
> CMake Error at CMakeLists.txt:18 (include):
> include could not find load file:
>
> mshadow/cmake/Cuda.cmake
>
> CMake Error at C:/Program Files
> (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138
> (message):
> Could NOT find CUDA: Found unsuitable version "7.5", but required is exact
> version "6.0" (found C:/Program Files/NVIDIA GPU Computing
> Toolkit/CUDA/v7.5)
> Call Stack (most recent call first):
> C:/Program Files
> (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:372
> (_FPHSA_FAILURE_MESSAGE)
> C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindCUDA.cmake:845
> (find_package_handle_standard_args)
> E:/OpenCV249/OpenCVConfig.cmake:215 (find_package)
> CMakeLists.txt:39 (find_package)
>
> PS: It seems something is missing. Any idea?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/494>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
Also, if you don't plan to modify mxnet itself, I suggest you download the
binary releases directly: https://github.com/dmlc/mxnet/releases

On Thu, Nov 5, 2015 at 3:19 PM, Chuntao HONG <chuntao.hong@gmail.com> wrote:

> You need those submodules like mshadow, ps-lite and dmlc-core.
>
> It is suggested that you use git to get the code (git clone --recursive
> https://github.com/dmlc/mxnet), github download does not handle
> submodules properly.
>
> Or you can also try to download the submodules yourself. They are located
> under github.com/dmlc/
>
> On Thu, Nov 5, 2015 at 3:08 PM, Chunde <notifications@github.com> wrote:
>
>> Hi, I downloaded the MXNet Source, and tried to build it on Windows 10
>> using VS 2015. I first use CMake GUI to load the source folder, then press
>> configure(I know I need to set the third-party path, I have CUDA 7.5, CUDNN
>> v3, and OpenBlas). But i got the following errors:
>>
>> CMake Error at CMakeLists.txt:16 (include):
>> include could not find load file:
>>
>> mshadow/cmake/mshadow.cmake
>>
>> CMake Error at CMakeLists.txt:17 (include):
>> include could not find load file:
>>
>> mshadow/cmake/Utils.cmake
>>
>> CMake Error at CMakeLists.txt:18 (include):
>> include could not find load file:
>>
>> mshadow/cmake/Cuda.cmake
>>
>> CMake Error at C:/Program Files
>> (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138
>> (message):
>> Could NOT find CUDA: Found unsuitable version "7.5", but required is exact
>> version "6.0" (found C:/Program Files/NVIDIA GPU Computing
>> Toolkit/CUDA/v7.5)
>> Call Stack (most recent call first):
>> C:/Program Files
>> (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:372
>> (_FPHSA_FAILURE_MESSAGE)
>> C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindCUDA.cmake:845
>> (find_package_handle_standard_args)
>> E:/OpenCV249/OpenCVConfig.cmake:215 (find_package)
>> CMakeLists.txt:39 (find_package)
>>
>> PS: It seems something is missing. Any idea?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dmlc/mxnet/issues/494>.
>>
>
>
>
> --
> HONG Chuntao
> System Research Group
> Microsoft Research Asia
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by xmuhcd** [comment]
Hello Chuntao,

Many thanks, 
I see the problem now. Actually I am interested by the project, so I would like to read through the code, and try to test it with the source code running on VS.

**Comment by yajiedesign** [comment]
if you want use cuda,must use vs2013,the cuda 7.5 not support 2015.

**Comment by xmuhcd** [comment]
Hi yajie, I know, when I compiled using VS 2015, it pops out some errors, so I use VS 2013, everything now seems good. Thanks!

**Comment by lsvigorous** [comment]
@xmuhcd, do you successfully enable USE_DIST_KVSTORE on windows ? I met several error due to the dependency in ps-lite, basically protobuf, gflags, glog.
@tqchen, do we have a doc on the ps-lite also ?

Thanks.

**Comment by xmuhcd** [comment]
@Isvigorous, I didn't notice that symbol, just use all default setting. So I'm not sure about that.

Best regards

**Comment by yajiedesign** [comment]
@lsvigorous i am send pr fix promble https://github.com/dmlc/ps-lite/pull/25

**Comment by lsvigorous** [comment]
@yajiedesign, I met no problem with USE_DIST_KVSTORE disabled, will try your solution.

**Comment by bcd33bcd** [comment]
@xmuhcd do you succeed in config mxnet on windows? I across a problem with use https://github.com/dmlc/mxnet/releases GPU version.
![image](https://cloud.githubusercontent.com/assets/8981954/11654655/6694a688-9de2-11e5-9f5b-4515a281bfe0.png)

**Comment by xmuhcd** [comment]
@bcd33bcd I did it successfully. However, I am using VS 2013, it not works for 2015.

**Comment by bcd33bcd** [comment]
@xmuhcd I have used VS2013 either. And I considerd may be my lib/dll files broken.Could you send me libmxnet.dll/libmxnet.lib from email?

**Comment by xmuhcd** [comment]
@bcd33bcd Sure, I can send the entire project to you tonight. I am now working at school.

**Comment by bcd33bcd** [comment]
@xmuhcd thank you very much.Please sent it to bcd33bcd@126.com .

**Comment by Trangle** [comment]
@bcd33bcd the similar error with you, do you solve it now?
