### ISSUE TITLE
R package: poor NAMESPACE & missing help pages

### ISSUE THREAD

**Issue by UBod** [dmlc/mxnet#4940]
I downloaded and compiled mxnet 0.9.4 with GPU support on a server running CentOS 7 and built and installed the R package. The package loads fine and it seems it also works, but there are some changes compared to earlier versions, and they don't seem right or at least strange to me:

- The NAMESPACE file only consists of two simple imports, but lacks all exports, which requires me to prefix all calls into the package with 'mxnet:::'. This is not only inconvenient, it also makes all my previous code (and all mxnet tutorials) invalid.

- All help pages are gone. I understand that the vignettes and online tutorials still provide a lot of information, but they never cover all arguments of all R functions, so it would be really great if there was some quick reference.

I do not know whether the two points mentioned above are errors or intended. In any case, I am curious about the background.

Thanks in advance, U

--

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Linux (CentOS 7)

Package used (Python/R/Scala/Julia): R

MXNet version: 0.9.4

If you are using R package, please provide

R `sessionInfo()`:
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu/x86_64 (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mxnet_0.9.4

loaded via a namespace (and not attached):
[1] tools_3.3.0      Rcpp_0.12.9      codetools_0.2-14

**Comment by thirdwing** [comment]
Hi, you met this "error" because the R package uses a two-step installation method.

See https://github.com/dmlc/mxnet/blob/master/Makefile#L299-L306

The NAMESPACE with two lines of code is the minimal package. After install it, you need to export all methods by `require(mxnet); mxnet:::mxnet.export("R-package")`.

Then help files can be generated by `require(roxygen2); roxygen2::roxygenise("R-package")`.

**Comment by UBod** [comment]
Thanks for your quick and helpful response! Sorry, that way my fault. I forgot that I took a shortcut because of an issue specific to my platform that I reported earlier (https://github.com/dmlc/mxnet/issues/1491). As said, my fault. I created the symbolic link as noted in my reply to the other issue, re-ran the Makefile and now it works excellently!
