### ISSUE TITLE
Can't download the VGG16 Model from Mxnet model zoo

### ISSUE THREAD

**Issue by lilhope** [dmlc/mxnet#4943]
Hi,  I am trying to download the VGG16 Model from http://data.dmlc.ml/mxnet/models/imagenet/ .But I can't find the VGG16 model in the imagenet folder. I use the command `wget http://data.dmlc.ml/mxnet/models/imagenet/vgg/vgg16.tar.gz` ,It gives a 404 ERROR.

**Comment by geniusgeek** [comment]
you can get the pretrained models from http://data.dmlc.ml/mxnet/models/imagenet/vgg/
and source from https://github.com/geniusgeek/deep-learning-models 
you can get the weights from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_th_dim_ordering_th_kernels.h5 or browse through the internet

**Comment by lilhope** [comment]
@geniusgeek , the first link was not available.

**Comment by VoVAllen** [comment]
Please refer to this...... I don't know why it doesn't work. @mli 
https://github.com/dmlc/mxnet/issues/4750

**Comment by lilhope** [comment]
@VoVAllen It works now

**Comment by lincolnBush** [comment]
The problem occurred again....The files cannot be downloaded now.

**Comment by lilhope** [comment]
@lincolnBush I've download the model, I can send it to you if you don't mind to leave you e-mail.

**Comment by VoVAllen** [comment]
Try to bind 54.208.175.7 with data.dmlc.ml in hosts

I'm not sure whether this could work or not
