### ISSUE TITLE
Upload the usable Android library libmxnet_predict.so please!!!

### ISSUE THREAD

**Issue by nihilityworld** [dmlc/mxnet#4945]
Is there anyone have an usable android library which mxnet vision is after v0.8.0?
I have tried compile the  amalgamation many times, but it broken when using in Android app.

**Comment by piiswrong** [comment]
@xlvector

**Comment by xlvector** [comment]
You can send me an email xlvector#gmail.com, and I can send one to you.

**Comment by nihilityworld** [comment]
@xlvector, do you receive my e-mail? My e-mail address is 980078316@qq.com

**Comment by xlvector** [comment]
@nihilityworld  sent!

**Comment by piiswrong** [comment]
could you submit it to dmlc/webdata and post the link here?

Xiang Liang <notifications@github.com>于2017年2月13日 周一上午1:11写道：

**Comment by xlvector** [comment]
OK, I will do it this weekend.
