### ISSUE TITLE
user defined activation function

### ISSUE THREAD

**Issue by ferodia** [dmlc/mxnet#495]
Hello,
I would like to build RBF neural network using mxnet, but the gaussian activation function is not available (there are only sigmoid, relu and tanh)
could you please tell me how and where can I add it ?

Thanks!

**Comment by piiswrong** [comment]
Hi,
If you want the best GPU performance, you can add an operator under src/operator. activation-inl.h would be a good example.
If you just want a quick hack, you can try NumpyOp. Please see example/numpy-ops/numpy_softmax.py

If you managed to create an operator or a working RBF model, you are welcome to contribute to MXNET. Please consider put you work under example and submit a PR.

Thanks
