### ISSUE TITLE
How to create a symbol with multiple output?

### ISSUE THREAD

**Issue by lincolnBush** [dmlc/mxnet#4957]
I wanted to slice a image into 2 parts and feed them to different operations, to do this, I have to create a symbol with multiple output but cannot find any examples about it? Is there are anyone know about this? Thank you very much.

**Comment by lincolnBush** [comment]
This seems to be different from the multi-label classification or regression problem as it needs to slice the images into 2 different parts at the beginning

**Comment by VoVAllen** [comment]
mx.sym.Group

**Comment by Godricly** [comment]
There is a [slicechannel](http://mxnet.io/api/python/symbol.html#mxnet.symbol.SliceChannel) operator in mxnet. It can slice the tensor evenly alone the axis. You can find it in [lstm example]( https://github.com/dmlc/mxnet/blob/master/example/rnn/old/lstm.py#L71).

**Comment by lincolnBush** [comment]
Thank you very much all
