### ISSUE TITLE
LIBTIFF_4.0 link errors

### ISSUE THREAD

**Issue by chuan92** [dmlc/mxnet#496]
my os is **ubuntu15.04** and I install opencv via **'sudo apt-get install libopencv-dev'**.
However, during the make process of mxnet, I got the following error.

*/usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4: undefined reference to'TIFFIsTiled@LIBTIFF_4.0'* 
*/usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4: undefined reference to'TIFFOpen@LIBTIFF_4.0'*

...

It seems that opencv needs libtiff4, but the official repositories only provide libtiff5. Should I re-install opencv or re-install libtiff4 from source? Or there's another solution?

Thanks.

**Comment by piiswrong** [comment]
you can try remove opencv and install from source

**Comment by pluskid** [comment]
Feel free to re-open if the issue is still not resolved.
