### ISSUE TITLE
Variable batch size 

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#4960]
Hi, can we have some feature supporting varaible batch size? When doing lstm validation, I need to fill those buckets with duplicated examples if the number of example is not enough.
Alough I can bypass this issue by flating each bucket data with speical designed bucket key, is there any more elegant solution?

**Comment by piiswrong** [comment]
you can use Module.reshape

**Comment by Godricly** [comment]
any example or doc about this?

**Comment by thomelane** [comment]
Some related discussions can be found in https://github.com/apache/incubator-mxnet/issues/2294.

And a good example can be found in the [Faster RCNN example](https://github.com/apache/incubator-mxnet/tree/master/example/rcnn), where a [`MutableModule`](https://github.com/apache/incubator-mxnet/blob/master/example/rcnn/rcnn/core/module.py#L30) is defined which supports variable input data.

**Comment by thomelane** [comment]
Also with the Gluon API, `Block`s support variable batch sizes out of the box.
