### ISSUE TITLE
multiple GPU support?

### ISSUE THREAD

**Issue by ZhangAustin** [dmlc/mxnet#498]
Does mxnet support multiple GPUs for DNN/LSTM parallel training? How?

In terms of speed/efficiency, how does the "parameter server" parallelzation, comparing to the "asynchronized sgd"?

**Comment by antinucleon** [comment]
MXNet support not only multiple GPU but also multi-machine.

For Feedforward network, there is high-level API which is described here:
https://mxnet.readthedocs.org/en/latest/python/model.html#use-multiple-devices
For LSTM, we currently make the example by using low level API. To run on
multi-device, you need to add key value API which is hidden in high level
feed forward model API.
For Speed, you can take this benchmark for reference:
https://github.com/dmlc/mxnet/tree/master/tests/python/multi-node

**Comment by tqchen** [comment]
ps or kvstore is a ***system abstraction*** to implement the parallel learning ***algorithms***. On single node multi GPU, the algorithm is synchronized SGD. While distributed version support both sync and async algorithms

**Comment by lsvigorous** [comment]
is windows version of multi-machine supported now ?

**Comment by antinucleon** [comment]
Yes,

**Comment by tqchen** [comment]
https://mxnet.readthedocs.org/en/latest/distributed_training.html
