### ISSUE TITLE
why can't change the name of input variable "data" and label variable "softmax_label"? 

### ISSUE THREAD

**Issue by Pinnh** [dmlc/mxnet#4980]
when I attempt to change the name of variable 
from x = mx.sym.Variable('data') to x = mx.sym.Variable('dat')
some errors ocur,as below:

ValueError: Unknown initialization pattern for dat. Default initialization is now limited to "weight", "bias", "gamma" (1.0), and "beta" (0.0).Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern

**Comment by piiswrong** [comment]
You need to also change data_names and label_names in module

**Comment by Pinnh** [comment]
ok, it works， thanks~
in order to help other people，i list changes below:
model=mx.module.Module(symbol = net)
change to:
model=mx.module.Module(symbol = net,data_names=["dat"])
