### ISSUE TITLE
New issue with MXNet after installing Anaconda

### ISSUE THREAD

**Issue by Techro-Raj** [dmlc/mxnet#4981]
## Environment info

Operating System: macOS Sierra

Compiler: Apple LLVM version 8.0.0 (clang-800.0.42.1)

Package used (Python/R/Scala/Julia): Python

## Error
After I installed Anaconda, MXNet is no longer recognized in my programs. I get the error: ImportError: No module named mxnet

Is there a workaround? Because I really need Anaconda.

**Comment by piiswrong** [comment]
anaconda maintains its own packages. You need to reinstall mxnet to anaconda python

**Comment by Techro-Raj** [comment]
@piiswrong How do I do that?

**Comment by piiswrong** [comment]
how did you install mxnet the first time? Just do it again
