### ISSUE TITLE
There is no explicit api for operations

### ISSUE THREAD

**Issue by Pinnh** [dmlc/mxnet#4982]
Can you provide explicit api for operations?I know the mxnet operations' api are automatically generate by code and has the document of operations，but as a developer, api can't provide the params and the meaning of params,every time people write a operation  which not saw before should to view official site document,this seems a trivial thing, also they look like compile errors.

operations like: mx.sym.Convolution

this is also a suggestion.
thanks.

**Comment by piiswrong** [comment]
Document is here http://mxnet.io/api/python/symbol.html#mxnet.symbol.Convolution
You can also view it by help(mxnet.symbol.Convolution)

Exactly what change are you proposing?

**Comment by Pinnh** [comment]
Yes,directly view annotations in IDE while not in document may better, it is the future change we hope for
