### ISSUE TITLE
R Installation fails

### ISSUE THREAD

**Issue by mg64ve** [dmlc/mxnet#4987]
I have just tried to install the R package and I am getting:

From R Studio:

`
> install.packages("mxnet")
Installing package into ‘/home/marco/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
--2017-02-12 11:25:47--  https://dmlc.github.io/drat/src/contrib/mxnet_0.9.4.tar.gz
Resolving dmlc.github.io (dmlc.github.io)... 151.101.112.133
Connecting to dmlc.github.io (dmlc.github.io)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://dmlc.ml/drat/src/contrib/mxnet_0.9.4.tar.gz [following]
--2017-02-12 11:25:47--  http://dmlc.ml/drat/src/contrib/mxnet_0.9.4.tar.gz
Resolving dmlc.ml (dmlc.ml)... 192.30.252.153, 192.30.252.154
Connecting to dmlc.ml (dmlc.ml)|192.30.252.153|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-02-12 11:25:47 ERROR 404: Not Found.
`

From R console:

`
> install.packages("mxnet")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://dmlc.github.io/drat/src/contrib/mxnet_0.9.4.tar.gz'
Content type 'text/html' length 178 bytes
=================================================================================
downloaded 9340 bytes
Error in getOctD(x, offset, len) : invalid octal digit
The downloaded source packages are in
	/tmp/RtmpauR432/downloaded_packages
Warning message:
In install.packages("mxnet") :
  installation of package ‘mxnet’ had non-zero exit status
`

My system is:

`
Linux Mint 18.1 Serena \n \l
Linux inspiron 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

R version is:

`
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18.1
locale:
LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=de_CH.UTF-8       LC_NAME=C                 
LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
drat_0.1.2  tools_3.2.3
SysInfo:
sysname                                      release 
"Linux"                           "4.4.0-53-generic" 
version                                     nodename 
74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016                                   "inspiron" 
machine                                        login 
"x86_64"                                    "unknown" 
user                               effective_user 
"marco"                                      "marco" 
R Version:
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          2.3                         
year           2015                        
month          12                          
day            10                          
svn rev        69752                       
language       R                           
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree       
`

Is the problem the download of the package?
Thanks.
Regards.

**Comment by thirdwing** [comment]
As we have said in the document, the drat is for OSX and Windows users.

You need to compile from source on Linux.

**Comment by littletree-github** [comment]
The problem is https://dmlc.github.io/drat/src/contrib/mxnet_0.9.4.tar.gz returns 404 Not Found
Can someone fix the download link?
The exact same problem also happens on Max OS X El Captain because the source tar ball can not be downloaded.

**Comment by thirdwing** [comment]
This is really expected. We only provide the **binary** package for OSX and Windows.

You met this error because you changed the default option for `install.packages` in R. This can be changed during the unofficial distributions, like `brew`. Many OSX users don't know this.

You need to set `type` to be `binary`, which is the default value by the R-core team.

```
install.packages("mxnet", repos="http://dmlc.ml/drat/", type="binary")
```

**Comment by littletree-github** [comment]
thank you @thirdwing however, I still got error with your command:
```
> install.packages("mxnet", repos="http://dmlc.ml/drat/", type="binary")
Error in install.packages("mxnet", repos = "http://dmlc.ml/drat/", type = "binary") : 
  type 'binary' is not supported on this platform
> 
```

**Comment by thirdwing** [comment]
Maybe we are using different version of OSX. Please try `mac.binary` or `mac.binary.mavericks`.

**Comment by littletree-github** [comment]
```
> install.packages("mxnet", repos="http://dmlc.ml/drat/", type="mac.binary.mavericks")
```
works!
Thank you @thirdwing for such quickly response!

**Comment by yl2** [comment]
I am trying to install mxnet for R on a linux machine. I tried the suggestions above with type = binary, mac.binary, mac.binary.mavericks but none of them worked. Any suggestions on how to install mxnet for R on linux? Thanks!

> install.packages("mxnet", repos = "http://dmlc.ml/drat/", type = "source")
Installing package into ‘/q5/hhq5/rlib’
(as ‘lib’ is unspecified)
trying URL 'http://dmlc.ml/drat/src/contrib/mxnet_0.9.5.tar.gz'
Warning in download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'http://dmlc.ml/drat/src/contrib/mxnet_0.9.5.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://dmlc.ml/drat/src/contrib/mxnet_0.9.5.tar.gz'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘mxnet’ failed
> 
> 
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.3.3 tools_3.3.3    tcltk_3.3.3

**Comment by thirdwing** [comment]
As a Linux user, I think you need to compile mxnet from source.
