### ISSUE TITLE
Fail to compile the latest mxnet with GPU

### ISSUE THREAD

**Issue by ChenKQ** [dmlc/mxnet#4993]
## Environment info
Operating System:   *CentOS7*
Compiler:   *gcc 4.8; cuda7.0*
Package used (Python/R/Scala/Julia):
anaconda python 2.7
MXNet version:
latest
Or if installed from source:
yes
## Error Message:

src/operator/tensor/././indexing_op-inl.cuh: error: more than one instance of overloaded function "max" matched the argument list:
   function "max(int,int)"
 .....
argument types are: (size_t,size_t)

Is it the problem of CUDA Version?  My CUDA version is 7.

**Comment by piiswrong** [comment]
you need cuda 7.5 and above

**Comment by ChenKQ** [comment]
Thanks. It is fine to compile mxnet after updating cuda to 8.0.
