### ISSUE TITLE
Error after replaced target_shape with shape

### ISSUE THREAD

**Issue by HuitingLiu** [dmlc/mxnet#4995]
label = mx.sym.Reshape(data=label, target_shape=(0,))
=>
label = mx.sym.Reshape(data=label, shape=(0,))

The error message is below:

`Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 25, in main
    output_size=vocab_size, dropout=0.0, mx_ctx=CTX)
  File "/home/ec2-user/mxnet-seq2seq/seq2seq.py", line 29, in __init__
    self.decoder = self.build_lstm_decoder()
  File "/home/ec2-user/mxnet-seq2seq/seq2seq.py", line 143, in build_lstm_decoder
    for_training=is_train, )
  File "/home/ec2-user/src/mxnet/python/mxnet/module/bucketing_module.py", line 186, in bind
    force_rebind=False, shared_module=None, grad_req=grad_req)
  File "/home/ec2-user/src/mxnet/python/mxnet/module/module.py", line 345, in bind
    grad_req=grad_req)
  File "/home/ec2-user/src/mxnet/python/mxnet/module/executor_group.py", line 187, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/ec2-user/src/mxnet/python/mxnet/module/executor_group.py", line 279, in bind_exec
    shared_group))
  File "/home/ec2-user/src/mxnet/python/mxnet/module/executor_group.py", line 483, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/home/ec2-user/src/mxnet/python/mxnet/symbol.py", line 542, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/home/ec2-user/src/mxnet/python/mxnet/symbol.py", line 609, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/ec2-user/src/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator reshape0: [22:43:52] src/operator/tensor/./matrix_op-inl.h:151: Check failed: oshape.Size() == dshape.Size() (26 vs. 260) Target shape size is different to source. Target: (26,)
Source: (26,10)

Stack trace returned 75 entries:
[bt] (0) /home/ec2-user/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x29) [0x7fb1824b14d9]
[bt] (1) /home/ec2-user/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet2op12ReshapeShapeERKN4nnvm9NodeAttrsEPSt6vectorINS1_6TShapeESaIS6_EES9_+0x1467) [0x7fb182c3c2b7]
[bt] (2) /home/ec2-user/src/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1ddecf7) [0x7fb183bb4cf7]
[bt] (3) /home/ec2-user/src/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1de02d2) [0x7fb183bb62d2]
[bt] (4) /home/ec2-user/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x509) [0x7fb183bd0d99]
[bt] (5) /home/ec2-user/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x8e) [0x7fb182fe771e]
[bt] (6) /home/ec2-user/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EESs+0x240) [0x7fb182fead40]
[bt] (7) /home/ec2-user/src/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0x271) [0x7fb182fe2bb1]
[bt] (8) /opt/python3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7fb18c8bc92c]
[bt] (9) /opt/python3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call+0x165) [0x7fb18c8bba75]
[bt] (10) /opt/python3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x283) [0x7fb18c8b3ee3]
[bt] (11) /opt/python3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x967f) [0x7fb18c8ab67f]
[bt] (12) python3(_PyObject_FastCallDict+0xa2) [0x451182]
[bt] (13) python3() [0x53ddf5]
[bt] (14) python3(_PyEval_EvalFrameDefault+0x2a2c) [0x541a5c]
[bt] (15) python3() [0x53dca1]
[bt] (16) python3(_PyFunction_FastCallDict+0x14a) [0x546c7a]
[bt] (17) python3(_PyObject_FastCallDict+0x1ef) [0x4512cf]
[bt] (18) python3(_PyObject_Call_Prepend+0xcb) [0x4513cb]
[bt] (19) python3(PyObject_Call+0x60) [0x450fa0]
[bt] (20) python3(_PyEval_EvalFrameDefault+0x3b25) [0x542b55]
[bt] (21) python3() [0x53dca1]
[bt] (22) python3(_PyFunction_FastCallDict+0x14a) [0x546c7a]
[bt] (23) python3(_PyObject_FastCallDict+0x1ef) [0x4512cf]
[bt] (24) python3(_PyObject_Call_Prepend+0xcb) [0x4513cb]
[bt] (25) python3(PyObject_Call+0x60) [0x450fa0]
[bt] (26) python3(_PyEval_EvalFrameDefault+0x3b25) [0x542b55]
[bt] (27) python3() [0x53dca1]
[bt] (28) python3() [0x53df9f]
[bt] (29) python3(_PyEval_EvalFrameDefault+0x2a2c) [0x541a5c]
[bt] (30) python3() [0x53dca1]
[bt] (31) python3() [0x53df9f]
[bt] (32) python3(_PyEval_EvalFrameDefault+0x2a2c) [0x541a5c]
[bt] (33) python3() [0x53dca1]
[bt] (34) python3(_PyFunction_FastCallDict+0x14a) [0x546c7a]
[bt] (35) python3(_PyObject_FastCallDict+0x1ef) [0x4512cf]
[bt] (36) python3(_PyObject_Call_Prepend+0x74) [0x451374]
[bt] (37) python3(PyObject_Call+0x60) [0x450fa0]
[bt] (38) python3() [0x4c65fb]
[bt] (39) python3() [0x4bde2a]
[bt] (40) python3(_PyObject_FastCallDict+0xa2) [0x451182]
[bt] (41) python3(_PyObject_FastCallKeywords+0xd4) [0x451674]
[bt] (42) python3() [0x53ddf5]
[bt] (43) python3(_PyEval_EvalFrameDefault+0x3c1e) [0x542c4e]
[bt] (44) python3() [0x53dca1]
[bt] (45) python3() [0x53df9f]
[bt] (46) python3(_PyEval_EvalFrameDefault+0x3c1e) [0x542c4e]
[bt] (47) python3() [0x53dca1]
[bt] (48) python3() [0x53df9f]
[bt] (49) python3(_PyEval_EvalFrameDefault+0x3c1e) [0x542c4e]
[bt] (50) python3() [0x53dca1]
[bt] (51) python3() [0x53df9f]
[bt] (52) python3(_PyEval_EvalFrameDefault+0x2a2c) [0x541a5c]
[bt] (53) python3() [0x53dca1]
[bt] (54) python3(_PyFunction_FastCallDict+0x14a) [0x546c7a]
[bt] (55) python3(_PyObject_FastCallDict+0x1ef) [0x4512cf]
[bt] (56) python3(_PyObject_Call_Prepend+0xcb) [0x4513cb]
[bt] (57) python3(PyObject_Call+0x60) [0x450fa0]
[bt] (58) python3() [0x4c65fb]
[bt] (59) python3() [0x4bde2a]
[bt] (60) python3(_PyObject_FastCallDict+0xa2) [0x451182]
[bt] (61) python3(_PyObject_FastCallKeywords+0xd4) [0x451674]
[bt] (62) python3() [0x53ddf5]
[bt] (63) python3(_PyEval_EvalFrameDefault+0x3c1e) [0x542c4e]
[bt] (64) python3() [0x53dca1]
[bt] (65) python3() [0x53df9f]
[bt] (66) python3(_PyEval_EvalFrameDefault+0x2a2c) [0x541a5c]
[bt] (67) python3() [0x53dca1]
[bt] (68) python3(PyEval_EvalCode+0x60) [0x53eab0]
[bt] (69) python3(PyRun_FileExFlags+0x168) [0x426278]
[bt] (70) python3(PyRun_SimpleFileExFlags+0xdd) [0x42645d]
[bt] (71) python3(Py_Main+0xd15) [0x43a8d5]
[bt] (72) python3(main+0x162) [0x41d652]
[bt] (73) /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fb1aa551b15]
[bt] (74) python3() [0x41d711]
`

**Comment by piiswrong** [comment]
shape=(0,) -> shape=(-1,)

**Comment by HuitingLiu** [comment]
Thanks!
