### ISSUE TITLE
Save and evaluate mxnet model between full epochs for finetuning

### ISSUE THREAD

**Issue by Strateus** [dmlc/mxnet#4996]
There was a topic:
[http://github.com/dmlc/mxnet/issues/1593](https://github.com/dmlc/mxnet/issues/1593)

But it seems new interface (mx.mod.Module) does not have **epoch_size** argument anymore. Is there a way to save model during finetuning?

**Comment by piiswrong** [comment]
You can use mx.io.ResizeIter to make your data smaller.

**Comment by Strateus** [comment]
thank you
