### ISSUE TITLE
R build fails on OSX Mavericks Machine

### ISSUE THREAD

**Issue by sbodenstein** [dmlc/mxnet#500]
I've built MXNet on an OSX Mavericks machine without problems (all the Python examples run fine). However, I can't build the R package with `R CMD INSTALL R-package`. Running this gives the following error:

```
In file included from executor.cc:9:
././base.h:12:10: fatal error: 'dmlc/base.h' file not found
#include <dmlc/base.h>
         ^
1 error generated.
make: *** [executor.o] Error 1
ERROR: compilation failed for package ‘mxnet’
```

Also, I'm using R 3.2.2.

**Comment by tqchen** [comment]
Please make sure you have initialized the git submodule and pulled dmlc-core

**Comment by thirdwing** [comment]
It is my fault. I forgot to update the building instruction.

@sbodenstein Please use `make rpkg` to generate `mxnet_0.5.tar.gz`, then `R CMD INSTALL mxnet_0.5.tar.gz`.

**Comment by sbodenstein** [comment]
Great! It works now.
