### ISSUE TITLE
Bucketing module prediction

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#5008]
``` python
    def load_param(self, param_path):
        node_data = mx.nd.load(param_path)
        # pickle is not working although the doc says so
        # param_file = open('./model/card-0001.params','rb')
        # print pickle.load(param_file)

        # parse node data into 2 lists
        arg_param={}
        aux_param={}
        for k, v in node_data.items():
            tp, name = k.split(':', 1)
            if tp == 'arg':
                arg_param[name] = v
            if tp == 'aux':
                aux_param[name] = v
        print(arg_param)
        print(aux_param)
        return arg_param, aux_param

    def __init_ocr(self):
        batch_size = 1
        self.predictor=mx.module.BucketingModule(sym_gen, default_bucket_key=self.default_bucket_key,context=mx.context.gpu(0))
        arg_param, aux_param = self.load_param(self.path_of_params)
        self.predictor.bind(self.data_shapes, self.label_shapes,for_training=False)
        self.predictor.init_params(arg_params=arg_param, aux_params=aux_param)

    def predict(self, data_batch):
        self.predictor.forward(data_batch, is_train=False)
        return self.predictor.get_outputs()

    # sym_gen
    def sym_gen(bucket_key):
        label_length, lstm_length = bucket_key.split(',')
        lstm_length = int(lstm_length)
        label_length = int(label_length)
        return get_symbol(num_classes, num_hidden, lstm_length, label_length), data_name, label_name
```

I tried to load my bucketing ocr using bucketing module with saved model.  The prediction predicts nothing but blank in ctc for all examples even if I use training data for testing.  
The training was doing ok with model converged and saved.

**Comment by Godricly** [comment]
How can I make sure the forward execution is finished when the get_outputs is called? @tqchen 
```python 
    def predict(self, data_batch):
        self.predictor.forward(data_batch, is_train=False)
        return self.predictor.get_outputs()
```

**Comment by tqchen** [comment]
do get_outputs()[0].wait_to_read()

**Comment by Godricly** [comment]
thx. Problem was fixed. I was using np.argmax on nd.array. something was wrong with it. But after converting it to numpy with asnumpy, it works good.

**Comment by xinghedyc** [comment]
@Godricly I'm working on cnn-lstm-ocr tasks like example/warpctc but I do not know how to add bucketing in the whole process, could you give me some help or guide? Thank you very much.

**Comment by Godricly** [comment]
Do you have bucket design?  I already shared mine on top. I can't share the network for you. Its almost the same way as other bucketing work. Although I actually kept lstm length fixed.  I can actually support it easily.

**Comment by xinghedyc** [comment]
@Godricly Thank you for your help, I was stuck in this problem, have you ever eet it? 
#5162

**Comment by sunspring320** [comment]
@Godricly would you provide of the predict python code in BucketingModule with variable-length sequence? i have some difficulty , thanks!

**Comment by Godricly** [comment]
I already did right?
