### ISSUE TITLE
 there appear nan in convolution weight

### ISSUE THREAD

**Issue by moveforever** [dmlc/mxnet#5013]
at batch 1,  there appear nan in convolution weight at batch 1. And i set clip=5.0. i set monitor and information about weight is printed:
![nan](https://cloud.githubusercontent.com/assets/5248288/22931955/93b15bf0-f301-11e6-84c5-97268ff5c1c8.png)
why? how can i set extra hyperparameter？

**Comment by tornadomeet** [comment]
which model/dataset and code? need more information.
you can try to reduce the learning-rate.

**Comment by moveforever** [comment]
i design a network for predicting click throgh rate, and a local network of the network is convolution network. However, the convolution network weight is nan 
i reduce learning-rate=0.00001 and clip_gradient=1, it doesnot work, and convolution still appear nan

**Comment by moveforever** [comment]
i print gradient array, and find gradient is nan 

![Uploading grad_nan.png…]()

**Comment by tornadomeet** [comment]
@moveforever  hello, convolution layer should be numerical stability, because we use it always for big model and big dataset, and it also test in background. 
i suggest first, check you data value, make sure the value is normal, because your first layer of convolution grad is nan. then check your symbol file, had better visual the symbol graph. 

thanks~

**Comment by moveforever** [comment]
@tornadomeet , thanks for your advice, it works. i found there were something wrong with data.
tks.

**Comment by YeWenting** [comment]
Hi @moveforever, I encountered this problem too. Could you please tell me your solution? This might be helpful to my situation:)

**Comment by moveforever** [comment]
@YeWenting , Wrong data may lead to nan, so check your data, and make sure your data is right

**Comment by YeWenting** [comment]
@moveforever , I have checked my data but seemed to be ok. If you could tell me your scenario, it might help me to solve my problem:)
