### ISSUE TITLE
How to create an empty model of specified structure?

### ISSUE THREAD

**Issue by GreenKing** [dmlc/mxnet#5024]
I have a model of matconvnet and I can get the specific parameters of the model in Python. Now I want to run this model in mxnet. How can I create an empty model of the same structure in mxnet such that I can fill all the parameters on my own? Any help will be appreciatived!

**Comment by lilhope** [comment]
Just write the net,then use your parameters to initial the net,simple code like this:
``` 
     def net():
            a = mx.sym.Variable('data')
            conv1 = mx.sym.Convolution(data=a,kernel=(3,3),num_fliter=64,name="conv1")
            flatten = mx.sym.Flatten(data=conv1,name='flatten')
            fc = mx.sym.FullyConnected(data=b,num_hidden=4,name="fc1")
            return fc
```
this will return a net symbol, then you can use this code to load your parameters :
```
     def load_checkpoint(file_name):
            save_dict = mx.nd.load(file_name)
            arg_params = {}
            aux_params = {}
            for k, v in save_dict.items():
            tp, name = k.split(':', 1)
            if tp == 'arg':
                arg_params[name] = v
            if tp == 'aux':
                aux_params[name] = v
            return arg_params, aux_params
```
Now you get the arg_params,then use the params initialize you net,see `mx.mod.Module` for detail. if you want to fix some parameters ,just add the param's name to fixed_param_prefix.   
example code was in `/mxnet/example/rcnn/train_end2end.py` line74 -line 85, 102 -105,141 -145, hope it helps.

**Comment by GreenKing** [comment]
@lilhope Thank you very much!
I have followed your advice load part of my model as following code
```
def gen_model_mx(my_params):
    data = mx.sym.Variable('data')
    net = mx.sym.Convolution(data, name='conv1', kernel=(11,11), num_filter=96, stride=(2,2))
    net = mx.sym.BatchNorm(net, name='bn1')
    
    model = mx.mod.Module(net)
    
    data_iter = mx.io.NDArrayIter(data=np.zeros((1,3,127,127)))
    model.bind(data_shapes=data_iter.provide_data)

    arg_params = {
        "conv1_weight": mx.nd.array(my_params['conv1f']),
        "conv1_bias":  mx.nd.array(my_params['conv1b']),
        "bn1_beta":  mx.nd.array(my_params['bn1b']),
        "bn1_gamma":  mx.nd.array(my_params['bn1m']),
    }

    aux_params = {
        "bn1_moving_mean": mx.nd.array(my_params['bn1x'][:, 0]),
        "bn1_moving_var" : mx.nd.array(my_params['bn1x'][:, 1]**2),       
    }

    model.init_params(arg_params=arg_params, aux_params=aux_params)
    model.save_checkpoint(prefix="mymodel", epoch=1)
```

and I try to use the saved model as following
```
def model_test():
    model = mx.model.FeedForward.load("mymodel", 1, ctx=mx.cpu(0))

    z_crop = load_test_data()
    res = model.predict(z_crop)
    
    print res
```
I found that it works fine with Convolution layer but the output data of BatchNorm layer is not as expected.
As noticed that `mean` and `var` are initialized in `aux_params ` dict. Is there any trick to deal with BatchNorm layer ? Or is my operation valid ?

**Comment by lilhope** [comment]
@GreenKing I haven't use bath norm in mxnet, so I can't help you.

**Comment by tornadomeet** [comment]
@GreenKing  your code should be ok, but i'm not familiar with bn  implemented in matconvnet, and it's may be help to read the src code of these two framework and check what's the difference.

**Comment by GreenKing** [comment]
I'll check it again. Thank you @lilhope @tornadomeet

**Comment by GreenKing** [comment]
I rewrote the batchnorm symbol myself and it gives the right output
