### ISSUE TITLE
some questions about clip and convolution update?

### ISSUE THREAD

**Issue by moveforever** [dmlc/mxnet#5031]
Question 1:when computing convolution layer gradient, whether gradient become nan?
 Question 2:when gradident is nan, does clip work?

small help welcome, thks.

**Comment by tornadomeet** [comment]
should  Analyze what's really caused nan about convolution, because some time the grad of conv is nan,but not caused by convolution itself(maybe casued by data value).

**Comment by moveforever** [comment]
@tornadomeet ,thank you very much, it were caused by data.
