### ISSUE TITLE
Lastest LSTM version

### ISSUE THREAD

**Issue by Godricly** [dmlc/mxnet#5038]
What is the latest version of lstm implementation? I'm still using the old one in warpctc example? Is there any new implementation after NNVM? @feiyulv

My image iter can outputs 1600 samples per second while the lstm only able to process 100 per second.
The gpu is almost idle all the time.

**Comment by piiswrong** [comment]
example/rnn/cudnn_lstm_bucketing is a new example

**Comment by mz24cn** [comment]
my benchmark:
scripts                         run_time(minutes)   speed(samples/s)  first_epoch:train-perplexity/val-perplexity    last_epoch:train-perplexity/val-perplexity  
old cudnn version:
rnn/old/rnn_cell_demo.py                 35         ~700                          254              238                          199              179
rnn-time-major/rnn_cell_demo.py          34         ~700                          207              222                          162              193
new unroll version:
rnn/lstm_bucketing.py                    64         ~290                          875              862                          267              249
new cudnn version:
rnn/cudnn_lstm_bucketing.py              6          ~2300                         1047             1040                         345              334
special case:
rnn/cudnn_lstm_bucketing.py(250 epoch)   78         ~2300                         1057             1018                         49               264
rnn/old/rnn_cell_demo.py+PR(#4819)       38         ~690                          123              134                          47               55

batch size is adjusted to 32 for all case. device set to one GPU (GTX1080), others are default, nightly building, 0.9.4, python 3.6.

现在cudnn版本的RNN模型自动给initializer套一个专门版本的初始化器，然后再自动解包到一般形式，初始化好之后再重新打包成一个参数，比较复杂，细节还没看明白，做的很精妙。But the results are strange. Especially the results on validation data are not good as the old. 我也不不太能理解这个结果，是不是我跑的有问题。**Could you reproduce my results?**

**Comment by piiswrong** [comment]
Could you list the exact command you used to run each example?

**Comment by piiswrong** [comment]
BTW the old one uses a custom perplexity metric and it's wrong.

**Comment by Godricly** [comment]
Where is the fusing cudnn?

**Comment by eric-haibin-lin** [comment]
@Godricly  cudnn lstm ->
https://github.com/dmlc/mxnet/blob/master/example/rnn/cudnn_lstm_bucketing.py

**Comment by Godricly** [comment]
@eric-haibin-lin Sry, i didn't make it clean. What I am asking is how cudnn involves in this example. It looks like that the new rnn interface was only wraping the old one.

**Comment by Godricly** [comment]
Found it. :frowning_face:
