### ISSUE TITLE
NVCC crash when compiling indexing_op.cu

### ISSUE THREAD

**Issue by PrismQ** [dmlc/mxnet#5041]
## Environment info
Operating System: Windows 10.0.14393

Compiler: MSVC 19.0.24210.0 (VS14)    CUDA 8.0.61

Package used (Python/R/Scala/Julia): libmxnet

MXNet commit hash : 3b9d82d

## Error Message:

5>  Building NVCC (Device) object CMakeFiles/cuda_compile.dir/src/operator/tensor/Release/cuda_compile_generated_indexing_op.cu.obj
5>  indexing_op.cu

nvcc error : ‘cicc’ died with status 0xC0000005 (ACCESS_VIOLATION)

## Steps to reproduce

1. check out mxnet
2. turn off openCV support, write MKL path info in makefile   and generate VS14 sln file
3. open sln, set "Release x64" and compile

I tried to compile the project 4 times. It always crash at indexing_op.cu

## What have you tried to solve it?

1. switch to an older commit b11d3a2 (tag v0.9.3) will solve the problem.

**Comment by piiswrong** [comment]
I don't think nvcc works with cicc, @ap-hynninen does it?

**Comment by piiswrong** [comment]
This is strange, nothing after 3b9d82d touched indexing_op.cu

**Comment by ap-hynninen** [comment]
@piiswrong Do you mean after https://github.com/dmlc/mxnet/commit/b11d3a2550b3ad9d96f42e7d15e2c418dd2b4c52 ?

@ptrendx can you comment on the cicc error?

**Comment by thomascatlee** [comment]
I met the same problem, cicc crashed.

I changed VS14 to VS12, still cicc crashed.

I'll try 0.9.3, and report if it works.

**Comment by piiswrong** [comment]
So this seems to be windows specific.
Maybe try vs15?

**Comment by piiswrong** [comment]
Could you add -v -keep flags to nvcc invocation

This should show the exact way cicc was launched. And keep the intermediate file that it was given

With that we will be able to file a bug with Nvidia

**Comment by PrismQ** [comment]
5>  indexing_op.cudafe2.gpu
5>
5>  #$ cicc  -arch compute_61 -m64 -ftz=0 -prec_div=1 -prec_sqrt=1 -fmad=1 -nvvmir-library "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/bin/../nvvm/libdevice/libdevice.compute_30.10.bc" --orig_src_file_name "D:/dev/mxnet/mxnet/src/operator/tensor/indexing_op.cu"  "indexing_op.cpp3.i" -o "indexing_op.ptx"
5>
5>CUSTOMBUILD : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
5>

[indexing_op.txt](https://github.com/dmlc/mxnet/files/782997/indexing_op.txt)
[indexing_op.zip](https://github.com/dmlc/mxnet/files/783011/indexing_op.zip)

**Comment by hahaxun** [comment]
same issue for me

**Comment by Raa23** [comment]
I have the same issue as well (Win10 + VS2013)

5>  indexing_op.cu
5>  
5>CUSTOMBUILD : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
5>  
5>  CMake Error at cuda_compile_1_generated_indexing_op.cu.obj.Release.cmake:282 (message):
5>    Error generating file
5> C:/dev/mxnet/build/CMakeFiles/cuda_compile_1.dir/src/operator/tensor/Release/cuda_compile_1_generated_indexing_op.cu.obj
5>

**Comment by junshipeng** [comment]
same issue for me, (Win10 + CUDA8.0 + OpenCV3.1 + VS2015 + cudnn5.1),
I don't know how to solve it

**Comment by sxjscience** [comment]
@Chen-Wang-CUHK has also met this problem. The cuda version is the latest CUDA 8.0.61.

Also, the commit that causes the problem seems to be between https://github.com/dmlc/mxnet/commit/e6224381 and https://github.com/dmlc/mxnet/commit/b11d3a2550b3ad9d96f42e7d15e2c418dd2b4c52. Need someone to do a binary search. The commits are listed here (https://github.com/dmlc/mxnet/commits/master) and we can check the middle commit to limit the domain.

**Comment by hahaxun** [comment]
I have tried debug version, it seems work, but when I change to release , it have same issue.

**Comment by li-haoran** [comment]
i meet the same issue.
when i compile the mxnet-0.9.3 in different computer one is sm-21 another is sm_52 with same configuration win7,vs13 update5,cuda7.5.  In sm-21 successful, but in sm-52 failed by cicc crashed

**Comment by sxjscience** [comment]
@li-haoran, are you using the CUDA 8.0.61 version (the latest)? I'm also using Windows10 and I could compile it using CUDA 8.0.44.

**Comment by li-haoran** [comment]
@sxjscience  no, i use the cuda7.5. it is successful in sm_21 gpu card, but when i turned to the sm-52 gpu card. the compile is failed

**Comment by li-haoran** [comment]
the dubug versionin sm-52 gpu card is successful, the release is still failed

**Comment by hahaxun** [comment]
@li-haoran  it‘s successful, but it have so much crash

**Comment by hahaxun** [comment]
it's not just for indexing_op.cu, it's more about the bug of nvcc, I delete indexing_op.cu, others file still cause some issue

**Comment by sxjscience** [comment]
@hahaxun Which cuda version are you using? Could you try the cuda 0.8.44 (An older version of CUDA 8.0).

**Comment by hahaxun** [comment]
I use cuda 7.5 + win7 + vs2013 + GTI960.

**Comment by sxjscience** [comment]
@hahaxun OK, I've tried the CUDA 8.0.44 + Win10 + VS2015 Community on three machines and the combination works well.

**Comment by hahaxun** [comment]
@sxjscience thank you , it should be a nvcc or vs bug,when it compile many cu file on sm_52 , nvcc crash.

**Comment by sxjscience** [comment]
@hahaxun Yes, I also suspect that it's related to nvcc. Could you help try the previous combinations? (CUDA 8.0.44 https://developer.nvidia.com/cuda-80-download-archive + VS2015 Community)

**Comment by hahaxun** [comment]
@sxjscience  I have try it, it have same issue

**Comment by jennyzhang0215** [comment]
@sxjscience  After rolling back several versions, we found that the commit id d2fae3102501145f7597505fb19c76578b2d4f20 failed but the commit id 62e91d578bd1916f1e5e3288d0bdb24329d0faa4 succeeded. Thus, the cicc problem is located in the commits in Jan 26.

**Comment by sxjscience** [comment]
@piiswrong @ap-hynninen I think it may be this PR 340f965e2ba97e73c66aeda8eeb7d3b02eba05e6.

**Comment by ap-hynninen** [comment]
I can do some debugging on this once my desktop arrives that has windows. Should be today or tomorrow.

**Comment by sxjscience** [comment]
@hahaxun @PrismQ @li-haoran

@jennyzhang0215 and @Chen-Wang-CUHK have confirmed that the problem can be solved by turning into cuda v8.0.44. cuda v7.5 and cuda v8.0.61 will all trigger the error.

You could download the cuda v8.0.44 from the link here: https://developer.nvidia.com/cuda-80-download-archive

**Comment by Chen-Wang-CUHK** [comment]
Yes. I have solved this problem by using cuda v8.0.44. Thanks a lot!

2017-03-03 13:50 GMT+08:00 Xingjian Shi <notifications@github.com>:

**Comment by ap-hynninen** [comment]
In the mxnet Windows installation page it says: "Use CMake to create Visual Studio solution in ./build". What is the command for doing this?

**Comment by piiswrong** [comment]
mkdir build; cd build; cmake ..

**Comment by ap-hynninen** [comment]
I was able to compile OK with 8.044, as expected. Is it worth fixing this? Could we just tell windows users to use cuda 8.0.44?

**Comment by ap-hynninen** [comment]
I have made a WAR for this but I'm worried about fully testing it, keeping it up to date in the future, and performance degradation due to use of Thrust.

**Comment by piiswrong** [comment]
Ok. Can we detect cuda version and throw an error instead of crashing nvcc?
pragma error?

**Comment by ap-hynninen** [comment]
Throw a pragma saying "Install CUDA 8.044" :) I'll look into it..

**Comment by ap-hynninen** [comment]
Hmm, doesn't crash for me on Win 7, VS 2015, CUDA 8.044

**Comment by ap-hynninen** [comment]
@PrismQ I can't reproduce this bug. How did you produce the visual studio solution files? I used:
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" ..

**Comment by piiswrong** [comment]
@ap-hynninen I think you need cuda 8.0.61 for it to crash?

**Comment by ap-hynninen** [comment]
Ah, OK let me try one more time..

**Comment by ap-hynninen** [comment]
Great, I got it to crash now

**Comment by sxjscience** [comment]
Should be solved by https://github.com/dmlc/mxnet/pull/5308. @PrismQ would you like to test again?

**Comment by PrismQ** [comment]
@sxjscience @ap-hynninen   I tested c356e25 (current master) using 8.0.61 and was able to compile. Thanks a lot:)

**Comment by maomran** [comment]
Same problem.
Env:
Linux Ubuntu
Cuda V9.0.176
mxnet 1.2.1 build from source
`nvcc error   : 'cicc' died due to signal 11 (Invalid memory reference)`
