### ISSUE TITLE
MNIST training example not exiting on CPU instances after training completion

### ISSUE THREAD

**Issue by sampathchanda** [dmlc/mxnet#5065]
Hi,

Am running MNIST training on 2 CPU instances using MXNET with 10 epochs (Default script, provided). However, even after the training is all done ( I could see that the execution reaches the end of train_mnist.py script), execution isn't exiting. 

Can anyone help me with this issue.

## Environment info
Operating System: Amazon Linux
Package used (Python/R/Scala/Julia): Python
MXNet Installed from sources
MXNet commit hash (`git rev-parse HEAD`): 266e439d366f8d3022f52c700a77229811d4cd77
Python version and distribution: Python 2.7.12

## Steps to reproduce
1. cd $HOME/mxnet/examples/image_classification/
2. ../../tools/launch.py -n 1 -H hosts python train_mnist.py

hosts file consists of the worker hostnames (2 workers in my case, as follows):
deeplearning-worker1
deeplearning-worker2

**Comment by Soonhwan-Kwon** [comment]
If you launced it by ../../tools/launch.py, there is ../../tools/kill-mxnet.py to kill the process.

**Comment by sampathchanda** [comment]
For those who are also facing this issue, please follow the steps mentioned by @qiyuangong in the issue #5094 to get the scripts working as expected. Am now able to successfully run the example given on multi CPU cluster, and hence closing this issue.
