### ISSUE TITLE
Request for install script for CentOS

### ISSUE THREAD

**Issue by sampathchanda** [dmlc/mxnet#5067]
Can anyone please make an install script for CentOS, similar to the install scripts present in setup_utils directory.

Thanks !!

**Comment by luoyetx** [comment]
I think [install-mxnet-fedora-python.sh](https://github.com/dmlc/mxnet/blob/master/setup-utils/install-mxnet-fedora-python.sh) should work for CentOS7.

**Comment by sampathchanda** [comment]
That worked. Thanks !!

However, had to fix an issue with cblas, as said in following thread:
https://github.com/dmlc/mxnet/issues/1442

That is, changing -lcblas to -lsatlas in https://github.com/dmlc/mshadow/blob/master/make/mshadow.mk#L56
