### ISSUE TITLE
Re-organize examples

### ISSUE THREAD

**Issue by piiswrong** [dmlc/mxnet#507]
We have a lot of good examples but the example folder is kinda getting cluttered.
We can re-organize the folder structure to make it clearer:
+image_classification
+feature_guide
+autoencoder
+rnn
+adversary
+etc

Also, we should make it possible for people to contribute examples, and related pretrained weights, without submitting PR to mxnet. It will be easier for contributors and for us to maintain.
Any ideas on how to do it?

**Comment by tqchen** [comment]
+1 for the task based examples.

I think it is fine to do examples as PR, because they are real contributions and we like to give credit our contributors that.

**Comment by antinucleon** [comment]
+1

**Comment by piiswrong** [comment]
I think we can have both: an in house example repo, plus an exmaple registry, where people can freely post their work with mxnet

**Comment by tqchen** [comment]
I like the idea of example registry. 

It can either be a README.md(with links to people's repo) or wiki.

**Comment by piiswrong** [comment]
wiki sounds better. The idea is to minimize the effort it takes to register a work

**Comment by futurely** [comment]
It's best to have a fine-tuning example https://github.com/dmlc/mxnet/issues/379 in the style of [this doc](http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html).

**Comment by mli** [comment]
also agree that we can reorg the example by applications. it would be even better if each examples supports tags. for example, for the imagnet inception examples, we can have

```
# tags: ilsvrc12, inception, batch-normalization, convolution
``` 

and them build a tag index automatically. so people who are interested on dn technologies can find the examples quickly

**Comment by piiswrong** [comment]
Search would be good. 
The docker registry model looks pretty nice. Is there a solution for building something like that easily?

**Comment by mli** [comment]
do you mean a docker hub like service to host pre-trained models? probably putting a model in a downloadable place is good enough. if we use docker, we often link the model into docker, rather than make the model into the docker image, which will result in frequent building.

if you mean the tag search, probably a simple grep script will do the trick. we already did that in the dmlc blog, see
https://github.com/dmlc/dmlc.github.io/blob/master/_posts/2015-11-03-training-deep-net-with-R.markdown
