### ISSUE TITLE
[scala-package] Raise the error 'terminate called without an active exception'

### ISSUE THREAD

**Issue by yxzf** [dmlc/mxnet#5071]
@javelinjs I run the mxnet on the spark with yarn-cluster, the important config of submission is below:
```
--executor-cores 1 \
 --executor-memory 8g \
 --queue $QUEUE \
 --master $MASTER \
 --num-executors 10 \
 --driver-memory 8g \
--conf spark.my.job.cpus="0"
--conf spark.my.job.num.worker=8 \
 --conf spark.my.job.num.server=2 \
 --conf spark.my.job.num.epoch=2 \
 --conf spark.my.job.batch.size=128 \
```
From the log of worker, I find it raise the error '' when the first epoch is finished:
![image](https://cloud.githubusercontent.com/assets/9815568/23125278/e7073f50-f7ab-11e6-83a4-062a859bd23e.png)

Do you know why?

**Comment by javelinjs** [comment]
Did it work fine on a standalone cluster?

**Comment by yxzf** [comment]
@javelinjs We only can submit spark job in yarn with yarn-client or yarn-cluster.

I test mxnet on a dataset, which has 211 partitions in HDFS(437827 row).
(1) if I use all partitions, the result is above.
(2)Today I tried to select a small fraction, with sql "limit 10000", then only 1 partition, and I set the number of worker to be 8, so it will shuffle to be 8 partitions (In MXNet.scala 113). And the job executed successfully.
(3) And I tried to select with sql "limit 100000", then still only 1 partition and shuffled to be 8 partitions. But the job failed. The 0-4th epoch was done, but in 5th epoch, it still raised the error, "terminate called without an active exception"
![image](https://cloud.githubusercontent.com/assets/9815568/23153787/670fb59e-f845-11e6-9a02-3b5913635c50.png)

I search the error 'terminate called without an active exception', which is multithreading problem of  C++, but I don't know where it raised. I was so confused. Do you know why?

**Comment by yxzf** [comment]
@tqchen @piiswrong @CodingCat  Do you know where the error 'terminate called without an active exception' raised?

**Comment by yxzf** [comment]
Maybe the reason is the parameter 'setTimeout' of class MXNet  is set to be smaller.
