### ISSUE TITLE
How can I run train_alternate.py with only 4G or less of the memory of the GPU ?

### ISSUE THREAD

**Issue by MU001999** [dmlc/mxnet#5073]
Can I make the batch_size less or do other things? @pluskid @pineking @thinxer

**Comment by lilhope** [comment]
I think the batch size = 1 if you only have one GPU when training the RPN network, it can't be modified.After you train the RPN, you will train a RCNN network,this batch size can be modified,you can set it in file `/rcnn/tools/train_rcnn.py`.

**Comment by MU001999** [comment]
Can it be modified to be less than 1 ?

**Comment by lilhope** [comment]
@MU001999 The batch size means how many images you put into the network every time, if it less than one,your network get **no input**.

**Comment by MU001999** [comment]
Thanks a lot! @lilhope
