### ISSUE TITLE
questions about prediction API

### ISSUE THREAD

**Issue by lancerkz** [dmlc/mxnet#5076]
Hi community 

Recently, I'm playing with MXNet. and some questions raised during my experiments.  

Q1: I just wonder why size of libmxnet_predict.so is large than libmxnet.so? Is it(amalgamation version) target to have a compact lib? 

Info: 
* both are compiled only support CPU
* openBLAS is used. 
* for libmxnet: has Opencv, no openmp, no KVStore, no hdfs, no s3
* platform is Mac OSX 10.12
* libmxnet_predict.so is around 22M, and libmxnet.so is around 16M. 

Q2: I'm using lstm_bucketing.py from rnn folder as training script. and I added following two lines to save json/model parameter. 

```
    model.save_params('xx.params')
    model.symbol.save('xx.json')
```

but json string could be not parsed by MXPredCreate function of prediction library. 
error code shows 

mxnet_predict-all.cc:22737: Check failed: op != nullptr Operator Embedding is not registered
Assertion failed: (predh)

It seems embedding OP is not compiled in prediction library.  My question is do we have any workaround to use Embedding layer in prediction library? Or do we have any example to show how to load pre-trained word embedding vectors using CPP or python? 

Thanks !

K.

**Comment by piiswrong** [comment]
you need to add src/operator/embedding.cc into amalgamation/mxnet-predict0.cc

**Comment by freddycct** [comment]
@piiswrong there is not such file `src/operator/embedding.cc`
it seems that the embedding code is now in `src/operator/tensor/indexing_op.cc`
But I have problems including it in `amalgamation/mxnet-predict0.cc`

```
In file included from jni/predictor.cc:4:
jni/../mxnet_predict-all.cc:38:10: fatal error: 'indexing_op-inl.cuh' file not found
#include <indexing_op-inl.cuh>
```

**Comment by piiswrong** [comment]
Pull master and try again.

**Comment by freddycct** [comment]
finally worked, thanks

**Comment by lancerkz** [comment]
Hi @piiswrong 
Thanks for quick response. I checked your update on python file. it works now

Hi @freddycct 
Thanks for sharing. Yes. I got same error message like yours when adding indexing_op.cc

Recap solution after @piiswrong 's update.  
1, #include "src/operator/tensor/indexing_op.cc" in mxnet_predict0.cc in the folder of amalgamation
2, make clean && make, again. 
3, you could find Embedding OP in generated mxnet_predict-all.cc.

Unfortunately, regarding the issue to use prediction CPP API to evaluate model generated by lstm_bucketing.py is still open. Embedding OP could be found now. but still missing other OP. 
Error message shows Operator SliceChannel again. 

I'll try to add SliceChannel manually, and keep your guys updated. 

Thanks !
K.

**Comment by lancerkz** [comment]
I got some time to play with it again. 
Here are my findings. 

for the model of lstm_bucketing.py from rnn. I added 

`
#include "src/operator/tensor/indexing_op.cc"
#include "src/operator/slice_channel.cc"
#include "src/operator/tensor/init_op.cc"
`

and prediction API could work with it now. 

Thanks for help !

K.
