### ISSUE TITLE
Linker error when building mlp.cpp with VS2015

### ISSUE THREAD

**Issue by Bumblebee1964** [dmlc/mxnet#5093]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows 10 64 bit

Compiler: VS2015 C++

Package used (Python/R/Scala/Julia): ----

MXNet version: Latest nightly Windows build 20170221, CUDA 8.0.61, cudnn 8.0v5.1

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
mlp.obj : error LNK2001: unresolved external symbol __imp_MXOptimizerFree
mlp.obj : error LNK2001: unresolved external symbol __imp_MXOptimizerFindCreator
mlp.obj : error LNK2001: unresolved external symbol __imp_MXOptimizerUpdate
error LNK2001: unresolved external symbol __imp_MXOptimizerCreateOptimizer

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Just compiled the mlp.cpp sample in a C++ VS2015 solution. This worked in an earlier install from MXNet but based on a version from MxNet.cpp with cudnnv3.1, CUDA 7.5 and VS2013. (entire MXNet version in a separate folder structure).
2.
3.

## What have you tried to solve it?

1. Tried to find where the symbols that cannot be linked are defined. Can't find those in the source code on Github.
2. Googled for a solution
3.

**Comment by webbery** [comment]
I have the same problem but the MxnetTestApp can pass. I compared the full command of two project. They looks same. My code only include <mxnet-cpp/MxNetCpp.h>. I try to write CMakeLists or add `#progma command(lib,'libmxnet.lib')` but the link error remain occured.
And my link error is:
~~~
mnist.obj : error LNK2019: unresolved external symbol __imp__MXGetLastError
...
~~~
and my link command is
~~~
/OUT:"E:\test\mnist\Debug\mnist.exe" /MANIFEST /NXCOMPAT /PDB:"E:/test/mnist/Debug/mnist.pdb" /DYNAMICBASE "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib" "D:\DevLib\mxnet\lib\libmxnet.lib" /IMPLIB:"E:/test/mnist/Debug/mnist.lib" /DEBUG /MACHINE:X86 /SAFESEH /INCREMENTAL /PGD:"E:\test\mnist\Debug\mnist.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"mnist.dir\Debug\mnist.exe.intermediate.manifest" /ERRORREPORT:PROMPT /NOLOGO /LIBPATH:"D:\Program Files (x86)\Visual Leak Detector\lib\Win32" /TLBID:1 
~~~
Does I copy the MxnetTestApp proj to my work place and change it to work?

**Comment by Bumblebee1964** [comment]
Hi, I have solved the problem. I have built the latest release of MxNet toegther. I cloned the code for the C++ API through a link on the MxNet website. These two or not compatible! You need to download/clone the latest version of the C++ API from Github. For the rest the procedure for installing etc. remains the same. Basically only the header files are different between the 2 c++ API versions.

**Comment by webbery** [comment]
I have solved my problem too. My project base on WIN32 platform. But when I used x64 compiler "Visual Studio 14 Win64" this project compiled successfully. I use the nighty build version without gpu for code test.
