### ISSUE TITLE
multiple inputs fail on amalgamation

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#5095]
@piiswrong, can you please help me with the java amalgamation?

I have the following architecture defined in python
```
def model(): # best performing feb 16 2017
    x = mx.sym.Variable('x') # with shape (batch_size,)
    y = mx.sym.Variable('y') # with shape (batch_size, N)

    x_embedding = mx.sym.Embedding(
        data=x,
        input_dim=20000,
        output_dim=40,
        name='x_embedding'
    ) # x_embedding produces (batch_size, 40)

    fc1  = mx.sym.FullyConnected(data=y, name='fc1', num_hidden=40)
    act1 = mx.sym.Activation(data=fc1, name='act1', act_type='tanh')

   # irrelevant code below...
```
in the java code when performing prediction, I defined the shapes as follow,
```
int [] xShape = { 1 };
Predictor.InputNode xInput = new Predictor.InputNode("x", xShape);

int [] yShape = { 1, N };
Predictor.InputNode yInput = new Predictor.InputNode("y", yShape);
```
What is the ordering when defining `Predictor.InputNode[]`? 
Should it be
`Predictor.InputNode[] inputs = new Predictor.InputNode[]{ xInput, yInput };`
or
`Predictor.InputNode[] inputs = new Predictor.InputNode[]{ yInput, xInput };`

It seems that the ordering matters, because I get different errors depending on how they are ordered. Note, it does seem that multiple inputs does not work in java-based amalgamation.

These are the errors I get, 
```
[18:50:30] jni/../mxnet_predict-all.cc:635: [18:50:30] jni/../mxnet_predict-all.cc:28772: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (40,82) to.shape=(40,1)
Exception in thread "main" org.dmlc.mxnet.MxnetException: [18:50:30] jni/../mxnet_predict-all.cc:28772: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (40,82) to.shape=(40,1)
	at org.dmlc.mxnet.Predictor.createPredictor(Native Method)
	at org.dmlc.mxnet.Predictor.<init>(Predictor.java:45)
	at MXNetPredictor.main(MXNetPredictor.java:68)

```
when I switch the ordering, 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fffafcc60b0, pid=39989, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_112-b16) (build 1.8.0_112-b16)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.112-b16 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libsystem_platform.dylib+0x60b0]  _platform_memmove$VARIANT$Haswell+0x210
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# ../hs_err_pid39989.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
./mxnet_predictor.sh: line 6: 39989 Abort trap: 6           java -Djava.library.path=${MXNET_HOME}/lib -cp ${CLASSPATH} MXNetPredictor
```

**Comment by Piyush3dB** [comment]
@freddycct I've been using JS amalgamation lately.  That error is coming from the shape inference module complaining that something isn't right in the shape dimensions you've specified.  Multiple inputs should be supported because the same `c_predict_api` functions are exported to JS as the ones used in the shared object.  As a sanity check, are you successfully able to infer the correct shapes given your input dimensions in your python version?

**Comment by freddycct** [comment]
The python version works, but not the Java JNI version, something is probably wrong with the infer shapes, i am still debugging the C++ codes,

also, i am not very sure whether the shape i specified is correct,

whether `int [] yShape = { 1, N };` can be `int [] yShape = { N };`

**Comment by freddycct** [comment]
i found out more, it seems that 
```
CopyAttr(g.indexed_graph(),
             g.GetAttr<nnvm::ShapeVector>("shape"),
             &arg_shapes, &out_shapes, &aux_shapes);
```
put the wrong values into `arg_shapes`,
mxnet_predict-all.cc is providing the wrong shape for the second input when the shape of second input and first input is different.

**Comment by freddycct** [comment]
there's definitely a bug, i am debugging and will submit a PR later.

**Comment by freddycct** [comment]
@jdeng

#5109 pull request
