### ISSUE TITLE
where can I  set the environment variables for mxnet ?

### ISSUE THREAD

**Issue by janelu9** [dmlc/mxnet#5097]
such as  MXNET_CPU_PRIORITY_NTHREADS,
In which file? config.mk?

**Comment by lilhope** [comment]
I think(not sure),if you want to set this environment variable only once,do `export  MXNET_CPU_PRIORITY_NTHREADS` before you run your code. If not, modify the config.mk and  compile your mxnet

**Comment by janelu9** [comment]
@lilhope maybe your first method is right 
I find “ Setting the environment export MXNET_CUDNN_AUTOTUNE_DEFAULT=1 sometimes also helps.” in the documents
