### ISSUE TITLE
fatal error:cub/device/device_radix_sort.cuh: No such file or directory

### ISSUE THREAD

**Issue by poorfriend** [dmlc/mxnet#5113]
In file included from src/operator/tensor/././sort_op.h:85:0,
                 from src/operator/tensor/./indexing_op.h:24,
                 from src/operator/tensor/indexing_op.cu:8:
src/operator/tensor/./././sort_op-inl.cuh:10:44: fatal error: cub/device/device_radix_sort.cuh: No such file or directory
 #include <cub/device/device_radix_sort.cuh>
                                            ^
compilation terminated.
make: *** [build/src/operator/tensor/indexing_op_gpu.o] Error 1

**Comment by poorfriend** [comment]
I know, I fix it by  downloading the whole newsest code

**Comment by Soonhwan-Kwon** [comment]
I encoutered same error and for who visit this issue again, it was caused by the new submodule cub(https://github.com/NVlabs/cub). git clone this new submodule in your mxnet home , it will be okay

**Comment by JasonBrody** [comment]
Thanks Kwon! It works!

**Comment by HawkAaron** [comment]
I cloned all the code recursively, but still encoutered this error, do you know how to fix it ?
