### ISSUE TITLE
numpy like matrix operation for ndarray and symbol variable

### ISSUE THREAD

**Issue by zcyang** [dmlc/mxnet#512]
mxnet is awesome for implementing some commonly used models like mlp and convnets. To develop some new models requires some efforts.

The current support of numpy like matrix operation for ndarray and symbol variable is very limited. These are important to develop new models that are not supported by the existing layers.

It will be perfect if the matrix indexing, slicing, summation, multiplication, reshaping etc are supported well. Or those operations are supported in C++, but the python interface is not available yet? Where can I find some examples?

**Comment by tqchen** [comment]
Yes, the idea is to add operations as we need and make it easier to do so. 

- Currently, there is a PythonOp that allows you to directly write operator in python.
- More optimized operator can be added from c++ side, using mshadow, with no knowledge of GPU programming.

So either you can quickly hack up what you need using numpy, or add important ops in c++ as we need to add them(open up issues on what we want and we can discuss how it can be added)

We are also continuing to enhance the interface to make adding new operations easier than the current way.

**Comment by zcyang** [comment]
May I ask are there any examples on how to hack with PythonOp for some numpy like operations?

**Comment by tqchen** [comment]
Yes here it is https://github.com/dmlc/mxnet/tree/master/example/numpy-ops

Please also feel free to open issue for specific Op you want as you encounter problems, we can discuss more in detail on how things can be added :) Most of which should be pretty straight forward

**Comment by tqchen** [comment]
@piiswrong I think we want to highlight NumpyOp somewhere in the doc(maybe python/index.md), can you open a PR for this?

**Comment by zcyang** [comment]
many thanks!

**Comment by piiswrong** [comment]
I think we need to few HOWTO pages and link them in the root README
1) How to create new operators (c++ and numpy)
2) How to write custom training loop

**Comment by tqchen** [comment]
move discussion to #586
