### ISSUE TITLE
HOWTO pages for key use cases

### ISSUE THREAD

**Issue by piiswrong** [dmlc/mxnet#513]
Given the the questions we have been getting, I think it's time we create some succinct  guides for key use cases:
+ How to create new operators (c++ & python & julia & ...)
+ How to create custom training loops

Also, since few people read the hole doc and nobody read FAQ before AQ, we should link them in bold somewhere you can't miss, like in the root README.md

I can write the python operator part. Can someone help with the rest

**Comment by tqchen** [comment]
Let us do it. I think we can put it on python/index.md
here is the current guide for c++ ops https://github.com/dmlc/mxnet/blob/master/doc/developer-guide/operator.md

@piiswrong  would be great if you can push numpy ops

**Comment by pluskid** [comment]
The Julia side user defined operator is not ready yet due to multi-thread callback issues dmlc/MXNet.jl#16. But I can add the Julia part for the howto once the implementation is ready.
