### ISSUE TITLE
Discussion and troubleshooting on PyPI (pip) installation (the newest 0.9.3 release)

### ISSUE THREAD

**Issue by szha** [dmlc/mxnet#5134]
The PyPI [mxnet](http://mxnet.io) installation is now available with three variants:
- [mxnet](https://pypi.python.org/pypi/mxnet/) on both `OSX` and `Linux`, based on `openblas`
- [mxnet-cu75](https://pypi.python.org/pypi/mxnet-cu75/) on `Linux`, supports `CUDA-7.5` and `cuDNN-5.1`
- [mxnet-cu80](https://pypi.python.org/pypi/mxnet-cu80/) on `Linux`, supports `CUDA-8.0` and `cuDNN-5.1`.
Note: `Windows` is NOT supported yet.

Mac/Linux users can install it via `pip install mxnet`. Be sure to update `pip` (`setuptools`) to the most recent version, by `pip install -U pip`. Example on `OSX`:

```bash
% pip search mxnet
mxnet-cu75 (0.9.3a3)  - MXNet is an ultra-scalable deep learning framework. This version uses CUDA-7.5.
mxnet-cu80 (0.9.3a3)  - MXNet is an ultra-scalable deep learning framework. This version uses CUDA-8.0.
mxnet (0.9.3a3)       - MXNet is an ultra-scalable deep learning framework. This version uses openblas.
% pip install mxnet
Collecting mxnet
  Downloading mxnet-0.9.3a3-cp27-cp27m-macosx_10_11_x86_64.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 193kB/s
Collecting numpy (from mxnet)
  Downloading numpy-1.12.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.4MB)
    100% |████████████████████████████████| 4.4MB 324kB/s
Installing collected packages: numpy, mxnet
Successfully installed mxnet-0.9.3a3 numpy-1.12.0
```

For users with GPU and desire to enjoy GPU acceleration, please make sure the prerequisites on the PyPI page are met, as copied here:
mxnet-cuxx packages support Linux platform only, and requires that [CUDA-7.5](https://developer.nvidia.com/cuda-downloads)/[CUDA-8.0](https://developer.nvidia.com/cuda-downloads) and [cuDNN-5.1](https://developer.nvidia.com/cudnn) are already installed, along with the proper [NVIDIA driver](http://www.nvidia.com/download/find.aspx). For package with CUDA-7.5 support on Linux, check [mxnet-cu75](https://pypi.python.org/pypi/mxnet-cu75/). For package with CUDA-8.0 support on Linux, check [mxnet-cu80](https://pypi.python.org/pypi/mxnet-cu80/)
For more instructions, check [CUDA Toolkit online documentation](http://docs.nvidia.com/cuda/index.html).

These packages are tested with `Mac OS X 10.10/10.11`, `ubuntu 14/16` and `Amazon Linux` with no problem. Please report any issues or installation difficulties or usage problems here, with detailed information. For having the debug output, please use `pip install -v mxnet`. Thanks.

**Comment by phunterlau** [comment]
big thanks. I have successfully installed `pip install mxnet-cu80` on CentOS 7 with `Anaconda` python.
<img width="837" alt="screen shot 2017-02-23 at 11 35 47 pm" src="https://cloud.githubusercontent.com/assets/1690881/23294582/f9dd5f8e-fa20-11e6-919f-19c8909b28ed.png">

**Comment by marklit** [comment]
Are there any plans to support installing pip-installed, GPU-accelerated builds on Windows in the near future?

**Comment by szha** [comment]
@marklit, sorry for the late reply. Definitely there's plan on releasing that eventually. I will see what I can do by the next release. Also, community contribution is always welcome!

**Comment by lxn2** [comment]
Hi @szha,

I pip installed mxnet and ran some basic training scripts from tests/python/train. On AWS's P2 instances it worked just fine. On G2.2xlarge instance I got "Illegal instruction":

`
[ec2-user@ip-172-31-9-113 mxnet]$ python tests/python/train/test_conv.py 
[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
[19:58:54] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(100,1,28,28)
[19:58:54] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(100,1,28,28)
INFO:root:Start training with [cpu(0)]
Start training with [cpu(0)]
Illegal instruction
`

Traceback:
```
(gdb) run
Starting program: /home/ec2-user/mxnet-virtenv/bin/python tests/python/train/test_conv.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /home/ec2-user/mxnet-virtenv/local/lib64/python2.7/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0
[New Thread 0x7fffed2bc700 (LWP 32515)]
[New Thread 0x7fffecabb700 (LWP 32516)]
[New Thread 0x7fffea2ba700 (LWP 32517)]
[New Thread 0x7fffe7ab9700 (LWP 32518)]
[New Thread 0x7fffe52b8700 (LWP 32519)]
[New Thread 0x7fffe2ab7700 (LWP 32520)]
[New Thread 0x7fffe02b6700 (LWP 32521)]
Missing separate debuginfo for /usr/lib64/libstdc++.so.6
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/43/4c339faa62ca4e59eb71572a60967fe54a69ad.debug
Missing separate debuginfo for /lib64/libgcc_s.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/3f/d5f89de59e124ab1419a0bd16775b4096e84fd.debug
[New Thread 0x7fffd4fd0700 (LWP 32522)]
[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
[19:35:10] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(100,1,28,28)
[New Thread 0x7fffc6e8e700 (LWP 32523)]
[New Thread 0x7fffc668d700 (LWP 32524)]
[New Thread 0x7fffc5e8c700 (LWP 32525)]
[New Thread 0x7fffc568b700 (LWP 32526)]
[New Thread 0x7fffc4e8a700 (LWP 32527)]
[19:35:10] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(100,1,28,28)
[New Thread 0x7fffbe216700 (LWP 32528)]
[New Thread 0x7fffbda15700 (LWP 32529)]
INFO:root:Start training with [cpu(0)]
Start training with [cpu(0)]

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7fffbda15700 (LWP 32529)]
0x00007fffd633b99a in sgemm_kernel () from /home/ec2-user/mxnet-virtenv/local/lib/python2.7/site-packages/mxnet/libmxnet.so
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.168.amzn1.x86_64 keyutils-libs-1.5.8-3.12.amzn1.x86_64 krb5-libs-1.13.2-12.40.amzn1.x86_64 libcom_err-1.42.12-4.40.amzn1.x86_64 libffi-3.0.13-16.5.amzn1.x86_64 libgomp-4.8.3-9.111.amzn1.x86_64 libselinux-2.1.10-3.22.amzn1.x86_64 openssl-1.0.1k-15.96.amzn1.x86_64 python27-libs-2.7.12-2.120.amzn1.x86_64 zlib-1.2.8-7.18.amzn1.x86_64
(gdb) bt
#0  0x00007fffd633b99a in sgemm_kernel () from /home/ec2-user/mxnet-virtenv/local/lib/python2.7/site-packages/mxnet/libmxnet.so
#1  0x0000000000000000 in ?? ()
```
Nvidia Driver version is 367.57.

**Comment by phunterlau** [comment]
Oh, the pip installation doesn't work with GPU plugin

**Comment by lxn2** [comment]
Hi @phunterlau, what do you mean?

**Comment by phunterlau** [comment]
em, I typed from cellphone...sorry. I was going to ask, did you install `mxnet-cu80` or `mxnet`? the later one doesn't have GPU support.

**Comment by lxn2** [comment]
Oh, I see. Thanks for the clarification! But shouldn't we have the `mxnet` installation be able to run on both GPU and CPU instances?

**Comment by phunterlau** [comment]
@lxn2 can you check if the CUDA version on your G2.2xlarge matches `mxnet` installation? if use CUDA 7.5, the old one, you might want to `pip install mxnet-cu75`. I guess the problem comes from CUDA version, since P2 is newer while G2.2xlarge is old which may use the old version.

**Comment by lxn2** [comment]
I installed CUDA 8.0 on the G2 and tested `mxnet-cu80` but still the same "Illegal Instruction". @szha @mli said to ask you if these were compiled with all flags so that it can run on older GPUs?

**Comment by szha** [comment]
@lxn2 Actually none of the CUDA_ARCH was turned on because the build was timing out https://github.com/dmlc/mxnet-distro/blob/master/pip_linux_cu80.mk#L55. It's relying on NVRTC instead.

**Comment by szha** [comment]
@lxn2 The trace you pasted seems not to be using GPU.

**Comment by jkbradley** [comment]
Does this thread cover `mxnet-mkl`?  If so, I'm hitting issues with installing it via `pip`.  Running `pip install mxnet-mkl` returns error:
```
Collecting mxnet-mkl
  Could not find a version that satisfies the requirement mxnet-mkl (from versions: )
No matching distribution found for mxnet-mkl
```

Note that https://pypi.python.org/pypi/mxnet-mkl does not actually exist, though https://pypi.python.org/pypi/mxnet-mkl/0.9.3 does.

Thanks!

**Comment by szha** [comment]
@jkbradley thanks for bringing this up. This issue does not cover the mxnet-mkl since it hasn't been released yet.

I attempted an experimental release for MKL version based on 0.9.3. During the process, I caught some issues (which were later fixed in #5085 etc), so I took down all the uploaded artifacts. MKL version will be available for the next release.

**Comment by jkbradley** [comment]
Oh OK thanks @szha for the quick response!  Some of the docs indicate that it has been released, so you may get more queries about it: http://mxnet.io/get_started/index.html

**Comment by szha** [comment]
@jkbradley OK, MKL variant is available now for version 0.9.5. Try ```pip install mxnet-mkl```

**Comment by szha** [comment]
0.10.0 has been released for a while and there hasn't been many activities on this thread. Closing now.

**Comment by eric-haibin-lin** [comment]
Re: Illegal Instruction, I think the reason is that the DLAMI was using the master branch of openblas instead of stable release, and that version of openblas is buggy.
