### ISSUE TITLE
LSTMCell unroll error on GPU

### ISSUE THREAD

**Issue by saicoco** [dmlc/mxnet#5139]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
centOS, Tesla K40
Compiler:
gcc4.9.X
Package used (Python/R/Scala/Julia):
python
MXNet version:
0.9.4
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
bfc75a23aa2bdba7e158ec12afdcdb1658bf060b
If you are using python package, please provide

Python version and distribution:
python2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

This is part of my code:  
```python
audio_data = mx.sym.Variable(name='audio_data')
face_data = mx.sym.Variable(name='face_data')
softmax_label = mx.sym.Variable('softmax_label')
    
# LSTM1, LSTM2
rnn1 = mx.rnn.LSTMCell(num_hidden=256, prefix='lstm1_')
rnn1_outputs, rnn1_states = rnn1.unroll(length=49, inputs=audio_data, merge_outputs=False)
rnn2 = mx.rnn.LSTMCell(num_hidden=256, prefix='lstm2_')
rnn1_out_expand = [mx.sym.expand_dims(item, axis=1) for item in rnn1_outputs]
rnn1_out_concat = mx.sym.Concat(*rnn1_out_expand, dim=1, num_args=49)
rnn2_outputs, rnn2_states = rnn2.unroll(length=49, inputs=rnn1_out_concat, merge_outputs=False)
    
rnn1_last_out = mx.sym.Reshape(data=rnn1_outputs[-1], shape=(-1, 256), name='rnn1_last_out_reshape')
rnn2_last_out = mx.sym.Reshape(data=rnn2_outputs[-1], shape=(-1, 256), name='rnn2_last_out_reshape')
rnn_outputs = mx.sym.Concat(rnn1_last_out, rnn2_last_out, num_args=2, dim=1, name='rnn_outputs')
```  

I just wanna concat the last outputs of `rnn1` and `rnn2`, here `audio_data_shape=(98, 49, 75)`, when I
run the code on CPU, it's OK; but when I run it on GPU, it will raise this:  

```
[19:19:24] src/operator/./slice_channel-inl.h:170: Check failed: dshape[real_axis] % param_.num_outputs == 0 (49 vs. 0) num_outputs (98) does not divide input dimension 0 (49).
```  

I figure out the `unroll()`, `inputs` has three  ways to precess, here the `rnn1_outputs` is `list`:  

1. Concat it at time axis;
2. input `rnn1_outpus`  

Above two things I have tryied, the error raises about `slicechannel` whenever I do in one of the two ways. Is there something different on CPU or GPU for LSTMCell?

**Comment by sxjscience** [comment]
The error message seems reasonable as we may need to use `rnn1.unroll(length=98, inputs=audio_data, merge_outputs=False)` since audio_data_shape is (98, 49, 75).

**Comment by sxjscience** [comment]
In fact I cannot repeat the error, I've run the following code and it works well for the latest MXNet.
```python
import mxnet as mx
audio_data = mx.sym.Variable(name='audio_data')
face_data = mx.sym.Variable(name='face_data')
softmax_label = mx.sym.Variable('softmax_label')
    
# LSTM1, LSTM2
rnn1 = mx.rnn.LSTMCell(num_hidden=256, prefix='lstm1_')
rnn1_outputs, rnn1_states = rnn1.unroll(length=49, inputs=audio_data, merge_outputs=False)
rnn2 = mx.rnn.LSTMCell(num_hidden=256, prefix='lstm2_')
rnn1_out_expand = [mx.sym.expand_dims(item, axis=1) for item in rnn1_outputs]
rnn1_out_concat = mx.sym.Concat(*rnn1_out_expand, dim=1, num_args=49)
rnn2_outputs, rnn2_states = rnn2.unroll(length=49, inputs=rnn1_out_concat, merge_outputs=False)
    
rnn1_last_out = mx.sym.Reshape(data=rnn1_outputs[-1], shape=(-1, 256), name='rnn1_last_out_reshape')
rnn2_last_out = mx.sym.Reshape(data=rnn2_outputs[-1], shape=(-1, 256), name='rnn2_last_out_reshape')
rnn_outputs = mx.sym.Concat(rnn1_last_out, rnn2_last_out, num_args=2, dim=1, name='rnn_outputs')
exe = rnn_outputs.simple_bind(ctx=mx.gpu(), audio_data=(98, 49, 75))
```

**Comment by saicoco** [comment]
@sxjscience , it works well in CPU, Is it also works well  about GPU?

**Comment by sxjscience** [comment]
I could run the code successfully on my machine using `ctx=mx.gpu()`

**Comment by saicoco** [comment]
Yeap, it works well on GPU, also I try other apart of symbol and it works well. I run my code on two gpus previous, it's raise above error; I try one gpu, it raise following:  

```
/mxnet/mshadow/mshadow/././././cuda/tensor_gpu-inl.cuh:56: too large launch parameter: MapReduceKeepDim1[256,1,1]
```  
It could be error about the framewok I designed.BTW,I ask a naive problem..how to location the line error raises when it report lots of information about c++ not python

**Comment by sxjscience** [comment]
Such an error message indicates that a failed infer_shape call. You can insert lines like `rnn_outputs.infer_shape(audio_data=(98, 49, 75))` in the symbol constructing function and test if it could run successfully.

**Comment by saicoco** [comment]
Get~~~, thanks a lot
