### ISSUE TITLE
Why does my net keep output 'rmse=nan' ?

### ISSUE THREAD

**Issue by metorm** [dmlc/mxnet#5155]
Environment info
Operating System:Windows 10

python(Anaconda) on CPU

MXNet version:0.92

-------------

Here is my net structure, a simple FC net used for Regression:

    # define net
    net_in = mx.symbol.Variable('data')
    net_in = mx.symbol.Flatten(data=net_in)

    net_label = mx.symbol.Variable('softmax_label')

    fc1 = mx.symbol.FullyConnected(data=net_in, name='fc1', num_hidden=512)
    act1 = mx.symbol.Activation(data=fc1, name='relu1', act_type="relu")
    fc2 = mx.symbol.FullyConnected(data=act1, name='fc2', num_hidden=512)
    act2 = mx.symbol.Activation(data=fc2, name='relu2', act_type="relu")
    fc5 = mx.symbol.FullyConnected(data=act2, name='fc5', num_hidden=net_out_size)
    net_out = mx.symbol.LinearRegressionOutput(data=fc5, label=net_label, name='net_out')

But, as the train starts, all I get is 'rmse=nan':

```
INFO:root:Epoch[3] Batch [4900] Speed: 12179.05 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5000] Speed: 12748.44 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5100] Speed: 12527.91 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5200] Speed: 12115.77 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5300] Speed: 12547.50 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5400] Speed: 12844.48 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5500] Speed: 12728.28 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5600] Speed: 12336.30 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5700] Speed: 11458.47 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5800] Speed: 11047.26 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [5900] Speed: 10428.04 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [6000] Speed: 11419.49 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [6100] Speed: 11692.42 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [6200] Speed: 12641.62 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [6300] Speed: 12427.80 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [6400] Speed: 12343.95 samples/sec     Train-rmse=nan
INFO:root:Epoch[3] Batch [6500] Speed: 12331.94 samples/sec     Train-rmse=nan
INFO:__main__:Epoch[3] Train-rmse=nan
INFO:__main__:Epoch[3] Time cost=26.430
INFO:__main__:Epoch[3] Validation-rmse=nan
INFO:root:Epoch[4] Batch [100]  Speed: 12373.45 samples/sec     Train-rmse=nan

```

When I use smaller net (with fc layer size = 256), The net gives `rmse=inf` at the start of the training, then it converges soon. But when I increase the `num_hidden` to `512`, I get these `nan`s. I can understand how multiply  & add computation gives 'nan'.

Anyone provide me some suggestion? Thank you!

By the way, May be my problem is not linear, is there any better alternative to my last layer `mx.symbol.LinearRegressionOutput` ?

**Comment by metorm** [comment]
Well, normalizing my input to [0,1] solves this issue.
Through its still unknown why the output is `nan` instead of `inf` in this case.

**Comment by salemmohammed** [comment]
@metorm I have the same issue with train_mnist.py and MLP. I got the output nan or infa.
My data is the Mnist dataset. 
How you solved your problem ?
@ 5516
