### ISSUE TITLE
Concat operator supports concating at dimension zero?

### ISSUE THREAD

**Issue by yang1fan2** [dmlc/mxnet#516]
Hi
I noticed that concat operator only support concating at dimension one currently. For RNN, concating output of LSTMs before Softmax (i.e. concat all the batches from different locations among a sentence) will speed up the training process substantially.
Thanks;

**Comment by tqchen** [comment]
Yes, this can be done by extending the https://github.com/dmlc/mxnet/blob/master/src/operator/channel_op_common.h to add a concat dimension argument.

Note that mshadow's concat and slice support along arbitrary dimension. But we need to add it :)

Are you interested in contributing? Also note although mshadow is templated, we can either enumerate dim with template, or do some reshape trick, to reshape to a 3D tensor and concat on dim 1. So it is general for any dimension

**Comment by yang1fan2** [comment]
Sure, I'll try
Thanks;

**Comment by tqchen** [comment]
thanks to @yang1fan2 this is now supported

**Comment by tqchen** [comment]
#650
