### ISSUE TITLE
do predictor in amalgamation support gpu boosting?

### ISSUE THREAD

**Issue by xinghedyc** [dmlc/mxnet#5171]
I find it it's slow when just using cpu to do inference.

**Comment by piiswrong** [comment]
If you are using gpu why use amalgamation?

**Comment by xinghedyc** [comment]
Thanks for your relpy ,this is because I have just seen the example/warpctc/ocr_predict.py which uses amalgamation predictor,
so it would be better to just use module API to do inference?

**Comment by piiswrong** [comment]
Yes. Amalgamation is only for deploying to embedded devices etc

**Comment by xinghedyc** [comment]
Thank you, I got it.
