### ISSUE TITLE
BUG in mx.rnn.FusedRNNCell API?

### ISSUE THREAD

**Issue by lilhope** [dmlc/mxnet#5177]
I use the mx.rnn.FusedRNNCell API as follow:
```
a = mx.sym.Variable('data')
b = mx.sym.Embedding(data=a,input_dim=100,output_dim=20)
cell = mx.rnn.FusedRNNCell(num_hidden=128,num_layers=2,mode='lstm',dropout=0.5)
output,_ = cell.unroll(length=16,inputs=b)
last_output = output[-1]
```
then I set the data_shape to infer the shape of `last_output`:
```
#data_shape:(batch,length)
data_shape ={'data',(1,16)}
last_output.infer_shape(**data_shape)
```
It cause the `error: src/operator/./slice_channel-inl.h:173: Check failed: dshape[real_axis] % param_.num_outputs == 0 (1 vs. 0) num_outputs (16) does not divide input dimension 1 (1).`    
I see the output of `mx.symbol.RNN()`,the shape of it is `[16L,1L,128L]`,so maybe the `mx.sym.SliceChannel(outputs,axis=axis,num_outputs=length,squeeze_axis=1)` cause this error.

**Comment by piiswrong** [comment]
need to change that line to `mx.sym.SliceChannel(outputs,axis=0,num_outputs=length,squeeze_axis=1)`
will fix later

**Comment by lilhope** [comment]
@piiswrong Nice!
