### ISSUE TITLE
Infer_shape error I don't understand.

### ISSUE THREAD

**Issue by Techro-Raj** [dmlc/mxnet#5185]
I'm trying to write a network to solve binary classification. I am using logistic regression for the loss function.
```import mxnet as mx
import numpy

batch_size = 1

train_iter = mx.io.CSVIter(data_csv="feature_train_v1.csv", data_shape=(1,50),
                   label_csv="label_train_v1.csv", batch_size=batch_size)

val_iter = mx.io.CSVIter(data_csv = "feature_validate_v1.csv", data_shape=(1,50),
                    label_csv="label_validate_v1.csv", batch_size = batch_size)

net = mx.sym.Variable('data')
Y = mx.symbol.Variable('gt_label')
net = mx.sym.FullyConnected(data=net, name='fc1', num_hidden=50)
net = mx.sym.Activation(data=net, act_type="sigmoid")
out = mx.sym.LogisticRegressionOutput(data=net, label=Y, name="out") # Calculate the Loss !

model = mx.mod.Module(
    symbol = out,
    data_names = ['data'],
    label_names = ['gt_label']
)

# Evaluate:
def log_loss(predict, label): # log loss function
    loss = 0
    label = label.T.reshape((-1,))
    prediction_correctness = 0
    for i in range(label.shape[0]):
        if predict[i] == label[i]:
            prediction_correctness = 1
        else:
            prediction_correctness = 0
        loss += prediction_correctness * np.log(predict[i]) + (1-label[i])* np.log(1-predict[i])
    return np.exp(loss/predict.size)

metric = mx.metric.create(log_loss)

# train the network
model.fit(train_iter, eval_data=val_iter, eval_metric = metric,
            optimizer_params={'learning_rate':0.01, 'momentum': 0.9},
            num_epoch=1000)

model.score(val_iter, metric)

# Predict:

# label parameter necessary?
test_iter = mx.io.CSVIter(data_csv = "feature_test_v1.csv", data_shape=(1,50), batch_size = batch_size)
model.predict(test_iter).asnumpy()
```

I followed the api and tutorial, but I'm not sure what I'm doing wrong.
Here is my error:
[12:44:26] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/./logging.h:300: [12:44:26] src/c_api/c_api_symbolic.cc:385: InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]fc1_weight
	[2]fc1_bias
	[3]gt_label

Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x000000010dac61b8 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010e0bd08f _ZN5mxnet14MatchArgumentsIN4nnvm6TShapeEEEvRKNS1_12IndexedGraphERKNSt3__113unordered_mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEET_NS6_4hashISD_EENS6_8equal_toISD_EENSB_INS6_4pairIKSD_SE_EEEEEEPNS6_6vectorISE_NSB_ISE_EEEEPKc + 3519
[bt] (2) 2   libmxnet.so                         0x000000010e0bb268 MXSymbolInferShape + 1368
[bt] (3) 3   _ctypes.so                          0x00000001083adf57 ffi_call_unix64 + 79

infer_shape error. Arguments:
  data: (1, 1L, 50L)
  softmax_label: (1,)
Traceback (most recent call last):
  File "neuralnet.py", line 42, in <module>
    num_epoch=1000)
  File "/Applications/anaconda/lib/python2.7/site-packages/mxnet/module/base_module.py", line 388, in fit
    for_training=True, force_rebind=force_rebind)
  File "/Applications/anaconda/lib/python2.7/site-packages/mxnet/module/module.py", line 345, in bind
    grad_req=grad_req)
  File "/Applications/anaconda/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 187, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/Applications/anaconda/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 279, in bind_exec
    shared_group))
  File "/Applications/anaconda/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 483, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/Applications/anaconda/lib/python2.7/site-packages/mxnet/symbol.py", line 542, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/Applications/anaconda/lib/python2.7/site-packages/mxnet/symbol.py", line 609, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/Applications/anaconda/lib/python2.7/site-packages/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [12:44:26] src/c_api/c_api_symbolic.cc:385: InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]fc1_weight
	[2]fc1_bias
	[3]gt_label

Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x000000010dac61b8 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010e0bd08f _ZN5mxnet14MatchArgumentsIN4nnvm6TShapeEEEvRKNS1_12IndexedGraphERKNSt3__113unordered_mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEET_NS6_4hashISD_EENS6_8equal_toISD_EENSB_INS6_4pairIKSD_SE_EEEEEEPNS6_6vectorISE_NSB_ISE_EEEEPKc + 3519
[bt] (2) 2   libmxnet.so                         0x000000010e0bb268 MXSymbolInferShape + 1368
[bt] (3) 3   _ctypes.so                          0x00000001083adf57 ffi_call_unix64 + 79

I'm new to MXNet, so if anyone can help me, thank you!

**Comment by piiswrong** [comment]
you need to add label_name='gt_label' to your csviter constructor

**Comment by Techro-Raj** [comment]
Thanks. I'm having trouble figuring out the label shape. In my label csv file, it has 1 column for the output with many rows. In my data input files I have 50 features. From what I understand, data_shape reshapes each row, so I simply kept the row shape the same by entering (1,50). Wouldn't the label shape just be (1,1)? Except I'm getting an infer shape error when I do that.
