### ISSUE TITLE
singleton manager

### ISSUE THREAD

**Issue by mli** [dmlc/mxnet#52]
a singleton manager to guarantee the destruct order. one reason is that, any class needs to destroy narray should guarantee engine is still alive because narray calls `Engine::Get()->PushDelete()`

an example solution:
```
struct Singleton {
    static KVStore store;
   // others 
    static Engine engine;
};
Engine::Get() { return &Singleton::engine; }
```

**Comment by tqchen** [comment]
Will use GetSharedRef instead to ensure destruction order
