### ISSUE TITLE
How to estimate the MXNet gpu memory consumption? 

### ISSUE THREAD

**Issue by ZiJianZhao** [dmlc/mxnet#5208]
I've implement a encoder-decoder model for machine translation task. 
The lstm implementation is like that in mxnet/example/rnn/old/lstm/py.
And the basic setup is as follows:
```Python
    num_buckets = 5
    batch_size = 64
    num_layers = 1
    enc_input_size = 50000
    dec_input_size = 50000
    num_embed = 400
    num_hidden = 800
    num_label = 50000
    encoder_mode = 'lstm'
    decoder_mode = 'lstm'
```
But the memory consumption is puzzling, I try two experiments with different settings:
 1. embed: 100, hidden: 200, memory: 1222mb
 2. embed: 400, hidden: 800, memory: 2895mb

There are two puzzling things:
 1. The memory consumption is too large compared to the theoretically computed memory for parameters.
 2. It seems to consume more memory than pytorch with same network architecture. (maybe due to my poor coding way, but how does coding way influence the memory consumption?)

So I have three questions:
 1. Is it normal for a network with the settings above to consume so much memory?
 2. How does the coding way influence the memory consumption?
3. How to estimate the MXNet gpu memory consumption?

**Comment by janelu9** [comment]
almost the same as cpu cost？

**Comment by ZiJianZhao** [comment]
The large memory consumption is due to the implementation of the older version. In the latest version, the group has fix this issue and the memory consumption is normal now.

**Comment by mcxkarakoc** [comment]
.
