### ISSUE TITLE
Why batch size need to be smaller in NDArrayIter?

### ISSUE THREAD

**Issue by junranhe** [dmlc/mxnet#521]
I construct a NdarrayIter for extract the features online, so my data size == batch_size, 
and throw a python error:
python/mxnet/io.py", line 175, in __init__
"batch_size need to be smaller than data size when not padding."

**Comment by pluskid** [comment]
It seems to be a bug that was fixed before and then overwritten in a recent complicated merging.

**Comment by tqchen** [comment]
i.c. maybe open a quick fix for this?
