### ISSUE TITLE
SequentialRNNCell simple_bind raise segmentation fault

### ISSUE THREAD

**Issue by saicoco** [dmlc/mxnet#5212]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 15.10
Compiler:
gcc4-9.x
Package used (Python/R/Scala/Julia):
Python
MXNet version:
0.9.4
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
bfc75a23aa2bdba7e158ec12afdcdb1658bf060b
If you are using python package, please provide

Python version and distribution:
python2.7 Anaconda4.0
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
```
[20:51:28] include/nnvm/./././op.h:514: Segmentation fault (core dumped)
```
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
```python
import mxnet as mx
def caption_module(num_lstm_layer, seq_len, vocab_size, num_hidden, num_embed, batch_size, dropout=0.):

    seq = mx.sym.Variable('word_data')
    label = mx.sym.Variable('softmax_label')
    image_feature = mx.sym.Variable('image_feature')
    image_embed = mx.sym.FullyConnected(data=image_feature, num_hidden=num_embed, name='img_embed')
    word_embed = mx.sym.Embedding(data=seq, input_dim=vocab_size, output_dim=num_embed, name='seq_embed')

    # Concat image_embed with word_embed in axis=1 (batch_size, length+1, num_hidden)
    image_embed_reshape = mx.sym.expand_dims(image_embed, axis=1, name='image_embed_expand_dims')
    embedd_feature = mx.sym.Concat(image_embed_reshape, word_embed, num_args=2, dim=1, name='embed_concat')

    stack = mx.rnn.SequentialRNNCell()
    for i in range(num_lstm_layer):
        stack.add(mx.rnn.LSTMCell(num_hidden=num_hidden, prefix='lstm_l%d_' % i))
    outputs, states = stack.unroll(length=seq_len+1, inputs=embedd_feature, merge_outputs=True)

    outputs_crop = mx.sym.crop(outputs, begin=(0, 1, 0), end=(batch_size, seq_len+1, num_embed))
    pred = mx.sym.Reshape(outputs_crop, shape=(-1, num_hidden))
    pred = mx.sym.FullyConnected(pred, num_hidden=vocab_size, name='pred_fc')
    label = mx.sym.Reshape(label, shape=(-1,))
    softmax_output = mx.sym.SoftmaxOutput(data=pred, label=label, name='softmax')
    return softmax_output

if __name__ == '__main__':
    lstm = caption_module(num_lstm_layer=2, seq_len=100, vocab_size=1000, num_hidden=256, num_embed=256, batch_size=12)
    lstm_exec = lstm.simple_bind(ctx=mx.cpu(), is_train=False, word_data=(12, 100), softmax_label=(12, 100), image_feature=(12, 4096))
```
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

## What have you tried to solve it?  

1. Set `print xxx` to check carsh, such as `bind` in `bucketing_module`, then `bind` in `module`, `DataParallelExecutorGroup`, in the end, I find it in method `bind` of `symbol`. However, when the `bind` 
in `symbol` complete, it should return `executor`, but it dumps.  

2.Track `op.h 514`, I find following code:  
```c++
CHECK(idx < data_.size() && data_[idx].second)
        << "Attribute " << attr_name_
        << " has not been registered for Operator " << op->name;  
```
I guess it could happen in `data_[idx]`, `data_[idx]` should visit somewhere wrong.

ps: this sym is a part of [image caption-NIC](https://arxiv.org/pdf/1411.4555.pdf) I relize

**Comment by piiswrong** [comment]
Your code works fine on my machine. Try git pull && git submodule update && make clean && make

**Comment by saicoco** [comment]
@piiswrong, Thanks, it works well after update~~~~ maybe I should follow with the pull&&request all the time, then I will not confuse next time
