### ISSUE TITLE
About assigning value to a tensor

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#522]
Thank you for the awesome package! I'm programming using MXNet and have a question about the way we assign value to tensor, e.g. https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py#L166 Can we directly access the original value without [:] added? I've tried that and find no problem. But https://github.com/dmlc/mxnet/blob/master/doc/tutorial/new_op_howto.md points out that adding [:] is a necessity. I must have missed some critical part of the design.

**Comment by piiswrong** [comment]
with out [:] you are allocating a new ndarray (or numpy.ndarray) to store the results. This will hurt performance and sometimes correctness.
I would keep the [:] unless I really want to allocate a new array

**Comment by tqchen** [comment]
Without [:], actually what was happened was the old ndarray is discard, and the variable now stores an float value in python. So the correctness of code depend on how you use it

**Comment by sxjscience** [comment]
Thank you very much @piiswrong @tqchen ! I've figured out the difference now.
