### ISSUE TITLE
How to create a custom GPU operation with custom CUDA kernels for computation

### ISSUE THREAD

**Issue by xbkong** [dmlc/mxnet#5233]
Although mxnet documentation did mention that it is possible to Use C++/mshadow and CUDA to create custom operations, it has no real examples of how to used a custom CUDA kernel (taking gpu pointers) as part of a custom operation. Can anyone provide a simple example of this flow?

**Comment by luoyetx** [comment]
You can refer to roi_pooling operator inside mxnet, [roi_pooling-inl.h](https://github.com/dmlc/mxnet/blob/master/src/operator/roi_pooling-inl.h), [roi_pooling.cc](https://github.com/dmlc/mxnet/blob/master/src/operator/roi_pooling.cc) and [roi_pooling.cu](https://github.com/dmlc/mxnet/blob/master/src/operator/roi_pooling.cu).

**Comment by Ldpe2G** [comment]
what about this one: https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/ndarray_softmax.py

**Comment by xbkong** [comment]
Thanks
