### ISSUE TITLE
Singleton dimension get dropped during shape inference

### ISSUE THREAD

**Issue by pluskid** [dmlc/mxnet#524]
It seems if the final output is of dimension 1, (i.e. shape `(N,1)` with mini-batch size `N`), the singleton dimension is dropped. This might be reasonable for single dimension softmax output. But this special treatment makes the rest of the story (e.g. multi-output softmax and especially regression) less consistent and could confuse people a lot especially when the error message about dimension is buried in the C++ side.

I think it might be sensible to leave the shape as what it is. i.e. the output of a dense layer with `num_hidden=10` is simply of size `(N,10)`, while `num_hidden=1` is simply `(N,1)` (instead of `(N,)`).

(A side note: it seems our linear regression output layer only support scalar output?)

Ref: dmlc/MXNet.jl#20

**Comment by piiswrong** [comment]
responding to side note, I think I pushed a patch to make it support vector output

**Comment by pluskid** [comment]
Closing because after a while I successfully convinced myself that this is fine...
