### ISSUE TITLE
Uploading to shinyapps

### ISSUE THREAD

**Issue by seuriously** [dmlc/mxnet#5240]
Hi guys, just found this amazing package.
I was trying to upload to shinyapps.io but stumble upon this error:
```
Error: Unable to retrieve package records for the following packages:
- "mxnet"
```

knowing that mxnet is not in CRAN repository and different installation than just devtools::install_github(),
is it possible to make an app in shinyapps with this package?

thanks.

**Comment by jeremiedb** [comment]
If using your own shiny server, you absolutly can use mxnet. 
I haven't done it on shinyapps, but it shouldn't be an issue either. I think your issue may likely be of the same kind as one discussed here: https://groups.google.com/forum/#!topic/shiny-discuss/l6nug9hMh7g

**Comment by seuriously** [comment]
Hi, thanks for the tips. 
However, both devtools::install_github("dmlc/mxnet") and devtools::install_github("dmlc/mxnet/tree/master/R-package") throws the same error.

**Comment by statist-bhfz** [comment]
You should follow the official installation instructions: http://mxnet.io/get_started/setup.html#overview

**Comment by seuriously** [comment]
Hi, thanks for the suggestion.
I tried adding these on first line of my codes
`  install.packages("drat", repos="https://cran.rstudio.com")
  drat:::addRepo("dmlc")
  install.packages("mxnet")

library(drat)
library(mxnet)`

yet still shows the same original error.
Any other way?

**Comment by thirdwing** [comment]
The drat is only for Windows and OSX. shinyapps.io should use Linux servers.

I don't think there is a simple method to deploy app on shinyapps.io.

**Comment by seuriously** [comment]
I see. Alright man. So what I'm getting is right now it is not possible to deploy mxnet on shinyapps.io
Is that also why on ur github you didn't deploy it on shinyapps?

**Comment by thirdwing** [comment]
It is possible, but not an easy task.

You need to build a source mxnet package for Linux. Currently it is quite hard to make this happen.

So we didn't deploy the mxnet shiny app on shinyapps.io

If there are enough users want to use mxnet for shiny, we can try to talk with RStudio team on this.
