### ISSUE TITLE
in the mxnet0.9.4 has a bug in python35 win10, but in python27 is normal

### ISSUE THREAD

**Issue by whaozl** [dmlc/mxnet#5242]
![1](https://cloud.githubusercontent.com/assets/6327360/23580128/a57f9840-0136-11e7-853a-1c25ef0cf7b6.png)

![2](https://cloud.githubusercontent.com/assets/6327360/23580131/a93ea9f8-0136-11e7-910d-a267294d96e5.png)

**Comment by yajiedesign** [comment]
fix into https://github.com/dmlc/mxnet/pull/5268
wait merge

**Comment by whaozl** [comment]
thanks!
