### ISSUE TITLE
Installing MXNet on Python 3.6

### ISSUE THREAD

**Issue by jdchoi77** [dmlc/mxnet#5244]
I'm trying to install MXNet on Python 3.6.  I got the `libmxnet.so` compiled but `setup.py` by default installs MXNet on Python 2.7.  Is there an easy way to modify `setup.py` such that it will install the MXNet package on Python 3.6 (e.g., `/usr/local/lib/python3.6/dist-packages/`) instead?  I'm using Ubuntu Server 16.04 LTS.  Thank you!

**Comment by bravomikekilo** [comment]
maybe you can change the setup script under setup-util folder
change the `sudo python setup.py install` to `sudo python3 setup.py install`

**Comment by jdchoi77** [comment]
@bravomikekilo I have tried `sudo python3 setup.py install`, which puts the package under `/usr/local/lib/python3.6/dist-packages/` but it does not get recognized from the interpreter. For now, I setup `PYTHONPATH=/home/ubuntu/mxnet/python`, which gets the job done but will dig more into this issue. Thanks.
