### ISSUE TITLE
How to get symbol by symbol clocking in a module (including data iter)

### ISSUE THREAD

**Issue by jmerkow** [dmlc/mxnet#5246]
I am trying to obtain clocking information for each symbol (especially data) on a Module.

I built a simpleiter exactly like in the [tutorial](http://mxnet.io/tutorials/python/data.html), except for the following modification:

```
class SimpleIter:
...
    def next(self):
       ###### CHANGE Below
       time.sleep(np.random.randint(0,100)>75)
       ###### CHANGE Above
        if self.cur_batch < self.num_batches:
            self.cur_batch += 1
            data = [mx.nd.array(g(d[1]), ctx=self.ctx) for d,g in zip(self._provide_data, self.data_gen)]
            assert len(data) > 0, "Empty batch data."
            label = [mx.nd.array(g(d[1]), ctx=self.ctx) for d,g in zip(self._provide_label, self.label_gen)]
            assert len(label) > 0, "Empty batch label."
            return SimpleBatch(data, label)
        else:
            raise StopIteration
```

~25% of the time this data iter will be slower by 1 second.

Then I have the following fit:

```
n = 32
data = SimpleIter(data_names=['data'], 
                  data_shapes=[(n, 100)],
                  data_gen=[lambda s: np.random.uniform(-1, 1, s)],
                  label_names=['softmax_label'],
                  label_shapes=[(n,)], 
                  label_gen=[lambda s: np.random.randint(0, num_classes, s)],
                 num_batches=40)
data_par = mx.io.PrefetchingIter([data])

## time normal
mod = mx.mod.Module(symbol=net, context=[mx.gpu(0)])
mod.fit(data, num_epoch=5)

## time prefetched
mod = mx.mod.Module(symbol=net, context=[mx.gpu(0)])
mod.fit(data_par, num_epoch=5)
```

With my real network, I'd like to be able to see how much time my custom dataiter is costing me, as compared to the other symbols/layers in order to determine if I should spend time trying to speed up, and then if I was actually successful in speeding it up.

**Comment by tornadomeet** [comment]
could you try profiler in MXNet, it should help us to analyze the io part.

**Comment by jmerkow** [comment]
the profiler gives very low level times.  It does raise a question though, what is 'CopyCPU2CPU' Its taking up a lot of cycles.

**Comment by tornadomeet** [comment]
suggest remove `data_par = mx.io.PrefetchingIter([data])` and set engine type to `NaiveEngine` to profiler your code.

**Comment by jmerkow** [comment]
I wanted to compare the speed ups from prefetching. Is there a programmatic way to set the engine? Or only through ENV variables? 

Also, then still doesn't give a layer by layer timing, is there a call back or something I can run at the end of each symbol to display/collect the time, and/or the processing time?

**Comment by jmerkow** [comment]
The only way to do this it seems is to use a Monitor.  You can output the time and parse it out (or write to CSV or etc). Closing for now.
