### ISSUE TITLE
problem about a3c.py

### ISSUE THREAD

**Issue by achao2013** [dmlc/mxnet#5256]
i just learn the a3c example of RL, and i fell confused in the code of a3c.py as follows.

pi = module.get_outputs()[1]
 h = args.beta*(mx.nd.log(pi+1e-6)+1)
module.backward([mx.nd.array(adv), h])
i think, according to the previous code, the loss backward should be as follows:

pi = module.get_outputs()[0]
h=args.beta*module.get_outputs()[1]
module.backward([mx.nd.array(mx.nd.log(pi+1e-6)*adv), h])

do i make wrong concept of a3c or make a mistake about the use of python interface? @piiswrong

**Comment by piiswrong** [comment]
I could have made a mistake. Do you get better result after the change?

**Comment by achao2013** [comment]
i will have a try, what's the best result of current program? @piiswrong

**Comment by apeng5399** [comment]
in sym the return group is  mx.symbol.Group([policy, entropy, value]),  so in backward the 'h', is used to update for  entropy or value? @achao2013 @piiswrong

**Comment by achao2013** [comment]
i have pull request for this problem in #5473 @piiswrong

**Comment by apeng5399** [comment]
I use the A3C in my problem,I find the results was almost same for 1,2,8,16woker with 1,2,8,16cpu cores, Ilimit the Omp_num_thread=1,I check the cpu each python process have almost same cpu and memory, it show no effect . any advice? @piiswrong @achao2013
