### ISSUE TITLE
 I can not find  the python file of the definition model, only the official training of good models such as imagenet, vgg16, vgg19

### ISSUE THREAD

**Issue by whaozl** [dmlc/mxnet#5259]
https://github.com/dmlc/mxnet-model-gallery

http://data.mxnet.io/models/imagenet/

**Comment by whaozl** [comment]
**I want to have a python symbol Corresponding to the official pre-training model in the [imagenet models](http://data.mxnet.io/models/imagenet/)** for exmaple vgg16 vgg19

**Comment by lilhope** [comment]
At `/example/image-classfication/symbol/vgg`

**Comment by whaozl** [comment]
@lilhope  it is not vgg19, it is vgg16, and it is not Corresponding to the official pre-training model in the imagenet models(http://data.mxnet.io/models/imagenet/vgg/vgg16-symbol.json and http://data.mxnet.io/models/imagenet/vgg/vgg19-0000.params)
