### ISSUE TITLE
Adding random noise to optimizer.

### ISSUE THREAD

**Issue by eldercrow** [dmlc/mxnet#5270]
I am trying to implement the idea of https://arxiv.org/abs/1511.06807, adding random gradient noise during backpropagation. I've implemented it by modifying the old python code, and it works, but I would like to implement it into the current c++ optimizers (src/operator/optimizer_op-inl.h). 
I found that I need a random variable generator to do that, and found some relevant code in src/operator/dropout-inl.h. What I do not know is how to add a resource requester into optimizers. Can I simply use an old-fashioned way? Or can I add a resource requester in NNVM_REGISTER_OP?
Any help would be appreciated.

**Comment by sxjscience** [comment]
The implementation of sampling op may be helpful https://github.com/dmlc/mxnet/blob/master/src/operator/tensor/sample_op.h#L180.

**Comment by eldercrow** [comment]
This is exactly what I wanted. Thanks a lot!
