### ISSUE TITLE
got memory error 

### ISSUE THREAD

**Issue by maxpy** [dmlc/mxnet#528]
Here is my code:

num_gpus = 1
gpus = [mx.gpu(i) for i in range(num_gpus)]
symbol, arg ,aux = mx.model.load_checkpoint('vgg', 1)

internals = symbol.get_internals()
fea_symbol = internals["drop7_output"]
feature_extractor = mx.model.FeedForward(ctx=gpus, symbol=fea_symbol, 
                                         arg_params=arg,
                                         aux_params=aux,
                                         allow_extra_params=True)
img =loadImg('py.png').reshape(1,3,224,224)
out = feature_extractor.predict(img)

I load one image to predict , got error:
MXNetError: [14:04:55] d:\chhong\mxnet\src\storage\./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory

change ctx to cup , then  error:
Minimum workspace size:292225024
Given:134217728,

My PC memory size 8G, and  gpu memory size is 2G.
And installed mxnet release version  20151102_win64_gpu.7z
vgg-0001.params  file is 553MB

**Comment by piiswrong** [comment]
2G is not enough for running vgg.
Try reduce batch_size to 1 and increment gradually

**Comment by winstywang** [comment]
You may need to change the parameter here: https://github.com/dmlc/mxnet/blob/master/src/operator/convolution-inl.h#L52

**Comment by maxpy** [comment]
Thank you all.
I solve the problem by add numpy_batch_size=1,  param :

    netPredict = mx.model.FeedForward(ctx=gpus, symbol=fea_symbol, 
            numpy_batch_size=1,arg_params=arg,aux_params=aux, allow_extra_params=True)
