### ISSUE TITLE
Issues on the latest Windows for R

### ISSUE THREAD

**Issue by jeremiedb** [dmlc/mxnet#5281]
Building the R package from the pre-build Windows releases is no longer working: 
https://github.com/yajiedesign/mxnet/releases

It works fine up to the build 20170304, but since the 20170305 build, the package can be installed but several functionnalities are crashing. 

The first moment in building the package where I noticed an anomaly is during the roxygenise step: 

```
> roxygen2::roxygenise("R-package/")

Warning message:
In .recacheSubclasses(def@className, def, doSubclasses, env) :
  undefined subclass "mx.metric.logger" of class "refObject"; definition not updated
```

After that, the 2 remaining preparation steps run as usual: 

```
R CMD build --no-build-vignettes R-package
R CMD INSTALL --no-multiarch R-package
```

Following the package installation, the NDarrays operations are crashing:  

```
> xx<-mx.nd.array(12)
> mx.nd.sqrt(xx)
Error in mx.nd.sqrt(xx) : 
  ./base.h:291: Unsupported parameter type object type for argument data, expect integer, logical, or string.

```
Given no change was made to base.h for a while, the issue is likely from somewhere else. The 20170305, 20170306 and 20170307 builds are all causing the same problem and I couln't see any recent commit that would have cause this. Any help appreciated, thanks!

**Comment by piiswrong** [comment]
@mli Need to do the same fix for all packages. I think it's better to change to NDArray-or-Symbol rather than modifying all packages.

**Comment by jeremiedb** [comment]
Hi, I was wondering is there was any planned fix for this issue or if I may be of any help with it? 
Latest built from 20170327 is still producing the same error. Thanks!

**Comment by gwern** [comment]
I installed mxnet today on Ubuntu Linux, and after running into frustratingly bad performance on a simple linear regression issue, I discovered the advice in https://github.com/dmlc/mxnet/issues/4287 to use rmsprop... which crashes:

```
R> mxModel1 <- mx.model.FeedForward.create(lro1, X=train.x, y=train.y,
+                                         eval.data=list(data=test.x, label=test.y),
+                                         ctx=mx.cpu(), num.round=nRound,
+                                         array.batch.size=batchSize,
+                                         eval.metric=mx.metric.rmse,
+                                         verbose=verbose,
+                                         array.layout=array.layout,
+                                         optimizer=optimizer
+                                         )
Error in mx.nd.sqrt(n - g * g + 1e-04) : 
  ./base.h:291: Unsupported parameter type object type for argument data, expect integer, logical, or string.
Calls: mx.model.FeedForward.create ... <Anonymous> -> lapply -> FUN -> update -> mx.nd.sqrt
```

As does jeremiedb's simple `nd.sqrt` example with the same `base.h`-related error. (Note: it does run if I switch to "sgd" as the optimizer and set a `learning.rate` as well, so my installation is otherwise working.)

**Comment by sagaragrawal13** [comment]
Hi, similar to gwern, I am also facing issues with optimizer rmsprop. 

Could you please help. thanks in advance.

**Comment by jeremiedb** [comment]
Could you precise which version you installed and how? I just reinstalled the most recent version (on Ubuntu 16.04) and both `mx.nd.sqrt`  and rmsprop optimizer worked fine. 

@sagaragrawal13 is the issue with rmsprop appearing when running on multiple GPUs? There's currently an issue for all optimizers but SGD when training on multiple devices (#5296), but single CPU or GPU should be ok.

**Comment by sagaragrawal13** [comment]
@jeremiedb  I am using mxnet version 0.9.4 on R studio Server edition with R version 3.2.5 (2016-04-14). 

Please let me know if this helps.

**Comment by thirdwing** [comment]
@sagaragrawal13 Can you try to install the latest one? Please let me know you still met the error.

**Comment by sagaragrawal13** [comment]
@thirdwing  Sure. I will try and let you know. 

Thanks for quick replies. :+1:

**Comment by sagaragrawal13** [comment]
@thirdwing Updating the version solved the issue. Thanks.

**Comment by thirdwing** [comment]
Great!

I am closing this now. Feel free to reopen.
