### ISSUE TITLE
specific initialize for the variable inside  mx.sym()

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#5286]
in `prelu`, the variable inside is `gamma` which share the same name with `bn`, and the default init of `gamma` in `bn` is `1.0`, but in `prelu` it need be initialized less than `1.0` for convergence(always 0.25), how to use the  new initialization api `mx.init.InitDesc()`?

just tryed two wrong usage:
```python
prelu = mx.sym.LeakyReLU(conv,  act_type="prelu", attr={"init":"mx.init.Constant(0.25)"}, name="prelu1")  
```
```python
prelu = mx.sym.LeakyReLU(conv, act_type="prelu", init=mx.init.Constant(0.25), name="prelu1")
```
@piiswrong

**Comment by piiswrong** [comment]
```
gamma = mx.sym.Variable("prelu1_gamma", init=mx.init.Constant(0.25))
prelu = mx.sym.LeakyReLU(conv, gamma, act_type="prelu", name="prelu1")
```

**Comment by tornadomeet** [comment]
thanks, it work!
