### ISSUE TITLE
Bucketing module checkpoint handling

### ISSUE THREAD

**Issue by sergeykolychev** [dmlc/mxnet#5289]
It would have been nice if there were high level checkpoint functions that were able to save/restore
all symbols used by the bucketing module.
Current default functionality (save_rnn_checkpoint) saves a random symbol that happens to be current at the epoch end.

**Comment by Godricly** [comment]
I think they share same parameters. So it is not a big problem here. What do you mean by random symbol?

**Comment by sergeykolychev** [comment]
@Godricly , yes, I they do share the same parameters, no problem with params, the problem with the saving of the symbol. Bucketing module has several modules under the hood and
in the base_module the checkpoint function is called with self.symbol with is in the case of the bucketing module self._curr_module.symbol. Now _curr_module switches depending on randomly shuffled data. So whatever module happen to be current at the end of the epoch will have its symbol dumped into ..-symbol.json. I think in order to reload the net state without re-reading the data and reconstructing the buckets info we do need to save all symbols for all sub modules.

**Comment by kandoiNikhil** [comment]
Hi @sergeykolychev , did you find a solution for this ?
