### ISSUE TITLE
When create one symbol, how to set multi-input data?

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#529]
Hello~
  In some scenarios, one layer(the middle layer, not the input data layer) needs more than one input layer, and these inputs don't have the same formula mode, just like in caffe (one layer may have more bottom layers) , so how to set this multi-input data when buliding one layer in Symbolic?
assume that i have written a NewLayer in python side refer to [new_op_howto](http://mxnet.readthedocs.org/en/latest/tutorial/new_op_howto.html), and the NewLayer has two inputs, how to set this in symbol? Does mxnet currently support this style ?or how i should do this?
ths.

**Comment by winstywang** [comment]
Check the implementation of Concat Op.

**Comment by tornadomeet** [comment]
@winstywang , the inputs don't have the same formula mode, so we cannot concat it. I'm writing the crop layer in python, just as(but not the same ) https://github.com/BVLC/caffe/pull/1639,

**Comment by piiswrong** [comment]
Just declare any input and weights in list_arguments ['input_1', 'input_2',...]
and when creating the symbol 
new_layer = NewLayer()
new_layer(input_1=x1, input_2=x2...)

**Comment by tornadomeet** [comment]
@winstywang , Yeah, i got it, when more inputs, just as concat = mx.symbol.Concat(*[conv, pool])
thanks a lot!

**Comment by tornadomeet** [comment]
@piiswrong , thanks, i do it according to the your method, it works!
maybe you can consider put this guide to [new_op_howto](http://mxnet.readthedocs.org/en/latest/tutorial/new_op_howto.html)~
