### ISSUE TITLE
Could we make CI tests available locally?  

### ISSUE THREAD

**Issue by jli05** [dmlc/mxnet#5293]
Could we make as many tests as possible available locally, so that a developer can invoke `make test` to test through locally?

**Comment by eric-haibin-lin** [comment]
I think the script is available in tests/Jenkins/run_all.sh 

On 2017年3月7日, at 06:33, Jencir Lee <notifications@github.com> wrote:

Could we make as many tests as possible available locally, so that a developer can invoke make test to test through locally?
