### ISSUE TITLE
C++ example using predict API from image

### ISSUE THREAD

**Issue by matthill** [dmlc/mxnet#531]
The new amalgamation C++ code is really cool.  I'm planning on switching away from Caffe which is an absolute pain to deploy with its million dependencies.  I'm having trouble putting together a simple example that reads an image (e.g,. jpg) and performs a feedforward to classify the results.  I'm sure it's simple to do, but it doesn't seem obvious to me.  A simple example program to go along with that API would be super useful for those of us looking to deploy these models.

**Comment by tqchen** [comment]
Thanks for the suggestion. We do not yet have a C++ example so far(which is a bit shame as the main program is in c++), but you can find examples in
- Go https://github.com/jdeng/gomxnet
- python https://github.com/dmlc/mxnet/blob/master/predict/python/mxnet_predict.py and https://github.com/dmlc/mxnet/blob/master/tests/python/predict/mxnet_predict_example.py
- Java https://github.com/dmlc/mxnet/pull/526

All of these relies on a C API, so actually they are using C :)  I guess things can be done with opencv fairly easily, except that we did not have examples yet to put up a C++ example. Let us know if these examples make sense to you and if you are interested in contributing a C++ example

**Comment by worldveil** [comment]
Hi, I would also like to help with this. 

Unfortunately, I'm not an expert in linking C libraries to other languages like Go, Python, and Java as you show above, so they aren't too illustrative of how one might go about using, say, a model trained in the Python bindings in a C++ context. 

Might there be other examples you could point to, or even perhaps some old commits that might show this? I'm afraid the documentation isn't too clear to me either, though I could certainly be reading them incorrectly.

**Comment by winstywang** [comment]
All calls from host languages to mxnet core are directed using the C API here:https://github.com/dmlc/mxnet/blob/master/include/mxnet/c_api.h Please let us know if you have further questions.

**Comment by worldveil** [comment]
OK, that's somewhat helpful. Is there an example of the C API used as a C script?

**Comment by winstywang** [comment]
Sorry there is no such examples currently. It should not be hard since the interface is clearly defined. Looking forward to your contribution if possible.

**Comment by worldveil** [comment]
@winstywang @tqchen Hmmm as someone who isn't an extremely fluent C/C++ programmer, I don't know how to proceed. My use case is quite simple, I'd like to:

* Load a model file that was already trained in Python
* Load image file(s)
* Output a prediction(s)

in C++. If putting together an example like this is so difficult, then Tensorflow seems a much better choice. (Not in any way on a knock on this project or maintainers. Rather a question of usecase and dev time.)

My view of this library was it was meant to be for this sort of thing, but it seems more research oriented.

**Comment by caprice-j** [comment]
I'm now making a C++ program which reads a pre-trained model and classify a jpg file. Here is the current program (still incomplete): https://github.com/caprice-j/mxnet/blob/master/example/image-classification-cplusplus/predict.cc

I succeeded as to calling MXPredCreate() with no compile error, but when I executed the C++ program it showed: 

$ ./predict
[16:19:22] ./dmlc-core/include/dmlc/./logging.h:208: [16:19:22] src/operator/operator.cc:19: Cannot find Operator FullyConnected in registry

From this log message, it seemed like I have to register "FullyConnected" symbol, but when I add 

MXNET_REGISTER_OP_PROPERTY(FullyConnected, mxnet::op::FullyConnectedProp);

in my predict.cc: line 19, then another error message showed and segfaulted:

[16:19:03] ../../dmlc-core/include/dmlc/./logging.h:208: [16:19:03] ../../dmlc-core/include/dmlc/registry.h:53: Check failed: (fmap_.count(name)) == (0) FullyConnected already registered
libc++abi.dylib: terminating with uncaught exception of type dmlc::Error: [16:19:03] ../../dmlc-core/include/dmlc/registry.h:53: Check failed: (fmap_.count(name)) == (0) FullyConnected already registered
Abort trap: 6


I'd like to ask you of how to deal with this problem.
I'm using "model/mnist-0-symbol.json" and "model/mnist-0-0001.params" as a test pre-trained model (borrowed from the example/image-classification directory).

**Comment by caprice-j** [comment]
I added the following lines, hoping to "register" FullyConnected and the other symbols.

  SymbolHandle myHandle;
  MXSymbolCreateFromJSON((const char* ) jsonStr.buf, &myHandle);

But the program returned:

[21:16:26] ./dmlc-core/include/dmlc/./logging.h:208: [21:16:26] src/operator/operator.cc:19: Cannot find Operator FullyConnected in registry
[21:16:26] ./dmlc-core/include/dmlc/./logging.h:208: [21:16:26] src/operator/operator.cc:19: Cannot find Operator FullyConnected in registry

The same error twice. Hmm.

**Comment by matthill** [comment]
Linking two other requests for similar functionality:

  - https://github.com/dmlc/mxnet/issues/868
  - https://github.com/dmlc/mxnet/issues/762

**Comment by tqchen** [comment]
move to #868
