### ISSUE TITLE
Build error because of protobuf

### ISSUE THREAD

**Issue by tmfs10** [dmlc/mxnet#532]
I'm trying to build MXnet on CentOS 6.5. First I got the error that meta_message.pb.h and node.pb.h in ps-lite/include/ps/internal were generated by a newer version of protoc than the one on my server. Then when I installed the latest version from https://github.com/google/protobuf, I got the message that they were generated by an older version.

Which version do I need?

**Comment by mli** [comment]
please have a pull: git pull && git submodule update

the problem should be solved

**Comment by tqchen** [comment]
closing for now, please feel free to reopen it
