### ISSUE TITLE
bin/im2rec speed is very slow

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#5324]
the performance `bin/im2rec` is well at beginning, but after a while, the speed is dropped down **10x ~100x** slower, so what's wrong?  i encounter this many times.

no other task is running in the linux server.
200w small image with less than 30*30 size.

**Comment by piiswrong** [comment]
The first few images are on disk cache so its fast.

**Comment by tornadomeet** [comment]
but if 200w image with size 15*15, then the speed of `bin/im2rec` is always about 100X than 200w image with 30*30. 
if image size is 30*30, only about first 10% images's speed is normal.

**Comment by mli** [comment]
upgrade your ssd... e.g. nvme ssd.

**Comment by tornadomeet** [comment]
tuhao..

so it's normal speed on SAS disk.
