### ISSUE TITLE
[YARN] MXNet on YARN Example

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#533]
Now everything is ready for distributed training, and we have an [AWS example](http://mxnet.readthedocs.org/en/latest/aws.html) here for a ssh based distributed training on bare mental.

However, more cluster scheduler compatible way of job submission can naturally be supported, as DMLC comes with the [trackers](https://github.com/dmlc/dmlc-core/tree/master/tracker) for all platforms including YARN. This thread is opened to call for an example on training mxnet on YARN.

Anyone who are interested can reply.  @mli correct me if I am wrong 
As far as I know, all the things needed are
- [ ] YARN cluster with GPU
- [ ] Modify https://github.com/dmlc/dmlc-core/blob/master/tracker/dmlc_yarn.py to add latest [env variable](https://github.com/dmlc/ps-lite/blob/dev/doc/env.md) of ps-lite, maybe involve modify appmaster a bit.
- [ ] Put data on hdfs or s3, and submit as usual.

**Comment by daleloogn** [comment]
exciting works

**Comment by tqchen** [comment]
@qiaohaijun would you be interested in working on this

**Comment by zorksylar** [comment]
Any plan for Mesos?

**Comment by schlichtanders** [comment]
any progress on this?
I probably would like to use MXNet on Hadoop / Yarn, however the lack of documentation is a real obstacle

**Comment by schlichtanders** [comment]
why was this closed if it is not resolved?

**Comment by schlichtanders** [comment]
please...
?
