### ISSUE TITLE
Import Error update after latest pull

### ISSUE THREAD

**Issue by ForoughA** [dmlc/mxnet#5368]
After pulling the latest version of mxnet on Monday March 13, 2017 I get the following import error when I try: import mxnet as mx
ImportError: cannot import name rmspropalex_update
I was able to solve it by removing the " import rmspropalex_update " from file [mxnet/python/mxnet/optimizer.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py) but I am not sure if that is going cause any problems later on.

Below is the detailed information:

## Environment info
Operating System:
mac OS X El Capiton, version 10.11.5

Compiler:
clang-800.0.38

Package used (Python/R/Scala/Julia):
Python

MXNet commit hash (`git rev-parse HEAD`):
8861ccc032fa64f4a13b84fb82f6edb4febef2be

Python version and distribution:
Python 2.7.12 --- Anaconda 4.2.0

## Error Message:
"Traceback (most recent call last):
  File "prover.py", line 23, in <module>
    import mxnet as mx
  File "/Users/Forough/mxnet/python/mxnet/__init__.py", line 23, in <module>
    from . import optimizer
  File "/Users/Forough/mxnet/python/mxnet/optimizer.py", line 6, in <module>
    from .ndarray import sgd_update, sgd_mom_update, adam_update, rmsprop_update, rmspropalex_update
ImportError: cannot import name rmspropalex_update "

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
import mxnet as mx

## What have you tried to solve it?

1. I was able to solve it by removing the "import rmspropalex_update" [from file mxnet/python/mxnet/optimizer.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py)

**Comment by piiswrong** [comment]
make clean && make

**Comment by ForoughA** [comment]
I get a make error when doing that. Here is the complete error log:

## Error log:
rm -rf python/mxnet/*/*.so python/mxnet/*/*.cpp
rm -f -r build lib bin *~ */*~ */*/*~ */*/*/*~ R-package/NAMESPACE R-package/man R-package/R/mxnet_generated.R \
		R-package/inst R-package/src/*.o R-package/src/*.so mxnet_*.tar.gz
cd /Users/Forough/mxnet/dmlc-core; /Applications/Xcode.app/Contents/Developer/usr/bin/make clean; cd -
rm -f line_split.o recordio_split.o input_split_base.o io.o local_filesys.o data.o recordio.o config.o  libdmlc.a test/filesys_test test/dataiter_test test/iostream_test test/recordio_test test/split_read_test test/stream_read_test test/split_test test/libsvm_parser_test test/split_repeat_read_test test/strtonum_test test/logging_test test/parameter_test test/registry_test test/csv_parser_test test/unittest/dmlc_unittest test/unittest/unittest_any.o test/unittest/unittest_array_view.o test/unittest/unittest_config.o test/unittest/unittest_json.o test/unittest/unittest_logging.o test/unittest/unittest_main.o test/unittest/unittest_optional.o test/unittest/unittest_serializer.o test/unittest/unittest_threaditer.o *~ src/*~ src/*/*~ include/dmlc/*~ test/*~
/Users/Forough/mxnet
cd /Users/Forough/mxnet/ps-lite; /Applications/Xcode.app/Contents/Developer/usr/bin/make clean; cd -
rm -rf build  tests/test_connection  tests/test_kv_app  tests/test_simple_app tests/*.d
find src -name "*.pb.[ch]*" -delete
/Users/Forough/mxnet
cd /Users/Forough/mxnet/nnvm; /Applications/Xcode.app/Contents/Developer/usr/bin/make clean; cd -
rm -f -rf build lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o cli_test
/Users/Forough/mxnet
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/mkl/mkl_cppwrapper.cc -o build/src/operator/mkl/mkl_cppwrapper.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/mkl/mkl_memory.cc -o build/src/operator/mkl/mkl_memory.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/nnpack/nnpack_util.cc -o build/src/operator/nnpack/nnpack_util.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/broadcast_reduce_op_index.cc -o build/src/operator/tensor/broadcast_reduce_op_index.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/broadcast_reduce_op_value.cc -o build/src/operator/tensor/broadcast_reduce_op_value.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/control_flow_op.cc -o build/src/operator/tensor/control_flow_op.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_broadcast_op_basic.cc -o build/src/operator/tensor/elemwise_binary_broadcast_op_basic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_broadcast_op_extended.cc -o build/src/operator/tensor/elemwise_binary_broadcast_op_extended.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_broadcast_op_logic.cc -o build/src/operator/tensor/elemwise_binary_broadcast_op_logic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_op_basic.cc -o build/src/operator/tensor/elemwise_binary_op_basic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_op_extended.cc -o build/src/operator/tensor/elemwise_binary_op_extended.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_op_logic.cc -o build/src/operator/tensor/elemwise_binary_op_logic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_scalar_op_basic.cc -o build/src/operator/tensor/elemwise_binary_scalar_op_basic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_scalar_op_extended.cc -o build/src/operator/tensor/elemwise_binary_scalar_op_extended.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_binary_scalar_op_logic.cc -o build/src/operator/tensor/elemwise_binary_scalar_op_logic.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_sum.cc -o build/src/operator/tensor/elemwise_sum.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/elemwise_unary_op.cc -o build/src/operator/tensor/elemwise_unary_op.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/indexing_op.cc -o build/src/operator/tensor/indexing_op.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/init_op.cc -o build/src/operator/tensor/init_op.o
g++ -std=c++11 -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/Forough/mxnet/mshadow/ -I/Users/Forough/mxnet/dmlc-core/include -fPIC -I/Users/Forough/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include  -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -MMD -c src/operator/tensor/matrix_op.cc -o build/src/operator/tensor/matrix_op.o
In file included from src/operator/tensor/matrix_op.cc:7:
In file included from src/operator/tensor/./matrix_op-inl.h:9:
In file included from include/mxnet/operator_util.h:24:
In file included from include/mxnet/base.h:16:
/Users/Forough/mxnet/nnvm/include/nnvm/./tuple.h:35:3: error: static_assert failed "Tuple only support simple data
      type like int"
  static_assert(std::is_pod<ValueType>::value,
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/operator/tensor/./matrix_op-inl.h:673:37: note: in instantiation of template class
      'nnvm::Tuple<dmlc::optional<int> >' requested here
  nnvm::Tuple<dmlc::optional<int> > begin, end;
                                    ^
In file included from src/operator/tensor/matrix_op.cc:7:
In file included from src/operator/tensor/./matrix_op-inl.h:14:
In file included from src/operator/tensor/../elemwise_op_common.h:18:
src/operator/tensor/../operator_common.h:229:11: error: no matching member function for call to 'Init'
    param.Init(attrs->dict);
    ~~~~~~^~~~
src/operator/tensor/matrix_op.cc:209:18: note: in instantiation of function template specialization
      'mxnet::op::ParamParser<mxnet::op::SliceParam>' requested here
.set_attr_parser(ParamParser<SliceParam>)
                 ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/parameter.h:127:15: note: candidate function [with Container =
      std::__1::unordered_map<std::__1::basic_string<char>, std::__1::basic_string<char>,
      std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >,
      std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> > > >]
      not viable: no known conversion from 'mxnet::op::SliceParam' to 'dmlc::Parameter<mxnet::op::SliceParam>' for
      object argument
  inline void Init(const Container &kwargs,
              ^
In file included from src/operator/tensor/matrix_op.cc:7:
In file included from src/operator/tensor/./matrix_op-inl.h:9:
In file included from include/mxnet/operator_util.h:18:
In file included from /Users/Forough/mxnet/dmlc-core/include/dmlc/registry.h:14:
In file included from /Users/Forough/mxnet/dmlc-core/include/dmlc/parameter.h:22:
In file included from /Users/Forough/mxnet/dmlc-core/include/dmlc/json.h:29:
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:179:21: error: no viable conversion from 'mxnet::op::SliceParam'
      to 'dmlc::any'
    this->construct(std::forward<T>(other));
                    ^~~~~~~~~~~~~~~~~~~~~~
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:229:3: note: in instantiation of function template
      specialization 'dmlc::any::any<mxnet::op::SliceParam>' requested here
  any(std::forward<T>(other)).swap(*this);
  ^
src/operator/tensor/../operator_common.h:241:17: note: in instantiation of function template specialization
      'dmlc::any::operator=<mxnet::op::SliceParam>' requested here
  attrs->parsed = std::move(param);
                ^
src/operator/tensor/matrix_op.cc:209:18: note: in instantiation of function template specialization
      'mxnet::op::ParamParser<mxnet::op::SliceParam>' requested here
.set_attr_parser(ParamParser<SliceParam>)
                 ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:176:13: note: candidate constructor
      [with T = mxnet::op::SliceParam]
inline any::any(T&& other) {
            ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:192:13: note: candidate constructor not viable: no known
      conversion from 'mxnet::op::SliceParam' to 'dmlc::any &&' for 1st argument
inline any::any(any&& other) {
            ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:196:13: note: candidate constructor not viable: no known
      conversion from 'mxnet::op::SliceParam' to 'const dmlc::any &' for 1st argument
inline any::any(const any& other) {
            ^
/Users/Forough/mxnet/dmlc-core/include/dmlc/any.h:163:31: note: passing argument to parameter 'other' here
  inline void construct(any&& other);
                              ^
3 errors generated.
make: *** [build/src/operator/tensor/matrix_op.o] Error 1

**Comment by ForoughA** [comment]
Hi, thanks for the solution. The issue is still unresolved after doing make clean && make.
