### ISSUE TITLE
how to clip the weights of the params in module

### ISSUE THREAD

**Issue by papercatnku** [dmlc/mxnet#5381]
I am trying to implement a Wasserstein GAN with mxnet. 
An necessary procedure is to clamp the weights of the discriminator to a fixed range(i.e. [-0.01,0.01]), i am wondering whether there is any convenient interface to do that with module api? (convenient means other than manually bind an executor and do the clamp of each NDArray)
Can any one share any experience？ Thanks

**Comment by sergeykolychev** [comment]
use adam or rmsprop optimizers with clip_gradient param, recently these optimizers were 
reworked specifically to make Wasserstein GAN trainable.
