### ISSUE TITLE
Can NumpySoftmax(mx.operator.NumpyOp) run on GPU?

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#539]
Can ```NumpySoftmax(mx.operator.NumpyOp)``` run on GPU?

**Comment by jermainewang** [comment]
Hi,

The `NumpySoftmax` is implemented using `numpy` operators, so it could only run on CPU. To use a GPU version softmax, you could use `mx.symbol.SoftmaxOutput` to create a symbol and follow the the symbolic execution to run your code. You may want to look at the document [here](https://mxnet.readthedocs.org/en/latest/python/symbol.html#symbol-creation-api-reference).

Best,
Minjie
