### ISSUE TITLE
Documentation of monitor

### ISSUE THREAD

**Issue by georg-at-github** [dmlc/mxnet#5391]
Hello,

I would like to log the outputs of certain layers of my NN in a forward sweep. Perhaps a monitor could be a solution to this, but I have found no documentation whatsoever beside the install_monitor function for a module. Could you give me hitn where to find more information?

Thanks!

**Comment by bigdata2** [comment]
You can find an example of how to use monitor in mxnet/example/python-howto/monitor_weights.py

**Comment by georg-at-github** [comment]
Thanks!
