### ISSUE TITLE
mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead

### ISSUE THREAD

**Issue by whaozl** [dmlc/mxnet#5394]
```
model= mx.model.FeedForward(ctx=mx.cpu(), symbol=fea_symbol, numpy_batch_size=64,
                                             arg_params=model.arg_params, aux_params=model.aux_params,
                                             allow_extra_params=True)
```
**How to write by using mx.mod.module**

**Comment by qiyuangong** [comment]
In latest version, `train_mnist.py`( and `fit.py`) is written based on mx.mod.module. You can adapt your code to `mx.model.FeedForward` based on this example with limited modifications.

**Comment by whaozl** [comment]
Thanks

**Comment by 123chengbo** [comment]
@whaozl  could you show me the modified model.py， i don’t know how to deal with it。

thank you。

**Comment by whaozl** [comment]
you can find the mx.mod.module using example in the mxnet examples.

**Comment by 123chengbo** [comment]
i've tried to modify the model.py（according totrain_mnist.py、 fit.py），but it is not correctly。 I am new to python，i‘ve tried but can not figure it out 。
If you show me the modified model.py，that would help a lot。
Thank you so much。

**Comment by vizakshat** [comment]
I tried mx.mod.Module but it takes arguments such as data shapes when binding.
In feed forward we didn't need data shapes. What if i dont know the data shapes??
How can I incorporate Module?
