### ISSUE TITLE
I wann to train ResNet-50 based on my data

### ISSUE THREAD

**Issue by ysh329** [dmlc/mxnet#5404]
As title, I have two questions below:

1. Which repo the model(ResNet-50: http://data.dmlc.ml/mxnet/models/imagenet-11k-place365-ch/) comes from? 
From [tornadomeet/ResNet](https://github.com/tornadomeet/ResNet) or [KaimingHe/deep-residual-networks](https://github.com/KaimingHe/deep-residual-networks) converted by tool?

2. What is the detailed preprocessing of these image data on pretrained stage?

**Comment by ysh329** [comment]
@tornadomeet @ry

**Comment by thatindiandude** [comment]
@mli

**Comment by mli** [comment]
trained from scratch based on https://github.com/dmlc/mxnet/tree/master/example/image-classification

**Comment by ysh329** [comment]
@mli Thanks a lot!
