### ISSUE TITLE
using float16, check fail

### ISSUE THREAD

**Issue by cainiao2hao** [dmlc/mxnet#5413]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Win7

Compiler:
VS2015

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.9.3

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
python 3.6

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

 d:\program files (x86)\jenkins\workspace\mxnet\mxnet\dmlc-core\include\dmlc\./logging.h:300: [21:26:49] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\include\mxnet/operator.h:267: Check failed: in_type->at(i) == mshadow::default_type_flag || in_type->at(i) == -1 Unsupported data type 2
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pydev\pydevd.py", line 1596, in <module>

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
example code,  example/image-classification/alexnet_fp16.py

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.
1. run train_cifar10.py, parameter is "--network alexnet_fp16  --batch-size 64 --gpus 0"!
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by piiswrong** [comment]
@ap-hynninen

**Comment by piiswrong** [comment]
alexnet require input to be larger than 227x227. cifar is only 32x32 so you need a different network or bigger images.

**Comment by cainiao2hao** [comment]
I updated mxnet code and rebuild it. It's ok to run. Thanks.
