### ISSUE TITLE
Inception model on Android

### ISSUE THREAD

**Issue by tzutalin** [dmlc/mxnet#542]
Hi,
  I am also working on deep learning on mobile device. , I implemented Caffe, FastRCNN, and FasterRCNN to Android platform. But I would like to remove some layers in different models to speed up and reduce memory usage. May I know which layers you remove? What's your inception model? What's the accuracy? Thanks
https://github.com/tzutalin/Android-Object-Detection

**Comment by antinucleon** [comment]
In my thesis there is a tutorial of make a 0.4 time complexity compared to
AlexNet, and performance is same to ZF (83% in top 5). But as it is still
private now, you may find Kaiming He's paper in constrain complexity
helpful.

**Comment by tqchen** [comment]
@tzutalin this might also be helpful mxnet.readthedocs.org/en/latest/developer-guide/note_memory.html As the arch was used to reduce memory usage

**Comment by tzutalin** [comment]
@tqchen
Thanks. I will take a detailed look at the website.

@antinucleon,
Hope you can release your model someday.

**Comment by antinucleon** [comment]
You may use this model for now;
https://github.com/Leliana/WhatsThis/tree/master/app/src/main/res/raw

and we will release it later

**Comment by tqchen** [comment]
closing for now, please feel free to open it. @tzutalin if you are interested, we would also love to have your contribution to mxnet
