### ISSUE TITLE
Where is gen_data.py in example/bi-lstm-sort/

### ISSUE THREAD

**Issue by ysh329** [dmlc/mxnet#5448]
As [README.md in mxnet/example/bi-lstm-sort](https://github.com/dmlc/mxnet/tree/master/example/bi-lstm-sort) mentions:
This is an example of using bidirection lstm to sort an array.
Firstly, generate data by:
```shell
cd data
python gen_data.py
```

However, I couldn't find gen_data.py and I searched the whole directory as below:
```shell
yuens@Spark$ find . -name *gen_data.py*                                                                                  
zsh: no matches found: *gen_data.py*
```

**Comment by gurumurthys** [comment]
Refer to https://github.com/dmlc/mxnet/issues/2783

**Comment by ysh329** [comment]
@gurumurthys Thanks my brother.
