### ISSUE TITLE
Multiple data inputs for an operation

### ISSUE THREAD

**Issue by sxjscience** [dmlc/mxnet#545]
I'm trying to build a loss function that contains multiple data inputs, e.g, loss = in_data[0] * in_data[1] - out_data[0]. I find the only operation in MXNet  that support multiple data inputs is `mx.symbol.Concat`. But in this situation, I may need to take a list of symbols as data inputs. For example, I may need this kind of Op:

      loss= NewLossOP(data=[sym1, sym2], name='NewLoss')

Can I achieve that using `mxnet.symbol.Group`? (Maybe like this:)

      loss = NewLossOP(data=mxnet.symbol.Group([sym1, sym2]), name='NewLoss')

**Comment by tqchen** [comment]
You can take multiple data input, for example, checkout, fullyconnected.

**Comment by sxjscience** [comment]
@tqchen I haven't stated the question clearly. Actually, I'm trying to use `mx.operator.NumpyOp` for a quick hack of the loss layer, but I fail to add other arguments besides 'data' and 'label'. Does the NumpyOp support such usage? Coding an Op in C++ may be an overkill for my problem.

**Comment by tqchen** [comment]
I think it should support your usage, as long as you add them in list_arguments @piiswrong

**Comment by tornadomeet** [comment]
@sxjscience you can prefer to #529

**Comment by sxjscience** [comment]
Thank you very much @tqchen and @tornadomeet. In fact, I find I cannot run the `numpy_softmax.py` example after updating mxnet to the latest version. It reports the following error:
      
    File "example\\numpy-ops\\numpy_softmax.py", line 48, in <module>
    mlp = mysoftmax(data=fc3, name = 'softmax')
    File "C:\Users\sxjscience\AppData\Roaming\Python\Python27\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\operator.py", line 23, in __call__
    return self.get_symbol(*args, **kwargs)
    File "C:\Users\sxjscience\AppData\Roaming\Python\Python27\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\operator.py", line 207, in get_symbol
    **kwargs)
    File "C:\Users\sxjscience\AppData\Roaming\Python\Python27\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\symbol.py", line 798, in creator
    ctypes.byref(sym_handle)))
    File "C:\Users\sxjscience\AppData\Roaming\Python\Python27\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 73, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
    mxnet.base.MXNetError: Invalid Parameter format for info expect  but value='0x22f3250L'

**Comment by piiswrong** [comment]
did you rebuild mxnet? It's fine for me.

**Comment by sxjscience** [comment]
@piiswrong I've found the problem. The bug is caused by https://github.com/dmlc/mxnet/blob/master/python/mxnet/operator.py#L202. Using `hex` for 16-bit string conversion will cause the [Trailing L Problem](http://stackoverflow.com/questions/5917203/python-trailing-l-problem) for 64-bit value. I've revised the code to

    cb_ptr = format(cast(pointer(self.info_), c_void_p).value, 'x')

and it works well.

**Comment by piiswrong** [comment]
Thanks for the fix. Are you sure scanf("%p", &p) doesn't need the 0x in front? Could you open a PR for this?

**Comment by vchuravy** [comment]
`scanf("%p", &p)` will need the `0x` in front. 

In Julia I have to do `pstring = bytestring("0x", hex(reinterpret(UInt, pointer_from_objref(info))))` to get the correct value.

**Comment by sxjscience** [comment]
@piiswrong @vchuravy I've made the pr and I'm not sure about the `scanf("%p", &p)` issue.
