### ISSUE TITLE
Amalgamation for iOS

### ISSUE THREAD

**Issue by loretoparisi** [dmlc/mxnet#546]
Is possibile to add amalgamation for iOS?

**Comment by antinucleon** [comment]
Yes, but as currently no one in dmlc is major in mobile development, we
would like volunteers help us to contribute a simple demo, and we can
provide kinds of supports.

**Comment by loretoparisi** [comment]
I see, could you explain the approach, given the assumption all of us have read the amalgamation stuff in https://mxnet.readthedocs.org/en/latest/tutorial/smart_device.html and that can edit/read a Make file?
This could be a starting point then!

**Comment by tqchen** [comment]
Here is an outline how it can be done, because there is no additional dependency besides blas, it should be quite identical to what was given

- [ ] Use the amalgamation script https://github.com/dmlc/mxnet/tree/master/amalgamation to create a C library
- [ ] Find a blas library in IOS, openblas or other blas, to link and create a C library ```libmxnet_predict.so```
- [ ] Create a swift/object-c wrapper, that calls https://github.com/dmlc/mxnet/blob/master/include/mxnet/c_predict_api.h
   - The call is only a foreign C call, so should be easy for both language
   - You can ref other wrappers such as https://github.com/jdeng/gomxnet/ on how to call C API
- You  should be good to go

**Comment by zachmayer** [comment]
I think iOS has Apple's BLAS library: [vecLib](https://developer.apple.com/library/prerelease/ios/documentation/Performance/Conceptual/vecLib/index.html)

**Comment by loretoparisi** [comment]
@zachmayer Yes I confirm that Accelerate it's a good numerical and vectorial library, I have used in several Audio visualization and real time waveform and stream manipulation projects.
@tqchen Give ```Accelerate framework```, could you define the steps to link and create a C library libmxnet_predict.so? Sorry, that is not clear to me already.

**Comment by tqchen** [comment]
Just modify Makefile and  ```type make```

**Comment by tqchen** [comment]
To be more specific,  change lines here to adapt link to accelerate lib. We already used the same BLAS interface, so there is no code you have to change in mxnet

**Comment by tqchen** [comment]
@loretoparisi Please let us know if you have any update on this, we would love to have your contribution and get it work on iOS

**Comment by loretoparisi** [comment]
@tqchen Yes. I'm now looking back at my old porting of ```Essentia``` audio library to iOS, just to have a comparison of the two approach: https://github.com/loretoparisi/EssentiaTouch

**Comment by tqchen** [comment]
sounds great, let us know how itgoes

**Comment by antinucleon** [comment]
Someone has done it, but is in Chinese: http://www.liuxiao.org/2015/12/ios-mxnet-%E7%9A%84-ios-%E7%89%88%E6%9C%AC%E7%BC%96%E8%AF%91/

**Comment by loretoparisi** [comment]
@antinucleon :+1: it seems that there are binary files as well in the solution proposed.

**Comment by tqchen** [comment]
@loretoparisi Do you have progress on this? It would be great if you can contribute an official example back to the mxnet repo

**Comment by loretoparisi** [comment]
@tqchen not yet but I'm looking to.

**Comment by phunterlau** [comment]
I am also talking to an iOS expert and see if he can help making a demo like Whatsthis. Hope it works.

**Comment by pppoe** [comment]
Hello, I've put up an iOS version here: https://github.com/pppoe/WhatsThis-iOS

**Comment by tqchen** [comment]
thanks @pppoe It has been added to the example
