### ISSUE TITLE
compile failed with latest mxnet

### ISSUE THREAD

**Issue by apeng5399** [dmlc/mxnet#5470]
win10+vs2015+mxnet0.9.4+python2.7

Error	LNK2019	unresolved external symbol "public: __cdecl ps::Customer::Customer(int,class std::function<void __cdecl(struct ps::Message const &)> const &)" (??0Customer@ps@@QEAA@HAEBV?$function@$$A6AXAEBUMessage@ps@@@Z@std@@@Z) referenced in function "public: __cdecl ps::KVServer<float>::KVServer<float>(int)" (??0?$KVServer@M@ps@@QEAA@H@Z)	mxnet	D:\Library\Mxnet\build\kvstore.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: __cdecl ps::Customer::~Customer(void)" (??1Customer@ps@@QEAA@XZ) referenced in function "public: virtual __cdecl ps::KVServer<float>::~KVServer<float>(void)" (??1?$KVServer@M@ps@@UEAA@XZ)	mxnet	D:\Library\Mxnet\build\kvstore.obj	1	

**cmake** 
Found OpenBLAS libraries: D:/Library/OpenBLAS/lib/libopenblas.dll.a
Found OpenBLAS include: D:/Library/OpenBLAS/include
CUDA detected: 8.0
Found cuDNN (include: D:/Library/CUDNN/include, library: D:/Library/CUDNN/lib/x64/cudnn.lib)
Added CUDA NVCC flags for: sm_52
 OpenCV_LIBS=opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs
OpenCV found (D:/Library/OpenCV32/build/x64/vc14/lib)
Try OpenMP C flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
Try OpenMP CXX flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
Found OpenMP: /openmp  
Found cuDNN (include: D:/Library/CUDNN/include, library: D:/Library/CUDNN/lib/x64/cudnn.lib)
Found PROTOBUF Compiler: D:/Library/Protobuf/builds/Release/protoc.exe
Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Configuring done
Generating done

**Comment by AthenaAlala** [comment]
@apeng5399 I also have this problem. Have you solved the problem? Can you help me?

**Comment by apeng5399** [comment]
after that i do 2 things
1.there is so file need to link in vs2015， it cant find,sorry i forgot the name, maybe ps-lite or something about distributed train.
2.update the related file to the same version , I just update all the file to the latest one.
hope it can help

**Comment by MichealRay** [comment]
same problem, anyone can help?
