### ISSUE TITLE
[NNPACK BUG] MXPredGetOutput occasionally stucked when getting the 2nd output node

### ISSUE THREAD

**Issue by pallashadow** [dmlc/mxnet#5508]
The bug only shows up when using NNPACK as backend. 
When I am trying to MXPredGetOutput from multiple node, the result from 1st node would always be got successfully, however the 2nd node would have a **low chance** to stuck forever. It shows up occasionally, but it is critical for high frequency tasks such as face detection. 

I also confirm that it happens on android device and in older version like v0.8

GDB shows this function is waiting for some threads. 

## Environment info
Operating System: Ubuntu 14.04 / android
Compiler: GCC
Package used:  NNPACK
MXNet version: v0.93 / v0.8

## GDB debug message when paused: 

> 
0	pthread_cond_wait@@GLIBC_2.3.2		185	0x7ffff7bc8404	
1	std::condition_variable::wait(std::unique_lock<std::mutex>&)	/usr/lib/x86_64-linux-gnu/libstdc++.so.6		0x7ffff3c622bc	
2	mxnet::engine::ThreadedEngine::WaitForVar(mxnet::engine::Var*)	/home/pallas/mxnet/lib/libmxnet.so		0x7ffff40af409	
3	mxnet::NDArray::SyncCopyToCPU(void*, unsigned long) const	/home/pallas/mxnet/lib/libmxnet.so		0x7ffff412ba58	
4	MXPredGetOutput	/home/pallas/mxnet/lib/libmxnet.so		0x7ffff40a42ae	
5	GetOutput	mxnet_cpp_helper.cpp	186	0x4ed828	

## C++ source code
`//

    /* 3 Do Predict Forward */
    MXPredForward(pred_hnd);

    // 4 Get Output Result
    int output_size = 0;

    /*bbox_pred, cls_prob*/
    vector<mx_uint> output_index = {0, 1};
    vector<mx_uint> bbox_shape;
    std::vector<float> bbox_data;
    GetOutput(pred_hnd, output_index[0], bbox_shape, bbox_data, output_size);

    vector<mx_uint> cls_shape;
    std::vector<float> cls_data;
    GetOutput(pred_hnd, output_index[1], cls_shape, cls_data, output_size);
`

` //

    void GetOutput(PredictorHandle pred_hnd, const int output_index, vector<mx_uint> &shapes, std::vector<float> &data, int &output_size){
    mx_uint *shape = 0;
    mx_uint shape_len;
    shapes.clear();
    // Get Output Result
    MXPredGetOutputShape(pred_hnd, output_index, &shape, &shape_len);
    size_t size = 1;
    for (mx_uint i = 0; i < shape_len; ++i){
        size *= shape[i];
        shapes.push_back(shape[i]);
    }
    std::cout<<"shape: "; for (mx_uint i=0;i<shape_len;i++) std::cout<<", "<<shape[i]; std::cout<<std::endl;
    /* prepare the space for output */
    data.resize(size);
    output_size = size;
    MXPredGetOutput(pred_hnd, output_index, &(data[0]), size);
    }
`

**Comment by Maratyszcza** [comment]
I recently fixed a race condition in pthreadpool (see Maratyszcza/pthreadpool@630dfb6638927df1f3181eee339662a86b3cea0b), the threading library used by NNPACK. This race condition sometimes resulted in deadlock. If you use an earlier pthreadpool version, this is the likely cause of your problem.

**Comment by pallashadow** [comment]
@Maratyszcza 
fixed, love you.
