### ISSUE TITLE
If a output of a static graph doesn't connect to a loss function or BlockGrad, what will happen?

### ISSUE THREAD

**Issue by yang1fan2** [dmlc/mxnet#552]
Can I construct a static graph like this?
During backward process, will the error, which is propagated in this particular output, be zero?

Thanks;

**Comment by pluskid** [comment]
+1 for this question. We should document this clearly. Will an error be raised? Or will just arbitrary garbage gradient be back-propagated leading to undefined behavior?

**Comment by tqchen** [comment]
Users is asked to pass a top_grad in this case on backward, for each of non-blocked output. So you can treat this as an layer and even chain multiple executors together

**Comment by pluskid** [comment]
@tqchen Yes, but what happens if the user run `backward` without passing top_grad, will an error be raised?

**Comment by tqchen** [comment]
Yes, an error will be raised
