### ISSUE TITLE
'Undefined Symbol: sdot_ ' error when running the mnist example

### ISSUE THREAD

**Issue by canchen257** [dmlc/mxnet#553]
Hi, I have successfully build mxnet and install python package, but when I try to run the mnist example
![4](https://cloud.githubusercontent.com/assets/7553233/11112177/7ea4e05e-894b-11e5-9acc-61e907172709.jpg)

I got the error as below:
![2](https://cloud.githubusercontent.com/assets/7553233/11111971/4d19fe2c-8949-11e5-9c8c-c2bd977fd712.jpg)

My environment is Ubuntu 14.04 and I have installed the blas, cblas and lapack successfully following this article: http://blog.csdn.net/mlnotes/article/details/9676269. And the .a file s is in the usr/local/lib as below:
![3](https://cloud.githubusercontent.com/assets/7553233/11112061/3dfc1e2e-894a-11e5-895d-a6d341e22fbf.jpg)

At the same time, I have modify USE_BLAS = blas in config.mk as suggest in this thread: https://github.com/dmlc/mxnet/issues/245. However, I can not solve this problem either.  Could anybody help me?

**Comment by vchuravy** [comment]
since you have `libcblas` and `libblas` you probablk have a netblas installed so you should set `USE_BLAS = atlas`. And then do `make clean && make` what error do you then get?

**Comment by canchen257** [comment]
@vchuravy After make clean in the mxnet root file, It seems the situation becomes worse. I meet some problems I have never met before. Now I could NOT make -j4.
![5](https://cloud.githubusercontent.com/assets/7553233/11113934/a6ab2134-895b-11e5-9266-a55ae06d70d7.jpg)

**Comment by vchuravy** [comment]
Could you try installing `libblas-dev` with `apt-get`? It seems you are missing the correct header files.

**Comment by canchen257** [comment]
@vchuravy after I use the sudo apt-get libblas-dev， I still meet the problem below:
![6](https://cloud.githubusercontent.com/assets/7553233/11114337/faf50d06-895e-11e5-82ff-6c3fa4525be6.jpg)
I wonder why this would happen?

**Comment by canchen257** [comment]
@vchuravy  Well, when I change USE_BLAS = blas， I can build the library successully. However, when I run the mnist example, I still meet the problem in the beginning : undefined symbol:sdot_.

**Comment by tqchen** [comment]
This could due to in-compete version of the blas, Maybe you can consider build with other blas, for example OpenBlas instead

**Comment by tqchen** [comment]
closing for now, feel free to reopen when needed
