### ISSUE TITLE
Ask : Prediction with single image with API Module

### ISSUE THREAD

**Issue by Shiro-mx** [dmlc/mxnet#5556]
hello, 
I was wondering if it is possible to predict on a picture without creating and saving a .rec and .lst file with API Module ? I know it is possible with mxnet amalgamation, but using gpu is impossible with this version of mxnet

**Comment by sergeykolychev** [comment]
https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/module.py#L527
https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/module.py#L571
