### ISSUE TITLE
I think we need a instant messenger

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#556]
we need a im to do better communication.

**Comment by vchuravy** [comment]
I would be in favor of having an IRC channel

**Comment by zachmayer** [comment]
How about gitter?  e.g. https://gitter.im/dmlc/mxnet

**Comment by pluskid** [comment]
Does gitter allow you to search (all) the chat history? 

I'm not objecting other kinds of communication channels, but what is the downside of just using github issues?

**Comment by zachmayer** [comment]
I think it does let you search all history.  I think the goal of something like gitter is to allow people to ask random question that might not be appropriate for issues, and let developers coordinate.  It's very similar to IRC.  Lots of github repos seem to be using gitter, so I made the suggestion.

**Comment by winstywang** [comment]
Gitter is good for some quick questions.

**Comment by vchuravy** [comment]
I just found irc.gitter.im which allows you to connect via a traditional irc client to gitter so I am fine with that too.

**Comment by starimpact** [comment]
likely most of you guys like gitter, so ask the Tianqi Chen to create one.
OK?

**Comment by tqchen** [comment]
gitter added.
