### ISSUE TITLE
how to implement shared convolutional kernel by n input feature maps

### ISSUE THREAD

**Issue by caffeTao** [dmlc/mxnet#557]
Hi,i wanna use n filters sharing one convolutional kernel to filter n input feature map and output n feature map，i notice though feature maps are sliced, there will be n kernels,too. so how can we add an flag for sharing kernel?Looking forward to your instruction.thx.

**Comment by piiswrong** [comment]
I'm not sure if I understand but if the kernel is shared wouldn't the n outputs be identical?

**Comment by caffeTao** [comment]
not really, one input feature map a time, and for n input feature map there will be n output, but the kernel is the same, that's what i wanna do

**Comment by piiswrong** [comment]
that's a batch of n images right? Just make n the batchsize

**Comment by caffeTao** [comment]
sorry, my English is poor that makes you misunderstand. Not the batch,it's the channel that n represent, the operation is just like pooling, one featur map corresponds to one same kernel，the output n feature map. Maybe convolution is not designed to handle operation of this type. So i wonder how to implement it.

**Comment by tqchen** [comment]
If you want to share some kernel of convolution, you can create a common variable, and pass them in when you construct convolution, for example

```python
filter = mx.sym.Variable('filter')
out1 = mx.sym.Convolution(in1, weight=filter, no_bias=True)
out2 = mx.sym.Convolution(in2, weight=filter, no_bias=True)
```

**Comment by caffeTao** [comment]
will the filter be learned in training process? Does it need extra initiation? And can i use for recurrence to handle the channel data？ thx

**Comment by tqchen** [comment]
The filter can be binded, and you can get gradient from the filter, so in that sense it can be learned. In Current convention, it will be learnt if you set the name to end with suffix weight. It will be initialized as normal convolution weights.

I do not understand on what do you mean by recurrence

**Comment by caffeTao** [comment]
I'm so sorry for my poor representation. it's for circulation to handle all the feature maps like for(){}.For the suffix weight, i don't think i know what to do exactly, name the filter "filter_weight"?

**Comment by tqchen** [comment]
Yes, ''layer_k_filter_weight'' should be a nice name

**Comment by caffeTao** [comment]
thx, I 'll have a try

**Comment by tqchen** [comment]
closing for now, feel free to reopen if you have further questions

**Comment by umichyiwan** [comment]
do I need to explicitly use different names for shared weights layers or I can just simply leave it blank and let mxnet assign names for those layers. Does the name of layers really matters?
Thank you!

**Comment by biycyr** [comment]
@tqchen I have tried to create shared layers. I tried your answer on mxnet/example/image-classification/symbols/mlp.py
`
def get_symbol(num_classes=10, **kwargs):
    data = mx.symbol.Variable('data')
    data = mx.sym.Flatten(data=data)
    fc1_weight = mx.symbol.Variable('fc1_weight',init=mx.init.Xavier())
    b1_weight = mx.symbol.Variable('b1_wweight',init=mx.init.Xavier())
    fc2_weight = mx.symbol.Variable('fc2_wweight',init=mx.init.Xavier())
    b2_weight = mx.symbol.Variable('b2_weight',init=mx.init.Xavier())
    fc3_weight = mx.symbol.Variable('fc3_weight',init=mx.init.Xavier())
    b3_weight = mx.symbol.Variable('b3_weight',init=mx.init.Xavier())
    fc1  = mx.symbol.FullyConnected(data = data, weight=fc1_weight,bias=b1_weight,name='fc1', num_hidden=128)
    act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
    fc2  = mx.symbol.FullyConnected(data = act1, weight=fc2_weight,bias=b2_weight,name = 'fc2', num_hidden = 64)
    act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
    fc3  = mx.symbol.FullyConnected(data = act2, weight=fc3_weight,bias=b3_weight,name='fc3', num_hidden=num_classes)
    mlp  = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
    return mlp`

but I get 
'IndexError: tuple index out of range'

Do I need to assign the shape of weights first?

**Comment by CheungDuMing** [comment]
very complex! no function as the same as reuse_variable in tensorflow?
