### ISSUE TITLE
compile mxnet dmlccore.lib error on VS2015

### ISSUE THREAD

**Issue by louiskoo520** [dmlc/mxnet#5576]
dmlccore.lib(local_filesys.obj) : error LNK2038: 检测到“_MSC_VER”的不匹配项:  值“1900”不匹配值“1800”(image-classification-predict.obj 中)
4>LIBCMTD.lib(stdexcpt.obj) : error LNK2005: "public: __cdecl std::bad_cast::bad_cast(class std::bad_cast const &)" (??0bad_cast@std@@QEAA@AEBV01@@Z) 已经在 dmlccore.lib(local_filesys.obj) 中定义
4>LIBCMTD.lib(stdexcpt.obj) : error LNK2005: "public: __cdecl std::exception::exception(class std::exception const &)" (??0exception@std@@QEAA@AEBV01@@Z) 已经在 dmlccore.lib(local_filesys.obj) 中定义
4>LIBCMTD.lib(stdexcpt.obj) : error LNK2005: "public: virtual __cdecl std::bad_cast::~bad_cast(void)" (??1bad_cast@std@@UEAA@XZ) 已经在 dmlccore.lib(local_filesys.obj) 中定义
4>LIBCMTD.lib(stdexcpt.obj) : error LNK2005: "public: virtual __cdecl std::exception::~exception(void)" (??1exception@std@@UEAA@XZ) 已经在 dmlccore.lib(local_filesys.obj) 中定义
4>LIBCMTD.lib(stdexcpt.obj) : error LNK2005: "public: virtual char const * __cdecl std::exception::what(void)const " (?what@exception@std@@UEBAPEBDXZ) 已经在 dmlccore.lib(local_filesys.obj) 中定义
4>LIBCMTD.lib(sprintf.obj) : error LNK2005: sprintf_s 已经在 dmlccore.lib(local_filesys.obj) 中定义
4>LIBCMTD.lib(vsnprnc.obj) : error LNK2005: _vsprintf_s_l 已经在 dmlccore.lib(local_filesys.obj) 中定义
4>dmlccore.lib(local_filesys.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl operator delete(void *,unsigned __int64)" (??3@YAXPEAX_K@Z)，该符号在函数 "int `public: virtual void __cdecl dmlc::io::LocalFileSystem::ListDirectory(struct io::LocalFileSystem::URI const &,class std::vector<struct dmlc::io::FileInfo,class std::allocator<struct dmlc::io::FileInfo> > *)'::`1'::dtor$4" (?dtor$4@?0??ListDirectory@LocalFileSystem@io@dmlc@@UEAAXAEBUURI@23@PEAV?$vector@UFileInfo@io@dmlc@@V?$allocator@UFileInfo@io@dmlc@@@std@@@std@@@Z@4HA) 中被引用
4>dmlccore.lib(local_filesys.obj) : error LNK2019: 无法解析的外部符号 _Init_thread_header，该符号在函数 "class std::_Iostream_error_category & __cdecl std::_Immortalize<class std::_Iostream_error_category>(void)" (??$_Immortalize@V_Iostream_error_category@std@@@std@@YAAEAV_Iostream_error_category@0@XZ) 中被引用
4>dmlccore.lib(local_filesys.obj) : error LNK2019: 无法解析的外部符号 _Init_thread_abort，该符号在函数 "int `class dtor$0::_Iostream_error_category & __cdecl std::_Immortalize<class std::_Iostream_error_category>(void)'::`1'::dtor$0" (?dtor$0@?0???$_Immortalize@V_Iostream_error_category@std@@@std@@YAAEAV_Iostream_error_category@0@XZ@4HA) 中被引用
4>dmlccore.lib(local_filesys.obj) : error LNK2019: 无法解析的外部符号 _Init_thread_footer，该符号在函数 "class std::_Iostream_error_category & __cdecl std::_Immortalize<class std::_Iostream_error_category>(void)" (??$_Immortalize@V_Iostream_error_category@std@@@std@@YAAEAV_Iostream_error_category@0@XZ) 中被引用
4>dmlccore.lib(local_filesys.obj) : error LNK2019: 无法解析的外部符号 __acrt_iob_func，该符号在函数 "public: virtual class dmlc::SeekStream * __cdecl dmlc::io::LocalFileSystem::Open(struct dmlc::io::URI const &,char const * const,bool)" (?Open@LocalFileSystem@io@dmlc@@UEAAPEAVSeekStream@3@AEBUURI@23@QEBD_N@Z) 中被引用
4>dmlccore.lib(local_filesys.obj) : error LNK2019: 无法解析的外部符号 __stdio_common_vsprintf_s，该符号在函数 _vsprintf_s_l 中被引用
4>dmlccore.lib(local_filesys.obj) : error LNK2019: 无法解析的外部符号 __std_exception_copy，该符号在函数 "public: __cdecl std::exception::exception(class std::exception const &)" (??0exception@std@@QEAA@AEBV01@@Z) 中被引用
4>dmlccore.lib(local_filesys.obj) : error LNK2019: 无法解析的外部符号 __std_exception_destroy，该符号在函数 "public: virtual __cdecl std::exception::~exception(void)" (??1exception@std@@UEAA@XZ) 中被引用
4>dmlccore.lib(local_filesys.obj) : error LNK2001: 无法解析的外部符号 _Init_thread_epoch
4>D:\Python\MXNet\mxnet1\mxnet\build\example\image-classification\predict-cpp\Debug\image-classification-predict.exe : fatal error LNK1120: 9 个无法解析的外部命令

**Comment by yajiedesign** [comment]
strange..

**Comment by louiskoo520** [comment]
@yajiedesign  cpmpile of the latest mxnet on win10 using vs2015 need have to use opencv3 while I used opencv2.4 now?

**Comment by yajiedesign** [comment]
@louiskoo520 opencv3
