### ISSUE TITLE
Issues on installing mxnet on R with GPU support on Windows 10

### ISSUE THREAD

**Issue by EddieIT** [dmlc/mxnet#5577]
I am attempting to install mxnet on R with GPU support on windows 10, but encountered numerous errors during the process. 

After some digging, I have identified the root of the issues. Overall, the installation file and source code for R is a total mess. I followed the instruction in this link [http://mxnet.io/get_started/windows_setup.html](url). After running `R CMD INSTALL --no-multiarch R-package` on the command prompt, the first issue encountered is this:
* installing to library 'D:/R/R-3.3.3/library'
* installing *source* package 'mxnet' ...
ERROR: a 'NAMESPACE' file is required
* removing 'D:/R/R-3.3.3/library/mxnet'`

After resolving this by referring to this link [http://stackoverflow.com/questions/17196225/error-a-namespace-file-is-required](url), another issue occuered due to missing "nnvm" file. Error as follow:

* installing to library 'D:/R/R-3.3.3/library'
* installing *source* package 'mxnet' ...
** libs
c:/Rtools/mingw_64/bin/g++  -I"D:/R/R-3.3.3/include" -DNDEBUG -I../inst/include   -I"D:/R/R-3.3.3/library/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c mxnet.cc -o mxnet.o
In file included from mxnet.cc:9:0:
./ndarray.h:11:24: fatal error: nnvm/c_api.h: No such file or directory
 #include <nnvm/c_api.h>
                        ^
compilation terminated.
make: *** [mxnet.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "D:/R/R-3.3.3/etc/x64/Makeconf" -f "D:/R/R-3.3.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mxnet.dll" WIN=64 TCLBIN=64 OBJECTS="executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o"' had status 2
ERROR: compilation failed for package 'mxnet'
* removing 'D:/R/R-3.3.3/library/mxnet'

After resolving this by downloading the nnvm from some other place, then there is issue with source code. The source code apparently is missing some functions. Error as follow:
* installing to library 'D:/R/R-3.3.3/library'
* installing *source* package 'mxnet' ...
** libs
c:/Rtools/mingw_64/bin/g++  -I"D:/R/R-3.3.3/include" -DNDEBUG -I../inst/include   -I"D:/R/R-3.3.3/library/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c mxnet.cc -o mxnet.o
In file included from mxnet.cc:8:0:
./base.h: In function 'std::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                          ^
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                        ^
mxnet.cc: In function 'void mxnet::R::ProfilerSetConfig(int, const string&)':
mxnet.cc:27:53: error: 'MXSetProfilerConfig' was not declared in this scope
   MX_CALL(MXSetProfilerConfig(mode, filename.c_str()));
                                                     ^
./base.h:81:14: note: in definition of macro 'MX_CALL'
     int e = (func);                                                \
              ^
mxnet.cc: In function 'void mxnet::R::ProfilerSetState(int)':
mxnet.cc:31:35: error: 'MXSetProfilerState' was not declared in this scope
   MX_CALL(MXSetProfilerState(state));
                                   ^
./base.h:81:14: note: in definition of macro 'MX_CALL'
     int e = (func);                                                \
              ^
make: *** [mxnet.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "D:/R/R-3.3.3/etc/x64/Makeconf" -f "D:/R/R-3.3.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mxnet.dll" WIN=64 TCLBIN=64 OBJECTS="executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o"' had status 2
ERROR: compilation failed for package 'mxnet'
* removing 'D:/R/R-3.3.3/library/mxnet'

Overall, the installation file and source code for R is pretty sloppy. Would appreciate if anyone have any means on installing mxnet.

**Comment by EddieIT** [comment]
After some fiddling, I realised that the newest version of mxnet might not support R. To install mxnet in R on windows, I have to use the windows binaries along with the source code that is released on the same date.

This is actually kind of disappointing. It would be great if mxnet for R is kept up to date.

**Comment by thirdwing** [comment]
Please follow my instruction from https://gist.github.com/thirdwing/89aa9bfc588ade138496e6932072152c

The installation has been test on a Windows Server machine with GPU. It will be merged into the documents later.

![mxnet_r_gpu_win](https://cloud.githubusercontent.com/assets/1547093/26741283/a38b842a-478d-11e7-9656-3e30b1cf8ecf.jpg)
