### ISSUE TITLE
More Complicated Labels

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#558]
how can i pass the bounding boxes info into an operator

**Comment by piiswrong** [comment]
it's just a vector of 4 numbers

**Comment by starimpact** [comment]
the original label part of  input data is just one dimension. how can i make it be 4 dimensions.

**Comment by starimpact** [comment]
use infershape？

**Comment by XericZephyr** [comment]
You might want to use `mx.io.ImageRecordIter` to pass in label with width 4. And you will need the tricks below to help you use lengthy label (and, unfortunately, the label size must be fixed). 

1. Before you do preprocessing, write image list as follow: 
```
image_index  \t  label_1 \t  label_2  \t label_3 \t label_4 \t image_path 
```
2. When you use `im2rec` tool, remember to set `label_width=4` in the command line to generate specific RecordIO file. 
3. In your python code, pass `label_width=4` and `path_imglist=<<YOUR_IMAGE_LIST_PATH>>` to the `ImageRecordIter` constructor. 
Then you are good to pop out the label with size (batch_size, label_width) with `mx.io.ImageRecordIter`. 

Hope it helps. 

BTW, @piiswrong the usage of mysterious `label_width` magic is still missing in the document. Could we just write it into the document?

**Comment by starimpact** [comment]
thanks, but using intershape is ok.
actually, i need to pass a label matrix and a label vector, not only a label vector.

**Comment by tqchen** [comment]
Now that #504  is merged in. You can build a index to get the labels you want.

**Comment by tqchen** [comment]
@XericZephyr Yes, the label_woth is exactly what you meant, can you contribute a PR to add your understanding to the doc?

**Comment by XericZephyr** [comment]
Thanks for inviting. I will be working on it shortly.

**Comment by luxiangju** [comment]
@XericZephyr 
I tried multi_label training in the same way, but the model.fit returns the error:
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in softmax's label argument
Corresponding keyword of symbol: softmax_label
Shape inconsistent, Provided =(192,2), inferred shape=(192,1)

BTW: how to use the intershape ?

**Comment by paipai880429** [comment]
@luxiangju Same problem. And in image.lst, I turned the multi-label to  a binary vector: 1 0 0 1 1 to represent the labels.

**Comment by xiadeye** [comment]
how to set label-width with im2rec.py? It returns 'im2rec.py: error: unrecognized arguments: --label-width=7'

**Comment by edwardfang** [comment]
> how to set label-width with im2rec.py? It returns 'im2rec.py: error: unrecognized arguments: --label-width=7'

you may use `--pack-label`
