### ISSUE TITLE
callbacks destroy 'value' in BatchEndParam for subsequent callbacks of that type

### ISSUE THREAD

**Issue by jmerkow** [dmlc/mxnet#5590]
It appears that calling one callback seem destroy the value in BatchEndParam.

Using callbacks like:
```
    batch_end_callbacks = [mx.callback.Speedometer(args.batch_size, 20),
                           mx.callback.Speedometer(args.batch_size, 10)]
```

Results in the following log:

> INFO:root:Epoch[0] Batch [10]   Speed: 60.70 samples/sec        Train-accuracy=0.122869
> INFO:root:Epoch[0] Batch [20]   Speed: 60.85 samples/sec        Train-accuracy=0.157031
> INFO:root:Epoch[0] Batch [20]   Speed: 61.00 samples/sec        Train-accuracy=nan
> INFO:root:Epoch[0] Batch [30]   Speed: 61.01 samples/sec        Train-accuracy=0.164844
> INFO:root:Epoch[0] Batch [40]   Speed: 61.20 samples/sec        Train-accuracy=0.191406
> INFO:root:Epoch[0] Batch [40]   Speed: 61.39 samples/sec        Train-accuracy=nan
> INFO:root:Epoch[0] Batch [50]   Speed: 60.78 samples/sec        Train-accuracy=0.194531
> INFO:root:Epoch[0] Batch [60]   Speed: 60.84 samples/sec        Train-accuracy=0.221875
> INFO:root:Epoch[0] Batch [60]   Speed: 60.90 samples/sec        Train-accuracy=nan

**Comment by zihaolucky** [comment]
@jmerkow it has been reset.

**Comment by jmerkow** [comment]
Do you know where this is happening?

**Comment by zihaolucky** [comment]
I guess

https://github.com/dmlc/mxnet/blob/master/python/mxnet/metric.py#L43-L50

https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L462

https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/base_module.py#L485-L488
