### ISSUE TITLE
the name method of outputs of slicechannel should be changed!

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#5599]
Hi, @piiswrong 
now name method is the following:
```cpp
  std::vector<std::string> ListOutputs() const override {
    std::vector<std::string> ret;
    for (int i = 0; i < param_.num_outputs; ++i) {
      ret.push_back(std::string("output") + static_cast<char>('0' + i));
    }   
    return ret;
  }
```
it use the ascii table to name the outputs of slicechannel, and start from char '0'. so, it can only support 256-30=226 outputs maximally.
I suggest to use number to replace it.

**Comment by piiswrong** [comment]
it's already fixed.
