### ISSUE TITLE
[Discussion] Uneven load for different GPU device?

### ISSUE THREAD

**Issue by XericZephyr** [dmlc/mxnet#561]
The current set up for mxnet is assuming Multiple GPUs have same or similar capacity. So the data parallelism is done evenly for every GPU. 

Now let's consider, what if we have three GPUs, e.g. one 980 with 3GB memory and two Titan X with 12 GB memory? 

Seems we have two options:

1. The batch size should be set to fit the 980 device, which wastes the power of the two Titan X. 
2. Or we ignore the 980 device and use just two Titan X devices, which wastes the computing power of the 980. 

Neither of them is perfect, so probably we shall figure out a way to distribute the data unevenly to different devices. Just a suggestion, thanks.

**Comment by mli** [comment]
you can change the split function:

https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L80

it currently changes the batch equally. you can changes into according to the gpu memory, but i guess according the gpu flops is better.

**Comment by XericZephyr** [comment]
@mli  Thanks! I am aware of the code. However, only modifying this part is not general enough. I will try to open a PR shortly to solve this issue. Thanks.

**Comment by tqchen** [comment]
This is merged in #566
