### ISSUE TITLE
Cannot find symbol MultiBoxPrior and other contribs

### ISSUE THREAD

**Issue by lvaleriu** [dmlc/mxnet#5610]
**'Module' object has no attribute 'MultiBoxPrior'**

## Environment info
Operating System: Ubuntu 16.04

MXNet version - installed from source:
MXNet commit hash (`git rev-parse HEAD`): f0a450d6d5605f4d5d59f974460673be4251b70c

Python version and distribution: python 2.7.12

## Error Message:
Traceback (most recent call last):
  File "***/ssd/demo.py", line 168, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "***/ssd/demo.py", line 106, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "***/ssd/symbol/symbol_vgg16_reduced.py", line 163, in get_symbol
    net = get_symbol_train(num_classes)
  File "***/ssd/symbol/symbol_vgg16_reduced.py", line 119, in get_symbol_train
    num_channels=num_channels, clip=True, interm_layer=0)
  File "***/ssd/symbol/common.py", line 164, in multibox_layer
    anchors = mx.contrib.symbol.MultiBoxPrior(from_layer, sizes=size_str, ratios=ratio_str, \
**AttributeError: 'module' object has no attribute 'MultiBoxPrior'**

## Minimum reproducible example
**Run the demo code from example/ssd/demo.py**

## Steps to reproduce
Run the demo code from example/ssd/demo.py

## What have you tried to solve it?

Build the mxnet project from sources with different options (DEBUG=1, DEV=1, USE_PROFILE=1) and then python setup.py install

**Comment by piiswrong** [comment]
did you rebuild after updating mxnet?

**Comment by lvaleriu** [comment]
Of course. I did a make clean each time. 
mxnet-0.9.5-py2.7.egg
print (mx.__version__) = 0.9.5

**Comment by lvaleriu** [comment]
Compiled again this morning with the latest sources and it works now. I can use again this symbol. Wonder what caused the issue a few days ago.

**Comment by lvaleriu** [comment]
I just tried one thing: Build the mxnet submodule from the mxnet-ssd official repository. This time it worked - i can run again the ssd demo script from the mxnet/example directory. The mxnet fork doesnt seem to be very distant from the latest master, so i dont get what is different.

**Comment by zhreshold** [comment]
pull the latest code plz. f0a450d is updated 8 days ago, while the pr is merged 3 days ago.

**Comment by lvaleriu** [comment]
All is clean again. Thanks!
