### ISSUE TITLE
Training an MLP using my own data

### ISSUE THREAD

**Issue by nikrao** [dmlc/mxnet#5614]
I am learning MXNet, and to see if I really understand what's going on, I decided to try and learn a multilayer perceptron on some toy data a generated. I create some synthetic data of size n X d, and corresponding labels of size n X 1. 

I also have test data of size m X d and corresponding m X 1 labels. 

I create the iterables as:

`batch_size = 100`
`train_iter = mx.io.NDArrayIter(Xtr, ytr, batch_size, shuffle=True)`
`val_iter   = mx.io.NDArrayIter(Xtt, ytt, batch_size)`

and an MLP as:
`# input data`
`net = mx.sym.Variable('data')`
`# input layer`
`net = mx.sym.FullyConnected(data = net, name='fc1',num_hidden=100)`
`net = mx.sym.Activation(data=net,name='act1',act_type='relu')`
`# second layer `
`net = mx.sym.FullyConnected(data=net,name='fc2',num_hidden=50)`
`net = mx.sym.Activation(data=net,name='act2',act_type='tanh')`
`# output layer`
`net = mx.sym.FullyConnected(data=net,name='fc3',num_hidden=1)`
`net = mx.sym.Activation(data=net,name='output',act_type='sigmoid')`

I then set up the model and train:

`model.fit(`
`    X=train_iter,      `
 `   eval_data=val_iter, `
 `   batch_end_callback = mx.callback.Speedometer(batch_size, 200) `
`)`

I get the following error:

`infer_shape error. Arguments:`
 ` data: (100, 500L)`
`  softmax_label: (100, 1L)`

The sizes seem fine to me. Any idea what's happening?

**Comment by ysh329** [comment]
You can refer this issue:
I wann to train ResNet-50 based on my data · Issue #5404 · dmlc/mxnet
https://github.com/dmlc/mxnet/issues/5404

**Comment by ysh329** [comment]
The model size is related to **the size of input image before first train** and network input user defined. 

For example, if you train a ResNet using 3*229*229-size input image, you will get a pretrained model with 3*229*229-size input. In addition, this's also related to the model itself, if the model does not have a full connection layer, then size of input image can be ignored.

**Comment by nikrao** [comment]
Thanks for the reply. But what about cases when I don't have an *image* as input? My input is just a 500 dimensional vector. (the 500L above). In that case, the input fully connected layer
` net = mx.sym.FullyConnected(data = net, name='fc1',num_hidden=100)`

should be able to take care of this right? It is already flattened so I do not have to use the `mx.sym.Flatten()` function . 

In the MNIST case, the flatten() function takes an image of size `1 x 28 x 28` and returns a vector of length `784`

**Comment by piiswrong** [comment]
try resize label to (100,)

**Comment by nikrao** [comment]
Hi @piiswrong , thanks for the suggestion. That was my initial shape of the data, and I got the same error. I tried it again:

`infer_shape error. Arguments:`
 ` data: (100, 500L)`
 ` softmax_label: (100,)`

Below, I am also copying the rest of the error message I get:

---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-6-215bc5e47146> in <module>()
      4     X=train_iter,       # training data ITERABLE
      5     eval_data=val_iter, # validation data ITERABLE
----> 6     batch_end_callback = mx.callback.Speedometer(batch_size, 200) # output progress for each 200 data batches
      7 )

/usr/local/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/model.pyc in fit(self, X, y, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, logger, work_load_list, monitor, eval_end_callback, eval_batch_end_callback)
    770 
    771         arg_names, param_names, aux_names = \
--> 772                 self._init_params(dict(data.provide_data+data.provide_label))
    773 
    774         # setup metric

/usr/local/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/model.pyc in _init_params(self, input_shapes, overwrite)
    498     def _init_params(self, input_shapes, overwrite=False):
    499         """Initialize weight parameters and auxiliary states"""
--> 500         arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
    501         assert(arg_shapes is not None)
    502 

/usr/local/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/symbol.pyc in infer_shape(self, *args, **kwargs)
    635         """
    636         try:
--> 637             res = self._infer_shape_impl(False, *args, **kwargs)
    638             if res[1] is None:
    639                 arg_shapes, _, _ = self._infer_shape_impl(True, *args, **kwargs)

/usr/local/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/symbol.pyc in _infer_shape_impl(self, partial, *args, **kwargs)
    718             ctypes.byref(aux_shape_ndim),
    719             ctypes.byref(aux_shape_data),
--> 720             ctypes.byref(complete)))
    721         if complete.value != 0:
    722             arg_shapes = [

/usr/local/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.pyc in check_call(ret)
     76     """
     77     if ret != 0:
---> 78         raise MXNetError(py_str(_LIB.MXGetLastError()))
     79 
     80 if sys.version_info[0] < 3:

MXNetError: [10:17:37] src/c_api/c_api_symbolic.cc:398: InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias


Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x000000010e3d6978 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010e999a14 _ZN5mxnet14MatchArgumentsIN4nnvm6TShapeEEEvRKNS1_12IndexedGraphERKNSt3__113unordered_mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEET_NS6_4hashISD_EENS6_8equal_toISD_EENSB_INS6_4pairIKSD_SE_EEEEEEPNS6_6vectorISE_NSB_ISE_EEEEPKc + 3092
[bt] (2) 2   libmxnet.so                         0x000000010e997db9 MXSymbolInferShape + 1161
[bt] (3) 3   _ctypes.so                          0x000000010ca3e7d7 ffi_call_unix64 + 79

**Comment by piiswrong** [comment]
Your network doesn't have a loss layer. The last layer needs to be softmaxOutput

**Comment by nikrao** [comment]
ah !! dumb mistake. thanks ! that worked
