### ISSUE TITLE
'cufftResult_t' error when predicting a large image using fcn

### ISSUE THREAD

**Issue by huazehuang** [dmlc/mxnet#562]
Hi

I tried to predict a large image using fully convolutional network, mxnet terminated and gave me an error message as " **terminate called after throwing an instance of 'cufftResult_t'** "

The fcn implementation I used is from https://github.com/tornadomeet/mxnet/tree/fcn-xs/example/fcn-xs 

I think this is somewhat relates to a memory issue. I used a Titanx. In my machine, when the long edge of an image exceeds 505 pixels, mxnet throws this error. For example, images with the size of (224, 505), (505, 505) will give me this error. However, even I used a (504, 504) image, it will be fine. 

A 504 x 504 image use 9128 MB memory. And the TitanX has 11519 MB memory.

**Comment by tornadomeet** [comment]
currently the [fcn-xs example](https://github.com/tornadomeet/mxnet/tree/fcn-xs/example/fcn-xs) there is not Not completely ready, it only change the vgg16 model to fully-convolution-network style, so when u predict one image use the vgg16fc model, you should also resize it to (224,224) first;

**Comment by huazehuang** [comment]
@tornadomeet I think is not because the example itself. I also have my own version of fcn. It produces the same problem. Nevertheless both version are able to to work on a smaller image (less than 505).

**Comment by tornadomeet** [comment]
@huazehuang , thanks for report this bug. i just test large image, i think the problem is that the defalut  workspace for convolution is too small when u using very large image, so i update the [fcn-xs example](https://github.com/tornadomeet/mxnet/tree/fcn-xs/example/fcn-xs), u can change workspace_default's value depenod on your image size;
now the big image predict here is ok.

**Comment by huazehuang** [comment]
@tornadomeet Thanks for updating your code. 

The problem still exists. I have tried many large workspace size, but it didn't help. 

Did you try on GPU? In my case, increase workspace size can help to make it work on CPU, but not GPU.

Another strange thing is in [InitTemp function](https://github.com/dmlc/mxnet/blob/68a25b2c4e5e26c12045d433fece8c6e4d9c9d2d/src/operator/convolution-inl.h#L252), it already check if the workspace size can hold the convolution space.

**Comment by tornadomeet** [comment]
I test it on both GPU and CPU, also passed. can you give your test code.
for the InitTemp funciton, i also found it is broken when the input image is too large. though it checked, it seems that when should configure the workspace when we construct the convulution symbol.

**Comment by huazehuang** [comment]
The code is here [test example](https://github.com/huazehuang/mxnet/blob/fcn-xs/example/fcn-xs/test.py)

Thanks!

**Comment by huazehuang** [comment]
I resolve this issue by disabling the cudnn and recompiling mxnet. Thanks for helping!
