### ISSUE TITLE
MKL2017 numerical instability

### ISSUE THREAD

**Issue by cjolivier01** [dmlc/mxnet#5650]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu

Compiler:
gcc 5.4

Package used (Python/R/Scala/Julia):
Python

MXNet version:
0.9.4

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

cd example/rnn
sed -i '/args.mom/d' lstm_bucketing.py
./get_ptb_data.sh
python lstm_bucketing.py --optimizer adam

"When using a MXNet version that is compiled with USE_MKL2017=1, this will get to a Train-Perplexity of around 400 after one Epoch. When USE_MKL2017=0, this goes down to < 200 in the same number of steps."

"I can reproduce the problem also on my Ubuntu machine. If I enable USE_MKL2017=1 but comment out the support for just MKLFullyConnectedOP, I see results that are similar to MKL2017 turned off, i.e. at least part of the problem lies there.## What have you tried to solve it?"

2017-03-31 08:35:53,727 Epoch[0] Batch [1300]   Speed: 192.69 samples/sec       Train-Perplexity=599.170847
2017-03-31 08:35:54,749 Epoch[0] Train-Perplexity=614.747938
2017-03-31 08:35:54,749 Epoch[0] Time cost=289.619

**Comment by piiswrong** [comment]
@glingyan @zhenlinluo

**Comment by zhenlinluo** [comment]
This is regression issue caused by #5587 .
