### ISSUE TITLE
grad_req from symbol.bind doesn't work in lstm?

### ISSUE THREAD

**Issue by yang1fan2** [dmlc/mxnet#568]
Hi
      For the current lstm.py code, if I change grad_req in rnn_sym.bind from "add" to "write". It will produce the same perplexity curve as the one with "add".
      Moreover, I am rewriting the RNN components in mxnet and using similar design from TensorFlow. But I met some problems. I am pretty sure that the grad_req in my rewriting version is "write". Because under my experiments, the result get worser when the sequence length of input increase. Furthermore, I have used python/visualization.py to visual both the current lstm.py and my rewriting version. These two graph are the same.

Thanks;

**Comment by tqchen** [comment]
add and write should be the same if we update every batch, because the gradient is always accumulated before write to the gradient holder. 

The only difference was when doing update every two batches for example, then reset every two batch and with add will work differently than write

**Comment by pluskid** [comment]
+1, if you check out the parameter in the IPython notebook, it says
```
update_period = 1
```
so add and write are the same here.

**Comment by yang1fan2** [comment]
That's really helpful
Thanks;
