### ISSUE TITLE
Build error: "‘cv’ does not name a type" with USE_OPENCV = 0

### ISSUE THREAD

**Issue by benqua** [dmlc/mxnet#5685]
While building from source, an error:
```
src/io/image_det_aug_default.cc:18:14: error: ‘cv’ does not name a type
 using Rect = cv::Rect_<float>;
              ^
Makefile:207: recipe for target 'build/src/io/image_det_aug_default.o' failed
make: *** [build/src/io/image_det_aug_default.o] Error 1

```
is thrown.

This is weired because USE_OPENCV = 0 in config.mk.

## Environment info
Operating System:
Ubuntu 16.04
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
911f7474deafc3cc95a2589b89432f94f22cbbe1

## Error Message:
src/io/image_det_aug_default.cc:18:14: error: ‘cv’ does not name a type
 using Rect = cv::Rect_<float>;
              ^
Makefile:207: recipe for target 'build/src/io/image_det_aug_default.o' failed
make: *** [build/src/io/image_det_aug_default.o] Error 1

## Minimum reproducible example
Easily reproducible by following the step by step below on a newly installed ubuntu 16.04 without opencv. 
## Steps to reproduce
1. git clone --recursive https://github.com/dmlc/mxnet.git
2. cd mxnet/
3. emacs make/config.mk -> change USE_OPENCV = 1 to USE_OPENCV = 0
4. make -j8

It compiled fine on the same system with the same configuration with mxnet version 2735414c9f55e3e33d7eeb0c0293e0175e2644d6

**Comment by freddycct** [comment]
i experience this too

**Comment by freddycct** [comment]
any quickfix? i cannot continue when i cannot compile...
