### ISSUE TITLE
Does it make sense when using distributed training with different type GPUs

### ISSUE THREAD

**Issue by bachml** [dmlc/mxnet#5692]
Sorry for my pool English.

I have two machines, one has 4 * Titan X Pascal，the other one has 4 * 1080Ti. Both have nearly Single-Precision Performance. 

I am wondering if I can deploy distributed training with these two machines with different type GPUs. 
Thanks.

**Comment by bachml** [comment]
Further to say, does it make sense using distributed training with different performance machines, like 4*Titan machine with 3*Titan machine?

**Comment by eric-haibin-lin** [comment]
You need to adjust the 'workload' list accordingly when performing data parallel on heterogeneous machines 

On 2017年4月4日, at 20:36, bachml <notifications@github.com> wrote:

Further to say, does it make sense using distributed training with different performance machines, like 4Titan machine with 3Titan machine?
