### ISSUE TITLE
"ImportError: cannot import name libinfo" python import error on windows

### ISSUE THREAD

**Issue by xylcbd** [dmlc/mxnet#570]
platform : windows

1,build with vs2015 success;
2,python setup.py build && python setup.py install;
3,python$: import mxnet

then error accured:
<code>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "mxnet\base.py", line 10, in <module>
    from . import libinfo
ImportError: cannot import name libinfo
</code>

**Comment by tqchen** [comment]
I do not know what happened on this side, but seems https://github.com/dmlc/mxnet/blob/master/python/mxnet/libinfo.py was not found.

Another way you can try is simply add path to mxnet/python to the PYTHONPATH environment variable, or insert it to the first location sys.path everytime you import mxnet

**Comment by xylcbd** [comment]
![image](https://cloud.githubusercontent.com/assets/3643991/11230744/61495392-8ddc-11e5-8643-5df5c905b1e5.png)

nothing is modified.
Python 2.7.10 64bit  , win7 64bit (win10 64bit) system

**Comment by tqchen** [comment]
closing due to inactive status, feel free to reopen if there is update

**Comment by JunWorks** [comment]
I have to same error, and I can confirm libinfo.py is in the same library as base.py. Any idea?

**Comment by lancerts** [comment]
Installed mxnet according to https://github.com/dmlc/mxnet/releases. However, the same error. It is clear that  libinfo.py is in the same library as base.py.

Solution?

**Comment by hjk41** [comment]
can some python guru look into this?

On Wed, Jan 13, 2016 at 8:07 AM, lancerts <notifications@github.com> wrote:

> Installed mxnet according to https://github.com/dmlc/mxnet/releases.
> However, the same error. It is clear that libinfo.py is in the same library
> as base.py.
>
> Solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/570#issuecomment-171106116>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by xgfs** [comment]
Apparently it can be solved if you put cudnn & opencv & BLAS dlls in the Anaconda's site-packages folder. The problem is that libinfo.py only gives info about the libmxnet, that depends on these three libraries that are not being copied.

**Comment by xylcbd** [comment]
I copied these dlls , and issue still exists.

**Comment by xylcbd** [comment]
It works, the solution is below.

1st:
python build & install success
2st:
copy all dependence dlls(opencv,openblas etc.) to C:\Python27\Lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\
3rd:
before import mxnet add mxnet package path to PATH environment.
os.environ['PATH']=r'C:\Python27\Lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet;' + os.environ['PATH']

**Comment by Hermes777** [comment]
what if it happens on ubuntu? I'm now facing the problem.

**Comment by xylcbd** [comment]
everything is ok on ubuntu with python 2.7.

**Comment by Vesnica** [comment]
I found another reason may cause this problem: screen

I always launch notebook(jupyter) in a screen session, and I'm not aware that screen will unset LD_LIBRARY_PATH env var, so the library load will fail

To fix this, add content below to ~/.screenrc:
`setenv LD_LIBRARY_PATH /usr/local/cuda-7.5/lib64(or your lib path)`

then restart screen sessions to take effect

**Comment by dtmoodie** [comment]
xylcbd's solution fixed my problem, is there any danger to adding that call early in the __init__.py file for mxnet?

**Comment by CharlesMei** [comment]
When i compile mxnet in my win10 laptop，i get similar error ```self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]``` . I copy the files(```libgcc_s_seh-1.dll、libgfortran-3.dll、libopenblas.dll、libquadmath-0.dll```) in the prebuild mxnet (3rdparty\openblas\bin) to solve the problem, it works. People who meet the same problem can try  this.

**Comment by yasserzamani** [comment]
@CharlesMei , I had same issue (even when those files was already in my PATH) but running jupyter notebook inside `Anaconda Prompt` fixed that! (without copying those files!)
