### ISSUE TITLE
Improve the doc of mx.operator.NumpyOp

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#571]
such as:
1. name ends with 'label' will not be allocated memory.
2. could pass some constant parameters by using __init__(self, param1, param2...) function.
3. the number of in_data is depended on the number of return values of function list_arguments.

I must guess and try to write myself operator with NumpyOp. :disappointed:

**Comment by starimpact** [comment]
1. name ends with 'label' will not be allocated memory for gradient.

**Comment by tqchen** [comment]
@starimpact  It would be great if you can contribute update to the NumpyOp docstring :)

**Comment by starimpact** [comment]
OK, but I will do it at free time, recently I am a little busy.Because I'm doing project with mxnet which I am just familiar with only half month.

**Comment by starimpact** [comment]
So many question are going to be solved:smile:

**Comment by tqchen** [comment]
Things are improving, thanks to all the contributors, including effort from you

**Comment by starimpact** [comment]
yes, I want make it better also.
I like the flexibility.
