### ISSUE TITLE
blas issue compile issue

### ISSUE THREAD

**Issue by Yunrui** [dmlc/mxnet#572]
hi all, 

I am encountering the blas compile issue on EI Capitan. I searched and found similar questions about it, saying reason might be bias not installed. So I installed openblas thru brew, changed config file as "USE_BLAS = openblas". No luck. And I also tried to export LIBRARY_PATH=/usr/local/Cellar/openblas/0.2.15/include/, still got the exactly same error as below.

Anyone shed some light?

In file included from include/mxnet/base.h:13:
In file included from ./mshadow/mshadow/tensor.h:16:
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
    #include <cblas.h>
             ^
In file included from src/c_api/c_predict_api.cc:9:
In file included from include/mxnet/symbolic.h:17:
In file included from include/mxnet/./base.h:13:
In file included from ./mshadow/mshadow/tensor.h:16:
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
    #include <cblas.h>
             ^
In file included from src/c_api/c_api.cc:11:
In file included from include/mxnet/base.h:13:
In file included from ./mshadow/mshadow/tensor.h:16:
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
    #include <cblas.h>
             ^
In file included from src/common/tblob_op_registry.cc:6:
In file included from include/mxnet/ndarray.h:17:
In file included from include/mxnet/./base.h:13:
In file included from ./mshadow/mshadow/tensor.h:16:
./mshadow/mshadow/./base.h:120:14: fatal error: 'cblas.h' file not found
    #include <cblas.h>
             ^
1 error generated.
1 error generated.
1 error generated.
1 errormake: *** [build/common/tblob_op_registry.o] Error 1 generated.

make: *** Waiting for unfinished jobs....
make: *** [build/c_api/c_predict_api.o] Error 1
make: *** [build/resource.o] Error 1
make: *** [build/c_api/c_api.o] Error 1

**Comment by pluskid** [comment]
An easier option is just to use the built-in BLAS of OS X:
```
USE_BLAS = apple
```
as in [make/osx.mk](make/osx.mk)

**Comment by Yunrui** [comment]
actually, I used "USE_BLAS = apple" at the very beginning, but encounter the same build failure. Then I thought my bias was not installed correctly, then I tried open blas....

**Comment by tqchen** [comment]
You want to add the path to CPLUS_INCLUDE_PATH and C_INCLUDE_PATH. Or add them in -I flag in the ADD_CFLAGS

**Comment by antinucleon** [comment]
Add modify the config.mk like this
```
ADD_LDFLAGS = -I/usr/local/opt/openblas/lib
ADD_CFLAGS =  -I/usr/local/opt/openblas/include
```

**Comment by phunterlau** [comment]
I had the exact similar issue before and my solution was: adding /usr/local/include and /usr/local/lib to the PATH, and `USE_BLAS = apple`

**Comment by Yunrui** [comment]
thanks, the issue was resolved by adding ADD_LDFLAGS and ADD_CFLAGS

**Comment by Strateus** [comment]
Had same issue, fixed it with same flags, but compilation stopped here:

/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:122: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:136: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:122: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:136: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

**Comment by martinbel** [comment]
As a reference, if those 2 lines are added to `make/osx.mk`, then the bash command in the docs remain the same: 
`cd mxnet; cp make/osx.mk ./config.mk; make -j$(sysctl -n hw.ncpu)`

**Comment by LiberiFatali** [comment]
For `ADD_LDFLAGS`, it should be `-L`

**Comment by nodejh** [comment]
First install `openblas `
```
$ brew install --fresh -vd openblas
......
macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openblas/lib
    CPPFLAGS: -I/usr/local/opt/openblas/include

==> Summary
🍺  /usr/local/Cellar/openblas/0.2.18_2: 20 files, 41.8M, built in 12 minutes 33 seconds
```


Then Add `ADD_LDFLAGS` and `ADD_CFLAGS ` to config.mk:

```
USE_BLAS = apple
ADD_LDFLAGS = -I/usr/local/opt/openblas/lib
ADD_CFLAGS =  -I/usr/local/opt/openblas/include
```

**Comment by anddelu** [comment]
I also meet this error:
/data/apps/mxnet/mshadow/mshadow/./base.h:136:23: fatal error: cblas.h: No such file or directory #include <cblas.h>

my environment:
centos 7
gcc  4.8.5
glibc 2.17
opencv 2.4.13
openblas 0.2.19

# set config.mk
ADD_LDFLAGS = -L/opt/OpenBLAS -L/opt/OpenBLAS/lib
ADD_CFLAGS = -L/opt/OpenBLAS -L/opt/OpenBLAS/lib
USE_BLAS = openblas

Thanks very much!

**Comment by nodejh** [comment]
First install `openblas`

```
$ brew install --fresh -vd openblas
......
macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openblas/lib
    CPPFLAGS: -I/usr/local/opt/openblas/include

==> Summary
🍺  /usr/local/Cellar/openblas/0.2.18_2: 20 files, 41.8M, built in 12 minutes 33 seconds
```

Then Add `ADD_LDFLAGS` and `ADD_CFLAGS` to config.mk:

```
USE_BLAS = apple
ADD_LDFLAGS = -I/usr/local/opt/openblas/lib
ADD_CFLAGS =  -I/usr/local/opt/openblas/include
```

**Comment by ChangliangSun** [comment]
apt-get install libblas-dev liblapack-dev

**Comment by ShankarNara** [comment]
OS used : MacOS
I am sorry ,

But where is this config.mk or osx.mk file?

**Comment by lonelygo** [comment]
> OS used : MacOS
> I am sorry ,
> 
> But where is this config.mk or osx.mk file?

cp make/osx.mk ./config.mk
then, find “USE_BLAS = apple” line
add
