### ISSUE TITLE
Take for ever to run forward()

### ISSUE THREAD

**Issue by data-compute-geek** [dmlc/mxnet#5722]
## Environment info
Operating System:  Deep Learning AMI for Amazon Linux
Package used (Python):
MXNet version: 0.7.0
Python version and distribution: 2.7

I am trying to use the Customized Symbol define at http://mxnet.io/tutorials/python/symbol.html, but it seems to take for ever to run the forward() method.  Debug shows that the it gets stuck at step self.assign(out_data[0], req[0], mx.nd.array(y)).

Here is the code:

import mxnet as mx;
import numpy as np;

class Softmax(mx.operator.CustomOp):
    def forward(self, is_train, req, in_data, out_data, aux):
        x = in_data[0].asnumpy()
        y = np.exp(x - x.max(axis=1).reshape((x.shape[0], 1)))
        y /= y.sum(axis=1).reshape((x.shape[0], 1))
        self.assign(out_data[0], req[0], mx.nd.array(y))
        print("Softmax.forward")
        
    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
        print("Softmax.backward")        
        l = in_data[1].asnumpy().ravel().astype(np.int)
        y = out_data[0].asnumpy()
        y[np.arange(l.shape[0]), l] -= 1.0
        self.assign(in_grad[0], req[0], mx.nd.array(y))

# register this operator into MXNet by name "softmax"
@mx.operator.register("softmax")
class SoftmaxProp(mx.operator.CustomOpProp):
    def __init__(self):
        # softmax is a loss layer so we don’t need gradient input
        # from layers above. 
        super(SoftmaxProp, self).__init__(need_top_grad=False)
    def list_arguments(self):
        return ['data', 'label']
    def list_outputs(self):
        return ['output']
    def infer_shape(self, in_shape):
        data_shape = in_shape[0]
        label_shape = (in_shape[0][0],)
        output_shape = in_shape[0]
        return [data_shape, label_shape], [output_shape], []
    def create_operator(self, ctx, shapes, dtypes):
        return Softmax()
    

class SimpleBatch(object):
    def __init__(self, data, label, pad=0):
        self.data = data
        self.label = label
        self.pad = pad

class SimpleIter:
    def __init__(self, data_names, data_shapes, data_gen,
                 label_names, label_shapes, label_gen, num_batches=10):
        self._provide_data = zip(data_names, data_shapes)
        self._provide_label = zip(label_names, label_shapes)
        self.num_batches = num_batches
        self.data_gen = data_gen
        self.label_gen = label_gen
        self.cur_batch = 0
    def __iter__(self):
        return self
    def reset(self):
        self.cur_batch = 0        
    def __next__(self):
        return self.next()
    @property
    def provide_data(self):
        return self._provide_data
    @property
    def provide_label(self):
        return self._provide_label
    def next(self):
        if self.cur_batch < self.num_batches:
            self.cur_batch += 1
            data = [mx.nd.array(g(d[1])) for d,g in zip(self._provide_data, self.data_gen)]
            assert len(data) > 0, "Empty batch data."
            label = [mx.nd.array(g(d[1])) for d,g in zip(self._provide_label, self.label_gen)]
            assert len(label) > 0, "Empty batch label."
            return SimpleBatch(data, label)
        else:
            raise StopIteration
            

num_classes = 10
net = mx.sym.Variable('data')
net = mx.sym.FullyConnected(data=net, name='fc1', num_hidden=64)
net = mx.sym.Activation(data=net, name='relu1', act_type="relu")
net = mx.sym.FullyConnected(data=net, name='fc2', num_hidden=num_classes)
#net = mx.sym.SoftmaxOutput(data=net, name='softmax')
net = mx.symbol.Custom(data=net, op_type='softmax')
print(net.list_arguments())
print(net.list_outputs())

n = 32
data = SimpleIter(['data'], [(n, 100)], 
                  [lambda s: np.random.uniform(-1, 1, s)],
                  ['custom0_label'], [(n,)], 
                  [lambda s: np.random.randint(0, num_classes, s)])

mod = mx.mod.Module(symbol=net,label_names=('custom0_label',))
mod.fit(data, num_epoch=5)

Can anyone give a hand?

Thanks.

**Comment by piiswrong** [comment]
please update mxnet

**Comment by data-compute-geek** [comment]
Thank you for the quick response. 
What would be the quickest way to update mxnet on  Deep Learning AMI for Amazon Linux? Or do I have to install mxnet from scratch following http://mxnet.io/get_started/amazonlinux_setup.html
Again, thank you for your help.

**Comment by piiswrong** [comment]
AMI should have the latest version. Are you sure you are using 0.7?
what does mxnet.__version__ show?

**Comment by data-compute-geek** [comment]
I ended up re-installing it and it seems to work now. I launched this instance a while ago. Maybe mxnet will not get updated if I don't release the instance. I will try another one and see if the version is the latest.
