### ISSUE TITLE
Any ideas about the conv kernel sizes in inception.py

### ISSUE THREAD

**Issue by cuihenggang** [dmlc/mxnet#573]
Hi,

I noticed that in "example/imagenet/inception.py", which I assume is the model for the 1000-class ImageNet dataset, the kernel sizes of the convolutional layers are a little different from the kernel sizes described in the original GoogLeNet paper. Did you discover this set of configurations would achieve higher accuracy?

Actually I just find the structure of the network is also a little different. In the original GoogLeNet paper, each set of inception layers (3a, for example) has a depth of 2 (at most two convolutional layers stacked one on the other), while in "inception.py", there is a set of three convolutional layer stacked together (called "double 3x3 reduce + double 3x3" in "inception.py"). Is it a bug or it's supposed to be like that?

Thanks,
Cui

**Comment by antinucleon** [comment]
It is Inception-6 Network, which is described in BatchNorm paper.
