### ISSUE TITLE
mxnet R Package install using devtools::install_github("dmlc/mxnet/R-package")

### ISSUE THREAD

**Issue by neten12** [dmlc/mxnet#5744]
I'm getting the following error when trying to install using devtools

Downloading GitHub repo dmlc/mxnet@master
from URL https://api.github.com/repos/dmlc/mxnet/zipball/master
Installing mxnet
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  '/tmp/RtmpCUvylF/devtools1ca26ea451c2/dmlc-mxnet-723966c/R-package'  \
  --library='/home/neten/R/x86_64-pc-linux-gnu-library/3.3' --install-tests 

* installing *source* package ‘mxnet’ ...
ERROR: a 'NAMESPACE' file is required
* removing ‘/home/neten/R/x86_64-pc-linux-gnu-library/3.3/mxnet’
* restoring previous ‘/home/neten/R/x86_64-pc-linux-gnu-library/3.3/mxnet’
Error: Command failed (1)
In addition: Warning message:
GitHub repo contains submodules, may not function as expected!

**Comment by jeremiedb** [comment]
install_github won't work. If you're on Linux, then I'm afraid you need to compile the library from source following those instructions: 
http://mxnet.io/get_started/build_from_source.html

If you're on Ubuntu, good news is that these instructions are quite straightforward and should work as is (add openblas FLAG in config if using it for blas).

**Comment by neten12** [comment]
Thanks for the response. I'll do that
