### ISSUE TITLE
Dying BilinearSampler

### ISSUE THREAD

**Issue by JohanCao** [dmlc/mxnet#5780]
Hi All,

I am trying to insert the BilinearSampler layer in my network. However, the network parameters stop updating after a few iterations. The reason is that the output of the BilinearSampler become all zeros (according to the document, out-boundary points will be padded as zeros after the sampler). Is there any way to fix this? Many thanks!

**Comment by piiswrong** [comment]
tune learning rate, initialization etc.

**Comment by JohanCao** [comment]
I did not normalize the grid, maybe this is why. But I am not sure why the grid has to be normalized to [-1,1], because I also tried to generate the grid with the GridGeneratorOp and the output grid is not normalized.  

I think the un-normalized grid is for resizing an image. Consider the following code which maximize an image 4X larger, the grid is between [-0.5, 0.5].

---------------------------------------------
import mxnet as mx
import numpy as np
import scipy.io as sio
from PIL import Image

im = Image.open('test2.png')
im_data = np.array(im, dtype = np.double)
im_data = np.swapaxes(im_data, 0, 2)
im_data = np.swapaxes(im_data, 1, 2)
im_data = np.expand_dims(im_data, 0)
im_data = mx.nd.array(im_data)

grid_data = mx.nd.array([[0.5,0,0,0,0.5,0]])  # affine matrix to maximize an image

# ---- symbol ---------
g_input = mx.symbol.Variable("g_input")
im_input = mx.symbol.Variable("im_input")
grid = mx.symbol.GridGenerator(data = g_input, transform_type = 'affine',target_shape = (im_data.shape[2],im_data.shape[3]))
out = mx.symbol.BilinearSampler(data = im_input, grid = grid)
# ----------------------


executor = out.bind(mx.cpu(),{'g_input':grid_data,'im_input':im_data})
output = executor.forward()
output = output[0].asnumpy()

output = np.squeeze(output)
output = np.swapaxes(output, 0, 2)
output = np.swapaxes(output, 0, 1)
im_save = Image.fromarray(np.uint8(output))
im_save.save('out_img.png')

**Comment by JohanCao** [comment]
The problem is not normalize to [-1,1]
