### ISSUE TITLE
SSD example GPU memory leak 

### ISSUE THREAD

**Issue by BensonBlack** [dmlc/mxnet#5781]
## Environment info
Operating System: Ubuntu 14.04

Compiler: gcc version 4.8.4

Package used (Python/R/Scala/Julia):Python

MXNet version:0.9.5

When running the SSD examples, the GPU memory increases  from the beginning to the end, which looks like a GPU memory leak problem. Did anybody get the same issue?

**Comment by edwardzeng** [comment]
You should set a more small batch size,for example 16,8 or 4.




发自网易邮箱大师
On 04/11/2017 20:47, BensonBlack wrote:
Environment info

Operating System: Ubuntu 14.04

Compiler: gcc version 4.8.4

Package used (Python/R/Scala/Julia):Python

MXNet version:0.9.5

When running the SSD examples, the GPU memory increases from the beginning to the end, which looks like a GPU memory leak problem. Did anybody get the same issue?

**Comment by BensonBlack** [comment]
@edwardzeng 
When running the SSD examples, I set the batch size only 1, 4 or 8.But the problem still exists.

**Comment by edwardzeng** [comment]
I don't meet this problem when running it. What's your graphics memory? Maybe your data is too big，it will lead to this problem.




On 04/12/2017 08:51, BensonBlack wrote:

@edwardzeng
When running the SSD examples, I set the batch size only 1, 4 or 8.But the problem still exists.

**Comment by BensonBlack** [comment]
@edwardzeng 

My code:
    # parse image list
    image_list = [i.strip() for i in args.images.split(',')] * 1000

image_list has 2*1000 images.
Does the image_list too big?

**Comment by edwardzeng** [comment]
Do you meet this problem in test period ？I have same problem in test period and can't fix it.




On 04/12/2017 13:53, BensonBlack wrote:

@edwardzeng

My code:
# parse image list
image_list = [i.strip() for i in args.images.split(',')] * 1000

image_list has 2*1000 images.
Does the image_list too big?

**Comment by BensonBlack** [comment]
@zhreshold , Can you fix it?

**Comment by zhreshold** [comment]
It's not memory leak, I used base_module.predict() API, which will keep all detection outputs copies in memory, that's why gpu memory is increasing. If you need to predict thousands of images, you can use iter_predict() function instead.
```
def detect(self, det_iter, show_timer=False):
        """
        detect all images in iterator

        Parameters:
        ----------
        det_iter : DetIter
            iterator for all testing images
        show_timer : Boolean
            whether to print out detection exec time

        Returns:
        ----------
        list of detection results
        """
        num_images = det_iter._size
        if not isinstance(det_iter, mx.io.PrefetchingIter):
            det_iter = mx.io.PrefetchingIter(det_iter)
        result = []
        for det in self.mod.iter_predict(det_iter):
            det = det[0][0][0].asnumpy()
            res = det[np.where(det[:, 0] >= 0)[0]]
            result.append(res)
        return result
```
Note that this is much slower than predict, because for each image, the result will be copied from gpu to cpu. It's up to you which one you'd like.

**Comment by BensonBlack** [comment]
@zhreshold .Thank you.

**Comment by mcxkarakoc** [comment]
.
