### ISSUE TITLE
Problem with installing mxnet on R v.3.3.3

### ISSUE THREAD

**Issue by mo-onstalker** [dmlc/mxnet#5796]
I have a Problem installing mxnet under the current R Version 3.3.3. 
The issue is probably similiar to [this](https://github.com/dmlc/mxnet/issues/2079). Can you help me on this topic?

## Environment info
Operating System:
Windows 10
R Studio

## Minimum reproducible example
> install.packages("drat", repos="https://cran.rstudio.com")
> drat:::addRepo("dmlc")
> install.packages("mxnet")

## Error Message:
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/src/contrib/PACKAGES.gz': HTTP status was '502 Proxy error (The IP of the web site cannot be found)'
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/src/contrib/PACKAGES': HTTP status was '502 Proxy error (The IP of the web site cannot be found)'
Warning in install.packages :
  unable to access index for repository https://dmlc.github.io/drat/src/contrib:
  cannot open URL 'https://dmlc.github.io/drat/src/contrib/PACKAGES'
Installing package into ‘C:/Users/xxx/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/src/contrib/PACKAGES.gz': HTTP status was '502 Proxy error (The IP of the web site cannot be found)'
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/src/contrib/PACKAGES': HTTP status was '502 Proxy error (The IP of the web site cannot be found)'
Warning in install.packages :
  unable to access index for repository https://dmlc.github.io/drat/src/contrib:
  cannot open URL 'https://dmlc.github.io/drat/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘mxnet’ is not available (for R version 3.3.3)
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.3/PACKAGES.gz': HTTP status was '502 Proxy error (The IP of the web site cannot be found)'
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.3/PACKAGES': HTTP status was '502 Proxy error (The IP of the web site cannot be found)'
Warning in install.packages :
  unable to access index for repository https://dmlc.github.io/drat/bin/windows/contrib/3.3:
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.3/PACKAGES'

**Comment by jeremiedb** [comment]
You seem to have taken the proper steps, so I don't know whether the issue is with drat or on your side.  
I keep an up to date compiled R Windows package if you want to try it: 
`install.packages("https://github.com/jeremiedb/mxnet_winbin/raw/master/mxnet.zip", repos = NULL)`

**Comment by thirdwing** [comment]
```
HTTP status was '502 Proxy error (The IP of the web site cannot be found)'
````

I guessed the problem might be on your side.

I just test the drat installation on a Windows machine. It works well.

**Comment by matt32106** [comment]
are you not behind a proxy? error msg may indeed be a hint:
`'502 Proxy error (The IP of the web site cannot be found)'`

**Comment by mo-onstalker** [comment]
Thanks for the fast help. I tried it on another Windows machine yesterday and it worked as well. Admin won't adjust the Proxy so i just can't use the package on this condition i guess.

Error message is indeed helpful, i just couldn't make use of IP not found information. But if the Proxy blocks the response that's just what you get.

**Comment by cmwetherell** [comment]
The URL from @jeremiedb worked well for me, whereas drat did not work. I am running Microsoft R Open 3.3.3. Thanks!

**Comment by jeremiedb** [comment]
drat is no longer in use and the pre-compiled libraries are now stored on S3. Below is the procedure, taken from the updated documentation: https://mxnet.incubator.apache.org/get_started/install.html . 

```
cran <- getOption("repos")
cran["dmlc"] <- "https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/"
options(repos = cran)
install.packages("mxnet")
```
