### ISSUE TITLE
How to set int8 or float16 to predict?

### ISSUE THREAD

**Issue by ysh329** [dmlc/mxnet#5822]
I downloaded pretrained model from model zoo. However, MXNet will load model as float32 format defaultly. I want to make inference as float16 or int8 format.

I think there're two ways to accomplish: 
1. transform float32 model into float16/int8  
2. compute as float16/int8 format on the whole prediction

Does MXNet have some example codes, which have accomplished one or two way(s) above?
Thanks a lot!

**Comment by Godricly** [comment]
you can use [cast](http://mxnet.io/api/python/symbol.html#mxnet.symbol.cast) to convert type.

**Comment by ysh329** [comment]
@Godricly 

It's strange when I tried function `cast`.

```Python
In [22]: mx.symbol.cast([0.9, 1.3], dtype='int32')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-ed75a717bc10> in <module>()
----> 1 mx.symbol.cast([0.9, 1.3], dtype='int32')

mxnet/cython/symbol.pyx in symbol._make_atomic_symbol_function.creator (mxnet/cython/symbol.cpp:3513)()

TypeError: Compose expect `Symbol` as arguments
```

**Comment by ysh329** [comment]
I knewn. Docs should be updated......

Thanks a lot!
