### ISSUE TITLE
Inconsistent versions of dmlc-core are used by mxnet and nnvm separately

### ISSUE THREAD

**Issue by weijianwen** [dmlc/mxnet#5828]
Both mxnet and nnvm require `dmlc-core` as a dependency. However two different versions, `dmlc-core@3dfbc62` for mxnet and `dmlc-core@3a51614` for nnvm are introduced introduce mxnet's soruce tree via submodules. According to commit comparing, differences between them are non trival. Could you check it?

https://github.com/dmlc/dmlc-core/compare/3a51614d39b69fdb5de1efcf1016426626d267a6...3dfbc62cc85dc718b0a0f326d82c9e20d70ab321

**Comment by piiswrong** [comment]
It doesn't matter. When compiling with mxnet nnvm will use mxnet/dmlc-core

**Comment by weijianwen** [comment]
@piiswrong Thank you for the explaination, Eric. But I think will be good if `mxnet` and `nnvm` use the same version of `dmlc-core` in development and integration for code consistency consideration.

I'm closing this issue and will reopen it if if I spot anything abnormal related.
