### ISSUE TITLE
how do I do to let the layer be a lost layer, in c++?

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#588]

**Comment by starimpact** [comment]
I don't know how to make a layer be a loss function.I know how to do with python, in which I can set ```__init__(False)```

**Comment by vchuravy** [comment]
Take a look at how the numpy layer works under the hood and search for `need_top_grad`

https://github.com/dmlc/mxnet/blob/master/src/operator/native_op-inl.h#L231-L242

**Comment by starimpact** [comment]
But I didn't see the similar way for regression_output-inl.h(I know it is the loss function layer.)
```python
  std::vector<int> DeclareBackwardDependency(
    const std::vector<int> &out_grad,
    const std::vector<int> &in_data,
    const std::vector<int> &out_data) const override {
    return {in_data[reg_enum::kLabel], out_data[reg_enum::kOut]};
  }
```

**Comment by vchuravy** [comment]
In both cases there is no backward dependency declared onto the out_gradient.

**Comment by starimpact** [comment]
oh , thank you , I will have a try. :smile:

**Comment by starimpact** [comment]
yes ,it is worked.
thank you very much.
