### ISSUE TITLE
what is CSR in "nnvm/graph.h"

### ISSUE THREAD

**Issue by kernel8liang** [dmlc/mxnet#5907]
```
// Node pointers in CSR structure.
std::vector<Node> nodes_;
// CSR pointer of node entries
std::vector<size_t> entry_rptr_;
```
what is CSR ?

**Comment by yuruofeifei** [comment]
This explains well: https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR.2C_CRS_or_Yale_format.29
Note: The CSR format saves on memory only when NNZ < (m (n − 1) − 1) / 2

**Comment by kernel8liang** [comment]
thanks.
