### ISSUE TITLE
How to save the final model in training mnist data using train_cifar10.py or train_mnist.py? 

### ISSUE THREAD

**Issue by ysh329** [dmlc/mxnet#5909]
I used `train_cifar10.py` and `mx.model.save_checkpoint` to save final model . 

# Problem

But I met the problem below: 

```Python
Traceback (most recent call last):
  File "train_cifar10.py", line 63, in <module>
    mx.model.save_checkpoint(prefix=prefix, epoch=num_epochs)
TypeError: save_checkpoint() takes exactly 5 arguments (2 given)
```

**Where can I find these two terms (`arg_params`, `aux_params`)?**, or how to get arg_params, aux_params variables after training?

# `save_checkpoint` docs

The docs about `save_checkpoint` is below:

### mxnet.model.save_checkpoint(prefix, epoch, symbol, arg_params, aux_params)
Checkpoint the model data into file.

Parameters:	
* prefix (str) – Prefix of model name.  
* epoch (int) – The epoch number of the model.  
* symbol (Symbol) – The input Symbol.  
* arg_params (dict of str to NDArray) – Model parameter, dict of name to NDArray of net’s weights.  
* aux_params (dict of str to NDArray) – Model parameter, dict of name to NDArray of net’s auxiliary states.  

Notes  
* prefix-symbol.json will be saved for symbol.  
* prefix-epoch.params will be saved for parameters.  

# My Code

My code is below: 

```Python
import os
import argparse
import logging
logging.basicConfig(level=logging.DEBUG)
from common import find_mxnet, data, fit
from common.util import download_file
import mxnet as mx

def download_cifar10():
    #data_dir="data"
    #fnames = (os.path.join(data_dir, "cifar10_train.rec"),
    #          os.path.join(data_dir, "cifar10_val.rec"))
    #download_file('http://data.mxnet.io/data/cifar10/cifar10_val.rec', fnames[1])
    #download_file('http://data.mxnet.io/data/cifar10/cifar10_train.rec', fnames[0])
    fnames = range(2)
    fnames[0] = '/home/yuens/Software/mxnet/mydata_val.rec'
    fnames[1] = '/home/yuens/Software/mxnet/mydata_train.rec'
    return fnames

if __name__ == '__main__':
    # download data
    (train_fname, val_fname) = download_cifar10()

    # parse args
    parser = argparse.ArgumentParser(description="train cifar10",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    fit.add_fit_args(parser)
    data.add_data_args(parser)
    data.add_data_aug_args(parser)
    data.set_data_aug_level(parser, 2)
    parser.set_defaults(
        # network
        network         = 'resnet',
        num_layers      = 110,
        # data
        data_train      = train_fname,
        data_val        = val_fname,
        num_classes     = 10,
        num_examples    = 50000,
        image_shape     = '3,55,55',#32
        pad_size        = 0,
        # train
        batch_size      = 1,#128,
        num_epochs      = 30,
        lr              = .05,
        lr_step_epochs  = '200,250',
    )
    args = parser.parse_args()

    # load network
    from importlib import import_module
    net = import_module('symbols.'+args.network)
    #net = import_module('symbols.'+)
    #import symbol_unet
    #net = symbol_unet.get_symbol()
    sym = net.get_symbol(**vars(args))

    # train
    #mx.sym.Variable(init=mx.init.Xavier)
    fit.fit(args, sym, data.get_rec_iter)
    prefix = "ssnet-dogcat-55"
    num_epochs = 25
    mx.model.save_checkpoint(prefix=prefix, epoch=num_epochs)
```

Besides, I tried function mxnet.model.FeedForward.save but met problem below:
```Python
Traceback (most recent call last):
  File "train_cifar10.py", line 64, in <module>
    mx.model.FeedForward.save(prefix=prefix, epoch=num_epochs)
TypeError: unbound method save() must be called with FeedForward instance as first argument (got nothing instead)
```

# Related Issues  
How to save the final model in training mnist data using train_mnist.py ? · Issue #5323 · dmlc/mxnet
https://github.com/dmlc/mxnet/issues/5323

**Comment by ysh329** [comment]
After executing `python train_cifar10.py -h`, I knew how to save model as below:
```shell
python train_cifar10.py --network ssnet --model-prefix ./ssnet-dogcat-55 
```

However, how can I write `save` or `save_checkpoint` function in the python code?

**Comment by jdhao** [comment]
@ysh329 , according to official documentation, the model FeedForward is deprecated, you should use module instead. see [here](http://mxnet.io/tutorials/python/module.html) for an example of how to use module to build the network and save the network paramter

**Comment by ysh329** [comment]
@jdhao Thanks a lot!

**Comment by jdhao** [comment]
@ysh329 , if my answer solves your problem. You should close this issue. Also I suggest that you may search google before opening an issue.

**Comment by ysh329** [comment]
@jdhao Okay, I forgot :laughing:
