### ISSUE TITLE
Soft thresholding aka L1 regularization

### ISSUE THREAD

**Issue by patwa67** [dmlc/mxnet#5911]
The Lasso can easily be implemented using a squared error (LinearRegression) loss and soft thresholding on the weights (i.e. setting weights between -t and t to zero in the backward pass). Is this possible to implement?

**Comment by moveforever** [comment]
yes, you can.
you can reference Ftrl(Optimizer)[https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py](url)

**Comment by patwa67** [comment]
The Ftrl optimizer doesn't work:
```
import mxnet as mx
import numpy as np

data = np.random.rand(500,3)
sumlab1 = (data[:,0]+data[:,1])
sumlab2 = sumlab1 + np.transpose(np.random.rand(500,1)*0.1)
label = np.transpose(sumlab2)

batch_size = 50
ntrain = int(data.shape[0]*0.8)
train_iter = mx.io.NDArrayIter(data[:ntrain, :], label[:ntrain], batch_size, shuffle=True,label_name='lin_reg_label')
eval_iter = mx.io.NDArrayIter(data[ntrain:, :], label[ntrain:], batch_size)

X = mx.sym.Variable('data')
Y = mx.symbol.Variable('lin_reg_label')
fully_connected_layer  = mx.sym.FullyConnected(data=X, name='fc1', num_hidden = 1)
lro = mx.sym.LinearRegressionOutput(data=fully_connected_layer, label=Y, name="lro")

model = mx.mod.Module(
    symbol = lro ,
    data_names=['data'],
    label_names = ['lin_reg_label']# network structure
)


model.fit(train_iter, eval_iter, optimizer='Ftrl',
            optimizer_params={'learning_rate':0.01},
            num_epoch=100)
```

AttributeError: type object 'NDArray' has no attribute 'abs'

**Comment by moveforever** [comment]
@patwa67 , I have fixed it in my project, and you can refer to https://github.com/moveforever/mxnet/commit/b822e95b4fa176a462221347dc40ab0c42a2058f

**Comment by patwa67** [comment]
How do I get that change into my MXNet installation?

**Comment by moveforever** [comment]
copy file python/mxnet/optimizer.py

**Comment by moveforever** [comment]
copy file python/mxnet/optimizer.py into `lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet`

**Comment by patwa67** [comment]
There is no change in:
https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py
Do you mean another file?

**Comment by patwa67** [comment]
I don't have:
site-packages/mxnet-0.9.5-py2.7.egg/mxnet/
Can I just create these or do I need to install something?

**Comment by patwa67** [comment]
OK, I just replaced in dist-packages/mxnet/
However, it was necessary change to:
```
from .ndarray import abs as ABS
```

**Comment by NamLQ** [comment]
Could someone implement Ftrl optimizer  in R?
