### ISSUE TITLE
my faster-rcnn can work on cpu, but not on gpu, why?

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#594]
HI,
anchor_regressioncost is for bound box regression in my faster-rcnn framework.
but it can only work on cpu, will fail on gpu.
but anchorclassifycost can work ok both on cpu and gpu.
Can you help me figure it out?
Please see my github.
```
https://github.com/starimpact/mxnet/blob/master/src/operator/anchor_regressioncost-inl.h
```

**Comment by sneakerkg** [comment]
Hi Ming,
I'm very interested in working together with you on Faster-rcnn. Please give me a few days to catch up with your current work.

**Comment by starimpact** [comment]
i must solve it today

**Comment by piiswrong** [comment]
What's the error message

**Comment by starimpact** [comment]
just quit, no error message

**Comment by starimpact** [comment]
another strange question is , in gpu mode, it will die quietly when i printf one value of in_data.

**Comment by starimpact** [comment]
@tqchen can you give me some tips?

**Comment by starimpact** [comment]
@tqchen can you give some hints?

**Comment by starimpact** [comment]
if there is a restriction in gpu mode that cannot access each value of a tensor directly?

**Comment by vchuravy** [comment]
You can't use printf in CUDA except if you add `-arch sm_20` or higher to NVCCFLAGS

http://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#formatted-output

**Comment by starimpact** [comment]
I think I found the problem: in gpu mode , mshadow does not support fetching single value of a Tensor.

**Comment by starimpact** [comment]
@vchuravy No, I still can do printf("hello world") in gpu mode.

**Comment by starimpact** [comment]
Sovled !!!    :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile: :smile:

**Comment by XericZephyr** [comment]
Congratulations man~ @starimpact

**Comment by gongenhao** [comment]
@starimpact will you share example or PR for the faster RCNN implementation?

**Comment by starimpact** [comment]
the code is complicated, not easy to be shared.
