### ISSUE TITLE
mxnet Installation error in R v3.4.0 win10 64bit

### ISSUE THREAD

**Issue by Mrugankakarte** [dmlc/mxnet#5948]
While installing mxnet package for R v3.4.0 win10 64bit, I'm getting following error. Please help.
I was using this steps:
`> install.packages("drat", repos="https://cran.rstudio.com")`
`> drat:::addRepo("dmlc")`
`> install.packages("mxnet")`

`Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'`
`Installing package into ‘C:/Users/Mrugank/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)`
`Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'`
`Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'`
`Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.4/PACKAGES.gz': HTTP status was '404 Not Found'`
`Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.4/PACKAGES': HTTP status was '404 Not Found'`
`Warning in install.packages :
  unable to access index for repository https://dmlc.github.io/drat/bin/windows/contrib/3.4:
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.4/PACKAGES'`
`Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘mxnet’`
  `These will not be installed`

**Comment by Mrugankakarte** [comment]
While installing mxnet package for R v3.4.0 win10 64bit, I'm getting following error. Please help.
I was using this steps:
`> install.packages("drat", repos="https://cran.rstudio.com")`
`> drat:::addRepo("dmlc")`
`> install.packages("mxnet")`


`Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'`

`Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/src/contrib/PACKAGES.rds': HTTP status was '404 Not Found'`

`Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  missing value where TRUE/FALSE needed`

`Error in install.packages : Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  missing value where TRUE/FALSE needed`

**Comment by RogerBorras** [comment]
I have the same error with the new R v.3.4.0 release!

**Comment by Mrugankakarte** [comment]
Well, maybe mxnet has not been updated for R v3.4.0

I also tried installing it by following instructions on [this website](http://mxnet.io/get_started/windows_setup.html) under the section 'Installing MXNet on a computer with GPU' but I couldn't find the '/nocudnn' folder anywhere.

**Comment by thirdwing** [comment]
@Mrugankakarte You are correct. I haven't upload the pkg from R 3.4.0.

Please wait for a while.

**Comment by jeremiedb** [comment]
If needed while DRAT is updated, you can install a recently compiled version for Windows (April 11) using: 
`install.packages("https://github.com/jeremiedb/mxnet_winbin/raw/master/mxnet.zip", repos = NULL)`

**Comment by RogerBorras** [comment]
Thanks @jeremiedb!

**Comment by Mrugankakarte** [comment]
@thirdwing @jeremiedb  Thanks!!

**Comment by thirdwing** [comment]
I have upload the mxnet for R 3.4 on Windows 64. Please check it.

**Comment by Mrugankakarte** [comment]
Thanks!! It's working.
