### ISSUE TITLE
[DOC] KVStore

### ISSUE THREAD

**Issue by eric-haibin-lin** [dmlc/mxnet#5949]
Currently kvstore api doc only shows one of the many options to create kvstore. http://mxnet.io/api/python/kvstore.html?highlight=kvstore#mxnet.kvstore.create

Actually there are many more, and detailed description at this page: http://mxnet.io/architecture/overview.html?highlight=local_allreduce_cpu#multiple-devices-on-a-single-computer
Would be great if these options appear in kvstore doc, or at least have a link for reference

**Comment by starimpact** [comment]
thank you! I am looking for it!

**Comment by eric-haibin-lin** [comment]
Do you mind contributing with a PR to make this documentation more
elaborative? It will be helpful for others, too
