### ISSUE TITLE
Should parameter server have GPU installed

### ISSUE THREAD

**Issue by juilin** [dmlc/mxnet#5953]
Hi,

I am planning distributed training by using MXNet. Do I need to allocate a GPU machine for parameter server? Is MXNet parameter server CPU-based or GPU-based?

Thanks,
Juilin

**Comment by eric-haibin-lin** [comment]
GPU is not required. You can do dist training with CPU. The framework supports both 

On 2017年4月23日, at 22:09, juilin <notifications@github.com> wrote:

Hi,

I am planning distributed training by using MXNet. Do I need to allocate a GPU machine for parameter server? Is MXNet parameter server CPU-based or GPU-based?

Thanks,
Juilin

**Comment by juilin** [comment]
@eric-haibin-lin, 

Thanks for the answer. Do I need to do anything to enable GPU support in parameter?

Regards,
Rui-Lin

**Comment by eric-haibin-lin** [comment]
You can check http://mxnet.io/how_to/multi_devices.html for a overview of distributed training
