### ISSUE TITLE
Profiler: all operators are collapsed as a single unit in the profiler

### ISSUE THREAD

**Issue by bikestra** [dmlc/mxnet#5959]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

Compiler:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Package used (Python/R/Scala/Julia):Python 3.4.3

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): e4338628641ea8d7db0b6dd249428262aafe98b2

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Problem:

In the json file produced from profiler, all operators are collapsed as a single unit as below, making it impossible for me to break down the computation. Also, the name of the entry seems truncated, as it starts with '[' but not closed with ']'. This did not happen in commit 8861ccc032fa64f4a13b84fb82f6edb4febef2be which I had been using. 

```
        {
            "name": "[Embedding,Concat,Reshape,Slice",
            "cat": "category",
            "ph": "E",
            "ts": 55657562,
            "pid": 0,
            "tid": 447691082
        },
```
Is this grouping of operators intended? If so, is there a way for me to control the level of grouping?

**Comment by eric-haibin-lin** [comment]
This is due to the bulk execution in MXNet to reduce gaps between kernel launches. You can set 
MXNET_EXEC_BULK_EXEC_TRAIN = 0 
MXNET_EXEC_BULK_EXEC_INFERENCE = 0 
to disable it and see the time taken by individual op.

**Comment by eric-haibin-lin** [comment]
@ZihengJiang do you mind checking why the name is/looks like truncated?

**Comment by ZihengJiang** [comment]
@eric-haibin-lin I think it is due to the maximum length of opr_name is 32, https://github.com/dmlc/mxnet/blob/master/src/engine/profiler.h#L22

**Comment by padentomasello** [comment]
Hi there, 

My profiles are still grouping operators after recompiling mxnet with `MXNET_EXEC_BULK_EXEC_TRAIN = 0` and `MXNET_EXEC_BULK_EXEC_INFERENCE = 0`. 

## Environment Info
Operating System:
Distributor ID: Ubuntu
Description: Ubuntu 16.04.2 LTS


Compiler:
gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Package used (Python/R/Scala/Julia):Python 3.6

MXNet Version: `3d4d845`

**Comment by bikestra** [comment]
Hi @padentomasello , these are environment variables, not config variables for compilation. You don't have to recompile.
