### ISSUE TITLE
Load caffe without caffe dependency?

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#597]
Just like https://github.com/szagoruyko/loadcaffe in torch7, there is no need to install caffe. Can mxnet do this? Currently, I just find caffe converter in mxnet, but need caffe installed.

**Comment by piiswrong** [comment]
I took a look at this:
https://github.com/szagoruyko/torch-caffe-binding
https://github.com/szagoruyko/loadcaffe
They looks like good reference. Maybe people working on caffe bindings can use this.
@jermainewang

**Comment by sxjscience** [comment]
I think it can be done by compile the official caffe protobuf `caffe.proto` to get the `caffe_pb2.py` file, which can do the parsing. https://github.com/kitofans/caffe-theano-conversion is also a good reference.

**Comment by tqchen** [comment]
closed by #620
