### ISSUE TITLE
how to build im2rec from im2rec.cc on a Windows machine?

### ISSUE THREAD

**Issue by Bumblebee1964** [dmlc/mxnet#5976]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Windows 10, x64

Compiler: VS2015

Package used (Python/R/Scala/Julia): c-api

MXNet version:

Or if installed from source: 0.9.4

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
I have created a console solution using im2rec.cc and linking it with libmxnet.lib. However the symbols used in im2rec.cc are not exported by libmxnet.lib, producing linker errors. Has anyone being able to build im2rec on Windows and how should it be done? Possible to share the project file?

1 of the 14 unresolved externals:
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: static class dmlc::InputSplit * __cdecl dmlc::InputSplit::Create(char const *,unsigned int,unsigned int,char const *)" (?Create@InputSplit@dmlc@@SAPEAV12@PEBDII0@Z) referenced in function main	Bin2Rec	C:\Projects\MXNet\Examples\Bin2Rec\Bin2Rec\im2rec.obj	1	

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by kice** [comment]
You need to build mxnet your self and create a new vc project and reference the mxnet solution.

**Comment by Bumblebee1964** [comment]
This worked out, thanks:)
