### ISSUE TITLE
Deduplicate the Inception network definitions

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#598]
There are [multiple Inception definitions](https://github.com/dmlc/mxnet/search?l=python&q=factory&type=Code&utf8=%E2%9C%93) scattered around some of which may be incorrect as suggested by @antinucleon in https://github.com/soumith/convnet-benchmarks/issues/68#issuecomment-156734520. It would be easier to maintain a single authoritative version.

**Comment by jermainewang** [comment]
Hi, thanks for your advice! This will indeed help a lot to avoid bugs in copy/paste codes. Would you like to offer a hand on this? :)

Minjie

**Comment by futurely** [comment]
The latest https://github.com/dmlc/mxnet/pull/624 can serve as the orthogonal network definitions.

**Comment by tqchen** [comment]
closing for now, as #624
