### ISSUE TITLE
error exists when build mxnet with USE_DIST_KVSTORE = 1

### ISSUE THREAD

**Issue by dushoufu** [dmlc/mxnet#599]
when i modified the config.mk and let USE_DIST_KVSTORE = 1,then build and I get the error
src/kvstore/./kvstore_dist.h:12:19: fatal error: ps/ps.h: No such file or directory
I guess there is a ps.h located in the directory /ps-lite/src/ps.h, but no ps/ps.h. 
If I mkdir the ps/ps.h, then will bring more errors,possibly because of dependencies error.

who can give me some help with this?

**Comment by shuokay** [comment]
You should clone mxnet with ```git clone --recursive https://github.com/dmlc/mxnet```, if not, submodules cant be fetched.

**Comment by hjk41** [comment]
You can also do "git submodule update" to get the submodules after you have
done "git clone"

On Tue, Nov 17, 2015 at 5:07 PM, shuokay <notifications@github.com> wrote:

> You should clone mxnet with git clone --recursive
> https://github.com/dmlc/mxnet, if not, submodules cant be fetched.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/599#issuecomment-157313983>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by mli** [comment]
please also run `git pull`, it seems that your clone of mxnet is a little bit old

**Comment by dushoufu** [comment]
Thank everybody. My problem is OK. I'm a starter of GIT.

**Comment by mli** [comment]
great, i'll close this issue now, please feel free to reopen it if your issue is still there
