### ISSUE TITLE
python doc error in KVstore example

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#601]
in the KVstore example:
```python
>>> def update(key, input, stored):
>>>     print "update on key: %d" % key
>>>     stored += input * 2
>>> kv.set_updater(update)
```
where `kv.set_updater` should be
`kv._set_updater(update)`

**Comment by mli** [comment]
yeah, we try to replace it by `set_optimizer`, which is probably more straightforward for optimization algorothms.  can you please push a PR to fix the example. thanks
