### ISSUE TITLE
cifar-100.ipynb error

### ISSUE THREAD

**Issue by catmonkeylee** [dmlc/mxnet#602]
model.fit(X=train_dataiter,
          eval_data=test_dataiter,
          eval_metric="accuracy",
          batch_end_callback=mx.callback.Speedometer(batch_size, 200),
          epoch_end_callback=mx.callback.do_checkpoint(model_prefix))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-80656f7a97d1> in <module>()
      3           eval_metric="accuracy",
      4           batch_end_callback=mx.callback.Speedometer(batch_size, 200),
----> 5           epoch_end_callback=mx.callback.do_checkpoint(model_prefix))

/home/test/project/mxnet/python/mxnet/model.pyc in fit(self, X, y, eval_data, eval_metric, epoch_end_callback, batch_end_callback, kvstore, logger)
    709             optimizer = opt.create(self.optimizer,
    710                                    rescale_grad=(1.0/batch_size),
--> 711                                    **(self.kwargs))
    712         elif isinstance(self.optimizer, opt.Optimizer):
    713             optimizer = self.optimizer

/home/test/project/mxnet/python/mxnet/optimizer.pyc in create_optimizer(name, rescale_grad, **kwargs)
     45             return Optimizer.opt_registry[name.lower()](
     46                 rescale_grad=rescale_grad,
---> 47                 **kwargs)
     48         else:
     49             raise ValueError('Cannot find optimizer %s' % name)

TypeError: __init__() got an unexpected keyword argument 'num_round'

**Comment by mli** [comment]
we changed `num_round` into `num_epoch`, can you please push a PR to fix it? thanks

**Comment by antinucleon** [comment]
Updated
