### ISSUE TITLE
Sum Operator

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#603]

**Comment by starimpact** [comment]
I know there is a sumall_except_dim, but it can not do it .

**Comment by tqchen** [comment]
This can be supported by adding blas api asum to mshadow. Like the vector dot https://github.com/dmlc/mshadow/blob/master/mshadow/tensor_cpu-inl.h#L337

**Comment by lukemetz** [comment]
Does mshadow/mxnet support this? I too was trying to write a sum op but ran into issues constructing scalars(tensors with zero shape). In addition it looks like ndarray doesn't support at-least construction of scalars. Is the workaround just leave it in shape (1,)?

**Comment by tqchen** [comment]
Yes, currently we construct it using shape ``` (1,)```

**Comment by tqchen** [comment]
c.f.  norm https://github.com/dmlc/mxnet/blob/master/src/ndarray/unary_function-inl.h#L82

**Comment by yajiedesign** [comment]
@tqchen this ops is add? https://github.com/dmlc/mxnet/blob/master/src/ndarray/unary_function-inl.h#L176

**Comment by tqchen** [comment]
seems was added @piiswrong did you add this?

**Comment by piiswrong** [comment]
yes min/max/sum
