### ISSUE TITLE
can't build with CUDA on macOS 10.12.4

### ISSUE THREAD

**Issue by boofhead** [dmlc/mxnet#6032]
I'm having trouble building mxnet shared library from source with Cuda and Cudnn. I can compile and run the CUDA samples so nvcc seems to be working ok. building with attached config.mk and `make
 -j`

## Environment info
Operating System:
macOS 10.12.4

Compiler:
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode_8.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:46_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

MXNet commit hash (`git rev-parse HEAD`):
703e8eeb117109ea345639610780e30775056412

## Error Message:
cd /Users/robin/mxnet/dmlc-core; /Applications/Xcode_8.2.1.app/Contents/Developer/usr/bin/make libdmlc.a USE_SSE=1 config=/Users/robin/mxnet/config.mk; cd /Users/robin/mxnet
cd /Users/robin/mxnet/nnvm; /Applications/Xcode_8.2.1.app/Contents/Developer/usr/bin/make lib/libnnvm.a DMLC_CORE_PATH=/Users/robin/mxnet/dmlc-core; cd /Users/robin/mxnet
make[1]: `libdmlc.a' is up to date.
make[1]: `lib/libnnvm.a' is up to date.
/usr/local/cuda/bin/nvcc -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_50,code=compute_50 -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -I/Users/robin/mxnet/mshadow/ -I/Users/robin/mxnet/dmlc-core/include -fPIC -I/Users/robin/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include -DMSHADOW_USE_CUDNN=1  -I/Users/robin/mxnet/cub -DMXNET_USE_NVRTC=1" -M -MT build/src/operator/contrib/quantize_gpu.o src/operator/contrib/quantize.cu >build/src/operator/contrib/quantize_gpu.d
/usr/local/cuda/bin/nvcc -c -o build/src/operator/contrib/quantize_gpu.o -std=c++11 -Xcompiler -D_FORCE_INLINES -g -O3 -ccbin g++  -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_50,code=compute_50 -Xcompiler "-DMSHADOW_FORCE_STREAM -Wall -Wsign-compare -O3 -I/Users/robin/mxnet/mshadow/ -I/Users/robin/mxnet/dmlc-core/include -fPIC -I/Users/robin/mxnet/nnvm/include -Iinclude -funroll-loops -Wno-unused-variable -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.2/include/opencv -I/usr/local/Cellar/opencv/2.4.13.2/include -DMSHADOW_USE_CUDNN=1  -I/Users/robin/mxnet/cub -DMXNET_USE_NVRTC=1" src/operator/contrib/quantize.cu
In file included from tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:1:
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:21:31: error: typedef redefinition with different types
      ('mshadow::half::half_t' vs '_ZN7mshadow4half6half_tE')
typedef mshadow::half::half_t _ZN7mshadow4half6half_tE;
                              ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: previous definition is here
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:117:1150: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...(cudaSetupArgument((void *)(char *)&__par6, sizeof(__par6), (size_t)48UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)5...
                                                                                                                                                                     ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:117:1260: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...*)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)56UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par8)), sizeof(__par8), (size_t)58UL) != cudaSuc...
                                                                                                                                                      ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:122:1150: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...(cudaSetupArgument((void *)(char *)&__par6, sizeof(__par6), (size_t)48UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)5...
                                                                                                                                                                     ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:122:1260: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...*)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)56UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par8)), sizeof(__par8), (size_t)58UL) != cudaSuc...
                                                                                                                                                      ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:127:1169: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...(cudaSetupArgument((void *)(char *)&__par6, sizeof(__par6), (size_t)48UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)5...
                                                                                                                                                                     ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:127:1279: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...*)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)56UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par8)), sizeof(__par8), (size_t)58UL) != cudaSuc...
                                                                                                                                                      ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:132:1151: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...(cudaSetupArgument((void *)(char *)&__par6, sizeof(__par6), (size_t)48UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)5...
                                                                                                                                                                     ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:132:1261: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...*)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)56UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par8)), sizeof(__par8), (size_t)58UL) != cudaSuc...
                                                                                                                                                      ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:137:1151: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...(cudaSetupArgument((void *)(char *)&__par6, sizeof(__par6), (size_t)48UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)5...
                                                                                                                                                                     ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:137:1261: error: invalid application of 'sizeof' to an incomplete type
      '_ZNSt3__114numeric_limitsIN7mshadow4half6half_tEE4typeE' (aka '_ZN7mshadow4half6half_tE')
  ...*)(__cudaAddressOf(__par7)), sizeof(__par7), (size_t)56UL) != cudaSuccess) return;if (cudaSetupArgument((void *)(__cudaAddressOf(__par8)), sizeof(__par8), (size_t)58UL) != cudaSuc...
                                                                                                                                                      ^~~~~~~~
/var/folders/g8/n9zkdg4d6xvb2jwc_0mv88wr0000gn/T/tmpxft_00001a5c_00000000-4_quantize.compute_50.cudafe1.stub.c:19:16: note: forward declaration of '_ZN7mshadow4half6half_tE'
typedef struct _ZN7mshadow4half6half_tE _ZNSt3__123__libcpp_numeric_limitsIN7mshadow4half6half_tELb0EE4typeE;
               ^
/usr/local/cuda/include/thrust/system/cuda/detail/bulk/malloc.hpp:110:7: warning: private field 'm_program_break' is not used [-Wunused-private-field]
void *m_program_break;
      ^
/usr/local/cuda/include/thrust/system/cuda/detail/bulk/malloc.hpp:113:8: warning: private field 'm_max_data_segment_size' is not used [-Wunused-private-field]
size_t m_max_data_segment_size;
       ^
/usr/local/cuda/include/thrust/system/cuda/detail/bulk/malloc.hpp:242:15: warning: private field 'm_is_free' is not used [-Wunused-private-field]
private: bool m_is_free:1;
              ^
/usr/local/cuda/include/thrust/system/cuda/detail/bulk/malloc.hpp:243:8: warning: private field 'm_size' is not used [-Wunused-private-field]
size_t m_size:((8) * sizeof(size_t)) - (1);
       ^
/usr/local/cuda/include/thrust/system/cuda/detail/bulk/malloc.hpp:244:8: warning: private field 'm_prev' is not used [-Wunused-private-field]
block *m_prev;
       ^
/usr/local/cuda/include/thrust/system/cuda/detail/bulk/malloc.hpp:445:19: warning: private field 'm_in_use' is not used [-Wunused-private-field]
private: unsigned m_in_use;
                  ^
6 warnings and 11 errors generated.
make: *** [build/src/operator/contrib/quantize_gpu.o] Error 1

[config.mk.txt](https://github.com/dmlc/mxnet/files/965960/config.mk.txt)

**Comment by piiswrong** [comment]
@ZihengJiang looks like its related to quantize op

**Comment by ZihengJiang** [comment]
should be fixed by https://github.com/dmlc/mxnet/pull/6131. Also, I suggest adding this build combination into CI

**Comment by boofhead** [comment]
thanks
