### ISSUE TITLE
How to install and use tensorboard in MXNet?

### ISSUE THREAD

**Issue by ysh329** [dmlc/mxnet#6038]
I found there's a tutorial about [Understanding the vanishing gradient problem through visualization — mxnet 0.9.3 documentation](http://mxnet.io/tutorials/python/understanding_vanish_gradient.html), which used tensorboard to visualize result change.

However, how can I enable this magic tensorboard? Install TensorFlow first? and then? Thanks a lot!
![TB](https://raw.githubusercontent.com/zihaolucky/tensorboard/data/docs/tutorial/mnist/pic1.png)

**Comment by piiswrong** [comment]
see dmlc/tensorboard repo

**Comment by ysh329** [comment]
@piiswrong Thanks a lot!

**Comment by zihaolucky** [comment]
@ysh329 You can `pip install tensorboard` under a same env of your MXNet.

**Comment by ysh329** [comment]
@zihaolucky Yes, I'm installing :laughing:

**Comment by zihaolucky** [comment]
And we have a callback for you. https://github.com/dmlc/mxnet/blob/master/python/mxnet/contrib/tensorboard.py

**Comment by ysh329** [comment]
@zihaolucky Thanks a great lot! :sweat_smile:
