### ISSUE TITLE
AttributeError: module 'mxnet' has no attribute 'rnn

### ISSUE THREAD

**Issue by lilhope** [dmlc/mxnet#6067]
I install mxnet with this command`pip install mxnet-cu80`,when I use the rnn API,I get an error`AttributeError: module 'mxnet' has no attribute 'rnn'`, but I notice that in the source code `mx.rnn` is still here.

**Comment by lilhope** [comment]
I use python3 and anaconda

**Comment by lilhope** [comment]
I copy the source code `/mxnet/python/mxnet/rnn` to `/anaconda3/lib/python3/site-packages/mxnet` and do`import mxnet.rnn` then it works.

**Comment by szha** [comment]
The 0.9.3 release didn't have rnn api. You can try ```pip install -U mxnet-cu80``` now as the 0.9.5 version is now available.

**Comment by lilhope** [comment]
@szha ,It doesn't work,this is the message:
```
lilhope@lilhope-desktop:~$ pip install -U mxnet-cu80
Collecting mxnet-cu80
  Using cached mxnet_cu80-0.9.3a3-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy (from mxnet-cu80)
  Downloading numpy-1.12.1-cp36-cp36m-manylinux1_x86_64.whl (16.8MB)
    100% |████████████████████████████████| 16.8MB 103kB/s 
Installing collected packages: numpy, mxnet-cu80
  Found existing installation: numpy 1.11.3
    Uninstalling numpy-1.11.3:
      Successfully uninstalled numpy-1.11.3
Successfully installed mxnet-cu80-0.9.3a3 numpy-1.12.1
```

**Comment by szha** [comment]
@lilhope sorry my bad. I'm working on resolving this and will keep you posted.

**Comment by szha** [comment]
@lilhope now try again

**Comment by szha** [comment]
0.9.5 pip packages have been released for a while and should have resolved this problem.
