### ISSUE TITLE
[RNN] What is exactly NLL metric?

### ISSUE THREAD

**Issue by XericZephyr** [dmlc/mxnet#614]
The code is at https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py#L181 .

```python
def calc_nll(seq_label_probs, X, begin):
    
    nll = 0.
    for seqidx in range(len(seq_label_probs)):
        next_idx = (begin + seqidx + 1) % X.shape[0]
        y = X[next_idx, :]
        py = seq_label_probs[seqidx].asnumpy()
        nll += -np.sum(np.log(py)) / len(y)
    return nll
```

I have several questions.  

* I have problems in finding reference to the metric `nll`? What is the definition of NLL? What's the meaning of it? 
* Is `len(y)` always equal to `batch_size` ? If so, why do we need so complicated function?

**Comment by winstywang** [comment]
nll means negative log likelihood.
@antinucleon Could you confirm the second question?

**Comment by tqchen** [comment]
````len(y)``` indeed equals batch_size. Would be great if you can suggest a simpler version

**Comment by tqchen** [comment]
closing for now, but please open a PR or new issue if you have a new proposal
