### ISSUE TITLE
neighbor layer unequal grad problem

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#615]
example: ```layer1->layer2```
then, out_grad of layer1 should equal to in_grad of layer2, right?
but not here, why?

**Comment by tqchen** [comment]
This question is a bit without context.

This should in general be true, unless layer1 is also connected to other layer, and the gradient will be summed up.  If it was not the case on your side, maybe consider post an minimum example to reproduce the problem

**Comment by starimpact** [comment]
layer1 has pre layer, and only one post layer.
for example:
I set the values of in_grad of layer2 all 1s. and then the out_grad of layer1 only have several 1s, others are 0s.
this is really strange.
BTW, layer2 is the loss layer.

**Comment by starimpact** [comment]
BTW2, layer2 has serveral label parameters, not only one.

**Comment by tqchen** [comment]
Yes, this is strange if it is what you described, it could be  memory overflow problem that faied to assign some of in_grad. 

Or you forget to declare dependency to out_grad, in such case the out_grad will simply be invalid in backward

**Comment by starimpact** [comment]
actually, the layer1 is cov layer, and the layer2 is my self-defined loss layer. and the loss layer do not deed to backdepend to the out_grad.

**Comment by starimpact** [comment]
actually, the layer1 is cov layer, and the layer2 is my self-defined loss layer. and the loss layer do not need to backdepend of the out_grad.

**Comment by starimpact** [comment]
maybe it is he memory overflow problem of in_grad of layer2.
but I print the values of in_grad after I set its value. and it is normal.

**Comment by starimpact** [comment]
the following is my loss layer's infershape, should be no problem:
```python
  bool InferShape(std::vector<TShape> *in_shape,
                  std::vector<TShape> *out_shape,
                  std::vector<TShape> *aux_shape) const override {
    using namespace mshadow;
    CHECK_EQ(in_shape->size(), 5);

    TShape &datashape = (*in_shape)[anchor_regcost_enum::kData];
    TShape &labelshape = (*in_shape)[anchor_regcost_enum::kLabel];
    TShape &coordshape = (*in_shape)[anchor_regcost_enum::kCoordLabel];
    TShape &bbshape = (*in_shape)[anchor_regcost_enum::kBBsLabel];
    TShape &infoshape = (*in_shape)[anchor_regcost_enum::kAnchorInfoLabel];

    labelshape = Shape4(datashape[0], param_.anchornum, datashape[2], datashape[3]);
    coordshape = Shape4(datashape[0], 2, datashape[2], datashape[3]);
    bbshape = Shape4(datashape[0], 4, datashape[2], datashape[3]);
    infoshape = Shape4(param_.anchornum, 2, datashape[2], datashape[3]);

    out_shape->clear();
    out_shape->push_back(datashape);

    return true;
  }
```

**Comment by starimpact** [comment]
my loss layer2:
```cpp
    tdata_in = 1.0f;
    tlabel = 2.0f;
    tcoordlabel = 3.0f;
    tbbslabel = 4.0f;
    tinfolabel = 5.0f;
    tgrad_in = 6.0f;
```
the out_grad of layer1 is all 6.0s.
but when do:
```cpp
//    tdata_in = 1.0f;
//    tlabel = 2.0f;
//    tcoordlabel = 3.0f;
//    tbbslabel = 4.0f;
//    tinfolabel = 5.0f;
    tgrad_in = 6.0f;
```
the out_grad of layer1 is sparse 6.0s, others are 0s.

really, really strange....................

**Comment by starimpact** [comment]
I found the in_grad value is affected by in_data.

**Comment by starimpact** [comment]
in_data is just like a mask of in_grad.

**Comment by tqchen** [comment]
check the inplace option, if you set that, but the operation you performed cannot be done in inplace manner

**Comment by starimpact** [comment]
I have no inplace functions.

**Comment by starimpact** [comment]
zero values of in_data should has no correspond values of in_grad. maybe its the reason.

**Comment by tqchen** [comment]
I have little evidence on what happened on your side then. Maybe you can do some unit tests on the operators to see if the behavior is correct.

**Comment by starimpact** [comment]
does mshadow or mxnet process the following automatically?
```zero values of in_data should has no correspond values of in_grad```

**Comment by tqchen** [comment]
I don't understand your question

**Comment by starimpact** [comment]
i am confused a little also....

**Comment by starimpact** [comment]
for example:
```cpp
tdata_in = 0.0f;
tgrad_in = 6.0f;
```
will cause pre layer1's values be all 0s.
but
```
```cpp
tdata_in = 1.0f;
tgrad_in = 6.0f;
```
will cause pre layer1's values be all 6s. this is what I want.

**Comment by tqchen** [comment]
I see what you mean, you cannot assume mutating the input of in_data will change the state of previous layer. Each operator should act in an independent way, by only mutating the outputs(out_data in forward and in_grad in backward).

Otherwise the behavior is undefined. Because the memory allocation algorithm will take advantage of such restriction and re-uses some of the memory

**Comment by starimpact** [comment]
how do you explain this situation?
the tdata_in really acts like a mask of tgrad_in of this layer and out_grad of pre-layer.

**Comment by starimpact** [comment]
this is unreasonable.

**Comment by tqchen** [comment]
The restriction is you can only change in_grad in backward and out_data in forward, the operator will need to obey this restriction. Because the gradient is all the previous operator need to backprop the gradient to input(maybe together with some context like in_data, out_data)

**Comment by starimpact** [comment]
my second proof:
```cpp
    tdata_in = 0.0f;
    tdata_in[0][0][0][0] = 1.f;
    tgrad_in = 6.0f;
```
then in the out_grad of pre-layer, only the first value of it is 6, others are 0s.

**Comment by starimpact** [comment]
I don't think the in_data has any relationship with in_grad also, but the experiment data shows not.

**Comment by starimpact** [comment]
backwarddependency:
```cpp
  std::vector<int> DeclareBackwardDependency(
    const std::vector<int> &out_grad,
    const std::vector<int> &in_data,
    const std::vector<int> &out_data) const override {
    return {//out_data[anchor_regcost_enum::kOut],
            in_data[anchor_regcost_enum::kData],
            in_data[anchor_regcost_enum::kLabel],
            in_data[anchor_regcost_enum::kCoordLabel],
            in_data[anchor_regcost_enum::kBBsLabel],
            in_data[anchor_regcost_enum::kAnchorInfoLabel],
            };
  };
```

**Comment by tqchen** [comment]
You cannot change content of in_data in Backward Function.

**Comment by starimpact** [comment]
just experiment, I want know what's wrong between the in_grad and out_grad.

**Comment by starimpact** [comment]
I will do more experiments to find the reason.
Do you have any other better suggestion?

**Comment by tqchen** [comment]
Good luck on finding the cause. But please do not assume you can change content of in_data in backward

**Comment by starimpact** [comment]
OK, I will not do it.

**Comment by starimpact** [comment]
Solved , It's my problem.:smile:
