### ISSUE TITLE
Problem R-package install on Windows 10 : NAMESPACE file is missing

### ISSUE THREAD

**Issue by ChrisBotella** [dmlc/mxnet#6159]
Hello,

As I am not expert in R package installing, I have been struggling a lot with the installation of mxnet R-package for Windows. 

Short version, I think I have done the first steps, by following the indications given in the official tutorial and in answers to other issues, especially #1085. But the final command `R CMD INSTALL --no-multiarch R-package` outputs an error saying a `NAMESPACE` file is required but there is no such file in `.../mxnet/R-package/` and I don't know where i am suppose to find this file. And if it is because I have done something wrong in the previous steps, I have really no idea what to change.  Please, I need some help or advices =/

## Environment info
*Operating System: Windows 10
*Package used : R
*R informations : 
-R version 3.3.2 (2016-10-31)
-Platform: x86_64-w64-mingw32/x64 (64-bit)
-Running under: Windows >= 8 x64 (build 9200)
-locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                   LC_TIME=French_France.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] tools_3.3.2

## How I tried to install : 
I followed globaly the installing procedure given at [](http://mxnet.io/get_started/windows_setup.html) but not with the versions mentioned in this tutorial, they don't seem to be up to date if I believe what i found in the similar forum issues. Correct me if I misunderstood... 

*I first download and install 
- Visual studio Community 2015 with update 3  at [](https://my.visualstudio.com/downloads?wt.mc_id=o~msft~vscom~older-downloads&campaign=o~msft~vscom~older-downloads)
- cudaToolKit v8.0  (associated with  cudNN v5.1) 

* Download the .zip of **mxnet github repository** [](https://github.com/dmlc/mxnet/) and unzip it in a `../mxnet/` folder. 

* Download the **cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0 for Windows 10** .zip file found at [](https://developer.nvidia.com/rdp/cudnn-download)  .  I chose this version following the instructions of the last `mxnet` windows package release, it condition the choice of cudaToolKit v8.0.  

* I unzip it in a `.../cudnn` folder, so in `cudnn/cuda/` I have 3 folders : `bin/`, `lib/` and `include/`.  * Download **20160531_win10_x64_gpu.7z**  and **20170505_mxnet_x64_vc14_gpu.7z** of  the build windows update 20170505 found at [](https://github.com/yajiedesign/mxnet/releases).
- Unzip the first in a folder `.../20160531_win10_x64_gpu/`
- Unzip the second in a folder `.../20170505_mxnet_x64_vc14_gpu`
- I copy the contain of previous folder `.../cudnn/cuda/`  (3 folders `bin/`, `lib/` and `include/`) and paste it into `.../20160531_win10_x64_gpu/3rdparty/cudnn/`.

* Now in the folder `../mxnet/R-package/` I create `inst/libs/x64/` and fill it with the .dll files found in  those folders
-.../20160531_win10_x64_gpu/3rdparty/cudart
-.../20160531_win10_x64_gpu/3rdparty/cudnn/bin (cudnn64_5.dll)
-.../20160531_win10_x64_gpu/3rdparty/openblas/bin
-.../20160531_win10_x64_gpu/3rdparty/vc
-.../20160531_win10_x64_gpu/3rdparty/lib
-.../20170505_mxnet_x64_vc14_gpu/build/   , which contain only `libmxnet.dll`
=> I have now 12 .dll files in `libs/x64/`.

* I create folder `include/` into `.../mxnet/R-package/inst/` and copy the 3 folders from `.../20170505_mxnet_x64_vc14_gpu/include/` .

* Open the Windows terminal as admin, I go into the folder `.../mxnet/` and execute the command line `R CMD INSTALL --no-multiarch R-package`. Immediatly, I get the following error message : 

## Error Message:
* installing to library 'C:/Users/Christophe/Documents/R/win-library/3.3' 
* installing *source* package 'mxnet' ...
ERROR: a 'NAMESPACE' file is required
* removing 'C:/Users/Christophe/Documents/R/win-library/3.3/mxnet'
* restoring previous 'C:/Users/Christophe/Documents/R/win-library/3.3/mxnet'

**Comment by Mrugankakarte** [comment]
Hi,
I had the same issue. I found this new guide, check it out. I haven't tried it yet but I guess it should work.

[Link](https://gist.github.com/flammit/24a5e8b29c63f7fd5c9900176ad04062)

**Comment by thirdwing** [comment]
I am sorry that I don't have a Windows machine with GPU.

A two-round installation is required for R installation. We need to generate NAMESPACE in the first round.

Please see https://github.com/dmlc/mxnet/blob/master/Makefile#L324-L331

**Comment by ChrisBotella** [comment]
@thirdwing , Thank you for your answer, supposing my previous actions where ok, I tried the commands you indicated. So what I did : 
* cd to the folder` .../mxnet/` and type the following commands
* `echo "import(Rcpp)" > R-package/NAMESPACE` -> Ok, I get the NAMESPACE file in `.../mxnet/R-package/`
* `echo "import(methods)" >> R-package/NAMESPACE` -> still ok
* `R CMD INSTALL R-package`   
##First Error 
installing to library 'C:/Users/Christophe/Documents/R/win-library/3.3'
installing *source* package 'mxnet' ...
** libs
*** arch - i386
Warning: l'exécution de la commande 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mxnet.dll" OBJECTS="executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o"' renvoie un statut 127
ERROR: compilation failed for package 'mxnet'

I go on so may be you can understand what is going on...

* `Rscript -e "require(mxnet); mxnet:::mxnet.export(\"R-package\")"`  => This produces no error and finally says "All generation finished on R-package..." 
* `Rscript -e "require(devtools); install_version(\"roxygen2\", version = \"5.0.1\", repos = \"https://cloud.r-project.org/\")"` => Installation OK
* `Rscript -e "require(roxygen2); roxygen2::roxygenise(\"R-package\")"` => OK
* `R CMD build --no-build-vignettes R-package` => Goes until the end and makes the file **mxnet_0.9.5.tar.gz** in .../mxnet/ but many warnings appeared, the first one is : 
Warning in cleanup_pkg(pkgdir, Log) : unable to run 'make clean' in 'src'
* Then, I try to finally install the package from this .tar.gz file on rstudio with the command `install.packages(C:/Program Files/mxnet/mxnet_0.9.5.tar.gz', repos = NULL, type="source")` 
##Second Error
 installing *source* package 'mxnet' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-33~1.2/include" -DNDEBUG -I../inst/include   -I"C:/Users/Christophe/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c executor.cc -o executor.o
In file included from ./executor.h:13:0,
                 from executor.cc:10:
././symbol.h:11:24: fatal error: nnvm/c_api.h: No such file or directory
 #include <nnvm/c_api.h>
                        ^
compilation terminated.
make: *** [executor.o] Error 1
Warning: l'exécution de la commande 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="mxnet.dll" OBJECTS="executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o"' renvoie un statut 2
ERROR: compilation failed for package 'mxnet'
 removing 'C:/Users/Christophe/Documents/R/win-library/3.3/mxnet'
 restoring previous 'C:/Users/Christophe/Documents/R/win-library/3.3/mxnet'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\Christophe\Documents\R\win-library\3.3" "C:/PROGRA~1/mxnet/mxnet_0.9.5.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/PROGRA~1/mxnet/mxnet_0.9.5.tar.gz’ had non-zero exit status

@Mrugankakarte  Thank you, I will also try this option in the meantime, it seems quite detailed.

**Comment by thirdwing** [comment]
@ChrisBotella @Mrugankakarte 

Please follow my instruction from https://gist.github.com/thirdwing/89aa9bfc588ade138496e6932072152c

The installation has been test on a Windows Server machine with GPU. It will be merged into the documents later.

![mxnet_r_gpu_win](https://cloud.githubusercontent.com/assets/1547093/26741283/a38b842a-478d-11e7-9656-3e30b1cf8ecf.jpg)

**Comment by thirdwing** [comment]
You can also try to install my pre-built pkg:
```r
install.packages("mxnet", repos="http://104.131.145.31")
```

**Comment by Mrugankakarte** [comment]
@thirdwing  Thanks a lot!!! Got no errors while installing using your pre-built package. 
Have you found out any solution regarding #5979 ?

**Comment by ChrisBotella** [comment]
@thirdwing ,

Thank you very much, I followed you instructions at [](https://gist.github.com/thirdwing/89aa9bfc588ade138496e6932072152c) I know it works fine. 

I couldn't find `mxnet.dll`, that I was supposed to move in `./R-package/inst/libs/x64`, but it doesn't perturb the install.

**Comment by thirdwing** [comment]
That is my mistake. mxnet.dll will be generated during the installation.
