### ISSUE TITLE
MXNet initialization with Constant, One or Zero returning errors

### ISSUE THREAD

**Issue by nikrao** [dmlc/mxnet#6166]
I am using mxnet initializer.Mixed to provide a mixed initialization, and get an error whenever I try to use Constant, One or Zero. 

Examples below:

>>>net = <some network that has been created>
>>>init = mx.initializer.Mixed(['fcout_bias', '.*'], [mx.init.Constant(-10.0), mx.init.Normal(0.01)])
>>>Traceback (most recent call last):
>>>  File "<stdin>", line 1, in <module>
>>>AttributeError: 'module' object has no attribute 'Constant'
'
Same error with mx.init.One or Zero

But if I try
>>> init = mx.initializer.Mixed(['fcout_bias', '.*'], [mx.init.Uniform(10.0), mx.init.Normal(0.01)])
>>> 

no error. Have the other initializers not been implemented in the MXNet version present in the AMI How do I make sure I have all the latest features?

## Environment info
Operating System:
Ubuntu

Compiler:
AWS EC2 Deep Learning AMI

Package used (Python/R/Scala/Julia):
Python

Python version and distribution:
Python 2.7.6

## Error Message:
AttributeError: 'module' object has no attribute 'Constant'

## Minimum reproducible example
>>> all_layers = net.get_internals()
>>> all_layers.list_outputs()
>>>['data', 'fc1_weight', 'fc1_bias', 'fc1_output', 'ac1_output', 'kl1_moving_avg', 'kl1_output', >>>'dl1_output', 'fcout_weight', 'fcout_bias', 'fcout_output', 'acout_output', 'softmax_label', >>>'ce_preds']
>>>init = mx.initializer.Mixed(['fcout_bias', '.*'], [mx.init.Constant(-10.0), mx.init.Normal(0.01)])
>>>Traceback (most recent call last):
>>>  File "<stdin>", line 1, in <module>
>>>AttributeError: 'module' object has no attribute 'Constant'

**Comment by pluskid** [comment]
The error message says the `init` module does not have `Constant`. Maybe you happen to be using a very old version of MXNet?

**Comment by nikrao** [comment]
I'm using what comes as the default in the DeepLearning AMI. Is there a way
I can upgrade that?

**Comment by pluskid** [comment]
What is your `mx.__version__`?

**Comment by nikrao** [comment]
0.9.3

**Comment by nikrao** [comment]
Isn't this the latest release? Would you still suggest I update?

**Comment by pluskid** [comment]
Yes, it seem to be the latest stable release. However, `mx.init.Constant` was added after that. You can try to upgrade to the pre-release v0.9.5 or if the only thing you need is `mx.init.Constant`, you could probably just copy that piece of code from the latest github code. https://github.com/dmlc/mxnet/blob/master/python/mxnet/initializer.py#L346

**Comment by nikrao** [comment]
I replaced the file with the one you linked to, but get the same error
still.

btw when i try to re-compile, i get another error after this (after git
pull and git submodule):

sudo make clean
Makefile:35: mshadow/make/mshadow.mk: No such file or directory
Makefile:36: /home/ubuntu/src/mxnet/dmlc-core/make/dmlc.mk: No such file or
directory
Makefile:131: /home/ubuntu/src/mxnet/ps-lite/make/ps.mk: No such file or
directory
make: *** No rule to make target `/home/ubuntu/src/mxnet/ps-lite/make/ps.mk'.
Stop.

**Comment by pluskid** [comment]
Can you run
```
git submodule init
git submodule update --recursive
```
and `make` again?

**Comment by nikrao** [comment]
did it, still the same error. Would you like me to send you the logs from
make?

**Comment by pluskid** [comment]
Can you check `mx.__version__` to make sure you are running the latest version that you compiled? (should be 0.9.5)

**Comment by nikrao** [comment]
nope. still 0.9.3

**Comment by nikrao** [comment]
so is this some issue with make?

**Comment by pluskid** [comment]
I think it is the way that you are compiling somehow does not overwrite the system wide existing code. You might be importing from some other sources, and that is also why when you directly replace the initializer.py, it does not work. I have not used the AMI environment, maybe you will need to figure out where the default mxnet is located in this environment.

**Comment by nikrao** [comment]
OK. Let me retry the whole thing but with installing MXNet on a GPU from
scratch

thanks
