### ISSUE TITLE
ubuntu source compile error

### ISSUE THREAD

**Issue by Moore123** [dmlc/mxnet#6169]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: ubuntu-14.04.1

Compiler:
 g++ 4.8.4-2ubuntu1~14.04.3
cuda 8.0.44

Package used (Python):

MXNet version: 

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):  104162b68853801481338c796078d63899a09913

If you are using python package, please provide

Python version and distribution: python2.7

## Error Message:
compile-error:

src/operator/tensor/./multisample_op.h: In instantiation of ‘void mxnet::op::MultiSampleOpForward(const nnvm::NodeAttrs&, const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&) [with xpu = mshadow::cpu; generator = mxnet::op::GeneralizedNegativeBinomialSampler]’:
src/operator/tensor/multisample_op.cc:359:1:   required from here
src/operator/tensor/./multisample_op.h:145:74: error: ‘class mshadow::Random<mshadow::cpu, float>’ has no member named ‘GetRandInt’

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1. nothing
2.
3.

**Comment by Soonhwan-Kwon** [comment]
Is this your first installation or you cloned properly with --recursive? If it is not, it could be the problem of the outdated or insufficient depedencies for mshadow.
1. Delete the whole mxnet and reinstall all with git clone https://github.com/dmlc/mxnet --recursive
2. or move to the mxnet/mshadow then git pull -u origin master to get update the dependency.

**Comment by Moore123** [comment]
fresh clone with recursive is OK now.   Previously is older version within directory git pull only .

This issuse could be closed.
