### ISSUE TITLE
can we feed multi input data to mxnet?

### ISSUE THREAD

**Issue by qianguih** [dmlc/mxnet#617]
Hi, there,
    I am trying to do multi-task learning using mxnet. Is it possible to feed multi-input to a network in mxnet?

**Comment by huazehuang** [comment]
See the multi-label io [doc](https://github.com/dmlc/mxnet/blob/master/doc/python/io.md#extension-mutliple-labels-for-a-single-image)

**Comment by qianguih** [comment]
Hi, thanks for your reply.
Actually, there are different sources of input rather than one same set of input with multi labels in my case. Is this possible in Mxnet?

**Comment by sneakerkg** [comment]
Hi,

Could your problem being solved by creating multiple data iterators, each
one is responsible for one data source.

Thanks,
Tianjun


2015年11月18日星期三，qianguih <notifications@github.com> 写道：

**Comment by huazehuang** [comment]
In this case you need to specify multiple mx.sym.Variable. For example

``` python
data1 = mx.symbol.Variable('data1')
fc1 = mx.symbol.FullyConnected(data=data1, name='fc1', num_hidden=128)
data2 = mx.symbol.Variable('data2')
fc2 = mx.symbol.FullyConnected(data=data2, name='fc2', num_hidden=128)
concat = mx.symbol.Concat(*[data1, data2])
fc3 = mx.symbol.FullyConnected(data=concat, name='fc3', num_hiddent=128)
softmax = mx.symbol.SoftmaxOutput(data=fc3, name='softmax')

```

**Comment by qianguih** [comment]
Hi, guys,
    thanks for pointing out how to write a multi source input network. Moreover, how can we write the training command?
    Currently, I am following the CIFAR 100 example. https://github.com/dmlc/mxnet/blob/master/example/notebooks/cifar-100.ipynb
    How can we feed multi source input to the network when calling model.fit to train the network?

**Comment by huazehuang** [comment]
The training command ```fit``` is the same. You just need to specify a multi input network and data iterator. 

Note that the default data iterator currently does not support multi source input.  You need to hack a little of [NDArrayIter](https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py#L126) to build your own data iterator.

**Comment by pluskid** [comment]
Doesn't ndarray iter already support multiple input?

**Comment by piiswrong** [comment]
NDArrayIter already supports multi input/output. Just pass in multiple data source.

**Comment by qianguih** [comment]
sorry, could you be more specific? how to write the script?

**Comment by Light--** [comment]
could you be more specific? how to write the script? @piiswrong @pluskid
