### ISSUE TITLE
Problem with implementing tree-LSTM's in mxnet

### ISSUE THREAD

**Issue by ForoughA** [dmlc/mxnet#6181]
I am implementing tree-LSTM's for predicting the negativity/positivity of sentences in mxnet and I am using the [BucketingModule](https://github.com/dmlc/mxnet/blob/master/docs/how_to/bucketing.md) to do this. The tree LSTM is structured similar to the structure of the parse-tree of each sentence. Therefore, each training sample will need a different structure. So I am using one bucket per input sample. Also, not all the LSTM blocks in a single structure have shared weights. For example, in a tree consisting of n nodes, k of the nodes can share the same weights and the other (n-k) can share their weights. The partition is not limited to two. In fact, it often is the case that most of the blocks do not share weights with the others.

  * My first problem is with training. If I train using 'sgd', and 'momentum' : 0.0, the training works fine. However, if I change momentum or try to use other optimizers such as 'adam', the training returns an inconsistency shape error due to the self.states dictionary in the Updater class in [optimizer.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/optimizer.py). It initializes the self.states dictionary for the first sentence. When the second sentence is fed, the "index" of the states is not necessarily the same as the first sentence. But the updater re-uses the already created states for the first sentence and fails at look-up time for the second equation. 

  * My second question is how can I do mini-batch training under this setting?

[My code](https://github.com/ForoughA/neuralTrig) is available on github. The main file to run is neuralTrig.py.

**NOTE: In order to run the code, the 'allow_extra_params' flag needs to be sat to True in exec_.copy_params_from(arg_params, aux_params, allow_extra_params=True) in function set_params(self, arg_params, aux_params) in file [executor_group.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/executor_group.py) line 332.**

## Environment info
Operating System: 
MAC OS X El Capitan

Compiler: 
clang-800.0.38

Package used (Python/R/Scala/Julia): 
Python

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
58e334639c4d5a875bb5b8b33036c3fab8ed7115

If you are using python package, please provide

Python version and distribution:
Python 2.7.13 :: Anaconda 4.3.1 (x86_64)

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:

[08:11:32] /Users/Forough/mxnet/dmlc-core/include/dmlc/logging.h:300: [08:11:32] src/operator/nn/../tensor/../elemwise_op_common.h:31: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 2-th input: expected (1,120), got (120,240)

Stack trace returned 9 entries:
[bt] (0) 0   libmxnet.so                         0x00000001074d5f35 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x00000001074d3539 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x000000010754de72 _ZZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ENKUlPNSB_IS3_NSD_IS3_EEEEPKcE_clESL_SN_ + 498
[bt] (3) 3   libmxnet.so                         0x000000010754db26 _ZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ + 198
[bt] (4) 4   libmxnet.so                         0x0000000107bf7e92 _ZN5mxnet2op13ElemwiseShapeILi3ELi1EEEbRKN4nnvm9NodeAttrsEPNSt3__16vectorINS2_6TShapeENS6_9allocatorIS8_EEEESC_ + 226
[bt] (5) 5   libmxnet.so                         0x0000000107a11b7e _Z12SetShapeTypePKN4nnvm2OpERKNS_9NodeAttrsERKN5mxnet7ContextERKNSt3__16vectorINS6_7NDArrayENSA_9allocatorISC_EEEERKiPSF_ + 1326
[bt] (6) 6   libmxnet.so                         0x0000000107a156b5 MXImperativeInvoke + 1093
[bt] (7) 7   _ctypes.so                          0x0000000101e59f57 ffi_call_unix64 + 79
[bt] (8) 8   ???                                 0x00007fff5e40bc90 0x0 + 140734774688912

Traceback (most recent call last):
  File "neuralTrig.py", line 214, in <module>
    main()
  File "neuralTrig.py", line 184, in main
    epoch_end_callback  = mx.rnn.do_rnn_checkpoint(cell, 'trainedModel', 1))
  File "/Users/Forough/anaconda2/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/base_module.py", line 475, in fit
    self.update()
  File "/Users/Forough/anaconda2/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/bucketing_module.py", line 401, in update
    self._curr_module.update()
  File "/Users/Forough/anaconda2/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/module.py", line 570, in update
    kvstore=self._kvstore)
  File "/Users/Forough/anaconda2/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/model.py", line 123, in _update_params
    updater(index*num_device+k, g, w)
  File "/Users/Forough/anaconda2/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/optimizer.py", line 690, in __call__
    self.optimizer.update(index, weight, grad, self.states[index])
  File "/Users/Forough/anaconda2/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/optimizer.py", line 324, in update
    lr=lr, wd=wd, **self.kwargs)
  File "/Users/Forough/anaconda2/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/_ctypes/ndarray.py", line 133, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/Users/Forough/anaconda2/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 78, in check_call
    **raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [08:11:32] src/operator/nn/../tensor/../elemwise_op_common.h:31: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node  at 2-th input: expected (1,120), got (120,240)**

Stack trace returned 9 entries:
[bt] (0) 0   libmxnet.so                         0x00000001074d5f35 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x00000001074d3539 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x000000010754de72 _ZZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ENKUlPNSB_IS3_NSD_IS3_EEEEPKcE_clESL_SN_ + 498
[bt] (3) 3   libmxnet.so                         0x000000010754db26 _ZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ + 198
[bt] (4) 4   libmxnet.so                         0x0000000107bf7e92 _ZN5mxnet2op13ElemwiseShapeILi3ELi1EEEbRKN4nnvm9NodeAttrsEPNSt3__16vectorINS2_6TShapeENS6_9allocatorIS8_EEEESC_ + 226
[bt] (5) 5   libmxnet.so                         0x0000000107a11b7e _Z12SetShapeTypePKN4nnvm2OpERKNS_9NodeAttrsERKN5mxnet7ContextERKNSt3__16vectorINS6_7NDArrayENSA_9allocatorISC_EEEERKiPSF_ + 1326
[bt] (6) 6   libmxnet.so                         0x0000000107a156b5 MXImperativeInvoke + 1093
[bt] (7) 7   _ctypes.so                          0x0000000101e59f57 ffi_call_unix64 + 79
[bt] (8) 8   ???                                 0x00007fff5e40bc90 0x0 + 140734774688912

## Minimum reproducible example
Here is [my code](https://github.com/ForoughA/neuralTrig) on git. 
The main file to run is neuralTrig.py. 

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

Here is [my code](https://github.com/ForoughA/neuralTrig) on git. 
The main file to run is neuralTrig.py. If we set the momentum to something other than zero it fails. If we use another optimzier it also fails.
**NOTE: In order to run the code, the 'allow_extra_params' flag needs to be sat to True in exec_.copy_params_from(arg_params, aux_params, allow_extra_params=True) in function set_params(self, arg_params, aux_params) in file [executor_group.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/executor_group.py) line 332.**

**Comment by ForoughA** [comment]
My issue was resolved by tweaking the _update_params(..) function in [model.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py) with the function below. 

NOTE: this does not support multiple devices, the way the original MxNet code does. It rather changes the dictionary keys (index passed to updater) to the parameter names, so that if the graph is dynamic, the newly created states in updater are attached to the right names. This is essential since for a dynamic graph list indexing is not preserved from one graph to the next. Therefore, the initial implementation does not support it. However, as noted this is just a temporary hack.

After changing the function, the arg_names and param_names should be passed to _update_params() in function update() in file [module.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/module.py).
i.e.: 
_update_params(self._exec_group.param_arrays,
                           self._exec_group.grad_arrays,
                           updater=self._updater,
                           num_device=len(self._context),
                           kvstore=self._kvstore,
                           param_names=self._exec_group.param_names,
                           arg_names=self._exec_group.arg_names)

Theis is the tweaked version of _update_params(..) in file  [model.py](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py)
def _update_params(param_arrays, grad_arrays, updater, num_device,
                   kvstore=None, param_names=None, arg_names=None):
    """ Perform update of param_arrays from grad_arrays not on kvstore."""
    if param_names==None and arg_names==None:
        for index, pair in enumerate(zip(param_arrays, grad_arrays)):
            arg_list, grad_list = pair
            if grad_list[0] is None:
                continue
            if kvstore:
                # push gradient, priority is negative index
                kvstore.push(index, grad_list, priority=-index)
                # pull back the sum gradients, to the same locations.
                kvstore.pull(index, grad_list, priority=-index)
            for k, p in enumerate(zip(arg_list, grad_list)):
                # faked an index here, to make optimizer create diff
                # state for the same index but on diff devs, TODO(mli)
                # use a better solution latter
                w, g = p
                updater(index*num_device+k, g, w)
    elif param_names!=None and arg_names!=None:
        ctr = -1
        for i, index in enumerate(arg_names):
            if index in param_names:
                ctr += 1
                arg_list  = param_arrays[ctr]
                grad_list = grad_arrays[ctr]

                if grad_list[0] is None:
                    continue
                if kvstore:
                    # push gradient, priority is negative index
                    kvstore.push(ctr, grad_list, priority=-ctr)
                    # pull back the sum gradients, to the same locations.
                    kvstore.pull(ctr, grad_list, priority=-ctr)

                for k, p in enumerate(zip(arg_list, grad_list)):
                    w, g = p
                    # This deos not support the diff device implemented in the 
                    # if statement above. This is a hack for TreeLSTM application
                    # with different structures per sample
                    updater(index, g, w)
    else:
        raise AssertionError("Both arg_names (%s) and param_names (%s) shouls be fed."
                             %(str(arg_names), str(param_names)))

**Comment by herokang** [comment]
Hi, do you figure out how to do mini-batch training with TreeLSTM?

**Comment by ForoughA** [comment]
Mini batching is not possible using the bucketing module. 

There is a new interface that is better for tree-lstms [here](https://github.com/dmlc/mxnet/pull/7022/files#diff-67f289376d3b2858314672c2a21dfb38R5) with these [tutorials](https://github.com/dmlc/mxnet/tree/master/docs/tutorials/gluon) and [examples](https://github.com/dmlc/mxnet/tree/master/example/gluon)

**Comment by herokang** [comment]
I read the examples and the tutorials, but I don't think the example [tree_lstm](https://github.com/dmlc/mxnet/blob/master/example/gluon/tree_lstm/main.py#L160) really does mini-batch physically. The example calculates forward() and backward() for every instance, then it just update gradients to weight after a batch_size, but in the core engine, the real calculation with CPU/GPU is not parallelized by mini-batch. Do I understand it right?

**Comment by szha** [comment]
@herokang that's right. Batching on a dynamic graph is not straightforward, and will take some work on the backend.

**Comment by herokang** [comment]
@szha so does mxnet have a plan on how to batch dynamic computation graphs? Like TensorFlow Fold.
