### ISSUE TITLE
Cannot even perform matrix multiplication using CPU??

### ISSUE THREAD

**Issue by xuancong84** [dmlc/mxnet#6205]
On Machine 1, Ubuntu 16.04.2 (LTS 64-bit), I have installed a fresh copy of mxnet using the standard command line:
pip install mxnet-cu80

Just trying the simplest maths function (matrix multiplication) fails as follows:
```
xuancong@wxc-i2r:~/projects/mxnet$ python                                 
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2                          
Type "help", "copyright", "credits" or "license" for more information.    
Anaconda is brought to you by Continuum Analytics.                        
Please check out: http://continuum.io/thanks and https://anaconda.org     
>>> import mxnet as mx                                                    
>>> from numpy import *                                                   
>>>                                                                       
>>> mx.__version__                                                        
'0.9.5'                                                                   
>>>                                                                       
>>> sA=mx.nd.array(random.randint(0,9,[2,3]), ctx=mx.gpu())               
>>> sB=mx.nd.array(random.randint(0,9,[3,2]), ctx=mx.gpu())               
>>> mx.nd.dot(sA,sB).asnumpy()                                            
array([[ 35.,  28.],                                                      
       [ 44.,   0.]], dtype=float32)                                      
>>>                                                                       
>>> sA=mx.nd.array(random.randint(0,9,[2,3]))                             
>>> sB=mx.nd.array(random.randint(0,9,[3,2]))                             
>>> mx.nd.dot(sA,sB).asnumpy()                                            
Illegal instruction (core dumped)                                         
xuancong@wxc-i2r:~/projects/mxnet$                                        
```               

So I cannot even get started on my Desktop, that is quite disappointing!!!

However, I have done exactly the same thing on Machine 2 (with identical OS version, miniconda2, etc), surprisingly it works without crashing.

My suspicion is the following:
Machine 1 has CPU= Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz which only support AVX instruction set but not AVX2 instruction set; Machine 2 has CPU=Intel(R) Xeon(R) CPU E5-2643 v4 @ 3.40GHz which support both AVX and AVX2 instruction set. MXNET's CPU matrix multiplication code is compiled with AVX optimization which assumes both AVX and AVX2 support. However, it does not check for AVX2 instruction support. How can the developers be so inexperienced on instruction-level optimization? 

Numpy, Scipy, Tensorflow, Theano, etc does not have these kind of problems though-:(

**Comment by piiswrong** [comment]
@szha Looks like a binary compatibility problem?

**Comment by eickhoff** [comment]
I have the same issue. 

Intel(R) Xeon(R) CPU E5-4650 0 @ 2.70GHz (no AVX2 support):
Code does not run.

Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (with AVX2 support):
Code runs flawlessly.

**Comment by xuancong84** [comment]
Since the binary does not work, I have to compile from source, but I get the following error.

```
xuancong@wxc-i2r:~/packages/mxnet$ make
Makefile:35: mshadow/make/mshadow.mk: No such file or directory
Makefile:36: /home/xuancong/packages/mxnet/dmlc-core/make/dmlc.mk: No such file or directory
Makefile:131: /home/xuancong/packages/mxnet/ps-lite/make/ps.mk: No such file or directory
make: *** No rule to make target '/home/xuancong/packages/mxnet/ps-lite/make/ps.mk'.  Stop.
```

It seems that some necessary files are missing preventing make to proceed.

**Comment by szha** [comment]
@xuancong, thanks for reporting this. I'm looking into this. Do you mind trying out '''mxnet-cu80mkl''' too?

**Comment by xuancong84** [comment]
I have managed to built MXNET from source with MKL2017 and CUDA, now it works on my desktop! That is good! 
Thanks to @szha , the mxnet-cu80mkl pip wheel also works without crashing!

So I hope this could give some tips to the developer. Not so many computers support AVX2 instruction set, so when you build the optimized binary, try not to optimize too much.

Hi @piiswrong , while compiling MXNET, I do see control_flow_ops.cu, so what is the corresponding API function? Do you have any idea? Thanks!

**Comment by szha** [comment]
@xuancong84 @eickhoff I've fixed this problem for ```mxnet, mxnet-cu75, mxnet-cu80```. Could you ```pip install -U``` and try the new version and see if the issue is fixed for you?

**Comment by eickhoff** [comment]
Works out-of-the-box now for me.
Thanks a lot!

**Comment by xuancong84** [comment]
Now it works! Many thanks!-:)

**Comment by keivenhuang** [comment]
@szha ,I try the command 'pip install -U mxnet',but it still doesn't work,however,when I build MXNet from source，it now works!

**Comment by szha** [comment]
@keivenhuang thanks for reporting. What's the issue when you use pip install and what system are you on?

**Comment by keivenhuang** [comment]
@szha ,thanks for your reply,i have the same issue as xuancong84 ,now i find the reason,when i use pip,the newest version is mxnet-0.10.0.post2-py2.py3-none-manylinux1_x86_64.whl,but the version from souce is mxnet-0.10.1
