### ISSUE TITLE
Using imperative programming returns incompatible attr in node error

### ISSUE THREAD

**Issue by dwbhappy** [dmlc/mxnet#6213]
I am attempting to reproduce the network I have with imperative programming in R. While using the symbolic programming the network is a simple mxnet with one hidden layer and 20 nodes:

`NHIDDEN <- 20`
`array.batch.size <- 200`
`act <- mx.symbol.Variable("data")`
`fc1 <- mx.symbol.FullyConnected(act, num.hidden = NHIDDEN, name='fc1')`
`act <- mx.symbol.Activation(data = fc1, act_type = "tanh", name="act")`
`fc2 <- mx.symbol.FullyConnected(act, num_hidden=1, name='fc2')`

My imperative program is:

`W <- mx.symbol.random_normal(loc=0, scale=1, shape=c(1, NHIDDEN))`
`b <- mx.symbol.random_normal(loc=0, scale=1, shape=c(1, NHIDDEN))`
`W_out = mx.symbol.random_normal(loc=0, scale=1,shape=c(1, NHIDDEN))`
`b_out = mx.symbol.random_normal(loc=0, scale=1,shape=c(1, 1))`
`hidden_layer = mx.symbol.tanh((mx.symbol.dot(act, W) + b))`
`y_out = mx.symbol.dot(hidden_layer,W_out) + b_out`

This fails with the error:
mxnet/dmlc-core/include/dmlc/logging.h:304: [15:10:36] src/operator/nn/./../tensor/../elemwise_op_common.h:33: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _plus4 at 1-th input: expected (200,1), got (20,1)

How should I define this simple network using the imperative style of programming?

**Comment by dwbhappy** [comment]
I was able to find a tutorial with an example showing how to leverage the imperative programming language to solve this issue in Python. I should be able to translate it to R. The tutorial by Julien Simon is here:
https://medium.com/@julsimon/an-introduction-to-the-mxnet-api-part-3-1803112ba3a8

The code sample is also here:
https://gist.github.com/juliensimon/7cfef0423b0183e891774a289e156b49

**Comment by Garglesoap** [comment]
Did you happen to translate this in R?
