### ISSUE TITLE
unknown gpu error

### ISSUE THREAD

**Issue by yuconglin** [dmlc/mxnet#6271]
Can anyone help with a gpu issue? Thanks in advance
## code
import mxnet as mx
a = mx.nd.ones((2,3), mx.gpu())
## error
[11:38:52] /home/ylin67/softwares/mxnet/dmlc-core/include/dmlc/logging.h:303: [11:38:52] /home/ylin67/softwares/mxnet/mshadow/mshadow/./tensor_gpu-inl.h:35: Check failed: e == cudaSuccess CUDA: unknown error

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x39) [0x7fcba8a91449]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN7mshadow9SetDeviceINS_3gpuEEEvi+0xe0) [0x7fcba9341c80]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data+0x30) [0x7fcba9349e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x90c30) [0x7fcbc452ac30]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7fcbc8ba9184]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fcbc88d6bed]

[11:38:52] /home/ylin67/softwares/mxnet/dmlc-core/include/dmlc/logging.h:303: [11:38:52] /home/ylin67/softwares/mxnet/mshadow/mshadow/./tensor_gpu-inl.h:35: Check failed: e == cudaSuccess CUDA: unknown error

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x39) [0x7fcba8a91449]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN7mshadow9SetDeviceINS_3gpuEEEvi+0xe0) [0x7fcba9341c80]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data+0x30) [0x7fcba9349e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x90c30) [0x7fcbc452ac30]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7fcbc8ba9184]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fcbc88d6bed]

terminate called after throwing an instance of 'dmlc::Error'
terminate called recursively
  what():  [11:38:52] /home/ylin67/softwares/mxnet/mshadow/mshadow/./tensor_gpu-inl.h:35: Check failed: e == cudaSuccess CUDA: unknown error

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x39) [0x7fcba8a91449]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN7mshadow9SetDeviceINS_3gpuEEEvi+0xe0) [0x7fcba9341c80]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data+0x30) [0x7fcba9349e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x90c30) [0x7fcbc452ac30]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7fcbc8ba9184]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fcbc88d6bed]
Aborted (core dumped)

## GPU info from nvidia-smi
Tue May 16 12:03:08 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K4100M       Off  | 0000:01:00.0      On |                  N/A |
| N/A   57C    P0    22W /  N/A |    809MiB /  4035MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     26525    G   /usr/bin/X                                     470MiB |
|    0     27142    G   compiz                                         173MiB |
|    0     27599    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd   163MiB |
+-----------------------------------------------------------------------------+

**Comment by eric-haibin-lin** [comment]
Could you also post the commit version for MXNet so that we can reproduce?

**Comment by yuconglin** [comment]
commit bc6e4b4cbc4e3e4f361acb5d7cebb60ffa36ec50

**Comment by yuconglin** [comment]
I figured that it was a cuda driver issue instead of mxnet issue.

**Comment by HQ01** [comment]
Hi,
Would you mind sharing with me how you solve this problem? @yuconglin I came across the same issue. It worked perfectly a few days ago but just broke.

**Comment by yuconglin** [comment]
@HQ01 if restart does not fix. you probably can try to re-install cuda driver

**Comment by HQ01** [comment]
@yuconglin Yeah I simply re-installed it and it worked. Thanks!
