### ISSUE TITLE
Any tools to convert pretrained mxnet model to model for caffe?

### ISSUE THREAD

**Issue by iamhankai** [dmlc/mxnet#628]
Any tools to convert pretrained mxnet model to model for caffe?

**Comment by winstywang** [comment]
I think you should ask this question to caffe developers...

**Comment by futurely** [comment]
To do network parameters extraction and construction in the opposite direction of https://github.com/dmlc/mxnet/blob/master/tools/caffe_converter/convert_model.py all you need are [`symbol, arg_params, aux_params = load_checkpoint(prefix, epoch)`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py) and https://github.com/BVLC/caffe/blob/master/examples/pycaffe/caffenet.py.

**Comment by n3011** [comment]
I have previously developed a tool to convert model from cxxnet to caffe model, it may help you write your own code for mxnet version
https://github.com/n3011/cxxnet_converter

**Comment by EasonD3** [comment]
Is there any script (from MXNet model to Caffe model) that could be shared so far? And can we convert any kind MXNet model (e.g., GoogleNet, ResNet, or some customized model) into their Caffe format directly?

**Comment by antinucleon** [comment]
@EasonD3 I think it is better to ask this question in Caffe issue. We don't have script to convert model to caffe and and we don't have plan to do it.

**Comment by EasonD3** [comment]
I see. Thanks @antinucleon

**Comment by hahnyuan** [comment]
I have write a tool for visulize https://github.com/hahnyuan/darknet-visualizer
