### ISSUE TITLE
cpp-package multiple GPU support?

### ISSUE THREAD

**Issue by rococopeach** [dmlc/mxnet#6284]
Does cpp-package support multiple GPUs parallel training? 
I am trying to implement A3C using cpp-package.

I saw another thread "How to run on multiple GPUs - python". https://github.com/dmlc/mxnet/issues/3082
It seems I need to use module instead of bind. I could not find module in cpp-package.

Do I need to use KVStore directly? How?
How mxnet::cpp::SetOptimizer works?

**Comment by lx75249** [comment]
module is under development, you can use KVStore directly for now. See https://github.com/lx75249/mxnet/blob/vdsr-bug/cpp-package/example/lap.cpp#L271

**Comment by rococopeach** [comment]
I did not know lac.cpp include how to use kvstore.
I think I under stand how it works.
Thank you very much.
