### ISSUE TITLE
training speed is much slower when I install through building form source instead of using pip to install.

### ISSUE THREAD

**Issue by githubfragments** [dmlc/mxnet#6296]
Hello, I install MXNet through building from source and pip.
The training speed:
1. building from source: 5 samples / sec,
2. install through pip:     9 samples /sec

I use the same net, just switching between the two mxnet python package, but the speed is quite difference. Why running speed through building from source is so slow?

ps:
cuda: 7.5
cudnn: v4
Precompiled package through pip is in 2017. 05. 08
source is download in 2017. 05. 16

**Comment by szha** [comment]
Are you using the 0.9.5 version through pip? Which package are you using (`mxnet-cu75` / `mxnet-cu75mkl`)? What example are you running? On what hardware?
Starting from 0.9.5 I statically linked cudnnv6 to the wheel which might contribute to the performance difference.

**Comment by githubfragments** [comment]
I  installed mxnet-cu75，0.9.5 version through pip, running on maxwell titan x with ordinary conv nets.  Cudnnv4 is used. Is that caused such a big difference?

**Comment by szha** [comment]
the 0.9.5 version doesn't use your installed cudnnv4, but rather the statically linked cudnnv6 :)

**Comment by githubfragments** [comment]
Thanks, the problem is solved. The cudnnv4 is used previously when compiling. After I change the cudnn version to 6.0 and recompile,  the speed is normal.
