### ISSUE TITLE
python install error due to invalid syntax

### ISSUE THREAD

**Issue by pineking** [dmlc/mxnet#630]
run the command: python setup.py install

the error is:

Extracting mxnet-0.5.0-py2.6.egg to /usr/lib/python2.6/site-packages
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/mxnet-0.5.0-py2.6.egg/mxnet/model.py', 232, 26, '                       for k, v in train_data.provide_data}\n'))

**Comment by piiswrong** [comment]
try add a \ at the end of 231?

what's your python version? upgrading to 2.7 probably will resolve this.

**Comment by pluskid** [comment]
it seems the OP is using python 2.6.

**Comment by pineking** [comment]
Fixed it by updating to python 2.7, this information should be told in prerequisites and install part of the documents.
