### ISSUE TITLE
Deeplab and atrous convolution

### ISSUE THREAD

**Issue by hondaathma** [dmlc/mxnet#6326]
Hi,
I am unable to find atrous convolution layers in mxnet(for deeplab).Can I incorporate any caffe  operations and python layers in mxnet?

**Comment by Piyush3dB** [comment]
For atrous convolution you can use

```python
mx.sym.Convolution(data=net, num_filter=channels, kernel=filter_dimension, stride=stride, dilate=dilate)
```
where the `dilate` parameter specifies how wide the convolution kernel reaches.
