### ISSUE TITLE
MxnetTestApp throw runtime exception on window 10 x64

### ISSUE THREAD

**Issue by anzw** [dmlc/mxnet#635]
I download 20151110_win64_cpu_only.7z, when run MxnetTestApp on window 10 x64, it throws runtime exception 
![10](https://cloud.githubusercontent.com/assets/4187342/11273285/692ddf2e-8f0d-11e5-9ac2-979573993a70.PNG)

**Comment by piiswrong** [comment]
@hjk41

**Comment by hjk41** [comment]
The bug reproduces on my machine. I am debugging now.

On Fri, Nov 20, 2015 at 3:05 AM, Eric Junyuan Xie <notifications@github.com>
wrote:

> Assigned #635 <https://github.com/dmlc/mxnet/issues/635> to @hjk41
> <https://github.com/hjk41>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/635#event-469549660>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by tqchen** [comment]
closing for now
