### ISSUE TITLE
char-lstm notebook gives different (overfeat) results than saved notebook on github (py2/3?)

### ISSUE THREAD

**Issue by udibr** [dmlc/mxnet#636]
I've re run the [char-lstm notebook](https://github.com/dmlc/mxnet/blob/master/example/rnn/char_lstm.ipynb) without modifing anything and compared the training and validation of the original notebook on github to the results I got (which I called SGD). It looks like something has changed and now the model is overfitting a little bit but the validation is a little bit better.
I noticed that I am running python 2.7.10 while the stored version on github was using python 3.4.2
![image](https://cloud.githubusercontent.com/assets/608789/11270580/2aafa0f4-8e8e-11e5-93ec-749177256b1a.png)

**Comment by antinucleon** [comment]
Recently we merged a new PR which leads to these change: https://github.com/dmlc/mxnet/pull/484 .Sorry we didn't update notebook together

**Comment by tqchen** [comment]
@antinucleon can you update the notebook result and close this issue?

**Comment by tqchen** [comment]
closing for now, guess was fixed due to the changes
