### ISSUE TITLE
mx.sym.Dropout() Segmentation fault

### ISSUE THREAD

**Issue by GrindstoneLZX** [dmlc/mxnet#6365]
I tried to add dropout operation to train a MLP network, however I encontered segmentation fault.
So I wrote a simple example, and the segmentation fault occurred.
Please take a look, thank you!

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
ubuntu 16.04

Compiler:
g++ 5.4.0
cuda 8.0
cudnn 6.0

Package used (Python/R/Scala/Julia):
Python 2.7

MXNet version:
0.9.5

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):
7c39f845d32679eaa2287b2554c133d9e45923e2

If you are using python package, please provide

Python version and distribution:
2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
Segmentation fault (core dumped)
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
``` python
import mxnet as mx
import numpy as np

input_array = mx.nd.array([[3., 0.5,  -0.5,  2., 7.],
                     [2., -0.4,   7.,  3., 0.2]], ctx=mx.gpu(0))

a = mx.symbol.Variable('a')
dropout = mx.symbol.Dropout(a, p=0.2)
executor = dropout.simple_bind(a=input_array.shape, ctx=mx.gpu(0))

executor.forward(is_train=True, a=input_array)
print executor.outputs[0].asnumpy()

```
## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

if I set `is_train = False`, then there is no error, however when I set `is_train = True`, segmentation fault occurred.

## What have you tried to solve it?

1.
2.
3.

**Comment by piiswrong** [comment]
the code runs fine on my machine. Please check your environment, build, gpu setup etc

**Comment by GrindstoneLZX** [comment]
@piiswrong I upgraded CUDA to latest version, problem solved.
Thank you!

**Comment by thvasilo** [comment]
@piiswrong I'm facing the same issue on a machine with CUDA 7.5, is there any way to use dropout with CUDA7.5 and MXNet 0.9 (or 0.10)?
