### ISSUE TITLE
Error installing perl bindings 

### ISSUE THREAD

**Issue by rbnx** [dmlc/mxnet#6379]
OS: Ubuntu 16.04
Compiler: gcc 5.4.0
Package used: Perl
MXNet version: (0.9.3)

I am trying to install the perl bindings (AI::MXNet).
I downloaded this repo, compiled everything then moved to the perl-package folder but I am unable to install AI::MXNetCAPI or AI::NNVMCAPI
I keep getting this error: 

```
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- NNVMCAPI.bs blib/arch/auto/AI/NNVMCAPI/NNVMCAPI.bs 644
rm -f blib/arch/auto/AI/NNVMCAPI/NNVMCAPI.so
LD_RUN_PATH="/home/r/Programming/mxnet/perl-package/AI-NNVMCAPI/../../lib" x86_64-linux-gnu-gcc  -shared -L/usr/local/lib -fstack-protector-strong nnvm_wrap.o  -o blib/arch/auto/AI/NNVMCAPI/NNVMCAPI.so  \
   -L/home/r/Programming/mxnet/perl-package/AI-NNVMCAPI/../../lib -lmxnet   \
  
x86_64-linux-gnu-gcc: error: nnvm_wrap.o: No such file or directory
Makefile:481: recipe for target 'blib/arch/auto/AI/NNVMCAPI/NNVMCAPI.so' failed
make: *** [blib/arch/auto/AI/NNVMCAPI/NNVMCAPI.so] Error 1
```

**Comment by rbnx** [comment]
@sergeykolychev Any suggestions? 
Thanks.

**Comment by sergeykolychev** [comment]
Hi Ruben,
You'll find the instructions for ubuntu at the bottom of this page
https://github.com/dmlc/mxnet/blob/master/docs/get_started/ubuntu_setup.md
From the looks of it you did not install the 'swig' that is used to generate the .cc files.

**Comment by rbnx** [comment]
@sergeykolychev you are right I hadn't installed SWIG, thanks for all your hard work!

**Comment by davehodg** [comment]
And this is exactly what I just found!

**Comment by davehodg** [comment]
https://github.com/dmlc/mxnet/blob/master/docs/get_started/ubuntu_setup.md

This link is broken.

**Comment by davehodg** [comment]
The proper link is now:

https://github.com/apache/incubator-mxnet/blob/master/docs/install/ubuntu_setup.md

**Comment by sergeykolychev** [comment]
@davehodg can you help with maintaining the project ?

**Comment by davehodg** [comment]
Still struggling to install AI::FANN.

For which I need this apparently.

**Comment by davehodg** [comment]
The proper link is now:

https://github.com/apache/incubator-mxnet/blob/master/docs/install/ubuntu_setup.md

**Comment by sergeykolychev** [comment]
@davehodg AI::FANN ? You've got me confused, how's related to AI::MXNet ?

**Comment by davehodg** [comment]
It’s AI::MXNet. 

Please hold.

**Comment by sergeykolychev** [comment]
@davehodg Cool, thanks. Just in a case you can also get working mxnet/perl via docker from https://hub.docker.com/r/mxnet/perl/

**Comment by davehodg** [comment]
I’m still trying to piece things together!

**Comment by sergeykolychev** [comment]
yeah I get it, just wanted to let you know that with already precompiled docker image you do not need to go through trouble of compiling the mxnet lib and perl bindings if you want just to try it.
It's as simple (assuming you've got docker installed)
```
docker pull mxnet/perl
docker run mxnet/perl perl -e 'use AI::MXNet qw(mx); my $ar = mx->nd->ones([2,2]); print (($ar*2)->aspdl)'
```
I apologize if these instructions are redundant.

**Comment by davehodg** [comment]
What dep am I missing?

# docker run mxnet/perl perl -e 'use AI::MXNet qw(mx); my $ar = mx->nd->ones([2,2]); print (($ar*2)->aspdl)'
libdc1394 error: Failed to initialize libdc1394

[
 [2 2]
 [2 2]
]

**Comment by sergeykolychev** [comment]
@davehodg
It's just a harmless warning from OpenCV (a prerequisite of mxnet) that does not affect anything, but if you want to get rid of it just link /dev/raw1394  to /dev/null
```
docker run -v /dev/null:/dev/raw1394 mxnet/perl perl -e 'use AI::MXNet qw(mx); my $ar = mx->nd->ones([2,2]); print (($ar*2)->aspdl)'
```
https://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394

**Comment by sergeykolychev** [comment]
@davehodg 
you can run (for example) the calculator.pl from the examples dir by
 ```
## see http://blogs.perl.org/users/sergey_kolychev/2017/04/machine-learning-in-perl-part2-a-calculator-handwritten-digits-and-roboshakespeare.html
docker run -v /dev/null:/dev/raw1394 mxnet/perl mxnet/perl-package/AI-MXNet/examples/calculator.pl
```

**Comment by davehodg** [comment]
I’m having to revise docker. I haven’t done it for a while.

The perils of being in PHP land most of this year.

**Comment by davehodg** [comment]
Would you mind if I had a play with AI-MXNet as part of the pull request challenge?

Ta,

Dave

**Comment by sergeykolychev** [comment]
@davehodg not at all, please play with it as you see fit.
The more attention this gets from perl community the better.

**Comment by xFFFFF** [comment]
I have this issue too, you ommited this warning: `No library found for -lmxnet`

**Comment by sergeykolychev** [comment]
@xFFFFF Cool!, glad to see some interest. Let me know if you'll run by any bug.

**Comment by sergeykolychev** [comment]
@xFFFFF 
Just tested the lib on perl 5.26.1
You'll need small patch to get all tests to pass on this perl. I am working on larger patch that will include this fix as well.
```
--- a/perl-package/AI-MXNet/lib/AI/MXNet/AutoLoad.pm
+++ b/perl-package/AI-MXNet/lib/AI/MXNet/AutoLoad.pm
@@ -27,7 +27,7 @@ sub AUTOLOAD
     my $sub = "_${prefix}_$name";
     {
         no strict 'refs';
-        *{"$class::$name"} = sub { shift; $real_class->$sub(@_); };
+        *{"${class}::$name"} = sub { shift; $real_class->$sub(@_); };
     }
     goto $class->can($name);
 }
```

**Comment by xFFFFF** [comment]
I did not notice any error ... an example from your blog with gluon start without any warning. Only I did not finished traing, because I want do something else. I gave up today. I am a total novice and will take some time to run what I want to run :) - ML with buy or sell. It's a pity that most of the examples are operations on images, not numbers :(

**Comment by sergeykolychev** [comment]
@xFFFFF 
One of the tests fail on perl 5.26.1 without that patch above. If you don't care, just ignore.
check out calculator.pl :-) as close to numbers as they come. Images are also converted to numbers before being fed into the network.
On serious note, if you are really new to the subject start with this book. http://neuralnetworksanddeeplearning.com/chap1.html
