### ISSUE TITLE
Compilation issue with openblas

### ISSUE THREAD

**Issue by Strateus** [dmlc/mxnet#638]
Edited/Added 
USE_BLAS = openblas
ADD_CFLAGS =  -I/root/openblas/include
ADD_LDFLAGS = -I/root/openblas/lib

to config.mk but still get this error:

/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:122: recipe for target 'lib/libmxnet.so' failed
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lopenblas
collect2: error: ld returned 1 exit status
Makefile:136: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

What should i check for?

**Comment by piiswrong** [comment]
-I/root/openblas/lib -> -L/root/openblas/lib

**Comment by Strateus** [comment]
Worked, thank you!
