### ISSUE TITLE
How do I supress the log in convolution?

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#6383]
```
This convolution is not supported by cudnn, MXNET convolution is applied.
```

**Comment by wangg12** [comment]
This is very annoying to the std output for it outputs this log in every non cudnn conv operation of each forward time.

**Comment by wangg12** [comment]
@piiswrong Could you help?

**Comment by xioryu** [comment]
You may turn off the cudnn autotune message manually by:
export MXNET_CUDNN_AUTOTUNE_DEFAULT=0

**Comment by wangg12** [comment]
@xioryu This does not work.

**Comment by wangg12** [comment]
I think it's better to have this logging message in building the graph and not show it in forward time. It is too annoying...

**Comment by wangg12** [comment]
Perhaps I will simply comment this line the next time I recompile mxnet......

**Comment by realwecan** [comment]
Hi @wangg12 just wanted to let you know I ran into the same issue and do you have any clue about what is actually the cause for this problem?

For me I was able to get rid of the error messages by re-installing a proper version of cudnn. You may want to make sure you have the correct/appropriate cudnn version.

**Comment by wangg12** [comment]
@realwecan I've tried cudnn 5.1 and 6.0, not work.

**Comment by lilhope** [comment]
@wangg12 same issue with you. I use the dilated convolution,seems not supported.

**Comment by lc8631058** [comment]
@wangg12 @lilhope @realwecan have you guys figured this out?  does this error influences the result?

**Comment by wangg12** [comment]
@lc8631058 It does not affect the result. It is just a annoying log message which need a better design in mxnet mechanism.
