### ISSUE TITLE
Add unpooling operator for segmentation network

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#640]
https://github.com/dmlc/mxnet/pull/422 and https://github.com/dmlc/mxnet/pull/503 have added the deconvolution operator for segmentation. The other missing piece to construct a complete segmentation network is the unpooling layer (https://github.com/dmlc/mxnet/issues/337#issuecomment-157978068).
Current reference implementation is only in Caffe.
https://github.com/HyeonwooNoh/caffe/blob/new_data_layer/src/caffe/layers/unpooling_layer.cpp
https://github.com/HyeonwooNoh/caffe/blob/new_data_layer/src/caffe/layers/unpooling_layer.cu

**Comment by tornadomeet** [comment]
yes, when using the [Deconvnet](http://cvlab.postech.ac.kr/research/deconvnet/) for segmentation, the last op is uppooling, but currently, the io part for segmentation is not support.
if the  mxneters agreed adding the uppolling op, i will try it.

**Comment by tqchen** [comment]
Yes, that would be great

**Comment by tornadomeet** [comment]
i just see this, i'll do it this week~

**Comment by antinucleon** [comment]
Done. https://github.com/dmlc/mxnet/pull/746
