### ISSUE TITLE
Potential race in Engine code?

### ISSUE THREAD

**Issue by Luo-Liang** [dmlc/mxnet#6413]
https://github.com/dmlc/mxnet/blob/master/src/engine/threaded_engine.cc#L314

In this piece of code, there may be a potential race condition where the content of `PushSync()` call finishes earlier than the `finished_cv_.wait()` so that the notification of `PushSync()` is lost?
I think we need to guard 

 finished_cv_.wait(lock, [this, &done]() {
        return done.load() || kill_.load();
      });

with 

if(done == false)
  finished_cv_.wait(lock, [this, &done]() {
        return done.load() || kill_.load();
      });

?_?
thanks

**Comment by piiswrong** [comment]
@tqchen

**Comment by piiswrong** [comment]
If done is already true will wait still block?

**Comment by Luo-Liang** [comment]
good call!

It turns out the done.load() || kill.load() is checked first already. So there is no need to change.

http://en.cppreference.com/w/cpp/thread/condition_variable/wait
