### ISSUE TITLE
Installing mxnet on Mac

### ISSUE THREAD

**Issue by mwegman4** [dmlc/mxnet#645]
Hello,

I'm attempting to build and install the mxnet package to use in R/RStudo (on my Mac OSX10.10.5). I've been following the steps described in the installation guide, but am receiving an error when I try to build mxnet on the project root.

I began with:
1) Installed git
2) Terminal: git clone --recursive https://github.com/dmlc/mxnet
3) Installed homebrew [0.9.5 (git revision 3d1e; last commit 2015-11-18)]
4) Terminal: brew update
5) Terminal: brew tap homebrew/science
6) Terminal: brew info opencv
7) Terminal: brew install opencv
8) Terminal: cp make/osx.mk config.mk

Output: cp: make/osx.mk: No such file or directory
So I tried...

9) Terminal: cd mxnet
10) Terminal: cp make/osx.mk config.mk
11) Terminal: make -j4

Output:
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/im2rec] Error 1

What am I doing wrong?

**Comment by piiswrong** [comment]
could you provide more detail before ld: symbol(s) not found for architecture x86_64
?

**Comment by phunterlau** [comment]
do you use clang or gcc from brew? I had similar problem with gcc from brew, if change back to clang (from xcode), it solves the problem

**Comment by pluskid** [comment]
I guess we should add to the document that only compiling with clang is supported on OS X.

**Comment by phunterlau** [comment]
hack1nt0 from sina weibo <http://www.weibo.com/1762781217> proposed and tested his own clang-omp and clang-omp++ solution for using OpenMP with BLAS on Mac. If CPU only, openmp is not really necessary because BLAS can take care of multi-thread and fully utilize CPUs, but with multiple GPU, it still make some sense.

![](http://ww1.sinaimg.cn/large/6911e821jw1ey9rzfiebij20ku03cmzd.jpg)

**Comment by zachmayer** [comment]
@mwegman4 
1. Installed git
2. Terminal: `git clone --recursive https://github.com/dmlc/mxnet`
3. Installed homebrew [0.9.5 (git revision 3d1e; last commit 2015-11-18)]
4. Terminal: `brew update`
5. Terminal: `brew tap homebrew/science`
6. Terminal: `brew info opencv`
7. Terminal: `brew install opencv`
**8a. `cd mxnet`**
8b. Terminal: cp make/osx.mk config.mk

**Comment by zachmayer** [comment]
nvm!

**Comment by zachmayer** [comment]
I had to edit `config.mk` to get it to compile:
```
export CC = clang-omp
export CXX = clang-omp++
USE_OPENMP = 1
```

I also had to install `clang-omp` via brew:
```{bash}
brew install clang-omp
brew install pkg-config
```

The directions I followed are here: https://medium.com/@lelayf/installing-mxnet-for-r-on-yosemite-291470055980#.4tn8uqst6

**Comment by phunterlau** [comment]
@zachmayer yes, if use clang-omp, these changes are needed, my test also confirms this. OpenMP is primarily for multi-GPU for fast data loading (from my understanding) while BLAS can take care of multi-thread CPU. Since most of Macs don't have multi-CUDA-GPU cards, clang-omp may not be necessary. Is it correct?

**Comment by mwegman4** [comment]
As a side note, I was originally having trouble installing openCV so I went through these steps:

**Comment by mwegman4** [comment]
http://blogs.wcode.org/2014/10/howto-install-build-and-use-opencv-macosx-10-10/

**Comment by mwegman4** [comment]
Still getting an error. [Here](https://github.com/dmlc/mxnet/files/43437/Output.txt) is the full output when I follow instructions posted by @zachmayer and run make -j4

**Comment by phunterlau** [comment]
@mwegman4 have you tried `brew install opencv` as in the instruction? If opencv is built by source, it may not find all correct PATH variables.

**Comment by thirdwing** [comment]
@mwegman4 In your log,

```
ld: warning: object file (/usr/local/lib/libopencv_imgcodecs.a(loadsave.cpp.o)) was built for newer OSX version (10.11) than being linked (10.10)
```

It indicates you have more than one version of opencv installed on your system. My advice is to remove them and reinstall opencv through `brew`

**Comment by mwegman4** [comment]
Thanks for identifying this. I was able to uninstall the brew installed version (wish I would have realized brew could install it first!), but I still have opencv installed through the process I followed here: http://blogs.wcode.org/2014/10/howto-install-build-and-use-opencv-macosx-10-10/ The files are located in my usr/local/lib folder and I'm not quite sure how to properly uninstall them. It appears that Xcode now only comes with SDK10.11 which is the the underlying cause of the incompatibility (since I pointed to this SDK in Cmake and I'm using OS 10.10.5). When I try to simply delete the opencv files in my usr/local/lib folder and then use brew to install opencv, I get this
[this.txt](https://github.com/dmlc/mxnet/files/44124/output2.txt) error running make -j4. Is there a way to uninstall this incorrectly compiled version or point to the brew-installed version of opencv? 

Thanks.

**Comment by tqchen** [comment]
closing due to inactive status, feel free to reopen if there is update

**Comment by formath** [comment]
brew install clang-omp has been not working. So how to install clang-omp easily?

**Comment by liangfu** [comment]
I foun the option `-Xclang -fopenmp` should be used instead of normal `-fopenmp` for xcode built-in clang based compiler, and installing `clang-omp` is no longer necessary. This should be fixed in `${ROOT_DIR}/dmlc-core/CMakeLists.txt`.

**Comment by phunterlau** [comment]
@liangfu nice finding. I don't think OpenMP is necessary since BLAS can take all CPUs, glad that mac can remove OpenMP dependency.

**Comment by liangfu** [comment]
@phunterlau It's nice to consider adding native support for macOS. But is there any continuous integration systems (like travis-ci) that support checking the compatibility of future versions? Then I would submit a PR. 
BTW, I don't think BLAS would automaticly take all CPUs, systems like OpenBLAS support changing number of threads only at compile time, not at run-time. So, manually handle multi-threading with features like OpenMP is usually necessary.

**Comment by thirdwing** [comment]
What do you mean native support for macOS?

Actually all travis-ci tests we have now are on OSX.

**Comment by rohitsaboo** [comment]
Here's what I had to do to get mxnet to build on MacOS Sierra (10.12.1):

```sh
$ HOMEBREW_CC=clang brew install openblas
```
Add/modify the following lines in config.mk
```
export CC=clang
export CXX=clang++

ADD_LDFLAGS = -L/usr/local/opt/openblas/lib -L/usr/local/lib/graphviz/
ADD_CFLAGS = -I/usr/local/opt/openblas/include

USE_BLAS = openblas
```

**Comment by rohitsaboo** [comment]
I had an environment variable called BIN that seemed to be interfering with building mxnet causing errors of the form

```
cd /Users/rohit/src/mxnet/dmlc-core; make libdmlc.a USE_SSE=1 config=/Users/rohit/src/mxnet/config.mk; cd /Users/rohit/src/mxnet
make[1]: `libdmlc.a' is up to date.
clang++ -DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/rohit/src/mxnet/mshadow/ -I/Users/rohit/src/mxnet/dmlc-core/include -fPIC -Iinclude -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -Wno-unused-local-typedefs -msse3 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 -I/usr/local/Cellar/opencv/2.4.13.1/include/opencv -I/usr/local/Cellar/opencv/2.4.13.1/include -I/usr/local/opt/openblas/include -DMXNET_USE_NVRTC=0 -std=c++11  -o /Users/rohit/src/mxnet/beam/bazel/bin/Users/rohit/src/mxnet  -pthread -lm -lopenblas  -L/usr/local/Cellar/opencv/2.4.13.1/lib -lopencv_calib3d -lopencv_contrib -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_gpu -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videostab -L/usr/local/opt/openblas/lib -L/usr/local/lib/graphviz/
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/rohit/src/mxnet/beam/bazel/bin/Users/rohit/src/mxnet] Error 1
```

Unsetting `BIN` and building seemed to fix this:
```
mxnet$ BIN= make -j8
```

Additionally, I also did the following to build mxnet on MacOS Sierra (10.12.1) though I'm not sure how much of this is really necessary:

```
$ HOMEBREW_CC=clang brew install openblas
```
Add/modify the following lines in config.mk:
```
export CC=clang
export CXX=clang++

ADD_LDFLAGS = -L/usr/local/opt/openblas/lib -L/usr/local/lib/graphviz/
ADD_CFLAGS = -I/usr/local/opt/openblas/include

USE_BLAS = openblas
```

DISCLAIMER: I just started mucking around with mxnet a few hours back and have only tried the python example after doing this. Your machine (and my machine after a few hours) may still choose to blow up :)

**Comment by liangfu** [comment]
I submitted a PR intend to add support for Mac. see PR #4260 
@rohitsaboo My personal solution to add OpenBLAS is to download the code from github, compile and install from the source code. After installation, the library would be installed into `/usr/local`, specifically at /usr/local/include and /usr/local/lib. Then after configuring the library with cmake targeting XCode to compile, everything goes fine without any unexpected error.
