### ISSUE TITLE
Error in RNN Sample

### ISSUE THREAD

**Issue by qmiwang** [dmlc/mxnet#646]
Maybe there is an error in lstm.py
line 186 : ` def set_rnn_inputs(m, X, begin):`
Given two sequences : `x1= [0, 1, 2, 3, 4]'`  and `x2= [5, 6, 7, 8, 9]'`
then we get X_batch: `X =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]'`, with batch_size is one.
After calling:  `set_rnn_inputs(m, X, 0)`
we get seq_data and seq_labels for sequence 1 (i.e. `x1`):
 `seq_data = [0, 1, 2, 3, 4]'` and  `seq_labels = [1, 2, 3, 4, 5]'`
Calling: `set_rnn_inputs(m, X, 5)`,
we get seq_data and seq_labels for sequence 2 (i.e. `x2`):
 `seq_data = [5, 6, 7, 8, 9]'` and  `seq_labels = [6, 7, 8, 9, 0]'`.

There are some problems in generated train_data for each sequence (i.e. `seq_data` and `seq_labels` ) after calling function `set_rnn_inputs`.
* Generated train_data of each sequence contains element which dose not exist in raw sequence. Actually, sequence `x1` dose not contain element `5` and sequence `x2` dose not contain element `0`.
* An wrong train-pair was generated for each sequence, `4 --->   5` and `9  --->   0`. In sequence prediction task, the end of each sequence dose not has a label and it should't be feed into the network anymore. 

Though those may do not influence the result, it is better to correct it !  
(`x1, x2, x` are column vectors )

**Comment by XericZephyr** [comment]
What's the actual sequence you mean? 
[0 1 2 3 4 5 6 7 8 9] or [0 5 1 6 2 7 3 8 4 9] ?

If you mean the first, I think the result is OK.

**Comment by qmiwang** [comment]
@XericZephyr I updated my words. And I am confused about the orgnization of the dataset (`X_train_batch`). May you please explain it again?

**Comment by XericZephyr** [comment]
I think you should first got an understanding of language model, which is just to predict the next word using the previous words. For example, in sequence [0, 1, 2, 3, 4], if input 1, also from previous information stored in `c`(cell state) and `h`(hidden state, also output), you get an ideal output 2.  

For organization of `X_train_batch`, let's take an example. 
Assume now you have a sequence [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].  And, we have `batch_size` == 2 and `seq_len` == 3. 
So first `drop_tail`, you will got 
```
1 6
2 7 
3 8 
4 9
5 10
```
(drop 11 in the sequence.)

Notice 1 and 5 forms a batch, and 2 and 6 is the label for this batch. (You can deduce the same for batch (2,6) (3,7) ...) 

Then the batch is truncated to fit the `seq_len`, e.g. 3. So the final `X_train_batch` is 
```
1 6
2 7
3 8
```
Every line forms a batch and the next line is the label to the batch. You might also be curious about the behavior of last line, i.e. What's the label of last line? The answer the first line, which I personally think is weird. 
For details, you might also check the code of `set_rnn_inputs`, which will help you gain better understanding.
