### ISSUE TITLE
How to use simple_bind for multiple GPUS

### ISSUE THREAD

**Issue by JACKHAHA363** [dmlc/mxnet#6476]
The following code gives this error. 
devs = [mx.gpu(0), mx.gpu(1)]
exe = net.simple_bind(ctx=devs, data=data_shape)

it gives error:
F0527 05:31:35.191905 23992 base.h:273] Check failed: r == str.length()-1 (6 vs. 7)

**Comment by jmacglashan** [comment]
I don't think you can bind on multiple devices? Maybe I'm wrong, but binding an executor from a symbol is the lowest-level execution machinery which asks to allocate memory on a specific device, in which case it wouldn't make sense to bind on multiple devices (that would mean you create multiple executors). 

If you want to spread training out over multiple devices, you should use a higher-level API like Module, or write your own higher-level interface that does the managing using tools like the KVStore.
