### ISSUE TITLE
Finetune error according tutorial: ValueError: Cannot find output that matches name "flatten0_output"

### ISSUE THREAD

**Issue by ysh329** [dmlc/mxnet#6483]
I want to finetune pretrained `inception-BN, squeezeNet, NIN, caffenet, vgg16, vgg19` models from model zoo, which happened this `ValueError`.

It's okay for finetuning `resnet, resneXt` models.

@kevinthesun @zackchase @sunilmallya @aileli :laughing: 
THanks a lot!

**Comment by sunbinbin1991** [comment]
I finetune a model have same question with you

**Comment by ysh329** [comment]
@sunbinbin1991 Have you added `flatten0_output` layer?

**Comment by ysh329** [comment]
@tornadomeet :sos:

**Comment by sunbinbin1991** [comment]
I find my problem, because I used caffenet to finetune my model, actually, this model have no layer"flatten0",so instead, change it with "drop7", that works, in a demo ,it said:

`layer_name: the layer name before the last fully-connected layer`

It depends, after change it ,it works ,good luck

**Comment by ysh329** [comment]
@sunbinbin1991 okay, my brother, Thanks.

**Comment by tornadomeet** [comment]
@ysh329 have you solved it ?

**Comment by ysh329** [comment]
Yes, Thanks a lot!

After attaining the `sym` varible using `load_checkpoint`, I used `sym.get_internals().list_outputs()` to check the outputs of each layer. And replace `flatten0` with `flatten_0`.
