### ISSUE TITLE
Build fails for Mxnet 0.10.0 in warp-ctc plugin

### ISSUE THREAD

**Issue by xinq2016** [dmlc/mxnet#6504]
## Environment info
Operating System: Ubuntu14.04

Compiler:

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.10.0

Or if installed from source: git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive

## Error Message:

In file included from plugin/warpctc/warpctc.cc:8:0:
plugin/warpctc/./warpctc-inl.h: In member function ‘virtual void mxnet::op::WarpCTCOp<xpu>::Backward(const mxnet::OpContext&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mxnet::TBlob>&, const std::vector<mxnet::TBlob>&)’:
plugin/warpctc/./warpctc-inl.h:124:14: error: ‘class mxnet::TBlob’ has no member named ‘dev_mask_’
     if (data.dev_mask_ == cpu::kDevMask) {
              ^
plugin/warpctc/./warpctc-inl.h:127:21: error: ‘class mxnet::TBlob’ has no member named ‘dev_mask_’
     } else if (data.dev_mask_ == gpu::kDevMask) {
                     ^
plugin/warpctc/./warpctc-inl.h:133:52: error: ‘class mxnet::TBlob’ has no member named ‘dev_mask_’
       LOG(FATAL) << "Unknown device type " << data.dev_mask_;
                                                    ^
plugin/warpctc/./warpctc-inl.h:152:14: error: ‘class mxnet::TBlob’ has no member named ‘dev_mask_’
     if (data.dev_mask_ == gpu::kDevMask) {
              ^
plugin/warpctc/./warpctc-inl.h:196:14: error: ‘class mxnet::TBlob’ has no member named ‘dev_mask_’
     if (data.dev_mask_ == cpu::kDevMask) {
              ^
plugin/warpctc/./warpctc-inl.h:198:21: error: ‘class mxnet::TBlob’ has no member named ‘dev_mask_’
     } else if (data.dev_mask_ == gpu::kDevMask) {
                     ^
make: *** [build/plugin/warpctc/warpctc.o] Error 1

## Minimum reproducible example
cd ~
git clone https://github.com/baidu-research/warp-ctc
cd warp-ctc
mkdir build
cd build
cmake ..
make
sudo make install

git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive
cd ~/mxnet
cp make/config.mk .

modify the config.mk as following:
USE_BLAS = openblas
USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda
USE_CUDNN = 1
WARPCTC_PATH = /home/nd/warp-ctc (which my wrap ctc installed)
MXNET_PLUGINS += plugin/warpctc/warpctc.mk

make

**I git clone the latest version of MXNet, make as above, and error. While there is no such error in the version of 0.9.5.** How can I fix it?

Many thanks
Xin.q.

**Comment by piiswrong** [comment]
ctc has been integrated into main package. See 

Meanwhile @ZihengJiang @sbodenstein lets fix the plugin

**Comment by ZihengJiang** [comment]
Should be fixed by https://github.com/dmlc/mxnet/pull/6511

**Comment by xinq2016** [comment]
@piiswrong @ZihengJiang 
so you mean that i dont need to add the warpctc path and plugin any more?
