### ISSUE TITLE
amalgamation, backtrace and backtrace_symbols not declared in scope

### ISSUE THREAD

**Issue by patricianing** [dmlc/mxnet#6518]
Have anyone seen the following issues? Is there an easy way to fix them? Thanks!

mxnet_predict-all.cc:646:50: error: ‘backtrace’ was not declared in this scope
     int nframes = backtrace(stack, MAX_STACK_SIZE);
                                                  ^
mxnet_predict-all.cc:648:51: error: ‘backtrace_symbols’ was not declared in this scope
     char **msgs = backtrace_symbols(stack, nframes);

**Comment by divamgupta** [comment]
Hi,

I am also facing the same issue. Did you manage to solve it?

**Comment by clnperez** [comment]
same here
