### ISSUE TITLE
Setting lr_multiplier for convolution layer

### ISSUE THREAD

**Issue by hondaathma** [dmlc/mxnet#6522]
Hi,
I have trouble setting lr_multiplier and decay_mult for convolution operation.

example:

`fc1_voc12_c3=mx.symbol.Convolution(name='fc1_voc12_c3',data=conv_feat,kernel,(3,3),no_bias=True,num_filter=num_classes,dilate=24)`

How can I set a different lr_mult for this layer alone in my Deeplab implementation?

**Comment by piiswrong** [comment]
weight=mx.sym.var('fc1_voc12_c3_weight', lr_mult=0.1)
fc1_voc12_c3=mx.symbol.Convolution(name='fc1_voc12_c3',data=conv_feat, weight=weight, kernel,(3,3),no_bias=True,num_filter=num_classes,dilate=24)
