### ISSUE TITLE
[Pull Requests] Hide gamma, beta, var, mean in graph visualization

### ISSUE THREAD

**Issue by Lyken17** [dmlc/mxnet#6524]
Hi all

After ResNet, Batch Normalization becomes quite popular and is widely used recently. However, for visualization, I found parameters `bn_gamma`, `bn_beta`, `bn_var`, `bn_mean` occupy a lot of space while providing little information.  [plot_complex.pdf](https://github.com/dmlc/mxnet/files/1043750/plot_complex.pdf) And it also made visualization of some large networks totally unreadable [plot_complex_resnet.pdf](https://github.com/dmlc/mxnet/files/1043767/plot_complex_resnet.pdf)

During my experiments, BN is always treated as a normal layer (like a convolution). Designers usually does not focus on beta/gamma/mean/var, especially on visualization. I suggest to hide these parameters during visualization.

Examples after modification
[plot_clean.pdf](https://github.com/dmlc/mxnet/files/1043765/plot_clean.pdf)
[plot_clean_resnet.pdf](https://github.com/dmlc/mxnet/files/1043776/plot_clean_resnet.pdf)

I have submitted a [pull request](https://github.com/dmlc/mxnet/pull/6523) for this issue.

**Comment by piiswrong** [comment]
Thanks for PR.
