### ISSUE TITLE
MXNET 0.10.0 "endsWith" not found

### ISSUE THREAD

**Issue by grant0321** [dmlc/mxnet#6525]
I'm using MXNET 0.10.0 on Linux Mint (with GPU) and get the following error when running a CNN model using R:

Error in mx.model.init.params(symbol, input.shape, output.shape, initializer,  : 
  could not find function "endsWith"

I've tried downloading and recompiling the MXNET code over the past couple of days with the same results.

**Comment by thirdwing** [comment]
I guess you are using R 3.2. `endsWith` was introduced in R 3.3.

I will fix this.
