### ISSUE TITLE
Missing parent artifacts for mxnet-scala with Scala 2.11

### ISSUE THREAD

**Issue by winitzki** [dmlc/mxnet#6531]
Creating a Scala project with Scala 2.11 depending on mxnet 0.9.3a fails because of missing artifacts.

build.sbt has:

```
libraryDependencies ++= Seq(
...
  , "ml.dmlc.mxnet" % "mxnet-core_2.11" % "0.9.3a"
)
```

Error:

```
	module not found: ml.dmlc.mxnet#mxnet-core_2.11;0.9.3a
[warn] ==== local: tried
[warn]   <user home>/.ivy2/local/ml.dmlc.mxnet/mxnet-parent_2.11/0.9.3a/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/ml/dmlc/mxnet/mxnet-parent_2.11/0.9.3a/mxnet-parent_2.11-0.9.3a.pom
```

Looking at the Maven page http://search.maven.org/#search%7Cga%7C1%7Cmxnet shows that the artifacts mxnet-parent_2.10 and mxnet-full-parent_2.10 are published, but no "parent" artifacts with Scala 2.11 are published.

Trying to build the mxnet-scala package from source (`make scalapkg`) also fails with similar error messages,

```
[ERROR] The build could not read 8 projects -> [Help 1]
[ERROR]
[ERROR]   The project ml.dmlc.mxnet:mxnet-init_2.11:0.10.1-SNAPSHOT (<user home>mxnet/scala-package/init/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for ml.dmlc.mxnet:mxnet-init_2.11:0.10.1-SNAPSHOT: Could not find artifact ml.dmlc.mxnet:mxnet-parent_2.11:pom:0.10.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project ml.dmlc.mxnet:mxnet-scala-init-native-parent:0.10.1-SNAPSHOT (<user home>mxnet/scala-package/init-native/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for ml.dmlc.mxnet:mxnet-scala-init-native-parent:0.10.1-SNAPSHOT: Could not find artifact ml.dmlc.mxnet:mxnet-parent_2.11:pom:0.10.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 11 -> [Help 2]
[ERROR]
[ERROR]   The project ml.dmlc.mxnet:mxnet-macros_2.11:0.10.1-SNAPSHOT (<user home>/mxnet/scala-package/macros/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for ml.dmlc.mxnet:mxnet-macros_2.11:0.10.1-SNAPSHOT: Could not find artifact ml.dmlc.mxnet:mxnet-parent_2.11:pom:0.10.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 11 -> [Help 2]
```

It appears that the scala-2.11 artifacts require some "parent" `pom`s to be published, which were (by mistake?) not published to maven.

What would be desirable - to have Scala 2.11 and Scala 2.12 artifacts published and usable.

As another wish - to have sbt-based scala build file, so that the mxnet-scala project could be built separately, imported into IntelliJ with SBT, etc. Right now I can't seem to be able to do this.

**Comment by javelinjs** [comment]
I'll upload the missing artifacts for 2.11 today. Scala 2.12 will be supported soon - tests required.

**Comment by winitzki** [comment]
I'd be interested in fixing this myself in the Scala package, if I only knew more about the nature of the problem. Please let me know if I can be of help. For instance, would it be possible to have a build.sbt file so that the Scala package can be loaded into IntelliJ  for building and development?

**Comment by javelinjs** [comment]
Please try again. It should have worked now.

**Comment by winitzki** [comment]
Works now! Thank you. Can I help in any way to move towards Scala 2.12 and 0.10 release for scala package? You can close the issue if you think there is nothing more to do.

**Comment by winitzki** [comment]
Would it be possible to update the Scala artifacts to 0.10 so that they contain the contrib package and and possibly fix another problem I'm having? https://github.com/dmlc/mxnet/issues/6554

**Comment by javelinjs** [comment]
I'll do a check to make sure the scala package is consistent with the python api. The 0.10 jar will be released soon. Close this issue for now.
