### ISSUE TITLE
[R] require R >= 3.3.0

### ISSUE THREAD

**Issue by thirdwing** [dmlc/mxnet#6539]
I want to get opinions from R users on this.

Do you think it is reasonable to require R >= 3.3.0?

There are two reasons I want to set the requirement:

(1) currently we host the pre-built R package on github: https://github.com/dmlc/drat/tree/gh-pages/bin/macosx/el-capitan/contrib

Less packaging work if we just support the latest two versions of R

(2) some utility functions we wrote by ourselves have been provide by the `base` package from R 3.3

**Comment by thirdwing** [comment]
@hetong007 @jeremiedb @miguelgfierro @jiajiechen @RogerBorras  @paulsendavidjay

**Comment by paulsendavidjay** [comment]
I think it's reasonable to do so at this point.

**Comment by hetong007** [comment]
I think it makes sense to switch to 3.3.0

**Comment by jeremiedb** [comment]
I'm also comfortable with R >= 3.3

**Comment by miguelgfierro** [comment]
I also think it makes sense

**Comment by RogerBorras** [comment]
Yes, I agree that this is very reasonable. Thanks @thirdwing and coauthors for this amazing R library.

**Comment by thirdwing** [comment]
Close by #6840
