### ISSUE TITLE
WindowsError in python 2.7 (Anaconda) after cmake/VS2013 compilation successful

### ISSUE THREAD

**Issue by Strateus** [dmlc/mxnet#655]
I have Windows 7 64.
I modified base.py to print the path:

```
>>> import mxnet as mx
C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\libmxnet.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 44, in <module>
    _LIB = _load_lib()
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 36, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Anaconda\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError:  [Error 193] %1 is not a valid Win32 application
>>> 
```

I dont see any documentation warnings that i need to use Python 3.0+. Cmake though warned that he wasnt able to find python 3+ binaries. And Ubuntu version works good on python 2.7.10 (Anaconda as well). Is windows version of mxnet is for Python 3 only?

**Comment by Strateus** [comment]
Any help please?

**Comment by tqchen** [comment]
This seems to be same error @thirdwing encountered, which happens to some windows machine but we do not know why, @hjk41 do u have any idea on this?

**Comment by thirdwing** [comment]
Exactly the same error on my machine.

**Comment by yajiedesign** [comment]
you Anaconda is 64bit? and you compilation mxnet with 64bit?

**Comment by Strateus** [comment]
Python 2.7.10 |Anaconda 2.3.0 (32-bit)| (default, Nov  7 2015, 13:29:20) [MSC v.1500 32 bit (Intel)] on win32
mxnet compilation is 64 bit, i used Cmake and VS2013, there is no 32 bit option. How can i make 32 bit compilation of mxnet?

**Comment by hjk41** [comment]
This seems to be a bug introduced recently. I tried with x64 build on
Windows 10 several weeks ago and it worked fine. Now I have the same error.
I will try to figure out the problem.

On Sat, Nov 21, 2015 at 2:24 PM, Igor S <notifications@github.com> wrote:

> Python 2.7.10 |Anaconda 2.3.0 (32-bit)| (default, Nov 7 2015, 13:29:20)
> [MSC v.1500 32 bit (Intel)] on win32
> mxnet compilation is 64 bit, i used Cmake and VS2013, there is no 32 bit
> option. How can i make 32 bit compilation of mxnet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/655#issuecomment-158594570>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
@Strateus Could you try the latest version, or download the binary distribution from https://github.com/dmlc/mxnet/releases/tag/weekly_binary_build? The bug was somehow resolved on my machine, though I am not sure by which commit.

**Comment by Strateus** [comment]
Now i have some error during compilation: 
```
Error	196	error C2064: term does not evaluate to a function taking 2 arguments	C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xrefwrap	283	1	mxnet
```
Any suggestions?

**Comment by hjk41** [comment]
This is a bug bring in recently. Fixing...


On Thu, Nov 26, 2015 at 7:14 PM, Igor S <notifications@github.com> wrote:

> Now i have some error during compilation:
>
> Error   196 error C2064: term does not evaluate to a function taking 2 arguments    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xrefwrap 283 1   mxnet
>
> Any suggestions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/655#issuecomment-159885212>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
PR #731 (https://github.com/dmlc/mxnet/pull/731) should fix this. Please
wait till it is merged.

On Fri, Nov 27, 2015 at 10:56 AM, Chuntao HONG <chuntao.hong@gmail.com>
wrote:

> This is a bug bring in recently. Fixing...
>
>
> On Thu, Nov 26, 2015 at 7:14 PM, Igor S <notifications@github.com> wrote:
>
>> Now i have some error during compilation:
>>
>> Error   196 error C2064: term does not evaluate to a function taking 2 arguments    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xrefwrap 283 1   mxnet
>>
>> Any suggestions?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dmlc/mxnet/issues/655#issuecomment-159885212>.
>>
>
>
>
> --
> HONG Chuntao
> System Research Group
> Microsoft Research Asia
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
OK. it is merged. Please have another try. :-)

On Fri, Nov 27, 2015 at 11:10 AM, Chuntao HONG <chuntao.hong@gmail.com>
wrote:

> PR #731 (https://github.com/dmlc/mxnet/pull/731) should fix this. Please
> wait till it is merged.
>
> On Fri, Nov 27, 2015 at 10:56 AM, Chuntao HONG <chuntao.hong@gmail.com>
> wrote:
>
>> This is a bug bring in recently. Fixing...
>>
>>
>> On Thu, Nov 26, 2015 at 7:14 PM, Igor S <notifications@github.com> wrote:
>>
>>> Now i have some error during compilation:
>>>
>>> Error   196 error C2064: term does not evaluate to a function taking 2 arguments    C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xrefwrap 283 1   mxnet
>>>
>>> Any suggestions?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/dmlc/mxnet/issues/655#issuecomment-159885212>.
>>>
>>
>>
>>
>> --
>> HONG Chuntao
>> System Research Group
>> Microsoft Research Asia
>>
>
>
>
> --
> HONG Chuntao
> System Research Group
> Microsoft Research Asia
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by Strateus** [comment]
I have same issue now as at the beginning:
```
WindowsError:  [Error 193] %1 is not a valid Win32 application
```
I just copied new dll from build/Release to previous mxnet python installation, or i need to reinstall python build as well?

**Comment by hjk41** [comment]
Yes. Please reinstall.

On Fri, Nov 27, 2015 at 3:21 PM, Igor S <notifications@github.com> wrote:

> I have same issue now as at the beginning:
>
> WindowsError:  [Error 193] %1 is not a valid Win32 application
>
> I just copied new dll from build/Release to previous mxnet python
> installation, or i need to reinstall python build as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/655#issuecomment-160057864>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by Strateus** [comment]
Now its very strange, i tried to import it twice in a row and there are different errors:
```
>>> import mxnet
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Anaconda\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Anaconda\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError:  [Error 193] %1 is not a valid Win32 application
>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>

>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 10, in <module>
    from . import libinfo
ImportError: cannot import name libinfo
>>> 
```

**Comment by Strateus** [comment]
btw im cloning master, maybe i need to clone some branch?

**Comment by hjk41** [comment]
I am using master. Windows 10 with Python 3.4 x86_64.

Is it possible for you to try Python 3.4? I cannot install mxnet with
python 2.7 on my machine. It requires vcpython27, which only supports
windows 7/8/8.1.   @_@

On Fri, Nov 27, 2015 at 3:31 PM, Igor S <notifications@github.com> wrote:

> btw im cloning master, maybe i need to clone some branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/655#issuecomment-160058881>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
a probably stupid question: are you using 32bit or 64bit python? You will
need 64bit python to use 64bit mxnet.

On Fri, Nov 27, 2015 at 4:53 PM, Chuntao HONG <chuntao.hong@gmail.com>
wrote:

> I am using master. Windows 10 with Python 3.4 x86_64.
>
> Is it possible for you to try Python 3.4? I cannot install mxnet with
> python 2.7 on my machine. It requires vcpython27, which only supports
> windows 7/8/8.1.   @_@
>
> On Fri, Nov 27, 2015 at 3:31 PM, Igor S <notifications@github.com> wrote:
>
>> btw im cloning master, maybe i need to clone some branch?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dmlc/mxnet/issues/655#issuecomment-160058881>.
>>
>
>
>
> --
> HONG Chuntao
> System Research Group
> Microsoft Research Asia
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by Strateus** [comment]
i replied to that earlier - im using 32 bit python. So there is no way to install on 32 bit python under windows?

**Comment by hjk41** [comment]
The pre-built binary distribution is 64bit. So you will need 64bit python
to use that package. I think it is also possible to built 32bit mxnet and
use it in 32bit python. Let me have a try.

On Fri, Nov 27, 2015 at 8:16 PM, Igor S <notifications@github.com> wrote:

> i replied to that earlier - im using 32 bit python. So there is no way to
> install on 32 bit python under windows?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/655#issuecomment-160127787>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by li-haoran** [comment]
i also meet the same question:
import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "D:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "D:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "D:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "D:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] 

i use the VS2013 and PTVS, after i build successfully.  I follow the installation guide,and i use "python setup.py install".But i can't import the mxnet.

**Comment by hjk41** [comment]
haoran, are you using 32bit Python or 64bit?

On Thu, Dec 10, 2015 at 11:36 AM, li-haoran <notifications@github.com>
wrote:

> i also meet the same question:
> import mxnet as mx
> Traceback (most recent call last):
> File "", line 1, in
> File
> "D:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet__init__.py",
> line 7, in
> from .base import MXNetError
> File "D:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py",
> line 43, in
>
>
>
> *LIB = load_lib() File
> "D:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line
> 35, in _load_lib lib = ctypes.cdll.LoadLibrary(lib_path[0]) File
> "D:\Python27\lib\ctypes__init*.py", line 443, in LoadLibrary
> return self.
> *dlltype(name) File "D:\Python27\lib\ctypes__init_*.py", line 365, in
> *init*
> self._handle = _dlopen(self._name, mode)
> WindowsError: [Error 126]
>
> i use the VS2013 and PTVS, after i build successfully. I follow the
> installation guide,and i use "python setup.py install".But i can't import
> the mxnet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/655#issuecomment-163477238>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by li-haoran** [comment]
i use 64.bit python 2.7.10.

**Comment by tqchen** [comment]
closing due to inactive status, feel free to reopen if there is update

**Comment by K-Wu** [comment]
I'm encountering the same problem
import mxnet as mx

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import mxnet as mx
  File "C:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "C:\Python27\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "C:\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

I'm using python 2.7.10 64 on win10 x64.

**Comment by cupermanrose** [comment]
@tqchen @K-Wu I had the same problem.Did you have any solution?

**Comment by K-Wu** [comment]
@cupermanrose haven't so far. Still waiting for the official fixing.

**Comment by hjk41** [comment]
Guys, I don't really have a clue here. Are you all using Windows 7? Could
that have caused the problem?

On Tue, Dec 22, 2015 at 11:59 AM, K-Wu <notifications@github.com> wrote:

> @cupermanrose <https://github.com/cupermanrose> haven't so far. Still
> waiting for the official fixing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/655#issuecomment-166499850>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by cupermanrose** [comment]
@hjk41  I have built the mxnet(USE_DIST_KVSTORE) and installed python package on some machines successfully.But the error 126 occurred when I import mxnet.Maybe I should wait for the official fixing about error 126?

**Comment by hjk41** [comment]
Could you try to install MXNET on a short path, say d:\mxnet? And make sure
libmxnet.dll is in your PATH.

On Tue, Dec 22, 2015 at 2:08 PM, cupermanrose <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41> I have built the
> mxnet(USE_DIST_KVSTORE) and installed python package on some machines
> successfully.But the error 126 occurred when I import mxnet.Maybe I should
> wait for the official fixing about error 126?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/655#issuecomment-166521363>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by yajiedesign** [comment]
@K-Wu  @cupermanrose put depneds dll in python.exe path.like openv_*.dll. zmq *.dll

**Comment by cupermanrose** [comment]
@yajiedesign I put libopenblas.dll libzmq-v120-mt-4_0_4.dll opencv_world300.dll in python.exe path still error.

**Comment by yajiedesign** [comment]
@cupermanrose  OPENCV_CORE300.DLL  OPENCV_IMGPROC300.DLL OPENCV_IMGCODECS300.DLL

**Comment by cupermanrose** [comment]
@yajiedesign My opencv has only opencv_world300.dll opencv_world300d.dll and opencv_ffmpeg300_64.dll.

**Comment by li-haoran** [comment]
i add the build path(...mypath/x64/release/) to my pc's environment path,then it works.

**Comment by cupermanrose** [comment]
@Strateus I met the same problem.I tried to import mxnet twice ,the first error is error 126 The specified module could not be found and the second error is cannot import name libinfo.Have you fixed it?

**Comment by Strateus** [comment]
Im not using mxnet now, it does not support 32 bit Python under Windows, only 64bit.

**Comment by cupermanrose** [comment]
@Strateus I think I fix the problem.Put the libmxnet.ll to mxnet\python\mxnet before installing python package.

**Comment by lancerts** [comment]
always get ,the first error is error 126 The specified module could not be found and the second error is cannot import name libinfo...

**Comment by horsepurve** [comment]
I had the same problem, and finally I figured it out. I used Dependency walker to analyze the .dll and found many missing API-MS-WIN-CORE DLLs. Then I recalled that before compiling mxnet, I firstly had to install MS C++ Compiler Nov 2013 CTP, which, however, couldn't be installed until the conflicting Visual C++ Redistributable 2013 were uninstalled. Hence, I reinstalled it and collected all the dependent DLLs. It worked.

**Comment by fengfengyuyu** [comment]
#  [Error 193] %1 is not a valid Win32 application

i also met similar problem. OS: win7 64;python:anaconda Py2.7 64bit 
i just tried 20160309_win10_x64_gpu.7z and 20151209_win64_gpu.7z  and ocurred the same error.
is there any method to solve it?
`
WindowsError                              Traceback (most recent call last)
<ipython-input-1-cb88d04c42ec> in <module>()
----> 1 import mxnet as mx

C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\__init__.py in <module>()
      5 
      6 from .context import Context, current_context, cpu, gpu
----> 7 from .base import MXNetError
      8 from . import base
      9 from . import ndarray

C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py in <module>()
     41 __version__ = libinfo.__version__
     42 # library instance of mxnet
---> 43 _LIB = _load_lib()
     44 
     45 # type definitions

C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py in _load_lib()
     33     """Load libary by searching possible path."""
     34     lib_path = libinfo.find_lib_path()
---> 35     lib = ctypes.cdll.LoadLibrary(lib_path[0])
     36     # DMatrix functions
     37     lib.MXGetLastError.restype = ctypes.c_char_p

C:\Anaconda\lib\ctypes\__init__.pyc in LoadLibrary(self, name)
    441 
    442     def LoadLibrary(self, name):
--> 443         return self._dlltype(name)
    444 
    445 cdll = LibraryLoader(CDLL)

C:\Anaconda\lib\ctypes\__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    363 
    364         if handle is None:
--> 365             self._handle = _dlopen(self._name, mode)
    366         else:
    367             self._handle = handle
WindowsError:  [Error 193] %1 is not a valid Win32 application`

**Comment by bluekingdom** [comment]
I met this problem too. And then fix by add
1) mxnet root path, 
2)all dependent dll path, 
to PATH. 
It work!
