### ISSUE TITLE
No Scala support for _contrib_CTCLoss

### ISSUE THREAD

**Issue by winitzki** [dmlc/mxnet#6554]
Trying to use MXNet with Scala and getting an error while loading a trained model that uses CTCLoss:

Failed loading Op _contrib_ctc_loss0 of type _contrib_CTCLoss: [14:00:15] src/core/op.cc:55: Check failed: op != nullptr Operator _contrib_CTCLoss is not registered

I noticed that CTCLoss was introduced in 0.10 while the Scala packages are published only at version 0.9.3a. Perhaps that's the problem, or perhaps something else must be done to be able to use _contrib_CTCLoss? I'd be interested in fixing this myself in the Scala package, if I only knew more about the nature of the problem.

**Comment by Ldpe2G** [comment]
@winitzki Scalapkg actually supports CTCLoss. All the operators starts with _contrib_ are under the
contrib package, so you can use the CTCLoss by 
```scala
import ml.dmlc.mxnet._
val ctcLoss = contrib.Symbol.CTCLOSS()()(Map(...))
```

And the Scalapkg uses macro to auto generate the symbol. So no needs to add symbols by hand. You can refer to #3217 for more details.

**Comment by winitzki** [comment]
@Ldpe2G  my problem is that I'm actually loading a model from JSON & param files, and the model was trained in Python / mxnet. I am having this error message while loading a model that uses CTCLoss. The Python API seems to use CTCLoss without any trouble. But when I do `Model.loadCheckpoint(prefix, epoch)` it gives me the error shown above... I have the same code working (loading a trained model from JSON  & param files) with the MNIST test that does not use CTCLoss.

**Comment by winitzki** [comment]
Let me try to include the `mxnet-macros` package, maybe that will help.

Where do I get `ml.dmlc.mxnet.contrib`? I don't see any JAR artifact that has that `contrib` package!

**Comment by winitzki** [comment]
So, maybe the problem is that the current 0.9.3a JAR artifact `mxnet-core` does not contain the `contrib` package. The files in `scala-package/core/src/main/scala/ml/dmlc/mxnet/contrib/` were added on Apr. 11, whereas the JAR artifact `mxnet-core` was published on Mar. 26. So, that's why I don't see them, and perhaps that's why my Scala code can't use CTCLoss.

Would it be possible to update the Scala artifacts to 0.10 so that they contain the `contrib` package and and possibly fix this problem?
(I am having multiple problems compiling the mxnet source under OS X, so I can't test whether it's the real root of the problem.)

**Comment by Ldpe2G** [comment]
@winitzki Would you mind to provide the trained model and json file so I can do some test with the lastest scala-pkg to see what cause this?

**Comment by winitzki** [comment]
Unfortunately we are not allowed to provide this data to third parties... **However**, I tried further to figure out what the problem is, and I think the only missing thing for us is a 0.10 release of the mxnet `jni` library.

I was able to compile `mxnet` successfully on an OS X, but only after I changed a couple of things in the build settings while following `docs/get_started/osx_setup.md`.

One of these changes was, unfortunately, that I had to disable OpenCV. This makes my build unusable for our purposes. Another was that I had to change g++ to g++-7, gcc to gcc-7, and linker flags in `scala-package/native/osx-x86_64-cpu/pom.xml` and `scala-package/init-native/osx-x86_64/pom.xml` from `-force_load` to `-Wl,-force_load,` in three places.

The result is a full mxnet/scala package with 0.10.1-SNAPSHOT version that I can now use to load the json file and param file for our trained model that uses CTC Loss. So, indeed if you could just build and publish the latest 0.10 release for scala package with supported platforms (OSX and Linux64), that would fully solve my problem.

In fact, the problem would be fully solved and we would be unblocked if you could just compile the jni library `libmxnet-scala-osx-x86_64-cpu.jnilib` for the 0.10 release on OSX non-gpu. That's the only thing I can't compile correctly so far. (Linux compilation works fine!) I would really appreciate your help since it's probably quite easy for you to compile this.

**Comment by Ldpe2G** [comment]
@javelinjs

**Comment by javelinjs** [comment]
As I mentioned in #6531 I need to do a check to make sure the scala package is consistent with the python api. I'll publish 0.10 soon, probably on this weekend. Sorry for the inconvenience.

**Comment by javelinjs** [comment]
0.10.0-SNAPSHOT has been published. Have a try please.

**Comment by winitzki** [comment]
The issue with CTC Loss is now resolved (model can be loaded) when using the snapshot artifact under OS X,

```
libraryDependencies += "ml.dmlc.mxnet" % "mxnet-full_2.11-osx-x86_64-cpu" % "0.10.0-SNAPSHOT"
```

Thank you for a quick response!

**Comment by javelinjs** [comment]
You're welcome. Close this issue for now.
