### ISSUE TITLE
Use iterations directly instead of epoch_size

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#656]
From the early experiences of training DL models https://github.com/BVLC/caffe/issues/59#issuecomment-33399073, most of the time epoch size, i.e. the number of samples, is a totally unnecessary and annoying burden for the users to maintain. It's much more natural to use iterations directly and automatically go to the beginning at the end of the dataset. At least it should become optional and secondary to iterations.

**Comment by jermainewang** [comment]
I think we already support that. The `NDArrayIter` could support `last_batch_mode` as [`roll_over`](https://github.com/dmlc/mxnet/blob/master/python/mxnet/io.py#L140) which may be what you want?

**Comment by futurely** [comment]
To be more clear, I mean these [`epoch_size`](https://github.com/dmlc/mxnet/search?utf8=%E2%9C%93&q=epoch_size) should be replaced by iterations.

**Comment by tqchen** [comment]
These are optional parameters, which are only needed for consensus purpose for distributed training. For single machine, num_epoch is used

**Comment by futurely** [comment]
The document should be more explicit about the usage of user facing parameters.

**Comment by tqchen** [comment]
Yes, you are absolutely right. The best way is to improve it when we find things that can be improved, so it can always be better? It would be great if you can open a PR to contribute your wisdom into this case and improve the docstring so people won't get confused later

Thanks!

**Comment by futurely** [comment]
This example is just a special case of the bigger issue in https://github.com/dmlc/mxnet/issues/657.

**Comment by tqchen** [comment]
Again it will be great to have your contribution in opening a PR to help making mxnet better. I see improvement even w.r.t. to this issue is great for all of us, and such steps of changes can again big momentum easier, with your wisdom and code into it
