### ISSUE TITLE
Abstract the train_model example into a generic tool

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#657]
The [lastest](https://github.com/dmlc/mxnet/tree/0e08b173c0545b0db92335fad3ed4b482f4a3c98/example/image-classification) image classifcation examples are more re-usable than the older versions. It is helpful to further evolve them into more generic tools to train any model on any dataset.

The use case is users can start training by passing in some necessary parameters such as symbol_network, data_dir, train_rec, val_rec, learning_rate, and model_prefix etc. on the command line or in configuration files without writing a single line of code. Dataset parameters and optimization parameters should be in separate files since it's very common to try different training parameters on the same dataset. The changes would greatly improve the user accessibility, reduce the overhead of setting up experiments and speed up the innovations.

**Comment by jermainewang** [comment]
Good suggestion. Let me summarize what you suggests:
* Separate dataset parameters and optimization parameters with network configuration.
* Allow command line (or separate config file) to accept dataset/optimization parameters for easy use.
Do I understand your points?

Also, I think we should unify the semantics of command line arguments of our applications, so once users learn how to use one application, they know how to use them all. Maybe we could do it together with your efforts to re-organizing applications @mli ?

**Comment by futurely** [comment]
Yes, those requirements are exactly what the users need in daily use. Thanks for your interest!

**Comment by tqchen** [comment]
partly done in https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_imagenet.py
