### ISSUE TITLE
Saving predicted outputs in MXNetR

### ISSUE THREAD

**Issue by nnguyen24** [dmlc/mxnet#6570]
Hello, I have a question regarding the usage of MXNetR. After each training epoch, I want to save the predicted values using training inputs and testing inputs into a file so that I can plot them later on. I tried to customize my callback function but found no way to get access to the predicted outputs generated during the training process. I am quite new to MXNetR so it would be great if you can give me some general ideas of how I should do this. 

P/S: I am aware that MXNetR allows the user to save the model after each training epoch. I can save all models generated during training and then predict the outputs with these models. However, if the number of models is large, this method would consume a lot of space.

**Comment by nnguyen24** [comment]
Hello, I have a question regarding the usage of MXNetR. After each training epoch, I want to save the predicted values using training inputs and testing inputs into a file so that I can plot them later on. I tried to customize my callback function but found no way to get access to the predicted outputs generated during the training process. I am quite new to MXNetR so it would be great if you can give me some general ideas of how I should do this. 

P/S: I am aware that MXNetR allows the user to save the model after each training epoch. I can save all models generated during training and then predict the outputs with these models. However, if the number of models is large, this method would consume a lot of space.

**Comment by thirdwing** [comment]
I think this can be done in a callback function.

In `function(iteration, nbatch, env, verbose)`, the `env` is an environment, where you can store your results.

**Comment by kimtang** [comment]
You can modify the metric function to save the predicted outputs. For example in the accuracy function:
`mx.metric.accuracy <- mx.metric.custom("accuracy", function(label, pred) {
  ypred = max.col(t(as.array(pred)), tie="first")
  return(sum((as.array(label) + 1) == ypred) / length(label))
})`

the label and predicted data are passed and you can implement the saving feature here.

**Comment by nnguyen24** [comment]
@kimtang : Thank you, it does help.
