### ISSUE TITLE
SSD example fails to run after "backward headgrads and detach" commit

### ISSUE THREAD

**Issue by flyashi** [dmlc/mxnet#6578]
## Environment info
Operating System:
Ubuntu 16.04.1

Compiler:
gcc

Package used (Python/R/Scala/Julia):
Python

MXNet version:
see git-bisect details below

Python version and distribution:
Python 2.7.6, from apt

## Error Message:
Please paste the full error message, including stack trace.

    [16:32:06] /home/ubuntu/src/mxnet/dmlc-core/include/dmlc/logging.h:304: [16:32:06] src/core/symbolic.cc:72: Symbol.ComposeKeyword argument name anchors not found.
    Candidate arguments:
    	[0]cls_prob
    	[1]loc_pred
    	[2]anchor

    Stack trace returned 10 entries:
    [bt] (0) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f588da225bc]
    [bt] (1) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm23KeywordArgumentMismatchEPKcRKSt6vectorISsSaISsEERKN4dmlc10array_viewISsEE+0x22a) [0x7f588f54715a]
    [bt] (2)     /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm6Symbol7ComposeERKN4dmlc10array_viewIPKS0_EERKSt13unordered_mapISsS4_St4hashISsESt8equal_toISsESaISt4pairIKSsS4_EEERSE_+0x128f) [0x7f588f543d0f]
    [bt] (3) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(NNSymbolCompose+0x31b) [0x7f588f5308db]
    [bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f593905eadc]
    [bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7f593905e40c]
    [bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48e) [0x7f59392755fe]
    [bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x15f9e) [0x7f5939276f9e]
    [bt] (8) python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
    [bt] (9) python() [0x568b3a]

    Traceback (most recent call last):
      File "demo.py", line 99, in <module>
        ctx, args.nms_thresh, args.force_nms)
      File "demo.py", line 40, in get_detector
        .get_symbol(len(CLASSES), nms_thresh, force_nms)
      File "/home/ubuntu/src/mxnet/example/ssd/symbol/symbol_vgg16_ssd_300.py", line 179, in get_symbol
        net = get_symbol_train(num_classes)
      File "/home/ubuntu/src/mxnet/example/ssd/symbol/symbol_vgg16_ssd_300.py", line 150, in get_symbol_train
        variances=(0.1, 0.1, 0.2, 0.2), nms_topk=nms_topk)
      File "<string>", line 47, in _contrib_MultiBoxDetection
      File "/home/ubuntu/src/mxnet/python/mxnet/_ctypes/symbol.py", line 136, in _symbol_creator
        s._compose(name=name, **kwargs)
      File "/home/ubuntu/src/mxnet/python/mxnet/symbol.py", line 419, in _compose
        self.handle, name, num_args, keys, args))
      File "/home/ubuntu/src/mxnet/python/mxnet/base.py", line 85, in check_call
        raise MXNetError(py_str(_LIB.MXGetLastError()))
    mxnet.base.MXNetError: [16:32:06] src/core/symbolic.cc:72: Symbol.ComposeKeyword argument name anchors not found.
    Candidate arguments:
    	[0]cls_prob
    	[1]loc_pred
    	[2]anchor

    Stack trace returned 10 entries:
    [bt] (0) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f588da225bc]
    [bt] (1) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm23KeywordArgumentMismatchEPKcRKSt6vectorISsSaISsEERKN4dmlc10array_viewISsEE+0x22a) [0x7f588f54715a]
    [bt] (2) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm6Symbol7ComposeERKN4dmlc10array_viewIPKS0_EERKSt13unordered_mapISsS4_St4hashISsESt8equal_toISsESaISt4pairIKSsS4_EEERSE_+0x128f) [0x7f588f543d0f]
    [bt] (3) /home/ubuntu/src/mxnet/python/mxnet/../../lib/libmxnet.so(NNSymbolCompose+0x31b) [0x7f588f5308db]
    [bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f593905eadc]
    [bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7f593905e40c]
    [bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48e) [0x7f59392755fe]
    [bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x15f9e) [0x7f5939276f9e]
    [bt] (8) python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
    [bt] (9) python() [0x568b3a]

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. git checkout; git submodule update; make, python setup.py install, export PYTHONPATH=..., etc.
2. in example/ssd; in demo - run python script to download demo images; in model - download and extract pre-trained model
3. python demo.py

## What have you tried to solve it?
git bisect leads to:

    32ced389c1e52e2874c75ef75b09973835b15138 is the first bad commit
    commit 32ced389c1e52e2874c75ef75b09973835b15138
    Author: Eric Junyuan Xie <piiswrong@users.noreply.github.com>
    Date:   Tue May 30 19:02:08 2017 -0700
    
    backward headgrads and detach (#6332)
        
    lint
    
    fix
    
    add updated grad
    
    add retain grad
    
    exclude reduce
    
    cpp cached invoke
    
    cached symbol
    
    move symbol init module
    
    symbol cython
    
    udpate
    
    updated_grad->fresh_grad
    
    fix
    
    * fix

    :040000 040000 adaeb00044a3e43a3385b05a6889cff069950da9 f167af6857f2e03362d6b60758ceb1f1c54a89cd M	include
    :160000 160000 93072dc8733aa2a89459ecf16413d96ad0b998db 7796ac76ccea1fba31afc32056c83f6da38b6c57 M	nnvm
    :040000 040000 4dd3013b83ee48214962301d6fb1fcdf0c611c5d 604df134541a3649ffce3f6ab644c00a7b4ba528 M	python
    :040000 040000 6b9680f27430bb69f707a833a427c65fce7690bd ce3ee023e5271961230b8be9df855293b72e8e4f M	src
    :040000 040000 3c36e17186e599db7ea9523c7dc4ca22834e48ae 082e2c610ef3883b3b9e37b8f63fddb9fbab1cdc M	tests

That's [this commit](https://github.com/dmlc/mxnet/commit/32ced389c1e52e2874c75ef75b09973835b15138).

**Comment by piiswrong** [comment]
Thanks for reporting. SHould be fixed by this: https://github.com/dmlc/mxnet/commit/b2e7c3aad0eee3af8aab22fc0ec24fbf530a5bd2

**Comment by flyashi** [comment]
Confirmed fixed - thank you!
