### ISSUE TITLE
Checkpoint every some iterations

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#658]
`mxnet.callback.do_checkpoint` is usable as the epoch_end_callback. It is desirable to checkpoint more frequently since the model might reach the peak performance in the middle of an epoch.
```
def do_checkpoint(prefix, iters):
    def _callback(iter_no, sym, arg, aux):
        """The checkpoint function."""
        iters = max(1, iters)
        if iter_no > 0 and iter_no % iters == 0:
            save_checkpoint(prefix, iter_no + 1, sym, arg, aux)
    return _callback
```

**Comment by jermainewang** [comment]
Hi,

I think you could do this using `batch_end_callback`. One example is the [`Speedmetor` ](https://github.com/dmlc/mxnet/blob/master/python/mxnet/callback.py#L52). You could implement similar callback but do `save_checkpoint` in the function body.

-Minjie

**Comment by futurely** [comment]
The snippet does that. Please help commit it. Thanks!

**Comment by tqchen** [comment]
@futurely Would be great if you can open a PR on this:) Maybe rename the do_checkpoint to be do_checkpoint_during_iteration

**Comment by mli** [comment]
you can set `epoch_size` to reduce the size of an epoch, whose default value is `num_examples/batch_size`

**Comment by futurely** [comment]
Still need to do an extra computation `checkpoint_iters * batch_size` or re-computation when `batch_size` is changed. Simply setting `checkpoint_iters` is more user friendly.

**Comment by futurely** [comment]
The same applies to `validation_iters` which can't be set explicitly now.

**Comment by pluskid** [comment]
There is a bigger problem: the parameters are located on each worker device, and only sync-ed back to CPU at the end of each epoch (see [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L370)). So saving checkpoints in the middle of an epoch will only get parameters from the last epoch.

I do agree that being able to save and inspect models per iteration (batch) is useful for some specific cases and also for debugging.

**Comment by futurely** [comment]
Batch end callback can do this by checking `iter_no % num_checkpoint_iterations == 0`. Another trick is to fake epoch_size to be num_checkpoint_iterations rather than `ceil(num_samples / batch_size)`.

**Comment by jonbakerfish** [comment]
FYI: a checkpoint class for `batch_end_callback`:

    class BatchCheckpoint(object):
        def __init__(self, mod, prefix, period, save_optimizer_states=False):
            """checkpoint for batch_end_callback

            Parameters
            ----------
            mod : subclass of BaseModule
                The module to checkpoint.
            prefix : str
                The file prefix for this checkpoint.
            period : int
                How many batchs to wait before checkpointing.
            save_optimizer_states : bool
                Indicates whether or not to save optimizer states for continued training.

            Example
            -------
            >>> # save checkpoint every ten batches.
            >>> module.fit(iterator, num_epoch=n_epoch,
            ... batch_end_callback=callback.BatchCheckpoint(module, prefix, 10))
            """
            self.mod = mod
            self.prefix = prefix
            self.period = period
            self.save_optimizer_states = save_optimizer_states

        def __call__(self, param):
            if (param.nbatch + 1) % self.period == 0:
                self.mod.save_checkpoint(self.prefix + '-e-%04d-b'%param.epoch, 
                                         param.nbatch + 1, self.save_optimizer_states)

**Comment by futurely** [comment]
The Gluon API does not need callback anymore.
https://github.com/apache/incubator-mxnet/blob/4044703afed6c9c6942674a42036b248710156e1/example/gluon/image_classification.py
