### ISSUE TITLE
[Python Symbolic API] failed to use one symbol multiple times in a single op

### ISSUE THREAD

**Issue by zhangkaixu** [dmlc/mxnet#659]
for example
`sym.concat(s1, s1)` or `s2 = s1 * s1`
If I do so, the model can be trained by calling `fit()` due to the logs I see. But it stopped there and cannot execute the rest of my code.

Of course I can replace `s1 * s1` by `s1 ** 2`, but this is a bug, right?

**Comment by tqchen** [comment]
Thanks for reporting this, should be fixed after #665 get merged
