### ISSUE TITLE
Print detailed architecture definition and check shapes during network construction

### ISSUE THREAD

**Issue by futurely** [dmlc/mxnet#660]
for two reasons:
1. Save the training output in log files for each experiment and the above information helps users find out the network architectures in question retrospectively.
2. Fail early if the shapes are inconsistent. The errors in a network definition can be found out before the network starts to run. Otherwise, the program just crashes and emits a huge core dump file which is much less useful for debugging than fine-grained log details.
```
./dmlc-core/include/dmlc/logging.h:208: [19:50:25] ./mshadow/mshadow/./././dot_engine-inl.h:285: Check failed: dst.size(0) == sleft[0] && dst.size(1) == sright[1] && sleft[1] == sright[0] dot-gemm: matrix shape mismatch
[19:50:25] ./dmlc-core/include/dmlc/logging.h:208: [19:50:25] src/engine/./threaded_engine.h:295: [19:50:25] ./mshadow/mshadow/./././dot_engine-inl.h:285: Check failed: dst.size(0) == sleft[0] && dst.size(1) == sright[1] && sleft[1] == sright[0] dot-gemm: matrix shape mismatch
terminate called after throwing an instance of 'dmlc::Error'
  what():  [19:50:25] src/engine/./threaded_engine.h:295: [19:50:25] ./mshadow/mshadow/./././dot_engine-inl.h:285: Check failed: dst.size(0) == sleft[0] && dst.size(1) == sright[1] && sleft[1] == sright[0] dot-gemm: matrix shape mismatch
```

**Comment by piiswrong** [comment]
Which op generated this? Ideally this should be caught in infershape before forward/backward starts.

**Comment by futurely** [comment]
All errors are posted. There is no clue to find out the answer. That's why all relevant information should always be printed out.

**Comment by piiswrong** [comment]
when things fail in the engine, you can try using NAIVE_ENGINE, and backtrace will give you the call hierarchy.

**Comment by HeNine** [comment]
I had a similar problem when using `mx.symbol.FullyConnected()`. Changing `mx.nd.array([1,2,3,4,5])` to `mx.nd.array([[1,2,3,4,5]])` (note the extra level of nesting), seems to have solved it.

**Comment by futurely** [comment]
Using `Flatten` in the last layers avoids the error.
```
  pool = mx.sym.Pooling(data = data, kernel = (8, 8), stride = (1, 1), pool_type = 'avg', name = 'global_pool')
  flatten = mx.sym.Flatten(data = pool, name = 'flatten')
  dropout = mx.symbol.Dropout(data = flatten, p = 0.2, name = 'dropout')
  fc1 = mx.symbol.FullyConnected(data = dropout, num_hidden = num_classes, name = 'fc1')
  softmax = mx.symbol.SoftmaxOutput(data = fc1, name = 'softmax')
```
