### ISSUE TITLE
CTC build failed for speech_recognition example

### ISSUE THREAD

**Issue by xinq2016** [dmlc/mxnet#6603]
## Environment info
Operating System: Ubuntu 14.04

Compiler:

Package used (Python/R/Scala/Julia): python

MXNet version: 0.10.0

Or if installed from source: git clone https://github.com/dmlc/mxnet.git ~/mxnet --recursive

## Error Message:
There are 3 Errors with different build schedules:
git clone with MxNet, modify the config.mk with 
USE_BLAS = openblas
USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda
USE_CUDNN = 1
three different modifications as follows, and then run the example of speech_recognition:

**1.  without MXNET_PLUGINS += plugin/warpctc/warpctc.mk**
net = mx.sym.WarpCTC(data=net, label=label, label_length=num_label, input_length=seq_len)
AttributeError: 'module' object has no attribute 'WarpCTC'

**2. with MXNET_PLUGINS += plugin/warpctc/warpctc.mk**
terminate called after throwing an instance of 'std::runtime_error'
what(): Error: compute_ctc_loss, stat = cuda memcpy or memset failed

**3. with MXNET_PLUGINS += plugin/warpctc/warpctc.mk, and delete all the new ctc_loss files (the folder ctc_include, ctc_loss.cc, ctc_loss.cu and ctc_loss-inl.h) as mentioned in the previous issue** https://github.com/dmlc/mxnet/issues/6121
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: compute_ctc_loss, stat = execution failed
Aborted (core dumped)

## Minimum reproducible example

As mentioned above, modify the config.mk in different ways, then run the example.

## Steps to reproduce
after make the mxnet, and python installed, run the example of speech_recognition with the deepspeech.cfg

python main.py --configfile deepspeech.cfg

From the three different builds and errors, it shows that the mxnet need the wrap-ctc plugin, and the problem is still the ctc of mxnet in the src\operator\contrib folder? 

@piiswrong, Would you please help me to dig into this issue? How can I fix it?

Many thanks
Xin.q.

**Comment by piiswrong** [comment]
@sbodenstein Any updates on fixing this?

**Comment by sbodenstein** [comment]
@piiswrong: I tried one or two things to fix it (which didn't work), and then ran out of time for a release. 

I will try and make some time this Saturday to return to this.

**Comment by alues** [comment]
same issue with warp-ctc's lstm_ocr.py and toy_ctc.py @sbodenstein

**Comment by piiswrong** [comment]
@sbodenstein Another approach is to change warpctc implementation to be the same with the new ctc_loss, while keeping the original interface

**Comment by sbodenstein** [comment]
@piiswrong: that would be easy to do. I guess the advantage of having a warpctc plugin that does not rely on our new CTC layer, is that upstream Warp CTC changes are immediately useable.

What do you think?

**Comment by alues** [comment]
any update for this problem? @sbodenstein

**Comment by xinq2016** [comment]
is there any update for this issue? @piiswrong, @sbodenstein 
and there is a question may be not related to mxnet.
I've built the deep speech2 architecture in keras, tensorflow, and mxnet, but any of them achieves a good performance.
The architecture is believed to be right. So how can I optimize the neural network to get the performance in  papers?

Many thanks

**Comment by piiswrong** [comment]
@sbodenstein I think making it work is enough for now. Let's use the new ctc layer.

**Comment by sbodenstein** [comment]
@piiswrong: ok, I'll add it.

**Comment by piiswrong** [comment]
@xinq2016 What dataset did you use? You need hundreds of thousands of hours of training data to get baidu's numbers.

**Comment by piiswrong** [comment]
@sbodenstein Any updates? I just noticed that there is a removeblank step in warpctc but not in the new ctcloss. Are the results equivalent? If not why?

**Comment by xinq2016** [comment]
@sbodenstein， 
I use the librispeech for English, and my own corpus for mandarin, which has about 1,400 hours.
1. For English, I build the model with English character, which has 29 labels including <SPACE>
2. For Mandarin, I build the model in two ways, no <SPACE> for mandarin modeling.
 1). phone-level modeling with 218 labels;
 2). character-level modeling with 4816 labels 

Before MXNet, I used the code coming from Baidu github, coding in Keras, with 1 Conv + 3 GRU + 1 FC.
For three models, the final loss seem to be around 40 and bad CER about 40%+. 
While there is some issue with the MXNet with warp-ctc, so I have no result in MXNet.

How can I optimize the RNN architecture? Is there some tips?

Many thanks

**Comment by vandanavk** [comment]
Anyone still seeing the issue (AttributeError: 'module' object has no attribute 'WarpCTC')? I have tried all possible solutions suggested in various GitHub issues. But I still see this error with speech recognition example. It seems to work fine with the ctc example.
