### ISSUE TITLE
Large time cost over GPU computation

### ISSUE THREAD

**Issue by SpecialM2580** [dmlc/mxnet#6605]
I'm trying mxnet code from API,
`   n = 10
    a = mx.nd.ones((1000, 1000))
    b = mx.nd.ones((6000, 6000), mx.gpu())
    tic = time.time()
    c = do(a, n)
    wait(c)
    print('Time to finish the CPU workload: %f sec' % (time.time() - tic))
    d = do(b, n)
    wait(d)
    print('Time to finish both CPU/GPU workloads: %f sec' % (time.time() - tic))`
and the result is:

Time to finish the CPU workload: 1.327401 sec
Time to finish both CPU/GPU workloads: 117.675283 sec

There are no error during compilation, and i use the same configurations as in caffe compiled on my machine.(gpu: 980m). caffe on my PC can conduct gpu computation at once, yet mxnet on my PC has to wait 100 seconds at least. What's wrong with my configuration?

**Comment by piiswrong** [comment]
what's definition of do and wait?

**Comment by SpecialM2580** [comment]
It's okay now, I used wrong CUDA arch when compiled opencv, after changing the CUDA arch in opencv, It has been reduced to 1.8 second.
