### ISSUE TITLE
how to use profiler

### ISSUE THREAD

**Issue by GuanhuaWang** [dmlc/mxnet#6608]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 14.04

Compiler:g++, nvcc

Package used (Python/R/Scala/Julia):python

MXNet version: latest

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

0. recursively pull the code from your repo. 
1. I modify the config.mk and set USE_PROFILER = 1
2. then I `make`
3. After that I run `python /mxnet/example/profiler/profiler_executor.py`
4. It says "/mxnet/dmlc-core/include/dmlc/./logging.h:300: [22:33:05] src/c_api/c_api.cc:85: Need to compile with USE_PROFILER=1 for MXNet Profiler"

## What have you tried to solve it?

1. I try to build the source code again, but same errors.
2.
3.

Can you provide more details about how to use the MxNet profiler?

**Comment by piiswrong** [comment]
run
```
import mxnet
print(mxnet.__file__)
```
See if you are really using the mxnet you just compiled

**Comment by GuanhuaWang** [comment]
Yep, I think this is the correct path I compiled.

>>> import mxnet
>>>
>>> print(mxnet.__file__)
/mxnet/python/mxnet/__init__.pyc

**Comment by ZihengJiang** [comment]
Have you executed `make clean` if you did `make` before?

**Comment by tornadomeet** [comment]
make sure no space left at the end line ```USE_PROFILER = 1```

**Comment by GuanhuaWang** [comment]
Yep, that is the problem @ZihengJiang , thanks ziheng !
