### ISSUE TITLE
Add an optional parameter to visualise the architecture of networks with other shapes? 

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#663]
Currently, in https://github.com/dmlc/mxnet/blob/master/python/mxnet/visualization.py#L62, the shape of elements is "box". Personally I think other shapes like "oval" may look better, because boxes occupy too much space.   ^_^

**Comment by wangg12** [comment]
@pluskid How to fix the problem that both the `plot_network` method and `node_attr` dict have "shape"  ?

**Comment by pluskid** [comment]
you can merge the dict provided by user if not none. the mergedn dict will overwite existing entries.
