### ISSUE TITLE
infer_shape fails and bind fails, but infer_shape_partial succeeds

### ISSUE THREAD

**Issue by jmacglashan** [dmlc/mxnet#6631]
MXNet version: 0.10

`infer_shape` and binding fails in certain conditions when the shape should be inferable, and in fact, `infer_shape_partial` is able to successfully infer the shape. In the below example, the problem seems to stem from applying an expand_dims operator after a symbol has been broadcast on an axis with size 0.

Setup:
```
x = mx.sym.ones((5, 1, 3))
y = mx.sym.var('y', shape=(1, 3))
y2 = mx.sym.broadcast_axis(y, axis=0, size=0)  # (0, 3)
y3 = mx.sym.expand_dims(y2, axis=1)  # (0, 1, 3)
c = mx.sym.concat(x, y3, dim=1)  # *should* be (5, 2, 3)
```
Although the shape should be clear, `c.simple_bind(mx.cpu())` fails and if you do `c.infer_shape()` you get the output:
```
(None, None, None)
```

However, to further demonstrate that the shape should be inferable; `c.infer_partial_shape()` *does* correctly infer the shape. It outputs:
```
([(1, 3)], [(5, 2, 3)], [])
```

So something is wrong about how `infer_shape` and binding is working but isn't wrong in `infer_partial_shape`.

I'll further note that if you avoid the `expand_dims` and shape the var with the extra dimension to start it works. That is:
```
x = mx.sym.ones((5, 1, 3))
y = mx.sym.var('y', shape=(1, 1, 3))
y2 = mx.sym.broadcast_axis(y, axis=0, size=0)  # (0, 1, 3)
c = mx.sym.concat(x, y2, dim=1)  # (5, 2, 3)
```
correctly has `infer_shape` produce `(5, 2, 3)` and simple_bind also works. So concat should be passing down the shape information, but it's getting lost somewhere in the expand_dims.

This all suggests that there is some bug in the `infer_shape`, possibly in `expand_dims` not passing down the 0 shapes, but not in the `partial_infer_shape`.

**Comment by piiswrong** [comment]
This is because concat doesn't do backward shape inference yet. You can verify it by grouping y3 and c, then do infer_shape_partial. You'll see y3 is still empty.

it can be fixed by adding backward shape infer to concat. Would you like to propose a fix?

**Comment by reminisce** [comment]
`infer_partial_shape` not raising exceptions doesn't mean the shape inference is completed without problems. In the backend, `infer_partial_shape` and `infer_shape` do the same thing, except that `infer_partial_shape` would return shape inference results even though some shapes cannot be inferred, while `infer_shape` would print error messages (what shapes cannot be inferred) and return None. simple_bind needs complete shape inference results to continue.

**Comment by jmacglashan** [comment]
I'm not sure how it is the case that concact doesn't do backward shape inference. Everything works fine when you don't do expand_dims. The last code block that I posted *works* and that involves the shape having to be inferred from the concat. How is that working if concat doesn't do backward shape inference? If by some chance that fixes it though, then that's great. I would propose a fix, but I'm not up to speed enough on the C++ backend myself.

Reminsice, it's not that infer_shape_partial is merely not raising exceptions, it's that it's actually reporting the correct and complete shape information: it correctly infers that the output should be 5, 2, 3. If it is able to determine that that is the output shape, what else is missing that infer_shape chokes on?

**Comment by reminisce** [comment]
@jmacglashan If `infer_shape` failed, it should print the error message containing words
`Cannot decide shape for the following arguments...`. What are the input args that the error message suggest you consider providing shapes for?

What is `x2` in your script?

**Comment by jmacglashan** [comment]
This is the complete output on the infer_shape:
```
>>> c.infer_shape()
__main__:1: UserWarning: Cannot decide shape for the following arguments (0s in shape means unknown dimensions). Consider providing them as input:
	
(None, None, None)
```

So it thinks there are zeros, but then doesn't report any. And indeed, the infer_shape_partial does not report any zeros. I listed it's output shape previously, but for completeness, here the full output of that call:
```
>>> c.infer_shape_partial()
([(1, 3)], [(5, 2, 3)], [])
```
As you can see, everything is complete, with no zeros.



`x2` shouldn't have been there, sorry. I originally had one more step in the example with x, but decided it added nothing to the demonstration of the error and simplified the example by removing it without fixing that part :p I fixed the code in the original message.

**Comment by szha** [comment]
I had a similar issue in #5568 with different ops but same problem (failed infer_shape but all results present in infer_shape_partial)

**Comment by reminisce** [comment]
@jmacglashan There are two problems:
1. `c = mx.sym.concat(x, y3, dim=1)` should be `c = mx.sym.concat(x, y3, dim=0)`
1. When you `y2 = mx.sym.broadcast_axis(y, axis=0, size=0)`, this leaves an internal node with undetermined output shapes (0 in the first dim). As MXNet does not support empty tensors, this is still treated as `infer_shape` failure even though arg shapes and output shapes can be deduced.

**Comment by piiswrong** [comment]
@jmacglashan Looks like its expand_dims that's not doing backward shape infer. You can try fix the infer_shape function

**Comment by jmacglashan** [comment]
@reminisce No, those are not mistakes :p The concat dim was deliberately dim=1 and *not* dim=0. This simplified example actually followed from a use case myself and colleagues had where concat was on a second dimension (has to do with mixture models).

The broadcast_axis was also deliberately sized to zero so that it can be inferred to match the batch dimension. (In actual practice x would be something more like a data arg and y a tunable variable/weight, but I don't think it's important to describe the specific reasoning we ran into this problem). size=0 in this way is entirely valid when the operations support the backward shape inference, as in shown in the last code block I posted (that eschews the expand_dims) which also has size=0 in the broadcast and which works fine.

The problem seems to be with expand_dims. As piiswrong said, it sounds like the issue is that expand_dims doesn't do the backward shape inference. Since I'm not up to speed on the backend side of mxnet, it's not something I can fix myself soon. If someone else sees this and can tackle this issue before me though, that would be great.

**Comment by reminisce** [comment]
@jmacglashan I see. I went through the InferShape pass in gdb and noticed the output of broadcast_axis's shape has 0 in the first dim at the end of the pass, which should have been back-inferred by the output of expand_dims. I can help by submitting a PR to fix this.

**Comment by jmacglashan** [comment]
Great, thanks very much!
