### ISSUE TITLE
Ubuntu building R mxnet, when i run 'make rpkg', procuced Error.

### ISSUE THREAD

**Issue by GuilongZh** [dmlc/mxnet#6662]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04

Compiler:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

Package used (Python/R/Scala/Julia):
R

MXNet version:
installed from source

MXNet commit hash (`git rev-parse HEAD`):
d75ef8eb65a56ecec6613458017a0c83f7a9ed34

If you are using python package, please provide
Yes, I using python MXNet installed from source. And it's __version__ = '0.10.0'.

R version and distribution:
R version 3.4.0 (2017-04-21)

R `sessionInfo()`:
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.0

## Error Message:
~/Downloads/rmxnet/mxnet$ make rpkg
mkdir -p R-package/inst
mkdir -p R-package/inst/libs
cp -rf lib/libmxnet.so R-package/inst/libs
mkdir -p R-package/inst/include
cp -rf include/* R-package/inst/include
cp -rf dmlc-core/include/* R-package/inst/include/
cp -rf nnvm/include/* R-package/inst/include
echo "import(Rcpp)" > R-package/NAMESPACE
echo "import(methods)" >> R-package/NAMESPACE
R CMD INSTALL R-package
Warning: invalid package ‘R-package’
Error: ERROR: no packages specified
Makefile:349: recipe for target 'rpkg' failed
make: *** [rpkg] Error 1

## Steps to reproduce
I running standard examples, when i run 'make rpkg', it produced the error.
What can i do? it's because i installed python package?
Thanks for your help.

**Comment by thirdwing** [comment]
I am sorry that I don't know why you met the error.

Can you run `R CMD INSTALL R-package` manually and show me what happened?

**Comment by GuilongZh** [comment]
~/Downloads/rmxnet/mxnet$ R CMD INSTALL R-package
Warning: invalid package ‘R-package’
Error: ERROR: no packages specified

That 'R-package' is the folder? like the following？


zhang@ubu:~/Downloads/rmxnet/mxnet$ ls
amalgamation     dlpack       make           plugin           snapcraft.yaml
appveyor.yml     dmlc-core    Makefile       prepare_mkl.sh   snap.python
bin              docker       matlab         ps-lite          src
build            docs         MKL_README.md  python           tests
cmake            example      mshadow        README.md        tools
CMakeLists.txt   include      NEWS.md        readthedocs.yml
CONTRIBUTORS.md  Jenkinsfile  nnvm           R-package
cpp-package      lib          NOTICE         scala-package
cub              LICENSE      perl-package   setup-utils

**Comment by thirdwing** [comment]
Yes, the "R-package" is a folder.

**Comment by GuilongZh** [comment]
Yes, you are right. I found there are two versions of R on my computer. And i installed mxnet in one of versions.  Thanks for your help!
