### ISSUE TITLE
Cannot find Scala source code or documentation that matches the current compiled code/library

### ISSUE THREAD

**Issue by dragonhyq** [dmlc/mxnet#6677]
Dear all, 

I was trying to use mxnet scala API while reading its source, and I could not find its source or documentation.

For example. 

I was reading an example in [mnist classification](https://github.com/dmlc/mxnet/blob/master/scala-package/examples/src/main/scala/ml/dmlc/mxnetexamples/imclassification/TrainMnist.scala), and I was trying to find the definition of `Symbol.FullyConnected()`, so I looked at the current  [src](https://github.com/dmlc/mxnet/blob/master/scala-package/core/src/main/scala/ml/dmlc/mxnet/Symbol.scala), but could not find it. The current [Scala documentation](http://mxnet.io/api/scala/docs/index.html#ml.dmlc.mxnet.Symbol$) is faithful to the source, so it does not have it either. 

An [old version](https://github.com/terrytangyuan/mxnet/blob/master/scala-package/core/src/main/scala/ml/dmlc/mxnet/Symbol.scala) I found online has it, but it's not up-to-date. 

In IntelliJ through sbt I directly used 

```
libraryDependencies ++= Seq(
// https://mvnrepository.com/artifact/ml.dmlc.mxnet/mxnet-scala-native-parent
  "ml.dmlc.mxnet" % "mxnet-full_2.11-osx-x86_64-cpu" % "0.9.3a”)
```

And the imported library, i.e. `ml.dmlc.mxnet._` has `Symbol.FullyConnected()` in there. But everything I use in IntelliJ is compiled code, so I cannot read the source code. 

Could anyone direct me to the source code or documentation that actually maps the library/compiled code? 

Many thanks.

**Comment by Ldpe2G** [comment]
@dragonhyq  Scalapkg now use macro to automatically generate the symbol(operator, layer), so no needs to add symbols by hand. That's why you can not find the definition of FullyConnected in source code.

**Comment by dragonhyq** [comment]
@Ldpe2G Thanks for your reply. So, what would be the best way to know what operations are available for a Symbol object since there is no documentation/source-code for that? I can go through the list that pops up in IntelliJ after writing `Symbol` to see what's there and just choose the one I want, but is there a better way?

**Comment by Ldpe2G** [comment]
@dragonhyq 
There are two ways: 
you can refer to the python doc: http://mxnet.io/api/python/symbol.html#api-reference,
or refer to the C++ source code: https://github.com/dmlc/mxnet/tree/master/src/operator

**Comment by dragonhyq** [comment]
@Ldpe2G Thanks, I will do that!
