### ISSUE TITLE
Installation problems: mxnet for R-3.1.3 on windows8.1 x64 

### ISSUE THREAD

**Issue by 546492928** [dmlc/mxnet#6691]
I run following codes to install mxnet for R-3.1.3 on windows8.1 x64,
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("mxnet")

The error messages are:

> install.packages("drat", repos="https://cran.rstudio.com")
Installing package into ‘C:/Users/turbo1/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.1/drat_0.1.0.zip'
Content type 'application/zip' length 70200 bytes (68 KB)
opened URL
downloaded 68 KB

package ‘drat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\turbo1\AppData\Local\Temp\Rtmp2x1mBS\downloaded_packages
> drat:::addRepo("dmlc")
> install.packages("mxnet")
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://dmlc.github.io/drat/bin/windows/contrib/3.1
Installing package into ‘C:/Users/turbo1/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://dmlc.github.io/drat/bin/windows/contrib/3.1

   package ‘mxnet’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘mxnet’ is not available (as a binary package for R version 3.1.3)
> 
Please help me!

**Comment by RogerBorras** [comment]
Update to R v.3.3 or 3.4!

**Comment by 546492928** [comment]
@RogerBorras  I have tried it, but it still doesn't work, the error messages are as follows

> install.packages("drat", repos="https://cran.rstudio.com")
Installing package into ‘C:/Users/shenliu/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/drat_0.1.2.zip'
Content type 'application/zip' length 73018 bytes (71 KB)
downloaded 71 KB

package ‘drat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\shenliu\AppData\Local\Temp\RtmpUfdMbe\downloaded_packages
> drat:::addRepo("dmlc")
> install.packages("mxnet")
Installing package into ‘C:/Users/shenliu/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘iterators’, ‘bindr’, ‘pkgmaker’, ‘registry’, ‘rngtools’, ‘gridBase’, ‘foreach’, ‘doParallel’, ‘brew’, ‘assertthat’, ‘bindrcpp’, ‘glue’, ‘pkgconfig’, ‘rlang’, ‘tibble’, ‘plogr’, ‘NMF’, ‘irlba’, ‘Rook’, ‘viridisLite’, ‘gridExtra’, ‘dplyr’, ‘htmlwidgets’, ‘igraph’, ‘influenceR’, ‘rgexf’, ‘scales’, ‘viridis’, ‘DiagrammeR’, ‘visNetwork’, ‘data.table’

Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.2/PACKAGES.gz': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.2/PACKAGES': HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository https://dmlc.github.io/drat/bin/windows/contrib/3.2:
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.2/PACKAGES'

  There are binary versions available but the source versions are later:
       binary source needs_compilation
glue    1.0.0  1.1.0              TRUE
tibble  1.3.0  1.3.3              TRUE
irlba   2.1.2  2.2.1              TRUE
dplyr   0.5.0  0.7.0              TRUE

  Binaries will be installed
Packages which are only available in source form, and may need compilation of
  C/C++/Fortran: ‘rlang’ ‘mxnet’
  These will not be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/iterators_1.0.8.zip'
Content type 'application/zip' length 316292 bytes (308 KB)
downloaded 308 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/bindr_0.1.zip'
Content type 'application/zip' length 14695 bytes (14 KB)
downloaded 14 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/pkgmaker_0.22.zip'
Content type 'application/zip' length 558489 bytes (545 KB)
downloaded 545 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/registry_0.3.zip'
Content type 'application/zip' length 185956 bytes (181 KB)
downloaded 181 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/rngtools_1.2.4.zip'
Content type 'application/zip' length 155349 bytes (151 KB)
downloaded 151 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/gridBase_0.4-7.zip'
Content type 'application/zip' length 160705 bytes (156 KB)
downloaded 156 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/foreach_1.4.3.zip'
Content type 'application/zip' length 389142 bytes (380 KB)
downloaded 380 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/doParallel_1.0.10.zip'
Content type 'application/zip' length 184498 bytes (180 KB)
downloaded 180 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/brew_1.0-6.zip'
Content type 'application/zip' length 104727 bytes (102 KB)
downloaded 102 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/assertthat_0.2.0.zip'
Content type 'application/zip' length 43598 bytes (42 KB)
downloaded 42 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/bindrcpp_0.1.zip'
Content type 'application/zip' length 567177 bytes (553 KB)
downloaded 553 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/glue_1.0.0.zip'
Content type 'application/zip' length 34947 bytes (34 KB)
downloaded 34 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/pkgconfig_2.0.1.zip'
Content type 'application/zip' length 19748 bytes (19 KB)
downloaded 19 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/tibble_1.3.0.zip'
Content type 'application/zip' length 566754 bytes (553 KB)
downloaded 553 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/plogr_0.1-1.zip'
Content type 'application/zip' length 17649 bytes (17 KB)
downloaded 17 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/NMF_0.20.6.zip'
Content type 'application/zip' length 2490198 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/irlba_2.1.2.zip'
Content type 'application/zip' length 255922 bytes (249 KB)
downloaded 249 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/Rook_1.1-1.zip'
Content type 'application/zip' length 280264 bytes (273 KB)
downloaded 273 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/viridisLite_0.2.0.zip'
Content type 'application/zip' length 57582 bytes (56 KB)
downloaded 56 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/gridExtra_2.2.1.zip'
Content type 'application/zip' length 483322 bytes (471 KB)
downloaded 471 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/dplyr_0.5.0.zip'
Content type 'application/zip' length 2520396 bytes (2.4 MB)
downloaded 2.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/htmlwidgets_0.8.zip'
Content type 'application/zip' length 848659 bytes (828 KB)
downloaded 828 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/igraph_1.0.1.zip'
Content type 'application/zip' length 8192332 bytes (7.8 MB)
downloaded 7.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/influenceR_0.1.0.zip'
Content type 'application/zip' length 56235 bytes (54 KB)
downloaded 54 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/rgexf_0.15.3.zip'
Content type 'application/zip' length 517445 bytes (505 KB)
downloaded 505 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/scales_0.4.1.zip'
Content type 'application/zip' length 609664 bytes (595 KB)
downloaded 595 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/viridis_0.4.0.zip'
Content type 'application/zip' length 1741199 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/DiagrammeR_0.9.0.zip'
Content type 'application/zip' length 4594005 bytes (4.4 MB)
downloaded 4.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/visNetwork_1.0.3.zip'
Content type 'application/zip' length 2665044 bytes (2.5 MB)
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/data.table_1.10.4.zip'
Content type 'application/zip' length 1455417 bytes (1.4 MB)
downloaded 1.4 MB

package ‘iterators’ successfully unpacked and MD5 sums checked
package ‘bindr’ successfully unpacked and MD5 sums checked
package ‘pkgmaker’ successfully unpacked and MD5 sums checked
package ‘registry’ successfully unpacked and MD5 sums checked
package ‘rngtools’ successfully unpacked and MD5 sums checked
package ‘gridBase’ successfully unpacked and MD5 sums checked
package ‘foreach’ successfully unpacked and MD5 sums checked
package ‘doParallel’ successfully unpacked and MD5 sums checked
package ‘brew’ successfully unpacked and MD5 sums checked
package ‘assertthat’ successfully unpacked and MD5 sums checked
package ‘bindrcpp’ successfully unpacked and MD5 sums checked
package ‘glue’ successfully unpacked and MD5 sums checked
package ‘pkgconfig’ successfully unpacked and MD5 sums checked
package ‘tibble’ successfully unpacked and MD5 sums checked
package ‘plogr’ successfully unpacked and MD5 sums checked
package ‘NMF’ successfully unpacked and MD5 sums checked
package ‘irlba’ successfully unpacked and MD5 sums checked
package ‘Rook’ successfully unpacked and MD5 sums checked
package ‘viridisLite’ successfully unpacked and MD5 sums checked
package ‘gridExtra’ successfully unpacked and MD5 sums checked
package ‘dplyr’ successfully unpacked and MD5 sums checked
package ‘htmlwidgets’ successfully unpacked and MD5 sums checked
package ‘igraph’ successfully unpacked and MD5 sums checked
package ‘influenceR’ successfully unpacked and MD5 sums checked
package ‘rgexf’ successfully unpacked and MD5 sums checked
package ‘scales’ successfully unpacked and MD5 sums checked
package ‘viridis’ successfully unpacked and MD5 sums checked
package ‘DiagrammeR’ successfully unpacked and MD5 sums checked
package ‘visNetwork’ successfully unpacked and MD5 sums checked
package ‘data.table’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\shenliu\AppData\Local\Temp\RtmpUfdMbe\downloaded_packages
> install.packages("mxnet")
Installing package into ‘C:/Users/shenliu/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.2/PACKAGES.gz': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.2/PACKAGES': HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository https://dmlc.github.io/drat/bin/windows/contrib/3.2:
  cannot open URL 'https://dmlc.github.io/drat/bin/windows/contrib/3.2/PACKAGES'
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘mxnet’
  These will not be installed

**Comment by thirdwing** [comment]
I am afraid you are using R 3.2

**Comment by 546492928** [comment]
@thirdwing 
Does it only support the latest version of R ? If so, does it mean that once there is a new version of R, I need to update my R for using it?

**Comment by thirdwing** [comment]
Not always the latest one. But we are planning to use some new functions in R 3.3, so I am afraid you need R >= 3.3.0 to use mxnet.
