### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Hexiang-Hu** [dmlc/mxnet#6697]
https://github.com/dmlc/mxnet/blob/430ea7bfbbda67d993996d81c7fd44d3a20ef846/tools/caffe_converter/convert_caffe_modelzoo.py#L61

Should be "resnet-101" instead of "resnt-101".

**Comment by chunyang-wen** [comment]
you can send a pull request for it. And you are contributing to the project!

**Comment by Hexiang-Hu** [comment]
just submitted one...
