### ISSUE TITLE
stream_gpu-inl.h:65: Default GPU stream was used when MSHADOW_FORCE_STREAM was on

### ISSUE THREAD

**Issue by raygit** [dmlc/mxnet#671]
Hi all,

Sorry to bother you but i encountered this issue when i attempted to run the binary after the file ***basic_stream.cu*** was built, and it threw out the message:
```
stream_gpu-inl.h:65: Default GPU stream was used when MSHADOW_FORCE_STREAM was on
```
Appreciate your help as to why this is occurring?

Btw, i've compiled this on OSX El Capitan with CUDA 7.5 installed; path settings appear to be correct.

**Comment by tqchen** [comment]
This could due to  we didn't updated the example of mshadow. This warning is due to some operation did not have stream set, (some tensor did not get the stream set correctly). let us move to issue of https://github.com/dmlc/mshadow
