### ISSUE TITLE
[R] grad.req is hard-coded in model training

### ISSUE THREAD

**Issue by thirdwing** [dmlc/mxnet#6723]
See https://github.com/dmlc/mxnet/blob/master/R-package/R/model.R#L114

**Comment by thirdwing** [comment]
We can simplify and refactor the RNN model training after fixing this: https://github.com/dmlc/mxnet/blob/master/R-package/R/rnn_model.R#L63

**Comment by jeremiedb** [comment]
Is there a reason for having grad.req to "add" rather than "write" as the later seems the proper way to go as in #1715? In the RNN rewrite I use, grad.req is set to "write" and behaves just fine. 

Is the intent to refactor based on the new mx.symbol.RNN?

**Comment by thirdwing** [comment]
@jeremiedb I think you are correct. It should be "write". This should be fixed.
