### ISSUE TITLE
[Custom op backward] Crashed when manipulate out_grad

### ISSUE THREAD

**Issue by Zehaos** [dmlc/mxnet#6751]
I am writing a custom op, and I got stucked when writing the backward part. 

When I call *out_grad[0].asnumpy()* or do any manipulation of the out_grad, the program crash without any error message. 

I tried fill the in_grad with zeros, the program run smoothly, but I need the grad to flow backward.
```
    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
            self.assign(in_grad[0], req[0], 0)
            self.assign(in_grad[1], req[1], 0)
```

What's going wrong here?

**Comment by Zehaos** [comment]
I use *.shape* to got the shape of the out_grad, it turn out to be ‘( )’, maybe something went wrong in the upstream.

**Comment by hdjsjyl** [comment]
@Zehaos  have you solved the problems, my out_grad is none. Any advice will be appreciated
