### ISSUE TITLE
Can't convert Slice layer & Eltwise layer from caffe to mxnet?

### ISSUE THREAD

**Issue by wangxianliang** [dmlc/mxnet#676]
The following is output:

Traceback (most recent call last):
  File "convert_symbol.py", line 164, in <module>
    main()
  File "convert_symbol.py", line 156, in main
    symbol_string, output_name = proto2script(sys.argv[1])
  File "convert_symbol.py", line 122, in proto2script
    raise Exception('Unknown Layer %s!' % layer[i].type)
Exception: Unknown Layer Slice!

**Comment by tqchen** [comment]
This was because these layer may not yet be supported in mxnet, or the mapping was not yet added. Please feel free  to open a issue on each operators(layer) that is missing, and we can find ways to add them, or give guidance on how they can be added

**Comment by futurely** [comment]
This is part of the https://github.com/dmlc/mxnet/issues/404 (no [pun](https://en.wikipedia.org/wiki/HTTP_404) intended) issue.
