### ISSUE TITLE
mx.model.init.params has one extra parameter in mxnet0.10.0 compared to previous versions

### ISSUE THREAD

**Issue by lichen11** [dmlc/mxnet#6788]
I am trying to reproduce https://statist-bhfz.github.io/cats_dogs_finetune and find the following issue with the version of mxnet. Its function mx.model.init.params, has one extra parameter output.shape.

The original function is as follows:
arg_params_new <- mxnet:::mx.model.init.params(
    symbol = new_soft, 
    input.shape = c(224, 224, 3, 8), 
    initializer = mxnet:::mx.init.uniform(0.1), 
    ctx = mx.gpu(0)
    )$arg.params

Using mxnet0.10.0, the error complains that argument "output.shape" is missing, with no default. I cannot find references on what this output shape refers to. What does this parameter output.shape mean here? Should it be 8, which is the batch size? Also only the following would work: (8), not c(8) or 8. 
arg_params_new <- mxnet:::mx.model.init.params(
    symbol = new_soft, 
    input.shape = c(224, 224, 3, 8), 
    output.shape = (8),
    initializer = mxnet:::mx.init.uniform(0.1), 
    ctx = mx.gpu(0)
    )$arg.params

**Comment by thirdwing** [comment]
Sorry for this. I am refactoring the related functions. The related example and documents will be updated after that.

**Comment by thirdwing** [comment]
@lichen11 I have updated the tutorial in https://github.com/dmlc/mxnet/pull/6935

It should run without any errors.
