### ISSUE TITLE
Can not find the link to 'local_allreduce_cpu'  example according to the mxnet doc

### ISSUE THREAD

**Issue by universewill** [dmlc/mxnet#6814]
I read the page: http://mxnet-tqchen.readthedocs.io/en/latest/system/multi_node.html  
But i can not find the AlexNet on imagenet example.
Can anyone give some help here?  

> local_allreduce_cpu is similar to local_update_cpu except that the averaged gradients are copied back to the devices, and then weights are updated on devices. It is faster than 1 when the weight size is large so we can use the device to accelerate the computation (but we increase the workload by k times). Examples are AlexNet on imagenet.

**Comment by kevinthesun** [comment]
Here is alexnet model definition: https://github.com/dmlc/mxnet/blob/master/example/image-classification/symbols/alexnet.py

You can train with https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_imagenet.py
