### ISSUE TITLE
why MKL fullyconnected operator not available in 0.10

### ISSUE THREAD

**Issue by BiranLi** [dmlc/mxnet#6817]
## Environment info
Operating System:Centos7.3

Compiler:g++4.8.5

Package used (Python/R/Scala/Julia):python

MXNet version:0.10.0

Or if installed from source:source

If you are using python package, please provide

Python version and distribution:2.7.5

------

I use mxnet with MKL in KNL machine. But I found mkl-fullyconnected opeator didn't used in version 0.10.

**Comment by ykim362** [comment]
It was disabled because of a numerical stability issue.
But, in terms of performance, there is no big difference.

It will be re-activated in the future, with a new MKL-DNN library.

**Comment by szha** [comment]
@ykim362 when will it become available?

**Comment by ykim362** [comment]
@szha Currently, an integration with the new mkl-dnn library is under development together with the sparse tensor refactoring. So, it might be available in 3-4 weeks.

**Comment by BiranLi** [comment]
@ykim362 Do you have a stable version of mxnet on KNL or KNM machines? 
The version (0.9.2)  I am using now looks like there is a problem with the correctness in the backward calculation. I have modified the  way to  calculate FC to call sgemm, the result was error.

I try to initialize the network with constant parameters and use uniform input data.
And then compared with the calculation results of P40, the forward results are consistent, but the backward is not the same.

**Comment by ykim362** [comment]
@BiranLi Which version of MKLML are you using? The previous MKLML has an error in backward pooling layer. Could you try to use this MKLML lib? You can download the file and copy include and lib directories into your MKL root directory. It is set to /usr/local by default. https://github.com/01org/mkl-dnn/releases/download/v0.7/mklml_lnx_2017.0.3.20170424.tgz

**Comment by BiranLi** [comment]
@ykim362 I am using a stable MKL2017 library which version is 20170127, not a MKLML library. 
What about the MKL library needs to be updated to lastest. I check the intel official website, the lastest library's version is 20170413.

**Comment by ykim362** [comment]
@BiranLi I see. Is there any way you can try MKLML? In the case of MKL 2017, I will check with the team working on MKL 2017, tomorrow.

**Comment by BiranLi** [comment]
@ykim362  I'm tring to download the MKLML lib, but I cannot access the download page. Could you send me  a download package by email or cloud disk？
I see. Thank you for your assistant.

**Comment by ykim362** [comment]
@BiranLi The above link is a public github location. Do you have an access to other github repositories?

**Comment by BiranLi** [comment]
@ykim362  I mean this package is hosted on the Amazon cloud, and my network here is not normal to visit the Amazon cloud.

**Comment by ykim362** [comment]
@BiranLi The MKLML package is on github.com, not on Amazon cloud. On any machine you have an internet access, you can download it. Then, you can transfer the tgz file into your specific node.

https://github.com/01org/mkl-dnn/releases/download/v0.7/mklml_lnx_2017.0.3.20170424.tgz

**Comment by BiranLi** [comment]
@ykim362 All the download links redirect to amazonaws. Such as https://github-production-release-asset-2e65be.s3.amazonaws.com/58414589.It's error msg is 

> _github-production-release-asset-2e65be.s3.amazonaws.com connect timeout._

**Comment by ykim362** [comment]
@BiranLi I think you might need to check your network. The link works fine on several different machines. It doesn't forward to AWS on my side.

**Comment by BiranLi** [comment]
@ykim362  My company's DNS maybe redirect the link. Thank you.

**Comment by ykim362** [comment]
@BiranLi No problem! Thanks.

**Comment by ykim362** [comment]
@BiranLi I have confirmed that the latest MKL(full MKL) you can download in the below link has the same fixes in MKLML0424. Its build date is 04/30.
https://software.intel.com/en-us/mkl

**Comment by BiranLi** [comment]
@ykim362 Thank you for your reply. I will update MKL to latest version.

**Comment by BiranLi** [comment]
@ykim362 I found the problem was caused by mxnet. The latest mxnet works.

**Comment by ykim362** [comment]
@BiranLi I see. Thanks for letting me know!

**Comment by BiranLi** [comment]
Close the issue because it was fixed.
