### ISSUE TITLE
I want to use opencv in a C++ layer. 

### ISSUE THREAD

**Issue by horserma** [dmlc/mxnet#6837]
Hi,
I sort of want to use opencv in my custom c++ layer. To be more specific, I want to use resize function on some matrices. But I am curious how to adapt the "Tensor" to the cv::mat kind so that I can use resize function. Any suggestions? Thanks.

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/blob/master/src/io/image_io.cc#L200
