### ISSUE TITLE
implement SeLU 

### ISSUE THREAD

**Issue by CNevd** [dmlc/mxnet#6838]
Trying to implement selu activation and Alphadropout, any proposals?

**Comment by Ldpe2G** [comment]
@CNevd you can refer to my implementation https://github.com/Ldpe2G/DeepLearningForFun/blob/master/Mxnet-Scala/SelfNormNets/src/main/scala/snns/Ops.scala

**Comment by CNevd** [comment]
Thanks @Ldpe2G
