### ISSUE TITLE
sample_rois function bug which harms accuracy of Faster RCNN

### ISSUE THREAD

**Issue by shenh10** [dmlc/mxnet#6848]
Previous issue #6809 
It has been proved to be a bug, which harms the accuracy of VOC detection results. Before fixing the bug, with ResNet, VOC2007+2012 as training data, VOC2007test as test data, the mAP can only reach 0.726. By change 
    labels[fg_rois_per_this_image:] = 0
to 
    labels[overlaps[keep_indexes] < config.TRAIN.FG_THRESH] = 0

the mAP reach 0.795, which is even a little higher than reported result.

Cheers,
Han

**Comment by i-MaTh** [comment]
good job !

**Comment by Zehaos** [comment]
Hi, @shenh10 
I think it is not a bug. We should set a higher config.TRAIN.FG_FRACTION, if 
```
labels[overlaps[keep_indexes] < config.TRAIN.FG_THRESH] = 0
```
bring much mAP improvement.

**Comment by shenh10** [comment]
@Zehaos Nope, I think there are label conflicts in padding rois. You can check the reference issue.

**Comment by Zehaos** [comment]
@shenh10 , I know, but 
```
labels[overlaps[keep_indexes] < config.TRAIN.FG_THRESH] = 0
```
is in conflict with config.TRAIN.FG_FRACTION.

**Comment by shenh10** [comment]
@Zehaos True, so maybe you should highlight this issue or set larger FG_THRESH value to avoid the gap happen, or you can change the gap sampling which samples from all bg rois instead of whole rois set. I addressed this problem because 3~4 people have trained their model and can get no more than 73% mAP.

**Comment by shenh10** [comment]
@Zehaos To keep the sense of FG_FRACTION, the latter should be a good choice

**Comment by Zehaos** [comment]
@shenh10 Agree! You can make a new pull request.

**Comment by shenh10** [comment]
@Zehaos Sure, I will retrain the model to validate the accuracy.
