### ISSUE TITLE
Add meaningful information in the failure in RNN tutorial, when the file with the training data is not present

### ISSUE THREAD

**Issue by b0noI** [dmlc/mxnet#6856]
error example:

python lstm_bucketing.py

leads to the following error:
Traceback (most recent call last):
  File "lstm_bucketing.py", line 56, in <module>
    invalid_label=invalid_label)
  File "lstm_bucketing.py", line 35, in tokenize_text
    lines = open(fname).readlines()
IOError: [Errno 2] No such file or directory: './data/ptb.train.txt'

It would be nice to have here the information that https://github.com/dmlc/mxnet/blob/master/example/rnn/get_ptb_data.sh need to be used in order to download the file.

**Comment by kevinthesun** [comment]
I think the download information is already in the readme file: Run get_ptb_data.sh to download PenTreeBank data.
