### ISSUE TITLE
How to copy the data from the Tensor 'src' to the crop of Tensor 'dst'?

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#686]
Hello, all,
  I'm writing one operator in c++ side, but encountered some difficulties .  
  Suppose that we have 2 Tensors: src and dst , both with the format Tensor<xpu, 4, real_t>, the shape of src is (1, 128, 300, 300),  and the shape of dst is (1, 128, 400, 400), now i want to copy the data of src to the subspace of dst, with its range (1,128,50:350,50:350); how to do that?  

  The simplest way is using 'for' loop, and for each element in the corresponding dst, we use "=" assigning its value form src; but when xpu is gpu, this is not allowable; i want to use the crop op in mshdow, but it seems that when cropping a tensor, it returns CroppingExp, and we can only  use this in right side of "="; (Another way maybe the Copy fun in mshadow can do it, but i try it not successfuly.);  

   thanks~

**Comment by tqchen** [comment]
Let us move this issue to https://github.com/dmlc/mshadow

We can update the CropExp to support RValue evaluation, reference slice expression https://github.com/dmlc/mshadow/blob/master/mshadow/extension/slice.h So you can use it at right side of assignment

**Comment by tqchen** [comment]
Let us know if you are interested in contributing this.

**Comment by tornadomeet** [comment]
@tqchen , yes ,i'll try this.
