### ISSUE TITLE
mx.nd.array() VS np.array()

### ISSUE THREAD

**Issue by kobenaxie** [dmlc/mxnet#6865]
mxnet-0.10

x = [np.ones(2), np.ones(2)]
y = mx.nd.array(x)

Code above can pass, but Code below failed.

x = [mx.nd.ones(2), md.nd.ones(2)]
y = mx.nd.array(x)

/home/jlxie/anaconda2/envs/mxnet-0.10/lib/python2.7/site-packages/mxnet/ndarray.pyc in array(source_array, ctx, dtype)
   1110                 source_array = np.array(source_array, dtype=dtype)
   1111             except:
-> 1112                 raise TypeError('source_array must be array like object')
   1113     arr = empty(source_array.shape, ctx, dtype)
   1114     arr[:] = source_array

TypeError: source_array must be array like object

Is it a bug ???

**Comment by reminisce** [comment]
When you call mx.nd.array(x), if x is not a np.ndarray type, a numpy ndarray will be constructed out of np.array(x). In your case, neither x is a np.ndarray type, but in the first case, x is recognizable to np.array() interface, while the second one is not since it is a list of mxnet ndarray type.

**Comment by sampathchanda** [comment]
I still don't understand why is the first case recognizable to np.array() interface but the second case not recognizable to mx.nd.array() interface (should be true on similar lines, isn't it?)

It makes little sense for me to see that the list of numpy arrays are accepted and converted to an mxnet ndarray, but a list of mxnet ndarrays are not accepted.

**Comment by y12uc231** [comment]
Ok, so you @reminisce  are saying that I should change the internal elements to nd/np arrays first and then do mx.nd.array. But if we do this, we will loose the grad values which we had . Please explain
