### ISSUE TITLE
[cpp-package] SimpleBind every minibatch?

### ISSUE THREAD

**Issue by CNevd** [dmlc/mxnet#6867]
In the example [mlp_gpu.cpp](https://github.com/dmlc/mxnet/blob/master/cpp-package/example/mlp_gpu.cpp#L91) seems executor is got from SimpleBind every minibatch, why?
and ```UpdateAll``` update all the arg_arrays include ```X``` and ```label```?  @lx75249

**Comment by lx75249** [comment]
1. It's not necessary to bind every batch, the code was a mistake...
2. I didn't exclude data and label when UpdateAll because it's irrelevant to the result in that case and i'm lazy...

**Comment by CNevd** [comment]
thanks @lx75249
