### ISSUE TITLE
advise for implement a C++ layer

### ISSUE THREAD

**Issue by vikingMei** [dmlc/mxnet#6873]
hi, I'm writing a NCE loss in C++, the forward is easy, but backward is some hard to me, the formula as below:

`ograd[i,j,k] = -y[i,j,k] / ( y[i,j,k] + k*pn[i,j,k] )`
`ograd[0, :, :] += 1.0`

I'm writing with [softmax_output](https://github.com/dmlc/mxnet/blob/master/src/operator/softmax_activation-inl.h) as template, using the old style(previous 0.9.0) as [here](http://mxnet.io/architecture/overview.html#operators-in-mxnet), because the [tutorial](http://mxnet.io/how_to/new_op.html#c) told little about how to make a loss layer

I'm a newbie to mxnet and cuda&cudnn, and only know 2 possible solution:
1. using cuda and openmp to write for loop
1. using mshadow (just guess)

are there any better solution? 

where can I find document about how to do this more quickly, or, which can I take as example

thanks for any help

**Comment by piiswrong** [comment]
You can use the kernel::launch mechanism: https://github.com/dmlc/mxnet/blob/master/src/operator/tensor/indexing_op.h#L200

**Comment by vikingMei** [comment]
@piiswrong , tks, I'lll have a try

**Comment by vikingMei** [comment]
missing complete

@piiswrong, thanks
