### ISSUE TITLE
Amalgamation compilation for Android

### ISSUE THREAD

**Issue by edmBernard** [dmlc/mxnet#6889]
I try to compile Amalgamation for Android development.
I got an Error on include path : 
```bash
user:~/Documents/lib/mxnet/amalgamation$ make ANDROID=1
aarch64-linux-android-clang++ -std=c++11 -Wno-unknown-pragmas -Wall -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_SSE=0 -DDISABLE_OPENMP=1 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DDMLC_LOG_STACK_TRACE=0 -DMSHADOW_FORCE_STREAM -DMXNET_USE_OPENCV=0 -DMXNET_PREDICT_ONLY=1 -I/home/user/Documents/lib/OpenBLAS -I/home/user/Documents/lib/OpenBLAS/include -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -O3 -fPIC -o jni_libmxnet_predict.o -c jni/predictor.cc
clang50++: warning: argument unused during compilation: '-mhard-float' [-Wunused-command-line-argument]
In file included from jni/predictor.cc:4:
jni/../mxnet_predict-all.cc:33:10: fatal error: 'dmlc-core/src/data.cc' file not found
#include <dmlc-core/src/data.cc>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:84 : la recette pour la cible « jni_libmxnet_predict.o » a échouée
make: *** [jni_libmxnet_predict.o] Erreur 1
```

If I add path with CFLAGS parameter :
```
CFLAGS+=-I ${MXNET_ROOT}/ -I ${MXNET_ROOT}/mshadow/ -I ${MXNET_ROOT}/dmlc-core/include -I ${MXNET_ROOT}/dmlc-core/src -I ${MXNET_ROOT}/nnvm/include -I ${MXNET_ROOT}/nnvm -I ${MXNET_ROOT}/dlpack/include -I ${MXNET_ROOT}/include
```
I got lots of symol redefinition :
```
In file included from jni/predictor.cc:4:
jni/../mxnet_predict-all.cc:48910:5: error: redefinition of 'MXSymbolFree'
int MXSymbolFree(SymbolHandle symbol) {
    ^
/home/user/Documents/lib/mxnet_android/amalgamation/../src/c_api/c_api_symbolic.cc:161:5: note: previous definition is here
int MXSymbolFree(SymbolHandle symbol) {
    ^
In file included from jni/predictor.cc:4:
jni/../mxnet_predict-all.cc:48914:5: error: redefinition of 'MXSymbolCopy'
int MXSymbolCopy(SymbolHandle symbol, SymbolHandle *out) {
    ^
/home/user/Documents/lib/mxnet_android/amalgamation/../src/c_api/c_api_symbolic.cc:165:5: note: previous definition is here
int MXSymbolCopy(SymbolHandle symbol, SymbolHandle *out) {
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
21 warnings and 20 errors generated.
make: *** [jni_libmxnet_predict.o] Error 1
```

**Comment by edmBernard** [comment]
It seem amalgamation don't expand correctly several *.cc file 
there is `dmlc-core/src/data.cc` but also some from `src/c_api/c_api_*.cc`

I don't see why.

**Comment by edmBernard** [comment]
I managed to compile amalgamation, my step : 
```
# make standalone toolchain for android
android-ndk-r15/build/tools/make_standalone_toolchain.py --arch arm  --api 21 --install-dir android_compiler_armv7_32bit --stl=libc++ --force
export PATH=/home/user/Documents/lib/android_compiler_armv7_32bit/bin/:$PATH
# OpenBLAS
cd $PATH_TO_OPENBLAS
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 libs
# mxnet amalgamation
cd $PATH_TO_MXNET/amalgamation
# edit Makefile to add OpenBLAS Path
make mxnet_predict-all.cc
export CC=arm-linux-androideabi-clang
export CXX=arm-linux-androideabi-clang++
# fopen64 is not known, I replace them by std::fopen in mxnet_predict-all.cc
make ANDROID=1
```

To do in this order or it will not work. 
`make mxnet_predict-all.cc` don't work correctly after `export CC=...` and `export CXX=...`

If you have a more straightforward solution, I'll take it.

**Comment by ZaccurLi** [comment]
I followed your method to compile amalgamation step by step:
`# make standalone toolchain for android
android-ndk-r15/build/tools/make_standalone_toolchain.py --arch arm  --api 21 --install-dir android_compiler_armv7_32bit --stl=libc++ --force
export PATH=/home/user/Documents/lib/android_compiler_armv7_32bit/bin/:$PATH
# OpenBLAS
cd $PATH_TO_OPENBLAS
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1 libs
# mxnet amalgamation
cd $PATH_TO_MXNET/amalgamation
# edit Makefile to add OpenBLAS Path
make mxnet_predict-all.cc
export CC=arm-linux-androideabi-clang
export CXX=arm-linux-androideabi-clang++
# fopen64 is not known, I replace them by std::fopen in mxnet_predict-all.cc
make ANDROID=1`
and get one error `#include <dmlc-core/src/data.cc>`
then I add the CLFAGS as you give, but there are lots of symol redefinition.

Can you give the whole steps in details?
Thx

**Comment by edmBernard** [comment]
I got the same issu when I define cross compilator before the construction of `mxnet_predict-all.cc`
I don't know why. 
in my step : 
```
export CC=/usr/bin/clang  # the normal one (x86)
export CC=/usr/bin/clang++  # the normal one (x86)
make mxnet_predict-all.cc
export CC=arm-linux-androideabi-clang
export CXX=arm-linux-androideabi-clang++
# fopen64 is not known, I replace them by std::fopen in mxnet_predict-all.cc
make ANDROID=1
```

**Comment by ZaccurLi** [comment]
@edmBernard 
I `make mxnet_predict-all.cc` before export CC, but the default compiler in my computer is gcc. I think this is why I cannot succeed compling it by your steps.
I have compiled amalgamation successfully, and put the steps at #7146 
[How to compile Amalgamation for android?](https://github.com/dmlc/mxnet/issues/7146)

Anyway, thanks a lot!
