### ISSUE TITLE
Revert on old mxnet version v0.9.5

### ISSUE THREAD

**Issue by edmBernard** [dmlc/mxnet#6891]
Since the change of the cub module from NVlab to dmlc.
I was not able to go on previous version due to issues with commit hash. 
Did you know how I can go back to v0.9.5.

**Comment by piiswrong** [comment]
try directly clone with tag v0.9.5

**Comment by edmBernard** [comment]
thanks, it seem to work. 
`git clone --recursice --branch v0.9.5 https://github.com/dmlc/mxnet.git`

**Comment by edmBernard** [comment]
In fact, It don't work. The cub history was not imported by the clone command.
I fix the problem with : 
```
git clone  --branch v0.9.5 https://github.com/dmlc/mxnet.git
cd mxnet/cub
git fetch --unshallow
cd ..
git submodule --init --recursive
```
