### ISSUE TITLE
need to download VS 2013 Redistributable Packages for windows CPU version

### ISSUE THREAD

**Issue by phunterlau** [dmlc/mxnet#692]
got this reminder from a weibo post http://www.weibo.com/u/1994147141 that windows CPU version needs https://www.microsoft.com/en-us/download/details.aspx?id=40784 we should update the installation instruction with this. Thanks.

**Comment by hjk41** [comment]
I thought I fixed it...

The latest version of the binary are linked with static runtime library.
Let me try it on a clean machine.

On Mon, Nov 23, 2015 at 4:04 PM, Hongliang Liu <notifications@github.com>
wrote:

> got this reminder from a weibo post http://www.weibo.com/u/1994147141
> that windows CPU version needs
> https://www.microsoft.com/en-us/download/details.aspx?id=40784 we should
> update the installation instruction with this. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/692>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by thirdwing** [comment]
I need this when building R package with binary file last Sunday.

It is a definitely clean Windows server on AWS. But this VS runtime should have been installed on most Windows machines, since many applications need it.

**Comment by hjk41** [comment]
thanks for reporting this issue. I will fix it in the next release

On Wed, Nov 25, 2015 at 1:02 PM, Qiang Kou (KK) <notifications@github.com>
wrote:

> I need this when building R package with binary file last Sunday.
>
> It is a definitely clean Windows server on AWS. But this VS runtime should
> have been installed on most Windows machines, since many applications need
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/692#issuecomment-159492382>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
The library needed is actually vcomp120.dll, which unfortunately cannot be
statically linked. I will figure out if we can include it in the package.
(if license allows us).

On Wed, Nov 25, 2015 at 2:02 PM, Chuntao HONG <chuntao.hong@gmail.com>
wrote:

> thanks for reporting this issue. I will fix it in the next release
>
> On Wed, Nov 25, 2015 at 1:02 PM, Qiang Kou (KK) <notifications@github.com>
> wrote:
>
>> I need this when building R package with binary file last Sunday.
>>
>> It is a definitely clean Windows server on AWS. But this VS runtime
>> should have been installed on most Windows machines, since many
>> applications need it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/dmlc/mxnet/issues/692#issuecomment-159492382>.
>>
>
>
>
> --
> HONG Chuntao
> System Research Group
> Microsoft Research Asia
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
This should have been fixed. I included vcomp120.dll in the new packages.
