### ISSUE TITLE
Fail Install Mxnet Windows 10

### ISSUE THREAD

**Issue by Statislove** [dmlc/mxnet#6930]
Fail of install
I use this guide https://gist.github.com/thirdwing/89aa9bfc588ade138496e6932072152c

Fail on command 
`R CMD INSTALL --no-multiarch R-package`

C:\GPU\mxnet>R CMD INSTALL --no-multiarch R-package
* installing to library 'C:/Users/Statislove/Documents/R/win-library/3.4'
* installing *source* package 'mxnet' ...
** libs
make: Nothing to be done for `all'.
installing to C:/Users/Statislove/Documents/R/win-library/3.4/mxnet/libs/x64
** R
** demo
** inst
** preparing package for lazy loading
** help
No man pages found in package  'mxnet'
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for 'mxnet':
 .onLoad failed in loadNamespace() for 'mxnet', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: не могу загрузить разделяемый объект 'C:/Users/Statislove/Documents/R/win-library/3.4/mxnet/libs/x64/libmxnet.dll':
  LoadLibrary failure:  Не найден указанный модуль.

Ошибка: загрузка не удалась
Выполнение остановлено
ERROR: loading failed
* removing 'C:/Users/Statislove/Documents/R/win-library/3.4/mxnet'

What is mistake?

**Comment by thirdwing** [comment]
It seems R can't load the shared lib.

I am sorry I can't figure out where is the error from the log you provided.

Can you try to install the prebuilt pkg to see if it works?

```r
cran <- getOption("repos")
cran["dmlc"] <- "https://s3.amazonaws.com/mxnet-r/GPU"
options(repos = cran)
install.packages("mxnet")
```

**Comment by Statislove** [comment]
Thank, i setup mxnet. Really, i think it's not possible. To install, i make magic steps with UBUNTU.
But now i'm really happy 👍

**Comment by thirdwing** [comment]
I am closing this now. Feel free to reopen if necessary.
