### ISSUE TITLE
creating a new loss layer with python API

### ISSUE THREAD

**Issue by fhowen** [dmlc/mxnet#694]
Hi,I'm trying to use python API to write a new loss layer.I found the example here:examples/numpy-op/numpy_softmax.py
but I have a question:
(1)in the backward, the in_grad parameter ,how did it get the initial value?
(2)I read the code in /src/operator/softmax-inl.h ,and I found the function SoftmaxGrad(grad,out,label),but I can't find the implemention of it ,so how does this work?

thanks.

**Comment by fhowen** [comment]
@piiswrong

**Comment by piiswrong** [comment]
1) in_grad is grad for input, or bottom_grad. out_grad is from top. It's uninitialized if need_top_grad=False, i.e. for loss layer. Otherwise it comes from layers above.
2) It's in mshadow/cuda/tensor-gpu.cuh
