### ISSUE TITLE
R-package: handling of incomplete batches by mx.io.arrayiter

### ISSUE THREAD

**Issue by MarkusBonsch** [dmlc/mxnet#6941]
Hello,

as far as I understand, the python version of the array data iter `mxnet.io.NDarrayiter` provides an argument for determining the handlig of the last batch `last_batch_handle`
The R version `mx.io.arrayiter` seems not to provide this. 
This raises two questions for me:
1. Is it correct that in R the last batch is always padded?
2. If yes, does the default function `mx.model.train` train on the random padded data since it doesn't seem to discard the last batch?

**Comment by thirdwing** [comment]
You can find how we did in https://github.com/dmlc/mxnet/blob/master/R-package/src/io.cc#L98-L103

The `last_batch_handle` parameter can be added if necessary.

**Comment by MarkusBonsch** [comment]
Dear thirdwing,

thank you very much for your quick answer.
There is no need to add the argument for my purpose, thank you.

But I still do not fully understand the behaviour. Maybe you can clarify.

As far as I can read from the C code, all batches are initialized with 0s: `batch.resize(batch_size * line_size, 0.0f)`. 
Then, only existing data is overwritten: `size_t end = std::min(order.size(), begin + batch_size);`.
 Therefore, I would assume that incomplete batches are padded by 0. However, testing the behaviour in R reveals that the data from the previous batch is repeated if a batch is incomplete:

```
library(mxnet)

## check what an iterator does with non-complete batches
dat <- matrix(1:10, nrow = 1)

test <- mx.io.arrayiter(data = dat, label = dat, batch.size = 3, shuffle = FALSE)

test$reset()
nbatch <- 1
while(test$iter.next()){
  cat("batch: ", nbatch, "\n")
  print(as.array(test$value()$data))
  nbatch <- nbatch + 1
}
## batch:  1 
##     [,1] [,2] [,3]
##[1,]    1    2    3
##batch:  2 
##     [,1] [,2] [,3]
##[1,]    4    5    6
##batch:  3 
##     [,1] [,2] [,3]
##[1,]    7    8    9
##batch:  4 
##     [,1] [,2] [,3]
##[1,]   10    8    9
```

Thank you for your help,

Markus

**Comment by thirdwing** [comment]
I think this is expected behavior.

Just use your example:

(1) begin = 0, end = 3, before memcpy batch = {0, 0, 0}, after memcpy batch = {1, 2, 3}

(2) begin = 3, end = 6, before memcpy batch = {1, 2, 3}, after memcpy batch = {4, 5, 6}

(3) begin = 6, end = 9, before memcpy batch = {4, 5, 6}, after memcpy batch = {7, 8, 9}

(4) begin = 9, end = 10, before memcpy batch = {7, 8, 9}, after memcpy batch = {10, 8, 9}

**Comment by MarkusBonsch** [comment]
Great explanation. 
Thank you very much for the excellent support.

I wasn't aware that the batch is only initialized once to 0 and then just overwritten in the desired positions.

Thanks again.
