### ISSUE TITLE
Is mxnet symbol support conditional control flow?

### ISSUE THREAD

**Issue by Zehaos** [dmlc/mxnet#6968]
I want to add some conditional control in my symbol, it seems that if-else is evaluated in symbol construction time. But I want it to evaluated in symbol run time.
```
a = mx.symbol.Variable(name='a')
b = mx.symbol.Variable(name='b')

if a>b:
    c = a-b
else:
    c = a+b
```
TensorFlow provides the tf.cond() operator to deal with it, is there a counterpart in mxnet?

**Comment by CNevd** [comment]
mx.symbol.where

**Comment by Zehaos** [comment]
@CNevd From the  [doc mx.symbol.where](http://mxnet.io/api/python/symbol.html), I know that *mx.symbol.where* is somewhat limited, it return elements from x or y.

**Comment by CNevd** [comment]
Yeah you can let x=a-b and y=a+b

**Comment by Zehaos** [comment]
@CNevd Yes, but it is lack of generalization.

**Comment by Godricly** [comment]
if you can precompute those conditions. bucketing is a good choice.

**Comment by Zehaos** [comment]
@Godricly @CNevd  Thanks for your advice.

**Comment by jiang1st** [comment]
Hi, I am new to mxnet. Now I want to add some conditional control in my network. I notice that sym.where can do this work by:

```
f_x = a - b
f_y = a + b

result = mx.sym.where(condition=gt, f_x, f_y)
```

I am curious to know, in the above example, if the condition is true, will f_y=a+b be executed ? (maybe f_y is executed but the result will not be returned? )

I read the example of tensorflow, the explanation is quite clear:

```
z = tf.multiply(a, b)
result = tf.cond(x < y, lambda: tf.add(x, z), lambda: tf.square(y))
```
> If x < y, the tf.add operation will be executed and tf.square operation will not be executed.


So, is mx.sym.where equivalent to tf.cond? Thanks.

**Comment by Godricly** [comment]
take a try with gluon. symbol is a bit old and less convenient.

**Comment by jiang1st** [comment]
@Godricly Thanks. But moving my project from symbol to gluon might a hard work.
