### ISSUE TITLE
train and save on gpu(1), load error on gpu(0)

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#699]
I trained a network on gpu(1) in server, and saved the parameters with cPickle, now I set the context be gpu(0) in my laptop and tried to read the trained parameters with cPickle, then I encounter the following error:
```
[10:35:49] ./dmlc-core/include/dmlc/logging.h:208: [10:35:49] ./mshadow/mshadow/./tensor_gpu-inl.h:35: Check failed: e == cudaSuccess CUDA: invalid device ordinal
```
I guess it is caused by the difference of context.
How to solve it?

**Comment by mli** [comment]
probably due to 1) gpu(0) is not available on your laptop, or 2) you still bind the model into gpu(1) on your laptop

**Comment by starimpact** [comment]
no, no.
I can do train on gpu(0) of my laptop.

**Comment by starimpact** [comment]
no,no.
if I load the parameters trained on gpu(0) of server, it will have no any problem. My laptop only have one gpu.

**Comment by jermainewang** [comment]
Could you provide more details about the problem? Like the code snipplet? so we could give further help.

**Comment by starimpact** [comment]
OK, I will give a code snippet.

**Comment by starimpact** [comment]
for example:
```python
import mxnet as mx
import cPickle
def write_onserver():
    ctxdev = mx.gpu(1)
    num = mx.nd.ones((10, 4), ctx=ctxdev)
    cPickle.dump(num, open('hi.bin', 'wb'))

def read_onlaptop():
    num = cPickle.load(open('hi.bin', 'rb'))
    print num.asnumpy()
```
run  ```write_onserver``` on the gpu1 of server(server has several gpus). and then copy the ```hi.bin``` to the local laptop. my laptop only have 1 gpu, then run ```read_onlaptop```. It will be failed.
But, If I run ```write_onserver``` on the gpu0 of server, and then copy ```hi.bin``` to the local laptop. then run ```read_onlaptop```. It will be success.

**Comment by tqchen** [comment]
This is because pickle is being royal to the device of the array. You can copy the parameters to cpu first before you save the parameters, which is lone additional line. This is also what was happening in the background when you pickle

```python
numcpu = num.copyto(mx.cpu())
cPickle.dump(num, open('hi.bin', 'wb'))
```

**Comment by starimpact** [comment]
thanks very much @tqchen
