### ISSUE TITLE
Multiple GPUs training failed

### ISSUE THREAD

**Issue by tfwu** [dmlc/mxnet#6990]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04 LTS and 14.04LTS

Compiler:

Package used (Python/R/Scala/Julia):

MXNet version: 

Or if installed from source: Yes

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution: python 2.7

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

[22:38:21] src/mxnet/dmlc-core/include/dmlc/./logging.h:304: [22:38:21] src/mxnet/mshadow/mshadow/./stream_gpu-inl.h:55: Check failed: e == cudaSuccess CUDA: an illegal memory access was encountered

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

run the provided example/rcnn with multiple GPUs

**Comment by eldercrow** [comment]
Try reverting #6954 and see if it works. I've just made a comment on that commit.
