### ISSUE TITLE
I used pip and anaconda2 to install MXNet, and now how can I install torch plugin?

### ISSUE THREAD

**Issue by freshmanfresh** [dmlc/mxnet#6991]
When I install MXNet, I used anaconda2 and pip.  I also install torch correctly. Now, I want to use MXNet as the frontend of torch, how can I install the torch plugin? (That is, how I can connect MXNet with torch?)
Thanks a lot!

**Comment by githubfragments** [comment]
Do you successfully use torch for Mxnet?
