### ISSUE TITLE
How to get the data in symbol？？

### ISSUE THREAD

**Issue by DoubleKing0625** [dmlc/mxnet#7037]
I think，the definition of symbol in mxnet is just like the Variable in pytorrch.
In pytorch, i can use Variable.data to visit the original tensor values, now i want to do same thint in mxnet. Buuut i can't find API which can deal this task. 
So anyone knows it?

**Comment by Soonhwan-Kwon** [comment]
Symbol does not have data inside, but module's get_params() does have information you want.
as http://mxnet.io/api/python/module.html#mxnet.module.BaseModule.get_params
have tensor values you want.
```
print mod.get_params()
args_params, aux_params = mod.get_params()
args_params['key_you_want_to_see'].asnumpy()
```
