### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Orange15** [dmlc/mxnet#704]
there is an error when update to master. (mac osx clang)
thanks.

In file included from src/operator/embedding.cc:8:
src/operator/./embedding-inl.h:60:11: error: use of undeclared identifier 'take'
    out = take(data, wmat);
          ^
src/operator/./embedding-inl.h:42:12: note: in instantiation of member function 'mxnet::op::EmbeddingOp<mshadow::cpu>::Forward'
      requested here
  explicit EmbeddingOp(EmbeddingParam p) {
           ^
src/operator/embedding.cc:13:14: note: in instantiation of member function 'mxnet::op::EmbeddingOp<mshadow::cpu>::EmbeddingOp'
      requested here
  return new EmbeddingOp<cpu>(param);
             ^
In file included from src/operator/embedding.cc:8:
src/operator/./embedding-inl.h:81:15: error: use of undeclared identifier 'take_grad'
    grad_in = take_grad(data, grad_out, param_.input_dim);
              ^
src/operator/./embedding-inl.h:42:12: note: in instantiation of member function 'mxnet::op::EmbeddingOp<mshadow::cpu>::Backward'
      requested here
  explicit EmbeddingOp(EmbeddingParam p) {
           ^
src/operator/embedding.cc:13:14: note: in instantiation of member function 'mxnet::op::EmbeddingOp<mshadow::cpu>::EmbeddingOp'
      requested here
  return new EmbeddingOp<cpu>(param);
             ^

**Comment by yang1fan2** [comment]
It seems that you have to update your mshadow code. The newest mshadow added function "take" and "take_grad"
In git, type commands below
"
git submodule init
git submodule update
"
Hope this will help
