### ISSUE TITLE
How to move mxnet into TK1?

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#705]
there are some features which TK1 doesn't support.
such as msse3.
is there any easy configure method?

**Comment by starimpact** [comment]
remove msse3 and MSHADOW_USE_SSE.

**Comment by tqchen** [comment]
As you can see this is due to CUDNN turned on, compile without CuDNN should work

**Comment by thirdwing** [comment]
Actually I have compiled mxnet on TK1 without CuDNN weeks ago.

**Comment by starimpact** [comment]
cudnn is fast, will it affect the performance by disable it?

**Comment by thirdwing** [comment]
I met some issues when I tried to use cudnn with Theano on TK1, so I disabled it this time.

I can have some test in the weekends.

**Comment by starimpact** [comment]
compiling passed, but there is strange link error:
```
dmlc-core/libdmlc.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1
```

**Comment by starimpact** [comment]
@thirdwing Can you tell what did you do when you moved mxnet into TK1?

**Comment by starimpact** [comment]
problem is solved.
the reason is that dmlc-core can't be cleaned when use ```make clean``` under the mxnet.

**Comment by thirdwing** [comment]
@starimpact Congrats! I started from `git clone` and I think that's why I didn't met this problem.
