### ISSUE TITLE
make error with opencv .. thank you ..

### ISSUE THREAD

**Issue by guotong1988** [dmlc/mxnet#706]
Package opencv-2.0.0-12.el6.x86_64 already installed and latest version
Nothing to do
[root@localhost mxnet]# make
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -MM -MT build/io/io.o src/io/io.cc >build/io/io.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -c src/io/io.cc -o build/io/io.o
In file included from src/io/io.cc:5:0:
src/io/./image_augmenter.h:10:30: 致命错误：opencv2/opencv.hpp：没有那个文件或目录
编译中断。
make: *** [build/io/io.o] 错误 1

**Comment by piiswrong** [comment]
where is your opencv installed? if not in the standard directory you'll need to add it to CFLAGS and LDFLAGS.

Also, I'm not sure about this is relevant by opencv 2.0 seems too old

**Comment by guotong1988** [comment]
Thank you . I finally solve this problem by download the OpenCV tar and make && install it

**Comment by guotong1988** [comment]
/usr/bin/ld: cannot find -lcblas
collect2: 错误：ld 返回 1
make: *** [lib/libmxnet.so] 错误 1

**Comment by guotong1988** [comment]
/usr/bin/ld: /usr/lib/../lib64/libcblas.a(cblas_sgemm.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/../lib64/libcblas.a: could not read symbols: Bad value
collect2: 错误：ld 返回 1
make: *** [lib/libmxnet.so] 错误 1

**Comment by piiswrong** [comment]
which blas are you using. Could you try atlas? sudo apt-get install libatlas-dev and change USE_BLAS to atlas

**Comment by tqchen** [comment]
It was due to blas was not dynamically compiled, you might need to switch to openblas or other BLAS, please feel free to reopen if necessary

**Comment by skevidu** [comment]
openblas works for me and I use opencv3.
