### ISSUE TITLE
ReadTheDocs Documentation Not Versioned

### ISSUE THREAD

**Issue by JosephCatrambone** [dmlc/mxnet#707]
The documentation versions listing and build listings displays only numerous copies of "Versions:
latest."  (See also: https://readthedocs.org/projects/mxnet/builds/)  

This isn't terribly cumbersome right now, as there appears only to be mxnet==0.5a1, 0.5a2, and 0.5a3 in Pip at the moment, but as the project grows it could become tricky to keep things in order.  Perhaps just a datetime stamp or release tag?

**Comment by xgdgsc** [comment]
+1. Do you recommend to use master always? Providing release tags would make it easier for users to try.
