### ISSUE TITLE
R Package Installation fails

### ISSUE THREAD

**Issue by aussetg** [dmlc/mxnet#708]
OS : Debian Unstable
R : 3.2.2
CUDA : 7.5
cuDNN : r3
compiler : gcc-4.9 ( forced to match nvcc )

python example/image-classification/train_mnist.py  WORKS
R CMD INSTALL mxnet_0.5.tar.gz FAILS

Log : https://gist.github.com/aussetg/feccb9cb0ff19e55506a

Thanks, please ask for any other informations

**Comment by thirdwing** [comment]
I think this is due to the `-fstack-protector-strong` flag you are using.

Can you remove it and try again?

**Comment by aussetg** [comment]
I'll do it tomorrow. I also think it's the cause. 

I'm using all the default options btw, I'll see if it's an Mxnet option, Rcpp option or R option and report back

Thanks

**Comment by thirdwing** [comment]
It should be from R. Maybe you can check the file `/etc/R/Makeconf`

**Comment by aussetg** [comment]
Yes I checked.

#Grep
`guillaume ) grep stack /etc/R/Makeconf
# configure  '--prefix=/usr' '--with-cairo' '--with-jpeglib' '--with-readline' '--with-tcltk' '--with-system-bzlib' '--with-system-pcre' '--with-system-zlib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--datadir=/usr/share/R/share' '--includedir=/usr/share/R/include' '--with-blas' '--with-lapack' '--enable-R-profiling' '--enable-R-shlib' '--enable-memory-profiling' '--without-recommended-packages' '--build' 'x86_64-linux-gnu' 'build_alias=x86_64-linux-gnu' 'R_PRINTCMD=/usr/bin/lpr' 'R_PAPERSIZE=letter' 'R_BROWSER=xdg-open' 'LIBnn=lib' 'JAVA_HOME=/usr/lib/jvm/default-java' 'CC=gcc -std=gnu99' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=' 'F77=gfortran' 'FFLAGS=-g -O2 -fstack-protector-strong' 'CXX=g++' 'CXXFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g' 'FC=gfortran' 'FCFLAGS=-g -O2 -fstack-protector-strong'
CFLAGS = -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g $(LTO)
CXXFLAGS = -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g $(LTO)
CXX1XFLAGS = -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g
FCFLAGS = -g -O2 -fstack-protector-strong $(LTO)
FFLAGS = -g -O2 -fstack-protector-strong $(LTO)
SAFE_FFLAGS = -g -O2 -fstack-protector-strong -ffloat-store`

I added

`CFLAGS=-g -O2 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g
CXXFLAGS=-g -O2 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g
CXXXFLGAGS=-g -O2 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g`

to `~/.R/Makevars`

The package then compiles but fails to load, R crashes. I'll continue to investigate

**Comment by thirdwing** [comment]
Can you post the new log?

**Comment by aussetg** [comment]
I'll try to replicate it, it didn't give any errors at the time, just hanged until manually killed.

Apparently I can install the R package by using GCC 5.2 ( so the version R / RCpp was built against ) and everything works as long as you use mx.cpu(). If you try to use mx.gpu() the error is:

    Start training with 1 devices
    [18:48:34] ./dmlc-core/include/dmlc/././logging.h:208: [18:48:34] src/storage/storage.cc:43: Please compile with CUDA enabled
    Erreur : [18:48:34] src/storage/storage.cc:43: Please compile with CUDA enabled

I wonder if some file wasn't updated correctly because libmxnet.so definitely includes the CUDA symbols.

I nuked my mxnet folder and recloned it cleanly to rebuild it, currently there seems to be some problems with the compilation so if it doesn't work I'll just revert to yesterday commits

**Comment by thirdwing** [comment]
Sorry for this.

I am on travel now and I will look into this more closely after coming back to lab.
