### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by jjaskulowski** [dmlc/mxnet#7091]
> install.packages("mxnet")
Installing package into ‘C:/Users/Jaroslaw/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  dependencies ‘DiagrammeR (>= 0.9.0)’, ‘visNetwork (>= 1.0.3)’ are not available
Warning in install.packages :
  cannot open URL 'https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/bin/windows/contrib/3.2/PACKAGES.gz': HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open URL 'https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/bin/windows/contrib/3.2/PACKAGES': HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/bin/windows/contrib/3.2:
  cannot open URL 'https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/bin/windows/contrib/3.2/PACKAGES'
Pakiet, który jest dostępny jedynie w formie źródłowej i może wymagać kompilacji
  C/C++/Fortran: ‘mxnet’
  These will not be installed

**Comment by thirdwing** [comment]
Sorry that mxnet requires R >= 3.3.0

See https://github.com/dmlc/mxnet/blob/master/R-package/DESCRIPTION#L31
