### ISSUE TITLE
Scala mnist tutorial does not compile

### ISSUE THREAD

**Issue by kottmann** [dmlc/mxnet#7101]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
MXNet version:
Latest master verion

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

`error: value argmaxChannel is not a member of object ml.dmlc.mxnet.NDArray
[INFO]     val predictedY = NDArray.argmaxChannel(prob)`

**Comment by madjam** [comment]
@kottmann since your PR is merged, can this be closed now?
