### ISSUE TITLE
[gluon] Using mxnet evaluation metrics in gluon

### ISSUE THREAD

**Issue by jsamson008** [dmlc/mxnet#7110]
I was wondering if it was already easy to use mxnet.metric as the loss function in place of defining my own or using the gluon loss. For instance, I would prefer to use the mx.metric perplexity. 

Currently, I am defining my own loss function which calls the perplexity class, but this seems like a feature that would be good to have in gluon.

**Comment by piiswrong** [comment]
metric is in principle separate from loss. You can use all kinds of metrics to measure classification accuracy and you can use all kinds of loss to optimize classifier. They are not necessarily connected.

**Comment by jsamson008** [comment]
yup got it.
Thanks
