### ISSUE TITLE
 error: identifier "take" is undefined

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#712]
/search/data/user/qhj/github/mxnet/src/operator/./embedding-inl.h(60): error: identifier "take" is undefined
          detected during:
            instantiation of "void mxnet::op::EmbeddingOp<xpu>::Forward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with xpu=mxnet::gpu]" 
(44): here
            implicit generation of "mxnet::op::EmbeddingOp<xpu>::~EmbeddingOp() [with xpu=mxnet::gpu]" 
(44): here
            instantiation of class "mxnet::op::EmbeddingOp<xpu> [with xpu=mxnet::gpu]" 
(44): here
            instantiation of "mxnet::op::EmbeddingOp<xpu>::EmbeddingOp(mxnet::op::EmbeddingParam) [with xpu=mxnet::gpu]" 
/search/data/user/qhj/github/mxnet/src/operator/embedding.cu(13): here

/search/data/user/qhj/github/mxnet/src/operator/./embedding-inl.h(81): error: identifier "take_grad" is undefined
          detected during:
            instantiation of "void mxnet::op::EmbeddingOp<xpu>::Backward(const mxnet::OpContext &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &, const std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob>> &) [with xpu=mxnet::gpu]" 
(44): here
            implicit generation of "mxnet::op::EmbeddingOp<xpu>::~EmbeddingOp() [with xpu=mxnet::gpu]" 
(44): here
            instantiation of class "mxnet::op::EmbeddingOp<xpu> [with xpu=mxnet::gpu]" 
(44): here
            instantiation of "mxnet::op::EmbeddingOp<xpu>::EmbeddingOp(mxnet::op::EmbeddingParam) [with xpu=mxnet::gpu]" 
/search/data/user/qhj/github/mxnet/src/operator/embedding.cu(13): here

2 errors detected in the compilation of "/tmp/tmpxft_00023fa5_00000000-7_embedding.cpp1.ii".
CMake Error at cuda_compile_generated_embedding.cu.o.cmake:266 (message):
  Error generating file
  /search/data/user/qhj/github/mxnet/build/CMakeFiles/cuda_compile.dir/src/operator/./cuda_compile_generated_embedding.cu.o

make[2]: *** [CMakeFiles/cuda_compile.dir/src/operator/cuda_compile_generated_embedding.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/search/data/user/qhj/github/mxnet/mshadow/mshadow/tensor.h: In static member function ?.tatic mshadow::Shape<ndim> mshadow::expr::ShapeCheck<dim, mshadow::expr::BinaryMapExp<OP, TA, TB, DType, etype> >::Check(const mshadow::expr::BinaryMapExp<OP, TA, TB, DType, etype>&) [with int dim = 2; OP = mshadow::op::mul; TA = mshadow::expr::BinaryMapExp<mshadow::op::mul, mshadow::Tensor<mshadow::gpu, 2, float>, mshadow::expr::BinaryMapExp<mxnet::op::mshadow_op::power, mshadow::Tensor<mshadow::gpu, 2, float>, mshadow::expr::BinaryMapExp<mshadow::op::minus, mshadow::Tensor<mshadow::gpu, 2, float>, mshadow::expr::ScalarExp<float>, float, 1>, float, 1>, float, 1>; TB = mshadow::Tensor<mshadow::gpu, 2, float>; DType = float; int etype = 1]?.
/search/data/user/qhj/github/mxnet/mshadow/mshadow/tensor.h:67:1: warning: ?.hape2.mshadow::Shape<2>::shape_[1u]?.may be used uninitialized in this function [-Wmaybe-uninitialized]
       this->shape_[i] = s[i];
 ^
/search/data/user/qhj/github/mxnet/mshadow/mshadow/././expr_engine-inl.h:361:13: note: ?.hape2?.was declared here
     Shape<dim> shape2 = ShapeCheck<dim, TB>::Check(t.rhs_);
             ^
make[1]: *** [CMakeFiles/mxnet.dir/all] Error 2
make: *** [all] Error 2

**Comment by qiaohaijun** [comment]
centos 7.1 
g++ 4.8

**Comment by qiaohaijun** [comment]
# cd MXNET_ROOT
# grep take_grad -r .
# ./src/operator/embedding-inl.h:    grad_in = take_grad(data, grad_out, param_.input_dim);

just find the use grad_in ,but not find the code grad_in that the function defined

**Comment by piiswrong** [comment]
You need to update your mshadow library.
Try git submodule update

**Comment by qiaohaijun** [comment]
ok,problem fixed

**Comment by qiaohaijun** [comment]
please close this issuse
