### ISSUE TITLE
fresh installation of mxnet, nothing worked??

### ISSUE THREAD

**Issue by yliu7366** [dmlc/mxnet#7135]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04
Compiler:
gcc 
Package used (Python/R/Scala/Julia):
python
MXNet version:
mxnet-0.10.0.post2-py2.py3-none-manylinux1_x86_64.whl
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

Following mxnet offical tutorials (http://mxnet.io/tutorials/gluon/2-autograd.html) but found almost nothing worked, autograd is in mxnet.contrib instead of mxnet as listed in tutorial. attach_grad() is visible in API documentation but not available in python environment? Looks like documentation and actual code are completely unmatched, what's wrong?

>>> import mxnet as mx
>>> import mxnet.ndarray as nd
>>> import mxnet.autograd as ag
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named autograd
>>> import mxnet.contrib.autograd as ag
>>> x = mx.nd.array([[1,2],[3,4]])
>>> x.attach_grad()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NDArray' object has no attribute 'attach_grad'

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

**Comment by piiswrong** [comment]
You need to use nightly pre-release to use gluon
pip install mxnet-xxx --pre
