### ISSUE TITLE
[mxnet compile error] "/usr/bin/ld: cannot find -lnnpack" with NNPACK successfully installed

### ISSUE THREAD

**Issue by xingzhaoo** [dmlc/mxnet#7142]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: CentOS 7

Compiler: gcc 4.8.5 20150623

Package used (Python/R/Scala/Julia): Python

MXNet version: 

Or if installed from source: yes, used git to get the latest version

MXNet commit hash (`git rev-parse HEAD`): N/A

If you are using python package, please provide

Python version and distribution: 2.7.5 ,  virtualenv

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

 build/src/c_api/c_api_executor.o build/src/c_api/c_predict_api.o build/src/c_api/c_api.o build/src/c_api/c_api_error.o build/src/executor/inplace_addto_detect_pass.o build/src/executor/graph_executor.o build/src/executor/attach_op_execs_pass.o build/src/executor/attach_op_resource_pass.o build/src/kvstore/kvstore.o build/src/resource.o build/src/initialize.o /local/data1/users/shane/mxnet/ps-lite/build/libps.a /local/data1/users/shane/mxnet/dmlc-core/libdmlc.a /local/data1/users/shane/mxnet/nnvm/lib/libnnvm.a -pthread -lm -lopenblas -fopenmp -lrt -L/local/data1/users/shane/lib -lopencv_dnn -lopencv_ml -lopencv_objdetect -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_imgproc -lopencv_flann -lopencv_core -lnnpack  -lopencv_core -lopencv_imgproc -lopencv_imgcodecs /local/data1/users/shane/mxnet/deps/lib/libprotobuf-lite.a /local/data1/users/shane/mxnet/deps/lib/libzmq.a
**/usr/bin/ld: cannot find -lnnpack
collect2: error: ld returned 1 exit status
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lnnpack
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1**

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. followed procedures to install NNPACK at https://github.com/dmlc/mxnet/blob/75bc7c0cd5fd79b4e79787072412544f20b5f078/docs/how_to/nnpack.md

no error reported

2. cd mxnet
3. make -j8

error reported

## What have you tried to solve it?

1. Without NNPACK enabled (Set USE_NNPACK = 1 in config.mk), mxnet can be compiled and imported in python. All test py files under image-classification run successfully. OPENCV was installed and enabled.
2. looked up on MxNet source code, found Makefile under mxnet/ is related to this lnnpack in "opencv section"

**Comment by edmBernard** [comment]
To build mxnet with nnpack, I add these line in config.mk : 
```
# the additional link flags you want to add
ADD_LDFLAGS = -L/home/user/Documents/lib/NNPACK/lib

# the additional compile flags you want to add
ADD_CFLAGS = -I/home/user/Documents/lib/NNPACK/include -I/home/user/Documents/lib/NNPACK/third-party/pthreadpool/include
```
I made a dockerfile that compile mxnet with NNPACK. You can check if you the same things. [here](https://github.com/edmBernard/DockerFiles/blob/master/cpu/nnpack_mxnet/Dockerfile)

**Comment by xingzhaoo** [comment]
Thanks a lot @edmBernard . I was missing "ADD_LDFLAGS = -L/home/user/Documents/lib/NNPACK/lib" in config.mk
It's working now.
