### ISSUE TITLE
How to compile Amalgamation for android?

### ISSUE THREAD

**Issue by ZaccurLi** [dmlc/mxnet#7146]
# How to compile Amalgamation for android?
## Environment info
Operating System: `Ubuntu 14.04 64bit Desktop`
NDK vesion:  `android-ndk-r13b` or `android-ndk-r14b`
Compiler: `arm-linux-androideabi-clang++`
MXNet version: `v0.10.0`  or `v0.9.3`
MXNet commit hash : * master 799ed45

## Error Message:
```c
1. fatal error: src/c_api/c_api_error.cc: No such file or directory #include <src/c_api/c_api_error.cc>
2. fatal error: execinfo.h: No such file or directory  #include <execinfo.h>
3. error: use of undeclared identifier 'fopen64'; did you mean 'fopen'?
```
------
### Prepare:
***NDK Standalone ToolChain***:
```bash
cd yourpath/android-ndk-r13b/build/tools
python make_standalone_toolchain.py --arch arm --api 21 --install-dir yourpath/android-toolchain --stl=libc++  
```
***Download and Compile OpenBLAS***
```bash
export PATH=$PATH:yourpath/android-toolchain/bin 
git clone https://github.com/xianyi/OpenBLAS.git  
cd OpenBLAS  
make TARGET=ARMV7 HOSTCC=gcc CC=arm-linux-androideabi-gcc NOFORTRAN=1
make PREFIX=yourpath/openblas install
```
### Compile:
***Download Mxnet***
```bash
git clone --recursive https://github.com/dmlc/mxnet.git 
```
***Compile Amalgamation***
1.move into mxnet/amalgamation and prepare compile toolchain
```bash
cd mxnet/amalgamation
export PATH=$PATH:yourpath/android-toolchain/bin
export CC=arm-linux-androideabi-clang  
export CXX=arm-linux-androideabi-clang++  
```
2.modify OpenBLAS path  in mxnet/amalgamation/Makefile:(line 5)
```makefile
export OPENBLAS_ROOT=yourpath/openblas
```
3.add DEFS in mxnet/nnvm/amalgamation/Makefile:(line 2)
```makefile
DEFS+=-DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSHADOW_USE_SSE=0 -DDMLC_LOG_STACK_TRACE=0 -DMSHADOW_FORCE_STREAM -DMXNET_USE_OPENCV=0 -DMXNET_PREDICT_ONLY=1 -DDISABLE_OPENMP=1
export CFLAGS = -std=c++11 -Wall -O3 -Wno-unknown-pragmas -funroll-loops -Iinclude -fPIC $(DEFS)
```
4.add `#define fopen64 std::fopen` to *`Amalgamation.py(line 130)`* or *`mxnet_predict-all.cc(line 1)`*
4.1 In `Amalgamation.py`
```python
...
print >>f, '''
#define fopen64 std::fopen      #comment<<<<<<line:130
#if defined(__MACH__)
#include <mach/clock.h>
#include <mach/mach.h>
#endif
...
```
or 
4.2 In `mxnet_predict-all.cc`
```cc
#define fopen64 std::fopen      //comment<<<<<<line:1
#if defined(__MACH__)
...
```
5.compile amalgamation
```bash
make clean
make ANDROID=1
```
------
## Library
**Output: jni_libmxnet_predict.so**
copy jni_libmxnet_predict.so and libc++_shared.so to android project

**Comment by piiswrong** [comment]
Would you like to submit a pr for the fopen fix?

**Comment by edmBernard** [comment]
@ZaccurLi  when I retry to use your method I got an error on OpenBLAS compilation : 
```
/home/dev/lib/arm7-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lm_hard
```
how did you solve this problem ? 
It seem to be a removed functionnality since ndk12

**Comment by edmBernard** [comment]
I test it different ndk version : 
it work on android-ndk-12b, android-ndk-13b, android-ndk-14b
but don't work on android-ndk-15b

**Comment by edmBernard** [comment]
I made a Dockerfile to automate mxnet compilation for android and resume your process. 
https://github.com/edmBernard/DockerFiles/blob/master/cpu/android_mxnet/Dockerfile

**Comment by Corea** [comment]
Did you successfully run an android app with output library? I got following errors with version `0.10.0` built by `android-ndk-r14b` on `Mac OS X 10.12.5`.

- `cannot find "libopenblas.so"` (Solved)
- `cannot locate symbol "__emutls_v._ZN5mxnet8autograd15AutogradRuntime9is_train_E"`

**Comment by edmBernard** [comment]
not yet I'll test this week and give you feedback if it works (or not)

**Comment by vkhadir** [comment]
hi @Corea indeed with @edmBernard we had the same log error after adding ``libopenblas.so`` with the jniLibs list 
``java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_v._ZN5mxnet8autograd15AutogradRuntime9is_train_E" referenced by "/data/app/com.example.admin.mod-1/lib/arm/libmxnet_predict.so"...``

**Comment by edmBernard** [comment]
there is the same issue here : https://github.com/dmlc/mxnet/issues/7180

**Comment by Piyush3dB** [comment]
PR #7222 should fix this issue.  Please try it out.

**Comment by edmBernard** [comment]
thanks for your work I'll test it tomorrow

**Comment by MU001999** [comment]
where should copy the libc++_shared.so to? I copy it to jniLibs/armeabi and write `System.loadBinary("c++_shared");` in Predictor.java, but the app will stop when opening.

**Comment by eric-haibin-lin** [comment]
@arank


On 2017年9月13日, at 02:50, IceBo <notifications@github.com> wrote:

where should copy the libc++_shared.so to? I copy it to jniLibs/armeabi and write System.loadBinary("c++_shared"); in Predictor.java, but the app will stop when opening.

**Comment by novioleo** [comment]
@ZaccurLi 
i followed your tutorial step by step,i generated the predict.so successfully.but,i can't run my android application with it . because the symbol.json can't interpret rightly.
so,can you send me your complied predict.so,or help me with this problem?

**Comment by zhulihuacmss** [comment]
@Corea i have met the same problem 'can not find openblas.so', how did you solve it? thanks

**Comment by edmBernard** [comment]
@zhulihuacmss 
Hi, You have to change the path in amalgamation Makefile: [here](https://github.com/apache/incubator-mxnet/blob/master/amalgamation/Makefile#L23)

**Comment by YXLCN** [comment]
> @ZaccurLi when I retry to use your method I got an error on OpenBLAS compilation :
> 
> ```
> /home/dev/lib/arm7-toolchain/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lm_hard
> ```
> how did you solve this problem ?

I got this error too, could u tell me how to fix it?
