### ISSUE TITLE
AssertionError when generate rpn detetcion. Why does it show this error and how can I fix it?

### ISSUE THREAD

**Issue by MissDores** [dmlc/mxnet#7158]
INFO:root:########## GENERATE RPN DETECTION
voc_2007_trainval gt roidb loaded from /home/myname/DPNs/mxnet/example/rcnn/data/cache/voc_2007_trainval_gt_roidb.pkl
prepare roidb
Traceback (most recent call last):
  File "train_alternate.py", line 107, in <module>
    args.frequent, args.kv_store, args.work_load_list)
  File "train_alternate.py", line 35, in alternate_train
    test_rpn(image_set, year, root_path, devkit_path, 'model/rpn1', rpn_epoch, ctx[0])
  File "/home/myname/DPNs/mxnet/example/rcnn/tools/test_rpn.py", line 32, in test_rpn
    imdb_boxes = generate_detections(detector, test_data, voc, vis=vis)
  File "/home/myname/DPNs/mxnet/example/rcnn/rcnn/rpn/generate.py", line 55, in generate_detections
    for databatch in test_data:
  File  "/home/myname/DPNs/mxnet/example/rcnn/rcnn/loader.py", line 94, in next
    provide_data=self.provide_data, provide_label=self.provide_label)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/io.py", line 133, in __init__
    assert isinstance(data, (list, tuple)), "Data must be list of NDArrays"
AssertionError: Data must be list of NDArrays

@precedenceguo

**Comment by precedenceguo** [comment]
As the error says, check if the data is a list of NDArrays.

**Comment by MissDores** [comment]
This is what I get when I print 'self.data', and I think it is the shape of NDArrays. I don't know why the error raises. I just train the rcnn with PASCAL dataset and did not make any modification with the code. I really want to know what's wrong and how to fix it? Thank you very much.
```
{'data': array([[[[-113.68 , -112.68 , -110.68 , ...,   38.32 ,   37.32 ,   37.32 ],
         [-116.68 , -115.68 , -113.68 , ...,   38.32 ,   38.32 ,   38.32 ],
         [-117.68 , -117.68 , -115.68 , ...,   39.32 ,   39.32 ,   39.32 ],
         ...,
         [ -87.68 ,  -88.68 ,  -89.68 , ...,  -54.68 ,  -54.68 ,  -54.68 ],
         [ -80.68 ,  -77.68 ,  -74.68 , ...,  -54.68 ,  -54.68 ,  -54.68 ],
         [ -74.68 ,  -69.68 ,  -62.68 , ...,  -55.68 ,  -55.68 ,  -54.68 ]],

        [[-106.779, -105.779, -103.779, ...,   70.221,   69.221,   69.221],
         [-109.779, -107.779, -105.779, ...,   70.221,   70.221,   70.221],
         [-109.779, -108.779, -106.779, ...,   71.221,   71.221,   71.221],
         ...,
         [-107.779, -108.779, -108.779, ...,  -34.779,  -34.779,  -34.779],
         [-103.779, -102.779, -101.779, ...,  -33.779,  -33.779,  -32.779],
         [ -99.779,  -97.779,  -94.779, ...,  -33.779,  -33.779,  -32.779]],

        [[ -93.939,  -92.939,  -90.939, ...,   90.061,   89.061,   89.061],
         [ -95.939,  -94.939,  -92.939, ...,   90.061,   90.061,   90.061],
         [ -94.939,  -94.939,  -93.939, ...,   91.061,   91.061,   91.061],
         ...,
         [-101.939, -101.939, -102.939, ...,   10.061,   10.061,   10.061],
         [ -99.939,  -98.939,  -97.939, ...,    9.061,   10.061,   10.061],
         [ -97.939,  -95.939,  -92.939, ...,    8.061,    8.061,    9.061]]]]), 'im_info': array([[ 600.        ,  800.        ,    1.60000002]], dtype=float32)}
```

**Comment by MissDores** [comment]
This is what I get when I print 'self.data', and I think it is the shape of NDArrays. I don't know why the error raises. I just train the rcnn with PASCAL VOC 2007 dataset and did not make any modification with the code. I really want to know what's wrong and how to fix it? Thank you very much.
```
{'data': array([[[[-113.68 , -112.68 , -110.68 , ...,   38.32 ,   37.32 ,   37.32 ],
         [-116.68 , -115.68 , -113.68 , ...,   38.32 ,   38.32 ,   38.32 ],
         [-117.68 , -117.68 , -115.68 , ...,   39.32 ,   39.32 ,   39.32 ],
         ...,
         [ -87.68 ,  -88.68 ,  -89.68 , ...,  -54.68 ,  -54.68 ,  -54.68 ],
         [ -80.68 ,  -77.68 ,  -74.68 , ...,  -54.68 ,  -54.68 ,  -54.68 ],
         [ -74.68 ,  -69.68 ,  -62.68 , ...,  -55.68 ,  -55.68 ,  -54.68 ]],

        [[-106.779, -105.779, -103.779, ...,   70.221,   69.221,   69.221],
         [-109.779, -107.779, -105.779, ...,   70.221,   70.221,   70.221],
         [-109.779, -108.779, -106.779, ...,   71.221,   71.221,   71.221],
         ...,
         [-107.779, -108.779, -108.779, ...,  -34.779,  -34.779,  -34.779],
         [-103.779, -102.779, -101.779, ...,  -33.779,  -33.779,  -32.779],
         [ -99.779,  -97.779,  -94.779, ...,  -33.779,  -33.779,  -32.779]],

        [[ -93.939,  -92.939,  -90.939, ...,   90.061,   89.061,   89.061],
         [ -95.939,  -94.939,  -92.939, ...,   90.061,   90.061,   90.061],
         [ -94.939,  -94.939,  -93.939, ...,   91.061,   91.061,   91.061],
         ...,
         [-101.939, -101.939, -102.939, ...,   10.061,   10.061,   10.061],
         [ -99.939,  -98.939,  -97.939, ...,    9.061,   10.061,   10.061],
         [ -97.939,  -95.939,  -92.939, ...,    8.061,    8.061,    9.061]]]]), 'im_info': array([[ 600.        ,  800.        ,    1.60000002]], dtype=float32)}
```
@precedenceguo

**Comment by MissDores** [comment]
I solved the problem by change `self.data` to `[self.data]` in loader.py :: class ROIIter :: def next, and add an if statement because the code runs normal and no error shows when it runs the RPN training phase:
```
def next(self):
        if self.iter_next():
            self.get_batch()
            self.cur += self.batch_size
            if self.mode=='train':
                return mx.io.DataBatch(data=self.data, label=self.label,
                                       pad=self.getpad(), index=self.getindex(),
                                       provide_data=self.provide_data, provide_label=self.provide_label)
            else:
                return mx.io.DataBatch(data=[self.data], label=[self.label],
                                       pad=self.getpad(), index=self.getindex(),
                                       provide_data=self.provide_data, provide_label=self.provide_label)
        else:
            raise StopIteration
```
Based on the above modification, other related lines need also be modified:
change `databatch.data` to `databatch.data[0]` in generate.py and tester.py.
The error and the modification is quite weird and I still don't know why. But it works and run through after the modification.
