### ISSUE TITLE
the accuracy of InceptionBN model on ILSVRC 12

### ISSUE THREAD

**Issue by abangdd** [dmlc/mxnet#716]
https://raw.githubusercontent.com/dmlc/web-data/master/mxnet/image/inception-with-bn-imagnet1k.png
the local-test is only 65%, it's unreasonablly lower than cxxnet example
is there something wrong with the picture?

**Comment by antinucleon** [comment]
Two networks are trained in different way: cxxnet is using manually learning rate reduce. This example is  using factor reduction. As the reduction factor is 0.94 per epoch, in this figure, final learning rate is: 0.002266. While in cxxnet example, the final learning rate is much smaller than this value.

**Comment by abangdd** [comment]
I see, thank you
