### ISSUE TITLE
where is the `clip` function in ndarray module defined?

### ISSUE THREAD

**Issue by liangfu** [dmlc/mxnet#7161]
## Environment info
Operating System: macOS
Compiler: clang
Package used (Python/R/Scala/Julia): Python
MXNet version: 0.10.1
Python version and distribution: python-2.7

## Error Message:
The import lines tries to import `clip` function from `ndarray` module, however, I looked everywhere and no clip function is defined in `ndarray`.
As I observed the function is implemented in ndarray.cc file, so I wildly guess it's should be provided by _ctypes/ndarray.py, but I can't find any `clip` function imported from there either. 
I'm wondering what did I miss to import the `clip` function from `ndarray` module? How should I fix that? (I'm doing this in macOS, didn't confirm the issue in other operating systems.)

**Comment by edmBernard** [comment]
here : https://github.com/dmlc/mxnet/blob/master/src/operator/tensor/matrix_op.cc#L442
you can find the line definition of each function in the documentation: http://mxnet.io/api/python/ndarray.html#mxnet.ndarray.clip

**Comment by piiswrong** [comment]
try make clean and make

**Comment by liangfu** [comment]
thanks for your help.
