### ISSUE TITLE
Cant convert caffe model to mxnet

### ISSUE THREAD

**Issue by divamgupta** [dmlc/mxnet#7162]
Cant convert caffe model. 

I treid `python convert_caffe_modelzoo.py resnet-50`

## Error Message:

```
libdc1394 error: Failed to initialize libdc1394
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "convert_caffe_modelzoo.py", line 115, in <module>
    fname, _ = convert_caffe_model(args.model_name, model_meta_info[args.model_name])
  File "convert_caffe_modelzoo.py", line 101, in convert_caffe_model
    (prototxt, caffemodel, mean) = download_caffe_model(model_name, meta_info, dst_dir)
  File "convert_caffe_modelzoo.py", line 89, in download_caffe_model
    prototxt = mx.test_utils.download(meta_info['prototxt'], model_name+'_deploy.prototxt')
AttributeError: 'module' object has no attribute 'download'
```

## Minimum reproducible example

`python convert_caffe_modelzoo.py resnet-50`

## Environment info
Operating System: Ubuntu 14.04

Compiler: gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
Installed from source:
MXNet commit hash: a242e9f4b77bf705ae679de05642fbe88f870a9f
Caffe commit hash: 4efdf7ee49cffefdd7ea099c00dc5ea327640f04
Python version and distribution: Python 2.7.6

**Comment by xiaoheizi123** [comment]
I also cannot convert resnet-50 using **python convert_caffe_modelzoo.py resnet-50**

`converting scale layer, beta shape = (2048,), gamma shape = (2048,)
        skipping layer res5c of type Eltwise
        skipping layer res5c_relu of type ReLU
        skipping layer pool5 of type Pooling
converting layer fc1000, wmat shape = (1000, 2048), bias shape = (1000,)
        skipping layer prob of type Softmax
/home/users/rui.zheng/anaconda2/lib/python2.7/site-packages/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['prob_label'])
  warnings.warn(msg)
Traceback (most recent call last):
  File "convert_caffe_modelzoo.py", line 144, in <module>
    fname, _ = convert_caffe_model(args.model_name, model_meta_info[args.model_name])
  File "convert_caffe_modelzoo.py", line 133, in convert_caffe_model
    convert_mean(mean, [mx_mean])
  File "/home/users/rui.zheng/works/incubator-mxnet/tools/caffe_converter/convert_mean.py", line 44, in convert_mean
    mean_blob.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
`
f.read() is ok, but mean_blob is None when print it，
I also read [https://github.com/apache/incubator-mxnet/blob/430ea7bfbbda67d993996d81c7fd44d3a20ef846/docs/how_to/caffe.md](url), and do what **Converting Caffe trained models to MXNet**  part shows, but it is still wrong, what should I do?
