### ISSUE TITLE
Installation link for R package is out of date / broken

### ISSUE THREAD

**Issue by hack-r** [dmlc/mxnet#7164]
This is from copying and pasting the Installation code on the R package page:

```
--2017-07-22 13:51:46--  https://s3-us-west-2.amazonaws.com/apache-mxnet/R/CRAN/src/contrib/mxnet_0.10.1.tar.gz
Resolving s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)... 52.218.160.4
Connecting to s3-us-west-2.amazonaws.com (s3-us-west-2.amazonaws.com)|52.218.160.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-07-22 13:51:47 ERROR 404: Not Found.
```

**Comment by thirdwing** [comment]
As we have said in the document, we only provide pre-built pkgs for Windows and OSX. You are trying to install the source pkg for Linux, which is not provided.

If you are using OSX, you might have installed the R using brew which has different configurations from the official R for OSX. In this case, please try

```r
install.packages("mxnet", type = "el-capitan.binary")
```

The installation has only been tested with the official R installation from R-project website.
