### ISSUE TITLE
[ps-lite] should update commit timestamp

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#720]
I try use tools/lanch.py in local mode, failed may time, then I find ps-lite commit timestamp should update

**Comment by jermainewang** [comment]
@mli could you please look into this?

**Comment by mli** [comment]
please run `git submodule update`

**Comment by qiaohaijun** [comment]
I run "git submodule update" but don't work
I change the ps-lite branch to dev, and work
