### ISSUE TITLE
libmxnet.so: undefined symbol: culibosOnce

### ISSUE THREAD

**Issue by caron-lee** [dmlc/mxnet#721]
I built mxnet and installed python module. However, when I import mxnet in python, It shows:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
python/mxnet/../../lib/libmxnet.so: undefined symbol: culibosOnce

**Comment by jermainewang** [comment]
Do you have cuda libraries in your LD_LIBRARY_PATH?

**Comment by caron-lee** [comment]
YES， I have added, I found 
nm libmxnet.so  | grep culibosOnce
                 U culibosOnce
nm /usr/local/cuda/lib64/libculibos.a | grep culibosOnce
00000000000006a0 T culibosOnce
But there isn't libculibos.so. (CUDA version 7.5)

**Comment by caron-lee** [comment]
I found this in the nvidia document:
"Note that libculibos.a is not needed when the shared version of these libraries is
used."
So I'm totally confused.

**Comment by piiswrong** [comment]
nm libmxnet.so | grep culibosOnce on my machine returns nothing. Do you have any custom CCFLAGS or LDFLAGS?
Maybe try make clean_all, pull mxnet and update submodule, then build everything again?

**Comment by caron-lee** [comment]
It's my fault. Thanks @piiswrong
