### ISSUE TITLE
NDArrayIter Shuffle Reproducibility

### ISSUE THREAD

**Issue by jimxinbo** [dmlc/mxnet#736]
I cannot repeat the results every time I ran the same script.

If I fix some seeds on the initialization of the weights and set shuffle==False in mx.io.NDArrayIter. I can repeat the same results. But if I set shuffle==True in mx.io.NDArrayIter. Even by adding a mx.random.seed() before calling mx.io.NDArrayIter, I cannot get consistent results every time. 

Is this because I cannot seed the shuffle of ArrayIter by now? Any way around so that I can control the shuffling for repeating results?

Thank you.

**Comment by piiswrong** [comment]
You need to also seed numpy and random to guarantee reproducibility.
@tqchen should we also seed those in mx.random.seed by default?

**Comment by jimxinbo** [comment]
Thx piiswrong, to also seed numpy solved it.
