### ISSUE TITLE
recipe for target 'bin/im2rec' failed

### ISSUE THREAD

**Issue by zhoubinxyz** [dmlc/mxnet#745]
build/ndarray/unary_function_gpu.o: In function `_GLOBAL__sub_I_tmpxft_00004ed5_00000000_4_unary_function.cudafe1.cpp':
/home/zhoub/mxnet/src/ndarray/./unary_function-inl.h:87: undefined reference to `mxnet::common::TBlobOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
/home/zhoub/mxnet/src/ndarray/./unary_function-inl.h:91: undefined reference to `mxnet::common::TBlobOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
/home/zhoub/mxnet/src/ndarray/./unary_function-inl.h:96: undefined reference to `mxnet::common::TBlobOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
/home/zhoub/mxnet/src/ndarray/./unary_function-inl.h:100: undefined reference to `mxnet::common::TBlobOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
/home/zhoub/mxnet/src/ndarray/./unary_function-inl.h:104: undefined reference to `mxnet::common::TBlobOpRegistry::__REGISTER_OR_FIND__(std::string const&)'
build/ndarray/unary_function_gpu.o:/home/zhoub/mxnet/src/ndarray/./unary_function-inl.h:108: more undefined references to `mxnet::common::TBlobOpRegistry::__REGISTER_OR_FIND__(std::string const&)' follow
collect2: error: ld returned 1 exit status
Makefile:137: recipe for target 'bin/im2rec' failed
make: *** [bin/im2rec] Error 1

**Comment by zhoubinxyz** [comment]
I have tried to compile without CUDA, and it success.

**Comment by zhoubinxyz** [comment]
The problem is the version of g++ or gcc I am working with.
It is very similar with caffe's problem you may referred to https://groups.google.com/forum/#!msg/caffe-users/a6TDx89IByY/49ZD6rtyCwAJ

**Comment by tqchen** [comment]
glad it works out for you, closing

**Comment by bonsairobo** [comment]
I have this same problem, but I require CUDA. Is there a way to fix this?

**Comment by KeithYin** [comment]
@bonsairobo  you can try gcc-5.4 to do this

**Comment by ShoufaChen** [comment]
I have also meet this problem with cuda use  gcc 4.8 .

I solved it by using  gcc 5.5
