### ISSUE TITLE
support for 3D convolution 

### ISSUE THREAD

**Issue by kayhan-batmanghelich** [dmlc/mxnet#747]
Dear Developers,

MXNET is a great tool. I really enjoyed the performance and the design of the interface. I was wondering if there is  any plan to add 3D convolution and 3D pooling? Having 3D support in addition to the distributed computation (which is already there in MXNET) would be tremendously helpful in medical imaging applications where images are volumetric (3D).

My understanding is that it is not supported yet (am I missing something). It seems in the current version, it is possible to define a 3d kernel 

```
data3d = mx.symbol.Variable('data')
conv3d= mx.symbol.Convolution(data = data, num_filter=1, kernel=(4,4,4), stride=(2,2,2))
```

but it results in error during the execution:

```
conv2_exec = conv3d.bind(ctx=mx.cpu(), args={'data' : dd, 'convolution5_weight':ker , 'convolution5_bias': mx.nd.ones(1) })
conv2_exec.forward()
conv2_exec.outputs[0].asnumpy()
```
```
MXNetError                                Traceback (most recent call last)
<ipython-input-93-48a3ad8ac538> in <module>()
----> 1 conv2_exec = conv3d.bind(ctx=mx.cpu(), args={'data' : dd, 'convolution5_weight':ker , 'convolution5_bias': mx.nd.ones(1) })
      2 conv2_exec.forward()
      3 conv2_exec.outputs[0].asnumpy()
      4 imshow(conv2_exec.outputs[0].asnumpy().squeeze())

[...]
/Users/kayhan/Projects/gitSandBox/mxnet/tests/python/gpu/../../../python/mxnet/base.pyc in check_call(ret)
     72     """
     73     if ret != 0:
---> 74         raise MXNetError(py_str(_LIB.MXGetLastError()))
     75 
     76 def c_str(string):

MXNetError: InferShape Error in convolution5's weight argument
Corresponding keyword of symbol: convolution5_weight
Shape inconsistent, Provided =(1, 1, 4, 4, 4), inferred shape=(1,1,4,4)
```

**Comment by antinucleon** [comment]
Hi Kayhan,

Thanks for using MXNet. @lukemetz is working on this, and a WIP PR can be found at:
https://github.com/dmlc/mxnet/pull/687

After it is finished, we will support 3D conv

**Comment by piiswrong** [comment]
Hi,
Thanks for the interest. @korneil is working on this but hasn't updated for a while.

**Comment by kayhan-batmanghelich** [comment]
Hi @antinucleon and @piiswrong , I was wondering if there is any update about this? Thanks.

**Comment by piiswrong** [comment]
@kayhan-batmanghelich @korneil hasn't been active for a while. You are welcome to pick up where he left off

**Comment by machuck** [comment]
Any new updates? 3d support features are getting increasingly important. Thanks again!

**Comment by great-thoughts** [comment]
Any updates?

**Comment by piiswrong** [comment]
should be fully supported now

**Comment by Pagey** [comment]
Thanks dearly for the 3d support- seems to be working well, however, does mx.symbol.LRN support 3d? When I add such a layer, e.g. in alexnet fashion:
lrn1 = mx.symbol.LRN(data=relu1, alpha=0.0001, beta=0.75, knorm=2, nsize=5)
   
I keep crashing with this:

[12:13:24] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\dmlc-core\include\dmlc\./logging.h:300: [12:13:24] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\nnvm\include\nnvm/tuple.h:446: Check failed: dim == static_cast<int>(ndim()) (4 vs. 5) dimension do not match target dimension 4 vs 5
[12:13:24] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\dmlc-core\include\dmlc\./logging.h:300: [12:13:24] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\src\engine\./threaded_engine.h:329: [12:13:24] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\nnvm\include\nnvm/tuple.h:446: Check failed: dim == static_cast<int>(ndim()) (4 vs. 5) dimension do not match target dimension 4 vs 5
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

**Comment by Pagey** [comment]
BatchNorm doesn't seem to support 3d either?? similar dimension (4<>5) errors

**Comment by Pagey** [comment]
@piiswrong are BatchNorm or LRN supposed to support 3d? as I wrote I'm getting dimension errors on these-
Thanks!
