### ISSUE TITLE
ld: library not found for -lgomp 

### ISSUE THREAD

**Issue by yib2** [dmlc/mxnet#749]
I thought this problem occurred because wrong setting on gcc or opencv, probably. Is there anyone having the same problem? I have reinstall all dependencies and Xcode itself. It doesn't work.

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: lib/libmxnet.a(mxrtc.o) has no symbols
clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
In file included from tools/im2rec.cc:21:
In file included from /usr/local/Cellar/opencv/2.4.12/include/opencv2/opencv.hpp:56:
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:961:18: warning: 
      'CvForestTree::train' hides overloaded virtual functions
      [-Woverloaded-virtual]
    virtual bool train( CvDTreeTrainData* trainData, const CvMat* _subsa...
                 ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:867:18: note: hidden
      overloaded virtual function 'CvDTree::train' declared here: different
      number of parameters (2 vs 3)
    virtual bool train( CvMLData* trainData, CvDTreeParams params=CvDTre...
                 ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:877:26: note: hidden
      overloaded virtual function 'CvDTree::train' declared here: different
      number of parameters (8 vs 3)
    CV_WRAP virtual bool train( const cv::Mat& trainData, int tflag,
                         ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:1149:18: warning: 
      'CvBoostTree::train' hides overloaded virtual functions
      [-Woverloaded-virtual]
    virtual bool train( CvDTreeTrainData* trainData,
                 ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:867:18: note: hidden
      overloaded virtual function 'CvDTree::train' declared here: different
      number of parameters (2 vs 3)
    virtual bool train( CvMLData* trainData, CvDTreeParams params=CvDTre...
                 ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:877:26: note: hidden
      overloaded virtual function 'CvDTree::train' declared here: different
      number of parameters (8 vs 3)
    CV_WRAP virtual bool train( const cv::Mat& trainData, int tflag,
                         ^
2 warnings generated.
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/im2rec] Error 1

**Comment by qiaohaijun** [comment]
mac?

**Comment by yib2** [comment]
yes

**Comment by leocnj** [comment]
You may follow the solutions used in #728 to at least successfully compile a CPU version using openblas on Mac OS X 10.11.

**Comment by thirdwing** [comment]
I think this is because your compiler doesn't have OpenMP support.

**Comment by phunterlau** [comment]
if the machine has only one CUDA GPU, OpenMP is not really needed. BLAS can handle multi-CPU, either Apple's blas or openblas. I suggest `USE_OPENMP=0` in `config.mk`. It solved my installation problem on mac.

**Comment by caprice-j** [comment]
Try 

brew install clang-omp
make CXX=clang-omp++

It worked for me.

**Comment by yib2** [comment]
Thanks for your share.
It works for me. Just realize that gcc always makes things messy and costs long time to compile.

**Comment by ShirleyLee1995** [comment]
appletekiMacBook-Air-3:bin apple$ brew install clang-omp
Warning: clang-omp-2015-04-01 already installed
appletekiMacBook-Air-3:bin apple$ make CXX=clang-omp++
make: *** No targets specified and no makefile found.  Stop.
why。。。

**Comment by nam-nguyen17** [comment]
> Try
> 
> brew install clang-omp
> make CXX=clang-omp++
> 
> It worked for me.

I try your following cmd but I got

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "clang-omp".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by szha** [comment]
@nam-nguyen17 omp ships as part of the llvm in homebrew now. See https://stackoverflow.com/a/48746939
