### ISSUE TITLE
[dist-train] thread not close

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#753]
I follow the guide  
https://github.com/dmlc/mxnet/tree/master/example/image-classification

I find that when the train job is over, the thread on machines is not closed .

**Comment by qiaohaijun** [comment]
I train model on 7 and 15 GPU machines which equipped with four K40m gpu card

**Comment by qiaohaijun** [comment]
centos 7.1
g++ 4.8
python 2.7

**Comment by antinucleon** [comment]
What's the meaning of thread is not closed? Do you mean process?

**Comment by tqchen** [comment]
closed due to inactive status, feel free to re-open
