### ISSUE TITLE
Support FP16

### ISSUE THREAD

**Issue by erogol** [dmlc/mxnet#757]

**Comment by antinucleon** [comment]
We have DType template parameter which allow all code to be compiled with fp16, however we don't have enough hands to implement it. Could you consider to PR one? We can offer kinds of help.

**Comment by piiswrong** [comment]
on a side note f16 currently won't improve performance on NVIDIA cards.

**Comment by qiaohaijun** [comment]
@piiswrong do you mean the next genaration gpu support ?

**Comment by erogol** [comment]
but still f16 means less memory, am I right or still GPU would consider it f32?

**Comment by tqchen** [comment]
One step toward this is to support typed NDArray, and then we can add a typecast operator, and gradually add fp16 and fixed point support, things should not be hard as mshadow is templatized, and we don't have to re-implement most of the code

**Comment by piiswrong** [comment]
The infrastructure for FP16 is already there now. You just need to add FP16 support for the layers you want to use. Most NDArray functions now support FP16

**Comment by futurely** [comment]
https://github.com/dmlc/mxnet/pull/1675
