### ISSUE TITLE
Compilation failed when using intel mkl on OS X 10.11

### ISSUE THREAD

**Issue by were** [dmlc/mxnet#759]
I attempted to install mxnet with BLAS = mkl.

It failed at linking phase.

Here is the error log.

````
ld: unknown option: --start-group
a - build/operator/native_op.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
````

**Comment by piiswrong** [comment]
are you using make/os.mk?

**Comment by were** [comment]
I changed some options in os.mk.

I know I was `BLAS = apple` before.

I just want to make sure whether mkl works well.

**Comment by mli** [comment]
you need to set `USE_INTEL_PATH` to your mkl directory

**Comment by tqchen** [comment]
see also #928
