### ISSUE TITLE
[initialization] how to initial every symbal?

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#760]
these days I begin use mxnet to train model.
who can give me some doc about initialize every symbol that like caffe does?

**Comment by qiaohaijun** [comment]
layers {
  name: "fc8"
  type: INNER_PRODUCT
  bottom: "fc7"
  top: "fc8"
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  inner_product_param {
    num_output: 1000
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

**Comment by qiaohaijun** [comment]
layers {
  name: "conv5"
  type: CONVOLUTION
  bottom: "conv4"
  top: "conv5"
  blobs_lr: 1
  blobs_lr: 2
  weight_decay: 1
  weight_decay: 0
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    group: 2
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
      value: 0.1
    }
  }
}

**Comment by tqchen** [comment]
This is not yet supported in current initializer. You can however, implement your own initializer to support initializing by the name of the weight
