### ISSUE TITLE
There is too little cpp examples.

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#762]
No document of describing how to build a Deep Network with CPP.:cry:

**Comment by piiswrong** [comment]
It's not very hard to figure out. Just trace the python code through c_api.cc to their c++ bindings.
You are welcome to submit a PR for this.

**Comment by starimpact** [comment]
I'm working on it.

**Comment by piiswrong** [comment]
Thanks. BTW, how is your Faster RCNN implementation going?

**Comment by starimpact** [comment]
it has been done.

**Comment by starimpact** [comment]
Actually, I just implemented the RPN part of it.

**Comment by starimpact** [comment]
I still have no idea what ```const char* param_bytes``` is which is in function ```MXPredCreate```.
I guess it is the parameters of network, such as ```weight``` and ```bias```, but how I organize them for ```param_bytes``` ?

**Comment by starimpact** [comment]
@piiswrong @tqchen

**Comment by tqchen** [comment]
move to https://github.com/dmlc/mxnet/issues/868
