### ISSUE TITLE
rgb or bgr? 

### ISSUE THREAD

**Issue by suhangpro** [dmlc/mxnet#767]
I found two examples about making predictions using pre-trained models: 
1) [mxnet/example/notebooks/predict-with-pretrained-model.ipynb](https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb)
2) [mxnet/tests/python/predict/mxnet_predict_example.py](https://github.com/dmlc/mxnet/blob/master/tests/python/predict/mxnet_predict_example.py#L40)

In 2) there is an explicit conversion from rgb to bgr: 
```
sample = sample[:, :, [2,1,0]]
```
however there's no such conversion in 1). Which one should be fixed?

**Comment by antinucleon** [comment]
Sorry for the out-of-dated doucments. MXNet receive RGB image, and in internal, it is BGR. We will update it soon, or would you consider to send a PR to delete BGR info in document? Thanks

**Comment by tornadomeet** [comment]
@antinucleon @winstywang , so if the internel of MXNet is BGR, then the line [caffe_converter](https://github.com/dmlc/mxnet/blob/master/tools/caffe_converter/convert_model.py#L68) should be deleted?

**Comment by suhangpro** [comment]
I opened issue #765 , which removes the aforementioned line from  mxnet/tests/python/predict/mxnet_predict_example.py.

**Comment by tqchen** [comment]
The internal is RGB, it is only BGR in opencv decoding staging, and transformed to rgb right after that

**Comment by tornadomeet** [comment]
en, i see, so in this issue, just only need to delete ```sample = sample[:, :, [2,1,0]]``` in mxnet_predict_example.py

**Comment by tqchen** [comment]
the predict loads in with skimage, which could already been rgb i guess

**Comment by tornadomeet** [comment]
yes, it is rgb order in skimage, refer to (skimage.io.html)[http://scikit-image.org/docs/dev/api/skimage.io.html]
