### ISSUE TITLE
compiling failed with GPU enabled

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/mxnet#768]
Hi,

Compile with CPU only is OK. But encountered with the following error when CUDA/CUDDN is enabled:

g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -MM -MT build/operator/lrn.o src/operator/lrn.cc >build/operator/lrn.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -c src/operator/lrn.cc -o build/operator/lrn.o
In file included from src/operator/lrn.cc:10:0:
src/operator/./cudnn_lrn-inl.h:130:3: error: ‘cudnnLRNDescriptor_t’ does not name a type
   cudnnLRNDescriptor_t lrn_desc_;
   ^
In file included from src/operator/./lrn-inl.h:9:0,
                 from src/operator/lrn.cc:8:
src/operator/./cudnn_lrn-inl.h: In destructor ‘virtual mxnet::op::CuDNNLocalResponseNormOp::~CuDNNLocalResponseNormOp()’:
src/operator/./cudnn_lrn-inl.h:25:40: error: ‘lrn_desc_’ was not declared in this scope
     CHECK_EQ(cudnnDestroyLRNDescriptor(lrn_desc_), CUDNN_STATUS_SUCCESS);
                                        ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:25:5: note: in expansion of macro ‘CHECK_EQ’
     CHECK_EQ(cudnnDestroyLRNDescriptor(lrn_desc_), CUDNN_STATUS_SUCCESS);
     ^
src/operator/./cudnn_lrn-inl.h:25:49: error: ‘cudnnDestroyLRNDescriptor’ was not declared in this scope
     CHECK_EQ(cudnnDestroyLRNDescriptor(lrn_desc_), CUDNN_STATUS_SUCCESS);
                                                 ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:25:5: note: in expansion of macro ‘CHECK_EQ’
     CHECK_EQ(cudnnDestroyLRNDescriptor(lrn_desc_), CUDNN_STATUS_SUCCESS);
     ^
src/operator/./cudnn_lrn-inl.h: In member function ‘virtual void mxnet::op::CuDNNLocalResponseNormOp::Forward(const mxnet::OpContext&, const std::vector<mshadow::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&)’:
src/operator/./cudnn_lrn-inl.h:48:42: error: ‘lrn_desc_’ was not declared in this scope
                                          lrn_desc_,
                                          ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:47:5: note: in expansion of macro ‘CHECK_EQ’
     CHECK_EQ(cudnnLRNCrossChannelForward(s->dnn_handle_,
     ^
src/operator/./cudnn_lrn-inl.h:49:42: error: ‘CUDNN_LRN_CROSS_CHANNEL_DIM1’ was not declared in this scope
                                          CUDNN_LRN_CROSS_CHANNEL_DIM1,
                                          ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:47:5: note: in expansion of macro ‘CHECK_EQ’
     CHECK_EQ(cudnnLRNCrossChannelForward(s->dnn_handle_,
     ^
src/operator/./cudnn_lrn-inl.h:55:51: error: ‘cudnnLRNCrossChannelForward’ was not declared in this scope
                                          out.dptr_), CUDNN_STATUS_SUCCESS);
                                                   ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:47:5: note: in expansion of macro ‘CHECK_EQ’
     CHECK_EQ(cudnnLRNCrossChannelForward(s->dnn_handle_,
     ^
src/operator/./cudnn_lrn-inl.h: In member function ‘virtual void mxnet::op::CuDNNLocalResponseNormOp::Backward(const mxnet::OpContext&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&)’:
src/operator/./cudnn_lrn-inl.h:81:43: error: ‘lrn_desc_’ was not declared in this scope
                                           lrn_desc_,
                                           ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:80:5: note: in expansion of macro ‘CHECK_EQ’
     CHECK_EQ(cudnnLRNCrossChannelBackward(s->dnn_handle_,
     ^
src/operator/./cudnn_lrn-inl.h:82:43: error: ‘CUDNN_LRN_CROSS_CHANNEL_DIM1’ was not declared in this scope
                                           CUDNN_LRN_CROSS_CHANNEL_DIM1,
                                           ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:80:5: note: in expansion of macro ‘CHECK_EQ’
     CHECK_EQ(cudnnLRNCrossChannelBackward(s->dnn_handle_,
     ^
src/operator/./cudnn_lrn-inl.h:92:59: error: ‘cudnnLRNCrossChannelBackward’ was not declared in this scope
                                           input_grad.dptr_), CUDNN_STATUS_SUCCESS);
                                                           ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:80:5: note: in expansion of macro ‘CHECK_EQ’
     CHECK_EQ(cudnnLRNCrossChannelBackward(s->dnn_handle_,
     ^
src/operator/./cudnn_lrn-inl.h: In member function ‘void mxnet::op::CuDNNLocalResponseNormOp::Init(mshadow::Stream<mshadow::gpu>*, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&)’:
src/operator/./cudnn_lrn-inl.h:111:42: error: ‘lrn_desc_’ was not declared in this scope
       CHECK_EQ(cudnnCreateLRNDescriptor(&lrn_desc_), CUDNN_STATUS_SUCCESS);
                                          ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:111:7: note: in expansion of macro ‘CHECK_EQ’
       CHECK_EQ(cudnnCreateLRNDescriptor(&lrn_desc_), CUDNN_STATUS_SUCCESS);
       ^
src/operator/./cudnn_lrn-inl.h:111:51: error: ‘cudnnCreateLRNDescriptor’ was not declared in this scope
       CHECK_EQ(cudnnCreateLRNDescriptor(&lrn_desc_), CUDNN_STATUS_SUCCESS);
                                                   ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:111:7: note: in expansion of macro ‘CHECK_EQ’
       CHECK_EQ(cudnnCreateLRNDescriptor(&lrn_desc_), CUDNN_STATUS_SUCCESS);
       ^
src/operator/./cudnn_lrn-inl.h:112:38: error: ‘lrn_desc_’ was not declared in this scope
       CHECK_EQ(cudnnSetLRNDescriptor(lrn_desc_,
                                      ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:112:7: note: in expansion of macro ‘CHECK_EQ’
       CHECK_EQ(cudnnSetLRNDescriptor(lrn_desc_,
       ^
src/operator/./cudnn_lrn-inl.h:116:43: error: ‘cudnnSetLRNDescriptor’ was not declared in this scope
                                      lrn_k), CUDNN_STATUS_SUCCESS);
                                           ^
./dmlc-core/include/dmlc/logging.h:68:9: note: in definition of macro ‘CHECK’
   if (!(x))                                                \
         ^
src/operator/./cudnn_lrn-inl.h:112:7: note: in expansion of macro ‘CHECK_EQ’
       CHECK_EQ(cudnnSetLRNDescriptor(lrn_desc_,
       ^
In file included from src/operator/./lrn-inl.h:10:0,
                 from src/operator/lrn.cc:8:
src/operator/lrn.cc: At global scope:
./dmlc-core/include/dmlc/parameter.h:247:43: warning: ‘mxnet::op::__make__LRNParamParamManager__’ defined but not used [-Wunused-variable]
   static ::dmlc::parameter::ParamManager &__make__ ## PType ## ParamManager__ = \
                                           ^
src/operator/lrn.cc:24:1: note: in expansion of macro ‘DMLC_REGISTER_PARAMETER’
 DMLC_REGISTER_PARAMETER(LRNParam);
 ^
In file included from include/mxnet/operator.h:13:0,
                 from src/operator/./lrn-inl.h:11,
                 from src/operator/lrn.cc:8:
./dmlc-core/include/dmlc/registry.h:206:22: warning: ‘mxnet::op::__make_OperatorPropertyReg_LRN__’ defined but not used [-Wunused-variable]
   static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/mxnet/operator.h:480:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
   DMLC_REGISTRY_REGISTER(::mxnet::OperatorPropertyReg, OperatorPropertyReg, name) \
   ^
src/operator/lrn.cc:26:1: note: in expansion of macro ‘MXNET_REGISTER_OP_PROPERTY’
 MXNET_REGISTER_OP_PROPERTY(LRN, LocalResponseNormProp)
 ^
make: *** [build/operator/lrn.o] Error 1

**Comment by piiswrong** [comment]
Where is you cudnn library? Did you put it in cuda folder or add it in CCFLAGS and LDFLAGS?
Is it cudnn v3?

**Comment by kaishijeng** [comment]
cudnn library are installed:

/usr/local/cuda/include
/usr/local/cuda/lib64

cudnn version: 
cudnn-6.5-linux-x64-v2

**Comment by piiswrong** [comment]
You need to replace it with cudnn v3
