### ISSUE TITLE
Is there any example about LSTM with attention mechanism?

### ISSUE THREAD

**Issue by happygds** [dmlc/mxnet#769]
I follow the file: example/rnn/lstm.py and try to write a LSTM Cell symbol with attention. Should I put the computing of relevance score outsize this cell or in it ? If in, how to represent the i-th feature vector and their dynamic weighted sum ?

**Comment by jermainewang** [comment]
Hi, currently we don't have attention LSTM yet. I would say put the computation of score out of the LSTM cell but maybe you could find some more efficient way to implement them together. In terms of detailed implementation, could you represent the attention weight using a tensor?

**Comment by tqchen** [comment]
This is something @antinucleon is looking at, we will need some internal softmaxTransform operator

**Comment by lightingghost** [comment]
Can I know how the issue goes on?

It seems attention model needs a softmax, what if implementing the softmax using the symbolic APIs provided? How will it influence the performance?

Thanks

**Comment by moveforever** [comment]
Any progress for attention model?

**Comment by Ldpe2G** [comment]
@moveforever you can refer to: https://github.com/magic282/MXNMT/blob/master/mxwrap/attention/BasicAttention.py

**Comment by moveforever** [comment]
@Ldpe2G tks.
