### ISSUE TITLE
R package installation fails on mac osx 10.11

### ISSUE THREAD

**Issue by leocnj** [dmlc/mxnet#771]
Following the instruction provided by the mxnet document

    install.packages("drat", repos="https://cran.rstudio.com")
    drat:::addRepo("dmlc")
    install.packages("mxnet")

I run the above commands in RStudio and met the following errors - mostly from the last step

    > install.packages("mxnet")
    curl: (22) The requested URL returned error: 404 Not Found
    Warning in install.packages :
    download had nonzero exit status
    Warning in install.packages :
    cannot open compressed file  /var/folders/df/ctxs2j3d14n8jp16xy_8n8g9nslbq4/T//Rtmpg1hpr7/file76f02c177987', probable reason 'No such file or directory'
    curl: (22) The requested URL returned error: 404 Not Found
    Warning in install.packages :
    download had nonzero exit status
    Warning in install.packages :
    cannot open compressed file  '/var/folders/df/ctxs2j3d14n8jp16xy_8n8g9nslbq4/T//Rtmpg1hpr7/file76f02c177987', probable reason   'No such file or directory'
    Error in install.packages : cannot open the connection

My R SessionInfo() is 

    R version 3.1.2 (2014-10-31)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
    [1] tools_3.1.2

**Comment by leocnj** [comment]
I also tried the second approach (using Rscript)  described in the document. Unfortunately, the last step "R CMD INSTALL mxnet_0.5.tar.gz" gave me the following errors

```r
installing to /Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
```
Any thought on how to successfully install R-package? Thanks.

**Comment by tqchen** [comment]
One comment on second approach, I noticed you build with CUDA, consider add path to libcudart.7.5.dylib to your library path. I guess it is ```LD_LIBRARY_PATH```(it is in linux) but I am not 100 percent sure

**Comment by leocnj** [comment]
After updating R to the latest 3.2.2, the first approach WORKS! 

![image](https://cloud.githubusercontent.com/assets/4459248/11522816/ce3753c0-9889-11e5-8829-515e43bc4177.png)

**Comment by tqchen** [comment]
Glad it works for you, I would also recommend try the second approach, as it gives you R version with CUDA, while default OSX build from drat seems is CPU only

**Comment by thirdwing** [comment]
Just to be clear. In the drat repo, we only have CPU version for only R 3.2.*.

**Comment by leocnj** [comment]
@tqchen and @thirdwing thanks very much. Will try the second approach to enable GPU for the R-package.

**Comment by leocnj** [comment]
Tried the second approach - compiling the R pkg from source to be able to use GPU in mxnet-R

I have been trying installing the R package (w/ GPU support) on OS X EI Capitan. After doing

- disabling Integrity Protection as suggested by @changkun (see #575)
- set LD_LIBRARY_PATH to include "where the libcudart.7.0.5 is"
- set DYLD_FALLBACK_LIBRARY_PATH to include "where the libcudart.7.0.5 is"; **note that this step may not be mandatory**.

I finally can compile the R package and a testing running on both CPU and GPU works inside the R sessions initialized in a terminal. 

However, the only left issue is that mxnet cannot be loaded inside **RStudio** (the latest version). 
```r
> require(mxnet)
Loading required package: mxnet
Error : .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so
  Reason: image not found
```

**Comment by thirdwing** [comment]
This is a known issue I met this summer. I think it has been fixed and I can talk about it with Kevin from Rstudio later.

You can try to run

```r
Sys.getenv("LD_LIBRARY_PATH")
```

in RStudio and show me the results?

**Comment by leocnj** [comment]
Inside Rstudio
```r
> Sys.getenv("LD_LIBRARY_PATH")
[1] ""
```
In a contrast, in terminal
```bash
 echo $LD_LIBRARY_PATH 
/usr/local/cuda/lib:/Users/lchen/cudnn3/cuda/lib:/Developer/NVIDIA/CUDA-7.5/lib:/Users/lchen/torch/install/lib:
```

**Comment by thirdwing** [comment]
Exactly the same problem I met during this summer. I will come back to you later.

**Comment by danmalter** [comment]
`install.packages("drat", repos="https://cran.rstudio.com")
library(drat)
drat:::addRepo("dmlc")
install.packages("mxnet")
library(mxnet`

When trying to install from the above code on a Mac (OS X Yosemite Version 10.10.4), I get the following error.  Any help would be appreciated.  This is with R version 3.2.4

`Error : .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so, 10): Library not loaded: /usr/local/lib/libgomp.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs/libmxnet.so
  Reason: image not found
Error: package or namespace load failed for ‘mxnet’`

**Comment by thirdwing** [comment]
Sorry, it is my fault. I built the R package with OpenMP. I will upload a new one soon.

**Comment by danmalter** [comment]
Thanks for the quick response.

**Comment by thirdwing** [comment]
I have just upload a new one. Can you try again?

**Comment by danmalter** [comment]
Unfortunately I am still getting the same error even after deleting the package and reinstalling.  It looks like the files were modified today on your end at 7:42 PM.  

![screen shot 2016-03-23 at 9 16 58 pm](https://cloud.githubusercontent.com/assets/6834027/14006576/a005a040-f13c-11e5-94c9-1af8c7afce17.png)

R Folder
![screen shot 2016-03-23 at 9 19 04 pm](https://cloud.githubusercontent.com/assets/6834027/14006600/e912558a-f13c-11e5-84d4-0ba98e10634c.png)


![screen shot 2016-03-23 at 9 18 14 pm](https://cloud.githubusercontent.com/assets/6834027/14006592/cc0f2698-f13c-11e5-9799-945e73f9ab2e.png)

**Comment by thirdwing** [comment]
@danmalter Can you try again? I think I removed openmp this time.

**Comment by danmalter** [comment]
@thirdwing It works now on my Mac.  Thanks a lot and I look forward to using the package.

**Comment by haodong** [comment]
set variable DYLD_LIBRARY_PATH to cuda_home by export cmd and then run rstudio from terminal by `open -a "/Applications/RStudio.app"`

**Comment by haodong** [comment]
I used the secondary approach to install but not work when directly open rstudio (open from terminal is OK).

```r
> Sys.getenv("DYLD_LIBRARY_PATH")
[1] "/Developer/NVIDIA/CUDA-7.5/lib"
> library(mxnet)
Error : .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '.../R/library/mxnet/libs/libmxnet.so':
  dlopen(.../R/library/mxnet/libs/libmxnet.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: .../R/library/mxnet/libs/libmxnet.so
  Reason: image not found
Error: package or namespace load failed for ‘mxnet’
```

**Comment by thirdwing** [comment]
There might some issues in how RStudio handles environment variable.

Quick solution: start Rstudio from the terminal by `/Applications/RStudio.app/Contents/MacOS/RStudio`.

**Comment by ianxxiao** [comment]
@thirdwing: i am getting the following error. It seems to be similar to what @danmalter encounter before. My R version is 3.2.4 and I am using a Mac. 

What did you guys do? I should be downloading the latest version of mxnet right?

![image](https://cloud.githubusercontent.com/assets/5623823/15448806/27ae74ec-1f3a-11e6-8328-d362351de8da.png)

**Comment by thirdwing** [comment]
Can you try to install opencv through brew?

On Sat, May 21, 2016 at 8:57 AM, ianxxiao <notifications@github.com> wrote:

> @thirdwing <https://github.com/thirdwing>: i am getting the following
> error. It seems to be similar to what @danmalter
> <https://github.com/danmalter> encounter before. My R version is 3.2.4
> and I am using a Mac.
>
> What did you guys do? I should be downloading the latest version of mxnet
> right?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/5623823/15448806/27ae74ec-1f3a-11e6-8328-d362351de8da.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/771#issuecomment-220779161>
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by ianxxiao** [comment]
@thirdwing works! thanks 👍

**Comment by ToruHironaka** [comment]
I could install mxnet R packages but could to use mxnet. 

> library(drat)
> drat::addRepo("dmlc")
> install.packages("mxnet")
--- Please select a CRAN mirror for use in this session ---
trying URL 'http://dmlc.github.io/drat/bin/macosx/mavericks/contrib/3.2/mxnet_0.7.tgz'
Content type 'application/octet-stream' length 2095829 bytes (2.0 MB)
==================================================
downloaded 2.0 MB

But, I could not use mxnet. 

> require("mxnet")
Loading required package: mxnet

 *** caught segfault ***
address 0x60, cause 'memory not mapped'

Traceback:
 1: .Call(symbol)
 2: Module(module, mustStart = TRUE, where = env)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 7: loadModule("mxnet", TRUE)
 8: fun(libname, pkgname)
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(fun(libname, pkgname), error = identity)
13: runHook(".onLoad", env, package.lib, package)
14: loadNamespace(package, c(which.lib.loc, lib.loc))
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(expr, names, parentenv, handlers[[1L]])
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
19: try({    ns <- loadNamespace(package, c(which.lib.loc, lib.loc))    env <- attachNamespace(ns, pos = pos, deps)})
20: library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,     warn.conflicts = warn.conflicts, quietly = quietly)
21: doTryCatch(return(expr), name, parentenv, handler)
22: tryCatchOne(expr, names, parentenv, handlers[[1L]])
23: tryCatchList(expr, classes, parentenv, handlers)
24: tryCatch(library(package, lib.loc = lib.loc, character.only = TRUE,     logical.return = TRUE, warn.conflicts = warn.conflicts, quietly = quietly),     error = function(e) e)
25: require("mxnet")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
aborting ...
Segmentation fault: 11

My Mac's System: 10.11.5
OS X El Capitan 
R 3.2.2

**Comment by thirdwing** [comment]
Might be related to the version of OSX. I am not sure.

**Comment by michaelsbradleyjr** [comment]
Possibly related to: https://github.com/BVLC/caffe/pull/3696 ?

**Comment by michaelsbradleyjr** [comment]
FWIW, after building the R package, I unpacked it then:

```
cd mxnet/inst/libs
install_name_tool -add_rpath /usr/local/cuda/lib libmxnet.so
```

After that, I did:

```
cd ../..
R CMD INSTALL ./mxnet_0.7.tar.gz
```

And the installation was successful and the library usable (I've been running through some demos).
