### ISSUE TITLE
make error on Mac OS X 10.11:ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by lorraine2015** [dmlc/mxnet#774]
I installed opencv with brew. and I got a warning:
Warning: homebrew/science/opencv dependency gcc was built with a different C++ standardlibrary (libstdc++ from clang). This may cause problems at runtime.
Make error is like:
"operator delete(void*, unsigned long)", referenced from:
      dmlc::Error::~Error() in ccCQi1gp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1
how can I fix this?

**Comment by phunterlau** [comment]
try use CC=clang instead of gcc, because opencv is built on clang only.

**Comment by tqchen** [comment]
closing for now, feel free to reopen if needed
