### ISSUE TITLE
same address for listarguments and listoutputs??

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#781]
when I call the following two functions, I found that ```out_str_array1``` and ```out_str_array2``` have same address. It may not be a critical problem, but I think it should be better if you can make the couple be different.
```cpp
int MXSymbolListArguments(SymbolHandle symbol,
                          mx_uint *out_size,
                          const char ***out_str_array1)
```
```cpp
int MXSymbolListOutputs(SymbolHandle symbol,
                        mx_uint *out_size,
                        const char ***out_str_array2)
```

**Comment by antinucleon** [comment]
I don't get your point. Does it hurt to reuse temp space?!

**Comment by jermainewang** [comment]
In which case will this matter?

**Comment by tqchen** [comment]
It will not pose a problem, the requirement is that the data is copied out as soon as function finishes, and these temp variables are thread local

**Comment by starimpact** [comment]
not a critical problem anyway.
yes, copy the out as soon as function finishes is a solution.
