### ISSUE TITLE
How to create a custom metric function by mx.metric.np in python?

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#786]
For example, if I need a metric of "error rate" or some other metrics like that in R api, how to make it?

**Comment by jermainewang** [comment]
You could use `EvalMetric` add pass it to the `model.fit` function with `eval_metric` parameter. You could see https://github.com/dmlc/mxnet/blob/master/python/mxnet/metric.py for more details.

**Comment by jermainewang** [comment]
The `mx.metric.np` function takes a numpy function as the first argument which is of the form `callable(label, pred)`. It returns an `EvalMetric` object that should be passed to `model.fit` function with `eval_metric` argument.

See [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/metric.py#L94) and [here](https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L685) for more details.

**Comment by wangg12** [comment]
@jermainewang Still can't understand. I tried some but got wrong results. Could you please give an example how to write a callable metric like "err rate"?

**Comment by wangg12** [comment]
@jermainewang Thx. I've figured it out.
