### ISSUE TITLE
About python skimge package version.

### ISSUE THREAD

**Issue by Moore123** [dmlc/mxnet#787]
unbuntu 14.04.03 LTS platform python2.7 , install skimge by apt tools, that's an elder skimage version.

then in the file  neural-style/run.py should be correct as:
 from skimage.filter import denoise_tv_chambolle，#for versoin: 0.9.3

for new version of skimage package could be:
from skimage.restoration import denoise_tv_chambolle

**Comment by piiswrong** [comment]
Thanks! Could you push a fix?
try:
 import one
except:
 import another
should work fine.

**Comment by tqchen** [comment]
any updates on this? closing for now, a PR on this will be appreciated
