### ISSUE TITLE
Some gpu/cpu related questions

### ISSUE THREAD

**Issue by suhangpro** [dmlc/mxnet#788]
##### symbol binding
`NDArray` can be created on the device of choice, and the binding function also takes a 'ctx' as parameter. What's the intended behavior if they are declared differently? 

For instance, here a and b are created on gpu(0) but the context of the generated executor is cpu(), where will the work be done on? The output indicates gpu(0). The same happens in reverse: the output will be on cpu(0) if a and b are on cpu(0) no matter what the 'ctx' is. 
```python
A = mx.symbol.Variable('A')
B = mx.symbol.Variable('B')
C = A * B
a = mx.nd.ones(3,mx.gpu(0)) * 4
b = mx.nd.ones(3,mx.gpu(0)) * 2
c_exec = C.bind(ctx=mx.cpu(), args={'A' : a, 'B': b})
c_exec.forward()
c_exec.outputs[0].context # --> gpu(0)
```

##### model api
The model api also takes 'ctx' parameter. The model below has parameters on cpu(0) and 'ctx' declared as gpu(0). This time seems the 'ctx' parameter has higher priority. 
``` python
model = mx.model.FeedForward(
        ctx                = mx.gpu(0), # mx.gpu(0)
        symbol             = network,
        num_epoch          = args.num_epochs,
        learning_rate      = args.lr,
        momentum           = 0.9,
        wd                 = 0.00001,
        initializer        = mx.init.Xavier(factor_type="in", magnitude=2.34),
        arg_params         = mx.model.FeedForward.load('vgg19',1).arg_params) # mx.cpu()
```

##### multiple cpus
This might be a silly question, but I cannot find any related information in the documents. Like `NDArray` can be created on the gpu of choice (gpu(0), gpu(1) ...), is there any distinctions between cpu cores (cpu(0), cpu(1) ...)? 

In [example code](https://github.com/suhangpro/mxnet/blob/master/example/image-classification/train_model.py#L32) I see this:  
``` python
    devs = mx.cpu() if args.gpus is None else [
        mx.gpu(int(i)) for i in args.gpus.split(',')]
```
Here only cpu(0) is declared for 'devs' for cpu-only mode. Can mxnet uses all the cpu cores on my machine?

**Comment by jermainewang** [comment]
Hi,

Thank you for your question. For CPU, you could not specify the device id. The device id is only used for GPU. MXNet uses multi-threaded engine to utilize the multi-core power. You could set `MXNET_CPU_WORKER_NTHREADS` environment variable to specify how many threads (roughly how many cores) you would like to use.

**Comment by suhangpro** [comment]
@jermainewang Many thanks! Btw do I need to adjust MXNET_CPU_PRIORITY_NTHREADS accordingly for cpu-only mode? Couldn't understand what "prioritized CPU jobs" means. Also any thoughts on my first two questions?

**Comment by tqchen** [comment]
Normally you do  not have to. On CPU, most time consuming part are matrix multiplications, which is parallelized already if you use libraries such as openblas.

**Comment by suhangpro** [comment]
@tqchen Thanks! Any comments on my first two questions?

**Comment by suhangpro** [comment]
@jermainewang After `export MXNET_CPU_WORKER_NTHREADS=36`, mxnet still only uses 2 cores when running the mnist example.

**Comment by tqchen** [comment]
The worker threads is only related to parallelization of concurrent path, which is not a lot
