### ISSUE TITLE
Variable-size input 

### ISSUE THREAD

**Issue by ddtm** [dmlc/mxnet#789]
I wonder what the preferred way of dealing with variable-size inputs? Say, I'd like to train on batches of different sizes with different spatial dimensions (height and width).

Thanks!

**Comment by jermainewang** [comment]
I am not sure about the exact details. One way I could think about is using a fixed-size inputs and a mask matrix that mask out those invalid input during training. This is what we did for LSTM.

**Comment by ddtm** [comment]
Thanks for the answer! I see two problems with this approach. For my use case during test phase I don't know max dimensions of my inputs ahead of time. The second problem is that the net will be doing unnecessary computations (it is especially bad if the size difference between an average input and the max is substantial). I think in Caffe this is solved by allowing tensors to be resized on demand. The resize operation will trigger memory allocation only if the new size is larger than the current, otherwise the existing allocation is not touched.

**Comment by jermainewang** [comment]
You are right. That's why we are working on the minpy project that could do this dynamic things like [autograd](https://github.com/HIPS/autograd). We are working that so please stay tuned.

**Comment by tqchen** [comment]
What was wanted here was a dynamically resizable structure with fixed graph, this could possibly be done in the symbolic API as well, like what you  mentioned. 

The most flexible way will be imperative gradient @jermainewang  mentioned and that is most flexible direction the project can go

**Comment by ddtm** [comment]
@jermainewang @tqchen Thanks for the clarifications. Do you have a rough timeframe for this dynamic allocation to be incorporated into the project?

I also wonder if it is difficult to implement the resizable structure for the current state of mxnet? Which steps should be taken in order to add this feature?

**Comment by ddtm** [comment]
Still hoping for some guidelines

**Comment by tqchen** [comment]
see https://github.com/dmlc/mxnet/blob/master/doc/tutorial/bucketing.md
