### ISSUE TITLE
Databases with numpy

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#791]
I have several large numpy arrays I'd like to use for training, but they don't all fit in main memory. I know I can use NDArrayIter if I have the arrays in main memory, but I'd like to store and read them from disk. How can I store/read them using mxnet? These are not images.

**Comment by piiswrong** [comment]
I'm working on that feature now.
in the mean time, you can try ndarrayiter with this: http://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html
I've never tried this, but it should work. just remember to turn off shuffling.

**Comment by winstywang** [comment]
Stay tuned. Will contribute a PR soon

**Comment by mazeLinx** [comment]
@winstywang does this issue be fixed?

**Comment by yl2612** [comment]
@piiswrong NDArrayIter doesn't work on numpy memory maps with more than 65535 number of arrays. I have a (75000, 4, 128, 128) nd-array and when I used NDArrayIter, it said `TypeError: Invalid type '<class 'numpy.core.memmap.memmap'>' for data`.

**Comment by yangshao** [comment]
@yl2612 I come across the same error as you for the TypeError, Did you solve it  or not?

**Comment by yl2612** [comment]
@yangshao i wrote my own iterator instead

**Comment by yangshao** [comment]
hi，can you share it？ thanks a lot！

**Comment by haehn** [comment]
@yl2612 @yangshao did you solve this? if yes, could you please share code?
