### ISSUE TITLE
InferShape Error in softmax's label argument

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#794]
I created NDArrayIter by numpy array and then feed it to `model.fit`. However, I got error as follow:
```python
MXNetError: InferShape Error in softmax's label argument
Corresponding keyword of symbol: softmax_label
Shape inconsistent, Provided =(100, 1), inferred shape=(100)
```
I did this by using the mnist example script.

**Comment by piiswrong** [comment]
Corresponding keyword of symbol: softmax_label
Shape inconsistent, Provided =(100, 1), inferred shape=(100)

as you can see the model want's (100) and your label's shape is (100,1).
just do label=label.squeeze() and you should be good.

**Comment by wangg12** [comment]
@piiswrong Thanks!
