### ISSUE TITLE
RReLU activation?

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#803]
In the example here: https://github.com/dmlc/mxnet/blob/master/example/notebooks/cifar-100.ipynb RReLU is used as the activation, but when I try using it in my network I get the following error: 

`mxnet.base.MXNetError: Invalid Input: 'rrelu', valid values are: {'relu', 'sigmoid', 'softrelu', 'tanh'}`

**Comment by antinucleon** [comment]
Please use ```LeakyReLU``` instead of ```Activation```

**Comment by jmschrei** [comment]
It works, thanks. What's the reason for the separation between LeakyReLU and activations?

**Comment by piiswrong** [comment]
LeakyReLU has parameters, activations dont.
