### ISSUE TITLE
strange speed problem with c_api.

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#806]
hi, guys , I have finished the cpp version predictor with ```c_api```. but the speed is bad.
the strange thing is that the cpp version's speed is worst than python version's.
such as, do prediction on the same image, the speed is ```40ms in python```, but ```200ms in cpp```.(I am very surely that the cpp version's ```device_type==2(gpu)```).
the timer is ```time.time() in python``` and ```gettimeofday() in cpp```.
I have checked the base code of python, and sure that the base ```c_api``` functions used in cpp are in the same way with python's.
such as: ```MXExecutorForward``` and ```MXExecutorOutputs``` and ```MXNDArraySyncCopyToCPU```.
Did I miss something important? :cry: 

I am gonna to use ```c_predict_api``` to implement the predictor. I hope it will be quicker.
What do you think?

**Comment by starimpact** [comment]
The more weird thing is that, the time cost of predict of CPP version becomes same to Python version's when I run the predict more than one times.

**Comment by tqchen** [comment]
Normally prediction is bounded by computation(which are already in c++), which means moving to c++ may not speed you up.

**Comment by starimpact** [comment]
i know it.

**Comment by tqchen** [comment]
Was due to some resources are lazily allocated in first run
