### ISSUE TITLE
max pooling accepts kernels which are too big

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#810]
If I set the kernel to be bigger than the dimension size in python, it just reduces that dimension to 1. I presume this works correctly for max pooling (though perhaps doing more calculations than necessary?), but it might mess up average pooling. Regardless, it should probably raise a warning/error to let the user know the dimensions mismatch.

**Comment by piiswrong** [comment]
here is code in infershape:
```C
    oshape[2] = std::min(dshape[2] + 2 * param_.pad[0] - param_.kernel[0] + param_.stride[0] - 1,
                         dshape[2] + 2 * param_.pad[0] - 1) / param_.stride[0] + 1;
    oshape[3] = std::min(dshape[3] + 2 * param_.pad[1] - param_.kernel[1] + param_.stride[1] - 1,
                         dshape[3] + 2 * param_.pad[1] - 1) / param_.stride[1] + 1;
    CHECK(oshape[2] > 0 && oshape[3] > 0) << "Pooling: kernel size exceed input";
```
Looks like it crashes in this case unless pad is big enough. Are you padding?

**Comment by jmschrei** [comment]
I'm using the default pad.

**Comment by piiswrong** [comment]
That's strange. It should have crashed. Could you print something before src/operator/pooling-inl.h:183 and check if there are anything wrong?

**Comment by tqchen** [comment]
any progress on this thread? please reopen if there is update
