### ISSUE TITLE
Order of RGB channel

### ISSUE THREAD

**Issue by zhouye** [dmlc/mxnet#820]
The decoded image in mxnet is stored as RGB order, but in the file https://github.com/dmlc/mxnet/blob/master/src/io/iter_normalize.h, line 180-182

      data[0] -= param_.mean_b;
      data[1] -= param_.mean_g;
      data[2] -= param_.mean_r;

The mean_b variable stand for the mean value of the R channel. I think it's a little confusing for people who want to manually set these parameters.

**Comment by qiaohaijun** [comment]
you mean it is a bug?

**Comment by zhouye** [comment]
Maybe it's a bug. This part behaves the same as cxxnet.

**Comment by tqchen** [comment]
Nice catch, can you please send a PR to fix this? Thanks!

**Comment by zhouye** [comment]
I think it may need some extra work to preserve the compatibility of old models and config files. Do you have any ideas?

**Comment by tqchen** [comment]
It is OK, as existing configuration when mean value is set, they are identical

**Comment by zhouye** [comment]
See https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_imagenet.py.
Is the mean value correct in this configuration?

**Comment by tqchen** [comment]
see what you mean cc @antinucleon can you comment on this?

**Comment by tqchen** [comment]
Let us simply fix this, as most model released so far use mean-image configs

**Comment by antinucleon** [comment]
@zhouye Thanks for catching this! Let's fix it for now. The pretrained model is using mean value: 117, 117, 117 so doesn't hurt. But for other self-trained model, it may has slightly influence.

**Comment by antinucleon** [comment]
https://github.com/dmlc/mxnet/pull/822
