### ISSUE TITLE
[Javascript] Call for Contribution and Suggestions

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#821]
This thread is opened to bring attention to https://github.com/dmlc/mxnet.js . The javascript port of mxnet that runs completely on browser, thanks to emscripten and amalgamation. This is fun. This thread is opened for suggestions and contributions to the library, including

- [ ] Improve html demo
- [ ] Cleanup and generate documents for Javascript code
- [ ] More fun demos, as it enables any mxnet model basically on js.

None of the current DMLC developers are javascript hackers, so the library was in primal but working stage, we are definitely looking for contributors to improve and lead the project

**Comment by skevidu** [comment]
Nice idea. We just need a working plan.

**Comment by gujunli** [comment]
Very Nice, I still need to catch up with the white paper to learn more. I
will post if I have any suggestions. Great job, guys!

thanks.
junli

On Fri, Dec 4, 2015 at 1:07 PM, skevidu <notifications@github.com> wrote:

> Nice idea. We just need a working plan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/821#issuecomment-162082021>.
>



-- 
************************************************
Junli Gu--谷俊丽
Coordinated Science Lab
University of Illinois at Urbana-Champaign
************************************************

**Comment by tqchen** [comment]
moving discussion directly to https://github.com/dmlc/mxnet.js/issues/2
