### ISSUE TITLE
build failed on OSX library not found for -lgomp

### ISSUE THREAD

**Issue by skevidu** [dmlc/mxnet#825]
Build failed on Mac OSX version 10.10.5
Anyone can help?

ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libmxnet.so] Error 1
make: *** Waiting for unfinished jobs....
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/libmxnet.a(mxrtc.o) has no symbols
In file included from tools/im2rec.cc:21:
In file included from /usr/local/Cellar/opencv/2.4.12/include/opencv2/opencv.hpp:56:
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:961:18: warning: 'CvForestTree::train'
      hides overloaded virtual functions [-Woverloaded-virtual]
    virtual bool train( CvDTreeTrainData* trainData, const CvMat* _subsample_idx, CvRTrees...
                 ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:867:18: note: hidden overloaded virtual
      function 'CvDTree::train' declared here: different number of parameters (2 vs 3)
    virtual bool train( CvMLData* trainData, CvDTreeParams params=CvDTreeParams() );
                 ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:877:26: note: hidden overloaded virtual
      function 'CvDTree::train' declared here: different number of parameters (8 vs 3)
    CV_WRAP virtual bool train( const cv::Mat& trainData, int tflag,
                         ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:1149:18: warning: 'CvBoostTree::train'
      hides overloaded virtual functions [-Woverloaded-virtual]
    virtual bool train( CvDTreeTrainData* trainData,
                 ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:867:18: note: hidden overloaded virtual
      function 'CvDTree::train' declared here: different number of parameters (2 vs 3)
    virtual bool train( CvMLData* trainData, CvDTreeParams params=CvDTreeParams() );
                 ^
/usr/local/Cellar/opencv/2.4.12/include/opencv2/ml/ml.hpp:877:26: note: hidden overloaded virtual
      function 'CvDTree::train' declared here: different number of parameters (8 vs 3)
    CV_WRAP virtual bool train( const cv::Mat& trainData, int tflag,
                         ^
2 warnings generated.
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/im2rec] Error 1

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/issues/749

**Comment by skevidu** [comment]
Thanks.
solved from the suggestion from #749:

brew install clang-omp
make CXX=clang-omp++

**Comment by ShirleyLee1995** [comment]
appletekiMacBook-Air-3:bin apple$ brew install clang-omp
Warning: clang-omp-2015-04-01 already installed
appletekiMacBook-Air-3:bin apple$ make CXX=clang-omp++
make: *** No targets specified and no makefile found.  Stop.
why？
