### ISSUE TITLE
[alexnet initialize] I find that alexnet initial use normal will help to get good result

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#826]
the default initializer is Xavier. After a few test, I find that the alexnet model didn't converge well, when change to mx.initializer.Normal and get a converge result.

The initializer is so important

**Comment by mli** [comment]
i'm totally agree. could you please share your results, we can update the codes or put the results on README.md

**Comment by piiswrong** [comment]
Initialization and learning rate affects each other. my guess is with Xavier you need a smaller learning rate.

**Comment by qwzju0222** [comment]
Using Xavier initializer and setting learning rate as 0.001 also will converge.
After 20 epoch training can get 45% top-1 accuracy.
