### ISSUE TITLE
[dist-train] kill all mxnet job on different node

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#827]
I write a script to kill all mxnet job on different node, because I always kill the dist-train job after a few epoch to change the super parameter.

I post it out, maybe some one need it too .

**Comment by qiaohaijun** [comment]
#!/usr/bin/env python

import os, sys

if len(sys.argv) != 2:
  print "usage: %s <hostfile>" % sys.argv[0]
  sys.exit(1)

host_file = sys.argv[1]
prog_name = "train_imagenet"

# Get host IPs
with open(host_file, "r") as f:
  hosts = f.read().splitlines()
ssh_cmd = (
    "ssh "
    "-o StrictHostKeyChecking=no "
    "-o UserKnownHostsFile=/dev/null "
    "-o LogLevel=quiet "
    )
kill_cmd = (
    " "
    "ps aux |"
    "grep -v grep |"
    "grep 'python train_imagenet.py' |"
    "awk '{print \$2}'|"
    "xargs kill"
    )
print kill_cmd
for host in hosts:
  cmd = ssh_cmd + host +" \""+ kill_cmd+"\""
  print cmd
  os.system(cmd)

  print "Done killing"

**Comment by qiaohaijun** [comment]
https://gist.github.com/qiaohaijun/37337aa5542ce56d6b73

**Comment by qiaohaijun** [comment]
USEAGE
===

$ python kill-mxnet.py host.txt

and host.txt is the host list of node that the dist-train job run on.

**Comment by piiswrong** [comment]
@mli Maybe we can do this automatically?

**Comment by mli** [comment]
my usual way is 

```
cat hosts | xargs -I{} ssh -o StrictHostKeyChecking=no {} 'uname -a; pgrep python | xargs kill -9'
```

though it kills all python jobs...

**Comment by qiaohaijun** [comment]
@mli  yes, your way kill all python jobs, How can to identify the mxnet job?

**Comment by qiaohaijun** [comment]
@piiswrong the best way I think is automatically kill the mxnet job

**Comment by mli** [comment]
it's often the resource manager's job to do the kill. the current problem is that when in default, we launch a remote process via ssh. see https://github.com/dmlc/ps-lite/blob/dev/tracker/dmlc_ssh.py#L71 

however, when the launching process is killed, the remote process are miserably still live.. there is definitely something wrong here.

**Comment by mli** [comment]
we definitely can find a way to solve it, by

1. either figure out why the remote process is still alive after the launching process is killed 
2. or we store the remote process id after luanching. once we stop or exit the launcher, we go the remote machine to kill that job if necessary. we can add this function here https://github.com/dmlc/mxnet/blob/master/tools/launch.py#L46

**Comment by tqchen** [comment]
My recommendation is look into some kind of resource manager, such as yarn or mesos. Things should be readily supported, especially, yarn support is already there

**Comment by qiaohaijun** [comment]
@tqchen it is a good idea.

**Comment by tqchen** [comment]
cross ref https://github.com/dmlc/mxnet/issues/533
