### ISSUE TITLE
[Discussion] FP16 Support

### ISSUE THREAD

**Issue by antinucleon** [dmlc/mxnet#833]
Ideally, we have everything to support FP16,
While trying to train Inception-7, I find out it is necessary to support FP16 now, as it is so memory consuming.

Let's set a milestone.

**Comment by piiswrong** [comment]
The question is do we want it as a global constant or a per tensor variable. The former requires rebuilding to switch and the later requires major refactor of frontend code, since it's currently const there.

**Comment by tqchen** [comment]
we want a per tensor type aware thing, so fp16 can be part of the graph

**Comment by piiswrong** [comment]
Then we need to discuss how to handle this in python and cudnn. Currently mx_float is a const. 
Also do we want to alway convert or let mshadow support different source/target type?

**Comment by tqchen** [comment]
mshadow is typed, and mshadow accept DataType as flag, we can use mshadow's cast operator to cast between types. There is a type flag in TBlob already, need a patch to support dtype in NDArray

**Comment by piiswrong** [comment]
Does cudnn support mixed type operations?

**Comment by tqchen** [comment]
Unlikely, but we can do explicit cast op

**Comment by piiswrong** [comment]
Should data type be the property of symbol?

**Comment by tqchen** [comment]
Hmm, I guess we can support some kinda of inference, and make datatype one loose property like device

**Comment by tqchen** [comment]
The quickest way is to first make low level operator type aware, and support cast, so things can be added gradually, as opposed to need to support everything

**Comment by piiswrong** [comment]
I think we can make mshadow primitives support different input/output type. Then later we can add type inference to minimize casting.

**Comment by tqchen** [comment]
mshadow primitive ***already*** support mixed type, like
```c++
Tensor<xpu,float> a;
Tensor<xpu, fp16> b, out;
out = cast<fp16>(a) + b;
```
The last line generate one kernel that takes fp16 and float input and add to

**Comment by piiswrong** [comment]
can we make the cast implicit

**Comment by tqchen** [comment]
currently no due to type inference cost, but I guess it works for most of case we need

**Comment by piiswrong** [comment]
What do you mean by type inference cost? Can it be resolved at compile time?

**Comment by tqchen** [comment]
Yes, it can be, except we need to cost some engineering to write the type inference code, we can do it gradually, first by explicit cast, then add implicit inference

**Comment by piiswrong** [comment]
Ok. Let's try to do this properly so we can easily support all types. I think TF also supports int. should be useful for softmax and nlp models.

**Comment by futurely** [comment]
https://github.com/dmlc/mxnet/pull/1675

**Comment by KiddoZhu** [comment]
@tqchen How can I use cast<> in my code? I cannot find a definition of cast in mshadow.
