### ISSUE TITLE
Strange error in loading checkpoint

### ISSUE THREAD

**Issue by sofiawu** [dmlc/mxnet#836]
I used the windows cpu mxnet library  and I run the predict code with the model 
There is a error when I want to load the trained model. The error message is below:

 in __init__
    self.model = mx.model.FeedForward.load(model_prefix, load_epoch, ctx=mx.cpu(
), numpy_batch_size=1)
  File "D:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\model.py", lin
e 787, in load
    symbol, arg_params, aux_params = load_checkpoint(prefix, epoch)
  File "D:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\model.py", lin
e 437, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "D:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\symbol.py", li
ne 767, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "D:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line
 74, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:31:19] D:\chhong\mxnet\dmlc-core\include\dmlc/json.h:
510: Check failed: (ch) == ('{') Error at Line 0, around ^`er2013-symbol.json`,
Expect '{' but get 'f'

I felt very strange about the path D:\chhong\mxnet\dmlc-core\include\dmlc/json.h: 
because I don't have this path and it seem the absolut path of the person who built
the window mxnet cpu version.

**Comment by piiswrong** [comment]
what's the content of er2013-symbol.json? Does it start with an 'f' instead of '{'?
