### ISSUE TITLE
TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by wxbforwork** [dmlc/mxnet#840]
hi there, I just install the latest mxnet in Ubuntu 14.04 according to the installation guide http://mxnet.readthedocs.org/en/latest/build.html.When I try to run train_mnist.py example, there comes an error like this:
![screenshot from 2015-12-06 11 32 16](https://cloud.githubusercontent.com/assets/14830489/11611525/a990f12a-9c0d-11e5-8331-3e31d446f752.png)
When I try "import mxnet"  in python, it is successfully imported. About a month ago I ran train_mnist.py from earlier version and there was no error printed.
The error has troubled me a few days.I tried to read related file and codes, but it is a little difficult for me.Please tell me why this error is happened.Thank you!

**Comment by piiswrong** [comment]
I works fine for me. try update to the newest mxnet version and make clean & make

**Comment by AllenSCU** [comment]
I got the same problem. At last I comment out the line "initializer = mx.init.Xavier(factor_type="in", magnitude=2.34)," in train_model.py file and then It works. In addtion, I can't find mx.init.Xavier() in mxnet, just finding some initial  methods like mx.init.normal(). Could anyone tell me where is it?

**Comment by piiswrong** [comment]
@AllenSCU Please pull the latest changes.

**Comment by AllenSCU** [comment]
Thank you so much. :D
