### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by hack1nt0** [dmlc/mxnet#843]
At the bottom there are detail configuration file of mine, just skip to them if you are in a hurry.

========

+ Brew install opencv clang-omp libiomp openblas

Default clang compiler don't support openmp yet, so change the CC and CXX to clang-omp and clang-omp++ respectively. 

Also add proper path to ADD_LDFLAGS and ADD_CFLAGS for openblas detecting.

========

+ Install CUDA and CUDNN

[CUDA](https://developer.nvidia.com/cuda-downloads), and update ADD_LDFLAGS properly.

[CUDNN](https://developer.nvidia.com/cudnn), and union CUDA's include folder and lib folder with the CUDNN ones respectively.

========

### My config.mk:
------------------------------------------------------------------------------------------------------
```shell
export CC = clang-omp
export CXX = clang-omp++ -std=c++11
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS = -L/usr/local/opt/openblas/lib -L/usr/local/cuda/lib -L/usr/local/lib

# the additional compile flags you want to add
ADD_CFLAGS = -I/usr/local/opt/openblas/include -I/usr/local/include

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA libary to link and compile flag
# if you have already add them to enviroment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = /Developer/NVIDIA/CUDA-7.5

# whether use CUDNN R3 library
USE_CUDNN = 1

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iteraor
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
USE_BLAS = openblas
```
-------------------------------------------------------------------------------------------------------
### My .bash_profile:
-------------------------------------------------------------------------------------------------------
```shell
# added by clang-omp
export OPENMP_HOME=/usr/local/Cellar/libiomp/20150701
export CLANGOMP_HOME=/usr/local/Cellar/clang-omp/2015-04-01
export PATH=$CLANGOMP_HOME/bin:$PATH
export C_INCLUDE_PATH=$CLANGOMP_HOME/libexec/include/clang-c:$OPENMP_HOME/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$CLANGOMP_HOME/libexec/include/c++/v1:$OPENMP_HOME/include:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$CLANGOMP_HOME/libexec/lib:$OPENMP_HOME/include:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CLANGOMP_HOME/libexec/lib:$OPENMP_HOME/include:$LD_LIBRARY_PATH

#added by cuda
export LD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:$LD_LIBRARY_PATH
export PATH=/Developer/NVIDIA/CUDA-7.5/bin:$PATH
```

-----------------------------------------------------------------------------------------------------

**Comment by piiswrong** [comment]
Uh... Is this a question or a guide? If it's a guide please consider open a PR and merge it into the doc. Your contribution is appreciated.

**Comment by hack1nt0** [comment]
OK, Thanks.

**Comment by tqchen** [comment]
@hack1nt0 is there any update on this? A PR on this guide to https://github.com/dmlc/mxnet/blob/master/doc/build.md is greatly appreciated

**Comment by hack1nt0** [comment]
@tqchen  @piiswrong:

Sorry for late reply, but I came cross a new make error on 'bin/im2rec' after upgraded my Mac OS to 10.11.2.

And I have submited a new issue. Only When it solved I can confidently contribute to PR.
