### ISSUE TITLE
cpp interface compiling error

### ISSUE THREAD

**Issue by toothacher17** [dmlc/mxnet#844]
Hi, all

I am using mxnet for neural networks, which would be integrated as a part into a new model. I have asked you for some suggestions before in #369. Thanks to your suggestions, I implemented the python version already, and got a primary but promising result.

I am now trying to rewrite it with cpp for efficiency and speed. However, I am not very familiar with cpp. The cpp examples are very limited. I am trying the exmaple/cpp/use_ ndarray.cpp example. Basically, my code is:

![image](https://cloud.githubusercontent.com/assets/7029845/11616035/71b34fa6-9c3e-11e5-9a5f-19ee1506c541.png)

The compiling context is:
(1). python code is runnable, so the compile should be right

(2). I tested the mxnet::Tshape and mxnet::Context, they are correct (which means I could initialize and get its public attributes), but when I wanted to construct the NDArray, it reported error:

![image](https://cloud.githubusercontent.com/assets/7029845/11616043/92109128-9c3e-11e5-9493-a4429f98d484.png)

(3). But when I try to construct NDArray with default constructor, it is okay, which means "mxnet::NDArray a;" could pass the compile.

How could this problem happen? How could I solve it? Thanks a lot! @hjk41

**Comment by piiswrong** [comment]
You need -L../lib -lmxnet

**Comment by toothacher17** [comment]
Thank you a lot! Really really appreciated! That helped! Now I could run the basic like this:

![image](https://cloud.githubusercontent.com/assets/7029845/11617095/1f9cb6d4-9c58-11e5-82b1-0b812afdda7a.png)

However, when I am trying to do some operators on the NDArray, like +=, -=, it fails again:

the code is
![image](https://cloud.githubusercontent.com/assets/7029845/11617107/45dd3670-9c58-11e5-9f51-66fb265cbc84.png)

the compiling result is:
![image](https://cloud.githubusercontent.com/assets/7029845/11617111/5f7200ca-9c58-11e5-963d-0a67c0b62786.png)

I read the header file doc:

![image](https://cloud.githubusercontent.com/assets/7029845/11617116/88c77356-9c58-11e5-9a7d-21a8c1a8b7ae.png)

I think the += operator should be able to work? So code like "c += b;" should be working?

Thanks a lot!

**Comment by piiswrong** [comment]
as you can see, you are missing cblas_sgemm, which means you need to link to a blas library like -lopenblas.
Any symbol missing error most likely means missing library. Find them and link to them.

**Comment by toothacher17** [comment]
Thank you very much, everything is working now. Thank you very much!
