### ISSUE TITLE
[doc] Is there a plan to translate the core documents to chinese?

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#845]
MXNET has a lot user of China, is there a plan to translate the core documents to chinese?

**Comment by qiaohaijun** [comment]
@mli @tqchen

**Comment by tqchen** [comment]
I think the core team might not have enough time to do this, but we could love to have community effort on this, maybe even on a separate repo

**Comment by tqchen** [comment]
Sorry for the delayed reply as we were all at NIPS in the last week

**Comment by mli** [comment]
i'm agree that chinese translation is very important for china users. i'd love to have them, but probably seek help from other guys at @tqchen mentioned.
