### ISSUE TITLE
Is there a c++ example for predicting an image?

### ISSUE THREAD

**Issue by sofiawu** [dmlc/mxnet#846]
I find all the example are based on python, so is there any example based on c?

**Comment by zhangchen-qinyinghua** [comment]
Not yet.

I noticed that there's a simple example about how to use NDArray  with cpp interface now.

And I myself am currently struggling on bind executor and symbol and operators...

**Comment by sofiawu** [comment]
I write the predict C++ code use the c_predict_api.h, and it seems work.

**Comment by zhangchen-qinyinghua** [comment]
Oh you mean, Preidcting.
However, the Training in cpp code still seems hard by now.

**Comment by tqchen** [comment]
related #891
