### ISSUE TITLE
Imagenet 22k example

### ISSUE THREAD

**Issue by pjreddie** [dmlc/mxnet#847]
Is there an example of the training command for imagenet 22k? I found the model definition but not the actual command to train it, I'm wondering what batch size you used. Thanks!

**Comment by qiaohaijun** [comment]
@pjreddie  do you mean the super parameter of train job

**Comment by pjreddie** [comment]
Yeah probably. On the website [here](http://dmlc.ml/mxnet/2015/10/27/training-deep-net-on-14-million-images.html) it says the learning rates and stuff but not batch size. I followed the link but couldn't find the 22k specific command used for training. It looks like the default batch size is 32 but i'm not sure if you used a larger one or not.

**Comment by antinucleon** [comment]
The code is here:
https://github.com/dmlc/mxnet/tree/master/example/image-classification

The symbol definition is in symbol_inception-bn-full.py

You need to modify two places:

first change model symbol and add inception-bn-full in selection.

https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_imagenet.py#L9


second is change data iterator to point to right data:

https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_imagenet.py#L47


After these changing you can run train_imagenet.py. You need to set other
param when run this script.


You can try the batch size, usually we choose max size fit all memory, eg,
32/48/64

**Comment by pjreddie** [comment]
I'm just wondering what batch size was used for generating the graph on the website.

**Comment by antinucleon** [comment]
@pjreddie should be 32 per card.
