### ISSUE TITLE
[dist-train] script launch.py‘s  -n -s parameter

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#848]
how to set the number of 'n' and 's'?
how to maximize the use of cpu to compute update of weight. 
on my cluster, the cpu usage is less 30%

PS

$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2000.062
BogoMIPS:              4798.92
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31

**Comment by mli** [comment]
Often set -n to be the number of gpu machines you have. But you can set -s to a larger number , eg 2n. But the weights updating is often quite simple, 30% seems normal to me

**Comment by qiaohaijun** [comment]
@mli thanks, your reply help me a lot, I will not focus on it.

**Comment by qiaohaijun** [comment]
please close this issue
