### ISSUE TITLE
Imagenet training accuracy keeps 0.001 even after shuffling the data list

### ISSUE THREAD

**Issue by jimxinbo** [dmlc/mxnet#850]
I am running alexnet on imagenet12 data. I followed the im2rec tutorial where I definitely shuffled the datalist. But the train and val accuracy keep at around 0.001. Any suggestions?

Btw, I am using most of the default settings in train_imagenet.py (e.g. initial learning rate is 0.01) and the data were loaded in successfully.

I tried adding "shuffle = True" in ImageRecordIter, but as is expected this did not make any difference (given that my train.rec is generated from a shuffled list txt file).

Thx.

**Comment by qiaohaijun** [comment]
I occur the similiar problem.
I hope the following can help you

you change the 
https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L56
=>
        initializer        = mx.init.Normal(sigma=0.01),

and try it again

**Comment by qiaohaijun** [comment]
other way, you can add a new model named alexnet-bn, use the your current super parameter, it converge too.

**Comment by jimxinbo** [comment]
I see your point. I checked that changing the initializer in train_model.py worked for me. Great, thanks!

**Comment by qiaohaijun** [comment]
you are welcome, I find the initialization issue from the comparsion with caffe initialization.

**Comment by jimxinbo** [comment]
I see. That's a good catch.
