### ISSUE TITLE
Step by step guide of implementing a C++/MShadow layer

### ISSUE THREAD

**Issue by GravApple** [dmlc/mxnet#855]
Considering about the efficiency, I am very interested in implementing new C++/MShadow operators, and I have read through the mxnet documents and mshadow tutorial. However, creating a new layer still seems difficult to me, thus I am wondering if anyone could provide a step by step guide of implementing a C++/MShadow layer? 

Thanks in advance.

**Comment by qiaohaijun** [comment]
cool

**Comment by erogol** [comment]
I also want to see such guidance. I just switched from Caffe to MXNet but implementing a new layer is a pain in the neck here compared to the abstraction provided by Caffe.

**Comment by piiswrong** [comment]
Yes, we do need a tutorial for this. However we are currently short handed as half of the team is going to NIPS and it's X'mas after that. Any help on this is welcome.

Here is the set of documents that's missing:
How to create your own DataIter
How to create your own model
How to create your own C++ layer
How to solve your own model.

Again, we really appreciate any help on making MXNet easier to use. Please feel free to share your experiences.

**Comment by winstywang** [comment]
Please refer to this guide: https://mxnet.readthedocs.org/en/latest/developer-guide/operator.html Hope this helps.

**Comment by qiaohaijun** [comment]
is there is a plan translate the doc to chinese?

**Comment by winstywang** [comment]
@qiaohaijun Currently, the answer is no. We still have a lot of tasks at higher priority at hand. Your contribution is welcomed.

**Comment by GravApple** [comment]
@winstywang I have read through that, yet to understand them in a more detailed way still needs to trace through more codes, especially those functions referring to mshadow. I am wondering if you could give me a list of 'must-read' codes that I can check for?
Thanks.

**Comment by GravApple** [comment]
@piiswrong Thank you for your response. I believe the listed documents are important for those who want to use mxnet for research purpose, which will make surely mxnet a more powerful and wide used tool.

**Comment by winstywang** [comment]
@GravApple I suggest you to read through the examples in mshadow folder.

**Comment by ysh329** [comment]
mark

* How to create your own DataIter
* How to create your own model
* How to create your own C++ layer
* How to solve your own model.
