### ISSUE TITLE
Sampling from multiple databases

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#857]
In an unbalanced binary classification problem you often want to randomly select an equal number of positive and negative examples for each batch, despite the total number of positive and negative examples being vastly different. Is it possible to include iterator functionality to go over multiple datasets (arrays, memmaps, etc..), where each one corresponds to a different label, and have an equal number of each sample from each randomly selected?

Something like the following:

```
>>> positives.shape[0]
100
>>> negatives.shape[0]
1000000
>>> data = mx.io.NDArrayIter( { 'softmax_label' : { 0: negatives, 1: positives } }, batch_size=128, shuffle=True ) 
```

Then 64 samples would be drawn from negatives (with label 0) and 64 would be drawn from positives (with label 1).

**Comment by piiswrong** [comment]
You can do this by subclassing mx.io.DataIter

**Comment by winstywang** [comment]
Close for now. If you have any other questions, feel free to reopen it
