### ISSUE TITLE
KV store is used by default in train_imagenet example and it's hurting performance a lot  when batch size is small

### ISSUE THREAD

**Issue by piiswrong** [dmlc/mxnet#858]
KVStore is enabled by default even for single GPU training. And for small batch_size (128) it's reducing speed by half (compared to setting it to None)

An immediate fix would be to disable kvstore for single GPU training. However it's still strange that KVStore would affect performance for single GPU since it shouldn't be doing anything in this situation.

@mli

**Comment by mli** [comment]
That's possible since kvstore has extra memory copy. But what kind of nn and hardware you are using?

**Comment by piiswrong** [comment]
alexnet+TitanX. I changed --kv-store from 'local' to 'local_allreduce_device' and speed bumped from 350samples/s to 700samples/s

**Comment by qiaohaijun** [comment]
@piiswrong how many gpu cards do you use?

**Comment by cjnewstar111** [comment]
I use alexnet + 4gpus（Tesla K80）,and i use the kvstore with argument 'local'
but my speed is much lower：
while i use one gpu，the log of speed is "196.53 samples/sec"
when i use two gpus, the log of speed is "211.29 samples/sec"
when i use three gpus, the speed is "226.64 samples/sec"
when i use for gpus , the speed is "184.15 samples/sec"

**Comment by mli** [comment]
should be resolved by #932 

@cjnewstar111 you may consider to pass `--kv-store local_allreduce_device` more info https://github.com/mli/mxnet/tree/master/example/image-classification#note-on-performance
