### ISSUE TITLE
 Mxnet on Windows 10 error

### ISSUE THREAD

**Issue by bcd33bcd** [dmlc/mxnet#863]
I use the https://github.com/dmlc/mxnet/releases GPU version, all dll/lib path added in link file,but aslo report error.
![image](https://cloud.githubusercontent.com/assets/8981954/11654732/cd899e7a-9de2-11e5-8de8-f6fce1d2f31f.png)

**Comment by yajiedesign** [comment]
@bcd33bcd  do you add mxnet.lib?

**Comment by bcd33bcd** [comment]
I could not find mxnet.lib. Maybe you mean libmxnet.lib?

**Comment by yajiedesign** [comment]
yes,libmxnet.lib

**Comment by bcd33bcd** [comment]
I have contained the lib file already.But no effect.Could you send the file to my email address?THX. And don't forgent libmxnet.dll

**Comment by yajiedesign** [comment]
@bcd33bcd and you must complie with 64bit

**Comment by bcd33bcd** [comment]
Yes, I aslo complie with 64bit ,release.

**Comment by piiswrong** [comment]
try make clean, pull newest changes, make again

**Comment by bcd33bcd** [comment]
@piiswrong It doesn't work.Maybe my dll/lib files broken.Could you send me your libmxnet.dll/libmxnet.lib from email?

**Comment by hjk41** [comment]
You can download the pre-built library and sample VS solution from the
release tab of mxnet:
https://github.com/dmlc/mxnet/releases/tag/weekly_binary_build

On Wed, Dec 9, 2015 at 7:20 AM, bcd33bcd <notifications@github.com> wrote:

> @piiswrong <https://github.com/piiswrong> It doesn't work.Maybe my
> dll/lib files broken.Could you send me your libmxnet.dll/libmxnet.lib from
> email?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/863#issuecomment-163053641>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by bcd33bcd** [comment]
I did use the pre-built library but still occur the problem.

**Comment by hjk41** [comment]
We are building CPP wrapper of MxNet as a new project. You can track the progress here: https://github.com/hjk41/MxNet.cpp

Closing this issue for now.
