### ISSUE TITLE
Question about the default name of data and label

### ISSUE THREAD

**Issue by GravApple** [dmlc/mxnet#866]
I encountered the following error message
```
Symbol.InterShapeKeyword argument name softmax_label not found
```
When I traced through the codes, I found the following instructions in ```mxnet/io.py```
```
self.data = _init_data(data, allow_empty=False, default_name='data')
self.label = _init_data(label, allow_empty=True, default_name='softmax_label')
```
I am wondering if the name of the data symbol and output symbol must be ```'data'``` and ```'softmax'``` individually, and can't be customised?

**Comment by piiswrong** [comment]
No. All that's required is your dataiter provide data&label whose name match those in your network. For example if your loss layer is named 'l1' than your dataiter must output 'l1_label'

**Comment by vchuravy** [comment]
Maybe we should change softmax to take a symbol instead of having a fixed label name. It would also be more consistent with the regression outputs. Additionally if no symbol is provided we could automatically insert a symbol with the name `softmax_label`

**Comment by GravApple** [comment]
@piiswrong 
Thank you very much for your response. I see your point, and I changed the ```default_name``` in ```mxnet/io.py```, then the model works fine.
Thus I am wondering if there is a way to use customised name without directly changing in ```mxnet/io.py```?

====
In addition, I have a question about the backwards process of logistic regression. I find the following code in ```src/operator/regression_output.cc```
```
case reg_enum::kLogistic:
      return new RegressionOutputOp<cpu, mshadow_op::sigmoid, mshadow::op::minus>();
```
As you use ```minus``` as the ```BackwardOp```, then I am curious in which place you deal with the gradient of ```sigmoid```? Please let me know if I misunderstand something.

**Comment by piiswrong** [comment]
@GravApple sigmoid has the nice property that it's derivative is just y - l

**Comment by GravApple** [comment]
@piiswrong I see. I will try exploring mxnet more. Thank you for your patience.
