### ISSUE TITLE
build a windows project to use the mxnet lib,we can not execute it? what's the problem

### ISSUE THREAD

**Issue by freepjf** [dmlc/mxnet#867]
there is a simple example,i can build it with no error,but when i run the program, it shows the console but do nothing,and can not run to printf.what's the matter???

#include <stdio.h>
#include <windows.h>
#include "base.h"
#include "c_api.h"

int main()
{
	printf("strat");

	KVStoreHandle out;
	MXKVStoreCreate("local", &out);
	return 0;
}

**Comment by hjk41** [comment]
You are probably missing some DLLs. You will need to add the path to all
the dependent DLLs to you PATH. For example, if you use OpenBLAS, then
libopenblas.dll should be in your PATH, same as OpenCV and cuDNN.

On Wed, Dec 9, 2015 at 10:06 AM, freepjf <notifications@github.com> wrote:

> there is a simple example,i can build it with no error,but when i run the
> program, it shows the console but do nothing,and can not run to
> printf.what's the matter???
>
> #include
> #include
> #include "base.h"
> #include "c_api.h"
>
> int main()
> {
> printf("strat");
>
> KVStoreHandle out;
> MXKVStoreCreate("local", &out);
> return 0;
>
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by freepjf** [comment]
the project directory have all the dll:
cudart32_75.dll  cudart64_75.dll cudnn64_70.dll libgcc_s_seh-1.dll libgfortran-3.dll libmxnet.dll
libopenblas.dll libquadmath-0.dll libzmq-v120-mt-4_0_4.dll opencv_world300.dll

i can run the console with no error,  but it appear forever, do nothing. i build it with vs2013.

**Comment by hjk41** [comment]
Could you try if you can use the binary distribution here?:
https://github.com/dmlc/mxnet/releases/download/weekly_binary_build/20151209_win64_cpu_only.7z

Remember to run the *setupenv.cmd* file before opening
app/MxnetTestApp/MxnetTestApp.sln

On Wed, Dec 9, 2015 at 10:56 AM, freepjf <notifications@github.com> wrote:

> the project directory have all the dll:
> cudart32_75.dll cudart64_75.dll cudnn64_70.dll libgcc_s_seh-1.dll
> libgfortran-3.dll libmxnet.dll
> libopenblas.dll libquadmath-0.dll libzmq-v120-mt-4_0_4.dll
> opencv_world300.dll
>
> i can run the console with no error, but it appear forever, do nothing. i
> build it with vs2013.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867#issuecomment-163090236>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by freepjf** [comment]
i use your project to build, first:run setupenv.cmd,then open the project app/MxnetTestApp/MxnetTestApp.sln, copy all dll to the project dir, build is ok but run is the same error ?  if there any different enviroment between us?

**Comment by hjk41** [comment]
did you try the cpu-only version or the gpu version? For GPU, you will also
need cuDNN library.
1. run setupenv.cmd
2. open VS, then open the solution (VS must be started after you run
setupenv.cmd, or it won't load the PATH environment variable correclty)
3. if using cuDNN, put cudnn64_xx.dll into 3rdparty/cudnn. Make sure the
cudnn DLL file is in 3rdparty/cudnn/bin
4. build and run the program

On Wed, Dec 9, 2015 at 12:19 PM, freepjf <notifications@github.com> wrote:

> i use your project to build, first:run setupenv.cmd,then open the project
> app/MxnetTestApp/MxnetTestApp.sln, copy all dll to the project dir, build
> is ok but run is the same error ? if there any different enviroment between
> us?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867#issuecomment-163103737>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by sofiawu** [comment]
I have the same problem.
when I comment the functions in c_predict_api.h, it works well.
But when I use the functions , it just shows the console and even can not print the messages I put in the first line in main function.

**Comment by hjk41** [comment]
That's strange. Both CPU version and GPU version works alright for me, with
and without c_predict_api.h.

On Wed, Dec 9, 2015 at 12:26 PM, sofiawu <notifications@github.com> wrote:

> I have the same problem.
> when I comment the functions in c_predict_api.h, it works well.
> But when I use the functions , it just shows the console and even can not
> print the messages I put in the first line in main function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867#issuecomment-163105883>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by freepjf** [comment]
i take the same order, use your project, only build and run，but there is the same problem.

**Comment by hjk41** [comment]
Could you attach a screenshot of the error, both when running from console
and from VS? I cannot reproduce it here.

On Wed, Dec 9, 2015 at 12:45 PM, freepjf <notifications@github.com> wrote:

> i take the same order, use your project, only build and run，but there is
> the same problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867#issuecomment-163107784>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by freepjf** [comment]
i have email you with the 126 email, take a photo, you kan see i add printf,but the console didn't show,  f10 run it can not go to main. it can run with nothing error  but can not run to main.

**Comment by hjk41** [comment]
I see. VS is trying to load the debug symbols for the system DLLs. You can
see it from the "Output" window. If you wait for long enough, it will
eventually finish and enter the main function. This usually takes around a
minute or so, depending on your environment.

You can get rid of this behavior by undefining the "_NT_SYMBOL_PATH"
environment variable. Go to "My Computer"->"Properties"->"Advanced system
settings"->"Environment Variables"->"System variables", find
"_NT_SYMBOL_PATH", and then click "delete". Then, restart your VS, and it
should work just fine.


On Wed, Dec 9, 2015 at 1:30 PM, freepjf <notifications@github.com> wrote:

> i have email you with the 126 email, take a photo, you kan see i add
> printf,but the console didn't show, f10 run it can not go to main. it can
> run with nothing error but can not run to main.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867#issuecomment-163115407>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by sofiawu** [comment]
I have the same problem as @freejf.
I wait for a very long time maybe an hour and still can not enter the main function.
I check the system variables  and can not find the _NT_SYMBOL_PATH

**Comment by freepjf** [comment]
my computer config is E3-1230 v2,the environment did not have NT_SYMBOL_PATH, the problem is running for several hours。 it can not work。 the dll is no longger load from then on when i email you.
i think there is something different environment between you and me.

**Comment by hjk41** [comment]
Can you pause (Ctrl+Alt+Break) the program and see what it is doing? Is it
running in libmxnet.dll or some other dll?

On Wed, Dec 9, 2015 at 3:07 PM, freepjf <notifications@github.com> wrote:

> my computer config is E3-1230 v2,the environment did not have
> NT_SYMBOL_PATH, the problem is running for several hours。 it can not work。
> the dll is no longger load from then on when i email you.
> i think there is something different environment between you and me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867#issuecomment-163136284>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by freepjf** [comment]
it saids:  
title: The call stack contains only external code
you need to turn off just my code and load symbols in order to view source for this location

module information
version: 6.1.7601.19018 (win7sp1_gdr.150928-1507)
Original Location  C:\Windows\System32\ntdll.dll

**Comment by freepjf** [comment]
can you build a exe file to another pc(clean pc) to run?you can print "helloe word" for example.

**Comment by zhubuntu** [comment]
I have the same problem, Have you solved it?

**Comment by hjk41** [comment]
Sorry about late response. I really don't have a clue at this moment. Is it
possible for us to talk on QQ and show me your screen remotely?

On Sun, Dec 13, 2015 at 7:06 PM, zhubuntu <notifications@github.com> wrote:

> I have the same problem, Have you solved it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867#issuecomment-164247471>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhubuntu** [comment]
@hjk41 That will be so good, this is my friend's QQ number 282206777 ,he is having this problem too,and he is always at the laboratory. Thank you very much .

**Comment by freepjf** [comment]
i tried to use dynamic link,it is fine.

**Comment by zhubuntu** [comment]
@freepjf Do you mean use mxnet as dynamic link ,or you build your program as dynamic link.I did build my C++ program with libmxnet.dll but it didn't work.

**Comment by hjk41** [comment]
@freepjf <https://github.com/freepjf> I guess you mean linking the VC
runtime library as dynamic?

On Mon, Dec 14, 2015 at 8:44 PM, zhubuntu <notifications@github.com> wrote:

> @freepjf <https://github.com/freepjf> Do you mean use mxnet as dynamic
> link ,or you build your program as dynamic link.I did build my C++ program
> with libmxnet.dll but it didn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/867#issuecomment-164427767>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by freepjf** [comment]
I use  LoadLibrary("libmxnet") when I build my project, it is fine

**Comment by hjk41** [comment]
After some debugging with @zhubuntu, we found that Windows 7 cannot correctly execute the problem, while Windows 8.1 and Windows 10 work fine. If you are having the same issue, try @freepjf 's approach, or upgrade your OS.

**Comment by xylcbd** [comment]
oh my god... is this issue fixed ?

**Comment by blakeliu** [comment]
My os is windows7, and i compiled release and debug version, is not work!!! and i tried https://github.com/dmlc/mxnet/releases/download , also not work

**Comment by guker** [comment]
I also found that Window7 cant not work ,but I have sloved it. 
method:
1. use  windows api function :  LoadLibraryA
2. use  windows api function:   GetProcAddress , load interface of mxnet
