### ISSUE TITLE
solver parameter set？

### ISSUE THREAD

**Issue by achao2013** [dmlc/mxnet#869]
I just want to ask how to control the test interval and snapshot in the training process?

**Comment by piiswrong** [comment]
use callbacks in mx.callbacks

**Comment by qiaohaijun** [comment]
you can read the python code ‘train_model.py’ in example

**Comment by achao2013** [comment]
from mx.callbacks, i can only use batch_end_callback or epoch_end_callback, but i want a paramter like iter_end_callback in the mxxnet document.

**Comment by piiswrong** [comment]
we renamed iter to batch (I think)

**Comment by achao2013** [comment]
so i think i need to develop a function by myself that i can specify the iterval to test or snapshot

**Comment by piiswrong** [comment]
I think simple use checkpoint as batch_end_callback should work
