### ISSUE TITLE
[R] object 'mx.ctx.internal.default.value' not found

### ISSUE THREAD

**Issue by utengr** [dmlc/mxnet#870]
Finally getting a chance to go through the vignette and I cannot get the model to predict.  I get the following error on the MNIST example:

> preds <- predict(model, test)
Error in mx.ctx.default() : 
  object 'mx.ctx.internal.default.value' not found

Here is the model summary:
> summary(model)
           Length Class         Mode
symbol     1      Rcpp_MXSymbol S4  
arg.params 6      -none-        list
aux.params 0      -none-        list

**Comment by thirdwing** [comment]
@utengr  Can you tell me which operating system and which version of R you are using?

`'mx.ctx.internal.default.value' not found` error in Windows has been reported in #714 .

I just don't have enough time to track down this. It is around the end of semester and exams are coming.

**Comment by utengr** [comment]
Sorry, I know better than that.  Here it is, but take care of finals first :)

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          2.2                         
year           2015                        
month          08                          
day            14                          
svn rev        69053                       
language       R                           
version.string R version 3.2.2 (2015-08-14)
nickname       Fire Safety

**Comment by utengr** [comment]
Update:  Restarted R and it works fine for now, but according to others it may be only temporary.  I'll keep monitoring it.

**Comment by dmi3kno** [comment]
This [gist ](https://gist.github.com/mick001/a32f2a5540a7dcca880948a939108bcc)here has the following description of the problem:

> I noted that when you call "require(mxnet)" it generates the mx.ctx.internal.default (or something similar) variable and if you accidentally delete it from the workspace (for instance using rm(list=ls()) you need to restart R or the entire RStudio in order for mxnet functions to work properly.

**Comment by thirdwing** [comment]
This has been fixed in #3010
