### ISSUE TITLE
Error with GPU

### ISSUE THREAD

**Issue by zhaofan0622** [dmlc/mxnet#871]
(1) I can run the demo using GPU successfuly.
"python example/image-classification/train_mnist.py --network lenet --gpus 0"

(2) I can run my own model using CPU successfuly.

(3) When I run my model using GPU, I get an error:

[10:36:06] ./dmlc-core/include/dmlc/logging.h:208: [10:36:06] src/engine/./threaded_engine.h:295: [10:36:06] ./mshadow/mshadow/././cuda/tensor_gpu-inl.cuh:281: Check failed: (dst.size(0)) == (label.size(0)) SoftmaxGrad: label shape mismatch
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'

**Comment by piiswrong** [comment]
your label shape is wrong. check if you have an extra dimension

**Comment by zhaofan0622** [comment]
@piiswrong 
My 'image.lst'  TXT  file is created by MATLAB. I have checked this file  and found no problem. If ignoring the check,I can run my model with GPU, but the train accuracy drops gradually.

**Comment by zhaofan0622** [comment]
@piiswrong ,
I have known the reason,but without solution. my network only has convolutional layers, and the input of final softmax layer is the output of  final convolutional layer.I'm sure that the output of  final convolutional layer is 1*1*K(K classes),but in softmax layer, it isn't  consistent with the 1D label .

**Comment by piiswrong** [comment]
reshape final convolutional layer output to (K,) with reshape symbol

**Comment by tqchen** [comment]
closing due to inactive status, please feel free to reopen
