### ISSUE TITLE
the speed of 4GPUS is slower than 1 GPU

### ISSUE THREAD

**Issue by cjnewstar111** [dmlc/mxnet#872]
Hi, I have a problem about the speed.
I use the mxnet to train the imagenet-1k with alexnet and the batch size is 256.  I have 4 gpus(Telsa K80) in one machine.
here is the log of the mxnet:
1 gpu: "Speed: 196.53 samples/sec";  
2 gpus:"Speed: 211.29 samples/sec"
3 gpus:"Speed: 226.64 samples/sec"
4 gpus:"Speed: 184.15 samples/sec"
Maybe i configured some parameters inappropriately。I need help， thanks！

**Comment by tqchen** [comment]
could due to slow PCI, maybe you can try ```kvstore=local_allreduce_device```

**Comment by cjnewstar111** [comment]
thanks for your reply。
the pci bus of my machine is pci-e, and it works well for the CXXNET.
while i ues the "local_allreduce_device",all of the speed is faster than before, but the speedup rate is still not expected. here is the log:
one gpu(Tesla K80):    "Speed: 409.13 samples/sec"
two gpu(Tesla K80):     "Speed: 485.46 samples/sec"
three gpu(Tesla K80):  "Speed: 540.19 samples/sec"
four gpu(Tesla K80):    "Speed: 595.51 samples/sec"

**Comment by cjnewstar111** [comment]
my arguments of the train_imagenet.py is like this:
--network=alexnet  --kv-store=local_allreduce_device  --data-dir=F:/DeepLearning/data/imagenet/  --model-prefix=F:/DeepLearning/data/imagenet/model/  --batch-size=256 --gpus=0,1,2,4

**Comment by piiswrong** [comment]
I think the recent changes cause bad choices for KVStore reduce methods. It's also happening to me. In addition batch_size is affecting speed in an unpredictable way. @mli Could you look into it?

**Comment by mli** [comment]
Alexnet eats a lot of pcie bandwidth. We often use a much larger batchsize. The inception network is much better

**Comment by piiswrong** [comment]
@mli KVStore.create is unaware of the context being used (which is gpu) and always select 'local_allreduce_cpu' which cause gradients to be copied to CPU even for single GPU training. We should change the interface to include context

**Comment by mli** [comment]
#858 #932

**Comment by z-xiuxiu** [comment]
I also have a problem about the speed. when I train a model, the speed is lower and lower during the training process. I use 4  gpus (TITAN X) and here is the training speed
![screenshot from 2017-04-21 09 12 44](https://cloud.githubusercontent.com/assets/27837384/25258670/99629f3c-2673-11e7-8ddc-d059166ea55a.png)
