### ISSUE TITLE
How can I obtain gradient feedback over the input image?

### ISSUE THREAD

**Issue by erogol** [dmlc/mxnet#877]
Given an image, I want to see the gradient feedback propagated to the input image. Is it viable with MxNet?

**Comment by winstywang** [comment]
just check grad_map['data']

**Comment by erogol** [comment]
I try to find grad_map in cifar-10 example but no success. where should I call grap_map?

**Comment by winstywang** [comment]
You need to check the exact name of the gradient map in your codes. You can also check the adversary example in example folder

**Comment by erogol** [comment]
where is the related module for "from data import mnist_iterator"

**Comment by winstywang** [comment]
It should be in the example folder named data.py

**Comment by tqchen** [comment]
close for inactive status, please feel free to reopen
