### ISSUE TITLE
[R]Shiny App - Failed to recognize format of file

### ISSUE THREAD

**Issue by The-Dub** [dmlc/mxnet#878]
Hi,
First thank you for putting together this library and writing a shiny app for that. When i saw that i got very excited, but unfortunately I can't manage to make it work.
The image loads properly, but the ML library throw me some errors that I don't know what it means / how to solve it, so I'm posting here hoping for some explanation.

Here is what i get when i try to throw an image at it (it's actually the picture in the folder, from Crouching Tiger Hidden Dragon):

<code>[08:52:26] d:\chhong\mxnet\src\operator\./softmax_output-inl.h:187: Softmax symbol is renamed to SoftmaxOutput. This API will be deprecated in Dec, 2015
Invalid Parameter - "C:\\Users\\e018304\\AppData\\Local\\Temp\\5q1Sb05N.pnm"
'gm.exe' is not recognized as an internal or external command,
operable program or batch file.
Invalid Parameter - "C:\\Users\\e018304\\AppData\\Local\\Temp\\5219wn01.pnm"
'gm.exe' is not recognized as an internal or external command,
operable program or batch file.
Invalid Parameter - "C:\\Users\\e018304\\AppData\\Local\\Temp\\5Qlg398Y.pnm"
'gm.exe' is not recognized as an internal or external command,
operable program or batch file.
Error in eval(substitute(expr), envir, enclos) : 
  [instance(0,0,0,0,0000000000000000,non-shared)] CImg<double>::load(): Failed to recognize format of file 'C:\Users\e018304\AppData\Local\Temp\Rtmpe8wNya\shinyapp542c4b513ca2\mxnet_shiny-master\cthd.jpg'.</code>

If anybody could let me know if it's a bug or me that's doing something wrong, I'll be very grateful!
thank you !

**Comment by thirdwing** [comment]
@The-Dub Sorry for this. Windows doesn't have imagemagick installed by default.

Can you follow the link below to install imagemagick and try again?

http://www.imagemagick.org/script/binary-releases.php

**Comment by The-Dub** [comment]
I installed it and made sure the "vcomp120.dll" was properly installed on my machine, but I still encounter the same error. 
Do i need to associate something with imagemagick?

**Comment by thirdwing** [comment]
@The-Dub Please give me more time.

`gm.exe` should be part of imagemagick.

**Comment by The-Dub** [comment]
thank you, i will try to reinstall it, maybe something went wrong

**Comment by thirdwing** [comment]
Your problem is actually from imager.

Maybe you can get help from https://github.com/dahtah/imager

He is the real expert on this.

On Thu, Dec 10, 2015 at 8:43 AM, The-Dub <notifications@github.com> wrote:

> Reopened #878 <https://github.com/dmlc/mxnet/issues/878>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/878#event-488180656>.
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by The-Dub** [comment]
Oki doki, thank you for your help :)!

**Comment by danmalter** [comment]
@The-Dub I know this issue is closed, but just to confirm, the same issue was resolved for me on a Mac after I downloaded imagemagick using homebrew.
