### ISSUE TITLE
make error on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by zizhan** [dmlc/mxnet#883]
my Graphics is Intel Iris Pro.

I got a warning like:
clang-3.5: warning: argument unused during compilation: '-pthread'
ld: warning: directory not found for option '-L/Developer/NVIDIA/CUDA-7.5/lib64'
Undefined symbols for architecture x86_64:
 "__ZN5mxnet2op24CreateRegressionOutputOpIN7mshadow3gpuEEEPNS_8OperatorENS0_8reg_enum20RegressionOutputTypeE", referenced from:    __ZNK5mxnet2op20RegressionOutputPropILNS0_8reg_enum20RegressionOutputTypeE1EE14CreateOperatorENS_7ContextE in regression_output.o
 __ZNK5mxnet2op20RegressionOutputPropILNS0_8reg_enum20RegressionOutputTypeE0EE14CreateOperatorENS_7ContextE in regression_output.o
......

Make error is like:
ld: symbol(s) not found for architecture x86_64
clang-3.5: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libmxnet.so] Error 1

Thx in advance.

**Comment by piiswrong** [comment]
Iris Pro doesn't support cuda. So you need to turn it off

**Comment by zizhan** [comment]
@piiswrong thanks a lot. finally successfully complie and train... T T
