### ISSUE TITLE
question about default blas chosen for windows

### ISSUE THREAD

**Issue by teng88** [dmlc/mxnet#886]
according to the documentation, should the default blas chosen for windows be "blas", however, currently is "atlas"?

**Comment by jimxinbo** [comment]
Not sure if this will help, but I have successfully build up mxnet on windows.

Regarding blas, I download the latest binary package of openblas from http://www.openblas.net/. Once you run Cmake, it will complain about not finding atlas, where you can just set BLAS to be Open; and then using the corresponding include dir and libs.

**Comment by piiswrong** [comment]
@hjk41 Could you have a look?

**Comment by hjk41** [comment]
It is caused by the cmake file in MShadow.

I think we should set OpenBLAS as default. More and more people are using
OpenBLAS nowadays.

On Thu, Dec 10, 2015 at 4:02 PM, Eric Junyuan Xie <notifications@github.com>
wrote:

> @hjk41 <https://github.com/hjk41> Could you have a look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/886#issuecomment-163528256>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by teng88** [comment]
really quick answer :+1: 
I can help to change this if you are willing to.

**Comment by hjk41** [comment]
Already pushed to mshadow, you can pull the latest mshadow and clear cmake
cache, then it should try to find OpenBLAS by default.

On Thu, Dec 10, 2015 at 4:42 PM, Teng Cao <notifications@github.com> wrote:

> really quick answer [image: :+1:]
> I can help to change this if you are willing to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/886#issuecomment-163534618>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by teng88** [comment]
:+1:
