### ISSUE TITLE
Error from ‘im2rec.py’ and 'make_list.py'

### ISSUE THREAD

**Issue by handyzeng** [dmlc/mxnet#889]
Python version: 3.4
Visual Studio 2013 Win64 build

1.
In ‘im2rec.py’ and 'make_list.py', error happens in the function 'make_list'.
The 'chunk_size' is a float value, so it can not be the index of 'image_list'.
I think it is better change the line
 'chunk_size = N/num_chunks' 
  to 
 'chunk_size = int(N/num_chunks)'

2. Whe use im2rec.py,  I had the following error:
Traceback (most recent call last):
  File "im2rec.py", line 160, in <module>
    main()
  File "im2rec.py", line 157, in main
    write_record(args, image_list)
  File "im2rec.py", line 70, in write_record
    record = mx.recordio.MXRecordIO(args.prefix+'.rec', 'w')
  File "D:\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\mxnet-0.
5.0-py3.4.egg\mxnet\recordio.py", line 32, in __init__
    uri = ctypes.c_char_p(uri)
TypeError: bytes or integer address expected instead of str instance
Exception ignored in: <bound method MXRecordIO.__del__ of <mxnet.recordio.MXReco
rdIO object at 0x0000000002430278>>
Traceback (most recent call last):
  File "D:\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\mxnet-0.
5.0-py3.4.egg\mxnet\recordio.py", line 44, in __del__
    if self.writable:
AttributeError: 'MXRecordIO' object has no attribute 'writable'

I don't know why. 
Can anybody help?

Thanks,

Best wishes,

**Comment by piiswrong** [comment]
1 is a python 2&3 compatibility thing. In python 2 1/2==0 and in python 3 1/2 == 0.5...
2 is a python 3 bug. I'll look into it

**Comment by handyzeng** [comment]
Thanks。
Python 2.7 runs well。

发自我的 iPhone
