### ISSUE TITLE
[error] Check failed: (param_.workspace) >= (required_size) 

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#890]
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [15:04:06] src/engine/./threaded_engine.h:295: [15:04:06] src/operator/./convolution-inl.h:258: Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 666989568 Bytes
Given: 536870912 Bytes

**Comment by qiaohaijun** [comment]
GPU k40m
12G memory
when this error ocur, just use  4786MiB memory

what's the problem

**Comment by piiswrong** [comment]
This is a known bug and it will be fixed after https://github.com/dmlc/mxnet/pull/873 is merged
@tqchen this is the cudnn algorithm bug I talked about

**Comment by qiaohaijun** [comment]
@piiswrong @tqchen  #873  work
