### ISSUE TITLE
How to take multiple rows from Embedding layer?

### ISSUE THREAD

**Issue by swpd** [dmlc/mxnet#892]
From the documentation, currently the embedding layer only support taking **one-hot** input to retrieve one row from the embedding weight matrix.

I want to take multiple rows (say, **N** rows, **N** is not fixed) from the embedding and then sum all these rows up before feeding to the next layer. Is it possible to achieve this with the current implementation of **MXNet**, or should I customize a new embedding layer?

Besides, can the weight matrix be updated in a sparse manner? For example in language model the vocabulary size might be **~1M**, while only a relatively small number of rows of embedding matrix need to be updated given a training instance. With sparse updating a lot of memory can be saved.

Any help would be appreciated!

**Comment by Kublai-Jing** [comment]
I don't think currently mxnet supports this feature. To give you a temporary solution, you can allocate a (batch_size, embedding_dimension) matrix using mxnet. And use numpy yourself to do whatever you want (taking multiple rows in numpy is easy) and just do something like:

    exec.embed[:] = np.sum(W[ind,:], axis=0)

. Then just train the model and everytime you call backward(), you need to update the numpy parameters by yourself.

**Comment by jiumem** [comment]
@pluskid does it support now? In my case, I want to train a item2vec model and each item will be represented by multiple rows from the embedding layer.

**Comment by pluskid** [comment]
I'm not sure if I understand you correctly. In a recent update we updated the Embedding operator to support arbitrary input dimension. Say if you have an input of shape `(10, 20)`, each element is the index of the word in the vocabulary. Then the output will be of shape `(10, 20, D)` where `D` is the embedding dimension. The current (updated) [char-lstm example](https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py#L66) actually uses this feature.

**Comment by pluskid** [comment]
For memory efficient gradient updating. @tqchen implemented memory efficient gradients computing. But I am not sure the updating part (optimizer) could be easily implemented for sparse updating as we probably need to modify the kvstore to support sparse matrices (or do we already support?). @tqchen or @mli might be able to give some comments.

**Comment by jiumem** [comment]
Pretty good! thanks! @pluskid
