### ISSUE TITLE
Error while image_width != image_height

### ISSUE THREAD

**Issue by srand99** [dmlc/mxnet#893]
The training program can not work while the image width and height are different.
I can train the samples with 80x80 pixels, but 64x72 could no work.
In my training, image_width=64 and image_height=72.

I used data_shape = (3, 72, 64), then I got an error:
[[[19:45:42] ./dmlc-core/include/dmlc/logging.h:208: [19:45:42] src/io/./image_augmenter.h:198: Check failed: static_cast<index_t>(res.cols) >= param_.data_shape[1] && static_cast<index_t>(res.rows) >= param_.data_shape[2] input image size smaller than input shape
I print all of them, the result is:
res.cols=64, param_.data_shape[1]=72, res.rows=72, param_.data_shape[2]=64

I changed the parameter to: data_shape = (3, 64, 72), then I got another error:
[19:47:01] ./dmlc-core/include/dmlc/logging.h:208: [19:47:01] ./mshadow/mshadow/./tensor_cpu-inl.h:124: Check failed: (_dst.shape_) == (_src.shape_) Copy:shape mismatch:(3,64,72) vs (3,72,64)

Thanks.

**Comment by tqchen** [comment]
This is can be fixed, by changing it to 
```
static_cast(res.rows) >= param_.data_shape[1] && static_cast(res.cols) >= param_.data_shape[2] 
```
Thanks for the catch! Do you mind to open a PR for this?

cc @sneakerkg @winstywang

**Comment by tqchen** [comment]
fixed by https://github.com/dmlc/mxnet/pull/900
