### ISSUE TITLE
R package compilation error

### ISSUE THREAD

**Issue by dselivanov** [dmlc/mxnet#894]
I got following error while package compilation (`R CMD INSTALL mxnet_0.5.tar.gz`):

> ndarray.cc: In static member function ‘static void mxnet::R::NDArray::Save(const List&, const string&)’:
ndarray.cc: In static member function ‘static void mxnet::R::NDArray::Save(const List&, const string&)’:
ndarray.cc:220:15: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<std::__cxx11::basic_string<char> >’ and ‘Rcpp::NamesProxyPolicy<Rcpp::Vector<19> >::const_NamesProxy’)
     lst_names = data_lst.names();

**Comment by dselivanov** [comment]
I removed ` -std=c++11` flag from `CXXFLAGS` in my *Makevars*  file and this resolves problem. But why this is so important?

**Comment by thirdwing** [comment]
@dselivanov I am sorry that I also don't have any idea about this.

Can you tell me which operating system and which version of R you are using?

**Comment by dselivanov** [comment]
I installed mxnet and `R 3.2.2` on fresh new *ubuntu 15.10*, `gcc 5.2`. But mxnet shared library I used `gcc 4.9` as nvidia only supports 4.9 branch.

**Comment by dselivanov** [comment]
should we close this or keep as a reminder?

**Comment by thirdwing** [comment]
I have to say that we have troubles with GCC5 in other Rcpp-realted projects. I am trying to figure out the real reasons.

**Comment by dselivanov** [comment]
@thirdwing same error - **ndarray.cc:220:32: error: ambiguous overload for 'operator='** with latest version from master ( https://github.com/dmlc/mxnet/tree/e0be39ddc6fe15b18f6fc09f9ad061ac3378b668 ) and `gcc-6/g++-6` on OS X:
> g++-6 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../inst/include -DUSEAVX -DUSEOMP                                                 -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Users/dymitriyselivanov/Library/R/3.3/library/Rcpp/include"  -mavx2 -fopenmp -fPIC  -Wall -mtune=core2 -g -O2  -march=native -Ofast -c ndarray.cc -o ndarray.o
In file included from ndarray.cc:7:0:
./base.h: In function 'std::__cxx11::string mxnet::R::toPyString(const string&, const RObject&)':
./base.h:276:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < vec.size(); ++i) {
                        ~~^~~~~~~~~~~~
./base.h: In function 'std::vector<unsigned int> mxnet::R::Dim2InternalShape(const Rcpp::Dimension&)':
./base.h:340:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < rshape.size(); ++i) {
                      ~~^~~~~~~~~~~~~~~
./ndarray.h: In destructor 'mxnet::R::NDBlob::~NDBlob()':
./base.h:83:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro 'MX_CALL'
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:83:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:34:7: note: in expansion of macro 'MX_CALL'
       MX_CALL(MXNDArrayFree(handle));
       ^
ndarray.cc: In member function 'void mxnet::R::NDArrayPacker::Push(const RObjectType&)':
ndarray.cc:133:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     RCHECK(shape_.size() == rshape.size())
            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
ndarray.cc:136:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       RCHECK(shape_[i] == rshape[i])                         
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
ndarray.cc: In member function 'Rcpp::NumericVector mxnet::R::NDArrayPacker::Get() const':
ndarray.cc:153:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   RCHECK(ret.size() == data_.size());
          ~~~~~~~~~~~^~~~~~~~~~~~~~~
./base.h:73:9: note: in definition of macro 'RCHECK'
   if (!(x)) RLOG_FATAL << "RCheck failed: " #x << ' ' /* NOLINT(*) */
         ^
ndarray.cc: In member function 'std::size_t mxnet::R::NDArray::Size() const':
ndarray.cc:194:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (size_t i = 0; i < dim.size(); ++i) {
                      ~~^~~~~~~~~~~~
ndarray.cc: In static member function 'static void mxnet::R::NDArray::Save(const List&, const string&)':
ndarray.cc:220:32: error: ambiguous overload for 'operator=' (operand types are 'std::vector<std::__cxx11::basic_string<char> >' and 'Rcpp::NamesProxyPolicy<Rcpp::Vector<19> >::const_NamesProxy')
     lst_names = data_lst.names();

**Comment by dselivanov** [comment]
Reinstalled all with `clang-3.8` toolchain which comes with llvm38 (can be installed with `brew install llvm38` ) - no issues... 
(note that we also should reinstall `Rcpp` with same toolchain - see https://github.com/RcppCore/Rcpp/issues/555)
Here is my `~/.R/Makevars` for `clang-3.8` - hope will be useful for somebody
```
CXX   = clang++-3.8
CXX1X = clang++-3.8
CC    = clang-3.8
CXX1XFLAGS += -mtune=native -Ofast
CXXFLAGS   += -mtune=native -Ofast
CFLAGS     += -mtune=native -Ofast
#for clang-3.8 openmp
#copied /usr/local/Cellar/llvm/3.8.1/lib/clang/3.8.1/include/omp.h
#to /usr/local/include
PKG_LIBS       += -L/usr/local/Cellar/llvm/3.8.1/lib -liomp5
PKG_CPPFLAGS   += -DUSEAVX -DUSEOMP
PKG_CXX1XFLAGS += -mavx -fopenmp=libomp
PKG_CXXFLAGS   += -mavx -fopenmp=libomp
PKG_CFLAGS     += -mavx -fopenmp=libomp
```

Also 2 lines in config.mk should be adjusted to work properly with clang-3.8 and openmp:

```sh
# the additional link flags you want to add
ADD_LDFLAGS = -L/usr/local/Cellar/llvm/3.8.1/lib -liomp5
# the additional compile flags you want to add
ADD_CFLAGS = -fopenmp=libomp
```
