### ISSUE TITLE
how to initialize the weights

### ISSUE THREAD

**Issue by sofiawu** [dmlc/mxnet#902]
I want to init the fc layer weights alone , how to do ?

**Comment by tqchen** [comment]
You can pass pre-initialized weight into  Feedforward as in 

https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L479

The Feedforward is a thin wrapper of  NDArray and initialization happens here https://github.com/dmlc/mxnet/blob/master/python/mxnet/model.py#L540 You can do arbitrary operations you like to initialize the ndarrays like in this function. Either by reusing initializer class, or do your own initialization

**Comment by qiaohaijun** [comment]
this issue help a lot

**Comment by gaush123** [comment]
Hi @qiaohaijun, I am extremely new to mxnet, could you please shed some more light regarding the solution. May I know what exact changes do I need to make, to change weight initialization method of one particular layers, along with changing its mean and std, like we do in Caffe
`weight_filler { type: "gaussian" mean: 0.0 std: 0.01 }`

Thanks,
Gaurav

**Comment by MissFishLi** [comment]
Hi @gaush123 , I wondered if your problem has solved. Could you please shall your solution with me?

**Comment by gaush123** [comment]
No, I didn't exactly solve this issue.

**Comment by II-Matto** [comment]
@gaush123 @MissFishLi Check out the initializers: http://mxnet.readthedocs.io/en/latest/packages/python/model.html#module-mxnet.initializer. Probably the `Load` or `Mixed` will suit your needs.
