### ISSUE TITLE
Context  of parameters of a network in GPU is shown CPU 

### ISSUE THREAD

**Issue by erogol** [dmlc/mxnet#905]
In the example predict-with-pretrained-model.ipynb if I do the following 

```
# Load the pre-trained model
prefix = ROOT_PATH+"Inception_BN"
num_round = 39
model = mx.model.FeedForward.load(prefix, num_round, ctx=mx.gpu(), numpy_batch_size=1)

for i in model.arg_params.values():
    print i.context
```

All the output is cpu(0) even I guess the code is executed in GPU while prediction. I guess this is a bug.

**Comment by tqchen** [comment]
All the parameters  of ```mx.model``` resides in are on cpu and will be copied to GPU before training and copied back after it finishes. This makes things easier to load  GPU trained models into CPU.

**Comment by erogol** [comment]
Thanks for the explanation.
