### ISSUE TITLE
First NDArray allocation very slow

### ISSUE THREAD

**Issue by lukemetz** [dmlc/mxnet#907]
This is a semi bug report due to a bad interaction between opencv 3.0.0 and mxnet.

With opencv 3.0.0 compiled with cuda and opencl the first allocation of an NDarray on a gpu performed by mxnet takes around 30 seconds to complete.

When recompiling opencv 3.0.0 without cuda and opencl the first allocation is .194 seconds. 

The second allocation in both cases is very fast, (0.00014) and a cpu context is also very fast.

I was experiencing a similar issue in theano (https://github.com/Theano/Theano/issues/3351) which is very strange. I am not exactly sure what is wrong and where this should be filed, but I wanted to make some note just in case another has this issue.

**Comment by piiswrong** [comment]
This also happened to me when I link to cuda enabled opencv. I ended up disabling it. You can try nvidia-smi -pm 1 to set the gpus in persistent mode. It helps a bit

**Comment by yajiedesign** [comment]
set arch code gencode
Reference http://codeyarns.com/2014/03/03/how-to-specify-architecture-to-compile-cuda-code/
