### ISSUE TITLE
new cpp example error, Cannot find Operator FullyConnected in registry error

### ISSUE THREAD

**Issue by toothacher17** [dmlc/mxnet#908]
Hi, all

The new small cpp example is pretty cool and help understand how to use cpp with mxnet. I tried to use it but failed. The code was able to compile, but would get:

![image](https://cloud.githubusercontent.com/assets/7029845/11759620/3aa071ee-a04c-11e5-99c7-b0b96e5e1c30.png)

The use_ndarray.cc code was able to run. But the mlp.cc code could not. It is strange since I checked operator.cc code, the FullyConnencted Operator should be already registered. I asked the contributor but she did not meet with that problem. Does anyone of you meet this kind of question? It would be great if you can solve my questions or offer any suggestions.

Thanks a lot

**Comment by piiswrong** [comment]
could you try to add a line at operator.cc:19 to print out the name of registered Operators?

**Comment by toothacher17** [comment]
I try to print out the size of all registered operators, here is the code:

![image](https://cloud.githubusercontent.com/assets/7029845/11760116/d4857c8c-a05b-11e5-8aea-e18fead8fa00.png)

and I got the result is:

![image](https://cloud.githubusercontent.com/assets/7029845/11760118/df6ca83c-a05b-11e5-9adc-9f6ec1cf76e4.png)

it seems that no Operators were registered... Was it related with the Mac Machine? I was able to run with python and NDArray example

Thanks

**Comment by zhangchen-qinyinghua** [comment]
@toothacher17 
1.
Really strange. Especially you got 0 as the size of the list.
Also, I test the code on Mac Os,  and it runs well.

2.
However, I do make a mistake here.
I handled the NDArray by hand, so I should add:
```
in_args[i].WaitToRead();
```
in every training loop.
I will fix this later.

**Comment by toothacher17** [comment]
yes, it is really strange, especially considering that the python code could run....

**Comment by toothacher17** [comment]
Was it related to the libmxnet.so file?

**Comment by toothacher17** [comment]
@zhangchen-qinyinghua @piiswrong If I compiled the program with libmxnet.so in the mxnet/lib/ folder, then the program would get this error:

![image](https://cloud.githubusercontent.com/assets/7029845/11762724/abf70642-a0be-11e5-8701-d74b5f124d05.png)

If I compiled it without libmxnet.so in the folder mxnet/lib/ (i moved it to another directory for python), then it would happen with the error I mentioned before.

I believe this could be the problem. The registered Operators should be in the dynamic library, which is more reasonable structure. So it is unreasonable for me to compile the code without the .so file in the mxnet/lib/ folder...

I am not sure whether this is the problem...If it is, how to solve it with the error of the image I showed?

**Comment by zhangchen-qinyinghua** [comment]
@toothacher17 
If ./mlp is in ./path/, then try to make a link of libmxnet.so in ./path/lib/. And run ./mlp in ./path.
This should help.

Besides, how did you compile your project? I think you should always use libmxnet.a.

**Comment by toothacher17** [comment]
@zhangchen-qinyinghua . @piiswrong . Thanks a lot, it is some problem with the dynamic lib, the including path related problem. I worked in screen and did not source it, so the updated path was not added into the whole project. It is solved now. Sorry for the so stupid question causing the confusion and time wasting......Thank you very much!

**Comment by zhangchen-qinyinghua** [comment]
@toothacher17 
It's OK.
