### ISSUE TITLE
Intern position in MSRA for developing MxNET

### ISSUE THREAD

**Issue by hjk41** [dmlc/mxnet#916]
I am hiring an intern to develop MxNET in MSRA. Some of my working items include:
1. C++ interface for MxNET, including some examples
2. Distributed training in Microsoft
3. Windows support for MxNET and setting up pre-merge testing for Windows

Either part time or full time is welcome. If you are interested, send me an email at chhong(at)microsoft.com

**Comment by mli** [comment]
also post at weibo?

**Comment by hjk41** [comment]
Let's try it on github first. If some contributor is interested, that would
be great. I will try Weibo if no one is interested here.


On Mon, Dec 14, 2015 at 12:13 PM, Mu Li <notifications@github.com> wrote:

> also post at weibo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/916#issuecomment-164339017>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
Cool.
Will working remotely be OK?

I am working on C++ interface too, and It is part of my current work.

**Comment by hjk41** [comment]
@zhangchen-qinyinghua Do you have an IM? Let's have a chat. You can add my Skype: hongchuntao, or Google Hangout: chuntao.hong(at)gmail.com

**Comment by zhangchen-qinyinghua** [comment]
@hjk41 
Yeah, sure.

**Comment by piiswrong** [comment]
Closed due to inactive status. Feel free to reopen if any update.
