### ISSUE TITLE
change the python code

### ISSUE THREAD

**Issue by UniqueAndys** [dmlc/mxnet#918]
Recently I want to change some code under mxnet/python/mxnet, specificly the model.py. I have follow the installation, "cd python; python setup.py develop --user", which allows to change the python code. I have changed the code, but I still can't get the result. Can someone fix this problem for me?

**Comment by piiswrong** [comment]
Try add mxnet/python to your python path and you won't need to install

**Comment by UniqueAndys** [comment]
@piiswrong I have added mxnet/python to my python path in ~/.bashrc, the question is whether I change the file under mxnet/python/mxnet/**.py, for examples, I add logging.info('***') in callback.do_checkpoint,
I can't see the content I add in the terminal window.

**Comment by UniqueAndys** [comment]
@piiswrong When I use the python interface code, does it really call the .py under mxnet/python? Because even I remove all the files under mxnet/python, it also works!

**Comment by piiswrong** [comment]
Probably because you installed mxnet before. Try remove it first

**Comment by tqchen** [comment]
The best way to keep things up to date with pulls, is simply remove all installations from user side, and add the mxnet/python to PYTHONPATH

**Comment by UniqueAndys** [comment]
@piiswrong @tqchen Thank you very much! When I running my program, I force quiting it and find out that the python lib I use actually lies under the anaconda path because I use the "python setup.py install" to install. When I use "python setup.py develop --user" to install, it won't add to the anaconda path, or as you said @piiswrong , I just need to add the mxnet/python.

**Comment by tqchen** [comment]
Thanks for the catch, added the detail in https://github.com/dmlc/mxnet/blob/master/doc/build.md#python-package-installation for developer recommendations, please see if there is anything can be improved
