### ISSUE TITLE
always error :compile with USE_DIST_KVSTORE=1 to use dist_sync 

### ISSUE THREAD

**Issue by cupermanrose** [dmlc/mxnet#920]
I want test ./image-classification/train_mnist.py in dist-training on local machine.But always error at :compile with USE_DIST_KVSTORE=1 to use dist_sync.It even error when I test "kv = mxnet.kv.create('dist_sync')" in Python.I have modified and compiled config.mk before I tested.Could you give me some help?

**Comment by mli** [comment]
are you using windows? it seems that we didn't test the distributed version at windows yet, i'll have a look once i got my new surface setup @hjk41

**Comment by cupermanrose** [comment]
@mli It errors in Linux.When I first compiled,the makefile is "USE_DIST_KVSTORE=0".Then I changed the makefile , "make clean_all" and make again like you say in one issue.
![image](https://cloud.githubusercontent.com/assets/15868412/11801100/83f85e78-a31d-11e5-8a62-4582f009e75f.png)

**Comment by tqchen** [comment]
It is likely you need to reinstall the package after you remaked the project.

**Comment by mli** [comment]
so your compilation is finished successfully? from the error log, it seems that you installed the python package. i suggest you to reinstall the python package since the libmxnet.so is changed.

**Comment by tqchen** [comment]
see option 2 in http://mxnet.readthedocs.org/en/latest/build.html#python-package-installation

**Comment by cupermanrose** [comment]
@ml  @tqchen  Thanks a lot!I deleted the python package and updated mxnet.And I run image-classification/train_mnist.py with dist_sync successfully.I think it was ending training but throw exception like this
![image](https://cloud.githubusercontent.com/assets/15868412/11802461/eb8c9122-a32b-11e5-8071-90fee48afce9.png)

One more question,does it make error if I just type "import mxnet;kv = mxnet.kv.create('dist_sync')" in python?(when I tested ,the error log
![image](https://cloud.githubusercontent.com/assets/15868412/11802546/e0694956-a32c-11e5-8866-9380cb173a61.png)
)
If it will be wrong,I think the doc http://mxnet.readthedocs.org/en/latest/distributed_training.html need to have a little modification.

**Comment by mli** [comment]
if you use dist_sync or dist_async, we often expect that you run the program by `tools/launch.py`, rather than just `python`

see example

https://github.com/dmlc/mxnet/tree/master/example/image-classification#distributed-training

**Comment by cupermanrose** [comment]
@mli  ok,thanks for help!
