### ISSUE TITLE
Something about operator parameter

### ISSUE THREAD

**Issue by zhangchen-qinyinghua** [dmlc/mxnet#921]
Check the code here:
https://github.com/dmlc/mxnet/blob/master/src/operator/convolution-inl.h#L364

parameter is declared private.

What about making it public, and making the definition of a parameter in a single header so that c/cpp users could use them easily?

**Comment by zhangchen-qinyinghua** [comment]
**I am far from finishing reading the code now, so correct me if I was wrong.**

I think it it not like dynamic languages, such as Python, R and Java, new operators registered cannot be seen by C++ during runtime, so one has to expose them by hand.
And during this, something awkward happens.

To use the symbol and graph, which I think is quite useful, one has to make the operator a symbol first.
This includes setting up the parameters, and as far as I know, two ways to do so:

Check the code here:
https://github.com/dmlc/mxnet/blob/master/src/operator/convolution-inl.h#L364
and here:
https://github.com/dmlc/mxnet/blob/master/include/mxnet/c_api.h#L402

Either way includes something like this:
**You transfer a integer to string, Mxnet transfers string back to integer.**

And notice that the parameters in operators are always private, so you cannot change it by hand(not mention that the parameters are not exposed to users at all). You must use the ways described previously.

So I don't know any better ways to avoid this, and my suggestion:
Why not just expose part of each operators( especially the parameters) to (c/cpp) users as a header, and this not seem to increase the amount of work when adding new operators.

**Comment by piiswrong** [comment]
Operators are not meant to be created by user. They are automatically created by symbol during binding

**Comment by tqchen** [comment]
The idea is to allow user to create op in an agnostic way. For example:

```
auto* op = Operator::Create("FullyConnected");
op->Init({{"num_hidden", "10"}, {"data", 2}});
```

**Comment by zhangchen-qinyinghua** [comment]
@piiswrong @tqchen 
Sure, I do understand why it is designed this way.
However, this way do not seem to give any convenience when using the c/cpp interface.

Anyway, I'll close the issue for now.

**Comment by tqchen** [comment]
I get your point, the major problem was to get a good sugar with support for reflection style interface. It is interesting to ask how to create a language sugar for composing symbols. Maybe something from @mavenlin 's purine could be borrowed.

For example, 

```
Net << Op("FullyConnected") << set("num_hidden", 10) << set("no_bias", true)
       << Op("Activation") << set("act_type", "relu");
```

Please open a new issue (say. C++ syntax sugar for symbolic consturction) to discussion this question.

We can expect put these as addon libraries to what we have so far

**Comment by zhangchen-qinyinghua** [comment]
@tqchen 
Yeah, exactly what I mean.
I wonder if it is possible for CPP to have the reflaction feature. I've never used Purine, but the example you showed looks cool.
I'll open a new issue as you suggested later.
