### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by wangxianliang** [dmlc/mxnet#924]
explicit ResourceTempSpace(Context ctx, size_t ncopy)
        : ctx(ctx), space(ncopy), resource(ncopy), curr_ptr(0) {
      mshadow::SetDevice<xpu>(ctx.dev_id);
      for (size_t i = 0; i < space.size(); ++i) {
     **space[i] = new mshadow::TensorContainer<xpu, 1, real_t>();**
        resource[i].var = Engine::Get()->NewVariable();
        resource[i].id = static_cast<int32_t>(i);
        resource[i].ptr_ = space[i];
        resource[i].req = ResourceRequest(ResourceRequest::kTempSpace);
      }
    }
    ~ResourceTempSpace() {
      for (size_t i = 0; i < space.size(); ++i) {
        mshadow::TensorContainer<xpu, 1, real_t>* r = space[i];
        Engine::Get()->DeleteVariable(
           [[ r ]]RunContext rctx){
              MSHADOW_CATCH_ERROR(r->Release());
            }, ctx, resource[i].var);
**// no delete here**
      }
    }

**Comment by antinucleon** [comment]
TensorConatiner is like Vector, will be auto deleted at the end.

**Comment by tqchen** [comment]
Nice catch, need to add delete r; after 
```
MSHADOW_CATCH_ERROR(r->Release());
```
This need to be done in lambda function so that it is delayed executed.
Can you open a PR to solve this?

**Comment by tqchen** [comment]
fixed by https://github.com/dmlc/mxnet/pull/933
