### ISSUE TITLE
Simple Linear Regression Example

### ISSUE THREAD

**Issue by rinuboney** [dmlc/mxnet#926]
I'm trying to write a simple linear regression example like in [this theano tutorial](https://github.com/Newmu/Theano-Tutorials/blob/master/1_linear_regression.py).
```python
import mxnet as mx
import numpy as np

trX = np.linspace(-1, 1, 101)
trY = 2 * trX + np.random.randn(*trX.shape) * 0.33

X = mx.sym.Variable('data')
Y = mx.sym.Variable('softmax_label')

Y_ = mx.sym.FullyConnected(data=X, num_hidden=1)

cost = mx.sym.square(Y - Y_)

model = mx.model.FeedForward(symbol=cost, num_epoch=1, learning_rate=0.05, numpy_batch_size=101)

model.fit(X=trX, y=trY)
```
I get the following error:
```
Traceback (most recent call last):
  File "1_linear_regression.py", line 16, in <module>
    model.fit(X=trX, y=trY)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 714, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 541, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 376, in infer_shape
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 74, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in _minus0's rhs argument
```
1. What could be the problem?
2. What is the purpose of LinearRegressionOutput symbol? What is the difference between having and not having the symbol at the end of a net?

**Comment by piiswrong** [comment]
You need the LinearRegressionOutput to compute a loss for training

**Comment by rinuboney** [comment]
It works when I use LinearRegressionOutput
```python
import mxnet as mx
import numpy as np

trX = np.linspace(-1, 1, 101)
trY = 2 * trX + np.random.randn(*trX.shape) * 0.33

X = mx.sym.Variable('data')
Y = mx.sym.Variable('softmax_label')

Y_ = mx.sym.FullyConnected(data=X, num_hidden=1)

cost = mx.sym.LinearRegressionOutput(data=Y_, label=Y)

model = mx.model.FeedForward(symbol=cost, num_epoch=100, learning_rate=0.05, numpy_batch_size=1)

model.fit(X=trX, y=trY)
```
1. How can I define my own loss?
2. How can I access the weights of the FeedForward network?

**Comment by vchuravy** [comment]
For defining your own loss you will have to extend the RegressionOutput operator (similar to https://github.com/oist/mxnet/commit/4857f74ada4c2320d6f968f96c18b52d5bf7e72a). It would be great if we had a more general solution for this.

**Comment by dpolaski2** [comment]
Any answer on how to access the weights of the FeedForward network?

**Comment by lukemetz** [comment]
`FeedForward` has an dictionary of ndarray that correspond to all inputs to the graph, so in this case the input data, the input labels, and the model weights are inside. Look at what `model.arg_params` has in it. Grab the parameters that you want and then convert them to numpy with `asnumpy()`.
