### ISSUE TITLE
Is there any examples for full conv-network or feature map?

### ISSUE THREAD

**Issue by JamesKnowton** [dmlc/mxnet#927]
Hi, all, Thanks for your great work on mxnet. It's really fast and friendly. I have a question, can mxnet work for multi-task training or fine-turn network? For example, such as this paper from Jaderberg
```
http://www.robots.ox.ac.uk/~vgg/publications/2014/Jaderberg14/jaderberg14.pdf
http://arxiv.org/pdf/1502.02766v3.pdf
```

I want to train one network at first, and then use it's feature to fine-turn another dataset. After that, I will do two prediction task. What's more,  How about following full-conv with maxout network's implementation? Is there any examples? 

![20151214235028](https://cloud.githubusercontent.com/assets/16066374/11785593/815c6b56-a2bd-11e5-8091-3c17d42bb218.png)

**Comment by tqchen** [comment]
Yes, this might be related https://github.com/dmlc/mxnet/blob/master/example/notebooks/predict-with-pretrained-model.ipynb

**Comment by JamesKnowton** [comment]
Hi, @tqchen , thanks for your comment. But I think maybe it's a no downsample network. I mean, input an image and get an image out. Look at the figure 1 and 2. How can I write such example in mxnet?

**Comment by vchuravy** [comment]
@JamesKnowton You will have to use `SoftmaxOutput` with `multi_output=true` to get a multidimensional feature map with probabilities. For multi-task learning you can use several independent `SoftmaxOutput` layers.
I don't think mxnet currently has maxout, so you will have to implement that as an activation function.

**Comment by tornadomeet** [comment]
@JamesKnowton i have finished the temporary image segmentation example here:https://github.com/tornadomeet/mxnet/tree/seg/example/fcn-xs
it is input an image and output the segmentaiton image, maybe it is helpful for u.
i 'll make that example more concise and give a PR in the furture.

**Comment by JamesKnowton** [comment]
Thanks, @vchuravy , maybe I can gibe a PR about maxout function.
@tornadomeet , Thanks for your share. I will try your model.
