### ISSUE TITLE
Building error with MKL in Ubuntu 14.04

### ISSUE THREAD

**Issue by yzgysjr** [dmlc/mxnet#928]
Hi,

I have some problems building mxnet in Ubuntu 14.04.

In make/config.mk, I set
```{makefile}
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = mkl
endif
USE_INTEL_PATH = /usr/local/intel/mkl/include 
```

I had my MKL installed in a slightly different directory.

```{bash}
/usr/local/intel$ find . -name mkl.h
./compilers_and_libraries_2016.0.109/linux/mkl/include/mkl.h
```

And the information produced is

```{bash}
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -I/usr/local/intel/mkl/include /mkl/include -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -MM -MT build/resource.o src/resource.cc >build/resource.d
g++: error: /mkl/include: No such file or directory
make: *** [build/resource.o] Error 1
```

It is a bit strange that g++ wants to compile the directory /mkl/include...

Could any one kindly give me some help ? Thx :)

**Comment by piiswrong** [comment]
why are you setting USE_INTEL_PATH to /usr/local/intel/mkl/include when your mkl is installed at ./compilers_and_libraries_2016.0.109/linux/mkl/include/mkl.h

**Comment by yzgysjr** [comment]
@piiswrong  thank you for your help.

The problem is solved by setting

```{bash}
USE_INTEL_PATH = /usr/local/intel/compilers_and_libraries_2016.0.109/linux/
```
 
It seems that soft links here might not work properly.

**Comment by tqchen** [comment]
Can you try to add the lessons learnt to https://github.com/dmlc/mxnet/blob/master/doc/build.md ? A PR is more than welcomed so people can benefit this!

**Comment by yzgysjr** [comment]
It is a great pleasure for me and I will do this later this day :)

**Comment by tqchen** [comment]
PR by https://github.com/dmlc/mxnet/pull/950
