### ISSUE TITLE
Training accuracy issue

### ISSUE THREAD

**Issue by HaoTang1** [dmlc/mxnet#938]
New to MxNet. I've set up and tested the package on three different systems, an CPU-only Linux VM, an CPU-only Windows Server and a GPU-based windows PC.

The sample I'm using is  **example/notebooks/cifar10-recipe.ipynb**

When comparing the performance across all three systems, I noticed that during the initial training ([12] in **cifar10-recipe.ipynb**), the train-accuracy and validation-accuracy I got is around 0.4~0.5, which is pretty far from the 65% accuracy as the documentation stated. 
Here's an example output during my test on an GPU-based machine.

```
INFO:root:Start training with [gpu(0)]
INFO:root:Iter[0] Batch [50]	Speed: 561.85 samples/sec
INFO:root:Iter[0] Batch [100]	Speed: 540.63 samples/sec
INFO:root:Iter[0] Batch [150]	Speed: 543.20 samples/sec
INFO:root:Iter[0] Batch [200]	Speed: 543.80 samples/sec
INFO:root:Iter[0] Batch [250]	Speed: 543.89 samples/sec
INFO:root:Iter[0] Batch [300]	Speed: 542.24 samples/sec
INFO:root:Iter[0] Batch [350]	Speed: 543.71 samples/sec
INFO:root:Epoch[0] Train-accuracy=0.424153
INFO:root:Epoch[0] Time cost=92.967
INFO:root:Epoch[0] Validation-accuracy=0.475771
```

What is causing this difference between my test and the one in the document when it's using the same code to test the same data set? 

And also the documentation says "our model is able to achieve about 65% accuracy on testset(If not, try more times)", what does this "try more times" mean? 

Thanks

**Comment by wangg12** [comment]
@HaoTang1 "try more times" was added by me. It means to try to train more times from scratch. I tested that example and got accuracy around 60%, then I  tried about 3 more times to get that accuracy.

**Comment by HaoTang1** [comment]
@wangg12  Thanks. Got the accuracy raised to 0.72 after training 3 more times as well. 

But what's the reason my accuracy is lower than the documentation shows after the first epoch?

**Comment by wangg12** [comment]
@HaoTang1 Not sure. But I think it doesn't matter since 1 epoch is far from convergence.

**Comment by mli** [comment]
it may due to random() gives different values across different platforms, which could affect the first 1 or 2 epochs a lot
