### ISSUE TITLE
nvrtc is not supported in cuda 5.5 .

### ISSUE THREAD

**Issue by ZhimingWang** [dmlc/mxnet#941]
Hi , @piiswrong ：
nvrtc is not supported in cuda 5.5  .  Out of the consideration of compatibility , one better method is to use MACRO for distinguishing whether to use nvrtc , just as the case of cudnn. Thanks.

**Comment by yuzcccc** [comment]
+1, this change makes cuda-6.5 inapplicable

**Comment by piiswrong** [comment]
You are right. I'll add a flag when I have time. But I a little busy these days. It will be great if somebody can step in. Should be a simple change

**Comment by piiswrong** [comment]
fixed in https://github.com/dmlc/mxnet/pull/1048

**Comment by ZhimingWang** [comment]
@piiswrong , Thanks !
