### ISSUE TITLE
Segmentation fault when loading a saved numpy-op model

### ISSUE THREAD

**Issue by huazehuang** [dmlc/mxnet#948]
Hi mxnet team,

I'm using the example [numpy_softmax.py](https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/numpy_softmax.py. I tried to save the model by adding ```epoch_end_callback=mx.callback.do_checkpoint(model_prefix)```. The model is successfully fitted and saved. But when I load the saved model, mxnet gives a segmentation fault.

Any idea on this issue?

Thanks
Zehua

**Comment by tqchen** [comment]
This was a expected behavior, as it is hard to store the numpy object during serialization. Also cc @piiswrong  we might need a friendly message here.

What you can do is reconstruct the symbol in python code, and load the ndarrays and set them manually

**Comment by piiswrong** [comment]
I've thought about adding message. But the thing is it's hard to detect whether it's created by loading from json within the operator
