### ISSUE TITLE
Runtime Input Resizing

### ISSUE THREAD

**Issue by starimpact** [dmlc/mxnet#952]
hi, guys,
Now, I must resize the image or add black margin to make the input size of images be identity. I know it will be suitable for batch calculation.
I know a stupid way to pass the any size of image by recreating the net model every time for every new size of image.
But, what should I do to pass any size of image into mxnet efficiently?
Do you understand what I said? Any good idea?

**Comment by starimpact** [comment]
@tqchen @piiswrong

**Comment by tqchen** [comment]
The symbolic computation currently do not support runtime input resizing. This can be added by two ways
- Support runtime reshaping of the graph nodes.
- Support tvia a purely imperative API

**Comment by starimpact** [comment]
Is it a easy work or hard work compared with write a operator ?

**Comment by starimpact** [comment]
how to do it exactly, is there any basic manual ?
@tqchen @piiswrong

**Comment by tqchen** [comment]
This require change to the graph executor by adding something like rebind the input shape. This is possible, but require a bit engineering effort, including check the allocated memory and run re-allocation if the size is too small

**Comment by piiswrong** [comment]
@starimpact https://github.com/dmlc/mxnet/pull/1408 added this feature. You are welcome to test it.

**Comment by starimpact** [comment]
does it affect the performance ?

**Comment by starimpact** [comment]
@piiswrong How to use it? Is there any example?

**Comment by starimpact** [comment]
@piiswrong

**Comment by starimpact** [comment]
@piiswrong @tqchen Has this problem been solved or not ?
