### ISSUE TITLE
ld: library not found for -lgomp during RE-INSTALLATION

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/mxnet#953]
I was able to install mxnet successfully. However, after I removed everything related to mxnet and tried to re-install,  I encountered `ld: library not found for -lgomp`, which was successfully resolved by the instruction in build doc. 

```
Yuan-Tangs-MacBook-Pro:mxnet yuantang$ locate libgomp.dylib
/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/i386/libgomp.dylib
/usr/local/Cellar/gcc/5.2.0/lib/gcc/5/libgomp.dylib
/usr/local/lib/libgomp.dylib

File exists for any path above. 

ln -s path1 /usr/local/lib/libgomp.dylib
ln: /usr/local/lib/libgomp.dylib: File exists
```

Is there anything I missed? Note that this worked before.

**Comment by piiswrong** [comment]
I think I have seen this issue multiple times. I remember the solution was to copy make/osx.mk to mxnet root.

**Comment by terrytangyuan** [comment]
@piiswrong Thanks but I think it's a different issue. I've copied it already. It worked before (`-lgomp` can be found and `make -j4` worked) but when I tried to re-install it, it failed. Not sure if anyone else had this issue before.

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/issues?utf8=%E2%9C%93&q=lgomp

**Comment by terrytangyuan** [comment]
I tried that one but didn't work. 
```
brew install clang-omp
make CXX=clang-omp++

Yuan-Tangs-MacBook-Pro:mxnet yuantang$ brew install clang-omp
==> Downloading https://homebrew.bintray.com/bottles/clang-omp-2015-04-01.yosemi
Already downloaded: /Library/Caches/Homebrew/clang-omp-2015-04-01.yosemite.bottle.2.tar.gz
==> Pouring clang-omp-2015-04-01.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/clang-omp/2015-04-01: 1396 files, 378M

ln -s /usr/local/opt/gcc/lib/gcc/5/libgomp.dylib /usr/local/lib/libgomp.dylib
ln: /usr/local/lib/libgomp.dylib: File exists

make CXX=clang-omp++
(...ignored)
Yuan-Tangs-MacBook-Pro:mxnet yuantang$ make -j4
make: Nothing to be done for `all'.
```

Thanks. Note again that I have successfully built it before.

**Comment by terrytangyuan** [comment]
@piiswrong Thanks for your help. I just find this solution:

I'll have to use `ln -sf path1 /usr/local/lib/libgomp.dylib`, this `-f` option is used to force removing existing destination files (from previous install).  The previous installed libgomp does not work. 
You may update the build doc if you want.  :-)
