### ISSUE TITLE
how to display the train loss?

### ISSUE THREAD

**Issue by achao2013** [dmlc/mxnet#954]
when i train a model ,i can't see the train loss every 100 batches  when i add batch_end_callback=mx.callback.log_train_metric(100), this will only display the accuracy.  How can i see the train loss ?

**Comment by tqchen** [comment]
What we can do is to add a loss function evaluation metric(say logloss) and log that metric instead, as far as I recall, it is also possible to pass in multiple metrics

**Comment by achao2013** [comment]
got it

**Comment by kli-nlpr** [comment]
Is there some examples? Thanks
