### ISSUE TITLE
[dist-train] log miss when dist-train

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#956]
I train model on cluster of 8 machines. 
use ssh protocol, there is a problem that the content of log miss a lot.

any one else has met this issue?

**Comment by tqchen** [comment]
Could due to not frequent flush and force kill instead of normal exit of the program

**Comment by tqchen** [comment]
so the content that has not yet been flushed will not occur on the log

**Comment by mli** [comment]
it's possible, the log is transferred back via ssh in default, it may be delayed if the network is quite busy. you probably can reconfigure `logging` in python to write the log into disk
