### ISSUE TITLE
How to save lstm model?

### ISSUE THREAD

**Issue by rorschachhb** [dmlc/mxnet#957]
Hey guys. I was able to train lstm model on my own data, but don't know how to save it. I tried using pickle and got an error: `ValueError: ctypes objects containing pointers cannot be pickled`. I also tried using `model.save` and failed because apparently the model trained in the rnn example is not a `mx.model` object.

Forgive me if this question sounds stupid. Anyone knows the right way of doing this? Thanks.

**Comment by piiswrong** [comment]
You can return arg_dict and run mx.ndarray.save(fname, arg_dict) to save it and mx.ndarray.load(fname) to load it.

**Comment by rorschachhb** [comment]
I end up using `args = dict([(name, arr) for i, arr, grad_arr, name in model.param_blocks])` and `pickle.dump`. 
@piiswrong thanks anyway.
