### ISSUE TITLE
Compilation Errors on Windows 7-64bit

### ISSUE THREAD

**Issue by DaleSong89** [dmlc/mxnet#962]
hi all, when I was compiling mxnet using vs2013 solution generated by CMake Gui, there were always compilation errors such as:

    "mxnet\include\mxnet/ndarray.h(594): error : has_saveload is not a template"
    "D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\utility(201): error : incomplete type is not allowed detected during instantiation of class "std::pair<_Ty1, _Ty2> [with _Ty1=const int, _Ty2=mxnet::NDArray]" " 
    "mxnet\src\optimizer\./sgd-inl.h(114): error : incomplete type is not allowed"
    "mxnet\src\optimizer\./sgd-inl.h(114): error : pointer to incomplete class type is not allowed"
I used "Microsoft Visual C++ Compiler Nov 2013 CTP" files overwrite the ones exist in the vs2013 installation path. Version of the third-party libraires are Opencv3.0.0, Cuda 7.5 and cudnn is not used. Can anyone help me point out the problem? Thanks a lot!

**Comment by hjk41** [comment]
Just tried commit 6977ac7a44414c58e09211f221076e583c252be3, it worked fine.
Which commit are you trying it on?



On Thu, Dec 17, 2015 at 3:36 PM, Dale <notifications@github.com> wrote:

> hi all, when I was compiling mxnet using vs2013 solution generated by
> CMake Gui, there were always compilation errors such as:
>
> "mxnet\include\mxnet/ndarrayh(594): error : has_saveload is not a template"
> "D:\Program Files (x86)\Microsoft Visual Studio 120\VC\INCLUDE\utility(201): error : incomplete type is not allowed detected during instantiation of class "std::pair<_Ty1, _Ty2> [with _Ty1=const int, _Ty2=mxnet::NDArray]" "
> "mxnet\src\optimizer\/sgd-inlh(114): error : incomplete type is not allowed"
> "mxnet\src\optimizer\/sgd-inlh(114): error : pointer to incomplete class type is not allowed"
>
> I used "Microsoft Visual C++ Compiler Nov 2013 CTP" files overwrite the
> ones exist in the vs2013 installation path Version of the third-party
> libraires are Opencv300, Cuda 75 and cudnn is not used Can anyone help me
> point out the problem? Thanks a lot!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/962>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by yajiedesign** [comment]
fix with https://github.com/dmlc/mxnet/pull/935,do you pull new master?

**Comment by DaleSong89** [comment]
Thanks a lot!   
 I was trying on this version https://github.com/dmlc/mxnet/tree/4ba4f50254dd747af0bde2bb5b1d3847e576a368

**Comment by DaleSong89** [comment]
@hjk41 @yajiedesign 

Now I'm trying on   6977ac7    and    ea453a5    , both with no compilation errors but with the link error:
   
     LINK : fatal error LNK1104: cannot open file 'nvrtc.lib'


My     CUDA_TOOLKIT_ROOT_DIR     was set as: 
    
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v7.5

Is there something wrong I made? Thanks for your help!

**Comment by hjk41** [comment]
The nvrtc problem should be fixed by #971 , please wait for it to be merged.

**Comment by DaleSong89** [comment]
thanks very much！@hjk41

**Comment by juguangliang** [comment]
@DaleSong89 how do you install “Microsoft Visual C++ Compiler Nov 2013 CTP” ? I got the problem 0X80070666, thanks

**Comment by yajiedesign** [comment]
@juguangliang not  install  this, use vs2013 up5
