### ISSUE TITLE
Can I have a weight map when using multi-output in SoftmaxOutput layer

### ISSUE THREAD

**Issue by imafox** [dmlc/mxnet#965]
The question is like this, with one input image, I want to generate a soft-max map that have a soft-max output at every pixel . In other word, it outputs M*N normal softmax layer.
I know this can be implemented by multi_output in SoftmaxOutput layer in mxnet. But I don't want every M*N softmax have a gradient backward, So I need to set the weight of some gradient to zero. But it seems that I need to change the code of SoftMaxGrad in msshadow, can I have a easier way to do this?

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/pull/915 this pr has what you want. You can wait for it to get merged or pick out the relevant code yourself
