### ISSUE TITLE
Does the current BatchNorm Layer also work for fullyconnected layers

### ISSUE THREAD

**Issue by jimxinbo** [dmlc/mxnet#970]
A quick question. I am being lazy and did not check this out in the code. 

Seems when using BatchNorm on Fullyconnected layers, the learning can stuck at real bad accuracy from the very beginning and did not change at all. Is it because I am using it wrong or simply the current BatchNorm layer is only designed for conv layers? 

From the BN paper, though, it should be applicable to both conv and fc but the implementation can be a little different.

**Comment by piiswrong** [comment]
@antinucleon

**Comment by jimxinbo** [comment]
@antinucleon nevermind, I went through code, it supports both fully-connected and conv layers, good job. Please see if you will fix issue#1053.
