### ISSUE TITLE
Train CNN on big data set

### ISSUE THREAD

**Issue by Yunrui** [dmlc/mxnet#972]
Hello folks,

I am learning from the Handwritten example (http://mxnet.readthedocs.org/en/latest/R-package/mnistCompetition.html) to train a CNN model on my own dataset, which has bigger size (50 pixels * 70 pixels, and 500000 samples). My R throws "cannot allocate vector of size 12GB" exception when I do the following transpose as mentioned in the article: "train.x <- t(train.x/255)". 

My training set is bigger than the example, and my machine only have 16GB memory. But I really want to ask what's the right approach to handle big training set (actually my whole training set is 100x than 500,000 instances). Does it possible for mxnet (probably R in this case) to automatically handle big matrix which might not be able to hold completely in memory (partially load for example)? and what's distributed solution for training model and examples? 

Thanks in advance!

**Comment by piiswrong** [comment]
Please take a look at tools in MXNET_ROOT/tools/.
You can use ImageRecordIter (like training on imagenet) and to the transformations on the fly with symbolic API

**Comment by Yunrui** [comment]
Thanks, it looks like what I want, trying to fit to my data set.
