### ISSUE TITLE
forums/newsgroup/mailing-list for newbie questions?

### ISSUE THREAD

**Issue by hughperkins** [dmlc/mxnet#976]
Do you have something like a forums/newsgroup/mailing-list for newbie questions?  I checked on http://mxnet.readthedocs.org/en/latest/ , but couldnt seem to find?

Edit: and also checked https://github.com/dmlc/mxnet and http://mxnet.readthedocs.org/en/latest/faq.html  我会说中文。所以中文的也行 。。。

**Comment by vchuravy** [comment]
Setting up a https://disqus.com/ platform might be a good option to cut down the noise on the github issues.

**Comment by rened** [comment]
@vchuravy May I suggest a mailing list / google groups? Allows to stick to an email-based workflow.

**Comment by vchuravy** [comment]
disqus also works with e-mails, but I would be fine with google groups.

**Comment by hughperkins** [comment]
google groups kind of sucks from China.  I'm kind of pondering whether anyone has ever tried using a reddit subreddit for such a role?  (I've never tried it myself, or seen anyone try it, but the reddit interface is at least relatively lightweight, loads in less than 3 minutes!).  disqus works ok-ish.

**Comment by pineking** [comment]
google groups is the best choice, although I am in China.  I can access gmail or google group, that is the basic skill in china.

**Comment by vchuravy** [comment]
Ah I did a mistake I originally proposed discus, but what I actually meant is discourse. https://www.discourse.org/ It can be self-hosted (from within china as an example) or but behind an edge-cache (cloudflare has support for china) as an example see the rust user forum https://users.rust-lang.org/

**Comment by qigtang** [comment]
Or weechat, that will be real time.

**Comment by hughperkins** [comment]
威信行。反正它只有一个'e' :P 反正我终于暂时放弃了mx。但是可能很大的理由是因为找不到了容易回答我的问题的方法。

所以你们打算创造一个威信的团队？ 还是。。。 ？
