### ISSUE TITLE
distributed training using openmpi?

### ISSUE THREAD

**Issue by nicklhy** [dmlc/mxnet#977]
Following the tutorial http://mxnet.readthedocs.org/en/latest/aws.html, I successfully launched a distributed training process on my GPU cluster (3 computing servers with several K80 gpus).

However, I noticed that the only launchers in tools/launch.py are "SSHLauncher" and "LocalLauncher" . There does not exists a "MPILauncher" in dmlc_mpi.py. So, how can I use dmlc_mpi.py or mpirun to launch a mpi version distributed training program on my GPU cluster?

**Comment by tqchen** [comment]
MXNet is based on dmlc's tracking framework, so we should be able to do all launchers, including mpi and yarn. This being said, the launcher.py support might not be up to date to keep all these.

cc @mli  on this

**Comment by tqchen** [comment]
It is highly likely you could use dmlc_mpi.py in tracker folder, as the launcher is a think wrapper of the tracker scripts.

**Comment by mli** [comment]
We just use mpirun to run jobs while does not use any other mpi functions. We found ssh is often more stable than mpirun. Do you have any particular reason to use mpi?

**Comment by tqchen** [comment]
Well, when you are runing in a shared mpi cluster, using native scheduler helps you to allocate resources correctly. @mli  we should support this

**Comment by nicklhy** [comment]
@tqchen , thanks for your replies. I am still trying to launch it with dmlc_mpi.py. Some error info is printed after executing "python  /path-to-mxnet/tracker/dmlc_mpi.py -n 3 -s 3 -H hosts python train_cifar10.py --kv-store dist_sync --model-prefix weights/cifar":

zsh:1: command not found: orted
ORTE was unable to reliably start one or more daemons.
... ...

openmpi is installed in /opt manually and /opt/openmpi/bin is added to PATH in all servers(orted can be executed in all servers). I think this should be some env variable related errors since the default $PATH of a non-interactive+non-login shell(created like "ssh user@remote command") is "/usr/bin:/usr/local/bin".

I have similar errors using ssh but solved it by adding PATH in ['LD_LIBRARY_PATH', 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY'], get_env function, dmlc_ssh.py.
I think I should pass PATH, LD_LIBRARY_PATH together to the sub-processes before distributing them to different nodes.

**Comment by nicklhy** [comment]
@mli , I have to use a queueing system (torque + maui) to schedule gpu processes from different users in this cluster. One of my friend has launched a mpi version caffe training process like "qsub pbs.job"(to submit the training process). I am not sure if the ssh version mxnet could also work well with this queueing system.

**Comment by mli** [comment]
we had a script to launch job by qsub, see 

https://github.com/dmlc/dmlc-core/blob/master/tracker/dmlc_sge.py

the problem is that i slightly changed the `tracker.py`, so i made a separate implementation at ps-lite/tracker while didn't port dmlc_sge.py there yet. i planned to do it next week, and it will be great if you have a test if it is done. but if you need to use it immediately, please consider port dmlc_sge.py into ps-lite/tracker, the change should be minimal.
