### ISSUE TITLE
[VOTE] Folder name for optional Addon

### ISSUE THREAD

**Issue by tqchen** [dmlc/mxnet#978]
There will be several interesting addons, that requires additional dependency, and are optionally installed, this thread is used to vote for the name of addon folder, as well as suggestions on how to dynamically load these addons.
Example ongoing addons include Torch operator and Caffe adapter.

Please vote for the name you like
- 1. ```mxnet/opt```
- 2. ```mxnet/addon```
- 3. ```mxnet/plugin```

**Comment by mavenlin** [comment]
+1 for opt

**Comment by javelinjs** [comment]
+1 for plugin

**Comment by pluskid** [comment]
+1 for plugin

**Comment by dselivanov** [comment]
+1 for plugin

**Comment by piiswrong** [comment]
extension?

**Comment by tqchen** [comment]
also @mli @hotpxl @jermainewang

**Comment by tqchen** [comment]
let us go for plugin then
