### ISSUE TITLE
MXPredGetOutput in cpp example

### ISSUE THREAD

**Issue by kcINual** [dmlc/mxnet#979]
The newly added C++ example in `mxnet/example/cpp/image-classification/` is awesome! Contribute to liuxiao!

Tried to run that example with the pretrained `Inception-Full` model, found that it took about a second to run "MXPredGetOutput" in order to retrieve the prediction result. 

Any idea how to speed it up, or to work around it and get the best guess from the prediction?

**Comment by piiswrong** [comment]
I'm not sure what you mean. Are you saying one batch takes 1s? What's your GPU card? It sounds normal

**Comment by kcINual** [comment]
Just a single image for classification.

I'm testing it without GPU as I'll be running the classification task on SBC like Raspberry Pi or low-end NUC. The 1-sec result of running `MXPredGetOutput` was on an i5 quad-core CPU @ 3.00GHz with ubuntu.

Both mxnet and the cpp example are compiled with O3 optimization.

All other processes like `MXPredForward` `MXPredGetOutputShape` only took a blink on a CPU. Wondering if there's any way to speed up [MXPredGetOutput](http://mxnet.readthedocs.org/en/latest/doxygen/c__predict__api_8h.html#aeaadef67a6a9a2308f2d8160f91724af), or to just work around it and get the best guess result - and eventually, to find a way to classify image at video rate without GPU.

Any idea would help :+1:

**Comment by tqchen** [comment]
Because things are async. So GetOutput is actually waiting for the forward computation to finish.

**Comment by qt6636** [comment]
I got the same problem. when i test the same picture on mxnet of Python with gpu, it used 10 msec, but when on C, it almost used 10000 msec. So Any idea would help?

**Comment by idealboy** [comment]
I have the same problem, when I use multi thread to do inference MXPredGetOutput function, it is aboud 3X slower than single thread

**Comment by idealboy** [comment]
> Because things are async. So GetOutput is actually waiting for the forward computation to finish.

I have the same problem, when I use multi thread to do inference MXPredGetOutput function, it is aboud 3X slower than single thread

**Comment by idealboy** [comment]
> I'm not sure what you mean. Are you saying one batch takes 1s? What's your GPU card? It sounds normal

I have the same problem, when I use multi thread to do inference MXPredGetOutput function, it is aboud 3X slower than single thread

Thank you!

**Comment by idealboy** [comment]
> > Because things are async. So GetOutput is actually waiting for the forward computation to finish.
> 
> I have the same problem, when I use multi thread to do inference MXPredGetOutput function, it is aboud 3X slower than single thread

Does nd.SyncCopyToCPU(data, size) in MXPredGetOutput is blocked when in multi thread case?
