### ISSUE TITLE
Merge CNN and LSTM training

### ISSUE THREAD

**Issue by JamesKnowton** [dmlc/mxnet#981]
Hi, all. I am currently working on make CNN and LSTM joint-training. I don't know how can mxnet pass the error feedback from the top layer of LSTM to to the last layer of CNN? Can anyone give me some examples? Thanks.

**Comment by piiswrong** [comment]
cnn.forward()
copy_cnn_output_to_lstm_intput()
lstm.forward()
lstm.backward()
cnn.backward(lstm.input_grad)

This is basically what you need. You need to modify the call to bind in lstm to make it bind gradient for input

**Comment by sinmaystar** [comment]
@JamesKnowton 
I have met a same question, I want to use CNN and LSTM joint-training, CNN extract image features as LSTM's  input, do u success to do that?
