### ISSUE TITLE
[Question] Any clues to sum up the image along the channel dimension?

### ISSUE THREAD

**Issue by XericZephyr** [dmlc/mxnet#985]
For example, I have an image of size `256*256*3`. Can I sum up the RGB channel and get a `256*256` image with current symbols? Thanks.

**Comment by piiswrong** [comment]
I created an op that does this (actually more than this it does sum(input_1*input_2, axis=n)). It didn't seem to generic so I didn't commit it in the main repo. I would be greate if you can remove the prod part and make a SumWithAxis op
https://gist.github.com/piiswrong/e39f7383cae9d4134f5b

**Comment by tornadomeet** [comment]
you can use convolution for that, the num_hidden=1,kernel=(1,1),fix weight=1

**Comment by XericZephyr** [comment]
Thanks. @tornadomeet  Do you have any idea on how to fix weight (without back-propagation update)?

**Comment by antinucleon** [comment]
@XericZephyr Set gradient req to null, eg:
```
req = {"fc_weight" : "null", "conv_weight" : "write"}
```

**Comment by piiswrong** [comment]
This only works if you are trying to sum a 4d tensor along the second dimension though

**Comment by zhangchen-qinyinghua** [comment]
I think using convolution to do the sum is a smart idea, also a bit of a hack.
Operator to do sum (and other operate) in axis seems should be quite usefull.
