### ISSUE TITLE
mxnet is slow and use too much CPU when training ResNet

### ISSUE THREAD

**Issue by shiyemin** [dmlc/mxnet#990]
I'm training ResNet (ImageNet2015, MSRA) on a server with 8*K80. However when using all 16 GPUs (one K80 as two GPUs), all 48 CPUs are utilized. Meanwhile, the mxnet's speed is only 4.5 samples/sec, which is much too slow. Is there any possible reason?

**Comment by antinucleon** [comment]
There can be many reason.
1. How is your network? If network is a bottle neck, it will be slow.
2. What is your batch size? If your batch size is too small, it will be slow.
3. How is your PCI-Bandit? Default kvstore is on CPU, which will copy GPU to CPU then update. If your PCI-Bandit is limited, you can try sync on device.

**Comment by mli** [comment]
your performance number is abnormal. please have look at the [performance note](https://github.com/dmlc/mxnet/tree/master/example/image-classification#note-on-performance) to see whether or not it solves your problem

**Comment by shiyemin** [comment]
After change batch size from 16 to 128, the speed increase to 36 samples/sec and 85 samples/sec with using kv_store=local_allreduce_device. Is this normal?

**Comment by piiswrong** [comment]
with 16 gpus you probably need an even bigger batch size

**Comment by mli** [comment]
please try to use the largest batch size which can fit into gpu memory (look it by `nvidia-smi`)

**Comment by shiyemin** [comment]
Thanks a lot. I achieve 142 samples/sec by using a batch size of 512.
