### ISSUE TITLE
example/adversay/adversay_generation.ipynb does not work

### ISSUE THREAD

**Issue by adonishong** [dmlc/mxnet#991]
1. environment is python 2.7
2. got issue of no module "data", so I copy data.py from numpy-ops
3. with the line "for data, label in train_iter:", got this error "ValueError: too many values to unpack", so I make it "for data, label, pad, index in train_iter:"
4. with the line "arg_map["data"][:] = data", got this error "TypeError: type <type 'list'> not supported". with this error, I have no idea what to do now...

**Comment by antinucleon** [comment]
There is a change of iterator interface, but I didn't have time to fix the example yet. I will try to fix it in tomorrow.

**Comment by adonishong** [comment]
@antinucleon Appreciate for you guys fantastic work ^_^
