### ISSUE TITLE
Building failed with gcc 4.9.2 in Ubuntu 15.04

### ISSUE THREAD

**Issue by yzgysjr** [dmlc/mxnet#997]
Hi,

I have some problems building with gcc 4.9.2. Here is the output

```
In file included from src/symbol/./graph_executor.h:16:0,
                 from src/symbol/graph_executor.cc:11:
src/symbol/././static_graph.h:186:84: error: converting to ‘const std::unordered_set<unsigned int>’ from initializer list would use explicit constructor ‘std::unordered_set<_Value, _Hash, _Pred, _Alloc>::unordered_set(std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Value = unsigned int; _Hash = std::hash<unsigned int>; _Pred = std::equal_to<unsigned int>; _Alloc = std::allocator<unsigned int>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::hasher = std::hash<unsigned int>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<unsigned int>; std::unordered_set<_Value, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<unsigned int>]’
                                      const std::unordered_set<uint32_t>& banned = {}) const;

```

It seems that there are some grammar problems. However, the problem is solved when I set 
```
export CC = gcc-4.8
export CXX = g++-4.8
```

I wonder what causes the problem compiling with gcc 4.9.2. Thank you !

**Comment by shiyemin** [comment]
I have the same error on CentOS 6.5(Rocks OS) with GCC 4.9. But it works before i run "git pull". Maybe there are some error in recent commits. @mli

**Comment by shiyemin** [comment]
http://stackoverflow.com/questions/26947704/implicit-conversion-failure-from-initializer-list

By replacing {} with "std::unordered_set<uint32_t>()" in graph_executor.cc and static_graph.h, I successfully compiled mxnet.

**Comment by mli** [comment]
could you please make a PR? http://mxnet.readthedocs.org/en/latest/contribute.html

**Comment by shiyemin** [comment]
Here is my modifications: https://github.com/shiyemin/mxnet/commit/16bc2a241c33f60363eeeec2f23c997a8e9bd391

I will soon submit a pull request for this PR.
